### ISSUE TITLE
Import repository list missing an organisation (and now empty)

### ISSUE THREAD

**Issue by bilderbuchi** [readthedocs/readthedocs.org#10009]
## Details

* Read the Docs project URL: n/a
* Build URL (if applicable): n/a
* Read the Docs username (if applicable): bilderbuchi

## Expected Result

Just like in #7381, I want to import a [repository I made belonging to an organisation](https://github.com/pymeasure/leco-protocol) I am a member of.
I recently made an RTD account. At some point in the login flow, the pymeasure organisation did not yet have the permission checkmark. I got the permission granted a couple of hours later (I'm not an owner), and cross-checked that on the Github settings page.

On the import page, I expected to import that organisation's repository. 

## Actual Result
However, neither the pymeasure organisation was in the filter list on the right, nor the repo contained in the repository list. Personal repos and repos of other organisations I'm part of are visible.
Trying the refresh button multiple times, logging out/in, closing the browser did not help. It seems the refresh spinner was always visible for a long time (minutes). 
By now, the repository list remains completely empty, and the spinner does not stop spinning:
![image](https://user-images.githubusercontent.com/327442/217738470-ec586cb9-bbf0-433e-a25b-815523fa420c.png)

I checked that the RTD oauth app has permissions for the pymeasure orga.
I am part of 4 organisations. 
Funny enough, I left the ralph-group organisation (that I did not need anymore) to keep the list small (in #7381 there was a remark that GH API only imports 4 orgas), but that change is not reflected in the import page -- I suspect it's not refreshing at all.
I let a day or so pass before retrying (on the possibility that a server was borked or whatever).

**Comment by humitos** [comment]
Not 100% sure, but I guess you are hitting this issue https://github.com/readthedocs/readthedocs.org/issues/8979

**Comment by bilderbuchi** [comment]
Huh, that indeed sounds like it could be related. However, if so I am surprised that this has not been reported before -- if membership in conda-forge has such a consequence, anybody that maintains a conda package feedstock could not use the import page? Sounds to me like I shouldn't be the first one 😁

**Comment by bilderbuchi** [comment]
Another tack: I'm not clear about the difference between the "easy" (but broken) import and the "Import manually" button -- are they fully equivalent? I'm pretty sure I could fill out all the details in the manual import form, but does using that mean I'm missing some integrations or setup or something?

**Comment by humitos** [comment]
@bilderbuchi mainly, the difference is that Read the Docs will setup the webhooks to GH automatically for you. You can do that manually as well after importing the project using "Import manually".

**Comment by bilderbuchi** [comment]
Thanks!

**Comment by humitos** [comment]
This issue should be solved in the new templates. We have deployed them as beta at https://beta.readthedocs.org/. Please, login there and look for the organization/repository under the import page, and report back if you still don't find it there.

On the other hand, importing a project manually is now clearly explained at the import step, which was the documentation part missing from this issue:

![Screenshot_2023-06-05_12-25-28](https://github.com/readthedocs/readthedocs.org/assets/244656/6a979d87-0143-4ac1-b82c-69292f6167fa)

**Comment by bilderbuchi** [comment]
Thanks for fixing this, I see the org repos now! (Took me a while to figure out that I had to type a name into that search field to make the list of hits appear, I thought it had not found anything)

**Comment by domdfcoding** [comment]
I've started seeing the same issue as the OP, but in the beta website I can see all my orgs and repos. (although I can't actually add the project. Clicking "Next" takes me in circles.)

**Comment by humitos** [comment]
> in the beta website I can see all my orgs and repos. (although I can't actually add the project. Clicking "Next" takes me in circles.)

Would you mind recording a small video showing this together with the JS console of your browser? 🙏🏼

**Comment by Freed-Wu** [comment]
This problem seems to occur again. I cannot search my organizaiton's repo in configure automatically.

**Comment by stsewd** [comment]
@Freed-Wu make sure RTD has access to your organization, see https://docs.readthedocs.com/platform/stable/reference/git-integration.html#github-permission-troubleshooting
