### ISSUE TITLE
Documentation build freezes during pip install docs/requirements.txt and cancel build button is unresponsive.

### ISSUE THREAD

**Issue by drewoldag** [readthedocs/readthedocs.org#10011]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/python-template-test/
* Build URL (if applicable): https://readthedocs.org/projects/python-template-test/builds/19437865/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/drewoldag/

I am attempting to build the docs for a new project, when changes are made to the main branch, RTD identifies that and starts a build. However, the build gets stuck at this step:
python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt

The output looks as though all the requirements were installed, but the build hangs (potentially for hours) until it finally times out. The "Cancel build" button is not responsive.

## Expected Result

Would expect the Cancel build button to stop the build, and produce some additional output. 
Would expect that the next step after pip install docs/requirements.txt would begin. 

## Actual Result

The build hangs, and Cancel build button become unresponsive.

**Comment by drewoldag** [comment]
All previous builds have shown this problem as well: https://readthedocs.org/projects/python-template-test/builds/

**Comment by stsewd** [comment]
Hi there, looks like the project was re-created? I can't see those builds anymore. Also, the step that is "hanging" is probably the next step after the installation of requirements, we show the command only after it has been run.

**Comment by drewoldag** [comment]
Thanks for the feedback @stsewd. You're correct, the step that was hanging was the next step in the process (the actual sphinx build) And the ultimate issue was that I was not providing the correct path to the conf.py file. Instead I was providing just the directory that contained it, and I'm assuming that the build process was trying to `cat <directory>`. Still surprised that there wasn't a faster timeout, or some error reporting.

Either way, thank you for your help!
