### ISSUE TITLE
Build error with build id #19460807

### ISSUE THREAD

**Issue by Leirof** [readthedocs/readthedocs.org#10016]
## Details:

* Project URL: https://readthedocs.org/projects/Gipsy/
* Build URL(if applicable): https://readthedocs.org/projects/gipsy/builds/19460807/
* Read the Docs username(if applicable): LeiRoF

## Expected Result

Compile the website correctly such as the provious compiltations. It work correctly without error neither warning when I compile it in local.

## Actual Result

An error while compilting, at the step `git clean -d -f -f` but without more details.

**Comment by Leirof** [comment]
As I was unable also to change the domain or version and as there is no problem on other projects neither on this project in local, I deleted the project and recreated it on RTD, but I still have the same issue.

The new build that failed: https://readthedocs.org/projects/gipsy/builds/19464938/
(previous link is break because of the project deletion)

**Comment by humitos** [comment]
It seems you are hitting this issue: https://github.com/readthedocs/readthedocs.org/issues/4371. Can you please double-check your git submodules?

**Comment by Leirof** [comment]
You were right, thanks!
