### ISSUE TITLE
ethicalads snippet included even when project has disabled ads

### ISSUE THREAD

**Issue by rmdash** [readthedocs/readthedocs.org#10051]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/dash-docs-core/
* Build URL (if applicable): https://docs.dash.org/projects/core/en/stable/docs/index.html
* Read the Docs username (if applicable): dashcoreteam

## Expected Result

As a gold member, we have disabled advertisement on Dash docs and we would expect no ads code to load.

## Actual Result

We are seeing ethicalads on our docs:

https://imgur.com/a/GlLphOc

Kindly let us know how to proceed.

**Comment by stsewd** [comment]
Hi, looks like you need to re-build your project for the change to take effect, but this is also something we could get from our API, so users don't need to rebuild their docs.

**Comment by rmdash** [comment]
Resolved. These are the steps to follow to make docs ad-free:

Go to user setttings -> Gold Membership
Under "Gold Project", click "Select Project"
Under "Make a project ad-free", select the project and click "Make Project Ad-Free"
