### ISSUE TITLE
"Edit on Gitlab" not showing

### ISSUE THREAD

**Issue by Hyrla** [readthedocs/readthedocs.org#10057]
## Details

* Read the Docs project URL: https://esieabot.readthedocs.io/fr/latest/
* Build URL (if applicable): https://readthedocs.org/projects/esieabot-fr/builds/19553833/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/Hyrla
* Read the Docs repo : https://gitlab.esiea.fr/esieabot/esieabot-docs/rtd-francais

## Expected Result

I'm trying to replace the default link "View page source" by "Edit on Gitlab". I have added this html context to my conf.py and recompiled.

```
html_context = {
    "display_gitlab": True, # Integrate Gitlab
    "gitlab_host": "gitlab.esiea.fr", # Gitlab URL
    "gitlab_user": "esieabot", # Username
    "gitlab_repo": "esieabot-docs/rtd-francais", # Repo name
    "gitlab_version": "main", # Version
    "conf_py_path": "/source/", # Path in the checkout to the docs root
}
```

## Actual Result

The link remains "View page source" and not "Edit on Gitlab". Am I doing something wrong ?

**Comment by Hyrla** [comment]
Problem found. Readthedocs is overwriting html_context (why??). Here is the conf.py as generated by Read the Docs:

```
[...]

# My context as defined in my conf.py
html_context = {
    "display_gitlab": True, # Integrate Gitlab
    "gitlab_host": "gitlab.esiea.fr", # Gitlab URL
    "gitlab_user": "esieabot", # Username
    "gitlab_repo": "esieabot-docs/rtd", # Repo name
    "gitlab_version": "main", # Version
    "conf_py_path": "/docs/source/", # Path in the checkout to the docs root
}

[...]

# Autogenerated content by Read the Docs
if 'html_context' in globals():
    
    html_context.update(context) # It erased everything set by user because update() is used the wrong way!
    
else:
    html_context = context
```

I looked at how the file is generated and here is what I found: https://github.com/readthedocs/readthedocs.org/blob/main/readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl

```
if 'html_context' in globals():
    {% if dont_overwrite_sphinx_context %}
    for key in context:
        if key not in html_context:
            html_context[key] = context[key]
    {% else %}
    html_context.update(context)
    {% endif %}
else:
    html_context = context
```

So there is a flag called `dont_overwrite_sphinx_context` to don't overwrite the user context (??) and to enable it you have to contact the support (??) https://docs.readthedocs.io/en/stable/feature-flags.html

Do you have to pay to set your own edit button correctly?

**Comment by Hyrla** [comment]
There was a PR 5 years ago that added this feature flag: https://github.com/readthedocs/readthedocs.org/pull/4349

As far as I understand it, the idea is to use the settings set by the user on the dashboard and not the ones set in conf.py (which is strange by why not, I'm not an expert in Read the Docs).

**So I think the true issue is there is no GUI to let the user sets the gitlab settings when the repository is not on gitlab.com but on a self hosted instance.**

**Comment by sravel** [comment]
Hello, I also want to add link to gitlab and I try to used Flag
https://docs.readthedocs.io/en/stable/feature-flags.html#available-flags
I append on conf.py like
``` python
# add flag for readthedocs https://docs.readthedocs.io/en/stable/feature-flags.html#available-flags
DONT_OVERWRITE_SPHINX_CONTEXT = 'dont_overwrite_sphinx_context'
```
and also try global variables for readthedocs
![image](https://user-images.githubusercontent.com/11534773/221130456-191f2d10-434c-4328-9072-6afac87a07d1.png)
but fail to add link

**Comment by Hyrla** [comment]
@sravel hi, the feature flag can’t be enabled with an environment variable. It can only be done by the readthedocs’ admins. I contacted them with the support page, they enabled the flag and now it’s working.

The true issue is there is no way to configure it properly without this flag.

**Comment by stsewd** [comment]
> Problem found. Readthedocs is overwriting html_context (why??).

This was done to keep backwards compatibility, but I think we should just enable it for all projects, maybe a small set of projects will break, but the solution should be easy.

@sravel please contact support via https://readthedocs.org/support/.

**Comment by humitos** [comment]
> This was done to keep backwards compatibility, but I think we should just enable it for all projects, maybe a small set of projects will break, but the solution should be easy.

I'm 👍🏼 on enabling this broadly and start thinking about removing this feature flag completely. We can start by enabling it by default to all new projects if we are not already.

**Comment by stsewd** [comment]
Closing this in favor of https://github.com/readthedocs/readthedocs.org/issues/10293.
