### ISSUE TITLE
Proxito: canonical redirects don't need further inspection of the version/project/filename

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#10065]
Currently, our canonical redirect logic expects to the current project/version/filename

https://github.com/readthedocs/readthedocs.org/blob/c0c3f02606ff0f2100444ed1791c30338cd062f8/readthedocs/proxito/views/serve.py#L148-L155

But in reality, we shouldn't need those, because:

- http to https redirects don't need any of that information, we just need to change the protocol!
- subproject redirects only need the project from the unresolved domain, and resolve that as `main-project.rtd.io/projects/subproject/{path}` (no need for version or filename!)
- canonical domain redirects don't need any of that information, we just need to change the domain! And for subprojects, we don't allow custom domains on subprojects, and they will be picked up in the previous redirect, so nothing to worry about.

Moving the execution of the http-https and to-canonical-domain redirects should be easy, moving the other one requires adding a new way of unresolving a project

https://github.com/readthedocs/readthedocs.org/blob/c0c3f02606ff0f2100444ed1791c30338cd062f8/readthedocs/core/resolver.py#L173-L176

this new way will just accept the project and return the root path of it, no versions, no translations, just the root (like it would be a single version), for example:

- project.rtd.io/
- docs.example.com/
- project.rtd.io/projects/subproject/
- docs.example.com/projects/subproject/

**Comment by ericholscher** [comment]
@stsewd I think the trade off here is that we end up with multiple requests, instead of a single request. I believe the original implementation was trying to get the user to the right place with 1 HTTP redirect. That said, if we can be smarter here with caching, it would be great, but multiple round trips to the server is also a huge source of slowness for users, and something to consider in design.

**Comment by humitos** [comment]
> but multiple round trips to the server is also a huge source of slowness for users, and something to consider in design.

I think 1 HTTP redirect will be harder to implement correctly. Also, once implemented, I suppose the code will be harder to follow as well 😄
