### ISSUE TITLE
Is `readthedocs-build` still supported?

### ISSUE THREAD

**Issue by MrMino** [readthedocs/readthedocs.org#10089]
The repo for (`readthedocs-build`)[https://pypi.org/project/readthedocs-build/] seems to be archived. Is this CLI utility still supported?

I'm having an issue where it does not find the RTD config in my repo, simply because it's named `.readthedocs.yaml` instead of `.readthedocs.yml`. I would like to PR a fix for it, but I'm not sure if the rtd-build utility is still maintained. I'm using it to test my doc builds in CI.

**Comment by humitos** [comment]
Hi @MrMino! That package is deprecated and it's not used anymore. We've changed the build process completely and that package shouldn't be used.

With the new build process implementation, we are reconsidering packaging the build itself into its own package/repository and we may recover that PyPI namespace. However, we are not there yet.

**Comment by MrMino** [comment]
Hi @humitos, great to hear that, thanks!

Would PRs going in this direction be accepted?
Also, I've seen https://github.com/readthedocs/readthedocs-build/issues/3, which suggests making an `rtd` cli command with `rtd init` and such. Is this still considered?

**Comment by humitos** [comment]
Unfortunately, we are not at the stage where we can accept PRs because we haven't started with the work to package the builder. That repository you mentioned is archived and probably the whole repository will be discarded with the new implementation.
