### ISSUE TITLE
Build retry doesn't seem to happen

### ISSUE THREAD

**Issue by nijel** [readthedocs/readthedocs.org#10101]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/weblate/
* Build URL (if applicable): https://readthedocs.org/projects/weblate/builds/19641353/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/nijel/

## Expected Result

The failed build for a version should be retried as stated in the error message.

## Actual Result

During a busy period (we released a bug fix release quickly after the regular one), several builds ended up with “Concurrency limit reached”. One of that was build for the released version, and that version was never retried since then.

I've also tried to start the build manually for this version, and it ended up with the same error despite there are no other builds for the project currently running: https://readthedocs.org/projects/weblate/builds/19663935/

**Comment by humitos** [comment]
This happens when there is a lot of builds triggered for the same project (including its translations), it's retried every 5 minutes during ~2hs if I remember correctly, and then it stop retrying to avoid overloading our servers.

**Comment by nijel** [comment]
I'd not mind if the `latest` builds get discarded. Actually, I'd be fine with building only the most recent one once the limit is reached. With versions, it is more problematic for us because we version our documentation links, so users end up on non-existing documentation in this case.
