### ISSUE TITLE
Can't able to see documentation but build passed

### ISSUE THREAD

**Issue by shivangvijay** [readthedocs/readthedocs.org#10117]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/python-logger/
* Document URL: https://python-logger.readthedocs.io/en/latest/
* Repository URL: https://github.com/shivangvijay/Python-Logger
* Read the Docs username (if applicable): shivangvijay

## Expected Result

The sphinx documents should be there as build successful.

## Actual Result

Maze found page appears:- 

This is a 404 error page. The link you have followed or the URL that you entered does not exist. It might be that the documentation has been updated, or this page has been removed.

[Back to the front page of python-logger.readthedocs.io](https://python-logger.readthedocs.io/)

        \          SORRY            /
         \                         /
          \    This page does     /
           ]   not exist yet.    [    ,'|
           ]                     [   /  |
           ]___               ___[ ,'   |
           ]  ]\             /[  [ |:   |
           ]  ] \           / [  [ |:   |
           ]  ]  ]         [  [  [ |:   |
           ]  ]  ]__     __[  [  [ |:   |
           ]  ]  ] ]\ _ /[ [  [  [ |:   |
           ]  ]  ] ] (#) [ [  [  [ :===='
           ]  ]  ]_].nHn.[_[  [  [
           ]  ]  ]  HHHHH. [  [  [
           ]  ] /   `HH("N  \ [  [
           ]__]/     HHH  "  \[__[
           ]         NNN         [
           ]         N/"         [
           ]         N H         [
          /          N            \
         /           q,            \
        /                           \

**Comment by humitos** [comment]
Hi @shivangvijay! Are you able to build your documentation locally? It seem your project does not generates an `index.html` file.

**Comment by shivangvijay** [comment]
Hello @humitos, Thanks for the response. Yes I able to build documentation locally. My project generating docs.html

**Comment by humitos** [comment]
It seems you already fixed the problem because I can access to https://python-logger.readthedocs.io/en/latest/ now. Is this correct? Should I close the issue?

**Comment by shivangvijay** [comment]
Yeah, This issue is fixed. But If you open Recipes page:- https://python-logger.readthedocs.io/en/latest/Recipe.html# , No content is here. Can you tell me the reason, beacuse when build locally and open index.html, the content is available. 

Useful information:- 
The content in this page is generated by 'sphinx.ext.autodoc' extension.

**Comment by humitos** [comment]
> The content in this page is generated by 'sphinx.ext.autodoc' extension.

Probably, there is no content there because you are not installing the package you are documenting in the Read the Docs environment, but you have it installed locally.

You probably need to use the `python.install` config key: https://docs.readthedocs.io/en/stable/config-file/v2.html#python-install
