### ISSUE TITLE
Fails to load due to Indefinite Redirects

### ISSUE THREAD

**Issue by robbmcleod** [readthedocs/readthedocs.org#10135]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/numexpr/
* Build URL (if applicable): https://readthedocs.org/projects/numexpr/builds/19730434/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/robbmcleod/

## Expected Result

I had a report that the docs for NumExpr are not working anymore (https://github.com/pydata/numexpr/issues/429). Apparently there are an indefinite number of redirects. E.g.

https://numexpr.readthedocs.io

redirects to:

https://numexpr.readthedocs.io/projects/NumExpr3/projects/NumExpr3/projects/NumExpr3/projects/NumExpr3/projects/NumExpr3/projects/NumExpr3/projects/NumExpr3/projects/NumExpr3/projects/NumExpr3/projects/NumExpr3/projects/NumExpr3/projects/NumExpr3/projects/NumExpr3/projects/NumExpr3/projects/NumExpr3/projects/NumExpr3/projects/NumExpr3/projects/NumExpr3/projects/NumExpr3/

I went into the ReadTheDocs web interface and try and rebuild it but the same indefinite redirect behavior is seen.

Possibly related to #10112? I don't see any settings that would change the redirect behavior.

**Comment by stsewd** [comment]
Hi, looks like your project is set as a subproject of itself. I have deleted that relationship from our DB, probably something that was done before we had some checks in place to prevent that.
