### ISSUE TITLE
ipynb file suddenly not compiling even though no changes were made (still compiles locally)

### ISSUE THREAD

**Issue by Shreyas911** [readthedocs/readthedocs.org#10143]
* Read the Docs project URL: https://readthedocs.org/projects/sicopolis/
* Build URL (if applicable): https://readthedocs.org/projects/sicopolis/builds/19766939/
* Read the Docs username (if applicable): shreyasg911

I changed nothing in my sphinx directory and the docs just failed for no reason because an ipynb file could not be compiled. The docs still compile locally though.

Any help is appreciated!

Thanks,
Shreyas

**Comment by aazuspan** [comment]
I'm having the same issue with the same `pandoc: Unknown extension: smart` error.

https://readthedocs.org/projects/sankee/builds/19755717/

**Comment by humitos** [comment]
It seems the pandoc installed on Read the Docs does not have the `smart` extension installed (https://pandoc.org/MANUAL.html#extension-smart). You should research about how to install it on Ubuntu 22.04 and use `build.apt_packages` to install it on Read the Docs.

**Comment by mgeier** [comment]
The pre-installed Pandoc version on recent RTD images is fine, the projects in question seem to use and outdated RTD config (which I guess uses something much older than Ubuntu 22.04).

See https://github.com/spatialaudio/nbsphinx/issues/720#issuecomment-1467799866.

**Comment by Shreyas911** [comment]
Thanks much @mgeier! :)
