### ISSUE TITLE
Proxito: do `https` redirects at the middleware level

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#10144]
Currently, we are doing http->https redirects for docs pages only, things that aren't docs pages, like proxied APIs aren't being redirected.

https://github.com/readthedocs/readthedocs.org/blob/73a05d23dada5eb3d6103164de3fda6fbab6d2d7/readthedocs/proxito/views/serve.py#L287-L287

This is only relevant on .org, since on .com we do the http->https redirects at the nginx level for both, custom domains and public domains.

But since we want to remove all that logic from nginx and rely on proxito, we need to redirect all requests, not just docs pages.
Another solution can be to just always redirect to https on .org as we do on .com, that way we could just use https://docs.djangoproject.com/en/3.2/ref/settings/#std-setting-SECURE_SSL_REDIRECT (but we will be losing some control about caching those types of redirects if we use that setting instead of doing it manually)

**Comment by ericholscher** [comment]
> Another solution can be to just always redirect to https on .org as we do on .com, that way we could just use https://docs.djangoproject.com/en/3.2/ref/settings/#std-setting-SECURE_SSL_REDIRECT (but we will be losing some control about caching those types of redirects if we use that setting instead of doing it manually)

If we're losing our cache headers, I'm fine handling it ourselves 👍
