### ISSUE TITLE
Accepting invitation leads to 404 error

### ISSUE THREAD

**Issue by Ark-kun** [readthedocs/readthedocs.org#10145]
## Details

I've received the following e-mail:
```
Hello,
--
some-user has invited you to join the kfp-kubernetes project. You can accept or decline this invitation using the following link:https://readthedocs.org/invitations/XXXXXXX/ This invitation will expire in 2 weeks.
Keep documenting,
Read the Docs
```

When I click the link, I see the standard RTFD 404 error page: `This is a 404 error page. The link you have followed or the URL that you entered does not exist. It might be that the documentation has been updated, or this page has been removed.`

The project exists and I can see it: https://readthedocs.org/projects/kfp-kubernetes/

Please, help me accept the invitation.

## Expected Result

I expect clicking the "accept invitation" link to result in acceptance of invitation.
Or at least a proper error, not 404.

## Actual Result

I get error 404.

**Comment by stsewd** [comment]
Hi! Invitations expire after 2 weeks, the person who send you the invitation must invite you again.

**Comment by Ark-kun** [comment]
The invitation was just 2 hours old at that time.

**Comment by stsewd** [comment]
Probably the author revoked the invitation.
