### ISSUE TITLE
Docs: Research solution for reusable page meta data

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#10157]
## Problem statement

Our how-to guides and feature reference roughly consist of 3 string data elements that are reused or used in a different context than the page itself:

1) "TOC label"
2) "Short title"
3) "Lead paragraph"

![image](https://user-images.githubusercontent.com/374612/225654235-b30e1125-6833-43fa-947f-3c80910acf75.png)

While it's possible to be pragmatic or accept compromises regarding labels, the outcome will most certainly be less attractive: More cluttered navigation and texts that exist outside of their context and will eventually be forgotten in updates.

## Possibilities

We just focus on the 3 above examples of meta data fields, but the Feature Reference could benefit from more meta data. What is a "feature"? What does it consist of? Perhaps all features could have a link to a howto guide, perhaps all features could have a screenshot etc.

We are perhaps wanting to using Sphinx as a conventional static site generator. Think of how Hugo uses [front matter](https://gohugo.io/content-management/front-matter/).

## Solutions?

a) If there's an existing way to do it: We do it!
b) If it requires to write an extension, we need to decide if its worth it..

Meanwhile, the current situation of maintaining duplicate content will unfold, and we'll see how badly it goes or if its acceptable.

---

Branched out from #10131

**Comment by benjaoming** [comment]
A quick note on what we already did:

1) We looked into https://www.sphinx-doc.org/en/master/usage/restructuredtext/field-lists.html#file-wide-metadata and it doesn't seem like we can output anything from `docinfo` without writing a new Sphinx role/directive

2) We looked at https://github.com/sphinx-contrib/datatemplates but it doesn't seem to have a simple way to easily store data together with a page, we'd end up with separate YAML files and that's again fragmenting content into new location where they will be harder to maintain, translate etc.

**Comment by benjaoming** [comment]
Perhaps the way that [ablog](https://ablog.readthedocs.io/en/stable/) uses metadata can be used for inspiration?

```
.. post:: March 30, 2023
   :tags: newsletter, python
   :author: Arnold
   :location: Los Angelos
   :category: newsletter
```

**Comment by ericholscher** [comment]
Refs https://github.com/readthedocs/readthedocs.org/pull/10552

**Comment by ericholscher** [comment]
Going to close this, since I think we are trying to remove the number of places we're using this context, and hopefully can handle this manually going forward.
