### ISSUE TITLE
PDF gets generated regardless of the user choice in Advnaced Settings

### ISSUE THREAD

**Issue by gwilku** [readthedocs/readthedocs.org#10151]
## Expected Result

When you un-check the option:

` Enable PDF build
Create a PDF version of your documentation with each build.`

the PDF should not be generated

## Actual Result

The PDF is generated (and that leads to other errors with LATEXOPS, reported in a different issue)

**Comment by stsewd** [comment]
Hi, can you please fill the details from the issue template?

I'm guessing that your project is using a config file, so the options from the UI don't have effect.

**Comment by gwilku** [comment]
Thanks for reaching out.

The issue is not related to a particular project, but you are correct: there was the corresponding PDF option in .readthedocsyml. Commenting it solved the problem - thank you!

As a side note: it would be nice to have some info next to that option that says it's subject to override in the config.

**Comment by stsewd** [comment]
We do have a warning at the top

![Screenshot 2023-03-14 at 13-55-21 Edit Advanced Project Settings Read the Docs](https://user-images.githubusercontent.com/4975310/225108792-15c8d539-ba52-4456-acfb-bad0e70d3e53.png)

**Comment by gwilku** [comment]
OMG - I feel so dumb now... Thanks again!
