### ISSUE TITLE
Menu not expanding on Android Chrome

### ISSUE THREAD

**Issue by edtechre** [readthedocs/readthedocs.org#10159]
## Details

* Read the Docs project URL: https://www.pybroker.com
* Read the Docs username (if applicable): https://readthedocs.org/profiles/edtechre

Tapping the hamburger menu icon does not expand the menu on Android Chrome.

## Expected Result

The menu should expand. I tested on an identical Sphinx build with my own local server and it works fine there. But not when hosted on RTD.

## Actual Result

Nothing happens when the hamburger icon is tapped.

**Comment by stsewd** [comment]
Hi there, looks like jquery isn't being loaded on the theme. I see that you are using the latest version of the rtd theme, so jquery should be included, but for some reason is not..

**Comment by edtechre** [comment]
Thanks. My conf.py is here:
https://github.com/edtechre/pybroker/blob/master/docs/conf.py

I build locally with sphinx-build -n -W --keep-going -b html docs/ docs/_build/ and it works on my local server.

**Comment by edtechre** [comment]
I do see jquery.js loading from https://www.pybroker.com/_/static/javascript/readthedocs-doc-embed.js

I tried making this fix:
  <script>
      window.addEventListener("load", function() {
         jQuery(function() {
            SphinxRtdTheme.Navigation.enable(true);
         });
      });
   </script>

Now I see this error thrown from theme.js:
Uncaught TypeError: e is not a function
    at Object.enable (theme.js:1:1246)
    at HTMLDocument.<anonymous> ((index):130:36)
    at e (jquery.js:1:30392)
    at t (jquery.js:1:30718)

**Comment by humitos** [comment]
I'm hitting the same issue/error.

You can see a live example at https://test-builds.readthedocs.io/en/manual-integrations/

**Comment by stsewd** [comment]
Ref https://github.com/readthedocs/sphinx_rtd_theme/pull/1448

**Comment by irmen** [comment]
Confirming having the same issue for https://prog8.readthedocs.io/en/latest/

Firefox on Linux

**Comment by stsewd** [comment]
I think a temporal solution is to add this in your conf.py file.

```python
extensions = [
    "sphinxcontrib.jquery",
]
```

**Comment by irmen** [comment]
Thank you, this was indeed what fixed it for me

**Comment by stsewd** [comment]
This is being tracked at https://github.com/readthedocs/sphinx_rtd_theme/issues/1452.
