### ISSUE TITLE
sphinx autodoc  doesn't show anything for python files

### ISSUE THREAD

**Issue by shfarhee** [readthedocs/readthedocs.org#10155]
I am trying to import a project from git-hub to read the doc website where rst files are working and(source code) the python code is not showing anything. Where as the same setup is working fine in my local system.

RTD website
shows nothing

Details
Project URL: https://responsibleai.readthedocs.io/en/latest/
Build URL (if applicable):
Expected Result
Autodoc the module based on the docstrings inserted in every functions

Actual Result
The page remains empty for reference section(python files)

**Comment by shfarhee** [comment]
> Hi, in your build you can see that are several errors related to missing dependencies.
> 
> https://readthedocs.org/projects/responsibleai/builds/19803894/
> 
> > * ModuleNotFoundError: No module named 'numpy'
> 
> See https://docs.readthedocs.io/en/stable/faq.html#how-do-i-add-additional-software-dependencies-for-my-documentation.


Hi,Thanks .I am able to fix the module issue but now i am getting 'getsitepackages' issue (* AttributeError: module 'site' has no attribute 'getsitepackages'.
Failed to import)-https://readthedocs.org/api/v2/build/19819139.txt.
<img width="364" alt="getsitepackage" src="https://user-images.githubusercontent.com/116381069/225983959-1307f49e-fc8a-42f2-8848-75a664e20424.PNG">

**Comment by stsewd** [comment]
I saw that you are using an invalid config file https://github.com/cisco-open/ResponsibleAI/blob/main/docs/.readthedocs.yml, that should be at the root of your project, otherwise RTD won't be able to find it, and we don't support windows as OS

**Comment by shfarhee** [comment]
Thanks, I changed the yaml file to the root directory and i am still getting **'getsitepackages' issue (* AttributeError: module 'site' has no attribute 'getsitepackages'.**
<img width="364" alt="getsitepackage" src="https://user-images.githubusercontent.com/116381069/226412352-06e5f1b9-3800-41fe-ac38-7f2e87dab742.PNG">
