### ISSUE TITLE
Build error if `pandoc=3.1.1` *ie* latest version on conda-forge

### ISSUE THREAD

**Issue by valeriupredoi** [readthedocs/readthedocs.org#10162]
Hey guys, a quick note that the build is complaining if we have `pandoc=3.1.1` in our environment, see [here](https://readthedocs.org/projects/esmvalcore/builds/19814622/) - the error is not stopping the build, but I thought I'd let you know anyway; we are grabbing most of our dependencies from conda-forge, and pandoc is indeed at 3.1.1 there, and is the latest version (at the time of this writing), but I see that on PyPI is pretty ye olde at 2.3 from last year. Possibly an older pin in RTD? Cheers muchly and keep up the great work! Good weekend :beer:

**Comment by humitos** [comment]
Hi! Thanks for opening this issue. Can you expand on it? I'm not sure to understand what's the build error you are describing or what's the problem with `pandoc` on Read the Docs 😅

**Comment by valeriupredoi** [comment]
Hi @humitos - I've literally just realized it's not you guys, but us - we're building a conda virtual env where we get sphinx and other gubbins, and assumed (without prior check, my bad!) that sphinx there is at latest version (6.3.1) yet, the build is still complaining that pandoc is too new - so I assumed there may be some internal pinning from RTD or some other wizardry happening. But, I just checked, and we're pulling in sphinx=5 so no wonder the build via sphinx is complaining about a too new pandoc. Cheers and sorry for bugging you guys for something we should fix :beer: :grin:

**Comment by humitos** [comment]
No worries. Thanks for the full explanation about the issue 👍🏼
