### ISSUE TITLE
`eslint` checks are failing

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#10167]
All the PRs are failing the checks because of `eslint`. See for example, https://app.circleci.com/pipelines/github/readthedocs/readthedocs.org/7267/workflows/caa933d2-3775-461b-83ad-789befee4df0/jobs/17728

`eslint` is not saying _why_ it's failing. I tried to debug this locally but I wasn't able to run it correctly 🤷🏼

**Comment by agjohnson** [comment]
I bet this is similar to Poetry failing on CircleCI, and is related to ANSI escape codes.

**Comment by agjohnson** [comment]
I was wrong. It was a broken asdf/nvm (?) installation. Using the native node orb solved issues here.
