### ISSUE TITLE
/bin/bash: python3.8: command not found

### ISSUE THREAD

**Issue by emmettbutler** [readthedocs/readthedocs.org#10173]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/ddtrace
* Build URL (if applicable): https://readthedocs.org/projects/ddtrace/builds/19855881/

![](https://user-images.githubusercontent.com/55767766/226681867-6ecd8e0c-db5d-48a1-948b-e249aa0abd9a.png)
(Image copied from https://github.com/readthedocs/readthedocs.org/issues/10171#issuecomment-1478295099)

## Expected Result

Successful build

## Actual Result

Build fails with `/bin/bash: python3.8: command not found`.

**Comment by emmettbutler** [comment]
A workaround for this issue is to configure `build.tools.python` ([example](https://github.com/nextstrain/augur/commit/6b501cdefb58614b228dc1d45a8a572c277c234f))

**Comment by ericholscher** [comment]
We're rolling back out build server deploy, it should be fixed in ~5 mins.
