### ISSUE TITLE
"build.jobs.post_install" considered an invalid configuration option

### ISSUE THREAD

**Issue by EricR86** [readthedocs/readthedocs.org#10190]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/segtools/
* Build URL (if applicable): https://readthedocs.org/projects/segtools/builds/19894754/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/ericr86/

## Expected Result

The ability to run a command on post install of my project.

## Actual Result

An error message showing that the yaml option is specified in invalid, despite the documentation saying otherwise.
Error message:
```
Error

Problem in your project's configuration. Invalid "build.jobs.post_install": .readthedocs.yaml: Invalid configuration option: build.jobs.post_install. Make sure the key name is correct.
```
`post_install` in the allowed keys for `build.jobs`:
[https://docs.readthedocs.io/en/stable/config-file/v2.html#build-jobs](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-jobs)

**Comment by humitos** [comment]
(from the phone)

You need to use "build.os" to be able to use "build.jobs". Try that and let me know
