### ISSUE TITLE
Building docs with mambaforge-4.10 raises AttributeError

### ISSUE THREAD

**Issue by lukelbd** [readthedocs/readthedocs.org#10193]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/proplot/
* Build URL (if applicable): https://readthedocs.org/projects/proplot/builds/19910376/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/proplot/

## Expected Result

Documentation successfully builds with mamba (I am trying to switch to mamba to reduce excessive memory consumption errors that occur when RTD tries to solve my conda builds).

## Actual Result

Documentation raises the following error:

```python
AttributeError: module 'libmambapy' has no attribute 'QueryFormat'
```

This seems related to #9306. I saw in that thread that you fixed their problem by disabling some build setting -- is there any way I can do that via the web interface / some `readthedocs.yaml` setting? Or can this only be done on your end? Thanks in advance

**Comment by humitos** [comment]
OK. I disabled that setting for your project (`UPDATE_CONDA_STARTUP`) and triggered a new build at https://readthedocs.org/projects/proplot/builds/19915285/. It should be solved now. Feel free to close the issue or write another comment here 👍🏼

**Comment by lukelbd** [comment]
Awesome, thanks!
