### ISSUE TITLE
RTD Sphinx Builds failing due to `.. program-output::` being unable to find CLI commands

### ISSUE THREAD

**Issue by joshuacwnewton** [readthedocs/readthedocs.org#10205]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/spinalcordtoolbox/
* Build URL (if applicable):
    * Passing (March 28th, 3:22pm): https://readthedocs.org/projects/spinalcordtoolbox/builds/19932219/
    * Failing (March 28th, 5:24pm): https://readthedocs.org/projects/spinalcordtoolbox/builds/19933629/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/joshuacwnewton

## Expected Result

The various `.. program-output::` directives are able to find the relevant CLI scripts, and display their argparse help descriptions.

## Actual Result

The scripts cannot be found, and the following errors are generated (51 in total, one for each call):

```
119: WARNING: Command ['sct_analyze_lesion', '-h'] failed: [Errno 2] No such file or directory: 'sct_analyze_lesion'
125: WARNING: Command ['sct_analyze_texture', '-h'] failed: [Errno 2] No such file or directory: 'sct_analyze_texture'
131: WARNING: Command ['sct_apply_transfo', '-h'] failed: [Errno 2] No such file or directory: 'sct_apply_transfo'
137: WARNING: Command ['sct_compute_ernst_angle', '-h'] failed: [Errno 2] No such file or directory: 'sct_compute_ernst_angle'
143: WARNING: Command ['sct_compute_hausdorff_distance', '-h'] failed: [Errno 2] No such file or directory: 'sct_compute_hausdorff_distance'
...
```

## Self investigation

This is occurring on multiple PRs (https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4074, https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4078), neither of which touch our documentation, installation, etc. So, I don't think this is user error.

We [diffed the logs](https://www.diffchecker.com/DbbtLKF6/) between passing and failing runs, but because there's only a ~2hr time difference between passing and failing runs, the dependency changes are _extremely_ minimal. (A single patch update to `fonttools` is all I can see in the diff.)

We also tried [building the docs locally](https://github.com/spinalcordtoolbox/spinalcordtoolbox/issues/4082#issuecomment-1487454148) using Sphinx and encountered no errors. (Hence, opening an issue on RTD specifically.)

**Comment by stsewd** [comment]
Hi, this is probably the same problem as https://github.com/readthedocs/readthedocs.org/issues/10203#issuecomment-1487467158

**Comment by joshuacwnewton** [comment]
Thanks! I'll close this as a duplicate, then. (Especially given that the linked comment explicitly mentions changes to how the PATH is computed.)
