### ISSUE TITLE
Dunamai unable to find version tags on latest builds

### ISSUE THREAD

**Issue by rlaphoenix** [readthedocs/readthedocs.org#10214]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/vsgan/
* Build URL (if applicable): https://readthedocs.org/projects/vsgan/builds/19977977/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/rlaPHOENiX/

## Expected Result

The version number on the left sidebar underneath the Logo image should be `v1.6.4-post.69+efdcb75`.

## Actual Result

The version number is `v0.0.0-post.69+efdcb75`, indicating that `dunamai` had to fallback to `0.0.0` as it could not find a version tag. This doesn't happen on stable releases, nor on local builds.

My best guess is the git clone is not keeping tags?

**Comment by humitos** [comment]
Are you talking about this version number?

![Screenshot_2023-04-03_13-25-08](https://user-images.githubusercontent.com/244656/229495964-cbfc4af7-aa0a-4b36-aaac-499a8163a355.png)

In that case, where that version comes from? I saw that you are using Furo theme, so maybe there is a configuration you can check from it?

**Comment by humitos** [comment]
Read the Docs perform a shallow clone, maybe that's the reason. You can try by unshallowing it: https://docs.readthedocs.io/en/latest/build-customization.html#unshallow-git-clone

**Comment by rlaphoenix** [comment]
Yep! That worked like a charm. Now I wonder if there's a way to reduce load on RTD and build time by only unshallowing the git clone up until it gets a tagged commit.

**Comment by humitos** [comment]
I'm happy that you solved the issue. I'm sure there are some "dark git argument" that will do exactly that, but I think I'm not gonna be able to help you there with my limited knowledge of git 🙃
