### ISSUE TITLE
[Meta] Enable Discussions tab on this GitHub repo

### ISSUE THREAD

**Issue by EwoutH** [readthedocs/readthedocs.org#10218]
I would find it quite useful if the [Discussions](https://github.com/features/discussions) tab could be enabled on this repository. Then users would have a place to discuss questions, configurations and new ideas, without flooding the issues.

It can be enabled very easily, see [Enabling GitHub Discussions on your repository](https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-repository).

**Comment by humitos** [comment]
We have been following up with the StackOverflow community under the tag `read-the-docs` at https://stackoverflow.com/questions/tagged/read-the-docs

I'm not opposed to enabling it, but I don't have a strong preference for GitHub Discussions over StackOverflow at this point, considering that there are already a ton of questions/answers in SO. Would you like to elaborate more about what are the benefits of GH Discussions?

**Comment by humitos** [comment]
I'm closing this issue since we decided to not enable Discussions for now. We can revisit in the future, tho.
