### ISSUE TITLE
Project: put a rate limit on "Import project" form

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#10222]
We received a lot of spam projects in the last weeks. It seems that we don't have any kind of limit about how many projects can be imported per user in a window timeframe. We should limit this by 1 every 5 minutes or similar.

There are some work already done by `django-allauth` that we could copy. Basically, we should use the cache to check for this limits and fail the form validation.

**Comment by agjohnson** [comment]
Note there is a discussion here as well, link it.

**Comment by agjohnson** [comment]
@humitos I'll assign you for now so this is on our radar. But depending on where we land with direction, we can reassign this later as well. I'll keep it design decision until we decide, and perhaps this is a good conversation to go over next planning meeting as well.

**Comment by humitos** [comment]
I created a rule that allows 3 imports every 10 minutes on `/dashboard/import/.*`. Can you take a look at this rule please and if you OK with it, just turn it on? https://dash.cloudflare.com/76f653d51b8df4e9e956eb83a5ff42f4/readthedocs.org/security/waf/rate-limiting-rules/fd201ca1893e4bc899db9fd77c84e2cc cc @ericholscher

**Comment by ericholscher** [comment]
@humitos Looks good. I wonder about not limiting to just POST, and just limit on the GET for the form itself?

**Comment by humitos** [comment]
I saw that you already enabled the rule. There are a total of 7 events and all of them managed the challenge properly. I think it's working fine.

> I wonder about not limiting to just POST, and just limit on the GET for the form itself?

I don't have a strong opinion here, but making only GET won't work against bots, tho. If anything, we should put both, but that will make just "seeing the page" to count for rate-limit.

I'd say to test the rule as it is for now, and check how it behaves in some weeks. We can tune it later if we detect that's not catching some scenarios.

**Comment by humitos** [comment]
BTW, do you know if it's possible to see the body of the POST? I'd like to know what are the projects' URLs that are affected. That will tell us if it's caching potential spam or real people.

**Comment by ericholscher** [comment]
@humitos Unfortunately not. The firewall logs have metadata, but not the actual POST data. Should be easy enough to line up the timestamp with the project creation tho?

**Comment by humitos** [comment]
I'm not sure how to read this, but it seems that 710 import projects were blocked in the last 7 days and all of them managed the challenge. So, are they real people? 🤷🏼 

On the other hand, I haven't seen spammers creating multiple projects at once in these days yet. So, we haven't tested the rule under the situations we want to test.

If we are only penalizing real people, we can increase the rate limit a little more and try to catch only spammers.

**Comment by humitos** [comment]
Also, I'm thinking that to import a project the user may need to do 2 or more POSTs to the `/dashboard/import/` since we have a wizard form there 😅 . So, it probably makes sense to increase this.

Besides, we should add the same limitation to our APIv3 that allows users to create projects in bulk, right? However, that will kill one of the benefits of using the API 😞

**Comment by ericholscher** [comment]
I don't think spammers are going to use our API, so I'm not sure why we would implement it there unless we saw activity.

If most people are passing this, I agree lets make it less aggressive.

**Comment by humitos** [comment]
35 in total for the last 72hs and all of them managed. I think it's fine to leave it as is. It's not caching spammers yet, but we haven't had any spam attack lately either. In any case, if a real user is importing 6 projects in 10 minutes, is doing something weird anyways 😄 . I think we can close this issue here, but feel free to reopen if you consider there is something else I should do.
