### ISSUE TITLE
Flyout menu and other features broken with Sphinx>=6.0

### ISSUE THREAD

**Issue by dsavransky** [readthedocs/readthedocs.org#10242]
## Details

Upon adding a .readthedocs.yaml file to my project, I noticed multiple build issues with my html docs. I traced these down to the build system installing very old versions of both sphinx (1.8.6) and the rtd theme (0.4.3).  I forced these to be updated by adding documentation requirements, causing the latest versions of both to be installed at build time (6.1.3 and 1.2.0, respectively).  However, the html build was still broken in two ways:
1) The `collapse_navigation` theme option was being ignored (missing + signs from navigation items)
2) The flyout menu was present, but would not open when clicked on.

After some experimenting, I was able to fix both of these issues by setting the doc requirement on sphinx to be >4.0<6.0 (effectively forcing 5.3.0 to be installed).

While I see some other people having reported similar issues in the past, I cannot find any version 6-specific bug reports (apologies if a redundant issue already exists).

I've currently set it to build 3 versions: before adding the .yaml file (flyout works, collapse_navigation ignored due to old theme versions); with the 6.1.3 sphinx and 1.2.0 theme (flyout not working, collapse_navigation ignored); and one with 5.3.0 sphinx and 1.2.0 theme (everything works as expected).

* Read the Docs project URL: https://readthedocs.org/projects/exosims/
* Build URL (if applicable): 
  - No yaml file:  https://readthedocs.org/projects/exosims/builds/20086393/
  - yaml file, latest versions of theme and sphinx (broken): https://readthedocs.org/projects/exosims/builds/20086259/
  - yaml file, sphinx at 5.3.0 (fully working as expected): https://readthedocs.org/projects/exosims/builds/20086569/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/dsavransky/

## Expected Result

I expect `'collapse_navigation': False` honored (+ signs appear by navigation menu items), and the flyout menu to open when clicked.

## Actual Result

Neither of these happens unless Sphinx 5.3.0 is forced.

**Comment by stsewd** [comment]
Hi, the problem about the flyout menu, is probably because of https://github.com/readthedocs/sphinx_rtd_theme/issues/1452.

**Comment by stsewd** [comment]
Please subscribe to that other issue.
