### ISSUE TITLE
Builds: avoid breaking builds when adding a new field to our APIs

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#10257]
When adding a new field to our API, builds will immediately receive that new field, but our builders don't know about that new field yet, so creating an `APIVersion` or `APIProject` instance will fail

https://github.com/readthedocs/readthedocs.org/blob/60ffcb6b1d1edded7c521bfcb3d9f924fa0f54e9/readthedocs/projects/tasks/builds.py#L802-L802

We could inspect the available fields from the model to create the object only with those fields, and maybe log the fields that aren't part of the model.

ref https://github.com/readthedocs/readthedocs.org/issues/10256

**Comment by humitos** [comment]
> We could inspect the available fields from the model to create the object only with those fields, and maybe log the fields that aren't part of the model.

I like this idea. It will allow us to have both builders (old and new ones) at the same time while doing a deploy 👍🏼
