### ISSUE TITLE
Docs: Main page next steps

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#10252]
We have recently changed the main documentation page to reflect the documentation's all new Diátaxis structure:

https://docs.readthedocs.io/en/stable/

The previous change was deliberately limited. It included only text (and some emojis) but no visual layout elements.

This issue is about identifying the next steps:

* *What* can users benefit from seeing and discovering on the documentation landing page?
* Any small re-prioritizations of current elements?

**Comment by humitos** [comment]
I'm pretty excited about this 😄 

I think the first step here could be start collecting examples of other projects' main page that follow Diataxis or a similar pattern. Having all these examples in the same place will help us to be all in the same page and discuss with better arguments + being able to "still the best ideas" 😄 

Here are some examples that I found from some old conversations we had:

* https://docs.pennylane.ai/en/stable/
* https://jupyterbook.org/en/stable/intro.html
* https://pandas.pydata.org/docs/
* https://scipy.github.io/devdocs/index.html

**Comment by benjaoming** [comment]
@humitos I love that! We tried an experiment me and @ericholscher by discussing https://guide.wagtail.org/en-latest/ - but I think we agreed that even though it's visually appealing, it lacks on discovering the actual content. But I think we aligned some kind of vision by looking at examples together and sharing reflections.

One of my first two reactions when looking at multiple different examples is: 1) our current landing page is actually pretty good, it's just very friendly 2) aside from that, it does seem a bit underwhelming because it doesn't feature neither illustrations nor any visual widgets.

My favorite is the first one, PennyLane :) I really like its overall composition, which I could see as 4 elements: 1) the title and subheading, 2) simple important elements, 3) a longer intro and then as you scroll down 4) _other stuff_ appears with less importance, yet a great way for discoverability.

**Comment by ericholscher** [comment]
Yea, I think copying some kind of visual design from out marketing landing page could be good to add some visual flair if we wanted. 


Overall, I agree our landing page is pretty good, and could just use a bit to make it fancier, but it's way better than the "huge list of links" we have previously.

**Comment by humitos** [comment]
BTW, this is the feedback we got from the main page at Write the Docs Writing Day some weeks ago, https://github.com/readthedocs/readthedocs.org/issues/10300. I think it would be useful to consider it while working on these next steps.

**Comment by benjaoming** [comment]
Yes, this is really good feedback. Especially useful for the main page:

> General feedback on the copy on the main index page: Manuel explained that the selected topics are curated (as opposed to what's in the left nav), and they're meant to be the most important/useful topics for newcomers. That didn't always come through, and maybe small tweaks to the body copy in each section would help (some examples below).

**Comment by ericholscher** [comment]
Going to close this, and put together a new issue based on the nav refactor that we've doing.
