### ISSUE TITLE
RTD fails immediately with error that makes no sense

### ISSUE THREAD

**Issue by pllim** [readthedocs/readthedocs.org#10256]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/astropy/
* Build URL (if applicable): https://readthedocs.org/projects/astropy/builds/20155264/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/pllim/

## Expected Result

A build to happen.

## Actual Result

It fails immediately with no error that I can act upon. It claims the project does not have `.readthedocs.yaml` but we do, and we have been using that for a while. Explicitly defining it in Admin settings did not fix the problem.

When I look at the raw log, this is all I see:

```
Read the Docs build information
Build id: 20155264
Project: astropy
Version: latest
Commit: None
Date: 2023-04-18T16:59:49.491057Z
State: finished
Success: False
```

**Comment by stsewd** [comment]
Hi, this is probably related to our deploy from today, we are taking a look

**Comment by ericholscher** [comment]
This should be fixed, please let us know if it isn't.

**Comment by pllim** [comment]
I triggered a rebuild. 🤞

**Comment by pllim** [comment]
Fixed now. Thanks!
