### ISSUE TITLE
Outdated versions of sphinx and other dependencies being installed (with `pyproject.toml`), search stuck

### ISSUE THREAD

**Issue by EwoutH** [readthedocs/readthedocs.org#10263]
### Problem description

We've encountered an issue with Read the Docs configuration where search is not functioning properly, likely due to incompatible versions of `sphinx`, `sphinx-rtd-theme`, and other dependencies being installed. Our dependencies are specified in an optional `docs` dependency in a `pyproject.toml` [file](https://github.com/quaquel/EMAworkbench/blob/b2b542e33f69911924eabf214a057d86775ba050/pyproject.toml#L39), and our `.readthedocs.yaml` includes this:

```toml
[project.optional-dependencies]
docs = ["sphinx", "sphinx-rtd-theme", "readthedocs-sphinx-ext", "nbsphinx", "myst", "pyscaffold", "myst-parser"]
```
Then, our `.readthedocs.yaml` [includes](https://github.com/quaquel/EMAworkbench/blob/b2b542e33f69911924eabf214a057d86775ba050/.readthedocs.yaml#L24-L29) this:

```yaml
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
```

However, our Read the Docs [build log](https://readthedocs.org/projects/emaworkbench/builds/20059779/) first installs `sphinx<2` and `sphinx-rtd-theme<0.5`, and only after that, in a separate step, our actual `.[docs]` optional dependencies, which include `sphinx-6.1.3` and `sphinx-rtd-theme-1.2.0`. This issue is detailed in the PR [quaquel/EMAworkbench#242](https://github.com/quaquel/EMAworkbench/pull/242).

We've also tried [adding](https://github.com/quaquel/EMAworkbench/pull/242/commits/a51925f8a149aae2f528bce58285afc337c05293) a `docs/requirements.txt` file specifically for Read the Docs, but it still installs outdated versions of the dependencies. We're following [the documentation](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html), but search still [doesn't work](https://emaworkbench--242.org.readthedocs.build/en/242/).

### Expected behavior

The Read the Docs build should install the correct versions of `sphinx`, `sphinx-rtd-theme`, and `readthedocs-sphinx-ext` as specified in the `pyproject.toml` file, and search should function correctly.

### Steps to reproduce

1. Set up a `pyproject.toml` file with optional `docs` dependencies as shown above.
2. Configure `.readthedocs.yaml` as shown above.
3. Create a Read the Docs build.
4. Observe the installed versions of `sphinx`, `sphinx-rtd-theme` and other dependencies

### Environment details

- Project: [quaquel/EMAworkbench](https://github.com/quaquel/EMAworkbench)
- Build URL: https://readthedocs.org/projects/emaworkbench

### Additional context
- Our PR [quaquel/EMAworkbench#242](https://github.com/quaquel/EMAworkbench/pull/242)
- Possible related issue: [readthedocs/sphinx_rtd_theme#1452](https://github.com/readthedocs/sphinx_rtd_theme/issues/1452)

**Comment by stsewd** [comment]
> I can remove your project from that "feature", so it installs the latest version by default.

Done https://readthedocs.org/projects/emaworkbench/builds/20258938/

**Comment by stsewd** [comment]
Also seeing your PR https://github.com/quaquel/EMAworkbench/pull/242, note that search options work over the final HTML pages produced by your build https://docs.readthedocs.io/en/stable/config-file/v2.html#search-ranking, not the source files or files that are in your repo and aren't included in the final build of your docs.

**Comment by EwoutH** [comment]
Thanks a lot for getting back!

> Hi, this is to keep backwards compatibility with old projects, see https://docs.readthedocs.io/en/stable/build-default-versions.html#python. I can remove your project from that "feature", so it installs the latest version by default.

> Done https://readthedocs.org/projects/emaworkbench/builds/20258938/

Thanks!

One small note, it still installs `setuptools<58`. This a problem for us, since our docs dependencies are defined in a `pyproject.toml`. Optional requirements are only properly support from 63 and up. Is it possible to install a later version of setuptools in Readthedocs?

> But your main problem about the search not working is because of https://github.com/readthedocs/sphinx_rtd_theme/issues/1452, please follow the workaround from https://github.com/readthedocs/sphinx_rtd_theme/issues/1452#issuecomment-1490504991.

Thanks, this fixes our problem!

We started teaching a course today, so over a hundred students thank you!

CC @quaquel.

**Comment by stsewd** [comment]
> One small note, it still installs setuptools<58. This a problem for us, since our docs dependencies are defined in a pyproject.toml. Optional requirements are only properly support from 63 and up. Is it possible to install a later version of setuptools in Readthedocs?

I have forgotten about that, looks like this was done to break projects using `setup.py install` https://github.com/readthedocs/readthedocs.org/issues/8659, I remember that we talked about doing something smarter if this was a problem in the future (checking if the project is using `setup.py install`, and only install that version for those projects, and install the latest version for all others). So, probably that day has arrived :D

As a workaround, you can install the required version of setuptools just before installing your requirements.

https://github.com/quaquel/EMAworkbench/blob/1a3c678125415eea6f15bc27eec3bf9475033a08/.readthedocs.yaml#L24-L26

```yaml
python:
  install:
    - requirements: docs/setuptools.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
```
