### ISSUE TITLE
Can't import GitHub project into RTD

### ISSUE THREAD

**Issue by cjdb** [readthedocs/readthedocs.org#10266]
## Details

When I attempt to import https://github.com/cjdb/project_template, I get `Invalid project name, a project already exists with that name`. All of the fields in the import step were autopopulated by the import wizard.

* Read the Docs username (if applicable): https://readthedocs.org/profiles/cjdb/

## Expected Result

Since this project doesn't exist in RTD yet, I expect that it'd be imported without issue.

## Actual Result

![An image depicting my attempt to import, as described in the Details section of this bug report.](https://user-images.githubusercontent.com/8622748/233798836-7dc76035-81a9-4909-a7a2-028147045081.png)

**Comment by stsewd** [comment]
Hi, projects on RTD must have a unique identifier (slug), this is generated from the name of the project, in this case, the name `project-template` is already taken from another project (https://readthedocs.org/projects/project-template/). Please change the name of your project before hitting `next`.

**Comment by cjdb** [comment]
Thanks! I was under the impression that Read the Docs namespaced projects on a per-user basis similarly to GitHub, but it seems that I misremembered how the tutorial explained it.

Is there any appetite for namespacing?

**Comment by stsewd** [comment]
@cjdb not at the moment, this is since the identifier is used in the subdomain that the project is served from, e.g `docs.readthedocs.io` for the docs project.

**Comment by cjdb** [comment]
Thanks for taking the time to explain ☺
