### ISSUE TITLE
bump OpenSSL version to 1.1.1+

### ISSUE THREAD

**Issue by martino-vic** [readthedocs/readthedocs.org#10288]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/loanpy/
* Build URL (if applicable): https://readthedocs.org/projects/loanpy/builds/20373455/
* Read the Docs username: https://readthedocs.org/profiles/martino-vic/

## Expected Result

Wanted to build docs with Sphinx.

## Actual Result

`pip install sphinx` gets the newest version of [urllib3](https://github.com/urllib3), which requires `OpenSSL 1.1.1+` since a few days. However, the `ssl` module used in the Read the Docs build environment is compiled with an older version of OpenSSL (1.0.2n), which is not compatible with urllib3 v2.0. I can't see how to upgrade OpenSSL to 1.1.1+ through my .readthedocs.yml file. 

## Temporary solution

I have downgraded urllib3 to <2.0.0 in my requirements.txt but it would be great to be able to upgrade OpenSSL to version 1.1.1+ in the build environment.

## Related issue

https://github.com/urllib3/urllib3/issues/2168

**Comment by stsewd** [comment]
Hi, can you try with our newer docker images? See https://docs.readthedocs.io/en/stable/config-file/v2.html#build

Your project is using an old image https://github.com/LoanpyDataHub/loanpy/blob/9622090322138eaae895599b4fdb2625dbddb1ba/.readthedocs.yml#L11-L12

**Comment by martino-vic** [comment]
Perfect, worked like a charm. Thx. This is how my .readthedocs.yml file looks like now:

```
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.7"

sphinx:
  configuration: docs/conf.py
```
