### ISSUE TITLE
'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.

### ISSUE THREAD

**Issue by Dong237** [readthedocs/readthedocs.org#10286]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/rl4lms/
* Build URL (if applicable): https://readthedocs.org/projects/rl4lms/builds/20367540/
* Read the Docs username (if applicable): https://readthedocs.org/dashboard/

Dear all, I got the following error telling me about 'extras_require', which I don't understand what went wrong exactly. The building process was successful last week and nothing has been changed since then. Thanks a lot for any advice!

```
Collecting gym==0.21.0 (from rl4lms==0.2.2)
  Downloading gym-0.21.0.tar.gz (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 260.5 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by stsewd** [comment]
Hi, one of your dependencies isn't compatible with the latest version of setuptools (we are installing the latest version by default now). You can fix your build by explicitly installing a compatible version of setuptools, from https://github.com/openai/gym/issues/3176#issuecomment-1408598628, looks like that version is 65.5.0.


You can do this by changing your config file https://github.com/Dong237/RL4LMs/blob/f907aee6610963c05ec450c3e3b892f1277ac66f/.readthedocs.yaml#L15-L19 to:

```yaml
python:
  install:
    - requirements: setuptools.txt
    - method: pip
      path: .
    - requirements: requirements.txt
```

Wher setuptools.txt has `setuptools==65.5.0`

**Comment by Dong237** [comment]
Problem now solved, thank you so much!!

**Comment by FranciscoRSilva** [comment]
> Problem now solved, thank you so much!!

How ?

**Comment by Dong237** [comment]
> > Problem now solved, thank you so much!!
> 
> How ?

Hi I just added setuptools.txt to the root directory containing ``setuptools==65.5.0``, and also add it to .readthedocs.yaml file as suggested above. Then it worked.
