### ISSUE TITLE
Can not execute setup.py since setuptools is not available in the build environment

### ISSUE THREAD

**Issue by hcho3** [readthedocs/readthedocs.org#10285]
## Details

One of the dependencies in my `doc/requirements.txt` is failing to install with error
```
Collecting pyspark (from -r doc/requirements.txt (line 13))
  Downloading pyspark-3.4.0.tar.gz (310.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 310.8/310.8 MB 174.2 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.
      [end of output]
```
The same configuration used to work until yesterday. Can someone help? Any pointer will be appreciated.

The dependency (`pyspark`) uses `setup.py`, so `setuptools` is required.

* Read the Docs project URL: https://readthedocs.org/projects/xgboost/
* Build URL (if applicable): https://readthedocs.org/projects/xgboost/builds/20365200/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/chohyu01/

## Expected Result

The build should be able to install dependencies successfully.

## Actual Result

One dependency, `pyspark`, fails to install due to setuptools not available.

**Comment by stsewd** [comment]
Hi, I can see in your build that we are installing the latest version of setuptools and then installing an old version, https://github.com/readthedocs/readthedocs.org/pull/10287 should fix this.

**Comment by hcho3** [comment]
@stsewd Thank you!

**Comment by jdkent** [comment]
Thanks for the fix @stsewd! What's the typical release cycle for bug fixes like this?

if it's the next day or so, I can hold off merging some pull requests that depend on documentation being built, if it's a week or so out, I'll work out a temporary solution to check if documentation builds successfully.

Thank you.

**Comment by stsewd** [comment]
@jdkent @hcho3 this fix has been released.

Your build is passing now https://readthedocs.org/projects/xgboost/builds/20575157/
