### ISSUE TITLE
Github actions have start failing due to OpenSSL version

### ISSUE THREAD

**Issue by jparisu** [readthedocs/readthedocs.org#10296]
## Details

* Read the Docs project URL: [https://readthedocs.org/projects/{your_project_slug}/](https://readthedocs.org/projects/fast-dds-spy/)
* Build URL (if applicable): [https://readthedocs.org/projects/{your_project_slug}/builds/{build_id}/](https://readthedocs.org/projects/fast-dds-spy/builds/20420633/)

## Expected Result

We have several github repositories that contain a documentation package that using sphinx upload the documentation in ReadTheDocs.
This adds a new action `docs/readthedocs.org:fast-dds-spy ` with each new PR added.

## Actual Result

Since yesterday, all these repositories CIs have started to fail.
The error message is as follows:
`ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with OpenSSL 1.0.2n  7 Dec 2017. See: https://github.com/urllib3/urllib3/issues/2168`

I do not know if there is something we could change, as I do not know where this action runs or where dependencies are set.

These are other built that have failed:
- https://readthedocs.org/projects/dds-recorder/builds/20425761/
- https://readthedocs.org/projects/aml-ip/builds/20421920/

**Comment by stsewd** [comment]
Hi, please see https://github.com/readthedocs/readthedocs.org/issues/10290.

**Comment by jparisu** [comment]
Yes, the fix explained in https://github.com/readthedocs/readthedocs.org/issues/10290 fix the issue.
Thanks
