### ISSUE TITLE
Build (Sphinx): don't override html_context by default

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#10293]
Currently, we have this under a feature flag, but I think this should be the expected behavior.

ref https://github.com/readthedocs/readthedocs.org/issues/10057

**Comment by humitos** [comment]
Do you have any concerns about enabling the feature flag for everybody? Are you thinking about some use cases that are gonna break?

**Comment by stsewd** [comment]
Not really, but this could break some projects if users have some invalid values set and were relying on rtd to "fix" them, but that's the same result they would get if they build their docs locally.

**Comment by humitos** [comment]
Gotcha. In that case, I'm 👍🏼 on moving forward with this. I'll add it to the roadmap so we can prioritize it.
