### ISSUE TITLE
API with autodoc not shown, but passes build

### ISSUE THREAD

**Issue by temuller** [readthedocs/readthedocs.org#10306]
## Details

I am trying to show the API of my code with autodoc, but it is not shown online. When I build it locally, it is shown. The build passes both locally and on readthedocs, but the API is still not shown. I might be missing something in my `.readthedocs.yaml` file

* Read the Docs project URL: https://readthedocs.org/projects/hostphot/
* Build URL (if applicable): https://readthedocs.org/projects/hostphot/builds/20534677/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/temuller/

## Expected Result

To show the API of my code online on RTD.

## Actual Result

API not shown

**Comment by stsewd** [comment]
Hi, you can expand the logs in the build page by clicking on the steps, you'll see these warnings

> WARNING: autodoc: failed to import module 'coadd' from module 'hostphot'; the following exception was raised:
No module named 'numpy'

This is usually because you are not installing the same dependencies that you have locally.

**Comment by temuller** [comment]
Thanks! All I had to do was to add the `requirements.txt` file for my package :)
