### ISSUE TITLE
Logo no longer displays above left nav bar after hotfix described in #10290

### ISSUE THREAD

**Issue by yantosca** [readthedocs/readthedocs.org#10317]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/gchp/
* Build URL (if applicable): https://readthedocs.org/projects/gchp/builds/20600606/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/ryantosca/

## Expected Result

The [stable build of gchp.readthedocs.io (20600175)](https://readthedocs.org/projects/gchp/builds/20600175/) looks like the image below. Note the GCHP home link and GEOS-Chem logo above the left nav bar.

![stable](https://github.com/readthedocs/readthedocs.org/assets/5880296/4e8096f4-ea93-4b5e-a5fb-6d7a8783a5f6)

## Actual Result

After the update described in #10290, the GEOS-Chem logo [disappears in the latest build of gchp.readthedocs.io (20600606)](https://readthedocs.org/projects/gchp/builds/20600606/):

![latest](https://github.com/readthedocs/readthedocs.org/assets/5880296/64046e95-04c4-46e3-b51f-a219622bcdbc)

## Configuration files:

Here are the configuration files for the build.  Note that I use a couple of CSS files to place both the icon and the top link above the left nav bar.  

Also note: Before the hotfix in #10290, I have never used a `.readthedocs.yaml`.  I added the one below according to the instructions but it does not prevent the logo from disappearing.  

- [.readthedocs.yaml.](https://github.com/readthedocs/readthedocs.org/files/11454264/readthedocs.yaml.txt)
- [docs/requirements.txt](https://github.com/readthedocs/readthedocs.org/files/11454270/requirements.txt)
- [docs/source/conf.py](https://github.com/readthedocs/readthedocs.org/files/11454261/conf.py.txt)
- [docs/source/_static/css/icon_home.css](https://github.com/readthedocs/readthedocs.org/files/11454274/icon_home.css.txt)
- [docs/source/geos-chem-shared-docs/_static/theme_overrides.css](https://github.com/readthedocs/readthedocs.org/files/11454279/theme_overrides.css.txt)

**Comment by yantosca** [comment]
Also we are using older versions of sphinx and the RTD theme that have been proven to work together.  I am reluctant to change those.

**Comment by yantosca** [comment]
The same issue also happens with https://hemco.readthedocs.io:

- Latest: https://hemco.readthedocs.io/en/latest/  (logo disappears), [build 20603683](https://readthedocs.org/projects/hemco/builds/20603683/)

- Stable: https://hemco.readthedocs.io/en/stable/ (logo present), [build 19655277](https://readthedocs.org/projects/hemco/builds/19655277/)

**Comment by yantosca** [comment]
Also, I should mention that I was able to build the documentation locally on a linux laptop with `sphinx-autobuild` and the logo did not disappear.  It would seem that there is something going on in the new ubuntu-22.04 container.  If this piece of info helps...

**Comment by humitos** [comment]
Hi @yantosca. Can you double check you are using the exact same versions of Sphinx and theme in your local installation than on Read the Docs?

**Comment by yantosca** [comment]
Thanks for getting back to me @humitos.  I am indeed using the same sphinx and rtd theme locally as on ReadTheDocs.  See:

The full environment is:
[env.txt](https://github.com/readthedocs/readthedocs.org/files/11488124/env.txt)

```console
docutils                  0.16                     pypi_0    pypi
pybtex                    0.24.0                   pypi_0    pypi
pybtex-docutils           1.0.2                    pypi_0    pypi
recommonmark              0.7.1                    pypi_0    pypi
sphinx                    3.5.4                    pypi_0    pypi
sphinx-autoapi            1.9.0                    pypi_0    pypi
sphinx-autobuild          2021.3.14                pypi_0    pypi
sphinx-fortran            1.1.1                    pypi_0    pypi
sphinx-rtd-theme          0.5.2                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.4                    pypi_0    pypi
sphinxcontrib-bibtex      2.2.0                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.1                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
```

My requirements.txt for ReadTheDocs is:
```console
sphinx==3.5.4
sphinx_rtd_theme==0.5.2
sphinxcontrib-bibtex==2.2.0
recommonmark
docutils==0.16
jinja2==3.0.3
```
Is there a way to see the full environment on the ReadTheDocs builds?  I am requesting the same sphinx and RTD theme but maybe there is a different version in one of the dependencies.

**Comment by yantosca** [comment]
@humitos: I think there is still an issue going on with the `html_css_files`.  I just noticed that some of the files in the the `geos-chem-shared_docs/_static` path are not rendering.  This is imported as a Git submodule.  Is it possible to make sure that Git submodules are initialized during the clone commands (i.e. `git clone --recurse-submodules`)?

**Comment by yantosca** [comment]
@humitos: Further update.  I am sure the git submodule update is not being done and adding it will fix this issue.  I noticed in the [build 20600175](https://readthedocs.org/projects/gchp/builds/20600175/) referenced above there are these commands:
```console
git submodule sync
git submodule update --init --force --recursive src/MAPL src/GMAO_Shared ESMA_cmake src/gFTL-shared src/FMS src/GCHP_GridComp/FVdycoreCubed_GridComp src/GCHP_GridComp/GEOSChem_GridComp/geos-chem src/GCHP_GridComp/HEMCO_GridComp/HEMCO src/yaFyaml src/pFlogger docs/source/geos-chem-shared-docs
```
But in [build 20600606](https://readthedocs.org/projects/gchp/builds/20600606/), which is done in the ubuntu-22.04, these commands are not present.

Would it be possible to restore the `git submodule update` commands?  The reason we keep documentation in a submodule is that there are some pages with common content that get included into multiple guides on RTD, so we keep them in a single place.

**Comment by humitos** [comment]
> This is imported as a Git submodule. Is it possible to make sure that Git submodules are initialized during the clone commands (i.e. `git clone --recurse-submodules`)?

Are you using this config in your YAML file, https://docs.readthedocs.io/en/stable/config-file/v2.html#submodules?

**Comment by yantosca** [comment]
That fixes it!  Thanks @humitos.  Sorry, I the documentation in the hotfix for #10290 didn't mention submodules so I didn't think of looking at that.  Closing out now.
