### ISSUE TITLE
GitHub login picks up the wrong email when verifying asking to verify the account

### ISSUE THREAD

**Issue by mcapuccini** [readthedocs/readthedocs.org#10310]
## Details
I am trying to login into my RTD account after a long time. The GitHub login asks to verify my email but somehow a very old email is used for verification. I have changed by email in GitHub but it is not picked up by RTD and the old email is used instead.

## Expected Result
RTD should do verification using the current GitHub email.

## Actual Result
A very old email is used instead.

**Comment by stsewd** [comment]
Hi, this is because you need to manually change your email once you are logged in, if you don't have access to your old email, I can manually mark it as verified, so you can log in and change your email. If so, please contact us via email with your account information (support@readthedocs.org)

**Comment by stsewd** [comment]
This is being handled via email.
