### ISSUE TITLE
Support request: django-social-auth marked as spam

### ISSUE THREAD

**Issue by gepolis** [readthedocs/readthedocs.org#10315]
Read the Docs project URL: https://django-social-auth.readthedocs.io/en/latest/
Build URL (if applicable):
Read the Docs username (if applicable): gepolis

**Comment by benjaoming** [comment]
Hi @gepolis - thanks for filling this in.

Given that the URL is referenced from https://github.com/omab/django-social-auth, that could be a good idea.

But note that django-social-auth is deprecated years ago. It suggests to use https://github.com/omab/python-social-auth instead.

**Comment by benjaoming** [comment]
Hi @gepolis - unfortunately, what might have happened here is that the original project deleted its documentation and then got squatted by a spammer.

If you want to view the documentation, I suggest browsing it on GitHub or building it locally: https://github.com/omab/django-social-auth/tree/master/doc
