### ISSUE TITLE
autodoc_mock_imports not work

### ISSUE THREAD

**Issue by SimFG** [readthedocs/readthedocs.org#10322]
## Details

* Read the Docs project URL: https://gptcache.readthedocs.io/en/dev/
* Build URL (if applicable): https://readthedocs.org/projects/gptcache/builds/20725251/

## Expected Result

success to build the doc

## Actual Result

fail to build the doc, because the `httpx` link is wrongly checked.
![image](https://github.com/readthedocs/readthedocs.org/assets/21985684/2037dd19-2ff3-4dfc-90ac-fbc027eb2bf0)
When i remove the `httpx` dependency lib, it will work well.
I try to add the `autodoc_mock_imports = ["httpx"]` config, but it can't ignore the import

**Comment by stsewd** [comment]
Hi, this looks like a problem with your project, and not with RTD, you should be able to replicate that same error locally. I'd recommend you check from where that error is coming and fix it.

Looks like it's coming from somewhere in https://github.com/pydata/pydata-sphinx-theme/blob/main/src/pydata_sphinx_theme/short_link.py, and probably reading a value from your config or source files.
