### ISSUE TITLE
latexmk error on build

### ISSUE THREAD

**Issue by tomkralidis** [readthedocs/readthedocs.org#10328]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pygeoapi
* Build URL (if applicable): https://readthedocs.org/projects/pygeoapi/builds/20747902/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/tomkralidis/

## Expected Result

Expecting the build to complete successfully.

## Actual Result

There seems to be an error when the build runs:
```bash
 latexmk -r latexmkrc -pdf -f -dvi- -ps- -jobname=pygeoapi -interaction=nonstopmode 
```

with the following error:

```
[9] [10Error: /syntaxerror in /----nostringval----
Operand stack:

Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   2045   1   3   %oparray_pop   2044   1   3   %oparray_pop   2025   1   3   %oparray_pop   1884   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push
Dictionary stack:
   --dict:977/1684(ro)(G)--   --dict:0/20(G)--   --dict:77/200(L)--
Current allocation mode is local
GPL Ghostscript 9.26: Unrecoverable error, exit code 1

xdvipdfmx:fatal: pdf_ref_obj(): passed invalid object.
```

I disabled PDF output in my project setup, but above continues to break my build.

**Comment by stsewd** [comment]
Hi, this is because you have 2 rtd configuration files

- https://github.com/geopython/pygeoapi/blob/0.15.0/readthedocs.yml
- https://github.com/geopython/pygeoapi/blob/0.15.0/.readthedocs.yaml

The first one has all formats enabled and is taking priority.
