### ISSUE TITLE
Proxito: 404 page search box should hide search scope

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#10339]
As mentioned by @humitos, the way we add the search scope in the search field isn't very easy for the user to understand (see screenshot).

Here are some ways to work around it:

1. Easiest: Add a simple help text to show the user what `project:<slug>` means.

2. A bit less easy: Hide this input and inject automatically via JS event `onsubmit`. We would expect the user to want to search only on the project where the 404 occurred, so removing the choice seems fine.

3. Hardest, perhaps best? Add a checkbox "Search only in this project" and have it display on all project-related 404s. Either the checkbox will make JS inject `project:<slug>` in the search field or we expand search result pages to understand additional input fields (`name="project" value="slug"`).

![image](https://github.com/readthedocs/readthedocs.org/assets/374612/a0b6e063-4d2b-4e26-a00d-74a11b9340c5)

**Comment by humitos** [comment]
We are re-designing all these pages in the new dashboard, so I think this issue can be closed. cc @agjohnson
