### ISSUE TITLE
RTD latest build fails with cryptic error

### ISSUE THREAD

**Issue by pllim** [readthedocs/readthedocs.org#10343]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/astropy/
* Build URL (if applicable): https://readthedocs.org/projects/astropy/builds/20793386/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/pllim/

## Expected Result

Build to succeed. Or if it fails for a real reason, I want to see the usual traceback or warning list.

## Actual Result

"There was a problem with Read the Docs while building your documentation. Please try again later." and no useful info in the raw log.

**Comment by pllim** [comment]
I think it went away.

**Comment by humitos** [comment]
Hi! You probably hit an issue we had during deploy. It lasted about 30m
