### ISSUE TITLE
Projects: project creation form configuration file example/templates

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#10352]
This is the third step we described in #10342

In this step, we will start to add UI to our project creation pages and show the user example/template configuration files for their project. This will have it's own set of phases, but to start we are only talking about a fairly minimal UI:

- Project creation form wizard gets a new step that just shows the user an example configuration file to add
  - Show a template that works for most projects
  - Maybe a second/fallback example option that replicates the _current_ defaults that we're deprecating?
  - Our documentation probably shows these same examples as well

Eventually, the later versions of this might be a little smarter, but that doesn't need to hold up design at this phase. We'll want to get this feature in front of user first. Some additions we're pushing off until later:

- Granular configuration file examples for alternative build tools
  - We'd have a selection field with "Sphinx", "Mkdocs", etc. "Docusaurus" shows an example of using Docusaurus with our config file. This would be more direct marketing of build jobs/commands and custom doc tooling.
- Detection of a missing configuration file without building
  - We'd need a secondary task for this, to avoid triggering and failing a build.
  - For now, okay to guide the user with steps and a failing first build might be common. This might be the case even if we check for a file existing though

**Comment by humitos** [comment]
This could be slightly related to https://github.com/readthedocs/readthedocs.org/issues/11187 in some way.

**Comment by ericholscher** [comment]
Goal here is to do this after improving our docs for other tool support.

**Comment by agjohnson** [comment]
For the initial pass here, we can add to the list of `Example configuration for` dropdown with basic examples -- anything that requires just our configurartion file.

The next phase of this would be to link out to documentation pages for complex examples -- anything that requires additional JS/template/etc changes. We need documentation pages for these however.

**Comment by humitos** [comment]
I jumped into this today and I found it requires https://github.com/readthedocs/ext-theme/issues/184 as well. The frontend is not prepared to add another config file example easily, unfortunately. I will jump there and see if I find an easy way to do this.

**Comment by agjohnson** [comment]
Ah I just reviewed your PR, I asked about this. I think it should be easy enough to trigger the tabs from the dropdown, and I'd like to retain the dropdown if possible. I'll poke this really quick, we can always revert to a dropdown later if it is complicated.

**Comment by agjohnson** [comment]
Actually, yeah, it was super simple.

[Screencast from 2024-06-06 14-33-51.webm](https://github.com/readthedocs/readthedocs.org/assets/1140183/8a21d743-2410-4c15-a05a-d49055437b5c)
