### ISSUE TITLE
Skipped PR build remains a pending check in GitHub UI

### ISSUE THREAD

**Issue by hugovk** [readthedocs/readthedocs.org#10364]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/cpython-previews/
* Build URL (if applicable): https://readthedocs.org/projects/cpython-previews/builds/20835824/
* PR URL: https://github.com/python/cpython/pull/104100

## Expected Result

When skipping the build with:

```sh
if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && [ "$(git diff --quiet origin/main -- Doc/ .readthedocs.yml; echo $?)" -eq 0 ];
then
  echo "No changes to Doc/ - exiting the build.";
  exit 183;
fi
```

It should either show the GitHub check as a grey skipped result (or possibly green success, but skip would be more accurate).

## Actual Result

The build was cancelled as expected:

<details>
<summary>Details</summary>

<img width="823" alt="image" src="https://github.com/python/cpython/assets/1324225/32644599-484c-4990-8bd3-1b1cdada9b82">

</details>

https://readthedocs.org/projects/cpython-previews/builds/20835824/

However, the status check on GitHub still shows as pending:

<details>
<summary>Details</summary>

<img width="918" alt="image" src="https://github.com/python/cpython/assets/1324225/32207784-fe96-4d9e-9c7b-906c08da92d7">

</details>

And also shows in the tab:

<details>
<summary>Details</summary>

<img width="368" alt="image" src="https://github.com/python/cpython/assets/1324225/3059d494-c66f-4aa6-bb60-bbfe124ec1ae">

**Comment by benjaoming** [comment]
Note: Also reported here - https://github.com/readthedocs/readthedocs.org/issues/10335

**Comment by benjaoming** [comment]
I needed to just understand this very very basic thing that had gotten lost somehow:

* If a build succeeds, we send back a URL to the Pull Request preview!
* If a build is skipped, we _also_ send back a "success" status. But that status should NOT contain the PR preview URL, since the build was skipped :upside_down_face: 

It could be proposed to clear the whole status (after all, a build never succeeded) - but I think it's nice to keep it, including a URL to the build. That way, it's explicit when a build was skipped. IMHO, we need a more integrated _skipping_ mechanism if we're gonna skip builds and delete the "pending" status.

**Comment by benjaoming** [comment]
Currently, this is a bit of a mystery since my changes here are skipped and "pending" is overwritten correctly with "success": https://github.com/readthedocs/test-builds/pull/2100

**Comment by benjaoming** [comment]
This just became very very interesting, as my local dev environment (without any changes to current behavior) was able to pass back a "success" status, but the production environment wasn't.

See: https://github.com/readthedocs/test-builds/pull/2101

![image](https://github.com/readthedocs/readthedocs.org/assets/374612/f5ce364d-59a4-47cb-82c3-fb0e6f1464d1)

**Comment by benjaoming** [comment]
There is definitely something weird about the difference between these two PRs:

First commit should not be skipped and has a "success", subsequent commits all get a success, even if they are skipped:
https://github.com/readthedocs/test-builds/pull/2100

The first commit should be skipped but gets stuck at "pending" and never receives "success":
https://github.com/readthedocs/test-builds/pull/2102

**Comment by benjaoming** [comment]
We found the issue :heavy_check_mark: 

https://github.com/readthedocs/readthedocs.org/blob/0957dacd8045b9d31a7676218948c5213eca3d23/readthedocs/builds/models.py#L379-L393

In this method, we return an absolute path for successful builds. But if the build isn't successful, we return a relative path. This is of course an invalid `target_url` for GitHub's API, so we need to prepend our `PRODUCTION_DOMAIN` in a solid fashion.

I'll create a PR, just need to check how this `get_absolute_url` is used to make sure we're not doing something in for instance email templates with a different assumption.

**Comment by benjaoming** [comment]
I'm still seeing issues here - for example https://github.com/readthedocs/readthedocs.org/pull/10393.

Will reopen and investigate...

**Comment by benjaoming** [comment]
It works => https://github.com/readthedocs/readthedocs.org/pull/10410

**Comment by benjaoming** [comment]
Hmm, 2 potential explanations:

1) Something about the command - but I guess you tested this one
2) I wonder if `origin/main` is from the external PR fork or `python/cpython`
