### ISSUE TITLE
Docs: Refactor "Importing your documentation"

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#10383]
Currently, [Importing your documentation](https://docs.readthedocs.io/en/stable/intro/import-guide.html) is nested in the Tutorials section.

But it's not really a tutorial.

The current content will mislead a user looking for an easy tutorial. For the fast reader, the page might also wrongly convey only the manual method since the automatic method is easy to miss.

I would propose:

1) Create a how-to from the manual parts: "How to import a Git repository manually" :heavy_check_mark: 
2) Create a feature reference about Automatic Import of Git repositories :heavy_check_mark: 
3) Update the current Getting Started tutorial with references to these.
4) Redirect the old page to the new feature reference

**Comment by benjaoming** [comment]
Update: The first 2 items are now satisfied by new pages that were added recently so this should be much easier to implement.

**Comment by humitos** [comment]
This seems done already. We are linking to the manual import guide from getting started now.
