### ISSUE TITLE
Deprecation: Disabled version of "Default settings" or other guidance?

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#10386]
Refs: https://github.com/readthedocs/readthedocs.org/issues/10342

I noticed in this draft PR that we are removing the "Default settings" fieldset entirely from Advanced Settings: https://github.com/readthedocs/readthedocs.org/pull/10367

If we do that, then users won't be able to tell what their previous configuration was. Since we still keep the database fields, we have two alternative options:

1) Disable these input fields so the values are still visible
2) Output their values in a table, given that the project still hasn't migrated to `.readthedocs.yaml`

The "use case" for this would be projects that haven't acted on the deprecation, presumably because they weren't building anything in the deprecation period and didn't find it necessary to migrate yet.

![image](https://github.com/readthedocs/readthedocs.org/assets/374612/955eab18-79ca-49b6-9258-a0ab23175c85)

**Comment by humitos** [comment]
We kept showing these values as read-only for a few months after the deprecation. Now, we have deleted them from the form and we are deleting them from the db as well in #11124. There is nothing else to do here now.
