### ISSUE TITLE
Project import: "Edit Advanced Options"

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#10392]
In #10356, we added a new step about the configuration file. It prompts the user to add a `.readthedocs.yaml` configuration file before continuing.

This means that "Edit Advanced Options" in the previous step is dangling a bit. I think that adding a configuration step takes the users focus away from their previous "Edit Advanced Options" choice.

![image](https://github.com/readthedocs/readthedocs.org/assets/374612/183a5183-3200-4aba-ab4a-09ddc994f014)

I think there are 2 possible choices here:

1) Move the checkbox option to the configuration step.

2) Remove it entirely :100: After adding a configuration file, the most important thing for all users is to see that a build is running and get a failure/warning when a .readthedocs.yaml wasn't found or is invalid. Also, the previous use case of visiting "Advanced Options" largely does the same as what the config file offers!

CC: @agjohnson @humitos 

Related: https://github.com/readthedocs/readthedocs.org/issues/10342

**Comment by humitos** [comment]
Note that the "Advanced options" are completely useless actually:

![Screenshot_2023-06-14_11-50-31](https://github.com/readthedocs/readthedocs.org/assets/244656/c9d9d7f1-8ddb-4ed4-a9b9-269aed554ee6)

I'd vote to completely remove this step and move the "language" field to the initial step, which is the only important one (tied to the URL of the project). Those other "Extra details" (as the title says), should be found by the user later, not at import time, IMO.

**Comment by benjaoming** [comment]
> I'd vote to completely remove this step and move the "language" field to the initial step

It's a great idea to let the user choose the language in the initial import step. Is the step you mean?

I :100: agree that we should completely remove the "Edit advanced project options" checkbox.
