### ISSUE TITLE
Support sustained environments without boilerplate

### ISSUE THREAD

**Issue by jaraco** [readthedocs/readthedocs.org#10401]
In https://github.com/readthedocs/readthedocs.org/issues/9623#issuecomment-1270423706, I laid out an experience I'd like to have, namely that a user of RTD should be able to build on RTD and have their builds track with the latest version of the OS and Python. Currently, every user needs to add four lines of boilerplate to their config just to get what I believe to be a reasonable default behavior. Also, due to #8861, the user must periodically update the OS, adding staleness and toil to every project.

I don't want reproducible builds. I want low-maintenance builds.

Would you consider making "os: latest" and "python: latest" the default or at least have that behavior be configurable through a single line of configuration and not four lines of boilerplate?

**Comment by ericholscher** [comment]
We've just shipped a version of this, so if you'd like to test it out, it should now be live. The version that `latest` will point to is the most recent in the docs: https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python

**Comment by jaraco** [comment]
Awesome. Thanks. I've confirmed in jaraco.develop. I've pushed https://github.com/jaraco/skeleton/commit/68ac292eb37ce92e992e6fab05a44ad86f32e8f1, so the change should roll out to derived projects in the coming weeks.
