### ISSUE TITLE
Feature flag: MkDocs use latest has its logic inverted

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#10402]
Take a look at this code, https://github.com/readthedocs/readthedocs.org/blob/bcf45cd666b75d63319bc0d0b6fa18fec24967dc/readthedocs/doc_builder/python_environments.py#L212-L216

It seems when `DEFAULT_TO_MKDOCS_0_17_3=False` and `USE_MKDOCS_LATEST=True`, we are installing `mkdocs<1.1` when we should be installing `mkdocs` (latest).

Reverting this logic is easy. However, we should take a look at our data in Metabase to know how many projects this will affect and decide what/how to do.

Related #9779

**Comment by humitos** [comment]
@ericholscher are we OK just inverting this logic or do we want to do something before making the change?

**Comment by ericholscher** [comment]
@humitos I'm 👍 on unbreaking mkdocs, so let's do it. Alternatively, we just remove the feature flag, if old projects were already upgraded?
