### ISSUE TITLE
Allow alternative configuration filename for "Path for .readthedocs.yaml"

### ISSUE THREAD

**Issue by mcarans** [readthedocs/readthedocs.org#10468]
## What's the problem this feature will solve?

The filename `.readthedocs.yaml` makes sense in the root, but when using the "Path for .readthedocs.yaml" experimental feature, it makes more sense to allow the filename to be different since the full path is supplied. (In my case I want to drop the prefixed "." and use this path `documentation/readthedocs.yaml`.

## Describe the solution you'd like

Allow any filename or at least allow dropping the prefixed "." when using "Path for .readthedocs.yaml"

**Comment by humitos** [comment]
Hi @mcarans. Thanks for opening this issue. We talked about this in the past and we decided to only support one filename to avoid confusions and reduce the complexity around the configuration file.

Can you expand on the benefits about using a different filename different than `.readthedocs.yaml`?

**Comment by mcarans** [comment]
@humitos There isn't any need for the configuration file to be a hidden file if it is in a subfolder like `documentation`.

**Comment by humitos** [comment]
We are not going to allow other filenames for now. I'm closing this issue but we can revisit in the future.
