### ISSUE TITLE
Root file index.rst not found

### ISSUE THREAD

**Issue by MartinBeseda** [readthedocs/readthedocs.org#10499]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/sa-oo-vqe-qiskit/
* Build URL (if applicable): https://readthedocs.org/projects/sa-oo-vqe-qiskit/builds/21151352/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/MartinBeseda/

For the last two days I'm obtaining a combination of three errors signifying, that I'm missing `autodoc` extension, as `automodule` directive is unknown - that's not true, the extension is being installed and used. Also, I'm getting the errors about non-existing Markdown and Jupyter files, which should be also OK, as I'm using both `myst_parser` and `nbsphinx` extensions. Finally, I'm obtaining also an error about `docs/index.rst` file not found, while the root file is in `docs/source/index.rst` and it's being used as that, as the previous errors stems from the files included in its toctree.

Maybe this is not a bug and I'm sorry in that case, but it seems as a really strange combination of problems, which make no sense to me.

## Expected Result
Successfully built documentation.

## Actual Result
Combination of three errors:
```
root file /home/docs/checkouts/readthedocs.org/user_builds/sa-oo-vqe-qiskit/checkouts/latest/docs/index.rst not found
```
```
/home/docs/checkouts/readthedocs.org/user_builds/sa-oo-vqe-qiskit/checkouts/latest/docs/source/index.rst:14: WARNING: toctree contains reference to nonexisting document 'source/install'
```
```
/home/docs/checkouts/readthedocs.org/user_builds/sa-oo-vqe-qiskit/checkouts/latest/docs/source/saoovqe.rst:10: ERROR: Unknown directive type "automodule".
```

**Comment by humitos** [comment]
Note that your `.readthedocs.yaml` says `sphinx.configuration: docs/conf.py` but your configuration file is at `docs/source/conf.py`. Please, try changing that and let me know if that solves the issue.
