### ISSUE TITLE
YAML config: errors are not clear enough for users

### ISSUE THREAD

**Issue by jnikula** [readthedocs/readthedocs.org#10502]
## Details

I configured `.readthedocs.yaml` with:

```
build:
  tools:
    python: 3.11
```

## Expected Result

Nothing unusual.

## Actual Result

I got the error message:

> Problem in your project's configuration. Invalid "build.tools.python":
> expected one of (2.7, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, pypy3.7, pypy3.8,
> pypy3.9, miniconda3-4.7, mambaforge-4.10, 3), got 3.11

Despite the confusing message "expected 3.11, got 3.11", I realized the latter was probably a float instead of a string.

The workaround was simple:

```
build:
  tools:
    python: "3.11"
```

But it can potentially be a huge time waster for someone not familiar with the pitfalls of yaml parsing. It would be nice if the parsing was more robust against this kind of type issues. Or the documentation explicitly told to use quotes.

Oh, Norway problem, you ask? See https://hitchdev.com/strictyaml/why/implicit-typing-removed/

**Comment by humitos** [comment]
Yes. We have to improve the error message we expose to users to be more friendly 😄 . We have a few issues about this already. This is the code where we should give the users more context about what has happened: https://github.com/readthedocs/readthedocs.org/blob/1b32d18231a28022caf3c7aeb605abd850780a7b/readthedocs/config/validation.py#L15-L28

**Comment by humitos** [comment]
We should make the error of using `pip.install.extra_requirements: [doc]` clearer. See https://github.com/readthedocs/readthedocs.org/issues/10717

**Comment by stsewd** [comment]
Another error is that when using node, we require users to specify a python version too.

**Comment by humitos** [comment]
Another related issue: https://github.com/readthedocs/readthedocs.org/issues/6569

**Comment by humitos** [comment]
... and another one: https://github.com/readthedocs/readthedocs.org/issues/7707

There are a bunch of issues related to this 😞 -- probably worth prioritizing this work.

**Comment by humitos** [comment]
... another https://github.com/readthedocs/readthedocs.org/issues/8482 ...

**Comment by humitos** [comment]
🙃 , https://github.com/readthedocs/readthedocs.org/issues/8352

**Comment by humitos** [comment]
hrm... https://github.com/readthedocs/readthedocs.org/issues/9458

**Comment by humitos** [comment]
wait, there are more issues https://github.com/readthedocs/readthedocs.org/issues/9713

**Comment by stsewd** [comment]
An error isn't clear when a user is using an old version of the config file (v1).

Ref https://github.com/readthedocs/readthedocs.org/issues/10824

**Comment by stsewd** [comment]
Looks like we lose the message about the validation of the version of the config file.

Example: https://github.com/readthedocs/test-builds/blob/config-file-with-wrong-version-number/.readthedocs.yaml#L1
Build: https://readthedocs.org/projects/test-builds/builds/23531844/

**Comment by stsewd** [comment]
Another one when the build option is missing https://github.com/pfusik/ONE/blob/55dc7c6e4d388a85c0deb49c8da40edbfdba72e7/.readthedocs.yml

**Comment by agjohnson** [comment]
These last two are a slightly different issue, and are a change/bug where project notifications are only visible for the maintainer users.

The beta instances doesn't have this change yet, the error is clearer there:
https://beta.readthedocs.org/projects/test-builds/builds/23531844/

**Comment by humitos** [comment]
> These last two are a slightly different issue, and are a change/bug where project notifications are only visible for the maintainer users.

I opened https://github.com/readthedocs/readthedocs.org/issues/11146 to track this issue.

**Comment by humitos** [comment]
We made our error messages a clearer. They are not perfect still, tho, but I'm tempted to close this issue at this point since there are no clear directions here and the issue from the description was already fixed. Besides, we have created an issue per problem for those that are more important. See the list at https://github.com/readthedocs/readthedocs.org/issues/10985#issuecomment-1886680779

**Comment by agjohnson** [comment]
Agreed. I feel like we've addressed a few issues here in a few ways. If there are any more issues with the configuration file, we will address this individually at this point.
