### ISSUE TITLE
Support for theme-centered analytics 

### ISSUE THREAD

**Issue by agriyakhetarpal** [readthedocs/readthedocs.org#10501]
## What's the problem this feature will solve?

It would be great if there was an option on the Read the Docs administrator dashboard to display theme-based metrics, such as

1. The percentage (or number) of users with a browser-specific preference, with `prefers-color-scheme` media features in CSS or similar
2. Tracking the number of users who switch to a light or dark theme upon loading the documentation
3. and so on

## Describe the solution you'd like

Another, downloadable `.CSV` file similar to the traffic and search analytics files containing the aforementioned information, or making it displayable on the dashboard

## Alternative solutions

N/A

## Additional context

I feel this would be particularly helpful in various areas: to identify website accessibility concerns with Sphinx or MkDocs themes (improper colour contrast ratios, font sizes, conformance with WCAG 2.X, et cetera), to provide developers with the ability to prefer certain themes and light/dark modes for their API documentation based on the preferences of their users, and to understand internet demographics in general

**Comment by stsewd** [comment]
Hi there, our analytics solution is really basic, and don't think we will spend more time adding more features there, instead I'd recommend looking into services like Google Analytics or Plausible.
