### ISSUE TITLE
API: allow remote repo full name query

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#10513]
The new dashboard is still using the API v2 remote repo API, which does not allow for expansion on project results and doesn't have all of the fields that I'd like to use in the results listing. The API v3 needs the v2 API implementation for searching by full_name, the current pattern for searching `full_name` by icontains on the v2 API works okay for now.

I didn't want to alter the v2 API further, as we should really be moving towards the v3 API, but if it's just easier to add expansion there for some reason, that is also fine.

Note: this also gives expansion on the nested projects in the result, so we can get fields like the avatar_url, etc. The current v2 search only returns the project slug and a link to the project dashboard.

**Comment by humitos** [comment]
I created the #10551 for this, but I wanted to note here that we already had a filter called `name=`. The difference between `full_name=` and `name=` is that full name includes the name of the username/organization the repository belongs to.
