### ISSUE TITLE
Proxito 404: check for files in the DB instead of storage

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#10512]
## What's the problem this feature will solve?

Our 404 handler is slooooow, this is mainly because we hit our storage to check if a file exists,
in the worst case, we will do 6 calls to storage.

## Describe the solution you'd like

Instead of relying on calls to storage to check if a given file exists, we can use our DB for that. How's that? Well, as part of our build process, we create an HTMLFile object for each HTML file found in the user docs.

https://github.com/readthedocs/readthedocs.org/blob/f7d390cbb7b2d5838ece80d363c155895012c64c/readthedocs/projects/tasks/search.py#L138-L147

So we already keep track of every HTML file. This table is BIG, so we may want to first try to trim it a little, I don't think we need to keep track of every HTML file, we just need to track index.html/README.html and 404.html files.

What about search?
We rely heavily on the HTMLFile model for search, but I think we can do just fine without it. When indexing, we can just walk the storage as we do when creating the HTML files

https://github.com/readthedocs/readthedocs.org/blob/f7d390cbb7b2d5838ece80d363c155895012c64c/readthedocs/projects/tasks/search.py#L107-L110

And we can get the search ignore/ranking patterns from the config of the build object attached to the version.

https://github.com/readthedocs/readthedocs.org/blob/84f889a0e1a8a352d84a188749266fc262298471/readthedocs/builds/models.py#L310-L327

If we want, we can also skip that work and just hit that table as is right now.

## Additional context

A little related to https://github.com/readthedocs/readthedocs.org/issues/10061, where I talk about not hitting our application twice for 404s that aren't from the storage.

**Comment by humitos** [comment]
> So we already keep track of every HTML file. This table is BIG, so we may want to first try to trim it a little, I don't think we need to keep track of every HTML file, we just need to track index.html/README.html and 404.html files.

I understand that we don't need files like `tutorial/builds/customize-your-builds.html` because if the user hits that URL and it doesn't exist, we don't have to do anything, right? I mean, we only need to do the 404 handler when the URL ends with a trailing slash (e.g. `tutorial/builds/customize-your-builds/`)

If I'm correct here, I think it's a great idea what you are proposing.

By the way, we are getting rid of `README.html` feature in the near future I guess: https://github.com/readthedocs/readthedocs.org/issues/9993 (also related https://github.com/readthedocs/readthedocs.org/issues/1800)

> We rely heavily on the HTMLFile model for search, but I think we can do just fine without it. When indexing, we can just walk the storage as we do when creating the HTML files
>
> And we can get the search ignore/ranking patterns from the config of the build object attached to the version.

This also looks like a good idea to me. It simplifies the code and make everything more standardized, in my opinion.

**Comment by stsewd** [comment]
> I understand that we don't need files like tutorial/builds/customize-your-builds.html because if the user hits that URL and it doesn't exist, we don't have to do anything, right? 

yeah, we don't need to know if those files exist, it we are in the 404 handler, it means it wasn't found in storage.

**Comment by ericholscher** [comment]
We talked about this in a call, and we're 👍 on moving forward. Big wins:

* Reduce N queries to storage to 1 query to DB
* Better response times on 404s for users
* Reduce size of DB tables on search (ImportedFile is our biggest table currently)

**Comment by stsewd** [comment]
So, now one question, what do we want to do first?

- Replace storage calls with one DB call
- Reduce the table size

**Comment by ericholscher** [comment]
@stsewd I think the DB call work seems useful to start with.
