### ISSUE TITLE
Build error with build id #21180461

### ISSUE THREAD

**Issue by sblunt** [readthedocs/readthedocs.org#10511]
## Details:

* Project URL: https://readthedocs.org/projects/orbitize/
* Build URL(if applicable): https://readthedocs.org/projects/orbitize/builds/21180461/
* Read the Docs username(if applicable): sblunt

## Expected Result

Build successfully completed

## Actual Result

My last few readthedocs builds on the main branch of my repo have failed, even though pull request builds are passing and there don't seem to be issues with the builds themselves, as far as I can tell.

**Comment by stsewd** [comment]
Hi, looks like the container gets killed by time out or excessive memory consumption, your build took more than 45 minutes to run.

**Comment by sblunt** [comment]
Got it, thanks!

**Comment by sblunt** [comment]
Hi guys, I think this may be a similar issue, but my latest build (https://readthedocs.org/projects/orbitize/builds/23069134/) appears to complete after about 37 mins (according to the logs), but then keeps running until 45 mins and times out. Do you know what might be going wrong?

**Comment by humitos** [comment]
On Read the Docs Community we support builds to be ran up to 30 minutes (see https://docs.readthedocs.io/en/stable/builds.html). Builds taking more time than that will have unexpected behavior.

It seems your build takes around one hour. I recommend you to work in your Sphinx project to try reducing the amount of time it takes to build, by optimizing the process.
