### ISSUE TITLE
Autosummary fails, but only on RTD (works fine locally)

### ISSUE THREAD

**Issue by nchopin** [readthedocs/readthedocs.org#10527]
## Details

Hi, 
I host on RTD the documentation of the following python package:
https://github.com/nchopin/particles

See here: https://particles-sequential-monte-carlo-in-python.readthedocs.io/en/latest/

Everything was working nicely until a few months ago, when the links generated by autosummary stopped working. 

I manage to compile the doc locally with sphinx, without any issue. On RTD, I can see in the logs hundreds of messages that start with "WARNING: [autosummary] failed to import..." but all these modules do exist. 

This issue looks similar to  #4446, so I thought something was missing in my requirements.txt ? 
If this is the case, I can't find the missing requirement. I created a new conda environment on my machine from requirements.txt on my machine, and again I managed to buid the html website without issues (autosummary or otherwise). 

Any help greatly appreciated. 

* Read the Docs project URL: https://readthedocs.org/projects/particles-sequential-monte-carlo-in-python/
* Build URL (if applicable): https://readthedocs.org/projects/{your_project_slug}/builds/{build_id}/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/n_chopin

## Expected Result

Links generated by autosummary work. 

## Actual Result

See for instance here:
https://particles-sequential-monte-carlo-in-python.readthedocs.io/en/latest/resampling.html

This page is supposed to describe module "resampling", but its docstring is not included, and the links to the different functions are dead.

**Comment by humitos** [comment]
Hi @nchopin! It seems that Sphinx is showing some output saying that it's not able to find the module you want to document:

```
WARNING: [autosummary] failed to import 'particles.binary_smc.BIC': no module named particles.binary_smc.BIC
```

_(from https://readthedocs.org/projects/particles-sequential-monte-carlo-in-python/builds/21267623/)_

Make sure you are installing all the required dependencies on the Read the Docs environment to build your documentation.

**Comment by nchopin** [comment]
I am sorry, but I don't understand: this particular msg (and all the similar messages) mention classes / modules in **my** library, they are not part of some other library which would be omitted in the requirements.txt ?

**Comment by nchopin** [comment]
To put it in another way: if indeed the problem comes from missing dependencies, how can I find what are those missing dependencies? Again, things work fine locally, even in a conda environment generated from my requirements.txt.

**Comment by humitos** [comment]
So, you need to install your own library in the Read the Docs environment using `python.install`: https://docs.readthedocs.io/en/stable/config-file/v2.html#python

**Comment by nchopin** [comment]
Sorry, I feel really dumb, but what is this "Read the Docs environment" you are talking about? Is it a conda environment I must create locally? Is it defined somewhere on-line? 
I tried to find any mention of a  "Read the Docs environment" in the RTD documentation, but to no avail. I also googled it...
Sorry again, I'm really at my wits' ends.

**Comment by nchopin** [comment]
Yes, it works now, with the help of @armavica. If I understand correctly(?), the issue was that RTD was not installing my package, because the `readthedocs.yaml` file was missing this bit: 
 ```
python:
  install:
    - method: pip
      path: .
```

If I may, the docs are not super clear about this. For instance, on this page:
https://docs.readthedocs.io/en/stable/config-file/v2.html
you have a default template where the options are missing (not even commented out),
although that's something many projects would need?
