### ISSUE TITLE
Usin MKDocs Material theme with i18n plugin for localization differs from local build

### ISSUE THREAD

**Issue by MetalKnight56** [readthedocs/readthedocs.org#10537]
## Details

* Read the Docs project URL: https://epicfight-docs.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/epicfight-docs/builds/21281198/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/Gui_/

## Expected Result

Wiki should be following what i have on my end, considering i have all the requirements and parameters correct and they all work great, but when i execute the build on ReadTheDocs everything gets messed up, huge icons text all around where it shouldn't be and i'm guessing that's due to me using Material Theme with a localization plugin, but i don't understand why read the docs is having trouble pip intsalling these two as i've correctly requested it to do so.

Here's how it shoud look like:
![Screenshot 2023-07-12 043149](https://github.com/readthedocs/readthedocs.org/assets/77132244/990d01bc-5738-4ec5-93e9-a2067272e2b7)
As you can see everything works just fine. And i have this setup on my mkdocs .yml and .readthedocs.yaml:
![image](https://github.com/readthedocs/readthedocs.org/assets/77132244/36a265f0-b0b9-48c9-b360-1d1e1fd1965f)
![image](https://github.com/readthedocs/readthedocs.org/assets/77132244/5065ea67-ce2e-4ceb-b42f-98094744d67c)

Inside my requirements.txt i have the following:
![image](https://github.com/readthedocs/readthedocs.org/assets/77132244/1840020c-6bc1-4ef1-99ef-cd57ccb076e9)

## Actual Result
The actual result inside ReadTheDocs outputs this: 
![image](https://github.com/readthedocs/readthedocs.org/assets/77132244/9a8762bb-1401-4f50-a087-d71df0a2e0fc)
![image](https://github.com/readthedocs/readthedocs.org/assets/77132244/cc0f1e60-4bd4-4df2-a0f0-6d73e66a881a)
![image](https://github.com/readthedocs/readthedocs.org/assets/77132244/260a7d73-3eee-4c6c-909c-de160e9f024a)

As you can see, huge logos and all the files i have are located at the end of the wiki, and they are all messed up.

**Comment by MetalKnight56** [comment]
You can check how it looks on the actual wiki too: https://epicfight-docs.readthedocs.io/en/latest/
I would appreciatte any efforts to help me on this because i have no idea what's causing this.

Here's the docs repo too: https://github.com/MetalKnight56/EpicFight-Docs

**Comment by humitos** [comment]
It seems you already solve your issue by yourself. I can see the page correctly at https://epicfight-docs.readthedocs.io/en/latest/. Feel free to re-open if this is not solved.
