### ISSUE TITLE
Keep getting emails after adding .readthedocs.yaml

### ISSUE THREAD

**Issue by aragilar** [readthedocs/readthedocs.org#10533]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/scikits-odes/
* Build URL (if applicable): https://readthedocs.org/projects/scikits-odes/builds/{build_id}/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/aragilar/

## Expected Result

After I added the .readthedocs.yaml configuration, I would stop being emailed about the .readthedocs.yaml file.

## Actual Result

I keep getting emails about adding a .readthedocs.yaml file, and warnings when I log in. It's unclear what else I'm supposed to do?

**Comment by humitos** [comment]
Hi! The logic that sends the email checks for a YAML file used in the default version defined for your project. It seems your default version is `stable`, which was built 6 months ago and it didn't have a YAML file: https://readthedocs.org/projects/scikits-odes/builds/19158395/

If you build the version `stable` with a YAML file, you won't receive further emails about that project anymore.
