### ISSUE TITLE
Get error 'Build output directory for format "pdf" contains multiple files and it is not currently supported.'

### ISSUE THREAD

**Issue by ragger65** [readthedocs/readthedocs.org#10541]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/sicopolis/
* Build URL: https://readthedocs.org/projects/sicopolis/builds/21297116/
* Read the Docs username: https://readthedocs.org/profiles/ragger65/

## Expected Result

A new version of the user manual for the ice-sheet model SICOPOLIS (https://sicopolis.readthedocs.io/en/latest/) should have been built after a commit/push to the GitLab repository.

## Actual Result

The manual is still at the previous revision 35296849. The following error message appeared.

```
Build #21297116
[develop](https://readthedocs.org/dashboard/sicopolis/version/develop/edit/) (9d51c5418b348b75666d42e3c9f2bd5fd56997e7)
Build failed
Error

Build output directory for format "pdf" contains multiple files and it is not currently supported.
Please, remove all the files but the "pdf" you want to upload.
```

By contrast, the local build on my Linux workstation works perfectly.

**Comment by ragger65** [comment]
Disabling PDF format in the config file .readthedocs.yml circumvents the problem; the HTML manual then builds successfully. But I'd prefer a real fix that allows building also the PDF manual.

**Comment by humitos** [comment]
(from the 📱)

It seems the latexmk command to build your PDF file is failing:

```
!  ==> Fatal error occurred, no output PDF file produced!
```

Because of that, there is no PDF file generated. If you fix the problem, the PDF will be automatically uploaded to Read the Docs.

Are you able to generate the PDF locally? Does it look good?

**Comment by ragger65** [comment]
I have never tried to build the PDF locally. How can I do that?
