### ISSUE TITLE
How to authenticate to GEE in the RDT environment ? 

### ISSUE THREAD

**Issue by 12rambau** [readthedocs/readthedocs.org#10553]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pygaul/
* Build URL (if applicable): https://readthedocs.org/projects/pygaul/builds/21366947/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/borntobealive/

## Expected Result

To run some cells in my documentation I need to authenticate to GEE in the RDT build envirmonement. To do so I added some extra logic in my conf.py:   
  
```python
# conf.py
# -- Script to authenticate to Earthengine using a token -----------------------
def gee_configure() -> None:
    """Initialize earth engine according to the environment.

    It will use the creddential file if the EARTHENGINE_TOKEN env variable exist.
    Otherwise it use the simple Initialize command (asking the user to register if necessary).
    """
    # only do the initialization if the credential are missing
    if not ee.data._credentials:

        # if the credentials token is asved in the environment use it
        if "EARTHENGINE_TOKEN" in os.environ:

            # write the token to the appropriate folder
            ee_token = os.environ["EARTHENGINE_TOKEN"]
            credential_folder_path = Path.home() / ".config" / "earthengine"
            credential_folder_path.mkdir(parents=True, exist_ok=True)
            credential_file_path = credential_folder_path / "credentials"
            credential_file_path.write_text(ee_token)

        # if the user is in local development the authentication should
        # already be available
        ee.Initialize(http_transport=httplib2.Http())


gee_configure()
```
In short I need to write a token in home directory so that `ee.initialize()` method run without raising any error. I use this trick in Github build environment and it works like a charm (https://github.com/12rambau/pygaul/actions/runs/5620754215/job/15230257587).

## Actual Result

The build fails because the file is not correctly written (or not written at all I don't really manage to diagnose this one)

```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

*A description of what actually happened*

2 options: 
- I don't have the write to create the file /home/.config/earthengine/credential. It's very unexpected, it would crash earlier
- You don't save variables the same way as Github and other services and I write an empty string to the file. The format of the varialbe is: `{"client_id": "ARealID", "refresh_token": "ARefreshToken"}`, is there an issue from your side to manage the `"` character ? or should I use simple quote around everything ?

**Comment by humitos** [comment]
> I don't have the write to create the file /home/.config/earthengine/credential. It's very unexpected, it would crash earlier

I suppose that you miss-type this and it should be `/home/docs/.config/earthengine/credentials`, right? (note it contains the `docs` user on its path)


> ```python
>             credential_file_path = credential_folder_path / "credentials"
>             credential_file_path.write_text(ee_token)
> ```

Doesn't this need to close the file here like `credential_file_path.close()` since you are not under a `with` block?

Also, could you confirm your file is being created by running `cat /home/docs/.config/earthengine/credentials` using `build.jobs` (see https://docs.readthedocs.io/en/latest/build-customization.html#extend-the-build-process). You can **use a fake token** for this purpose.

Actually, probably simpler to run this on `build.jobs.pre_build`:

```bash
mkdir -p $HOME/.config
echo $EARTHENGINE_TOKEN > $HOME/.config/credentials
```

and isolate this problem from Python.

**Comment by 12rambau** [comment]
> Doesn't this need to close the file here like credential_file_path.close() since you are not under a with block?

Normally no as I'm using the built-in `write_text` method from [Pathlib Path](https://docs.python.org/fr/3/library/pathlib.html#pathlib.Path.write_text).

I'll check the other options you mentioned.

**Comment by 12rambau** [comment]
I created a fake EARTHENGINE_TOKEN, ched for typo multiple times and it seems the variable is empty. 

I tried both `cat $HOME/.config/earthengine/credentials` and `echo $EARTHENGINE_TOKEN`

I should be seeing something in the output right ? (https://readthedocs.org/projects/pygaul/builds/21368612/)

**Comment by humitos** [comment]
Note that your environment variable is set to "Private" and private variables are not available on Pull Requests: https://docs.readthedocs.io/en/stable/guides/environment-variables.html

That's why the content of that file is empty.

**Comment by 12rambau** [comment]
1. that's clever 
2. Apologies for not seeing that before. 

Let me merge my PR and see how it goes on main

**Comment by humitos** [comment]
Also, I just realize that you may be hitting this other issue https://github.com/readthedocs/readthedocs.org/issues/8636 as well.

**Comment by 12rambau** [comment]
I printed all the used variables in https://readthedocs.org/projects/pygaul/builds/21387313/

```
'{"client_id": "toto", "client_secret": "toto", "refresh_token": "toto"}'
the written file is: /home/docs/.config/earthengine/credentials
'{"client_id": "toto", "client_secret": "toto", "refresh_token": "toto"}'
The credential file is: /home/docs/.config/earthengine/credentials
what is this: <_io.TextIOWrapper name='/home/docs/.config/earthengine/credentials' mode='r' encoding='UTF-8'>
```

You are right, the problem is `quote`. Let me find a workaround that I'll share here (objective is to have a consistent solution that works on multiple platform)

**Comment by 12rambau** [comment]
I used tghe following workaround: 

```python 
import re 

pattern = r"^'[^']*'$"
if re.match(pattern, ee_token) is not None:
   ee_token = ee_token[1:-1]
```

Whch ensure that the rest of the script continues to work in other framework. 
Thanks for the support @humidos
