### ISSUE TITLE
API documentation: project installation succeeds but rtd cannot import it

### ISSUE THREAD

**Issue by Sebastian-Belkner** [readthedocs/readthedocs.org#10563]
## Details

Hi everyone,
I am trying to build a sphinx documentation including the API. Locally, it works nicely.
Following your [tutorial](https://docs.readthedocs.io/en/stable/tutorial/index.html), I update the readthedocs.yaml to tell it to install the software, `delensalot`. In e.g. `builds/21387394/` it reads that the software, `delensalot`, is successfully installed. The rtd build then proceeds and eventually executes the `sphinx` command.

* Read the Docs project URL: https://readthedocs.org/projects/delensalot/
* Build URL (if applicable): https://readthedocs.org/projects/delensalot/builds/21387394/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/SebastianBelkner/

## Expected Result

I would expect that `delensalot` is successfully installed.
the sphinx-build (last command: `python -m sphinx -T -E -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html` ) should be able to import `delensalot` and build the API doc.

## Actual Result

It looks like that the rtd installation cannot find `delensalot`.

**Comment by humitos** [comment]
Hi @Sebastian-Belkner! There is a potential problem on this line of your `docs/source/conf.py`:

```python
sys.path.insert(0, "./../")
```

You should use a relative path using the actual file as starting point. Right now, it's using the `CWD` which could be different on your local environment than on Read the Docs. Something like this may work:

```python
current_path = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(current_path, "../"))
```

Please, try it and let me know.

**Comment by Sebastian-Belkner** [comment]
That was exactly it! Thanks a lot for looking into it, much appreciated :)
