### ISSUE TITLE
Build marked as "Failed" when "exit 183" ("skip the build") is used

### ISSUE THREAD

**Issue by vstinner** [readthedocs/readthedocs.org#10567]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/cpython-previews/
* Build URL (if applicable): https://readthedocs.org/projects/cpython-previews/builds/21404205/
* Read the Docs username (if applicable): (I'm not an admin of this project)

## Expected Result

[ReadTheDocs documentation](https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition) says that exit 183 can be used to skip a build: I expect the build to be reported to GitHub as a "success".

## Actual Result

The build was reported to GitHub as a failure:

> docs/readthedocs.org:cpython-previews — **Read the Docs build failed!**

My related PR which triggered the doc build: https://github.com/python/cpython/pull/107235

**Comment by vstinner** [comment]
> Build URL (if applicable): https://readthedocs.org/projects/cpython-previews/builds/21404205/

This URL seems to say that the build is still running, wheareas it was already reported as a failure to GitHub.

```
Building ...
```

**Comment by vstinner** [comment]
I triggered a new doc build job: https://readthedocs.org/projects/cpython-previews/builds/21404472/

It completed as expected as "Build cancelled", and was reported as expected as a success to GitHub PR: good!

The strange thing is that the first job https://readthedocs.org/projects/cpython-previews/builds/21404205/ executed ``cat .readthedocs.yml`` and ``asdf global python 3.11.4`` commands 3 times in a row! Moreover, right now, it still says "Building ...", as if it didn't complete.

**Comment by hugovk** [comment]
Looking at timestamps in the logs:

https://beta.readthedocs.org/api/v2/build/21404205.txt

Seems it _logged_ each command three times, rather than running three times. The timestamps for each repeated command is identical.

**Comment by stsewd** [comment]
Hi, we were doing a deploy during that time, so that's probably the cause of the duplicate commands (to save the commands we hit an API, if this is retried, it will duplicate the commands).

**Comment by vstinner** [comment]
> Hi, we were doing a deploy during that time

Since the following job was fine, feel free to close the issue if you consider it to be fixed.
