### ISSUE TITLE
extension problem

### ISSUE THREAD

**Issue by gigster99** [readthedocs/readthedocs.org#1059]
from the FAQ: https://docs.readthedocs.org/en/latest/faq.html
"The NumPy and Google styles are two popular docstring formats. Fortunately, the default Read The Docs theme handles both formats just fine, provided your conf.py specifies an appropriate Sphinx extension that knows how to convert your customized docstrings."

However, when using napoleon, receive this error message:
   https://readthedocs.org/builds/nutrients/1914206/
   ImportError: No module named 'sphinx.ext.napoleon'

Settings in my 'conf.py' look like this:
   extensions = [
                        'sphinx.ext.autodoc',
                        'sphinx.ext.napoleon',
                        ]

Am also trying to run the extension:
   'sphinxcontrib.bibtex',

In my 'requirements.txt' file have setting:
   sphinxcontrib-bibtex

Settings in my 'conf.py' look like this:
   extensions = [
                        'sphinxcontrib.bibtext',
                        ]

However, when executing, receive this error message:
  ImportError: No module named 'sphinxcontrib'
  https://readthedocs.org/builds/nutrients/1914067/

What am I doing wrong with these two methods (napoleon and bibtex)?

**Comment by michaelaye** [comment]
Isn't it wrong to add sphinx stuff to the requirements.txt that really only should contain dependencies for the actual Python module to work?

**Comment by ofloveandhate** [comment]
@michaelaye i got this sense, too.  it feels weird to require my users to install packages needed for documentation only.
