### ISSUE TITLE
git fetch looks for non-existant commit

### ISSUE THREAD

**Issue by cyberw** [readthedocs/readthedocs.org#10600]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/locust/
* Build URL (if applicable): https://readthedocs.org/projects/locust/builds/21506314/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/cyberw/

## Expected Result

Build should work even though I have made a force push. Maybe I need to clean it somehow?

## Actual Result

https://readthedocs.org/projects/locust/builds/21506314/

```
git clone --depth 1 https://github.com/locustio/locust.git .

git fetch origin --force --prune --prune-tags --depth 50 refs/heads/f5028923cd77f35f8588c056843cf7c134d2bbff:refs/remotes/origin/f5028923cd77f35f8588c056843cf7c134d2bbff
fatal: couldn't find remote ref refs/heads/f5028923cd77f35f8588c056843cf7c134d2bbff
```

Both stable and latest are failing in this way, but at least my tagged builds are working, like this one: https://readthedocs.org/projects/locust/builds/21507262/

**Comment by cyberw** [comment]
On closer inspection, that commit *does* exist, but it still doesnt work. Perhaps the git syntax is incorrect?

Here's another one:

https://readthedocs.org/projects/locust/builds/21532225/

**Comment by stsewd** [comment]
We have disabled our new clone/checkout pattern while we fix this bug.

**Comment by cyberw** [comment]
Thanks! It is working now!
