### ISSUE TITLE
Building latest fails at checkout

### ISSUE THREAD

**Issue by wRAR** [readthedocs/readthedocs.org#10601]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/scrapy/
* Build URL (if applicable): https://readthedocs.org/projects/scrapy/builds/21507805/

## Expected Result

After changing the default branch to just created 2.10 I saw that building `latest` failed. To make sure it's not a problem at our side I changed the default branch back to 2.9 and `latest` fails to build too.

## Actual Result

The build runs the following commands:

```
git clone --depth 1 https://github.com/scrapy/scrapy.git .
git fetch origin --force --prune --prune-tags --depth 50
git checkout --force 2.9
```

After I do the same manually I see that the local repo indeed doesn't contain a `2.9` branch, or any other branch except `master` and `remotes/origin/master`.

**Comment by heyman** [comment]
We're seeing a similar error when building `latest` for [Locust](https://github.com/locustio/locust):

https://readthedocs.org/projects/locust/builds/21530410/

**Comment by stsewd** [comment]
> After changing the default branch to just created 2.10 I saw that building latest failed.

Did you change this from GitHub or the RTD dashboard?

**Comment by stsewd** [comment]
We have disabled our new clone/checkout pattern while we fix this bug.

**Comment by wRAR** [comment]
> Did you change this from GitHub or the RTD dashboard?

RTD, at https://readthedocs.org/dashboard/scrapy/advanced/

**Comment by jakirkham** [comment]
Also seeing this in 2 recent PR builds (retrying didn't help)

* https://readthedocs.org/projects/zarr/builds/21553600/
* https://readthedocs.org/projects/zarr/builds/21553600/

**Comment by jakirkham** [comment]
Looks like something just changed as checkout failures are showing up for this PR ( https://github.com/zarr-developers/numcodecs/pull/442 ):

* https://readthedocs.org/projects/numcodecs/builds/21553604/
* https://readthedocs.org/projects/numcodecs/builds/21553604/

However these didn't occur Mom a previous PR ( https://github.com/zarr-developers/numcodecs/pull/455 ) ~40mins ago

* https://readthedocs.org/projects/numcodecs/builds/21553487/

**Comment by jakirkham** [comment]
Thanks Santos! 🙏

Ah ok. That may be. Didn't immediately think it was GitHub related as the GitHub Actions jobs seemed to run ok

Retried the Numcodecs PR above as well and that seems to be working now too

Sorry for the noise

**Comment by humitos** [comment]
@wRAR @heyman Hi! We've deployed a fix for this case. Please, let us know if it's working as you expected 👍🏼

**Comment by wRAR** [comment]
Works for us: https://readthedocs.org/projects/scrapy/builds/21626059/
