### ISSUE TITLE
Deprecation: stop auto-finding `conf.py`/`mkdocs.yml` from the repository

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#10637]
We currently have code that automatically finds a `conf.py` on the repository when there is no `sphinx.configuration` defined ( (https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx-configuration). We should remove this auto-finding and make `sphinx.configuration` to have a better default (like `docs/conf.py`) or make it always required.

> *Note:* the same happens for `mkdocs.yml` and `mkdocs.configuration`

https://github.com/readthedocs/readthedocs.org/blob/a23bc260d57a213c33440b02017dcef59fa57a9e/readthedocs/projects/models.py#L944-L962

I [created a Metabase query](https://ethicalads.metabaseapp.com/question/475-projects-not-specifying-sphinx-configuration?days=90) for and **I found ~950 projects without specifying `sphinx.configuration`** in the last 180 days.

**Comment by agjohnson** [comment]
It might also make sense to first inspect the number of projects that are flagged as spam. This could drop the number of projects considerably too.

**Comment by agjohnson** [comment]
Is that 400 spam projects or 400 projects down from the original 950 projects? The query is stuck for me.

**Comment by humitos** [comment]
Total projects without filter then from spam

**Comment by humitos** [comment]
I checked this again today by making the query directly on the Telemetry database because Metabase times out when extending the date range:

```sql
SELECT
  DISTINCT data->'project'->>'slug' as slug
FROM
  "telemetry_builddata"
​WHERE
  NOT data->'config'->'user'->'sphinx' ? 'configuration'
;
```

Then, I filtered those slugs by "active" organizations and not spam projects. The results are:

- 22 projects on commercial
- 1202 projects on community

The next steps here are:

- Write a small blog post with specific dates
- Send an email to these users
- Add an `if` in the code to don't auto find these files after the deprecation date
- Delete the code that auto find these files

**Comment by agjohnson** [comment]
In Q4 we should send some emails out.

**Comment by ericholscher** [comment]
> I checked this again today by making the query directly on the Telemetry database because Metabase times out when extending the date range:
> 
> ```sql
> SELECT
>   DISTINCT data->'project'->>'slug' as slug
> FROM
>   "telemetry_builddata"
> ​WHERE
>   NOT data->'config'->'user'->'sphinx' ? 'configuration'
> ;
> ```
> 
> Then, I filtered those slugs by "active" organizations and not spam projects. The results are:
> 
> * 22 projects on commercial
> * 1202 projects on community
> 
> The next steps here are:
> 
> * Write a small blog post with specific dates
> * Send an email to these users
> * Add an `if` in the code to don't auto find these files after the deprecation date
> * Delete the code that auto find these files

We merged the blog post here: https://github.com/readthedocs/website/pull/342

I think we still need to send out the email to these folks.

**Comment by humitos** [comment]
@ericholscher do you want to quickly write the content of the email? I can send it after that. I sent you an invitation for collaboration on https://hackmd.io/QW2lFsFQTva5_WTN-a6i_A. It contains the text from a previous email as an initial idea for the structure.

**Comment by ericholscher** [comment]
@humitos updated the email :+1:

**Comment by humitos** [comment]
Email sent 📧
