### ISSUE TITLE
Build: unable to parse Conda environment file

### ISSUE THREAD

**Issue by fuzailpalnak** [readthedocs/readthedocs.org#10644]
## Details:

* Project URL: https://readthedocs.org/projects/gtkit/
* Build URL(if applicable): https://readthedocs.org/projects/gtkit/builds/21636694/
* Read the Docs username(if applicable): fuzailpalnak

## Expected Result

trying to build the docs as descried https://docs.readthedocs.io/en/stable/guides/conda.html

## Actual Result

There was a problem with Read the Docs while building your documentation. Please try again later. If this problem persists, report this error to us with your build id (21636694).

**Comment by humitos** [comment]
It seems Read the Docs is having problems when parsing https://github.com/fuzailpalnak/gtkit/blob/main/docs/environment.yml because it's raising:

```
'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

Unfortunately, I don't have more information than that for now.

Sentry issue to keep debugging: https://read-the-docs.sentry.io/issues/4313168682/

**Comment by humitos** [comment]
@fuzailpalnak were you able to solve this issue? can you explain what was happening?

**Comment by fuzailpalnak** [comment]
I don't know the exact cause of the issue, from where is arouse, however, after I removed all the text from the file and debugged just the empty file I still encountered the same error, so here, I assumed the issue had to be with the way the original file was generated, so I created a new empty file and transferred all the content to the new file, with this new file, there were no utf-8 issues.
