### ISSUE TITLE
Version selector at bottom left does not expand/work when clicked

### ISSUE THREAD

**Issue by kratsg** [readthedocs/readthedocs.org#10645]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pyhf/
* Read the Docs URL: https://pyhf.readthedocs.io/en/v0.7.2/

## Expected Result

Clicking the version selector at bottom left shows the other versions available to switch to.

## Actual Result

Nothing happens when clicking the version selector at bottom left.

**Comment by humitos** [comment]
It seems that jQuery is not properly injected on the resulting HTML. I see the following error when I open the Firefox console.

```
Uncaught ReferenceError: jQuery is not defined
```

**Comment by matthewfeickert** [comment]
I think this has been fixed but we're just seeing the frozen results of the dpeloyement? This works fine on the RTD build of https://github.com/scikit-hep/pyhf/pull/2293:

https://pyhf--2295.org.readthedocs.build/en/2295/

![image](https://github.com/readthedocs/readthedocs.org/assets/5142394/eee40aa7-06b9-4ba4-bf4f-42c3f4bdbe15)

**Comment by kratsg** [comment]
I'll tentatively close this for now.
