### ISSUE TITLE
NameError: name 'using_rtd_theme' is not defined

### ISSUE THREAD

**Issue by zmbc** [readthedocs/readthedocs.org#10654]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pseudopeople/
* Build URL (if applicable): https://readthedocs.org/projects/pseudopeople/builds/21686009/

## Expected Result

Docs build successfully

## Actual Result

NameError: name 'using_rtd_theme' is not defined.

Since [this commit](https://github.com/readthedocs/readthedocs.org/commit/2066e3486a25bbd76431e1f8c20be3da0043f03a), the using_rtd_theme variable is no longer defined, but it is still referenced later in the file:

https://github.com/readthedocs/readthedocs.org/blob/87cdbb6f70cce8ebb03edb24398cc285c36995cd/readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl#L51-L53

I don't see how this can work. What am I missing?

**Comment by zmbc** [comment]
Ah, I searched for this already being reported in Issues, but just checked PRs. It looks like https://github.com/readthedocs/readthedocs.org/pull/10653 addresses this.

**Comment by humitos** [comment]
@zmbc can you try again now? We've solved this issue and re-deploy.
