### ISSUE TITLE
RTD fails to update build to the latest working commit after failed commit

### ISSUE THREAD

**Issue by luarss** [readthedocs/readthedocs.org#10666]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/openroad/
* Build URL (if applicable): 
* - Latest working commit: https://readthedocs.org/projects/openroad/builds/21726212/
* - Failed commit: https://readthedocs.org/projects/openroad/builds/21726084/
* - Second working commit: https://readthedocs.org/projects/openroad/builds/21721347/

## Expected Result

When you access the page build [here](https://openroad--3905.org.readthedocs.build/en/3905/), and click on the build logs. You should be linked to the latest working commit. 

![image](https://github.com/readthedocs/readthedocs.org/assets/39641663/580122ee-e652-4cd9-801b-3851ed1fdafd)

## Actual Result

It links us to the second working commit.

**Comment by humitos** [comment]
It links to the latest working commit to me. Maybe it was a cache issue for some minutes
