### ISSUE TITLE
Commit that previously built properly won't build now

### ISSUE THREAD

**Issue by sachaMorin** [readthedocs/readthedocs.org#10665]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/stepmix/
* Build URL (Success): https://readthedocs.org/projects/stepmix/builds/21656419/
* Build URL (Failed): https://readthedocs.org/projects/stepmix/builds/21721152/

## Expected Result

My builds started failing recently so I tried to rebuild the last commit with working docs on August 18. I expected it to work.

## Actual Result

The build fails. Any help to debug this would be appreciated.

More generally my builds have been failing since [this commit](https://github.com/Labo-Lacourse/stepmix/commit/55190ac73821b6a08fde8540c01ead3ece42174a), but I can't see how this would affect the docs.

Thanks!

**Comment by humitos** [comment]
You are using different versions of Sphinx on each build. The build that's not working is using Sphinx 7 and the one that's passing is using Sphinx 6. That may be the reason.

**Comment by sachaMorin** [comment]
That worked. I had to specify an [extra requirement](https://docs.readthedocs.io/en/stable/config-file/v2.html#packages) in .readthedocs.yaml. Thanks!
