### ISSUE TITLE
New readthedocs project solves pdf build Problem

### ISSUE THREAD

**Issue by SimeonEhrig** [readthedocs/readthedocs.org#10661]
Since we moved to the configuration file format v2, the pdf build of our readthedocs page failed.

```
Error

Build output directory for format "pdf" contains multiple files and it is not currently supported. Please, remove all the files but the "pdf" you want to upload.
```

We didn't recognized immediately because the preview in PRs was still working (does not build pdf) and we didn't configured an e-mail notification. Simple fixes does not solve the problem. Therefore I created a second readthedocs page, which uses my fork for testing purpose. The build of the fork works without problem. It used the same development branch like the upstream. 

I found only one difference between both readthedocs project. The upstream runs the following command:

```bash
python -m pip install --upgrade --no-cache-dir pillow mock==1.0.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.9.1 recommonmark==0.5.0 sphinx sphinx-rtd-theme readthedocs-sphinx-ext<2.3
```

and the fork this command:

```bash
python -m pip install --upgrade --no-cache-dir sphinx readthedocs-sphinx-ext 
```

In the documentation, there is mentioned, that it happens because it the upstream is "legacy" project: https://docs.readthedocs.io/en/stable/build-default-versions.html#python

I'm not sure, if this causes the problem and if yes, how to move the readthedocs project to a "non-legacy" state. 

## Details

* Read the Docs project URL: https://readthedocs.org/projects/alpaka/
* Build URL (if applicable): https://readthedocs.org/projects/alpaka/builds/21693635/
* Read the Docs project of the fork URL: https://readthedocs.org/projects/alpaka-test/
* Build URL of the fork (if applicable): https://readthedocs.org/projects/alpaka-test/builds/21693936/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/SimeonEhrig/

**Comment by humitos** [comment]
New projects are installing only `sphinx` and `readthedocs-sphinx-ext`. We announced this at https://blog.readthedocs.com/python-core-requirements-changed/

I added the project `alpaka` to the feature flag so it has that new behavior and triggered a new build for its `latest` version at https://readthedocs.org/projects/alpaka/builds/21709321/. Let me know if it works as you expects.

We plan to migrate _all projects_ to the new behavior in the following months.

**Comment by SimeonEhrig** [comment]
@humitos Thanks for your help. I see that the dependencies are not installed anymore. Therefore the change was successful. Unfortunately, it does not solve the problem :-(

**Comment by humitos** [comment]
@SimeonEhrig how many PDF files are generated when you run the PDF command locally? Make sure that _only 1_ is generated, since Read the Docs does not support more than 1 currently (see https://github.com/readthedocs/readthedocs.org/issues/2045)

**Comment by SimeonEhrig** [comment]
@humitos Indeed, this was the problem. We stored the project logo in a pdf for the latex documentation. I replaced it by a png and now it is working. Thank you very much. But it is little bit strange, that my fork builds. Nevertheless the problem is solved.

P.S.: I already found the PR, which will solve the problem in future: https://github.com/readthedocs/readthedocs.org/pull/10438
