### ISSUE TITLE
Build error with build id #21736993

### ISSUE THREAD

**Issue by tkoyama010** [readthedocs/readthedocs.org#10671]
## Details:

* Project URL: https://readthedocs.org/projects/getfem-ja/
* Build URL(if applicable): https://readthedocs.org/projects/getfem-ja/builds/21736993/
* Read the Docs username(if applicable): tkoyama010

## Expected Result

Build without error.

## Actual Result

![image](https://github.com/readthedocs/readthedocs.org/assets/7513610/5f235431-636f-419c-9555-484c9a1fad5b)

**Comment by humitos** [comment]
It seems it was a temporal issue since all your following builds were building successfully. Please, keep us posted if the problem persist, tho.
