### ISSUE TITLE
Build error with build id #21767861

### ISSUE THREAD

**Issue by pcarbonn** [readthedocs/readthedocs.org#10688]
## Details:

* Project URL: https://readthedocs.org/projects/FO-dot/
* Build URL(if applicable): https://readthedocs.org/projects/fo-dot/builds/21767861/
* Read the Docs username(if applicable): pierre.carbonnelle

## Expected Result

After a small change, I expected the project to compile, or to give me an error message allowing me to take corrective actions.
The project compiles successfully on my machine.

## Actual Result

I got a "Compilation failed" error, without any detail nor explanation.

**Comment by humitos** [comment]
Can you try re-building your docs? It seems like a temporal issue.

**Comment by stsewd** [comment]
There was an issue with our builders, but they are working now.
