### ISSUE TITLE
Sudden theme change

### ISSUE THREAD

**Issue by gwilku** [readthedocs/readthedocs.org#10692]
## Details

* Read the Docs project URL: https://jscan-docs.readthedocs.io/en/latest/index.html
* Just ran a build with some minor tweaks to the content and no changes to theme, configuration, etc. Suddenly the looks has changed completely. WTF?

## Expected Result
Should look like https://docs.readthedocs.io/en/stable/

## Actual Result
Looks like crap

**Comment by gwilku** [comment]
Nevermind, turns out rtd just changed what the "default" theme is. Fixed it by using the direct theme name.

**Comment by kjosib** [comment]
Bitten by the same change. Solution is this edit to the `conf.py` file:
```
extensions = [ "sphinx_rtd_theme", ]
html_theme = "sphinx_rtd_theme"
```
This means local builds will require `pip install sphinx_rtd_theme` but such is life.

**Comment by faph** [comment]
The documentation should be updated: https://docs.readthedocs.io/en/stable/faq.html

**Comment by humitos** [comment]
Thanks @faph! I opened a PR to update this page completely.
