### ISSUE TITLE
Build error with build id #21769676

### ISSUE THREAD

**Issue by davidberenstein1957** [readthedocs/readthedocs.org#10691]
## Details:

* Project URL: https://readthedocs.org/projects/argilla_docs/
* Build URL(if applicable): https://readthedocs.org/projects/argilla-docs/builds/21769676/
* Read the Docs username(if applicable): recognai

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by stsewd** [comment]
Hi, I see that your latest builds are passing now, this was probably the same problem as https://github.com/readthedocs/readthedocs.org/issues/10689
