### ISSUE TITLE
Error code `PR_CONNECT_RESET_ERROR` on `readthedocs.org/*`

### ISSUE THREAD

**Issue by wchistow** [readthedocs/readthedocs.org#10698]
When I tried to sign up to readthedocs (URl - https://readthedocs.org/accounts/signup/) I've got this error:

```none
Secure Connection Failed

An error occurred during a connection to readthedocs.org. PR_CONNECT_RESET_ERROR

Error code: PR_CONNECT_RESET_ERROR
```

How to solve this error?

**Comment by stsewd** [comment]
Hi, this sounds like a temporal problem, can you try again?

**Comment by wchistow** [comment]
I tried: the problem remained

**Comment by Peter-developer01** [comment]
Try to sign up on the other browser and if available, on the other computer?

**Comment by wchistow** [comment]
@Peter-developer01, I haven't got an other computer, but about other browser... this error is in Yandex Browser, FireFox, Google Chrome, and Microsoft Edge.

**Comment by Peter-developer01** [comment]
Try enabling VPN and doing the process again?

**Comment by wchistow** [comment]
@humitos, Hm, I tried again, and now it's OK.
