### ISSUE TITLE
Messed up ANSI escape characters in build logs

### ISSUE THREAD

**Issue by mgeier** [readthedocs/readthedocs.org#10702]
Since a few weeks the logs contain some remnants of broken ANSI escape sequences.

This broke some time between July 7 (https://readthedocs.org/projects/nbsphinx/builds/21235580/) and August 12 (https://readthedocs.org/projects/nbsphinx/builds/21589795/)

## Details

* Read the Docs project URL: https://readthedocs.org/projects/nbsphinx/
* Build URL (if applicable): https://readthedocs.org/projects/nbsphinx/builds/21799832/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/geier/

## Expected Result

    reading sources...

## Actual Result

    [2Kreading sources...

**Comment by humitos** [comment]
I don't think we haven't change anything in our backend related to this. Could it be related with the different version of Sphinx? The one that doesn't show the `[2K` characters is 7.0.1 and the one that shows them is 7.2.0.

**Comment by mgeier** [comment]
Yeah, looks like it depends on the Sphinx version.

7.1.1 also has this problem (e.g. https://readthedocs.org/projects/insipid-sphinx-theme/builds/21471085/)

I can also confirm that more recent RTD builds with older Sphinx versions still work (e.g. https://readthedocs.org/projects/insipid-sphinx-theme/builds/21731912/).

However, locally it works fine for me. By default, the log messages are correctly shown in color, and with the `--no-color` flag they are shown correctly without color.

Maybe the auto-detection of color terminals somehow changed in Sphinx 7.1 and the RTD log is falsely detected as supporting color?

**Comment by mgeier** [comment]
I have created https://github.com/sphinx-doc/sphinx/issues/11675, maybe someone over there has an idea.

**Comment by humitos** [comment]
I'm closing this issue from here since we already found it's an issue on Sphinx itself more than on Read the Docs.
