### ISSUE TITLE
502 Bad Gateway error on project import from GitHub

### ISSUE THREAD

**Issue by mperez-cdf** [readthedocs/readthedocs.org#10707]
## Details

I'm trying to follow the "Getting started" tutorial. I have a GitHub account linked to Read The Docs, and now I want to import the tutorial project. I'm at that step of the tutorial: https://docs.readthedocs.io/en/stable/tutorial/index.html#importing-the-project-to-read-the-docs

So I'm at this page https://readthedocs.org/dashboard/import/ ; the project is shown and I can import it with the "+" button. I did change the name so it is unique. Everything seems OK... Until I click the "next" button.

## Expected Result

My first Read The Docs project is created and I can build a documentation

## Actual Result

502 Bad Gateway error, since yesterday (18 hours ago approximately)

![image](https://github.com/readthedocs/readthedocs.org/assets/122037372/a2488b38-3d30-40e9-902b-4c3975b42e27)

**Comment by stsewd** [comment]
Hi, maybe this was a temporal issue, I was able to import a project now, can you try again?

**Comment by mperez-cdf** [comment]
I still have the same problem...

I use firefox, maybe I'll try something else later

**Comment by mperez-cdf** [comment]
A workaround if the problem happens to someone else:
The manual import is working ("import manually" button on the right), with the exact same data than the automatic import

**Comment by opain** [comment]
I am having the same issue. I have tried importing from GitHub and entering manually, but receive the bad gateway error every time. I have been trying for about 20 mins.

**Comment by Marcussacapuces91** [comment]
same issue next year

**Comment by humitos** [comment]
Is there any way we can debug this issue? Any more context you can provide here? I never hit it when using Read the Docs.

**Comment by opain** [comment]
I have just tried again for the first time in a month, and now it seems to be working.

**Comment by humitos** [comment]
OK. I will close this issue since we don't have a good way to replicate it and it seems it's working fine for one of users affected. I'm happy to re-open it in case we have more debug information.

**Comment by mariakesa** [comment]
I have this issue! I submitted a ticket on readthedocs. Bad gateway.

**Comment by stsewd** [comment]
From support, a user was able to avoid this problem by using a different internet provider. Maybe there is an issue with an ISP you all have in common or a CF node, which may also depend on location.
