### ISSUE TITLE
Build error with build id #21850791

### ISSUE THREAD

**Issue by ots22** [readthedocs/readthedocs.org#10717]
## Details:

* Project URL: https://readthedocs.org/projects/scivision/
* Build URL(if applicable): https://readthedocs.org/projects/scivision/builds/21850791/
* Read the Docs username(if applicable): ots22

## Expected Result

Build to complete successfully

## Actual Result

The last step of the build that completes is

```
python -m pip install --upgrade --no-cache-dir pillow mock==1.0.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.9.1 recommonmark==0.5.0 sphinx sphinx-rtd-theme readthedocs-sphinx-ext<2.3
```

The next step doesn't give any output and the build errors at that point with a generic message ('There was a problem with Read the Docs while building your documentation.')

**Comment by ots22** [comment]
The error seemed to be caused by having
```
extra_requirements:
  - [doc]
```
in .readthedocs.yml, instead of
```
extra_requirements:
  - doc
```

**Comment by humitos** [comment]
@ots22 there is an example in the documentation about this config key: https://docs.readthedocs.io/en/stable/config-file/v2.html#packages

However, the error shown to the user should be pretty clear. I'm adding this to https://github.com/readthedocs/readthedocs.org/issues/10502
