### ISSUE TITLE
HTT header: attach header per-project instead of per-domain

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#10728]
## What's the problem this feature will solve?

Currently, we allow attaching http headers to custom domains only.

https://github.com/readthedocs/readthedocs.org/blob/0c1df7505beabcfba6bd0fd04e00bb1fecb9cbc3/readthedocs/projects/models.py#L1722-L1726

This has a couple of problems:

- If a project adds a new custom domain, we will need to create all current headers for that domain, and we will need to keep in sync all of them in case we change something.
- We can't have custom http headers for our default domains (readthedocs.io, readthedocs-hosted.com).

## Describe the solution you'd like

Instead of attaching the header to a custom domain, we attach it to the project. I don't think there is a case a user will want to have different values per domain, if we find that there is a use case for that, we could keep the old field and support both options.

## Alternative solutions

- Force people to always use a canonical custom domain if they want additional headers. 
- Keep all custom domains from a project in sync manually or have an automatic way of doing it.
- Create a custom nginx configuration each time we want to add a header to all domains a project is served from.

**Comment by humitos** [comment]
This seems a duplicated of https://github.com/readthedocs/readthedocs.org/issues/8649. Feel free to move anything from this issue there if there are more context/considerations here that are not there.
