### ISSUE TITLE
Unable to install `python3.11` with additional required packages

### ISSUE THREAD

**Issue by psss** [readthedocs/readthedocs.org#10720]
## Details

In psss/did/pull/321 I've updated the readthedocs config to require python 3.11 in order to use fresh sphinx.

* Read the Docs project URL: https://readthedocs.org/projects/did/
* Build URL (if applicable): https://readthedocs.org/projects/did/builds/21864548/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/psss/

## Expected Result

Python 3.11 installed and used for building the docs.

## Actual Result

Python 3.7 is used to build the docs which ends up with the failure to install fresh sphinx:

    ERROR: No matching distribution found for sphinx==7.2.4

The problem seems to be related to the `apt_packages` section. If I remove it, [fresh python is installed](https://readthedocs.org/projects/did/builds/21864752/). But I'm not able to build docs without the dependencies.

**Comment by humitos** [comment]
It seems that you have `build` config key defined twice in your YAML and the last one is getting executing. The one that does not define Python version. See https://beta.readthedocs.org/projects/did/builds/21864548/#202448641--14

Remove it and it should just work fine.

**Comment by psss** [comment]
Oh, I was blind, time to stop and leave for the weekend ;-) Thanks for the quick response and sorry for the noise! Now works nicely :)

Can I have a quick question though? With the fresh `sphinx` and `sphinx-rtd-theme` the left menu does not expand sections (select, format, utils are not shown):

* old: https://did.readthedocs.io/en/stable/overview.html#format
* new: https://did--321.org.readthedocs.build/en/321/overview.html#format

Was this an intentional change? Is there a config option to enable the menu expansion back?

**Comment by humitos** [comment]
> Can I have a quick question though? With the fresh `sphinx` and `sphinx-rtd-theme` the left menu does not expand sections (select, format, utils are not shown):

Please, open an issue on the theme for this at https://github.com/readthedocs/sphinx_rtd_theme/
