### ISSUE TITLE
Documentation says `build.tools.python: 3` should work but it doesnt

### ISSUE THREAD

**Issue by mithro** [readthedocs/readthedocs.org#10757]
The docs say that you can use `3` to get the `(latest stable CPython version)` however, when you try and use that value in your configuration the build will fail with;
```
Error
Problem in your project's configuration. Invalid configuration option "build.tools.python": expected one of (2.7, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3, miniconda3-4.7, mambaforge-4.10, mambaforge-22.9), got 3
```

Se the following screenshots;

![image](https://github.com/readthedocs/readthedocs.org/assets/21212/cdcd839f-ec05-423d-8789-e8fbcd434daa)

![image](https://github.com/readthedocs/readthedocs.org/assets/21212/a325ed50-2d64-4e14-8e6b-0d922a17d6d6)

**Comment by humitos** [comment]
This is a known bug. Please use `build.tools.python: "3"` (note the quotes). Duplicated of https://github.com/readthedocs/readthedocs.org/issues/10502
