### ISSUE TITLE
"stable" is not pointing to the correct version, and I can't figure out how to redirect it

### ISSUE THREAD

**Issue by mattip** [readthedocs/readthedocs.org#10782]
## Details

* Read the Docs project URL: https://asv.readthedocs.io
* Build URL (if applicable): 
* Read the Docs username (if applicable): https://readthedocs.org/profiles/mattip/

## Expected Result

https://asv.readthedocs.io/en/stable/ should be pointing to the v0.6.0 release https://asv.readthedocs.io/en/v0.6.0/, but points to the v0.5.1 release instead, which is not even active.

I don;t see any way to reconfigure where the stable release points to. In the docs [it says](https://docs.readthedocs.io/en/stable/versions.html)
> If you want a custom stable version, create either a tag or branch in your project with that name.

but that doesn't seem applicable in my case: then how do I update `stable` to a newly released version? Tags are not mutable, and a branch is not applicable.

**Comment by stsewd** [comment]
Hi, looks like the stable version didn't trigger a build when you released a new build. This is because your project has a branch named stable https://github.com/airspeed-velocity/asv/tree/stable, you should delete/deactivate that branchin order for RTD to point stable to the proper tag.

**Comment by mattip** [comment]
:facepalm: Thanks!
