### ISSUE TITLE
Project: use a dropdown for multi version/single version/single language options

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#10781]
## What's the problem this feature will solve?

Currently, we have a boolean option `single_version`, when it's false it means the project is a multi-version-language project. But with https://github.com/readthedocs/readthedocs.org/pull/10766, we now have another option, a project can be single language.

## Describe the solution you'd like

Use a choice field instead, with multi-version-languange being the default. We may be able to even show a preview of how this will look like based on the slug, lang, default version, etc, e.g `/en/latest/`, `/`, `/latest/`.

We can do this migration by adding a new field (`project_type`/`versioning_model`/`type`?) with 2 options (multi-version-language and single-version-language), do a data migration migrating the old `single_version` value to the choice field, maintaining backwards compatibility with our APIs should be easy, this would be just a field that's based on the value of the new choice field.

## Alternative solutions

Just use another boolean field and add some validations in place, so a user can't select all of them at once.

## Additional context

https://github.com/readthedocs/readthedocs.org/pull/10766#discussion_r1339282833

**Comment by humitos** [comment]
This makes sense to me. If we can create a new field called `versioning_model` (with the options: `single-version-single-language`, `multi-version-multi-language`, `multi-version-single-language` and `single-version-multi-language`) and do the migration will be the clearest and best, IMO.
