### ISSUE TITLE
Update docs about default installed dependencies

### ISSUE THREAD

**Issue by dracos** [readthedocs/readthedocs.org#10794]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/uk-covid19-inquiry-hearings/
* Build URL (if applicable): https://readthedocs.org/projects/uk-covid19-inquiry-hearings/builds/22117610/

## Expected Result

The build to continue to work as it did previously.

## Actual Result

The build fails saying "recommonmark" does not exist. It appears that the build is only installing `sphinx readthedocs-sphinx-ext` whereas the last successful build it installed `pillow mock==1.0.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.9.1 recommonmark==0.5.0 sphinx sphinx-rtd-theme readthedocs-sphinx-ext<2.3`. I haven't changed anything at my end. I have read https://docs.readthedocs.io/en/stable/build-default-versions.html#python which states that these extra packages should be installed automatically apart from "Projects created after August 7, 2023" - but my project was created before that date.

I can and will update my project to manually install these, but raising this issue due to the documentation stating this should not be necessary.

**Comment by stsewd** [comment]
Hi, this was done together with https://blog.readthedocs.com/defaulting-latest-build-tools/. The documentation should indeed be updated.

**Comment by cyberw** [comment]
Hi! I have another old project and have tried to add the required dependencies, but it still doesnt work https://readthedocs.org/projects/locust/builds/22137182/

**Comment by dracos** [comment]
@cyberw Your conf.py only sets html_theme if not on readthedocs - perhaps that also needs to change now?

**Comment by cyberw** [comment]
Maybe? That piece of code was written in 2014, and hasn't caused issues before though :)

**Comment by cyberw** [comment]
> @cyberw Your conf.py only sets html_theme if not on readthedocs - perhaps that also needs to change now?

That appears to have helped, thanks! Perhaps there was something wrong earlier - the only way I can imagine the code in conf.py working before but not now is if $READTHEDOCS was broken (unset) before but not now ¯\_(ツ)_/¯

**Comment by stsewd** [comment]
@cyberw we are no longer setting the theme on behalf of users, so you need to set the `html_theme` to your desired theme or Sphinx's default will be used (alabaster).

**Comment by cyberw** [comment]
👍 That makes sense! Can you help me run a new build for stable / 2.17.0? I tried moving my git tag but it doesnt seem to care...

**Comment by cyberw** [comment]
Did you do something, or did I get it working now? Regardless, thanks for the help & explanations :)

**Comment by stsewd** [comment]
@cyberw I didn't anything :) There is a problem with forced pushes to tags, where the previous commit will be used for the build, so when force-pushing to a tag, you'll need to trigger two builds (the first build will update the tag's commit, and the second will actually build that commit).

**Comment by cyberw** [comment]
Goot to know!
