### ISSUE TITLE
PyPy documentation is showing the "This is the latest development version" popup, how do I disable it?

### ISSUE THREAD

**Issue by mattip** [readthedocs/readthedocs.org#10791]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pypy/
* Build URL (if applicable): 
* Read the Docs username (if applicable): https://readthedocs.org/profiles/mattip/

## Expected Result

Display documentation at https://doc.pypy.org/en/latest/

## Actual Result

I get a pop-up box (with a minor typo):
> This is the latest development version
> Some features may not be yet available in the publised (sic) stable version. Read the [stable version of this documentation](https://doc.pypy.org/en/stable/)

The "Show version warning" checkbox is turned off. The project does not have a "stable" version, we want the latest development version only to be shown. Is there a way to do that?

After the simple fix to #10782 I figure this is also some misunderstanding, but I can't figure it out.

**Comment by ericholscher** [comment]
This is a bug on our side, so I've disabled this functionality for now. It should be gone from your docs.

**Comment by mattip** [comment]
Thank you!
