### ISSUE TITLE
Clicking "Build version" tries to build non-existant branch

### ISSUE THREAD

**Issue by dracos** [readthedocs/readthedocs.org#10793]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/uk-covid19-inquiry-hearings/
* Build URL (if applicable): https://readthedocs.org/projects/uk-covid19-inquiry-hearings/builds/22117480/

## Expected Result

As I don't have a "Default branch" set under "Advanced Settings", I expected that clicking "Build version" button on the front page or the Builds page would build the default branch for the repository (which is "main").

## Actual Result

It tries to build the master branch, which does not exist.

It works fine for pushes to GitHub triggering builds, it's only the manual button in the admin that does this.

**Comment by stsewd** [comment]
Hi, this is because you don't have your account linked to GitHub, RTD makes use of the GitHub API in order to find the default branch automatically, if you don't want to link your account, you can change the default branch from the Advanced Settings menu.

**Comment by dracos** [comment]
Oh, weird, wonder why I hadn't done that. Thanks!
