### ISSUE TITLE
building using sphinx_rtd_theme failed

### ISSUE THREAD

**Issue by aorliche** [readthedocs/readthedocs.org#10798]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/imagenomer/
* Build URL (if applicable): https://readthedocs.org/projects/imagenomer/builds/22126823/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/aorliche/

## Expected Result

Docs would be rebuilt after editing the index.rst in the docs, adding, committing, and pushing to GitHub.

## Actual Result

Error when attempting to apply sphinx_rtd_theme (not installed anymore?)
Builds as of 2 days ago were working.

![image](https://github.com/readthedocs/readthedocs.org/assets/79995801/bb7419d5-8344-475c-bf5a-4878a5662bad)

Thank you for help!

**Comment by stsewd** [comment]
Hi, we are no longer installing dependencies for users https://blog.readthedocs.com/defaulting-latest-build-tools/, you should explicitly specify the `sphinx-rtd-theme` package in your requirements.
