### ISSUE TITLE
New readthedocs configurations are not rendering math properly

### ISSUE THREAD

**Issue by NishantBaheti** [readthedocs/readthedocs.org#10790]
## Details

* Read the Docs project URL: (https://mlguidebook.com/en/latest/SupportVectorMachine/Explore.html#Algorithm)
* Build URL (if applicable): (https://readthedocs.org/projects/machinelearningexploration/builds/22098131/)
* Read the Docs username (if applicable): https://readthedocs.org/profiles/nishantbaheti/

## Expected Result

<img width="864" alt="image" src="https://github.com/readthedocs/readthedocs.org/assets/31793052/ff62cb33-9522-4bce-b658-cd475c1d34cb">

## Actual Result

<img width="869" alt="image" src="https://github.com/readthedocs/readthedocs.org/assets/31793052/ecfff5f3-b6b2-4eff-9104-8f11e89f3b48">

**Comment by mgeier** [comment]
This is a problem with `nbsphinx`, see https://github.com/spatialaudio/nbsphinx/issues/766
