### ISSUE TITLE
Could not import extension sphinx_rtd_theme

### ISSUE THREAD

**Issue by redteampanda-ng** [readthedocs/readthedocs.org#10802]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/log-analysis-manual/
* Build URL (if applicable): https://readthedocs.org/projects/log-analysis-manual/builds/22140327/

## Expected Result

Project gets built without errors.

## Actual Result

Since today, a lot of my projects fail during the build process with the same error:
``Could not import extension sphinx_rtd_theme (exception: No module named 'sphinx_rtd_theme')``

I did not change anything regarding the requirements. Adding the sphinx-rtd-theme to the requirements.txt, I get the same error.
What I did notice however in another project (around 10 days ago), is that "sphinx-rtd-theme" is being installed during the build process, even though I do not have a `requirements.txt` file present. It seems like that maybe changed in a recent update?

Thanks.

**Comment by jakobkogler** [comment]
Duplicate of #10798

**Comment by redteampanda-ng** [comment]
thanks, this worked.
https://github.com/NextronSystems/log-analysis-manual/commit/adefb192c74fbc33d4cb552e8e92a29828bc22a2
