### ISSUE TITLE
Error on project creation

### ISSUE THREAD

**Issue by HumanBot000** [readthedocs/readthedocs.org#10818]
The file /home/docs/checkouts/readthedocs.org/user_builds/playgroundpublic/checkouts/latest/docs/conf.py doesn't exist. Make sure it's a valid file path.

**Comment by humitos** [comment]
Hi @HumanBot000! Make sure the `conf.py` file your configuration file points to, exists on that path.

**Comment by HumanBot000** [comment]
I wanted to try it again with a different repository and a different docs,I
deleted both but now I can't pick the same name again

Manuel Kaufmann ***@***.***> schrieb am Mo., 16. Okt. 2023,
12:15:
