### ISSUE TITLE
Docs: improve sitemap and custom sitemap docs

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#10816]
A few notes for our sitemap docs:

- The note on using a custom sitemap just says "contact support". Instead, we should describe how to use a custom sitemap through a custom "robots.txt". That is, in a custom robots.txt on the default version, add the `Sitemap: https://slug.readthedocs.io/en/latest/sitemap.xml` directive.
- The sitemap feature page spends a lot of time describing *what* a sitemap is, where we should probably make the focus of this page on our own support of sitemaps.
- We refer to sitemaps in multiple places as `sitemap.xml`. https://sitemaps.org uses "Sitemaps", though I think a lowercase "sitemaps" is okay too.

And because it's currently coming up for me as the first search hit in our docs for "sitemap", it's probably worth noting that the [SEO guide](https://docs.readthedocs.io/en/stable/guides/technical-docs-seo-guide.html) feels slightly out of place on our own docs. It's good content though, so I'm not quite sure what to do with it. Is this maybe better website content? This can be a separate conversation, especially if changing the page title of the sitemap feature page bumps it up in the results.

**Comment by astrojuanlu** [comment]
Was this fixed in #10899 ?

**Comment by humitos** [comment]
I opened https://github.com/readthedocs/readthedocs.org/pull/11585 with the missing small changes requested in this issue 👍🏼 . Thanks for the pointer.
