### ISSUE TITLE
`Exact redirect` is not working as documented

### ISSUE THREAD

**Issue by jugmac00** [readthedocs/readthedocs.org#10849]
## Details

Following the documentation at https://docs.readthedocs.io/en/stable/user-defined-redirects.html#migrating-your-documentation-to-another-domain
I intended to apply the following settings:

```
Type: Exact Redirect
From URL: /$rest
To URL: https://mynewsite.com
Force Redirect: True
```

## Expected Result

I had hoped to be able to do that.

## Actual Result

There is no way to set `Force Redirect` at the web ui.

So, either the documentation is wrong, the UI does not expose that function, or the function is missing completely.

Thanks for looking into this!

P.S.: My company is a commercial customer and I tried to migrate to the .com site. I also filed a ticket with the support as maybe it is possible to set that option in the background to unblock me. I have not yet received a ticket number, so you'd need to look up the case by name.

**Comment by stsewd** [comment]
This was handled via email. In case someone else comes around this same problem, forced redirects are enabled by contacting support, https://docs.readthedocs.io/en/stable/user-defined-redirects.html#limitations.

**Comment by jugmac00** [comment]
Thanks, @stsewd, could you please update the linked paragraph from my issue to include a quick note about this and a link to the limitations sections? It was and it is completely non-obvious when you go the section I linked.
