### ISSUE TITLE
Unable to expand `Read the Docs` tab with version and downloads

### ISSUE THREAD

**Issue by kerim371** [readthedocs/readthedocs.org#10841]
## Details

When clicking on this button:
![image](https://github.com/readthedocs/readthedocs.org/assets/43808863/a079ffed-f2a0-4fdf-8196-b8d2a69ff466)
I expect it to be expended. But it doesn't.

It may be related to #4132 and #445 but trying latest version `sphinx-rtd-theme` didn't help. 
I think it also may be caused by [.readthedocs.yaml](https://github.com/tierra-colada/colada-docs/blob/main/.readthedocs.yaml). Maybe I miss some settings?

* Read the Docs project URL: https://readthedocs.org/projects/colada-docs/
* Built documentation: https://colada-docs.readthedocs.io/en
* Github project: https://github.com/tierra-colada/colada-docs

**Comment by humitos** [comment]
It seems that jQuery is not included in the HTML output. I'm seeing `Uncaught ReferenceError: jQuery is not defined` in the JS console. I remember we already fixed this problem, so maybe we have a regression here.

**Comment by stsewd** [comment]
Hi, can you try deleting the import and the setting of the `html_theme_path`?

https://github.com/tierra-colada/colada-docs/blob/1caf2e60ae7e43d1b1f13faf3961e21a58ab2f5b/source/conf.py#L66-L69

To use the theme, you only need to set the `html_theme_path` setting. Importing the theme is probably interfering with the sphinxcontrib_jquery extension. The theme requires jQuery to be loaded before we try to inject it.

**Comment by kerim371** [comment]
@stsewd hi

thank you!
After removing `sphinx_rtd_theme` from imports and its methods/functions of course it started to work.

> To use the theme, you only need to set the `html_theme_path` setting.

You probably meant `html_theme`.

The problem solved.
