### ISSUE TITLE
[beta UI] Manual import does nothing

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/readthedocs.org#10842]
## Details

* Read the Docs username (if applicable): https://readthedocs.org/profiles/Juanlu001/

## Expected Result

I can import a project with the Beta UI.

## Actual Result

![Screen Recording 2023-10-18 at 14 08 46](https://github.com/readthedocs/readthedocs.org/assets/316517/891bb93f-697f-49d2-8332-4c158c8323eb)

**Comment by agjohnson** [comment]
Thanks for the report @astrojuanlu !

I'm actually not able to reproduce this behavior at all, I get the next page from the view, which is the configuration example view. I tried on both my local dev and the beta, with a few different repositories.

Are you still noticing this behavior, and if so, any notable console errors perhaps? The templates for this view don't do much of anything special, just a standard POST, so any failure here should be pretty obvious.

Note: I'll continue to follow along here, but removing this from my sprint

**Comment by astrojuanlu** [comment]
I confirm I can't reproduce this anymore, thanks! 🚀

**Comment by agjohnson** [comment]
Oh good! If it happens again, the console might have some information to debug from. I suspect this was an issue with a release or something, though nothing has changed in the views or forms in a while :shrug:

**Comment by astrojuanlu** [comment]
I just saw this happening again with @rashidakanchwala today

**Comment by agjohnson** [comment]
I'm also now noticing this on my local instance. However, I don't have anything interesting to report here, I can't explain what the bug is just yet though I am able to reliably reproduce.

**Comment by agjohnson** [comment]
This form was using an old attribute it seems, I can't explain when it changed or why this seemed intermittent though.
