### ISSUE TITLE
.readthedocs.yaml file created but not found during build

### ISSUE THREAD

**Issue by rayluo** [readthedocs/readthedocs.org#10857]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/msal-python/
* Build URL (if applicable): https://readthedocs.org/projects/msal-python/builds/22297113/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/rayluo/

## Expected Result

Project should build successfully since I added a `.readthedocs.yaml` (into my `docs-staging` branch).

## Actual Result

I am still getting the following error:

> The configuration file required to build documentation is missing from your project. Add a configuration file to your project to make it build successfully. Read more at https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by humitos** [comment]
The problem is that your file is called `.readthedocs.yaml ` (note the extra space at the end)

```
/tmp/microsoft-authentication-library-for-python  a3c774b ✔                                                                                                                                                                                                                                                          2d14h  
▶ ls -la
drwxr-xr-x    - humitos 23 Oct 12:04 .git
drwxr-xr-x    - humitos 23 Oct 12:03 .github
.rw-r--r--  733 humitos 23 Oct 12:03 .gitignore
.rw-r--r--  571 humitos 23 Oct 12:04 '.readthedocs.yaml '
.rw-r--r-- 2.3k humitos 23 Oct 12:03 .travis.yml
...
```

Remove the space and it will work.

**Comment by rayluo** [comment]
Thank you, @humitos ! That accidental extra keystroke costed me quite some time. Ouch.

BTW, can a ReadTheDocs user access the logs that you pasted? I wonder whether I could have spotted it myself.

**Comment by humitos** [comment]
I just git cloned your repository and print the files in the repository.
