### ISSUE TITLE
Docs: explain how to use "canonical domain" via `READTHEDOCS_CANONICAL_URL`

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#10866]
When a project defines a custom domain and marks it as "Canonical", we use our `readthedocs-sphinx-ext` to inject:

https://github.com/readthedocs/readthedocs-sphinx-ext/blob/614109c6ad11eaacbcde1040b908967c80b81eba/readthedocs_ext/_templates/readthedocs-insert.html.tmpl#L4-L19

When migrating to the Addons approach, this code won't be executed anymore. We will need to document how to inject this `link` HTML tag on different doctools by using the `READTHEDOCS_CANONICAL_URL` environment variable for this purpose.

**Comment by davidism** [comment]
It would be nice to see an example of a value for `READTHEDOCS_CANONICAL_URL` as well. Or log the env vars during the build for reference. Based on how it's describe in https://docs.readthedocs.io/en/stable/canonical-urls.html#how-read-the-docs-generates-canonical-urls, it's not clear if the URL is only the domain `https://docs.readthedocs.io` or if it has the default version like `/en/stable/` at the end.

**Comment by davidism** [comment]
I'm fixing canonical URL support in Pallets-Sphinx-Themes right now, and I'm using `urlsplit` to get just the scheme and netloc, replacing the path with `/page/` which is the built-in redirect.

```python
rtd_canonical = os.environ["READTHEDOCS_CANONICAL_URL"]
parts = urlsplit(rtd_canonical)
app.config.html_baseurl = f"{parts.scheme}://{parts.netloc}/page/"
```

**Comment by humitos** [comment]
> It would be nice to see an example of a value for `READTHEDOCS_CANONICAL_URL` as well

Thanks for the suggestion. It seems we only have the example values for this variable in https://docs.readthedocs.io/en/stable/reference/environment-variables.html#envvar-READTHEDOCS_CANONICAL_URL 😅 

It will include the `/en/stable/`, yeah.

I hope that clarifies this. Let me know otherwise.

**Comment by davidism** [comment]
OK, so I should strip off `/<lang>/<version>/` and redirect to `/page/...` instead, so that all pages point to the default version as the canonical one. I'm not clear why it would be useful for the canonical URL to have the specific version slug in it, shouldn't every version have the same canonical? That said, I'm not sure what search engines think about canonical urls that are redirects, so I'm not sure if `/page/...` is good either.

Here's how I'm handling it in our theme now: https://github.com/pallets/pallets-sphinx-themes/blob/a8338e573a762151e0352d9cdf5e03a5ef069774/src/pallets_sphinx_themes/__init__.py#L73-L84

**Comment by humitos** [comment]
> I'm not clear why it would be useful for the canonical URL to have the specific version slug in it, shouldn't every version have the same canonical?

I understand the canonical URL has to be explicit and contains the exact URL as a source of truth for the current content. In that case, the version slug and language slug are required.

> That said, I'm not sure what search engines think about canonical urls that are redirects, so I'm not sure if `/page/...` is good either.

I'm not sure, but I suppose that Google wouldn't like to have a canonical URL that is a redirect to something else.

**Comment by davidism** [comment]
We ended up dropping all our version builds for various reasons, and just moving to latest tracking main and a stable branch. Then we can point the canonical URL at stable at all times, and link to that as the current version at all times.

**Comment by humitos** [comment]
We have some docs now:

- Sphinx: https://docs.readthedocs.io/en/stable/intro/sphinx.html#set-the-canonical-url
- Material for MkDocs: https://docs.readthedocs.io/en/stable/intro/mkdocs.html#set-the-canonical-url

We will keep adding how to use the canonical URL in other frameworks as well.
