### ISSUE TITLE
Redirects: always show `forced` options

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#10863]
## What's the problem this feature will solve?

When hiding the `forced` option from redirects, users aren't aware about this functionality unless they read the docs, or may be confused for people reading the docs, since they won't see the option as described in the docs.

## Describe the solution you'd like

Instead of hiding this option when a project doesn't have support for it, we should show it in a disable state, and add a help message with the reason why it's disabled, or show a note about it at the top.

## Alternative solutions

Just add a note at the top of the redirect form.

## Additional context

- https://github.com/readthedocs/readthedocs.org/issues/10849

**Comment by humitos** [comment]
It makes sense to me showing the option in a disabled state with a `?` icon pointing to our docs 👍🏼
