### ISSUE TITLE
Exact redirect with force not working

### ISSUE THREAD

**Issue by jugmac00** [readthedocs/readthedocs.org#10862]
## Details

I created a redirect as following:

```
Exact Redirect
/reference/python.html -> https://canonical-launchpad-manual.readthedocs-hosted.com/en/latest/reference/python/
```
including "force", ie the redirect should happen even when the URL does exist.

* Read the Docs project URL: https://readthedocs.org/projects/launchpad/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/jugmac00/

## Expected Result

I expect the redirect to work.

## Actual Result

It does not work. When I access https://launchpad.readthedocs.io/en/latest/reference/python.html it does not get redirected to https://canonical-launchpad-manual.readthedocs-hosted.com/en/latest/reference/python/

**Comment by jugmac00** [comment]
Ok, it looks like I need to include the language and the latest part, which is kinda documented. So this can be closed.

**Comment by stsewd** [comment]
@jugmac00 if you want to redirect a file, you can use a Page Redirect instead, that redirect works for all versions of your project.
