### ISSUE TITLE
Build: add support for Go 1.21

### ISSUE THREAD

**Issue by simondeziel** [readthedocs/readthedocs.org#10884]
## What's the problem this feature will solve?

Some projects require Go 1.21 to build.

## Describe the solution you'd like

Go 1.21 is the current latest stable release and RTD should support it.

## Alternative solutions

N/A

## Additional context

https://go.dev/doc/devel/release

**Comment by humitos** [comment]
Thanks for the suggestion. I'm adding this to the roadmap so I can add support once we can prioritize it. Are you currently unable to build your documentation due to this or is it OK for now to keep using 1.20?

**Comment by simondeziel** [comment]
Thanks for asking! We reverted to using Go 1.21 for the interim so it's not an urgent matter for now, thanks!

**Comment by humitos** [comment]
@simondeziel we've done a deploy today, you should be able to use Go 1.21 now. Let me know if it works as expected.
