### ISSUE TITLE
Manual webhook setup Github token

### ISSUE THREAD

**Issue by daquinteroflex** [readthedocs/readthedocs.org#10894]
Hi,

I was curious when this manual webhook Github token was going to be implemented. Does this currently have an effect on security with manual configurations?

https://github.com/readthedocs/readthedocs.org/blob/6410aa04d721d3c6669ae8c324f74036858db062/docs/user/guides/setup/git-repo-manual.rst?plain=1#L58

Cheers,
Dario

**Comment by daquinteroflex** [comment]
I've tried this. From what I can gather, is that until the `token` gets implemented for verification. Say, we won't be able to have an external API or even Github from a different user or organization, triggering the .readthedocs.yaml build for the particular repository that is loaded as part of the owner organization?

**Comment by stsewd** [comment]
Hi @daquinteroflex thanks for bringing this to our attention, we will be changing this, so integrations are always created with a secret. We will post an update about this early next week.

**Comment by stsewd** [comment]
We decided to do a security release, since abusing webhooks without a secret could be a problem https://blog.readthedocs.com/security-update-on-incoming-webhooks/. Thanks again for bringing this issue to our attention!
