### ISSUE TITLE
"Module not found error" thrown by myst-nb while running a jupyter notebook

### ISSUE THREAD

**Issue by dodu94** [readthedocs/readthedocs.org#10891]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/f4enix
* Build URL (if applicable): https://readthedocs.org/projects/f4enix/builds/22460764/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/Radiation-Transport-F4E/

## Expected Result

f4enix (the python module that I am documenting) should be correctly imported by the jupyter notebook included in the sphinx documentation.

## Actual Result

Checking https://f4enix.readthedocs.io/en/latest/examples/input/input.html , one can see how myst-nb throws a "Module not found error" when trying to import the module. This is weird, since locally it builds correctly and if it was an issue of missing dependencies I should get an error also when running autodoc, which instead works as expected.

**Comment by humitos** [comment]
Hi! If you want to document your own module, you have to install it by using `pip.install.method: pip` and `pip.install.path`. See https://docs.readthedocs.io/en/stable/config-file/v2.html#packages
