### ISSUE TITLE
Documentation missing for redirects

### ISSUE THREAD

**Issue by c19witness** [readthedocs/readthedocs.org#10905]
Page https://github.com/readthedocs/readthedocs.org/blob/main/docs/user/user-defined-redirects.rst has repeated use of "The example configuration would be" and then few lines of 'code` that would follow.  It's not clear where that configuration file is even if it is clear the lines are not Python or TOML/JSON/XML. Nor "front matter" of sorts.

The documentation would be even better if the `user-defined-redirects` page included more information about the location of the configuration file.

**Comment by humitos** [comment]
The documentation page is rendered at https://docs.readthedocs.io/en/stable/user-defined-redirects.html#exact-redirects-examples

The configuration it refers to is not to be included on any configuration file, but using the dashboard WebUI.
