### ISSUE TITLE
Fails to fetch tags when initializing the repository for ReadtheDocs build

### ISSUE THREAD

**Issue by Qizhen-Xue** [readthedocs/readthedocs.org#10923]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/nnabla/
* Build URL: https://readthedocs.org/projects/nnabla/builds/22626085/
* Read the Docs username: https://readthedocs.org/profiles/sirius229/

## Expected Result

Our project is using **Tags** to manage the release version. Previously before ReadtheDocs version update, the default git command will clone the whole repository and then checkout to the corresponding commit. At that time it all works fine.
After the recent ReadtheDocs update, we expect that the repository could fetch the corresponding tag with the default git command.

## Actual Result
The fetch fails due to git fetch command error.
![readthedocs_fetch_error](https://github.com/readthedocs/readthedocs.org/assets/91321484/bcb922f7-ad7a-4d2f-8571-1db1f51a4f8a)

## Suggested feature or behaviour
In my point of view, the fetch command should be `git fetch origin --force --prune --prune-tags --depth 50 refs/tags/v1.37.0:refs/remotes/origin/v1.37.0`. `refs/heads` should be replaced by `refs/tags`. 

I also noticed that the git commands are changed in https://github.com/readthedocs/readthedocs.org/pull/10430. Actually it does have an option to fetch tags, where is https://github.com/readthedocs/readthedocs.org/blob/12305bae59e2b5dccb3ecde88b9f94a4aa0473b7/readthedocs/vcs_support/backends/git.py#L150
However, I could not find a way to define `version_type` and `verbose_name` by myself. I also tried to set the environment variable to `READTHEDOCS_VERSION_TYPE` to be `tag`. But it's not allowed to set such an variable start with READTHEDOCS.

@humitos , sorry it might bother your work. But do you have any opinion that I could set my build job's version_type to be tag? Or if you have any other solution for this issue, please kindly give me some suggestion. I'm not sure if this problem is a bug or not. If so, I believe there should be many other projects would meet the same error. I've seen https://github.com/readthedocs/readthedocs.org/issues/10915, but it's not quite the same situation as it's not using tags to manage the release version. Now our release process is just in progress and blocked by this document build failure. Thanks for any help!

**Comment by Qizhen-Xue** [comment]
> Hi, this case should already be supported with #10738. Looks like your project hasn't triggered a build in a while, so it hasn't caught up with that change.
> 
> In order to fix this, you'll need to re-sync your versions, this is done automatically after clone, but since your project fails in that step, the sync never happens. I have manually triggered a sync for your project, you should be able to use the new tag now.
> 
> For users hitting this, you can solve it by triggering a build of an existing version (this will re-sync your versions to use the proper version type for latest). After that you should be able to trigger a build for latest. I'll see if we can detect all projects hitting this to trigger a re-sync for those.

Thanks a lot! It does work now.

**Comment by stsewd** [comment]
@Qizhen-Xue you can solve this by triggering a build on an existing version, but looks like you already did that

![Screenshot 2023-11-28 at 10-09-27 Builds Read the Docs](https://github.com/readthedocs/readthedocs.org/assets/4975310/a5ed789e-1c85-4b21-a80a-4b3618181f77)

Your problem should be solved

**Comment by Qizhen-Xue** [comment]
> @Qizhen-Xue you can solve this by triggering a build on an existing version, but looks like you already did that
> 
> ![Screenshot 2023-11-28 at 10-09-27 Builds Read the Docs](https://private-user-images.githubusercontent.com/4975310/286301761-a5ed789e-1c85-4b21-a80a-4b3618181f77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExODQ1MTIsIm5iZiI6MTcwMTE4NDIxMiwicGF0aCI6Ii80OTc1MzEwLzI4NjMwMTc2MS1hNWVkNzg5ZS0xYzg1LTRiMjEtYTgwYS00YjM2MTgxODFmNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjhUMTUxMDEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjU3MGMzZDllNGZlNGU4NjBhZTI1MDdiODRmOTc2ZjdmYmY4Y2Y1NDk3NGFiZjFkYTRiZjgyM2JlMzlhNGZkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.INXh-6jye5ZEfHB3YyNe_eFX5ctM2I5mKvm4jCUkgsI)
> 
> Your problem should be solved

Thank you for your information again! I do expect this trigger could solve my problem but it didn't work at the beginning. Now after further investigation, I found that it will only works after I trigger a build with both default version and default branch to be `v0.15.0`. Only default version `v0.15.0` and keep the default branch to be empty could not solve the problem. Moreover, once it successfully switch to `refs/tags`, I could only set `latest` branch points to a tag but no more branch such as master.
