### ISSUE TITLE
Build error with build id #22783920

### ISSUE THREAD

**Issue by tchaddad** [readthedocs/readthedocs.org#10946]
## Details:

* Project URL: https://readthedocs.org/projects/wcodp/
* Build URL(if applicable): https://readthedocs.org/projects/wcodp/builds/22783920/
* Read the Docs username(if applicable): tchaddad

## Expected Result

I am following these docs for using conda as my python environment: 

- https://docs.readthedocs.io/en/stable/guides/conda.html
- https://docs.readthedocs.io/en/stable/config-file/v2.html#conda

I am successfully able to build these docs with the Read the Docs Theme locally, and would like them to build in ReadtheDocs directly.

## Actual Result

The build online is failing. It seems to be **unable to create the conda environment**, and so never gets to the actual building the docs step. I'm a little lost on what I could be doing wrong...

**Comment by humitos** [comment]
it seems your `docs/environment.yml` file is encoded with UTF-16 and Read the Docs is expecting UTF-8. Please, try re-saving the file with UTF-8 encoding and it should solve the problem.

**Comment by tchaddad** [comment]
Thanks @humitos!  - this did the trick, and I'm not sure I would have figured it out without your tip!
