### ISSUE TITLE
`builds.tools.python: 3` documented, but not working

### ISSUE THREAD

**Issue by FriedrichFroebel** [readthedocs/readthedocs.org#10942]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pycaching/
* Build URL (if applicable): https://readthedocs.org/projects/pycaching/builds/22752032/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/FriedrichFroebel/

## Expected Result

```
build:
  os: ubuntu-22.04
  tools:
    python: 3
```

should work or throw a meaningful error message that the Python version should be a string.

## Actual Result

I am told that `3` is an invalid value, while the value itself occurs inside the list of allowed values:

> Problem in your project's configuration. Invalid configuration option "build.tools.python": expected one of (2.7, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, 3.12, 3, miniconda3-4.7, mambaforge-4.10, mambaforge-22.9), got 3

Only https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python seems to indicate that the value needs to be a  string.

**Comment by stsewd** [comment]
Hi, you need to use quotes to force the value to be string, see https://github.com/readthedocs/readthedocs.org/issues/9719. Sorry about the confusion.
