### ISSUE TITLE
Support for nested GitLab orgs

### ISSUE THREAD

**Issue by mathstuf** [readthedocs/readthedocs.org#10940]
I haven't run into this my self yet, but GitLab supports nested orgs, so `{user}/{repo}` doesn't work unless `user` is something like `org/suborg`. Something to think about at least; it's not urgent from my side at least.

**Comment by humitos** [comment]
HI @mathstuf! Can you please expand on what's the issue you are reporting here? It's not clear to me how that affect Read the Docs. Thanks.

**Comment by mathstuf** [comment]
URL construction seems to assume that URLs have just a `user` and a `repo` field when they could be `someorg/suborg/nestedorg/repo`. Maybe stuffing the extra components into one of the two fields works, but I would guess that they are used elsewhere in places that `/` may confuse other things.

**Comment by humitos** [comment]
@mathstuf is this affecting Read the Docs?

**Comment by mathstuf** [comment]
I don't know. Maybe someone tried to do something with a nested repo and migrated to a flatter layout instead? I intend this as a "there may be an issue" notification (in the vein of other issues we've found based on self-hosted GitLab instance support).

**Comment by humitos** [comment]
OK. Thanks for reporting it. I will close this issue then until we can confirm this is affecting us in some fashion. In that case, we can re-open 👍🏼
