### ISSUE TITLE
 Documentation needs to be removed

### ISSUE THREAD

**Issue by SevaraAkhtyamova** [readthedocs/readthedocs.org#10958]
We have a outdated documentation and can not delete it. Because of this our clients get a wrong information.

## Details

* Read the Docs project URL: no
* Build URL (if applicable): https://sdk-new.readthedocs.io/en/latest/index.html
* Read the Docs username (if applicable): no

**Comment by humitos** [comment]
> We have a outdated documentation and can not delete it

Why you can't delete it?

**Comment by SevaraAkhtyamova** [comment]
The documentation was written by the developer who quit many years ago. The repository and ''Read the docs'' project are linked to his email. We asked to delete the project him. He can not log in and do it. Also, now,  ''Read the docs'' project does not exist on site.
