### ISSUE TITLE
Interaction between redirects and trailing slashes

### ISSUE THREAD

**Issue by jeanas** [readthedocs/readthedocs.org#10962]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/rtd-redirects-test/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/jeanas/

## Expected Result

There are two redirects on this test project (which is a copy of the Python Packaging User Guide where I'm experimenting with redirects):

- Page redirect: `/additional` → `/guides/`
- Page redirect: `/current/` → `/guides/tool-recommendations/`

I expected redirects to work regardless of whether the URL has a final slash or not.

## Actual Result

With this,

- https://rtd-redirects-test.readthedocs.io/en/latest/additional works as expected
- https://rtd-redirects-test.readthedocs.io/en/latest/additional/ (with a trailing slash) yields a 404
- https://rtd-redirects-test.readthedocs.io/en/latest/current/ (with trailing slash) works as expected
- https://rtd-redirects-test.readthedocs.io/en/latest/current (no trailing slash) yields a 404

IOW, with the dirhtml builder of Sphinx, every moved page needs **two** redirects — one with trailing slash and one without.

**Comment by stsewd** [comment]
Hi, we are in the process of re-working our redirects feature. This use case will be solved with https://github.com/readthedocs/readthedocs.org/pull/10881.
