### ISSUE TITLE
Error while building the project. Unsure where the problem lies in project configuration.

### ISSUE THREAD

**Issue by hbshrestha** [readthedocs/readthedocs.org#10966]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/splat-tutorial/
* Build URL (if applicable): https://readthedocs.org/projects/splat-tutorial/builds/22931507/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/hbshrestha/

## What I did?
**Added the `.readthedocs.yml` file, which is a new requisite to build the model:**

I added the `.readthedocs.yaml` [file](https://github.com/SPLATteam/SPLAT-WebGuide/blob/main/.readthedocs.yaml) on the topmost path of the repository. I copied the suggested template for the `.yaml` file from [here](https://docs.readthedocs.io/en/stable/config-file/index.html).  I only out-commented the formats to allow pdf and epub.
![image](https://github.com/readthedocs/readthedocs.org/assets/50154485/9b8ea91e-1a77-4f6f-b4b4-73616b0d568f)

The configuration [file](https://github.com/SPLATteam/SPLAT-WebGuide/blob/main/docs/conf.py) and the path is the same. 
I only commented the formats in `conf.py` because it is now there in the `yaml` file.
![image](https://github.com/readthedocs/readthedocs.org/assets/50154485/7f10bc64-a585-4cae-8cc4-7eaa4debfe85)

## Expected Result
I expected the build to be complete without any issue.
Existing status of the project on the web: https://splat-tutorial.readthedocs.io/en/latest/

## Actual Result
I got an error while building the project as shown:
![image](https://github.com/readthedocs/readthedocs.org/assets/50154485/2f9d7670-49e5-46e4-be92-1dbe00256af9)

*A description of what actually happened*
I am not sure where the problem lies in building the project. How should the `*.yaml` file be modified to complete the build without the error?

**Comment by agjohnson** [comment]
The configuration file is indeed being found and read fine, that doesn't seem to be an issue. Looking at that build, the error is a project misconfiguration, namely you aren't installing the package `sphinx_rtd_theme`. You can see the error that cause the build to fail if you scroll down on that page.

You should look into defining all of your dependencies for your project:
https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html

**Comment by hbshrestha** [comment]
Thank you!
I was able to resolve the issue and complete the build by adding the `docs/requirements.txt` file with the dependencies.
![image](https://github.com/readthedocs/readthedocs.org/assets/50154485/29e879d5-d357-4a9c-adf7-39f6430e3e05)
