### ISSUE TITLE
Notifications: create notifications for projects with `skip=True`

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#10980]
Projects with `skip=True` used to show a hard coded template notification at

https://github.com/readthedocs/readthedocs.org/blob/12ac09fc8bef5888b81d603e0f5463ffd354b5b0/readthedocs/templates/core/project_bar_base.html#L32-L41

Now, with the new notification system we have lost that and we have to:

- [x] create a `Notification` object for each of these projects currently skipped
- [ ] create a Django signal to create a new `Notification` object when this field changes to `skip=True`
- [ ] create a Django signal to cancel the `Notification` when this `skip=False`

**Comment by humitos** [comment]
I created a script at https://gist.github.com/humitos/b5fec6d741a19ee1762ebe39c7d203aa that migrates:

* projects with `skip=True` and creates a `Notification` object for them
* builds with `.error` field populated and creates a `Notification` object for them mapping the old -> new message

I tested this script locally and it worked fine. We should run it after performing the deploy of the new notification system. I focus only on all builds from 2023 and 2024. If we want to go further back in time, we will need to define more message mappings.

I'm not too worried about missing a mapping or similar since usually errors on old builds are not super useful, anyways.

**Comment by agjohnson** [comment]
Also, we might not have a lot of project with this attribute. Even if we aren't doing a larger migration, we might just do a one-off solution here and make the necessary notification instances manually.

**Comment by humitos** [comment]
We talked in chat about this and we decided to only run the migration for `Project.skip=True` and keep the old `Build.error` messages around while maintaining the KO code to render them. This means reverting this commit: [`d4951a8` (#10922)](https://github.com/readthedocs/readthedocs.org/pull/10922/commits/d4951a83d226d9b6c539cc53166e5c9d53e426f7)

There won't be "duplicated notifications on builds" because the after merging #10922 we stop populating the `Build.error` field and start creating `Notification` objects instead. So, old builds will render the old field `Build.error` and new builds will render the new `Notification` objects 👍🏼 

The only required part of the migration script is for `Project.skip=True`:

```python
import structlog
from readthedocs.projects.notifications import MESSAGE_PROJECT_SKIP_BUILDS

log = structlog.get_logger(__name__)


# Migrate notifications for projects skipped
for project in Project.objects.filter(skip=True):
    log.info("Creating project skipped notification.", project_slug=project.slug)
    Notification.objects.add(
        attached_to=project,
        message_id=MESSAGE_PROJECT_SKIP_BUILDS,
        dismissable=False,
    )
```

In the future, if we change our mind or we want to go with the bigger `Build.error` -> `Notification` migration, we can do it using the script I wrote.

Slack conversation: https://readthedocs.slack.com/archives/C02DNG2HSNP/p1704296581578539?thread_ts=1704293584.321199&cid=C02DNG2HSNP

**Comment by humitos** [comment]
Projects with `skip=True` are already migrated to the new notification system.
