### ISSUE TITLE
Notifications: remove extra indentation and trailing newlines

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#10987]
I've found myself wanting to write the copy for all the messages in a simple way that avoid indentation and punctuation mistakes and I'm happy with the result so far. However, the downsides they have is they return they messages as `\n     \n    Please try...` (note the `\n` and the extra spaces).

I'd like to remove those automatically somehow without changing the way we write down the copy for these messages if possible.

We discussed this a little at https://github.com/readthedocs/readthedocs.org/pull/10922#discussion_r1440114956 where I exposed what I ideally want.

Example in the code:

https://github.com/readthedocs/readthedocs.org/blob/7d1daeeee24a0e70ffcf0debd6836c02d0b36ec3/readthedocs/notifications/messages.py#L71-L78

**Comment by stsewd** [comment]
You can use `textwrap.dedent` + `string.strip`.

```python
import textwrap

s = textwrap.dedent(
    """
    Foo

    bar
    """
).strip()
```

**Comment by humitos** [comment]
That works great!

However, it seems that `textwrap.dedent` does not support a translated string? Weird.

```
build_1        |   File "/usr/src/app/checkouts/readthedocs.org/readthedocs/core/admin.py", line 17, in <module>
build_1        |     from readthedocs.oauth.tasks import sync_remote_repositories
build_1        |   File "/usr/src/app/checkouts/readthedocs.org/readthedocs/oauth/tasks.py", line 15, in <module>
build_1        |     from readthedocs.oauth.notifications import (
build_1        |   File "/usr/src/app/checkouts/readthedocs.org/readthedocs/oauth/notifications.py", line 16, in <module>
build_1        |     Message(
build_1        |   File "/usr/src/app/checkouts/readthedocs.org/readthedocs/notifications/messages.py", line 20, in __init__
build_1        |     self.header = textwrap.dedent(header).strip()
build_1        |   File "/usr/lib/python3.10/textwrap.py", line 438, in dedent
build_1        |     text = _whitespace_only_re.sub('', text)
build_1        | TypeError: expected string or bytes-like object
```

**Comment by agjohnson** [comment]
+1 on dedent here

It looks like you are effectively doing `textwrap.dedent(_("..."))` though

To both make the source easy to work with and also solve the issue of the translations including extraneous whitespace, you probably need `_(textwrap.dedent("..."))`.

**Comment by agjohnson** [comment]
Noted at https://github.com/readthedocs/readthedocs.org/pull/10922#discussion_r1440905860

> However, it might be best to avoid altering our translation files until these strings are resolved. I don't quite know how gettext handles moved strings vs moved and altered strings, but I suspect the additional whitespace could throw off all the existing translations.

I'll add this to this sprint, as I'd like to help translators as much we can here. I don't really know if it matters though. Moving the string is probably already a somewhat breaking change.

**Comment by humitos** [comment]
> It looks like you are effectively doing `textwrap.dedent(_("..."))` though
> To both make the source easy to work with and also solve the issue of the translations including extraneous whitespace, you probably need `_(textwrap.dedent("..."))`.

Yes, I tried doing the first approach because doing `_(textwrap.dedent())` means doing it in _all the strings_ instead of just once. However, it seems the shortcut I want to follow is not possible here and I will need to re-write all the strings 😞

**Comment by agjohnson** [comment]
Yeah, I figured we'd have to do something like this, unfortunately. Multiline strings are always a pain.

I do believe there is magic you can do with gettext and creating your own gettext wrappers, but this is almost certainly way too deep.

**Comment by humitos** [comment]
I don't know exactly how gettext works internally, but I assumed that if I do `_(textwrap.dedent(header).strip())` inside the initializer at https://github.com/readthedocs/readthedocs.org/blob/24bd75d9208e64de6c670da0d1e5d48a2b49b9ec/readthedocs/notifications/messages.py#L25 the translation string won't get identified by gettext and exposed to be translated. If that works, we can write this only once, but I'm not sure how to test it.

**Comment by humitos** [comment]
I understand that we can't translate variables in a simple way:

> (The caveat with using variables or computed values, as in the previous two examples, is that Django’s translation-string-detecting utility, django-admin makemessages, won’t be able to find these strings. More on makemessages later.)

_(from https://docs.djangoproject.com/en/5.0/topics/i18n/translation/#standard-translation)_

I think what I've done here is the way to go, unfortunately 😞
