### ISSUE TITLE
Notifications: audit and tune notification body and subject copy

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#10985]
In #10922 I migrated all the messages exposed to users to the new notification system, but I haven't change them. There are plenty of them that are not super clear and can be improved to communicate the message in a simpler way.

Besides, since there is a new `header` copy now, we should decide how they are going to be shown to users and make them work in that context as well.

* Example: https://github.com/readthedocs/readthedocs.org/pull/10922#discussion_r1440146221
* Missing header: https://github.com/readthedocs/readthedocs.org/pull/10922#discussion_r1440125283
* Default header: https://github.com/readthedocs/readthedocs.org/pull/10922#discussion_r1440130523

**Comment by agjohnson** [comment]
I'm happy to help with some of the copy and grammar fixes here. There will be a fair amount to go through, I wasn't thorough in my review.

**Comment by humitos** [comment]
These are all the issues that I quickly found where users were confused about the error displayed:

* #10502
* #9008
* #6569
* #7707
* #8482
* #8352
* #9458 
* #9713
* #9365

**Comment by humitos** [comment]
Some of the issues linked here will require modifications in the `Config` validation object, not only improves in the error messages. We can track those as a different set of work.
