### ISSUE TITLE
Conda requirements install is broken

### ISSUE THREAD

**Issue by chuckthepiranha** [readthedocs/readthedocs.org#11006]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/eden
* Build URL: https://readthedocs.org/projects/eden/builds/23038816/

## Expected Result

These commands should run:

```
cat docs/requirements.yaml
conda env create --quiet --name latest --file docs/requirements.yaml
```

## Actual Result

This runs and fails:

```
python -mvirtualenv $READTHEDOCS_VIRTUALENV_PATH
```

A condo environment should be used, not a virtualenv.

**Comment by humitos** [comment]
You are using `build.tools.python: "3.8"` when you should be using Mamba or Conda there. See https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python

We are working to improve the error message so it's clearer what's happening here and how to solve it.
