### ISSUE TITLE
Development: double check `nodejs` versions

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#11008]
We are using nodejs v8.16 on development https://github.com/readthedocs/readthedocs.org/blob/6e7b0b470b91ca4b456930c0834d47f8abf9373d/dockerfiles/docker-compose-assets.yml#L5

but nodejs 10.17.0 on CircleCI https://github.com/readthedocs/readthedocs.org/blob/6e7b0b470b91ca4b456930c0834d47f8abf9373d/.circleci/config.yml#L63-L64

What's the correct version we should use?

I remember that _I pin_ the development instance to v8.16 because that was what we were using to build the assets locally some time (years?) ago and it was a working version. I'm not sure we can upgrade that nodejs version to a newer one. However, we may want to use a _different_ version for running `eslint` checks locally.

Reference: https://github.com/readthedocs/readthedocs.org/pull/10998

**Comment by agjohnson** [comment]
Node 8 is ancient. We should use Node 10 if the build process is working with that version.

**Comment by humitos** [comment]
I found another mismatch on the versions 😄 

If you jump into the Docker container and run `tox -e eslint`, it will use the Ubuntu's default installed version: `v12.22.9`

**Comment by agjohnson** [comment]
I actually was going to say that <14 might be safe even. I think 10 might have just been the last working version at the time. But 10 should definitely be the minimum

**Comment by humitos** [comment]
A lot of this code will be deleted once we are fully migrated into the new dashboard. That is on March, 2025. See https://about.readthedocs.com/blog/2024/11/rollout-of-our-new-dashboard/
