### ISSUE TITLE
Unable to sign in and not recieving verification emails. Can't create new account because email is already used....

### ISSUE THREAD

**Issue by utlco** [readthedocs/readthedocs.org#11004]
I have an account that's likely been disabled due to disuse (it's been probably ten years since I last logged in). However it still hosts some documentation for a github project (https://tcnc.readthedocs.io) and I'd like to add another project. The sign in notice asks that I contact readthedocs if I have don't receive a verification email, but contacting support requires signing in... I tried the password reset but did not receive an email for that either. So I'm trying here.

My username is "utlco" and my email address is "claude@utlco.com".

Would it be possible to either re-activate my account or delete it so I can re-use the email address? I'd like to be able to manage the existing project docs so keeping the old account would be ideal.

Thank you!

**Comment by humitos** [comment]
@utlco please send us an email to support@readthedocs.org
