### ISSUE TITLE
Notifications: think more about how to render them safely

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#11022]
@stsewd mentioned a few times that we need to escape all the values we render in the notifications that comes from the user. Due to that, we implement this small trick to run `escape()` on each of them: https://github.com/readthedocs/readthedocs.org/pull/10996

However, we are _always_ passing the `instance` the notification is attached to (User, Project, Organization, Build, etc) to the `Message` class to have access to all of fields from it. Due to that, there are some fields like `project.name` where the user has control and we have to `escape()` somehow.

I see two possible paths here:

1. change the rendering engine from regular Python `.format()`s + trick to call `escape()` on all the fields and use something like Jinja or regular Django Template Engine where we can call `{{ project.name|escape }}`
2. write an improve for the current rendering engine that it's always safe. Maybe using `.format_map` with a custom `dict` class that call `escape()` on `__getitem__` (https://docs.python.org/3/library/stdtypes.html#str.format_map)

* Related: https://github.com/readthedocs/readthedocs.org/pull/10922#discussion_r1440756414
* Related: https://github.com/readthedocs/readthedocs.org/pull/11018

**Comment by stsewd** [comment]
I think using Django's template engine should be fine, since it escapes all values by default.
