### ISSUE TITLE
Addons: add historical models to `AddonsConfig`

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#11125]
It would be good to add historical models to the addons configuration so we can understand what are the features project has enabled, but also track them as time series and make better decisions on feature usage.

I haven't used this pattern, but I suppose we have everything in place already and it shouldn't be hard to implement, right? cc @stsewd

**Comment by stsewd** [comment]
You only need to add this manager to the model https://github.com/readthedocs/readthedocs.org/blob/f283500df8267ec75d06928a56df03cbc8c3e5c8/readthedocs/core/models.py#L63-L63
