### ISSUE TITLE
Build stops after `git clean -d -f -f`

### ISSUE THREAD

**Issue by microbit-carlos** [readthedocs/readthedocs.org#11138]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/microbit-micropython
* Build URL (if applicable): https://readthedocs.org/projects/microbit-micropython/builds/23532431/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/microbit-carlos/

## Expected Result

The build to not stop after `git clean -d -f -f`

## Actual Result

After that command completes successfully the build stops and it's marked as failed.
https://readthedocs.org/api/v2/build/23532431.txt

<img width="854" alt="image" src="https://github.com/readthedocs/readthedocs.org/assets/29712657/8e5b463a-1940-49a8-bec0-25c8074fd710">

**Comment by stsewd** [comment]
Hi, your repository is missing a configuration file. A configuration file is now required to build on RTD. You can check our tutorial at https://docs.readthedocs.io/en/stable/config-file/index.html, and reference at https://docs.readthedocs.io/en/stable/config-file/v2.html.

We are tracking the issue about providing a better error message at https://github.com/readthedocs/readthedocs.org/issues/10502.
