### ISSUE TITLE
Notifications: always show notifications on build details' page

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#11146]
It seems that in https://github.com/readthedocs/readthedocs.org/pull/11117 we introduced a bug that it only shows the notifications for the build to users that have permissions over that project in particular --which is wrong. Since the project is public, it should show the notifications to all the users with access to the build detail's page.

**Comment by taylorhummon** [comment]
I've recreated the issue with a minimal install at:
https://github.com/taylorhummon/silently-failing-build
See: 
https://readthedocs.org/projects/silently-failing-build/builds/23550653/
