### ISSUE TITLE
Search textbox requires login to find!

### ISSUE THREAD

**Issue by jidanni** [readthedocs/readthedocs.org#11142]
Let's say we are on
https://readthedocs.org/projects/osgeo-proj/downloads/

and we want to do a search,
e.g., https://readthedocs.org/search/?q=proj&type=file

Well the search window is only on
https://readthedocs.org/dashboard
which requires login!

Therefore the search window should be on the other pages too.

**Comment by agjohnson** [comment]
This search interface is intended only for maintainers, which is why it requires authentication. Are you looking for a public search interface, perhaps for anyone reading your documentaiton? We point most folks towards using search from their documentation in this case.

**Comment by jidanni** [comment]
All I know is on https://proj.org/ by clicking several times mainly in the lower left corner I ended up at the first link I posted and thought it was great so wanted to find more.

Well then https://proj.org/ shouldn't have that link on it.

**Comment by agjohnson** [comment]
The per-project dashboard search is somewhat usable, which is available here or the "Search" tab on the project dashboard page:
https://readthedocs.org/search/?q=project:osgeo-proj%20

However, this is intended to be superseded by a feature that is currently in beta, [Addons](https://github.com/readthedocs/addons). We intend to surface our search *inside* project documentation instead of pointing the user to our application.

**Comment by jidanni** [comment]
> a little misleading.

All I know is on https://proj.org/

![20240227T135604](https://github.com/readthedocs/readthedocs.org/assets/1230959/bd5b96f1-fe16-4df1-b4c9-715ca5674d02)

Version 9.3 of Readthedocs? No. It's of Proj.

Versions: seem like they might be document packages but they are full
trees.

Downloads: OK these are documents.

On Read the Docs: OK, I guess.

On GitHub: These are not user-ready, but instead source.

**Comment by humitos** [comment]
I understand the confusion was cleared here and the new beta dashboard won't expose this view to users. I'm closing this issue since there is no action from our side to take here. However, feel free to comment here and re-open if you consider.
