### ISSUE TITLE
Build with poetry: failure to see installed packages

### ISSUE THREAD

**Issue by ewjoachim** [readthedocs/readthedocs.org#11149]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/procrastinate
* Build URL (if applicable): https://readthedocs.org/projects/procrastinate/builds/23555034/
* Read the Docs config: https://github.com/procrastinate-org/procrastinate/blob/main/.readthedocs.yml
* Sphinx config: https://github.com/procrastinate-org/procrastinate/blob/main/docs/conf.py

So: I'm installing my dependencies from Poetry, including a `docs` dependency group (not an extra, a dependency group, that's a poetry thing that's supported by RTD, as per the documentation). Then it looks like it's missing dependency that have been installed.

## Expected Result

Doc should build. And used to build. It [worked](https://readthedocs.org/projects/procrastinate/builds/23497155/) 5 days ago, and fails now.

## Actual Result

Failure: https://readthedocs.org/projects/procrastinate/builds/23555034/
`Could not import extension myst_parser (exception: No module named 'myst_parser')`

I can see the `myst-parser` package is installed in the `poetry install` step, and yet when trying to import it, the package isn't found.

Notes:
- The [readthedocs.yml](https://github.com/procrastinate-org/procrastinate/blob/main/.readthedocs.yml) is slightly not configured like [the doc says](https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry) (it's configured as the doc used to say) but I've tried [fixing that](https://github.com/procrastinate-org/procrastinate/pull/946/commits/9914d9693cbc526645eefdb3ac650c8a03bbacf3) and it [failed identically](https://readthedocs.org/projects/procrastinate/builds/23555238/).
- `myst-parser` is one of those packages for which the package name has a `-` and the import name has a `_`, but I've checked, and I'm using the correct name in `pyproject.toml`, and in `conf.py`.
- Would it be possible that it could be a poetry/virtualenv issue ? The failing extension is the first extension in my list, I'll try changing the order and see if it fails on the first one. I think a possible cause for the issue would be that poetry actually ends up installing packages in a different env than being used by RTD (so `virtualenv.create false` would not be working?) In that case the issue would likely come from the [doc](https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry) ?

**Comment by ewjoachim** [comment]
Yep, I tried changing the order of `extensions` and I got [another](https://readthedocs.org/projects/procrastinate/builds/23555034/) `No module named x` error.

`poetry install` says `Skipping virtualenv creation, as specified in config file.`, so it understands correctly.

Somehow, the Python environment we use is not the same as the one Sphinx expects. And somehow, it changed in the last 5 days.

**Comment by ewjoachim** [comment]
Poetry is `1.8.0`, not updated since December.

**Comment by humitos** [comment]
Take a look at #11150. Sens related

**Comment by ewjoachim** [comment]
Indeed, I checked before posting that there wasn't already an open issue... and that was opened after mine :) At least it goes to show I'm not the only one impacted

Should we follow this issue here or in #11150 ? (Or maybe it's a poetry bug ?)

**Comment by humitos** [comment]
We can continue taking this in the other issue sin or seems more related with poetry than read the docs

**Comment by ewjoachim** [comment]
Ok.
