### ISSUE TITLE
Notifications: add a test for notifications on build detail's page

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#11157]
We should add a test for https://github.com/readthedocs/readthedocs.org/pull/11153.

I just merged it because I want to deploy it today since it's a bug that's affecting too many users.

**Comment by agjohnson** [comment]
It might be best to write these tests against the API, as the new dashboard will be loading these from there, not from templates.

**Comment by humitos** [comment]
IIRC, the API already have tests for this. The idea of this issue was to avoid re-introducing the bug that #11153 fixes. I'm fine skipping this issue, tho --since we won't be using the old dashboard in the future. Maybe this is a no-op issue at this point.

**Comment by ericholscher** [comment]
Is this done with https://github.com/readthedocs/readthedocs.org/pull/11208 ?

**Comment by humitos** [comment]
No. This is about adding a test case to avoid repeating the issue #11153 -- but it's kind of invalid at the moment since we re-implementing this work in the new dashboard via APIv3

**Comment by ericholscher** [comment]
This is for the old dashboard, closing.
