### ISSUE TITLE
OAuth: decide what to do with old Bitbucket integration

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#11162]
## What's the problem this feature will solve?

We currently have two Bitbucket social apps, `bitbucket` and `bitbucket_oauth2`, the former uses a deprecated/insecure OAuth protocol (v1). We no longer expose it to users, but we still have like 1K tokens/users. And recent versions of allauth no longer support that provider.

https://github.com/readthedocs/readthedocs.org/pull/11160

## Describe the solution you'd like

~Check if those tokens still work, and decide on further actions, maybe email users letting them know that they can connect to BB using our new integration.~ Remove all those integrations from the DB.

## Additional context

https://github.com/readthedocs/readthedocs.org/pull/11160

**Comment by humitos** [comment]
> We no longer expose it to users, but we still have like 1K tokens/users

I think users are not even able to use these accounts via the Bitbucket integration since we don't even expose them in the login form. So, I think this integration is currently useless and probably safe to remove.

**Comment by stsewd** [comment]
We have like ~500 users that don't have any other accounts connected on .org and 1 on .com. But they all have an email, so they can use the password reset workflow to access their accounts, but as mentioned by Manuel, they can't use the old BB integration to login anyway (or at least from the UI), since we don't expose it in our login form.

**Comment by ericholscher** [comment]
@stsewd I think we deleted the old integrations, but should probably email them first to explain the issue 👍

**Comment by stsewd** [comment]
> @stsewd I think we deleted the old integrations, but should probably email them first to explain the issue 👍

Not sure what the email would be about... User were never able to use it in the past, it was dead code basically. We could write the email about that, but not sure if it's helpful at all.

**Comment by ericholscher** [comment]
ah, ok. In that case I'm fine deleting them.

**Comment by stsewd** [comment]
>  Users couldn't login with that account?

Nope, we didn't expose that option in our login page. Most of those users had another account linked or a password.

**Comment by ericholscher** [comment]
Gotcha, then yea, let's just delete it.

**Comment by stsewd** [comment]
Deleted.
