### ISSUE TITLE
Unexpected `mkdocs` build failure: not using project's installed `mkdocs` extensions.

### ISSUE THREAD

**Issue by davidorme** [readthedocs/readthedocs.org#11167]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/safedata-validator
* Build URL (if applicable): https://readthedocs.org/projects/safedata-validator/builds/23590836/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/DavidOrme/

## Expected Result

I'm making sure a release branch builds MkDocs pages correctly on RTD. Recent releases on the same project built without problem. See for example, this build from last week, which succeeded:

https://readthedocs.org/projects/safedata-validator/builds/23516950/

## Actual Result

The new code doesn't have any changes to the RTD configuration or build process, but it fails. The package is installed using `poetry`  and the `pyproject.toml` file  includes all of the packages required to build the documentation in the `docs` group. I use `poetry install --with docs` to install the package requirements.

Looking at the logs, both builds successfully install via `poetry`. The earlier successful build then gets to the build step: `python -m pip install --upgrade --no-cache-dir mkdocs` and immediately finds all the required packages that have been installed by `poetry`. The failing build gets to the same step and does not find those installs, so installs the RTD standard `mkdocs` suite of packages and not the extra requirements included in `poetry`. So it fails when `mkdocs` tries to use those extensions.

I can't see what is causing this - I don't think I've changed anything that impacts this!

**Comment by collindutter** [comment]
Also facing this issue, our builds using poetry are suddenly failing. Have also made no changes to RTD or Poetry configuration. In our case the error is:

```
ERROR   -  Config value 'theme': Unrecognised theme name: 'material'. The available installed themes are: mkdocs, readthedocs
ERROR   -  Config value 'markdown_extensions': Failed to load extension 'pymdownx.highlight'.
ModuleNotFoundError: No module named 'pymdownx'
ERROR   -  Config value 'plugins': The "glightbox" plugin is not installed

Aborted with 3 configuration errors!
```

**Comment by davidorme** [comment]
Thanks for that edit @collindutter, I hadn't seen #11152 and can confirm that using `VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install` resolves the issue for me.
