### ISSUE TITLE
Cannot find module when mkdocs tries to build the site

### ISSUE THREAD

**Issue by dmundra** [readthedocs/readthedocs.org#11176]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/civicactions-handbook/
* Build URL (if applicable): https://readthedocs.org/projects/civicactions-handbook/builds/23605796/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/dmundra/

## Expected Result

Our builds were working, see this example https://readthedocs.org/projects/civicactions-handbook/builds/23494880/

## Actual Result

But then for this https://readthedocs.org/projects/civicactions-handbook/builds/23605796/ and subsequent builds we get this error:

```
Error: MkDocs encountered an error parsing the configuration file: while constructing a Python object
cannot find module 'materialx.emoji' (No module named 'materialx')
  in ".config/mkdocs.yml", line 22, column 22
```

I am not sure why and we haven't changed the configuration. I am testing upgrading Materials theme but running into a different module that cannot be found.

Am I missing anything in the mkdocs configuration that is causing the issue?

**Comment by agjohnson** [comment]
This is a bug introduced with Poetry 1.8:

- #11150 

You can find the explanation and a workaround there

**Comment by stsewd** [comment]
The solution is documented in our docs at https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-poetry

**Comment by dmundra** [comment]
Thank you @agjohnson and @stsewd. The addition of `VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH` to the install step fixed it for us.
