### ISSUE TITLE
Config validation error in build.os. Value os not found

### ISSUE THREAD

**Issue by derks** [readthedocs/readthedocs.org#11173]
Any help would be much appreciated... using pretty stock `.readthedocs.yaml` from the docs.

## Details

* Read the Docs project URL: https://readthedocs.org/projects/cement/
* Build URL (if applicable): https://readthedocs.org/projects/cement/builds/23604160/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/derks/

## Expected Result

Successful build.

## Actual Result

```
Error
Config validation error in build.os. Value os not found.
```

<img width="856" alt="Screenshot 2024-02-29 at 9 53 23 AM" src="https://github.com/readthedocs/readthedocs.org/assets/130503/77f682b6-a452-4a03-9933-ecaf505b77a9">

**Comment by stsewd** [comment]
Hi, you are missing using the `build.os` config value, see our docs for a quick start of a valid config file https://docs.readthedocs.io/en/stable/config-file/v2.html.

We should probably link to our docs when such errors appear.

**Comment by derks** [comment]
@stsewd thank you for the quick reply. Can you elaborate on what is not right in the `.readthedocs.yaml` configuration in the repo?

- https://github.com/datafolklabs/cement/blob/main/.readthedocs.yaml

**Comment by stsewd** [comment]
@derks looks like you have two cofig files https://github.com/datafolklabs/cement/blob/main/readthedocs.yml, you should delete the other one.

**Comment by derks** [comment]
Geeeeeeeeze.... not sure how I missed that :/. Thank you for the help... I'll try that now.

**Comment by derks** [comment]
@humitos thank you again for your help. I was able to fix `main` (latest) now... however I have having issues with building the `3.0` version (this is a Git tag). I tag `3`, `3.0` every time I make a `3.0.x` release, and this is the source for the `3.0` version. It seems that RTD is not pulling down the latest `3.0` tag, and therefore continues to fail.

Any insights? Is this a cache issue that will resolve itself, or is there anything we/I can do to force it along?

**Comment by stsewd** [comment]
@derks if you forced push the tag, you need to first build any other version for the commit to be updated first, after that you can trigger a build for it to pick the correct commit. See https://github.com/readthedocs/readthedocs.org/issues/10838.
