### ISSUE TITLE
Build: add support for Go 1.22

### ISSUE THREAD

**Issue by simondeziel** [readthedocs/readthedocs.org#11189]
## What's the problem this feature will solve?

Some projects require Go 1.22 to build.

## Describe the solution you'd like

Go 1.22 is the current latest stable release and RTD should support it.

## Alternative solutions

N/A

## Additional context

https://go.dev/doc/devel/release

**Comment by humitos** [comment]
Hi @simondeziel! Thanks for opening this issue. Would you mind posting the URL of the projects requiring Go 1.22? Thanks.

**Comment by simondeziel** [comment]
Hey @humitos, sure it's the LXD project where we are trying to switch to Go 1.22 for every bits https://github.com/canonical/lxd/pull/13042

**Comment by humitos** [comment]
Closing in favor of a more generic issue that will include this work as well: https://github.com/readthedocs/readthedocs.org/issues/11350
