### ISSUE TITLE
cannot set conf.py on readthedocs advanced settigns

### ISSUE THREAD

**Issue by RunningLeon** [readthedocs/readthedocs.org#11186]
hi, recently find that there's no option to set conf.py of sphinx as before. So how to set `docs/en/conf.py` and `docs/zh_cn/conf.py` for different languages?

![image](https://github.com/readthedocs/readthedocs.org/assets/28671653/23812842-a8a6-44a7-a2d1-6045ce7bd401)

**Comment by humitos** [comment]
Hi @RunningLeon 👋🏼 . We don't support setting build options from the WebUI anymore. Read more about this in https://blog.readthedocs.com/migrate-configuration-v2/

You need to add a `.readthedocs.yaml` file to your project and use `sphinx.configuration` to define your `conf.py`. See https://blog.readthedocs.com/migrate-configuration-v2/

Let us know if that works for you.

**Comment by RunningLeon** [comment]
@humitos hi, thanks for your quick reply. But it still cannot build docs of Chinese version. Here are steps done:
1  create `.readthedocs.yaml` and `.readthedocs-zh_cn.yaml` and set `confg.py` for each file in [PR](https://github.com/InternLM/lmdeploy/pull/1245/files).
2. Change to the path of config as `.readthedocs-zh_cn.yaml` and saved
3.  But as the PR triggers,  the build of zh-cn version still uses `.readthedocs.yaml` instead of `.readthedocs-zh_cn.yaml`

**Comment by humitos** [comment]
I suppose that you should be getting a form validation error since the filename must be called `.readthedocs.yaml`. It can be named differently. So, you may need to put it under a different directory, like `docs/zh-cn/.readthedocs.yaml`

**Comment by RunningLeon** [comment]
Hi, thanks. putting the file `.readthedocs.yaml` in docs/en and docs/zh_cn works.
