### ISSUE TITLE
Notifications: add django-messages message on project successfully removed

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#11192]
Removing a project could be a little clearer, just some feedback would be nice:

- Go to project settings
- Scroll down to remove project
- Click remove project
- Confirm remove project
- Redirect goes to dashboard but no confirmation

For similar actions we emit a Django message (toast message in our UI).

**Comment by ericholscher** [comment]
@agjohnson It seems like this is already setup in the code?

https://github.com/readthedocs/readthedocs.org/blob/d406770acfd51f497fe54ac6e47e075311237768/readthedocs/projects/views/private.py#L209-L210

**Comment by ericholscher** [comment]
Looking at it more, it seems like the vanilla views package doesn't implicit this logic, so all of our success_messages are likely not being shown? 🙃

**Comment by ericholscher** [comment]
> Looking at it more, it seems like the vanilla views package doesn't implicit this logic, so all of our success_messages are likely not being shown? 🙃
> 
> Confirmed this by doing a project update, and there's no messages shown at all:
> 
> [readthedocs.org/readthedocs/projects/views/private.py](https://github.com/readthedocs/readthedocs.org/blob/d406770acfd51f497fe54ac6e47e075311237768/readthedocs/projects/views/private.py#L191-L193)
> 
> Lines 191 to 193 in [d406770](/readthedocs/readthedocs.org/commit/d406770acfd51f497fe54ac6e47e075311237768)
> 
>  class ProjectUpdate(ProjectMixin, UpdateView): 
>      form_class = UpdateProjectForm 
>      success_message = _("Project settings updated")


@humitos @stsewd Do y'all remember these working at some point? I thought we had messages for this, but even in the old dashboard I'm not seeing any.

**Comment by agjohnson** [comment]
Ah, that would make a lot of sense then. I have actually noticed some cases where this _did_ work (and thought is was quite nice UX we should be using more broadly), but I don't recall what forms/views.

**Comment by ericholscher** [comment]
@agjohnson Yea, we've forcing it in a couple places on Delete's specifically. Should be able to copy similar logic probably for the other views, but it's a shame it isn't built in to vanilla-views from what I can tell.

**Comment by agjohnson** [comment]
Yeah, that's unfortunate. Maybe this is a much larger project then, but the benefit might also be a lot higher impact too -- getting us notifications on most all of our forms hopefully? We can push this out if so, I didn't look into why the notification was missing originally.

**Comment by stsewd** [comment]
> > Looking at it more, it seems like the vanilla views package doesn't implicit this logic, so all of our success_messages are likely not being shown? 🙃
> 
> @humitos @stsewd Do y'all remember these working at some point? I thought we had messages for this, but even in the old dashboard I'm not seeing any.

I know that views need to inherit from a mixin for the message to work https://docs.djangoproject.com/en/5.0/ref/contrib/messages/#adding-messages-in-class-based-views

**Comment by agjohnson** [comment]
I just found the view I was thinking of, it was on the organization team member invite form. Inviting a team member gives a nice toast message "Invite sent".

**Comment by humitos** [comment]
Lately, the only place where I've seen them is when logging in:

![Screenshot_2024-07-09_11-39-05](https://github.com/readthedocs/readthedocs.org/assets/244656/896ec339-9643-4368-9336-13a80962dba6)

**Comment by ericholscher** [comment]
I'm doing a project to refactor the settings to use this as a base class for all the admin views 👍
