### ISSUE TITLE
Notification: beta swap template logic fixes

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#11209]
While working on #11208 I found issues likely affecting the beta notification message. Just noting for now:

- When on the beta dashboard, `{{ PRODUCTION_DOMAIN }}` is `beta.readthedocs.org`, not `readthedocs.org`. The link should use PRODUCTION_DOMAIN|slice:"5:" or similar
- It's not possible to link to the commercial dashboard beta with simply `beta.readthedocs.com/projects/foo`, as this will always 404 if the user is not logged in. Instead #11208 links to the login view first, to ensure the user is always seeing the login first if they are not logged in yet.
- The header can be conditional too, and "You are using our new beta dashboard" on the beta instance.

This notification is getting into some complex area already, it might be also worth implementing the last part that #11208 added, which was linking to the same url between both dashboards.

**Comment by agjohnson** [comment]
I'm still waiting on this one as we are just getting to testing auth. When we are closer to giving users the new auth pages I'll have more interest in doing this for both sites.

**Comment by humitos** [comment]
We have auth pages already working on new `web-ext-theme`. I'm testing this in https://docs.ops.verbthenouns.com/ for now, and I'm planning to test it on a customer domain next. See https://github.com/readthedocs/readthedocs-corporate-ops/issues/893

It would be good if we can move forward with this, so we can migrate more users to the new templates soon 🎉 . We are pretty close 😄
