### ISSUE TITLE
Installing `rsync` by default

### ISSUE THREAD

**Issue by LecrisUT** [readthedocs/readthedocs.org#11219]
## What's the problem this feature will solve?

On manual `build.commands` we only have `cp` we can use, but for the most part, `rsync` is more robust and for those familiar can be safer w.r.t. creating the correct path structure. It can even eliminate `mkdir -p` commands

## Describe the solution you'd like

Install `rsync` by default on the supported os images

## Alternative solutions

I have tried to install rsync manually, but as you can see [here](https://beta.readthedocs.org/projects/mystmd-temp/builds/23751827/), that doesn't help :thinking:

**Comment by stsewd** [comment]
Hi, we won't be installing packages by default anymore, since projects have different requirements.

> I have tried to install rsync manually, but as you can see [here](https://beta.readthedocs.org/projects/mystmd-temp/builds/23751827/), that doesn't help 🤔

See https://github.com/readthedocs/readthedocs.org/issues/9599.

You may be able to install rsync by downloading the binary https://rsync.samba.org/download.html.

**Comment by ssbarnea** [comment]
This should be reopened, especially as @stsewd suggestion would not work. I tried it myself.

Any attempt to download and install the binary will fail because it will not have access to [required system libraries](https://readthedocs.org/projects/ansibleeda/builds/25370035/), rsync is not really a portable executable.

```
rsync: error while loading shared libraries: libpopt.so.0: cannot open shared object file: No such file or directory
```

I had to do really ugly commands to attemp to install it and still failed:
```yaml
    - curl -o /tmp/rsync.tar.gz https://download.samba.org/pub/rsync/binaries/ubuntu-22.04-x86_64/rsync-3.2.7.tar.gz
    - tar -vxzf /tmp/rsync.tar.gz -C /tmp
    # Copy executable in the first directory in path, which happens to be writable on RTD
    - mkdir -p ${PATH%%:*}
    - cp /tmp/usr/local/bin/rsync ${PATH%%:*}/
    - type rsync
```

**Comment by stsewd** [comment]
@ssbarnea please subscribe to https://github.com/readthedocs/readthedocs.org/issues/9599. As we won't pre-install rsync by default.
