### ISSUE TITLE
API: notification filtering

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#11214]
It sounds like we'll need more complex filtering on the API v3 notifications endpoints to support returning more than one value of `Notification.state`. For example, it sounds like most of the cases we'll need to use `status__in=read,unread`.

**Comment by humitos** [comment]
I found this shouldn't be hard to implement and it seems it's required for the work @agjohnson is doing on the notifications for the new dashboard. So, I went ahead and added this filter.
