### ISSUE TITLE
[Beta dashboard] Feedback

### ISSUE THREAD

**Issue by LecrisUT** [readthedocs/readthedocs.org#11215]
A small bug report along with this, we cannot submit feedback on the support page: https://beta.readthedocs.org/support/

---

Thank you for the work on this new dashboard. It is more legible.

Some feedback:
- Dark-mode please
- `addons` section is a bit confusing. Afaiu the flyout is already enabled by default on projects, but with `Enable Addons` off, the effect of it is not so well defined. Having a temporary link to a post regarding this feature would help
- Why are screenshots mandatory for submitting feedback?

![Screenshot_20240314_122527](https://github.com/readthedocs/readthedocs.org/assets/25577083/f9cd6861-34ae-4fd9-a70f-b1402aff501f)

**Comment by humitos** [comment]
> we cannot submit feedback on the support page: https://beta.readthedocs.org/support/

What problem are you having with this form?

**Comment by humitos** [comment]
Thanks! That explains what happens. It seems the beta domain is not defined as a source to receive feedback from.

**Comment by agjohnson** [comment]
Thanks for your feedback here @LecrisUT!

I'll fix the web form. Thanks for screenshots, they are very helpful but shouldn't be mandatory.

> Dark-mode please

That is definitely planned, I have lightly played with this already and it is on our roadmap. Likely after the beta period is over and we are working on new features.

We're tracking the change here:

- https://github.com/readthedocs/ext-theme/issues/216

> addons section is a bit confusing

This UI is definitely minimal for now, we planned on this for now and will be improving the layout here soon. We are quickly accumulating configuration options here and need more UI.

- https://github.com/readthedocs/ext-theme/issues/293

**Comment by agjohnson** [comment]
Ah I see what you are saying now. Screenshots on issues are optional, but the support form does indeed have a required screenshot field.

**Comment by humitos** [comment]
We fixed the issue to submit feedback from the beta instance. Besides, the other suggestions have a specific issue to track that work. Please, subscribe there to receive updates. I'm going to close this one as fixed.
