### ISSUE TITLE
Development: investigate Cloudflare Tunnel

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#11210]
We had an issue with the NGROK subscription and our account is suspended now. We tried to fix the problem but its price is a lot higher than what we were paying for before.

We already have an account for Cloudflare, so we should do a little research for Cloudflare Tunnel which seems a a good replacement. **The only requirement here would be to have a domain associated to it that doesn't change** --which was the feature we were paying for in NGROK.

References:

* https://developers.cloudflare.com/pages/how-to/preview-with-cloudflare-tunnel/
* https://hub.docker.com/r/cloudflare/cloudflared

**Comment by humitos** [comment]
NGROK seems to continue working for us after adjusting the plan settings.

On the other hand, @ericholscher shared this documentation link with NGROK alternatives in case we want to come back to this issue at some point: https://github.com/anderspitman/awesome-tunneling

**Comment by agjohnson** [comment]
Unless Ngrok isn't doing something for us, swapping tunneling providers feels like a distraction. Ngrok seems to work fine for us, we're just not using it enough to justify paying a whole lot for it. If we prioritize downgrading that seems like enough to me.

**Comment by humitos** [comment]
I will close this issue for now. We can come back to it in the future if we need it.
