### ISSUE TITLE
redirect and CORS policies

### ISSUE THREAD

**Issue by rouault** [readthedocs/readthedocs.org#11223]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/osgeo_proj/
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): N/A

## Issue

We have setup an "exact redirect" from ``/schemas/*`` to ``/en/latest/schemas/:splat`` using HTTP 302.
so that URLs like https://proj.org/schemas/v0.7/projjson.schema.json get resolved to https://proj.org/en/latest/schemas/v0.7/projjson.schema.json
However the "from" URL cannot be used in context where CORS is needed

https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fproj.org%2Fschemas%2Fv0.7%2Fprojjson.schema.json&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote returs a "Fired XHR event: error"
whereas https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fproj.org%2Fen%2Flatest%2Fschemas%2Fv0.7%2Fprojjson.schema.json&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote works with "Fired XHR event: load"

Is there a way to setup a redirect that is CORS friendly?  Or replicate content that is under the /en/latest/foo/bar hierarchy as non-versioned content at top level /foo/far in a non-redirected way?

This is related to https://github.com/OSGeo/PROJ/issues/4088

**Comment by humitos** [comment]
Hi, thanks for opening this issue. What would be needed on the Read the Docs side to support CORS on the redirect?

**Comment by humitos** [comment]
Do we need `access-control-allow-origin: *` on the 302 response?

**Comment by m-mohr** [comment]
Yes, as far as I know we need:

````
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: Location
````

**Comment by jorisvandenbossche** [comment]
Not directly related to the topic about redirecting here, but for the original use case from PROJ that triggered this issue: I was wondering if readthedocs supports hosting some static files at a specific location, independent from the automated builds and related version / url scheme? 
i.e. for this specific case, is there a way to host a file at https://proj.org/schemas/v0.7/projjson.schema.json, _without_ it having to redirect to one of the doc versions at https://proj.org/en[latest/stable/9.3/..]/ 

I didn't directly find anything about this in the readthedocs documentation. But if not possible through readthedocs itself, does readthedocs still allow this to be done by the person managing the proj.org server/domain? (or do the redirects conflict with that?)

**Comment by humitos** [comment]
@jorisvandenbossche 

> is there a way to host a file at [proj.org/schemas/v0.7/projjson.schema.json](https://proj.org/schemas/v0.7/projjson.schema.json), _without_

If I understand correctly, what you want is to remove the "language" part from the URL? Is that correct?

If that's the case, the documentation about this is at https://docs.readthedocs.io/en/stable/versioning-schemes.html

You can go to your project's setting and enable it:
![Screenshot_2024-03-25_16-31-51](https://github.com/readthedocs/readthedocs.org/assets/244656/5f181310-fb25-409b-a527-d088eccabbd4)

**Comment by jorisvandenbossche** [comment]
Not exactly, what I meant is: for a project that _is_ using the "multiple versions with/without translations" scheme, i.e. where URLs for the documentation artifacts start with eg `/en/latest/`, to separately also host some files outside of that url scheme (not part of one of the documentation versions)

**Comment by humitos** [comment]
> Yes, as far as I know we need:
> 
> ```
> Access-Control-Allow-Origin: *
> Access-Control-Expose-Headers: Location
> ```

I added these headers to your project's domain:

```
$ curl -s -I https://proj.org/schemas/v0.7/projjson.schema.json | grep access-control
access-control-allow-origin: *
access-control-expose-headers: Location
```

I checked with the links from the original description and both return the same response now. I'm closing this issue, but let me know any feedback you may have and we can reopen the issue if required.
