### ISSUE TITLE
docs/user/downloadable-documentation.rst links to PDF doc is broken

### ISSUE THREAD

**Issue by pevik** [readthedocs/readthedocs.org#11233]
## Details

* Read the Docs project URL: https://docs.readthedocs.io/_/downloads/en/latest/pdf (linked from https://docs.readthedocs.io/en/stable/downloadable-documentation.html)

## Expected Result

https://docs.readthedocs.io/_/downloads/en/latest/pdf (linked from https://docs.readthedocs.io/en/stable/downloadable-documentation.html) should download PDF.

## Actual Result

https://docs.readthedocs.io/_/downloads/en/latest/pdf returns 404 Page Not Found. [ePub](https://docs.readthedocs.io/_/downloads/en/latest/epub/) and [Zipped HTML](https://docs.readthedocs.io/_/downloads/en/latest/htmlzip/) are working.

**Comment by humitos** [comment]
Hi @pevik. The PDF link for our documentation project returns 404 because we are not building the PDF format for our documentation. We only build HTML and ePUB, that's why those links work.
