### ISSUE TITLE
Project version filter returns 500

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#11231]
It seems the `ProjectVersionListFilterSet.get_visibility()` is receiving the wrong amount of arguments.

To reproduce, just hit https://beta.readthedocs.org/projects/bigo-live-hack/?privacy=&sort=&visibility=hidden

Sentry issue: https://read-the-docs.sentry.io/issues/4721614191/?project=148442&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=7d&stream_index=7

**Comment by agjohnson** [comment]
I can take this on, I'm already working in these filters.
