### ISSUE TITLE
Build not using specified version of sphinx

### ISSUE THREAD

**Issue by 03bennej** [readthedocs/readthedocs.org#11236]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/eipy/
* Build URL (failed): https://readthedocs.org/projects/eipy/builds/23844804/
* Build URL (latest passing build): https://readthedocs.org/projects/eipy/builds/23315114/

## Expected Result

Successful build using sphinx="^4.2" which was working fine (see latest passing build above).

## Actual Result

Failed build due to use of sphinx=7.2.6 (I think).

*A description of what actually happened*

I recently changed some minor code in my repo and noticed the documentation build failed on readthedocs. I was using sphinx="^4.2" (specified in pyproject.toml). In the past readthedocs had used this specified version, but now the most recent version of sphinx is being used. 

I'm happy to use a more recent version of sphinx but it doesn't seem compatible with my extensions (also specified in pyproject.toml), and called in docs/source/conf.py.

Any help to get the documentation back up and running would be much appreciated. Thanks

**Comment by ewjoachim** [comment]
Hey, I see your project uses poetry.
I see you haven't updated your [`.reathedocs.yaml`](https://github.com/GauravPandeyLab/eipy/blob/main/.readthedocs.yml#L13-L17) file with the [recent changes](https://github.com/readthedocs/readthedocs.org/issues/11150) (here are the [new instructions](https://docs.readthedocs.io/en/latest/build-customization.html#install-dependencies-with-poetry))
This specific bug had the consequence that, until the change to the `.readthedocs.yaml` file was done, poetry dependencies would be ignored by RTD, so it really looks like this is the change you need to make to make things work :)

**Comment by 03bennej** [comment]
> Hey, I see your project uses poetry. I see you haven't updated your [`.reathedocs.yaml`](https://github.com/GauravPandeyLab/eipy/blob/main/.readthedocs.yml#L13-L17) file with the [recent changes](https://github.com/readthedocs/readthedocs.org/issues/11150) (here are the [new instructions](https://docs.readthedocs.io/en/latest/build-customization.html#install-dependencies-with-poetry)) This specific bug had the consequence that, until the change to the `.readthedocs.yaml` file was done, poetry dependencies would be ignored by RTD, so it really looks like this is the change you need to make to make things work :)

That worked. Thanks Joachim
