### ISSUE TITLE
Build: set build state cancelled when skipping a build via exit code 183

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#11232]
Originally raised here:

- https://github.com/readthedocs/ext-theme/issues/269

This seems like another version of the issue

- https://github.com/readthedocs/readthedocs.org/issues/11170

The backend is not setting the build state to "cancelled" when the 183 exit code is used to cancel a build, so the new dashboard does not show the correct build state:

![image](https://github.com/readthedocs/readthedocs.org/assets/1140183/c1c6874d-3ae2-4b02-b1ae-3c63ea998e8e)

With this change in the backend, the new dashboard should already be set up to support this build state.

**Comment by humitos** [comment]
This should already be working. We have the code that does this: https://github.com/readthedocs/readthedocs.org/blob/5315a7eef4e30890c1ef9c27b4eec94d79829857/readthedocs/projects/tasks/builds.py#L496-L498

**Comment by agjohnson** [comment]
My example was from my local instance from `main`, seems there is a problem. Here is one from prod:

https://beta.readthedocs.org/projects/test-builds/builds/23830235/

![image](https://github.com/readthedocs/readthedocs.org/assets/1140183/9140a761-faaa-48d9-9dbc-cfbb34ab9ab2)

**Comment by humitos** [comment]
Cool. I will double check then.

**Comment by humitos** [comment]
Oh, I just re-read the issue description after testing this locally and I found that I it works as we planned originally. We only mark builds as CANCELLED when:

- our application cancels the build due duplicated build
- the user manually cancels the build by clicking the button

When any commands exits with `183` code we don't consider that build as CANCELLED. I'm not 100% sure if changing this behavior is correct.

I implemented this idea in https://github.com/readthedocs/readthedocs.org/pull/11240 in case we are OK to move forward with this change.

**Comment by agjohnson** [comment]
> When any commands exits with 183 code we don't consider that build as CANCELLED. I'm not 100% sure if changing this behavior is correct.

Is this intentional or just not something we updated? Or I guess, is there a particular concern here?

From the dashboard perspective, setting a cancelled state seems like consistent UX to me. I think I am still +1 on this change unless there is something big blocking us.

**Comment by humitos** [comment]
> Is this intentional or just not something we updated? Or I guess, is there a particular concern here?

I don't remember why we took this decision, and I'm not sure how much impact it will have, but I don't know of anything super obvious at least 😄

**Comment by agjohnson** [comment]
Yeah that is my take too. I think we're probably safe to make your change then.
