### ISSUE TITLE
Document jump anchor point

### ISSUE THREAD

**Issue by zhangwh807** [readthedocs/readthedocs.org#11253]
Hello，Why can markdown use the "[link](... /.. The /1.guide.m #title 1) "syntax can lead you to a title in another page, but building with readthedocs and clicking on the link leads to 404

**Comment by stsewd** [comment]
Hi, I'm guessing you are using MkDocs to build your project? You should use the syntax that is supported by your documentation tool, not GitHub.

**Comment by zhangwh807** [comment]
Thank you for your answer, I am using wreathedocs to build a document project, but the document is hosted on GitHub, will this affect?

**Comment by stsewd** [comment]
>  I am using wreathedocs to build a document project, but the document is hosted on GitHub, will this affect?

To be clear, in order to build your documentation from your GitHub project, RTD uses a tool that you specify in the configuration file, like Sphinx or MkDocs, you should read the documentation from that tool about how to link to other files.
