### ISSUE TITLE
Enhanced Documentation Review Process

### ISSUE THREAD

**Issue by sachin-suresh-rapyuta** [readthedocs/readthedocs.org#11264]
## What's the problem this feature will solve?

During the review process, it is crucial for reviewers to efficiently assess and understand the changes made to the documentation. Currently, navigating to specific changes requires manually searching for the file within the ReadtheDocs documentation structure, which can be time-consuming and detracts from the review experience.

## Describe the solution you'd like

1. **Direct Navigation to Modified Content**:

When accessing a doc build preview link, the user should be taken directly to the portion of the documentation where changes have been made. This direct navigation ensures that reviewers can immediately focus on the content that requires their attention.

2. **Differential Highlighting**:

Changes made to the RST or MD files should be visually highlighted within the documentation preview. This highlighting could take the form of color coding or other visual indicators that distinctly mark added, modified, or removed content. By clearly delineating changes, reviewers can more easily assess and provide feedback on the modifications.

**Comment by stsewd** [comment]
> When accessing a doc build preview link, the user should be taken directly to the portion of the documentation where changes have been made. This direct navigation ensures that reviewers can immediately focus on the content that requires their attention.

I think a similar solution to what I described in https://github.com/readthedocs/readthedocs.org/issues/6621#issuecomment-1934923045 can be useful here. We can detect the new pages added in a PR, and we could even go further and sort pages by number of changes after running a diff, that way we work over the resulted pages instead of trying to guess from the source files.

**Comment by sachin-suresh-rapyuta** [comment]
>I'm happy to receive detailed feedback about how you imagine this feature could be implemented considering what we discussed already and its UX exposed to users.

Here are some feedbacks/suggestions:

### How it can be implemented?

1. Change Detection:

- Utilize Git or similar version control systems integrated with RTD to detect changes between builds.
- Identify modified `.rst` files (or other documentation source files) in a commit or across a range of commits. Something like what @stsewd suggested.

2. Link Generation:

- Generate direct links to the corresponding sections/pages in the RTD build preview for each detected change.

- Adjust file paths to match the URL structure of the RTD preview site. This may involve stripping base directory names (like `docs/`) and converting file paths to pretty URLs.

3. Configuration Options:

-  Allow project maintainers to configure the maximum number of direct links displayed to prevent flooding the interface when numerous changes are detected.

- Provide options in RTD project settings for customizing URL conversion rules (e.g., how to handle directory names, and file extensions).

### UX Improvement suggestions

1. Configuration UI:

In the RTD project settings, include a user-friendly UI for configuring the direct navigation feature, such as specifying the maximum number of direct links to display and setting URL conversion rules.

2. Feedback Mechanism:

Incorporate a way for reviewers to provide feedback directly from the build preview interface, such as comments or suggestions on the modified sections. This could be integrated with the project's issue tracking system. This could greatly improve the review process.

3. Visual Indicators:

I think this is already a part of the Beta implementation.

Not sure how much of this actually makes sense 😊
