### ISSUE TITLE
Add user settings for navigation with arrow keys through Sphinx's navigation_with_keys theme option

### ISSUE THREAD

**Issue by C0rn3j** [readthedocs/readthedocs.org#11266]
## What's the problem this feature will solve?

RTD isn't by default very keyboard-friendly for navigation.
This is solved by an [opt-in Sphinx theme feature](https://github.com/sphinx-doc/sphinx/pull/2064).  
This feature makes documentation much nicer to read with just the keyboard, as it allows for quick page flips and not having to use the mouse.

## Describe the solution you'd like

I have sent pull requests to a few projects to hardcode enable the arrow navigation, *a single example of such PR - https://github.com/kdave/btrfs-progs/pull/754*

This is tedious to do per-repo, and not everyone has the same workflow, so someone might in fact want to keep this disabled.   
See upstream Sphinx issue https://github.com/sphinx-doc/sphinx/issues/12227 that outlines a few problems with having this enabled for everyone, thus I believe a user-configurable toggle that would effectively change `navigation_with_keys` would be a good idea.  

Implementing `navigation_with_keys: True` by default in Sphinx was not seen as an ideal solution, as per the above upstream issue.

RTD already has an expandable menu where this could be possibly added in without visually changing the main view, if adding a cogwheel somewhere was undesirable:

![image](https://github.com/sphinx-doc/sphinx/assets/1641362/5f5ffc7a-8dc7-41b2-8770-b72bbd04a329)

Since this by default conflicts with x-scroll keys, maybe letting the user re-define the keybinds for page flips would also be a good idea, to get the best of both worlds.

**Comment by humitos** [comment]
Thanks for opening this issue.

I explained in https://github.com/sphinx-doc/sphinx/issues/12227#issuecomment-2042178181 why we are not going to add `navigation_with_keys: True` by default.

However, your issue mentions "add user settings..." which is something we should start considering and discussing at some point. We have been implementing "reader features" as addons and I see users/readers wanting to use Read the Docs in a consistent way across all the documentation projects. So, I think we can take this part of the issue and discuss it as an addons: https://github.com/readthedocs/addons/issues/285
