### ISSUE TITLE
Allow building frequency to reduce RTD loads

### ISSUE THREAD

**Issue by zerothi** [readthedocs/readthedocs.org#11273]
## What's the problem this feature will solve?

Instead of re-building the documentation for every commit, I would suggest one to be able to
only rebuild the `latest` docs with some frequency.

## Describe the solution you'd like

On `github` actions one can setup a cron like this:
```yaml
on:
    schedule:    
       cron: ...
```
which allows one to only run the `RTD` at a certain frequency.
This would also be great for the pressure on RTD, I highly doubt that a lot of the doc builds are really changing a great deal. So smaller projects could easily do this incrementally.

## Alternative solutions

I have tried disabling builds, and manually doing this every week, that is far from optimal.

## Additional context
I think very little else is required.

**Comment by agjohnson** [comment]
Thanks for the suggestion! While we don't support this directly, we do have a few features that allow for similar workflows on build projects already. So, though this seems intuitive for this workflow, we don't have room on our roadmap for this.

Instead, I'd point you at either manually triggering builds through a generic webhook, or you can configure your project to automatically skip building unless a condition is met -- such as files changing in your repository inside your `docs/` directory:

- https://docs.readthedocs.io/en/stable/builds.html#cancelling-builds
- https://docs.readthedocs.io/en/stable/build-customization.html#cancel-build-based-on-a-condition

**Comment by zerothi** [comment]
Thanks for this!

I didn't find this because I looked here: https://docs.readthedocs.io/en/stable/config-file/v2.html
which as the headline suggests would be exhaustive in what the configuration file could provide.

So I didn't think anything else was present in the specification of the file.

Thanks!

**Comment by agjohnson** [comment]
That's helpful to know! I noted this in #11274 as I had trouble getting to the page I was looking for too. This information is indeed a bit deeper in our documentation than it probably should be.
