### ISSUE TITLE
Switching themes failed when uploading a Sphinx project to ReadTheDocs.

### ISSUE THREAD

**Issue by lafvintech** [readthedocs/readthedocs.org#11284]
Hello, I uploaded a Sphinx-built project to GitHub, and then used readthedocs.org to link to the GitHub repository. Using the sphinx_rtd_theme, it can be built normally, but when using other Sphinx themes, it doesn't work. And ReadTheDocs reports an error.

The following is the error content
`python -m sphinx -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html

Running Sphinx v7.3.5 making output directory... done WARNING: html_static_path entry '_static' does not exist Traceback (most recent call last): File "/home/docs/checkouts/readthedocs.org/user_builds/super-starter-kit-for-raspberry-pi/envs/latest/lib/python3.12/site-packages/sphinx/cmd/build.py", line 332, in build_main app = Sphinx(args.sourcedir, args.confdir, args.outputdir, ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/docs/checkouts/readthedocs.org/user_builds/super-starter-kit-for-raspberry-pi/envs/latest/lib/python3.12/site-packages/sphinx/application.py", line 268, in init self._init_builder() File "/home/docs/checkouts/readthedocs.org/user_builds/super-starter-kit-for-raspberry-pi/envs/latest/lib/python3.12/site-packages/sphinx/application.py", line 338, in _init_builder self.builder.init() File "/home/docs/checkouts/readthedocs.org/user_builds/super-starter-kit-for-raspberry-pi/envs/latest/lib/python3.12/site-packages/sphinx/builders/html/__init__.py", line 228, in init self.init_templates() File "/home/docs/checkouts/readthedocs.org/user_builds/super-starter-kit-for-raspberry-pi/envs/latest/lib/python3.12/site-packages/sphinx/builders/html/__init__.py", line 276, in init_templates theme_factory = HTMLThemeFactory(self.app) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/docs/checkouts/readthedocs.org/user_builds/super-starter-kit-for-raspberry-pi/envs/latest/lib/python3.12/site-packages/sphinx/theming.py", line 162, in init self._load_entry_point_themes() File "/home/docs/checkouts/readthedocs.org/user_builds/super-starter-kit-for-raspberry-pi/envs/latest/lib/python3.12/site-packages/sphinx/theming.py", line 187, in _load_entry_point_themes _config_post_init(self._app, self._app.config) File "/home/docs/checkouts/readthedocs.org/user_builds/super-starter-kit-for-raspberry-pi/envs/latest/lib/python3.12/site-packages/sphinx/config.py", line 654, in check_confval_types default = opt.default ^^^^^^^^^^^ AttributeError: 'tuple' object has no attribute 'default' Exception occurred: File "/home/docs/checkouts/readthedocs.org/user_builds/super-starter-kit-for-raspberry-pi/envs/latest/lib/python3.12/site-packages/sphinx/config.py", line 654, in check_confval_types default = opt.default ^^^^^^^^^^^ AttributeError: 'tuple' object has no attribute 'default' The full traceback has been saved in /tmp/sphinx-err-pf4otd7v.log, if you want to report the issue to the developers. Please also report this if it was a user error, so that a better error message can be provided next time. A bug report can be filed in the tracker at https://github.com/sphinx-doc/sphinx/issues. Thanks!`

**Comment by humitos** [comment]
Hi, can you please paste the URL of your project on Read the Docs and the build URL as well? Thanks.

**Comment by lafvintech** [comment]
> Hi, can you please paste the URL of your project on Read the Docs and the build URL as well? Thanks.

https://super-starter-kit-for-raspberry-pi.readthedocs.io/en/latest/
This is the link to my ReadTheDocs project, which is currently using the sphinx-rtd-theme and working normally.

Previously, when switching themes, I had modified the requirements.txt and conf.py, but readthedocs.org seemed to indicate that it couldn't load the themes correctly. The theme I'm using is https://sphinx-themes.org/sample-sites/sphinx-pdj-theme/

**Comment by agjohnson** [comment]
This is an issue with Sphinx 7.3 (your build states `Running Sphinx v7.3.5`), which had a number of releases today and yesterday. Because your project is not pinning it's dependencies, it installed the latest Sphinx release automatically. You should try pinning your Sphinx version to <7.3 and perhaps you can file an issue with Sphinx. It seems there were a number of theming changes in 7.3.

**Comment by lafvintech** [comment]
> This is an issue with Sphinx 7.3 (your build states `Running Sphinx v7.3.5`), which had a number of releases today and yesterday. Because your project is not pinning it's dependencies, it installed the latest Sphinx release automatically. You should try pinning your Sphinx version to <7.3 and perhaps you can file an issue with Sphinx. It seems there were a number of theming changes in 7.3.
After specifying the version to 7.2.5, it seems the themes can be used now,  thanks!

**Comment by lafvintech** [comment]
> This is an issue with Sphinx 7.3 (your build states `Running Sphinx v7.3.5`), which had a number of releases today and yesterday. Because your project is not pinning it's dependencies, it installed the latest Sphinx release automatically. You should try pinning your Sphinx version to <7.3 and perhaps you can file an issue with Sphinx. It seems there were a number of theming changes in 7.3.

After specifying the version to 7.2.5, it seems the themes can be used now, thanks!
