### ISSUE TITLE
builds not triggered since feb 16

### ISSUE THREAD

**Issue by emmettbutler** [readthedocs/readthedocs.org#11293]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/ddtrace/builds/

## Expected Result

New [release tags](https://github.com/DataDog/dd-trace-py/tags) on the dd-trace-py repository should trigger Readthedocs builds.

## Actual Result

Since Feb 16 when dd-trace-py v2.6.2 had its documentation [built](https://readthedocs.org/projects/ddtrace/builds/23460362/), no new tags have triggered docs builds. There have been no changes to the `.readthedocs.yml` file since that version.

Clicking the "Build Version" button results in a build being triggered from the most recent tag. Why isn't this happening automatically when new tags are published? How might I debug this?

**Comment by humitos** [comment]
Hi @emmettbutler! Read the Docs doesn't build the documentation for new tags automatically. If you want to enable that, you can use [Automation Rules](https://docs.readthedocs.io/en/latest/automation-rules.html). Let me know if that's what you are looking for.

**Comment by emmettbutler** [comment]
@humitos are builds on new commits to branches automatic? I'll look into automation rules - it seems like they do probably solve our use case. I'm also interested in knowing why this changed recently without any changes to our repo. Did RTD change behavior around this in the last few months?

**Comment by emmettbutler** [comment]
🤷 my best guess is that an automation rule got deleted somehow. I just created one and will reopen this ticket if it doesn't get triggered on the next release. Thanks for your help @humitos.
