### ISSUE TITLE
Tests: start running tests with ext-theme and new templates enabled

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#11299]
We are getting close to the point where we should be running tests against ext-theme and the new templates, as these will inflict some tests failures where tests are looking for specific response or interacting with forms, and also where we are isolating new behavior in views with `settings.RTD_EXT_THEME_ENABLED`

For a first pass, we can start by marking any tests a xfail if they feel like they are primarily for the legacy dashboard, instead of repairing all the tests.

**Comment by stsewd** [comment]
We are running test with ext-theme on .org, we are only missing .com (https://github.com/readthedocs/readthedocs-corporate/pull/1807). For that we just need https://github.com/readthedocs/ext-theme/issues/393.
