### ISSUE TITLE
Allauth: update to use latest version

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#11309]
## What's the problem this feature will solve?

The latest versions of allauth include some improvements and fixes related to SAML, which is a feature we are active developing for .com.

Last time I saw that were some breaking changes related to templates, and changes around using json fields.

## Additional context

The last time we updated allauth (https://github.com/readthedocs/readthedocs.org/pull/11134) we hit only one problem I think, it was related to a missing changelog entry about a field change in google. Another problem we had we about the settings, but that wasn't related to allauth itself, but to our settings inheritance.

**Comment by humitos** [comment]
> latest versions of allauth include some improvements and fixes related to SAML

What are those improvements and fixes? Knowing that will help us to work on prioritization of this upgrade.

**Comment by stsewd** [comment]
You can just check the changelog and look for "SAML" https://docs.allauth.org/en/latest/release-notes/recent.html Some important ones are:

- SAML: accessing the SLS/ACS views using a GET request would result in a crash (500).
- SAML: the login view did not obey the SOCIALACCOUNT_LOGIN_ON_GET = False setting.
