### ISSUE TITLE
Multiple copies of the same github repo

### ISSUE THREAD

**Issue by da5nsy** [readthedocs/readthedocs.org#11325]
## What's the problem this feature will solve?

We* are currently trying to implement multi-language support, and were hoping to do this through RTD.
We were imagining that we would have multiple languages hosted in a single github repo, but it looks like we can only add a github repo once (whereas we think we would need to add it multiple times, into different RTD projects).

*(the infrastructure working group of [The Turing Way](https://book.the-turing-way.org/))

## Describe the solution you'd like

Ability to import the same github repo multiple times.

## Alternative solutions

We could potentially switch to a "one repo per language" approach, but this would require considerable restructuring and changes to our current way of working.

## Additional context

We are using crowdin to handle translations.
If anyone from the RTD team is interested in getting more involved in helping this project we would welcome them with open arms! ❤️

**Comment by stsewd** [comment]
Hi, a workaround is to manually import the repository from https://readthedocs.org/dashboard/import/manual/.

**Comment by humitos** [comment]
You should be able to import the same repository multiple times by using the new dashboard at https://beta.readthedocs.org --there, we removed this limitation. Please, let us know if it works for you.

**Comment by agjohnson** [comment]
@da5nsy Just adding here that the new dashboard allows for *automatic* configuration of multiple projects against the same repository. There is no need for manual configuration of multiple projects if you add the project from the new dashboard.

**Comment by humitos** [comment]
@da5nsy were you able to import your project twice? I'm closing this issue since it's not an issue anymore on the new dashboard (https://app.readthedocs.org/). However, let us know if you need more help.
