### ISSUE TITLE
Notifications: not shown on other people's projects

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#11333]
Opening a build details page for a project where you are not a maintainer returns 403 and show no notifications at all.

1. go to https://beta.readthedocs.org/projects/chemprop/builds/24161295/
2. check the console

![Screenshot_2024-04-24_12-45-08](https://github.com/readthedocs/readthedocs.org/assets/244656/c95b912e-1776-4c6e-9c1f-9464635c5df8)

**Comment by humitos** [comment]
We've been hitting this a lot lately and this has triggered a NR alarm. It would be good if we can prioritize this because of the alarm, but also because it's a confusing UX entering a failing project and not knowing why it failed.

**Comment by stsewd** [comment]
What would be the expected result here? Looks like we aren't showing notifications on purpose

https://github.com/readthedocs/readthedocs.org/blob/019719a2b08f759a06e1029e8c3345209adc78de/readthedocs/api/v3/permissions.py#L66-L73

Do all build/project notifications have private information in those? Do we want to show those to all users? If this is just for helping debug a problem, I think we just need to bring impersonate to .org.

**Comment by humitos** [comment]
The expected result here is to copy the behavior we used to have: show all build notifications on build detail pages to all users for public projects.

The code you showed from the API may have introduced a bug by mistake.

Note that if you go to https://app.readthedocs.org/projects/test-builds/builds/24735510/ in an Incognito window, you won't see the build error notification --which is the problem we want to solve. This is not to help us to debug issues, but something that's expected for users to see on public projects.

**Comment by humitos** [comment]
Actually, we _just_ receive a support email about this exact same problem: https://app.frontapp.com/open/cnv_ni9id53?key=IXuAcHhM5AG28s077lJ-Tlebut_7QyNp 😄
