### ISSUE TITLE
docu: Subprojects "example_project" not working

### ISSUE THREAD

**Issue by buhtz** [readthedocs/readthedocs.org#11358]
## Details
See https://docs.readthedocs.io/en/stable/subprojects.html where you point to an "example_project" (https://example-project.readthedocs.io/en/latest/) and its subproject (https://example-project.readthedocs.io/projects/plugin).

The link to the subproject is not valid anymore and gives a 404.

**Comment by stsewd** [comment]
Hi, those were meant as examples of how the URLs will be generated. Those projects aren't managed by the RTD team. Maybe we should use projects that we manage as examples.

**Comment by bmorelli25** [comment]
I was also confused by this. It wasn't clear to me that these are simply example URLs. I expected to see docsets that I could click around in.

**Comment by humitos** [comment]
I opened a PR that makes those URLs non-linkable to remove the confusion.
