### ISSUE TITLE
Build tools: update `latest` versions

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#11350]
## What's the problem this feature will solve?

The version we have of miniconda (4.7) is quite old, I remember checking for this some time ago, and thinking that there weren't more versions available (5.x for example). Turns out that they changed their versioning scheme some time ago... Their versions now appear to be linked to a python version and the miniconda version (e.g `miniconda3-3.12-24.1.2.0`).

## Describe the solution you'd like

We are close to June, that's our 6 months policy update for all build tools, so we can maybe wait until that to update it. Or just do one exception, as our policy mentions.

## Alternative solutions

Maybe find a way to manually upgrade miniconda for users that need it?

## Additional context

We have one user not being able to build their docs, a probable cause is the version of miniconda. See https://github.com/numba/pixie/pull/12.

**Comment by humitos** [comment]
> We are close to June, that's our 6 months policy update for all build tools, so we can maybe wait until that to update it

Yeah, I think it's fine to update them all in June. We are only one week away from it and we need to do the work, review, deploy, etc still.

**Comment by jezdez** [comment]
Please let me know if you need any details about this (this also ships with the mamba solver as the new backend for conda, making it almost as fast as mamba CLI). Blog post: https://conda.org/blog/2023-11-06-conda-23-10-0-release

**Comment by humitos** [comment]
We are using `asdf` (https://asdf-vm.com/) to install these versions, so we will need to use the following ones as latest(s):

```
▶ asdf list all python | grep miniconda | grep 24\. 
miniconda3-3.9-24.1.2-0
miniconda3-3.10-24.1.2-0
miniconda3-3.11-24.1.2-0
miniconda3-3.12-24.1.2-0
```

```
▶ asdf list all python | grep mambaforge | grep 23\.
mambaforge-23.1.0-0
mambaforge-23.1.0-1
mambaforge-23.1.0-2
mambaforge-23.1.0-3
mambaforge-23.1.0-4
mambaforge-23.3.0-0
mambaforge-23.3.1-0
mambaforge-23.3.1-1
mambaforge-23.10.0-0
mambaforge-23.11.0-0
```
