### ISSUE TITLE
Organizations: better creation flow

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#11356]
There are a few places that the new dashboard should try harder to avoid creating a new organization for new users:

- The organization listing view only shows a create button when the user has no organizations. It doesn't show after the first organization is added/connected for the user.
- The organization placeholder content on the organization listing follows this same logic.

This logic could probably be improved on, maybe giving users more opportunity to create organizations -- perhaps there are reasons to allow this?

The organization creation flow could also try to connect users to an existing organization, or at least try to guide the user to find their existing organization.

What are some options for detecting/guessing an organization for a user? What cases are users authenticating but not being connected to their organization, and can we even prevent this?

**Comment by humitos** [comment]
I found a bunch of users creating organization by mistake while checking "Cancelled" subscriptions on "Read the Docs for Business". So, it seems to be a pretty common issue that users hit there.

* https://github.com/readthedocs/meta/issues/149#issuecomment-2124656880

**Comment by agjohnson** [comment]
Yeah, we've known this for a while but haven't done much to change this UX. Users creating extraneous organizations is in part a symptom of jumping straight to the organization creation workflow on signup, and also poor UX around connecting users to existing organizations.

We've tried a few different ways to connect users to the correct organization signup, but I think we should look at data here. I would be very surprised if users were using the SSO/SAML organization specific signup links, these links are a rather confusing experience. I would expect team/organization invites to be really natural though. If users are being trapped into organization creation through invites, something seems wrong.

I think to supplement not great UX on the sign up side, we need better signup flow UX too.

- Not giving every user the organization creation flow would be a start. We could give that workflow only when signing up for an account from a link on our website.
- Asking users if they should already have an organization before creating a new one is also a good step maybe. I don't yet know how we frame this question to the user though.

Connecting users to existing organizations is very hard UX to get correct though, we just need to be iterating on patterns.

**Comment by humitos** [comment]
> Not giving every user the organization creation flow would be a start. We could give that workflow only when signing up for a trial from a link on our website. Or at very least, give the user the dashboard before pushing them into an organization.

This is probably a good first step, 👍🏼

**Comment by agjohnson** [comment]
I've added a very small step in this direction in my work on placeholder content:

![image](https://github.com/readthedocs/readthedocs.org/assets/1140183/6405141f-c27a-45f9-8a58-bfeb2d0eecc7)

**Comment by humitos** [comment]
The other day I thought that a better/good UX could be as follow:

1. When the user signs up, instead of showing the "Create an organization" form, show a prompt like "First time here?"
2. It shows the options:
   * My organization is already registered in Read the Docs
   * I want to create a new organization for my company
3. If the use selects "My organization is already registered", we show something like "We weren't able to find the organization attached to your email domain. Make sure you have registered with your company's email and not your personal email". Besides, we tell them "Contact your organization's owner and tell them to invite you to the organization. They will send you a link with the invitation"
4. If they select "I want to create a new organization", we show the form to create the organization

This may not be the _best_ pattern, but I like the approach because it's very explicit and we can communicate clearly what the user should follow on each case. What do you think?

**Comment by agjohnson** [comment]
I was loosely thinking of something similar, this feels like a great place to start. We have the option of coming back later to maybe making this more interactive if we need, and can start with the easy option which is just giving the user more information. Certainly this will be better than just throwing everyone into organization creation.

I'd also consider improving the creation form in the same batch of work. We do mention the trial and subscription on the organization creation view, but perhaps the next thing we need there is to force the user into selecting something with a dollar amount attached. We still aren't asking for a card up front, but making the user aware of our pricing on organization creation will give the user a reason to be more careful.

**Comment by humitos** [comment]
Sounds good to me!

**Comment by agjohnson** [comment]
I'm guessing we'll probably want a separate view, something other than `/organizations/create` view. The view doesn't need to do anything though, so we could just use more FUI components to add the interactivity to `/organizations/create/` too.

**Comment by humitos** [comment]
I removed the design decision tag and added this issue to the Q3 so prioritize it to work in the next sprints.

**Comment by humitos** [comment]
There are more work that could be done here. However, the initial step towards the solution was already implemented. We can come back to this workflow while working on user on boarding --we touched on this during our Book Club as well.
