### ISSUE TITLE
RTD build for PR is instantly failing with persistent "Unknown problem" error message

### ISSUE THREAD

**Issue by joshuacwnewton** [readthedocs/readthedocs.org#11363]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/spinalcordtoolbox/
* Build URL (if applicable): https://readthedocs.org/projects/spinalcordtoolbox/builds/24516903/
* Read the Docs username (if applicable): N/A

## Expected Result

A succeeding build.

## Actual Result

> There was a problem with Read the Docs while building your documentation. Please try again later. If this problem persists, report this error to us with your build id (24516903).

This error happens on repeated retries: https://readthedocs.org/projects/spinalcordtoolbox/builds/

The PR had been passing, so I thought to revert my recent changes. But, reverting the changes in the associated PR (https://github.com/spinalcordtoolbox/spinalcordtoolbox/pull/4493) did not fix the problem.

**Comment by stsewd** [comment]
Hi, there was a problem with our latest release, we are working on a fix now.

**Comment by stsewd** [comment]
All builds are affected :(

**Comment by joshuacwnewton** [comment]
Not a worry! Just happy there's a known cause. :)

Sorry to be the unlucky user who caught the downstream effects while you're in the process of fixing things. :hearts:
