### ISSUE TITLE
Docs: missing information on Cloudflare to Cloudflare proxy configuration

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#11371]
I was looking for these directions to point a user to them but could not find them in the docs anymore.

From the translation file:

```
"Due to a limitation, a domain cannot be proxied on Cloudflare to another "
"Cloudflare account that also proxies. This results in a \"CNAME Cross-User "
"Banned\" error. In order to do SSL termination, we must proxy this "
"connection. If you don't want us to do SSL termination for your domain -- "
"**which means you are responsible for the SSL certificate** -- then set your"
" CNAME to ``cloudflare-to-cloudflare.readthedocs.io`` instead of "
"``readthedocs.io``."
```

Perhaps we removed this on purpose, as it's not a common configuration?

**Comment by stsewd** [comment]
I think it was removed because it was no longer a problem :man_shrugging:

**Comment by agjohnson** [comment]
In that users can just use the standard CNAME with their own Cloudflare account? I guess we'll see. I had a user note that they had problems using their own Cloudflare account in front of us and mentioned the record as a fix.

**Comment by stsewd** [comment]
So, yeah, looks like users need to uncheck the "proxy" option when creating a CNAME. And we shouldn't recommend using the `cloudflare-to-cloudflare.readthedocs.io`, as that points directly to our LB, and we are required to use CF for addons now.

**Comment by humitos** [comment]
I'm putting this issue in Q4 so we update this docs.
