### ISSUE TITLE
Allow change of username

### ISSUE THREAD

**Issue by digitalresistor** [readthedocs/readthedocs.org#11391]
## What's the problem this feature will solve?

I am attempting to change my username, as it contains my dead name. I am unable to find any location where I can do so.

I found an old bug report that suggested deleting/recreating your account, however that would mean losing access to a large amount of projects.

## Describe the solution you'd like

I would like a form where I am able to change my username.

## Alternative solutions

Creating a new account, adding that new account to large variety of projects, and then deleting the old account. This is cumbersome and error prone.

## Additional context

I am a non-binary transfemme and would like to shed my dead name as much as possible.

**Comment by humitos** [comment]
Hi @digitalresistor! I'd love to help you with this request. Can you please contact us via https://app.readthedocs.org/support/ while being logged in with the account you want to change your username? Thanks.

**Comment by digitalresistor** [comment]
@humitos 

I tried to submit the form, but was redirected to this URL:

https://app.readthedocs.org/support/error/?code=bad_referer&message=This%20form%20was%20not%20submitted%20from%20the%20configured%20location.

<img width="1171" alt="Screenshot 2024-06-10 at 21 36 22" src="https://github.com/readthedocs/readthedocs.org/assets/649426/fb56e244-9b23-4c5d-b45d-a6188a76db8e">

**Comment by humitos** [comment]
Ups... You found a bug 😄 . I've already fixed. Can you try again?

**Comment by digitalresistor** [comment]
Done, and my username was changed. Thank you so much!

**Comment by humitos** [comment]
Thanks great! 👍🏼
