### ISSUE TITLE
API: updates to endpoint for triggering a new build

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#11390]
In https://github.com/readthedocs/ext-theme/issues/336 I found it rather hard to work with the different views that trigger a new build and would prefer to use our API endpoint for this. Our endpoint has some short comings though:

- It only returns the pks/slugs, requiring user manually build their own URLs instead of returning resolved URLs
- It might not support the same build retry logic that external builds use to actually retry a build, not create a new build
- There could be better error handling and error response from the server.

**Comment by agjohnson** [comment]
Actually, this API does have what I need, but the docs are wrong:

```
{
    "build": "{BUILD}",
    "project": "{PROJECT}",
    "version": "{VERSION}"
}
```

**Comment by humitos** [comment]
@agjohnson note that `{BUILD}` syntax means it's a build object. You can find the structure for this obejct on the "Build details" section of the documentation: https://docs.readthedocs.io/en/stable/api/v3.html#build-details

**Comment by agjohnson** [comment]
It's in string quotes though, so implies this is an id/pk instead of a full object.

**Comment by humitos** [comment]
It's with quotes because it's a JSON and if you don't use quotes there, it breaks Sphinx 🤷🏼

**Comment by agjohnson** [comment]
But that seems to be because we're using `{BUILD}` as a placeholder notation. [The docs](https://docs.readthedocs.io/en/stable/api/v3.html#build-triggering) don't mention what this notation is or what data structures these refer to.

If we follow the pattern from other responses and instead show the full response, that would be clearer. Even a truncated response on the nested objects would be clearer, if we're worried the full response is too long.

**Comment by agjohnson** [comment]
I am going to separate out fixing our API docs to make them clear. I have never noticed that our APIv3 docs comment many nested objects using strings and this could definitely be much clearer.

Changes to the API are in #11407
