### ISSUE TITLE
Flyout: unicode characters break URLs in flyout

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#11403]
If a generated path contains unicode characters, the flyout will have broken links when switching versions to the same page.

To reproduce:

- Go to https://test-builds.readthedocs.io/en/unicode-paths/subpath/%E0%B9%84%E0%B8%9F%E0%B8%A5%E0%B9%8C.html
- Open the flyout and inspect links for switching versions
- All URLs have encoded strings as URL paths. For example: `https://test-builds.readthedocs.io/en/sphinx-awesome/=?utf-8?b?L3N1YnBhdGgv4LmE4Lif4Lil4LmMLmh0bWw=?=`
- This URL is invalid and leads to a 404

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_wgb5z)

**Comment by ericholscher** [comment]
👍 on doing this. We keep hitting this error in Sentry as well, and would be great to fix it.
