### ISSUE TITLE
Question regarding subscriptions "CDN public documentation"

### ISSUE THREAD

**Issue by rffontenelle** [readthedocs/readthedocs.org#11414]
Translating this string, I'm stuck with the following doubt

https://github.com/readthedocs/readthedocs.org/blob/488d50dc4239d3d73ccf9d142f009714ebc95e82/readthedocs/subscriptions/constants.py#L26

Does this mean to put public documentation in CDN (i.e. CDN was used as if it was a verb) or the public documentation of the CDN (I.e. so the user can read more about the CDN itself) ?

**Comment by humitos** [comment]
Hi 👋🏼 . It means the public documentation the user builds on Read the Docs will be exposed through a CDN. Let me know if that makes sense. We can add a comment in the code for translators as well.

**Comment by stsewd** [comment]
We could probably change it to "CDN for public documentation"

**Comment by rffontenelle** [comment]
> We could probably change it to "CDN for public documentation"

That looks awesome
