### ISSUE TITLE
Addons: remove the "beta" from it

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#11419]
We can start considering Read the Docs Addons as stable at this point probably, so we can remove all the mentions to "beta" from our documentation and dashboard.

Reference: https://github.com/readthedocs/readthedocs.org/pull/11412#discussion_r1638729566

**Comment by ericholscher** [comment]
This is now done 👍

**Comment by humitos** [comment]
This was done in https://github.com/readthedocs/readthedocs.org/issues/11453
