### ISSUE TITLE
Document serve failed today

### ISSUE THREAD

**Issue by HydrogenSulfate** [readthedocs/readthedocs.org#11428]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/{your_project_slug}/
* Build URL (if applicable): https://readthedocs.org/projects/{your_project_slug}/builds/{build_id}/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/HydrogenSulfate/

## Expected Result

*A description of what you wanted to happen*
Today our document can not be accessed and report 404: <https://paddlescience-docs.readthedocs.io/zh/latest/>. But all things right yesterday. Can any one help?
## Actual Result

*A description of what actually happened*

**Comment by stsewd** [comment]
Hi, sorry about that. Looks like a bug that was introduced in https://github.com/readthedocs/readthedocs.org/pull/11385. We are discussing how to fix this.

**Comment by humitos** [comment]
@HydrogenSulfate we fixed the issue and deploy it. Your documentation is being served properly at https://paddlescience-docs.readthedocs.io/zh/latest/ 👍🏼 . Let us know if it works as you expect.

Note that we made this change because `zh` language code is deprecated and shouldn't be used. Instead, `zh_CN` (Simplified Chinese) or `zh_TW` (Traditional Chinese) should be used. You can change this from your project settings.

**Comment by HydrogenSulfate** [comment]
> @HydrogenSulfate we fixed the issue and deploy it. Your documentation is being served properly at https://paddlescience-docs.readthedocs.io/zh/latest/ 👍🏼 . Let us know if it works as you expect.
> 
> Note that we made this change because `zh` language code is deprecated and shouldn't be used. Instead, `zh_CN` (Simplified Chinese) or `zh_TW` (Traditional Chinese) should be used. You can change this from your project settings.

Though this problem has been fixed quickly, I found this is a incompatible change, because all the public document links before(such as all the links in our example table: <https://github.com/PaddlePaddle/PaddleScience?tab=readme-ov-file#%E6%A1%88%E4%BE%8B%E5%88%97%E8%A1%A8>) can not be accessed any more as the prefix in url has been changed from `zh/latest/zh` to `zh-cn/latest/zh`. Is there any way to make it compatible?

**Comment by HydrogenSulfate** [comment]
> @HydrogenSulfate you can create a redirect from `zh` to `zh-cn` in your project to fix these links. See https://docs.readthedocs.io/en/stable/user-defined-redirects.html

Fixed, thanks again!
