### ISSUE TITLE
Docs: Write initial Addons documentation page

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#11425]
The idea here is probably for @humitos to write an initial draft and work with @plaindocs as a primary editor.

**Comment by plaindocs** [comment]
OK, @humitos and I chatted about this and reckon the following is a decent approach:

- Find a home for each separate addon within the most relevant section of the existing docs structure (more details on that below)
  - Focus on docs for maintainers (readers shouldn't really need them)
  - Leave advanced js/json config for last

- Add a new Addons page or section listing+linking them with a short description (kinda like the existing marketing page)
  -   Add a config section around enabling the addons, or where they are  on by default  

For homes for addons, I'm thinking something like 

- Analytics -> hosting documentation
- DocDiff -> Build process (PR previews)
- PR notification -> Build process (PR previews)
- Version flyout -> Reading documentation
- non-stable notification (have we thought about merging the three banner sections in the docs) -> reading documentation
- latest notification -> reading documentation
- search as you type -> reading documentation (cross linked from search in hosting docs)
- Sponsorship -> reading docs

And while I'm there, doing some refactoring of existing related pages that are replaced by the new addons (being phased out), including 

- [https://docs.readthedocs.io/en/stable/flyout-menu.html](https://docs.readthedocs.io/en/stable/flyout-menu.html)
- [https://docs.readthedocs.io/en/stable/versions.html#version-warning](https://docs.readthedocs.io/en/stable/versions.html#version-warning)
- https://docs.readthedocs.io/en/stable/server-side-search/index.html

I'll get started on this early next week
