### ISSUE TITLE
Docs: kill "Choosing between our two platforms" and link to `about.`

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#11456]
We have this page https://docs.readthedocs.io/en/stable/choosing-a-site.html in our documentation and we have a better version of it that looks nicer and it's going to be more maintained at https://about.readthedocs.com/choosing-a-platform/. The later also have buttons to be able to signup.

I propose to kill the page from the docs and create a redirect to the page from `about.` cc @ericholscher

**Comment by ericholscher** [comment]
I feel like probably both of these pages should go away, and we should just be linking to our pricing page?

**Comment by humitos** [comment]
I opened a PR for this and added a redirect for https://docs.readthedocs.io/en/latest/choosing-a-site.html to go to https://about.readthedocs.com/pricing/

**Comment by humitos** [comment]
We need to decide what to do on the website:

- "Choosing a platform" link from the "Login" menu
- "Choosing a platform" button from the "Signup modal"

Should we remove both? Should we change the copy and to something? What else? cc @ericholscher

**Comment by ericholscher** [comment]
I know @agjohnson has had some thoughts here. I'm fine updating them to point folks to the pricing page and changing up the copy to something like "Compare our platforms" or similar?

**Comment by agjohnson** [comment]
The log in link can be a link to pricing, or maybe better it just goes away completely. That seems like the wrong answer to the user's questions on that menu.

The log in dropdown should probably have more content in it, maybe some of the content from the modal. Right now it just shows the URL might not explain too much to the user if they aren't already familiar.

The modal can link to the pricing page, as we show that on links to sign up. That seems like an okay path for new users still.

**Comment by agjohnson** [comment]
However! Looking at analytics for docs and our website, the choosing a platform page is in the top 10ish results on both. We might consider that this content is doing us some good.

I will say I have not had a user confused about which platform to use for a while now, this seems to be less likely recently. It may or may not have anything to do with the choosing a platform pages, especially as the content isn't strong.

But perhaps it does show that users have a need to learn which platform is the best fit -- perhaps in a way that the pricing page is not going to help.

**Comment by humitos** [comment]
I think we can keep the page in our website for now at https://about.readthedocs.com/choosing-a-platform/ then to centralize both pages there, at least, instead of have this content duplicated.

**Comment by ericholscher** [comment]
> However! Looking at analytics for docs and our website, the choosing a platform page is in the top 10ish results on both. We might consider that this content is doing us some good.

I'm guessing that's because we're linking folks there in multiple places, and not necessarily organic. But I agree we should just have it in one place, and the website feels like the right place.
