### ISSUE TITLE
Bulk deactivate/hide versions

### ISSUE THREAD

**Issue by edgarrmondragon** [readthedocs/readthedocs.org#11476]
## What's the problem this feature will solve?

* Deleting a bunch of old or unwanted versions from my project.
* Unhiding some preview branches.

## Describe the solution you'd like

Looking at the list of version in `https://app.readthedocs.org/projects/<project>`, I'd like to be able to select any number of versions and apply a bulk action to them, e.g. hide or deactivate them.

## Alternative solutions

This could be accomplished with the API, but it's a heavier ask for less technical users.

## Additional context

NA

**Comment by humitos** [comment]
Hi @edgarrmondragon! Thanks for opening this issue. Would you mind expanding on the use case here? Usually, projects don't have a lot of active versions that they want to hide or de-activate --that's why I'm asking for more information here to understand the context better.

If you need to do this for one of your particular projects, we can help you.

Personally, I'm not seeing this as a frequently used feature; but I may be missing something here.

**Comment by edgarrmondragon** [comment]
> Hi @edgarrmondragon! Thanks for opening this issue. Would you mind expanding on the use case here? Usually, projects don't have a lot of active versions that they want to hide or de-activate --that's why I'm asking for more information here to understand the context better.
> 
> If you need to do this for one of your particular projects, we can help you.
> 
> Personally, I'm not seeing this as a frequently used feature; but I may be missing something here.

@humitos Sure! Our library publishes a number (usually between 3 and 6) of pre-releases before a final release. These ended up in the version flyout, which was undesirable for us because we wanted to only list final versions there. This was solved for future releases by making use of automation rules, but I had to go back and "clean up" quite a few old pre-releases. Does that make sense?

**Comment by humitos** [comment]
It does make sense, yes. However, I think it was probably a miss-configuration of your project that activated _all the versions_ automatically, leading to a non-desired outcome. I think the feature would be complex enough to implement and not frequently used by many users to be useful.

On the other hand, we can help you with this particular issue. Please, contact us via https://app.readthedocs.org/support/ and we can hide/deactivate those versions for you so you don't have to do it one by one. Thanks.
