### ISSUE TITLE
Proxito: use new dashboard templates

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#11483]
The work here is:

- [x] Add all of the templates that proxito will need for login, at https://github.com/readthedocs/ext-theme/issues/427
- [x] Add error pages too, at https://github.com/readthedocs/ext-theme/issues/304)
- [ ] Set proxito templates as the new dashboard in local development
- [ ] Set proxito templates as the new dashboard in operations
- Lastly, there needs to be a discussion on cut over for user domains to the new dashboard templates

**Comment by humitos** [comment]
>  Set proxito templates as the new dashboard in local development

We cannot permanently do this since it requires using `DEBUG=False` in local development. We know this is pretty hard to do it correctly and each time we require doing it it's complex.

> Set proxito templates as the new dashboard in operations
> Lastly, there needs to be a discussion on cut over for user domains to the new dashboard templates

We already have a plan at https://github.com/readthedocs/readthedocs-ops/issues/1515 and I created a few small issues with the actionables.

**Comment by agjohnson** [comment]
> We cannot permanently do this since it requires using DEBUG=False in local development. 

Debug does not need to be disabled to use the new dashboard and proxito templates. I think you're thinking of _seeing the new error pages in Proxito_, which does indeed require running the instance with `--no-django-debug` and manually restarting the instances and performing collectstatic/etc. I'd agree we can't easily do this.

The work I did on `common` does achieve this, running the instance with `inv docker.up -we` will start both the web instance and proxito instance with the new dashboard.

So, I'd call all of this done.
