### ISSUE TITLE
Notifications: removing a message causes unwanted unknown message notification

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#11482]
I noticed that when removing a message in code, or altering the message id, that all of the old messages stored in the database but not dismissed are still emit to the user as an `Unknown message`.

To reproduce:

- Add a notification to your user, like the new dashboard notification
- Change the id of the notification in the database or delete the message in code
- Reload and you should receive this notification:

![image](https://github.com/user-attachments/assets/4680b11b-5eee-4109-bd90-2baeb6d14518)

We should probably just raise an internal error, not message the user in this scenario. Sending a message is unexpected.

**Comment by humitos** [comment]
On the user side, we should show _nothing_ (no notification at all). On the application side, we should log a Sentry event/New Relic log. We can't raise an exception because the production DB could have old IDs that were deleted in code but they are still in the DB.
