### ISSUE TITLE
Upgrade rust build environment to 1.79

### ISSUE THREAD

**Issue by nkaz001** [readthedocs/readthedocs.org#11488]
## What's the problem this feature will solve?

```
Error

Config validation error in build.tools.rust. Expected one of (1.55, 1.61, 1.64, 1.70, 1.75, 1.78, latest), got type str (1.79). Double check the type of the value. A string may be required (e.g. "3.10" instead of 3.10)
```

## Describe the solution you'd like

Please add Rust 1.79

## Alternative solutions

.

## Additional context

Since my library is using the features which is stabilized in 1.79, downgrading to 1.78 is not an option.

**Comment by nkaz001** [comment]
That's unfortunate. Is there a way to work around this, such as using the nightly version of 1.78?

**Comment by humitos** [comment]
You should be able to remove your `build.tools.rust` entry and then run the commands manually:

```yaml
asdf install rust 1.79
asdf global rust 1.79
```

Let me know if that works.

**Comment by nkaz001** [comment]
It works by manually running the build command using build.command. Thank you for your help.
