### ISSUE TITLE
Old-version notification shows on version that matches stable version

### ISSUE THREAD

**Issue by rhdtownsend** [readthedocs/readthedocs.org#11531]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/mesa-doc/

## Expected Result

In this project, the tag `stable` points to the head of the release/r24.03.1 branch in the [github repo.](https://github.com/MESAHub/mesa) Therefore, when viewing the [release/r24.03.1](https://docs.mesastar.org/en/release-r24.03.1/) documentation pages, I expect there _not_ to be a warning that I'm looking at an older version of the docs.

## Actual Result

When I view the [release/r24.03.1](https://docs.mesastar.org/en/release-r24.03.1/) documentation pages, I _do_ see a warning that I'm looking at an old version of the docs. When I switch to the [stable](https://docs.mesastar.org/en/stable/) documentation pages the warning goes away -- but the git hash at the bottom of the page remains identical.

**Comment by stsewd** [comment]
Hi, when manually setting the stable version, it no longer acts as an alias (as it can point to any commit). We have an open issue to let users truly configure a stable alias, see https://github.com/readthedocs/readthedocs.org/issues/5319.

**Comment by rhdtownsend** [comment]
Thanks for the quick response. From a quick look through the linked issue, it seems like being able to set the stable version is work in progress - do I understand correctly?


On Aug 8, 2024, at 3:05 PM, Santos Gallegos ***@***.***> wrote:

﻿

Hi, when manually setting the stable version, it no longer acts as an alias (as it can point to any commit). We have an open issue to let users truly configure a stable alias, see #5319<https://urldefense.com/v3/__https://github.com/readthedocs/readthedocs.org/issues/5319__;!!Mak6IKo!J2yp_a3CpZNSfslc4VcftsWyW2C8RYSer0oyd_fNWt6QRtYNOA7QS1jKyVaOpdTYCPHC_qFcX5nOsW-f-AeGKvSdMDo3nQ$>.

**Comment by stsewd** [comment]
> Thanks for the quick response. From a quick look through the linked issue, it seems like being able to set the stable version is work in progress - do I understand correctly?

Yes, it's a new feature we are planning to implement.

**Comment by rhdtownsend** [comment]
Thanks -- I'll keep my eyes open!
