### ISSUE TITLE
Admin: project repository selection always uses public HTTPS URL

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#11562]
In the case of private repositories, this would be both URLs to SSH and HTTPS. We likely need to use a different model property in the field name.

![image](https://github.com/user-attachments/assets/2ba6e43f-cd54-4f59-8416-9e06a05f57f7)

This list is from an organization with private repositories, they should all be SSH URLs.

**Comment by humitos** [comment]
I have a few questions here:

* Are you able to import any of those private repositories properly?
* Why do we need to show the cloning URL to the user here? I understand this is just the displayed URL, but then we are using the "cloning" URL from the `RemoteRepository` instance (which will be SSH)
* Users are not super familiarized with SSH URLs, won't just add confusion here showing some repositories with HTTPS  URLs (public) and other with SSH URLs (private)?
* What value does it add to show different URLs to users here?

**Comment by agjohnson** [comment]
> Why do we need to show the cloning URL to the user here?

We use the cloning URL in all other places -- on the project details, project admin, and in the project creation:

![image](https://github.com/user-attachments/assets/70911983-91fe-44f9-b701-b1d6878d8883)

> Users are not super familiarized with SSH URLs, won't just add confusion here showing some repositories with HTTPS URLs (public) and other with SSH URLs (private)?

The project configuration also shows a Git SSH URL used directly above the remote repo field. These two conflict in URL schemes. This is definitely more confusing that these aren't identical:

![image](https://github.com/user-attachments/assets/c2d0d4a8-d20a-425a-a761-61c262c37234)

Is there any reason _we shouldn't use the correct URL here_?

**Comment by humitos** [comment]
> Is there any reason _we shouldn't use the correct URL here_?

To me, _the correct URL_ of the repository is the HTTPS version. The SSH version is _only_ the "clone URL" and there is no reason to expose to the users in my opinion, since they can do nothing with that URL. However, the HTTPS version of it is clickable and will give users quick access to the underlying repository. The SSH version of it is useless to users.

**Comment by agjohnson** [comment]
These URLs in this field aren't clickable though. Either way, we don't need to _display_ the HTTPS URL to make an element linked. This links to the website and doesn't show the website URL:

![image](https://github.com/user-attachments/assets/981394b6-be41-46a2-812e-98fccd3f55aa)

A similar display pattern is used on the project creation form:

![image](https://github.com/user-attachments/assets/cabe6903-9b9c-4d21-a108-b180c2e16a32)

Each has:

- An icon for the repo
- A short name of `{organization/user}/{repo}`
- The cloning URL

Eventually, the remote repository selection would reuse the project creation UI. So will show the cloning URL anyways. Linking an element to the repository website is fine, but showing the website URL instead of the cloning URL would be misleading and confusing, especially for users that know about Git.

Either way, I'm really not sure what admin user would be interacting with project creation, project configuration, or the project repository and _not know what SSH URLs are_. We should be designing for users with more experience on the project admin.

A rich display is the end goal here, but until then, the cloning URL is 100% the way to go to me, and is likely a one line change in addition.

**Comment by agjohnson** [comment]
I put up a change, it was indeed small.

- #11564

The field renders the same value as the repo_url now:

![image](https://github.com/user-attachments/assets/13cbaf52-60dc-48b5-945b-2d2f44dcbb53)
