### ISSUE TITLE
2FA: login with a social account shouldn't ask for the 2fa code

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#11571]
After enabling 2FA in my account, if I login with GitHub, I'm asked for the 2FA code. We should not ask for this to users if they are login in with social accounts.

**Comment by stsewd** [comment]
Currently, allauth doesn't have an option for something like this, this will be a new feature request there.

As a note, Sentry also requires an OTP when using a social account. One may argue that setting up 2FA should then be enforced at the social provider, but I also see being useful to always enforce 2FA at the RTD level, say all members from an org in RTD for business should have 2FA, even users that aren't part of their GitHub org, but are part of their RTD org.

And requiring 2FA will also help protect users in case of a vulnerability that allows an attacker to capture the OAuth token (we had one of this in the past). It's also another layer of protection in case their social account is compromised, and they didn't set up 2FA there.

**Comment by ericholscher** [comment]
If there isn't a configuration on allauth for this, I think we're OK keeping it as implemented. I think it's a "nice to have" that isn't worth spending a bunch of time on it.
