### ISSUE TITLE
2FA: Social login doesn't work after enabling 2fA on .org

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#11570]
## Details

When enabling 2FA on .org, social login (github, gitlab) don't work, we get a 502 error from nginx (so, no sentry issue).

Not sure what else to do to debug here... it works on .com without any problems. This feels like a similar error I was having with SAML at the beginning of the implementation, it went away after some time, maybe the same will happen here :man_shrugging:

**Comment by humitos** [comment]
Are you able to reproduce this locally?

**Comment by stsewd** [comment]
And, nope, can't replicate this locally.

**Comment by stsewd** [comment]
the error in nginx is the same as https://github.com/readthedocs/readthedocs-ops/issues/1539. But I don't think the error is related to a bad header being sent, there are some guides about setting a buffer size in nginx (https://www.cyberciti.biz/faq/nginx-upstream-sent-too-big-header-while-reading-response-header-from-upstream/), but we have `proxy_buffering off;`. I think this is similar to the bug I was seeing with SAML, where the application randomly crashed. But here is more deterministic (at least when you have 2fA enabled).

**Comment by stsewd** [comment]
The SAML bug was fixed with an update to a dep https://codeberg.org/allauth/django-allauth/issues/3593#issuecomment-2297136, maybe there is another dep from 2FA that has some C deps...

**Comment by stsewd** [comment]
The SAML bug at least I was able to reproduce locally, and find the code that crashed, but here I'm not able to debug it... I tried reading the code, but I don't see anything obvious where it would crash.

**Comment by stsewd** [comment]
Tomorrow I'm going to try to call that code from the django shell, and see if it crashes

**Comment by agjohnson** [comment]
Note: this does look like the same errors from nginx as the GitHub/GitLab login issue

**Comment by humitos** [comment]
> but we have `proxy_buffering off;`.

This doesn't mean that `proxy_buffer_size` does not make any effect. Its value is always contemplated, but the strategy is different: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering

**Comment by stsewd** [comment]
This was fixed with https://github.com/readthedocs/readthedocs.org/pull/11673. For any strangers from the internet, the problem was we are using signed cookies for sessions, they can grow large, and nginx doesn't like large headers. allauth serializes the whole user and social account into the session to keep track of the login state, but it also didn't help that we had two cookies for the session.
