### ISSUE TITLE
Link checker bot (Oh Dear) now blocked

### ISSUE THREAD

**Issue by adamchainz** [readthedocs/readthedocs.org#11630]
## Details

I use a link checker tool called [Oh Dear](https://ohdear.app/). It checks all links on my blog, of which many are links to Read-the-Docs-hosted sites. This checker has given me many valuable fixes over the years, letting me fix links across some major project docs changes.

On 27 Sep, it failed with 147 new errors, all 403 responses from RtD projects:

<img width="1055" alt="Xnapper-2024-09-30-16 31 10" src="https://github.com/user-attachments/assets/e1ffbec6-d8c4-4002-b860-1ad09c8af3cb">

I'm guessing you or a provider enabled some new blocking rule that affects Oh Dear, probably to combat AI crawlers per your [June blog post](https://about.readthedocs.com/blog/2024/07/ai-crawlers-abuse/). Would it be possible to undo it? Is there something I or Oh Dear can do to pass the checks? 

* Read the Docs project URL: all of them

## Expected Result

Link checks work.

## Actual Result

403 responses.

**Comment by humitos** [comment]
@adamchainz can you provide some of those URL that are returning 403 so we have something to test against? Do those URL _always_ return 403 or they are flaky?

**Comment by humitos** [comment]
@ericholscher on Sep 26, we swapped to the new `web-ext-theme` ASG. Do you think it could be related somehow? 🤔 

Also note that another user reported a similar issue some weeks ago, https://github.com/readthedocs/readthedocs.org/issues/11615, but I wasn't able to find an issue in our side.

**Comment by adamchainz** [comment]
> @adamchainz can you provide some of those URL that are returning 403 so we have something to test against? Do those URL _always_ return 403 or they are flaky?

Sure, here's the full list:

[broken-links-adamj.eu-20241001023746-37704017990.csv](https://github.com/user-attachments/files/17202977/broken-links-adamj.eu-20241001023746-37704017990.csv)


> Is it possible to reduce the amount of requests per minute or similar as a test?

Unfortunately, they don't support any control for this. I believe they are very respectful, though.

**Comment by humitos** [comment]
I did a quick test with those URLs and all of them give me 200 or 302 with a simple `curl -ILs`. If Oh Dear is hitting rate limit, it should be a 429, instead of a 403, tho. I'm not sure what's happening here.

I also checked the amount of 403 status code in CF and I don't see they have increased after Sep 26 when we performed the ASG change:

![Screenshot_2024-10-01_12-09-38](https://github.com/user-attachments/assets/a7ca0c35-ec73-48db-9411-47c3c9ec23b5)

**Comment by humitos** [comment]
Interesting... Starting on Tuesday, Sep 24, all OhDear traffic started to return 403 for some reason.

![Screenshot_2024-10-01_12-14-50](https://github.com/user-attachments/assets/4dc4c2fd-09d1-48f1-9f00-803999cd1165)

**Comment by humitos** [comment]
I tried running the following command with 8 process in parallel:

```bash
for url in `cat urls.issue.11630.txt`; do curl -sIL -A "Mozilla/5.0 (compatible; OhDear/1.1; +https://ohdear.app/checker; brokenLinks)" $url | grep HTTP; done
```

and any of my requests were blocked. All of them returned 200/302 status codes 🤷🏼

**Comment by adamchainz** [comment]
Thanks for looking and sharing @humitos. I wonder if some other header from OhDear is tripping CloudFlare bot protection or something.

@mattiasgeniar, would you be able to advise? Maybe something changed in OhDear. If tagging on GitHub isn't appropriate, I can submit a support ticket.

**Comment by ericholscher** [comment]
This is getting blocked by the CF managed rules for AI bots, it seems:

<img width="792" alt="Screenshot 2024-10-01 at 10 22 34 AM" src="https://github.com/user-attachments/assets/75502d5d-973b-47ae-95b2-11e5fb0f2310">

**Comment by ericholscher** [comment]
I updated our managed rule, which I don't think will change anything, but will be good to test again. Can see the results [here](https://dash.cloudflare.com/76f653d51b8df4e9e956eb83a5ff42f4/readthedocs.io/security/events?user-agent~contains=OhDear&time-window=360) (CF dashboard).

**Comment by ericholscher** [comment]
I've added an explicit exemption for Oh Dear as well, so that should hopefully fix it.

**Comment by adamchainz** [comment]
I ran a new check and it came back with 403s again 😞

**Comment by adamchainz** [comment]
Okay, after another run, everything worked. Thank you @ericholscher !

**Comment by humitos** [comment]
Wohoo! Thanks for the feedback. I'm going to close this issue as solved now, but feel free to re-open/comment if it stops working for any reason.
