### ISSUE TITLE
Version selector does not appear in main page (at least for pull requests) with sphinx-rtd-theme==3.0.0

### ISSUE THREAD

**Issue by rouault** [readthedocs/readthedocs.org#11654]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/osgeo_proj/
* Build URL: https://osgeo-proj--4270.org.readthedocs.build/en/4270/

## Expected Result

Since the switch to sphinx-rtd-theme==3.0.0, the version selector does not appear in the main page (at least for pull requests), but only in sub-pages

Compare https://osgeo-proj--4270.org.readthedocs.build/en/4270/ vs https://osgeo-proj--4270.org.readthedocs.build/en/4270/about.html

Related pull request: https://github.com/OSGeo/PROJ/pull/4270

## Actual Result

Version selector should appear on main /index.html page too

**Comment by ericholscher** [comment]
I see it on the main page -- guessing this might be related to a caching issue? Does something like this work? 

https://osgeo-proj--4270.org.readthedocs.build/en/4270/?nocache=True
