### ISSUE TITLE
Python 3.13 support

### ISSUE THREAD

**Issue by jrobichaud** [readthedocs/readthedocs.org#11671]
## What's the problem this feature will solve?

Python 3.13 is out in the wild but it is not currently possible with readthedocs to use it to genererate the documentation

<img width="819" alt="image" src="https://github.com/user-attachments/assets/6a8a5eaf-baae-4ecd-9b42-ba63f6d09167">

## Describe the solution you'd like

Add python 3.13 to the available build tools

## Alternative solutions

We can of course use 3.12 in the meantime.

## Additional context

I noticed the problem when I tried bump python version to 3.13 in this project ( https://github.com/jrobichaud/django-structlog/pull/675) and the build failed.

**Comment by humitos** [comment]
Thanks for reporting this. We plan to make Python 3.13 available following our ~6 months upgrade policy. We updated these versions in June last time, so we will reach the 6-months policy in the next months. I'm adding this issue to Q4 👍🏼

**Comment by jrobichaud** [comment]
When will this be live?
I just tried with python 3.13 and it still fails.

**Comment by humitos** [comment]
Next Tuesday
