### ISSUE TITLE
Tutorial project produces "WARNING: [autosummary] failed to import lumache"

### ISSUE THREAD

**Issue by LarrySnyder** [readthedocs/readthedocs.org#11699]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/rtd-tutorial-lvs4/
* Build URL (if applicable): https://readthedocs.org/projects/rtd-tutorial-lvs4/builds/26002272/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/LarrySnyder/

## Expected Result

*Tutorial project builds without errors/warnings, pages render correctly*

## Actual Result

*Got `WARNING: [autosummary] failed to import lumache`, `ModuleNotFoundError: No module named 'lumache'`, and related warnings/errors. Also, [API page](https://rtd-tutorial-lvs4.readthedocs.io/en/latest/api.html) is blank, and `autofunction` does not render on [usage](https://rtd-tutorial-lvs4.readthedocs.io/en/latest/usage.html) page.*

<img width="340" alt="Screenshot 2024-10-19 at 1 33 07 PM" src="https://github.com/user-attachments/assets/e7502843-d058-4489-b954-7f4e46ce12ab">

<img width="656" alt="Screenshot 2024-10-19 at 1 32 31 PM" src="https://github.com/user-attachments/assets/fd23f0f1-83d9-473f-83a8-96a62eb1c84a">

## Steps to Reproduce

1. Go to [tutorial template](https://github.com/readthedocs/tutorial-template/), click "Use this template" > "Create a new repository". 
2. Enter repo name (I used `rtd-tutorial-LVS4`), leave other settings at default values, click "Create repository".
3. Go to RTD [dashboard](https://readthedocs.org/dashboard/), click "Import a Project", click "+" next to the repo, accept defaults, click "Next". (Build triggers automatically.)
4. Go to Builds page, open the build, "View raw". Log contains:

```
[rtd-command-info] start-time: 2024-10-19T17:22:14.871854Z, end-time: 2024-10-19T17:22:16.045951Z, duration: 1, exit-code: 0
python -m sphinx -T -b html -d _build/doctrees -D language=en . $READTHEDOCS_OUTPUT/html
Running Sphinx v7.1.2
making output directory... done
[autosummary] generating autosummary for: api.rst, index.rst, usage.rst
WARNING: [autosummary] failed to import lumache.
Possible hints:
* ModuleNotFoundError: No module named 'lumache'
* KeyError: 'lumache'
* ValueError: not enough values to unpack (expected 2, got 1)
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://www.sphinx-doc.org/en/master/objects.inv...
building [mo]: targets for 0 po files that are out of date
writing output... 
building [html]: targets for 3 source files that are out of date
updating environment: [new config] 3 added, 0 changed, 0 removed
[2Kreading sources... [ 33%] api
[2Kreading sources... [ 67%] index
[2Kreading sources... [100%] usage
/home/docs/checkouts/readthedocs.org/user_builds/rtd-tutorial-lvs4/checkouts/latest/docs/source/api.rst:4: WARNING: autosummary: failed to import lumache.
Possible hints:
* ModuleNotFoundError: No module named 'lumache'
* KeyError: 'lumache'
* ValueError: not enough values to unpack (expected 2, got 1)
WARNING: autodoc: failed to import function 'get_random_ingredients' from module 'lumache'; the following exception was raised:
No module named 'lumache'
WARNING: autodoc: failed to import exception 'InvalidKindError' from module 'lumache'; the following exception was raised:
No module named 'lumache'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
copying assets... copying static files... done
copying extra files... done
done
[2Kwriting output... [ 33%] api
[2Kwriting output... [ 67%] index
[2Kwriting output... [100%] usage
generating indices... genindex done
writing additional pages... search done
dumping search index in English (code: en)... done
dumping object inventory... done
```

**Comment by stsewd** [comment]
Hi, this is part of the tutorial, see https://docs.readthedocs.io/en/stable/tutorial/#making-build-warnings-more-visible.

**Comment by LarrySnyder** [comment]
Oof, sorry about that!
