### ISSUE TITLE
Addons: show notification only on non-default versions

### ISSUE THREAD

**Issue by kmnhan** [readthedocs/readthedocs.org#11701]
## What's the problem this feature will solve?

Under the notifications tab in addons menu, there is an option to show a notification on non-stable and latest versions. Currently this option shows notifications on all non-stable versions including `latest`.

I'm currently using `latest` as the default version since it allows quick doc updates without new releases. Hence, I don't want to notify users on `latest` but I still want to display notifications on outdated builds.

## Describe the solution you'd like
IMO notifications should be displayed on all *non-default* versions instead of non-stable versions, and the link on those notifications should point to the default version instead of `stable`.

## Alternative solutions
Add more fine-grained options for the notifications such as customizing the messages

**Comment by humitos** [comment]
We have an issue that seems to be the same as this one at https://github.com/readthedocs/addons/issues/133. Basically, it will allow you to disable "showing a notification on `latest` version". I understand that will solve your issue, right?

**Comment by kmnhan** [comment]
Yup! Thanks, didn't know that addons had a separate repo. May be nice to mention that in the docs or issue template?

**Comment by humitos** [comment]
Yes, thanks for the suggestion. We are trying to consolidate all the work around addons and make it more explicit.
