### ISSUE TITLE
Traffic dropped to 0

### ISSUE THREAD

**Issue by Caenorst** [readthedocs/readthedocs.org#11713]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/kaolin/

We saw a drop to 0 or 1 views on our doc since October 8, we used to have at least 100 views per day.
Github views / unique views / cloning are consistently at 100+ per day too.

**Comment by stsewd** [comment]
Hi, please see https://github.com/readthedocs/readthedocs.org/issues/11707 and https://github.com/readthedocs/readthedocs.org/issues/9530#issuecomment-2233541583 for a solution.
