### ISSUE TITLE
Downloading from Jupyter Book

### ISSUE THREAD

**Issue by afeld** [readthedocs/readthedocs.org#11728]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/computing-in-context/, https://readthedocs.org/projects/jupyter-book/, etc.
* Build URL (if applicable): n/a
* Read the Docs username (if applicable): https://readthedocs.org/profiles/afeld/

## Steps to Reproduce

1. Visit a Jupyter Book, such as [this Markdown page](https://computing-in-context.afeld.me/) or [this notebook page](https://computing-in-context.afeld.me/lecture_16.html).
2. In the toolbar at the top, hover over the download (⬇️) icon.
3. Click `.md` or `.ipynb`, respectively.

## Expected Result

The file is downloaded.

## Actual Result

The Markdown or notebook JSON (respectively) is shown as plain text.

## Additional information

Pretty sure this used to work without any relevant change on my end, so assuming there was some change with the hosting infrastructure...?

If the desired behavior is to download JSON etc. by default, [the `Content-Disposition` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) would need to be set to `attachment`. Looking at [the architecture](https://me-readthedocs.readthedocs.io/en/latest/development/architecture.html), the header could be added via [`add_header` in the NGINX config](https://nginx.org/en/docs/http/ngx_http_headers_module.html), or [in Cloudflare using HTTP response header modification rules](https://developers.cloudflare.com/rules/transform/response-header-modification/).

If it should be configurable, then that would need changes a bunch of places I imagine 🙂 

Thanks!

**Comment by humitos** [comment]
I'm not able to reproduce this issue. I'm able to see the plan text `.md` file and the `.ipynb` as a JSON file. Also, clicking on the PDF it opens the modal to print the current page.

I'm on Firefox 132.0

**Comment by afeld** [comment]
Right, the plain text is showing:

<img width="1624" alt="image" src="https://github.com/user-attachments/assets/7b565c28-a280-4826-828f-1886d508c879">

Tested on Firefox 131.0.3, Chrome 130.0.6723.70, and Safari 18.0.1 — the behavior is the same.

The hope is that the Markdown/JSON were automatically downloaded as files; in other words, that visiting https://computing-in-context.afeld.me/_sources/index.md would automatically download `index.md`. I believe this was previously the behavior on ReadTheDocs, at most a year ago, maybe?

The workaround is [having people do `File`->`Save File As...`](https://computing-in-context.afeld.me/notebooks.html#downloading-notebooks). My site is for students who are new to coding, and therefore I'd like to avoid any extra steps/confusion.

Hope that all makes sense!

**Comment by afeld** [comment]
Iiiiinteresting, didn't know about the `download` attribute. Ok, will propose that solution to the theme.

**Comment by afeld** [comment]
Thanks for the quick responses!
