### ISSUE TITLE
build

### ISSUE THREAD

**Issue by Faith-Ogundu** [readthedocs/readthedocs.org#11735]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/{your_project_slug}/
* Build URL (if applicable): https://readthedocs.org/projects/{your_project_slug}/builds/{build_id}/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/{your_rtd_username}/

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by Faith-Ogundu** [comment]
my github is failing to implement changes. it failing to build with jekyll

**Comment by stsewd** [comment]
@Faith-Ogundu please fill all the information from the template, there isn't much we can do to help otherwise.
