### ISSUE TITLE
Cannot change the "Default branch" field

### ISSUE THREAD

**Issue by wRAR** [readthedocs/readthedocs.org#11772]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/scrapy/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/wRAR

I'm trying to change the "Default branch" field from 2.11 to 2.12 on https://app.readthedocs.org/dashboard/scrapy/edit/ and while it shows 2.12 after the form is submitted, refreshing the page shows 2.11 again.

**Comment by humitos** [comment]
I'm not able to reproduce this issue.

However, I noticed that it was _incredibly slow_ after hitting "Save" button. Maybe you got a 502 and that's why it didn't save the changes?

Would you mind trying it again?

**Comment by wRAR** [comment]
The answer is simple, the "Description" field fails validation due to now being longer than allowed, and I didn't notice this :(
