### ISSUE TITLE
Traffic data missing

### ISSUE THREAD

**Issue by zhenry9** [readthedocs/readthedocs.org#11784]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/mrb-docs/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/zhenry9/

## Expected Result

Clicking on traffic analytics should show page view data. 

## Actual Result

No data available displayed, 0 page views. My project is for internal use and for sure doesn't have lots of views, but it definitely has some. A lot from me on different devices, as well as some from other employees. I would like access to this data to measure usage of the documentation.

**Comment by humitos** [comment]
Do you have addons analytics enabled? You can enable it following these steps: https://docs.readthedocs.io/en/stable/traffic-analytics.html
