### ISSUE TITLE
Repeat of issue #11615

### ISSUE THREAD

**Issue by oleibman** [readthedocs/readthedocs.org#11845]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/phpspreadsheet/
* Build URL (if applicable): https://readthedocs.org/projects/{your_project_slug}/builds/{build_id}/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/{your_rtd_username}/

Problem first reported as https://github.com/readthedocs/readthedocs.org/issues/11615 in September. You suggested that I open an issue with Php, which I did. They offered a suggestion on how my code might be changed, and that worked from Sep. 24 until yesterday, when it failed with they same symptom (403 attempting to use Php file_get_contents to read url). This time, I opened an issue with Php first. They suggested I contact you. https://github.com/php/php-src/issues/17121

I hope one of you can figure out what's going wrong. This is slightly different than the previous problem. Then, the problem was repeatable in all environments. Now, it seems to only happen from Github. Our test suite is run several times a day, but only 4 requests are made to your site with each run. Php suggests that maybe our user-agent is missing, but I don't see why that would cause github to behave differently than my local environment. Also, I tested using curl instead of file_get_contents, and that worked in all environments, but I'm not sure it's a requirement I wish to add to my project.

## Expected Result

No error/warning messages fetching an image from `https://phpspreadsheet.readthedocs.io/en/latest/topics/images/01-03-filter-icon-1.png`

## Actual Result

```
Exception: file_get_contents(https://phpspreadsheet.readthedocs.io/en/latest/topics/images/01-03-filter-icon-1.png): Failed to open stream: HTTP request failed! HTTP/1.1 403 Forbidden
```

**Comment by cmb69** [comment]
Might be related to #11630.

**Comment by oleibman** [comment]
Seem to have arrived at a usable solution in the Php ticket.
