### ISSUE TITLE
https://twilio-php.readthedocs.io/en/latest/ taken over by a unauthorised user

### ISSUE THREAD

**Issue by sbansla** [readthedocs/readthedocs.org#11859]
Previously link **https://twilio-php.readthedocs.io/en/latest/** was used by "https://github.com/twilio/twilio-php" 
But now it has been used by taken over by a "https://github.com/suaib98/twilio-php" which does not exists

Question:
1. I would like to know how the process works, if one github repo stopped using a readthedocs link, then can it be taken over by other github repo ? Is this the standard procedure ?

**Comment by humitos** [comment]
Hi. Please, follow the following guide: https://docs.readthedocs.io/en/stable/abandoned-projects.html
