### ISSUE TITLE
i18n (non-english) builds and deployment on readthedocs

### ISSUE THREAD

**Issue by rufuspollock** [readthedocs/readthedocs.org#139]
readthedocs appears to have some intention to support different language builds of material as it puts 'en' into all urls :-)

However, I can't see from the readthedocs docs or the dashboard how to enable i18n builds or how to get deployed.

As a concrete use case we are building Open Data Manual in both english and other languages off of sphinx rest stored in github (see https://github.com/okfn/opendatamanual -- whose README details how we prep and build the i18n material):
- http://opendatamanual.org/en/ - english (we don't currently add the version in the url but that would be no problem to change)
- http://opendatamanual.org/it/ - italian

We'd love to use readthedocs for this but need some way to have, for example, the 'it' version built and deployed. (We considered a hack approach by using the subproject feature but we imagined this would lead to urls like {subproject}/en/latest).

NB: i18n until recently was only in head for sphinx but as of v1.1 is now in main release.

Thanks again for creating such a great tool.

**Comment by techtonik** [comment]
@myroslav have you created the new issue?
