### ISSUE TITLE
Remove our hacked Domain Validator in new Django

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#1707]
https://code.djangoproject.com/ticket/18119 is the ticket for tracking this.

**Comment by stsewd** [comment]
The related PR isn't merged in django yet

**Comment by humitos** [comment]
This is the upstream PR: https://github.com/django/django/pull/7300

I'm moving this out from 3.0 since it's not on us and it's more like a Cleanup task.

**Comment by humitos** [comment]
This is the chunk of code we want to remove:

https://github.com/rtfd/readthedocs.org/blob/4031b9078efba9948301e89c948a236671086d26/readthedocs/projects/validators.py#L23-L50

Our code was copied from an old PR, https://github.com/django/django/pull/3477
