### ISSUE TITLE
Warn or Fail build if there is no `index.html` generated

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#1800]
Docs look broken when there isn't an index file to serve. We should probably be validating that an `index.html` or a `README.html` exists, which we will serve at the root of their docs.

**Comment by humitos** [comment]
I think this is already implemented since when there is no `index.html` generated RTD generates one for us with a message which also points to the "Getting Started Guide" at #3447 

@ericholscher If that's the issue, can we close this one?

**Comment by ericholscher** [comment]
Believe this should still be the case. People can still have no `index.[md|rst]` and have a build pass. We're only generating them if there is no sphinx/mkdocs config found.

**Comment by stsewd** [comment]
Related issue #2483

**Comment by agjohnson** [comment]
This is also very easy to hit with mkdocs.

**Comment by stsewd** [comment]
I don't think we have a way to indicate a `waning` in the build process. Also, mkdocs already handle the case where users have a README file, so, we can't just check for a missing index file, we could do the check in the generated docs.

**Comment by stsewd** [comment]
Also, now sphinx-quickstart suggest an index file by default, which can help to have fewer users without an index file.

**Comment by humitos** [comment]
Checking for `index.html` after build instead of at build time (checking for `.md` or `.rst`) is good. I just found an example where the `index.html` comes from an static `.html` file and we were creating an `index.md` that overrides the static file the user wanted. See https://github.com/readthedocs/readthedocs.org/pull/7305

**Comment by ericholscher** [comment]
Yea -- we should be able to figure this out via ImportedFile objects, and wouldn't be a hard feature to build I think 👍

**Comment by chrisjsewell** [comment]
FYI, I was just bitten by this in https://github.com/executablebooks/sphinx-external-toc/issues/1#issuecomment-817374457

**Comment by humitos** [comment]
We did some work to start logging what are the projects where we are creating the `index.html` file automatically at https://github.com/readthedocs/readthedocs.org/pull/10471. After some weeks we will contact them telling we are removing this feature.

I'm assigning this issue to myself so I work on this in the next weeks.

**Comment by humitos** [comment]
We have some logs already at https://onenr.io/0LwGgpA0Yw6. It seems we have around ~114 projects (.org and .com combined)
