### ISSUE TITLE
Change Iranian language support to Persian or Farsi

### ISSUE THREAD

**Issue by eafzali** [readthedocs/readthedocs.org#2007]
I'm trying to add Farsi translation to my docs but there's no Farsi option available on readthedocs.org

**Comment by eafzali** [comment]
Oh, I've found it. It's named Iraninan. It should be renamed to Farsi or Persian. https://en.wikipedia.org/wiki/Persian_language

**Comment by agjohnson** [comment]
Thanks for the background on this, we should get this updated. It seems this currently refers to the Iranian language family, and might also require breaking out other languages in the family? Lacking knowledge here, I'm depending on Wikipedia, which mentions Persian, Pashto, Kurdish, and Balochi as major languages in the family. I'm not sure how granular this needs to get though.

If anyone has an additional input here, it would be helpful!

**Comment by ericholscher** [comment]
I'm going to close this, since I don't think we have the information needed. Feel free to comment on this ticket with more info and we'll consider it 👍
