### ISSUE TITLE
Do site confirmation with AJAX & in-page popup

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#2034]
Currently we have a lot of pages that are "are you sure?" things that would be better for UX being just an API call with a verification. Refactor code to fix this.

**Comment by dojutsu-user** [comment]
@ericholscher 
I found the "are you sure?" page on following activity:

- Deletion of a domain
- Wiping a version
- Signing Out
- Cancelling Gold Subscription
- Deletion of a project

Is there anything that I'm missing out?
and also, do you want the `in-page popup confirmation` and then `AJAX call` on all the pages in the above list?

**Comment by humitos** [comment]
This is already done on the new beta dashboard https://beta.readthedocs.org/

![Screenshot_2023-09-15_13-36-41](https://github.com/readthedocs/readthedocs.org/assets/244656/ed0ff8f2-b46f-44f2-9885-c712099be134)

![Screenshot_2023-09-15_13-35-57](https://github.com/readthedocs/readthedocs.org/assets/244656/fb2f2810-cfa7-4c2d-be00-18968126ef45)
