### ISSUE TITLE
Add documentation for translation contributors

### ISSUE THREAD

**Issue by thwee-alchemist** [readthedocs/readthedocs.org#2107]
Greetings,

I saw that some of your localization is incomplete, and I'm interested in localization anyway. I used to speak fluent German, and was wondering if you could show me how you do localization, while I  help out with some of the language. 

I'm Software Engineer and have a professional interest in localization, even though it seems to be going the way of the Dodo.

For starters, I was wondering how much of a time commitment you look for when contributing, or how much time your contributers typically log. I know this can be a difficult measure to get, but even a personal estimate would be plenty for me, providing me something to look forward to :)

Joshua Moore

**Comment by agjohnson** [comment]
Great, we're excited for the interest! Sorry we've been awful about providing a clear path for this.

As far as how *we* do localization, here's some background:
http://docs.readthedocs.org/en/latest/i18n.html

As far as how *contributors* would help us, or other projects, with translations, we desperately need to write this documentation.

Translation contributions should be fairly minimal for maintaining translations, though the initial translation effort might take a while to catch up with all the strings. We'll see about getting this contribution doc set up for folks interested in lending a tongue.

**Comment by stsewd** [comment]
Related to https://github.com/rtfd/readthedocs.org/issues/2607

**Comment by agjohnson** [comment]
We have a few docs on managing i18n, but I think we still need a contributor doc. Adding this to our i18n milestone.

**Comment by rffontenelle** [comment]
Currently, there's a [Contributing to Read the Docs](https://docs.readthedocs.io/en/stable/contribute.html) page with a tiny section called [Helping on translations](https://docs.readthedocs.io/en/stable/contribute.html#helping-on-translations).

I would love to see mentions on translating Transifex resources "readthedocs" (software translation) and "readthedocs-docs" (documentation translation), managing local translation (e.g. running `tx` and `django-admin` to update message catalogs), testing translation before considering it ready, etc.

**Comment by humitos** [comment]
@rffontenelle I wrote a "Guide: Manage Translations" some time ago at https://docs.readthedocs.io/en/stable/guides/manage-translations.html. Would you like to take a look and open a PR with the suggested changes?

**Comment by humitos** [comment]
I'm closing this issue and pointing people arriving at this issue to #4462
