### ISSUE TITLE
Extend webhook notifications with build status (queued, running, failed, succeeded) & commit id

### ISSUE THREAD

**Issue by Korijn** [readthedocs/readthedocs.org#2251]
Webhook build notifications currently trigger only on build failure. Also, the `commit_id` that was built is missing from the JSON object that is sent.

If possible, I'd like to extend this feature to trigger on any build status transition:
- queued
- running
- failed
- succeeded

Also, in order to integrate with e.g. Bitbucket/Github build status APIs, the `commit_id` should be included in the JSON object that is sent.
## Requirements

Webhooks are not currently set up as an asynchronous task, meaning sending these notifications will block the process. We should instead be executing these as Celery tasks. The function that currently sends these notifications is here:
https://github.com/rtfd/readthedocs.org/blob/712e75d30a92bbdcf3a2597dafc16c58897eeefc/readthedocs/projects/tasks.py#L776

This will require the following work items:
- [ ] All current calls to `webhook_notification` should be changed to execute a task instead. This will require setting `webhook_notification` as a Celery task as well. This should only execute on the `web` task queue.
- [ ] `webhook_notification` should add the `Build.commit` attribute to the data payload
- [ ] Add asynchronous task calls to other points in the build system -- when we queue a build, when we start a build, and when we finish a build. Currently, we only call this when the build fails.
- [ ] Emails should only send on failure, webhooks should send regardless of the build status at the end of the build task

Here is the actual build task:
https://github.com/rtfd/readthedocs.org/blob/712e75d30a92bbdcf3a2597dafc16c58897eeefc/readthedocs/projects/tasks.py#L105

Here is where builds currently send failure notifications:
https://github.com/rtfd/readthedocs.org/blob/712e75d30a92bbdcf3a2597dafc16c58897eeefc/readthedocs/projects/tasks.py#L185

Builds are triggered from:
https://github.com/rtfd/readthedocs.org/blob/f6603f40599fac810993989cffc55da82f19feeb/readthedocs/core/utils/__init__.py#L67

**Comment by agjohnson** [comment]
Both of these additions sound like features we should have. I think this stands to be a single ticket here. It should be simple enough to attribute the changeset that triggered the build. In order to trigger webhook notifications on extraneous functions, we would have to add more task triggers in the project build functions. Currently, the notifications are only triggered at the point that the project build failed.

**Comment by shubheksha** [comment]
@agjohnson, I'd like to take this up!

**Comment by agjohnson** [comment]
Great! If you need some more direction, I can update the description here a bit further. Let me know if you have questions on any implementation details, I'm happy to answer.

**Comment by shubheksha** [comment]
Sorry about getting back so late! It would be of immense help if you can update the description further & give me a little direction on how to start. I've been going through the celery [docs](http://docs.celeryproject.org/en/latest/userguide/tasks.html) to familiarize myself with tasks.

**Comment by gvanrossum** [comment]
@agjohnson Could you help @shubheksha out here? She's trying to contribute for the first time and she would like you to give her some more specific guidance on this particular issue. E.g. is reading up on celery useful at all? What exactly did you mean by "there should really be a wrapper task around this"? (I wish I knew this code base better so I could answer that myself!)

**Comment by Korijn** [comment]
@agjohnson  Are you too busy? I can work out a plan for @shubheksha if you're unavailable.

**Comment by gvanrossum** [comment]
Please do help!

**Comment by agjohnson** [comment]
Sorry all, this fell off my radar :( I can expand on some of what i laid out above, but @Korijn, more help would be always be welcome here as well!

**Comment by agjohnson** [comment]
@shubheksha I updated the description with some more explicit information on how this would be implemented. Feel free to raise a question here if something doesn't make sense, I'm happy to provide more guidance.

This will require some basic knowledge of Celery, but only enough to implement a `task` decorator around the current `webhook_notification` function and turn the current calls into task calls. Currently, we're executing `webhook_notification` directly from the project build task.

**Comment by shubheksha** [comment]
Thank you, @Korijn & @gvanrossum. :smile: 
@agjohnson - thank you for the expanded description. I will try to get something working & ask for further guidance in case I get stuck!

**Comment by humitos** [comment]
@shubheksha were you able to start working on this? are you still interested on this issue? Maybe we can take a look together.

**Comment by safwanrahman** [comment]
>All current calls to webhook_notification should be changed to execute a task instead. This will require setting webhook_notification as a Celery task as well. This should only execute on the web task queue.

@Korijn There are only one calls of `webhook_notification` is `send_notifications` task. As `send_notifications` is already a task and is called assynchronously everywhere, I think creating task for each webhook notification is overkill.
https://github.com/rtfd/readthedocs.org/blob/712e75d30a92bbdcf3a2597dafc16c58897eeefc/readthedocs/projects/tasks.py#L732-L739

I think this issue should cover sending webhook notification all the time of the build, while its queyed, failed or successed.

**Comment by 73VW** [comment]
Has anyone made progresses on this?

How can I help?

I was thinking about making a Gitter integration for Read the Docs but I saw that there was only the failure notification. It would be really nice if we could implement this then we could have all build status appear in Gitter activity tab just like for Travis or others.

**Comment by shivanshu1234** [comment]
Has this issue gone stale? If not, I would like to work on it.

**Comment by ZeyadYasser** [comment]
Seems like nobody is working on this, I will start working on it.

**Comment by ZeyadYasser** [comment]
As @safwanrahman said `send_notifications` is already a task and is called asynchronously, I think it would be sufficient to adjust it so it only sends emails if the build fails, and just use it for other states (queued, running, failed, succeeded).
https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/projects/tasks.py#L1352-L1365
Please correct me if I am wrong.

**Comment by Korijn** [comment]
Sounds good to me?

**Comment by ZeyadYasser** [comment]
While working on this I faced a design issue.
[Github's build status](https://developer.github.com/v3/repos/statuses/#create-a-status) webhook url depends on the sha of the commit
e.g. `https://api.github.com/repos/:owner/:repo/statuses/:sha`
so the user will not be able to supply it as webhook in the settings of his project as it might vary from build to build.
I found that the case is similar with gitlab and bitbucket status APIs.
Do you think we should maybe allow placeholders? so the supplied url would be something like this maybe
`https://api.github.com/repos/:owner/:repo/statuses/{commit_hash}` where commit_hash will be replaced with the commit hash before sending the request. 
I think that it might not be intuitive in the UI, maybe a hint in the (notifications settings) page would make it better?

**Comment by karnicaa** [comment]
Hi. Is this issue still open?

**Comment by stsewd** [comment]
@karnicaa yes, there is a PR for it https://github.com/readthedocs/readthedocs.org/pull/5621
