### ISSUE TITLE
Subprojects feature appears to conflict with "projects" dir on packaging.python.org

### ISSUE THREAD

**Issue by ncoghlan** [readthedocs/readthedocs.org#2292]
## Details

packaging.python.org has a subpage called "projects" to list some of the core packaging related projects: https://github.com/pypa/python-packaging-user-guide/blob/master/source/projects.rst

Since PyPUG is built using Sphinx HtmlDir, that normally appears at: https://packaging.python.org/projects/
## Expected Result

The ReST text linked above is rendered at the given URL
## Actual Result

We get a 404 error as described in https://github.com/pypa/python-packaging-user-guide/issues/253

This works fine when building locally, so my suspicion is that it's a collision with the new(ish) subprojects feature: http://read-the-docs.readthedocs.io/en/latest/faq.html#how-do-i-host-multiple-projects-on-one-cname

**Comment by ncoghlan** [comment]
Just noting that we'll probably address this specific instance on PyPUG's end by renaming the affected page, but it would still be preferable if the "projects" subdirectory was usable for documentation sets that aren't using the subprojects feature.

**Comment by ncoghlan** [comment]
I've renamed the offending PyPUG page to "key_projects.rst", so the collision has been resolved in our particular case, but it was still a very confusing failure mode.

**Comment by agjohnson** [comment]
Sorry for this confusion, yeah it's a path issue with the web servers in front of the docs. We have an issue open already for this on our operations repo, I'll update here when things should be resolved.

**Comment by stsewd** [comment]
I'm not sure if something changed in the server, but I can't replicate this now https://test-simple-stsewd.readthedocs.io/en/latest/projects/ I'm using `htmldir` as builder, I also tested it with the `html` builder, `/projects` was 404 and `/projects.html` was ok.

**Comment by stsewd** [comment]
Oops, now I was able to replicate the problem, it happens when the project is a `single version`.

**Comment by humitos** [comment]
I think we now have everything in place to make this issue/feature request/bug possible by allowing to define a different URL regex for projects.

**Comment by humitos** [comment]
@stsewd @ericholscher can we solve this issue by using our new feature for custom URLs?

**Comment by stsewd** [comment]
@humitos the new proxito implementation won't have this problem.
