### ISSUE TITLE
Document TikZ support

### ISSUE THREAD

**Issue by jluttine** [readthedocs/readthedocs.org#234]
I'm using the following TikZ extension to Sphinx succesfully on my computer:
http://people.ee.ethz.ch/~creller/web/tricks/sphinx-tikz.html

I added the extension (tikz.py) to my github repository and tried whether readthedocs manages to build the docs. It can build PDF with the figures nicely but building HTML generates a warning:
"WARNING: pdftoppm command cannot be run"
and the build process doesn't succeed.

Would it be possible to have necessary packages installed? For Ubuntu Linux you roughly have to have the following packages installed: texlive, texlive-pictures, poppler-utils, and netpbm or imagemagick (according to the TikZ extension website).

**Comment by argriffing** [comment]
Just to make sure I understand, there is not a way for me to use tikz within the sphinx rst files of docs hosted on readthedocs.org? Sorry to revive such an old issue/thread.

**Comment by jluttine** [comment]
@ericholscher Yeah, old issue, but... :) Would it be possible to install the necessary Ubuntu packages? It'd be much more convenient than the clumsy workaround. I'm now working on a simple wrapper package that would distribute only those missing binaries so that users could specify that package as a requirement in RTD. That would make the workaround much easier to use. But it sure would be even easier if those packages were installed in the RTD system. I think that those image conversion/manipulation libraries might be useful for some other packages as well.

@argriffing If you use sphinx-tikz extension, you can use TikZ in Sphinx documentation, but in order to make it work on readthedocs.org, you currently need to do some tricks to be able to use the missing binaries.

**Comment by jluttine** [comment]
Oh, actually I found a simple fix. The package I'm using had a new option to choose a different backend which is supported by Read the Docs. So, I think I'm good, thanks anyway! :+1:
