### ISSUE TITLE
Make prefix redirect to respect the language if present in the path

### ISSUE THREAD

**Issue by jab** [readthedocs/readthedocs.org#2347]
I have a prefix redirect set up for bidict.readthedocs.io with "from URL" set to `/`, and no other redirects set up. This is causing e.g. bidict.readthedocs.io/changelog.html to redirect to bidict.readthedocs.io/en/master/changelog.html as desired, i.e. when the url includes no language or version, you are redirected to a default language and version.

However, bidict.readthedocs.io/en/changelog.html should also redirect to bidict.readthedocs.io/en/master/changelog.html, but instead it redirects to bidict.readthedocs.io/en/master/en/changelog.html, which gives 404. i.e. When the url does include a language but does not include a version, the prefix redirect should intelligently redirect to the default version for the given language.

Any interest in adding support for this?

**Comment by humitos** [comment]
I understand your point.

I'd say, how do we know that `/en` in `/en/changelog.html` means the language and not just a subpath?

We could adapt this code to check also without the `<version_slug>` but we would need to write a good amount of tests and check that we are not breaking other places.

https://github.com/rtfd/readthedocs.org/blob/4fa2746040aee0aafcdb09e0e5674dcb42ea9809/readthedocs/redirects/utils.py#L57-L59

**Comment by stsewd** [comment]
There isn't a good way to determinate if the path is a language or part of the path. But what you want can be done with exact redirects.

- `/en/$rest` -> `/en/latest/`
- `/$rest` -> `/en/latest/`
