### ISSUE TITLE
Deleted repository not detected

### ISSUE THREAD

**Issue by beruic** [readthedocs/readthedocs.org#2412]
## Details

I have deleted the repository at https://github.com/beruic/bootstrap-tagsinput, but it does not disappear when i refresh in the repository importer at https://readthedocs.org/dashboard/import/.

**Comment by humitos** [comment]
I confirm that I'm able to reproduce this. I created a repository called `1` in GitHub and I imported without problem to RTD. Then I deleted the project from RTD and also from GitHub. After that I hit re-sync in RTD and I still seeing my `1` repository to be able to import.

**Comment by beruic** [comment]
I just checked BTW. The deleted repository still appears in my list.

**Comment by humitos** [comment]
After #7183, GitHub integration in cleaning up old `RemoteRepository` from that user _only if it's not connected to a Project_. This will have impact in the "Import Project" page that won't show stale repositories that do not exist anymore.

The same work/code needs to be ported to GitLab and Bitbucket to be able to close this issue.
