### ISSUE TITLE
Stop creating a conf.py/mkdocs.yaml file automatically for users and doing magic 

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#2483]
We should stop adding a `conf.py` file for projects that don't have one.  We also used to do magic around README handling, we should remove it:

https://github.com/rtfd/readthedocs.org/blob/535f31540fea36a321d148cfee302b34e90adfc9/readthedocs/doc_builder/base.py#L97-L116

**Comment by stsewd** [comment]
We could create a redirect for all projects? Also, for mkdocs projects, this is already done in the mkdocs side https://github.com/rtfd/readthedocs.org/issues/1615#issuecomment-441853457

For sphinx there isn't a configuration or an extension (I just did a simple google search). I guess we could write this in the rtd-extension, or just deal with this creating an index file. Why? Because people can even create docs without a README file, and hit the 404 issue.

**Comment by ericholscher** [comment]
Updated this issue to be about removing the magic around README handling.

**Comment by saadmk11** [comment]
If I understood correctly we need to remove this part of the code:
https://github.com/rtfd/readthedocs.org/blob/2872832d75ebd8098184e714b9101a455504e1eb/readthedocs/doc_builder/base.py#L106-L111

we will not support README to index creation anymore ?

 and for `sphinx` builder we should remove this part of the code to not automatically create the config file:
https://github.com/rtfd/readthedocs.org/blob/2872832d75ebd8098184e714b9101a455504e1eb/readthedocs/doc_builder/backends/sphinx.py#L175-L177

which will generate a `NOT_FOUND` Error.
Can you Please confirm? if that's what needs to be done here?

**Comment by davidfischer** [comment]
> should remove this part of the code to not automatically create the config file

I will let others chime in as well, but I am in favor :+1: of removing this.

In general, I believe that Read the Docs should not make broken projects build that are unable to be built outside of Read the Docs. This will lead to more predictable builds.

**Comment by astrojuanlu** [comment]
It is my understanding that this is not a "Good First Issue"?

**Comment by stsewd** [comment]
yeah, this is going to be handled when we have the new builders in place.

**Comment by humitos** [comment]
There is a bunch of history here and lot of issues linked to this issue plus others that talk about probably the same thing. So, I'm doing a small summary of what we are doing here:

- find all the projects where we are creating a Sphinx/MkDocs configuration file (using our logs from https://github.com/readthedocs/readthedocs.org/pull/5609#issuecomment-1620084901)
  - Community:
    - Sphinx: 1.6k
    - MkDocs: 143
  - Commercial:
    - Sphinx: 187
    - MkDocs: 20
- write a changelog blogpost about this deprecation and removal with an exact date
- contact them to communicate we are deprecating this feature and they should upgrade their projects before that date
- update https://github.com/readthedocs/readthedocs.org/pull/5609 to remove the auto-create configuration files

**Comment by humitos** [comment]
I sent the email to these users today 📧 🚀 . We set August 28th for the feature removal.
