### ISSUE TITLE
Symlinks and subdomains

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#2661]
Reading this, http://docs.readthedocs.io/en/latest/symlinks.html#subdomains, I'm not sure if this is correct, outdated, or could be better.

```
location ~ ^/en/(.+)/(.*) {
    alias /home/docs/checkouts/readthedocs.org/user_builds/$domain/rtd-builds/$1/$2;
    error_page 404 = @fallback;
    error_page 500 = @fallback;
}
```

How do you handle the multi language documentations here?

Example, http://scrapy-chs.readthedocs.io/zh_CN/latest/

**Comment by agjohnson** [comment]
We should just remove Nginx examples, it's not part of RTD configuration. Our actually Nginx configuration is different that this.

**Comment by humitos** [comment]
@agjohnson do you want me to make a PR that removes all of these non-RTD configurations?

**Comment by agjohnson** [comment]
@humitos hold off for now, we need to make a decision on what to keep in our docs

**Comment by ericholscher** [comment]
We've removed symlinks, so closing this 👍
