### ISSUE TITLE
Alter the use of RemoteRepository

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#2759]
Thinking about this more, `RemoteRepository` should not be a mapping of user access to remote repository objects, but instead should be just a list of accumulated remote repository objects. There should be a secondary table that provides a many to many mapping between remote users and remote repository objects. This lets us associate a project to a GitHub repo, for example, and multiple users would get access to the project on our side.

- [ ] Add a model for remote user <-> remote repository
- [ ] Add a migration that moves this data around
- [ ] Make sync operations update both tables

**Comment by aswinshenoy** [comment]
I wish to work this issue @agjohnson, is this still open?
Regards

**Comment by humitos** [comment]
This was done in originally https://github.com/readthedocs/readthedocs.org/pull/7536, and the work continued in the branch https://github.com/readthedocs/readthedocs.org/tree/remote-repository-normalization

I think we can close this issue. I'm trying to target the start of data sync for next deploy.
