### ISSUE TITLE
Standardize language slug in URLs (e.g. `/pt_BR/` -> `/pt-br/`)

### ISSUE THREAD

**Issue by JulienPalard** [readthedocs/readthedocs.org#2763]
Hi,

I have a question about the `lang_slug` which currently is, according to [models.py:175](https://github.com/rtfd/readthedocs.org/blob/ae67af44c2044dd5f6168edd96494b0e7b0facd6/readthedocs/builds/models.py#L175), just the configured `language`. So readthedocs is actually using for Portuguese as spoken in Brasil ``/pt_BR/`` in the path, which looks heavy being the only path segment with an underscore and the only path segment with capitalized characters. I'd prefer to see ``/pt-br/`` here.

I can understand it can't be easily changed (sites already generated with /pt_BR/ in URLs, blogs pointing to those docs…), so there's some solutions:

1. Keep raw IETF language tags like ``pt_BR`` in URLs, capitalized and with an underscore.
2. Change to lower-cased-with-dash language tags and automatically generate 301 redirections.
3. Allow to configure the ``lang_slug`` near the ``language``, keeping lang_slug=language by default.

I think 3 is probably the best solution as it's not breaking anything and allowing to fully personalize the language slug, typically allowing "fr-fr", "fr-FR", "fr_FR", too if one really wants or needs it, typically while porting a manually generated localized documentation to readthedocs.

**Comment by ericholscher** [comment]
Yep -- I think if we did anything we should standardize it to an actual slug, with 301's. We've done this in the past a few times, and it's kind of a PITA, because we serve URL's in a few different places, but we have the infra in place to do it, since we already removed `_`'s from slugs.

**Comment by JulienPalard** [comment]
If you standardize to an actual slug, I propose a "lowercased-with-dash" version of language tags simplifying "redundent" tags like "fr-fr" to "fr" like I proposed in [PEP 545](https://www.python.org/dev/peps/pep-0545/#language-tag), leading to path segments like `/pt-br/`, `/fr/`, `/de/`, `/fr-ca/`, …

It would be great to keep a compatibilty here, so if PEP 545 notation does not works for you, please tell me so we can find an agreement?

**Comment by ericholscher** [comment]
Sounds like a good approach.

**Comment by ericholscher** [comment]
@JulienPalard Are you at Pycon?

**Comment by JulienPalard** [comment]
@ericholscher No :( But if you want to "speak" I'm always on IRC (freenode), I'm mdk, I live in UTC+2 but I always backlog if you HL/PM me. I'm also available by mail (c.f. the mail used in my commits).

**Comment by ericholscher** [comment]
@JulienPalard Mostly, we're talking here at Pycon about moving the official python docs to RTD. I'm curious if you have thoughts on that re: PEP 545 -- would that make your life easier, better, worse, etc?

**Comment by JulienPalard** [comment]
For the translations we're only maintaining a set of .po files: https://github.com/python/python-docs-fr, I'm not sure in which hierarchy RTD expects them (http://docs.readthedocs.io/en/latest/localization.html#project-with-multiple-translations is not that verbose), typically I don't know how RTD fetches different version for different languages.

Our hierarchy is: One repository per language (to manage administrative rights) and one branch per version (as always), as you can see. Also we're using the `gettext_compact=0` sphinx option.

So, tell me that everything is incompatible between our hierarchy and RTD and it may make my life worse, tell me everything's ok and it will obviously make my life easier: Not having to implement the language fetch/build in docsbuild-scripts, not having to recreate a language switcher: less code to maintain.

If everything's OK, few question remain, the first one: We expected to have the ability to release a language *without* adding it to the language switcher, so a new community of translators can have a look at their work, without starting to "advertise" (show in the language switcher) an almost untranslated version.

**Comment by ericholscher** [comment]
Great -- where is the build script that you use for https://github.com/python/python-docs-fr?

We can likely make that hierarchy work -- I'll need to look more into it. I can set up a set of examples to see how it all fits together.

**Comment by JulienPalard** [comment]
We do not use anything to build python/python-docs-fr, it on exists since like 15 minutes¹.

15 minutes ago we were hosted on [afpy/python_doc_fr](https://github.com/AFPy/python_doc_fr/) and [had a Makefile to build all versions](https://github.com/AFPy/python_doc_fr/blob/master/Makefile#L12), then we were rsyning this to https://www.afpy.org/doc/python/3.6/.

The plan [is](https://www.python.org/dev/peps/pep-0545/#patch-docsbuild-scripts-to-compile-translations)/was to use [docsbuild-scripts](https://github.com/python/docsbuild-scripts/) to build translations alongside with the existing documentations.

**Comment by ericholscher** [comment]
Awesome -- I'll take a peek and see what I can do tomorrow at the sprints.

**Comment by JulienPalard** [comment]
Awesome! Thanks!

**Comment by ericholscher** [comment]
I got these docs working with a small hack -- but the PO files in the repo seem to be invalid according to Sphinx (`WARNING: reading error: /Users/eric/checkouts/cpython/Doc/locales/fr/LC_MESSAGES/library/sys.po`). It seems the existing stuff was doing some processing, but likely I'm just not configuring Sphinx correctly?

**Comment by ericholscher** [comment]
https://github.com/ericholscher/cpython/commit/f828b70edc653eb782a6067478b6091bc881d934 shows the initial bits.

**Comment by JulienPalard** [comment]
I'm not aware of sphinx being able to work with po files. According to sphinx doc you have to compile po files to mo_files beforehand using msgfmt: http://www.sphinx-doc.org/en/stable/config.html#confval-locale_dirs.

So I typically use a Makefile to do it, like:


```
RELEASE := 3.6
PO_PATH := python-docs-fr/
CPYTHON_PATH := cpython/
MODE := autobuild-dev-html

PO_FILES := $(patsubst $(PO_PATH)/%,%,$(wildcard $(PO_PATH)/*.po $(PO_PATH)/*/*.po))
MO_FILES := $(addprefix $(CPYTHON_PATH)mo/fr/LC_MESSAGES/,$(patsubst %.po,%.mo,$(PO_FILES)))

.PHONY: all
all: $(MO_FILES)
	$(MAKE) -C $(CPYTHON_PATH)/Doc/ SPHINXOPTS='-D locale_dirs=../mo -D language=fr -D gettext_compact=0' $(MODE)

$(MO_FILES): $(CPYTHON_PATH)mo/fr/LC_MESSAGES/%.mo: $(PO_PATH)/%.po
	mkdir -p $(dir $@)
	msgfmt $< -o $@
```

You can change the CPYTHON_PATH and the PO_PATH by invokike make like `make CPYTHON_PATH=../whatever/ PO_PATH=./)` (trailing slashes mandatory on this one).

**Comment by ericholscher** [comment]
I thought you could get it to autobuild with http://www.sphinx-doc.org/en/stable/config.html#confval-gettext_auto_build

**Comment by ericholscher** [comment]
but yea -- I'm not super familiar with translation workflows to be honest.

**Comment by JulienPalard** [comment]
@ericholscher I just got the time to try your patch and it worked for me: https://dpaste.de/cEFn.

**Comment by ericholscher** [comment]
Interesting. What version of Sphinx? It was handling the translation of the front page, but all the other pages were broken. I'm guessing it's a config error perhaps.

**Comment by JulienPalard** [comment]
I'm using Sphinx 1.3.5 in this venv.

**Comment by ericholscher** [comment]
Hmm ok. I'm on 1.6.1 -- wonder if there were some changes between. It breaks on the po->mo file conversion using Sphinx's native conversion. Will try and look at it more.

**Comment by JulienPalard** [comment]
Tried again after a proper clean of my cpython clone (which is on branch 3.6, on 07a40a162389) it worked again: https://dpaste.de/w3bC

**Comment by JulienPalard** [comment]
Yup, I'm having the read_error with 1.6.1.

**Comment by JulienPalard** [comment]
Probably due to [empty Language header in po files](https://github.com/python/python-docs-fr/blob/3.6/about.po#L15), I'm fixing this to try again.

**Comment by JulienPalard** [comment]
I pushed this fix, works for me with 1.6.1 now.

**Comment by ericholscher** [comment]
Great, are the docs properly translated when you build them? I am getting the index page being translated, but not the other content (`tutorial/index.html` for example).

**Comment by ericholscher** [comment]
Example here: http://python-fr.readthedocs.io/fr/hack-in-language/

**Comment by ericholscher** [comment]
I actually have this working locally now, let me see if I can fix it on RTD.

**Comment by ericholscher** [comment]
Woot! http://python-fr.readthedocs.io/fr/hack-in-language/tutorial/index.html should be properly translated now.

**Comment by ericholscher** [comment]
Maybe the more interesting URL: http://python.readthedocs.io/fr/hack-in-language/tutorial/index.html

**Comment by ericholscher** [comment]
For some reason the titles on the index pages aren't being properly translated, but the content is.

**Comment by JulienPalard** [comment]
That's strange, the index page is correctly translated locally. Looks like only `sphinx.po` is "missing", but I still have no idea why. Other titles on other index pages seems to work fine (http://python.readthedocs.io/fr/hack-in-language/tutorial/index.html).

**Comment by JulienPalard** [comment]
@ericholscher I see warnings about my README.rst being found by sphinx-build þ As I think I should also add other things like travis config, we should probably move translations in a directory. What about fr/LC_MESSAGES/? Maybe a bit "sphinx-specific" but why not. Does it make life easier for you?

**Comment by ericholscher** [comment]
Yea, I think it's probably easiest to keep the data we actually want in a subdirectory -- we could always just delete the README when we pull it in, as well. I mostly just put things together to see how hard it would be to get it up on RTD. We can definitely clean up the scripts and improve them :)

**Comment by JulienPalard** [comment]
I'm actually more on the side of "put po at the root of the directory", but there's may be more than just a README, like travis-ci config to check pull requests and .gitlab to give the issue template... Does `{LANGUAGE_TAG}/LC_MESSAGES/`` looks a good choice to make life easier?

**Comment by humitos** [comment]
> Change to lower-cased-with-dash language tags and automatically generate 301 redirections.

I think this solution should not be super complex now we have El Proxito. I think we can create a redirect that takes the language from the URL and perform the following:

```python
language = ...  # get from the URL
new_language = language.lower().replace("_", "-")
new_url = .... # replace the language in the URL
return redirect(new_url, status=301)
```

@stsewd what do you think about this approach?

**Comment by stsewd** [comment]
yeah, that could work.
