### ISSUE TITLE
Unsupported ssh targets should disable the ssh host check

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#2925]
When pulling from unsupported sources, SSH will fail due to the host check not being accepted first. We can do a blanket disable of the host check on the server, but for security, we should probably at least be expecting to check the host key of GitHub, Bitbucket, etc. This perhaps might not be an option we can add to Git, Mercurial, etc, so perhaps this just falls back to the system level anyways.

**Comment by stsewd** [comment]
This only happens in .com (actually it doesn't happen anymore). There is an issue on .com for using an alternative method to stop the host check.
