### ISSUE TITLE
Redirect to the default version of any translation when visiting /{lang}/

### ISSUE THREAD

**Issue by mfrasca** [readthedocs/readthedocs.org#2968]
## Details

* Project URL: http://readthedocs.org/projects/ghinidesktop-docsi18n-it/
* Read the Docs username (if applicable): mariotomo

I have registered [the project](http://readthedocs.org/projects/ghinidesktop-docsi18n-it/) as Italian translation of [ghini](https://readthedocs.org/projects/ghini/). Italian is one of a couple translations I have registered for the Ghini project. Others are [French](http://ghini.readthedocs.io/fr/) and [Spanish](http://ghini.readthedocs.io/es/). These work as a charm.

## Expected Result
translated project documentation visible at short url: http://ghini.readthedocs.io/it/

## Actual Result
maze found at http://ghini.readthedocs.io/it/

*A description of what actually happened*
the translated docs are built, and I can see them at http://ghinidesktop-docsi18n-it.readthedocs.io/, but not at the shorter link, which is the one offered to the user.
![image](https://user-images.githubusercontent.com/122869/27486361-f460266c-57f5-11e7-8da9-65466d0977a6.png)

I tried twice: remove the project, create it again, same result. I have forced a build, same result. I did not yet try to create the project under a different name, I will do so shortly (without removing the one which is not working) and comment here. but I would rather follow a uniform project naming policy.

**Comment by mfrasca** [comment]
under a different name [ghini-it](http://ghini-it.readthedocs.io/it/ghini-1.0-dev/) works, but the link again does not. I find a different maze, not "page not there yet" but "permission denied".

**Comment by mfrasca** [comment]
I did not change anything and it now works. I will try with registering one more translation, and report here.

**Comment by mfrasca** [comment]
http://ghinidesktop-docsi18n-ar.readthedocs.io/ar/latest/ (gives the still totally untranslated documentation, but it does show the desired page)
http://ghini.readthedocs.io/ar/latest/ (gives Maze found, Permission Denied)

**Comment by stsewd** [comment]
Hi, are you still having this issue? All the links provided work properly (I really don't understand your last comment, sorry)

**Comment by mfrasca** [comment]
I had forgotten about this, I think it has to do with the fact I'm not using 'master': I'm working with branches 'ghini-1.0-dev' and 'ghini-1.1-dev' and 'master' does not mean much to me.

http://ghini.readthedocs.io/it/ does not work,
http://ghini.readthedocs.io/it/ghini-1.0-dev works
and I wish to use the first, shorter link, when telling people where they can find the translated docs.

ghini-1.0-dev is the default version for all projects, the one being translated as well as its translations, but only http://ghini.readthedocs.io/ correctly sends me to http://ghini.readthedocs.io/ghini-1.0-dev, for translations I have to type the complete url, or a maze is found.

**Comment by stsewd** [comment]
So the problem here is to redirect to the default version of any translation when visiting `/{lang}/`.

**Comment by mfrasca** [comment]
yes, this is a better title for the issue. I guess it wasn't clear to me either, what was going on.

**Comment by stsewd** [comment]
I changing the title to be more accurate to the real issue

**Comment by mfrasca** [comment]
@stsewd , are you sure it's clear enough?  or was the clearer option too long?
**redirect to the default version of any translation when visiting /{lang}/**

**Comment by humitos** [comment]
Supporting this is not trivial since these files are served by nginx directly and does not hit the Django instance. So, at that level, we don't know what it's the default version.

In case we want to handle this, we would need to redirect `/{lang}/` requests to Django, and it will needs to return a 302 to the full path containing the default version.

**Comment by humitos** [comment]
A lot of things have changed since this issue was opened. We are now using El Proxito, which is a proxy implemented in Python and we have access to the database at this point. If we want to, we could properly redirec `/{lang}/` to the default version of that language.
