### ISSUE TITLE
CNAME goes to wrong project and/or a 404

### ISSUE THREAD

**Issue by AlbertMietus** [readthedocs/readthedocs.org#3179]
I would like to serve my '_MESS_' project (http://mess.readthedocs.io/) from a own domain. So, I setup
 **CNAME** support as described by: http://docs.readthedocs.io/en/latest/alternate_domains.html#cname-support

However, I doesn't work.  Even after a log of variations and "debugging" (details below).

So, I assume it's a bug....

Effect & reproduce
===============
- When I surf to a _real page_ (eg http://MESS.SoftwareBeterMaken.nl/en/latest/README.html), I got a 404 (the maze page)
- And, when I surf to the top-site (http://MESS.SoftwareBeterMaken.nl), I end up at a **different project** (always: http://docs.mio-lang.org/zh_CN/latest/)! 

Firstly, I assumed I made a mistake. And tries several variations -- no effect. And even created another new project; doing everything again; even with another domain  (http://DocIdeas.mietus.nl/). **Nothing improved**. The latter link goes to the same _"Chinese page"_
 
Details
=====

DIG
----
>    MESS.SoftwareBeterMaken.nl. 2900 IN CNAME readthedocs.io.

(Also see: https://toolbox.googleapps.com/apps/dig/#ANY/MESS.SoftwareBeterMaken.nl)

Setting
--------
At RTfD:  (project=MESS) Admin | Domains
>    MESS.SoftwareBeterMaken.nl

I tried this with and without trailing dot -- no effect

Bug or Mistake?
============
As (I assume) many people use this feature, I can't imagine it;s a bug. So, when it's my mistake, please help.  Or maybe it's a real bug. Then please fix :-)

Note: As A suggestion, I would be nice to be able to retrieve "logging/debugging" info about this, So I/others can get feedback on why which page, or symlinks, or ... is (mis)used. Than I would be able to fix my mistake

Something like the views on the "BUILD/..." page would be nice
(like: https://readthedocs.org/projects/mess/builds/6158940/)

_Thanks for RTfD, ReadTheDocs.org and the help_

_--Albert_

**Comment by RichardLitt** [comment]
> As (I assume) many people use this feature, I can't imagine it;s a bug. So, when it's my mistake, please help. Or maybe it's a real bug. Then please fix :-)

If it's a mistake many people make, it's a problem if we don't have that in the documentation to help people out. Either way, we need to fix this workflow. :)

**Comment by AlbertMietus** [comment]
# WORKAROUND

Only use lowercase in de domain-field

## This kind of solves it ....

It depend op capitals in the Admin ->Domain - > ... field
When *CamelCaseWords* are used in that field, it does **NOT** work. 

* I used **MESS.SoftwareBeterMaken.nl**-- for readability. It didn't work. 
* But  a second, after I set it to **mess.softwarebetermaken.nl** it does work.

## (still, it a bug: in code or docs)
Plz doc it. Or better:  use .lowercase() before using the setting. Thanks

**Comment by ericholscher** [comment]
Sounds like a good fix! https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/projects/forms.py#L546 would be a good place to implement it 🎆

**Comment by dojutsu-user** [comment]
@ericholscher I would like to work on this issue.

**Comment by dojutsu-user** [comment]
I would like to work on this issue. Can anybody guide me as I am totally new here.

**Comment by stsewd** [comment]
@dojutsu-user this should be fixed here https://github.com/rtfd/readthedocs.org/blob/2d9ca7df405a15c3e7e278c68c3fb9f98fe13d36/readthedocs/projects/forms.py#L646 I guess, but first, you should test that this behavior persists in the current version of rtd.

**Comment by dojutsu-user** [comment]
@stsewd I registered a free domain and added the CNAME records (according to the docs) and then added the Domain in the readthedocs.org Admin Panel in CamelCase.

![screenshot from 2018-10-02 10-20-27](https://user-images.githubusercontent.com/29149191/46329777-2a482800-c62d-11e8-9595-5ae8e95fe396.png)

It is working, when I tried to go to [http://DOCS.DojutsuUserHelloWorld.Tk](http://DOCS.DojutsuUserHelloWorld.Tk) , the docs opened without any error.
I think that the error is no more.

**Comment by stsewd** [comment]
@dojutsu-user thanks for checking!

@AlbertMietus is this still a problem for you?

**Comment by AlbertMietus** [comment]
“DOCS” is not CamelCase!

Plz test with too; I think that was the part what triggered the bug (I filled). I can’t remember however the details 

Next, when all test are ok, ...
It’s a good habit to check the code-changes between the then/now versions to verify code is indeed improved (To make sure; the test results isn’t changed by something else)

If & when, add a note to the bug report to summarize and mention the “commit(s)”, and close it

This feedback is just here, as you asked for assistance; possibly it’s not needed — but better to share a good engineering practice to often, as to little...

Thanks

--albert

**Comment by stsewd** [comment]
So, I can't enter to http://docs.mio-lang.org/ either http://DOCS.DojutsuUserHelloWorld.Tk, I'll test this with a domain I own later.

**Comment by dojutsu-user** [comment]
@stsewd I have changed the domain from camel case to lowercase. And now it seems to be working with me. Please confirm it from your side also.
And the domain is registered for 12 months. So, I don't think that this error is because of the domain.

**Comment by stsewd** [comment]
It works for me too! What was the exact domain that makes it fail?

**Comment by dojutsu-user** [comment]
@stsewd exact domain was **DOCS.DojutsuUserHelloWorld.Tk**

**Comment by stsewd** [comment]
Wasn't that the same that was working yesterday? :_

**Comment by dojutsu-user** [comment]
@stsewd yes, this confusion might be from my side because CNAME records may take 2-3hrs to properly set up. And I tested it immediately. This might be the reason but I'm not sure about why it stopped working.

**Comment by dojutsu-user** [comment]
@stsewd any update on this?

**Comment by nymd** [comment]
This is still a bug @stsewd @dojutsu-user @AlbertMietus 

Brand new project (sft-protocol.readthedocs.io)

Brand new domains (tried both sftprotocol.com and sft-protocol.com)

Using the "docs" subdomain, everything gets redirected the SAME project as the OP's issue.

;; ANSWER SECTION:
docs.sft-protocol.com.	300	IN	CNAME	readthedocs.io.

curl -v http://docs.sft-protocol.com/
*   Trying 104.18.228.122...

< HTTP/1.1 302 Found
< Location: http://docs.mio-lang.org/zh_CN/latest/

I've never used CamelCase or any sort of capitals anywhere in the project settings or DNS.

**Comment by ericholscher** [comment]
You have to setup the exact CNAME you want, so `docs.sftprotocol.com (Edit) (Remove)`

**Comment by stsewd** [comment]
Sorry for the bot, this is still valid.

**Comment by eviatarbach** [comment]
I am having this same problem, with a new project and the domain in lowercase. http://www.parasweep.io keeps resolving to http://docs.mio-lang.org/zh_CN/latest/.

**Comment by davidfischer** [comment]
> I am having this same problem, with a new project and the domain in lowercase. http://www.parasweep.io keeps resolving to http://docs.mio-lang.org/zh_CN/latest/.

Starting after the next deploy, you'll just get a 404. This changed in #5143.

The reason you're getting this is that you have not correctly setup your domain. Here's our [documentation](https://docs.readthedocs.io/en/stable/custom_domains.html) on the subject.
You have correctly set the CNAME record for `www.parasweep.io` to `readthedocs.io`, however, the Domain record you added to Read the Docs just says "parasweep.io" and not "www.parasweep.io". You should be able to change it here: https://readthedocs.org/dashboard/paraweep/domains/

**Comment by eviatarbach** [comment]
Thank you so much! That fixed it.

**Comment by ericholscher** [comment]
This is now shipped :+1:
