### ISSUE TITLE
Add feature to force request to redirect to canonical domain

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#3231]
- [ ] Add project/domain option for always redirecting to the canonical URL
- [ ] Add X-READTHEDOCS-CANONICAL header handling to ensure no redirection on
  the request. This is a backup for proxied domains
- [ ] We currently allow for specifying the readthedocs project slug using the
  X-RTD-SLUG header on proxy requests. Perhaps we want to change this to
  X-READTHEDOCS-*, where we don't use "RTD" anywhere else.

**Comment by humitos** [comment]
> Add project/domain option for always redirecting to the canonical URL

Isn't this the current option that we are showing in the Domain detail page: 

  This Domain is the primary one where the documentation is served from

I suppose if the Domain has this option checked, we should automatically redirect to it.

> Add X-READTHEDOCS-CANONICAL header handling to ensure no redirection on
the request. This is a backup for proxied domains

If I understand correctly, is this the `canonical_url` that we have in the `metadata.json` file? Shouldn't this be read by `redirect` (our Flask app) and make the redirection at that point?

https://github.com/rtfd/redirect/blob/0663928b4112b28b1bc81957139f0b9e79846789/redirect/__init__.py#L65-L66

> We currently allow for specifying the readthedocs project slug using the
X-RTD-SLUG header on proxy requests. Perhaps we want to change this to
X-READTHEDOCS-*, where we don't use "RTD" anywhere else.

This is a breaking change. Does it worth to "make a deprecation plan" and duplicate the headers in the meanwhile?

**Comment by humitos** [comment]
There is a PR related to this at https://github.com/rtfd/redirect/pull/12

**Comment by agjohnson** [comment]
> Isn't this the current option that we are showing in the Domain detail page

Well, no, because that's not what the feature does currently :)

Because `canonical=True` does not currently redirect, we might need to be more careful about enabling a strict redirect like this. I'm not sure if that dictates that we need a separate option or not though, but I don't think we can assume a redirect is what the user wanted.

I'm guess this will be implemented in proxito, if anywhere. This is something for the design doc perhaps.

**Comment by humitos** [comment]
What's the point of having a `canonical=True` Domain and keep serving the docs under the non-canonical URL? I'm not sure to find a good answer to that. Although, I think this will affect people proxing to us, right?

Anyway, forcing the redirect will be a change in the feature as you said. So, I'm :+1: on adding an extra option `canonical_redirect=True` to enforce the redirect based on user desire :smile: 

Pinging @davidfischer since I know he had some opinions about this.

> I'm guess this will be implemented in proxito, if anywhere. This is something for the design doc perhaps.

Agreed.

Useful links:
* [canonical URL passed to context}(https://github.com/rtfd/readthedocs.org/blob/b67fbf7c9bae4cdf38d05bc93c251fd84352df4e/readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl#L94)
* [`link rel='canonical'` HTML injected](https://github.com/rtfd/readthedocs-sphinx-ext/blob/f1a01c51c675d36ac365162ea06814544c2aa410/readthedocs_ext/_templates/readthedocs-insert.html.tmpl#L4-L17)

> NOTE: we have `Domain.canonical(bool)` and `Project.canonical_url(str)` in our models, which sounds duplicated and potentially inconsistent

**Comment by agjohnson** [comment]
It's definitely the case that `canonical=True` was poorly named or poorly applied when we originally wrote the implementation. Ideally `canonical=True` would function the way you're describing. From our current perspective, `canonical=True` only affects how the resolver determines the domain for the project and pieces like search and auth on the commercial side -- it effecticely `primary=True`, not `canonical=True`.

I think `canonical_redirects=True` probably makes the most sense, and we can make it the new default going forward (old domains are `False`). From our perspective, we have two settings: `primary=True` for the resolver and `canonical=True` for this feature. From the user perspective, there is only one setting, `primary` and `canonical` are synonymous -- there probably isn't good UI we can apply here for this case.

I'd be -1 on making proxito do any form of content rewriting probably. I'm not sure of support by search engines, but I believe there is an HTTP spec `Link` header that would allow for `Link: rel=canonical`.

If `Link` header has the support we need, then implementing this header in proxito would maybe be my vote. Otherwise, I guess this is fine in build output still.

**Comment by davidfischer** [comment]
Generally, I favor redirecting to the canonical domain for *all* requests. Ideally, we should never serve the same documentation on two different domains. Serving the same thing in multiple places generally just yields confusion as well as being bad for SEO.

While I can understand the logic of not changing functionality on people, I can't really think of why anybody would set `canonical=True` and then not want redirection so I don't think this will be as harmful for users as feared.

**Comment by agjohnson** [comment]
We never described `canonical=True` as a redirect feature to the user, so I don't think we can make this call for them.

We can pull data up on this as well, that would be a good place to start. We probably don't have many projects with multiple domains on either instance.

**Comment by davidfischer** [comment]
> We never described canonical=True as a redirect feature to the user, so I don't think we can make this call for them.

I agree that this is true, but I can't imagine what other functionality a user would hope for with `canonical=True`. I think our infrastructure was just not setup to handle this redirection properly before and now it can.

> We can pull data up on this as well, that would be a good place to start. We probably don't have many projects with multiple domains on either instance.

I don't think multiple domains matters in this instance. The redirection can occur (should occur IMO) even on a `readthedocs.io` subdomain. For example: `requests.readthedocs.io` -> `python-requests.org`.

My biggest concern would be avoiding what Google considers ["duplicate content"](https://support.google.com/webmasters/answer/66359?hl=en). Overall, I don't think we will be flagged for it or anything, but it is a risk. Nonetheless, I continue to believe that hosting identical content on multiple domains is not correct (for users or for search engines) and should be avoided whenever possible. This is exactly what redirects are for and I can't think of anything redirects would break.

**Comment by ericholscher** [comment]
This is now shipped 🎉
