### ISSUE TITLE
Better commit, identifier and tag model

### ISSUE THREAD

**Issue by techtonik** [readthedocs/readthedocs.org#3304]
While working on #1820 I found that RTD mixes too much concepts together. To make things more decoupled, `builds.models.Version` could be less abstract:
https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/builds/models.py

In particular, I'd like to see separate `commit` field that, unlike current `identifier`, doesn't container any  branch names or RTD specific labels like STABLE and LATEST. At least there should also be `identifier_type` that explicitly documents the meaning of the current value of `identifier`.

So there are three identifier models here:
1. VCS side permanent ids - how git identifies source version - that is essentially only commit hash.
2. VCS side *alias ids* - tags, branch names that VCS understands and can use in URLs
3. RTD side *alias ids* - LATEST, STABLE that VCS doesn't understand

**Alias ids** are dynamic labels that are recalculated to commit hash at some point, so they should carry the information at which point in time who recalculated them and what was the result. VCS side *alias ids* are used to construct back links to documentation.

This way every version should contain:
- commit
- vcs_label (tag or branch, if any)
- rtd_label (STABLE or LATEST if any)

The logic to select how to construct the URL for RTD:
- rtd_label || vcs_label

The logic to select how to construct the URL for VCS:
- vcs_label || commit

**Comment by stsewd** [comment]
I think we already do this, also we have a `type` field.

> This way every version should contain:
>
>    commit
>    vcs_label (tag or branch, if any)
>    rtd_label (STABLE or LATEST if any)

- commit -> identifier
- vcs_label -> verbose_name
- rtd_label -> slug

**Comment by techtonik** [comment]
> * commit -> identifier
> * vcs_label -> verbose_name
> * rtd_label -> slug
label
Reverse mapping for these is not true:

* identifier -> commit, tag, branch, LATEST, STABLE
* verbose_name -> <any name, not vcs specific>
* slug -> <name for URL>

**Comment by humitos** [comment]
Thanks for the suggestions here. Unfortunately, we are not going to implement it anytime soon since it requires a lot of code refactor and we have other priorities in mind. So, I'm closing this issue as not planned. We can come back in the future if needed.
