### ISSUE TITLE
Branch does not appear

### ISSUE THREAD

**Issue by niden** [readthedocs/readthedocs.org#337]
Greetings,

We have created a new branch of the documents in our project "1.0.0" and it appears that it is not being picked up by RTD. All the previous branches "0.9.0", "0.8.0" etc. have appeared in the past (and are still there) but the 1.0.0 refuses to do so.

Any pointers are more than appreciated.

Github project: https://github.com/phalcon/docs
RTD: https://readthedocs.org/projects/phalcon-php-framework-documentation/

Thanks!

**Comment by iblis17** [comment]
Hi,
I also have some problem about branch: I cannot see any branch in the [admin panel](https://readthedocs.org/dashboard/couchapp/versions/).

Github project: https://github.com/couchapp/couchapp
I want to add build for branch `stable-1.0`, but I cannot figure out any way to add it.

**Comment by agjohnson** [comment]
@iblis17 please create a new issue to track this separate issue, this ticket has been closed for a long time now

**Comment by iblis17** [comment]
@agjohnson ok. Thanks for your reply!

**Comment by pevogam** [comment]
I encountered the same issue. I am not sure what is the meaning of creating a new issue and lose all the information already gathered here if it is the same issue in the end. @iblis17 Can you post here a link with your reopened issue then?

**Comment by stsewd** [comment]
@pevogam I think the this is the issue https://github.com/rtfd/readthedocs.org/issues/2163

**Comment by pevogam** [comment]
@stsewd Thanks a bunch!

**Comment by pllim** [comment]
Six years on and https://github.com/rtfd/readthedocs.org/issues/337#issuecomment-13444783 still helped. Thanks!

**Comment by stsewd** [comment]
@pllim if your project was imported ~2 months ago, it should work, if your project was imported a time ago, you can have this new feature adding new permissions to the github webhook https://docs.readthedocs.io/en/stable/webhooks.html#github

`Branch or tag creation, Branch or tag deletion `

**Comment by williamfgc** [comment]
from [comment](https://github.com/readthedocs/readthedocs.org/issues/337#issuecomment-13445779)

> so the new version doesn't get picked up until a new build
happens.

saved me hours of frustration.

**Comment by stsewd** [comment]
@williamfgc if you have a webhook setup with the proper permissions, you can get your branches updated on each push. See https://docs.readthedocs.io/en/stable/webhooks.html#webhook-creation

> Select Let me select individual events, and mark Branch or tag creation, Branch or tag deletion and Pushes events

**Comment by williamfgc** [comment]
@stsewd thanks for the follow up. rtd is working great with the new conda env feature. The related issue is that my new branch wasn't appearing (our webhooks are set up so all branches in upstream will be recognized) in the Inactive Versions menu. I was spending time trying several things, but the above line had the answer, a new Build must be triggered from rtd to sync with github for the very first time, after that it's automatic as expected...saved my day. Thanks for the great work with rtd, the conda env feature is pretty awesome.
