### ISSUE TITLE
UX changes around project tags

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#3476]
There are a few issues with project "tags". I've noticed misuse of tags since we started prompting users for these:

* This overlaps with VCS "tags", something we rely on for versions. We shouldn't continue to introduce this confusion. We could rename "tags" to something else, or could improve the UX around tags
* I'd say prompting for tags on the dashboard page is a bad pattern. We should consider a more consistent pattern for onboarding if we want to make this an onboarding step. We already have other similar onboarding steps, this should probably be included in that. The listing of "tags" is probably the wrong place to tell users to add them though, as new users don't even know what tags are at the point they are being asked.

There might be some ideas we can borrow from GitHub. Heck, any reason we're not just importing these along with the repository information on import? Obviously this doesn't keep things in sync, but at least seeds our data.

**Comment by stsewd** [comment]
GitHub uses the word `Topics`.
What about `Keywords`?

**Comment by RichardLitt** [comment]
Keywords makes the most sense to me. Topics would also work, but I think it is more semantically constrained in scope.

**Comment by humitos** [comment]
Maybe a stupid question but, is `keywords` a meanful word for people that's not technical? I mean, people that it's not a developer, for example (considering that RTD is not just software projects)

To me, not being a native English speaker, `keywords` it's associated with software and `topics` has a more general meaning/sense. It invites me to add some words about the content of my docs itself.

**Comment by RichardLitt** [comment]
Keywords can be used in nontechnical contexts too, yes. The meaning doesn't change much between contexts: salient words which are useful for identifying content.

**Comment by agjohnson** [comment]
On the new dashboard this is not a user editable field on the dashboard, it is only editable on the admin forms. I think that satisfies my needs here, I mostly felt the sidebar form was awkward.

I do agree the name could be clearer. I don't love "topics" but that does match GitHub and would probably be my choice if we ever did change it.

However, I also feel the name is a minor point in the usability difficulties of project tags. I'll close this issue as I feel this is close enough.
