### ISSUE TITLE
Refactor BuildCommand and move outside doc_builder/

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#3541]
Once #3520 got merged, we will end up with a couple of name that are inconsistent: https://github.com/rtfd/readthedocs.org/pull/3520/files/7f6c098983acb4bb3afc90e5c780af7dae9ec9d8#r163198277

In this case it should be named just `Command` and moved out `doc_builder/`. Besides a new `BuildCommand` should exist that handles all the interaction with the Build itself and saving the command in the database.

The idea is to find out more names like that one and refactor.

**Comment by dojutsu-user** [comment]
@humitos 
I request you to please update the issue description as the link provided is not working anymore.
I am interested in sending a PR for this.

**Comment by humitos** [comment]
@dojutsu-user I don't remember exactly what I wanted to do, but it seems that we have some classes in `doc_builder/environments.py` that can be refactored and move it out from that directory.

I think there are some class names that don't really make sense because they have a `Build` prefix but they don't handle a build, or similar.

I suggest you to read the PR linked and check if you find our a good refactor that can be applied to those classes. Otherwise, we could probably close the issue if you find out that it's obsolete and there are no good refactor here.

**Comment by dojutsu-user** [comment]
@humitos 
I did go through the attached PR and there are some small refactors suggested there.
I am working on it.
Will make a PR soon.

**Comment by humitos** [comment]
A similar refactor was already done in #8815, so we can close this issue.
