### ISSUE TITLE
Remove record dependency from BaseEnvironment

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#3643]
Currently, the `BaseEnvironment` class check if `record` is defined and if so, record the command into the database, https://github.com/rtfd/readthedocs.org/pull/3520/files#r168777620

This is not a good approach since `BaseEnvironment` should know nothing about recording a command.

So, I think it's a good idea to have something like `pre_run_command` and `post_run_command` methods so classes that inherit from it can override those to do whatever they need (record the command in this specific case)

**Comment by agjohnson** [comment]
Is there a specific reason why BaseEnvironment shouldn't know about command reporting? It seems like the best place to implement this logic is in a shared base

**Comment by humitos** [comment]
`BuildEnvironment` is the one that should know about recording a Build since it's the one used for building process.

> Maybe we should call it `BaseBuildEnvironment` to make it consistent with the other pieces.

`BaseEnvironment` is used not just for Build but also for VCS commands.

**Comment by stsewd** [comment]
I was trying to take this, but looks like a big refactor, and I'm thinking in another approach in #5028

**Comment by humitos** [comment]
This class was refactored and `BaseEnvironment` does not receives a `record=` argument anymore.
