### ISSUE TITLE
Refactor tasks files

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#3775]
We have a lot of lines of code in `projects/tasks.py` and maybe some of them doesn't belong there or they can be moved to `core/tasks.py`.

Tasks we can consider moving,

- [ ] fileify
- [ ] send_notifications
- [ ] email_notification
- [ ] webhook_notification
- [ ] remove_dir
- [ ] clear_artifcats
- [ ] clear_*_artifacts
- [ ] finish_inactive_builds

We want to refactor these files and take a look if there are other task files than can be refactored also.

Ref: #3762

**Comment by shubham76** [comment]
Hey! Can I take this issue?

**Comment by RichardLitt** [comment]
@shubham76 Go ahead! Make sure to link back to this issue in your PR (I normally do this in the body), especially if the PR only affects one of the subtasks and not the entire issue.

**Comment by agjohnson** [comment]
This probably needs a little more hashing out before someone can jump in.

**Comment by agjohnson** [comment]
I raised this on the underlying PR comment already.

`readthedocs.core` is not an obvious spot for code, it doesn't mean much to me and has become a dumping ground for code. I'd prefer we look into a different pattern for moving these files around:

* Break up `readthedocs.projects.tasks` into submodules: `readthedocs.projects.tasks.build` or `readthedocs.projects.tasks.sync`, etc
* Move to an application where the tasks makes more sense -- if a task operates on versions, it should be in `readthedocs.builds.tasks`

I'd prefer either over `readthedocs.core`

**Comment by shubham76** [comment]
Okay! So we shouldn't move the code to `readthedocs.core` and instead to other submodules as you are suggesting.
In that case, I think I have messed up the PR. I'll start from scratch and try making changes as you had suggested [here](https://github.com/rtfd/readthedocs.org/pull/3804#issuecomment-373557172).

**Comment by shubham76** [comment]
Hey! So how many submodules should we have to move above mentioned files into?

**Comment by Alig1493** [comment]
Is this issue still open?

**Comment by stsewd** [comment]
@Alig1493 there is an open PR  for this https://github.com/rtfd/readthedocs.org/pull/3943

**Comment by ericholscher** [comment]
I closed #3943 because it is old and had many conflicts. If anyone else wants to attempt this, I'm all for it. Please do try and keep the refactor minimal though!

**Comment by Alig1493** [comment]
@ericholscher If this requires a new PR I'd like to take a stab at it.

**Comment by stsewd** [comment]
@Alig1493 go ahead!

**Comment by Alig1493** [comment]
@stsewd Before proceeding I noticed that there are 5 failing tests in the updated upstream master, namely in rtd_tests/tests/test_backend.py(3) and rtd_tests/tests/test_celery.py(2) files. Will this be an issue moving forward?

**Comment by Alig1493** [comment]
@stsewd I keep getting errors in tests which require for me to connect to a remote repository. Is there any chance that there certain tests that will fail in local?

**Comment by Alig1493** [comment]
@dojutsu-user I see. I can't seem to figure out the issue on my end though. Keeps telling me it has failed to connect to remote repositories.

**Comment by Alig1493** [comment]
@stsewd My git version shows to be at version 2.7.4

**Comment by dojutsu-user** [comment]
@Alig1493 Can you post an screenshot or some error log??
and also, are you using tox?

**Comment by Alig1493** [comment]
@dojutsu-user sure.
![image](https://user-images.githubusercontent.com/15125420/48311525-485d5c80-e5cb-11e8-969b-c9b1106a3daa.png)

**Comment by humitos** [comment]
@Alig1493 you are not using the correct `git` version. The first line of your screenshot says that `--prune-tags` arg is not known.

**Comment by shivanshu1234** [comment]
Hello, I see this issue still exists. I'm new here and would like to take a shot at it. 

May I know why https://github.com/rtfd/readthedocs.org/pull/4888 was not merged?

**Comment by stsewd** [comment]
It got staled and with a lot of conflicts I think

**Comment by shivanshu1234** [comment]
Okay, thank you.

**Comment by Iamshankhadeep** [comment]
is this issue still open?

**Comment by dojutsu-user** [comment]
Hi @Iamshankhadeep 
Thanks for your interest in contribution.
There's already PR open for this issue #5333.
I would suggest to please look for another open issues.
Thanks.

**Comment by humitos** [comment]
Our code changed a lot since this issue was opened and we are going to remove a lot of this code in #6535 or a similar one, these days.
