### ISSUE TITLE
Hide Privacy levels on the .org

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#3781]
Currently we are still exposing privacy levels to users, but they don't work as intended. A refactor a long time ago broke "private" versions on the .org, and we don't have any real reason to support them, since all the branches are open source & public. 

We should hide the UI around privacy levels, so that users stop setting things to private and then having them break.

**Comment by stsewd** [comment]
Related https://github.com/rtfd/readthedocs.org/issues/2663

**Comment by dojutsu-user** [comment]
Is this still open?
I would like to take this issue up.

**Comment by ericholscher** [comment]
Yea, there is a good bit of work and thinking required here, so I wouldn't start on it right away. We need to account for all the projects that have set non-default privacy levels, because removing the UI would make it impossible for them to change it. We also should figure out if we want this logic in the .org at all, or if we want to move it all into the .com as extensions somehow.

**Comment by dojutsu-user** [comment]
@ericholscher 
One suggestion, we can remove the UI for the users which have default option set (i.e. PUBLIC) and for the other users, we can show a warning in the `Advanced Settings` saying something like this -
 **It is recommended to change your Privacy Level to Public.**

**Comment by stsewd** [comment]
We already hide version privacy levels, the only missing thing is https://github.com/readthedocs/readthedocs.org/issues/2663
