### ISSUE TITLE
Support mercurial subrepositories

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#3834]
With a lot of the work we're doing in git submodules lately, we realized we don't support mercurial subrepositories. We should probably do that, as there probably isn't a huge reason not to.

This might involve bringing mercurial back in as a dependency so that we can get the repo configuration/etc through a native python binding.

**Comment by humitos** [comment]
You made a mistake stale bot. Re-opening.

**Comment by humitos** [comment]
I don't think we will implement this since Mercurial is not big used in our platform. Also, we are thinking about _maybe_ deprecate mercurial at some point for the same reason. See #8840
