### ISSUE TITLE
Improve Build Performance

### ISSUE THREAD

**Issue by davidfischer** [readthedocs/readthedocs.org#3870]
## Details

* Project URL: https://readthedocs.org/projects/godot

I don't mean to single out the Godot project but this issue is easily visible with their project because it has a long build time. A local build of the [Godot Docs](https://github.com/godotengine/godot-docs) took 20 full minutes on my local CPU (core i7 2.3ghz). CPU was maxed 99%+ on a single core for almost all of the time (Yay, GIL). Memory usage was less than 200MB. All but a small percentage of the time was spent on the `writing output...` step.

Possibilities:

* Use [pypy](http://pypy.org/). In a preliminary test, using pypy cut my local build time by 50% on Godot. Memory usage was a bit higher. This would probably have to be an opt-in feature as pypy would probably break some doc builds.
* Get faster build servers
* Investigate sphinx performance improvements

**Comment by agjohnson** [comment]
I have another client that notices long Sphinx build times. I'd be curious what a profile on Sphinx looks like for either project. I'm not quite sure where it's spending time currently, though I have some ideas.

**Comment by humitos** [comment]
@davidfischer I think this issue can be closed. We are supporting `pypy3.5` now in the [config file](https://docs.readthedocs.io/en/stable/config-file/v2.html#build).

Besides, we have a bigger and faster builder servers with the new scaling groups.
