### ISSUE TITLE
No TeX files were found

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#3906]
## Details

* Project URL: http://readthedocs.org/projects/pypy/
* Build URL (if applicable): http://readthedocs.org/projects/pypy/builds/6993675/

## Expected Result

Sucessful build.

## Actual Result

The error `No TeX files were found` was reported.

Two things here:

1. As this raises a `BuildEnvironmentError` the build is marked as FAILED:

https://github.com/rtfd/readthedocs.org/blob/786edd46d55f41e2709de69d38fd738bea3bc2fd/readthedocs/doc_builder/backends/sphinx.py#L352-L354

   I think this should raise a `BuildEnvironmentWarning` since the PDF generation is not mandatory for the docs to SUCCESS the build.

2. Why this is happening?

Related #1877

> the HTML documentation is updated to the latest build today (dbe5e735e9f7)

![captura de pantalla_2018-04-04_17-06-23](https://user-images.githubusercontent.com/244656/38337357-8fcb6f98-382a-11e8-80a8-8891a8555229.png)

![captura de pantalla_2018-04-04_17-06-32](https://user-images.githubusercontent.com/244656/38337358-9244d534-382a-11e8-9b45-0ffdd1abe750.png)

**Comment by humitos** [comment]
This is not happening anymore in that project. Although, I'm not sure if it's still relevant since the PDF latex backend has changed to use `latexmk` now.

**Comment by UnixedIT** [comment]
Same error!
please check this project:

https://bit.ly/39OVE7Q

thank you.
