### ISSUE TITLE
Cant build bitbucket repo docs

### ISSUE THREAD

**Issue by jewelsjacobs** [readthedocs/readthedocs.org#393]
I have a PUBLIC bitbucket repo: git@bitbucket.org:attlabs/att_html5_uverse_poc.git. I've installed the Read the Docs service for this repo.

I added it as a project in both my local build of rtd and tried to import it on https://readthedocs.org/dashboard/import/ for kicks.

Both times I received the error:
It looks like you entered a private repo - please use the public (http:// or git://) clone url

I tried entering:
https://attlabs@bitbucket.org/attlabs/att_html5_uverse_poc.git and git@bitbucket.org:attlabs/att_html5_uverse_poc.git which are the urls bitbucket shows me.
I also tried http://attlabs@bitbucket.org/attlabs/att_html5_uverse_poc.git but no dice.

When I built this project locally at http://127.0.0.1:8000/builds/att_html5_uverse_poc/ (which you obviously won't be able to see) I got the error: 

> Build for att_html5_uverse_poc
> Built: May 13, 2013. 6:03 p.m.
> State: Finished
> Outcome: Failed
> Version: latest
> Type: html
> 
> Sphinx Standard Output
> Environment Standard Error
> 
> Failed to import project; skipping build.
> Please make sure your repo is correct and you have a conf.py

I checked and I have a conf.py in my att_html5_uverse_poc/docs folder so I'm not sure what is going on.

Just FYI I also have this repo app hosted on heroku so I have a remote heroku master branch of this repo too.  Not sure if that matters.

I have to say trying to get this working for me has been quite a challenge.  I can't find any real decent docs on bitbucket repos with Read the Docs.

Thanks for all of your help!

**Comment by huckl3b3rry87** [comment]
Is it possible to use readthedocs using a private git repository? Can I do it like you suggested above:
You can set ALLOW_PRIVATE_REPOS = True in your options to bypass that check.

If so, where do I modify this file?
