### ISSUE TITLE
allow to specify a git branch

### ISSUE THREAD

**Issue by certik** [readthedocs/readthedocs.org#4]
For testing purposes, it'd be cool to just use a "docs" branch, or some other branch of git. Otherwise I always need to push into the master, just to test some idea out, to make sure things build at readthedocs.org

**Comment by pfalcon** [comment]
> In the edit project dialog you should be able to specify a default branch.

Fast forward 5 years, there's neither "project edit dialog" nor ability to specify a branch.

**Comment by agjohnson** [comment]
@pfalcon 

![screen shot 2016-01-04 at 12 16 31 pm](https://cloud.githubusercontent.com/assets/1140183/12099394/076126d6-b2dd-11e5-8d75-a328ae26bba0.png)

**Comment by pfalcon** [comment]
@agjohnson : I see, thanks. For slow folks like me, who can't get it right away: You need to go to your project, click "Admin" button, then "Versions" in left navbar. Then you will be shown a list of tags, and most importantly, *branches* of your git repo. All branches are by default unselected. You need to click "Active" checkbox by the branches you want to build docs from, and then Submit button. After that, you will be able to see those branches in list of "versions" throughout readthedocs UI, and build from them.

**Comment by nad2000** [comment]
Using "Version" tab I can see that "latest" is mapped to a branch (git):
![screenshot from 2018-06-01 17-30-22](https://user-images.githubusercontent.com/177266/40822789-fd737666-65c1-11e8-8bc5-d88b01739028.png)
But how it could be mapped to a different branch? While I was testing I was using this specific branch. Now I need to map it to **master**. Hitting edit or going via Admin->Versions... didn't help either.

**Comment by stsewd** [comment]
@nad2000 you need to do this in the `Admin section`, `Advanced settings` -> `Default branch`

**Comment by rayluo** [comment]
Leaving a mark here to help future readers. If the [solution mentioned above](https://github.com/readthedocs/readthedocs.org/issues/4#issuecomment-168801691) by @pfalcon would NOT work for you, you should double check:

* the Integrations setting in your project inside ReadTheDocs
* and/or the webhooks in your repo's hoster, such as Github

In my case, somehow the integration has been broken for quite a while, so RTD can not pick up the new branch that I've pushed into my repo. My workaround is to delete the old integration, and create a new one.
