### ISSUE TITLE
SyncRemoteRepository (PublicTask) fail when an Exception is raised

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#4077]
`PublicTask` is used to run a Celery Task and communicate the result to the FE. When the result is an `Exception` we are having an `EncodeError` since the exception is not being able to be encoded properly by `kombu`:

    kombu.exceptions.EncodeError: Object of type 'Exception' is not JSON serializable

This error happens at https://github.com/rtfd/readthedocs.org/blob/eb6dd0b3ddf0c8dee32f0aa7c617eeaa78373e4f/readthedocs/core/utils/tasks/public.py#L83 when the `info['error']` is populated.

(I found this by debugging for a while, the original exception that I saw was at https://github.com/rtfd/readthedocs.org/blob/eb6dd0b3ddf0c8dee32f0aa7c617eeaa78373e4f/readthedocs/core/utils/tasks/retrieve.py#L28 saying that `EncodeError` is not iterable)

I'm almost sure that this start happening when we upgrade to Celery 4 and the default serializer became `json`.

To reproduce this, 

1. run `runserver` with celery (`ALWAYS_EAGER=False`)
1. raise an exception in `GithubService.sync` method
1. click on sync while importing a project

Related: #4076 
Related: https://github.com/readthedocs/readthedocs-corporate/issues/323
Reported upstream: https://github.com/celery/kombu/issues/573#issuecomment-387835445

**Comment by humitos** [comment]
This is already fixed in #4078 with _one_ solution but it's not the best: to be able to get `info` data, `status` _and_ the `exception` raised we are marking a FAILED task as SUCCESS.

**Comment by xrmx** [comment]
Got this too, any idea on where the EncodeError comes from?

**Comment by humitos** [comment]
@xrmx yes. The problem is with Celery 4 (it didn't happen with Celery 3) and it's why we try to encode the exception inside the task data. The PR linked in my previous comment fixes the problem _in one_ way. Not the best one, though.

**Comment by stsewd** [comment]
I'll take a look at this after #4656

**Comment by stsewd** [comment]
Ok, I just saw the linked issue https://github.com/celery/kombu/issues/868 and the PR https://github.com/rtfd/readthedocs.org/pull/4078
