### ISSUE TITLE
Cleanup how path are handled (dev/production)

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#4119]
There are some places where we are checking for the `DEFAULT_PRIVACY_LEVEL` to decide things that are not related to the privacy level but more related to the site/instance we are running (community/corporate site).

Example, `get_production_media_path` is using this to decide if we need to use `MEDIA_ROOT` or `PRODUCTION_MEDIA_ARTIFACTS`: https://github.com/rtfd/readthedocs.org/blob/84cefc40f00083cbc74a473ffb4ef890294159a1/readthedocs/projects/models.py#L402

Besdies, I think that `get_production_media_path` is not a good name for this method and shouldn't have the `production` word on it. Example of usage of this: https://github.com/rtfd/readthedocs.org/blob/84cefc40f00083cbc74a473ffb4ef890294159a1/readthedocs/search/utils.py#L22-L27

Why we can't use just the same method `full_json_path` without worry about where we are each time that method is called?

> There is a `get_production_media_url` also with the same problem.

Also, here https://github.com/rtfd/readthedocs.org/blob/84cefc40f00083cbc74a473ffb4ef890294159a1/readthedocs/projects/views/public.py#L185 we have harcoded `/prod_artifacts` and we should find a way to get it from a common place.

Related: https://github.com/readthedocs/readthedocs-ext/pull/128

**Comment by humitos** [comment]
This checks have changed a lot now we are using the django storage to get manage them. Although, there are still some places that we can refactor or remove completely this check. Some code will be removed in #6535 or similar.

**Comment by stsewd** [comment]
We don't have this code anymore, and we have everything in storage now.
