### ISSUE TITLE
HTML docs builds are hanging when PDF build fails

### ISSUE THREAD

**Issue by audreyfeldroy** [readthedocs/readthedocs.org#416]
As of today, the builds for the HTML version of Complexity are hanging, even though the HTML version of the Complexity docs seems to build fine locally.

See https://readthedocs.org/builds/complexity/

Note that the PDF build for Complexity is broken due to a bug in Sphinx:

```
! Package inputenc Error: Unicode char \u8:├ not set up for use with LaTeX.
```

@pydanny and I are looking into this now and seeing if we can fix Sphinx and get the PDF to build properly.

**Comment by Situphen** [comment]
It still an issue but the solution @macro1 worked for me!

**Comment by ryscet** [comment]
Unfortunately still an issue. I get the error: ! Package inputenc Error: Unicode char \u8:═ not set up for use with LaTeX.

I use macro 1 solution and recommendations from [other forums](http://docutils-users.narkive.com/03NJDYRK/unicode-box-drawing-characters-in-pdf-via-latex)  with no success:

`latex_elements = {
    # Additional stuff for the LaTeX preamble.
        'preamble': "".join((
        '\usepackage{shortvrb}',
        '\usepackage[postscript]{ucs}',
        '\usepackage{pstricks}',
        '\usepackage[utf8x]{inputenc}',

        '\DeclareUnicodeCharacter{2550}{═}'
`

I would appreciate some suggestions

**Comment by macro1** [comment]
@ryscet: To use my solution you might want to try ASCII characters as the substitution, instead of replacing it with the character that was causing issues.

**Comment by settermjd** [comment]
@macro1 thanks for the fix. Works for me in a local build as well.
