### ISSUE TITLE
Remove MkdcocsJson builder

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#4205]
Now we use mkdocs 1.7, the json command was removed here https://www.mkdocs.org/about/release-notes/#other-changes-and-additions-to-version-0170

Looks like we aren't using it since I have built some mkdocs projects with no errors (just the html build is reported anyway).

Looks like it is used in the search `readthedocs/search/utils.py` file.

Here is the unused builder

https://github.com/rtfd/readthedocs.org/blob/b693d56b23f4492a96b55a194c7030f84fc084b7/readthedocs/doc_builder/backends/mkdocs.py#L262-L266

**Comment by stsewd** [comment]
Yup, that's where it needs to be removed.

Actually, I was waiting to see if there are some efforts from the mkdocs side to bring back the json output, but I didn't find anything https://github.com/mkdocs/mkdocs/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+json

But, looks like we could have a workaroung to bring search for mkdocs https://github.com/rtfd/readthedocs.org/issues/4588#issuecomment-417318189

From my side, I think we can remove that code and worry about the future implementation later. Not sure anyway.

**Comment by dojutsu-user** [comment]
should I make a PR?

**Comment by stsewd** [comment]
I'd wait for another maintainer to confirm

**Comment by stsewd** [comment]
Unblocking this, the json builder isn't needed to support mkdocs server search https://github.com/readthedocs/readthedocs.org/pull/6937

**Comment by stsewd** [comment]
This was done in https://github.com/readthedocs/readthedocs.org/pull/6937
