### ISSUE TITLE
Better UX to comunicate warnings on the build page

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#4226]
## Details

Some users that report a problem say that the build show no errors, but there are warnings (which contains very useful information to solve the problem). The problem is that those warnings aren't very easy to see.

## Possible solutions

We can't identify in a proper way if there is a warning, the status code is `0` for success, and everything else an error. But we can parse the output and search for some keywords like `WARNING`, `warning`, etc.

- Doing this in the server side (an additional field in the db) seems like a little overkill.
- We can show this only in the client side
  - Highlight the warning keywords only
  - or show a warning symbol (or color) in the _command title_

**Comment by humitos** [comment]
Not a real fix but the `-W` or strict mode option will make these commands to fail. I'm saying that's not a real fix since the user has to activate that option.

Since we are marking the `not 0` exit codes with _read_, I suppose that we could mark any output with the `WARNING` word (or similar) with _yellow_ from the client.

**Comment by humitos** [comment]
We can think more about this issue. If we can figure it out a good "parsing logic" of command output to make reliable, I think we can use the "mark the command with _yellow_" idea. However, I think the "parsing logic" is the more important thing here.

I'm not considering this for the new build notification system I'm working on. In any case, this new system is considering having different type of notifications: error, warning, tip, etc. Once we have that parsing logic defined, we can trigger a warning notification.
