### ISSUE TITLE
Automate documentation language indexing

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#4230]
For projects that have translations, if the document is not fully translated, Google can display results for the base language untranslated strings in a translated version. We can address this with a sitemap, and we can also address this with meta tags:
https://support.google.com/webmasters/answer/189077

The implementation of this might be difficult though:

* If we can use a common context variable that is passed in and used by major themes, then it's pretty easy for us to insert some `<link>` elements with the hreflang links.
* If we can't use context data directly, we'll have to override a template and add the links in the template override (hoping that themes use this and don't override this to remove the block)

For example, a `layout.html` override would approximate this, only using context data with a list of translations:

```jinja2
{% extends "!layout.html" %}
{% block linktags %}
    <link rel="alternate" hreflang="en" href="http://docs.godotengine.org/en" />
    <link rel="alternate" hreflang="de" href="http://docs.godotengine.org/de" />
    <link rel="alternate" hreflang="es" href="http://docs.godotengine.org/es" />
    <link rel="alternate" hreflang="fr" href="http://docs.godotengine.org/fr" />
    <link rel="alternate" hreflang="ko" href="http://docs.godotengine.org/ko" />
    <link rel="alternate" hreflang="pl" href="http://docs.godotengine.org/pl" />
    <link rel="alternate" hreflang="pt-br" href="http://docs.godotengine.org/pt-br" />
    <link rel="alternate" hreflang="uk" href="http://docs.godotengine.org/uk" />
    <link rel="alternate" hreflang="zh-cn" href="http://docs.godotengine.org/zh-cn" />
    {{ super() }}
{% endblock %}
```

A template override could work for the majority of projects, and only themes that remove the standard `linktags` block would not get the automated language feature.

**Comment by humitos** [comment]
This issue is related to the generation of the sitemap: #557

**Comment by stsewd** [comment]
> We can address this with a sitemap, and we can also address this with meta tags

We already have this with sitemap. Closing
