### ISSUE TITLE
Move pseudo-notification for webhooks from project pages

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#4235]
In unifying some of the patterns for notifications, we noticed that the pseudo-notification for a disconnected webhook stands out. A couple patterns for moving this would be:

* An indicator to let users know that project is incorrectly configured
* Email notification on the problem, if it persists?
* When a webhook is not configured correctly, instead of notifications pointing to the connect services page, we should point users with a persistent notification that points to the integration page. The integration page would mention the underlying issue ("You need to connect a GitHub account") with a pointer to how to resolve the issue.

With this, the notification can be removed from the base project base template.

**Comment by humitos** [comment]
I'm considered this type of notification. It won't be attached to particular users, but to the `Project` instance instead.
