### ISSUE TITLE
Adding Test for new search prototype

### ISSUE THREAD

**Issue by safwanrahman** [readthedocs/readthedocs.org#4264]
Upon merging  #4211, there will be some code that is not tested.
There should be test for following functionality:

`search/documents.py`
- [ ] Test that objects returned from `PageDocument.get_queryset` are indexed only. 
  - `get_queryset` method is overwritten to exclude the files which does not need to be indexed. Need to add test that its working perfectly while adding, updating and deleting the `HTMLFile` object.
- [ ] Test `faceted_search` method for both `PageDocument` and `ProjectDocument`

`search/faceted_search.py`
- [ ] Test both `FileSearch` and `ProjectSearch`

`projects/models.py`
- [ ] Test `HTMLFile` proxy model returns only `.html` file objects.
- [ ] Test `json_file_path`, `processed_json` property and `get_processed_json` function

`projects/tasks.py`
- [ ] Need to have some test for `_manage_imported_files` function to check that `HTMLFile` objects are creating and deleting successfully and upon deletation, the data is removed from the index.
- [ ] Test `HTMLFile` and `ImportedFile` are created separately. (Its very much important for search index as only `HTMLFile` signal is catched to reindex the file.

`search/tests/utils.py`
- [ ] Test `get_search_query_from_project_file` is returning correct query

Need to add any other tests that are useful.

**Comment by safwanrahman** [comment]
More as following:
- [ ] adding test for `bulk_post_create`,  and `bulk_post_delete`
- [ ] Test bulk indexing work after build complete.
- [ ] Test previous file got removed from index after build complete
- [ ] Test `project.tasks._manage_imported_files` function
- [ ] Test `./manage.py reindex_elasticsearch` management command
- [ ] Test `index_html_file` and `remove_html_file` functions.
- [ ] Test all tasks in `readthedocs/search/tasks.py`

**Comment by ericholscher** [comment]
We have lots of tests for search now 👍
