### ISSUE TITLE
Move `python_interpreter` out of the config object.

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#4343]
The config object has a `python_interpreter` property, which just concatenates a string, this can be moved to a function.

Ref to https://github.com/rtfd/readthedocs.org/pull/4298#discussion_r200779437

**Comment by dojutsu-user** [comment]
@stsewd 
Is this still open? I would like to take this issue up.
If yes, what according to you can be the name of the function?

**Comment by stsewd** [comment]
Yes, it's still open, and actually I was waiting to finish the changes related to all the config file before going for this one.

**Comment by dojutsu-user** [comment]
okay, that means this issue needs to wait a little, right?

**Comment by stsewd** [comment]
Yeah, I mean we could start now, but it would cause some conflicts on some big PRs, anyway, not sure how deep would be this change, it may be very simple, but just in case. I'll let you know when we are safe to fix this

**Comment by rshrc** [comment]
![screenshot from 2019-03-01 19-59-05](https://user-images.githubusercontent.com/28453217/53645698-77bdd500-3c5f-11e9-8c75-eccb13301e48.png)

So this is already done?

**Comment by aditya-369** [comment]
Hi I am Aditya. Is this still on to do or someone else is working?

**Comment by dojutsu-user** [comment]
@rshrc @aditya-369 
This issue is still valid.

**Comment by agarwalrounak** [comment]
Hi @aditya-369, I am working on this issue. I am so sorry that I forgot to comment here the same.

**Comment by aditya-369** [comment]
@agarwalrounak cool no problem.

**Comment by stsewd** [comment]
I'm closing this, there were a lot of changes since this issue. python_interpreter is fine just there.
