### ISSUE TITLE
Add web/build specific settings files

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#4391]
Current dev environments don't account for the same splits between web and build configuration, such as the lack of database access on build machines. This should probably be modeled in our settings somehow, so it can be used by contrib/supervisor.conf etc to spin up multiple queues.

**Comment by humitos** [comment]
I'm closing this since I think we already achieved this by using docker compose: https://docs.readthedocs.io/en/stable/development/standards.html
