### ISSUE TITLE
Document YAML python.use_system_site_packages option

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#4418]
A user raised (https://github.com/rtfd/readthedocs.org/issues/4362#issuecomment-404766625) that it was hard to find this option

```yaml
python:
   use_system_site_packages: true
```

I checked the docs and I didn't find anything about this: https://docs.readthedocs.io/en/latest/yaml-config.html

We need to extend our docs to mention this in the YAML config page.

**Comment by stsewd** [comment]
ha, I thought the user check the option from the web interface. Also, I was documenting this as a new option for the v2
