### ISSUE TITLE
Search results are different when logged in

### ISSUE THREAD

**Issue by davidism** [readthedocs/readthedocs.org#4452]
### Details

* Read the Docs project URL: https://readthedocs.org/projects/flask/
* Build URL (if applicable): https://readthedocs.org/projects/flask/builds/7564797/
* Read the Docs username (if applicable): davidism

### Expected Result

Searching using the Sphinx-generated search page should return the same results whether I am logged in to RTD or not.

### Actual Result

When I am logged in to RTD, search returns different results that are missing API links, context, and highlighting. If I do the same search in a private windows, I get the expected results that match our current hosted docs. @davidfischer got the correct results even though he was logged in, the difference is that I'm an owner of the project.

* RTD search when I'm logged in:
    * https://flask.readthedocs.io/en/rtd/search/?q=render_template
    * ![rtd logged in search](https://user-images.githubusercontent.com/1242887/43422464-98a4915a-93fe-11e8-8659-92eed5610bac.png)
* Results when logged out, or on current docs site:
    * http://flask.pocoo.org/docs/1.0/search/?q=render_template
    * ![logged out search](https://user-images.githubusercontent.com/1242887/43422507-c29fe234-93fe-11e8-9a45-b3c4ea87a27b.png)

**Comment by davidfischer** [comment]
This definitely looks like an API bug. It seems like there is a [search API](https://readthedocs.org/api/v2/docsearch/?q=render_template&project=flask&version=rtd&language=en) that 404s when a user is logged out.

**Comment by davidfischer** [comment]
This API 404s when the version is not public. I'm still investigating this to see exactly what the benefits and tradeoffs are.

**Comment by safwanrahman** [comment]
I do not think its a bug. If the project is not public, we do not show to them to public user.

**Comment by davidism** [comment]
Not sure what you mean. I accessed the docs when logged out, so they must have been accessible to the public user. And I got different, correct results doing that than what was served when I was logged in.

**Comment by davidism** [comment]
How is getting different, incorrect results when logged in not a bug? Why is the Sphinx-generated search calling out to the RTD API and changing the results when logged in. I don't want that, I want search results to match what we currently get with Sphinx.

**Comment by safwanrahman** [comment]
With sphinix, its not possible to have many search features. That can be a different design issue.
This can be discussed if we can open up the search regardless of permission.

**Comment by safwanrahman** [comment]
I strongly hope our ongoing search upgrade will have more accurate result than current one.

**Comment by davidfischer** [comment]
I think a combination of proceeding on the search upgrade and an opt-out flag for custom search seems like a good path forward.

**Comment by ericholscher** [comment]
This is generally a bug with privacy levels, which shouldn't effect projects once they are live and public.

The goal here is to provide better search than Sphinx can with it's basic JS backed search indexes. Sphinx search isn't full-text, and doesn't provide results for a large number of words in the normal documentation text. Our goal is to build something better built on top of elastic search.

The specific issue that would address this is https://github.com/rtfd/readthedocs.org/issues/4289 -- currently we are just doing full-text indexing, without taking into account the code-level objects. Indexing the code objects will make this work much better, and the goal is to have it done in the next couple weeks as part of our Search Improvement GSOC, which will also offer many other search improvements.

**Comment by ericholscher** [comment]
I tried to test flask against our revamped search, but ended up with an issue building the docs with the theme:

```
Traceback (most recent call last):
  File "/Users/eric/projects/readthedocs.org/user_builds/flask/envs/rtd/lib/python3.5/site-packages/sphinx/builders/html.py", line 1030, in handle_page
    output = self.templates.render(templatename, ctx)
  File "/Users/eric/projects/readthedocs.org/user_builds/flask/envs/rtd/lib/python3.5/site-packages/readthedocs_ext/readthedocs.py", line 135, in rtd_render
    content = old_render(template, render_context)
  File "/Users/eric/projects/readthedocs.org/user_builds/flask/envs/rtd/lib/python3.5/site-packages/sphinx/jinja2glue.py", line 196, in render
    return self.environment.get_template(template).render(context)
  File "/Users/eric/projects/readthedocs.org/user_builds/flask/envs/rtd/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/eric/projects/readthedocs.org/user_builds/flask/envs/rtd/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/eric/projects/readthedocs.org/user_builds/flask/envs/rtd/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/eric/projects/readthedocs.org/user_builds/flask/envs/rtd/lib/python3.5/site-packages/sphinx/themes/basic/page.html", line 10, in top-level template code
    {%- extends "layout.html" %}
  File "/Users/eric/projects/readthedocs.org/user_builds/flask/envs/rtd/lib/python3.5/site-packages/pallets_sphinx_themes/pocoo/layout.html", line 16, in top-level template code
    {% set version_warning = current_version.banner() if current_version %}
  File "/Users/eric/projects/readthedocs.org/user_builds/flask/envs/rtd/lib/python3.5/site-packages/jinja2/sandbox.py", line 427, in call
    return __context.call(__obj, *args, **kwargs)
  File "/Users/eric/projects/readthedocs.org/user_builds/flask/envs/rtd/lib/python3.5/site-packages/pallets_sphinx_themes/versions.py", line 141, in banner
    ).format(latest=latest.name, href=latest.href(context))
AttributeError: 'NoneType' object has no attribute 'name'
```

Seems related to the removal of `versions` from the flask `conf.py` and the theme still wanting it.

**Comment by ericholscher** [comment]
I've got results for this in the new branch, and we're working to make sure the proper API reference gets weighted properly.

**Comment by davidism** [comment]
When I said "API result", I meant the link to specific API methods, not the literal "API" link, although that does appear to be weighted differently too. The header and api links have a `#id` hash that takes you to the specific location on the page. None of the results in the RTD search version have these hashes, whereas the Sphinx search version has these at the top in addition to the 18 results. The ability to link to specific sections of docs is one feature Sphinx has over Google and other searches, so I don't want to lose that.

**Comment by davidism** [comment]
Seems to still be an issue.

**Comment by davidism** [comment]
Looks like the flag added by #4570 can't be overridden in `<head>` because the RTD extension always injects its content at the end of `<head>` irrespective of what the theme templates do. I want to add [the following](https://github.com/pallets/pallets-sphinx-themes/blob/42e19a53a6396833a2735b589116ed00eb83fd6d/src/pallets_sphinx_themes/themes/pocoo/layout.html#L13-L22) to `<head>` to disable new search until it returns the same API results as old search:

```html+jinja
  {%- if READTHEDOCS and not readthedocs_docsearch %}
    <script>
      if (typeof READTHEDOCS_DATA !== 'undefined') {
        if (!READTHEDOCS_DATA.features) {
          READTHEDOCS_DATA.features = {};
        }
        READTHEDOCS_DATA.features.docsearch_disabled = true;
      }
    </script>
  {%- endif %}
```

However, RTD's JS, which is [injected after the code above](https://github.com/rtfd/readthedocs-sphinx-ext/blob/master/readthedocs_ext/readthedocs.py#L127-L131), doesn't check if `READTHEDOCS_DATA` is already defined, and just overwrites it, so the flag gets wiped away.

Luckily, the `end_body` variable in the injection code is a misnomer, because it actually represents the end of `<head>`, not `<body>`, so I can put my override script in the `{% block footer %}` block. However, it would be nice to be able to control where RTD injects code.

This is also somewhat related to #5187, because the incorrect `canonical` tag is injected with the same code.

**Comment by davidism** [comment]
Fix for search disable flag in Pallets-Sphinx-Themes: https://github.com/pallets/pallets-sphinx-themes/pull/20

**Comment by davidfischer** [comment]
> However, it would be nice to be able to control where RTD injects code.

Ya, this isn't ideal. We try to inject late for performance reasons but that isn't ideal. I think the longer term solution here is to have a better way to turn off docsearch, the flyout menu and other features (probably in the YAML file).

**Comment by dojutsu-user** [comment]
@davidism 
I think this is fixed now.
You can see the search results for `flask` project here: https://readthedocs.org/projects/flask/search/?q=render_template&type=file&project=flask&version=master

**Comment by davidism** [comment]
I'm referring to the ones within Sphinx, not from the readthedocs project page.

**Comment by dojutsu-user** [comment]
@davidism 
The search results shown on the readthedocs project will be the same with Sphinx.
I have built a demo project for `flask` which uses Read the Docs's search.
https://flask-dojutsu-user.readthedocs.io/en/latest/search.html?q=render_template_string

**Comment by stsewd** [comment]
We dropped the privacy levels from .org, and we don't use that to filter results anymore. We are also indexing more content for search now (#7063). The last PR should be deployed next week.
