### ISSUE TITLE
Cancelling a Gold subscription ends benefits immediately

### ISSUE THREAD

**Issue by UniversalSuperBox** [readthedocs/readthedocs.org#4504]
## Details

* Read the Docs username (if applicable): UniversalSuperBox

## Expected Result

Upon canceling a Read the Docs Gold subscription, benefits are retained until the renewal would be charged.

## Actual Result

Upon canceling a Read the Docs Gold subscription, benefits end for all adopted projects immediately, regardless of the next renewal date.

I think I'm telling a bit of a story between this and #4503. My plan was to unsubscribe now to cancel both subscriptions and then subscribe again on my next renewal date. I guess the software showed me what for. :)

**Comment by agjohnson** [comment]
I think we should probably switch the subscription handling on our side to either prorate and refund (which i thought was the application already, maybe it is), or to cancel the gold subscription at the end of the billing period.

**Comment by dojutsu-user** [comment]
What needs to be done here?
I am interested in sending a PR for this.

**Comment by humitos** [comment]
We are handling subsciptions via the Stripe Customer Portal now and we have it configured as "Cancel at end of billing period".
