### ISSUE TITLE
Validate user input URLs on redirect form

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#4555]
There are cases where allowing the user to input a `To URL` without a leading slash produce weird redirects. See https://github.com/rtfd/readthedocs.org/pull/4501#issuecomment-414677186

Besides the case described in that comment, there are other that needs to be validated. For example when we redirect to external sites, this should allow a URL that starts with `http` for example.

I pushed a commit for one of these cases at https://github.com/rtfd/readthedocs.org/pull/4501/commits/f6fed2d92cd1a35ba65bf31f068e76670158cc2a but I also realize that we are using jQuery to dynamically change the inputs of the form. This is a problem when the form returned a validation error since it starts with the default state (no inputs at all) and a red error message which could confuse even more our users.

**Comment by stsewd** [comment]
Related to https://github.com/rtfd/readthedocs.org/issues/4023

**Comment by stsewd** [comment]
Should we allow URLs without `/` at the beginning? I mean, for no-external urls.
