### ISSUE TITLE
Apply failing projects for more resources

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#4573]
We have been experimenting with issues regarding CPU time and RAM memory when constructing documentation. Because of this reason, we have been increasing CPU time on projects that need more to build properly and we have thoughts several ideas on how to manage this resources in a smart way at #4403 

The process of increasing the resources can't be automatic since any misconfigured  (or vandalism) project will be given a lot of resources and will make our servers to crash.

Now that we have a specific celery queue for this kind of projects (#4553) we want to define a process for users to apply to that queue and be able to build their documentation without RAM issues.

> NOTE: the downside for the projects that pick this queue is that they will need to wait a little more for the worker to pick their build. In the end, the build will take a little more time.

Things we want to consider:

- autodetect that a project has been failing for many days
- check the project is not SPAM, vandalism or similar
- notify the project's owner informing the ability to apply for more resources
- suggest the project's owner our guide for these cases: https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html
- if none of those proposed "solutions" apply to the project, we should route their builds to this custom queue

We may want to include a section in that documentation page talking about this process, like: "If you already tried all of the steps from this guide and you are still experiencing issues, please open an issue on GitHub explaining this and asking for more resources"

Ref: https://github.com/rtfd/readthedocs-ops/pull/395#issuecomment-415458429

**Comment by ericholscher** [comment]
This is now being done automatically I believe 👍 https://blog.readthedocs.com/better-conda-support/
