### ISSUE TITLE
Support HTTPS redirect

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#4641]
This is a placeholder issue, we've had a few requests to enable HTTPS always on, and hey why not HSTS as well, when HTTPS is checked on the project domain admin dashboard page.

Edit: for HSTS, see https://github.com/readthedocs/readthedocs.org/issues/4135 instead of this issue.

**Comment by davidfischer** [comment]
I think we could turn on HSTS on readthedocs.org and readthedocs.io without issues.

I'm not sure we should do this for custom domains at all. I'm not strictly opposed to it, but I'm not sure we should do it, either. Turning on HSTS with a long max-age (a short max-age isn't useful) is a one-way street. You can't really go back. Once somebody's browser has received a response with HSTS for docs.example.com, that browser will never request that site over plain HTTP again. Clearing the HSTS settings for a browser is non-trivial.

**Comment by agjohnson** [comment]
Yup, we've certainly hit this before. Let's focus on https first, we can come back to HSTS.

**Comment by invinciblycool** [comment]
@agjohnson Would like to take this up. Any pointers as to where to start?

**Comment by stsewd** [comment]
@invinciblycool I think this can be solved only for the core team, as they have access to the servers

**Comment by humitos** [comment]
What's the status of this issue? It seems the only missing thing is enabling HSTS.

In another PR, @davidfischer implemented `PUBLIC_DOMAIN_USES_HTTPS = True` and `https` on custom domains, so we are maybe ready for HSTS?

**Comment by davidfischer** [comment]
> In another PR, @davidfischer implemented `PUBLIC_DOMAIN_USES_HTTPS = True` and `https` on custom domains, so we are maybe ready for HSTS?

I think we may never do HSTS for custom domains. HSTS for readthedocs.io can roll out anytime. For .org, it is nearly ready (see the private ops issue https://github.com/rtfd/readthedocs-ops/issues/294)

The harder one is redirecting custom domain traffic HTTP -> HTTPS. To do this, we need to know that the domain is active and the certificate is deployed. Many custom domains are not setup correctly and don't have a certificate. Redirecting those would be bad.

I see two ways to do HTTP -> HTTPS for custom domains:

- Write a file (`.https` or something like it) and nginx can redirect if it sees that file
- Write a database entry when the certificate is setup correctly (or just repurpose the https flag). Then we would need to change our logic such custom domains always hit django rather than just hitting nginx. We might be able to *only* hit django when the domain is requested over HTTP only and HTTPS doesn't hit django.

Do you see any other way?

**Comment by JLLeitschuh** [comment]
This should be considered a security vulnerability in RTFD.

Developers utilizing RTFD sometimes link to their releases which could be maliciously MITM to link to compromised artifacts.

Additionally, there are vulnerabilities that can be executed by abusing the Copy-Paste functionality in browsers to hide unexpected payloads, for example when copying shell commands.

Here's an example:
https://thejh.net/misc/website-terminal-copy-paste

**Comment by davidfischer** [comment]
@JLLeitschuh There's a couple things going on here:

> This should be considered a security vulnerability in RTFD.

I'm all for running the entire site over HTTPS and I do believe that would increase security and privacy. However, I would not call running a static website over HTTP a security vulnerability.

> Developers utilizing RTFD sometimes link to their releases which could be maliciously MITM to link to compromised artifacts.

Can you go into a little more details here?

> Additionally, there are vulnerabilities that can be executed by abusing the Copy-Paste functionality in browsers to hide unexpected payloads, for example when copying shell commands.

What does this have to do with an HTTPS redirect?

**Comment by humitos** [comment]
> HSTS for readthedocs.io can roll out anytime. For .org, it is nearly ready (see the private ops issue [rtfd/readthedocs-ops#294](https://github.com/rtfd/readthedocs-ops/issues/294))

That private issue is closed and it seems that it's already active.

> I see two ways to do HTTP -> HTTPS for custom domains:

I think the solution at nginx level is better because of performance, but I'd probably like to have the data on the db also as a "trustable source".

**Comment by davidfischer** [comment]
> That private issue is closed and it seems that it's already active.

HSTS is not active. We just had a few remnants of the dashboard that were served over plain HTTP and if we enable HSTS none of the dashboard can be served over HTTP.

**Comment by AustinShalit** [comment]
Hi folks,

Just looking to see if this issue made it onto the roadmap for an upcoming release.

Thank you!

**Comment by davidfischer** [comment]
@AustinShalit, this issue sort of has a few things going on with it. Specifically are you asking about HTTP -> HTTPS redirects for custom domains?

**Comment by AustinShalit** [comment]
Sorry about not being clear.  Yes, I am talking about HTTP -> HTTPS redirects for custom domains.

**Comment by AustinShalit** [comment]
@davidfischer It has been a week. I just wanted to make sure I didn't get lost in the notification noise.

**Comment by davidfischer** [comment]
Sorry I missed this. For custom domains, this is a somewhat complicated feature and will require an architectural change on our side. Currently serving docs on a custom domain only serves static files. However, this change necessitates making sure that the cert for the domain is successfully deployed before doing the redirect. We have hundreds of custom domains that "work" but are not configured such that we can issue a certificate for them so we can't just do a redirect for all of them without breaking lots of docs.

This is on the roadmap and should be completed this year, but it is not likely to be in a release in the next week or two.

**Comment by mrocklin** [comment]
For others, we ended up working around this by adding a JavaScript redirect from http -> https in our sphinx theme.  It's not 100% perfect, but pragmatically it has been working out great.

https://github.com/dask/dask-sphinx-theme/blob/master/dask_sphinx_theme/static/js/custom.js

https://github.com/dask/dask-sphinx-theme/blob/8e25fe28390b28df7ab1c3f0e0c647f834c8a844/dask_sphinx_theme/layout.html#L6

**Comment by JLLeitschuh** [comment]
@mrocklin This still leaves you vulnerable to a downgrade attack where a potential attacker can strip our your custom JS logic and leave them in a downgraded state. Unfortunately, I'd argue that your solution gives a false sense of security when really, none is offered there.

**Comment by Fiahblade** [comment]
Any new updates on this?

**Comment by Daltz333** [comment]
Just an issue bump, since it was talked about being done (now last year).

**Comment by davidfischer** [comment]
To update here, #6905 is scheduled for release next week and will solve this issue. In order to redirect, you need to make sure that the HTTPS flag is set on your custom domain.

![Screen Shot 2020-04-22 at 3 29 16 PM](https://user-images.githubusercontent.com/185043/80040108-32d1af00-84ae-11ea-8d06-6eae899e7d4f.png)

**Comment by AustinShalit** [comment]
Just out of curiosity, what kind of redirect was implemented?

**Comment by mrocklin** [comment]
Woo!  Thanks Readthedocs maintainers!

**Comment by ericholscher** [comment]
> Just out of curiosity, what kind of redirect was implemented?

@AustinShalit We currently have it as a 302 to be safe. Once we're confident in the code, we'll likely switch it to a 301.

**Comment by ryanpitts** [comment]
Yesssss thank you for this!
