### ISSUE TITLE
Improve the Build Process Documentation

### ISSUE THREAD

**Issue by davidfischer** [readthedocs/readthedocs.org#4679]
While working on #4676, I linked from the getting started guides and import guides to the [Build Process docs](https://docs.readthedocs.io/en/latest/builds.html). These docs could use improvement and simplifications

Here's some ideas:

* Detail common errors (out of memory, too much time) and what to do about it. We discuss these issues but we should use the *exact verbiage* in the error messages in the build output so people can search for them.
* Do we really need a "Writing your own builder" section here? Maybe that should be in the developer docs. Ditto for "Builder responsibility".
* Have details on configuring the right version of Python, right version of MkDocs/Sphinx, and other Yaml config options.
* Do we really need links to `tasks.py` and `doc_builders` at the top? These should probably be much further down if anywhere.
* The "You can see the current Docker build images..." paragraph is out of place. It should probably be under "The build environment".

**Comment by humitos** [comment]
This issue is still valid and seems to have good ideas to re-work on the docs.

**Comment by humitos** [comment]
Most of this page was re-written from when this issue was opened. We have troubleshooting sections in other places and examples about how to use the config file, `build.jobs` and more. I'm closing it.
