### ISSUE TITLE
Adopting a projected as gold user fails

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#4711]
### How to reproduce it

1. sign up as Gold member
1. go to https://readthedocs.org/accounts/gold/subscription/
1. select the project that you want to adopt

### Expected Result

Adopts the project.

###  Actual Result

Fails with a 500.

https://sentry.io/read-the-docs/readthedocs-org/issues/587668658/

### The problem

This line

https://github.com/rtfd/readthedocs.org/blob/44e02def230b937e4eca396864de9fc81f4ef33f/readthedocs/gold/views.py#L109

cause the problem since we are receiving a "project name" and using it as "project slug".

**Comment by dojutsu-user** [comment]
@humitos I would like to work on this issue.

**Comment by stsewd** [comment]
@dojutsu-user go ahead!
