### ISSUE TITLE
Suggests a v2 config file from the current options to help transition from v1 or web

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#4746]
We don't have many settings on the conf file, but it will be a cool feature to have, and also it will help to migrate to v2.

It may depend on https://github.com/rtfd/readthedocs.org/issues/4638

Ref https://github.com/rtfd/readthedocs.org/pull/4732#discussion_r224063394

**Comment by stsewd** [comment]
We could warn in each build to a link with the new config or docs as suggested in https://github.com/rtfd/readthedocs.org/pull/5338#pullrequestreview-206764047

**Comment by humitos** [comment]
In #5519 we added a message to communicate with users about the usage of a `.readthedocs.yml` config in the build output.

I think a cool idea would be to add a link to create this file with the specific content on their own repository. I found that adding `?filename=.readthedocs.yml` to the link that creates the file into the GitHub repository we can name it properly. Although, I didn't find how to populate the content of it.

Example: https://github.com/rtfd/readthedocs.org/new/master?filename=.readthedocs.yml

Reference: https://github.blog/2012-12-05-creating-files-on-github/

**Comment by saadmk11** [comment]
@humitos we can do this by just adding `&value=` after filename. something like:
https://github.com/rtfd/readthedocs.org/new/master?filename=.readthedocs.yml&value=version%3A%202%0Aformats%3A%20all%0Asphinx%3A%0A%20%20configuration%3A%20docs%2Fconf.py%0Apython%3A%0A%20%20%20install%3A%0A%20%20%20%20%20%20-%20requirements%3A%20requirements%2Flocal-docs-build.txt

**Comment by humitos** [comment]
That's exactly what I was looking for!

I think this is a really good usage for this,

* we can generate the proper content depending on the user's settings
* we are not being rude like by just performing a commit
* we let the user to customize our content suggestion
* immediately after the user makes the commit, we will trigger a new build with these new settings

I would add this link next to the message that promotes the usage of this file with so the user can create it by themselves, @davidfischer what do you think?

We can use "this technique" to suggest

1. the content of the file to migrate from v1 to v2
1. content of a new setting file for v2

**Comment by humitos** [comment]
We already deprecated v1 of the config file and we will remove it on October. I'm closing this issue because it's not valid anymore.
