### ISSUE TITLE
python 3.7 compatibility problem

### ISSUE THREAD

**Issue by Seburath** [readthedocs/readthedocs.org#4756]
## Details
This is the Fisrt Issue I publish, sorry If It have mistakes

Im trying to run my the readthedocs site on my machine, but I get an error.
On:
```
python manage.py migrate
```

## Expected Result

Server running...

## Actual Result

```
SyntaxError: Generator expression must be parenthesized
```

**Comment by Seburath** [comment]
@stsewd make me understand that this is not urgent, so I will be working on this :)

**Comment by stsewd** [comment]
Just to be clear, this error only happens when running rtd with python 3.7, it works fine with <=3.6.

**Comment by aanm** [comment]
I'm hitting the same issue.

```
  File "/home/aanm/rtd/lib/python3.7/site-packages/django/contrib/admin/widgets.py", line 152
    '%s=%s' % (k, v) for k, v in params.items(),
    ^
SyntaxError: Generator expression must be parenthesized
```

**Comment by dojutsu-user** [comment]
@aanm 
The reason for this error is that Django 1.11 is not compatible Python3.7 and probably there are no plans to make Django 1.11 compatible with latest version of python. (see the discussion [here](https://github.com/django/django/commit/931c60c#commitcomment-30423485))
Please stick to Python<=3.6

**Comment by stsewd** [comment]
Python3.7 support was added to django 1.11.17  (released the past december) https://docs.djangoproject.com/en/2.1/releases/1.11.17/. I'll update the version soon.

**Comment by davidfischer** [comment]
I believe Celery is also not yet compatible with 3.7.

**Comment by stsewd** [comment]
Yeah, https://github.com/celery/celery/issues/4913#issuecomment-412950201, and we are blocked in the celery update https://github.com/rtfd/readthedocs.org/issues/4643

**Comment by humitos** [comment]
I believe this is not an issue anymore since we upgraded celery finally. On the other hand, we are now mentioning that 3.6 is the Python version to use: https://docs.readthedocs.io/en/stable/development/install.html#requirements

I'm closing it for now since we don't plan to officially support > 3.6 for now.

**Comment by sivaraam** [comment]
> I believe this is not an issue anymore since we upgraded celery finally. On the other hand, we are now mentioning that 3.6 is the Python version to use: [docs.readthedocs.io/en/stable/development/install.html#requirements](https://docs.readthedocs.io/en/stable/development/install.html#requirements)
>

While that was nice, it's sad that the documentation didn't help me realize quickly that RTF _does not_ run with Python 3.7  (which to be honest, is very strange given that [3.7 is needed for building the docs locally](https://github.com/readthedocs/readthedocs.org/issues/5335#issuecomment-466135137)!). I had to search through a related issues to find this [weirdness](https://github.com/readthedocs/readthedocs.org/issues/5335#issuecomment-466379832). The fact that the hyperlink for the "Python 3.6" text in the [documentation](https://docs.readthedocs.io/en/stable/development/install.html#requirements) just links to the Python website homepage didn't help me either.

Given that distributions have started shipping Python version > 3.6 by default (Python 3.8.2 in Ubuntu 20.04 at the time of writing), it would be great if the documentation is updated to mention that RTD doesn't support Python version > 3.6 yet for running as a least measure. Thanks.
