### ISSUE TITLE
Webhook fails when project has multiple integrations

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#4818]
If the project has configured multiple integrations for the same provider, this line fails

https://github.com/rtfd/readthedocs.org/blob/08a97bd5a316c0a6f18684e81b23e97e862b599c/readthedocs/integrations/models.py#L218

That line is called with `args=[]` and `kwargs={'integration_type': 'github_webhook', 'project': Project}`, so if there are more than one integration for `github_webhook` for that project, it raises `MultipleObjectsReturned`.

Sentry: https://sentry.io/read-the-docs/readthedocs-org/issues/271730166/

**Comment by dojutsu-user** [comment]
@humitos Hey, can i take this issue up?
and also, it is not clear to me as to what needs to be done on this?

**Comment by humitos** [comment]
If you import a project and then setup from the Admin -> Integrations two or more integrations for the same service it fails when running that task linked in my previous comment.

**Comment by dojutsu-user** [comment]
okay, i was able to reproduce the error in terminal with `python manage.py shell`
I think we can try something like this
```python3
original = super(IntegrationQuerySet, self).filter(*args, **kwargs).first()
```
I find that every item in the queryset `original = super(IntegrationQuerySet, self).filter(*args, **kwargs)` corresponds to same value of `cls_replace`which is present in the method `_get_subclass_replacement`

For checking, i tried something like this
```python3
def _get_subclass_replacement(self, original):
    for x in original:
            cls_replace = self._get_subclass(x.integration_type)
            print(id(cls_replace))

def get(self, *args, **kwargs):
        original = super(IntegrationQuerySet, self).filter(*args, **kwargs).first()
        return self._get_subclass_replacement(original)
```
and in the shell opened by `python manage.py shell`, 
```python3
>>> from readthedocs.integrations.models import Integration
>>> from readthedocs.projects.models import Project
>>> pikachu_demo = Project.objects.order_by('-modified_date').first()
>>> Integration.objects.get(project=pikachu_demo)
52636152
52636152
```

The mentioned `cls_replace` variable is present here
https://github.com/rtfd/readthedocs.org/blob/9b2b17c0fc603267b4b20f5923862c2db82602da/readthedocs/integrations/models.py#L201-L215

**Comment by stsewd** [comment]
Related to https://github.com/rtfd/readthedocs.org/issues/4932, and we should find a way of deleting the duplicate ones.

**Comment by agjohnson** [comment]
On an incoming webhook, we have a unique identifier for a specific webhook integration. So this view might need to be adjusted, but where else are we calling this method from? It seems at this point we shouldn't have to guess which integration is being used, they all have unique identifiers.

**Comment by saadmk11** [comment]
Currently we are using Integration `pk` to get the integration for the incoming webhook.
https://github.com/readthedocs/readthedocs.org/blob/34d1a1571b4fe6ad81876234f432b2cce9eb67f8/readthedocs/api/v2/views/integrations.py#L727-L731

So, There should not be any `MultipleObjectsReturned` error.

@humitos Can you please tell me when this error occurs?  In the incoming webhook or somewhere else?
e.g: I have tried replicating it for incoming webhook and it seems to work fine.

**Comment by saadmk11** [comment]
Another place we use `Integration.objects.get` is `setup_webhook`.
In this PR https://github.com/readthedocs/readthedocs.org/pull/6124 I have made it so that we always pass a integration to `setup_webhook` method.
the only time the integration is not passed to it is when we import the project.

**Comment by humitos** [comment]
> @humitos Can you please tell me when this error occurs? In the incoming webhook or somewhere else?

All that I know about this issue is what I mentioned in the description and in my second comment. I lost track about it :disappointed: 

_Maybe_ it's not valid anymore after the refactors that this code has suffered in the last months.

**Comment by stsewd** [comment]
Closing this in favor of https://github.com/readthedocs/readthedocs.org/issues/7727 where the actual bug is described.
