### ISSUE TITLE
Inject canonical tag on mkdocs as we do with Sphinx

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#4820]
In Sphinx if a user has a custom domain we setup the canonical tag for the user (we also have some docs for that feature https://docs.readthedocs.io/en/latest/canonical.html)

In Sphinx we do that here https://github.com/rtfd/readthedocs.org/blob/9b2b17c0fc603267b4b20f5923862c2db82602da/readthedocs/doc_builder/templates/doc_builder/conf.py.tmpl#L95-L95

On mkdocs we don't do that, but it's possible using the `site_url` setting https://www.mkdocs.org/user-guide/configuration/#site_url

We can do that here

https://github.com/rtfd/readthedocs.org/blob/9b2b17c0fc603267b4b20f5923862c2db82602da/readthedocs/doc_builder/backends/mkdocs.py#L107-L107

Ref https://github.com/rtfd/readthedocs.org/issues/3137

**Comment by dojutsu-user** [comment]
@stsewd I would like to take this issue up.
I didn't find the way to get the canonical url of the project, is it present in the keyword arguments that `append_conf` receive, i.e. `__`?

**Comment by stsewd** [comment]
That comes from the project model, but this issue has the `Needed: design decision` label, we need to wait to be approved before writing some code

**Comment by stsewd** [comment]
Just adding that looks like the `site_url` option have been there for a long time, nothing relevant on the changelog https://www.mkdocs.org/about/release-notes/#other-changes-and-additions-to-version-0160

**Comment by astrojuanlu** [comment]
> Just btw MKdocs just yesterday added support for Environment variables in version 1.2.0, all you have to do is make a variable with the final URL available for the build :)

https://www.mkdocs.org/about/release-notes/#support-added-for-environment-variables-in-the-configuration-file-1954

**Comment by benjaoming** [comment]
As mentioned by @astrojuanlu, we can use environment variables in `.mkdocs.yml` and that would be valuable in general to users.

However, then this needs to be fixed: https://github.com/readthedocs/readthedocs.org/issues/8529
