### ISSUE TITLE
Custom redirect produces an infinite redirect

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#4848]
In #4673 we found that defining a custom redirect could produce an infinite redirect. Then, in #4833 we fixed this but some questions about "What's the best way to solve this?" came up.

For now, we are returning a 404 to avoid a 500 (which doesn't make too much sense) and also to avoid the original issue that was the infinite redirect.

This issue is just to track different opinions on how to solve this the best way.

**Comment by stsewd** [comment]
This points to a very old implementation of our proxito code. Right now, if we have an infinite redirect in the 404 view, we just continue with our 404 handling, which seems okay, if we are in the 404 handler means that we didn't find that file, redirecting to that same file will get the same result.

**Comment by humitos** [comment]
So, what's the current behavior? If it detects there is an infinite redirect it just returns 404, right? If that's the case, we can probably close this issue.

I took a look at what other possible HTTP status code we could return, but I didn't find anyone that I like more than 404. However, I'd like to differentiate, if possible, a regular 404 from a 404 that's because of an infinite loop, but 🤷🏼

**Comment by stsewd** [comment]
> So, what's the current behavior? If it detects there is an infinite redirect it just returns 404, right? If that's the case, we can probably close this issue.

yep
