### ISSUE TITLE
Better errror message for lists in config file

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#4914]
After https://github.com/rtfd/readthedocs.org/pull/4740 is merged, we will show the error message for lists as `list.{index}`, which isn't so clear, we should use `list[{index}]` instead.

Raised in https://github.com/rtfd/readthedocs.org/pull/4740#discussion_r233957618

**Comment by dojutsu-user** [comment]
@stsewd 
Can I take this issue?

**Comment by stsewd** [comment]
This isn't blocker anymore, but we still need to figure out a clean way of implementing this.

And I'm not really sure adding that logic is worth it, we should just keep the current message.

**Comment by humitos** [comment]
> we still need to figure out a clean way of implementing this.

This will take care the person that implements it.

I'm removing the `Design decision` label and marking it as `Accepted`.

> And I'm not really sure adding that logic is worth it, we should just keep the current message.

We can decide that when we see the changes in the PR propsed.
