### ISSUE TITLE
Add typedoc support to build environment

### ISSUE THREAD

**Issue by graup** [readthedocs/readthedocs.org#4920]
RTD supports sphinx-js and jsdoc. It works well with `build: image: latest`.

Recently sphinx-js added typedoc support for typescript. Could typedoc be installed in the builder image? Or is there a way to install it myself?

    npm install -g typedoc

Ref #3338

**Comment by humitos** [comment]
@graup we are already installing `jsdoc` with `npm`, so I think it won't be a problem to another npm dependency.

The line that has to be modified is this one:

https://github.com/rtfd/readthedocs-docker-images/blob/master/Dockerfile#L62

Thanks!

**Comment by dojutsu-user** [comment]
@humitos 
I am not familiar with that part of of the code, but would love to send a PR if it is just the modification of the line mentioned.
Can I take this?

**Comment by dojutsu-user** [comment]
@humitos 
I have made a PR
https://github.com/rtfd/readthedocs-docker-images/pull/81

**Comment by graup** [comment]
@humitos can we get this PR merged? thanks

**Comment by graup** [comment]
As a quick update, I successfully tested the typedoc integration [here](https://github.com/aergoio/herajs). It works with sphinx-js as the only requirement, the new `latest` docker image, and the Python 3 interpreter. I also had to write a setup.py script than does `npm install` because typedoc needs all the npm packages to properly parse the code.

Thanks!

**Comment by humitos** [comment]
There is a newer a simpler way to specify `typedoc` now. Check out this comment https://github.com/readthedocs/readthedocs.org/issues/3069#issuecomment-1130049390
