### ISSUE TITLE
Create a plugin for mkdocs integration as we do with Sphinx

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#4924]
Probably this would be a very low priority but I wanted to put it here so we don't forget.

Currently, we inject some values on the mkdocs config file 

https://github.com/rtfd/readthedocs.org/blob/c37b00995c1bbc5ee51d3552ef176546373bb912/readthedocs/doc_builder/backends/mkdocs.py#L107-L169

This is a problem when mkdocs make incompatible changes between versions, if we write an extension we can have more control over this.

Related #4820 #4827

Docs about writing plugins https://www.mkdocs.org/user-guide/plugins/#developing-plugins

**Comment by pranay414** [comment]
@stsewd Can I work on this?

**Comment by dojutsu-user** [comment]
Hi @pranay414 
Thanks for your interest in contribution.
This issue has a `Feature` tag -- https://docs.readthedocs.io/en/latest/roadmap.html?highlight=feature#triaging-issues

I would suggest to pick any other issue for now.

**Comment by pranay414** [comment]
Oh okay!

**Comment by humitos** [comment]
I think we decided we are not going to do this work anytime soon, at least.
