### ISSUE TITLE
Make raw_config private

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#4966]
In the config module we shouldn't mutate the original value, this is solved, but we are still exposing the `raw_config` as a public attribute, but we are mutating that attribute internally, we should make that private. And maybe expose the original too? We don't use that anywhere, so not sure.

Raised in https://github.com/rtfd/readthedocs.org/pull/4740#discussion_r239426405
Blocked by https://github.com/rtfd/readthedocs.org/pull/4740

**Comment by dojutsu-user** [comment]
@stsewd 
I think that this issue is no longer blocked.

> we should make that private

By this... did you mean to change the variable name to `_raw_config`?

**Comment by stsewd** [comment]
Yeah, maybe rename it to something more explicit if it makes sense or keep the same name, that's fine

**Comment by dojutsu-user** [comment]
I suggest to rename it to `raw_config_copy`.

**Comment by stsewd** [comment]
If renamed it should still be private, I don't see `_copy` adding more meaning, we can just keep the same name I guess

**Comment by dojutsu-user** [comment]
Okay... then, I think it can be renamed to `_raw_config` or else this issue can be closed.

**Comment by kushthedude** [comment]
@stsewd As far as I can understand, We need to make `raw_config` private and show a `raw-config` example file ?
