### ISSUE TITLE
Upgrade Django to 2.2

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#5058]
Django 2.2 LTS is scheduled to be released on April, 2019: https://www.djangoproject.com/download/#supported-versions

This is a meta issue to comment here all the things that need to be changed or considered before this date to start the migration in a smooth way.

We are currently using Django 1.11 LTS which its support ends on (at least) April, 2020.

**Comment by davidfischer** [comment]
Thanks for creating this. I also wanted to mention that I'm +1 on only taking LTS releases of Django going forward.

**Comment by dojutsu-user** [comment]
@humitos 
This will be huge :tada: 
Here is a non-exhaustive list of deprecated things:

* `django.utils.functional.allow_lazy` ([ref](https://docs.djangoproject.com/en/1.10/ref/utils/#django.utils.functional.allow_lazy))
* `ForeignKey` requires 'on_delete` parameter.
* `AutoOneToOneField` from `django-annoying` required `on_delete` parameter.
* Currently, we are using version `1.1.0` of `django-filters`, it needs to be updated to `2.0.0.`
* This line
    ```python3
    url(r'^admin/', include(admin.site.urls))
    ``` 
    needs to be changed **to this**:
    ```python3
    url(r'^admin/', admin.site.urls)
    ```
* Resolve these two clashes:
    ```
    builds.Version: (auth.E005) The permission codenamed 'view_version' clashes with a builtin permission for model 'builds.Version'.
    ```
    ```
    projects.Project: (auth.E005) The permission codenamed 'view_project' clashes with a builtin permission for model 'projects.Project'.
    ```

**Comment by humitos** [comment]
Django 2.2 is already released. This issue is not blocked anymore. It would be good to receive contributions for this migration.

> We have a separate code base for our commercial hosting to consider as well.

I suppose the changes there won't be too many considering the list of  deprecated things.

**Comment by davidfischer** [comment]
> I suppose the changes there won't be too many considering the list of deprecated things.

Well, there will be a fair bit of changes and coordinating with the other repos will involve some challenges. For example, every single `urls.py` file will require changes. Every single `models.py` with a foreign key will require changes.

**Comment by stsewd** [comment]
We also need to check if our dependencies support django 2.x

**Comment by dojutsu-user** [comment]
> It would be good to receive contributions for this migration.

Will definitely send PRs relating to this.

**Comment by davidfischer** [comment]
Django 2.x added `SESSION_COOKIE_SAMESITE` and `CSRF_COOKIE_SAMESITE`. I believe no changes to our codeline are required as the default values are appropriate for us.
