### ISSUE TITLE
abandoned project request: zeek

### ISSUE THREAD

**Issue by jsiwek** [readthedocs/readthedocs.org#5060]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/zeek/
* Build URL (if applicable): https://zeek.readthedocs.io/en/latest/
* Read the Docs username (if applicable): jsiwek (me), @RaphaelAslanian (current owner)

## Expected Result

I'd like to obtain the 'zeek' project name on RTD in association with our current/active project at https://github.com/zeek/zeek and https://www.zeek.org.

The  current 'zeek' project on RTD only hosts the literal "Hello World" string, so doesn't seem like proper usage.  It's also the only commit made by the current owner in a fork of the original project, https://github.com/Diastro/Zeek, which has not had any substantial commits besides a couple "typo fix" PRs since 2013.

I tried emailing the current owner directly a couple weeks ago, but without a response yet.

**Comment by jsiwek** [comment]
We're using a custom domain now, so the project name is less an issue.

**Comment by jsiwek** [comment]
Since the last comment, we've observed some people getting confused about the existing/abandoned 'zeek' project and would like to pursue acquiring it again so we can direct users to the right place.

**Comment by stsewd** [comment]
@jsiwek I have contacted the user today, I'm waiting for a reply. If we don't hear anything in 6 weeks, we can give you access to the project.

https://docs.readthedocs.io/en/stable/abandoned-projects.html

/remind me about take action on this project in 6 weeks

**Comment by stsewd** [comment]
@jsiwek user replied, and the project was deleted. You can create a project with that name now!

**Comment by stsewd** [comment]
This was already handled, bot
