### ISSUE TITLE
Support Sphinx2

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#5064]
Sphinx2 is doing a [lot of incompatible changes](http://www.sphinx-doc.org/en/master/changes.html#release-2-0-0-in-development) that we should start considering into our roadmap to support it.

This is not an issue to start working _now_, but to consider that it will affect our platform in many ways and we should start thinking about it and noting down where the problems would be and what are the actions that we should take.

Related: https://github.com/rtfd/readthedocs.org/pull/3581#issuecomment-450917453

**Comment by stsewd** [comment]
And we need https://github.com/rtfd/readthedocs.org/pull/3581, well we only need that if we want to make sphinx 2.0 the default

**Comment by davidfischer** [comment]
I don't think sphinx2 will be our default for quite some time.

**Comment by humitos** [comment]
> FYI. Sphinx builder dirhtml in Sphinx 2.0+ uses the name dirhtml. I think RTD v2 config is using htmldir. I'm not sure if the two are mapping correctly.

(from https://github.com/rtfd/readthedocs.org/issues/4638#issuecomment-491609697)

**Comment by stsewd** [comment]
We map the builder from the config file to our custom builder, so if anything we should change our builder custom builder (if needed). Also maybe is a good idea to include `dirhtml` as option in the config  file too?

**Comment by stsewd** [comment]
We already support sphinx2. Only the rtd theme is missing support for it.

**Comment by nschloe** [comment]
@stsewd Could you please link the bug for the rtd theme?

**Comment by stsewd** [comment]
@nschloe https://github.com/readthedocs/sphinx_rtd_theme/pull/838
