### ISSUE TITLE
Hide banned projects from the site

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#5152]
Change the .public and .private method of the ProjectQuerySetBase so they hide `banned` user's projects by default. We ban users because of spam, but don't delete them because we don't want to give spammers feedback on what's happening.

Users should probably still see their own banned projects, but nobody else, so this is a bit more complicated than a simple fix. 

Refs https://github.com/rtfd/readthedocs.org/pull/5097

**Comment by agjohnson** [comment]
I like the method of altering the querysets to silently drop these projects. We shouldn't be linking to or promoting any of these projects on site, or in our API.

**Comment by dojutsu-user** [comment]
@ericholscher 
I would like to take this issue up.

**Comment by humitos** [comment]
@dojutsu-user you can work on it if you want. I think it's clear what it's needed to do. I'm marking this issue as `Accepted`.

**Comment by dojutsu-user** [comment]
@humitos 
I will start working on it and will submit a PR soon.

**Comment by dojutsu-user** [comment]
@humitos 
I will start working on this after a few days. I am busy with the project evaluations and end semester exams right now.
Sorry for the delay.

**Comment by ericholscher** [comment]
Sorry for the misleading ticket here. We are going ahead and deleting these projects, instead of filtering them out. Closing this issue.
