### ISSUE TITLE
Allow for multiple hits per search result

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#5212]
Currently, our search results only display the first, and hopefully the best, search term found in the page. On clicking through to the result page, this requires having to manually scan a potentially large page for your search term. If we were able to support linking to individual search terms in documents, it would be easier to scan for the search hit.

I'm not sure if there is a good way to do this with our current index, but if not, I could see section indexes being helpful here. An example of a search the allows for multiple hits per page is the webpack docs. The search here links to the section heading containing the search result instead of to the individual search hit.

This depends on #4281 in some fashion, unless we go with section indexing.

**Comment by dojutsu-user** [comment]
Closing this as the code related to its already deployed in production.
More info: https://blog.readthedocs.com/improved-search-and-search-as-you-type/
