### ISSUE TITLE
Automate queue selection for resource intensive builds

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#5215]
We've had a number of problems stemming from projects over utilizing our build queue, especially when the projects require a lot of resources to build. We manually perform this task now, but it would be helpful to perhaps automate this so that we can ensure quick builds end up on a fast build queue, and slow builds are serviced by larger build servers.

Ideally, we'd know the average memory used to build a project, however, we can half-ass this guess by using average build time as a proxy metric. We're already collecting build time on Build objects, so a basic query will get us the average build time for project builds.

I'm proposing that on triggering a build, we decide the between a build queue of `build` or `build-large` based on the average build time for the last X builds. If average build time is over, say, the 90% percentile for build times, we push the build to a separate server with lower concurrency and higher resources.

We're effectively doing this now, but by specifying the queue manually.

**Comment by humitos** [comment]
> I'm proposing that on triggering a build, we decide the between a build queue of `build` or `build-large` based on the average build time for the last X builds. If average build time is over, say, the 90% percentile for build times, we push the build to a separate server with lower concurrency and higher resources.

I like this idea. Looks simple enough and not too hard to implement. BTW, considering that this will be done on the webhook request _before_ creating the task, how much time that db query (calculating average) would take?

Also, do you think that this would only apply once when `project.build_queue=None` and after being set by this logic we do not calculate averages anymore?

> We're effectively doing this now, but by specifying the queue manually.

For the records, this is currently our `build03` queue.

**Comment by ericholscher** [comment]
This is now shipped: https://blog.readthedocs.com/better-conda-support/
