### ISSUE TITLE
Refactor docker version selection

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#5234]
Right now, we support arbitrary image names inside our `DOCKER_IMAGES` setting, but our version validation is much more strict. For instance, I had an image `readthedocs/build:dev` and can no longer use that image name, as the validation method only supports:

* Numbered images that aren't RCs
* Version `latest`
* Version `stable`

The version is silently changed to `latest` if there isn't a match.

The actual functionality should be:

* If we aren't in DEBUG, RC images are not selectable
* We pull out any version name from the DOCKER_IMAGES that aren't deselected
* An error is raised if the image is not found, `latest` isn't silently forced

**Comment by humitos** [comment]
I don't think we need this anymore since we are not building our own images as before (`readthedocs/build:dev`). I'm closing this issue. We can revisit in the future if required.
