### ISSUE TITLE
Make search exclude files a path operation

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#5247]
Our method of filtering out files from search operations was a string comparison, which produced a lot of false positive hits. This comparison should be a path comparison that looks explicitly for `os.path.join(doc_path, 'search.html')` instead of using string comparison.

Filtering is disabled for now, we should clean up search results soon and reenable it.

Refs #5246

**Comment by dojutsu-user** [comment]
I would like to work on this.
Can I get more info on this... it is not clear to me.

**Comment by agjohnson** [comment]
Here is the main issue:
https://github.com/rtfd/readthedocs.org/pull/5246/files#diff-7faf5e6b86776ca9b80505230b669285R114

It simply looked for paths ending `search.html` for example. This would incorrectly catch files like `foo/search.html` or `foo_search.html`.

If we can't use file operations for this query in some way, we should at least be more strict about the root path. We should more explicitly catch the default sphinx pages we're not looking to index.
