### ISSUE TITLE
Search: Highlight exact matches improvements

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#5270]
In #4292 exact match search was implemented, but I'm not sure it is working as expected or at least it could be improved in some ways.

Following [this link](https://docs.readthedocs.io/en/stable/search.html?q=%22404+not+found%22&check_keywords=yes&area=default#), we search for `"404 not found"`

* I expect to get the whole phrase highlighted
* only get results where the whole text appears in that specific order
* there are results where `not` is highlighted alone, which makes me confuse

In [this another example](https://docs.readthedocs.io/en/stable/search.html?q=%22results+not+found+here%22&check_keywords=yes&area=default#), I search for `"results not found here"`

* do not fallback on sphinx search when using exact match

[Another search](https://docs.readthedocs.io/en/stable/search.html?q=%22custom+domains%22&check_keywords=yes&area=default#) for `"custom domains"`

* clicking on the first result goes to https://docs.readthedocs.io/en/stable/custom_domains.html?highlight=%22custom%20domains%22 which contains `?highlight="custom domains"` which makes the JS code to get confused and do not highlight anything

**Comment by ericholscher** [comment]
This is using the ES [Simple String Query](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-simple-query-string-query.html) -- but it has almost no documentation on how it works. Quoting the search does result in a smaller set of results than not quoting, but I don't fully understand what is happening.

**Comment by ericholscher** [comment]
I believe it's saying "all these words must be present on the page", but not all those words are showing up in the query results, but they are indeed all _on_ the page.

**Comment by ericholscher** [comment]
You can see the results better on site search: http://localhost:8000/search/?q=%22custom+domains%22&type=file&version=latest&project=docs

**Comment by ericholscher** [comment]
Looks like a known issue: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html

> Highlighters don’t reflect the boolean logic of a query when extracting terms to highlight. Thus, for some complex boolean queries (e.g nested boolean queries, queries using minimum_should_match etc.), parts of documents may be highlighted that don’t correspond to query matches.

**Comment by dojutsu-user** [comment]
@humitos 
We have removed the `highlight` url param, is this issue still valid?

**Comment by stsewd** [comment]
The highlight is back, but not sure if we can do much about this.

**Comment by stsewd** [comment]
From the docs https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-highlighting.html

```
fragmenter

    Specifies how text should be broken up in highlight snippets: simple or span. Only valid for the plain highlighter. Defaults to span.

    simple
        Breaks up text into same-sized fragments. 
    span
        Breaks up text into same-sized fragments, but tries to avoid breaking up text between highlighted terms. This is helpful when you’re querying for phrases. Default. 
```

Didn't test how it looks like, but maybe I'll give it a try later.

**Comment by stsewd** [comment]
> I expect to get the whole phrase highlighted

I'll see if I can play around operators and see if there is any improvement, but this again falls to try to parse the query.

> do not fallback on sphinx search when using exact match

We always need to fallback to the original search when there aren't results, this way we guarantee we don't miss anything. The search extension doesn't fallback.

> which contains ?highlight="custom domains" which makes the JS code to get confused and do not highlight anything

That may be tricky to solve, we could analyze the original query and return the intended text without any operators (but this could result in dropping some original content from the query). And we would need to implement a mini-parser for the single simple query (probably not that hard).

**Comment by stsewd** [comment]
> I'll see if I can play around operators and see if there is any improvement, but this again falls to try to parse the query.

Nope, using just the `and` operator didn't solve this.

**Comment by stsewd** [comment]
@humitos what you are looking there is the default Sphinx search, our search returns zero results for that query.

**Comment by humitos** [comment]
Closing in favor of https://github.com/readthedocs/addons/issues/36
