### ISSUE TITLE
Extend versions' states

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#5321]
Currently we have `active` and `non-active` versions' states.

[I suggested](https://github.com/rtfd/readthedocs.org/issues/4001#issuecomment-432165843) more states like `inactive` and `deprecated` so they are still being served or shown in the flyout as needed.

I'm creating this issue here to tack this since the #4001 won't cover these new states for now.

**Comment by stsewd** [comment]
What would be the difference between "inactiva" and "deprecated"? Or are you talking about one state here? Maybe "hidden" is a better name?

**Comment by agjohnson** [comment]
"hidden" or "archived" are pretty clear adjectives for these versions. Seems we could have the following fields on the version model:

* `active` = `True` or `False` -- is the version going to build again?
* `archived` = `True` or `False` -- is the version archived?
* maybe `deprecated` = `True` or `False` -- is the version not recommended for use?

I think all the possible combinations make sense in this case. Even if a version is `active = False`, the user can still communicate that it is archived, archived and deprecated, or just deprecated and never built again.

**Comment by humitos** [comment]
@agjohnson I'm not following you exactly.

Although the adjectives are clear, I'm not sure to understand how they behaves on our platform:

* `archived` won't be shown in the flyout menu and won't be served
* `deprecated` won't be shown in the flyout but it will be served when hitting the URL

Combining these, `archived=True` and `active=True` is the only state that does not make too much sense since we will be building a Version that won't be served at all.

On the other hand, `deprecated=True` and `active=True` makes sense, since although the version is not more supported, a typo or a note or similar could always be added and it needs to be updated (re-built).

The workflow that I see here would be:

1. the version is `active=False` originally
1. make it public, `active=True`
1. it gets `deprecated=True` after years
1. fix a typo on it and re-build automatically
1. after some months/years more it's not supported anymore and want to remove it from the public list of docs, marked as `archived=True`
   * this action will probably mark the version as `active=False` also
   * will remove artifacts for this version

**Comment by humitos** [comment]
> What do you think about these states? Do these version states help with UX around versions?

I like these states. `hidden` is clearer than `archived` to me, though.

I'm :+1: on going forward with them.

**Comment by agjohnson** [comment]
Cool. I'm not sure exactly how these attributes are structured yet, as there are some competing values there perhaps. Like, any value of `hidden` doesn't make sense when we have `live=False`.

Any opinions here?

**Comment by humitos** [comment]
> Like, any value of `hidden` doesn't make sense when we have `live=False`.

In my mind `hidden` takes preference over `live` when `hidden=True`. The other case, `live` takes preference over `hidden` when `live=False`. I don't think it's a problem.

**Comment by agjohnson** [comment]
Sure, but if there is conflict in how these fields are used, they should be grouped under a single choice field, not necessarily all boolean attributes.

For instance, using the above as an example, if `live` and `hidden` result in overlapping outcomes, it doesn't make sense to treat these two attributes as separate boolean fields. They should be grouped under a single choice field so that it's not a question of which boolean field takes precedence. We need to figure out these overlaps in meaning still.

So far I think we've only seriously considered `active=True` and `hidden=True`. These two don't seem like conflicting options.

**Comment by agjohnson** [comment]
We should probably prioritize finishing this and having some functionality for hiding versions however. Users currently don't have any way to accomplish this other than deactivating a version.

**Comment by stsewd** [comment]
So, hidden is implemented. `live` sounds like the same as `built` for me. Not sure about the `deprecated` state, looks the same as `hidden` but only with the deprecated banner. Maybe we could just mark hidden versions as deprecated or something like that.

**Comment by stsewd** [comment]
Any thoughts if this should be considered valid now?

**Comment by agjohnson** [comment]
I was most interested in hidden, I don't have strong opinions about the others and would aggress that it sounds like there is some redundant meanings there. Deprecated might be a nice dedicated attribute to have, but likely requires we do something special with deprecated versions in a consistent way. Currently, it might only feed into the sphinx deprecated extension, and wouldn't work for other tools. We could revisit this later if we come up with a plan for other version states i think
