### ISSUE TITLE
Don't include searchbox in singlehtml builds

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#5359]
Search isn't supported in this kind of builders (search.html isn't included).

Building locally doesn't show the search box, but on rtd it's shown, because our builder is named `readthedocssinglehtml`

Themes check only for https://github.com/rtfd/sphinx_rtd_theme/blob/8c31a26a79702a0ffbb2ee153d4bb054d58087ac/sphinx_rtd_theme/searchbox.html#L1-L1

Should we patch the theme? (problem will still present in other themes) or should we change the way we call our builder or override the builders

**Comment by humitos** [comment]
I suppose there should be an option in the theme to disable the searchbox completely. Then, our builder should be called with that option.

This also option will be useful in other cases too.

**Comment by ericholscher** [comment]
I don't think this is an RTD issue. Presumably the theme should handle this, no?

**Comment by stsewd** [comment]
@ericholscher yeah, the theme should handle this, but it could probably be present in other themes that don't take the `readthedocssinglehtml` builder into consideration. I can patch our theme if that sounds good

**Comment by humitos** [comment]
> that don't take the `readthedocssinglehtml` builder into consideration

As a general comment, we should move away of these specific builder names probably and use a [similar approach as the one used in hoverxref extension](https://github.com/readthedocs/sphinx-hoverxref/blob/master/hoverxref/extension.py#L100): we inject our own mixin that changes behavior _only_ where we need it but does not override user's.
