### ISSUE TITLE
Refactor `build_docs_html` to use `build_docs_class`

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#5410]
`build_docs_html`

https://github.com/rtfd/readthedocs.org/blob/4911600c230809bd6fb3585d1903121db2928ad6/readthedocs/projects/tasks.py#L839-L839

should use https://github.com/rtfd/readthedocs.org/blob/4911600c230809bd6fb3585d1903121db2928ad6/readthedocs/projects/tasks.py#L903-L917

as the other builders and not be a special case.

**Comment by Iamshankhadeep** [comment]
Can I work on it? I think it is easy enough to solve. but still I am new to this community so learning everything I can.

**Comment by krutik710** [comment]
@stsewd Has this issue been assigned to anyone?
If not I can start working on it!

**Comment by dojutsu-user** [comment]
It seems like no one is working on it currently.
I'm working on it.

**Comment by stsewd** [comment]
Feel free to take this issue!

**Comment by saadmk11** [comment]
@stsewd if we use `build_docs_class` then what will happen to:
https://github.com/rtfd/readthedocs.org/blob/4911600c230809bd6fb3585d1903121db2928ad6/readthedocs/projects/tasks.py#L845-L847

as they depend on the `builder` but `build_docs_class` returns only `success` not the `builder`.

**Comment by humitos** [comment]
This was done in https://github.com/readthedocs/readthedocs.org/pull/9002/files#diff-2c0b1d043c9dce8c6517b5f5ee669e37a2b673e5b2263a6968f25364c942b351R311
