### ISSUE TITLE
Link to in-progress build from dashboard

### ISSUE THREAD

**Issue by jasonaowen** [readthedocs/readthedocs.org#5427]
## Details

When a project is building, the dashboard page (eg `https://readthedocs.org/projects/<project-name>/`) shows a message:

> Your documentation is building
> 
> You'll be able to view your documentation in a minute or two, once your project is done building.

## Expected Result

I expected to find a link to the in-progress build, as I would find on a dashboard in Travis CI or Jenkins.

## Actual Result

There is no link, and instead I have to navigate to the builds tab and click on the most recent build.

**Comment by shivanshu1234** [comment]
I would like to work on this issue.

**Comment by stsewd** [comment]
This was done in #5431
