### ISSUE TITLE
Sitemap does not include HTTPS links for custom domains

### ISSUE THREAD

**Issue by strophy** [readthedocs/readthedocs.org#5445]
The generated `sitemap.xml` gets the URL for each available version by calling [`get_docs_url`](https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/projects/models.py#L474). For custom domains, this returns HTTP links, which perform a 301 redirect to the HTTPS version. But sitemaps should only point to actual pages (references: [Google](http://www.thesempost.com/google-avoid-including-redirected-urls-sitemaps/), [Bing](https://sitebulb.com/hints/xml-sitemaps/redirect-3xx-url-in-xml-sitemaps/)) and not redirects, or the crawler may begin losing trust in the sitemap and put a penalty on the information it contains.

Also, the docstring for this method is probably incorrect, as noted [here](https://github.com/rtfd/readthedocs.org/issues/5391#issuecomment-471963127). This method actually returns HTTPS links for non-custom domains. Related issue: #4641 

Example: [https://docs.dash.org/sitemap.xml](https://docs.dash.org/sitemap.xml)

**Comment by Seenivasanseeni** [comment]
I have started to work on this.

**Comment by dojutsu-user** [comment]
Still valid bot.

**Comment by humitos** [comment]
Marking the issue as Accepted since is something we want to fix.

**Comment by KartikKapil** [comment]
hello @humitos  i would like take this issue up what exactly do i need to do for this ???

**Comment by humitos** [comment]
Hi @KartikKapil! The requirements for this issue are in the description of the issue. Is there any particular point that you don't understand from there?

**Comment by KartikKapil** [comment]
@humitos  i could not figure out that how to change the function get_docs_url to make sure it oints to the pages but does not redirect

**Comment by ashadhaz** [comment]
Hey @humitos I would like to work on this issue. Is it still open?

**Comment by humitos** [comment]
@ashadhaz yes, it's still open

**Comment by Parth1811** [comment]
@ashadhaz are you still working on this issue? If not I would like to work on this.

**Comment by Parth1811** [comment]
I am working on this issue as mentioned on IRC.

@stsewd how should this be fixed, there are two approaches:
1. Simply place `https` instead of `http` and expect the custom domain to have SSL.
2. In the `get_docs_url` method make a request and check if the domain has SSL and then proceed accordingly.

**Comment by ericholscher** [comment]
This is now fixed 👍
