### ISSUE TITLE
Proxito: look for custom 404 pages in the parent project of subprojects

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#5557]
After implementing #353 we do support custom 404 pages if we find a `404.html` page in the current version (or default version) of the project.

Although, if we are accessing a `subproject` this logic does not work and the standard 404 page is served.

My guess is that the problem is at 

https://github.com/rtfd/readthedocs.org/blob/2e29b61a815994b646dda204b975e1c8d7926b79/readthedocs/core/views/__init__.py#L193

Since that function checks for `request.slug` and if it does exist it just return it, but that `request.slug` is always set to the superproject at

https://github.com/rtfd/readthedocs.org/blob/2e29b61a815994b646dda204b975e1c8d7926b79/readthedocs/core/middleware.py#L71

or here if it's a custom domain,

https://github.com/rtfd/readthedocs.org/blob/2e29b61a815994b646dda204b975e1c8d7926b79/readthedocs/core/middleware.py#L85

In the end, the subproject is never considered when looking for a custom 404.

I'm not sure how big will be the impact of setting the subproject's slug to `request.slug` (which seems more accurate to me) in other places of the codebase.

**Comment by rshrc** [comment]
Is someone working on this issue currently?

**Comment by humitos** [comment]
@rshrc I don't think so. It's labeled as `design decision`.

Please, feel free to analyze its context and give and propose a detailed solution. It would be good to make the discussion happen and work towards the solution.

**Comment by humitos** [comment]
Also, I think there is another discussion that can take place here. There are two possible paths to take here,

1. setup a 404.html page on the superproject and that page should be server for all the subprojects (current behavior, but broken)
1. each subproject should have their own custom 404 at their root path (behavior proposed on the description by changing the `request.slug`)

**Comment by stsewd** [comment]
I don't think this is a problem anymore, currently we are using django's URL resolve + `_get_project_data_from_request` to resolve the current project, which will be set to the subproject correctly.

https://github.com/readthedocs/readthedocs.org/blob/cd8f2da0d430f7c4454368c321d6859caa4808b6/readthedocs/proxito/views/serve.py#L465-L472

And quick test to confirm

https://test.org.stsewd.dev/projects/stsewd-demo/en/fasfd

You can see the source code to check that the 404 page served was from the subproject.

What we don't do yet is this

> I think we should check for a subproject 404 page, then the parent project 404

**Comment by ericholscher** [comment]
> What we don't do yet is this
> 
> > I think we should check for a subproject 404 page, then the parent project 404

Should we do this?

**Comment by stsewd** [comment]
> > What we don't do yet is this
> > > I think we should check for a subproject 404 page, then the parent project 404
> 
> Should we do this?

I'm -1, since that would require more calls to storage :)

**Comment by ericholscher** [comment]
Makes sense to me :)
