### ISSUE TITLE
Implement Static Type Checking Using ``mypy`` in RTD

### ISSUE THREAD

**Issue by dojutsu-user** [readthedocs/readthedocs.org#5582]
RTD code base is growing on a regular basis and we might want to implement static type checking for cleaner code.

- We can update the code base in a step by step manner. Making changes in one app at a time and testing it.
- Integrating mypy with travis-ci will also help to prevent avoidable errors.

Many orgs have already implemented it (Zulip, Dropbox, Instagram... ).
[Zulip](https://github.com/zulip/zulip) is an open source project and we can take help from its code base (if we gets stuck). They have added mypy in a stepped manner which can be seen in some PRs - [#7949](https://github.com/zulip/zulip/pull/7949), [#7936](https://github.com/zulip/zulip/pull/7936), [#7934](https://github.com/zulip/zulip/pull/7934), [#7890](https://github.com/zulip/zulip/pull/7890), [#7886](https://github.com/zulip/zulip/pull/7886).

**Comment by stsewd** [comment]
If we implement this, I think we could just add the type checking in new code and little refactors rather than whole apps. There could be some problems with type checking and imports (executing unnecessary code, circular dependencies). I know there are some workarounds but, they feel hacky sometimes.

**Comment by dojutsu-user** [comment]
@stsewd 
I understand the problem of circular imports. But, my inspiration is from Zulip, as it is another big project, and has implemented it. And we can also do the same. It will benefit us in the long run.

**Comment by agjohnson** [comment]
I'm -0 on type checking I suppose. It's nice to have in theory, but we're limited on engineering efforts and I'm not sure how much benefit the core team will really get out of static type checking compared to the amount of work that is going to go into adding and maintaining type checking annotations. We still haven't had a strong push to finish code style linting, so core team would be pretty unlikely to maintain type checking annotations.

Easing into type checking is a possibility if we decide to go this route.

@rtfd/core feelings? :+1: :man_shrugging: :-1: ?

**Comment by stsewd** [comment]
Well, in python 3.7 type annotations got a lot better (lazy evaluation). I'm -0, we could try this with new projects.

Also, we currently use the `:type:` role in some docstrings, which isn't really checked by any tool (I don't like that)

**Comment by humitos** [comment]
I vote here is to test "how we feel it in a new small project". I wouldn't go directly to the main repository. It's good to have it but it's really verbose and we are not already using it anywhere, so we will have a learning curve that I think we can't afford at this moment in a big repository like this one.

I'm :+1: on using it in a new Sphinx extension or small project and have a new discussion after that.

**Comment by dojutsu-user** [comment]
We can use this with [commonmark.py](https://github.com/readthedocs/commonmark.py)? It is a relatively small project.

**Comment by sjjessop** [comment]
For what the opinion of a random passer-by is worth: commonmark.py still supports Python 2.7, and for that reason you'd be signing up for a sub-standard experience of using type annotations. If you're concerned that you wouldn't maintain annotations, then it'd be even less fun to do so using a syntax you know is obsolete.

**Comment by humitos** [comment]
> I vote here is to test "how we feel it in a new small project"

We started testing this idea on https://github.com/readthedocs/readthedocs-assistant.

I'm don't think we will implement `mypy` on the main codebase for in the near future. We weren't even able to blackify our code yet which had a bigger priority than mypy.

Unfortunately, I'm closing this issue since we won't tackle it anytime soon. We can always come back to this, tho.
