### ISSUE TITLE
Github integration ignores source_suffix

### ISSUE THREAD

**Issue by lazka** [readthedocs/readthedocs.org#559]
Example: https://python-gtk-3-tutorial.readthedocs.org/en/latest/index.html

The repo uses ".txt" as source_suffix which breaks the "Edit on GitHub" link.

See https://github.com/sebp/PyGObject-Tutorial/issues/24

**Comment by mgeier** [comment]
This still doesn't work if `source_suffix` is a list of suffixes!
It seems that only the first element of the list is taken into account.

**Comment by agjohnson** [comment]
@mgeier can you please open a separate issue to address the problem you're describing? The original issue here has been resolved for a while now.

**Comment by mgeier** [comment]
@agjohnson: OK, done: #1871.
