### ISSUE TITLE
Edit on GitHub link is broken for branches with e.g. slash in the name

### ISSUE THREAD

**Issue by jodal** [readthedocs/readthedocs.org#561]
If you have docs built from a branch with e.g. slash in the name, like `v1.x/master`, then RTD will "slugify" it and use v1.x-master in URLs. That's OK.

The problem is that RTD use this slugified branch name to construct the "Edit on GitHub" URL as well, which then becomes a broken link.

**Comment by Jamim** [comment]
It looks like there is some regression, so it's broken again.
I believe that this issue should be reopened.

**Comment by stsewd** [comment]
@Jamim Please give more information, like the project where you are seeing this

**Comment by jack1142** [comment]
@stsewd I can see this happening in Cog-Creators/Red-DiscordBot project on `V3/develop` version and `latest` version which uses `V3/develop` too:
https://docs.discord.red/en/v3-develop/
https://docs.discord.red/en/latest/
