### ISSUE TITLE
Unify build_env and setup_env

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#5672]
Currently we are using two different build instances 

https://github.com/rtfd/readthedocs.org/blob/2e797fa1b45fe9772c6cf77c4fd55731d515585d/readthedocs/projects/tasks.py#L454-L454

https://github.com/rtfd/readthedocs.org/blob/2e797fa1b45fe9772c6cf77c4fd55731d515585d/readthedocs/projects/tasks.py#L536

We have some places where we are expecting for the `setup_env`  attr.

This should be only one instance.

**Comment by humitos** [comment]
I'm not sure to follow this issue.

* What are the current problems?
* What are the benefits of using the same build environment?

**Comment by stsewd** [comment]
Code is hard to read and follow, the `setup_env` is expected in a parent class. Also, sometimes we are setting the environment to `None`, but we always need an environment. Also that we sometimes expect a dictionary and others an object.

We could still use separated environments, because we don't know the docker image to use at the clone step (this is known after parsing the config file). But the rest of things need to be refactored.

**Comment by humitos** [comment]
We have to be careful with this because on `setup_env` we are passing `update_on_success=False` to avoid changing the state of the build and we are only passing `environment=` to the `build_env` (although, I'm not sure if it could be a problem)
