### ISSUE TITLE
Latest html build of docs does not include images; branch html build does

### ISSUE THREAD

**Issue by alexpreynolds** [readthedocs/readthedocs.org#5709]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/bedops/
* Build URL (if applicable): https://readthedocs.org/projects/bedops/builds/9087007/
* Read the Docs username (if applicable): alexpreynolds

## Expected Result

Images in: https://bedops.readthedocs.io/en/latest/ are rendered exactly as they are rendered in: https://bedops.readthedocs.io/en/v2p4p36/

## Actual Result

Images are missing from the `latest` build, which are visible in the `v2p4p36` (branch) build. In place of images, broken images ("missing links") are shown, instead.

**Comment by humitos** [comment]
I don't see any errors related to your project in our servers.

Also, it seems that something you changed is producing this effect because I build your docs locally (outside Read the Docs) by calling `make html` and I have the missing images as well.

Please, check your latest changes to find out if there is something wrong there.

**Comment by humitos** [comment]
Try building your docs locally and let me know if you can reproduce this issue or not.

**Comment by alexpreynolds** [comment]
I cannot reproduce this issue if I build the documents locally — outside of RTD (_i.e._, `git pull origin master`, `cd docs`, and `make html`, followed by `open _build/html/index.html`, loads images correctly).

The issue only seems to appear on the documentation site hosted through bedops.readthedocs.io, and only in the `latest` build (based off the `master` branch).

For instance, this image can be found:

https://bedops.readthedocs.io/en/v2p4p36/_images/set_operations_v2.png

But this URL is not found:

https://bedops.readthedocs.io/en/latest/_images/set_operations_v2.png

Same file. The only change is in the path.

The `latest` docs are based off the `master` branch. 

Both `master` and `v2p4p36` have the same commits for documentation. 

Because the documentation folder has the same content in both branches, I don't understand why the images for the v2p4p36 site are correctly linked, and images for the `latest` site are not. 

I do not see any errors in the RTD build log for the `latest`/`master` branch, which is why I submitted this issue.

**Comment by davidfischer** [comment]
I ran the following exactly and I see the same issues as @humitos:

    git clone https://github.com/bedops/bedops.git
    cd bedops/docs/
    virtualenv .venv
    source .venv/bin/activate
    pip install -r requirements.txt
    pip install "sphinx<2"
    make html

I see a couple problems:

* Since you are using a custom stylesheet in `docs/_static`, you need to add the following to your `conf.py`: `html_static_path = ['_static']`
* The images that are in `raw` blocks are not being copied. When sphinx sees an image directive, [it knows to copy the image over to the output directory](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html?highlight=automatically#images) but it can't do that for `raw` blocks. You need to either copy these over yourself or refactor the docs to not use `raw`.

Hopefully that helps.

**Comment by humitos** [comment]
> I cannot reproduce this issue if I build the documents locally — outside of RTD (_i.e._, `git pull origin master`, `cd docs`, and `make html`, followed by `open _build/html/index.html`, loads images correctly).

Did you cleanup your local environment before? You may have some old files (images) located in the right folder and that's why they are found in your computer but not in ours.

Try running `make clean` first or starting from scratch following the steps that David mentioned. Let us know.

**Comment by alexpreynolds** [comment]
I did the following on a "clean" computer with Python 3.5.2 (Anaconda):

```
$ git clone https://github.com/bedops/bedops.git
$ git branch
* **master**
$ cd bedops/docs
$ make clean
$ pip install -r requirements.txt
$ make html
$ open _build/html/index.html
```

The `index.html` that I open links to the images and displays them correctly.

The problem seems to be specifically with the `latest` RTD build, which is hosted on bedops.readthedocs.org. 

I don't know how to troubleshoot why the `latest` build is failing, while the `v2p4p36` build on bedops.readthedocs.org works fine.

The `latest` RTD build is based off the `master` code branch. The `v2p4p36` RTD build is based off the `v2p4p36` code branch.

There is no difference in the `conf.py` file between the master and v2p4p36 code branches, nor are there any differences in the code in the rest of the `docs` folder, between these two branches.

If there is a problem with `conf.py`, why does it work for the `v2p4p36` RTD build, but not for the `latest` RTD build?

**Comment by alexpreynolds** [comment]
To reiterate what seems like the root of the problem with an example:

This image can be found, taken from the `v2p4p36` build:

https://bedops.readthedocs.io/en/v2p4p36/_images/set_operations_v2.png

But this image is not found for the `latest` build:

https://bedops.readthedocs.io/en/latest/_images/set_operations_v2.png

This is the exact same image file. The only change here is in the path.

The RTD site returns no log errors for the `latest` or `v2p4p36` builds. I have no evidence that something went wrong on RTD's side (although something is clearly wrong).

RTD is copying images to the correct location for the `v2p4p36` build.

RTD is not copying images for the `latest` build.

All documentation and configuration files for both builds are identical. 

RTD is not copying images for one build, but it is copying them for another.

**Comment by stsewd** [comment]
What version of sphinx are you using locally? Read the Docs is using `v1.8.5`

**Comment by humitos** [comment]
> $ pip install -r requirements.txt
> $ make html

There are something missing in your steps for full clean environment.

This `pip install` command will only install `sphinx-better-theme==0.1.4` and the next command `make html` will fail saying that sphinx is not installed in the system.

So, you are probably using an environment with a bunch of other packages. I can't reproduce the error without knowing exactly how is your environment setup.

**Comment by alexpreynolds** [comment]
I added a [hotfix](https://github.com/bedops/bedops/commit/6a7bd31a585b5e8a7d2e66ff9d1e40ae89aed16f) to manually copy images from the docs folder to the `_build/html/_static` build subdirectory, to ensure that they are available.

The following works for me locally:

```
$ conda create --name sphinx-test python=3.6
$ conda activate sphinx-test
(sphinx-test) $ pip install -r requirements.txt 
(sphinx-test) $ pip install sphinx==1.8.5
(sphinx-test) $ cd bedops/docs
(sphinx-test) $ make clean
(sphinx-test) $ make html
(sphinx-test) $ open _build/html/index.html
```

However, with this hotfix, the `latest` build on RTD now gives a build failure error:

> Error
> There was a problem with Read the Docs while building your documentation. Please try again later.
> However, if this problem persists, please report this to us with your build id (9117264).

**Comment by alexpreynolds** [comment]
For reference: https://readthedocs.org/api/v2/build/9117264.txt

**Comment by alexpreynolds** [comment]
In addition to showing that the build works with an Anaconda environment (e.g., "sphinx-test"), I added a hotfix that manually copies files to the `_static` subfolder. 

The `latest` build does not work, but the `v2p4p36` build does. 

Before the hotfix, both builds relied on the same configuration. 

After the hotfix (based on recommendations described above), `latest` and `v2p4p36` have different configurations, but still the `latest` build does not link to images correctly.

Something appears to be wrong with how the `latest` build manages access to either the `_static` — or to other locations where images are kept — which does not affect builds of other versions. 

Changes to the configuration — before and after the hotfix — do not change the outcome.

**Comment by alexpreynolds** [comment]
This is kind of a black box once the files are pushed out to the readthedocs site. I don't know how to troubleshoot a situation where the documents build locally, but do not get hosted correctly on the readthedocs site. Is there anyone who can help?

**Comment by stsewd** [comment]
I'll try to dig in to this tomorrow

**Comment by humitos** [comment]
I want to confirm that following this steps locally: https://github.com/readthedocs/readthedocs.org/issues/5709#issuecomment-495370052 I'm able to see the images on the index output page

**Comment by humitos** [comment]
@alexpreynolds I triggered a new build on Read the Docs and images are not present: https://readthedocs.org/projects/bedops/builds/9405545/

Although, the scenarios are not the same. Your project is using Python2.7 to build the docs and no conda. In the steps that you described, Python3.6 _and_ conda are used.

Also, your Makefile is running

    find _build/../assets -type f -name "*.png" -exec cp -f "{}" _build/html/_static \;


which is not executed in Read the Docs since we do not call `make html` as a step. You should fix your configuration to make Sphinx to copy these images for you instead of doing it manually.

Finally, I do not think that this is a problem of Read the Docs, but _how_ your project is setup on Read the Docs. I recommend you to use a https://docs.readthedocs.io/en/latest/config-file/v2.html and make Sphinx to find the images that you want to include by itself instead of using `find` in the Makefile. That will solve all the issues you are having.

**Comment by aiqc** [comment]
`make clean` solved it for me.

https://stackoverflow.com/questions/67650549/readthedocs-not-finding-image-and-html-is-different-from-github

**Comment by aiqc** [comment]
So if you *view page source* on RTD all of the asset paths start with `_static` so I moved all of my images into `_static/images` then updated the references `<img src="_static/images/...`
