### ISSUE TITLE
Request to increase memory limit for ligo-virgo-public-alerts-user-guide

### ISSUE THREAD

**Issue by lpsinger** [readthedocs/readthedocs.org#5717]
Please increase the memory limit for the project ligo-virgo-public-alerts-user-guide to 4 GB. This project builds some images based on astronomical data using the Matplotlib plot directive. When I test the build in a docker container, the memory usage (maximum resident set size) peaks at about 3 GB. The 4 GB request includes a safety margin.

## Details

* Read the Docs project URL: https://readthedocs.org/projects/ligo-virgo-public-alerts-user-guide/
* Build URL (if applicable): https://readthedocs.org/projects/ligo-virgo-public-alerts-user-guide/builds/9108977/
* Read the Docs username (if applicable): lpsinger

## Expected Result

The build should succeed.

## Actual Result

The html build fails with this error message:

    Command killed due to excessive memory consumption

**Comment by stsewd** [comment]
> Please increase the memory limit for the project ligo-virgo-public-alerts-user-guide to 4 GB

That's really a lot, I think 4GB is what our servers have.

I can see that your latest builds are successful, do you still need more resources for your project?

https://readthedocs.org/projects/ligo-virgo-public-alerts-user-guide/builds/

Also, please see https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html

**Comment by lpsinger** [comment]
I added a temporary workaround that allowed me to skip the memory-intensive part of the build, but it's not a satisfying solution because it diminishes reproducibility.

The advice in https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html is helpful, but unfortunately not relevant in this circumstance, because the peak memory use is due to opening a particular astronomical data file.

We do have our own self-hosted GitLab instance with GitLab runners. Is there a way that we can use our own hardware to build readthedocs documentation sets, short of a self-hosted installation of readthedocs?

**Comment by stsewd** [comment]
We have a feature coming #1083. And yes, you can have a self hosted instance of Read the Docs https://docs.readthedocs.io/en/stable/custom_installs/index.html

**Comment by lpsinger** [comment]
It looks like #1083 has not progressed. Is it possible to increase the memory allocation?

**Comment by stsewd** [comment]
@lpsinger we could increase it till 2GB, but not 4

**Comment by lpsinger** [comment]
Darn. I guess we'll just have to wait for #1083 to be resolved.
