### ISSUE TITLE
Point users to commercial solution for private repositories

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#5770]
Continuing with the idea of pointing our users to what they need, I think it's good to point to the Commercial solution at the Import Project page where they may be looking for for their private repositories.

I think that Travis does an excellent job for this.

![screenshot--2019 06 02-14-58-36](https://user-images.githubusercontent.com/244656/58942501-2ea97f80-877e-11e9-9f94-7d9bf4b69c2a.png)

It would be good to do something similar in our Community version.

This issue involves:

1. make sure that Private repositories are not shown in that list
1. add a paragraph explaining this in the template with a link pointing to readthedocs.com
1. make sure that this message won't appear in our Corporate version

**Comment by Abhi-khandelwal** [comment]
Hi @humitos Can I work on this issue ?

**Comment by dojutsu-user** [comment]
@Abhi-khandelwal Go ahead :tada:

**Comment by Abhi-khandelwal** [comment]
Actually I don't understand that which lists we are talking about ? is it that list when we try to import a project?

**Comment by dojutsu-user** [comment]
@Abhi-khandelwal 
yes..!!

**Comment by humitos** [comment]
@Abhi-khandelwal yes. In my mind, this message should go at the top of this page https://readthedocs.org/dashboard/import/
