### ISSUE TITLE
Rename slug of my project

### ISSUE THREAD

**Issue by vnmabus** [readthedocs/readthedocs.org#5836]
Hello,

Per #5403, it seems I can ask here if I want to rename a slug.

I currently have the page https://fda.readthedocs.io/en/latest/ . However, we changed the name of our project to brand it as a scikit. Would it be possible to have the documentation in https://scikit-fda.readthedocs.io/en/latest/ ?

Ideally I would want that the old page redirects to the new one, in order not to break the Internet.

Thanks in advance

**Comment by ericholscher** [comment]
Sure, we can definitely do that. I will get the redirects setup and deployed next week. 👍

**Comment by vnmabus** [comment]
I am reopening this, at it is still pending.

**Comment by ericholscher** [comment]
Bah, sorry for the delay here, do you still want this done?

**Comment by vnmabus** [comment]
Yes, please.

**Comment by ericholscher** [comment]
Just as a note, this will break all current links to the project. Hopefully in the near future we should be able to support automatic renaming & redirects, but currently it's all manual.

**Comment by ericholscher** [comment]
I can probably set them up in nginx for now, but it might break in the futute

**Comment by vnmabus** [comment]
> Just as a note, this will break all current links to the project. Hopefully in the near future we should be able to support automatic renaming & redirects, but currently it's all manual.

Hum, I though that it was possible to redirect the old url to the new one. I do not want to break existing links 😢.

**Comment by vnmabus** [comment]
Which information is needed?

**Comment by stsewd** [comment]
@vnmabus if you don't have anything like very complex settings in the admin, you can just create a new project with that name and delete the old one. But that wouldn't make a redirect for the other project.

**Comment by vnmabus** [comment]
Yeah, but that is the thing... I do not want to break existing links.

**Comment by humitos** [comment]
If you re-import your project under the new name, you can create an Exact redirect with `$rest` in the _old project_ pointing to the new URL. See https://docs.readthedocs.io/en/stable/user-defined-redirects.html#exact-redirects

**Comment by stsewd** [comment]
@humitos those would only work on 404

**Comment by ericholscher** [comment]
I'm closing this. It's a duplicate of #2267
