### ISSUE TITLE
Refactor view to class based views that use auth mixins

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#5856]
Instead of using one-off and disparate methods for authorization, views should be refactored to use CBV and authentication mixins that already exist, such as `AuthMixin`. This will reduce the number of ways that we're performing authentication and make our authorization more unified.

**Comment by stsewd** [comment]
Only these are left

https://github.com/readthedocs/readthedocs.org/blob/master/readthedocs/profiles/views.py

https://github.com/readthedocs/readthedocs.org/blob/master/readthedocs/gold/views.py

The other ones are public views
