### ISSUE TITLE
Change `rtfd` to `readthedocs` everywhere in the docs

### ISSUE THREAD

**Issue by dojutsu-user** [readthedocs/readthedocs.org#5870]
We have renamed the organisation from `rtfd` to `readthedocs`.
There are many places in our documentation where `rtfd` is present/used.
It would be good change `rtfd` to `readthedocs`.

**Comment by pranay414** [comment]
@dojutsu-user I would like to take this up.

**Comment by dojutsu-user** [comment]
Go ahead. :tada:

**Comment by stsewd** [comment]
Closed by #5871

**Comment by AlainGama** [comment]
Readthedocshttps://github.com/readthedocs/readthedocs.org/issues/5870
