### ISSUE TITLE
Remove django-guardian db

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#5875]
Django guardian was removed #5863, but we still have the tables on the db. Probably we want to do this after the deploy and when we are sure that nothing is broken.

https://django-guardian.readthedocs.io/en/stable/api/guardian.models.html#std:model-UserObjectPermission

**Comment by tapaswenipathak** [comment]
Hello @stsewd, Can I do take this?

**Comment by stsewd** [comment]
Sure! You should run the migrations after #5863 was merged to see what can be removed (or take a look at https://github.com/django-guardian/django-guardian/tree/devel/guardian/migrations), and make a migration removing those models.

**Comment by stsewd** [comment]
So, we have two ways to remove the migration. We actually needed to execute the first one before the deploy :/

The first one removes all the migrations from the db, and the second one is the sql to execute directly on the db (in case we can't do 1).

All this commands should be run from the commit c907f03a9 (just before the one that removes the app)

```
$ dj migrate --fake guardian zero
Operations to perform:
  Unapply all migrations: guardian
Running migrations:
  Rendering model states... DONE
  Unapplying guardian.0001_initial... FAKED
```

```
~/rtd/readthedocs.org on  c907f03a9! ⌚ 1:07:32
$ dj sqlmigrate --backwards guardian 0001_initial
BEGIN;
--
-- Alter unique_together for groupobjectpermission (1 constraint(s))
--
ALTER TABLE "guardian_groupobjectpermission" DROP CONSTRAINT "guardian_groupobjectperm_group_id_permission_id_o_3f189f7c_uniq";
--
-- Alter unique_together for userobjectpermission (1 constraint(s))
--
ALTER TABLE "guardian_userobjectpermission" DROP CONSTRAINT "guardian_userobjectpermi_user_id_permission_id_ob_b0b3d2fc_uniq";
--
-- Create model UserObjectPermission
--
DROP TABLE "guardian_userobjectpermission" CASCADE;
--
-- Create model GroupObjectPermission
--
DROP TABLE "guardian_groupobjectpermission" CASCADE;
COMMIT;
```

**Comment by tapaswenipathak** [comment]
@stsewd Do you wanna let me finish the issue or you wanna take it on your head?

**Comment by stsewd** [comment]
@tapaswenipathak this now needs a design decision. We need to execute the SQL or the command in the production server.

**Comment by ericholscher** [comment]
Ran into an issue running the backwards migration in prod. Going to have to hand-run the SQL.

**Comment by stsewd** [comment]
This was fixed, we executed the drop sql in the db
