### ISSUE TITLE
Build exited due to time out

### ISSUE THREAD

**Issue by BingmingWong** [readthedocs/readthedocs.org#5881]
## Details

* Read the Docs project URL:http://python-online.cn
* Build URL (if applicable):https://readthedocs.org/projects/mings-blog/builds/9326916/
* Read the Docs username (if applicable): WONGBINGMING

## Expected Result

Build completes without error

## Actual Result

Build exited due to time out

**Comment by stsewd** [comment]
Please check https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html, looks like disabling the pdf build can help

**Comment by BingmingWong** [comment]
Thanks, your suggestion is helpful.
