### ISSUE TITLE
Excessive memory consumption due to PyTorch

### ISSUE THREAD

**Issue by gugarosa** [readthedocs/readthedocs.org#5882]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/recogners/
* Build URL (if applicable): https://readthedocs.org/projects/recogners/builds/9327672/
* Read the Docs username (if applicable): gthrosa

## Expected Result

The build should complete itself without any errors.

## Actual Result

The build is not completed due to 'Command killed due to excessive memory consumption' error, probably caused by the size of torch being installed.

The main problem is that to actually build the Recogners docs, I need the package itself (installing it by ```pip install .```). And to have the package itself installed, I need to install the torch dependency. It is basically a cycle that I could not find another way to solve it.

So, I am begging here for a small amount of memory in that project in order to fix the problem. It might not be the ideal way, but is the one that I could think of without reworking any code.

Thank you for your attention and best regards,
Gustavo.

**Comment by stsewd** [comment]
Maybe can you try https://sphinx-autoapi.readthedocs.io/en/latest/? (it doesn't require to install the project to get the docstrings)

**Comment by gugarosa** [comment]
Amazing suggestion @stsewd, thank you so much! I was able to build it and everything worked out perfectly. I will be closing this issue.

Best regards,
Gustavo.
