### ISSUE TITLE
Is it possible use " pip install 3rd Markdown extension ? How ?

### ISSUE THREAD

**Issue by steveyang331** [readthedocs/readthedocs.org#5883]
## Details
Some functions doesn't support by default, such as strikethrough, 3rd theme. 

I need to install 3rd markdown extension. https://facelessuser.github.io/pymdown-extensions/installation/

but doesn't work when set extension to mydoc.yml 

I don't know where , how to use "pip install " command line on xxx.readthedoc.io project. 

## Expected Result

clear tell ppl where , how to use "pip install'' for 3rd markdwon extension. 

## Actual Result

can't find it .

Thanks.

**Comment by stsewd** [comment]
Please see https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

**Comment by steveyang331** [comment]
It's really hard to understand. There's no any step by step document tutorial . I spent 3 hours try to figure it out. but failed. 

Well. I show my every steps, please instruct me where's the wrong.  
OR
Please check my repo  https://github.com/steveyang331/Steve_Yang

Thanks .

**Step 1**
Create **requirements.txt** in  " docs/requirements.txt". 


**Step 2**
Add  MarkdownHighlight in requirements.txt 

https://github.com/ribalba/markdown.highlight

**Step 3**

Create .readthedocs.yml file in " docs/.readthedocs.yml "

https://github.com/steveyang331/Steve_Yang/raw/master/docs/.readthedocs.yml

**Step 4**

Go into " Advanced Settings " for  Requirements file :  docs/requirements.txt

Click " Save " button. 

**Step 5** 
Add 

```
plugins:
    - markdownhighlight
```

to mkdocs.yml

https://github.com/steveyang331/Steve_Yang/blob/master/mkdocs.yml

**Step 6** 

Build .
