### ISSUE TITLE
Error One or more submodule URLs are not valid:

### ISSUE THREAD

**Issue by macagua** [readthedocs/readthedocs.org#5884]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/entrenamiento-frameworks-web-python/
* Build URL (if applicable): https://readthedocs.org/projects/entrenamiento-frameworks-web-python/builds/9329915/
* Read the Docs username (if applicable): macagua

## Expected Result

Given the [.gitmodules](https://github.com/Covantec/entrenamiento.frameworks_web_python/blob/master/.readthedocs.yml#L23) file, the build succeeds.

## Actual Result

> Error
> One or more submodule URLs are not valid: ['recursos/leccion6/flask-crud-app', 'recursos/leccion6/flask-helloworld'].

**Comment by stsewd** [comment]
We don't support ssh urls for submodules yet, https only.

**Comment by macagua** [comment]
@stsewd Fixed with this commit [822277c](https://github.com/Covantec/entrenamiento.frameworks_web_python/commit/822277c5e37bd1639ea7154b2c046169a449a5ca). Thanks you!!!
