### ISSUE TITLE
Can't build with unicode

### ISSUE THREAD

**Issue by Disinterpreter** [readthedocs/readthedocs.org#5887]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/unanimated-rus/
* Build URL (if applicable): https://readthedocs.org/projects/unanimated-rus/builds/9336886/
* Read the Docs username (if applicable): Disinterpreter

## Expected Result

Building OK

## Actual Result

I can't build my document, but a checker was return as okey

**Comment by humitos** [comment]
@Disinterpreter `pdflatex` does not support Unicode. If you want to build your PDF with Unicode characters, you need to use `latex_engine = 'xelatex'` in your `conf.py` file. Let us know if that works.

**Comment by humitos** [comment]
We have a guide in our docs for this: https://docs.readthedocs.io/en/latest/guides/pdf-non-ascii-languages.html

**Comment by Disinterpreter** [comment]
So, I want to fix the problem. But I never configured readthedocs before. Would you suggest where I can configure `conf.py`?

**Comment by stsewd** [comment]
@Desinterpreter that's the sphinx configuration file https://github.com/fansub-collegium/unanimated-rus/blob/master/docs/conf.py.

Looks like you didn't created a sphinx project from the beginning, please check https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html

**Comment by Disinterpreter** [comment]
Well done!
https://readthedocs.org/projects/unanimated-rus/builds/9344169/

**Comment by Disinterpreter** [comment]
Oh! Sorry, I need to open it again.
What's happened with cyrillic symbols?
https://buildmedia.readthedocs.org/media/pdf/unanimated-rus/latest/unanimated-rus.pdf

**Comment by humitos** [comment]
@Disinterpreter you need to specify a different font probably for that. This is not a problem of Read the Docs actually, but how the LaTeX process is configured.

You will need to read more about `latex_elements` and how to customize it in Sphinx. Here you have a guide for that: https://www.sphinx-doc.org/en/master/latex.html

**Comment by Disinterpreter** [comment]
Okay! I'll do it on few next days. Set up a `more information` label.
