### ISSUE TITLE
SocialApp matching query does not exist.

### ISSUE THREAD

**Issue by mzch** [readthedocs/readthedocs.org#5888]
## Details

* Read the Docs project URL: 
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result
I installed Read The Docs locally but something wrong. What is wrong? Please advise me.

*A description of what you wanted to happen*
Can login Read The Docs instance via Github, GItlab or Bitbucket
## Actual Result
Error 'DoesNotExist at /accounts/github/login/'
*A description of what actually happened*
# DoesNotExist at /accounts/github/login/
#### SocialApp matching query does not exist.
Title|Details
-- | --
Request Method: | GET
Request URL:|https://www.docfesta.com/accounts/github/login/?process=login
Django Version:|1.11.22
Exception Type:|DoesNotExist
Exception Value:|SocialApp matching query does not exist.
Exception Location:|/srv/readthedocs/.pyenv/versions/3.6.8/lib/python3.6/site-packages/django/db/models/query.py in get, line 380
Python Executable:|/usr/bin/python3
Python Version:|3.6.8
Python Path:|['/srv/readthedocs/.pyenv/versions/3.6.8/lib/python3.6/site-packages/git/ext/gitdb',  '/srv/readthedocs/.pyenv/versions/3.6.8/lib/python36.zip',  '/srv/readthedocs/.pyenv/versions/3.6.8/lib/python3.6',  '/srv/readthedocs/.pyenv/versions/3.6.8/lib/python3.6/lib-dynload',  '/srv/readthedocs/.pyenv/versions/3.6.8/lib/python3.6/site-packages',  '/srv/readthedocs',  '/srv/readthedocs/.pyenv/versions/3.6.8/lib/python3.6/site-packages/gitdb/ext/smmap',  '/srv/readthedocs']
Server time:|月, 8 7月 2019 05:06:13 +0000

**Comment by dojutsu-user** [comment]
Hi @mzch 
Please see issue #2243

**Comment by mzch** [comment]
Very good. Why don't you add these steps in your document?

**Comment by stsewd** [comment]
@mzch feel free to add those steps to the docs, the custom installation steps aren't covered by the rtd team, but the community

**Comment by tapaswenipathak** [comment]
Hi @stsewd: Adding.
