### ISSUE TITLE
Redirects on subprojects do not work

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#5889]
Due to the way we get the `project.slug` from the `request` object (set by the `SubdomainMiddleware`), redirects instances for subprojects are never catched.

At this point,

https://github.com/readthedocs/readthedocs.org/blob/c91b332695eee93e32f86f9a18bce64f04480c1a/readthedocs/redirects/utils.py#L86-L88

`project` is the superproject instead of the subproject, and all the redirect instanced defined in the subproject are completely omited.

This is strongly related to #5557. We need to refactor the middleware and set the `subproject.slug` into the `request` object to make these things to work properly.

**Comment by Abhi-khandelwal** [comment]
Hi @humitos,  Can I work on this issue ?

**Comment by stsewd** [comment]
@Abhi-khandelwal sure

**Comment by Abhi-khandelwal** [comment]
@humitos  Can you help me with refactoring in the middleware ?

**Comment by stsewd** [comment]
Looks like the linked code is prior to proxito, we now catch the redirects from the subproject, but not as users would expect, tracking that problem in https://github.com/readthedocs/readthedocs.org/issues/10049.
