### ISSUE TITLE
Upgrade Sentry SDK for better Django integration

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#5890]
Sentry shows this note:

![Screenshot_2019-07-08_11-49-38](https://user-images.githubusercontent.com/244656/60801054-90427c80-a176-11e9-8e3e-eb5dd3e85702.png)

From what I can read in the docs at first sight, it may need some changes in our configuration to allow this integration.

* https://docs.sentry.io/platforms/python/django/
* https://docs.sentry.io/platforms/python/

**Comment by pranay414** [comment]
@humitos I'll would like to work on this. Please assign me.

**Comment by davidfischer** [comment]
@pranay414 I don't know if this is a good issue since the actual sentry integration is in our private operations repository.

Separately, there are a number of improvements in the newer SDK that I'm interested in.

**Comment by humitos** [comment]
Closing it from here since it's an -ops task and does not belong to this repo. I opened a PR where it belongs and we will be tracking it there.
