### ISSUE TITLE
New Submodule added to autosummary not showing up in latest build

### ISSUE THREAD

**Issue by Abby3017** [readthedocs/readthedocs.org#5906]
## Details

* [Project URL](https://projectqabby.readthedocs.io/en/latest/projectq.setups.decompositions.html)
* [Build URL](https://readthedocs.org/projects/projectqabby/builds/9229385/)
* Read the Docs username (if applicable): Abby3017

I was building the docs for following [project](https://github.com/Abby3017/ProjectQ/). I have added in new submodule in [given file](https://github.com/Abby3017/ProjectQ/blob/develop/docs/projectq.setups.decompositions.rst). The new submodule is reflected in sphinx build on local but when I try to build on readthedocs [following submodule](https://github.com/Abby3017/ProjectQ/blob/develop/docs/projectq.setups.decompositions.rst#projectqsetupsdecompositionsphaseestimation-module) is missing.

I have read [issues](https://github.com/readthedocs/readthedocs.org/issues?utf8=%E2%9C%93&q=autosummary) regarding autosummary file not included. But still can't figure out the problem.  
Any help will be appreciated. Thanks

**Comment by stsewd** [comment]
The latest build was on june 17th, with commit `62ecf4dcf`
https://readthedocs.org/projects/projectqabby/builds/9229404/

Looks like the webhook isn't configured, please check the webhooks under the repo, This can help to locate the webhooks on rtd https://docs.readthedocs.io/en/stable/webhooks.html

Anyway, I triggered a build for the latest commit https://readthedocs.org/projects/projectqabby/builds/9354819/

And there is another error

**Comment by stsewd** [comment]
https://github.com/Abby3017/ProjectQ/blob/655bc8dfb9853a5abf5b2c42b1ed07d7d5b4530c/docs/conf.py#L384

```
    obj = eval(info['module'] + '.' + info['fullname'])
  File "<string>", line 1
    .
    ^
SyntaxError: unexpected EOF while parsing
```

You can see the full log in https://readthedocs.org/projects/projectqabby/builds/9354819/

**Comment by Abby3017** [comment]
Thanks for your reply.
This error you mentioned, in [sphinx-documentation](http://www.sphinx-doc.org/en/master/usage/extensions/linkcode.html), if the domain is 'py', the info dictionary is guaranteed to contain both 'module' and 'fullname' keys. This shouldn't come, I will check about this.

But the build that [succeeded](https://readthedocs.org/projects/projectqabby/builds/9229385/), its not showing up the updated submodule.

**Comment by stsewd** [comment]
Also, the build is being triggered for the master branch, not develop. You should activate the `develop` version under the `Versions` tab of your rtd project.
