### ISSUE TITLE
View Docs Link Stuck at Localhost

### ISSUE THREAD

**Issue by kb1lqc** [readthedocs/readthedocs.org#5907]
## Details
I've installed the latest build of Read the Docs using the developer installation method and the documents are building. However, I am starting the server with 0.0.0.0:8000 and can view the website and kickoff the builds with the IP/HOSTNAME:8000 from a remote computer on my intranet. I have changed the `local_settings.py` to the following

```
PRODUCTION_DOMAIN:"http://<hostname>:8000"
PUBLIC_DOMAIN_USES_HTTPS = True
USE_SUBDOMAIN: True
SLUMBER_API_HOST = 'http://<hostname>:8000'
PUBLIC_API_URL = 'http://<hostname>:8000'
MEDIA_URL = 'http://<hostname>:80/media/'
```
The documentation for RTD doesn't talk about how to get the view link on the documentation versions to be correctly configured. For this test I built the latest RTD documentation. which passed.

![image](https://user-images.githubusercontent.com/331540/61021490-8e371400-a356-11e9-9873-0c4d756b498c.png)

* Read the Docs project URL: None
* Build URL (if applicable): None
* Read the Docs username (if applicable):

## Expected Result

I expected to be redirected to the HTML documentation with a URL starting with http://<hostname>:8000

## Actual Result

Link clearly shows `http://localhost:8000` which obviously doesn't work when on a remote computer
![image](https://user-images.githubusercontent.com/331540/61021303-c9851300-a355-11e9-942d-82807bdfe1b9.png)

**Comment by stsewd** [comment]
You are missing the public domain setting https://docs.readthedocs.io/en/stable/development/settings.html#public-domain

Also, we don't offer support for custom installations, please see https://docs.readthedocs.io/en/stable/support.html and https://docs.readthedocs.io/en/stable/open-source-philosophy.html

**Comment by stsewd** [comment]
Also, you can take a look to all the settings in https://github.com/readthedocs/readthedocs.org/blob/master/readthedocs/settings/base.py

**Comment by stsewd** [comment]
Closing as this is a because a missing setting, not a read the docs bug.

Also, please feel free to update the custom installation guide https://docs.readthedocs.io/en/stable/custom_installs/index.html

**Comment by kb1lqc** [comment]
@stsewd Happy to update docs when I know I have really figured it out. I changed PUBLIC_DOMAIN but the Read the Docsbuild I mentioned in my initial comments still shows localhost. Do I really need DNS settings as well external to this computer? I didn't think so. This strikes me as the link not being updated right. I did notice that building `pip` documentation actually points to the correct link. Maybe this is specific to Read the Docs stuff?

**Comment by stsewd** [comment]
I think you are not using subdomains (or you don't need to). Try `USE_SUBDOMAIN = False`. Setting `PUBLIC_DOMAIN` to the same in `PRODUCTION_DOMAIN` works for me locally.

**Comment by stsewd** [comment]
@kb1lqc hi, were you able to test the above setting?

**Comment by mudislandkid** [comment]
Hi There,

I've recently installed RTD on a local installation for the first time. After much playing about I managed to get the 'view documents' button to point to my local ip by going into the project settings/domians and adding my local ip:8000 to it. If I just do that, nothing happens. If I check the box to say 'This Domain is the primary one where the documentation is served from' then when I click 'View Documents' it takes me to a url of 192.x.x.x:8000/en/latest which gives a 404 error. It should point to 192.x.x.x:8000/docs/{project name}/en/latest. How do I get it to do this? I've followed all the steps mentioned above. My Public_Domain and Production_domain are set to: http://192.x.x.x (in the settings/base.py) as I do not have a local_settings.py file.

Any suggestions as to what I'm missing. It's really frustrating as I'm within touching distance of it all working so well!

Thanks in advance for any help/suggestions.

**Comment by stsewd** [comment]
@mudislandkid  I think you have `USE_SUBDOMAIN = True`

**Comment by mudislandkid** [comment]
@stsewd thanks for the suggestion, I've just double checked and no it is set to False. This is what I have: -

`    # Domains and URLs
    PRODUCTION_DOMAIN = '192.168.0.22'
    PUBLIC_DOMAIN = '192.168.0.22'
    PUBLIC_DOMAIN_USES_HTTPS = False
    USE_SUBDOMAIN = False
    PUBLIC_API_URL = 'http://{}'.format(PRODUCTION_DOMAIN)

    # Doc Builder Backends
    MKDOCS_BACKEND = 'readthedocs.doc_builder.backends.mkdocs'
    SPHINX_BACKEND = 'readthedocs.doc_builder.backends.sphinx'

    # slumber settings
    SLUMBER_API_HOST = 'https://readthedocs.org'
    SLUMBER_USERNAME = None
    SLUMBER_PASSWORD = None`

In the Domain settings within the web gui of the project I have set the domain to: http://192.168.0.22:8000

I thought maybe if I try setting it to http://192.168.0.22:8000/docs/{project name}/ that might solve it but it won't let me enter anything after the :8000/ as when I do it gives an error when I click save saying I cannot leave this field blank.

Any other suggestions?

Thanks again for your time.

**Comment by son1999hy** [comment]
I have successfully installed an instance of Read-the-Docs locally and integrated with the public instance of Github.

I have successfully imported and built three projects (even a private one after some minor code alterations, though it is not normally supported). One of these projects is the default template project that RTD suggests for testing.

I can view the docs in the machine where the RTD instance is installed. However, when I press the green "View Docs" button a 404 status code occurs. Supposedly, the docs should be under /docs/project/en/latest. As yo
![TlmLy](https://user-images.githubusercontent.com/46740820/104552690-d467e480-566b-11eb-8750-78ddc8330817.png)

u can see there is no docs prefix in the available URLs

My assumption was that the endpoints regarding the docs are updated dynamically and the Django application reloads, yet I have been searching the code and I have not found anything to support this assumption.

**Comment by ddquk** [comment]
> I have successfully installed an instance of Read-the-Docs locally and integrated with the public instance of Github.
> 
> I have successfully imported and built three projects (even a private one after some minor code alterations, though it is not normally supported). One of these projects is the default template project that RTD suggests for testing.
> 
> I can view the docs in the machine where the RTD instance is installed. However, when I press the green "View Docs" button a 404 status code occurs. Supposedly, the docs should be under /docs/project/en/latest. As yo
> ![TlmLy](https://user-images.githubusercontent.com/46740820/104552690-d467e480-566b-11eb-8750-78ddc8330817.png)
> 
> u can see there is no docs prefix in the available URLs
> 
> My assumption was that the endpoints regarding the docs are updated dynamically and the Django application reloads, yet I have been searching the code and I have not found anything to support this assumption.

I had the same problem,Have you solved it?
