### ISSUE TITLE
Tip message for config file when already using it

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#5909]
When the build fails, we are showing a message saying that using a `.readthedocs.yml` is the recommended way, even if the user is already using our config file.

![Screenshot_2019-07-11_10-48-08](https://user-images.githubusercontent.com/244656/61036444-6b921300-a3c9-11e9-8a6c-c99ab1821d98.png)

**Comment by stsewd** [comment]
Hmm, I think this is a bug, because the build didn't reach the save config step, the config is empty. So rtd thinks it doesn't have a configuration file. Not sure how we can fix this, maybe only show the tip if the build success?

**Comment by humitos** [comment]
Can we save the `config` into the Build after parsing it but before validating it?

**Comment by Urth** [comment]
Also note that the tip recommends `.readthedocs.yml` which is the deprecated form, it should read `.readthedocs.yaml` instead as noted in https://docs.readthedocs.io/en/stable/config-file/v2.html
```Read the Docs supports configuring your documentation builds with a YAML file. The configuration file must be in the root directory of your project and be named .readthedocs.yaml.```

**Comment by agjohnson** [comment]
I'd like to move this logic out of templates entirely, it's hard to keep in sync with what we do at the model or build process level. We have recently discussed wanting more suggestions -- ie "Pin docutils!" -- and it would help to have a generic way to pass a suggestion or list of suggestions to the templates for display manipulation.

Perhaps similar to https://github.com/readthedocs/readthedocs.org/issues/3399 it would be fan-fucking-tastic if the build process was able to emit warnings/suggestions as we come across each during the build process. This does complicate modeling around errors/warnings on builds though, so might be a long term goal.

An fine middle step between these two is to simply do this at the build detail view level. That is, iterate over all of the suggestions we might emit and evaluate whether the suggestion is valid for a build, adding valid suggestion(s) to the template context. This way we can keep the conditional logic maintained closer to application code, and still abstract the concept of suggestions away from template display.

This is a good backend change that someone could take on to help with new templates beta.

**Comment by humitos** [comment]
I read this issue and I'm taking into consideration what we have discussed here. I'm preparing a document with my thoughts that we can polish together once I push it.

In general, we will be able to create (error, warning, tip) notifications _from inside the build process_ and they will be attached to the `Build` object itself. After that, the front end will decide how/where to show them.
