### ISSUE TITLE
how stop a build triggered from long time ago with finish

### ISSUE THREAD

**Issue by macagua** [readthedocs/readthedocs.org#592]
Hi guys 

how stop a build triggered from long time ago without finish?

The docs is tested with travis-ci and the build is ok [0] but in readthedocs are many build triggered from long time ago without finish [1].

Any idea???

[0] https://travis-ci.org/collective/collective.spanishdocumentation/builds/15804944
[1] https://readthedocs.org/builds/plone-spanish-docs/

**Comment by linuxoid69** [comment]
I have the same problem. But I have not solved it (((
