### ISSUE TITLE
Disable shallow clone for opmuse

### ISSUE THREAD

**Issue by inty** [readthedocs/readthedocs.org#5922]
As per https://github.com/readthedocs/readthedocs.org/issues/5031 I'd like to disable shallow cloning for https://readthedocs.org/projects/opmuse/

Thanks!

**Comment by tapaswenipathak** [comment]
Hello @inty, @dojutsu-user, Doing.

**Comment by saadmk11** [comment]
hi @tapaswenipathak, Thank you for your interest but this is a support ticket. You can checkout [Good First Issues](https://github.com/readthedocs/readthedocs.org/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%22) to get started.

**Comment by tapaswenipathak** [comment]
Hello, I am doing tickets which interests me; @saadmk11 can I work on this?

**Comment by saadmk11** [comment]
I'm sorry but this issue is only actionable by the core team. :)

**Comment by stsewd** [comment]
@tapaswenipathak this can only be done from the admin panel of the project in production.

**Comment by stsewd** [comment]
@inty done, let us know if there is any problem. Please try first wiping before triggering a new build https://docs.readthedocs.io/en/stable/guides/wipe-environment.html

**Comment by inty** [comment]
@stsewd Works perfectly! Thank you very much.

**Comment by tapaswenipathak** [comment]
sure, thanks for letting me know folks.
