### ISSUE TITLE
readthedocs.yaml for sphinxcontrib-proof

### ISSUE THREAD

**Issue by cmhughes** [readthedocs/readthedocs.org#5923]
## Details

* Read the Docs project URL: https://github.com/cmhughes/latexindent.pl
* Build URL (if applicable): https://readthedocs.org/projects/latexindentpl/builds/
* Read the Docs username (if applicable): cmhughes

## Expected Result

I'm using a custom [`readthedocs.yaml`](https://github.com/cmhughes/latexindent.pl/blob/master/readthedocs.yaml) which I would like to install `sphinxcontrib-proof` using
```
pip install sphinxcontrib-proof
```

## Actual Result

As you'll see in the [builds](https://readthedocs.org/projects/latexindentpl/builds/) link above, I get the error:
```
Extension error:
Could not import extension sphinxcontrib.proof (exception: No module named 'sphinxcontrib.proof')
```

I wondered if you could help me with this? Thanks so much!

**Comment by humitos** [comment]
Use missed the `version: 2` setting in the YAML file. That's why.

Try that and report back. If the problem persists, feel free to reopen the issue. Thanks!

**Comment by cmhughes** [comment]
Thanks for this. I've added version: 2 and now receive:

```
/envs/latest/bin/python -m pip install --upgrade --upgrade-strategy eager --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/latexindentpl/.cache/pip .[sphinxcontrib-proof]
ERROR: Directory '.[sphinxcontrib-proof]' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
```

Any guidance would be gratefully received.

**Comment by humitos** [comment]
@cmhughes great!

You need a `requirements.txt` file. Take a look at https://docs.readthedocs.io/en/latest/guides/specifying-dependencies.html

You don't have to use `extra_requirements` in the YAML file.

**Comment by cmhughes** [comment]
Many thanks, I've resolved this now. 

For reference, I used

readthedocs.yaml
=
```
version: 2

build:
  image: latest

sphinx:
  configuration: documentation/conf.py

python:
  version: 3.6
  install:
    - requirements: documentation/requirements.txt
```
with

documentation/requirements.txt
-
```
sphinxcontrib-proof
```
