### ISSUE TITLE
Build error with build id #10

### ISSUE THREAD

**Issue by abbas2008** [readthedocs/readthedocs.org#5925]
## Details:

* Project URL: https://readthedocs.org/projects/lattindoc/
* Build URL(if applicable): https://readthedocs.org/projects/lattindoc/builds/10/
* Read the Docs username(if applicable): admin

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by saadmk11** [comment]
You should add what kind of errors your are getting so that we can help you :)

**Comment by dojutsu-user** [comment]
@abbas2008 
It would be very helpful if you could correct the `links`.
Currently, both of the links points to 404 pages.

**Comment by agjohnson** [comment]
Closing, there is not enough information to troubleshoot.
