### ISSUE TITLE
Fix the count of total projects shown on the homepage

### ISSUE THREAD

**Issue by dojutsu-user** [readthedocs/readthedocs.org#5927]
On the hompage (https://readthedocs.org/), we show the total count of the projects.

![Screenshot from 2019-07-15 14-23-42](https://user-images.githubusercontent.com/29149191/61207904-d6b64f00-a713-11e9-9388-8d7222a2a4d7.png)

This number also includes projects that are identified as spam.
It would be good if we exclude spam projects from it.

**Comment by Iamshankhadeep** [comment]
Can I work on it?

**Comment by saadmk11** [comment]
@Iamshankhadeep Go Ahead! :+1:

**Comment by Iamshankhadeep** [comment]
@saadmk11 can you guide me from where can I start?

**Comment by saadmk11** [comment]
You can start from here and update the `project_count` queryset.
https://github.com/readthedocs/readthedocs.org/blob/e12f70dbc733389a62b08d7744062ebbe58ce6e6/readthedocs/core/views/__init__.py#L37-L46

**Comment by Iamshankhadeep** [comment]
@saadmk11 can you please point out where is the `count()` function which is needed for `project_count` querry set?

**Comment by Abhi-khandelwal** [comment]
@Iamshankhadeep Can I work on this issue ?

**Comment by dojutsu-user** [comment]
@Iamshankhadeep 
You need to add a filter here -- https://github.com/readthedocs/readthedocs.org/blob/7be01d844b981635822d4df73f614ad2c3d71b8b/readthedocs/core/views/__init__.py#L45

@Iamshankhadeep @Abhi-khandelwal 
Any one can submit a PR. :smile:
