### ISSUE TITLE
Projects seem to break when git modules paths change

### ISSUE THREAD

**Issue by BlackLight** [readthedocs/readthedocs.org#5928]
## Details

* Read the Docs project URL: https://platypush.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/platypush/builds/9372854/

## Expected Result

When the path of a git module changes I'd expect the background logic to do the proper sync operations (change `.gitmodules`, prune the previous module, `git submodule sync`, `git submodule update`) and seamlessly migrate to the new path.

## Actual Result

RTD seems to try to clone the submodule into the existing folder without cleaning it up first, ending up with an error like:

```
One or more submodule URLs are not valid: ['platypush/backend/http/static/flag-icons']
```

**Comment by saadmk11** [comment]
> We don't support ssh urls for submodules yet, https only.

please see this : https://github.com/readthedocs/readthedocs.org/issues/5884

**Comment by stsewd** [comment]
The error is because your `.gitmodules` file has a ssh url https://github.com/BlackLight/platypush/blob/f5ef9957de405278995002e3031c7ed6ec4d5842/.gitmodules#L9

We only support http urls at the moment (looks like we should improve the msg error)

**Comment by BlackLight** [comment]
Thanks for the feedback, changing the submodule URL to https fixed it. I see two issues then:

- [Bug/unclear error] Would it be possible to fix the error with something that states "git/ssh URL schemas for submodules are not supported" instead of "One or more submodule URLs are not valid"?

- [Enhancement] Would it be possible to support git/ssh schemas for submodules as well? Not all the git repos out there are on GitHub, not all of them are served over https, and accepting only https prevents projects using those submodules from generating their docs.

**Comment by stsewd** [comment]
Thanks for the suggestions. The main restriction is because we don't support private repositories in our community site. There are some ideas in how to support public repositories with `ssh` schema in https://github.com/readthedocs/readthedocs.org/issues/4043

I'm opening a new issue to improve the error message
