### ISSUE TITLE
Remove usage of six

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#5929]
Read the Docs runs with python 3.6 only, and we don't declare the six package as a dependency (guess it's a dependency of another package)

https://github.com/readthedocs/readthedocs.org/blob/e12f70dbc733389a62b08d7744062ebbe58ce6e6/readthedocs/projects/models.py#L1479-L1479

You can check the correct replace in https://six.readthedocs.io/

**Comment by Abhi-khandelwal** [comment]
Hello @stsewd Can I work on this issue?

**Comment by dojutsu-user** [comment]
@Abhi-khandelwal 
Go for it. :tada: :smile:

**Comment by Abhi-khandelwal** [comment]
@dojutsu-user , Actually I got some doubt , Do I have to change `shlex_quote` to `shlex.quote` ?
