### ISSUE TITLE
Add Python examples for API v3 documentation

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#5935]
We already have cURL request examples for APIv3 docs at https://docs.readthedocs.io/en/latest/api/v3.html#get--api-v3-projects-

It would be awesome to have use `sphinx-tabs` to have multiple tabs. One with the cURL example we already have there and another Python tab with the same request using Python code with [Slumber](https://slumber.readthedocs.io/en/v0.6.0/)

If Slumber is not good enough for this, we can use just `requests` as the example from here https://docs.readthedocs.io/en/latest/guides/environment-variables.html

Ref: https://github.com/readthedocs/readthedocs.org/pull/5895#discussion_r303602609

**Comment by tapaswenipathak** [comment]
Hi @humitos: Is the ticket open? Can I add a PR?

**Comment by humitos** [comment]
@tapaswenipathak yes, sure!

**Comment by dibyaaaaax** [comment]
hey @humitos, can I work on this?

**Comment by humitos** [comment]
@dibyaaaaax sure! go ahead :)

**Comment by humitos** [comment]
This is already done in the linked and merged PR.
