### ISSUE TITLE
Search results missing context

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#5964]
I got a search result for "environment variables" on our docs that got a hit, but gave back blank results:

![image](https://user-images.githubusercontent.com/1140183/61567136-b0f2b800-aa3b-11e9-932e-6a190e0e88f1.png)

There should probably be something matching in the results to match the output of the other results. I'm assuming this was a heading match and we're displaying that differently?

**Comment by dojutsu-user** [comment]
@agjohnson 
I am guessing that this is default sphinx search results, For some reason -- RTD search failed or there is some caching/network issue.
Did you search on the docs locally? If yes, then there might be two reasons:
- Elasticsearch was not running
- Docs are not properly indexed
- If elasticsearch was running and docs are indexed properly, it might happen that url was using `localhost` and not `127.0.0.1`, elasticsearch doesn't allow requests from `localhost`. 

I am getting the correct results in our current docs -- https://docs.readthedocs.io/en/latest/index.html?rtd_search=environment%20variables
Can you test it once again?

**Comment by agjohnson** [comment]
No, this was prod docs, and was not Sphinx results. I'm getting results on our docs now for the search query, things look more correct.

My guess now is that this was stale javascript and our search page breaks with this. I won't rehash the need for versioning our static assets here, we've discussed this at length elsewhere.

We can probably close this, but should monitor the issue. If it was not stale JS, it might be an intermittent issue.
