### ISSUE TITLE
Support searching with facets.

### ISSUE THREAD

**Issue by dojutsu-user** [readthedocs/readthedocs.org#5966]
Search facets will be useful in many ways.
They can be used to target the search inside a subproject.
For example: Celery has a subproject Kombu, so we can search in Celery docs, we can search inside Kombu docs, like: `subproject: kombu serializers`

**Comment by stsewd** [comment]
Other type of facets/filters we could support 

- `:dir:dev/` to search only on the `dev/` directory
- `:project:subproject-alias` to search on the main project or a subproject

**Comment by stsewd** [comment]
We already support this syntax, the only thing missing is searching by sub-directories. I'll create a different issue for that.
