### ISSUE TITLE
Mkdocs build passing but 404 when visiting the documentation webpage

### ISSUE THREAD

**Issue by JavierLuna** [readthedocs/readthedocs.org#5972]
## Details
Tried building my project with mkdocs, starting with a simple `index.md` to check readthedocs integration. Build passes but when I try visit the documentation webpage, a 404 is returned.
Weird thing is I did the same steps with another repo from the ground up as a test and everything worked. These are the steps I performed in both scenarios:

1. Create Github repo (in my `datastorm` project I've used the one existing)
2. Clone it in local
3. Create python3 virtual environment.
4. `pip install mkdocs`
5. `mkdocs new .` (inside my repo).
6. Edit mkdocs.yml to include:
```
site_name: Datastorm
pages:
    - Index: index.md
```
7. Git add, commit, push
8. Import repository in readthedocs. Type: Git, Check advanced configuration.
9. In Admin -> Advanced settings:
```
Default version: latest
Default branch: master
Privacy level: Public
... (default in both cases)
Python interpreter: CPython 2.X (As 3.X doesn't get along with mkdocs)
Uncheck pdf and epub builds
Click Save
```
10. Build version "latest"
11. Build passes!
12. View docs
13. 404 :( 

(Strange thing is I did the exact same steps (even wrote them down) for the new repo I created and It showed the documentation without problems)

* Read the Docs project URL: [datastorm.readthedocs.io](https://datastorm.readthedocs.io)
* Build URL (if applicable): [https://readthedocs.org/api/v2/build/9402042.txt](https://readthedocs.org/api/v2/build/9402042.txt)
* Read the Docs username (if applicable): jluna

**EDIT**: Added requested information:
* Minimal repo with the same configuration which works fine: [https://github.com/JavierLuna/docstest](https://github.com/JavierLuna/docstest)
* Last build for that minimal repo: [https://readthedocs.org/api/v2/build/9407967.txt](https://readthedocs.org/api/v2/build/9407967.txt)

## Expected Result

Index showing up.

## Actual Result

Not found error.

Thank you very very much

**Comment by stsewd** [comment]
There is a warning in the build

> WARNING -  Config value: 'pages'. Warning: The 'pages' configuration option has been deprecated and will be removed in a future release of MkDocs. Use 'nav' instead. 

>  Weird thing is I did the same steps with another repo from the ground up as a test and everything worked. These are the steps I performed in both scenarios:

Please provide the url for the other project too.

Also, you should use a configuration file, to be more explicit in how your project is built on read the docs https://docs.readthedocs.io/en/stable/config-file/index.html

**Comment by JavierLuna** [comment]
* Minimal repo with the same configuration which works fine: [https://github.com/JavierLuna/docstest](https://github.com/JavierLuna/docstest)
* Last build for that minimal repo: [https://readthedocs.org/api/v2/build/9407967.txt](https://readthedocs.org/api/v2/build/9407967.txt)
* Webpage of that minimal repo: https://docstest-jluna.readthedocs.io/en/latest/

Tried changing 'pages' to 'nav', passing but still no webpage showing (https://readthedocs.org/api/v2/build/9407991.txt)

I'll try setting up the configuration file, will report with results.

**Comment by JavierLuna** [comment]
Tried setting up the `.readthedocs.yml` but the same result, build passes but no webpage.

* Last build with `.readthedocs.yml`: https://readthedocs.org/api/v2/build/9408030.txt
* `.readthedocs.yml`: https://github.com/JavierLuna/datastorm/blob/docs/.readthedocs.yml

**Comment by JavierLuna** [comment]
Okay, I've literally copied and pasted the `mkdocs.yml` and the `docs` folder into a new repo, set the configuration the same as I've stated in this ticket and it works.

Webpage: https://datastorm-docs.readthedocs.io/en/latest/
Build: https://readthedocs.org/api/v2/build/9414363.txt
Repo: https://github.com/JavierLuna/datastorm-docs

**Comment by stsewd** [comment]
@JavierLuna sorry for the confusion. Somehow the `datastorm` directory was created with root as owner, so the webs couldn't write the generated html files. I have fixed this from the server side.

I triggered a new build https://readthedocs.org/projects/datastorm/builds/9419027/ and the docs are visible https://datastorm.readthedocs.io/en/latest/

Let me know if you still have any other problems.
