### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by sergeylukin** [readthedocs/readthedocs.org#5978]
## Details

* Read the Docs project URL: https://toolz.readthedocs.io/

## Expected Result
Search should show a list of matching doc chunks

## Actual Result
A search page shows, but no search result is displayed

**Comment by dojutsu-user** [comment]
Hi @sergeylukin 
Thanks for bringing this issue to our notice.
There's some error with JavaScript.
I will open a PR with the fix.

**Comment by dojutsu-user** [comment]
Hi @sergeylukin 
Fix has been deployed in the production and the search is working again.
https://toolz.readthedocs.io/en/latest/search.html?q=python&check_keywords=yes&area=default

Thanks for your patience.
