### ISSUE TITLE
Disable shallow clone for pytest-httpserver

### ISSUE THREAD

**Issue by csernazs** [readthedocs/readthedocs.org#5988]
As per #5031 I'd like to disable shallow cloning for https://readthedocs.org/projects/pytest-httpserver/

It is using reno to manage release notes and I think it is failing because only the last 50 commits are pulled.

Thank you,
Zsolt

**Comment by stsewd** [comment]
Done, let us know if there is any problem

**Comment by csernazs** [comment]
Thanks! That was quick.
I had to wipe the environment to re-trigger the clone command, after that it works fine.
