### ISSUE TITLE
New branch w/commit doesn't appear until a push to master

### ISSUE THREAD

**Issue by reece** [readthedocs/readthedocs.org#5990]
## Details

* Read the Docs project URL: bioutils.readthedocs.io
* Build URL (if applicable):
* Read the Docs username (if applicable): reece

## Expected Result

When a new branch is created during a push *with a commit on the branch*, the branch should appear soon after and without an additional trigger under the versions tab.

I do NOT expect that empty new branches should appear (although that would be nice). I also do NOT want the new branch to build automatically.

## Actual Result

A new branch is listed only after a push to the master branch. Pushing to other active branches might also work, but I didn't test.

## Log / How to reproduce

Goal: Merge a commit in a fork into a new branch on the primary repo.

```
$ git checkout master
$ git checkout -b 22-documentation
$ git pull trentwatt   # git remote for fork
$ git merge trentwatt/master
$ git log --graph --decorate --pretty=oneline --abbrev-commit --all
*   0ebdb2c (HEAD -> 22-documentation, origin/22-documentation) Merge remote-tracking branch 'trentwatt/master' into 22-documentation
|\  
| * 6365806 (trentwatt/master) Expanded and reformatted for Sphinx the docstrings in normalize.py
* | d432af2 (origin/master, origin/HEAD, master) execute deploy stage only if tagged
* | 8f9087b (tag: 0.5.0) remove pytest installation from .travis.yml
* | 8c8f91a removed pip install from tox in favor of deps
$ git push
```

I confirmed that the push succeeded at github. I also confirmed that the webhook delivery succeeded on github, and that it was received by RTD. RTD shows this response (51edd122-ae79-11e9-8064-7ea42041c345):

```
{
  "build_triggered": false,
  "project": "bioutils",
  "versions": []
}
```

After 15 minutes, the branch still didn't appear on RTD. Then:

```
$ git co master
$ echo >>README.rst 
$ git com -am "tickled README to trigger RTD branch update"
$ git push
```

The 22-documentation branch appeared nearly immediately (<10 seconds after push).

I conclude that a commit on a new branch is insufficient to trigger RTD to update the branch list, and that a commit to master (or perhaps any active branch) is the essential trigger.

Does `"build_triggered": false` imply that the branch list is not updated?

## Relevant issues and links

* #337 
* #2163
* #5438. And [this comment](https://github.com/readthedocs/readthedocs.org/issues/5438#issuecomment-472113761) from @stsewd implies to me that branches should appear immediately. 
* [Update list of branch on readthedocs](https://stackoverflow.com/questions/50885887/update-list-of-branch-on-readthedocs)

None of these issues/links resolve the above problem.

**Comment by stsewd** [comment]
Is your webhook setup to listen to these events?

> Branch or tag creation, Branch or tag deletion and Pushes events

https://docs.readthedocs.io/en/stable/webhooks.html#github

**Comment by stsewd** [comment]
> Does "build_triggered": false imply that the branch list is not updated?

No, but if the versions were synced, the response should contain  `"versions": [master]` (or something not empty)

**Comment by reece** [comment]
@stsewd: I had not customized the push events. I did that, then repeated the reproduction steps and verified that the new branch showed up immediately. Issue solved. Thanks! Closing issue.

**Comment by jpchen** [comment]
same problem, i pushed a branch and i can see the success response from the webhook but the branch doesnt show up. FWIW i have a triggered build for a different branch thats just hanging, though that shouldn't be related?

**Comment by stsewd** [comment]
@jpchen we are having problems with the servers just now.
