### ISSUE TITLE
request for re-enabling jsk-doc

### ISSUE THREAD

**Issue by k-okada** [readthedocs/readthedocs.org#5991]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/jsk-docs/
* Build URL (if applicable):
* Read the Docs username (if applicable): kei_oakda

## Expected Result

due to our wrong settings, the jsk_docs project has been disabled. As suggested in https://github.com/jsk-ros-pkg/jsk_docs/issues/25,  i just have fixed the project doc/conf.py settings, so could you re-enable the projects? thanks in advance.

## Actual Result

https://readthedocs.org/projects/jsk-docs/ has been disabled.

**Comment by humitos** [comment]
@k-okada great! Did you disable the build to be triggered every 10 minutes?

**Comment by k-okada** [comment]
sure, I think I have removed these codes
https://github.com/jsk-ros-pkg/jsk_docs/commit/cb9ea3e1d6061207dea6847f9f1afbb8729fddf1#diff-684a0ceb2878d48b19612ca360e277ef


--
◉ Kei Okada



2019年7月25日(木) 19:49 Manuel Kaufmann <notifications@github.com>:

**Comment by humitos** [comment]
@k-okada I'm talking about this

![Screenshot_2019-07-28_16-12-38](https://user-images.githubusercontent.com/244656/62007832-8ba82d00-b152-11e9-8fb1-ee29cd9b35dd.png)

From https://github.com/jsk-ros-pkg/jsk_docs#how-to-trigger-the-build

You should remove that call to the webhook every 10 minutes to trigger a new build.

**Comment by k-okada** [comment]
we have disabled that script and not longer required. removed from the
document ->  https://github.com/jsk-ros-pkg/jsk_docs/blob/master/README.md
--
◉ Kei Okada



2019年7月28日(日) 23:13 Manuel Kaufmann <notifications@github.com>:

**Comment by humitos** [comment]
Hi @k-okada! I re-enabled your projects. Thanks!
