### ISSUE TITLE
Could not Checkout Time out error.

### ISSUE THREAD

**Issue by TCY-LajeevP** [readthedocs/readthedocs.org#5999]
We are facing Timeout error while checkout from Git.
WE tried many times but it is failing every time.

> git.exe checkout -f 147e13a135f4f3b60b1e9cc02205b2d81822e2ae
ERROR: Timeout after 10 minutes
FATAL: Could not checkout 147e13a135f4f3b60b1e9cc02205b2d81822e2ae
hudson.plugins.git.GitException: Command "git.exe checkout -f 147e13a135f4f3b60b1e9cc02205b2d81822e2ae" returned status code 130:
stdout: 
stderr:

**Comment by stsewd** [comment]
Please provide the read the docs project URL and build url

**Comment by stsewd** [comment]
Please provide the read the docs project URL and build url

**Comment by TCY-LajeevP** [comment]
we are not facing this issue now.

**Comment by humitos** [comment]
Thanks for the update.
