### ISSUE TITLE
PDF some fonts not display for Chinese Janpanese mixed text

### ISSUE THREAD

**Issue by lucays** [readthedocs/readthedocs.org#6006]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/ocg-rule/
* Build URL (if applicable):
* Read the Docs username (if applicable): 碎冰

## Actual Result

in output pdf, Japanese font display incorrently. some fonts become 'F'
and symbol like '①②③' dont display.
![J2_5JPVODDSC L55W~ ZZCI](https://user-images.githubusercontent.com/29814851/62007655-cf1a8f80-b182-11e9-8f54-154c5086528e.png)

![image](https://user-images.githubusercontent.com/29814851/62007662-e8234080-b182-11e9-8704-8c7c69cdce4d.png)
(should be '「HSR魔剣ダーマ」的②③的效果1回合各能使用1次。')

this project translate Japanese to Chinese, when default latex engine is pdflatex, all display corrently with following configuration(just not very beautiful):
```
latex_elements = {
'preamble': r'''
\hypersetup{unicode=true}
\usepackage{CJKutf8}
\DeclareUnicodeCharacter{00A0}{\nobreakspace}
\DeclareUnicodeCharacter{2203}{\ensuremath{\exists}}
\DeclareUnicodeCharacter{2200}{\ensuremath{\forall}}
\DeclareUnicodeCharacter{2286}{\ensuremath{\subseteq}}
\DeclareUnicodeCharacter{2713}{x}
\DeclareUnicodeCharacter{27FA}{\ensuremath{\Longleftrightarrow}}
\DeclareUnicodeCharacter{221A}{\ensuremath{\sqrt{}}}
\DeclareUnicodeCharacter{221B}{\ensuremath{\sqrt[3]{}}}
\DeclareUnicodeCharacter{2295}{\ensuremath{\oplus}}
\DeclareUnicodeCharacter{2297}{\ensuremath{\otimes}}
\begin{CJK}{UTF8}{gbsn}
\AtEndDocument{\end{CJK}}
''',
}
```

I found [here](https://docs.readthedocs.io/en/stable/guides/pdf-non-ascii-languages.html) now rtfd use xelatex as normal pdf engine(if use Chinese), but I dont know if doc use Chinese and some Japanese, how to display corrently.
seem I just need add some Japanese font?
how to display '①②③'?
What is the correct configuration?

**Comment by lucays** [comment]
2 pictures above use following config:
```
latex_engine = 'xelatex'
latex_use_xindy = False
latex_elements = {
    'preamble': '\\usepackage[UTF8]{ctex}\n',
}
```

and I tried use Japanese config:
```
latex_engine = 'platex'
latex_use_xindy = False
```
Nothing (Chinese and Japanese and picture) will show...

**Comment by humitos** [comment]
> this project translate Japanese to Chinese, when default latex engine is pdflatex, all display corrently with following configuration(just not very beautiful):

If everything works as you want with the `pdflatex` engine, you can force it in your conf.py file by writing,

    latex_engine = 'pdflatex'

There is no need to use `xelatex` if it does not fit your requirements.

**Comment by humitos** [comment]
If you use Chinese and Japanese fonts, you need to include them both in the preamble setting. I do not know a good combination for that and it's out of the scope of the help that Read the Docs folks can give you.

I suggest you to make your question on StackOverflow or a similar platform.

**Comment by lucays** [comment]
> If you use Chinese and Japanese fonts, you need to include them both in the preamble setting. I do not know a good combination for that and it's out of the scope of the help that Read the Docs folks can give you.
> 
> I suggest you to make your question on StackOverflow or a similar platform.



> If you use Chinese and Japanese fonts, you need to include them both in the preamble setting. I do not know a good combination for that and it's out of the scope of the help that Read the Docs folks can give you.
> 
> I suggest you to make your question on StackOverflow or a similar platform.

although now switch back to pdflatex, some Japanese font still dont display... 
seem some fonts missing in readthedocs server ?
I see, I will make a question on stackoverflow.

**Comment by humitos** [comment]
> seem some fonts missing in readthedocs server ?

I don't think so. There are a ton of font installed on the build server. The thing is that you have to specify exactly which ones you want to use for Sphinx to find them.

Thanks! Feel free to reopen if you consider.
