### ISSUE TITLE
Versions are sorted by ASCII rather than version or commit date

### ISSUE THREAD

**Issue by davidism** [readthedocs/readthedocs.org#6010]
## Details

* Read the Docs project URL: https://jinja.readthedocs.io/en/2.10.x
* Build URL (if applicable): https://readthedocs.org/projects/jinja/builds/9440202/
* Read the Docs username (if applicable): davidism

## Expected Result

During the build and in the rendered docs popup, versions are sorted in version order, newest to oldest. Baring that, since slugs might not be valid versions (2.10.1 vs 2.10.x), version slugs should be sorted by commit date.

## Actual Result

Versions are ASCII sorted, so 2.9.x ends up greater than 2.10.x.

---

When building Jinja's docs, Pallets-Sphinx-Themes examines `html_context["versions"]` and `html_context["current_version"]`, injected by RTD, to show a banner at the top of the page. This worked fine for our previous projects, like Flask, which had versions 1.0.x and 1.1.x. However, Jinja has 2.9.x and 2.10.x, and it became apparent that RTD was sorting these in ASCII order, which becomes inconsistent across ones and tens digits. This is problematic because we were relying on RTD to report versions in a consistent newest to oldest order.

This shows up in `html_context["versions"]`:

```python
[
    ("master", "/en/master/"),
    ("2.9.x", "/en/2.9.x/"),
    ("2.10.x", "/en/2.10.x/"),
]
```

And in the versions popup:

![jinja](https://user-images.githubusercontent.com/1242887/62068698-6a474f80-b1eb-11e9-8811-267adc45667b.png)

Compare to Flask's version popup:

![flask](https://user-images.githubusercontent.com/1242887/62068728-7d5a1f80-b1eb-11e9-9749-838b061f2d15.png)

The order is not consistent with version or commit date ordering.

**Comment by humitos** [comment]
Hi @davidism! We are aware of this already.

We do sort the version using PEP440 (https://docs.readthedocs.io/en/stable/versions.html#how-we-envision-versions-working). Although, if the version does not follow this schema, it's ASCII sorted --as you found. In your case `2.9.x` makes `packaging.version.Version` to fail when initialized and so Read the Docs consider it as a non-valid version number.

This issue was already reported at https://github.com/readthedocs/readthedocs.org/issues/5291 and there is an idea to track the commit date at https://github.com/readthedocs/readthedocs.org/issues/5649

I think that sorting by commit date won't work either, because your `1.0.x` could have a more recent commit than `1.1.x`, right?

I'm not sure what's the best path to follow here. Naming docs versions with `x` for the patch number is the way that I personally prefer, but I also found this issue.

**Comment by davidism** [comment]
Hmm, I see what you mean with commit date. The way I handle sorting in the theme is a small wrapper that strips off a configured suffix first, so that they are valid sortable versions again.

**Comment by humitos** [comment]
Maybe we can fallback to numerical sorting if the version does not follow the PEP440 scheme with one of these proposal solution: https://stackoverflow.com/questions/2574080/sorting-a-list-of-dot-separated-numbers-like-software-versions --what do you think?

**Comment by humitos** [comment]
`natsort` seems to be what we want: https://pypi.org/project/natsort/#sorting-versions

**Comment by davidfischer** [comment]
@humitos Are you proposing ripping out `packaging.version.Version` from https://github.com/readthedocs/readthedocs.org/blob/4b38e8228f2df43cd81823139f525d999f6e4467/readthedocs/projects/version_handling.py#L15-L39 and instead use `natsort`? We could definitely test that. Alternatively, this does seem common enough where we could replace `.x` and call `parse_version_failsafe` again.

**Comment by humitos** [comment]
@davidfischer No. I'm "thinking aloud without looking at the code" that we could fallback to `natsort` when the version is not parseable by `packaging.version.Version`. I haven't taken a deep look yet.

**Comment by davidfischer** [comment]
I put one possible solution into https://github.com/readthedocs/readthedocs.org/pull/6012.

**Comment by ericholscher** [comment]
This is now shipped, let me know if it's resolved 👍

**Comment by davidism** [comment]
I checked https://jinja.palletsprojects.com/. 2.10.x sorts above 2.9.x, but now master sorts last.

**Comment by stsewd** [comment]
@davidism you need to activate the master version that says "latest"

![Screenshot_2019-08-07 Versions Read the Docs](https://user-images.githubusercontent.com/4975310/62672234-866f8d00-b95f-11e9-90fc-33e45ebf12ab.png)

**Comment by davidism** [comment]
Any chance since "latest" points to "master" that they both can sort higher? I've been deliberately using master so all docs versions would match branches, and it was sorting as expected before.

**Comment by stsewd** [comment]
> Any chance since "latest" points to "master" that they both can sort higher?

Internally rtd creates a version named latest that points to master (that's how it gets sorted). You are using the _plane_ version of master.

> it was sorting as expected before. #4672

My guess, like the other branches (2.x), master was failing too, so it was being sorted by the ascii value `('master' > '2.x') is True`.

I haven't tried this, but I think maybe you can still have master as latest. Can you try going to advanced settings and select master in `Default branch`?
![Screenshot_2019-08-07 Edit Advanced Project Settings Read the Docs](https://user-images.githubusercontent.com/4975310/62673372-d18b9f00-b963-11e9-9c63-cceb13eac195.png)

**Comment by stsewd** [comment]
> I haven't tried this, but I think maybe you can still have master as latest. Can you try going to advanced settings and select master in Default branch?

Nope, that doesn't work.

We should treat master and trunk (whatever master is in other VCS) like we do with latest, or show the real version name in the selector, not the slug

**Comment by stsewd** [comment]
Changing the slug to the real name is a big chance, I'm making a patch for the first option

**Comment by stsewd** [comment]
PR at https://github.com/readthedocs/readthedocs.org/pull/6049

**Comment by stsewd** [comment]
@davidism master should be sorted first now

**Comment by davidism** [comment]
Awesome, thanks!
