### ISSUE TITLE
*.readthedocs.io is down.

### ISSUE THREAD

**Issue by avandesa** [readthedocs/readthedocs.org#6016]
## Details

* Read the Docs project URL: simpy.readthedocs.io, phpspreadsheet.readthedocs.io, any project site
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

Visiting any readthedocs site opens the docs

## Actual Result

The request for the page times out.

I can ping readthedocs.io, but not any project-specific site.

**Comment by stsewd** [comment]
The team is looking into it now

**Comment by ericholscher** [comment]
This should now be resolved.

**Comment by avandesa** [comment]
Yep, looks like it's up. Thanks guys!
