### ISSUE TITLE
Trouble making custom 404 (not found) work

### ISSUE THREAD

**Issue by markcmiller86** [readthedocs/readthedocs.org#6021]
## Details

* [Read the Docs project URL](https://visit-sphinx-github-user-manual.readthedocs.io/en/docs-markcmiller86_add_404_page_31jul19/index.html)
* Read the Docs username (if applicable): markcmiller86
* Source [GitHub Repo/Branch](https://github.com/visit-dav/visit/tree/docs/markcmiller86_add_404_page_31Jul19)

## Expected Result

Trying to make custom 404 (not found) page work following [these instructions](https://docs.readthedocs.io/en/stable/guides/custom-404-page.html)

I am getting something that is *almost* working sufficiently for my needs. But, [the 404 page](https://visit-sphinx-github-user-manual.readthedocs.io/en/docs-markcmiller86_add_404_page_31jul19/cli_manual/intro.htm) renders a bit funky in spite of the fact that there aren't any special links, images.

Also, I tried to use the `notfound.extension` in `conf.py` `extensions` variable and the build failed for lack of the extension. How is one supposed to `pip install ...` the extension when all they are doing is trigging a docs build on a vanilla RTD build? Should I be doing something like this in `conf.py`...

```
if os.environ.get('READTHEDOCS'):
  from subprocess import call 
   call(['pip', 'install', 'sphinx-notfound-page'])
```

I looked for something similar in example projects using `notfound.extension` and didn't see anything like this.

**Comment by stsewd** [comment]
The page doesn't load CSS files because of

> As the 404.html will be returned for all the URLs where the real page was not found, all its resources URLs and links must be absolute (starting with a /), otherwise they will not work when a user clicks on them.

You need to install the extension, you can install it using https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

**Comment by markcmiller86** [comment]
Ok, thanks so much.
