### ISSUE TITLE
AttributeError when running a build

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#6024]
## Steps to reproduce it

1. checkout `master`
1. remove the `.db` sqlite file
1. run migrations
1. create super user
1. import a project manually
1. trigger a build

## Actual result

This error is shown in the logs:

```
Traceback (most recent call last):
  File "/home/humitos/rtfd/code/readthedocs.org/readthedocs/projects/tasks.py", line 296, in update_docs_task
    return step.run(version_pk, *args, **kwargs)
  File "/home/humitos/rtfd/code/readthedocs.org/readthedocs/projects/tasks.py", line 431, in run
    self.send_notifications(version_pk, build_pk)
  File "/home/humitos/rtfd/code/readthedocs.org/readthedocs/projects/tasks.py", line 1070, in send_notifications
    if self.version.type != EXTERNAL:
AttributeError: 'dict' object has no attribute 'type'
```

## Expected behavior

No error.

**Comment by saadmk11** [comment]
We need to first run `python manage.py loaddata test_data` so that it sets the SLUMBER user and it will result in successful api calls :)

**Comment by minrock** [comment]
Hi, I just got the same error, but now when doing the `python manage.py loaddata test_data` I'm facing this error 

`django.db.utils.OperationalError: Problem installing fixtures: no such table: projects_project__old`

**Comment by stsewd** [comment]
@minrock you need to install the correct version of sqlite, see https://docs.readthedocs.io/en/stable/development/install.html#requirements

**Comment by minrock** [comment]
Thank you, didn't notice that
