### ISSUE TITLE
Command killed due to excessive memory consumption

### ISSUE THREAD

**Issue by fmaussion** [readthedocs/readthedocs.org#6025]
## Details

* Read the Docs project URL: https://oggm.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/oggm/builds/9456071/
* Read the Docs username (if applicable): fmaussion

Hi! I'm here again, with our expensive conda builds (for the context, I already had performance related issues in the past: https://github.com/readthedocs/readthedocs.org/issues/5098 , https://github.com/readthedocs/readthedocs.org/issues/4432).

Our projects simply requires a lot of packages, and conda has become very hungry lately. Can I ask for a higher memory limit for the following projects? They all have the same package requirements:

- https://readthedocs.org/projects/oggm
- https://readthedocs.org/projects/salem
- https://readthedocs.org/projects/rgitools
- https://readthedocs.org/projects/oggm-edu

Note that we would really love to be more efficient than that, but I really don't think we can. We also have working containers that could create our docs for you, but ReadTheDocs still doesn't accept arbitrary containers, right? 

Thanks in advance! 

Fabien

## Expected Result

The docs being built.

## Actual Result

``Command killed due to excessive memory consumption``

**Comment by humitos** [comment]
I'd like to take a look at this. Probably next week if I have some time. I think conda gets crazy when using multiple channels :/

My first attempt was to upgrade the `conda` version that your docs are using to build it (which they said that had some "memory leak" improvements), but I saw that your `oggm` project is already doing that :(

@fmaussion where I can see what packages will be installed by [`oggm-deps`](https://github.com/OGGM/oggm/blob/master/docs/environment.yml#L7)?

**Comment by fmaussion** [comment]
Thanks for your help @humitos !

your question motivated me to try to install the packages directly instead of via ``oggm-deps``. Our builds are now working!

Change in env: https://github.com/OGGM/oggm/pull/835/files

Build log: https://readthedocs.org/projects/oggm/builds/9457124/

Thanks for your help and sorry for the noise...

**Comment by humitos** [comment]
@fmaussion awesome! thanks for sharing the results!

**Comment by fmaussion** [comment]
@humitos if you agree I'd like to reopen this. In a sister project (with exactly the same env.yml) we are experiencing the memory issue at the conda step: 

https://readthedocs.org/projects/rgitools/builds/9481900/ 

Any idea on how to make it more efficient?

**Comment by humitos** [comment]
@fmaussion I've already add the flag to update conda on startup but it still fails.

Is it possible to remove all the dependencies that are not needed to build the documentation from the [environment.yaml](https://github.com/OGGM/rgitools/blob/master/docs/environment.yml)? For example, with a quick look, it seems that `pytest` is not required.

**Comment by humitos** [comment]
Also, you may want to consider to no use conda `conda` at all to build these documentation. You can just use simple `pip` to install all the dependencies (I think) --maybe not `pyproj` since requires a library but maybe it's not required to build the docs anyway. We suggest to do this when possible if the problem of OOM is hit. See https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html

**Comment by fmaussion** [comment]
@humitos (and @ocefpaf and @jswhit because I think they might be interested in this). I just managed to do something that would have been impossible a year ago: I moved to a full ``pip install`` of packages such as rasterio / geopandas / pyproj / netcdf4 on RTD, and it works! 

Here the requirements: https://github.com/OGGM/rgitools/blob/master/docs/requirements.txt

And the setup:

```
python:
   version: 3.5
   install:
      - requirements: docs/requirements.txt
   system_packages: true
   setup_py_install: true
``` 

The pinning of netCDF4 to a 2017 version were necessary for the netcdf4 library to work without an obscure ``HDF Error``.

After moving from pip to conda, then mamba, are we going back to pip again? :wink: Thanks to wheels, on linux this is at least an option.

**Comment by humitos** [comment]
@fmaussion I'm happy that you find out a way to make it builds the docs on Read the Docs without conda. I would love if you can keep me posted (or I can subscribe to an issue in your repo) since I'm interested on tracking this kind of issues on Read the Docs and collect some ideas, workflow problems, etc to continue thinking in different solutions.

**Comment by fmaussion** [comment]
Dear Maintainers, dear @humitos  - our builds started to fail because of timeout errors again, without any significant change on our side: https://readthedocs.org/projects/oggm/builds/10371200/ 

I you have time I'd be grateful about any advice about what's going on. Thanks!!!!

**Comment by fmaussion** [comment]
OK, nevermind - I think the problem is on our side, sorry for the noise.
