### ISSUE TITLE
Subprojects page throwing 502

### ISSUE THREAD

**Issue by dhalbert** [readthedocs/readthedocs.org#6027]
https://readthedocs.org/dashboard/circuitpython/subprojects/ is returning a 502. It did work once, in the past 20 minutes, but all other times it has failed.

**Comment by humitos** [comment]
Hrm... I'm not seeing anything relevant in our Sentry logs yet.

As a note, I saw that `circuitpython` has like ~150 subprojects. So, that may be making the DB query to timeout.

**Comment by dhalbert** [comment]
We do have a lot of subprojects :smiley:. I'm still seeing this: did you change anything about DB query timeouts, or perhaps the DB server(s) are just unusually loaded today? I'll try again during off hours.

**Comment by bdice** [comment]
Yes, I am seeing a 502 Error for https://readthedocs.org/ and https://readthedocs.org/dashboard/ as well. I also got one page to load before this error started appearing.

**Comment by dojutsu-user** [comment]
Hi @bdice 
We are having some troubles with our servers and therefore the 502 error.
Currently the team is looking into it.
Thanks for your patience.

**Comment by bdice** [comment]
It's working again for me -- thanks RTD team! :)

**Comment by agjohnson** [comment]
Closing. Seems like this was transient and related to Azure problems last week.
