### ISSUE TITLE
SSL Proxies no longer working

### ISSUE THREAD

**Issue by ewdurbin** [readthedocs/readthedocs.org#6036]
## Details

* Read the Docs project URL:
  - packaging.python.org
  - devguide.python.org
  - warehouse.pypa.io
  - pip.pypa.io
  - etc.

## Expected Result

SSL termination configured per https://docs.readthedocs.io/en/stable/custom_domains.html#proxy-ssl loads our docs

## Actual Result

As of approximately 15:39 UTC 2019-08-02 this configuration is serving Cloudflare 403 pages.

**Comment by ewdurbin** [comment]
Additional context: In all instances above we are terminating TLS with Fastly.

**Comment by agjohnson** [comment]
Hrm odd. Probably related to a move to Cloudflare on the readthedocs.org that we just did this morning. We're getting flooded with spam.

I'm on #readthedocs on freenode if it's easier to debug there.

I'll poke around on domains for now.

**Comment by agjohnson** [comment]
@ewdurbin What address are you proxying to in fastly?

**Comment by ericholscher** [comment]
What url are you proxying to?

**Comment by ewdurbin** [comment]
looks like they are all configured to proxy to readthedocs.org. which I guess is now out of date. I tried readthedocs.io but it wasn't working.

curling around it seems we need them each to proxy to something different. i kinda overlooked the part in the proxy ssl where the subdomain needs to be handled.

attempting that now.

**Comment by ewdurbin** [comment]
got it, overlooked the subdomain portion in the Proxy SSL configuration. looks like we're good here.

thank you for quick responses!
