### ISSUE TITLE
yaml config uses "htmldir" instead of "dirhtml"

### ISSUE THREAD

**Issue by davidism** [readthedocs/readthedocs.org#6038]
The Sphinx make target is called "dirhtml", but RTD's [yaml spec ](https://github.com/readthedocs/readthedocs.org/blob/93bcf8d19c367e1088893a4902b15a05d1ad190f/readthedocs/rtd_tests/fixtures/spec/v2/schema.yml#L99) uses "htmldir". RTD should match Sphinx for consistency. It can accept "htmldir" for compatibility, but should only document the correct name.

**Comment by humitos** [comment]
I agree with this suggestion :smile:

**Comment by kushthedude** [comment]
@humitos I would like to work on it

**Comment by dojutsu-user** [comment]
@kushthedude 
Go ahead. :tada:

**Comment by stsewd** [comment]
@kushthedude go ahead!

**Comment by Blackcipher101** [comment]
@humitos  @stsewd Is this issue still valid can I work on it

**Comment by stsewd** [comment]
@Blackcipher101 it's still valid, go ahead. You can check this old PR https://github.com/readthedocs/readthedocs.org/pull/6058 for suggestions.
