### ISSUE TITLE
No theme for me?

### ISSUE THREAD

**Issue by wtuemura** [readthedocs/readthedocs.org#6041]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/mamedoc/
* Build URL (if applicable): https://mamedoc.readthedocs.io/pt/latest/
* Read the Docs username (if applicable): wtuemura

## Expected Result
The normal RTD template and style should be applied to the page.
Page mirror:
http://mamedoc.epizy.com/

*A description of what you wanted to happen*

## Actual Result
No theme at all

Looks like a duplicate of #3715
Thank you.

**Comment by agjohnson** [comment]
Looks like you replaced our theme with an overrides file and didn't include the overrides file. Make sure you aren't completely replacing our CSS if you are adding a CSS file.

Closing as this isn't an RTD bug.

**Comment by wtuemura** [comment]
Got the site to work now.

Thank you for the reply.
