### ISSUE TITLE
Fixed footer ad close button is obscured by scrollbar

### ISSUE THREAD

**Issue by davidism** [readthedocs/readthedocs.org#6044]
The floating ad has an "X" close link, but it is overlapped by the scrollbar. This happens on at least Firefox 68 and Chromium 76.

![Firefox example](https://user-images.githubusercontent.com/1242887/62551425-d4ca4200-b820-11e9-85f9-0132e2223b4d.png)

![Chromium example](https://user-images.githubusercontent.com/1242887/62551521-0511e080-b821-11e9-8dce-0b0bde11d43c.png)

**Comment by lepture** [comment]
For https://docs.authlib.org/ it breaks the theme.

![image](https://user-images.githubusercontent.com/290496/64138183-e52d0700-ce36-11e9-805c-41285efb6cae.png)

**Comment by lepture** [comment]
@stsewd is there a way to define where the ad should be placed?

**Comment by davidism** [comment]
According to https://docs.readthedocs.io/en/stable/advertising/ad-customization.html, a special div id will be replaced.

```html
<div id="ethical-ad-placement"></div>
```

**Comment by humitos** [comment]
@davidfischer is this still an issue? I'm not sure if we are still serving text-ads.

**Comment by davidfischer** [comment]
We are not serving text-only ads currently.
