### ISSUE TITLE
Support GitLab for PR Builder

### ISSUE THREAD

**Issue by saadmk11** [readthedocs/readthedocs.org#6052]
## Details

As we have initially added support for GitHub, we need to start thinking about supporting other providers such as GitLab.

Initial building blocks were created for the PR Builder. Next Steps for supporting GitLab might be:

- [x] We do not set `'merge_requests_events': True` while creating a webhook for GitLab which does not give us access to merge request events. **We have to add this for future webhook creation and also figure out a way to add this to previously created webhooks for GitLab.**
 **PR:**  #6055  #6071

https://github.com/readthedocs/readthedocs.org/blob/e632813db6d42a5398d6162657bd6b59837c72af/readthedocs/oauth/services/gitlab.py#L234-L263

- [x] Handle incoming merge request Webhook from GitLab and creating external versions / triggering build or deleting external versions based on the webhook.
Docs for merge request webhook event: [merge-request-events](https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#merge-request-events). **PR:** #6066

- [x] Send Build Status Report through GitLab commit status API.
Docs for commit status API: [post-the-build-status-to-a-commit](https://docs.gitlab.com/ce/api/commits.html#post-the-build-status-to-a-commit) **PR:** #6076

Referencing this issue as it talks about supporting GitLab for PR Builder: https://github.com/readthedocs/readthedocs.org/issues/2464

**Comment by stsewd** [comment]
> We have to add this for future webhook creation and also figure out a way to add this to previously created webhooks for GitLab.

There are some ideas around that here https://github.com/readthedocs/readthedocs.org/issues/5062 (it's about github, but the same applies)

**Comment by saadmk11** [comment]
@stsewd I suppose we could do a automatic re-sync for GitLab through a Management Command. 
Or maybe we can show a site notification to the users who have a GitLab project with PR Builder enabled that they need to re-sync their GitLab webhook to get the PR Builder Working.

**Comment by ericholscher** [comment]
This sounds good. I think to start we can just start setting the `merge_requests` on new gitlab connections. We can then worry later about how to reconnect them, after we have the rest of the code working I think.

**Comment by saadmk11** [comment]
Yeah I was thinking the same :)

**Comment by saadmk11** [comment]
Closing this as all the work for this issue has been merged.
