### ISSUE TITLE
Delete Account failure

### ISSUE THREAD

**Issue by icgood** [readthedocs/readthedocs.org#6057]
## Details

* Read the Docs project URL: N/A
* Build URL (if applicable):
* Read the Docs username (if applicable): icgood

## Expected Result

I went to "Delete Account", typed in my username to confirm, and I expected my account to be deleted.

## Actual Result

I received an error page containing the fail whale:

```
          .
         ":"
       ___:____     |"\/"|
     ,'        `.    \  /
     |  O        \___/  |
   ~^~^~^~^~^~^~^~^~^~^~^~^~

   Fail.  Check back in a bit!
```

My account was not deleted, and I was still logged in when I went back to the homepage.

**Comment by stsewd** [comment]
Yeah, accounts created before this release https://docs.readthedocs.io/en/stable/changelog.html#version-3-6-0 (July 16, 2019) can't be deleted because of https://github.com/readthedocs/readthedocs.org/issues/5875#issuecomment-519380737. We are working in fixing the problem.

**Comment by humitos** [comment]
This is fixed. You should be able to delete your account. Feel free to reopen if that's not the case.
