### ISSUE TITLE
git submodules not cloned

### ISSUE THREAD

**Issue by fergonco** [readthedocs/readthedocs.org#606]
We have a project that includes some documentation from other repositories as submodules.

However, RTD is not cloning them. I have been looking to other issues and tried some things like including git statements on the Makefile. But it doesn't work.

Is this supported or is there any workaround? Thanks in advance.

The project is this one: http://geotalleres.readthedocs.org/

**Comment by gianarb** [comment]
@ericholscher this flow works in different branch? I added a submodule into the branch feature/layout-docs but it doesn't seem work..

Thanks for your work!

PS I use mkdocs
