### ISSUE TITLE
Add pagination to version's page

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6068]
Currently, we list all versions in one page. This is a problem for projects that have thousands of versions (it's difficult to search the versions and very slow for the db)

https://readthedocs.org/projects/docs/versions/

**Comment by agjohnson** [comment]
I don't want to paginate that page. We shouldn't be showing disabled versions at all on that page. Adding enabled versions should work like all of our other model views. There should be a separate form view that has a dropdown/autocomplete text input that sets the version to enabled on submit.

This is the pattern that we're working towards with the UI overhaul, so we should start moving in that direction. Feel free to repurpose this issue, but closing for now.
