### ISSUE TITLE
Search index not updated after renaming/moving of a page

### ISSUE THREAD

**Issue by dojutsu-user** [readthedocs/readthedocs.org#6069]
#5845 renames [APIv3 Design Document](https://docs.readthedocs.io/en/latest/development/design/apiv3.html) from `Design of APIv3` to `APIv3 Design Document` but the search results still contains both results.

Related link: https://docs.readthedocs.io/en/latest/index.html?rtd_search=apiv3

![Screenshot from 2019-08-13 21-23-29](https://user-images.githubusercontent.com/29149191/62956950-7816ea80-be11-11e9-8338-3b873db0065d.png)

**Comment by stsewd** [comment]
There is this error on sentry, maybe related to this issue

```
update or delete on table "projects_importedfile" violates foreign key constraint "sphinx_domains_sphin_html_file_id_a0307e9f_fk_projects_" on table "sphinx_domains_sphinxdomain"
```

It happens here

https://github.com/readthedocs/readthedocs.org/blob/e53af663c0996303c249743123b92ae886c1734f/readthedocs/projects/tasks.py#L1640-L1647

https://sentry.io/organizations/read-the-docs/issues/1144425753/?project=148442&query=is%3Aunresolved&statsPeriod=14d

**Comment by hiddeco** [comment]
Not sure if this is related, but for https://docs.fluxcd.io, we also notice that renamed files and files removed from git aren't removed from the index.

E.g. first result for this search: https://docs.fluxcd.io/en/latest/search.html?q=ignore&check_keywords=yes&area=default

**Comment by dojutsu-user** [comment]
@hiddeco 
Can you try wiping the version and then rebuilding the docs?
You can find the steps for it here: https://docs.readthedocs.io/en/stable/guides/wipe-environment.html

**Comment by hiddeco** [comment]
@dojutsu-user already did this before I commented, without any effect.

**Comment by jcampbell** [comment]
Thanks @stsewd for flagging this still-open issue. We're observing this on the great expectations docs (https://great-expectations.readthedocs.io/en/latest/). Searching for a moved page shows both the new (working) and broken link. I have tried wiping and rebuilding to no effect.

**Comment by Flid** [comment]
Also affecting https://kedro.readthedocs.io, most of the search queries show the broken links first, since we've moved some stuff around.

**Comment by Flid** [comment]
@dojutsu-user Can you please confirm if the bug is actually fixed for you?
Nothing changed for our project.

**Comment by humitos** [comment]
It's fixed but it's not deployed yet.

**Comment by madelyngreyes** [comment]
Do we have a status on the deployment of the possible fix by chance?

**Comment by stsewd** [comment]
@madelyngreyes it's already deployed. If you still have this problem, you should try rebuilding the version.

**Comment by Flid** [comment]
Our issue has been fixed after the release. Thank you!

**Comment by madelyngreyes** [comment]
My issue was fixed as well, thank you!
