### ISSUE TITLE
Version's page is slow

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6070]
Currently, we list all versions in one page. This is a problem for projects that have thousands of versions (it's difficult to search the versions and very slow for the db)

https://readthedocs.org/projects/docs/versions/

One idea is to don't list deactivated versions and use a form instead. Not really sure how that looks like, we still need a way to list all versions. If we put an auto complete widget, does the user know what version wants to activate?

Ref https://github.com/readthedocs/readthedocs.org/issues/6068#issuecomment-520908761

**Comment by dojutsu-user** [comment]
We can have infinite scroll?

**Comment by davidfischer** [comment]
This page's performance is tied to https://github.com/readthedocs/readthedocs.org/issues/3712. Generally each active version results in ~3 extra DB queries because it links to those versions' docs. Having even a couple hundred inactive versions shouldn't matter, but active versions definitely will.

**Comment by agjohnson** [comment]
I'm -1 on pagination and infinite scroll, or other patterns that continue showing inactive versions listed on this page. The pattern used here should be the same as our other CRUD UIs:

* The version list is *only* active versions
* A button at the top will lead to a form
* The form has an autocomplete text input to select the version, form submit adds `Version.active = True` to the selected version
* The newly selected `Version.active = true` version is now on the version list page.

**Comment by cz-kialo** [comment]
Just wanted to leave a comment here that this issue prevents us from defining more that one version (the default version) on readthedocs.com . Because of our continuous integration setup we have several ten-thousand tags in our repo on Github and the versions page just times-out with a 502 error.

A simple form to define a new version would be great.

**Comment by humitos** [comment]
@cz-kialo please, if you are using Read the Docs for Business contact us via the support email (support at readthedocs.com) and we will help you with this there. Thanks!

**Comment by cz-kialo** [comment]
@humitos thanks, we're already in contact with your support since some time, just wanted to make sure that the info is taken into account because this issue seems to get some attention at the moment.
