### ISSUE TITLE
Error when trying to import repositories from GitHub

### ISSUE THREAD

**Issue by astrofrog** [readthedocs/readthedocs.org#6075]
## Details

When I try and import repositories from GitHub, I see the following error:

```
There was an error with your request: get() returned more than one RemoteRepository -- it returned 2!
```

Screenshot:

<img width="828" alt="Screenshot 2019-08-16 at 13 54 50" src="https://user-images.githubusercontent.com/314716/63168952-76297300-c02d-11e9-9248-c99fdc68b861.png">

* Read the Docs username: astrofrog

## Expected Result

The page shows a list of repositories to import

## Actual Result

The error shown above occurs.

**Comment by humitos** [comment]
Thanks for reporting this. I've seen the same issue on #5351. I thought it was an exceptional case and I touched the database manually.

Now, this new report makes me think that there is something in our code that is creating duplicated `RemoteRepository` objects _or_ your account is old enough for where there was a bug in the code and we _were_ creating duplicated.

Are you part of GitHub/GitLab Organizations with _a lot_ of projects? I think that could be one of the possible issues, but not sure yet.

**Comment by astrofrog** [comment]
I have 371 repositories and am part of 32 organizations so it could be related to that 😁

**Comment by humitos** [comment]
@astrofrog is this issue still happening to you?

**Comment by astrofrog** [comment]
I think this is working now
