### ISSUE TITLE
Adding Contributor Covenant Code of Conduct

### ISSUE THREAD

**Issue by tapaswenipathak** [readthedocs/readthedocs.org#6078]
Hey folks: having a Contributor Covenant Code of Conduct should be a must for open source project, more necessary for the heavily contributed. I am suggesting adding Contributor Covenant Code of Conduct from https://www.contributor-covenant.org/ or say anywhere from where the maintainers feels is appropriate for the readthedocs GitHub org.

**Comment by stsewd** [comment]
Hi @tapaswenipathak, we do have a code of conduct https://docs.readthedocs.io/en/latest/code-of-conduct.html

**Comment by tapaswenipathak** [comment]
Hey @stsewd: The doc looks great for following, thanks! Feel free giving a thought if you require a Contributor Covenant Code of Conduct from https://www.contributor-covenant.org/ as well.
