### ISSUE TITLE
URL handling in PR builds (using `htmldir` builder)

### ISSUE THREAD

**Issue by plaindocs** [readthedocs/readthedocs.org#6083]
## Details

Looks like the URL handling for PR builds is off.

## Expected Result

When clicking "Conferences" (second link) in `https://external-builds.readthedocs.io/html/writethedocs-www/1055/index.html` the link is pointing at `https://external-builds.readthedocs.io/html/writethedocs-www/1055/conf/`.

## Actual Result

The PR build only understands that as 

`https://external-builds.readthedocs.io/html/writethedocs-www/1055/conf/index.html`.

**Comment by saadmk11** [comment]
We do not currently support `htmldir` builds URL Handling. You can add `index.html` after the url to see the doc for now. :)
e.g: `https://external-builds.readthedocs.io/html/writethedocs-www/1055/conf/index.html`

**Comment by stsewd** [comment]
This should be fixed now, we are serving docs (normal and from PRs) using another method that doesn't have this problem.

Feel free to ask to re-open if you still see this problem
