### ISSUE TITLE
invisible code-blocks

### ISSUE THREAD

**Issue by lschmelting** [readthedocs/readthedocs.org#6084]
Hello,

I need some help to find out why some code-block appears normally when the html page is compiled locally, while it does not appear in the online documentation:

* .rst file on Github https://github.com/e2nIEE/pandapower/blob/develop/doc/opf/powermodels.rst
 
* RAW .rst file https://raw.githubusercontent.com/e2nIEE/pandapower/develop/doc/opf/powermodels.rst
## Details

* Read the Docs project URL: https://pandapower.readthedocs.io/en/develop/opf/powermodels.html

## Expected Result (local)
![grafik](https://user-images.githubusercontent.com/49401816/63349433-b3f30800-c35b-11e9-82e8-da6f524f899a.png)

## Actual Result (Github)
![grafik](https://user-images.githubusercontent.com/49401816/63348076-da637400-c358-11e9-9d91-19e83f7e4f20.png)

Kind regards

**Comment by lschmelting** [comment]
Ok this is weird, at the moment it is displayed correctly (in Firefox). Me and another person both accessed the page at random moments in time and the code-block only shows up sometimes.

**Comment by stsewd** [comment]
I can't see the code blocks from firefox

**Comment by dojutsu-user** [comment]
@stsewd 
I am not able to see in Chrome (Version 74.0.3729.157 (Official Build) (64-bit)) and Ubuntu 18.04.2 LTS.

![Screenshot from 2019-08-21 00-10-32](https://user-images.githubusercontent.com/29149191/63375095-bd569180-c3a8-11e9-96c8-1954f4cc2635.png)

**Comment by lschmelting** [comment]
Any ideas what code change might help?

**Comment by stsewd** [comment]
Looks like the code was removed https://github.com/e2nIEE/pandapower/commit/c4bfae906e93208f9af2eba77b17bf12a16a0a73#diff-ed7075fc60742be1be75555dcf20ce39

If you still see this in another part of your docs feel free to open a new issue.
