### ISSUE TITLE
Compress output PDF

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#6089]
## Details
I'd like to compress the output PDF/EPUB file using [ghostscript](https://www.ghostscript.com/). However, it seems that ReadTheDocs does some custom configuration to it's latex PDF generation. Building the PDF locally outputs the PDF with the following format ``/build/latex/firstroboticscompetition.pdf``, and ReadTheDocs outputs it with ``/en/latest/frc-docs.pdf``. My documentation is over 80MB and is quickly growing larger, splitting it up into multiple sites is not an option due to the nature of what our documentation is.

**Question:** How do I compress my output PDF? 

* Read the Docs project URL: https://frc-docs.readthedocs.io/en/latest or https://github.com/wpilibsuite/frc-docs
* Build URL (if applicable): NA
* Read the Docs username (if applicable): NA

**Comment by davidfischer** [comment]
> ReadTheDocs outputs it with /en/latest/frc-docs.pdf

RTD always stores the PDF as `<project-slug>.pdf` so that's the answer to this oddity.

Are you running a post-build command or something to compress your PDF locally when you do it? I'm not sure if there's already a way to use ghostscript in Sphinx but there's probably a way to make an extension for it.

**Comment by Daltz333** [comment]
Sphinx doesn't seem to expose a latex end event, and I'd like to run a post-build command.

**Comment by humitos** [comment]
@Daltz333 you may be interested in the `build-finished` event. See https://www.sphinx-doc.org/en/master/extdev/appapi.html#event-build-finished

**Comment by Daltz333** [comment]
I dont believe there is a way to distinguish between HTML builds and latexpdf/epub builds

**Comment by humitos** [comment]
You will have the builder used at `app.builder`. For example,

```python
>>> app.builder
<sphinx.builders.html.StandaloneHTMLBuilder object at 0x7f328e39c128>
```

or

```python
>>> app.builder
<sphinx.builders.latex.LaTeXBuilder object at 0x7ff1d403b0f0>
```
