### ISSUE TITLE
Request for increase build memory resource in Chainer project

### ISSUE THREAD

**Issue by kmaehashi** [readthedocs/readthedocs.org#6092]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/chainer/
* Build URL (if applicable): https://readthedocs.org/projects/chainer/builds/9549466/
* Read the Docs username (if applicable): kmaehashi

## Expected Result

Document build succeeds.

## Actual Result

Build fails for 9 times out of 10 with the following error:

```
c++: internal compiler error: Killed (program cc1plus)
```

Our project would like to publish documentation for Python modules written in C++. I assume this is caused by the memory limitation. Could you consider increasing the memory allocation? Thanks in advance!

**Comment by humitos** [comment]
I increased the memory for your project and triggered a new build of latest. It worked: https://readthedocs.org/projects/chainer/builds/9550366/

I just triggered a second one just in case, but I suppose that it will keep working.

Let us know otherwise.

**Comment by kmaehashi** [comment]
Thank you!
