### ISSUE TITLE
Using Jupyter's bash_kernel with nbsphinx

### ISSUE THREAD

**Issue by kpj** [readthedocs/readthedocs.org#6095]
## Details

I am integrating Jupyter notebooks into my Sphinx documentation using [nbsphinx](https://github.com/spatialaudio/nbsphinx).
This works fine for Python kernels, but fails for e.g. [bash_kernel](https://github.com/takluyver/bash_kernel).
The problem is that `bash_kernel` requires an additional installation step.

I have already added `bash_kernel` as a dependency to my requirements file (specified as [described](https://docs.readthedocs.io/en/stable/config-file/v2.html#requirements-file)).
However, the kernel requires the execution of `python -m bash_kernel.install` to be available to Jupyter.

Is there a way of executing this instruction (or installing the kernel in some other way) on readthedocs.org?

There would be the way of adding `subprocess.call("python -m bash_kernel.install")` to `conf.py` but that seems very dirty.

* Read the Docs project URL: https://project-manager.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/project-manager/builds/9551280/
* Read the Docs username (if applicable): kpj

**Comment by stsewd** [comment]
> There would be the way of adding subprocess.call("python -m bash_kernel.install") to conf.py but that seems very dirty.

Unfortunately that's the only way, we don't support executing arbitrary commands.

Maybe it could be done with an extension.

**Comment by kpj** [comment]
I see. As a test, I added the following to my `conf.py`:
```python
import json
import subprocess

kernel_str = subprocess.check_output(['jupyter', 'kernelspec', 'list', '--json'])
kernel_data = json.loads(kernel_str)

if 'bash' not in kernel_data['kernelspecs']:
    # see https://github.com/takluyver/bash_kernel
    subprocess.call(['python', '-m', 'bash_kernel.install'])
```

The kernel is then available, but execution seems to fail: https://readthedocs.org/projects/project-manager/builds/9551548/
What would be the best way of debugging this?

**Comment by stsewd** [comment]
@kpj the best way is to execute the same commands locally and see if you can replicate the same error.

**Comment by kpj** [comment]
My apologies. I should have made clear that I already checked this setup locally, and it works fine.

In particular, I did the following:
```bash
# uninstall bash kernel
$ jupyter kernelspec uninstall bash

# build docs
$ sphinx-build source/ _build
Running Sphinx v2.0.1
Installing IPython kernel spec
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 4 source files that are out of date
updating environment: 4 added, 0 changed, 0 removed
reading sources... [100%] setup_config
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] setup_config
generating indices... genindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded.

The HTML pages are in _build.
```


I investigated the problem a bit more, and it turns out that the error code `127` indicates that the command `tree` cannot be found.
This might be a separate issue, but is there a way of providing it?

**Comment by kpj** [comment]
The error I get is:
```python
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/project-manager/envs/latest/lib/python3.7/site-packages/nbsphinx.py", line 861, in parse
    rststring, resources = exporter.from_notebook_node(nb, resources)
  File "/home/docs/checkouts/readthedocs.org/user_builds/project-manager/envs/latest/lib/python3.7/site-packages/nbsphinx.py", line 768, in from_notebook_node
    nb, resources = pp.preprocess(nb, resources)
  File "/home/docs/checkouts/readthedocs.org/user_builds/project-manager/envs/latest/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/home/docs/checkouts/readthedocs.org/user_builds/project-manager/envs/latest/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/home/docs/checkouts/readthedocs.org/user_builds/project-manager/envs/latest/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
tree
------------------


: 127
```

Is there a way of debugging this phenomenon without repeatedly pushing slight modifications?

**Comment by kpj** [comment]
Thanks, that is a great suggestion!

I pulled the latest default image and tried executing `tree`:
```bash
$ docker pull readthedocs/build:latest
$ docker run --rm -it readthedocs/build:latest /bin/bash
docs@96b16aad1e39:/$ tree
bash: tree: command not found
```
It does not seem to be available.

Furthermore, the `sphinx-build` command is not found. After checking the [Dockerfile](https://github.com/readthedocs/readthedocs-docker-images/blob/master/Dockerfile), neither of those command is explicitly installed (if I understand correctly).

**Comment by stsewd** [comment]
@kpj you are missing the installation steps of the virtual env and python dependencies.

It's weird that `tree` doesn't exist :/ maybe the docker image doesn't include that command

**Comment by kpj** [comment]
Thanks for the advice!
I'll then provide a custom tree command in the notebook.

**Comment by humitos** [comment]
`tree` command is not in `main` Ubuntu repository, it's in `universe`. It seems it's not installed by default on Ubuntu (server, at least) and we don't install it in our Docker image either.

We could add it to our image but we don't have a Docker image release planned yet, so it will take some time to be available on the servers.
