### ISSUE TITLE
Check use of `latest` for latest unreleased versions vs latest stable versions

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6096]
We should check this in our docs and help texts, it's confusing for some users.

**Comment by stsewd** [comment]
Here is a place where it needs clarification https://docs.readthedocs.io/en/stable/versions.html#version-warning and on the advanced settings `Show version warning`.

It should mention that the banner links to the latest stable version.

**Comment by KartikKapil** [comment]
@stsewd is this issue still open ?

**Comment by stsewd** [comment]
@KartikKapil yeah, but there is a PR in progress here https://github.com/readthedocs/readthedocs.org/pull/6143

**Comment by Blackcipher101** [comment]
@stsewd Can I work on this issue

**Comment by stsewd** [comment]
@Blackcipher101 if so, please use https://github.com/readthedocs/readthedocs.org/pull/6143

**Comment by humitos** [comment]
Related issue at https://github.com/readthedocs/readthedocs.org/issues/10674
