### ISSUE TITLE
Auto PR Build fails when branch force pushed

### ISSUE THREAD

**Issue by pllim** [readthedocs/readthedocs.org#6097]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/synphot/
* Build URL (if applicable): https://readthedocs.org/projects/synphot/builds/9552745/
* Read the Docs username (if applicable): pllim

xref spacetelescope/synphot_refactor#214

## Expected Result

Successful build and a green check.

## Actual Result

Error in build and the check got stuck in the yellow "pending" purgatory.

```
Read the Docs build information
Build id: 9552745
Project: synphot
Version: 214
Commit: e5c62052eb18eccd8c3b2ba9154fc7d841d42aa9
Date: 2019-08-22T20:05:54.195292Z
State: finished
Success: False

[rtd-command-info] start-time: 2019-08-22T20:05:54.611830Z, end-time: 2019-08-22T20:05:54.621555Z, duration: 0, exit-code: 0
git remote set-url origin https://github.com/spacetelescope/synphot_refactor

[rtd-command-info] start-time: 2019-08-22T20:05:54.724120Z, end-time: 2019-08-22T20:05:55.276842Z, duration: 0, exit-code: 1
git fetch origin --tags --prune --prune-tags --depth 50 pull/214/head:external-214
From https://github.com/spacetelescope/synphot_refactor
 ! [rejected]        refs/pull/214/head -> external-214  (non-fast-forward)
```

![Screenshot from 2019-08-22 16-46-58](https://user-images.githubusercontent.com/2090236/63548547-7aa5ce00-c4fc-11e9-9675-34e66080c617.png)

**Comment by stsewd** [comment]
Looks like we can't do a fetch when a commit was rebased, we need to do a clone instead.

**Comment by stsewd** [comment]
I just tested this, the payload from the pull request doesn't include if the sync was done with a forced push.

We are testing always doing a clone #5680, but not sure if it would be released. Another option is to force a clone for the PR versions.

**Comment by saadmk11** [comment]
I'm closing this as the PR regarding this is merged. :)
