### ISSUE TITLE
Global search on elasticsearch for private repositories

### ISSUE THREAD

**Issue by maldag** [readthedocs/readthedocs.org#6107]
I'm running a local instance of RTD (3.7.2) combined with elasticsearch.
Searching the whole RTD instance from the landing page also returns search entries belonging to private repositories. This seems to be a security flaw since the index probably doesn't care about access rights on the webpage.

The major goal I'm trying to achieve is hosting development and user documentation on the same server using private repositories for developers (which would access and search both) as well as user documentation for people without credentials.

Is there a way to propagate repository rights to elasticsearch?

**Comment by maldag** [comment]
Yes, I did setup two projects with one version (latest) each. Project A is a public project with public version and project B is a private project with a private version.

Elasticsearch will index both (Autoindex set to true) and will return results from the private project when not logged in as an appropriate user.

**Comment by stsewd** [comment]
Just a note here, we are in process to remove the privacy level from all projects https://github.com/readthedocs/readthedocs.org/pull/6194
