### ISSUE TITLE
Abandoned project request: pytd

### ISSUE THREAD

**Issue by chezou** [readthedocs/readthedocs.org#6114]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pytd/
* Build URL (if applicable):
* Read the Docs username (if applicable): chezou, @takuti

## Expected Result

We'd like to use the 'pytd' project name on RTD for our active project at https://github.com/treasure-data/pytd

The current 'pytd' project on RTD only hosts the initial generated page and seems using GitHub page instead as their official document for https://github.com/addisonlynch/pyTD.

**Comment by stsewd** [comment]
I'm pinning @addisonlynch is case the user can just give you the project (or delete the project so the name is available). Looks like there is some contact information too https://github.com/addisonlynch/pyTD#contact

**Comment by stsewd** [comment]
Also, I if you are unable to contact the user, we can follow our policy for abandoned projects https://docs.readthedocs.io/en/stable/abandoned-projects.html

**Comment by addisonlynch** [comment]
This is still in use...I'm sorry! I will be updating the project soon.

**Comment by stsewd** [comment]
@addisonlynch thanks for letting us know!
