### ISSUE TITLE
Request to enable SEARCH_ANALYTICS feature flag for project Veeam Best Practise 9.5u4a

### ISSUE THREAD

**Issue by szelesi** [readthedocs/readthedocs.org#6117]
## Details

* Read the Docs project URL:
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by stsewd** [comment]
Hi @szelesi, sorry for the delay here, can you please provide the project url? The name `Veeam Best Practise 9.5u4a` is a little ambiguous

**Comment by stsewd** [comment]
Closing since we don't know the project to activate the flag. And we are going to expose that all users soon anyway https://github.com/readthedocs/readthedocs.org/issues/6217
