### ISSUE TITLE
OPDS for browsing all manuals via eBook-Reader

### ISSUE THREAD

**Issue by Matthias84** [readthedocs/readthedocs.org#6120]
## Details

Hi , I use RDTD a lot to learn about python modules. Somethmes I download also PDFs/ePubs to read it offline at the PC (on travel, vacation ... with bad internet connectivity)

But what I think is missed, is a simple interface for eBook-Readers, to search for docs and download them. Luckily there is the [OPDS](https://opds.io) specification, that describes how to make use of RSS feeds, to implement such a machine level interface. Basically it offers ebook resources as .epub via different RSS catalogues and also implements search, metadata, ... . There are some existing libs and projects out there, which implement OPDS generators and most fields seem already available.
Maybe this is also interesting to other users that need offline docs from time to time? This would open the docs library to other ebook reading audience as well!

**Comment by ericholscher** [comment]
I don't think this is something that we are going to implement. Closing this for now.
