### ISSUE TITLE
Resync doesn't work for manully created integations

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6123]
- Import a project from github
- An integration is created automatically, resync button works
- Create a new integration manually
- The resync button appears, but it doesn't create the webhook on the git repo.

When doing a resync, a secret is added/changed, but the webhook wasn't created on the repo, so is going to always ask for a secret and fail.

Ref #6122

**Comment by saadmk11** [comment]
Looks like there are some issues. Working on it!

**Comment by stsewd** [comment]
Also, we should change the message https://github.com/readthedocs/readthedocs.org/issues/6122#issuecomment-526360199
