### ISSUE TITLE
Cache in footer view

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6126]
The footer view is assessed for each page view. We should make it faster :)

Ref: https://github.com/readthedocs/readthedocs.org/pull/6125#discussion_r319328817

**Comment by humitos** [comment]
Cache keys should be improved to avoid potential conflicts: https://github.com/readthedocs/readthedocs.org/pull/6125/files#r320606597

**Comment by tapaswenipathak** [comment]
Hi folks: I have added few PRs, let me know your thoughts https://github.com/readthedocs/readthedocs.org/pull/6148#issuecomment-529690680.

**Comment by dojutsu-user** [comment]
@stsewd I think it will result in not having correct results for #6121. We are storing the page views count from the footer views. So if that is cached -- the page view count will not be correct.

**Comment by stsewd** [comment]
We are going to move page views to its own endpoint https://github.com/readthedocs/readthedocs.org/pull/7739, after that we are going to cache it trough cloudflare.
