### ISSUE TITLE
This project is currently disabled and can't trigger new builds.

### ISSUE THREAD

**Issue by deshipu** [readthedocs/readthedocs.org#6128]
## Details

* Read the Docs project URL: http://pewpew.readthedocs.io
* Build URL (if applicable): 
* Read the Docs username (if applicable): sheep

## Expected Result

A new build is triggered.

## Actual Result

The message "This project is currently disabled and can't trigger new builds." is displayed and no new build is triggered. Also, trying to change the repository URL to now correct value (it has moved on github) instead takes me to the front page, and triggering a web hook results in a 406 status response with "This project is currently disabled" in the reply body.

**Comment by stsewd** [comment]
Hi @deshipu, we need to investigate why the project was disabled before enable it. A common case is that the project was triggering a lot of builds.

**Comment by deshipu** [comment]
That doesn't seem to be the case here, though, there were 4 builds 5 months ago, and before that other 4 builds 9 months ago.

I think it may be related to the fact that I moved the repository on GitHub to a different organization and forgot to update the URL on readthedocs, but there are redirects in place for that.

Thank you a lot for looking into it!

**Comment by deshipu** [comment]
I just checked my other projects, and it seems like they are all disabled. So this is probably something related to my account?

**Comment by stsewd** [comment]
Oh, I see. A reason for that is that your account could have been marked as spam incorrectly. I'll try to look at this today

**Comment by davidfischer** [comment]
I unbanned your account and you should be good to go. We recently flagged a number of spam accounts but I don't see any reason why your account should have been flagged.

**Comment by deshipu** [comment]
Thank you!
