### ISSUE TITLE
`Verify Email` link contains phishing (?) link

### ISSUE THREAD

**Issue by xobs** [readthedocs/readthedocs.org#6134]
## Details

* Read the Docs project URL: N/A
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): xobs

## Expected Result

I received an email that contained the text `To verify your email address and finish setting up your account, please go to: https://readthedocs.org/accounts/confirm-email/...`, but the actual link is completely different.

## Actual Result

If you click on the link, it takes you to the very spammy-looking URL `https://u11967345.ct.sendgrid.net/wf/click?upn=...`.  My email client flags this out as being fraudulent, because the domain name in the link doesn't match the domain name in the address, nor does it match the actual contents of the link.

**Comment by stsewd** [comment]
Do you have the email of the sender? Did you request  the email verification?

**Comment by stsewd** [comment]
I just tested the email verification. It gives this link, but the actual link is `https://u11967345.ct.sendgrid.net/wf/click?upn=gAU4-2Btfh-...`
![Screenshot_2019-09-04 Verify your email address - stsewd gmail com - Gmail](https://user-images.githubusercontent.com/4975310/64272308-b2e9db00-cf04-11e9-99f6-5bf8e30f435b.png)

> nor does it match the actual contents of the link.

For me it redirects to the confirmation page.

I'll investigate why it links to other domain

**Comment by davidfischer** [comment]
This is most likely added automatically by our mail provider to track clicks on links. I don't think we need or want this.

**Comment by ericholscher** [comment]
I've now turned off all tracking in our email settings. It was previously tracking link clicks and mail opens, which seems like a terrible default :(

**Comment by stsewd** [comment]
Just checked, it links to the correct domain now.

**Comment by davidfischer** [comment]
Thanks for the report @xobs and keep up all the good work on Fomu and Novena!
