### ISSUE TITLE
List only built versions on the footer

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6137]
When a version is `built=False` our code links to the version detail page

https://github.com/readthedocs/readthedocs.org/blob/89a58a07716ccf5793e0a241be174d52d1f03c76/readthedocs/builds/models.py#L296-L303

This method gets called from `sort_version_aware`, here we are passing all active versions (including not built).

https://github.com/readthedocs/readthedocs.org/blob/89a58a07716ccf5793e0a241be174d52d1f03c76/readthedocs/projects/models.py#L953-L986

This is a problem in .com, where we don't have access to that `URLCONF`, so reverse doesn't work.

I'm thinking two options:

1. Only list built versions, this is modify this method and add a filter (this method is only used in the footer).

https://github.com/readthedocs/readthedocs.org/blob/89a58a07716ccf5793e0a241be174d52d1f03c76/readthedocs/projects/models.py#L953

2. Only change this in .com, adding a new kwarg to .public (`only_builts=False`)

I'm more inclined to 1, so we affect .org and .com,  giving a link to the dashboard to a user that doesn't have permissions doesn't look correct.

**Comment by humitos** [comment]
Just want to note a use case of this.

Listing "`active` but not `built` versions" in the footer is _kind of a hidden feature_. Why? It allows people to list all the supported versions in the footer and create a `Redirect` pointing to a different hosting platform for old versions for example.

So, 1.x and 2.x are hosted at Read the Docs, but 0.8.x and 0.9.x are hosted in a different platform. You `active=True` the fourth of them and create two Redirects for 0.8.x and 0.9.x.

I've used this "hidden feature" for a user already.

**Comment by stsewd** [comment]
@humitos but when the version is `built=False` it links to the dashboard, so the redirect doesn't work there.

**Comment by ericholscher** [comment]
Yea, I think linking to the dashboard doesn't make sense. I'm happy to update the link to simply go to the docs page, and have it 404 if it isn't built. That enables the redirect logic that @humitos was talking about, and linking the dashboard is not useful for users basically ever.
