### ISSUE TITLE
Support custom static files served at root URL (/)

### ISSUE THREAD

**Issue by skirpichev** [readthedocs/readthedocs.org#6138]
Currently, we can add robots.txt to the root of the project with
``
html_extra_path = ['robots.txt']
``
Unfortunately, this doesn't work with html files.  For example, I tried to add site verification file for the Google Console just as for the robots.txt.  File was added to the project root (e.g. it is present in the HTML zip archive), but can't be viewed via HTTP:
$ HEAD -d https://diofant.readthedocs.io/googlef1d0c0c51427e8a4.html
404 Not Found

**Comment by humitos** [comment]
Right. We do not serve files at root (URL `/`). `robots.txt` is a special case, that's why it's served.

There other ways to verify a that owns a site that you may want to use.

**Comment by skirpichev** [comment]
> There other ways to verify a that owns a site

@humitos, the "other ways" - adding txt dns entry.  Maybe this option is available per user request?  

Or you do mean something else?

**Comment by stsewd** [comment]
Also, if you don't care about having different versions of your docs, you can mark the `Single version` option on the admin settings of your project, that way everything would be served from the root.

**Comment by skirpichev** [comment]
> Also, if you don't care about having different versions of your docs

No, thank you.  This is not an option for me.

**Comment by humitos** [comment]
@skirpichev I saw there is a way to use `meta` HTML tag.

BTW, I suppose you are talking about https://support.google.com/webmasters/answer/9008080?visit_id=637032978747984544-1520634005&rd=1&hl=en

**Comment by skirpichev** [comment]
> I saw there is a way to use meta HTML tag.

@humitos, are you sure there are?

I added meta tag to the index.rst.  It shown in the local version, right after the "charset" meta...  But on the rtfd.io - this tag absent...

**Comment by humitos** [comment]
@skirpichev I don't why RTD would behave different on the meta tags. Do you an example? It's hard to tell you otherwise.

**Comment by humitos** [comment]
Here you have a live example using a `meta:description` tag: https://test-builds.readthedocs.io/en/meta-tags/ on Read the Docs.

**Comment by skirpichev** [comment]
Sorry, forgot push to the origin :)  Thank you for help.  And patience.

It seems, you classified this as a support request.  I'm not ready to suggest a use case for such static files in /, except for the reported above (which has workarounds).  So, closing.

**Comment by adiroiban** [comment]
> Also, if you don't care about having different versions of your docs, you can mark the Single version option on the admin settings of your project, that way everything would be served from the root.

You can temporary set up "Single version" at the start of the project just to pass the Google validation.
Later you can disable this... I think that side effect is that all the previous versions are removed when this is enabled.
