### ISSUE TITLE
CORS: Query from github.io Page

### ISSUE THREAD

**Issue by ax3l** [readthedocs/readthedocs.org#6152]
## Details

* Read the Docs project URL: any
* Build URL (if applicable):
* Read the Docs username (if applicable):

Live page: https://ecp-warpx.github.io
Source: https://github.com/ECP-WarpX/ecp-warpx.github.io

## Expected Result

I am trying to query the public RTD API endpoint https://docs.readthedocs.io/en/stable/api/v2.html#project-versions from a [github.io page](https://pages.github.com/) with jQuery.

```html
  <script type="text/javascript">
    $(document).ready(function(){
      var project_rtd_id = 123456;
      /* see https://docs.readthedocs.io/en/stable/api/v2.html#project-versions */
      $.ajax({
         /* crossDomain: true, */
         url: "https://readthedocs.org/api/v2/project/" + project_rtd_id.toString() + "/active_versions/",
         /* dataType: "jsonp", */
         success: function(data) {
           $.each(data.versions, function(index, value) {
             var version_name = value.slug;
             /* do something with version_name */
           });
         },
         error: function () {
            console.error('Error loading the RTD API endpoint');
         },
      });
    });
  </script>

```

## Actual Result

I receive browser errors regarding CORS violations as soon as this page is deployed to `github.io`:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://readthedocs.org/api/v2/project/<myProjectID>/active_versions/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

I believe this is caused by a missing HTTP header at the endpoint. We can fix this by adding `Access-Control-Allow-Origin: *` for responses from `readthedocs.org/api/v2/`. As a side note, support for [JSONP](https://en.wikipedia.org/wiki/JSONP) would also be really awesome for v3 :)

**Comment by stsewd** [comment]
I'm closing this in favor of https://github.com/readthedocs/readthedocs.org/issues/6154 where we are discussing how to deal with this.
