### ISSUE TITLE
CORS problems around API

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#6154]
We currently support [JSONP on APIv2 in the Footer HTML endpoint](https://github.com/readthedocs/readthedocs.org/blob/30e495504911d0720558a6b307c9cd05a7dbfffb/readthedocs/api/v2/views/footer_views.py#L80) only.

Supporting JSONP on APIv3 will allow to query the API from different custom domains.

Suggested at #6152

**Comment by stsewd** [comment]
We shouldn't use jsonp for new code, we should use a CORS solution instead. And for public and read only endpoints.

**Comment by humitos** [comment]
@stsewd 

> We shouldn't use jsonp for new code

Why not?

> we should use a CORS solution instead

How is that solution?

**Comment by stsewd** [comment]
jsonp is to get around CORS, we are opening too much with that, I linked this in other of our projects (private). You can read the warning on this project for example https://jpadilla.github.io/django-rest-framework-jsonp/.

This lib is for handling CORS on django https://github.com/adamchainz/django-cors-headers

**Comment by humitos** [comment]
Thanks @stsewd for the data!

We already have `django-cors-headers` installed and it seems that we have been using it already for Ads. Although, I think we can improve its settings and enable it on the API as well.

**Comment by humitos** [comment]
I'm closing this issue because it's old and it does not adds value to the current situation. We have talked about CORS recently and we are working on the changes required.

**Comment by jobisoft** [comment]
This was closed without pointing to the current discussion. Where can I follow the progress?

I am not able to access the API from `<projectslug>.readthedocs.io` and also not from the custom domain setup for the project, and I find no public reference to CORS related hiccups besides this closed issue. Any help is appreciated.

**Comment by humitos** [comment]
Hi @jobisoft

> This was closed without pointing to the current discussion. Where can I follow the progress?

The discussion wasn't public. We will update the documentation for our API to reflect these decisions soon.
 
> I am not able to access the API from `<projectslug>.readthedocs.io` and also not from the custom domain setup for the project, and I find no public reference to CORS related hiccups besides this closed issue. Any help is appreciated.

What API endpoints are you using?

You should probably use the Proxied API that we designed for this particular case: instead of hitting `readthedocs.org/api/` you should use `<projectslug>.readthedocs.io/_/api/` (or just `/_/api/` without caring where your RTD site is hosted --.readthedocs.io or custom domain). Please, let me know if this works for you.

**Comment by jobisoft** [comment]
@humitos : Thanks for your response. The endpoint I am currently using is this:
https://readthedocs.org/api/v2/version/?project__slug=thunderbird-webextension-apis&active=true

The page itself is here:
https://thunderbird-webextensions.readthedocs.io/en/latest/

But I cannot seem to get the proxy endpoint running:
https://thunderbird-webextensions.readthedocs.io/_/api/v2/version/?project__slug=thunderbird-webextension-apis&active=true

I also tried v3 at
https://thunderbird-webextensions.readthedocs.io/_/api/v3/projects/thunderbird-webextension-apis/versions/

Could you point me to documentation regarding proxy API? It definitely would solve my issues.

Thanks for your time!

**Comment by stsewd** [comment]
@jobisoft we only proxy APIs that are commonly used from docs sites, like search, embed and footer. We won't be able to proxy all endpoints as they depend on the codebase from the main site. We are going to add a better (public) footer api for users to use https://github.com/readthedocs/readthedocs.org/pull/8052
