### ISSUE TITLE
Use `modified` time instead of `created` time for recording search queries

### ISSUE THREAD

**Issue by dojutsu-user** [readthedocs/readthedocs.org#6155]
We should use `modified` time here and not the `created` time.
`modified` time gets updated automatically, so the query should also be changed.

https://github.com/readthedocs/readthedocs.org/blob/98a7ff1758d829323e5ef9949f57401f7103ec4e/readthedocs/search/tasks.py#L213-L214

https://github.com/readthedocs/readthedocs.org/blob/98a7ff1758d829323e5ef9949f57401f7103ec4e/readthedocs/search/tasks.py#L159-L163

Ref: [#6088 (comment)](https://github.com/readthedocs/readthedocs.org/pull/6088#discussion_r318738599)

**Comment by Iamshankhadeep** [comment]
@dojutsu-user what do I need to know to start working on this issue?

**Comment by dojutsu-user** [comment]
Hi @Iamshankhadeep 
You can start working on this (Just a little knowledge of django ORM is required)
I think the issue description mentions everything.
Feel free to ask any doubts/questions if you get stuck anywhere. :smiley:

**Comment by Iamshankhadeep** [comment]
@dojutsu-user never worked on django so trying to put together the pieces. I think we just need to change `obj.created` to `obj.modified` and `order_by('-created') ` to `order_by('-modified') ` right?
