### ISSUE TITLE
Link to previous GSOC projects

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6156]
We should link to these posts

https://blog.readthedocs.com/search-improvements/
https://blog.readthedocs.com/improved-search-and-search-as-you-type/
https://blog.readthedocs.com/building-docs-for-pull-requests/

Ref https://github.com/readthedocs/readthedocs.org/pull/6147#pullrequestreview-285461077

**Comment by KartikKapil** [comment]
hello @stsewd i would like on this issue what exactly do i have to do for this??

**Comment by dojutsu-user** [comment]
Hi @KartikKapil 
Thanks for your interest in contribution. :tada:

We have GSoC related details in our documentation here: https://docs.readthedocs.io/en/stable/gsoc.html
Each past GSoC project has a blog post which describes the project (links are in the issue description). It would be better to add a section in the documentation which provides links to these blog posts.

**Comment by KartikKapil** [comment]
sir @dojutsu-user i have made the changes regarding the previous GSOC projects i have added the links to the direct GSOC archive 
added previous year gsoc projects #6333
