### ISSUE TITLE
Move `expandable_fields` to meta class

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6159]
We are using the old way, declaring `expandable_fields` at the class level instead of on the meta class.

Docs on https://github.com/rsinger86/drf-flex-fields

This file needs to be updated https://github.com/readthedocs/readthedocs.org/blob/master/readthedocs/api/v3/serializers.py

Ref https://github.com/readthedocs/readthedocs.org/pull/6158#discussion_r322472534

**Comment by Iamshankhadeep** [comment]
only the `serializers.py` needs to be updated?

**Comment by stsewd** [comment]
@Iamshankhadeep if you find other files, feel free to update those too
