### ISSUE TITLE
Build is passing first time but failing every other time

### ISSUE THREAD

**Issue by dino-bosnjic** [readthedocs/readthedocs.org#6161]
## Details

* Read the Docs project URL: This is private hosted server
* Build URL (if applicable): //
* Read the Docs username (if applicable): //

## Expected Result

Buld is passing every time.

## Actual Result

Build is passing just first time after creating new project. After first build, every other build is failing.  [Build failling](https://imgur.com/a/ULd7lmQ)

I have managed to force future build with this steps:
- Under Advanced settings changing Python Interpreter* from  CPython 3.x to CPython 2.x.
(When I make this change build is still failing. [See this image](https://imgur.com/a/jygxYsn))
- When I make change back to CPython 3.7 build is passing. Again this is working for just one time and we are back to start of the problem.

**Comment by stsewd** [comment]
Hi @dino-bosnjic, we don't support custom installations, you can read more about it here https://docs.readthedocs.io/en/stable/open-source-philosophy.html

Also, not really sure the problem you are having, there isn't much context. Make sure you have virtualenv installed for python2.x globally.

**Comment by dino-bosnjic** [comment]
Thanks for much needed help. That is exactly it.

**Comment by stsewd** [comment]
> That is exactly it.

Do you mean you were able to solve the problem?

**Comment by dino-bosnjic** [comment]
@stsewd  Yes, I've installed python2.x globally and that solved my problem.
