### ISSUE TITLE
Using Custom docker container for building rtd project

### ISSUE THREAD

**Issue by shahzebsiddiqui** [readthedocs/readthedocs.org#6162]
## Details
Issue with readthedocs build https://readthedocs.org/projects/buildtest/builds/9638753/ because I want to use my custom docker container for building my project. My custom docker container is the following https://hub.docker.com/r/shahzebsiddiqui/readthedocs-docker-images so I tried adding this see https://github.com/HPC-buildtest/buildtest-framework/commit/53e78a56756e1c8a88397804fad88207a2844a69

I know according to documentation https://docs.readthedocs.io/en/stable/config-file/v2.html#build there is an option ``build.image`` but the image is set to tag. There is no way for me to change the image name to my custom docker.

The reason why I need my own docker container is because the default container by readthedocs dont have a package called Lmod https://packages.ubuntu.com/bionic/lmod

* Read the Docs project URL:  https://readthedocs.org/projects/buildtest
* Build URL (if applicable):  https://buildtest.readthedocs.io/en/devel/
* Read the Docs username (if applicable):

My previous build https://readthedocs.org/api/v2/build/9633993.txt that were successful are running into issue where $LMOD_DIR is not defined. This is because this variable is set if Lmod is installed. 

The reason why I need this is I am trying to get sphinx-autodoc feature working. I am able to build the documentation locally on a server with Lmod and I am able to get the content generated

![image](https://user-images.githubusercontent.com/12942230/64632108-76b3f000-d3c6-11e9-984c-810a834df40c.png)

However I cant get this generated through rtd see https://buildtest.readthedocs.io/en/devel/command_reference.html because the build is failing to process all my python files

**Comment by stsewd** [comment]
We don't plan on supporting custom docker images. If the package `Lmod` is very popular on several docs, we can put in on our docker images. Also, you can try mocking the lib https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by shahzebsiddiqui** [comment]
Yes please if you can add ``Lmod`` that would be great. The documentation is not clear on how the docker container is invoked in backend. For instance, the container I have needs to source ``source /etc/profile`` generally this is required in a login shell. In docker you can get a interactive shell with tty using ``docker exec -it`` but I still need to invoke /etc/profile.

To demonstrate my local container build here is the output

```
[root@delta-swarm01 readthedocs-docker-images]# docker run -it --name readthedocs shahzebsiddiqui/readthedocs-docker-images
docs@96c82a0decd4:/$ echo $LMOD_DIR

docs@96c82a0decd4:/$ source /etc/profile
docs@96c82a0decd4:/$ echo $LMOD_DIR
/usr/share/lmod/lmod/libexec
docs@96c82a0decd4:/$ module av

-------------------------------------------------------------------------------------- /usr/share/lmod/lmod/modulefiles ---------------------------------------------------------------------------------------
   Core/lmod/6.6    Core/settarg/6.6

Use "module spider" to find all possible modules.
Use "module keyword key1 key2 ..." to search for all possible modules matching any of the "keys".


```

**Comment by shahzebsiddiqui** [comment]
Also please see lines the following lines in Dockerfile
https://github.com/shahzebsiddiqui/readthedocs-docker-images/blob/master/Dockerfile#L139
https://github.com/shahzebsiddiqui/readthedocs-docker-images/blob/master/Dockerfile#L141

I ran into issue so please see bug https://bugs.launchpad.net/ubuntu/+source/lua-posix/+bug/1752082 when installing Lmod

**Comment by stsewd** [comment]
We execute the commands you  see on the build page. We don't source anything from `/etc/profile/`. We can add the lib if it's heavy used on other projects/libs, if it's specific to this case we can't do that (we try to keep our docker images small).

Also, did you try mocking the dependency?

If that doesn't work, you can always try to execute any command on your `conf.py` file.

**Comment by shahzebsiddiqui** [comment]
Hi @stsewd,
According to https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules i believe mock is only compatible with pypi packages. Lmod is not distributed as pypi. It is packaged as .rpm, .deb, etc...

**Comment by stsewd** [comment]
@shahzebsiddiqui I mean you can mock the module/lib that depend on/use that package

**Comment by shahzebsiddiqui** [comment]
Ok i will give it a try, I am not familiar with mock. Will this ignore the modules during import defined in ``MOCK_MODULES``. If that is the case should I set it to the top level package. According to http://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports if i understand I should do to top-level package and not sub-modules. In this case ``MOCK_MODULES=["buildtest"]``.

**Comment by stsewd** [comment]
Yes, only the top level package

**Comment by shahzebsiddiqui** [comment]
Running into some issues. Here is the start of my conf.py

```
import os
import sys
from unittest.mock import MagicMock

BUILDTEST_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.environ["BUILDTEST_ROOT"] = BUILDTEST_ROOT
sys.path.insert(0, os.path.join(BUILDTEST_ROOT,'src'))

class Mock(MagicMock):
    @classmethod
    def __getattr__(cls, name):
        return MagicMock()

MOCK_MODULES = ["buildtest"]
sys.modules.update((mod_name, Mock()) for mod_name in MOCK_MODULES)
```

Getting a warning issue when building documentation
```
$ make clean; make html
Removing everything under '_build'...
Running Sphinx v2.0.1
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 60 source files that are out of date
updating environment: 60 added, 0 changed, 0 removed
reading sources... [100%] yaml_subcommand                                                                                                                                                                                                 
WARNING: __all__ should be a list of strings, not <MagicMock id='46912657924392'> (in module buildtest) -- ignoring __all__
/gpfs/home/siddis14/buildtest-framework/docs/command_reference.rst:4: WARNING: Failed to import "menu" from "buildtest.tools.menu".
No module named 'buildtest.tools'
looking for now-outdated files... none found
pickling environment... done
checking consistency... /gpfs/home/siddis14/buildtest-framework/docs/README.rst: WARNING: document isn't included in any toctree
/gpfs/home/siddis14/buildtest-framework/docs/api/modules.rst: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [100%] yaml_subcommand                                                                                                                                                                                                  
generating indices... genindex py-modindex
writing additional pages... search/home/siddis14/.local/share/virtualenvs/buildtest-framework-ghOUBUfH/lib/python3.7/site-packages/sphinx_rtd_theme/search.html:20: RemovedInSphinx30Warning: To modify script_files in the theme is deprecated. Please insert a <script> tag directly in your theme instead.
  {{ super() }}

copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 4 warnings.

The HTML pages are in _build/html.

```

The issue is with sub-modules.

**Comment by shahzebsiddiqui** [comment]
My makefile has a target ``apidocs`` that i use to generate the apidocs using ``sphinx-apidoc``

```
apidocs:
        sphinx-apidoc -f -e -o api ../src/buildtest
```

The files are generated and can be found at https://github.com/HPC-buildtest/buildtest-framework/tree/devel/docs/api the issue is these files are generated and working without need of mock in my system. I want to generate the apidocs for buildtest and all its sub-modules but it doesn't work in readthedocs.

**Comment by stsewd** [comment]
Please use the sphinx setting, the other code is an old workaround

```
autodoc_mock_imports = ["buildtest"]
```

**Comment by stsewd** [comment]
Ok, If I understand `buildtest` is your package? Is `Lmod` used to generate the docs? I guess you can try to find a way to not execute Lmod when importing a module, but just when it is needed.

Also, as I said, you can also try executing the commands to install the lib on your `conf.py` file and using this env var https://docs.readthedocs.io/en/stable/builds.html#build-environment to only execute those command on rtd.

**Comment by shahzebsiddiqui** [comment]
Yes ``buildtest`` is my python package. ``Lmod`` is a system package that is a dependency. It is not required for docs. In fact the docs are automatically created and .rst files are there. I will try to find way to redirect ``modules.rst`` the root of my api to retrieve the python files without having to import all python files.

**Comment by humitos** [comment]
We don't plan to support using a custom docker image for now. We have an ongoing discussion about supporting uploading docs already built instead that will help on many of this issues.

I'm closing this one for now. I'm opening https://github.com/readthedocs/readthedocs-docker-images/issues/112
