### ISSUE TITLE
Issues with git+https://github.com/username/repo@tag pip dependency in requirements.txt

### ISSUE THREAD

**Issue by lukelbd** [readthedocs/readthedocs.org#6181]
My `docs/requirements.txt` file includes an unpublished fork of a Github sphinx extension, `git+https://github.com/lukelbd/sphinx-automodapi@tag`.

After a few hours of debugging I realized that the `pip install git+...` on the readthedocs server was not updating every file, even after using new `tag`s and updating the version number in setup.py. In the end the only thing that worked was nuking the entire readthedocs page and starting another one from scratch -- I had hundreds of old versions that all used the older version of my Github sphinx extension and there is was no way to bulk delete them.

Could this have been a pip issue specific to the readthedocs server? I had no problem updting my package with `pip install git+https://github.com/lukelbd/sphinx-automodapi@tag` on my own machine -- it just seemed to silently refuse to update certain files on your server.

**Comment by stsewd** [comment]
Looks like a pip thing, not only with read the docs. You don't need to delete your project to clean de cache, you can wipe the build environment https://docs.readthedocs.io/en/stable/guides/wipe-environment.html (it gets deleted after some time automatically)

**Comment by lukelbd** [comment]
I don't really know how to reproduce the issue so I guess I'll close this for now. May re-open at a later date.

Also yes I know about "wipe" but I needed to wipe *hundreds* of old versions that used the old version of the sphinx extension, and there is no way to "bulk wipe". Would really love it if you guys added that to the website.

**Comment by stsewd** [comment]
@lukelbd we are testing removing all files (includes the virtual env) after each build, so wiping shouldn't be necessary when that option is active for all users
