### ISSUE TITLE
Unexpected HTML output of the RTD section in home page

### ISSUE THREAD

**Issue by johannfaouzi** [readthedocs/readthedocs.org#6188]
## Details

* Read the Docs project URL: https://pyts.readthedocs.io/en/update_doc_theme/
* Build URL (if applicable):
* Read the Docs username (if applicable): johannfaouzi

I am trying to move from the `sphinx_rtd_theme` theme to the `Alabaster` theme for one of my projects, and I have an issue regarding the section to change the branch, download the documentation, etc. It looks pretty ugly, and I don't understand why this is occurring.

## Expected Result

Something like this (taken from https://rtd-sphinx-theme-sample-project.readthedocs.io/en/alabaster/):
![Capture d’écran 2019-09-17 à 16 58 34](https://user-images.githubusercontent.com/17053934/65053580-6ffc1e80-d96c-11e9-8340-c02a24e5e726.png)

## Actual Result

This ugly thing (taken from https://pyts.readthedocs.io/en/update_doc_theme/index.html):
![Capture d’écran 2019-09-17 à 17 00 08](https://user-images.githubusercontent.com/17053934/65053695-a20d8080-d96c-11e9-9833-9034caf575e9.png)

Thank you very much.

**Comment by stsewd** [comment]
Maybe something to do with your custom css https://github.com/johannfaouzi/pyts/blob/update_doc_theme/doc/_static/custom.css, everything else looks correct.

**Comment by johannfaouzi** [comment]
Thank you very much for your quick reply, I will try to investigate.

**Comment by johannfaouzi** [comment]
I tried several things and the expected output only occurred when I disabled the whole custom CSS file:
```python
if 0:
    html_context = {
        'css_files': ['_static/custom.css'],
    }
```
Having an empty `custom.css` file does not work.

It means that it is currently impossible to use a custom CSS file and to have the nice output for the RTD section. I am reopening the issue, to see if a fix is possible.

**Comment by johannfaouzi** [comment]
Possibly related: https://docs.readthedocs.io/en/latest/development/design/theme-context.html

**Comment by johannfaouzi** [comment]
My bad, I put my custom CSS file in `html_context` instead of `html_css_files`. It works much better now. It is very well explained in the [documentation](https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html).
