### ISSUE TITLE
Version Warning banner does not appear

### ISSUE THREAD

**Issue by odscjames** [readthedocs/readthedocs.org#6202]
## Details

* Read the Docs project URL: https://odscjameswritessometestdocumentation.readthedocs.io

## Expected Result

I turned on "Show version warning" 

I go to https://odscjameswritessometestdocumentation.readthedocs.io/en/v0-1-0/cats.html

It is not "latest" or "Stable".

So I expect to see a warning banner.

## Actual Result

I don't see a warning banner.

![Screenshot from 2019-09-23 14-12-48](https://user-images.githubusercontent.com/37832009/65428493-5fd0bd00-de0c-11e9-9ed4-e2bc462344ca.png)

(I rebuilt the "v0-1-0" branch to see if that made a difference - it didn't)

**Comment by stsewd** [comment]
![Screenshot_2019-09-23 Versions Read the Docs](https://user-images.githubusercontent.com/4975310/65439380-aca49b80-ddec-11e9-83d3-88802e6df171.png)

You only have those versions. Master is latest, v0-1-0 is stable.

**Comment by odscjames** [comment]
I didn't realise it picked a stable automatically, sorry. I'll try and expand this and may re-open; this is actually me trying a simple reproduce of a problem we are seeing elsewhere in a much more complex setup.

**Comment by odscjames** [comment]
I have expanded this with another commit, and v-0-2-0. So now 0-2-0 should be the stable version and 0-1-0 the old version?

I'm still not seeing a banner on https://odscjameswritessometestdocumentation.readthedocs.io/en/v0-1-0/cats.html , as I would expect.

Can this be reopened? Thanks.

**Comment by stsewd** [comment]
Thanks. I can see that the api response is wrong

```
jQuery32107727874128011452_1569254799014({"html":"...","show_version_warning":true,"version_active":true,"version_compare":{"project":"Version 3.0 of test-builds-stsewd (4802638)","version":"3.0","is_highest":true,"url":"https://test-builds-stsewd.readthedocs.io/es/3.0/","slug":"3.0"},"version_supported":true});
```

**Comment by odscjames** [comment]
Thanks!

**Comment by stsewd** [comment]
Ok, looks like we have tests, and the api response is correct. The problem is that your version isn't compatible with PEP 440 https://www.python.org/dev/peps/pep-0440/. Please check https://docs.readthedocs.io/en/stable/versions.html#how-we-envision-versions-working. If you name your version like `v0.2.0` it should work.

**Comment by odscjames** [comment]
Ah, ok. Thank you.
