### ISSUE TITLE
RTD hosted repo build failure

### ISSUE THREAD

**Issue by rfaircloth-splunk** [readthedocs/readthedocs.org#6206]
## Details

* Read the Docs project URL:
* Build URL (if applicable):
https://readthedocs.org/projects/splunk-connect-for-syslog/builds/9711095/

* Read the Docs username (if applicable):

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*
Error
There was a problem with Read the Docs while building your documentation. Please try again later. However, if this problem persists, please report this to us with your build id (9711095).

Report any build issues here.

**Comment by stsewd** [comment]
There is an error while parsing your submodules file

https://github.com/splunk/splunk-connect-for-syslog/blob/master/.gitmodules#L4-L5

It doesn't have a path or url.

Also, if you don't  need those subomdules, you can skip them using a configuration file 

https://docs.readthedocs.io/en/stable/config-file/v2.html#submodules

**Comment by rfaircloth-splunk** [comment]
thanks a better error message would help but this totally makes sense thank you
