### ISSUE TITLE
PDF creation fails on dynamically-created badge image

### ISSUE THREAD

**Issue by rdnielsen** [readthedocs/readthedocs.org#6207]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/execsql/
* Build URL (if applicable): https://execsql.readthedocs.io/en/latest/
* Read the Docs username (if applicable): dreas.nielsen@gmail.com

## Expected Result

When a source document (RST file) contains a link to a dynamically-created badge, such as:

    .. image:: https://pypip.in/v/execsql/badge.png

The HTML is built correctly, but PDF creation fails and the overall build is reported as failing.

## Actual Result

The HTML is built correctly, but PDF creation fails and the overall build is reported as failing.

**Comment by stsewd** [comment]
I think there are some settings you need to tweak on your conf.py file to support those images on the pdf. Are you able to build the pdf locally?

**Comment by rdnielsen** [comment]
I haven't tried to build the PDF locally.  I'll do that.

**Comment by rdnielsen** [comment]
There's an import error and a syntax error in the exception handler:

```
  File "c:\python\python37\lib\site-packages\sphinx\registry.py", line 473, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "c:\python\python37\lib\site-packages\rst2pdf\pdfbuilder.py", line 129
    except Exception, e:
                    ^
SyntaxError: invalid syntax
```

The import error may be due to running this on Windows; I'll try it this evening on Linux.  The Syntax error is in the Sphinx source.

**Comment by rdnielsen** [comment]
With the following lines added to conf.py

```
extensions = ['rst2pdf.pdfbuilder']
pdf_documents = [('index', 'execsql', 'ExecSQL Documentation', 'Dreas Nielsen')]
```

The PDF is built successfully locally under Linux (Ubuntu 18.04) and Python 2.7.  During the build, the following error messages are issued:

```
[ERROR] image.py:359 The image (/tmp/tmpjuAif_.png, near line UNKNOWN in file /home/dreas/src/python/ExecSQL/doc/source/installation.rst) is broken or in an unknown format
[ERROR] image.py:359 The image (/tmp/tmp9L2Bby, near line UNKNOWN in file /home/dreas/src/python/ExecSQL/doc/source/installation.rst) is broken or in an unknown format
[ERROR] image.py:359 The image (/tmp/tmpllo0_H, near line UNKNOWN in file /home/dreas/src/python/ExecSQL/doc/source/installation.rst) is broken or in an unknown format
```

And the correct images are not displayed in the PDF.  A red circle/slash image is displayed instead.  (Also, the document heading structure is incorrect, but that's a different issue.)

After turning on PDF creation in RTD's advanced settings, updating the repository, and building documentation again with RTD, the build fails with the following message:

```
Extension error:
Could not import extension rst2pdf.pdfbuilder (exception: No module named rst2pdf.pdfbuilder)
```

My takeaway is that previously RTD was not using the `rst2pdf`package, and failing with those images, but it can't use the `rst2pdf` package.  Consequently, creation of PDF files containing those images is still non-functional.

**Comment by stsewd** [comment]
@rdnielsen you need to install the extension on Read the Docs too, you can do it with https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

**Comment by humitos** [comment]
Keep in mind that we don't use `rst2pdf` to build the PDF file. That extension won't work on Read the Docs, even if it's installed.
