### ISSUE TITLE
Definition list is not rendered in bold

### ISSUE THREAD

**Issue by pmantica1** [readthedocs/readthedocs.org#6208]
In https://graphql-compiler.readthedocs.io/en/latest/#the-graphql-compiler definitions lists are rendered in blue while in https://docs.readthedocs.io/en/stable/index.html they are rendered in bold. Do you know why this might this happens?

**Comment by stsewd** [comment]
It's the sphinx version. The Read the Docs theme isn't ready for sphinx2 yet.  https://docs.readthedocs.io/en/stable/index.html  is using sphinx 1.8
