### ISSUE TITLE
Mocked modules are ignored

### ISSUE THREAD

**Issue by Zlopez** [readthedocs/readthedocs.org#6209]
## Details
I'm trying to build documentation for our project, but I'm hitting issue with some modules. So I tried to mock them using your [guide](https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules), but according to the build output the mocked module is ignored.

I tried to first mock whole koji module, which doesn't work. After first try, I noticed that I'm still using Python 2.7, so I switched the interpreter in advanced setting to `CPython 3.x`. You can see the failed output bellow.
Commit with the change: https://github.com/fedora-infra/the-new-hotness/pull/260
Build URL: https://readthedocs.org/projects/the-new-hotness/builds/9714652/

Then I tried to mock only the failing module (I thought, after first try, that module explicitly mentioned in requirements.txt can't be mocked) and the result is bellow.

* Read the Docs project URL: https://readthedocs.org/dashboard/the-new-hotness
* Build URL (if applicable): https://readthedocs.org/projects/the-new-hotness/builds/9714753/
* Read the Docs username (if applicable): Zlopez

## Expected Result

*Mocked module is used*

## Actual Result

*Mocked module is ignored*

**Comment by stsewd** [comment]
Please make use of the sphinx setting https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#confval-autodoc_mock_imports

**Comment by Zlopez** [comment]
@stsewd I used the `autodoc_mock_imports` and I have the same issue.

RP URL: https://github.com/fedora-infra/the-new-hotness/commit/910ab096ff6dcd4e86d3465a51d8469688847f97
Build URL: https://readthedocs.org/projects/the-new-hotness/builds/9720334/

**Comment by stsewd** [comment]
Looks like it's failing on the installation step, when you mock a dependency, you need to exclude it from the installation.

**Comment by stsewd** [comment]
You can use either an environment variable https://docs.readthedocs.io/en/stable/builds.html#build-environment or a custom requirements file when building your docs on read the docs.

**Comment by Zlopez** [comment]
@stsewd Your PR did the trick, thanks for the help with this. :+1:
