### ISSUE TITLE
Remove `SEARCH_ANALYTICS` Feature Flag

### ISSUE THREAD

**Issue by dojutsu-user** [readthedocs/readthedocs.org#6217]
Remove `SEARCH_ANALYTICS` Feature Flag

Ref: [#6192 (comment)](https://github.com/readthedocs/readthedocs.org/pull/6192#issuecomment-536587714)

**Comment by keshav2212** [comment]
I want to resolve this issue. Can you tell me how I proceed for it.

**Comment by saadmk11** [comment]
You need to remove this 
https://github.com/readthedocs/readthedocs.org/blob/58f833d97b760b39f53957771a991f0103bd325d/readthedocs/projects/models.py#L1446

And search the code to find where else its been used. and remove it in those places as well.

**Comment by keshav2212** [comment]
Ok.

**Comment by KartikKapil** [comment]
@dojutsu-user  can i take up this issue , do i have to remove this from all the files or just manage.py??

**Comment by stsewd** [comment]
@KartikKapil you need to remove the flag from all files. You can take this PR as reference https://github.com/readthedocs/readthedocs.org/pull/6245

**Comment by keshav2212** [comment]
@stsewd there are still any mistake on that PR ?

**Comment by stsewd** [comment]
@keshav2212 test should pass, you can check the errors on the travis output, or running the tests locally https://docs.readthedocs.io/en/stable/development/tests.html

**Comment by keshavvinayak01** [comment]
@dojutsu-user This issue is still open right?

**Comment by keshavvinayak01** [comment]
@dojutsu-user @stsewd can you confirm that this solved the issue?  https://github.com/readthedocs/readthedocs.org/pull/6447
