### ISSUE TITLE
Abandoned project name disputes and PEP 541

### ISSUE THREAD

**Issue by felix-hilden** [readthedocs/readthedocs.org#6218]
The RTD [policy](https://docs.readthedocs.io/en/stable/abandoned-projects.html) for abandoned projects lists a number of conditions to be met for an abandoned project to be renamed, allowing for another project to take over the name. I have a question specifically about one of them.

**The project has fewer than 100 monthly pageviews**

[PEP 541](https://www.python.org/dev/peps/pep-0541/), which reportedly influenced your policy as well, allows for transferring the name of an abandoned package for new use. Suppose a transfer like that is made for a new version of some package for which maintenance has stopped. That is, a project with the same name, a similar domain and functionality. The original project is able to pull in a hundred views a month.

URLs for RTD documentation can be easy to remember: `<project>.readthedocs.org` However, in this context, users of the package would be directed to outdated and incorrect documentation. The PyPI name transfer can be an easy way for users to be notified of the abandonment and upgrade. But I understand that it is valuable to also keep the original documentation available.

In such a situation, do you still recommend for the new package to use another name?

**Comment by stsewd** [comment]
I'm not sure if I understood the question. Do you mean a project takes the old name on pypi but not on rtd?

I think the path here would be to rename the old project, and use the same name for the new project, and the new project could link to the old project in case someone needs the old docs.

**Comment by felix-hilden** [comment]
I think you did. A project takes over a name in PyPI, but possibly not in RTD.

I agree that also taking over the RTD name would be beneficial, but your requirement of less than a hundred views a month could be in conflict with it. A link to the old documentation would be appropriate as well, good point.

Thanks for the prompt reply!

**Comment by stsewd** [comment]
> but your requirement of less than a hundred views a month could be in conflict with it

We kind of are very flexible with the requirements as for now, I mean if it is a big project we are more cautious.

@felix-hilden do you have any other questions or a suggestion to update the policy? Or can we close this issue?

**Comment by felix-hilden** [comment]
That's all I wanted to know, thank you! I'll post the actual request when the time comes, if it does. For now, I'm satisfied with the information that it's possible.
