### ISSUE TITLE
Remove /projects/

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6221]
All related code should be removed, that page isn't useful https://readthedocs.org/projects/

https://github.com/readthedocs/readthedocs.org/blob/1ce31662650d6defa434587ec0325f044052ee72/readthedocs/urls.py#L56-L58

**Comment by iambenzo** [comment]
I'd like to pick this one up please

**Comment by saadmk11** [comment]
I think here we want to remove the `ProjectIndex` view which serves https://readthedocs.org/projects/ and Everything related to it.

https://github.com/readthedocs/readthedocs.org/blob/1ce31662650d6defa434587ec0325f044052ee72/readthedocs/projects/views/public.py#L40

**Comment by iambenzo** [comment]
Okay, thanks for the clarification.

I will have a go.
