### ISSUE TITLE
Remove rss feed

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6222]
All code related to this should be removed, isn't useful.

https://github.com/readthedocs/readthedocs.org/blob/1ce31662650d6defa434587ec0325f044052ee72/readthedocs/core/urls/__init__.py#L55-L66

**Comment by Iamshankhadeep** [comment]
@stsewd What do I exactly need to do? and some links where I can study will be useful. Thanks.

**Comment by saadmk11** [comment]
We need to remove this file:
 https://github.com/readthedocs/readthedocs.org/blob/1ce31662650d6defa434587ec0325f044052ee72/readthedocs/projects/feeds.py

and the URL's given above and see if anything else is there related to it and remove them.

**Comment by keshav2212** [comment]
should we remove all the code of the above two functions as well ?
