### ISSUE TITLE
Abandoned project name request: cumulus?

### ISSUE THREAD

**Issue by bli25broad** [readthedocs/readthedocs.org#6223]
I'm trying to import our team's github project https://github.com/klarman-cell-observatory/cumulus into readthedocs and name it "cumulus". When I search "cumulus", I found a project already exists with that name. However when I go to the corresponding readthedocs project, https://readthedocs.org/projects/cumulus/, there is nothing there. However, if I go to https://cumulus.readthedocs.io/en/latest/, I can see some pages, which link to a Git repo. 

I'm confused. Should I consider it as an abandoned project since there is nothing under the project? Or contact the owner of the Git repo linked via cumulus.readthedocs.io? 

If I should contact the owner of the git repo, how do I demonstrate "no response for 6 weeks"?

Thanks for any help!

## Details

* Read the Docs project URL:  https://readthedocs.org/projects/cumulus/
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): 

## Expected Result

*A description of what you wanted to happen*

Please let me know how to proceed.

## Actual Result

*A description of what actually happened*

N/A

**Comment by stsewd** [comment]
You can try to contact to the user on your own and request permissions to the project. If you are unable to contact the user, we can contact the user with their email (this is the 6 weeks count). Looks like the project isn't maintained anyway.

Also the project is on https://readthedocs.org/projects/cumulus/, but looks like it is set to private (we are about to drop privacy levels too #6194)

**Comment by bli25broad** [comment]
@stsewd , thanks a lot! I have contacted the owner but got no replied. Please start the 6 weeks count.

Thanks,
Bo

**Comment by stsewd** [comment]
I've sent the email today.

/remind me about take action on this project in 6 weeks

**Comment by stsewd** [comment]
I wasn't able to send the email to the one associated to the rtd account, it gives me an error. I'm pinning @msessa here. Let us know if you are ok giving permissions to @bli25broad over the Read the Docs project.

**Comment by bli25broad** [comment]
@stsewd , I haven't received any message from @messa.  Should we start to count for 6 weeks?

Thanks,
Bo

**Comment by stsewd** [comment]
I have already set the count, but I wasn't able to send the email to the one that is in their rtd account.

**Comment by messa** [comment]
> @stsewd , I haven't received any message from @messa

You made a typo, I’ve never heard about cumulus :)

**Comment by bli25broad** [comment]
@messa , sorry for the typo!

**Comment by bli25broad** [comment]
@stsewd , since we cannot send the email, should we still wait for 6 weeks?

Thanks,
Bo

**Comment by stsewd** [comment]
Yes, let's just wait in case the github mention works

**Comment by bli25broad** [comment]
Sure thing. Thanks @stsewd .

**Comment by bli25broad** [comment]
Hi @stsewd , is the 6 week clock due next Monday or Tuesday?

**Comment by stsewd** [comment]
@bli25broad November 14th. That's 6 weeks since I tried to contact the user https://github.com/readthedocs/readthedocs.org/issues/6223#issuecomment-538132861

**Comment by bli25broad** [comment]
Hi @stsewd , it's 6 weeks now.

**Comment by stsewd** [comment]
@bli25broad which is your rtd user?

**Comment by bli25broad** [comment]
@stsewd , my rtd user name is bli25broad.

Thanks,
Bo

**Comment by stsewd** [comment]
@bli25broad done, you are owner of the project now
