### ISSUE TITLE
Long project names and recent builds are too big to fit into project list

### ISSUE THREAD

**Issue by robredpath** [readthedocs/readthedocs.org#6225]
## Details

* Read the Docs project URL: n/a
* Build URL (if applicable): n/a
* Read the Docs username (if applicable): opendataservices

## Expected Result

I expect the list of projects on https://readthedocs.org/dashboard/ to show all of the project titles and their most recent build times legible

## Actual Result

Projects with long names *and* recent build times that are long when written out don't fit into the allocated space 
![Screenshot 2019-10-01 at 11 33 13](https://user-images.githubusercontent.com/641009/65955366-db032600-e43f-11e9-9a23-5a66c5bfff77.png)

**Comment by stsewd** [comment]
We are in the process of redesign the site, so probably this issue will be addressed there instead of fixing the current design.

**Comment by robredpath** [comment]
Thanks @stsewd - I look forward to seeing the new design!

**Comment by humitos** [comment]
@robredpath we re-design the dashboard completely. Can you confirm that you still have this issue on beta.readthedocs.org/dashboard/?

**Comment by robredpath** [comment]
@humitos I love the new design! And yes, the problem is fixed in the new design :)

**Comment by humitos** [comment]
Thanks! I'll close this issue as fixed then.
