### ISSUE TITLE
Build exited due to time out for PlatformIO Docs

### ISSUE THREAD

**Issue by ivankravets** [readthedocs/readthedocs.org#6227]
## Details

* Read the Docs project URL: http://docs.platformio.org/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/platformio/builds/9737736/

Is it possible to increase timeout for PlatformIO?

**Comment by stsewd** [comment]
Is the epub format required for your project? I think if you disable it the build could pass. https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html#reduce-formats-you-re-building

**Comment by ivankravets** [comment]
Hi @stsewd. I've just disabled `epub` but it didn't help. See https://readthedocs.org/projects/platformio/builds/9742637/

PDF is important for us. Our docs has a lot of pages, maybe this is a problem. In any case, we generate good traffic for your service. We would be happy to stay with your service.

Is it possible to increase this timeout for PlatformIO?

**Comment by ivankravets** [comment]
Under "good traffic" - I mean "embedded developers", this is a unique audience.

**Comment by stsewd** [comment]
@ivankravets we are ok increasing the build time, but first I wan to try other options.

Do you need the htmlzip output? You can enable just the pdf output with https://docs.readthedocs.io/en/stable/config-file/v2.html#formats

```yaml
formats:
    - pdf
```

**Comment by ivankravets** [comment]
Is it possible to configure this from "Advanced Settings" panel without creating extra YAML? I don't see this option.

**Comment by stsewd** [comment]
@ivankravets no, that's only possible using a configuration file.

**Comment by ivankravets** [comment]
Wow! Full empty docs https://docs.platformio.org/en/latest/#

https://github.com/platformio/platformio-core/blob/develop/.readthedocs.yml

How to revert back? It seems we have huge problems now. We can't build a new version, and can't revert to old.

**Comment by stsewd** [comment]
@ivankravets you are missing to set up the sphinx configuration and probably the requirements installation too, check a minimal example at the beggining https://docs.readthedocs.io/en/stable/config-file/v2.html#configuration-file-v2

We put some defaults otherwise, that may not fit your project.

**Comment by ivankravets** [comment]
I remove that config, I'm not sure that it works correctly. I also disabled all formats from WEB. Let see if it works. We have a lot of files in docs and it makes problems for your servers. We will move docs to our server.

**Comment by ivankravets** [comment]
> We put some defaults otherwise, that may not fit your project.

I tried differently - it does not work :(

See initial version https://github.com/platformio/platformio-core/commit/47ba1277338182b7618e55817f2dbe5fcb1b14c5

**Comment by ivankravets** [comment]
```yaml
version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
```

Build: https://readthedocs.org/projects/platformio/builds/9744430/

**Comment by stsewd** [comment]
@ivankravets you are missing to specify the requirements file or requirements that should be used to build your docs, and looks like you use submodules, you should include the submodules on the config file.

You can check https://docs.readthedocs.io/en/stable/config-file/v2.html#migrating-from-v1 to have an overview of what you should change, or read all the options.

**Comment by ivankravets** [comment]
How about to have default values? If a user does not specify some options, you will do the same what you do now without config.

I'm not sure that it's a good idea to write a full configuration file with Python, PIP, deps, etc. Tomorrow you change something in your config and docs again is offline. It's even better for you if we don't do this manually.

**Comment by stsewd** [comment]
@ivankravets we have some defaults, but not all projects fit that (you can check the default value on each option). Like we don't fetch submodules by default bc not all projects require that, or we don't try to install the first requirements file that we find (this was causing a lot of problems to some users). We also don't merge the options from the web interface when using a config file, this is to have only one canonical source of settings.

**Comment by ivankravets** [comment]
Default values are good for us. Is it possible to increase timeout just for our project? Or this value is global?

**Comment by stsewd** [comment]
@ivankravets yes, we can increase the build time for your project, but we would appreciate if you first try the other suggestions like disabling the formats that you don't need, since our resources are limited.

**Comment by ivankravets** [comment]
Do you have any ideas?

- https://github.com/platformio/platformio-core/blob/develop/.readthedocs.yml
- https://readthedocs.org/projects/platformio/builds/9745441/

**Comment by stsewd** [comment]
No, but thanks for disabling the other formats. I'll play increasing the build time now, I'll be triggering some builds on latest, please keep the changes for a minute.

**Comment by ivankravets** [comment]
Thanks! Should I close this issue?

**Comment by stsewd** [comment]
I have increased the build time to 20 minutes (it was timing out around 14). Builds are passing now https://readthedocs.org/projects/platformio/builds/9745570/

**Comment by ivankravets** [comment]
THANK YOU SO MUCH! 😊

**Comment by ivankravets** [comment]
It seems that 20 minutes is not enough :( 
- https://readthedocs.org/projects/platformio/builds/9745987/

It takes a few minutes on my machine for the full build. However, I've not tested latex. The only html.

Could we increase to 30 minutes?

**Comment by stsewd** [comment]
This is weird, some times the build takes ~700 seconds and others +1200 seconds.

**Comment by stsewd** [comment]
I triggered 3 consecutive builds, all of them passed. Not sure if it is going to time out in another builds.

![Screenshot_2019-10-02 Builds Read the Docs](https://user-images.githubusercontent.com/4975310/66089613-b09b9080-e545-11e9-96e8-32ee1e636ed9.png)

**Comment by ivankravets** [comment]
https://readthedocs.org/projects/platformio/builds/

Did you make any changes a few days ago? It has been working well for the last 3 years. Could we increase the timeout to 30min? It seems that it depends on general server loading. It's better to decrease CPU resources but increase timeout. So, builds will not fail. Thanks!

**Comment by stsewd** [comment]
so, I found the problem.

We are testing using a new build server, looks like the I/O operations are slower than the others. I put your project out of that builder for now. I'm reporting this back to allow us to improve it.

**Comment by ivankravets** [comment]
Hi @stsewd !

Sorry, we experience this issue again :( https://readthedocs.org/projects/platformio/builds/10428325/

Thanks in advance for your help!

**Comment by stsewd** [comment]
@ivankravets sorry for the late reply, I can see some of your builds are passing, but not consistently. I have increased the build resources for your project.

**Comment by ivankravets** [comment]
Thanks, Santos! 🤝

**Comment by ivankravets** [comment]
Hi @stsewd ,

Could you help with https://readthedocs.org/projects/platformio/builds/?

We can't build docs :(

P.S: Do you have problems only with us? :(

**Comment by humitos** [comment]
> Could you help with [readthedocs.org/projects/platformio/builds](https://readthedocs.org/projects/platformio/builds/)?

@ivankravets I understand that build worked. Although, since there are lot of "LaTex Warnings", RTD chunked the output to be able to save it on the DB: `Output is too big. Chunked at 4718592 bytes`

Unfortunately, the build is reporting as FAILED, but that's not true. This is a bug, but you should see your PDF updated properly. Can you double check that?

**Comment by ivankravets** [comment]
> Can you double check that?

You are right, docs is updated. Thanks, I will ignore this error.

**Comment by ivankravets** [comment]
@humitos please help https://readthedocs.org/projects/platformio/builds/
