### ISSUE TITLE
HTTPS -> HTTP redirect in URLs missing a trailing slash

### ISSUE THREAD

**Issue by davidfischer** [readthedocs/readthedocs.org#6229]
Under some circumstances, we are redirecting docs from HTTPS -> HTTP. We basically never want to do this.

```bash
$ curl -IL https://flask.palletsprojects.com/en/1.1.x/api
HTTP/2 301
...
location: http://flask.palletsprojects.com/en/1.1.x/api/
...
```
This is most visible with dirhtml builds where a trailing slash is often omitted and curling `https://flask.palletsprojects.com/en/1.1.x/api/` directly is fine. This affects subdomain docs too (`*.readthedocs.io`) but in a different manner (HTTPS -> HTTP -> HTTPS again):

```bash
$ curl -IL https://flask.readthedocs.io/en/1.1.x/api
HTTP/1.1 301 Moved Permanently
...
Location: http://flask.readthedocs.io/en/1.1.x/api/
...

HTTP/1.1 301 Moved Permanently
...
Location: https://flask.readthedocs.io/en/1.1.x/api/
...
```

It affects non-dirhtml docs as well although it isn't as visible because the issue is hit pretty infrequently because most requests end with `.html`:

```bash
$ curl -IL https://docs.readthedocs.io/en/stable/config-file
HTTP/1.1 301 Moved Permanently
...
Location: http://docs.readthedocs.io/en/stable/config-file/
```

~My current best guess is that this is due to the [nginx `try_files` directive](https://nginx.org/en/docs/http/ngx_http_core_module.html#try_files) using the first listener which is port 80.~ For subdomain docs, we have a blanket HTTP -> HTTPS redirect so this problem is masked although not really resolved. We can't do a blanket redirect for all custom domains because many people have not correctly setup their custom domain such that RTD can issue a certificate. (see https://github.com/readthedocs/readthedocs.org/issues/4641)

This also affects the redirects in place for `$lang/$version`:

```bash
$ curl -IL https://docs.readthedocs.io/en/stable
HTTP/1.1 301 Moved Permanently
...
Location: http://docs.readthedocs.io/en/stable/
...
```

**Comment by davidfischer** [comment]
Based on my reading, I think the fix may be to turn [`absolute_redirect off;`](http://nginx.org/en/docs/http/ngx_http_core_module.html#absolute_redirect) in nginx. It looks like nginx issues redirects under some circumstances and it uses the same `$scheme` as the request. Since SSL is terminated at the load balancer, the `$scheme` is `http` rather than `https`.

**Comment by Patil2099** [comment]
@davidfischer Can I work on this issue?

**Comment by stsewd** [comment]
@Patil2099 this requires access to our ops repo, that repo is private.

**Comment by davidfischer** [comment]
We rolled the fix out to this this week (`absolute_redirect off`) and it seems to be working without issue.
