### ISSUE TITLE
Custom 404 issue with dirhtml

### ISSUE THREAD

**Issue by davidfischer** [readthedocs/readthedocs.org#6230]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/flask/

## Expected Result

When doing a dirhtml build and having a custom 404 page, the paths to static assets (JS/CSS) are broken unless the request ends with a trailing slash and is one level deep.

Note: I pointed the Flask maintainers (@davidism specifically) at the [sphinx-not-found extension](https://sphinx-notfound-page.readthedocs.io/en/latest/). That may solve this problem although I haven't tracked down the underlying issue.

## Actual Result

* OK - https://flask.palletsprojects.com/en/1.1.x/asdfasdf/
* Static asset path issue - https://flask.palletsprojects.com/en/1.1.x/asdfasdf
* OK - https://flask.palletsprojects.com/en/1.1.x/asdfasdf/asdf
* Static asset path issue - https://flask.palletsprojects.com/en/1.1.x/asdfasdf/asdf/

**Comment by humitos** [comment]
What would be the solution for this?

All the assets are relative in that HTML, which makes the trailing `/` mandatory --otherwise, it ended up in an upper level that the one it's expecting.

`sphinx-notfound-page` page solves this by making all the links absolute (see https://sphinx-notfound-page.readthedocs.io/not/found/page.html).

**Comment by humitos** [comment]
Similar to the case described in the original post:

* https://sphinx-notfound-page.readthedocs.io/notfound/
* https://sphinx-notfound-page.readthedocs.io/notfound

**Comment by ericholscher** [comment]
Yea, this just feels like an issue with their 404 page, not anything we can do about it.

**Comment by humitos** [comment]
I'm closing this issue for now. Feel free to reopen if you consider that it's still valid.

**Comment by stsewd** [comment]
@humitos it's still valid. I still can reproduce the examples from David. Or does the project need to trigger a new build?

**Comment by davidism** [comment]
I think I just need to enable that extension when building on Read the Docs. Haven't had a chance to work on the docs in a while, but I don't see how there's anything RTD can do for this.
