### ISSUE TITLE
Sphinx error: missing master file

### ISSUE THREAD

**Issue by ekleinod** [readthedocs/readthedocs.org#6232]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/refereemanager/
* Build URL (if applicable): https://readthedocs.org/projects/refereemanager/builds/9740136/
* Read the Docs username (if applicable): ekleinod

## Expected Result

I expected the documentation to be built.

## Actual Result

An error occurred:

    Sphinx error:
    master file /home/docs/checkouts/readthedocs.org/user_builds/refereemanager/checkouts/latest/docs/contents.rst not found

## My tries to fix the problem

I read the corresponding issue and stackoverflow, all suggested to include the line

     master_doc = 'index'

in `conf.py`, which I did: https://gitlab.com/open-tt/refereemanager/blob/master/docs/source/conf.py

The read the docs configuration file looks ok for me too: https://gitlab.com/open-tt/refereemanager/blob/master/readthedocs.yml

I don't know what to do else, do you have a suggestion what I did wrong?

Thanks.

**Comment by stsewd** [comment]
Your conf.py file is on ` docs/source/conf.py`, you should put that on your rtd config file https://gitlab.com/open-tt/refereemanager/blob/master/readthedocs.yml

**Comment by ekleinod** [comment]
D'oh, now I'm feeling really stupid, but I did not see the problem. Sorry for bothering you.

Thanks for the fast and brilliant response :grin:
