### ISSUE TITLE
Position of the navigation buttons

### ISSUE THREAD

**Issue by rengel-de** [readthedocs/readthedocs.org#6240]
## Problem

With longer text one always has to scroll to the bottom to reach the 'Previous' and 'Next' navigation buttons. This makes hard to quickly step through the documentation.

## Suggested Improvement

Put the navigation buttons at the top.

**Comment by stsewd** [comment]
Hi @rengel-de, you can see all option from the Read the Docs theme on https://sphinx-rtd-theme.readthedocs.io/en/latest/configuring.html

What you are looking is the `prev_next_buttons_location` setting.

**Comment by rengel-de** [comment]
Thank you! And sorry, I'm just starting to use Sphinx.
