### ISSUE TITLE
Remove unused code from view and template

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6250]
Person isn't used, and we always expect to have `tags` in the context.

View

https://github.com/readthedocs/readthedocs.org/blob/0c69e7a0411d423cb7cbfc8e63fe0b5d530c7465/readthedocs/projects/views/public.py#L46-L62

Template
https://github.com/readthedocs/readthedocs.org/blob/master/readthedocs/templates/projects/project_list.html

Ref https://github.com/readthedocs/readthedocs.org/pull/6228#discussion_r332146543

**Comment by thegtzz** [comment]
hi, I'am new either in django or open source projects. What should I do with this issue exactly? Could you explain, please?
