### ISSUE TITLE
Increase build timeout limit for Koalas project

### ISSUE THREAD

**Issue by HyukjinKwon** [readthedocs/readthedocs.org#6254]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/koalas/builds/
* Build URL (if applicable): https://koalas.readthedocs.io/en/latest/?badge=latest
* Read the Docs username (if applicable): HyukjinKwon

## Expected Result

Build pass without timeout

![Screen Shot 2019-10-08 at 4 50 19 PM](https://user-images.githubusercontent.com/6477701/66377027-bda7fc00-e9eb-11e9-868b-8e14adf5c5d2.png)

## Actual Result

Build timeout

![Screen Shot 2019-10-08 at 4 50 09 PM](https://user-images.githubusercontent.com/6477701/66377040-c0a2ec80-e9eb-11e9-949c-e7423211eda2.png)

**Comment by HyukjinKwon** [comment]
To speed up, I had to disable PDF build and EPUB build; however, we still intermediately face this timeout (which spams emails .. :( .. ).

Can I ask to increase the timeout?

**Comment by HyukjinKwon** [comment]
To speed up, I had to disable PDF build and EPUB build; however, we still intermittently face this timeout (which spams emails .. :( .. ).

Can I ask to increase the timeout?

**Comment by humitos** [comment]
Hi @HyukjinKwon! I just took a look at your builds and I found that that all the builds were executed on one the same server (build04). We are having an issue with this server (it's executing too many builds at the same time) that we hopefully fix soon.

**Comment by HyukjinKwon** [comment]
Thanks! I am actively working on that project. I will update if I happen to find out this issue isn't persistent anymore!

**Comment by stsewd** [comment]
The project is failing for another reason now

```
Collecting package metadata: ...working... done
Solving environment: ...working... failed

ResolvePackageNotFound: 
  - java-jdk=8
```

The project doesn't have build04 as builder anymore.

**Comment by HyukjinKwon** [comment]
It suddenly fails there. I'll check and update within few days.

**Comment by HyukjinKwon** [comment]
Hi, the error was temporary. The problematic package started to install properly. https://readthedocs.org/projects/koalas/builds/9773902/

**Comment by HyukjinKwon** [comment]
Hi, I still face time out intermittently. Can I ask to increase time out please? I am handling flakiness of `java-jdk=8` as well separately but this timeout affects the build more seriously.

**Comment by humitos** [comment]
Hi @HyukjinKwon! I increased time and memory for your project. I'm closing this issue. Feel free to re-open if you think it's needed. Also, let me know if it's building properly :)

**Comment by HyukjinKwon** [comment]
Thank you so much guys!

**Comment by HyukjinKwon** [comment]
![Screen Shot 2019-10-11 at 8 53 05 PM](https://user-images.githubusercontent.com/6477701/66649449-28b23680-ec69-11e9-8207-55f5dc705724.png)

Eh, sorry @humitos can you double check if the time is increased?

**Comment by HyukjinKwon** [comment]
Also, seems like I can't reopen this issue :(. 
![Screen Shot 2019-10-11 at 8 54 01 PM](https://user-images.githubusercontent.com/6477701/66649495-48495f00-ec69-11e9-9787-2d4912526e48.png)

**Comment by stsewd** [comment]
Last builds are passing now

**Comment by HyukjinKwon** [comment]
![Screen Shot 2019-10-13 at 11 18 01 AM](https://user-images.githubusercontent.com/6477701/66710032-34a61180-edab-11e9-94e2-e455af00fad3.png)

eh, seems still failing. Can I ask to increase the timeout?

**Comment by stsewd** [comment]
![Screenshot_2019-10-12 Builds Read the Docs](https://user-images.githubusercontent.com/4975310/66710459-7fd60b00-ed3e-11e9-96cb-1852ff6705a6.png)

**Comment by HyukjinKwon** [comment]
Thanks for checking it closely @stsewd 

BTW, did the build in Read the docs decrease timeout lately?

Seems the builds started to fail again:

<img width="875" alt="Screen Shot 2019-10-15 at 8 43 59 AM" src="https://user-images.githubusercontent.com/6477701/66806546-1c0f3600-ef28-11e9-82ec-c286c557728e.png">
<img width="916" alt="Screen Shot 2019-10-15 at 7 41 32 AM" src="https://user-images.githubusercontent.com/6477701/66806547-1c0f3600-ef28-11e9-9951-ec00c870cc0a.png">

**Comment by stsewd** [comment]
> BTW, did the build in Read the docs decrease timeout lately?

No, we haven't. But looks like the conda step is taking a lot of the time

Do you need both channels?

https://github.com/databricks/koalas/blob/4022df3d97b3a9c12ed842cc1e7e0f43b100af56/dev/readthedocs-environment.yml#L6-L7

Conda gets slower depending on the number of channels.

Also, if you agree, we can try using the last version of conda for your project (there are some improvements to make it fast)

https://docs.readthedocs.io/en/stable/guides/feature-flags.html#available-flags

**Comment by HyukjinKwon** [comment]
Let me give a shot to don't use both channels (opened a PR https://github.com/databricks/koalas/pull/932). I will update you by EOD of tomorrow.

I will try `UPDATE_CONDA_STARTUP` as well.

However, I was wondering why it suddenly times out at 600 seconds instead of 900 seconds, which was used to be.

**Comment by stsewd** [comment]
> However, I was wondering why it suddenly times out at 600 seconds instead of 900 seconds, which was used to be.

Probably a bug on our code, sometimes if the command fails the command doesn't get updates on the db https://github.com/readthedocs/readthedocs.org/issues/4288

**Comment by HyukjinKwon** [comment]
Thanks, @stsewd, I will wait for the fix and follow what you guided first, and see what happens.

**Comment by stsewd** [comment]
I have enabled the flag, but it stills times out. I'm increasing the build time to 15 min

**Comment by stsewd** [comment]
Looks like is passing again, let me know if it keeps timing out

**Comment by HyukjinKwon** [comment]
Awesome!
