### ISSUE TITLE
Command killed due to excessive memory consumption

### ISSUE THREAD

**Issue by sjrowlinson** [readthedocs/readthedocs.org#6256]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/finesse/
* Build URL (if applicable): https://readthedocs.org/projects/finesse/builds/9771507/
* Read the Docs username (if applicable): sjrowlinson

## Expected Result

Successful build.

## Actual Result

Build failed due to excessive memory consumption:

![failed_build](https://user-images.githubusercontent.com/16781733/66414070-96076280-e9f0-11e9-8538-3abefcd7f3f3.png)

The log implies that it fails during the autosummary process but I can't be too sure that's the culprit yet (as previous builds have succeeded through this step).

**Comment by stsewd** [comment]
Looks like your project was building ~2 weeks ago. Any big changes around that time?

Also, looks like you are using a configuration file with settings that aren't supported when using conda https://github.com/readthedocs/readthedocs.org/issues/5388

**Comment by sjrowlinson** [comment]
The only change around that time which would affect the documentation building (I think) is the creation of quite a few more API documentation pages (around 40 or so) - so that `sphinx-autogen` (which I call recursively on all the docs/api directories via `conf.py`) has more work to do. It is after these new pages were created that I noticed the builds failing due to excessive memory consumption.

**Comment by stsewd** [comment]
I've increased the build time to 15 min and memory to 1200 mb, build is passing now https://readthedocs.org/projects/finesse/builds/9818824/

**Comment by AlexKuhnle** [comment]
For my repository I ran into a similar issue, but already in the very beginning when installing necessary requirements: [link](https://readthedocs.org/projects/tensorforce/builds/9937853/). Is there a way to prevent this from happening?

**Comment by sjrowlinson** [comment]
> I've increased the build time to 15 min and memory to 1200 mb, build is passing now https://readthedocs.org/projects/finesse/builds/9818824/

@stsewd Hi again, thanks very much for this. Unfortunately this error (of excessive memory consumption) has resurfaced even with these limits increased. Do you have any advice to get around this? I'm not aware of any of our dependencies being so large as to contribute a significant chunk of this 1200 MB limit but if it is anything I suspect that it will probably be `suitesparse` which is installed via conda through our environment file. As far as I'm aware there is no way around using conda for this as I don't think `suitesparse` is a default package on the RTD servers.

Is there any metric on your side which would show just how much memory a build for this project is actually consuming?

Thanks for any help again in advance!

**Comment by stsewd** [comment]
@sjrowlinson I'll try to dig this a little more and try to activate a flag to run your project with the latest version of conda (there are some improvements related to memory consumption)

**Comment by sjrowlinson** [comment]
@stsewd Thanks for taking the time to help with this. If it ends up being too much of a resource drain then I'll try switching to using Sphinx AutoAPI to avoid having to install the package - but that's mostly a last resort, as we may end up needing the package to be installed for some things.

**Comment by stsewd** [comment]
@sjrowlinson I have increased time and memory, the build is passing now https://readthedocs.org/projects/finesse/builds/10143568/

**Comment by sjrowlinson** [comment]
@stsewd That's great! Thanks again for the help.
