### ISSUE TITLE
Build Timeout

### ISSUE THREAD

**Issue by jasonyin** [readthedocs/readthedocs.org#6260]
## Details

* Read the Docs project URL:https://oracle-cloud-infrastructure-python-sdk.readthedocs.io
* Build URL (if applicable):https://readthedocs.org/projects/oracle-cloud-infrastructure-python-sdk/builds/9773307/
* Read the Docs username (if applicable): jasonyin

## Expected Result

Build pass

## Actual Result

Timeout

## Comments

Same code which got doc build pass here: https://readthedocs.org/projects/oracle-cloud-infrastructure-python-sdk/builds/9772534/.

**Comment by stsewd** [comment]
Hi @jasonyin, sorry for the problem. We are testing a different server to build docs. Your project should build fine now https://readthedocs.org/projects/oracle-cloud-infrastructure-python-sdk/builds/9773484/

ref https://github.com/readthedocs/readthedocs.org/issues/6227

**Comment by jasonyin** [comment]
thanks @stsewd , I can confirm the issue resolved. BTW, is there a way for us to get notice for these kind of testing on production? So we can plan our release accordingly?

**Comment by stsewd** [comment]
We don't have a way to communicate that currently, we just sample random projects, but usually it shouldn't cause this kind of trouble.
