### ISSUE TITLE
Night theme

### ISSUE THREAD

**Issue by Seedoorf** [readthedocs/readthedocs.org#6261]
It can be difficult to read some documentation for a long time. Dark theme can solve this issue. For example, night/light theme switcher

**Comment by humitos** [comment]
Hi! Thanks for the suggestion.

This is something that Read the Docs won't implement in the near future at least. We already have a theme (https://github.com/rtfd/sphinx_rtd_theme) and takes us a lot of effort to maintain.

Also, there are other themes that could be used by the author of the documentation if they consider (like https://sphinx-themes.org/html/groundwork-sphinx-theme/groundwork/index.html).

Finally, the browser itself (Firefox, at least) implements a Reading Mode + Dark theme that does all of this automatically.

Unfortunately, we don't have the resources. I'm sorry.
