### ISSUE TITLE
Message about number of inactive versions shown

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#6265]
The new version listing page with the filter to activate versions is really cool. Although, it hides that only the first 100 versions are shown:

https://github.com/readthedocs/readthedocs.org/blob/558e143743576ada85d9a0a4abb5cc0693d3181d/readthedocs/projects/views/public.py#L370

This could confuse users, thinking that we are showing all the inactive versions. To solve this, I think we could add a small text saying that we only show the first 100 inactive versions.

**Comment by davidfischer** [comment]
I'm on board with this. One pattern I've seen is to only show this message when there are 100 inactive versions.
