### ISSUE TITLE
Allow CORS from rendered page on readthedocs

### ISSUE THREAD

**Issue by johanneskoester** [readthedocs/readthedocs.org#6268]
## Details

* Read the Docs project URL: https://snakemake.readthedocs.io/en/latest
* Build URL (if applicable):
* Read the Docs username (if applicable): johanneskoester

## Expected Result

I have included a raw HTML snippet, that is supposed to render a dynamic badge from https://badge.dimensions.ai. The rendering fails though, because a cross site scripting attempt is blocked due to CORS settings.

## Actual Result

The badge is not properly rendered because the script aborts.
See the failing example here: https://snakemake.readthedocs.io/en/latest/

## Request
Would it be possible to allow such cross-site scripting, maybe via a white list? https://dimensions.ai is a public, trusted provider of scientific citation information.

**Comment by stsewd** [comment]
Hi, I can see the badge

![Screenshot_2019-10-09 Snakemake — Snakemake 5 7 0+6 g17c677b5 dirty documentation](https://user-images.githubusercontent.com/4975310/66517537-e8a45580-eaa8-11e9-8274-663b91c05971.png)

If there is a problem with CORS, the website that _owns_ the resource should allow to load that resource from `readthedocs.io`, no Read the Docs.

If you are trying to load a resource from Read the Docs on _another page_, that's a problem that we can solve with the proper CORS headers, but isn't what you are describing.

**Comment by johanneskoester** [comment]
Thanks @stsewd, that was a misunderstanding from my side then. I will contact the owners.
