### ISSUE TITLE
Build error with build id #9781095

### ISSUE THREAD

**Issue by pmoura** [readthedocs/readthedocs.org#6270]
## Details:

* Project URL: https://readthedocs.org/projects/logtalk3/
* Build URL(if applicable): https://readthedocs.org/projects/logtalk3/builds/9781095/
* Read the Docs username(if applicable): AnonymousUser

## Expected Result

Build marked as successful as the log shows that indeed it succeeded.

## Actual Result

Build marked as failed despite being successful.

**Comment by humitos** [comment]
It looks like a temporary error. It's the only build that has failed in the last +50 builds. It seems the server was overloaded. Nothing to worry about for now. Thanks!
