### ISSUE TITLE
fortran compiler issue 

### ISSUE THREAD

**Issue by ashleyzcy** [readthedocs/readthedocs.org#6282]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pyemsoftreadthedocs/
* Build URL (if applicable): https://pyemsoftreadthedocs.readthedocs.io/en/latest/
* Read the Docs username (if applicable): ashleyzcy

## Expected Result

shows the module contents (functions, types)

## Actual Result
Failed to import module. I can not pip install the f90wrap (defined in the requirements.txt) ,which is required to import the module, because there is no Fortran compiler..

Checked the: Use system packages option in the advanced settings. 

<details><summary>Build Details</summary>
<p>
Requirement already satisfied: numpy in /home/docs/.pyenv/versions/3.7.3/lib/python3.7/site-packages (from -r docs/requirements.txt (line 1)) (1.16.3)
Collecting f90wrap (from -r docs/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/dc/7c/8ba6fd3277470d134007bf174eca95500a534933a499e46327fe41bdf5b3/f90wrap-0.2.1.tar.gz
Building wheels for collected packages: f90wrap
  Building wheel for f90wrap (setup.py): started
  Building wheel for f90wrap (setup.py): finished with status 'error'
  ERROR: Complete output from command /home/docs/checkouts/readthedocs.org/user_builds/pyemsoftreadthedocs/envs/latest/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-0oukfkoa/f90wrap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-qgs487e0 --python-tag cp37:
  ERROR: running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building extension "f90wrap.sizeof_fortran_t" sources
  f2py options: []
    adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/f90wrap/fortranobject.c' to sources.
    adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/f90wrap' to include_dirs.
  building extension "f90wrap.arraydata" sources
  build_src: building npy-pkg config files
  running build_py
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/f90wrap
  copying f90wrap/__init__.py -> build/lib.linux-x86_64-3.7/f90wrap
  copying f90wrap/fortrantype.py -> build/lib.linux-x86_64-3.7/f90wrap
  copying f90wrap/f90wrapgen.py -> build/lib.linux-x86_64-3.7/f90wrap
  copying f90wrap/parser.py -> build/lib.linux-x86_64-3.7/f90wrap
  copying f90wrap/codegen.py -> build/lib.linux-x86_64-3.7/f90wrap
  copying f90wrap/fortran.py -> build/lib.linux-x86_64-3.7/f90wrap
  copying f90wrap/latex.py -> build/lib.linux-x86_64-3.7/f90wrap
  copying f90wrap/pywrapgen.py -> build/lib.linux-x86_64-3.7/f90wrap
  copying f90wrap/transform.py -> build/lib.linux-x86_64-3.7/f90wrap
  copying f90wrap/six.py -> build/lib.linux-x86_64-3.7/f90wrap
  copying f90wrap/runtime.py -> build/lib.linux-x86_64-3.7/f90wrap
  running build_ext
  customize UnixCCompiler
  customize UnixCCompiler using build_ext
  get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
  customize Gnu95FCompiler
  Could not locate executable gfortran
  Could not locate executable f95
  customize IntelFCompiler
  Could not locate executable ifort
  Could not locate executable ifc
  customize LaheyFCompiler
  Could not locate executable lf95
  customize PGroupFCompiler
  Could not locate executable pgfortran
  customize AbsoftFCompiler
  Could not locate executable f90
  Could not locate executable f77
  customize NAGFCompiler
  customize VastFCompiler
  customize CompaqFCompiler
  Could not locate executable fort
  customize IntelItaniumFCompiler
  Could not locate executable efort
  Could not locate executable efc
  customize IntelEM64TFCompiler
  customize GnuFCompiler
  Could not locate executable g77
  customize G95FCompiler
  Could not locate executable g95
  customize PathScaleFCompiler
  Could not locate executable pathf95
  customize NAGFORCompiler
  Could not locate executable nagfor
  don't know how to compile Fortran code on platform 'posix'
  warning: build_ext: f77_compiler=None is not available.
  
  building 'f90wrap.sizeof_fortran_t' extension
  error: extension 'f90wrap.sizeof_fortran_t' has Fortran sources but no Fortran compiler found
  ----------------------------------------
  ERROR: Failed building wheel for f90wrap
  Running setup.py clean for f90wrap
Failed to build f90wrap
Installing collected packages: f90wrap
  Running setup.py install for f90wrap: started
    Running setup.py install for f90wrap: finished with status 'error'
    ERROR: Complete output from command /home/docs/checkouts/readthedocs.org/user_builds/pyemsoftreadthedocs/envs/latest/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-0oukfkoa/f90wrap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gv2z213y/install-record.txt --single-version-externally-managed --compile --install-headers /home/docs/checkouts/readthedocs.org/user_builds/pyemsoftreadthedocs/envs/latest/include/site/python3.7/f90wrap:
    ERROR: running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building extension "f90wrap.sizeof_fortran_t" sources
    f2py options: []
      adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/f90wrap/fortranobject.c' to sources.
      adding 'build/src.linux-x86_64-3.7/build/src.linux-x86_64-3.7/f90wrap' to include_dirs.
    building extension "f90wrap.arraydata" sources
    build_src: building npy-pkg config files
    running build_py
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/f90wrap
    copying f90wrap/__init__.py -> build/lib.linux-x86_64-3.7/f90wrap
    copying f90wrap/fortrantype.py -> build/lib.linux-x86_64-3.7/f90wrap
    copying f90wrap/f90wrapgen.py -> build/lib.linux-x86_64-3.7/f90wrap
    copying f90wrap/parser.py -> build/lib.linux-x86_64-3.7/f90wrap
    copying f90wrap/codegen.py -> build/lib.linux-x86_64-3.7/f90wrap
    copying f90wrap/fortran.py -> build/lib.linux-x86_64-3.7/f90wrap
    copying f90wrap/latex.py -> build/lib.linux-x86_64-3.7/f90wrap
    copying f90wrap/pywrapgen.py -> build/lib.linux-x86_64-3.7/f90wrap
    copying f90wrap/transform.py -> build/lib.linux-x86_64-3.7/f90wrap
    copying f90wrap/six.py -> build/lib.linux-x86_64-3.7/f90wrap
    copying f90wrap/runtime.py -> build/lib.linux-x86_64-3.7/f90wrap
    running build_ext
    customize UnixCCompiler
    customize UnixCCompiler using build_ext
    get_default_fcompiler: matching types: '['gnu95', 'intel', 'lahey', 'pg', 'absoft', 'nag', 'vast', 'compaq', 'intele', 'intelem', 'gnu', 'g95', 'pathf95', 'nagfor']'
    customize Gnu95FCompiler
    Could not locate executable gfortran
    Could not locate executable f95
    customize IntelFCompiler
    Could not locate executable ifort
    Could not locate executable ifc
    customize LaheyFCompiler
    Could not locate executable lf95
    customize PGroupFCompiler
    Could not locate executable pgfortran
    customize AbsoftFCompiler
    Could not locate executable f90
    Could not locate executable f77
    customize NAGFCompiler
    customize VastFCompiler
    customize CompaqFCompiler
    Could not locate executable fort
    customize IntelItaniumFCompiler
    Could not locate executable efort
    Could not locate executable efc
    customize IntelEM64TFCompiler
    customize GnuFCompiler
    Could not locate executable g77
    customize G95FCompiler
    Could not locate executable g95
    customize PathScaleFCompiler
    Could not locate executable pathf95
    customize NAGFORCompiler
    Could not locate executable nagfor
    don't know how to compile Fortran code on platform 'posix'
    warning: build_ext: f77_compiler=None is not available.
    
    building 'f90wrap.sizeof_fortran_t' extension
    error: extension 'f90wrap.sizeof_fortran_t' has Fortran sources but no Fortran compiler found
    ----------------------------------------
ERROR: Command "/home/docs/checkouts/readthedocs.org/user_builds/pyemsoftreadthedocs/envs/latest/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-0oukfkoa/f90wrap/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gv2z213y/install-record.txt --single-version-externally-managed --compile --install-headers /home/docs/checkouts/readthedocs.org/user_builds/pyemsoftreadthedocs/envs/latest/include/site/python3.7/f90wrap" failed with error code 1 in /tmp/pip-install-0oukfkoa/f90wrap/
</p>
</details>

**Comment by humitos** [comment]
Hi @ashleyzcy! Can you be more specific about the issue that you are reporting? Are you able to build the docs locally? Are you installing all the dependencies properly on RTD? Isn't needed to setup an environment variable telling Python where Fortran compiler can be found?

**Comment by ashleyzcy** [comment]
> Hi @ashleyzcy! Can you be more specific about the issue that you are reporting? Are you able to build the docs locally? Are you installing all the dependencies properly on RTD? Isn't needed to setup an environment variable telling Python where Fortran compiler can be found?

Yes. I am able to build locally. In order to import the modules, I need to have numpy (installed) and f90wrap (have some issue with this, which needs a Fortran compiler) installed. Thanks for the advice. I am currently setting up the environment variable for the conf.py. I will keep this post updated if I have any luck.

**Comment by rafa-guedes** [comment]
@ashleyzcy same issue here.. Have you had any luck?

**Comment by ashleyzcy** [comment]
@rafa-guedes not sure if there is any solution out there...Good luck

**Comment by humitos** [comment]
I think the problem here is that the Read the Docs image used to build documentation does no have a fortran compilar (`gfortran`, for example). This is the Dockerfile we use to build the and I don't see a fortran compiler there: https://github.com/readthedocs/readthedocs-docker-images/blob/master/Dockerfile

**Comment by humitos** [comment]
> I can not pip install the f90wrap (defined in the requirements.txt) ,which is required to import the module, because there is no Fortran compiler..

You may want to [mock this module](https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules) in order to build your documentation. From the online content of your docs, I don't think you need that module for your docs. Otherwise, you can use [`autoapi`](https://sphinx-autoapi.readthedocs.io/)

**Comment by ashleyzcy** [comment]
@humitos thanks. That works out nicely! i just added one line to mock all the required packages to import my modules. 

autodoc_mock_imports = ["f90wrap", "_pyEMsoft", "_pyEMsoft","numpy"]
