### ISSUE TITLE
error: command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by BingmingWong** [readthedocs/readthedocs.org#6284]
## Details

* Read the Docs project URL:http://python-online.cn
* Build URL (if applicable):https://readthedocs.org/projects/mings-blog/builds/9799650/
* Read the Docs username (if applicable):WONGBINGMING

## Expected Result

build successfully when i change the python interpreter from python 2 to python 3

## Actual Result

error: command 'gcc' failed with exit status 1

**Comment by stsewd** [comment]
Does your project work locally if you use python3?
