### ISSUE TITLE
This project is currently disabled and can't trigger new builds

### ISSUE THREAD

**Issue by xylodev** [readthedocs/readthedocs.org#6291]
## Details

* Read the Docs project URL: https://amazon-payments-advanced.readthedocs.io
* Build URL (if applicable):
* Read the Docs username (if applicable): xylodev

## Expected Result

I'd like to get a new documentation build from the latest changes committed to the git repository.

## Actual Result

In the "Builds" section, when I select "latest" version from the dropdown and I click on the "Build version" button, I am getting the following error message:

```
This project is currently disabled and can't trigger new builds.
```

and no build is triggered. Seems like our account has been suspended, but I have no idea why, we're building docs once per month or so.

**Comment by stsewd** [comment]
Looks like your uses was banned by mistake, sorry about that. Everything should be working now, let me know if there is any other problem

**Comment by pierrebaudot** [comment]
Hello, 
I get the same message "This project is currently disabled and can't trigger new builds."
project: https://github.com/pierrebaudot/infotopopy.git 
Read the Docs username (if applicable): pierrebaudot

**Comment by stsewd** [comment]
@pierrebaudot please create a new issue
