### ISSUE TITLE
Specify the Sphinx version

### ISSUE THREAD

**Issue by Midnighter** [readthedocs/readthedocs.org#6296]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/cobra-component-models/
* Build URL (if applicable):
    1. https://readthedocs.org/projects/cobra-component-models/builds/9810044/
    2. https://readthedocs.org/projects/cobra-component-models/builds/9810057/
* Read the Docs username (if applicable):

## Expected Result

I have specified the Sphinx version in my `docs/requirements.txt` file as

```
Sphinx~=2.2
```

this is in the build linked under (i.). This is in accordance with [PEP440](https://www.python.org/dev/peps/pep-0440/) and should be interpreted as >=2.2.0,<3.

## Actual Result

The build does not upgrade Sphinx and keeps the default 1.8.5. When I pin the version exactly `Sphinx==2.2.0` this is recognized (as seen in build ii.) and the newer version installed. Seems like a bug to me.

**Comment by stsewd** [comment]
We just call `pip install -r requirements` under the hood.

**Comment by Midnighter** [comment]
My bad, and thank you for your support.

**Comment by oren0e** [comment]
@stsewd a quick question - if I have the sphinx requirements in a `setup.cfg` file e.g.
```
[extras]
doc =
    alabaster
    sphinx
```
will readthedocs take that into account when building the documentation or is it that it must be inside `requirements.txt`?

**Comment by stsewd** [comment]
@oren0e you have to use the `extra_requirements` option, see https://docs.readthedocs.io/en/stable/config-file/v2.html#packages.
