### ISSUE TITLE
Feature Request: Global edit_on_github_branch setting for all versions

### ISSUE THREAD

**Issue by pllim** [readthedocs/readthedocs.org#6297]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/astropy/
* Build URL (if applicable):
* Read the Docs username (if applicable): pllim

cc @bsipocz 

## Expected Result

"On GitHub -> Edit" option to only allow edit on `master` branch of the repo. We attempted this at astropy/astropy#9379 but realized that it would not retroactively apply to all the released versions we ever pushed out or archived.

The reason we want this is to prevent contributor to accidentally open a pull request against stale/release branches. We only accept pull request against the `master` branch.

Is there a global setting that we can use in, say, `.readthedocs.yml` to control this? Thank you!

## Actual Result

Contributor clicked on the "Edit" link and accidentally opened a pull request against the wrong branch in the source code repository.

**Comment by stsewd** [comment]
Sorry, don't think this isn't possible without rebuilding all versions.

Don't think we have a pattern to edit old versions without rebuilding. You could branch those versions and add the change and push that new version to rtd and add a redirect from the old version to the fixed version.

> Is there a global setting that we can use in, say, .readthedocs.yml to control this?

We don't plan to add global setting on the configuration file, only per version settings.

**Comment by pllim** [comment]
Thanks for the quick reply. We'll think of other ways on our end.

**Comment by bsipocz** [comment]
@stsewd - The link live however in the same dropdown menu the list of versions, too. Isn't there a way to patch that box in the deployed versions?

**Comment by stsewd** [comment]
> The link live however in the same dropdown menu the list of versions

That link is generated dynamically yes, but we always display the link from the same version the user is reading, we are working in making that configurable (but only something like display or not that link, no to change the content).

You can patch that menu using a custom js file, but that requires re building the versions too.

**Comment by bsipocz** [comment]
Being able to not display that link would solve all our headaches, so I'm extremely happy to hear that you're working on making that possible.

**Comment by stsewd** [comment]
@pllim did you reopen the issue to still request the global `edit_on_github_branch` setting? Or is there something else?

**Comment by pllim** [comment]
Yes, I did re-open it due to https://github.com/readthedocs/readthedocs.org/issues/6297#issuecomment-542862228 . Sorry for the confusion!

**Comment by stsewd** [comment]
@pllim so is the same requests as described in the description? or the one from the comment? (being able to not display the link)

**Comment by pllim** [comment]
Being able to **not** display the link would be a workaround solution for lacking a global setting, which I will accept. Does that make sense?

**Comment by humitos** [comment]
Thanks all for your feedback here.

We are working a new project called addons which is currently in beta (read more in our blog post at https://blog.readthedocs.com/addons-flyout-menu-beta/) which includes a new completely redesign of the flyout. We are considering these type of configuration there and we have an issue for this: https://github.com/readthedocs/addons/issues/51 and https://github.com/readthedocs/addons/issues/13

We will exposing the whole data that Read the Docs uses to build the flyout via a javascript event that users can subscript to and render the flyout exactly how they want: adding more section, removing sections, showing the language selector somewhere else, etc.

Please subscribe there for updates.
