### ISSUE TITLE
Build exited due to time out 450s

### ISSUE THREAD

**Issue by genzh** [readthedocs/readthedocs.org#6302]
https://readthedocs.org/projects/terralink-xde/builds/9817036/

please increase timeout build

**Comment by stsewd** [comment]
Please follow these suggestions first https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html. Also, if this is documentation for a private project, you may consider using readthedocs.com. All projects on readthedocs.org are public.

**Comment by stsewd** [comment]
Closing this in favor of https://github.com/readthedocs/readthedocs.org/issues/6308
