### ISSUE TITLE
Timeout seems to have reduced to 600 seconds.

### ISSUE THREAD

**Issue by KelSolaar** [readthedocs/readthedocs.org#6308]
## Details

* Read the Docs project URL: https://colour.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/colour/builds/9824912/
* Read the Docs username (if applicable): KelSolaar

## Expected Result

*A description of what you wanted to happen*

Build exited due to time out:

![image](https://user-images.githubusercontent.com/99779/67135832-99b1a980-f27a-11e9-9eeb-b54b20d3dabe.png)

## Actual Result

*A description of what actually happened*

The build should pass :) It seems like the timeout has been decreased from 900secs to 600secs recently as I have a few builds that died after 10mins. It is possible to increase the timeout please?

Cheers,

Thomas

**Comment by humitos** [comment]
I think this bug was introduced when replacing the setting in #6040.

**Comment by KelSolaar** [comment]
I think that I had a build passing after the commit got merged, e.g. https://readthedocs.org/projects/colour/builds/9794465/, I'm not sure how long it takes for the code to get rolled to the production server though.

It is kind of a bummer because I was intending to release a new version of [Colour](https://github.com/colour-science/colour) over the weekend but won't be able because I don't have a matching documentation build.

Let me know if there is anything I can do to help!

**Comment by stsewd** [comment]
> I think that I had a build passing after the commit got merged, e.g. https://readthedocs.org/projects/colour/builds/9794465/, I'm not sure how long it takes for the code to get rolled to the production server though.

We don't deploy changes that often, usually once or twice per month https://docs.readthedocs.io/en/stable/faq.html#what-commit-of-read-the-docs-is-in-production

I've investigated this. The rename of the settings is correct, but we didn't pull the new changes for the ops repo, that's why it's using the defaults of `600` seconds.

**Comment by ericholscher** [comment]
This should be fixed, sorry about that.

**Comment by KelSolaar** [comment]
No worries and thanks @ericholscher! I have a build that went through! <3
