### ISSUE TITLE
Search Queries with Elasticsearch 

### ISSUE THREAD

**Issue by maldag** [readthedocs/readthedocs.org#6312]
## Details
Using elasticsearch combined with RTD on a local hosted environment provides already a full-text search.

Is it possible to add simple Elasticsearch queries written here ?

https://www.elastic.co/guide/en/elasticsearch/reference/5.3/query-dsl-simple-query-string-query.html#_simple_query_string_syntax

**Comment by dojutsu-user** [comment]
Hi @maldag 
Yes you can take advantage of Simple Query String Syntax.
You can read more about this here: https://docs.readthedocs.io/en/stable/guides/searching-with-readthedocs.html
