### ISSUE TITLE
Increase build timeout limit for co2mpas project

### ISSUE THREAD

**Issue by vinci1it2000** [readthedocs/readthedocs.org#6313]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/co2mpas/builds/
* Build URL (if applicable):https://readthedocs.org/projects/co2mpas/builds/9832378/
* Read the Docs username (if applicable): vinci1it2000

## Expected Result

Build pass without timeout
<img width="829" alt="Screenshot 2019-10-21 at 11 56 35" src="https://user-images.githubusercontent.com/11716821/67195754-d821a280-f3f9-11e9-886f-dfa2f09142b0.png">

I had to disable PDF build and EPUB to build. Can I ask to increase the timeout?

## Actual Result

Build timeout
<img width="861" alt="Screenshot 2019-10-21 at 11 53 22" src="https://user-images.githubusercontent.com/11716821/67195539-65b0c280-f3f9-11e9-8596-f477de73f379.png">

**Comment by stsewd** [comment]
This is the same as https://github.com/readthedocs/readthedocs.org/issues/6308
