### ISSUE TITLE
Update CIDER's 302 redirects to 301s

### ISSUE THREAD

**Issue by danielcompton** [readthedocs/readthedocs.org#6318]
## Details

* Read the Docs project URL: http://cider.readthedocs.io
* Read the Docs username (if applicable): danielcompton, cc: @bbatsov

> Users can request a 301 redirect via our support queue and we just need to make a change on those redirects after they set them up and are happy. - https://github.com/readthedocs/readthedocs.org/pull/5727#pullrequestreview-241998379

Can we please request that you change all of the 302 redirects for CIDER to 301s? We have migrated to a new docs platform and [setup redirects](https://github.com/clojure-emacs/cider/pull/2734) for all pages to their new homes. Thanks!

**Comment by stsewd** [comment]
Done! 28 redirects were changed.

**Comment by danielcompton** [comment]
Thanks!
