### ISSUE TITLE
Pull request builds do not work correctly on paths containing spaces

### ISSUE THREAD

**Issue by eric-wieser** [readthedocs/readthedocs.org#6328]
Compare:

https://external-builds.readthedocs.io/html/clifford/167/Example%201%20Interpolating%20Conformal%20Objects.html (page not found)

https://clifford.readthedocs.io/en/latest/Example%201%20Interpolating%20Conformal%20Objects.html (working fine)

At least at a first glance, the cause seems to be the spaces in the path name, as all the ones without spaces seem to work fine. Perhaps there's something else going on though.

**Comment by humitos** [comment]
For some reason, in the production container (`media/html`) 4 files are saved --note that the files with spaces are there:

![Screenshot_2019-10-28_11-30-56](https://user-images.githubusercontent.com/244656/67671602-8a1b1a80-f976-11e9-987a-bbf1cef58f1a.png)

On the other hand, in the external build container (`external/html`) only 2 files are saved --none with spaces:

![Screenshot_2019-10-28_11-30-34](https://user-images.githubusercontent.com/244656/67671655-a4ed8f00-f976-11e9-85a1-4ddea177723b.png)

**Comment by eric-wieser** [comment]
Are those screenshots of a view I can see myself, or an internal one?

Looks like Sphinx is doing something weird there by creating both sets of files...

**Comment by humitos** [comment]
That's internal. It's our remote storage.

I had not time to test this out yet, but my guess is there was a change in the sphinx configuration or similar and this issue may not be related to RTD itself but with Sphinx (version or configuration).

**Comment by stsewd** [comment]
> For some reason, in the production container (media/html) 4 files are saved --note that the files with spaces are there:

Probably related to https://github.com/readthedocs/readthedocs.org/pull/6298

**Comment by stsewd** [comment]
I just did a test, both PR and _normal_ build are saved with underscore instead of spaces https://github.com/readthedocs/test-builds/pull/8 Checking how sphinx saves the files now

**Comment by stsewd** [comment]
Ok, I investigate the underlining problem, it's a bug on the version of django-storages that we are using (1.7.1). The bug is fixed here https://github.com/jschneier/django-storages/commit/2fbaa70ea21c12f3ce02cbe497b6f8085e34248b#diff-8837a54be44997b013e5c1b9bcc7d00bL104 (1.72)

We need to update the dependency.

**Comment by stsewd** [comment]
But before updating, we need to figure out this problem

https://github.com/readthedocs/readthedocs.org/blob/f5dbf2cec573bcc57ea4daa3cd4bf461cc8edce9/requirements/pip.txt#L106-L107

**Comment by stsewd** [comment]
I've checked all dependencies, didn't see anything pinned to an incompatible version. So my guess is that we needed to force an update instead of using the one from cache (in the deploy).

**Comment by humitos** [comment]
> But before updating, we need to figure out this problem

I've already figured out this issue in https://github.com/readthedocs/readthedocs.org/pull/6295/files#diff-ebacf6f6ae4ee68078bb16454b23247dR48-R56

So, we can just pin to those packages and it should work in production as well.
