### ISSUE TITLE
Build error with build id #9855232

### ISSUE THREAD

**Issue by pgunn** [readthedocs/readthedocs.org#6330]
## Details:

* Project URL: https://readthedocs.org/projects/CaImAn/
* Build URL(if applicable): https://readthedocs.org/projects/caiman/builds/9855232/
* Read the Docs username(if applicable): AnonymousUser

## Expected Result
*Report of success for the given log

## Actual Result
*Build is reported as failed (I don't see anything but warnings in the log)

**Comment by stsewd** [comment]
Hi @pgunn looks like a temporal error https://readthedocs.org/projects/caiman/builds/9855489/
