### ISSUE TITLE
RTD Python docs started including magic methods

### ISSUE THREAD

**Issue by eli-darkly** [readthedocs/readthedocs.org#6338]
## Details

* Read the Docs project URL: https://launchdarkly-python-sdk.readthedocs.io
* Build URL (if applicable): not sure what this is
* Read the Docs username (if applicable): LaunchDarkly

## Expected Result

We're using `sphinx_rtd_theme`, and our `conf.py` file can be found [here](https://github.com/launchdarkly/python-server-sdk/tree/master/docs). Between the conf file and the Sphinx annotations, we had set it up so that all of the methods we considered public were being documented, and private methods were not.

You can see an example of how this was supposed to look [here](https://launchdarkly-python-sdk.readthedocs.io/en/6.8.3/api-main.html#ldclient.client.LDClient), from the docs for our 6.8.3 release. In this class, the `__init__` method has a docstring and is included in the docs; all other methods beginning with underscores do not have docstrings and do not appear in the docs.

## Actual Result

At some point in between the 6.8.3 and 6.9.2 releases (February 2019 to May 2019), something changed so that other magic methods and properties are also appearing in the docs. You can see the same class documented [here](https://launchdarkly-python-sdk.readthedocs.io/en/6.9.2/api-main.html#ldclient.client.LDClient), showing not only `__enter__` and `__exit__` (which are defined in our code, but were previously excluded from docs) but also `__dict__`, `__module__`, and `__weakref__` (which aren't overridden in our code, they are just inheriting the default Python behavior). This is undesirable, and we can't find any change in our code or our doc configuration that would account for it.

Regular private methods (i.e. ones that start with an underscore and have no docstring, but are not magic methods) are still correctly being excluded from the docs.

The reason I think this might be an RTD issue, rather than a more general Sphinx issue, is that when we build the docs locally using the `Makefile` that you see [here](https://github.com/launchdarkly/python-server-sdk/tree/master/docs), this problem doesn't occur. Since we're not adding any special Sphinx options there, I'm guessing that there is some other difference in the configuration that's used when Sphinx is run by RTD.

Also note that the `.rst` files you see in that same directory use the option `:special-members: __init__` which as far as I know means it should _not_ be documenting any special members other than `__init__`.

**Comment by stsewd** [comment]
Hi @eli-darkly, if you build your project locally, what's the result? This looks like more a problem from the sphinx/autodoc side rather than Read the Docs.

**Comment by eli-darkly** [comment]
Ah yeah I bet that's it— Sphinx went to version 2.x on March 28. Our local build has a version constraint of `<2.0`; if RTD has gone to 2.x, I wouldn't be surprised if there are breaking changes in Sphinx's behavior.

That's a bit unfortunate though, since my expectation with a service like this is that it wouldn't update to an incompatible version of the tool.

**Comment by eli-darkly** [comment]
...Or maybe that's impossible, since our admin settings in RTD clearly specify a requirements file of `docs/requirements.txt`, and that is the same one with a `<2.0` constraint for Sphinx.

**Comment by stsewd** [comment]
> That's a bit unfortunate though, since my expectation with a service like this is that it wouldn't update to an incompatible version of the tool.

We try to have some nice defaults, but to make sure nothing breaks, we recommend using a configuration file.

I can see that the version of sphinx used six months ago and today was `1.8.5`, but 8 months ago the sphinx version was `1.7.9`

**Comment by stsewd** [comment]
The command on the make files doesn't look like much different from the command used to generate the documentation on Read the Docs. Please try building the docs locally with sphinx 1.8.5 and let us know.

**Comment by eli-darkly** [comment]
Dang— indeed, the problem shows up as soon as I upgrade to Sphinx 1.8.5 locally. Sorry, I missed that I was still running 1.7.9. So RTD is not doing anything inconsistent with the local build, and this must be a Sphinx issue. Thanks!
