### ISSUE TITLE
Combining Search View and Docsearch

### ISSUE THREAD

**Issue by dojutsu-user** [readthedocs/readthedocs.org#6341]
Currently we are serving the search results from two locations:

* Docsearch API (via DRF)
* Main Site Search (via Django Templates)

This creates many problems:
* Maintaing the same code in two place
* Adding a feature requires more work
* More code redundancy and code complexity.

It will be better if we have one API endpoint for both the use cases.

**Proposed Solution:**
For this, we can make use of [TemplateHTMLRenderer](https://www.django-rest-framework.org/api-guide/renderers/#templatehtmlrenderer) along with [JSONRenderer](https://www.django-rest-framework.org/api-guide/renderers/#jsonrenderer).
Django Rest Framework allows multiple [renderer_classes](https://www.django-rest-framework.org/coreapi/schemas/#renderer_classes) to be defined in a view. We can have renderer classes for json and html. We can continue serving the docsearch with the json response and for main site search we can have search-as-you-type. As soon as the user starts typing, we will get new API response in html form and we can render that as it is.

**Comment by humitos** [comment]
I don't have the full context for this, but from the description, it seems a good path forward to me. I have some questions:

1. does this refactor involve too much work?
1. is required for this refactor "search-as-you-type in the main site" or that can be done in a separate work?

I'd say to go ahead with this if the combination is simple and does not change the current behavior. I don't think this is in our current roadmap and my concern is not having too much time for review if the PR grows too much.

**Comment by ericholscher** [comment]
I think the main concern is around shipping rendered HTML over the API. We're starting to move away from HTML API responses to JSON responses that are built on the client side. What are the benefits of the HTML approach, when we're using the JSON approach already in the doc pages?

**Comment by Blackcipher101** [comment]
@stsewd can I sart working on the issue

**Comment by stsewd** [comment]
@Blackcipher101 this issue has the `Needed: design decision` label, we still need to decide how to resolve this.

**Comment by Blackcipher101** [comment]
@stsewd fine
