### ISSUE TITLE
Account webhook alerts will not clear from the dashboard

### ISSUE THREAD

**Issue by dwt2** [readthedocs/readthedocs.org#6342]
## Details

* Read the Docs project URL: https://readthedocs.org/dashboard/
* Build URL (if applicable):
* Read the Docs username (if applicable): lf-oran

## Expected Result

Some mechanism to clear the account alerts about webhooks.

## Actual Result

The account alerts don't go away, even after the project is deleted.

**Comment by stsewd** [comment]
You can clear them by clicking on the link.

See https://github.com/readthedocs/readthedocs.org/issues/5665#issuecomment-495185159 for more information
