### ISSUE TITLE
Latexmk breaks builds outside when DOCKER_ENABLED=False

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#6343]
For users setting up a new instance, we do not recommend that the user uses Docker. Therefore, our attempts to run latexmk fail every build.

To reproduce:
* Set DOCKER_ENABLED=False
* Don't have latexmk installed on your host system
* Run a build
* See the failure in build output

Core team uses Docker exclusively, so this is low priority. New contributors will hit this however. An easy solution would be to check for DOCKER_ENABLED before trying to use latexmk.

**Comment by krptic07** [comment]
Hi, Can i take up this issue ? And can anyone explain me a little bit what is to be done .

**Comment by KartikKapil** [comment]
@stsewd i would like to take up this issue ,

**Comment by stsewd** [comment]
Sure, feel free to send a pull request

**Comment by KartikKapil** [comment]
@stsewd  could you kindly guide me through it

**Comment by rohitjha941** [comment]
@KartikKapil  Can I take this if you are not working on this?

**Comment by Blackcipher101** [comment]
@agjohnson should we check if Docker_Enabled=False and then call the function to build latexmk

**Comment by stsewd** [comment]
Now we always recommend using docker compose to contribute to rtd, so I'm closing this
