### ISSUE TITLE
Please set DONT_SHALLOW_CLONE for bottleneck

### ISSUE THREAD

**Issue by qwhelan** [readthedocs/readthedocs.org#6346]
# Details
- Read the Docs project URL: https://bottleneck.readthedocs.io
- Read the Docs username (if applicable): qwhelan

Hi, I'm using `versioneer` and a special `sphinx` plugin to automatically cite contributors in the release notes, and the shallow clone is unfortunately interfering with both the versioning and thanking contributors. I'd appreciate it if `DONT_SHALLOW_CLONE` could be set for the `bottleneck` project.

Thanks,
Chris

**Comment by humitos** [comment]
Done! Let me know if anything!

**Comment by qwhelan** [comment]
Thank you!
