### ISSUE TITLE
Command killed due to excessive memory consumption

### ISSUE THREAD

**Issue by HyukjinKwon** [readthedocs/readthedocs.org#6350]
## Details

5 days ago, the build started failing suddenly due to memory consumption. There has not been a big change in this project, in particular, about the dependencies. (build started to failed with the symptom below after https://github.com/databricks/koalas/commit/b16142886f8b75daae7d2f9dafd2b4ced8705a05, which looks pretty much unrelated with dependencies).

I read https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html and but it's currently not feasible in this project ..

* Read the Docs project URL: https://readthedocs.org/projects/koalas/
* Build URL (if applicable): 
  From: https://readthedocs.org/projects/koalas/builds/9893868/
  To: https://readthedocs.org/projects/koalas/builds/9917514/
  And the current build: https://readthedocs.org/projects/koalas/builds/9917617/
  (For other builds, I tried several ways like pip's `--no-cache-dir` but no luck ..)

* Read the Docs username (if applicable): HyukjinKwon

## Expected Result

![Screen Shot 2019-11-06 at 11 07 04 AM](https://user-images.githubusercontent.com/6477701/68262107-9f362e80-0085-11ea-8144-3bde5f621787.png)

## Actual Result

![Screen Shot 2019-11-06 at 11 07 10 AM](https://user-images.githubusercontent.com/6477701/68262110-a0675b80-0085-11ea-93f4-f92bf1a95b90.png)

**Comment by stsewd** [comment]
I've increased the build resources, but looks like it's failing for another reason https://readthedocs.org/projects/koalas/builds/9927943/

**Comment by HyukjinKwon** [comment]
Thank you so much @stsewd . Let me try to investigate in my side first.

**Comment by HyukjinKwon** [comment]
@stsewd, seems Python 3.8 is just uploaded into Conda as of https://github.com/conda-forge/python-feedstock/pull/274#issuecomment-548831867 but seems not so many packages supporting this. I suspect this is the root cause given the timing about the build failure (5 ~ 6 days ago).

Now, the build seems getting there: https://readthedocs.org/projects/koalas/builds/9928921/ -
it required to install CPython due to PyArrow dependency so seems it eats more time :(.

Would you mind if I ask to increase the build time to, say, 1500 sec please if it's fine?

FWIW, I will be able to cut down the build time around next year by using one the latest dependency (Apache Spark) once that's release. I will try to use less resources.

**Comment by HyukjinKwon** [comment]
I triggered the latest build against master just for the record (https://readthedocs.org/projects/koalas/builds/9929050/)

**Comment by HyukjinKwon** [comment]
Ohh, NVM. it started to pass. Thank you so much @stsewd!
