### ISSUE TITLE
Virtualenv used when installing custom package but not used during docs generation

### ISSUE THREAD

**Issue by leon575777642** [readthedocs/readthedocs.org#6351]
## Details

* Read the Docs project URL: https://github.com/PrincetonUniversity/prga
* Build URL (if applicable): https://readthedocs.org/projects/prga/builds/9921362/
* Read the Docs username (if applicable): leon575777642

## Expected Result

Custom module installed and importable when building the documentation.

## Actual Result

The log shows my custom submodule and its dependencies are successfully installed by `/home/docs/checkouts/readthedocs.org/user_builds/prga/envs/latest/bin/python prga.py/setup.py install --force`. But later when building the documentation, the custom module cannot be imported for autodoc.

I doubt if it's because `sphinx-build` is not executed with the binary from the virtualenv. I can see from the log that it's using `python /home/docs/checkouts/readthedocs.org/user_builds/prga/envs/latest/bin/sphinx-build ...`.

**Comment by stsewd** [comment]
Last build looks good https://readthedocs.org/projects/prga/builds/9923974/

Probably that build was using a cached environment.

Let us know if you still see the problem, otherwise we can close this issue.

**Comment by leon575777642** [comment]
Thanks for your reply. I added the path to the module into `conf.py` in the latest build as a temporary fix.

Actually I think this is highly possibly not an issue of readthedocs. I tried to reproduce the problem locally and found that `python setup.py install` couldn't install the modules into the virtualenv site packages. I'm still studying why, but I'll close this issue for now.
