### ISSUE TITLE
Failing builds without any obvious reason

### ISSUE THREAD

**Issue by nijel** [readthedocs/readthedocs.org#6356]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/weblate
* Build URL (if applicable): https://readthedocs.org/projects/weblate/builds/9926874/
* Read the Docs username (if applicable): nijel

Today the documentation builds for Weblate started to fail without obvious reason. 

Looking at the jobs list, there is one build which is marked as failed on the list, but it is completed when looking at the details (https://readthedocs.org/projects/weblate/builds/9926085/). All consequent builds have failed, so maybe there is some cause hidden there?

## Expected Result

Builds should succeed. In case they fail, I'd like to know why they failed. 

## Actual Result

"This build was terminated due to inactivity. If you continue to encounter this error, file a support request with and reference this build id (9926874)."

**Comment by stsewd** [comment]
Hi @nijel this may be a temporary issue. We are checking our servers now.

**Comment by stsewd** [comment]
Triggered a new build https://readthedocs.org/projects/weblate/builds/9927471/, it's passing now.
