### ISSUE TITLE
Build error with build id #9927405

### ISSUE THREAD

**Issue by StykMartin** [readthedocs/readthedocs.org#6357]
## Details:

* Project URL: https://readthedocs.org/projects/restraint/
* Build URL(if applicable): https://readthedocs.org/projects/restraint/builds/9927405/
* Read the Docs username(if applicable): martstyk

## Expected Result

Build failed for no reason

## Actual Result

Build should pass

**Comment by stsewd** [comment]
Looks like it was a temporal issue, your last build is passing now https://readthedocs.org/projects/restraint/builds/9927441/
