### ISSUE TITLE
Publish configuration file schema to http://schemastore.org

### ISSUE THREAD

**Issue by segevfiner** [readthedocs/readthedocs.org#6363]
This will enable auto-completion & validation for the Read the Docs configuration file in various editors such as VS Code.

See http://schemastore.org

**Comment by stsewd** [comment]
The schema should be submitted here https://github.com/SchemaStore/schemastore.

I use schemastoer.org for autocompletion too :)

**Comment by KartikKapil** [comment]
@stsewd In which file will i find the configuration schema

**Comment by segevfiner** [comment]
I'm not sure if there is even one written. Might be necessary to write one based on the documentation & code first.

**Comment by stsewd** [comment]
We have one based on `yamale`

https://github.com/readthedocs/readthedocs.org/blob/master/readthedocs/rtd_tests/fixtures/spec/v2/schema.yml

**Comment by stsewd** [comment]
btw, this should be only done for v2, v1 is deprecated (not worth the effort)

**Comment by KartikKapil** [comment]
@stsewd thanks for the help

**Comment by stsewd** [comment]
@KartikKapil it should be ported to JSON schema

**Comment by KartikKapil** [comment]
@stsewd alright thanks a lot

**Comment by sadaansaad** [comment]
### Keybase proof

I hereby claim:

  * I am sadaansaad4 on github.
  * I am saadmoin4 (https://keybase.io/saadmoin4) on keybase.
  * I have a public key ASA2SzHzYcTT9hePS5-BVVg4uT_iOs8l4SWGEaFPe8pkMgo

To claim this, I am signing this object:

```json
{
  "body": {
    "key": {
      "eldest_kid": "0120364b31f361c4d3f6178f4b9f81555838b93fe23acf25e1258611a14f7bca64320a",
      "host": "keybase.io",
      "kid": "0120364b31f361c4d3f6178f4b9f81555838b93fe23acf25e1258611a14f7bca64320a",
      "uid": "49a6da89d3865ec63e9298d27868de19",
      "username": "saadmoin4"
    },
    "merkle_root": {
      "ctime": 1573878392,
      "hash": "4538c97cb2a20a70072c2f5a1f5ec97fd790d2954dc851f4dee1ffe9543e10f64121f39f9c9c7210da58abfdb9f4a0e61de78418b0dd51475bc2ebe69a5e6f99",
      "hash_meta": "f49ce3ac294578bbdee56c0aeb4c5ea4af92d4a22c9a23b30cd629a907f32339",
      "seqno": 9761301
    },
    "service": {
      "entropy": "s47IeWm8lINI2aJwGt2Q0NZF",
      "name": "github",
      "username": "sadaansaad4"
    },
    "type": "web_service_binding",
    "version": 2
  },
  "client": {
    "name": "keybase.io go client",
    "version": "5.0.0"
  },
  "ctime": 1573878399,
  "expire_in": 504576000,
  "prev": "a0ce475851584f99cb8cc143b46b0148215fa30481b18632c6e40c516fa00d8c",
  "seqno": 9,
  "tag": "signature"
}
```

with the key [ASA2SzHzYcTT9hePS5-BVVg4uT_iOs8l4SWGEaFPe8pkMgo](https://keybase.io/saadmoin4), yielding the signature:

```
hKRib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEgNksx82HE0/YXj0ufgVVYOLk/4jrPJeElhhGhT3vKZDIKp3BheWxvYWTESpcCCcQgoM5HWFFYT5nLjMFDtGsBSCFfowSBsYYyxuQMUW+gDYzEIIHte7655bEuFqRIeyNuMBOc+5QNeuwH2A3yM4Fv2ERYAgHCo3NpZ8RAXuzT4869caSHxccmpn4wlFfZH46V/Ii2eiwoBViHuvuqDt6E32YQ7pD3fxBKs/D/TQ2eTARj2LiCYZd9puTuBqhzaWdfdHlwZSCkaGFzaIKkdHlwZQildmFsdWXEIHihwPC2dU61GhnnaRVhdKu5UYa7qp55ZssxAuVdNkIKo3RhZ80CAqd2ZXJzaW9uAQ==

```

And finally, I am proving ownership of the github account by posting this as a gist.

### My publicly-auditable identity:

https://keybase.io/saadmoin4

### From the command line:

Consider the [keybase command line program](https://keybase.io/download).

```bash
# look me up
keybase id saadmoin4
```

**Comment by sadaansaad** [comment]
### Keybase proof

I hereby claim:

  * I am sadaansaad4 on github.
  * I am saadmoin4 (https://keybase.io/saadmoin4) on keybase.
  * I have a public key ASA2SzHzYcTT9hePS5-BVVg4uT_iOs8l4SWGEaFPe8pkMgo

To claim this, I am signing this object:

```json
{
  "body": {
    "key": {
      "eldest_kid": "0120364b31f361c4d3f6178f4b9f81555838b93fe23acf25e1258611a14f7bca64320a",
      "host": "keybase.io",
      "kid": "0120364b31f361c4d3f6178f4b9f81555838b93fe23acf25e1258611a14f7bca64320a",
      "uid": "49a6da89d3865ec63e9298d27868de19",
      "username": "saadmoin4"
    },
    "merkle_root": {
      "ctime": 1573878392,
      "hash": "4538c97cb2a20a70072c2f5a1f5ec97fd790d2954dc851f4dee1ffe9543e10f64121f39f9c9c7210da58abfdb9f4a0e61de78418b0dd51475bc2ebe69a5e6f99",
      "hash_meta": "f49ce3ac294578bbdee56c0aeb4c5ea4af92d4a22c9a23b30cd629a907f32339",
      "seqno": 9761301
    },
    "service": {
      "entropy": "s47IeWm8lINI2aJwGt2Q0NZF",
      "name": "github",
      "username": "sadaansaad4"
    },
    "type": "web_service_binding",
    "version": 2
  },
  "client": {
    "name": "keybase.io go client",
    "version": "5.0.0"
  },
  "ctime": 1573878399,
  "expire_in": 504576000,
  "prev": "a0ce475851584f99cb8cc143b46b0148215fa30481b18632c6e40c516fa00d8c",
  "seqno": 9,
  "tag": "signature"
}
```

with the key [ASA2SzHzYcTT9hePS5-BVVg4uT_iOs8l4SWGEaFPe8pkMgo](https://keybase.io/saadmoin4), yielding the signature:

```
hKRib2R5hqhkZXRhY2hlZMOpaGFzaF90eXBlCqNrZXnEIwEgNksx82HE0/YXj0ufgVVYOLk/4jrPJeElhhGhT3vKZDIKp3BheWxvYWTESpcCCcQgoM5HWFFYT5nLjMFDtGsBSCFfowSBsYYyxuQMUW+gDYzEIIHte7655bEuFqRIeyNuMBOc+5QNeuwH2A3yM4Fv2ERYAgHCo3NpZ8RAXuzT4869caSHxccmpn4wlFfZH46V/Ii2eiwoBViHuvuqDt6E32YQ7pD3fxBKs/D/TQ2eTARj2LiCYZd9puTuBqhzaWdfdHlwZSCkaGFzaIKkdHlwZQildmFsdWXEIHihwPC2dU61GhnnaRVhdKu5UYa7qp55ZssxAuVdNkIKo3RhZ80CAqd2ZXJzaW9uAQ==

```

And finally, I am proving ownership of the github account by posting this as a gist.

### My publicly-auditable identity:

https://keybase.io/saadmoin4

### From the command line:

Consider the [keybase command line program](https://keybase.io/download).

```bash
# look me up
keybase id saadmoin4
```

**Comment by KartikKapil** [comment]
> @stsewd what kind of test should i create for the schema

Friendly ping @stsewd :-)

**Comment by stsewd** [comment]
> @stsewd what kind of test should i create for the schema

Not sure, since we'll need to run the json schema checker in CI. Let's just start by placing the json schema here https://github.com/readthedocs/readthedocs.org/tree/master/readthedocs/config/tests/fixtures /fixtures/specs/ and see what others think.

**Comment by KartikKapil** [comment]
@stsewd  i have made a pull request with .JSON file hopefully to get test cases for the same . #6406

**Comment by KartikKapil** [comment]
@stsewd here i have made a new json file with the help of python3 and made a new pull request  #6424 kindly review it and help me make any changes if needed :)

**Comment by stsewd** [comment]
Just for clarification, this issue isn't about to just change the extension of the yamale schema or port the yaml file to a json file. Neither to use the same validation used in yamale.

You have to find the proper attributes that match that validations in https://json-schema.org/learn/getting-started-step-by-step.html

**Comment by Blackcipher101** [comment]
@stsewd Can I work on this Issue?

**Comment by stsewd** [comment]
@Blackcipher101 sure

**Comment by segevfiner** [comment]
Still relevant, and has some contributor work towards it already.

**Comment by stsewd** [comment]
Yes, the PR is https://github.com/readthedocs/readthedocs.org/pull/6501/ it needs review, but this isn't a priority for core team at the moment. If someone has time and is familiar with json schema, feel free to help with review there
