### ISSUE TITLE
Command killed due to excessive memory consumption 

### ISSUE THREAD

**Issue by afortiori** [readthedocs/readthedocs.org#6368]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/relex/
* Build URL (if applicable): https://relex.readthedocs.io/en/latest/
* Read the Docs username (if applicable): afortiori

## Expected Result

I expected the build to build correctly 

## Actual Result
When this command during build was run:
`/home/docs/checkouts/readthedocs.org/user_builds/relex/envs/latest/bin/python -m pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/relex/.cache/pip -r relex/requirements.txt`

I got the error: Command killed due to excessive memory consumption

**Comment by stsewd** [comment]
Hi @afortiori, looks like you don't need all those requirements to build your documentation https://github.com/SamMahen/RelEx

Actually, I don't see any documentation in the repository. You may want to check https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html

**Comment by afortiori** [comment]
I will include some more information which I apologize for leaving out. I have used Sphinx to generate documentation of the whole package, all of which is up and running on my computer. When I pushed the created documentation to Github and built the documentation on GitHub, some of the documentation was built (see here: [](https://relex.readthedocs.io/en/latest/relex.data.html) and here: [](https://relex.readthedocs.io/en/latest/relex.utils.html) ) but not all of it. I googled why the documentation would not update and found that it was because I used Cpython packages and did not include a requirments.txt file. I added the requirements.txt and got the memory error. 

The reason why the repository looks like it does not have documentation is because all the documentation is located on a branch (relex_cora) not the main branch. I am positive that I am building from that correct branch because some of the documentation has built correctly. Also, the requirments.txt as listed on the main branch is outdated, and I am using a larger and more updated one to build the package. I do not think it will be possible to make the requirments.txt shorter and have the package still build. On the readthedocs documentation, I saw that you can take out the requirements for sphinx and one or two other requirements, however, I get the memory error halfway through running the requirements.txt which means taking out one or two requirements will not solve the memory error.

**Comment by stsewd** [comment]
@afortiori please try to use a minimal requirements file to build the docs so we can try increase the memory limit from there.

**Comment by afortiori** [comment]
I will try that.
