### ISSUE TITLE
Local VM Install instructions - incorrect dependency information

### ISSUE THREAD

**Issue by merkledag** [readthedocs/readthedocs.org#6378]
## Details
* Read the Docs project URL: https://docs.readthedocs.io/en/stable/custom_installs/local_rtd_vm.html

## Expected Result

Instructions for setting up local RTD should work. The instructions are provided here state that Python 2.7 is the required version: https://docs.readthedocs.io/en/stable/custom_installs/local_rtd_vm.html

## Actual Result

I installed the prerequisites on Ubuntu16.04 as documented:
All python dependencies and setup tools are installed
Git
Sphinx

Then did the following
git clone https://github.com/readthedocs/readthedocs.org.git
cd readthedocs.org
sudo pip install -r requirements.txt

This resulted in this error
ERROR: Could not find a version that satisfies the requirement djangorestframework==3.10.3 (from -r requirements/pip.txt (line 10)) (from versions: 0.1, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.4.0, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.1.7, 2.1.8, 2.1.9, 2.1.10, 2.1.11, 2.1.12, 2.1.13, 2.1.14, 2.1.15, 2.1.16, 2.1.17, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 2.3.11, 2.3.12, 2.3.13, 2.3.14, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.8, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0, 3.2.1, 3.2.2, 3.2.3, 3.2.4, 3.2.5, 3.3.0, 3.3.1, 3.3.2, 3.3.3, 3.4.0, 3.4.1, 3.4.2, 3.4.3, 3.4.4, 3.4.5, 3.4.6, 3.4.7, 3.5.0, 3.5.1, 3.5.2, 3.5.3, 3.5.4, 3.6.0, 3.6.1, 3.6.2, 3.6.3, 3.6.4, 3.7.0, 3.7.1, 3.7.2, 3.7.3, 3.7.4, 3.7.5, 3.7.6, 3.7.7, 3.8.0, 3.8.1, 3.8.2, 3.9.0, 3.9.1, 3.9.2, 3.9.3, 3.9.4)
ERROR: No matching distribution found for djangorestframework==3.10.3 (from -r requirements/pip.txt (line 10))

The requirements for djangorestframework v3.10.3 is requires Python 3.5 as per https://www.django-rest-framework.org/#installation

Note: I then tried to install requirements in a Python3 virtual env, but this resulted in the following error:

building wheels for collected packages: elasticsearch-dsl, regex, unicode-slugify
  Building wheel for elasticsearch-dsl (setup.py) ... done
  Created wheel for elasticsearch-dsl: filename=elasticsearch_dsl-6.1.0-py2.py3-none-any.whl size=47258 sha256=2487e52721b9ea2f83e1b5a8b6e6c8441be40726c6b0c5d62a5fa897901b5f58
  Stored in directory: /tmp/pip-ephem-wheel-cache-ib__ebfj/wheels/5a/05/58/d3b5ca29058cb0c883d39d4c600b086900cdf1fed8f94f3365
  Building wheel for regex (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /nfs/home/pam/rtd/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-saadpnf_/regex/setup.py'"'"'; __file__='"'"'/tmp/pip-install-saadpnf_/regex/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-slusjsym --python-tag cp35
       cwd: /tmp/pip-install-saadpnf_/regex/
  Complete output (18 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/regex
  copying regex_3/__init__.py -> build/lib.linux-x86_64-3.5/regex
  copying regex_3/regex.py -> build/lib.linux-x86_64-3.5/regex
  copying regex_3/_regex_core.py -> build/lib.linux-x86_64-3.5/regex
  copying regex_3/test_regex.py -> build/lib.linux-x86_64-3.5/regex
  running build_ext
  building 'regex._regex' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/regex_3
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/nfs/home/pam/rtd/venv/include -I/usr/include/python3.5m -c regex_3/_regex.c -o build/temp.linux-x86_64-3.5/regex_3/_regex.o
  regex_3/_regex.c:48:20: fatal error: Python.h: No such file or directory
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for regex

My apologies if this is a newbie error. Any suggestions for what I should try to do next would be greatly appreciated. Let me know if I can get you more information to shed light this critical installation step.

Thank you in advance

**Comment by stsewd** [comment]
Hi @merkledag that document is maintained by the community, rtd team doesn't maintain that

https://docs.readthedocs.io/en/stable/custom_installs/index.html

You can follow more up to date instructions from here https://docs.readthedocs.io/en/stable/development/install.html

Please, feel free to update the other docs.

**Comment by merkledag** [comment]
Thank you @stsewd . Much appreciated.
