### ISSUE TITLE
typeerror numpy mocking not working?

### ISSUE THREAD

**Issue by AndrewAnnex** [readthedocs/readthedocs.org#6384]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/spiceypy
* Build URL (if applicable): https://readthedocs.org/projects/spiceypy/builds/9976362/
* Read the Docs username (if applicable): AndrewAnnex
* rdt.yaml file I am adding in a pr branch to attempt fixes: https://github.com/AndrewAnnex/SpiceyPy/blob/1290d90db6d71d6107eb1cf0410fd253d86639c1/.readthedocs.yml

## Expected Result

Builds to work like on my prior releases, like https://spiceypy.readthedocs.io/en/v2.3.1/documentation.html#module-spiceypy.spiceypy

also if there is a way to get all of the module functions to show up in the left sidebar, please let me know!

## Actual Result

I was notified recently that the builds on my master branch were failing to render all of the module docstrings (ex https://spiceypy.readthedocs.io/en/latest/documentation.html#module-spiceypy.spiceypy). This looks like some issue related to the mocking of numpy possibly, I added a new function recently to the master branch that imports `numpy.str_` and I get the following type error output in the build logs: 

```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/spiceypy/envs/upgrade_the_docs/lib/python3.7/site-packages/sphinx/ext/autodoc/importer.py", line 154, in import_module
    __import__(modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/spiceypy/envs/upgrade_the_docs/lib/python3.7/site-packages/spiceypy/__init__.py", line 31, in <module> 
    erract("set", 10, "return")
  File "/home/docs/checkouts/readthedocs.org/user_builds/spiceypy/envs/upgrade_the_docs/lib/python3.7/site-packages/spiceypy/spiceypy.py", line 4879, in erract
    op = stypes.stringToCharP(op)
  File "/home/docs/checkouts/readthedocs.org/user_builds/spiceypy/envs/upgrade_the_docs/lib/python3.7/site-packages/spiceypy/utils/support_types.py", line 204, in stringToCharP
    if isinstance(inobject, numpy.str_):
TypeError: isinstance() arg 2 must be a type or tuple of types
```

I created a conda environment locally to see if it was the numpy version but I couldn't replicate the type error.

**Comment by stsewd** [comment]
> I created a conda environment locally to see if it was the numpy version but I couldn't replicate the type error.

We use pip and virtualenv to build the docs.

Also, you can use conda in rtd too https://docs.readthedocs.io/en/stable/config-file/v2.html#conda

**Comment by AndrewAnnex** [comment]
@stsewd what other information do you need beyond what is contained in the logs at the build url?

I am not sure by what you mean about pip/virtualenv as that isn't the question I was asking, I was just using it to test to see if the version of numpy on the build worker (1.16.0) was somehow causing the typeerror.

**Comment by stsewd** [comment]
@AndrewAnnex I mean that you should try to replicate locally using pip as is done in read the docs

**Comment by AndrewAnnex** [comment]
I looked into this again by running the build again with a print statement to investigate the call to `numpy.str_` and I got the following outputs for `print(numpy.str_)` and `print(type(numpy.str_))`:
```
<sphinx.ext.autodoc.importer._MockObject object at 0x7f9c202c2588>
<class 'sphinx.ext.autodoc.importer._MockObject'>
```

so it looks like the mocking is not poperly mocking this part of numpy, I don't have much familiarity with mocking in python so I am not sure how to work around this other than not mocking numpy

**Comment by stsewd** [comment]
Looks like mock doesn't work with isinstance

https://github.com/AndrewAnnex/SpiceyPy/blob/8f34f1dcdb682d1de087a22c4aa518cf95f825de/spiceypy/utils/support_types.py#L207

https://stackoverflow.com/questions/11146725/isinstance-and-mocking

This isn't a rtd problem, but a problem with the mock lib. You could adapt your code to make it work with mock. Or try building without mocking

**Comment by AndrewAnnex** [comment]
Yep I agree with that, looks like I am making progress with the conda environment option. Thanks!

-Andrew Annex
