### ISSUE TITLE
Read the docs api v3 call for "Project Details" does not reflect what is in the U/I.

### ISSUE THREAD

**Issue by Aricg** [readthedocs/readthedocs.org#6388]
## Details

Read the docs api v3 call for  "Project Details" does not reflect what is in the U/I.

When querying the "Project Details"
https://docs.readthedocs.io/en/stable/api/v3.html#get--api-v3-projects-(string-project_slug)-

On a newly minted project, the api returns.

`
 'default_branch': 'master',
 'default_version': 'latest',
`

If you go to the U/I on a newly minted project
Default branch is not set to master it is set to "----"

The help text is as follows:

"What branch "latest" points to. Leave empty to use the default value for your VCS (eg. trunk or master)."

When reading the help text originally I thought that  "----" and master were equivalent.

However the behavior is different, as far as I can tell.

If you leave Default branch at ---
and then build "master" via the API /latest/ is unchanged.

If you Change Default branch from "----" to "master" then build master via the api
/latest/ and /master/ match.

So now I need to set all projects to "master" from "----"
But I have no way of seeing if this is already done.

## Expected Result

project details on a newly minted project should differentiate between --- and master. 

`
 'default_branch': '---',
 'default_version': 'latest',
` 

## Actual Result

`
 'default_branch': 'master',
 'default_version': 'latest',
`

**Comment by stsewd** [comment]
> 'default_branch': '---', 'default_version': 'latest',

`---` is just a placeholder to indicate empty, so in the API should be `` an empty string.

>  and then build "master" via the API /latest/ is unchanged.

Can you provide your rtd project? I need to check the builds, but I believe we build latest if master changes.

**Comment by Aricg** [comment]
Okay I have looked further and I think I have found the issue.

When you create a new project and trigger a build via the api of "master"

latest is not created, it is 404.

Since we never trigger 'latest' explicitly, you can find the docs at /master/ and never at /latest/

If you change the default version from ---- to master and then trigger /master/
latest is created, and matches what is in master.

Which is what lead to my confusion.

So the bug is something else than what I stated, but is still relevant imo.

**Comment by Aricg** [comment]
Here is an example of a newish project

https://docs.o-ran-sc.org/projects/o-ran-sc-it-dev/en/master/
https://docs.o-ran-sc.org/projects/o-ran-sc-it-dev/en/latest/

Documentation does not match.

**Comment by Aricg** [comment]
Builds are as follow.

It looks like the /latest/ version is  created on the first build. (or perhaps this is on project creation)

But then is never updated on subsequent builds via the api to master

Passed version master (html)6 days, 14 hours ago
Passed version master (html)1 week, 3 days ago
Passed version master (html)1 week, 3 days ago
Passed version latest (html)1 week, 3 days ago

**Comment by Aricg** [comment]
I have found that If I change default branch from "---" to "master"
It then it immediately builds /latest/ 
and then /master/ and /latest/ matches.

Also I think that after this change, subsequent builds via the api to /master/
also trigger /latest/ to update, but it does not show this explicitly in the build logs,
so I might be wrong there, I am going to try to test further.

**Comment by Aricg** [comment]
Oh my, I am actually completely wrong,

Changing the default branch in the U/I from --- to master just triggers latest to build once.
it does not cause latest to match what is seen when you navigate to /master/.

It seems like my options are,

enable the master branch for all project and remove the latest one.
or just trigger both to build.

You can close this.
