### ISSUE TITLE
Put anchor when searching for inactive versions

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6392]
After filtering inactive versions you have to scroll down all active versions to find the search result. A simple anchor should fix this.

We are introducing one here https://github.com/readthedocs/readthedocs.org/pull/6276/files, so we could just make the change in that PR

**Comment by humitos** [comment]
This is already solved in the new dashboard that uses a dynamic search box.

![Screenshot_2023-09-15_14-43-17](https://github.com/readthedocs/readthedocs.org/assets/244656/cc2c4832-7ffc-4be8-b0f5-230e28f1ddc1)
