### ISSUE TITLE
Improve regex for semver in automation rules

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6395]
We have a very basic pattern, but on the semver faq they have a better one

https://semver.org/#is-there-a-suggested-regular-expression-regex-to-check-a-semver-string

This needs to be changed and with a comment to the link from where it came from.

https://github.com/readthedocs/readthedocs.org/blob/ff0ad67991e599f79e9d956a3733785ccb78c505/readthedocs/builds/constants.py#L113-L113

**Comment by stsewd** [comment]
We should keep the `v` at the beginning, isn't valid semver, but looks like it's very common

https://semver.org/#is-v123-a-semantic-version

**Comment by piyushpalawat99** [comment]
I would like to start contributing to readthedocs, can I work on this issue?
