### ISSUE TITLE
Multiple accounts with same Github login?

### ISSUE THREAD

**Issue by WardBenjamin** [readthedocs/readthedocs.org#6400]
## Details

I currently have a ReadTheDocs account (blward) under a work email. I created a second account (benjaminloganward) for personal use, however since my Github account is tied to my work email, it doesn't seem like I can use it for my personal account. Is there a workaround, or can this behavior be changed? Cheers.

* Read the Docs project URL: N/A
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): benjaminloganward, blward

## Expected Result

Expected to be able to use same Github account with multiple ReadTheDocs accounts

## Actual Result

"The social account is already connected to a different account."

**Comment by stsewd** [comment]
We use allauth https://django-allauth.readthedocs.io/en/latest/ to handle that. Not sure about a solution.

>  since my Github account is tied to my work email

Maybe adding a secondary email?

**Comment by WardBenjamin** [comment]
I do have several emails tied to the same Github account. I'll look further into AllAuth.

**Comment by WardBenjamin** [comment]
As far as I'm aware, this is still an issue.

**Comment by stsewd** [comment]
> I do have several emails tied to the same Github account.

Did you try changing the primary email? (on github and/or rtd)

**Comment by humitos** [comment]
I don't think we can fulfill the expectations,

> Expected to be able to use same Github account with multiple ReadTheDocs accounts

Read the Docs does not allow this. One GitHub account is tied to one User account on Read the Docs.

**Comment by humitos** [comment]
Closing this for now. It's not in our plans to support one GH account to many RTD accounts.
