### ISSUE TITLE
Command killed due to excessive memory consumption

### ISSUE THREAD

**Issue by Deech08** [readthedocs/readthedocs.org#6403]
## Details

* Read the Docs project URL: [https://readthedocs.org/projects/whampy](https://readthedocs.org/projects/whampy/)
* Build URL (if applicable): [https://readthedocs.org/projects/whampy/builds/10012491/](https://readthedocs.org/projects/whampy/builds/10012491/)
* Read the Docs username (if applicable): Deech08

## Expected Result

Completed build (such as in previous builds): [https://readthedocs.org/projects/whampy/builds/9844011/](https://readthedocs.org/projects/whampy/builds/9844011/)

## Actual Result

Excessive memory consumption or time-outs

**Comment by stsewd** [comment]
I have increased the memory limit, the buils is passing now https://readthedocs.org/projects/whampy/builds/10020125/

**Comment by Deech08** [comment]
Thanks!
