### ISSUE TITLE
Readthedocs segmentation fault when pytorch is imported

### ISSUE THREAD

**Issue by sunilkpai** [readthedocs/readthedocs.org#6420]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/neurophox/
* Build URL (if applicable): https://readthedocs.org/projects/neurophox/builds/10045416/
* Read the Docs username (if applicable): sunilkpai
* Github URL: https://github.com/solgaardlab/neurophox

## Expected Result

I am using ReadTheDocs to build documentation for my project, and would like a clean build when using pytorch code. Without requiring pytorch in `setup.py`, I get a clean build but I cannot generate pytorch documentation. When requiring pytorch in `setup.py`, I expect to also get a clean build.

## Actual Result

After requiring pytorch in `setup.py`, the build fails with an unhelpful segmentation fault as the html is being generated. What about importing pytorch causes this result? One other issue in the logs seems to be that autodoc-typehints is incompatible with the sphinx version readthedocs uses.

**Comment by humitos** [comment]
We have had this issue before. It seems that PyTorch requires _a lot_ of memory to be imported or even installed.

Just in case, are you able to build your documentation locally (outside of Read the Docs)?

**Comment by sunilkpai** [comment]
I see, ok. Yes, I have indeed been able to use sphinx to build my docs locally.

**Comment by sunilkpai** [comment]
@humitos Any progress on this issue?

**Comment by humitos** [comment]
@suanmeiguo no, I'm not sure there is something we can do. It would be good to have some benchmark about where/how/why pytorch requires that amount of memory to be installed. Although, that would be something that pytorch community could fix in case we found the reason.
