### ISSUE TITLE
Request to enable SEARCH_ANALYTICS feature flag for project scrybe

### ISSUE THREAD

**Issue by manjotpahwa** [readthedocs/readthedocs.org#6421]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/scrybe-docs/
* Build URL (if applicable): https://readthedocs.org/projects/scrybe-docs/builds/
* Read the Docs username (if applicable): manjot

Request to try out the feature. Thanks!

**Comment by stsewd** [comment]
Done! You can check it here https://readthedocs.org/dashboard/scrybe-docs/search-analytics/
