### ISSUE TITLE
<PROJECT_ROOT>/media/json Generator

### ISSUE THREAD

**Issue by ln2khanal** [readthedocs/readthedocs.org#6425]
## This is not a bug reporting!
Hello Team, I have been working on top of the RTD community version. We, as a team is unable to figure out how the `<PROJECT_ROOT>/media/JSON` gets generated. The reason I am asking is not just to know the directory and the file creation, it's rather problems created as some of the projects' content inside the directory gets deleted out, sometimes all the content gets removed.

Would someone else point out what could be the reason for the deletion and how the content actually created?

`RTD version: 3.5.3`

**Comment by stsewd** [comment]
I think you are describing https://github.com/readthedocs/readthedocs.org/pull/6380 

It's fixed in 3.10.0 https://docs.readthedocs.io/en/stable/changelog.html#version-3-10-0
