### ISSUE TITLE
Regain ownership of project “MADAM”

### ISSUE THREAD

**Issue by eseifert** [readthedocs/readthedocs.org#6435]
## Details

* Read the Docs project URL: https://madam.readthedocs.io/
* Build URL (if applicable): https://github.com/eseifert/madam
* Read the Docs username (if applicable): eseifert

## Expected Result

When I am logged in I want to see the project in my list of projects.
When I am logged in I want to be able to edit the project.

## Actual Result

When I am logged in I don’t see the project in my list of projects.
When I am logged in I don’t see an Administration button.

**Comment by stsewd** [comment]
Hi, the maintainer of that project is https://readthedocs.org/profiles/mseifert/ Did you create that project and then give ownership to someone else?

**Comment by eseifert** [comment]
We worked on the project together, but I didn’t remember who created the readthedocs account. I will contact @seifertm. Could the project be transferred or should mseifert delete it and I re-add it?

**Comment by stsewd** [comment]
> Could the project be transferred or should mseifert delete it and I re-add it?

Yes, the project can be transferred, the user has to add you as owner from the admin.

**Comment by eseifert** [comment]
Thanks! That solved the issue.
