### ISSUE TITLE
High memory build queue

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#6446]
We already have a high resource build queue in use currently, however we could be doing more here to push projects towards these queues without intervention.

Probably the best marker we have right now is if the project is built with conda. This is a really good indicator that the project has higher resource demands, and should probably just get more memory and time, and be put into a special queue automatically.

It's not perfect though, because the config file would only be read during build, so at this point we're likely already on a low-resource builder and the build might fail.

A more advanced version of this would be to somehow track peak memory used on the last build and determine the queue from this information.

**Comment by stsewd** [comment]
> It's not perfect though, because the config file would only be read during build, so at this point we're likely already on a low-resource builder and the build might fail.

That isn't true, actually, we use the config file to get the build image, so the docker image isn't created yet when we parse it. So, we can alter the build limits before creating the docker image based on the conda setting.

**Comment by agjohnson** [comment]
Yes, true, but if we have servers specifically set aside for 2-4G memory builds, we'd want builds to be moved to that build queue, hopefully seamlessly.

For instance, most builds could probably happen under low resource build servers, like 2G memory instances. There would be a high cost to spinning up all the servers with enough memory to build large projects.

**Comment by humitos** [comment]
Related to https://github.com/readthedocs/readthedocs.org/issues/6742

**Comment by agjohnson** [comment]
So, if we want to automate queue selection, we have a couple of options:

* Try to build the project on build:default. If it fails with memory issues, requires conda, or something else, upgrade to build:large automatically?
* Try to build the project on build:large first. If the project has X builds that are successful and < 300s, move the project to the build:default queue?

I'm trying to think of a way to automate queue selection for us and reduce the number of errors that projects get up front.

**Comment by humitos** [comment]
We already implemented what @agjohnson suggested in the last comment at https://github.com/readthedocs/readthedocs.org/pull/6849 adding a custom celery router. We just need to remove the feature flag to make it work in all the projects.

We start always with `build:large` and move to `build:default` if we have more than N builds and a time avg of 300s. We also build `conda` projects in `build:large.`
