### ISSUE TITLE
Table layout broken?

### ISSUE THREAD

**Issue by apfelbox** [readthedocs/readthedocs.org#6449]
## Details

* Read the Docs project URL: https://www.doctrine-project.org/projects/doctrine-dbal/en/2.9/reference/types.html#mapping-matrix
* Build URL (if applicable): (?)
* Read the Docs username (if applicable): (?)

## Expected Result

I was browsing the Doctrine documentation, and as I saw the broken table, I decided to fix it. 
However, the syntax for the table looks correct – is there something wrong on the readthedocs-side?

## Actual Result

The table is not rendered (see link above).

## Also

I copy & pasted the table into my local repository (using `sphinx-build 1.8.1`), and there it compiled without issues (even if the layout still wasn't 100% correct).

<details>
<summary>Screenshots</summary>

#### Code

![2019-12-09 at 10 00](https://user-images.githubusercontent.com/1032411/70421763-cb6d1280-1a6a-11ea-8602-369fca8e37e4.png)

#### Rendered
![2019-12-09 at 10 00](https://user-images.githubusercontent.com/1032411/70421785-d58f1100-1a6a-11ea-9a0f-86ab1ac96de9.png)

</details>

**Comment by stsewd** [comment]
Can you please provide a link to your read the docs project?

**Comment by apfelbox** [comment]
Hi @stsewd,

hmm, I thought I was browsing the docs on readthedocs, but apparently they are using their own rst parser / hosting setup.

Sorry for the noise!
