### ISSUE TITLE
CNAME support not working

### ISSUE THREAD

**Issue by dangra** [readthedocs/readthedocs.org#645]
I followed the steps from [CNAME support](http://read-the-docs.readthedocs.org/en/latest/alternate_domains.html#cname-support) but keep getting 404 for http://doc.scrapinghub.com/

``` sh
$ dig doc.scrapinghub.com 
...
doc.scrapinghub.com.    246 IN  CNAME scrapinghub.readthedocs.org.
scrapinghub.readthedocs.org. 247 IN A   162.209.98.227
```

http://scrapinghub.readthedocs.org works fine.

**Comment by acpmasquerade** [comment]
Wasn't working before rebuilt.
