### ISSUE TITLE
Generic Webhooks sent from Github fail with 403

### ISSUE THREAD

**Issue by fxdgear** [readthedocs/readthedocs.org#6450]
I am trying to hook github up to send push events via the generic webhook, why not use github integration? reasons. So we are working around this by trying to use the generic webhook. 

Turns out when GH tries to send the request, I am getting a 403

```json
{"detail":"Authentication credentials were not provided."}
```

I've setup the `secret` value in the webhook form to be the token provided by RTD UI for creating a generic webhook. 

Thanks

**Comment by stsewd** [comment]
Hi, sorry for the late reply. What happens here is: The secret isn't the same as the token.

The secret isn't shown in the integrations menu (rtd creates this secret automatically for you if you are using gitlab/github).

The token is something only used for the generic integration. That token needs to be sent as a post parameter. I don't think GitHub allows you to add a custom post parameter.

You can read more about that here https://docs.readthedocs.io/en/stable/webhooks.html#using-the-generic-api-integration.

**Comment by fxdgear** [comment]
Ok thanks for the response. We were having some issues with the security team not wanting to clear `readthedocs` as a trusted vendor for allowing access through the GH integration. 

so I figured I would try the generic route, to avoid the hassle but it would appear that it's not possible. 

Thanks
