### ISSUE TITLE
Initialize all the attributes in build tasks on `__init__` method

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6452]
Move all the self attributes to the `__init__` method and work from there, right now we initialize the attributes around all the places.

https://github.com/readthedocs/readthedocs.org/blob/c2609f535981e871ff7fe979188cbbe141dd8bc3/readthedocs/projects/tasks.py#L216

https://github.com/readthedocs/readthedocs.org/blob/c2609f535981e871ff7fe979188cbbe141dd8bc3/readthedocs/projects/tasks.py#L301

Ref https://github.com/readthedocs/readthedocs.org/pull/6451#issuecomment-564079573

Edit: I edit the title and the description a little.

**Comment by KartikKapil** [comment]
@stsewd  [class UpdateDocsTaskStep(SyncRepositoryMixin):](url) already has a __init__  method do i need to look for more attributes of the same class to be added to the __init__ method

**Comment by stsewd** [comment]
@KartikKapil we need to refactor all that code, maybe move it out of the tasks.py file. This isn't a good first issue if you are not familiar with the codebase, but feel free to try

**Comment by KartikKapil** [comment]
@stsewd i wanted to give it a try , thank you :)

**Comment by Blackcipher101** [comment]
@stsewd Can I give this issue a try
