### ISSUE TITLE
There is a potentially fraudulent copy of my documentation being hosted by unknown actors on readthedocs

### ISSUE THREAD

**Issue by zzzeek** [readthedocs/readthedocs.org#6456]
## Details

* Read the Docs project URL:

https://sqlalchemy-html.readthedocs.io/

* Build URL (if applicable):
* Read the Docs username (if applicable):

unknown

## Expected Result

This project should not exist.  SQLAlchemy's official documentation is at https://docs.sqlalchemy.org/ .

## Actual Result

A broken copy of my site with no attribution that is also pulling in copyrighted elements from the www.sqlalchemy.org website (note these are NOT MIT licensed elements) and has stale content over a year old is misleading users and also providing an opportunity for malicious intent.

While SQLAlchemy's documentation content is MIT licensed, the branding and site itself is NOT.  I request that he page at https://sqlalchemy-html.readthedocs.io/ be taken down immediately.

**Comment by davidfischer** [comment]
Thanks for letting us know. Before going through formal takedown procedures, I simply emailed the user who controls it on RTD, pointed to this ticket, and asked them to take it down. Hopefully it is resolved easily but if needed we can take the next steps.

**Comment by zzzeek** [comment]
yup im assuming someone put it there when my site was down or something but id rather not have any copies that look just like my page floating out there if at all possible :)

**Comment by davidfischer** [comment]
The user responded and took down the forked docs. I'm glad we could get this resolved the easy way.

**Comment by zzzeek** [comment]
thanks!
