### ISSUE TITLE
Automatic build on pull request for Pyspectral

### ISSUE THREAD

**Issue by adybbroe** [readthedocs/readthedocs.org#6457]
## Details

Could you set the feature flag for automatic builds for PRs on our project, I suppose this is the flag EXTERNAL_VERSION_BUILD?

* Read the Docs project URL: https://pyspectral.readthedocs.io/
* Build URL (if applicable): 
* Read the Docs username (if applicable): adybbroe

## Expected Result

*A description of what you wanted to happen*
I would like to have RTD automatically building pull requests

## Actual Result

*A description of what actually happened*

**Comment by stsewd** [comment]
Done, please check https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html#troubleshooting
