### ISSUE TITLE
Why was my project placed in spam?

### ISSUE THREAD

**Issue by HeaTTheatR** [readthedocs/readthedocs.org#6458]
## Details
Why was my project placed in spam? Error - 406

<img src="https://habrastorage.org/webt/-4/dh/fd/-4dhfd4bcvce2pjxpeearchgm0m.png" />

* Read the Docs project URL: https://readthedocs.org/projects/kivymd/
* Read the Docs username (if applicable): KivyMD

**Comment by stsewd** [comment]
Hi @HeaTTheatR sorry about that, probably a mistake. I'll try to enable your project soon.

**Comment by HeaTTheatR** [comment]
@stsewd Thanks!

**Comment by stsewd** [comment]
Done!
