### ISSUE TITLE
Italicized code sample in function definition section is rendered with Unicode smart quotes

### ISSUE THREAD

**Issue by wesinator** [readthedocs/readthedocs.org#6459]
## Details

* Read the Docs project URL: https://yara.readthedocs.io/en/v3.11.0/modules/hash.html#c.md5
* Build URL (if applicable): https://github.com/VirusTotal/yara/blob/4df40fca364a8fdf29b2f84b2abac26cd16ca75f/docs/modules/hash.rst
* Read the Docs username (if applicable):

## Expected Result

Should render text with normal typed `" "` quotes, everywhere in rst code/function sections.

## Actual Result
Italicized text found in a function declaration is rendered by readthedocs between an `<em>` element, with Unicode smart quotes.
![image](https://user-images.githubusercontent.com/5124946/70870219-73e51000-1f5e-11ea-8de9-1f5211cd35ca.png)
This is a BIG no-no for programming related text.
_NEVER_ render smart quotes in a system that presents text or info used by programmers.

In this case, a user wanting to copy out `Example: hash.md5(0, filesize) == “feba6c919e3797e7778e8f2e85fa033d”` would have to manually replace the so-called 'smart' quotes with normal typed quotes to be able to use the example snippet.

The rst source file uses normal straight quotes, so this is a rendering issue on readthedocs end.

Firefox 71.0

**Comment by stsewd** [comment]
@wesinator can you replicate this locally? Also, can you try with another theme? (like alabaster). If the problem persists, it's an issue from the autodoc side.

**Comment by wesinator** [comment]
> @wesinator can you replicate this locally? Also, can you try with another theme? (like alabaster). If the problem persists, it's an issue from the autodoc side.

yep, seems the smart quotes rendering also happens in alabaster, even on its own doc page - https://alabaster.readthedocs.io/en/latest/#project-background
`Alabaster is a modified (with permission) version of Kenneth Reitz’s “krTheme” Sphinx theme`
vs.
https://github.com/bitprophet/alabaster/blob/33b4b203171e9fe0dc5515f0afabfb4f916323d5/docs/index.rst#project-background

**Comment by stsewd** [comment]
Ok, I dug a little here. Looks like is a thing from docutils https://docutils.sourceforge.io/docs/user/smartquotes.html#id5

If you want to have the original quotes you need to escape them or put the text into double `` so it gets rendered as code.

**Comment by wesinator** [comment]
ah, thanks 

https://github.com/readthedocs/readthedocs.org/issues/2940#issue-234941418  describes how to disable the smart quote rendering
