### ISSUE TITLE
Build exited due to time out

### ISSUE THREAD

**Issue by chillancezen** [readthedocs/readthedocs.org#6460]
## Details

* Read the Docs project URL:
* Build URL (if applicable):
https://readthedocs.org/projects/fortimanager-ansible-collection/builds/
* Read the Docs username (if applicable):
Linky
## Expected Result
success without timeout
*A description of what you wanted to happen*
Build exited due to time out

## Actual Result
Build exited due to time out

*A description of what actually happened*
it takes 9 minutes to `make html` on my local machine.  and it times out on readthedocs builds. 
I have 1233 rst files udner docgen directory. 

could some help to have a look?

thanks.

**Comment by stsewd** [comment]
@chillancezen please check https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html Let me know if the problem persists after following those suggestions, also make sure to only install the libs that are only required to build the docs.

**Comment by chillancezen** [comment]
> @chillancezen please check https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html Let me know if the problem persists after following those suggestions, also make sure to only install the libs that are only required to build the docs.

thanks for your guidance. I will try that

**Comment by chillancezen** [comment]
@stsewd 
hi Santos,  the problem persists.
the library dependency is not the problem, I have over 1200 rst files, that might probably what the issue is. 

could I have a way to increase the timeout threshold before it fails?
also cc @frankshen01
thanks in advance.
Link

**Comment by humitos** [comment]
Hi @chillancezen! If I understand correctly, Fortinet is a company and the documentation hosted is about one of its products. If so, you may consider to use our "Read the Docs for Business" (https://readthedocs.com) solution where you will have more resources to build your docs. Please, let me know if that makes sense. Thanks!
