### ISSUE TITLE
Installing a package with setup.py does not pick the right dependency

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#6462]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/dasher/
* Build URL (if applicable): https://readthedocs.org/projects/dasher/builds/10120006/

## Expected Result

Build should work. Although, it sometimes work --the second time the build is triggered in the same build server (note the `git clone` is not the first command but the `remote set-url` subcommand is used instead). See https://readthedocs.org/projects/dasher/builds/10120010/

## Actual Result

The build fails because when `setup.py` tries to install `dash` (from [`install_requires`](https://github.com/mfaafm/dasher/blob/master/setup.py#L74)) it selects a different package.

```
Searching for dash
Downloading https://files.pythonhosted.org/packages/75/a1/8fd6efd0e03f1548c2db8144d81f09a1debd6941d93c6a37996cf4d78b97/dash-bootstrap-components-0.7.3rc1.tar.gz#sha256=12c456f09f304ef980b5b9b2d5c521397d4d92139805a1497e8414da1f99b58b
Best match: dash bootstrap-components-0.7.3rc1
```

Note that it searches for `dash` but installs `dash-bootstrap-components` instead (`dash` is a valid package name in PyPI: https://pypi.org/project/dash/)

**Comment by humitos** [comment]
I was able to reproduce this issue locally by doing:

```bash
$ docker run --rm -it readthedocs/build:latest /bin/bash
docs@19e869e6738e:/$ cd
docs@19e869e6738e:~$ git clone --no-single-branch --depth 50 https://github.com/mfaafm/dasher.git
docs@19e869e6738e:~$  python3.7 -mvirtualenv --no-site-packages --no-download env
docs@19e869e6738e:~$ ./env/bin/python -m pip install --upgrade pip 
docs@19e869e6738e:~$ cd dasher/
docs@19e869e6738e:~/dasher$ ../env/bin/python setup.py install --force
```

**Comment by humitos** [comment]
Using `../env/bin/python -m pip install dash` install the proper package.

On the other hand, using `pip` to install the package itself also picks the right package:

```
docs@146a938a2043:~/dasher$ ../env/bin/python -m pip install .
Processing /home/docs/dasher
Collecting dash
  Downloading https://files.pythonhosted.org/packages/30/7e/0e7d010ae02797b522e368d53db24ac78f14dc982af6a599c06a67fce576/dash-1.7.0.tar.gz (62kB)
```

**Comment by humitos** [comment]
Executing the command `../env/bin/python setup.py install --force` twice makes the install to work. This seems like a bug in `setuptools` and not on Read the Docs.

**Comment by mfaafm** [comment]
I was also able to reproduce it locally and the bug only happens when installing with ``python setup.py install``.

This also explains why it worked locally and on the ci tests, since tox seems to install it with ``pip install -e .`` when the ``usedevelop=True`` is set. Installing it with pip works.

Still confused though, why it works in some cases then. 
I tried to use ``setuptools==41.0.1`` to use the version it uses in the successful builds, but I also get the same error there.
