### ISSUE TITLE
Edit on GitHub incorrect for "latest" version

### ISSUE THREAD

**Issue by djhoese** [readthedocs/readthedocs.org#6474]
## Details

* Read the Docs project URL: https://satpy.readthedocs.io/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

The link for "Edit on GitHub" should be a valid URL pointing to the correct file in the `master` branch for a project on GitHub when looking at the "latest" version.

## Actual Result

The URL for the latest version is `https://github.com/pytroll/satpy/blob/origin/master/doc/source/index.rst` where the `origin` part is extra. If you remove `origin` then the URL works. What's odd is I don't see this for other project that built ~2 weeks ago (https://pyresample.readthedocs.io/en/latest/).

**Comment by djhoese** [comment]
Just noticed if I pass "?version=master" in the URL then the "Edit on GitHub" URL is correct.

**Comment by djhoese** [comment]
This seems to have fixed itself. The only change I made was setting the default branch from "---" in the web settings to "master", rebuilding, and refreshing my browser page while clearing my browser cache.

So my original issue seems to be fixed.

**Comment by stsewd** [comment]
@djhoese sorry for the late reply. Glad you fixed it. Indeed, this was an old bug, rebuilding the docs should fix it.

**Comment by djhoese** [comment]
I had rebuilt a couple times and done a hard refresh. There may still be a bug related to the '---' default branch selection, but I guess you can just keep that in mind if this comes up with someone else's project.
