### ISSUE TITLE
Missing hyperlinks to source in RTD

### ISSUE THREAD

**Issue by joacorapela** [readthedocs/readthedocs.org#6479]
## Details

* Read the Docs project URL: https://svgpfa.readthedocs.io/
* Build URL (if applicable):https://readthedocs.org/projects/svgpfa/builds/10143120/
* Read the Docs username (if applicable):joacorapela@gmail.com

## Expected Result

My local build has hyperlinks to [source]. I expected that the RTD should also contain these hyperlinks.

## Actual Result

The RTD version does not have hyperlinks to [source].
![local](https://user-images.githubusercontent.com/27322752/71176522-f3762600-2261-11ea-8697-4a867fe4c95c.png)
The above figure shows the documentation built locally.

![RTD](https://user-images.githubusercontent.com/27322752/71176594-17396c00-2262-11ea-84f0-d67c7e0cd86c.png)
The above figure shows the documentation in RTD.

**Comment by stsewd** [comment]
@joacorapela this is happening because rtd isn't using your conf.py and requirements file. This is because you are not using a configuration file and rtd is trying to guess and generating some defaults.

Please use a configuration file to be explicit in how rtd should build your docs https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by joacorapela** [comment]
The orgininal problem happened while using autoapi. I switched to autodoc and I have the same problem. I put the sphinx files in my web server and it looks good, https://sccn.ucsd.edu/~rapela/svGPFA/, but I would prefer to use readthedocs.
J.

**Comment by stsewd** [comment]
@joacorapela yes, doesn't matter what extension you use. You should use a configuration file https://docs.readthedocs.io/en/stable/config-file/v2.html to tell rtd the location of your conf.py file and requirements file.

**Comment by joacorapela** [comment]
Thanks, it worked well for one built
https://readthedocs.org/api/v2/build/10145001.txt
but it failed on the next one
https://readthedocs.org/api/v2/build/10145528.txt

But I guess this is a different issue.
I will close the current issue and open a new one.

Thanks again, Joaquin
