### ISSUE TITLE
Update doxygen to 1.8.16

### ISSUE THREAD

**Issue by swaldhoer** [readthedocs/readthedocs.org#6483]
## Details

* Read the Docs project URL: https://native-lua.readthedocs.io/en/
* Build URL (if applicable): https://native-lua.readthedocs.io/en/add-doxygen/index.html
* Read the Docs username (if applicable): swaldhoer

## Expected Result

Building the doxygen API documentation should fully work.

## Actual Result

Only the doxygen mainpage is included but the ``Data Structures`` and ``Files`` tabs are missing (see [here](https://native-lua.readthedocs.io/en/add-doxygen/docs/api.html)). I re-buid locally with the RTD commands and the documentation was build correctly including the full doxygen page. I guess it's not working on RTD because of the old doxygen version.
Would it be possible to update doxgen on RTD to 1.8.16?

**Comment by humitos** [comment]
We have currently installed 1.8.13 (from Ubuntu Bionic). Do you know if there were significant changes between 1.8.13 and 1.8.16 to make this happen?

**Comment by swaldhoer** [comment]
I installed doxygen 1.8.13 and I get the same wrong result as on RTD. So I am pretty sure the problem comes from an old doxygen version on RTD.

Version 1.8.17 got released these days and I got a correct documentation build locally with that version. So maybe updating to the latest version would be good. Is this possible?

**Comment by humitos** [comment]
We usually only install the versions from Ubuntu and they have 1.8.13 currently. I suppose next Ubuntu 20.04 LTS version will include the newer. If so, our new image will have the new Doxygen by that time.

**Comment by swaldhoer** [comment]
Ok thanks, then I will try to use conda to get a newer doxgen on RTD.

**Comment by swaldhoer** [comment]
@humitos sorry but could you please have a look. I cant get the conda environment working:

- I added an RTD config file https://github.com/swaldhoer/native-lua/blob/add-doxygen/.readthedocs.yml
- I added a conda environment file, which works fine locally https://github.com/swaldhoer/native-lua/blob/add-doxygen/docs/environment.yml

But I get the following error on RTD:

```
Problem in your project's configuration. Invalid "conda.environment": environment not found

git remote set-url origin https://github.com/swaldhoer/native-lua.git
Command time: 0s Return: 0
git fetch origin --force --tags --prune --prune-tags --depth 50
From https://github.com/swaldhoer/native-lua
   1e09b56..031895b  add-doxygen -> origin/add-doxygen
Command time: 0s Return: 0
git checkout --force origin/add-doxygen
Previous HEAD position was 1e09b56 use conda environment on RTD to build the doxygen API documentation
HEAD is now at 031895b next try
Command time: 0s Return: 0
git clean -d -f -f
Command time: 0s Return: 0
```

I do not see a solution for my problem in https://github.com/readthedocs/readthedocs.org/issues/2651, but maybe I overlook something?

**Comment by swaldhoer** [comment]
I have not read the documentation well enough. I used
```yaml
conda:
  file: <file>
```
while this is documented:
```yaml
conda:
  environment: <file>
```

Works as expected. Thanks.
