### ISSUE TITLE
-ext not available on docker-compose setup

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#6490]
After removing the `GITHUB_TOKEN` to pull down and install `-ext` from the `Dockerfile`, we don't have available -ext anymore. This makes some features to not work when developing with docker-compose setup.

As a workaround for now, I'm executing:

```
inv docker.shell --running
pip3 install -e ../readthedocs-ext/
```

This should be an invoke command (maybe at `up` or similar) to make -ext available while using docker-compose or we can pull down and install `-ext` if `GITHUB_TOKEN` was passed when doing `inv docker.build` (only for Core Developers).

**Comment by piyushpalawat99** [comment]
I would like to work on this issue, can anyone guide me through it since I'm not completely familiar with the codebase yet?

**Comment by humitos** [comment]
Hi @piyushpalawat99! This issue is actionable only for Core Developers since it needs access to a private repository. Feel free to find another one. Thanks!

**Comment by humitos** [comment]
This is already done at https://github.com/readthedocs/readthedocs.org/blob/b657dd5bc721db7357b71363494cf814b1a4785a/dockerfiles/Dockerfile#L48-L52
