### ISSUE TITLE
Wrong year in the PDF build

### ISSUE THREAD

**Issue by brunato** [readthedocs/readthedocs.org#6496]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/elementpath/downloads/pdf/latest/
* Build URL: https://readthedocs.org/projects/elementpath/builds/10186071/
* Read the Docs username (if applicable): brunato@sissa.it

## Expected Result

PDF build with date `Dec 31, 2019`

## Actual Result

PDF build with date `Dec 31, 2020`

**Comment by stsewd** [comment]
Thanks for the report. Were you able to reproduce this issue locally? If so, isn't a Read the Docs problem. I can't remember if we do anything with the date from our side.

**Comment by brunato** [comment]
I've tried local build before open the issue and the PDF had the correct date.

**Comment by brunato** [comment]
Before opening the issue I also rebuilt the *stable* of another project that has failed a week before. The same problem happens:

* PDF download URL: https://readthedocs.org/projects/xmlschema/downloads/pdf/stable/
* Build URL: https://readthedocs.org/projects/xmlschema/builds/10186148/

Rebuilding the *latest* today all gone ok:

* PDF download URL: https://readthedocs.org/projects/xmlschema/downloads/pdf/latest/
* Build URL: https://readthedocs.org/projects/xmlschema/builds/10215022/

Nothing has changed on code between the latest published version and today.
Thanks

**Comment by humitos** [comment]
I'd guess that the year is calculated with one timezone (where it was already 2020) and the date with another one. We should find where that date comes from to solve this.

**Comment by austin-plixer** [comment]
This happened to us as well when buildign on the 31st, it was resolved in builds run this week

**Comment by brunato** [comment]
I'm sorry but what *more information* are needed? Don't I've provided enough info with my responses of Jan 7?
Thanks
