### ISSUE TITLE
ericholscher.com blog posts broken links

### ISSUE THREAD

**Issue by NumesSanguis** [readthedocs/readthedocs.org#6506]
## Details
All links I tried to https://ericholscher.com/blog are broken.

E.g.: https://ericholscher.com/blog/2016/jul/1/sphinx-and-rtd-for-writers/
Clickable link in "Getting Started with Sphinx" page: An introduction to Sphinx and Read the Docs for technical writers`

* Read the Docs project URL: https://docs.readthedocs.io/en/latest/intro/getting-started-with-sphinx.html

## Expected Result

Reupload of all blog posts originally hosted on https://ericholscher.com/blog

## Actual Result
All links I tried to https://ericholscher.com/blog are broken

**Comment by stsewd** [comment]
Thanks for the report. The links are missing `www`.

This should work https://www.ericholscher.com/blog/2016/jul/1/sphinx-and-rtd-for-writers/

We need to find all links pointing to that block and add the `www` subdomain.

**Comment by dibyaaaaax** [comment]
can I work on this?
