### ISSUE TITLE
Request: How-to guide on using autodoc with RTD to generate docs from code docstrings / type hints (link to Sphinx-RTD-Tutorial)

### ISSUE THREAD

**Issue by NumesSanguis** [readthedocs/readthedocs.org#6507]
### autodoc
I was trying to find information on how to auto-generated documentation from my code with docstring and type annotations. I couldn't find anything on the [`Getting Started with Sphinx`](https://docs.readthedocs.io/en/latest/intro/getting-started-with-sphinx.html) page, so I assumed RTD did not have such instructions.

Googling gave me the Sphinx documentation (hard to understand) and all kinds of blogpost, who all did it differently / outdated.
Finally I found the [`Sphinx-RTD-Tutorial `](https://sphinx-rtd-tutorial.readthedocs.io/en/latest/sphinx-config.html), which successfully helped me to generate docs from my code.

I think a how-to guide on how to use `autodoc` would be very beneficial to anyone wanting to get module API documentation on RTD.

* Read the Docs project URL: https://docs.readthedocs.io/en/latest/intro/getting-started-with-sphinx.html

## Expected Result

One of the following:
* Finding a link to `Sphinx-RTD-Tutorial ` (https://sphinx-rtd-tutorial.readthedocs.io/en/latest/sphinx-config.html) on the "Getting Started with Sphinx" page or a similar how-to guide under the section "External resources".
* Documentation by RTD themselves on how to setup `autodoc` to work with RTD.

## Actual Result
No link on `autodoc` in combination with RTD, so users know how to get auto-generated docs from Python modules.

**Comment by stsewd** [comment]
Thanks, a how to guide would be great to have

**Comment by NumesSanguis** [comment]
Any plans to add "Sphinx-RTD-Tutorial" or other tutorial to the docs?

**Comment by humitos** [comment]
@NumesSanguis this is not currently in our roadmap, but it's definitely a good improvement to have a how to guide that talks about `sphinx-autodoc`. We are happy to accept a Pull Request with this guide.

**Comment by humitos** [comment]
Unfortunately, this issue is not in our current roadmap and it was already marked as stale. I'm afraid that the core team is not going to work soon on it. I'm closing it for now, and we can revisit it in the future.

It would be good to promote more [`sphinx-autoapi`](https://sphinx-autoapi.readthedocs.io/) than `sphinx-autodoc` though, or even improve their docs there.
