### ISSUE TITLE
Optimize sync repository task by not fully cloning the repository

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#6508]
When triggering a build, besides the build itself, we do a sync of the versions we have in Read the Docs with the branches and tags in the repository (this is done by `SyncRepositoryTaskStep`).

At the moment, we are performing a full clone again just to query the branches and tags. This is usually not a big problem, but if the repository is big enough we are downloading it all again just for very small data needed.

In `git` this can be optimized by just querying the branches and tags remotely in the repository with this command `ls-remote`:

```
$ git ls-remote https://github.com/readthedocs/readthedocs.org | head


06df4171fe6b8f6a76f1e46c8c0715d37bc48361	HEAD
ff094c8ca32201c945648f82f701dec94a204686	refs/heads/19-upgrade
23e85d29df6a8200a1814efe710e4414a8ccb503	refs/heads/RescueTime-master
a927a7c30759c4ad7461525ee55e1a7aed1d490c	refs/heads/add-build-signals
717faa92a7ef00c5cfca7f56dbb0658751e421e5	refs/heads/add-call-to-theme-js
bf0363cd0a566f8077ceb159094e87019a9c8d7b	refs/heads/admin-icon
2071c21d2fa188c0065872ba325ca526aa2478ac	refs/heads/agj/eslint-repair
aab2472351b060f6f85f9fe496197cfb071678a7	refs/heads/agj/install-docs-update
3ae47ea4dd8fa4840e5122c50aa7ad8e10a5e122	refs/heads/agj/remove-symlink-serving
f16189015ef73651eb781f83cf9c5b575599a2a3	refs/heads/agj/ssh-add-key
```

**Comment by stsewd** [comment]
> At the moment, we are performing a full clone again just to query the branches and tags.

We only do a clone once, when building we use the current repo to query the tags/branches. We use `SyncRepositoryTaskStep` only when we receive a webhook that a branch/tag was added or removed.

**Comment by ericholscher** [comment]
Right, this is about optimizing the `SyncRepositoryTaskStep` code, since it can be called quite often, and when we clean builders after each task, it will use a ton of bandwidth.
