### ISSUE TITLE
Request to enable SEARCH_ANALYTICS feature flag for project frc-docs

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#6510]
## Details

* Read the Docs project URL: https://frc-docs.readthedocs.io/
* Build URL (if applicable): https://github.com/wpilibsuite/frc-docs
* Read the Docs username (if applicable): Daltz333

**Comment by stsewd** [comment]
This feature should have been already live after https://github.com/readthedocs/readthedocs.org/pull/6447/. Looks like we forgot to remove the `show_analytics` check in the template


https://github.com/readthedocs/readthedocs.org/blob/master/readthedocs/templates/projects/projects_search_analytics.html

**Comment by Parth1811** [comment]
Hey, I would like to fix this. May need some help though :)
Correct me if I'm wrong, do we simply have to remove this `if` condition and delete the `else` block. Essentially always executing the `if` block

https://github.com/readthedocs/readthedocs.org/blob/013f7bee9a137630fa7f2520e474df8b0292cc5c/readthedocs/templates/projects/projects_search_analytics.html#L14-L58

**Comment by stsewd** [comment]
@Parth1811 yes. There is another check for `show_analytics` in that file that should be removed as well.

**Comment by Parth1811** [comment]
Ok got it.

https://github.com/readthedocs/readthedocs.org/blob/013f7bee9a137630fa7f2520e474df8b0292cc5c/readthedocs/templates/projects/projects_search_analytics.html#L73
