### ISSUE TITLE
openra.readthedocs.org is already taken

### ISSUE THREAD

**Issue by Mailaender** [readthedocs/readthedocs.org#6514]
Hi, I want to solve https://github.com/OpenRA/OpenRA/issues/14225 with your awesome service. However someone already registered https://openra.readthedocs.io/ referencing a non-existing repository and deleted user name so I couldn't contact him first. Can you please free the sub-domain and project name?

**Comment by stsewd** [comment]
We follow this policy https://docs.readthedocs.io/en/stable/abandoned-projects.html for cases like this

**Comment by Mailaender** [comment]
Pinging @Rekojeht

**Comment by Rekojeht** [comment]
It has been a long time.. forgot I was the maintainer of that initiative. Let's work together to make that resource the best it can be! :)

**Comment by Mailaender** [comment]
Ha, I found you in the OpenRA bug tracker. :) Can you point it to https://github.com/OpenRA/docs/?

**Comment by Mailaender** [comment]
First you tell me to wait 6 months, now this gets auto-closed for inactivity. It's a bit ridiculous. We went with https://docs.openra.net/ now, but https://openra.readthedocs.io/ is still in hands of a stranger.

**Comment by stsewd** [comment]
@Mailaender the first step is for you to try to contact the owner, if are unable to do so, we try to contact the owner and wait 6 weeks.

Also, from https://github.com/readthedocs/readthedocs.org/issues/6514#issuecomment-574175855 I understood that was about to be solved.

https://docs.readthedocs.io/en/stable/abandoned-projects.html

> The candidate is able to demonstrate their own failed attempts to contact the existing owner

**Comment by Rekojeht** [comment]
Sorry, had some personal issues come up and completely forgot about this. How do I turn over this to whomever wants it? :)

**Comment by stsewd** [comment]
@Rekojeht you need to add the user as maintainer in https://readthedocs.org/dashboard/openra/users/

**Comment by Mailaender** [comment]
Nothing has really happened. :(

**Comment by stsewd** [comment]
@Mailaender what's your rtd user so @Rekojeht can add you as mantainer?

**Comment by Mailaender** [comment]
https://readthedocs.org/profiles/Mailaender/

**Comment by Rekojeht** [comment]
I have added you! I am so sorry it took so long to get this done. Please
feel free to remove me so I don't cause any further trouble on this. I
don't even know how I created this to begin with! I don't think I have ever
contributed anything to OpenRA. :(

**Comment by stsewd** [comment]
I can see you as maintainer now https://readthedocs.org/projects/openra/. Thanks @Rekojeht!

**Comment by Mailaender** [comment]
Thanks for handing it over. I removed you as the policy is that only engine maintainers should have access on official documentation. Your idea was good though. http://docs.openra.net is a life saver as the GitHub wiki renderer will timeout frequently as our documentation got so large.
