### ISSUE TITLE
Python 3 only code results in empty docs with no configuration file

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [readthedocs/readthedocs.org#6515]
## Details

* Read the Docs project URL:
https://readthedocs.org/projects/pygithub/
* Build URL (if applicable):
https://readthedocs.org/projects/pygithub/builds/10208150/
* Read the Docs username (if applicable):

## Expected Result

That the build would have failed, or at least warned -- some of the source files used Python 3 only code constructs since that commit removed Python 2 support, but they were blindly ignored and generated empty docs.

This may well be an upstream Sphinx bug, but I'd also expect this to happen more often in the future as more projects move away from Python 2. But this was also done with no configuration file, so everything default.

## Actual Result

The build passed with no warnings.

**Comment by stsewd** [comment]
You can actually see warning in the sphinx build step
 
![Screenshot_2020-01-13 PyGithub Read the Docs](https://user-images.githubusercontent.com/4975310/72267113-826e2800-35ed-11ea-9fa3-7a0ea26b64e3.png)


We want to improve that https://github.com/readthedocs/readthedocs.org/issues/4226
