### ISSUE TITLE
Make the readthedocs template a GitHub template

### ISSUE THREAD

**Issue by Mailaender** [readthedocs/readthedocs.org#6522]
Hello, can you make https://github.com/readthedocs/template a GitHub template repository?

* https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository
* https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template

Sorry for posting it here, but the template issue tracker is disabled.

**Comment by stsewd** [comment]
Curious about the reason. That project is mostly to show some rtd features when you create a new account. Looks out of date with the current sphinx version (repo was updated 6 years ago)

**Comment by Mailaender** [comment]
It's what gets build when you click https://readthedocs.org/dashboard/import/manual/demo/

**Comment by stsewd** [comment]
Yes, it's only used for that.

**Comment by Mailaender** [comment]
Thought it would be a good idea to fork it and start there.
