### ISSUE TITLE
Bad link to fabfile.py in Internationalization page in documentation

### ISSUE THREAD

**Issue by rffontenelle** [readthedocs/readthedocs.org#6525]
## Details

* Read the Docs project URL: https://docs.readthedocs.io/en/latest/development/i18n.html#transifex-integration
* Build URL (if applicable): n/a
* Read the Docs username (if applicable): n/a

## Expected Result

Clicking "fabric script" hyperlink should get to such script in the URL https://github.com/readthedocs/readthedocs.org/blob/master/fabfile.py

## Actual Result

Clicking such hyperlink results in 404 not found, as the script is not in the root directory of readthedocs repository

**Comment by stsewd** [comment]
We us invoke with a tasks.py file now https://github.com/readthedocs/readthedocs.org/blob/master/tasks.py.

**Comment by rffontenelle** [comment]
@stsewd Would you say it is enough to simply replace the URL then?

**Comment by stsewd** [comment]
Yeah, the paragraph and url should be updated.

**Comment by preetmishra** [comment]
@stsewd Can I work on this?

**Comment by rffontenelle** [comment]
@preetmishra Hey, feel free to provide a pull request to solve this.

**Comment by susanka068** [comment]
Is the isuue still open ?
then I'd like to work on this .

**Comment by susanka068** [comment]
is the issue still open ! and if nobody is working on this ! can i work on this  ?

**Comment by rffontenelle** [comment]
@susanka068 I seems @preetmishra wants to work on this, but check with him.

**Comment by susanka068** [comment]
fixed this issue #6532 @rffontenelle

**Comment by stsewd** [comment]
@susanka068 you need to update the paragraph too.

**Comment by preetmishra** [comment]
@susanka068 I have already a attached a PR. @rffontenelle @stsewd Can you please review it? #6531
