### ISSUE TITLE
Build error with build #10263776

### ISSUE THREAD

**Issue by pgunn** [readthedocs/readthedocs.org#6526]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/caiman
* Build URL (if applicable): https://readthedocs.org/projects/caiman/builds/10263776/
* Read the Docs username (if applicable): caiman

## Expected Result

*A description of what you wanted to happen*
Builds complete (or fail with an error we might fix)

## Actual Result

*A description of what actually happened*
Surprising timeout for the last several builds while conda environment is built. No clear path to fix it.

**Comment by pgunn** [comment]
I tried trimming some packages out that are not needed to build the environment, but we'd have trouble trimming things down further. The most recent build got us:

```
Killed


Command killed due to excessive memory consumption
```

**Comment by pgunn** [comment]
I've trimmed out as much as I can (this may be too small), and it's still running out of memory while trying to build the conda environment:

https://readthedocs.org/projects/caiman/builds/10266550/

I'm wary of building a new way to build our software to deal with this (particularly as we subclass some things in numpy and would like to only think about conda versioning, plus installing tensorflow through pip pulls in hundreds of megabytes of other stuff).

What do you recommend?

**Comment by stsewd** [comment]
Hi @pgunn if you have followed https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html in it's still running out of memory, I can try to increase the resources for your project tomorrow.

**Comment by stsewd** [comment]
I have increased the build resources for your project. I triggered two builds and they succeeded https://readthedocs.org/projects/caiman/builds/10271346/ https://readthedocs.org/projects/caiman/builds/10271260/
