### ISSUE TITLE
Introduce sphobjinv as dependency for intersphinx operations

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6529]
Right now we are using the package from intersphinx itself to handle operations like this.

https://github.com/readthedocs/readthedocs.org/blob/0be5a61c457a1eb09265ca1962e7c76db1b6f02d/readthedocs/projects/tasks.py#L1433-L1484

Which as you can see, it doesn't have a great API. The `sphobjinv` package (https://sphobjinv.readthedocs.io/en/latest/) has a great API and can be used as a CLI too. We could use it for a future feature for intersphinx too.

**Comment by humitos** [comment]
I'm :+1: on re-writing that section using this external library. It could be good to receive some help from the community here by marking this issue as Good First Issue.

**Comment by susanka068** [comment]
I'd like to work on this issue

**Comment by humitos** [comment]
We have removed this code completely from our code base.
