### ISSUE TITLE
Animation on "View the docs" Button

### ISSUE THREAD

**Issue by Blackcipher101** [readthedocs/readthedocs.org#6536]
## Details
The "view the docs" button should get an animation when you hover over it, as every other button on the page are animated it would make it look more standardised
gif can found at the bottom of the issue

## Expected Result
Animation when hovered over it

## Actual Result
No animation present

## GIF 
![ezgif com-crop](https://user-images.githubusercontent.com/33775493/72666265-7e4f6980-3a36-11ea-847a-eab97f3d07ff.gif)

**Comment by Blackcipher101** [comment]
I am starting to working on the issue

**Comment by stsewd** [comment]
Not sure if that was part of the design. Also, we are working on a redesign of the site

**Comment by Blackcipher101** [comment]
@stsewd should I work on this or continue with something else

**Comment by stsewd** [comment]
@Blackcipher101 issues with a design decision label need to wait to have a decision made from the core team before doing a PR

**Comment by Blackcipher101** [comment]
@stsewd Any updates on this? I have the all ready made the changes. If its fine with you, I can send the PR

**Comment by stsewd** [comment]
This still needs a design decision. Since we are working on the site redesign, this isn't a priority

**Comment by humitos** [comment]
This was completely re-designed in the new beta templates. Take a look at them at https://beta.readthedocs.org
