### ISSUE TITLE
PDFs are not deleted from buildmedia.readthedocs.org when project is deleted

### ISSUE THREAD

**Issue by fguillot** [readthedocs/readthedocs.org#6538]
I have deleted my project from "Read The Docs" a long time ago. But the PDF versions of the docs are still present and referenced in Google. These documents are obsolete. This creates confusion for my users.

Deleting a project from "Read The Docs" should automatically remove all associated artifacts on your object storage/CDN.

Examples:

- `https://buildmedia.readthedocs.org/media/pdf/miniflux/2.0.12/miniflux.pdf`
- `https://buildmedia.readthedocs.org/media/pdf/miniflux/2.0.14/miniflux.pdf`
- `https://buildmedia.readthedocs.org/media/pdf/miniflux/2.0.15/miniflux.pdf`
- etc.

The folder `https://buildmedia.readthedocs.org/media/pdf/miniflux/` should be removed.

Thank you

**Comment by humitos** [comment]
I think we introduce this bug when we moved from PDF on local disk to PDF on storage.

**Comment by humitos** [comment]
This bug is still present. Marking as accepted because we want to fix it.

**Comment by stsewd** [comment]
I have tested this, and deactivating a version or deleting the project does remove the files from storage. This may have been an error while deleting this project or something from when we changed from storage. I have deleted the associated files.

**Comment by kchudnovskiy** [comment]
I ran into the same issue. Could you please delete the associated files?
https://buildmedia.readthedocs.org/media/pdf/omf-developers-companion/latest/omf-developers-companion.pdf

**Comment by stsewd** [comment]
I checked, and that project does no longer exist in our DB, so I went ahead and removed all files from storage related to that project. If you still see the file, it's probably our CDN, it should clear in a while. You can verify that the file isn't there any more by hitting https://buildmedia.readthedocs.org/media/pdf/omf-developers-companion/latest/omf-developers-companion.pdf?dontcache
