### ISSUE TITLE
build Passed but Documentation not updated

### ISSUE THREAD

**Issue by Borda** [readthedocs/readthedocs.org#6540]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pytorch-lightning
* Build URL (if applicable): https://readthedocs.org/projects/pytorch-lightning/builds/10291191
* Read the Docs username (if applicable): Borda or waf04

### Expected Result

Updated documentation generated with Sphinx instead of MKDocs

### Actual Result

still, the old documentation generated by MKDocs

## Aditional context

We have been using MKDocs till for a while, then we transformed the docs do Sphinx a,d yesterday we also changed the documentation type in RTD setting. So now the documentation is built but there is no update on pytorch-lightning.rtfd.io
I have forked the project and created alternative documentation with the same configuration -https://readthedocs.org/projects/torch-lightning/builds/10287354 and here as expected the documentation is generated and deployed... the only difference is that the fork project was Sphinx since the beginning compared to the original one.

Similar to https://github.com/readthedocs/readthedocs.org/issues/2356

**Comment by stsewd** [comment]
I think I saw a similar case a while ago, I'll try to dig a little more this week.

**Comment by Borda** [comment]
@stsewd I am wondering if deleting the original project and creating it again would help... ?

**Comment by stsewd** [comment]
@Borda are you still experimenting this problem? I can see files were updated yesterday in the servers

**Comment by Borda** [comment]
it seems that it is fine now...
