### ISSUE TITLE
[DOC]: Broken link in the docs

### ISSUE THREAD

**Issue by s-weigand** [readthedocs/readthedocs.org#6541]
## Details

The docs contain a [broken link](https://docs.readthedocs.io/en/latest/yaml-config.html), which is referenced in [Local settings](https://docs.readthedocs.io/en/latest/development/design/yaml-file.html#local-settings) and [Spec](https://docs.readthedocs.io/en/latest/development/design/yaml-file.html#spec) subsections of the [YAML Configuration File](https://github.com/readthedocs/readthedocs.org/blob/master/docs/development/design/yaml-file.rst) section.

I guess that link should be to the [general config spec page](https://docs.readthedocs.io/en/latest/config-file/index.html) or the [v2 spec page](https://docs.readthedocs.io/en/latest/config-file/v2.html)

**Comment by stsewd** [comment]
We actually have a redirect for that... Not sure why isn't working. And we should use the :ref: role here instead of raw links

**Comment by stsewd** [comment]
The redirect not working may be a bug introduced with proxito

**Comment by Blackcipher101** [comment]
@stsewd can I start working on the issue

**Comment by stsewd** [comment]
Redirects are working again. Fixed in https://github.com/readthedocs/readthedocs.org/pull/6558

**Comment by s-weigand** [comment]
Thanks
