### ISSUE TITLE
Could not read username, terminal prompts disabled

### ISSUE THREAD

**Issue by YourMCGeek** [readthedocs/readthedocs.org#6544]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/shadownode-rtd/
* Build URL (if applicable): https://readthedocs.org/projects/shadownode-rtd/builds/10292571/
* Read the Docs username (if applicable): YourMCGeek

## Expected Result

The docs should build as travis-ci has passed it and successfully built it.

## Actual Result

I'm provided with the following error ![](http://boomer.pw/i/lZRRMT87.png)

### Edit
The repo is public!

**Comment by stsewd** [comment]
> The repo is public!

I can't access https://github.com/YourMCGeek/ShadowNode-RTD

**Comment by YourMCGeek** [comment]
> > The repo is public!
> 
> I can't access https://github.com/YourMCGeek/ShadowNode-RTD

I made a typo and now feel stupid :( Thanks for the quick reply though!
