### ISSUE TITLE
Pip 20.0 Causes broken builds

### ISSUE THREAD

**Issue by kevdagoat** [readthedocs/readthedocs.org#6552]
## Details

* Read the Docs project URL: https://hack-technicolor.readthedocs.io/en/stable/?badge=stable
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

Docs to successfully build.

## Actual Result

The build fails with a pip error.
![767D23CA-E489-4C10-9CB3-1282FA48549B](https://user-images.githubusercontent.com/42062334/72804739-14c89880-3c8c-11ea-9d84-899b213c426e.jpeg)

As per: 
https://github.com/pypa/pip/issues/7217
My suggestion would be to downgrade to pip version 19.

**Comment by p-l-** [comment]
Hi there!

Same for [cea-sec/ivre](https://github.com/cea-sec/ivre): https://readthedocs.org/projects/ivre/builds/10297635/.

I followed the same path as @kevdagoat and saw pypa/pip#7217: The current only workaround is to downgrade pip.

**Comment by GrahamDumpleton** [comment]
Version 20.0.1 of pip has just been released and is said to perhaps fix this.

**Comment by GrahamDumpleton** [comment]
Possibly took a bit for latest pip to propagate through, but builds working okay for me now.

**Comment by stsewd** [comment]
Hi, looks like there is a new pip release that fixes the problem. If you are still getting pip 20.0.0, you can force a clean installation by wiping the environment https://docs.readthedocs.io/en/stable/guides/wipe-environment.html

**Comment by kevdagoat** [comment]
Thanks all. I have forced built it and it is now working perfectly.
