### ISSUE TITLE
Latest pip release fails

### ISSUE THREAD

**Issue by kerimoyle** [readthedocs/readthedocs.org#6554]
## Details

* Read the Docs project URL:  https://readthedocs.org/projects/libcellml-tutorials
* Build URL (if applicable): https://readthedocs.org/projects/libcellml-tutorials/builds/10297974/  but the error was first encountered here: https://readthedocs.org/projects/libcellml-tutorials/builds/10297436/ when pip was updated

## Expected Result

Build without failing ... :)

## Actual Result

Currently all builds are failing because the automatic upgrade (since https://github.com/readthedocs/readthedocs.org/issues/4823 ) to pip 20.0 was buggy (see https://github.com/pypa/pip/issues/7620 ).  There's now a 20.0.1 release which seems to have fixed the problem for others ... but how can I force my readthedocs to also upgrade to the .1 version?

**Comment by stsewd** [comment]
Hi, you can force a clean installation by wiping the environment https://docs.readthedocs.io/en/stable/guides/wipe-environment.html

That will download the latest pip instead of using one from cache

**Comment by kerimoyle** [comment]
Brilliant - thanks so much for the quick reply :)

**Comment by Aricg** [comment]
Hi,
Wiping master or latest only fixes this for me for a single build, the next one fails with the same error.
All builds are triggered via the v3 api.
```
ImportError: cannot import name 'PackageFinder' from 'pip._internal.index' (/home/docs/checkouts/readthedocs.org/user_builds/o-ran-sc-doc/envs/master/lib/python3.7/site-packages/pip/_internal/index/__init__.py)
```

**Comment by stsewd** [comment]
@Aricg that's weird. Did you wipe only once? I can think of a reason where the wipe didn't propagate to all servers.

**Comment by Aricg** [comment]
@stsewd  I have done it multiple times to both stable and master to try to make it "take"

**Comment by stsewd** [comment]
@Aricg can you please trigger a wipe for latest but don't trigger any build. I want to check the servers for something

**Comment by stsewd** [comment]
@Aricg I just did it by myself from the admin. I think I found the problem https://github.com/readthedocs/readthedocs.org/pull/6571

**Comment by peterjc** [comment]
Like @Aricg in the last day or so I have tried wipe only for the problem to recur:
https://readthedocs.org/projects/thapbi-pict/builds/

It looks like the fix for #6571 was merged about 25 minutes ago, so hopefully the fix will go live shortly.

**Comment by stsewd** [comment]
@peterjc probably it will be live next week

**Comment by peterjc** [comment]
Thanks - I'll do a manual wipe as needed until then.

**Comment by johannfaouzi** [comment]
Is it possible to do a manual wipe for pull requests? I can't find a way to do so.

**Comment by humitos** [comment]
@johannfaouzi currently, no. We don't support that yet.

**Comment by SchoolGuy** [comment]
This is breaking this PR https://github.com/cobbler/cobbler/pull/2254 

The build environment cannot be wiped because this is (at least to my knowledge) not possible on PR's.

**Comment by stsewd** [comment]
@SchoolGuy see https://github.com/readthedocs/readthedocs.org/issues/6566
