### ISSUE TITLE
v3 api version-update method not working

### ISSUE THREAD

**Issue by Aricg** [readthedocs/readthedocs.org#6559]
## Details
I am trying to activate/deactivate versions via the v3 api
https://docs.readthedocs.io/en/stable/api/v3.html#version-update

This is implemented per your docs, however does not appear to be
it working yet as this always returns a 404.

```
$ lftools rtd project-version-update o-ran-sc-doc master false
{'active': 'false', 'privacy_level': 'public'}
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://readthedocs.org/api/v3/projects/o-ran-sc-doc/version/master/
```

Code on our end:

```
    def project_version_update(self, project, version, active,
                               privacy_level):
        """Edit a version.

        :param project: The project slug
        :param version: The version slug
        :param active: 'true' or 'false'
        :param privacy_level: 'public' or 'private'
        :return: {result}
        """
        data = {
            'active': active,
            'privacy_level': privacy_level
        }
        print(data)

        json_data = json.dumps(data)
        result = self.patch('projects/{}/version/{}/'.format(project, version),
                            data=json_data)
        return result
```

## Expected Result

I can activate versions via the API 

## Actual Result

API method returns 404.

**Comment by stsewd** [comment]
Believe there is a typo in the docs, it should be `projects/{project}/versions/{version}`

**Comment by Aricg** [comment]
Yep, there we go. thanks.

**Comment by Aricg** [comment]
Hi @stsewd  No longer returns a 404,
but its not updating the field.

**Comment by Aricg** [comment]
```$ lftools rtd project-version-update o-ran-sc-doc master false
{'active': 'false', 'privacy_level': 'public'}
<Response [204]>
```

**Comment by Aricg** [comment]
Changed to bool, still no dice.

```
$ lftools rtd project-version-update o-ran-sc-doc master false
{'active': False}
<Response [204]>
```
```
 'active_versions': [{'_links': {'_self': 'https://readthedocs.org/api/v3/projects/o-ran-sc-doc/versions/master/',
                                 'builds': 'https://readthedocs.org/api/v3/projects/o-ran-sc-doc/versions/master/builds/',
                                 'project': 'https://readthedocs.org/api/v3/projects/o-ran-sc-doc/'},
                      'active': True,
                      'built': True,
                      'downloads': {'htmlzip': 'https://docs.o-ran-sc.org/_/downloads/en/master/htmlzip/'},
                      'id': 4914070,
                      'identifier': 'origin/master',
                      'ref': None,
                      'slug': 'master',
                      'type': 'branch',
                      'urls': {'documentation': 'https://docs.o-ran-sc.org/en/master/',
                               'vcs': 'https://gerrit.o-ran-sc.org/r/doc'},
                      'verbose_name': 'master'},
```

**Comment by stsewd** [comment]
I'll try to dig into this later.

If you only want to activate new versions based on something, you can use https://docs.readthedocs.io/en/stable/automation-rules.html btw

**Comment by Aricg** [comment]
@stsewd It works via curl, so I'm guessing its on our side right now, digging into it.
Did you remove 'privacy_level' from the api?

**Comment by stsewd** [comment]
@Aricg yes, we removed the `privacy_level` field, that's part of https://github.com/readthedocs/readthedocs.org/issues/3781

**Comment by Aricg** [comment]
@stsewd Hi if you forget the trailing slash on PATCH /api/v3/projects/(string:project_slug)/version/(string:version_slug)/
it should return a 404 and not a 204. :D  (it's fixed)

**Comment by Blackcipher101** [comment]
@stsewd is this bug still valid if yes can I work on it

**Comment by Aricg** [comment]
@Blackcipher101  Just the documentation needs to be updated to fix the typo
"it should be projects/{project}/versions/{version}" (versions not version)
There is already an issue about the privacy level stuff.

**Comment by preetmishra** [comment]
@stsewd Has this been fixed? If not, can I work on this one?

**Comment by stsewd** [comment]
@preetmishra there is a PR already open
