### ISSUE TITLE
ImportError: cannot import name 'PackageFinder' from 'pip._internal.index'

### ISSUE THREAD

**Issue by pmoura** [readthedocs/readthedocs.org#6562]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/logtalk3/
* Build URL (if applicable): https://readthedocs.org/projects/logtalk3/builds/10301484/
* Read the Docs username (if applicable): pmoura

## Expected Result

Build succeeding.

## Actual Result

Build fails.

**Comment by stsewd** [comment]
Please check https://github.com/readthedocs/readthedocs.org/issues/6554
