### ISSUE TITLE
Inline reference in Chinese docs

### ISSUE THREAD

**Issue by wayneyou** [readthedocs/readthedocs.org#6565]
I tried to build docs written in Chinese, but it does work. For details, please refer to the zip folder.

[issue.zip](https://github.com/readthedocs/readthedocs.org/files/4094972/issue.zip)

The following is my repo on github:

https://github.com/wayneyou/nebula/blob/pdfcn/docs/1.overview/2.quick-start/1.get-started.md

**Comment by humitos** [comment]
@wayneyou can you describe exactly what's your issue? What's the actual behavior and what are you expecting?
