### ISSUE TITLE
Cannot wipe PR builder environment to fix "ImportError: cannot import name 'PackageFinder'"

### ISSUE THREAD

**Issue by huonw** [readthedocs/readthedocs.org#6566]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/stellargraph
* Build URL (if applicable): https://readthedocs.org/projects/stellargraph/builds/10303275/
* Read the Docs username (if applicable): huonw

We're using the beta PR builder (it's great :+1:), and unfortunately hit #6554 for those builds. We followed the instructions there to try to wipe the environment, but there's no explicit "version" for a PR builder:

![image](https://user-images.githubusercontent.com/1203825/72865934-ba801400-3d2d-11ea-820a-10998ddd17e4.png)

I tried wiping the `latest` environment, but our PR builds continued to fail (although it did fix our `latest` ones).

## Expected Result

After wiping some appropriate environment, new PR builds should start from a new environment, e.g. the wiping above did fix it for our `latest` builds:

- `latest` build before wiping `latest` (❌): https://readthedocs.org/projects/stellargraph/builds/10302298/
- `latest` build, after wiping `latest` (✅): https://readthedocs.org/projects/stellargraph/builds/10303293/

## Actual Result

I couldn't find a "PR" environment in the list of versions, and wiping the `latest` environment didn't affect the PR one:
- PR build, before wiping `latest` (❌): https://readthedocs.org/projects/stellargraph/builds/10303254/
- PR build, after wiping `latest` (❌): https://readthedocs.org/projects/stellargraph/builds/10303275/

**Comment by humitos** [comment]
Thanks for your report. This is definitely a problem, since there is no way to wipe an environment for a PR :)

I do not have a proper workaround to recommend you, and I'm not sure we are going to implement a way to wipe PRs environment since we are migrating to a different approach (without cache, maybe).

I can tell that this problem should be automatically fixed after one day without builds on each version because this cache is automatically deleted. If that does not happen in the following days, let me know and I will try to dig a little more.

**Comment by sobolevn** [comment]
Related: https://github.com/pypa/pip/issues/7620

**Comment by huonw** [comment]
> I do not have a proper workaround to recommend you, and I'm not sure we are going to implement a way to wipe PRs environment since we are migrating to a different approach (without cache, maybe).

Ok, thanks.

> I can tell that this problem should be automatically fixed after one day without builds on each version because this cache is automatically deleted. If that does not happen in the following days, let me know and I will try to dig a little more.

Unfortunately we have many PR pushes on weekdays so maybe it won't have a chance for deletion for a while. However, we usually don't have any new work on weekends, so maybe that'll give it a chance to be deleted.

**Comment by brockfanning** [comment]
We're just using the standard setup, as far as I know (not sure what PR builder is) but we're also getting the same error on all builds (`cannot import name PackageFinder`) as of today ([example build](https://readthedocs.org/projects/open-sdg/builds/10314805/)). So I'm wondering if it is a more general problem.

**Comment by stsewd** [comment]
@brockfanning for normal builds, please check https://github.com/readthedocs/readthedocs.org/issues/6554#issuecomment-577409023.

**Comment by huonw** [comment]
We just had a long weekend (88 hours) without any pushes/builds:

![image](https://user-images.githubusercontent.com/1203825/73235271-d4b06b00-41e1-11ea-9080-f4f0d1bc1777.png)

And, unfortunately, we're still hitting this, but somewhat inconsistently, e.g. for https://github.com/stellargraph/stellargraph/pull/730 :

1. https://readthedocs.org/projects/stellargraph/builds/10338264/ ✅ 
2. https://readthedocs.org/projects/stellargraph/builds/10338747/  ✅ 
3. https://readthedocs.org/projects/stellargraph/builds/10338749/ ❌  (one minute after 2)
4. https://readthedocs.org/projects/stellargraph/builds/10338940/ ❌ 

This applies to other PRs too, e.g. the first page of https://readthedocs.org/projects/stellargraph/builds/ currently has 6 PR passes and 8 PR failures (and all of them seem to be this `ImportError`):

![image](https://user-images.githubusercontent.com/1203825/73235371-53a5a380-41e2-11ea-9630-5e37562dc9a1.png)

**Comment by stsewd** [comment]
With https://github.com/readthedocs/readthedocs.org/pull/6598, this may be fixed (installing the buggy version of pip). Wiping still isn't supported

**Comment by ericholscher** [comment]
We are no longer keeping the build environment around, so wiping won't be supported.
