### ISSUE TITLE
Minor improvements to El Proxito

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#6567]
We have deployed el El Proxito and most documentation is being served through it now. Although, while deploying it we found some small bugs and edge cases that we quickly covered, introducing a shortcut or breaking a little the pattern that we had.

This issue is a way to collect these PR and this about how to refactor those cases to match the pattern that we already had:

* https://github.com/readthedocs/readthedocs.org/pull/6558
* run redirect tests through El Proxito
* https://github.com/readthedocs/readthedocs.org/pull/6564

**Comment by ericholscher** [comment]
I don't quite understand what this ticket is about? Is there an actual improvement in it?

**Comment by humitos** [comment]
We already addressed the three of them that are listed. I'm closing it.
