### ISSUE TITLE
Build killed due to excessive memory consumption

### ISSUE THREAD

**Issue by nikhilaravi** [readthedocs/readthedocs.org#6578]
## Details

* Read the Docs project URL: https://pytorch3d.readthedocs.io/en/latest/overview.html
* Build URL (if applicable): https://readthedocs.org/projects/pytorch3d/builds/10317957/
* Read the Docs username (if applicable): nikhilaravi

## Expected Result

Completed build.

## Actual Result

Build failed due to excessive memory consumption. 

We need to build a library which has C++ and CUDA kernels so it requires more memory than is available.

**Comment by nikhilaravi** [comment]
@humitos  would you be able to help us increase the memory and resolve this issue?

**Comment by nikhilaravi** [comment]
Update: the build works now so no need for increased memory!! I unclicked the 'Install Project' box in advanced settings and that seemed to resolve the issue.

**Comment by humitos** [comment]
Cool! Yeah, unfortunately, we don't have a good solution for installing pytorch at the moment :/
