### ISSUE TITLE
[Feature Request] Rerun/restart option for auto PR builder

### ISSUE THREAD

**Issue by pllim** [readthedocs/readthedocs.org#6580]
I have been using your auto PR builder feature and loving it. However, once in a while, the RTD run fails due to spurious error that usually goes away after a rerun (or restart, however you like to call it). When that happens in a build tied to a PR of a project that I have admin access to, the only way I know how to rerun it is to push a new commit or modify the existing commit and then force push. I only see rerun/restart option for branches on the repo, but not for the PRs. 

It would be nice to be able to click rerun/restart on a failed PR build on ReadTheDocs project dashboard when you have admin access to it.

**Comment by saadmk11** [comment]
One way to re-start a build is closing and reopening the PR.
related: https://github.com/readthedocs/readthedocs.org/issues/6524

**Comment by pllim** [comment]
Ah, okay. I'll close this issue as duplicate then. Thanks!
