### ISSUE TITLE
Add a permalink redirection in built docs

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#6587]
Currently, permalinks in Sphinx are tied to a specific page, and you need to know the page to link to the permalink. One feature we've discussed and played around with in the past is using our internal models of SphinxDomain domain data (and other Sphinx references) to redirect reader users to the correct page + anchor based on a reference id.

There is some overlap with features here:

* User wants a permalink to a section that has moved pages -- redirects could be used here instead, and this case should be relatively infrequent

In addition, there are some new use cases covered by this feature:

* User wants a short link into a section, without needing a page name
* We would have to think more on the implications here, but it could potentially even be a monkey patch for intersphinx. Currently, the difficulty with intersphinx is that the build needs access to multiple projects to access the objects.inv. An intersphinx replacement, with a mapping of `{'django': 'https://docs.djangoproject.org/..../'}` would simply output links `https://docs.djangoproject.org/_/ref/en/latest/py:class/Model`, and leave access control to RTD. This would push intersphinx complexity away from build time and put it right back into our authorization flow. Something to consider as a downstream effect of this at very least.

Some example URL options:

* `foo.example.com/_/ref/en/latest/py:class/foo_method`
* `foo.example.com/_/ref/en/latest/any/foo`
* `foo.example.com/_/ref/en/latest/foo`

**Comment by stsewd** [comment]
Since we are moving away from sphinx specific tooling in our application, I think a better fit for this is an extension. I'm imagining something like having a static page where you can find all references, and maybe have a `?redirect` parameter to do what this issue described. Something similar to https://github.com/webknjaz/intersphinx-untangled, e.g. https://webknjaz.github.io/intersphinx-untangled/docs.rtfd.io/.

**Comment by humitos** [comment]
> Since we are moving away from sphinx specific tooling in our application, I think a better fit for this is an extension

I'm closing this issue because of this reason 👍🏼
