### ISSUE TITLE
Clarify notification text

### ISSUE THREAD

**Issue by dkfellows** [readthedocs/readthedocs.org#6601]
It is extremely unclear that notifications will clear when clicked on (see #5665). Can you at least change the wording of the notifications themselves to make it clear that left clicking on them is what will clear them? While that doesn't fix the underlying problem of stale notifications, it at least means that users (who are almost always not going to be familiar with the details of how notifications work) will know how to clear them for themselves.

Alternatively, and more work, would be to make part of the notification element be styled as a close box such as might be expected on a window. (Clicking on that part should do the close action.) But that's more effort than just tweaking the notification text!

**Comment by stsewd** [comment]
Closing in favor of https://github.com/readthedocs/readthedocs.org/issues/7051
