### ISSUE TITLE
cannot import name 'PackageFinder' errors won't go away

### ISSUE THREAD

**Issue by mechanomi** [readthedocs/readthedocs.org#6604]
* Read the Docs project URL: https://readthedocs.org/projects/crate/
* Build URL (if applicable): https://readthedocs.org/projects/crate/builds/10348432/
* Read the Docs username (if applicable):

builds failing with:

```
ImportError: cannot import name 'PackageFinder' from 'pip._internal.index' (/home/docs/checkouts/readthedocs.org/user_builds/crate/envs/4.1/lib/python3.7/site-packages/pip/_internal/index/__init__.py)
```

I have seen other issue reports (e.g., https://github.com/readthedocs/readthedocs.org/issues/6554) that suggest the build issues we're having can be fixed by wiping the build environment

I have tried that multiple times. and indeed, sometimes the build works again afterward. but new commits to the branch end up failing with this error again

if you go to https://readthedocs.org/projects/crate/builds/ you will see a string of builds all triggered automatically today. some of them passing, and some of them failing with this error

I have not manually triggered any builds today. and I have not wiped any of the build environments. this is all just activity from GitHub hooks

**Comment by stsewd** [comment]
Hi, sorry about that. Yesterday we found the problem https://github.com/readthedocs/readthedocs.org/pull/6598/, the fix well be released soon.

**Comment by stsewd** [comment]
Fix was deployed

**Comment by mechanomi** [comment]
thank you! <3
