### ISSUE TITLE
docs.opnfv.org is 'Not Found.'

### ISSUE THREAD

**Issue by bramwelt** [readthedocs/readthedocs.org#6616]
## Details

The entire documentation site for OPNFV is missing. The most recent builds have succeeded, and as far as I know DNS hasn't changed recently.

* Read the Docs project URL: opnfvdocsdemo.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/opnfvdocsdemo/builds/
* Read the Docs username (if applicable):

## Expected Result

Going to https://docs.opnfv.org/ returns the documentation site.

## Actual Result
```
curl -i -L https://opnfvdocsdemo.readthedocs.io/
HTTP/1.1 302 Found
Content-Type: text/html; charset=utf-8
Location: http://docs.opnfv.org/en/stable-hunter/
Server: nginx
X-Frame-Options: DENY
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
X-Served: Django-Proxito
X-Deity: web04
Strict-Transport-Security: max-age=31536000; includeSubDomains
Date: Wed, 29 Jan 2020 23:13:29 GMT
Content-Length: 0

HTTP/1.1 301 Moved Permanently
Server: CloudFront
Date: Wed, 29 Jan 2020 23:13:29 GMT
Content-Type: text/html
Content-Length: 183
Connection: keep-alive
Location: https://docs.opnfv.org/en/stable-hunter/
X-Cache: Redirect from cloudfront
Via: 1.1 5ab5dc09da67e3ea794ec8a82992cc89.cloudfront.net (CloudFront)
X-Amz-Cf-Pop: HIO50-C1
X-Amz-Cf-Id: 0_rJ9aN8nFAFm6M9VPcWPWHa7B8QOaSW1_Y3Llttz31ZTaK03cTaYQ==

HTTP/2 404 
content-type: text/html; charset=utf-8
content-length: 10
server: nginx
x-frame-options: DENY
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-served: Proxito-404
x-deity: web03
strict-transport-security: max-age=0
date: Wed, 29 Jan 2020 23:13:30 GMT
x-cache: Miss from cloudfront
via: 1.1 1b0911478686968732f973d6e5e31d11.cloudfront.net (CloudFront)
x-amz-cf-pop: HIO50-C1
x-amz-cf-id: sRmKIeU3LyXtKb93316GUwkxqiChktuq227k3nhDcOPqU-78E7JFTA==

Not Found.
```

**Comment by ericholscher** [comment]
Seems like you're serving a CDN in front of this? What is the request you're sending to the backend?

**Comment by ericholscher** [comment]
Hitting our servers directly with the request works fine:

```
-> curl -IL -H "Host: docs.opnfv.org" 104.208.221.96/en/stable-hunter/
HTTP/1.1 200 OK
```

**Comment by ericholscher** [comment]
I can't debug this because your CDN is caching 404 statues.

**Comment by ericholscher** [comment]
We did just deploy some server changes on our side, but it seems this is being generated by Cloudflare based on the `x-cache: Error from cloudfront` header in the response -- but I can't really help debug it without more information.

**Comment by ericholscher** [comment]
I'd recommend pointing your domain at our servers to resolve this, and then we can try to fix it another way.

**Comment by ericholscher** [comment]
@bramwelt I've dumped traffic on our web servers, and I see you're sending this header:

```
X-RTD-SLUG: opnfv
```

This is causing the docs to not be found. If you remove this header, it should work.

**Comment by ericholscher** [comment]
@bramwelt I've deployed a temporary fix that should resolve this issue.

**Comment by bramwelt** [comment]
@ericholscher Thanks for the quick fix! :fireworks:  I'll report back to my team and see if we can't update our configuration to point directly at RTD. AFAIK we're doing a simple nginx reverse-proxy to serve on the custom domain, as we set this up way back when that was the recommended practice in order to [provide SSL](https://docs.readthedocs.io/en/stable/custom_domains.html#proxy-ssl).

**Comment by bramwelt** [comment]
Or maybe it's that that nginx reverse-proxy migrated to CloudFront and we're hitting the 'Cloudfront -> Cloudfront' issue. :thinking: In either case I'm closing this now that our issue is fixed.

**Comment by ericholscher** [comment]
@bramwelt We're looking at putting all of RTD behind cloudflare right now, and from what I can tell the LF projects are the only ones currently breaking. Can you share a bit more about how you have it configured? I think at this point you should be safe to just use our normal DNS setup, but I'd also like to know how things are currently configured to see if we can avoid breaking it.
