### ISSUE TITLE
Validate filenames for incorrect values before trying to serve it

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6624]
If you go to https://docs.readthedocs.io//// it gets a 404, which is correct (we could also redirect to /). But that's generating an error on sentry, we should at least catch it.

Ref https://sentry.io/organizations/read-the-docs/issues/1493620404/?project=1846644&referrer=alert_email

**Comment by humitos** [comment]
I think we should just catch the exception and raise/return a 404.

**Comment by humitos** [comment]
We may want to do that at the storage class level instead of every place where we do `storage.path` or `storage.url`.

**Comment by stsewd** [comment]
Also, azure has a limit in their filename lenght https://sentry.io/organizations/read-the-docs/issues/1451596963/?project=148442&query=is%3Aunresolved

**Comment by stsewd** [comment]
We use S3 now, this may still valid, we can check if there is a limit for S3 objects paths.

**Comment by humitos** [comment]
This seems to be solved already by following the proposal from the original description: "redirect to /".

```
▶ curl -I https://docs.readthedocs.io/// 
HTTP/2 302 
date: Wed, 21 Feb 2024 19:46:12 GMT
content-type: text/html; charset=utf-8
content-length: 0
location: /
cf-ray: 85917e79fea02fa6-MAD
cf-cache-status: MISS
cache-control: max-age=1200
content-language: en
strict-transport-security: max-age=31536000; includeSubDomains; preload
vary: Accept-Language, Cookie, Accept-Encoding
cdn-cache-control: public
cross-origin-opener-policy: same-origin
referrer-policy: no-referrer-when-downgrade
x-backend: web-i-03b90f7ad107e53be
x-content-type-options: nosniff
x-rtd-domain: docs.readthedocs.io
x-rtd-project: 
x-rtd-project-method: public_domain
x-rtd-version-method: path
x-served: Django-Proxito
server: cloudflare
alt-svc: h3=":443"; ma=86400
```
