### ISSUE TITLE
Validate webhook URL

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6625]
We have errors like `Invalid URL '': No schema supplied. Perhaps you meant http://?`

Where users don't put `https://` to their urls. We could, add `https://` if it wasn't given before save it or ask explicitly to the user to put `https?://`

ref https://sentry.io/organizations/read-the-docs/issues/789512412/?project=148442&query=is%3Aunresolved

**Comment by humitos** [comment]
We want to validate the URL when creating a webhook via the Project's Admin -> Notifications -> "New Webhook Notifications"

**Comment by santos22** [comment]
👋 

Is this still valid? Happy to take a look.

**Comment by humitos** [comment]
Hey @santos22! Yes. This is valid. Please go ahead and propose a PR :smiling_face_with_three_hearts:

**Comment by santos22** [comment]
Is there an example of an invalid URL that went through? I don't have access to the Sentry project. Looks like Django assumes 'http' if no scheme is given.

Reference:
https://github.com/django/django/blob/188b003014dc727ca22f7fafb21cf2fa0b3472d2/django/forms/fields.py#L695

**Comment by stsewd** [comment]
@santos22 you are right, we already use an URLField. I checked the DB and looks like we have some empty values.

We should make that field non-blank/null instead of checking for the protocol https://github.com/readthedocs/readthedocs.org/blob/4e095bf79f7db30e5654466768070da7fe08cfba/readthedocs/projects/models.py#L1448-L1452

**Comment by stsewd** [comment]
I'll remove those invalid values

**Comment by stsewd** [comment]
fixed by https://github.com/readthedocs/readthedocs.org/pull/6988
