### ISSUE TITLE
Command killed due to excessive memory consumption

### ISSUE THREAD

**Issue by muryanto1** [readthedocs/readthedocs.org#6627]
## Details

* Read the Docs project URL: https://cdat-vcs.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/cdat-vcs/builds/10382549/
* Read the Docs username (if applicable): muryanto1

## Expected Result

Successful build

## Actual Result

I am trying to build the '**try_fix_doctest**' branch of our project.
but the build has been failing: https://readthedocs.org/projects/cdat-vcs/builds/10377011/

Collecting package metadata: ...working... done
Solving environment: ...working... done
Killed

Command killed due to excessive memory consumption
----

**Comment by muryanto1** [comment]
Please look at this build log: https://readthedocs.org/projects/cdat-vcs/builds/10377011/

Please look at 'try_fix_doctest' version, not 'latest' version.

**Comment by stsewd** [comment]
@muryanto1 please check https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html if nothing of that works for you, let us know so we can increase the resources for your project

**Comment by muryanto1** [comment]
@stsewd I did. The rtd_environment.yml is the minimum that we need to be able to import our package.

**Comment by muryanto1** [comment]
@stsewd https://readthedocs.org/projects/cdat-vcs/builds/10389686/  the build failed in the conda env create step due to excessive memory consumption.

I tried creating the conda env locally in a 1 GB docker container:
$ docker run -m 1000000000 -it readthedocs/build:latest 

and then inside the container, I did:
docs@10082d0e95ce:~$ cd
docs@10082d0e95ce:~$ git clone -b try_fix_doctest https://github.com/CDAT/vcs.git
docs@10082d0e95ce:~$ cd vcs
docs@10082d0e95ce:~/vcs$ conda env create --name test_vcs --file docs/rtd_environment.yml

The environment got created fine, note that I only have 1 GB of memory for the container in which I created the conda env.

**Comment by stsewd** [comment]
I have increased the build resources for your project. To 2G of ram, but it's still failing, 2GB is the max we can give to a project. I have also tried to update the latest version of conda before doing the build (it contains some improvements related to memory consumption).

If you really need to parse the docstrings from your project, I'd recommend using https://github.com/readthedocs/sphinx-autoapi, which doesn't require to install your package to get the docstrings. Also, if you can't use autoapi, you can try mocking packages that require a lot of resources to be installed https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by muryanto1** [comment]
Hello, I tried to wipe out the build env, and triggered the build. It passed the conda env creation, and failed with the following: https://readthedocs.org/projects/cdat-vcs/builds/10429137/

/home/docs/checkouts/readthedocs.org/user_builds/cdat-vcs/checkouts/try_fix_doctest/docs/API/graphics/Jupyter/boxfill.ipynb: WARNING: Pygments lexer name 'ipython2' is not known
failed

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/cdat-vcs/conda/try_fix_doctest/lib/python3.7/site-packages/nbsphinx.py", line 1752, in depart_codearea_latex
    assert 'Verbatim' in lines[0]
AssertionError

**Comment by stsewd** [comment]
Looks related to missing dependencies, try to build the docs locally in a clean environment and see if you can reproduce it locally.

**Comment by muryanto1** [comment]
Hello, I am making some progress https://readthedocs.org/projects/cdat-vcs/builds/10436453/
Is it possible to increase the timeout for the jupyter notebook cell execution?
I read from https://github.com/ipython/ipython/issues/8382 that the timeout is configurable.

**Comment by muryanto1** [comment]
Hello, I was able to pass the conda env creation in this build: https://readthedocs.org/projects/cdat-vcs/builds/10440567/
I then had to add one package to the docs/rtd_environment.yml, and since then I cannot seem to pass the conda env creation (it says using excessive memory consumption) even after I wiped out the build env and rebuilt.
Do I really use that much memory?
Can someone check? Thanks.

**Comment by stsewd** [comment]
We don't have a record of that, but we capture the error from docker, your project is currently with 2GB

**Comment by muryanto1** [comment]
I got it working. Thank you. 
Closing the issue.
