### ISSUE TITLE
Requests from Webhook Notifications are missing `Content-Type` header

### ISSUE THREAD

**Issue by jack1142** [readthedocs/readthedocs.org#6631]
## Details

* Read the Docs project URL: https://readthedocs.org/dashboard/jack1142-red-prs
* Read the Docs username (if applicable): jack1142

This is just a test RTD project with failing build to make it easier to reproduce for me.

## Expected Result

I would expect the request sent to webhook to contain `Content-Type` header set to `application/json`.

## Actual Result

No `Content-Type` header.

**Comment by ericholscher** [comment]
This should be deployed next Tuesday.

**Comment by jack1142** [comment]
Looks like it works properly now, thanks!
