### ISSUE TITLE
Static templates don't work in readthedocs

### ISSUE THREAD

**Issue by choldgraf** [readthedocs/readthedocs.org#6632]
## Details

* Read the Docs project URL: https://sphinx-copybutton.readthedocs.io/
* Read the Docs username (if applicable): choldgraf

Here is the PR where I added the functionality that is causing issues on the RTD site: https://github.com/choldgraf/sphinx-copybutton/pull/58

## Expected Result

I am trying to build a Sphinx extension that [uses Sphinx static file templating](http://www.sphinx-doc.org/en/stable/theming.html#static-templates). I've got a `copybutton.js_t` file in my `_static` directory. When I build my site locally w/ Sphinx 2.3, it builds fine and the final output has an imputed `copybutton.js` file in it. 

## Actual Result

However, when my site builds on Sphinx, the `copybutton.js` file does not exist. Is this a bug? Or a feature deprecation that hasn't made it into the documentation?

**Comment by davidfischer** [comment]
> When I build my site locally w/ Sphinx 2.3, it builds fine and the final output has an imputed copybutton.js file in it.

One thing I see is that your docs on Read the Docs build with Sphinx 1.8.5. That's our default Sphinx version although you can override it by specifying the version in your [requirements.txt](https://github.com/choldgraf/sphinx-copybutton/blob/3018dd7bfcc950b0e6f4debfc0e8e139b54de042/doc/requirements.txt)

**Comment by choldgraf** [comment]
I actually looked into this a bit further, and I think the problem was on my end, rather than with Sphinx. It was an issue with linking the template file in the `setup.py` script. I'll close this now because I think it is fixed!
