### ISSUE TITLE
needs_sphinx = 2.3 not honored in conf.py

### ISSUE THREAD

**Issue by markcmiller86** [readthedocs/readthedocs.org#6634]
## Details

* Read the Docs project URL:https://readthedocs.org/projects/macsio/
* Build URL (if applicable): https://readthedocs.org/projects/macsio/builds/10395273/
* Read the Docs username (if applicable): markcmiller86

## Expected Result

Begin process with sphinx 2.3.

## Actual Result

Begins with sphinx 1.8.5, gets partway through running `conf.py` and then upon `subprocess.    run(['pip', 'install', 'breathe'])` uninstalls sphinx 1.8.5 and installs 2.3.1 and then ultimately hits a python exception with `ImportError: cannot import name 'FigureAligner' `

**Comment by stsewd** [comment]
@markcmiller86 you need to declare your dependencies and their versions in a requirements file

https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

RTD by default installs sphinx 1.8.

**Comment by markcmiller86** [comment]
Ok, I've done that and it seems to have fixed the html gen. Then, the PDF gen is failing...

https://readthedocs.org/projects/macsio/builds/10396127/

with error message like so...

```
.
.
.
Underfull \hbox (badness 10000) in paragraph at lines 3580--3580
\T1/ptm/m/n/10 MPI_Comm \T1/ptm/m/it/10 mpi-Comm\T1/ptm/m/n/10 , int \T1/ptm/m/
it/10 mpiTag\T1/ptm/m/n/10 , [][]\T1/ptm/m/it/10 MAC-
[44] [45] [46] [47] [48]
Underfull \hbox (badness 10000) in paragraph at lines 4069--4071
[]\T1/ptm/m/n/10 An in-te-ger value of ei-ther \T1/pcr/m/n/10 MACSIO_CLARGS_OK\
T1/ptm/m/n/10 , \T1/pcr/m/n/10 MACSIO_CLARGS_HELP \T1/ptm/m/n/10 or
[49]
! TeX capacity exceeded, sorry [input stack size=5000].
\font@name ->
             \T1/ptm/m/it/10 
l.4175 ...ne\_algorithm}{Welford Online algorithm}
                                                  .^^M
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on macsio.log.
.
.
.
```

I am using breathe and suspect the output from it is too much for the pdf gen workflow (which apparently uses latex) to digest. I don't necessarily *need* PDF generation here and so disabling it gets me back to a state where my docs gen ok.

But, sure would like to know if there is a way to resurrect the PDF gen.

Thanks for help.
