### ISSUE TITLE
Build error with build id #10398225

### ISSUE THREAD

**Issue by alokmenghrajani** [readthedocs/readthedocs.org#6637]
## Details:

* Project URL: https://readthedocs.org/projects/Subzero/
* Build URL(if applicable): https://readthedocs.org/projects/subzero/builds/10398225/
* Read the Docs username(if applicable): alokmenghrajani

## Expected Result

Successful build.

## Actual Result

Build errors after 9 seconds with no clear explanation of why it failed.

**Comment by stsewd** [comment]
Looks like an error when getting the submodules.

This submodule doesn't exist https://github.com/square/subzero/blob/68a7b51bcc128c831abc13758bd6501ce6ee0efe/.gitmodules#L4

This looks like a regression on gitpython or a new bug related to no-existing submodules

**Comment by alokmenghrajani** [comment]
Thanks, you are right, the submodule doesn't exist but it's also no longer needed since there's a directory with the same name.

Hopefully we'll now get a clean docs build. 🤞

**Comment by alokmenghrajani** [comment]
That fixed the docs, thanks!
