### ISSUE TITLE
 Build error with build id #10398995 (build doesn't even start)

### ISSUE THREAD

**Issue by jorisvandenbossche** [readthedocs/readthedocs.org#6638]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/geopandas/
* Build URL (if applicable): https://readthedocs.org/projects/geopandas/builds/10398995/
* Read the Docs username (if applicable): jorisvandenbossche

## Expected Result

Succeeding build

## Actual Result

The build doesn't even start. It says "triggered" for a long time, and then after a while it says "This build was terminated due to inactivity."

We previously had problems with the build, but that was always in one of the steps (eg when creating the conda environment)

**Comment by stsewd** [comment]
I can see your builds are passing now. Probably was a temporal error on our side, last week we were having some problems with the builders.

**Comment by jorisvandenbossche** [comment]
Yes, sorry I forgot to close this issue, the builds started running again
