### ISSUE TITLE
Build error with build id #10397232

### ISSUE THREAD

**Issue by Aricg** [readthedocs/readthedocs.org#6639]
## Details:

* Project URL: https://readthedocs.org/projects/lf-releng-global-jjb/
* Build URL(if applicable): https://readthedocs.org/projects/lf-releng-global-jjb/builds/10397232/
* Read the Docs username(if applicable): lf-rtd

## Expected Result

Build completes

## Actual Result

Build fails, last good build was 2 days 23h ago. No real error message that I can see.
is a .readthedocs.yaml required now?

**Comment by humitos** [comment]
Hi @Aricg! The `.readthedocs.yml` is not required. This is an internal problem in our servers. We will take a look and come back with more information.

**Comment by stsewd** [comment]
I imported this project manually, and it passed. But it took some time, I guess it's failing bc of memory consumption or build time (we don't record the real build time if a command fails, only after that command).

**Comment by Aricg** [comment]
@stsewd Can you increase the memory/build time for us? I believe that we are all paid up.

-->
lf-releng-common-packer2 weeks, 3 days ago failing
lf-releng-docs1 week, 6 days ago failing
lf-releng-global-jjb14 hours, 12 minutes ago failing
lfdocs-conf1 week, 5 days ago failing

**Comment by Aricg** [comment]
Actually, only the lf-releng-global-jjb job is failing due to mystery. The others just needed to be switched to python3

**Comment by Aricg** [comment]
Ignore this, the problem is with python dependencies on our side.
