### ISSUE TITLE
orphaned and outdated project blocks official doc

### ISSUE THREAD

**Issue by rgerhards** [readthedocs/readthedocs.org#6645]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/rsyslog/
* Build URL (if applicable):
* Read the Docs username (if applicable): yml

## Expected Result

*The rsyslog project would like to include the correct and current documentation.*

## Actual Result

*somebody submitted our github URL and no updates since 2017* This delivers incorrect information to users.

**Comment by humitos** [comment]
Hi @rgerhards! We do have a policy for this at https://docs.readthedocs.io/en/stable/abandoned-projects.html. Did you try contacting the user? I will take care and start that process in the following days.

**Comment by humitos** [comment]
I'm pinging @yml here that seems to be the same user on GH and RTD.

**Comment by rgerhards** [comment]
@humitos thx for the reply!

> Did you try contacting the user?

Not me personally, but a doc team member quite a while ago (1 year+) without success. We somehow lost focus on that issue and I just came across it again now and thought I give an github issue a try. Which looks good. :-)

Thanks also for guiding me with the process.

**Comment by rgerhards** [comment]
@humitos I checked my mail archive, we tried to contact yml at the Ende of 2017, begin of 2018 before we gave up. It looks like we dug out a related twitter profile, but also got no response. at that time. I've again tweeted today: https://twitter.com/rgerhards/status/1227572032226852867

The twitter profile also looks inactive.
