### ISSUE TITLE
UCX-PY Excessive Memory

### ISSUE THREAD

**Issue by quasiben** [readthedocs/readthedocs.org#6647]
## Details

* Read the Docs project URL: https://ucx-py.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/ucx-py/builds/10420341/
* Read the Docs username (if applicable): quasiben

## Expected Result

Build Succeed

## Actual Result

Build Error:
> Command killed due to excessive memory consumption

would it be possible to increase the memory limit ?

**Comment by humitos** [comment]
@quasiben could you try reducing the number of `channels` listing the environment file? conda has a bug about leaking memory.

**Comment by quasiben** [comment]
@humitos thanks for the suggestion.  I removed one channel (the other three I believe are still necessary) but I'm still getting the same build error.  We are downloading a dependency which is 500MB+ would this be a problem ?

**Comment by stsewd** [comment]
@quasiben I have increased the build resources for your project, but looks like it's failing for another reason https://readthedocs.org/projects/ucx-py/builds/10515295/

**Comment by quasiben** [comment]
Thanks @stsewd . I fixed the additional build issues. Very much appreciate the resource increase
