### ISSUE TITLE
Markdown image "alt text" is not ending up in the right place in the resulting html

### ISSUE THREAD

**Issue by khanspers** [readthedocs/readthedocs.org#6652]
## Details

* Read the Docs project URL: https://github.com/cytoscape/cytoscape-manual
* Build URL (if applicable): http://manual.cytoscape.org/en/latest/
* Read the Docs username (if applicable): 

## Expected Result
Given this markdown:

\![Starter Panel](_static/images/Launching_Cytoscape/Welcome_38.png)

The "alt" text should look like this in the html:
<p>
<img src="_images/Welcome_38.png" alt="Starter Panel">
</p>

## Actual Result
The alt text is rendered on the page and the html looks like this:
<p>
<img src="_images/Welcome_38.png" alt="_images/Welcome_38.png">
"Starter Panel"
</p>

See attached also
<img width="611" alt="Screen Shot 2020-02-12 at 3 41 25 PM" src="https://user-images.githubusercontent.com/1442197/74387747-41b12c80-4dae-11ea-8c1f-cb82cc556002.png">

**Comment by stsewd** [comment]
@khanspers do you see the same result when you build the docs locally? If so, this isn't a Read the Docs problem, but a problem with the markdown parser.

Actually it seems is this https://github.com/readthedocs/recommonmark/issues/88

**Comment by humitos** [comment]
@khanspers the issue seems fixed already. If it's not already in the latest `recommonmark` version, it will be in the next one. You could try installing `recommonmark` from `master` branch as a workaround for now. Let me know if that works :)
