### ISSUE TITLE
Erroneous reports of bad webhooks?

### ISSUE THREAD

**Issue by weaverba137** [readthedocs/readthedocs.org#6658]
## Details

* Read the Docs project URL: https://fiberassign.readthedocs.io, https://desimodel.readthedocs.io
* Build URL (if applicable):
* Read the Docs username (if applicable): weaverba137

## Expected Result

No expectation here.

## Actual Result

When I log in to readthedocs, I see these warnings:

```
    The project fiberassign doesn't have a valid webhook set up, commits won't trigger new builds for this project. See the project integrations for more information.
    The project desimodel doesn't have a valid webhook set up, commits won't trigger new builds for this project. See the project integrations for more information.
```

I replaced the fiberassign webhook today, but still see the warning.  desimodel was building fine as of a few days ago, so I don't see how it's webhook is broken.  On the GitHub side, the webhooks appear to be valid.

When I trigger builds manually, those work fine.

**Comment by stsewd** [comment]
@weaverba137 you need to click on the link of the notification in order for them to disappear. See https://github.com/readthedocs/readthedocs.org/issues/6601

**Comment by weaverba137** [comment]
Thank you, that works.

**Comment by Borda** [comment]
@weaverba137 do you have advice about error messages related to projects which have been deleted a long time ago?
![Screenshot 2021-03-09 at 13 22 09](https://user-images.githubusercontent.com/6035284/110469987-98388980-80da-11eb-92ef-61d7ee312c05.png)

**Comment by stsewd** [comment]
> @weaverba137 do you have advice about error messages related to projects which have been deleted a long time ago?
> ![Screenshot 2021-03-09 at 13 22 09](https://user-images.githubusercontent.com/6035284/110469987-98388980-80da-11eb-92ef-61d7ee312c05.png)

you need to click on the link in order to make the message disappear

**Comment by weaverba137** [comment]
Indeed, what @stsewd said!

**Comment by Borda** [comment]
> you need to click on the link in order to make the message disappear

I did but the link is broken as the project does not exist anymore:
- https://readthedocs.org/dashboard/pt-lightning-flash/integrations/
- https://readthedocs.org/dashboard/pt-lightning-sandbox/integrations/

**Comment by stsewd** [comment]
> > you need to click on the link in order to make the message disappear
> 
> I did but the link is broken as the project does not exist anymore:
> 
>     * https://readthedocs.org/dashboard/pt-lightning-flash/integrations/
> 
>     * https://readthedocs.org/dashboard/pt-lightning-sandbox/integrations/

Just click on it (no middle mouse click), it should disappear.
