### ISSUE TITLE
Build Timeout for frc-docs

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#6659]
## Details

* Read the Docs project URL: https://frc-docs.readthedocs.io/
* Build URL (if applicable):
* Read the Docs username (if applicable): Daltz333

Source available at: https://GitHub.com/wpilibsuite/frc-docs

## Expected Result
Successful and consistent builds 

## Actual Result
Nearly every other build times out on latex generation. Our project is quite large, and if its simply due to being a large project, then we'd like our limits increased. If, however, there is another issue we'd like help identifying it.

**Comment by Daltz333** [comment]
Update: Every build seems to be timing out with a local build working fine. Including latex. @stsewd sorry for the ping.

**Comment by davidfischer** [comment]
I went ahead and bumped up your build time.

How long do the builds take locally? We also have a guide on what to do if your builds take too many resources that might be worth looking at: https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html

**Comment by Daltz333** [comment]
They take about 12 minutes. We have about 1200 pages of documentation and some pages contain heavy latex.

**Comment by stsewd** [comment]
@Daltz333 your latest builds are passing. Anything else we can do?

https://readthedocs.org/projects/frc-docs/builds/

**Comment by Daltz333** [comment]
Thank you, it works good in the meantime. We are investigating self-hosting as our project gets larger and larger (and we can't split things up and use intersphinx). Thank you for your support.

**Comment by Daltz333** [comment]
Unfortunately we are a non-profit with a very small budget, but with a large amount of cloud compute power and bandwidth due to a partnership.
