### ISSUE TITLE
Domain redirect pointing to different website readthedocs project

### ISSUE THREAD

**Issue by botherder** [readthedocs/readthedocs.org#6663]
## Details

* Read the Docs project URL: http://viper-framework.rtfd.io/
* Build URL (if applicable): https://github.com/viper-framework/viper
* Read the Docs username (if applicable):

## Expected Result

The domain `viper.li` is configured to redirect to viper-framework readthedocs site. It is configured both on readthedocs.org, as well as on my Nginx to perform a proxy_pass as instructed.

## Actual Result

For reasons unknown to me, the service is currently redirecting instead to `https://pip.pypa.io/en/stable/`. I don't seem to find any configuration mistake on my end.

**Comment by humitos** [comment]
> It is configured both on readthedocs.org, as well as on my Nginx to perform a proxy_pass as instructed.

Are you sending the `X-RTD-SLUG`? What's the value of it? Can you share your NGINX configuration?

**Comment by botherder** [comment]
Uh weird, I did not have an X-RTD-SLUG set before, and it worked nevertheless. Fixed it now, and it works fine. Thanks! Closing this.
