### ISSUE TITLE
TensorFlow install: Command killed due to excessive memory consumption

### ISSUE THREAD

**Issue by mayou36** [readthedocs/readthedocs.org#6664]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/zfit/
* Build URL (if applicable): https://readthedocs.org/projects/zfit/builds/10451515/
* Read the Docs username (if applicable): mayou36

## Expected Result

It fails to install TensorFlow 2.1. Checking other, similar issues don't seem to really offer a solution. We would need to install it for the Typing.

The Docker container also does not seem to contain TensorFlow.

**Comment by stsewd** [comment]
@mayou36 I have increased the build resources for your project. The html build is passing now, I'd recommend disabling the formats you don't need (specially `htmlzip`, that's the one that's consumes more memory) https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html#reduce-formats-you-re-building
