### ISSUE TITLE
Drop mock dependency

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#6665]
We are using 

https://github.com/readthedocs/readthedocs.org/blob/59611eb3daffaa5c7b359c7d1eacc160ce7b4cbb/readthedocs/vcs_support/tests.py#L6-L6

In several places.

But in python3 we have `unittest.mock`, so we can drop this dependency

https://github.com/readthedocs/readthedocs.org/blob/59611eb3daffaa5c7b359c7d1eacc160ce7b4cbb/requirements/pip.txt#L76-L76

We need to replate all `import mock` to `from unittest import mock`

**Comment by GallowayJ** [comment]
@stsewd I would like to work on this provide it hasn't already been done?

**Comment by stsewd** [comment]
@GallowayJ sure, go ahead

**Comment by stsewd** [comment]
Closed by https://github.com/readthedocs/readthedocs.org/pull/6723
