### ISSUE TITLE
Project root URL redirects to different project

### ISSUE THREAD

**Issue by akheron** [readthedocs/readthedocs.org#6672]
## Details

* Read the Docs project URL: https://jansson.readthedocs.io/
* Build URL (if applicable):
* Read the Docs username (if applicable): akheron

## Expected Result

https://jansson.readthedocs.io should work and serve the Jansson documentation

## Actual Result

https://jansson.readthedocs.io seems to redirect to https://shellgui-docs.readthedocs.io/en/2.12/, which is a different project.

**Comment by humitos** [comment]
@akheron it seems your project is marked as translation of `shellgui-docs`. Can you check this under "Admin" in your project's dashboard page?

If that's not correct, you may need to remove it as translation of that project.

Please, let me know if this works.

**Comment by stsewd** [comment]
Also, if you didn't add your project as translation of the other project. It may bc of an old bug where any user could add their project as translation of another project

**Comment by akheron** [comment]
It seems that my project is marked as a translation for shellgui-docs, but I didn't add it, and it seems I cannot remove the linking:

![translations](https://user-images.githubusercontent.com/70927/74818743-dca68b00-5307-11ea-85d4-2ef8cf38813a.png)

**Comment by humitos** [comment]
@akheron I removed the translation manually.

As @stsewd said, this was an old bug in our code. Everything should be working now. Feel free to reopen the issue otherwise.
