### ISSUE TITLE
Please set DONT_SHALLOW_CLONE for astropy 🙇‍♀️

### ISSUE THREAD

**Issue by pllim** [readthedocs/readthedocs.org#6684]
This is similar request as #5648 . Also see astropy/astropy#9967.

## Details

* Read the Docs project URL: https://readthedocs.org/projects/astropy/
* Build URL (if applicable):
* Read the Docs username (if applicable): pllim

## Expected Result

Software version reported on RTD page is the expected version (v4.1.dev...).

## Actual Result

Software version reported on RTD page is not the expected version (v0.1.dev...).

**Comment by pllim** [comment]
p.s. If this is already fixed, feel free to close.

**Comment by stsewd** [comment]
Done!
https://readthedocs.org/projects/astropy/builds/10476111/

**Comment by pllim** [comment]
Thank you, @stsewd !
