### ISSUE TITLE
[Local Installation] Doc build uses 2.7 and so it fails

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#6685]
OS: Ubuntu 18.04

Following the Instructions at https://docs.readthedocs.io/en/stable/development/install.html

and building the following project https://github.com/wpilibsuite/frc-docs.git

It keeps attempting to build using Python 2.7 (even though Python3.6 and Python3.7) are installed. The environment was created with Python3.6 per the instructions.

It fails on installing Sphinx 2.2.0 because it doesn't exist for Python 2.7

**Comment by stsewd** [comment]
Please try using the new version of the config file, there you can specify the python version

https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by Daltz333** [comment]
I can give it a shot, however I thought documentation was built using 3.7 by default?

Our build at https://frc-docs.readthedocs.io/ works great, but locally it fails due to attempting to use 2.7

RTD limitations reserved to businesses limit us, and we are handling hundreds of thousands with a very small budget and can't afford the business plan. Hence the option to host locally since we have a very powerful free cloud provider.

**Comment by Daltz333** [comment]
I have attached a link to the appropriate django log.

https://hastebin.com/obatubopin.sql

**Comment by stsewd** [comment]
It's creating a 3.7 virtual env

```
[20/Feb/2020 19:55:24] readthedocs.doc_builder.environments:142[14495]: INFO Running: 'python3.7 -mvirtualenv --no-site-packages /home/daltz/readthedocs.org/user_builds/frc-docs/envs/latest' [$HOME]
```

But looks like it's resolving to 2.7

```
command /home/daltz/readthedocs.org/user_builds/frc-docs/envs/latest/bin/python -m pip install
```

Hope that can help you to debug further, doesn't look related to rtd, but the creation of the virtual env with the python version from your OS

**Comment by Daltz333** [comment]
Yeah, when I enter the frc-docs venv folder, the configuration file specifies 3.7 but the actual python binary is 2.7 when ran. It's quite odd, as this is a vanilla Ubuntu install (post ``sudo apt-get update && sudo apt-get upgrade -y``

**Comment by Daltz333** [comment]
So, looks like just doing ``sudo apt-get install virtualenv`` was one of my issues. I had to do ``python3.7 -m pip install virtualenv==16.7.9``.

Greater than version 20 of virtualenv broke it because it complained of --no-site-packages not existing.
