### ISSUE TITLE
Build only works in a fresh read the docs project

### ISSUE THREAD

**Issue by Aricg** [readthedocs/readthedocs.org#6687]
## Details

Having trouble with builds of this project. did several 'wipes' of the  project to get a fresh environment.
* https://readthedocs.org/projects/lf-releng-global-jjb/builds/

To reproduce I forked the repo, created a fresh read the docs project, and triggered a build. Surprisingly it passed!
* https://readthedocs.org/projects/globaljjbdocstest/builds/

Read the Docs username lf-rtd

## Expected Result

Appears that the code in our repository is valid according to read the docs, but only if I create a fresh read the docs project. Perhaps the wipe feature is not working as advertised.
Perhaps this is relating to all the tags we have on our main project, can't see any other difference.

On the failing build the last line of the console output is:
`Successfully installed Sphinx-2.3.1`

On the successful build the last of the matching console output is
`Successfully installed PyYAML-5.3 Sphinx-2.3.1 argcomplete-1.11.1 dulwich-0.19.15 importlib-metadata-1.5.0 pbr-5.4.4 reno-2.11.3 sphinx-bootstrap-theme-0.7.1 sphinxcontrib-applehelp-1.0.1 sphinxcontrib-devhelp-1.0.1 sphinxcontrib-htmlhelp-1.0.2 sphinxcontrib-jsmath-1.0.1 sphinxcontrib-programoutput-0.15 sphinxcontrib-qthelp-1.0.2 sphinxcontrib-serializinghtml-1.1.3 xmltodict-0.12.0 yq-2.10.0 zipp-3.0.0`

## Actual Result

Builds are failing on 
https://readthedocs.orgprojects/lf-releng-global-jjb/builds/
An identical fork of the project is passing here:
https://readthedocs.org/projects/globaljjbdocstest/builds/

**Comment by stsewd** [comment]
I think it may be related to the number of active versions in your original project. We fixed two bugs related to this, so maybe this is a regression or another problem. I'll investigate a little more

**Comment by Aricg** [comment]
@stsewd  Indeed that was it! removed 30 or so tags from active versions and the build completes.
Thanks!

**Comment by stsewd** [comment]
Just for the record, this was the error from the logs

```
Max retries exceeded with url: /api/v2/project/149754/active_versions/ (Caused by ReadTimeoutError("HTTPSConnectionPool(): Read timed out. (read timeout=5)",))
```

**Comment by stsewd** [comment]
And that was being call form

https://github.com/readthedocs/readthedocs.org/blob/2e100541ff5fdda1e0ddd213f499f14e2832b8b6/readthedocs/doc_builder/backends/sphinx.py#L124-L132

We should find a way to optimize that

**Comment by Aricg** [comment]
Just my two cents, the U/I doesn't really support an endless number of versions anyways, perhaps rather than scale the api calls indefinitely, you may consider automatically dropping the oldest active version after a certain number (maybe 40 or so)

**Comment by stsewd** [comment]
Yeah, we are working on the UI. The other option may be great, but it would be an option users can opt in. Also, possible creating automatic redirects so the internet doesn't break
