### ISSUE TITLE
Custom HTML5 translator not being run in readthedocs?

### ISSUE THREAD

**Issue by choldgraf** [readthedocs/readthedocs.org#6690]
## Details

We are building a Sphinx theme that uses Bootstrap.js, and thus have a Sphinx sub-class of HTML5Translator that does some extra translation to create proper bootstrap classes:

https://github.com/pandas-dev/pydata-bootstrap-sphinx-theme/blob/e6a52f9a52ed9ced23d3a8bbdafcdc9432ef8d66/pandas_sphinx_theme/bootstrap_html_translator.py#L29

The theme overrides the `html` translator so that this gets run instead.

We recently noticed that the them builds differently on readthedocs compared with locally. I'm trying to figure out why this is, and I wonder if it is because readthedocs *isn't* building with the `html` translator...I saw that the build command was actually:

```
python /home/docs/checkouts/readthedocs.org/user_builds/pandas-sphinx-theme/envs/latest/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
```

So it appears to be building with a `readthedocs` builder instead of `html`. I can't find documentation about this anywhere. Am I missing something? And could this be the reason that our HTML5Translator class isn't doing anything?

* Read the Docs project URL:
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

I expect our HTML5Translator sub-class to correctly produce HTML with the right classes, per our changes, when building HTML with readthedocs.

## Actual Result

These changes don't make it into the readthedocs builds, and I wonder if it is because readthedocs is using its own custom builder.

**Comment by davidfischer** [comment]
Read the Docs does use a [custom builder](https://github.com/readthedocs/readthedocs-sphinx-ext/blob/545103dd7557e4e247241ca9f3374548171c52d9/readthedocs_ext/readthedocs.py#L324-L337) to add various hooks to integrate projects more closely with Read the Docs. This is almost certainly the reason why your builder is not being used. I don't think there is currently a way to override this. Is the goal here to sort of put different bootstrap CSS into the theme?

**Comment by choldgraf** [comment]
Ahh I see - thanks for the clarification. In our case, we are using the HTML5Translator because Bootstrap has several "container" classes that it uses for pre-defined CSS rules etc. Rather than re-writing a bunch of custom CSS rules for Sphinx's own container class names, we use the translator to convert the Sphinx container classes into ones that Bootstrap understands.

More generally, is it not somewhat common for sphinx themes, extensions, etc to use modified HTML translators? Either way, I think it should be clearly mentioned in the documentation that readthedocs will not work with custom translators...

**Comment by humitos** [comment]
> we use the translator to convert the Sphinx container classes into ones that Bootstrap understands.

Just in case that this may help you. I'm using a custom Sphinx Translator in my extension (https://github.com/readthedocs/sphinx-hoverxref/blob/master/hoverxref/extension.py#L116) but I had to install it as part of the `readthedocs` builder:

```python
    app.set_translator('readthedocs', HoverXRefHTMLTranslator, override=True)
```

Maybe you can try that out in case you only need a translator and not a whole builder. Keep in mind that this is more like a hack and it's not officially support for Read the Docs currently.

**Comment by jorisvandenbossche** [comment]
> This is almost certainly the reason why your builder is not being used.

Note that we are using a custom *translator*, not builder. But yeah, since you register a translator for a certain builder, that's in practice still the problem.

> In our case, we are using the HTML5Translator because Bootstrap has several "container" classes that it uses for pre-defined CSS rules etc

More in general: the html that sphinx generates has some "conflicts" with how bootstrap expects the html to be (the "container" class is one example that bootstrap interprets differently, but eg also the classes added to tables are problematic). 
I have seen other projects write some javascript to edit the html generated by sphinx on the fly, but we tried it via the custom translator way.

>  I had to install it as part of the readthedocs builder:

@humitos thanks for the tip! That should indeed work nicely (as long as the builder name that readthedocs uses stays the same), it doesn't even feel that hacky to me ;)
