### ISSUE TITLE
Tables have lost their format

### ISSUE THREAD

**Issue by sergi-e** [readthedocs/readthedocs.org#6693]
## Details

* Read the Docs project URL: https://github.com/carla-simulator/carla
* Build URL (if applicable): https://carla.readthedocs.io/en/latest/

## Expected Result
Until right now, tables looked properly. In fact, they still do when using mkdocs serve locally to preview the results: 

![Screenshot from 2020-02-24 16-29-44](https://user-images.githubusercontent.com/59253112/75165955-75337580-5723-11ea-8d9c-c9874aac694b.png)

## Actual Result

However, something happened and the online version now looks like this: 

![Screenshot from 2020-02-24 16-29-30](https://user-images.githubusercontent.com/59253112/75165984-7fee0a80-5723-11ea-998c-7328e4fae401.png)

The issue is happening in all the documentation, for every table. It started happening today.

**Comment by stsewd** [comment]
@sergi-e please, make sure you are using the mkdocs version. I can see your previous builds were using

```
Collecting mkdocs>=1.0
  Using cached mkdocs-1.0.4-py2.py3-none-any.whl (1.2 MB)
```

And the latest build

```
Collecting mkdocs>=1.0
  Downloading mkdocs-1.1-py2.py3-none-any.whl (6.4 MB)
```

**Comment by sergi-e** [comment]
I updated to the latest mkdocs version and the tables look properly off-line however they don't in the documentation: 
https://carla.readthedocs.io/en/latest/cameras_and_sensors/

**Comment by sergi-e** [comment]
@stsewd Hello, sorry to bother you, but the problem persists. 
I think the build has been properly updated, as it figures like you said in https://readthedocs.org/projects/carla/builds/10501412/. 
However, not only do tables still appear with wrong format online, but also indexes on the side bar have mostly disappeared. Everything looks ok when previewing the mkdocs off-line, but the online version does not correspond with it.

**Comment by stsewd** [comment]
I think this is likely a problem with unpinned dependencies, did you try replicating locally with a clean environment?

**Comment by sergi-e** [comment]
@stsewd I haven't tried yet, but right now I can say that the last build made failed right after a pull request merged some documentation: https://readthedocs.org/projects/carla/builds/10508699/

**Comment by sergi-e** [comment]
@stsewd Now I have tried replicating in a clean system, installed mkdocs and the pages look the same to me, but different to the on-line versions.

**Comment by rockandska** [comment]
Seems related to https://github.com/mkdocs/mkdocs/issues/2028

**Comment by stsewd** [comment]
@rockandska thanks for the link. I'm closing this since it's a mkdocs bug.
