### ISSUE TITLE
Failure due to excessive memory consumption

### ISSUE THREAD

**Issue by sethaxen** [readthedocs/readthedocs.org#6699]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/e3fp/
* Build URL (if applicable): https://readthedocs.org/projects/e3fp/builds/10499025/
* Read the Docs username (if applicable): sdaxen

## Expected Result

I expected the docs to successfully build

## Actual Result

The build failed with `Command killed due to excessive memory consumption`

**Comment by sethaxen** [comment]
Reading around, it looks like this is a known issue with conda, and enabling the `UPDATE_CONDA_STARTUP` feature may help.

It would also be nice to have the `EXTERNAL_VERSION_BUILD` feature enabled for testing build changes in pull requests.

**Comment by st-bender** [comment]
Hi there,
sorry for jumping in but I had the same problem.
That's a pretty recent change apparently, using

```yaml
image: stable
```

instead of `latest` fixed it for me.

Cheers.

**Comment by stsewd** [comment]
> Reading around, it looks like this is a known issue with conda, and enabling the UPDATE_CONDA_STARTUP feature may help.

Unfortunately, the latest image is already using the latest version of miniconda available at the moment, so that won't help.

> It would also be nice to have the EXTERNAL_VERSION_BUILD feature enabled for testing build changes in pull requests.

You need to contact us via email for that https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

**Comment by stsewd** [comment]
Also, you can read https://github.com/readthedocs/readthedocs.org/issues/6710 for more information related to conda, but we can increase the build resources for your project.

**Comment by stsewd** [comment]
@sethaxen I have increased the build time for your project, builds are passing now https://readthedocs.org/projects/e3fp/builds/10515436/

**Comment by sethaxen** [comment]
Thanks, @stsewd!
