### ISSUE TITLE
Build error with build id #10499561

### ISSUE THREAD

**Issue by bmorris3** [readthedocs/readthedocs.org#6700]
## Details:

* Project URL: https://readthedocs.org/projects/helios-k/
* Build URL(if applicable): https://readthedocs.org/projects/helios-k/builds/10499561/
* Read the Docs username(if applicable): bmorris3

## Expected Result

Docs should build (they do locally).

## Actual Result

```
There was a problem with Read the Docs while building your documentation. Please try again later. However, if this problem persists, please report this to us with your build id (10499561).
```

**Comment by stsewd** [comment]
Believe this is because your submodule doesn't exist

https://github.com/exoclime/HELIOS-K/blob/master/.gitmodules

(there is only a folder, not a submodule)

**Comment by bmorris3** [comment]
That was the problem, thanks!
