### ISSUE TITLE
How to get rid of _a naming?

### ISSUE THREAD

**Issue by t-book** [readthedocs/readthedocs.org#6701]
## Details

* Read the Docs project URL: https://geonode-test-docs.readthedocs.io/en/master/
* Build URL (if applicable): https://readthedocs.org/projects/geonode-test-docs/builds/10496005/
* Read the Docs username (if applicable): toni_schoenbuchner

## Expected Result

A documentation showing versions 2.8, 2.10, master

## Actual Result

2.8 gets named to 2.8_a this is strange as there are no tags on side of github but only branches https://github.com/GeoNode/documentation/branches/all

I've already tried suggested steps from: https://github.com/readthedocs/readthedocs.org/issues/4062
(wipe out 2.8 and latest and rebuild latest without luck)

How to get rid of the _a naming?

Thanks for your help!

**Comment by stsewd** [comment]
Hmm, that's weird. Did you use to have a tag with that name, maybe?

Anyway, I think you can solve this by deactivating the `2.8_a` version and triggering a build on master or 2.10. The versions list should have a 2.8 version now (deactivated)

**Comment by t-book** [comment]
Hi @stsewd thanks for your help! Now, I think I know what's going on. Before the docs pointed to https://github.com/GeoNode/geonode (I've changed the URI in administration to point to our new repositiory). There indeed a 2.8 tag exists and RDT still seams to use it in background. Unfortunately disabling Version 2.8_a and rebuilding master did not work. Still the branch is named 2.8_a pointing to origin as shown below. Do you by chance can think of something else I could try?

Thanks a lot!

– t.


<img width="828" alt="Bildschirmfoto 2020-02-25 um 21 05 34" src="https://user-images.githubusercontent.com/20478652/75283248-c1111800-5812-11ea-8c9b-bc428bfe054a.png">

**Comment by stsewd** [comment]
@t-book looks like the project was deleted, do you still need to rename the version's slug? The previous step didn't work because the version is already pointing to the same branch/commit.

**Comment by t-book** [comment]
sorry @stsewd for my late reply. after several tries, we decided to set up a new environment and change the DNS. Doing so the _a naming disappeared. Thanks a lot for your help!

**Comment by ckreibich** [comment]
We've also recently had a `_a` suffix appear on one of our builds, and it's quite confusing — it's not clear what we did that caused this to appear, or how to get rid of it. We'll keep futzing. If anyone could explain what is going on there and how to fix it without drastic changed (reimporting the project etc), that would be very helpful.
