### ISSUE TITLE
Excessive memory use with 'latest' image (v6.0 broken builds)

### ISSUE THREAD

**Issue by st-bender** [readthedocs/readthedocs.org#6710]
## Details
Version 3.12.0 (Date: February 18, 2020) introduced
"This version has two major changes:
It updates our default docker images to stable=5.0 and latest=6.0."

That's exactly when building the docs started to fail for me.
It seems that the new `latest` image leads to excessive memory consumption with `conda`, some people have reported that. #6699, #6692.

## Expected Result

Successful build, as with `image: stable`

## Actual Result

As in #6699, #6692, broken build on
`conda env create --quiet --name latest --file .rtd-environment.yml`
due to
```
Collecting package metadata (repodata.json): ...working... Killed

Command killed due to excessive memory consumption
```

## Solution

Using `image: stable` fixes it for now.

Is it possible to pin the version, such as using `image: 5.0`?
The docs list only `latest` and `stable`.

**Comment by stsewd** [comment]
The latest image has the latest version of mini conda, which seem to consume more memory than before :man_shrugging:

> Is it possible to pin the version, such as using image: 5.0?
The docs list only latest and stable.

It's possible, but not recommended or documented. The reason is the images are supposed to be backwards compatible or don't break the builds like this, but if that happens, then `stable` should be used.

Also, we don't plan to keep all images in the server, since they can take some space, that's why pinning an image to a specific version may don't work in the future.

In the meantime, we can increase the build resources for projects facing this issue (but we recommend taking a look at https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html first).

**Comment by st-bender** [comment]
> The latest image has the latest version of mini conda, which seem to consume more memory than before 

New is not always better, especially if something like this happens, basically affecting every project that uses conda to build the docs. And I have seen some projects that desperately try to fix their doc builds, not realizing that it's not them but the RTD update that causes the builds to fail. You should have noticed a significant increase in failed builds in your logs on the day and the day after the version change.

> > Is it possible to pin the version, such as using image: 5.0?
> > The docs list only latest and stable.
> 
> It's possible, but not recommended or documented. The reason is the images are supposed to be backwards compatible or don't break the builds like this, but if that happens, then `stable` should be used.
> 
> Also, we don't plan to keep all images in the server, since they can take some space, that's why pinning an image to a specific version may don't work in the future.

Thanks, fair enough and I can understand the space issue. But at some point version 6 will become "stable" and break things again. Btw., it would be nice if the full version would be listed in the log, not just "stable" or "latest", but like "stable (5.0)", "latest (6.0)". That would have made it much easier to track down the problem.

> In the meantime, we can increase the build resources for projects facing this issue (but we recommend taking a look at https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html first).

I think you underestimate the consequences, it will not be "in the meantime", virtually **every project** that uses conda to build the docs is affected. Increasing the resources manually will be not feasible, and you won't know in advance if conda is used until you clone the repository, an automatic solution is also not feasible. Which leaves two options in my mind:
* Go back to the earlier version of conda
* Increase the default resources for every project.

And please don't get me wrong, I appreciate your work for the free software community, it's never been so easy to publish documentation. :)

**Comment by stsewd** [comment]
> I think you underestimate the consequences, it will not be "in the meantime", virtually every project that uses conda to build the docs is affected.

We are trying to solve the problem, but in the meantime we can increase the build resources for projects, so they don't get stuck.

We are testing downgrading conda just now. Also, we have been testing a couple of projects with the latest version of conda months before the release, and we didn't see any downside (actually it improved the build time in some projects)

**Comment by humitos** [comment]
@st-bender We are testing a new bigger build server that we think will solve most of the issues around conda and OOM. Would you like me to add your project to this build queue and help us with feedback on this?

**Comment by st-bender** [comment]
Hi @humitos, thanks for the update and the offer.
I think my project is too small and more personal/academic, so the docs are nice but not crucial and I can wait for the issue to be resolved. I am not sure that anyone reads the docs anyway. ;)

But I think you can try and give the people developing `xarray` https://xarray.pydata.org a hand.
They seem to have OOM failing doc builds: https://readthedocs.org/projects/xray/builds/, e.g. the last one: https://readthedocs.org/projects/xray/builds/10585624/
I am not involved there but I use it a lot.

**Comment by humitos** [comment]
@st-bender OK! Thanks for replying. Thanks for pointing that to me. I will contact them to ask if they want to help us to test this out.

I will close this issue then, because there is nothing actionable then. Feel free to reopen if you consider, though.
