### ISSUE TITLE
command killed due to excessive memory consumption

### ISSUE THREAD

**Issue by muryanto1** [readthedocs/readthedocs.org#6715]
## Details

* Read the Docs project URL: cdms.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/cdms
* Read the Docs username (if applicable): muryanto1

## Expected Result

read the docs build to pass

## Actual Result

I am getting Command killed due to excessive memory consumption
https://readthedocs.org/projects/cdms/builds/10511267/

Could you kindly update the conda to the latest version before it does the build? and also increase the memory limit for me? 2GB should do. Thank you so much.

**Comment by swaldhoer** [comment]
@stsewd I am facing the same issue, also during conda package installation which is very minimal (https://github.com/swaldhoer/native-lua/blob/6ff5af8baf54c397ac5aaef6059b1e22aa94c7b6/docs/environment.yml). Could you also please update build time settings for my project.

- Two weeks ago everything went fine (with the same settings): https://readthedocs.org/projects/native-lua/builds/10404416/

- Failing build now: https://readthedocs.org/projects/native-lua/builds/10567153/

**Comment by humitos** [comment]
@swaldhoer We are testing a new bigger build server that we think will solve most of the issues around conda and OOM. Would you like me to add your project to this build queue and help us with feedback on this?

**Comment by muryanto1** [comment]
@swaldhoer Sure, Thanks!

**Comment by humitos** [comment]
Oh, sorry! My previous message was meant to be directed to you, @muryanto1. Please, confirm me that it's OK to be added to the new build server.

**Comment by muryanto1** [comment]
@humitos  oh, ya, my fault. Sure, please, thank you.

**Comment by humitos** [comment]
Done. I triggered a new build for your `latest` version and it worked: https://readthedocs.org/projects/cdms/builds/10589233/

I'm closing this issue, but please feel free to reopen if you consider or open a new one if you have any feedback regarding the stability of your builds.

**Comment by swaldhoer** [comment]
@humitos would you plaese also add my project to the new infrastructure (see https://github.com/readthedocs/readthedocs.org/issues/6715#issuecomment-596072523)?

**Comment by humitos** [comment]
@swaldhoer done! I triggered a new build at https://readthedocs.org/projects/native-lua/builds/10593041/ and the environment was created successfully.

**Comment by mrconway** [comment]
@humitos Hi Manuel, if you could add our project to the new build server as well, that would be great.

https://readthedocs.org/projects/alphapy/

Thank you for your consideration.

**Comment by humitos** [comment]
Hi @mrconway! This is a closed issue. We usually don't keep an eye on them. Please contact us via support@readthedocs.org and we can continue there. Take a look at this guide before that: https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html, thanks!
