### ISSUE TITLE
Discrepancies between offline and online: sidebar index

### ISSUE THREAD

**Issue by sergi-e** [readthedocs/readthedocs.org#6716]
## Details

* Read the Docs project URL: https://github.com/carla-simulator/carla
* Build URL (if applicable): https://carla.readthedocs.io/en/latest/
* Read the Docs username: sergi-e

## Expected Result

This is what I see when making my documentation build offline: 

![Screenshot from 2020-02-27 14-16-40](https://user-images.githubusercontent.com/59253112/75449343-15300f80-596d-11ea-8301-de1561d262c9.png)

## Actual Result

This is what actually appears online: 

![Screenshot from 2020-02-27 14-16-56](https://user-images.githubusercontent.com/59253112/75449295-0184a900-596d-11ea-95ad-23bad9b9adb1.png)

There are many noticeable differences: The scrolling for the side bar has disappeared, fonts have changed, the online version has a "-" for the pages on the sidebar so the index can be hidden/shown... 

However, the important issue is that __most of these index have disappeared__. They show nothing and thus, the navigation in the docs is heavily hindered. Besides that, there are also some other differences such as table formats mentioned in #6693.

My actual mkdocs version:
`mkdocs, version 1.0.4 from /home/adas/.local/lib/python2.7/site-packages/mkdocs (Python 2.7)`

**Comment by stsewd** [comment]
@sergi-e were you able to find the solution for this?
