### ISSUE TITLE
Custom domain: Only Homepage redirecting

### ISSUE THREAD

**Issue by 4flixt** [readthedocs/readthedocs.org#6718]
## Details
We are using a custom domain for our project [do-mpc](https://www.do-mpc.com)
and selected "This Domain is the primary one where the documentation is served from."
As expected [do-mpc.readthedocs.io](https://do-mpc.readthedocs.io) redirects to our 
custrom domain homepage.
However, every other page , e.g. [do-mpc.readthedocs.io/en/latest/](https://do-mpc.readthedocs.io/en/latest/) do not redirect.

I have validated the same behavior with e.g. https://pip.pypa.io/en/stable/

As a website owner, I want my content to only exist one instance: my custom domain. 
Having identical content on multiple domains has implications for SEO: while I know I could setup canonicals on all pages, they are not a directive for a search engines, only a signal. A redirect would be more appropriate in that case.
Furthermore, the current behavior of only redirecting the homepage is incoherent.

## Expected Result
All pages redirect to my custom domain automatically.

## Actual Result
Only the homepage is being redirected.

**Comment by humitos** [comment]
We have already an issue opened for this at https://github.com/readthedocs/readthedocs.org/issues/3231

I'm closing this one as duplicated, but feel free to reopen if you think it's not.
