### ISSUE TITLE
Build fine but no docs. 

### ISSUE THREAD

**Issue by microprediction** [readthedocs/readthedocs.org#6720]
## Details

* Read the Docs project URL: https://colliderfeed.readthedocs.io/en/master/
* Build URL (if applicable):
* Read the Docs username (if applicable):microprediction

## Expected Result

See docs at https://colliderfeed.readthedocs.io/en/master/ after having verified successful build. 

## Actual Result

Maze

**Comment by stsewd** [comment]
@microprediction your documentation is there, you just happen to missing adding a `index.rst` file.

https://colliderfeed.readthedocs.io/en/latest/configuration.html

You can check our sphinx guide https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html
