### ISSUE TITLE
Project domains starting with a number are broken

### ISSUE THREAD

**Issue by AleG94** [readthedocs/readthedocs.org#6721]
## Details
Every project domain starting with a number (eg. 54street) doesn't show the documentation but instead `SORRY This page does not exist yet`.

It even happens for projects that do not exist. For example, look at the different behaviour of this two urls where both projects are not existent:

https://street54.readthedocs.io/en/latest/ (returns `Not Found`)
https://54street.readthedocs.io/en/latest/ (returns `SORRY This page does not exist yet`)

## Expected Result
The documentation should be visible at the project's url.

## Actual Result
The error `SORRY This page does not exist yet.` is always returned, even when build is successfull.

**Comment by AleG94** [comment]
The #6726 pull request would only solve a part of the issue. 

The main issue is that documentation is not shown for existing projects that start with a number. Even if documentation is there and build is successful, it will always show `SORRY This page does not exist yet.`.

Projects not starting with a number are fine instead.

**Comment by humitos** [comment]
@AleG94 do you have an example of that case? what's the project's dashboard URL under Read the Docs? BTW, there is no project with slug `54street` registered under RTD --that project does not exist.

**Comment by AleG94** [comment]
Both `54street` and `street54` are non-existent and were just mentioned to show how even non-existent projects are affected by this issue. To reproduce it, you can create a project with a slug that starts with a number and link it to the doc.

Here is a live example of the same exact RTD settings but on 2 different project slugs:

https://8pay.readthedocs.io/en/latest/ (returns error)
https://eight-pay.readthedocs.io/ (works as expected)

**Comment by humitos** [comment]
@AleG94 thanks for the info, you are right. I will try to debug this issue and see where is the problem.

**Comment by ericholscher** [comment]
I'm deploying a hotfix that should fix this issue.
