### ISSUE TITLE
html content directives

### ISSUE THREAD

**Issue by EDI-N** [readthedocs/readthedocs.org#6722]
## Details
Helo, there is the problem with html content creation: I like to add some "container" to RST, for example:
.. container:: idishnicheg
( https://docutils.sourceforge.io/docs/ref/rst/directives.html#container )
and use that directive:
https://wiki.edi-n.com/uk/latest/EDIN_DOCflow/edin_docflow/instruktsia-biznes-administratora.html#idishnicheg
It definatly worked last year...

* Read the Docs project URL: https://readthedocs.org/projects/docs-ua/
* Read the Docs username (if applicable): EDI-N

## Expected Result

Will be great to see result like this page formed with custom href="#container":
https://docutils.sourceforge.io/docs/ref/rst/directives.html#container

**Comment by stsewd** [comment]
@EDI-N did you try building locally? If you see the same result, it isn't a read the docs problem, but probably a dependency.

**Comment by EDI-N** [comment]
So I think container-feature was deprecated and now **for people**:
https://docs.typo3.org/m/typo3/docs-how-to-document/master/en-us/WritingReST/Hyperlinks.html
use this example in text like anchor:
```.. _english-only:```
and call it with:
`...bla-bla-bla.html#english-only`
and
`english-only_` - inside those page
