### ISSUE TITLE
Command killed due to excessive memory consumption

### ISSUE THREAD

**Issue by fepegar** [readthedocs/readthedocs.org#6727]
## Details

* Read the Docs project URL: https://torchio.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/torchio/builds/10523861/
* Read the Docs username (if applicable): `fepegar`

## Expected Result

A successful build.

## Actual Result

The command is killed when trying to install PyTorch:

```python-traceback
Collecting torch>=1.2
  Downloading torch-1.4.0-cp37-cp37m-manylinux1_x86_64.whl (753.4 MB)
Killed


Command killed due to excessive memory consumption
```

I enabled the `Use system packages` option, I thought that would get rid of the error. I'm quite new to RTD, please let me know if I'm missing something.

**Comment by fepegar** [comment]
Seem to work now.

**Comment by fepegar** [comment]
It's actually still happening: https://readthedocs.org/projects/torchio/builds/10527801/

**Comment by Aricg** [comment]
I am seeing this as well.
https://readthedocs.org/projects/onap-doc/builds/10536866/

**Comment by tswast** [comment]
I'm also encountering this as package installation time in the protobuf docs. https://readthedocs.org/projects/protobuf/builds/10540150/

**Comment by humitos** [comment]
Closing in favor of #6742 --please, subscribe there.
