### ISSUE TITLE
[Feature Request] Please enable PR builder for spacetelescope/reftools

### ISSUE THREAD

**Issue by pllim** [readthedocs/readthedocs.org#6734]
Thank you!

## Details

* Read the Docs project URL: https://readthedocs.org/projects/reftools/
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): pllim

## Expected Result

PR auto builder to run for a new PR on https://github.com/spacetelescope/reftools/

## Actual Result

It is not yet enabled.

**Comment by humitos** [comment]
I enabled it now. Please check out the documentation at https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

**Comment by pllim** [comment]
Thank you!
