### ISSUE TITLE
Please set DONT_SHALLOW_CLONE for libCEED

### ISSUE THREAD

**Issue by jedbrown** [readthedocs/readthedocs.org#6736]
## Details

* Read the Docs project URL: https://libceed.readthedocs.org
* Build URL (if applicable): https://readthedocs.org/projects/libceed/builds/10545392/
* Read the Docs username (if applicable): jedbrown

## Expected Result

Full commit list so that `git describe` and `git shortlog -s` yield reliable information.

## Actual Result

Shallow clone.

**Comment by jedbrown** [comment]
There might be something else at play. `git log` produces _some_ output while `git shortlog` produces _no_ output. If shallow cloning was the only issue, I'd expect it to produce partial output. See here, for example. https://readthedocs.org/projects/libceed/builds/10545416/
I can't think of a reason why `git shortlog` would produce no output, and haven't been able to reproduce that locally. Do you have any ideas?

**Comment by humitos** [comment]
I'm not sure to understand the issue. What's the problem that you are experimenting with shallow clone? Both builds you linked are passing without problems.

**Comment by jedbrown** [comment]
The builds passed, but `git describe` and `git shortlog` do not behave as desired (resulting in empty author information). The behavior of `git describe` makes perfect sense and will be fixed if we can disable shallow clone (it's also easier to work around). I don't understand why `git shortlog` produces no output; I would expect it to produce partial output (from the commits in the shallow clone).

**Comment by humitos** [comment]
Where are those commands ran? Read the Docs do not run them.

Anyways, I enabled NO SHALLOW CLONE in your project as you asked for. Feel free to reopen the issue if you consider.

**Comment by jedbrown** [comment]
We're running them to obtain information to be included in our docs. Thanks for the change; we'll give it a try.
