### ISSUE TITLE
Command killed due to excessive memory consumption onap-doc

### ISSUE THREAD

**Issue by Aricg** [readthedocs/readthedocs.org#6737]
## Details

https://readthedocs.org/projects/onap-doc/builds/10544473/
onap-rtd

Hello, we are transitioning from a monolithic docs repo with submodules to per project builds with sub-repos and intersphix linking, ONAP is a gold member. Can we have the memory limit increased for this project?

We are blocked on our transition due to these build failures currently.

**Comment by humitos** [comment]
I saw you have `htmlzip` in your Read the Docs configuration YAML file. This format consumes _a lot of memory_ I'm not sure you will be able to build it without tweaking your docs (to make them smaller). Do you really need to build that output format? Can you try disabling it and running a build again to know if the build passes? Thanks!

**Comment by Aricg** [comment]
@humitos Thank you, I removed htmlzip from that projects .readthedocs.yaml and the build passes now.
