### ISSUE TITLE
Command killed due to excessive memory consumption despite trivial conda environment file

### ISSUE THREAD

**Issue by duncanmmacleod** [readthedocs/readthedocs.org#6743]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/ciecplib/
* Build URL (if applicable): https://readthedocs.org/projects/ciecplib/builds/10553221/
* Read the Docs username (if applicable): duncanmmacleod

## Expected Result

The build to pass

## Actual Result

```
Collecting package metadata: ...working... Killed


Command killed due to excessive memory consumption
```

I have reduced the conda environment file to just this:

```yaml
name: ciecplib
channels:
  - conda-forge
dependencies:
  - python
```

and it still dies instantly. Any help is greatly appreciated. Thanks for operating this awesome free service.

**Comment by stsewd** [comment]
@duncanmmacleod I have increased the build resources for your project, but it's failing for another reason

https://readthedocs.org/projects/ciecplib/builds/10558679/

**Comment by duncanmmacleod** [comment]
Thanks @stsewd! I need to reinstate the dependencies now that the conda builds work. Will close this ticket as soon as I've done that and verified the build.

Thanks again.

**Comment by duncanmmacleod** [comment]
All is well now, thanks for the help @stsewd!

**Comment by duncanmmacleod** [comment]
@stsewd, I'm not sure about the proper procedure for this, but please could you make the same change for another project of mine, `requests-ecp`:

https://readthedocs.org/projects/requests-ecp/builds/

which is failing for the same reason? Thanks.

**Comment by duncanmmacleod** [comment]
For the record, I believe that the original problem, as diagnosed in #6757, is that using the `conda-forge` channel in your conda environment file for RTD will always result in a 'excessive memory consumption' build failure unless you are given extra resources.
