### ISSUE TITLE
Hope that the response body format from public API will be consistent

### ISSUE THREAD

**Issue by KengoTODA** [readthedocs/readthedocs.org#6744]
Thanks for hacking such a useful product! 👏

Especially the public API is awesome for who's motivated to automate workflow.
With help from your public API v3, [I successfully replaced puppeteer](https://github.com/KengoTODA/rtd-bot/pull/400) that makes my bot really fat and unstable.

Here I have a request for future development (API v4?), I hope it helps your hack and your community.

----

Currently the PATCH API like [version update](https://docs.readthedocs.io/en/stable/api/v3.html#version-update) responses `204` without any response body. This means that the format of the response body is not so consistent, and users need to judge before they handle the response body by `.json()` or a similar way.

For instance, I have [code to handle response status and body for error handling](https://github.com/KengoTODA/rtd-bot/blob/2888744ff27b41cb71ad33a42ccec9ca72a195d3/src/rtd.ts#L101-L114), and if API responses a JSON instead of an empty response body, I can shorten the following part:

```js
    .then((res) => {
      if (res.status != 204) {
        return Promise.all([res.status, res.json()])
      } else {
        // 204 responses empty text, so json() doesn't work
        return Promise.all([res.status, res.text()])
      }
    })
```

to simple and intuitive code like below:
```js
    .then((res) => {
      return Promise.all([res.status, res.json()])
    })
```

Thanks again for your hacking!

**Comment by stsewd** [comment]
Looks like we only return data on `PUT`, but not on `PATCH`. I think we should return data on `PATCH` too.

**Comment by stsewd** [comment]
Actually, we use django rest framework, 204 means no content https://www.django-rest-framework.org/api-guide/status-codes/#successful-2xx

https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.5

So, the response body is correct. We can't change the status code or add a body in apiv3, that will break backwards compatibility.

**Comment by stsewd** [comment]
And by the way, we have https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html to build docs from a pull request.

**Comment by KengoTODA** [comment]
Yes I know you're building a cool and official solution (I checked [the blog post](https://blog.readthedocs.com/building-docs-for-pull-requests/) before). Mine is a kind of playground, and hope that it'll be deprecated after the official solution becomes stable and public. :+1:

**Comment by stsewd** [comment]
Closing this as the API response is correct for a 204

**Comment by KengoTODA** [comment]
> Closing this as the API response is correct for a 204

Can I ask what you mean? It just means `wontfix`, right?
I confirmed that the response body is still in the TEXT format.

Then I will open a new issue to change the HTTP response status to 200, since [204 is cachable](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204) but the API response isn't.

**Comment by stsewd** [comment]
> Can I ask what you mean? It just means wontfix, right? I confirmed that the response body is still in the TEXT format.

204 code means you shouldn't expect a body on the response.

Your "hack" is the correct way to handle it

```js
    .then((res) => {
      if (res.status != 204) {
        return Promise.all([res.status, res.json()])
      } else {
        // 204 responses empty text, so json() doesn't work
        return Promise.all([res.status, res.text()])
      }
    })
```
