### ISSUE TITLE
Hope that Translates API returns language code of each project

### ISSUE THREAD

**Issue by KengoTODA** [readthedocs/readthedocs.org#6745]
Thanks for hacking such a useful product! 👏

Especially the public API is awesome for who's motivated to automate workflow.
With help from your public API v3, [I successfully replaced puppeteer](https://github.com/KengoTODA/rtd-bot/pull/400) that makes my bot really fat and unstable.

Here I have a request for future development (API v4?), I hope it helps your hack and your community.

----

I have [code with Translatest API v2 to make a list of related projects](https://github.com/KengoTODA/rtd-bot/blob/2888744ff27b41cb71ad33a42ccec9ca72a195d3/src/rtd.ts#L33-L50). In short I want to get information like `{ translations: Array<{slug: string, languageCode: string}> }` from the API.

API v2 supported it, however, API v3 does not respond `languageCode` data, so I need to invoke [project details API](https://docs.readthedocs.io/en/stable/api/v3.html#project-details) one by one.

Not sure it's an intentional change. I personally prefer the behavior of v2, so I wish the next API will support it.

**Comment by stsewd** [comment]
@KengoTODA we already support this

```bash
curl -H "Authorization: Token <token>" https://readthedocs.org/api/v3/projects/another-test-stsewd/translations/ | jq '.results | [.[] | {language: .language.code, slug: .slug}]'

[
  {
    "language": "en",
    "slug": "stsewd-demo"
  }
]
```

https://docs.readthedocs.io/en/stable/api/v3.html#translations

**Comment by KengoTODA** [comment]
@stsewd but I cannot find it in [the official doc of translations-listing API v3](https://docs.readthedocs.io/en/stable/api/v3.html#translations-listing), we probably need to update that?

**Comment by KengoTODA** [comment]
In its example response, `"results": ["PROJECT"]` is misleading. Does it return not a string but a project info like [Project details API](https://docs.readthedocs.io/en/stable/api/v3.html#project-details)?

**Comment by stsewd** [comment]
Yes, that means a project object. We should make it more clear on the docs.
