### ISSUE TITLE
heptapod (bitbucket replacement) gitlab-based webhook not triggering a build

### ISSUE THREAD

**Issue by mattip** [readthedocs/readthedocs.org#6747]
PyPy recently moved from bitbucket to `https://foss.heptapod.net/pypy/pypy`. Heptapod is a friendly fork of gitlab used to host mercurial VCS projects. I set up a gitlab webhook and can see in the Admins->Integrations tab that the hook is receiving information, but no build is triggered:
```
{
  "build_triggered": false,
  "project": "pypy",
  "versions": []
}
```

I tried setting the `latest` tag to build a branch named `default`. Is there something missing from the json (below, pasted from the `integrations` tab)?

xref [hepatpod issue](https://foss.heptapod.net/heptapod/heptapod/issues/196) about the published json

<details>

```
{
  "after": "3f863024f172c2b776c77fee8cd9a035394face2",
  "before": "c37d73493937c3824b5bc65e6368f334b0657daf",
  "checkout_hgsha": "33cd4b40943ec900b87a4e23e1fbceb923623162",
  "checkout_sha": "3f863024f172c2b776c77fee8cd9a035394face2",
  "commits": [
    {
      "added": [
        "lib-python/3/ensurepip/_bundled/pip-20.0.2-py2.py3-none-any.whl",
        "lib-python/3/ensurepip/_bundled/setuptools-44.0.0-py2.py3-none-any.whl"
      ],
      "author": {
        "email": "matti.picus@gmail.com",
        "name": "Matti Picus"
      },
      "hgid": "33cd4b40943ec900b87a4e23e1fbceb923623162",
      "id": "3f863024f172c2b776c77fee8cd9a035394face2",
      "message": "port 3fbda04b79cb to py3.6, use setuptools44.0.0 so all versions are the same\n\n--HG--\nbranch : py3.6\n",
      "modified": [
        "lib-python/3/ensurepip/__init__.py"
      ],
      "removed": [
        "lib-python/3/ensurepip/_bundled/pip-19.2.3-py2.py3-none-any.whl"
      ],
      "timestamp": "2020-03-05T12:25:54+02:00",
      "url": "https://foss.heptapod.net/pypy/pypy/commit/3f863024f172c2b776c77fee8cd9a035394face2"
    }
  ],
  "event_name": "push",
  "hg_after": "33cd4b40943ec900b87a4e23e1fbceb923623162",
  "hg_before": "90bfb51bc0566d63bd201527f23780c0e1f2b741",
  "message": null,
  "object_kind": "push",
  "project": {
    "avatar_url": "https://foss.heptapod.net/uploads/-/system/project/avatar/76/favicon2.png",
    "ci_config_path": null,
    "default_branch": "branch/default",
    "description": "PyPy is a very fast and compliant implementation of the Python language.",
    "git_http_url": "https://foss.heptapod.net/pypy/pypy",
    "git_ssh_url": "ssh://hg@foss.heptapod.net/pypy/pypy",
    "homepage": "https://foss.heptapod.net/pypy/pypy",
    "http_url": "https://foss.heptapod.net/pypy/pypy",
    "id": 76,
    "name": "pypy",
    "namespace": "PyPy",
    "path_with_namespace": "pypy/pypy",
    "ssh_url": "ssh://hg@foss.heptapod.net/pypy/pypy",
    "url": "ssh://hg@foss.heptapod.net/pypy/pypy",
    "visibility_level": 20,
    "web_url": "https://foss.heptapod.net/pypy/pypy"
  },
  "project_id": 76,
  "ref": "refs/heads/branch/py3.6",
  "repository": {
    "description": "PyPy is a very fast and compliant implementation of the Python language.",
    "git_http_url": "https://foss.heptapod.net/pypy/pypy",
    "git_ssh_url": "ssh://hg@foss.heptapod.net/pypy/pypy",
    "homepage": "https://foss.heptapod.net/pypy/pypy",
    "name": "pypy",
    "url": "ssh://hg@foss.heptapod.net/pypy/pypy",
    "visibility_level": 20
  },
  "total_commits_count": 1,
  "user_avatar": "https://xxxxxxx",
  "user_email": "xxxxxx",
  "user_id": 38,
  "user_name": "Matti Picus",
  "user_username": "mattip"
}
```

**Comment by stsewd** [comment]
Looking at the payload, everything looks correct (for what we expect in a GitLab payload).

Is this the rtd project https://readthedocs.org/projects/pypi/?

**Comment by mattip** [comment]
Sorry, I should have given the link. It is https://readthedocs.org/projects/pypy

**Comment by stsewd** [comment]
Oops, got the name wrong.

So, what happens here is that your project only has the `default` version activated (`latest`). We don't triggered a build on inactive versions. We do sync the versions when a new tag/branch/(or what in mercurial are those) is created/deleted.

If you want to trigger a build on a version, you must activate it. We offer automation rules in case you don't want to activate the versions manually after creating it https://docs.readthedocs.io/en/stable/automation-rules.html

**Comment by mattip** [comment]
I activated default. I now have two versions: "default" which is the default branch, and "latest" which seems to be an alias for it. Strange that we didn't need to do that with the bitbucket webhook.

**Comment by stsewd** [comment]
@mattip I think you don't need to activate default, with having latest is ok. The payload to added has `  "ref": "refs/heads/branch/py3.6"` so I thought you were trying to build that branch.

**Comment by mattip** [comment]
I just pushed to the default branch, [here](https://readthedocs.org/dashboard/pypy/integrations/112323/exchange/2fd0fcf1-d904-4d9e-8724-9ef47d19bc60/) is the integrations report. A doc build was not triggered. The payload has `"ref": "refs/heads/branch/default",` which is identical to the successful bitbucket integration build from two weeks ago: `"ref": "refs/heads/branch/default".

**Comment by mattip** [comment]
Again today the webhook [did not trigger](https://readthedocs.org/dashboard/pypy/integrations/112323/exchange/e081d554-fba3-4bf3-8da4-804c15264f5e/) with no information about what is wrong.

**Comment by stsewd** [comment]
I found the problem. The name of the branch is `default`, but the ref is `refs/heads/branch/default`, which means the name of the branch is `branch/default`. Not sure why heptapod includes that extra `branch/`

**Comment by mattip** [comment]
I will try `branch/default`.

**Comment by mattip** [comment]
Hmm, I cannot actually activate `branch/default` via the gui.

**Comment by stsewd** [comment]
That's because when we list the branches from the repo, we only get `default`

**Comment by mattip** [comment]
xref https://foss.heptapod.net/heptapod/heptapod/issues/227.

Does gitlab report the branch correctly? Heptapod is a friendly fork of gitlab

**Comment by stsewd** [comment]
Yeah, GitLab doesn't include `branch/` https://docs.gitlab.com/ce/user/project/integrations/webhooks.html#push-events
