### ISSUE TITLE
Pinning sphinx version not working for conda install

### ISSUE THREAD

**Issue by sjrowlinson** [readthedocs/readthedocs.org#6755]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/finesse/
* Build URL (if applicable): https://readthedocs.org/projects/finesse/builds/10565374/
* Read the Docs username (if applicable): sjrowlinson

## Expected Result

Pinning sphinx version at 2.3.1 as per the `environment.yml` file in the project:

![image](https://user-images.githubusercontent.com/16781733/76114944-1ac9cd00-5fdf-11ea-9270-d06dd8dae052.png)

## Actual Result

Build process seems to be ignoring this and just installing latest Sphinx release anyway:

![image](https://user-images.githubusercontent.com/16781733/76115073-611f2c00-5fdf-11ea-9a41-357e8dd1083c.png)

This results in the build failing due to a time out as Sphinx 2.4.0 seems to be very slow (which is why I want to pin to 2.3.1 for now).

**Comment by humitos** [comment]
Hi! I'm going to close this one as duplicated of #3829 and I'm going to apply the Feature Flag mentioned on https://github.com/readthedocs/readthedocs.org/issues/3829#issuecomment-515765278

Feel free to re-open if this does not work.

**Comment by humitos** [comment]
You may probably need to wipe the version's environment first.
