### ISSUE TITLE
RtD not shown with Sphinx automodule

### ISSUE THREAD

**Issue by LovelyBuggies** [readthedocs/readthedocs.org#6756]
## About

- RtD project url: https://nino-hist.site/en/latest/#
- RtD build url: https://readthedocs.org/projects/nino-hist/builds/10569080/
- Read the Docs username (if applicable): LovelyBuggies (GitHub)
- Based repo url: https://github.com/LovelyBuggies/Nino-hist

This is the similar problem met with jtpaquet in issue [\#4210](https://github.com/readthedocs/readthedocs.org/issues/4210), having no contents shown of `automodule` on RtD. 

For convenience, you do not need to run the source code in `./src` folder, just `cd doc` and `make html` is all right. In this project, I created a package named `hist` (though I named it as Nino-hist), so in my tests I used `import hist`.

I added [readthedocs.yml](https://github.com/LovelyBuggies/Nino-hist/blob/master/readthedocs.yml) to my project and had "Install Project" and "Use system packages" all properly set in [RtD - "Advanced settings"](https://readthedocs.org/dashboard/nino-hist/advanced/). 

## Practice 1

Initially, I didn't use `autodoc_mock_imports` in my `conf.py` and **it went well in my workspace** like this on RtD:

![](https://user-images.githubusercontent.com/29083689/76142844-79a94800-60ac-11ea-9b4d-081ee9a0ed58.png)

But RtD failed to load:

![](https://user-images.githubusercontent.com/29083689/76142948-6cd92400-60ad-11ea-883c-a9698e907bcc.png)

## Practice 2

After Googling a lot and viewing  [jtpaquet's issue](https://github.com/readthedocs/readthedocs.org/issues/4210), I added `autodoc_mock_imports = ["hist"]` to my `conf.py`. Things were not getting better, **the build was even failed in my workspace** -- no module contents shown. And something odd happened like this:

![](https://user-images.githubusercontent.com/29083689/76143025-57b0c500-60ae-11ea-83e0-ab536ae209e7.png)

Could anyone help? Thank you very much! ❤️

**Comment by humitos** [comment]
If you want to use `autodoc` you need to install your own package into the RTD environment. At https://github.com/LovelyBuggies/Nino-hist/blob/master/readthedocs.yml#L18 you need to add 

```
      - method: pip
        path: .
```

See https://docs.readthedocs.io/en/stable/config-file/v2.html#python

Another possibility could be to not use `autodoc` and use [`sphinx-autoapi`](https://sphinx-autoapi.readthedocs.io/) that does not require any module to be installed to get the docstring

**Comment by LovelyBuggies** [comment]
@humitos Thanks, I added 

```
      - method: pip
        path: .
```

to my yml file, but got an error in RTD: https://readthedocs.org/projects/nino-hist/builds/10571575/

**Comment by LovelyBuggies** [comment]
@humitos I would like to invite you as a maintainer on RtD if you want, so you are able to directly build your branch and see what's shown.

**Comment by stsewd** [comment]
@LovelyBuggies looks like you solved the problem https://github.com/LovelyBuggies/Nino-hist/commit/06ea79aeff1b08241f52299948711527f07700a7\

Feel free to ask to reopen if you are still facing the error
