### ISSUE TITLE
Cannot create conda environment, excess memory consumption

### ISSUE THREAD

**Issue by GavinHuttley** [readthedocs/readthedocs.org#6769]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/cogent3/
* Build URL (if applicable): https://readthedocs.org/projects/cogent3/builds/10588747/
* Read the Docs username (if applicable): GavinH

## Expected Result

Successfully construct the conda environment.

## Actual Result

The conda environment was being successfully built 3 weeks ago. The doc build [started failing due to excessive memory consumption](https://readthedocs.org/projects/cogent3/builds/10469694/) from a patch that [did not touch the docs or the build environment](https://github.com/cogent3/cogent3/commit/3bc0a8a413cb82ec6a3e86beaa0e2e71ad8ed3fb).

[The latest cogent3 patch](https://github.com/cogent3/cogent3/commit/8995534bfe3035eb989136a7d6adfaf32bb07cae) was an effort to reduce the conda environment size but has not resolved this issue.

Please note that conda is required here as we generate images files using plotly-orca which is not available on pypi.

**Comment by humitos** [comment]
Hi @GavinHuttley! We are testing a new bigger build server that we think will solve most of the issues around conda and OOM. Would you like me to add your project to this build queue and help us with feedback on this?

**Comment by GavinHuttley** [comment]
Sure!

**Comment by humitos** [comment]
Done. I triggered a new build for your `latest` version and it worked (the build didn't passed because a different error, but the environment was created successfully): https://readthedocs.org/projects/cogent3/builds/10589275/

I'm closing this issue, but please feel free to reopen if you consider or open a new one if you have any feedback regarding the stability of your builds.

**Comment by GavinHuttley** [comment]
Many thanks for this, the error indicates my own package (`cogent3`) was not installed. How does one specify a pip install of it? Can I do that in the conda yml file?
