### ISSUE TITLE
pdf generation fails after a 'libpng error: Not a PNG file'

### ISSUE THREAD

**Issue by Abdelkrim** [readthedocs/readthedocs.org#6770]
## Details

Building the documentation on my local machine works.

The document contains images such as this one:

![Value-Chain-1198x619](https://user-images.githubusercontent.com/791663/76369961-a754f200-6335-11ea-93c9-35970f1ea41b.png)

Deploying the project documentation on rtfd fails due to a **'libpng error: Not a PNG file'** due to the above mentioned image

* Read the Docs project URL: https://readthedocs.org/projects/alt-f1-software-architecture
* Build URL (if applicable): https://readthedocs.org/projects/alt-f1-software-architecture/builds/10589242/
* Read the Docs username (if applicable): Abdelkrim

## Expected Result

the build succeeds

## Actual Result

an error appears during the build : 

> /usr/share/texlive/texmf-dist/tex/latex/psnfss/t1pcr.fd)libpng error: Not a PNG file
> 
> !pdfTeX error: pdflatex (file ./Value-Chain-1198x619.png): libpng: internal err
> or
>  ==> Fatal error occurred, no output PDF file produced!
> Latexmk: Index file 'alt-f1-software-architecture.idx' was written
> Failure to make 'alt-f1-software-architecture.pdf'
> Collected error summary (may duplicate other messages):
>   pdflatex: Command for 'pdflatex' gave return code 256
> Latexmk: Errors, in force_mode: so I tried finishing targets

Thank you in advance for the time you will invest on my issue

**Comment by stsewd** [comment]
@Abdelkrim do you see the same problem when you build your docs locally in a clean environment? If so, this isn't a read the docs problem.

**Comment by Abdelkrim** [comment]
@stsewd the pdf is generated by sphinx.

* the pdf : [SoftwareEngineeringByALT-F1.pdf](https://github.com/readthedocs/readthedocs.org/files/4333057/SoftwareEngineeringByALT-F1.pdf)

* the image generating the error : ![Michael_Porters_Value_Chain-634x311](https://user-images.githubusercontent.com/791663/76686768-255b1680-661e-11ea-9d15-21ccbd98528b.png)

* the logs from sphinx while generating the pdf : [generate_pdf.txt](https://github.com/readthedocs/readthedocs.org/files/4333055/generate_pdf.txt)

thank you for you support

**Comment by humitos** [comment]
@Abdelkrim you are using Git LFS in that file (https://bitbucket.org/altf1be/software-architecture/src/master/source/_static/img/business-to-you.com/Value-Chain-1198x619.png) which is not supported for now. See https://github.com/readthedocs/readthedocs.org/issues/1846 for more information.

I'm closing this one, but feel free to re-open if you consider.

Thanks!

**Comment by Abdelkrim** [comment]
@humitos thank you for the support. I didn't think about Git LFS!

**Comment by Abdelkrim** [comment]
For those who got the issue, here is THE solution : https://github.com/readthedocs/readthedocs.org/issues/1846#issuecomment-477096309
