### ISSUE TITLE
Missing documentation page

### ISSUE THREAD

**Issue by lgatto** [readthedocs/readthedocs.org#6772]
## Details

- I just created an account through my github account.
- On the landing page (see screenshot), the link to the tutorial leads to a missing page
- Dead link: https://renku.readthedocs.io/en/latest/user/firststeps.html

![2020-03-11-065105_961x670_scrot](https://user-images.githubusercontent.com/384198/76386452-d46cc900-6364-11ea-86e2-65691f5e7eb1.png)

## Expected Result

- The *readthedocs* tutorial page 

## Actual Result

- SORRY This page does not exist yet.

**Comment by humitos** [comment]
Hi @lgatto! Can you expand the explanation of your problem?

The landing page works properly to me: https://renku.readthedocs.io/en/latest/

**Comment by lgatto** [comment]
The dead link is https://renku.readthedocs.io/en/latest/user/firststeps.html

Here's a screenshot:

![2020-03-12-063928_892x914_scrot](https://user-images.githubusercontent.com/384198/76490786-4b20c980-642c-11ea-8e53-e0c059f00398.png)

**Comment by stsewd** [comment]
@lgatto can you please put a link to the page where you see the broken link? Also, is this your project? If not, we are not the authors of those docs, we only host them. In that case, you should open an issue on their issue tracker.

**Comment by lgatto** [comment]
Right, sorry, I thought I opened this issue on the renki repo. This isn't yours to sort out, of course. Apologies for the inconvenience.
