### ISSUE TITLE
When using MagicMock to import PyTorch does not generate Module Index pages

### ISSUE THREAD

**Issue by muammar** [readthedocs/readthedocs.org#6773]
## Details

* Read the Docs project URL: https://ml4chem.readthedocs.io/en/latest/
* Build URL (if applicable):

I created this rule to be able to build the documentation for a package that depends on PyTorch. 

```
try:
    import torch
except ModuleNotFoundError:
    from unittest.mock import MagicMock


    class Mock(MagicMock):
       @classmethod
       def __getattr__(cls, name):
           return MagicMock()

    MOCK_MODULES = ['torch', "torch.optim", "torch.nn.Module"]

    sys.modules.update((mod_name, Mock()) for mod_name in MOCK_MODULES)
```

## Expected Result

`Module Index` section with all modules that import PyTorch should be present. 

## Actual Result

All modules that import PyTorch, a mocked module, did not produce module index pages.

More support: https://github.com/muammar/ml4chem/tree/master/docs 

How can this be fixed? Thanks.

**Comment by stsewd** [comment]
@muammar does sphinx generate the correct docs when building locally on a clean environment? If so, this isn't a read the docs problem.

**Comment by muammar** [comment]
> @muammar does sphinx generate the correct docs when building locally on a clean environment? If so, this isn't a read the docs problem.

I tried installing this in a clean environment without Pytorch and the moduleindex is created correctly. If it builds locally correctly why it is not behaving the same way on rdt? I do not understand. I would be glad if you could give me a hint.

**Comment by muammar** [comment]
Ok I think I figured this out. I will report back later.
