### ISSUE TITLE
Add name of build queue to celery worker names

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#6774]
Currently, when performing Celery management operations, the Celery workers report worker names such as `celery@build01`. This works okay for our normal builders, however builders in scaling groups do not have consistent or helpful names.

On Azure, we get `celery@buildlarg00001`, which is at least better than AWS: `celery@ip-123-123-123-123`, which is wholly unhelpful.

It would be great if we instead used the name of the queue in combination with the hostname or hash of the hostname, or something, so that it was easier to glance through Celery/Flower hosts.

Additionally, we're now getting errors for celery web queues, because both sets of workers are using the autogenerated names `celery@web01`, so we likely want a way to configure those queues as well, if they are sticking around (I don't think they are)

Some options:

* `build:default@ip-123-123-123-123` (can we control the `celery@` portion?)
* `celery@build:default/ip-123-123-123-123`
* `celery@build-default:ip-123-123-123-123`
* `celery@build-default:1d2b3c4d`

https://docs.celeryproject.org/en/stable/userguide/workers.html#starting-the-worker

**Comment by humitos** [comment]
> `build:default@ip-123-123-123-123` (can we control the `celery@` portion?)

This is possible. It's the one that I like the most because it gives us all the information.

I tested this locally,

```
python3 -m celery -A readthedocs.worker worker -c 1 -Q celery --hostname build:large@%h
```

and I got this name,

```
$ python3 -m celery  -A readthedocs.worker inspect stats
...
-> build:large@f8dd226df7cf: OK
    {
        "broker": {
            "alternates": [],
            "connect_timeout": 4,
...
```
