### ISSUE TITLE
Bug with cached image

### ISSUE THREAD

**Issue by ivankravets** [readthedocs/readthedocs.org#6783]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/platformio/
* Build URL (if applicable): https://readthedocs.org/projects/platformio/builds/
* Read the Docs username (if applicable): ikravets

## Expected Result

Original image https://github.com/platformio/platformio-docs/blob/develop/_static/images/ide/clion/ide-platformio-clion.png

## Actual Result

Actual image https://docs.platformio.org/en/latest/_images/ide-platformio-clion.png

**Comment by stsewd** [comment]
https://docs.platformio.org/en/latest/_images/ide-platformio-clion.png that gives 404, is that the problem?

**Comment by ivankravets** [comment]
It is here https://github.com/platformio/platformio-docs/tree/develop/_static/images/ide/clion

What is interesting, I added a duplicate `ide-platformio-clion-new.png` and it works :(

**Comment by stsewd** [comment]
Can you be more specific about the problem you are having if isn't about the 404?

**Comment by ivankravets** [comment]
I do not know what has happened. I removed the image, restart build, reverted image back and now it works :(

https://docs.platformio.org/en/latest/_images/ide-platformio-clion.png
