### ISSUE TITLE
use conda 4.7.12.1 for cdat-vcs

### ISSUE THREAD

**Issue by muryanto1** [readthedocs/readthedocs.org#6786]
## Details

* Read the Docs project URL:https://readthedocs.org/projects/cdat-vcs
* Build URL (if applicable): https://readthedocs.org/projects/cdat-vcs/builds/10624189/
* Read the Docs username (if applicable): muryanto1

## Expected Result

*A description of what you wanted to happen*
Hello, I have been having problem building with latest conda.
Miniconda released 4.8.2 on 3/11/2020.
Can you not do 'conda update --yes' for https://readthedocs.org/projects/cdat-vcs ?
I created a conda env locally using the project docs/rtd_environment.yml file and it built find with conda 4.7.12.1.

## Actual Result

*A description of what actually happened*
hitting Command killled due to excessive memory consumption.

**Comment by humitos** [comment]
Done. Please, next time contact us via support@readthedocs.org. Thanks!
