### ISSUE TITLE
conf.py not found although new location specified in .yml config file

### ISSUE THREAD

**Issue by mluerig** [readthedocs/readthedocs.org#6787]
## Details

* Read the Docs project URL: https://github.com/mluerig/phenopype/tree/development
* Build URL (if applicable): 
* Read the Docs username (if applicable): mluerig

## Expected Result

trying to build rtd page from the development branch, I have my `conf.py` in a separate source folder in the root dir. specified in readthedocs.yml. 

## Actual Result

keep getting `A configuration file was not found. Make sure you have a conf.py file in your repository.`

**Comment by stsewd** [comment]
@mluerig `docs_source/conf.py` doesn't exist on your repository https://github.com/mluerig/phenopype/tree/development

https://github.com/mluerig/phenopype/blob/cf7aa6dd5ba637db4b95a39dca3ad525a2b4e60a/readthedocs.yml#L10

**Comment by mluerig** [comment]
oh dang, sorry. 

one more thing though: in my sphinx `conf.py` I do `import phenopype` to get the version string. however, when trying to build RTD, I get an error msg that the package isn't installed. as per the instructions, I added the following to `readthedocs.yml`:

```
python:
   version: 3.7
   install:
      - method: pip # also tried setuptools
        path: phenopype
```
this doesn't work bc I don't get the relative path right. I am generally a bit confused as to what the virtual environment looks like. how would I have to specify the path for the package to be installed. 

alternatively, would it be possible to just to a relative module import from the directory to get the version string embedded in `_version.py`? is this even good practice? thanks!

**Comment by stsewd** [comment]
@mluerig the all commands are executed having your repository as  the current working directory. So the path should be `.`
