### ISSUE TITLE
No doxygen output generated with breathe

### ISSUE THREAD

**Issue by floriantschopp** [readthedocs/readthedocs.org#6795]
Hi everyone,

I have a problem when trying to our local build of the [maplab](https://github.com/ethz-asl/maplab/tree/develop-docs) documentation to readthedocs.org

When using the Makefile locally, the build takes quite some time and results in successfully (with some warnings but I can fix them later) building the API documentation. On readthedocs, the build is also successful (very fast) but skips the API part. From the build logs, I cannot find a trace of why this could be happening.
I read #5144, #5145, #5076 and #2958 but without finding my issue.

Any help is highly appreciated.

## Details

* Read the Docs project URL: https://maplab.readthedocs.io/en/develop-docs/
* Build URL (if applicable): https://readthedocs.org/projects/maplab/builds/10637813/
* Read the Docs username (if applicable): floriantschopp

## Expected Result

API documentation is generated using doxygen (with breathe/exhale)

## Actual Result

Doxygen returns empty.

**Comment by stsewd** [comment]
@floriantschopp we don't execute the make file, we only execute the sphinx-build command as you can see in https://readthedocs.org/projects/maplab/builds/10637813/.

**Comment by floriantschopp** [comment]
I just tried to reproduce the exact same setup that is documented in the build [log](https://readthedocs.org/projects/maplab/builds/10637813/) using the same `pip` setup and `sphinx-build` command. However, on my local machine exhale still builds my API correctly.

**Comment by floriantschopp** [comment]
@stsewd Anything else I can try? Thanks a lot for your assistance.

**Comment by stsewd** [comment]
@floriantschopp sorry, not sure what else to try. When you try locally, did you try in a clean directory? (removing all previous generated files, like `_output`/`output` dirs)

**Comment by floriantschopp** [comment]
Yea, I built it on a clean directory.

**Comment by floriantschopp** [comment]
FYI: I worked around this by using [sphinx-multiversion](https://github.com/Holzhaus/sphinx-multiversion) and a self-hosted documentation.

**Comment by humitos** [comment]
@floriantschopp from your build output, it seems that breathe is not well configured and it's not finding the source code of the API to document.

```
[~] Exhale: executing doxygen.
[+] Exhale: doxygen ran successfully in 0.33 seconds.
[~] Exhale: adding tree view css / javascript.
[+] Exhale: added tree view css / javascript.
[~] Exhale: parsing Doxygen XML.
[+] Exhale: finished parsing Doxygen XML in 0.01 seconds.
[~] Exhale: generating reStructuredText documents.
[+] Exhale: generated reStructuredText documents in 0.0 seconds.
```

From the RTD's output it seems that you are not checking out the submodules and I guess the API you want to document using doxygen is there.
