### ISSUE TITLE
Search result links to prior version of a moved document

### ISSUE THREAD

**Issue by sbenthall** [readthedocs/readthedocs.org#6822]
## Details

* Read the Docs project URL: https://hark.readthedocs.io/en/latest/

## Expected Result

Searching for "Portfolio" gets a top result which is this page:

https://hark.readthedocs.io/en/latest/example_notebooks/ConsPortfolioModel.html

## Actual Result

Searching for "Portfolio" gets to a 404 page:
https://hark.readthedocs.io/en/latest/example_notebooks/ConsPortfolioModelDoc.html

## Background information

- In this case, ConsPortfolioModelDoc was the name of the desired document in a previous version.
- The .rst documents point to this document via a symlink, which has been updated.
- A local sphinx build of the documentation gets the expected search result

**Comment by stsewd** [comment]
Shouldn't the search result be https://hark.readthedocs.io/en/latest/api-cs-ConsPortfolioModel.html?

**Comment by stsewd** [comment]
I can see everything is good in the files we use to index search, but looks like the index ins't being updated for some reason.

**Comment by sbenthall** [comment]
That is what I suspected. Something wrong with the updating of the search index.
I've tried rebuilding the site a couple times.
Is there anything else I can do to help debug this?

**Comment by stsewd** [comment]
We found the problem, this doesn't affect all projects. We hope to deploy the fix by tomorrow.

**Comment by stsewd** [comment]
@sbenthall search indexing should work now, if you find a problem in another project/version, you need to trigger a build in order to refresh the search index.
