### ISSUE TITLE
Issue with automatic webhook syncing

### ISSUE THREAD

**Issue by adithyabsk** [readthedocs/readthedocs.org#6824]
## Details

* Read the Docs project URL: https://pyrh.readthedocs.io/en/latest/
* Read the Docs username (if applicable): adithyabsk
* Project URL: https://github.com/robinhood-unofficial/pyrh

## Expected Result

I'd expect the webhook to sync. Another thing of note is that I was required to manually configure the project as the project nor the org did not show up in the import menu whereas other orgs that I am a part of, show up properly. Might this have something to do with recently changing the project's name?

I appreciate any help here.

## Actual Result
![image](https://user-images.githubusercontent.com/4440808/77653462-193c5680-6f46-11ea-9010-f0e1488d1024.png)

![image](https://user-images.githubusercontent.com/4440808/77653517-2bb69000-6f46-11ea-8c74-7fe1601551ce.png)

**Comment by adithyabsk** [comment]
I was able to get the docs to build by manually triggering the build

**Comment by stsewd** [comment]
@adithyabsk please check that the read the docs app has permissions over your organization at https://github.com/settings/applications

**Comment by adithyabsk** [comment]
@stsewd That worked. It might be useful to add to the docs as a place to look if that specific error shows up.

![image](https://user-images.githubusercontent.com/4440808/77678956-4dc10a00-6f68-11ea-8cbc-1f78e6825127.png)

**Comment by adithyabsk** [comment]
Thanks for the help!
