### ISSUE TITLE
Excessive memory consumption when building conda environment

### ISSUE THREAD

**Issue by gustavo-marques** [readthedocs/readthedocs.org#6835]
## Details

* Read the Docs project URL: https://mom6-tools.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/mom6-tools/builds/10727963/
* Read the Docs username (if applicable): gustavo-marques

## Expected Result
Successfully build the conda environment.

## Actual Result
Documentation builds fails because of  **Command killed due to excessive memory consumption error**. I was told this is due to the fact that conda consumes a lot of memory, and Readthedocs sets a limit to how much memory can be used. Would it be possible to increase the memory limit for this project?

Thanks!

**Comment by humitos** [comment]
If it's possible to install all the docs dependencies without using `conda-forge` channel, try that. It's a known bug in conda that it takes a lot of memory when using that channel. See https://www.anaconda.com/understanding-and-improving-condas-performance/

**Comment by gustavo-marques** [comment]
Thanks @humitos. Unfortunately, some of the dependencies are only available via conda-forge. Any other way to bypass this problem?

**Comment by humitos** [comment]
Hi @gustavo-marques, I moved your project to a bigger server. The conda step passed. Although, it's failing for a different reason: https://readthedocs.org/projects/mom6-tools/builds/10742778/

I'm closing this issue, but feel free to reopen if you still have the problem with the memory.
