### ISSUE TITLE
Successful build but docs are not updated

### ISSUE THREAD

**Issue by fepegar** [readthedocs/readthedocs.org#6837]
## Details

* Read the Docs project URL: https://torchio.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/torchio/builds/10730340/
* Read the Docs username (if applicable): `fepegar`

## Expected Result
I expected the docs reflect the new changes I pushed to GitHub. 

## Actual Result
The documentation is not updated.

For example, [this docstring](https://github.com/fepegar/torchio/blob/master/torchio/transforms/augmentation/spatial/random_elastic_deformation.py#L16) is [missing](https://torchio.readthedocs.io/transforms/augmentation.html#randomelasticdeformation). I'll temporarily host the docs on a GitHub repo, where [the changes are visible](https://fepegar.github.io/torchio-docs/transforms/augmentation.html#randomelasticdeformation).

I tried force-reloading the website with no luck.

**Comment by fepegar** [comment]
Actually, I think RTD is showing a pretty old version of the docs.

**Comment by fepegar** [comment]
Wiping the build and rebuilding didn't help.

**Comment by stsewd** [comment]
@fepegar all docstrings aren't show because sphinx can't find some packages

> WARNING: autodoc: failed to import class 'data.images.ImagesDataset' from module 'torchio'; the following exception was raised:

You can check all the warnings at the build html step

https://readthedocs.org/projects/torchio/builds/10735911/

**Comment by humitos** [comment]
Hi! If you take a look at the build's output, you will see lines like this:

```
WARNING: autodoc: failed to import class 'transforms.RandomElasticDeformation' from module 'torchio'; the following exception was raised:
```

It seems that some package is not properly installed.

**Comment by fepegar** [comment]
I fixed that and now I can see the docstrings. I'll check the logs before creating an issue next time. Thanks @stsewd and @humitos!

**Comment by humitos** [comment]
@fepegar you can use https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx-fail-on-warning to fail the builds if you have warnings like this one.

**Comment by fepegar** [comment]
I'll do that. Thanks!
