### ISSUE TITLE
Sidebar links giving 404 (something to do with spaces in url?)

### ISSUE THREAD

**Issue by CamDavidsonPilon** [readthedocs/readthedocs.org#6842]
## Details

* Read the Docs project URL: https://lifelines.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/lifelines/builds/10739010/
* Read the Docs username (if applicable): CamDavidsonPilon

## Expected Result

Clicking on a sidebar URL, like "Introduction to survival analysis", does not give a 404. 

## Actual Result

Well, it does give a [404](https://lifelines.readthedocs.io/en/latest/Survival%20Analysis%20intro.html). As of March 30th, 2020, this sidebar link was working.

This occurs on other RTD projects too, example: https://zepid.readthedocs.io/en/latest/. 

My current theory is that if the rst file name has spaces in it, it fails. For all the sidebar links that direct to rst files with spaces in the name, we get a 404. And the opposite is true too. 

Is this an intended change?

**Comment by ericholscher** [comment]
This should be fixed, sorry about that.

**Comment by CamDavidsonPilon** [comment]
Confirmed it's fixed, ty!
