### ISSUE TITLE
I am having problems building documentation 

### ISSUE THREAD

**Issue by robertosaavedr** [readthedocs/readthedocs.org#6852]
Sorry if this is something obvious, but I am having  to build my documentation

* Read the Docs project URL:
supermarket.readthedocs.io
* Build URL (if applicable):
https://readthedocs.org/projects/supermarket/builds/10751774/
* Read the Docs username (if applicable):
rsaavedr
## Expected Result
Built docs
## Actual Result
doesn't build

**Comment by stsewd** [comment]
@robertosaavedr you are trying to install your package using a setup.py file, but your project doesn't have one

https://github.com/robertosaavedr/Supermarket/blob/447e9bf56e72977063478766063a69a80563b166/readthedocs.yml#L1-L2

Also, you should use the v2 of the configuration file https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by robertosaavedr** [comment]
thanks :)
