### ISSUE TITLE
Request: Enable PR builder for stsci.tools

### ISSUE THREAD

**Issue by pllim** [readthedocs/readthedocs.org#6854]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/stscitools/
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): pllim

## Expected Result

I would like to enable your awesome PR builder feature for https://github.com/spacetelescope/stsci.tools . Is that possible?

Thank you very much for this great service to the open source community!

**Comment by humitos** [comment]
I enabled it. Check out the documentation at https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

Please, next time contact us through our support email.

**Comment by pllim** [comment]
Thank you, will do. Sorry for the noise here.
