### ISSUE TITLE
The local Markdown document is inconsistent with the effect on the RTD

### ISSUE THREAD

**Issue by soodifficult** [readthedocs/readthedocs.org#6855]
## Details

* Read the Docs project URL: http://doc.ig.inhandnetworks.com/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

*Line markup and table display in local Markdown have the same display effect on RTD*

## Actual Result

*If there is a markdown list before a new line, the line break may not be valid on the RTD; the Markdown table cannot be displayed on the RTD. Is only Mkdocs better compatible with markdown documents?*

**Comment by stsewd** [comment]
@soodifficult if you build your docs locally, do you see the same result? If so, this isn't a problem with rtd, but with the sphinx/recommonmark.

If you see different results, make sure you are using the same version of sphinx on rtd https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html#specifying-a-requirements-file

**Comment by soodifficult** [comment]
This is the problem：
The docs i build locally and on the RTD is not the same with my docs in VS Code. 
![image](https://user-images.githubusercontent.com/32888185/78861157-af07d380-7a66-11ea-893e-28e4f977d8ab.png)

**Comment by soodifficult** [comment]
![1586409936(1)](https://user-images.githubusercontent.com/32888185/78861335-23db0d80-7a67-11ea-9a8a-3115186d96e8.jpg)

**Comment by soodifficult** [comment]
I don't think this problem is caused by the requirements file. Because whatever i use or not use the requirements file, it's always will happend!

**Comment by stsewd** [comment]
>  The docs i build locally and on the RTD is not the same with my docs in VS Code.

@soodifficult we don't use the backend that VS code uses to render the markdown file. Please see https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html#using-markdown-with-sphinx or https://docs.readthedocs.io/en/stable/intro/getting-started-with-mkdocs.html
