### ISSUE TITLE
Build error with build id #10762523

### ISSUE THREAD

**Issue by shabak** [readthedocs/readthedocs.org#6857]
## Details:

* Project URL: https://readthedocs.org/projects/paxful/
* Build URL(if applicable): https://readthedocs.org/projects/paxful/builds/10762523/
* Read the Docs username(if applicable): shabak

## Expected Result

The docs have successfully built

## Actual Result

An error occurs, seems the problem is not with sources since i rolled back the commit but the same error happened
https://readthedocs.org/api/v2/build/10736096.txt

**Comment by humitos** [comment]
Hi! It seems that you are pinning a build image that it's not supported `2.0`. If you remove that line from your config file, it will be fixed. https://github.com/paxful/api-docs/blob/master/readthedocs.yml#L3

Also, I recommend you to upgrade your config file to v2: https://docs.readthedocs.io/en/stable/config-file/v2.html

Closing this issue. Feel free to re-open if that does not solve the issue.
