### ISSUE TITLE
Please set DONT_SHALLOW_CLONE for Fuzzinator

### ISSUE THREAD

**Issue by renatahodovan** [readthedocs/readthedocs.org#6858]
Fuzzinator is using `setuptools_scm` to get the version and the shallow clone is preventing `git describe` working correctly.
Could you please set `DONT_SHALLOW_CLONE`?

## Details

* Read the Docs project URL: https://readthedocs.org/projects/fuzzinator/
* Read the Docs username (if applicable): renatahodovan

## Expected Result

Fuzzinator 18.3.1+188.g862f857 documentation

## Actual Result

Fuzzinator 0.0+50.g862f857 documentation

**Comment by humitos** [comment]
I added this flag to your project. Let me know if anything.

**Comment by renatahodovan** [comment]
Thanks, it works already.
