### ISSUE TITLE
Allow users to customize the URL Pattern for their projects

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#6868]
Historically, we've offered a subset of URL patterns for a project. The default is `/$lang/$version/$filename`. We also offer multiple projects on a single domain via subproject & translations: `/projects/$subproject/$lang/$version/$filename`.  But we have a lot of users who want different things from these URLs:

* no `/projects/` or a different string there
* No language but still have a version

## Issue with the current approach

One big issue is we end up with conflicting regexs that can match. For example someone who wanted `/$version/$filename`, with a version and no language, could have a version of `en`. Our regexs wouldn't know how to actually parse this, and we'd have to guess.

## Proposed solution

It would be much cleaner if we could parse a specific project's URLs using a known regex. If we let users configure this, we would then be able to only have 1 regex that we're testing, and always have proper matches. For example in our config:

```
# Only version
readthedocs:
  url:
    format: '/$en/$filename'

# Custom subproject
readthedocs:
  url:
    format: '/components/$subproject/$en/$filename'
```

## Implementation

I think we could add this to the config file. We'd then sync it to the Database on build, and cache it in proxito for serving.

The actual URL resolution could use either the Django URL resolver or just the regex model. I'm imagining something like this:

https://github.com/readthedocs/readthedocs.org/blob/e166c1ccc327bcfd2e41850939ca59b101820f35/readthedocs/proxito/views/serve.py#L173-L178

**Comment by agjohnson** [comment]
I'm having trouble picturing how the actual resolution would work in this case, so i don't have much input there. Either seem reasonable, however I haven't dived deep into the proxito changes yet.

I'm -1 on using the config file for project level settings. Project level settings should be in the UI and database, controlling project level settings in version level config files is confusing UX as it's not easy to see which version is the canonical source. We can skip UI for now, I think the functionality is more important than allowing configuration. Adding a form field can be handled later

**Comment by ericholscher** [comment]
@agjohnson there's a PR that already implements this as a DB field: https://github.com/readthedocs/readthedocs.org/pull/6963

**Comment by ericholscher** [comment]
This is now merged and we're able to support it via an email to our support. I'm going to close this, since it's now implemented. It will be promoted more in the next release of our product, but the code is there 👍
