### ISSUE TITLE
Banner: warn users on latest they're looking at dev docs and link to stable

### ISSUE THREAD

**Issue by mdeff** [readthedocs/readthedocs.org#6884]
I've had multiple issues opened by users reading docs from `latest` (I don't know how they arrived there, maybe through a web search) without realizing those were for the development version, not the version they installed with `pip` or `conda`.

Could we extend the version banner to warn anytime people are not viewing `stable`? I've seen the discussion in #3481, where it's argued that this is complicated in general. I agree. But I think `latest` being the developement version is quite common. I'd propose three options for the banner:
1. no banner (or do it yourself)
2. banner warns on old and redirects to stable (what we have now)
3. banner warns on old and latest and redirects to stable (would cover many use cases in my opinion)

Example message from PyTorch.
![20200409_160410](https://user-images.githubusercontent.com/6806065/78904001-3744a380-7a7c-11ea-8771-7fe67ec6d040.png)

**Comment by stsewd** [comment]
You can do 1 with https://github.com/humitos/sphinx-version-warning.

> banner warns on old and latest and redirects to stable (would cover many use cases in my opinion)

I think we didn't do that because every project wants to be able to customize the wording and where to put the message, so is hard to cover all of these cases.

**Comment by mdeff** [comment]
I think a standard default would help a lot. The documentation could then redirect to <https://github.com/humitos/sphinx-version-warning> (or alternatives) for customization.

**Comment by humitos** [comment]
@mdeff Hi! We already have a warning banner implemented inside RTD (you can enable it from your admin's project). Although, as @stsewd said, it didn't cover all the cases and people had different ideas of what it was the best.

I implemented sphinx-version-warning as an high customizable alternative so each owner can show the banner where they like and how they like.

I'm afraid that we are not going to change RTD internal's behavior, but I'm happy to read any suggestion that you may have about that extension in case you find it useful for your use case.

**Comment by rmarzocchi84** [comment]
I have tried the a warning banner implemented inside RTD, but it do not show nothing. There is some option in the conf.py to set?
