### ISSUE TITLE
Can't find dependencies that were successfully installed

### ISSUE THREAD

**Issue by tych0** [readthedocs/readthedocs.org#6890]
## Details

* Read the Docs project URL: http://docs.qtile.org/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/qtile/builds/10815723/
* Read the Docs username (if applicable): tych0

## Expected Result

Build succeeds, cairocffi is found.

## Actual Result

Build fails, cairocffi is not found.

I've recently added cairocffi and xcffib to our build deps here: https://github.com/qtile/qtile/blob/master/.readthedocs.yml

But the build fails because it can't find the package cairocffi, even though it's clearly successfully installed earlier. I've enabled access to the site packages, but still no luck.

**Comment by pawamoy** [comment]
You could try to wipe the cache. Go to https://readthedocs.org/projects/qtile/versions/ when logged in, hit "edit" on a version and "wipe", then rebuild it.

**Comment by tych0** [comment]
Oh, turns out we needed to add it to our mock modules list: https://github.com/qtile/qtile/commit/004699015b4963be9a4d131a2e8f87266ffad2f4

Sorry for the noise :)

**Comment by pawamoy** [comment]
I was able to get passed the error with 

```diff
diff --git a/docs/conf.py b/docs/conf.py
index 3ced1939..da9aa76e 100644
--- a/docs/conf.py
+++ b/docs/conf.py
@@ -26,7 +26,7 @@ class Mock(MagicMock):
 MOCK_MODULES = [
     'libqtile._ffi_pango',
     'libqtile.backend.x11._ffi_xcursors',
-    'cairocffi',
+    #'cairocffi',
     'cairocffi.pixbuf',
     'cffi',
     'dateutil',
@@ -39,6 +39,7 @@ MOCK_MODULES = [
     'psutil',
     'trollius',
     'xcffib',
+    'xcffib._ffi',
     'xcffib.randr',
     'xcffib.xfixes',
     'xcffib.xinerama',
```

But now get this:

```console
sphinx-build -E -W -b html -d _build/doctrees   . _build/html
Running Sphinx v3.0.1
making output directory... done
/home/pawamoy/data/dev/forks/qtile/docs/conf.py:308: RemovedInSphinx40Warning: The app.add_stylesheet() is deprecated. Please use app.add_css_file() instead.
  app.add_stylesheet("no_scrollbars.css")
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 35 source files that are out of date
updating environment: [new config] 35 added, 0 changed, 0 removed
reading sources... [100%] manual/ref/widgets                                                                                                                                                                                                   

Warning, treated as error:
<QtileClass>:1:Explicit markup ends without a blank line; unexpected unindent.
```
