### ISSUE TITLE
A way to redirect to another version/branch

### ISSUE THREAD

**Issue by Kwoth** [readthedocs/readthedocs.org#6891]
## Details

I'm trying to redirect old versions of the docs to the latest. But I can't seem to find a way to do that. 

Here's what i've tried so far (i've tried dozens of random things, none have worked)
![image](https://user-images.githubusercontent.com/2537696/79059218-8efb2e80-7c77-11ea-80b5-1fc93ba4a8e8.png)

* Read the Docs project URL: https://nadekobot.readthedocs.io/
* Build URL (if applicable):
* Read the Docs username (if applicable): Kwoth

## Expected Result

When clicking https://nadekobot.readthedocs.io/en/1.0/ (or if possible any page on this version) it should redirect the user to https://nadekobot.readthedocs.io/en/latest/

## Actual Result

There is no redirect

**Comment by humitos** [comment]
Hi @Kwoth!

Take into account that `$lang` and `$version` are not variables. That may be confusing from the UI. The only variable that RTD supports is `$rest`

That said, another current limitation that redirects have, is that they are only triggered when a 404 is found. So, if the https://nadekobot.readthedocs.io/en/1.0/ returns a 200, no redirect are executed. (see https://docs.readthedocs.io/en/latest/user-defined-redirects.html#implementation)

If you de-activate version `1.0` and add a redirect like this, I think it should do what you are trying to do:

* Type: Exact Redirect (see https://docs.readthedocs.io/en/latest/user-defined-redirects.html#exact-redirects)
* From URL: /en/1.0/$rest
* To URL: /en/latest/

Hitting `/en/1.0/another/page.html` will redirect to `/en/latest/another/page.html`.

Let me know if that works.

**Comment by Kwoth** [comment]
Thank you very much!
