### ISSUE TITLE
reStructuredText highlight the python code

### ISSUE THREAD

**Issue by soodifficult** [readthedocs/readthedocs.org#6892]
## I hope reStructuredText can display python code like this. I try to use **.. highlight:: python**, but it's does not work well. I contacted reStructuredText and not long ago, I used markdown before.
* Read the Docs project URL:
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

I want it like this.(Python code in markdown)
![image](https://user-images.githubusercontent.com/32888185/79059725-0ba9ff00-7cb0-11ea-8c8f-4f9520feb2b3.png)

## Actual Result

When i use **.. highlight:: python**, that's the result.
![image](https://user-images.githubusercontent.com/32888185/79059770-6f342c80-7cb0-11ea-8c23-aee2e976de96.png)
![image](https://user-images.githubusercontent.com/32888185/79059776-765b3a80-7cb0-11ea-8962-d8d2906a55aa.png)

**Comment by humitos** [comment]
Hi @soodifficult! Have your tried using `.. code-block:: python` instead? See http://www.sphinx-doc.org/es/stable/markup/code.html#directive-code-block

**Comment by soodifficult** [comment]
Yes, I tried it. But no way

**Comment by humitos** [comment]
I recommend you build your docs locally to find out this problem. This is not a RTD issue. You may be not indenting the code properly.

**Comment by soodifficult** [comment]
ok，3ks a lot. I‘am here’ to ask for grammar.
