### ISSUE TITLE
[Self-Hosted RTD] Issue creating VENV

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#6893]
I am aware that this is not a supported scenario, but any help is appreciated regardless.

My name is Dalton and currently developing a [readthedocs docker image](https://github.com/Daltz333/docker-images/blob/frc-rtd-docker/frc-read-the-docs/Dockerfile) for streamlining self-hosting for the [wpilibsuite](https://github.com/wpilibsuite) organization. Following the [installation steps](https://docs.readthedocs.io/en/stable/development/install.html) through a standard ubuntu installation (on a separate machine running Ubuntu 18.04) seems to give a successful build, however my docker image seems to be failing with the below error message.

An additional note is if I log onto the docker image and run the command manually, it works just fine.

![image](https://user-images.githubusercontent.com/10674555/79094434-8103e700-7d25-11ea-8edd-26d39613718d.png)

Attached is the full log from the docker output: https://hastebin.com/akahawusol.cs

Why are we self hosting? https://hastebin.com/upuxitited.coffeescript

**Comment by humitos** [comment]
> Following the [installation steps](https://docs.readthedocs.io/en/stable/development/install.html) through a standard ubuntu

We moved away from that setup and we are using our own docker images now for development: https://docs.readthedocs.io/en/stable/development/standards.html

You may find some help from reading that guide and checking out how we create the Dockerfile's among others.

**Comment by humitos** [comment]
> Why are we self hosting? https://hastebin.com/upuxitited.coffeescript

Reading those reasons, I wouldn't recommend follow this path. We can talk about giving more resources to your project (in fact, we have bigger builders now). I think you will have more problems by maintaining your own instance, but that's up to you, of course. My 2 cents.

**Comment by deepshikhagandhi** [comment]
We have come across the same issue. Looks like there's an extra space introduced in that command due to https://github.com/readthedocs/readthedocs.org/commit/d0ddcb6c191b002c9dc620d8059faf736ec2c379#diff-31f8391d8643c47c6caedf53930c0b7e

Reverting this back to `site_packages = '--no-site-packages'` fixes the issue.

**Comment by Daltz333** [comment]
This issue is still present.

**Comment by humitos** [comment]
Hi @Daltz333! Unfortunately, we do not offer support on custom installations. We have a note in our docs about this: https://docs.readthedocs.io/en/stable/open-source-philosophy.html#unsupported

**Comment by stsewd** [comment]
This is because the version of virtualenv, in production we use https://github.com/readthedocs/readthedocs-docker-images/blob/f8db06c9cf64c3473a524c08b547805288b81f71/Dockerfile#L117

But in the repo we are pinning to https://github.com/readthedocs/readthedocs.org/blob/a75907cc311221f9382e71558cce53cd4de57f55/requirements/pip.txt#L4

We should pin to the same version

**Comment by Daltz333** [comment]
Not stale.

**Comment by DougCal** [comment]
Since PR https://github.com/readthedocs/readthedocs.org/pull/7330 fixes issue https://github.com/readthedocs/readthedocs.org/issues/7322, is this one fixed as well?  It was suggested that issue https://github.com/readthedocs/readthedocs.org/issues/7322 is the same as this one.

**Comment by stsewd** [comment]
It should be fixed, but we still should use the same version as docker as outside docker.

**Comment by humitos** [comment]
I'm closing this issue since there is no action required from the core team. As I mentioned in my previous comment, unfortunately we do not offer support for self-hosted Read the Docs instances.
