### ISSUE TITLE
build formats not respected

### ISSUE THREAD

**Issue by fmigneault** [readthedocs/readthedocs.org#6913]
## Details

* Read the Docs project URL: pavics-magpie.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/pavics-magpie/builds/10844271/
* Read the Docs username (if applicable): fmigneault
* RTD config matching build: https://github.com/Ouranosinc/Magpie/blob/magpie-utilities-doc/.readthedocs.yml

## Expected Result

Because `format` section for `.readthedocs.yml` file explicitly requests only for html build, the latex generation should not be executed. In my case, this causes a build failure because a file generated by an extension cannot be found under latex build.

## Actual Result

Readthedocs proceeds to build the (pdf)latex and fails, although the only actually requested html build already completed successfully. YAML config, nor the checkboxes in the advanced settings seem to be respected.

**Comment by humitos** [comment]
Hi! The build that you linked in the description built the commit dc5215bf79658f59dd12eb282e1d3f7d895193c5 that has this YAML file saying `format: all`. See https://github.com/Ouranosinc/Magpie/blob/dc5215bf79658f59dd12eb282e1d3f7d895193c5/.readthedocs.yml#L5

**Comment by fmigneault** [comment]
Ah! You're right. Build trigger didn't pick the latest commit in time. Thanks.
