### ISSUE TITLE
Build fails: virtualenv - the dest is Unrecognized Aruguments

### ISSUE THREAD

**Issue by leicao-me** [readthedocs/readthedocs.org#6915]
## Details

* Read the Docs project URL: https://github.com/readthedocs/readthedocs.org
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

The repo's doc successfully is built

## Actual Result

![unrecognized_arguments](https://user-images.githubusercontent.com/18321875/79480205-abbe9b80-7fc2-11ea-810c-cb02d5335fc4.JPG)

It says the dest argument is not recognized. 

THEN I manually put this error command in the command line, there's no error:

python3.6 -mvirtualenv  /readthedocs/user_builds/read-the-docs/envs/latest

![unrecognized_arguments1](https://user-images.githubusercontent.com/18321875/79480477-f9d39f00-7fc2-11ea-8f58-04cd0cffb809.JPG)

BTW, I‘m hosting the readthedocs service in a docker container. 
readthedocs version is 4.1.5

**Comment by leicao-me** [comment]
I also hardcoded double quotes to the path, but building still gives the same error

**Comment by humitos** [comment]
@leicao-me hi! It seems that you are not setting a RTD variable properly. Take a look at this guide: https://docs.readthedocs.io/en/stable/development/standards.html

**Comment by ericholscher** [comment]
Closing this as it isn't an issue on our side.
