### ISSUE TITLE
Issue building matplotlib plot_directive, sphinx 3.0

### ISSUE THREAD

**Issue by drewejohnson** [readthedocs/readthedocs.org#6916]
## Details
Since sphinx 3.0 was released, RTD has failed to build documentation on our master branch. The error is always in `app.add_directive` due to some of unexpected input argument

* Read the Docs project URL: http://serpent-tools.readthedocs.io/en/latest/
* Build URL (if applicable): [First failure](https://readthedocs.org/projects/serpent-tools/builds/10775661/) and [previous successful build](https://readthedocs.org/projects/serpent-tools/builds/10752799/)
* Read the Docs username (if applicable):

## Expected Result

Documentation is correctly built

## Actual Result

Documentation failed to be built. Error message:
```
python /home/docs/checkouts/readthedocs.org/user_builds/serpent-tools/envs/master/bin/sphinx-build -T -W -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
Running Sphinx v3.0.1
loading translations [en]... done
/home/docs/checkouts/readthedocs.org/user_builds/serpent-tools/envs/master/lib/python3.5/site-packages/sphinx/deprecation.py:49: RemovedInSphinx40Warning: sphinx.builders.html.DirectoryHTMLBuilder is deprecated. Check CHANGES for Sphinx API modifications.
  return getattr(self._module, name)
/home/docs/checkouts/readthedocs.org/user_builds/serpent-tools/envs/master/lib/python3.5/site-packages/readthedocs_ext/readthedocs.py:14: RemovedInSphinx40Warning: sphinx.builders.html.SingleFileHTMLBuilder is deprecated. Check CHANGES for Sphinx API modifications.
  from sphinx.builders.html import (DirectoryHTMLBuilder, SingleFileHTMLBuilder,

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/serpent-tools/envs/master/lib/python3.5/site-packages/sphinx/cmd/build.py", line 279, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/serpent-tools/envs/master/lib/python3.5/site-packages/sphinx/application.py", line 244, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/serpent-tools/envs/master/lib/python3.5/site-packages/sphinx/application.py", line 398, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/serpent-tools/envs/master/lib/python3.5/site-packages/sphinx/registry.py", line 414, in load_extension
    metadata = setup(app)
  File "/home/docs/.pyenv/versions/3.5.7/lib/python3.5/site-packages/matplotlib/sphinxext/plot_directive.py", line 262, in setup
    app.add_directive('plot', plot_directive, True, (0, 2, False), **options)
TypeError: add_directive() got an unexpected keyword argument 'width'

Exception occurred:
  File "/home/docs/.pyenv/versions/3.5.7/lib/python3.5/site-packages/matplotlib/sphinxext/plot_directive.py", line 262, in setup
    app.add_directive('plot', plot_directive, True, (0, 2, False), **options)
TypeError: add_directive() got an unexpected keyword argument 'width'
The full traceback has been saved in /tmp/sphinx-err-ihkfoj_f.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

There was a single PR that was merged between the good and bad builds - https://github.com/CORE-GATECH-GROUP/serpent-tools/pull/396

[link to specific build commit](https://github.com/CORE-GATECH-GROUP/serpent-tools/commit/aa9781aef7830b1505b6ba69bc78eb7b9efc48bf)

I have searched the [readthedocs](https://github.com/readthedocs/readthedocs.org/search?q=plot_directive&type=Issues), [sphinx](https://github.com/sphinx-doc/sphinx/search?q=plot_directive&type=Issues), and [matplotlib](https://github.com/matplotlib/matplotlib/search?o=desc&q=plot_directive&s=created&type=Issues) for related issues with no luck.

**Comment by stsewd** [comment]
Are you able to build your docs locally?

**Comment by drewejohnson** [comment]
Yes, I'm able to build locally with sphinx 3.0.1 and matplotlib 3.2.1

**Comment by humitos** [comment]
This is a bug in our extension, that it's not compatible with Sphinx 3.x

You can downgrade your Sphinx version for now. I hope we can deploy a fix for this soon.

**Comment by humitos** [comment]
Ups... I misread the log. It's a WARNING the problem with the extension, not an ERROR:

```
/home/docs/checkouts/readthedocs.org/user_builds/serpent-tools/envs/master/lib/python3.5/site-packages/sphinx/deprecation.py:49: RemovedInSphinx40Warning: sphinx.builders.html.DirectoryHTMLBuilder is deprecated. Check CHANGES for Sphinx API modifications.
  return getattr(self._module, name)
/home/docs/checkouts/readthedocs.org/user_builds/serpent-tools/envs/master/lib/python3.5/site-packages/readthedocs_ext/readthedocs.py:14: RemovedInSphinx40Warning: sphinx.builders.html.SingleFileHTMLBuilder is deprecated. Check CHANGES for Sphinx API modifications.
  from sphinx.builders.html import (DirectoryHTMLBuilder, SingleFileHTMLBuilder,
```

**Comment by humitos** [comment]
The problem is in the matplotlib sphinx extension that is not compatible with Sphinx 3.x.

```
  File "/home/docs/.pyenv/versions/3.5.7/lib/python3.5/site-packages/matplotlib/sphinxext/plot_directive.py", line 262, in setup
    app.add_directive('plot', plot_directive, True, (0, 2, False), **options)
TypeError: add_directive() got an unexpected keyword argument 'width'
```

**Comment by drewejohnson** [comment]
Interesting. These warnings don't appear when I build locally with sphinx 3.x and matplotlib 3.x, but I don't have the readthedocs builder. When I run `sphinx-build -T -W -E -b html . _build`, I don't see those errors. There are some other warnings that I've fixed and not pushed at the moment. But I am able to have a clean build.

I will pin our sphinx version < 3.0 in our docs/requirements.txt file and see how that works

**Comment by drewejohnson** [comment]
That seems to have done the trick! [Success](https://readthedocs.org/projects/serpent-tools/builds/10881163/)

Thank you
