### ISSUE TITLE
Can't install packages via conf.py

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#6919]
```
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
```

Sudo also seems to not exist.

Using the following script
```
if os.environ.get("READTHEDOCS"):
    # Tries to grab draw.io deb
    drawio_download = \
        subprocess.run(["wget", "-O", "drawio.deb",
                        "https://github.com/jgraph/drawio-desktop/releases/download/v12.6.5/draw.io-amd64-12.6.5.deb"])

    if drawio_download.returncode == 0:
        # If we got the draw.io deb, install it, and xvfb to run headless
        drawio_install = subprocess.run(["apt-get", "install", "-qy", "--force-yes", "libasound2",
                                         "./drawio.deb", "xvfb"])
        print("Dependencies Installed" if drawio_install.returncode == 0 else "Error Installing Dependencies")
    else:
        print("Error Downloading Dependencies")
```

**Comment by Daltz333** [comment]
We have some special dependencies 
```
inkscape
drawio
```
that aren't included in RTD

**Comment by Daltz333** [comment]
It looks like this may be because the docker packages are not ran with the root user.

**Comment by Daltz333** [comment]
Conda is an option, but the packages I want to use aren't on there. (drawio and inkscape)

**Comment by humitos** [comment]
Hi @Daltz333! We don't officially support installing arbitrary packages at build time. There are some people doing similar things in the `conf.py` but we don't recommend it and we can't guarantee that this will keep working in the future.

I saw that you also created an issue at https://github.com/readthedocs/readthedocs-docker-images/issues/131. That's basically the way we install packages in our Docker images. As these packages affect _all the builds_ we try to analyze if the package is a good candidate or not.

Summarizing, there is no workaround for this at the moment more than continue talking about these packages in the other issue you have created.

**Comment by humitos** [comment]
I'm closing this issue for now since we don't support installing packages using `apt-get` or other mechanisms. We should concentrate in the issue opened in the other repository, tho. Thanks!

**Comment by humitos** [comment]
This is currently possible by using `build.apt_packages` in the config file. See https://docs.readthedocs.io/en/stable/config-file/v2.html#build-apt-packages
