### ISSUE TITLE
How to enable query parameters in redirects?

### ISSUE THREAD

**Issue by mgeier** [readthedocs/readthedocs.org#6922]
I don't really understand how any of this works under the covers, but since  #5081 has been merged this should be supported, right?

For example, I have set the default version of my project to `0.6.0`, so it correctly redirects https://nbsphinx.readthedocs.io/ to https://nbsphinx.readthedocs.io/en/0.6.0/.

However, when I use the search URL with a query parameter, the parameter is somehow lost in redirection:

## Expected Result

https://nbsphinx.readthedocs.io/search.html?q=readthedocs should get redirected to https://nbsphinx.readthedocs.io/en/0.6.0/search.html?q=readthedocs

## Actual Result

https://nbsphinx.readthedocs.io/search.html?q=readthedocs gets redirected to https://nbsphinx.readthedocs.io/en/0.6.0/search.html

**Comment by stsewd** [comment]
This looks like a regression from our new proxy server

**Comment by ericholscher** [comment]
@mgeier What is the redirect that you have configured on your project for this case?

**Comment by ericholscher** [comment]
We figured out the issue, and should have a patch deployed next week.

**Comment by stsewd** [comment]
This is out now, you may still see https://nbsphinx.readthedocs.io/search.html?q=readthedocs not redirecting properly bc of your browser cache. Other works https://nbsphinx.readthedocs.io/search.html?q=testing
