### ISSUE TITLE
"Edit on Github" link broken by annotated tag

### ISSUE THREAD

**Issue by gboeing** [readthedocs/readthedocs.org#6932]
## Details

* Read the Docs project URL: https://osmnx.readthedocs.io/en/stable/
* Build URL (if applicable): https://github.com/gboeing/osmnx/
* Read the Docs username (if applicable): gboeing

## Expected Result

The "edit on Github" link at the top-right of the stable docs should point to the latest release.

## Actual Result

The [link](https://github.com/gboeing/osmnx/blob/685b9d0c7aac56ccd0ef3259515aa8404d254056/docs/source/index.rst) is broken. The problem seems to be how readthedocs uses the annotated tag that denotes the release. The link generated by readthedocs points to checksum `685b9d0` which is just an annotated tag that points to commit `902461a`. You can see this here:

```
$ git show 685b9d0c7aac56ccd0ef3259515aa8404d254056
tag v0.12
Tagger: gboeing <boeing@usc.edu>
Date:   Fri Apr 10 11:09:25 2020 -0700

v0.12

commit 902461ab8eb668732fa025c670057662fdd22039 (tag: v0.12)
Merge: bb1ef92 5ec6c2b
Author: Geoff Boeing <gboeing@users.noreply.github.com>
Date:   Fri Apr 10 11:06:56 2020 -0700

    Merge pull request #420 from gboeing/release
    
    v0.12 release
```

The [link](https://github.com/gboeing/osmnx/blob/685b9d0c7aac56ccd0ef3259515aa8404d254056/docs/source/index.rst) that readthedocs generates points to the annotated tag checksum, but that just leads you to a 404 page because you cannot browse at that point on Github. You [can](https://github.com/gboeing/osmnx/blob/902461ab8eb668732fa025c670057662fdd22039/docs/source/index.rst) only browse at the commit that the annotated tag points to. 

Related info from the [git docs](https://git-scm.com/book/en/v2/Git-Basics-Tagging):

> Git supports two types of tags: lightweight and annotated.
> 
> A lightweight tag is very much like a branch that doesn’t change — it’s just a pointer to a specific commit.
> 
> Annotated tags, however, are stored as full objects in the Git database. They’re checksummed; contain the tagger name, email, and date; have a tagging message; and can be signed and verified with GNU Privacy Guard (GPG). It’s generally recommended that you create annotated tags so you can have all this information

**Comment by gboeing** [comment]
May be related to #1820 and #3302

**Comment by gboeing** [comment]
This same broken-link problem is happening in other packages' stable docs, such as geopandas: https://geopandas.readthedocs.io/en/stable/ cc @jorisvandenbossche @martinfleis

**Comment by stsewd** [comment]
This is a regression from https://github.com/readthedocs/readthedocs.org/pull/6651

`git.TagReference._iter_packed_refs` returns `('685b9d0c7aac56ccd0ef3259515aa8404d254056', 'refs/tags/v0.12')` and `tag.commit` returns the correct commit. I'll dig if there is a way around without having to revert that PR.

**Comment by stsewd** [comment]
@gboeing the fix should be out tomorrow, you'll need to trigger a new build to your project in order to refresh the tags.

**Comment by gboeing** [comment]
Thanks!

**Comment by stsewd** [comment]
This is deployed now, annotated tags are working. I triggered a build for your project and geopandas. Make sure to do a hard refresh (ctrl + f5) when checking.

Anyone else hitting this, you need to trigger a build to latest, the commits should update automatically after that.

**Comment by gboeing** [comment]
Confirmed working now. Thanks.
