### ISSUE TITLE
Add support for custom sitemap.xml generated by the user

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#6938]
Our current `sitemap.xml` covers the most basic case. Although, there are users with other needs that require a more customized sitemap.xml.

We should implement the same mechanism that we do for custom `404.html`, where we provide the most basic one (Maze found) with the ability to change it by adding your own `404.html` to the output generated by Sphinx.

So, we could check first for `sitemap.xml` in the default version and serve that one as is if it exists. Here, extensions like [`sphinx-sitemap`](https://github.com/jdillard/sphinx-sitemap) may be a great help for the user.

This would be a better direction (an easier to implement) than lock all the users to have exactly the same sitemap.xml.

Reference: #6903 #5391 #6841

**Comment by eliasdabbas** [comment]
I just tried it, looks good but doesn't produce the `<lastmod>` tag :) 
There is an [open issue for it](https://github.com/jdillard/sphinx-sitemap/issues/3)...

**Comment by humitos** [comment]
I just realized that having the possibility to customize the `robots.txt`, you can change the `Sitemap:` entry in that file to point the robots to a customized `sitemap.xml` if you prefer. This does not fix this issue, but at least it's a _workaround_.

**Comment by eliasdabbas** [comment]
This is not a workaround. It's _the_ more comprehensive solution actually :) 

Customization of crawling happens in `robots.txt` where you signal to different bots different rules, link to sitemaps, exclude URL patterns, set crawl delays, etc. And sitemaps are simple lists of URLs with pretty much no functionality other than informing search engines about the URLs and some meta data. 

So, my updated recommendation is to include all the URLs in the sitemap, while giving users the option to customize the `robots.txt` file. 

I shared a suggested approach in #6903 
Please let me know if that makes sense, and if you have any other thoughts.

**Comment by Pradhvan** [comment]
@humitos if no one is working on this? I would love to pick this up. 😄

**Comment by humitos** [comment]
@Pradhvan thanks for your interested in here! Yeah, considering that we already support custom `robots.txt` and that you can change the `sitemap.xml` location from there, I don't think this issue is still relevant. In the end, if you want a custom sitemap right now, you can just modify the robots and use a third-party extension. I think there is no need to add another feature to RTD to do exactly the same.

I'm closing this issue for now and we can re-visit if someone comes with more strong opinions about why this is needed and using the robots.txt file is not enough.
