### ISSUE TITLE
enable billing annually rather than monthly

### ISSUE THREAD

**Issue by bowenli86** [readthedocs/readthedocs.org#6943]
## Details

read the docs should be able to bill users annually rather than monthly. I have to keep track of lots of receipts over the time, which is quite annoying

## Expected Result

read the docs should be able to bill users annually rather than monthly. 

## Actual Result

read the docs bill users monthly.

**Comment by humitos** [comment]
Hi @bowenli86! Do you refer to Gold Membership?

**Comment by bowenli86** [comment]
> Hi @bowenli86! Do you refer to Gold Membership?

Hi @humitos yes!

**Comment by ericholscher** [comment]
This is a duplicate of #6279. We can track it there.
