### ISSUE TITLE
Create Project API returns HTTP 500

### ISSUE THREAD

**Issue by Limonkufu** [readthedocs/readthedocs.org#6947]
## Details
I want to create a project with API v3 but it is giving me 500 Internal Error.

I have tried the example here: https://docs.readthedocs.io/en/stable/api/v3.html#project-create

* Read the Docs project URL: -
* Build URL (if applicable): -
* Read the Docs username (if applicable): limonkufu

## Expected Result

Successfully created project

## Actual Result

HTTP 500 Internal Server Error: Fail. Check back in a bit!

**Comment by humitos** [comment]
Thanks for the report. It seems that it's returning 500 when the `slug` already exists. What's the project's slug you are trying to create?

**Comment by Limonkufu** [comment]
That was one of the problems actually, there is no option to offer slug with the request so I am guessing it is trying to deduce it from the name.

This was the body I was sending:

```
{
    "name": "Test Project",
    "repository": {
        "url": "https://gitlab.com/limonkufu/test-project.git",
        "type": "git"
    },
    "homepage": "http://test-limonkufu.readthedocs.io/",
    "programming_language": "py",
    "language": "en"
}
```

I tried it again with the name set to `Test Project Limonkufu` and it got created succesfully.

**Comment by humitos** [comment]
Yes. The `slug` is deduced from the `name`. I followed the same idea from when importing manually https://readthedocs.org/dashboard/import/manual/

The name `Test Project Limonkufu` will end up with the slug `test-project-limonkufu`.
