### ISSUE TITLE
Adding Turkish Translations to the readthedocs.org and the projects' pages

### ISSUE THREAD

**Issue by BouRock** [readthedocs/readthedocs.org#6961]
Hi,
I completed Turkish translation of Read the Docs many times ago and I am still waiting to add to the site and projects' pages. Could you please add the translations to test the strings live. Also if you add the turkish language option to Transifex to translate "Turkish" word, I really appreciate it.

Regards,
Burak

**Comment by BouRock** [comment]
So when will be done?

**Comment by stsewd** [comment]
@BouRock thanks for the translations, we don't have a timeline for this at the moment.

**Comment by BouRock** [comment]
I understand. Your choice. Good luck.
