### ISSUE TITLE
Article snippet in search is executing HTML

### ISSUE THREAD

**Issue by lmeerwood** [readthedocs/readthedocs.org#6968]
## Details

* Read the Docs project URL: https://react-jsonschema-form.readthedocs.io/en/latest/search.html?q=fields
* Build URL (if applicable): Not Applicable
* Read the Docs username (if applicable): Not Applicable

## Expected Result

Article snippet shows small extract of article, text only.

## Actual Result

Article snippet shows small extract of article, rendering the `input` code as an actual input box. I'm fairly certain this isn't supposed to happen.

![image](https://user-images.githubusercontent.com/6085575/80334047-61c39880-8893-11ea-8d96-50e8ee58f1bf.png)

**Comment by stsewd** [comment]
@lmeerwood looks like you are using mkdocs, we don't provide server based search for mkdocs yet (#6937). So this is a mkdocs bug. If you don't see the same result locally, make sure you are using the same mkdocs version on rtd https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

**Comment by lmeerwood** [comment]
@stsewd, understood. I just came across it in a site I was visiting and thought I'd report it just in case. Cheers.
