### ISSUE TITLE
[SOLVED] Issues when installing self hosted instance.

### ISSUE THREAD

**Issue by pirona** [readthedocs/readthedocs.org#6974]
## Details

* Read the Docs project URL: not applicable
* Build URL (if applicable): not applicable
* Read the Docs username (if applicable): not applicable

## Expected Result

Working self-hosted instance

## Actual Result

I'm following this tutorial https://docs.readthedocs.io/en/stable/custom_installs/local_rtd_vm.html to install a self-hosted instance for my company. We have our own gitlab, so it's only logical to have this on our own servers.

When I have to install requirements, I'm meeting this issue : 

`Collecting django==2.2.12 (from -r requirements/pip.txt (line 6))
  Could not find a version that satisfies the requirement django==2.2.12 (from -r requirements/pip.txt (line 6)) (from versions: 1.1.3, 1.1.4, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 1.4.21, 1.4.22, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.6.11, 1.7, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.8a1, 1.8b1, 1.8b2, 1.8rc1, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.10, 1.8.11, 1.8.12, 1.8.13, 1.8.14, 1.8.15, 1.8.16, 1.8.17, 1.8.18, 1.8.19, 1.9a1, 1.9b1, 1.9rc1, 1.9rc2, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.9.10, 1.9.11, 1.9.12, 1.9.13, 1.10a1, 1.10b1, 1.10rc1, 1.10, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.10.6, 1.10.7, 1.10.8, 1.11a1, 1.11b1, 1.11rc1, 1.11, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.11.5, 1.11.6, 1.11.7, 1.11.8, 1.11.9, 1.11.10, 1.11.11, 1.11.12, 1.11.13, 1.11.14, 1.11.15, 1.11.16, 1.11.17, 1.11.18, 1.11.20, 1.11.21, 1.11.22, 1.11.23, 1.11.24, 1.11.25, 1.11.26, 1.11.27, 1.11.28, 1.11.29)
No matching distribution found for django==2.2.12 (from -r requirements/pip.txt (line 6))`

I noticed if I switch to python3, I'm able to meet requirements but I experience later some issues : some pages of my instance send errors : 
- impossible to create , erase, modifiy a project (tried the demo project)
Error:

`Request Method: | POST
-- | --
http://myserver.mydomain.tld:8000/wipe/demo/latest/
2.2.12
SyntaxError
invalid syntax (redis.py, line 21)
<frozen importlib._bootstrap> in _call_with_frames_removed, line 219
/usr/bin/python3
3.7.3
['/usr/local/lib/python3.7/dist-packages/git/ext/gitdb',  '/readthedocs/readthedocs.org',  '/usr/lib/python37.zip',  '/usr/lib/python3.7',  '/usr/lib/python3.7/lib-dynload',  '/usr/local/lib/python3.7/dist-packages',  '/usr/lib/python3/dist-packages',  '/artis/readthedocs/readthedocs.org',  '/usr/local/lib/python3.7/dist-packages/gitdb/ext/smmap',  '/readthedocs/readthedocs.org']

`

Are the two related ? Can I really use python3 to install readthedocs ? 
I installed this on Debian 10, fresh install, the server is dedicated to this use.

Thanks ahead for your help.

**Comment by humitos** [comment]
Hrm... That guide looks outdated. It talks about Python2.7 setup which we do not support anymore. We should probably remove it completely.

You may be more interested on checking out https://docs.readthedocs.io/en/stable/development/install.html and https://docs.readthedocs.io/en/stable/development/standards.html instead which are more up to date.

**Comment by pirona** [comment]
Hello,

Thanks a lot for that.

I still have the second issue so I guess it wasn't related after all.
I loaded the mentioned test_data. they appear in my interface, but when I try to erase one, I'm thrown the same trace : 


``

Request Method: | POST
-- | --
http://documentation.srv.int.artis.fr:8000/admin/projects/project/
2.2.12
SyntaxError
invalid syntax (redis.py, line 21)
<frozen importlib._bootstrap> in _call_with_frames_removed, line 219
/home/artis/venv/bin/python
3.7.3
['/home/artis/venv/lib/python3.7/site-packages/git/ext/gitdb',  '/artis/readthedocs/readthedocs.org',  '/usr/lib/python37.zip',  '/usr/lib/python3.7',  '/usr/lib/python3.7/lib-dynload',  '/home/artis/venv/lib/python3.7/site-packages',  '/artis/readthedocs/readthedocs.org',  '/home/artis/venv/lib/python3.7/site-packages/gitdb/ext/smmap',  '/artis/readthedocs/readthedocs.org']

`

**Comment by pirona** [comment]
I'm not sure I'm skilled enough to do this. My other option is to search how to to distribute a sphinx documentation. Maybe this is wiser.

**Comment by ericholscher** [comment]
Yea, I'd recommend our hosted platform, no need to run anything yourself.

**Comment by pirona** [comment]
Self-hosting is an intern policy, so I cannot get over this. Nonetheless, I figured out that installing Sphinx and the ReadTheDocs theme would be enough for us.

Thanks for your help.
