### ISSUE TITLE
Protocol missing from context['downloads']?

### ISSUE THREAD

**Issue by mgeier** [readthedocs/readthedocs.org#6977]
I would like to create a link in a custom HTML template to the PDF generated on RTD.

RTD populates the `'downloads'` key in the HTML context, but the URLs seem to be missing the protocol part (e.g. `https:`).

Is this intentional?

Am I supposed to prepend `https:`?
Shall I just assume it's `https:` because it can never be `http:`?
Or can I get this information from somewhere else?

## Details

* Build URL: https://readthedocs.org/projects/nbsphinx/builds/10925639/

## Expected Result

```
    'downloads': [ 
    ("pdf", "https://nbsphinx.readthedocs.io/_/downloads/en/latest/pdf/"),
    ("html", "https://nbsphinx.readthedocs.io/_/downloads/en/latest/htmlzip/"),
    ("epub", "https://nbsphinx.readthedocs.io/_/downloads/en/latest/epub/"),
    ],
```

## Actual Result

```
    'downloads': [ 
    ("pdf", "//nbsphinx.readthedocs.io/_/downloads/en/latest/pdf/"),
    ("html", "//nbsphinx.readthedocs.io/_/downloads/en/latest/htmlzip/"),
    ("epub", "//nbsphinx.readthedocs.io/_/downloads/en/latest/epub/"),
    ],
```

**Comment by stsewd** [comment]
>  Or can I get this information from somewhere else?

Yeah, I'd recommend using our api v2 or v3. We kind of want to remove those things from the context #6712.

https://docs.readthedocs.io/en/stable/api/v2.html#api-version-detail
https://docs.readthedocs.io/en/stable/api/v3.html#version-detail

With api v2, you can query the downloads without using a token. With v3 you'll need to use a personal token (this means you need to do this with an env variable at build time so you don't leak your token).

Also, `//` means the URL will use the same protocol as the current page, so you can just use that if you want.

**Comment by mgeier** [comment]
I've put a question mark into the issue title for a reason ... turns out it's not missing!

>  `//` means the URL will use the same protocol as the current page, so you can just use that if you want.

I didn't know that, thanks for educating me!

I just tried it, and, as you say, it works perfectly fine without prepending `https:`.

> I'd recommend using our api v2 or v3. We kind of want to remove those things from the context #6712.

But that would mean I'd have to fetch the information with JavaScript, right?

I'd very much prefer to provide the PDF link even to people who have JavaScript disabled in their browser.

AFAICT, #6712 is about removing the (potentially huge) list of `versions`. I'm fine with that.
But could you please keep the (very short) list of `downloads`?

**Comment by stsewd** [comment]
> But that would mean I'd have to fetch the information with JavaScript, right?

Yes

> But could you please keep the (very short) list of downloads?

I've linked your comment on the issue to take into consideration.

**Comment by mgeier** [comment]
Cool, thanks a lot!
