### ISSUE TITLE
Missing version selection

### ISSUE THREAD

**Issue by houayang** [readthedocs/readthedocs.org#6979]
## Details

* Read the Docs project URL: https://docs.opendaylight.org/en/latest/

## Expected Result

Footer is expected to have an option to switch from latest to other releases.

## Actual Result

Footer version selection is missing.

**Comment by ericholscher** [comment]
Hi,

This is likely because of a configuration on your side. You are proxying to us from some server:

```
-> dig +short docs.opendaylight.org
d9tk6tch5uznr.cloudfront.net.
```

We don't recommend this configuration, and suggest you use our supported setup: https://docs.readthedocs.io/en/latest/custom_domains.html

**Comment by houayang** [comment]
We currently proxy for [docs.onap.org](https://docs.onap.org/) as well, and version selection is working as expected.

```
dig +short docs.onap.org
d3kgktjkvnp4zz.cloudfront.net.
```

**Comment by ericholscher** [comment]
That request also 404's:

```
-> curl -IL "https://docs.onap.org/_/api/v2/footer_html/?callback=jQuery321017419822411307884_1588100712083&project=onap&version=elalto&page=index&theme=sphinx_rtd_theme&format=jsonp&docroot=%2Fdocs%2F&source_suffix=.rst&_=1588100712084"
HTTP/2 404
```

**Comment by stsewd** [comment]
> We currently proxy for docs.onap.org as well, and version selection is working as expected.

What you are seeing there is a "dummy" footer, not the one fetched from our API with up to date information.

**Comment by houayang** [comment]
Removing proxy fixed the issue. Thanks!
