### ISSUE TITLE
Custom domain error

### ISSUE THREAD

**Issue by EDI-N** [readthedocs/readthedocs.org#6980]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/docs-ua/

## Expected Result

Hello! Please help understand what's goes wrong. Change nothing in our settings and from 19:47 get cycling redirects from **wiki.edi-n.com**

What it can be?

**Comment by ericholscher** [comment]
It looks like you are proxying to us:

```
-> dig +short wiki.edi-n.com
91.194.88.11
```

What is your proxy sending?

**Comment by ericholscher** [comment]
I turned off the `https` setting on your domain, and now its working. I'm guessing your proxy was trying to follow the redirect you were sending to our backend.

**Comment by ericholscher** [comment]
I recommend you remove your proxy and use a custom domain setup as we document here: https://docs.readthedocs.io/en/latest/custom_domains.html

**Comment by EDI-N** [comment]
Thank you. Now we use proxy (haproxy v1.8) and redirect all requests to readthedocs.io:80
And now those setting are bad? And better without proxy?

**Comment by ericholscher** [comment]
@EDI-N yes, if you point directly to us with DNS there is much less chance of something breaking.

**Comment by EDI-N** [comment]
Thank you, Eric
