### ISSUE TITLE
Move automatic Docker limits back to a setting

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#6983]
We have different requirements for limits between community and commercial -- namely we allow a lot more build time by default on commercial. The most explicit version of this would be using the same logic to check memory, but pushed into a `@property` setting in community/commercial.

Because of the removal of all docker limit settings between community/commercial/ops, the default build time on commercial has dropped.

Also, there is a lot of information squirreled away in the DMI information:
`sudo find /sys/devices/virtual/dmi/id/ -type f | sudo xargs -n1 -t cat `

This could be of use if we want to detect default settings only when running in production perhaps. Having explicit limits on readthedocsinc.settings.base might be enough.

This was discovered in #6982 

- [ ] Revert the constant usage in project.models in #6982 back to a setting
- [ ] Revert other places where a setting was dropped for a constant
- [ ] Add commercial setting with longer build time

**Comment by humitos** [comment]
> The most explicit version of this would be using the same logic to check memory, but pushed into a `@property` setting in community/commercial.

It seems this is already done in https://github.com/readthedocs/readthedocs.org/pull/7023/

Now it's dynamically calculated based on RAM and using a coefficient to calculate the time. There were some adjustment to that logic over time and I think that it's working as we want now: higher memory and time on commercial than on community.
