### ISSUE TITLE
Request to enable CONDA_APPEND_CORE_REQUIREMENTS feature flag for project cocotb

### ISSUE THREAD

**Issue by eric-wieser** [readthedocs/readthedocs.org#6989]
Filing an issue as requested [here](https://docs.readthedocs.io/en/stable/guides/feature-flags.html#feature-flags).

Brought on by https://github.com/cocotb/cocotb/pull/1706, and a stop gap until #6965 is merged and released.

**Comment by humitos** [comment]
Hey @eric-wieser! I just enabled this in your project. Let me know if that worked as you expected.

**Comment by eric-wieser** [comment]
Thanks @humitos.

Is there any way to see the output of `conda env create`? Unfortunately the `--quiet` flag hides all of the information about which package versions were installed.

**Comment by humitos** [comment]
Hrm... I don't think we currently have a way to change that :disappointed:

**Comment by eric-wieser** [comment]
Is it done that way because the logs are huge and usually useless?

**Comment by humitos** [comment]
I'd say yes. In particular because of the progress bar that makes all the output to be broken anyways.

```
-q, --quiet           Do not display progress bar.
```

It seems there is no way to show the useful information without showing the progress bar.

**Comment by eric-wieser** [comment]
Would it be possible to run `conda list` as an extra command then?

**Comment by humitos** [comment]
I suggested that already at https://github.com/readthedocs/readthedocs.org/issues/5006#issuecomment-453824161 but didn't succeed :smile:
