### ISSUE TITLE
German Translation of "Triggered" - while a task is running - is bad.

### ISSUE THREAD

**Issue by nerdoc** [readthedocs/readthedocs.org#6998]
## Details

The translation of "Triggered" is bad. Although "Ausgeführt" is a correct translation of "Triggered", in this meaning it has a sort of "past" meaning, as it would have already been done in the past.
When a task is triggered, in German this would rather be translated with "Ausgelöst" or even better "Angestoßen". Another possibility would be "Begonnen" (begun).
I couldn't find a transifex or other project where RTD keeps it's translations? So Issue here.

![grafik](https://user-images.githubusercontent.com/2955584/80649222-24ad0100-8a61-11ea-994d-7b13b13a4011.png)

## Expected Result

I want to be informed if a task has been triggered, while it is running.

## Actual Result

The German trans says "Ausgeführt" which also means something like "done".

**Comment by stsewd** [comment]
Please see https://docs.readthedocs.io/en/stable/contribute.html#helping-on-translations
