### ISSUE TITLE
Translation Overview not showing projects.

### ISSUE THREAD

**Issue by JackCrispy** [readthedocs/readthedocs.org#7003]
## Details

* Read the Docs project URL:  https://wiki.statusbot.xyz/
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

The project dropdown should fill with all the projects I own.

## Actual Result

No projects show in the drop down.

**Comment by stsewd** [comment]
> The project dropdown should fill with all the projects I own.

Can you be more specific? If you mean the version selector, it only shows the versions for the current project, it doesn't show all your projects.

**Comment by JackCrispy** [comment]
ON the project page i have my project, i'm trying to add translating but when i click the dropdown it doesn't show any projects on the dropdown.

**Comment by stsewd** [comment]
@JackCrispy that list only shows projects where you are an owner.

**Comment by JackCrispy** [comment]
I am the owner.

**Comment by humitos** [comment]
@JackCrispy what's your project's URL and what's the project's URL you are trying to add as translation?

**Comment by JackCrispy** [comment]
The issue still persist, but I’m no longer using read the docs. Thanks for the help.

- plus I never tried to add a project URL as a translstion
The dropdown just won’t show my project, although I’m owner.
