### ISSUE TITLE
Remove useless path from output build commands

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#7004]
Instead of

```
 /home/docs/checkouts/readthedocs.org/user_builds/godot/envs/latest/bin/python -m pip install --exists-action=w --no-cache-dir -r requirements.txt 
```

![Screenshot_2020-04-30_11-00-38](https://user-images.githubusercontent.com/244656/80692432-d8e67000-8ad1-11ea-83e1-45cbdf7285bf.png)

We should have these commands listed as

```
python -m pip install --exists-action=w --no-cache-dir -r requirements.txt 
```

Reference https://github.com/readthedocs/readthedocs.org/pull/6992#issuecomment-621247945

**Comment by ericholscher** [comment]
@agjohnson if there is an easy way to backport this, I'd _love_ to ship it next week. It's bothered me for a long time :)

**Comment by stsewd** [comment]
We can also edit our commands to use the correct cwd when executing commands, so we only pass the relative path.

**Comment by agjohnson** [comment]
I did this display side in a hacky way, it's nothing reusable. Our solution would need to work for both our database and cold storage backed data, so it might make sense to continue doing this display side. Either way, I'm investing my time on the new templates, I don't want to worry about backporting any work into our current UI.

**Comment by agjohnson** [comment]
Basically what I did here was highly naive:

```js
const re_command_trim = /(\/usr\/src\/app|\/home\/docs)\/checkouts\/readthedocs.org\/user_builds\/[^\/]+\/[^\/]+\/[^\/]+\//g;
let command = build_command.command.replace(re_command_trim, "");
```

This covers both build cold storage and database entries, so unfortunately seems like the best place to do this? Anyways, this is already done in the new UI, and I'm not sure I have much to add to the hack above. We could remove the path from the commands as we are saving them if we want, but this hack will have to remain in place because of old data.

**Comment by humitos** [comment]
This was done at https://github.com/readthedocs/readthedocs.org/pull/9831
