### ISSUE TITLE
Automatic build on pull request for Pyresample

### ISSUE THREAD

**Issue by adybbroe** [readthedocs/readthedocs.org#7008]
## Details

* Read the Docs project URL: https://pyresample.readthedocs.io/
* Build URL (if applicable):
* Read the Docs username (if applicable): adybbroe

## Expected Result

I would love to have RTD automatically building pull requests on our Pytroll project *Pyresample*

## Actual Result

*A description of what actually happened*

**Comment by humitos** [comment]
It's done. Thanks.

Let us know if there is a problem with this.

Next time, please, contact us via our support email (support AT readthedocs DOT org). Thanks!

**Comment by adybbroe** [comment]
Many thanks @humitos ! 
And, yes, will try remember that! Tried remembering what I did last time, and found the issue I made for Pyspectral...

**Comment by humitos** [comment]
Yes, sorry. Don't worry. :+1:  We changed the process because we realized that making this request on public does not offer nothing useful to other people. So, we decided that it was better via private email

**Comment by adybbroe** [comment]
@humitos I send support a mail, as I still don't see RTD builds being triggered. Something I have missed?

**Comment by stsewd** [comment]
@adybbroe please check https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html#troubleshooting

**Comment by adybbroe** [comment]
Thanks @stsewd I think I did. But my problem was that I failed resyncing the webhooks for some strange reason. One of the other maintainers of Pyresample managed to do it, and then after closing and re-opening the PR we now see the RTD being triggered nicely. This is really a nice feature, thanks!
