### ISSUE TITLE
Intentionally degrade SEO for non-latest stable docs

### ISSUE THREAD

**Issue by choldgraf** [readthedocs/readthedocs.org#7010]
## Details

I have noticed a common problem across *many* projects that are hosted with readthedocs, particularly those that have been around for quite some time, which is that *older* versions of the documentation often show up *first* in search results. 

Here is a recent example I ran into with Sphinx's own docs:

![image](https://user-images.githubusercontent.com/1839645/80999160-12ccb480-8df9-11ea-8bd7-c07178209a3b.png)

As you can see, the 1.5.6 Sphinx documentation, which is many many versions old by now, is the first result. It also seems problematic that the latest *stable* version is not listed at all, and instead we only find a 4.0 dev version of the pages as well.

So here's my question: **would it be possible to add an option to intentionally degrade the SEO for non-latest stable (or `latest/`) documentation builds?**

I think that this could help improve the confusion around projects that have really old documentation show up (it is helpful to have the "these aren't the latest docs" flags, but I find it is still quite confusing for newcomers to follow them)

**Comment by stsewd** [comment]
Tomorrow we will be releasing "hidden versions" https://github.com/readthedocs/readthedocs.org/pull/6792 https://docs.readthedocs.io/en/latest/versions.html#states

That should help with this problem.

**Comment by choldgraf** [comment]
well that was a fast turnaround on that feature 😆 


thanks for the link - I agree that definitely should help. when a branch is "inactive" will it also stop showing up in google?

**Comment by stsewd** [comment]
When a version is inactive, the docs are deleted, so I guess google will stop to show those results?

**Comment by choldgraf** [comment]
oh sorry, I meant "hidden", not inactive

**Comment by stsewd** [comment]
When a version is hidden it's listed as Disallow in a `robots.txt` file, that should stop google of indexing those pages. If those pages are already indexed, looks like google will eventually stop to show them https://webmasters.stackexchange.com/questions/65184/will-the-already-indexed-urls-be-removed-if-i-use-a-robots-txt-for-my-site

**Comment by choldgraf** [comment]
awesome - well it sounds like I can close this and you all deserve a 🍺 :-)

**Comment by humitos** [comment]
> well it sounds like I can close this and you all deserve a beer :-)

Happy to share it with you... after the global :earth_americas: pandemic :mask: , of course :smile:
