### ISSUE TITLE
Build error with build id #10970188

### ISSUE THREAD

**Issue by flyleaf91** [readthedocs/readthedocs.org#7016]
## Details:

* Project URL: https://readthedocs.org/projects/embed_linux_tutorial/
* Build URL(if applicable): https://readthedocs.org/projects/embed-linux-tutorial/builds/10970188/
* Read the Docs username(if applicable): embedfire

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by lukasturcani** [comment]
Same issue on my project, build id: 10970197.

**Comment by rmorshea** [comment]
Same: https://readthedocs.org/projects/idom/builds/10970256/

**Comment by lukasturcani** [comment]
Mine seems to be working now.

**Comment by humitos** [comment]
It seems it's working now. Looks like a temporal issue on RTD --we received a page today about at that time. Please, keep us posted here if you keep seeing this error.
