### ISSUE TITLE
Build error with build id #10970377

### ISSUE THREAD

**Issue by timpitman** [readthedocs/readthedocs.org#7018]
## Details:

* Project URL: https://readthedocs.org/projects/stellargraph/
* Build URL(if applicable): https://readthedocs.org/projects/stellargraph/builds/10970377/
* Read the Docs username(if applicable): timpitman

## Expected Result

We've had a series of failed builds for our project today; earlier in the day they were working.  We did try to reset the build environment too, however that hasn't helped.

## Actual Result

Example of one of the failed builds (that failed in 2 seconds):
```
Read the Docs build information
Build id: 10970377
Project: stellargraph
Version: 1513
Commit: ed3995c89bea54914cbc5376f8e614e55227adaa
Date: 2020-05-05T07:30:04.430979Z
State: finished
Success: False
```

**Comment by humitos** [comment]
I seems it working now. We received a page today about that time. It was a temporal issue. Please, keep us posted if this is still happening to you. Thanks!

**Comment by timpitman** [comment]
Thanks @humitos! It appears to be resolved.
