### ISSUE TITLE
Running out of memory during `conda env create`

### ISSUE THREAD

**Issue by jakirkham** [readthedocs/readthedocs.org#7036]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/dask-cuda
* Build URL (if applicable): https://readthedocs.org/projects/dask-cuda/builds/10984836

## Expected Result

Docs complete build.

## Actual Result

It appears the doc build is unable to install the dependencies needed for the build due to a memory limitations.

```
conda env create --quiet --name latest --file conda/environments/builddocs_py37.yml
Collecting package metadata (repodata.json): ...working... Killed


Command killed due to excessive memory consumption
```

**Comment by ericholscher** [comment]
@jakirkham sorry about this -- we had a bug in our conda routing code. It should be fixed now.

**Comment by stsewd** [comment]
Build is passing now! https://readthedocs.org/projects/dask-cuda/builds/10984961/

**Comment by jakirkham** [comment]
No need to be sorry. In fact thanks for the quick turnaround! 😄

**Comment by quasiben** [comment]
Thank you all!
