### ISSUE TITLE
Remove design docs from docs

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#7045]
While searching our prod docs, I've been frequently getting first hits at our design docs. For instance, the first hit for query "teams" is a design doc for moving teams to community. As a user, this would be a pretty bad experience, and in a lot of cases would be confusing for the customer/user.

Ideally, our developer docs should be completely separate from our user docs, as the overlap between contributors and users is not strong. These are the most obvious parts to move out, so perhaps a good place to start the project.

Options here might be:

- [ ] Conditionally exclude developer doc source files from prod docs build. Build a separate project will all the docs?
- [ ] Move developer docs to a different doc path (or repository?). Ideally, we have `docs/` and a `developer_docs/` or something.

**Comment by humitos** [comment]
@agjohnson do you think this still worth the effort now that we have ranked down these pages?

https://github.com/readthedocs/readthedocs.org/blob/9e7ba81d4defce300be7d6ca40adbee454a241ca/.readthedocs.yml#L16-L17

**Comment by agjohnson** [comment]
Yes, I feel we should drop them. For a few reasons: they aren't helpful to end users, they aren't real documentation, and they go out of date quick because they weren't meant to be living documentation, just a way to start and hold a discussion around changes/features/etc.

I'd support at least not building them in our docs with a Sphinx excludes -- the end format is not something we use and we mostly just use the documentation as a proxy for having a discussion about the topics.

Ideally, these discussions probably exist somewhere else. Our policy docs are similar, and perhaps "policy" docs should become "discussion" docs, if that is a workflow that we find useful (i definitely find document -> discuss/fork/review -> update document to be a great workflow for distilling the important points of a conversation, so +1 on using this pattern more). However, there are some small benefits to keeping these docs in the same repo that we are updating, but I suspect these cases are limited.

**Comment by ericholscher** [comment]
Can we call this solved with the split to https://dev.readthedocs.io/en/latest/?

**Comment by humitos** [comment]
What about adding `noindex` to the design docs pages? See https://developers.google.com/search/docs/advanced/crawling/block-indexing

**Comment by agjohnson** [comment]
We could also author these in `meta`, to hide them away from users and user/dev docs. These do sort of fit inside dev docs, but are usually some form for output from meetings and private discussions that we have, so don't seem super helpful as documentation artifacts.

**Comment by humitos** [comment]
I think this problem is solved already with the split of `docs` and `dev` projects on Read the Docs.
