### ISSUE TITLE
Request apparently-abandoned project 'ops'

### ISSUE THREAD

**Issue by chipaca** [readthedocs/readthedocs.org#7053]
Hello,

I'm currently working on something we're calling "The Operator Framework", which you should be able to get via `pip install ops` as soon as we do a release (soon!).

Getting the API docs set up in rtd, I hoped I could use the same short name but it seems to be taken by what looks like an abandoned project. The github link doesn't work, and I don't see a way to contact the author via github or elsewhere.

Can I ask that you kick off the 'abandoned project' flow for this?

Thank you.

**Comment by davidfischer** [comment]
I sent a quick note to the maintainer asking if I can rename the project or whether they'd be willing to give the name up. I'm attempting to establish reachability (as defined in the [policy](https://docs.readthedocs.io/en/stable/abandoned-projects.html)). I have a note to check back in 6 weeks if nothing happens before then.

**Comment by chipaca** [comment]
I keep on coming back to check and having to re-do the maths, so for future me: that's 2020-07-03.

**Comment by chipaca** [comment]
Bump :slightly_smiling_face:

**Comment by davidfischer** [comment]
This old project is now considered abandoned and was renamed. Feel free to take that name.
