### ISSUE TITLE
Google analytics javascript code is generated locally, but not in prod

### ISSUE THREAD

**Issue by wrong-about-everything** [readthedocs/readthedocs.org#7058]
### Problem

I want to use Google analytics service. I got my analytics id and inserted it in `html_theme_options`. Then I run `make html`, open my project locally, and see generated javascript code for analytics in a bottom of each page, with preceding comment `<!-- Theme Analytics -->`. Then I `git add .` & `git commit` & `git push` all the changed files, go to [production docs](https://validol.readthedocs.io/en/latest/quick_start.html), and I don't see this code. I fail to find it in any other place either. My Google analytics account confirms that there is no traffic, but there is at least me :)

### Reproducible Project

Here is a [link to a repo conf file](https://github.com/wrong-about-everything/Validol/blob/master/docs/conf.py).

### Environment Info

- Python Version: 3.7.6
- Sphinx Version: 3.0.3
- RTD Theme Version: 0.4.3

**Comment by ericholscher** [comment]
I'm not sure how this would be set? Did you follow our guide here: https://docs.readthedocs.io/en/latest/guides/google-analytics.html
