### ISSUE TITLE
support toml config

### ISSUE THREAD

**Issue by ConorSheehan1** [readthedocs/readthedocs.org#7065]
### Feature request
Would it be possible to support toml config, rather than just yaml?

https://docs.readthedocs.io/en/stable/config-file/v2.html
Instead of only parsing `.readthedocs.yml`, could you support a section in `pyproject.toml`, like `[tool.readthedocs]`?

Maybe similar to how isort handles config?
https://github.com/timothycrosley/isort#configuring-isort

**Comment by stsewd** [comment]
I'd say we should just support one format and one name actually too, currently we support 4 names for the config file. If we ever change to parse the config file before cloning the repo that would make it harder/slow.

**Comment by stsewd** [comment]
We won't be supporting more formats here, it would introduce more complexity and dependencies to our code base with little gain.
