### ISSUE TITLE
Only show (or add option) search results for specific project, not all sub-projects.

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#7066]
frc-docs has the following structure setup

frc-docs
- frc-docs-es (Spanish sub-project)
- frc-docs-zh_CN (Chinese sub-project)
- more languages here

however, this greatly clutters up search
![image](https://user-images.githubusercontent.com/10674555/81727863-9751af80-9457-11ea-8f16-e8552c0e1371.png)

It would be fantastic if spanish search results only show up on the spanish sub-project. 

Offending URL: https://docs.wpilib.org/en/latest/search.html?q=getting+started&check_keywords=yes&area=default#

**Comment by stsewd** [comment]
Another way to avoid this is to mark those projects as translations rather than subprojects.

**Comment by stsewd** [comment]
For what you are asking, see https://github.com/readthedocs/readthedocs.org/issues/5966

**Comment by Daltz333** [comment]
I actually have both configured.

**Comment by Daltz333** [comment]
Is there a way to un-subproject a project without deleting and recreating the project?

**Comment by stsewd** [comment]
@Daltz333 yes, from the main project go to the admin tab, and thenin subprojects you can just delete the relationship, that won't remove your project (but it will break existing links).

**Comment by stsewd** [comment]
If you don't want to break those links, you'll need to create some redirects https://docs.readthedocs.io/en/stable/user-defined-redirects.html

**Comment by Daltz333** [comment]
Much appreciated, I'll go ahead and mark this as closed, but it would be great for additional documentation on sub-projects :)

**Comment by stsewd** [comment]
@Daltz333 what additional information should be added? We recently updated some of our docs, so maybe something that was missing is there now... But let us know so we can improve them

https://docs.readthedocs.io/en/stable/subprojects.html
