### ISSUE TITLE
autoclass documentation issue on web build

### ISSUE THREAD

**Issue by sparupat** [readthedocs/readthedocs.org#7072]
## Details
I am seeing issue with autoclass documentation on the web build. I was able to build the documentation locally and able to see the autoclass documentation without any issue. 

* Read the Docs project URL:
https://tensormonk.readthedocs.io/en/latest/modules/detection.html#id1

* Build URL: Did not see any errors in build logs
https://readthedocs.org/api/v2/build/11027961.txt

Conf.py and readthedocs.yml file links:

https://github.com/sparupat/TensorMONK/blob/master/docs/source/conf.py
https://github.com/sparupat/TensorMONK/blob/master/readthedocs.yml

I really appreciate your help in pointing the root cause of failure.

Local build snapshot:
<img width="726" alt="Screen Shot 2020-05-12 at 11 42 47 PM" src="https://user-images.githubusercontent.com/2997890/81769932-cc3c2180-94ac-11ea-977a-574869af8ff9.png">

**Comment by humitos** [comment]
> I am seeing issue with autoclass documentation on the web build.

What's the issue that you are seeing? I'm not sure to understand the report.

I can see the `AnchorDetector` at https://tensormonk.readthedocs.io/en/latest/modules/detection.html#tensormonk.detection.AnchorDetector

**Comment by sparupat** [comment]
@humitos Thanks a lot for the response. It looks like I was seeing the cached documentation on browser / server was rendering old html.

Marking the issue as closed.
