### ISSUE TITLE
Provide Github (etc) commit status for builds on branches / tags

### ISSUE THREAD

**Issue by Cadair** [readthedocs/readthedocs.org#7084]
This is not in relation to PR builds.

It would be really nice if after a build is triggered on a commit (i.e. a PR is merged or a tag pushed) if RTD sent a commit status back to the VCS site that triggered it. This would allow you to see the status of the RTD build along side all the other CI checks on that commit.

A bonus would be supporting the GitHub checks API to allow restarting the build etc.

**Comment by benjaoming** [comment]
Another point: A push can contain several commits. We always build the last commit.

**Comment by benjaoming** [comment]
New implementation looking good!

![image](https://github.com/readthedocs/readthedocs.org/assets/374612/95893048-58f0-4f4a-a5aa-1a288dd61d94)

![image](https://github.com/readthedocs/readthedocs.org/assets/374612/10e7e46d-a220-4c98-9885-d02667639aff)

Test with a build failure:

![image](https://github.com/readthedocs/readthedocs.org/assets/374612/ee0d868b-f049-4d69-9f34-08d06e63b2be)

Test with build success:

![image](https://github.com/readthedocs/readthedocs.org/assets/374612/4c142af7-cceb-4718-a0ea-eae6c1eb03fa)

**Comment by humitos** [comment]
I'm going to close this issue because we weren't able to prioritize in the past year and we are not planning to work on it soon. We can revisit in the future when working on expanding GitHub features.
