### ISSUE TITLE
View Docs button URL returns 404 as URL contains the `lang` component which is not on disk

### ISSUE THREAD

**Issue by Svenito** [readthedocs/readthedocs.org#7085]
## Details

Apologies if this isn't the right place for support, but I was unable to find anywhere else to ask for some help.

Running a local install of RTD 5.0.0 with custom readthedocs/build docker images

I have managed to get everything working up to the point where the builds are working and are being placed in the media directory, but I am getting a 404 because the build artefacts do not include the language folder, whereas the "view docs" button URL does include it.

"View Docs" button URL is : `docs/<project>/en/latest/`
Actual location is: `docs/<project>/latest`

Builds are ending up in `/var/www/html/media/html/<project>/latest` and can be browsed if I manually remove the `en` part of the URL

in my conf I have

```
MEDIA_ROOT = os.path.join("/var/www/html", 'media/')
MEDIA_URL = '/media/'
```

I've looked at the source and am unable to figure out why my build isn't ending up under and  `en` folder.

**Comment by humitos** [comment]
Hi! 5.0 does not support serving documentation from local disk anymore. We are using "El Proxito" application that serve the docs from the storage. You can check the documentation from https://docs.readthedocs.io/en/stable/development/standards.html

On the other hand, Read the Docs' core team does not help with support on custom installations. Please read our https://docs.readthedocs.io/en/stable/open-source-philosophy.html

**Comment by Svenito** [comment]
Ah ok, apologies, I hadn't seen the latter link. That's a fair statement. I'll look at solving this myself then.

**Comment by stsewd** [comment]
@Svenito also, if you are updating from a previous version, you can check our changelog for incompatible changes https://docs.readthedocs.io/en/stable/changelog.html#version-5-0-0
