### ISSUE TITLE
Gzipped files for download seem to be unzipped

### ISSUE THREAD

**Issue by mattpitkin** [readthedocs/readthedocs.org#7096]
## Details

* Read the Docs project URL: https://cwinpy.readthedocs.io/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable): mattpitkin

## Expected Result

I have various gzipped text files with the extension "txt.gz" in the documentation that can be downloaded (for example linked at the end of the second paragraph [here](https://cwinpy.readthedocs.io/en/latest/pe/pe.html#example-single-detector-data) or directly downloaded [here](https://cwinpy.readthedocs.io/en/latest/_downloads/87d6c629d92fa4bea4b9b0a56b59fc94/fine-H1-PULSAR08.txt.gz)). When someone downloads them they should get the gzipped file.

## Actual Result

When someone downloads the file it is actually unzipped although still retains the "txt.gz" extension.

**Comment by stsewd** [comment]
If you build locally with the same sphinx version used on rtd, are you able to reproduce it?

**Comment by mattpitkin** [comment]
My local build doesn't give unzipped files, but that's with sphinx 1.8.4 rather than v3.0.3 currently used on rtd. I'll upgrade and see if I get the same issue.

**Comment by mattpitkin** [comment]
I've upgraded to sphinx v3.0.3 and my local build doesn't give unzipped files.
