### ISSUE TITLE
Could not import extension sphinx_copybutton (exception: No module named 'sphinx_copybutton')

### ISSUE THREAD

**Issue by umeklinks** [readthedocs/readthedocs.org#7100]
Hi, I'm having an issue with the **`sphinx-copyButton`** extension when deploying on readthedocs.

I followed the procedure as stated on https://sphinx-copybutton.readthedocs.io/en/latest/ to install and configure it on the `conf.py`.

When I deploy my project locally using `make html` it works perfectly but when deploying over https://readthedocs.org/ it throws the error messages below.

```
Running Sphinx v1.8.5
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tryton-doc-text/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
ModuleNotFoundError: No module named 'sphinx_copybutton'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/tryton-doc-text/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tryton-doc-text/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 228, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tryton-doc-text/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/tryton-doc-text/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension sphinx_copybutton (exception: No module named 'sphinx_copybutton')

Extension error:
Could not import extension sphinx_copybutton (exception: No module named 'sphinx_copybutton')
```

This is my screenshot of the result when I run `make html` :

![copyButton](https://user-images.githubusercontent.com/13150442/82356536-9c84a080-99fb-11ea-9d1b-a1077b276056.png)

While deploying on readthedocs, it shows the error message stated above.

However, I was able to work around it with some information I got online. I now placed a `custom.js` alongside `custom.css` file in the `_static directory` and this worked perfectly on my machine. This time I tried deploying it on the readthedocs, it deployed without error message but the copyButton function did not work.

Here's a screenshot.

![copyButton_not present](https://user-images.githubusercontent.com/13150442/82356592-b0300700-99fb-11ea-94a7-a5f997f8995c.png)

Please any idea on how to fix this.

**Comment by stsewd** [comment]
You need to install that extension on rtd as well https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

**Comment by umeklinks** [comment]
I've tried but it's not working. I think I'll need more information on that.

**Comment by stsewd** [comment]
please provide a link to your rtd project

**Comment by blaisep-vgs** [comment]
Hi @stsewd , I'm having the same problem when I use the alabaster theme, even for a local build.

`sphinx-copybutton               0.3.0`

```python
extensions = ['sphinx.ext.autodoc',
              'sphinx.ext.doctest',
              'sphinx.ext.autosummary',
              'sphinx.ext.napoleon', # https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html)
              'sphinx.ext.intersphinx',
              'sphinx.ext.todo',
              'sphinx.ext.coverage',
              'sphinx.ext.mathjax',
              'sphinx.ext.ifconfig',
              'sphinx.ext.viewcode',
              'sphinx_rtd_theme',
              'sphinxcontrib.openapi', # https://sphinxcontrib-openapi.readthedocs.io/#)
              'sphinxcontrib.redoc' , # https://sphinxcontrib-redoc.readthedocs.io/en/stable/)
              'sphinx.ext.githubpages',
              'sphinx-copybutton',
              ]
```

**Comment by humitos** [comment]
@blaisep-vgs Hi! If the problem is present in your local build, it's not an issue related to Read the Docs. You may need to ask to the `sphinx-copybutton` folks for help. Thanks.

**Comment by blaisep-vgs** [comment]
LOL, @humitos , I am SO sorry, I thought this was the `sphinx-copybutton` team, I didn't event look at the top of the page! 🤦
