### ISSUE TITLE
Delete account form isn't an effective double check

### ISSUE THREAD

**Issue by davidfischer** [readthedocs/readthedocs.org#7103]
## Details

* URL: https://readthedocs.org/accounts/delete/

This form pre-populates the username such that it isn't an effective double check on the user deleting their account.

![Screen Shot 2020-05-19 at 3 10 22 PM](https://user-images.githubusercontent.com/185043/82383646-1d836e00-99e3-11ea-87f9-c5b5825ca485.png)

**Comment by santos22** [comment]
What about implementing something similar to the way GitHub handles users deleting a repository?

Before clicking:
![Screen Shot 2020-05-20 at 12 04 37 PM](https://user-images.githubusercontent.com/7004949/82486788-3dbe3600-9a92-11ea-8356-be87b1c5d410.png)

After clicking:
![Screen Shot 2020-05-20 at 12 04 46 PM](https://user-images.githubusercontent.com/7004949/82486809-431b8080-9a92-11ea-9cc9-4773ad47cc47.png)

**Comment by stsewd** [comment]
@santos22 that's what we already have, but the problem is the field is autocompleted by the browser, that should be disabled.

**Comment by santos22** [comment]
Whoops. I wasn't aware - good to know!

**Comment by davidfischer** [comment]
It's actually autocompleted server side.
