### ISSUE TITLE
Edit on github link is invalid and contains a spurious "origin"

### ISSUE THREAD

**Issue by eric-wieser** [readthedocs/readthedocs.org#7108]
## Details

* Read the Docs project URL: https://galgebra.readthedocs.io/en/latest/galgebra_guide.html
* Build URL (if applicable):
* Read the Docs username (if applicable):

Our conf.py is at https://github.com/pygae/galgebra/blob/master/doc/conf.py. The word `origin` does not appear it in, nor do we override any of the sphinx_rtd_theme `github_*` settings.

xref https://github.com/pygae/galgebra/issues/35

## Expected Result

The edit on github link should go to https://github.com/pygae/galgebra/blob/master/doc/galgebra_guide.rst

## Actual Result

The edit on github link goes to a 404 page, https://github.com/pygae/galgebra/blob/origin/master/doc/galgebra_guide.rst

**Comment by eric-wieser** [comment]
This looks like #5523 again?

**Comment by eric-wieser** [comment]
I suspect this is fixed by changing my "latest" branch from "----" to `master`

**Comment by eric-wieser** [comment]
Yep, that fixed it. Looks like your database has some stale `origin/master` defaults sitting in it somehow.

**Comment by stsewd** [comment]
Yeah, updating the default branch or just saving should do the trick.
