### ISSUE TITLE
Add more admin filters to build model admin

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#7109]
A couple of filters that would be helpful:

- [ ] Build state is not finished
- [ ] Build state is not finished or triggered (ie - build is actively doing something on one of the builders)
- [ ] Filter by build queue (filter by builder hostname prefix or something (builder hostnames are different in community and commercial))

**Comment by humitos** [comment]
We haven't had issues that require exploring the builds from the Django Admin at this deep lately, so I think we should probably close this issue.

**Comment by agjohnson** [comment]
Agreed, I think we have the first two already either way.
