### ISSUE TITLE
Documentation not building while using jupyter-sphinx

### ISSUE THREAD

**Issue by abhigyanprksh** [readthedocs/readthedocs.org#7111]
## Details
I was trying to figure out a way to embed executable Jupyter widgets in my documentation while using Sphinx for generating docs. I found an extension which allows us to do that ([jupyter-sphinx](https://github.com/jupyter/jupyter-sphinx)).

* Read the Docs project URL: https://readthedocs.org/projects/gunsnfloyd2k19/
* Build URL (if applicable): https://readthedocs.org/projects/gunsnfloyd2k19/builds/11087597/
* Read the Docs username (if applicable): abhigyanprksh

## Expected Result

Successful build. Building locally with sphinx works fine, however the. build is failing on readthedocs. 
This is the link to relevant git repository: https://github.com/abhigyanprksh/sphinx-jupyter

## Actual Result

The build fails with following error:
``AttributeError: 'JupyterCellNode' object has no attribute cm_language``

This is the link the exact part where the error is pointing: https://github.com/jupyter/jupyter-sphinx/blob/master/jupyter_sphinx/ast.py#L437

**Comment by humitos** [comment]
Hi @abhigyanprksh! Are you able to build your documentation locally? At first sight, it does not seems to be a problem related to Read the Docs, but with the extension itself.

If you can build it locally, double check that the versions installed on RTD are the same that you have installed locally.

**Comment by abhigyanprksh** [comment]
Yes, I am able to build locally. I haven't changed anything in the git repository. I have specified the same packages I used locally in my requirements.txt.

**Comment by humitos** [comment]
Oh, I see. Can you disable the `htmlzip` format on Read the Docs and try again? I guess that extension does not support it.

**Comment by abhigyanprksh** [comment]
Is that enabled by default? I will write a readthedocs.yml file to override it anyway.

**Comment by abhigyanprksh** [comment]
I guess this issue has more to do with the extension than readthedocs, I am closing this issue.
