### ISSUE TITLE
Search results don't respect "html_add_permalinks"

### ISSUE THREAD

**Issue by mgeier** [readthedocs/readthedocs.org#7119]
I'm not sure whether this is the right place to ask ...

This concerns the Sphinx search, but it doesn't occur when building locally, so I suspect it has something to do with the custom RTD search.

The search result page doesn't seem to strip the permalink markers if the option [html_add_permalinks](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_add_permalinks) is used.

This doesn't occur with the `sphinx_rtd_theme`.
I was using the `alabaster` theme, but it also happens with other themes as well.

## Details

* Read the Docs project URL: https://readthedocs.org/projects/audioscenedescriptionformat/
* Build URL (if applicable): https://readthedocs.org/projects/audioscenedescriptionformat/builds/11099481/

## Expected Result

When not using `html_add_permalinks` (i.e. using the default `¶`):

![image](https://user-images.githubusercontent.com/705404/82709638-5771a000-9c81-11ea-8a76-91f2b4a89bdf.png)

https://audioscenedescriptionformat.readthedocs.io/en/latest/search.html?q=treasure

## Actual Result

When using `html_add_permalinks = '\N{SECTION SIGN}'`:

![image](https://user-images.githubusercontent.com/705404/82710028-32c9f800-9c82-11ea-9ac8-d9773cf21be6.png)

https://audioscenedescriptionformat.readthedocs.io/en/html_add_permalinks/search.html?q=treasure

**Comment by stsewd** [comment]
This is a bug in our side, we just need to remove that from the title before indexing it.

**Comment by stsewd** [comment]
the fix should be deployed by next tuesday

**Comment by mgeier** [comment]
@stsewd Is there something I have to do to get the fix?

I have "wiped" and re-built the docs but the problem persists: https://audioscenedescriptionformat.readthedocs.io/en/html_add_permalinks/search.html?q=treasure

**Comment by stsewd** [comment]
@mgeier sorry, we didn't do a deploy this week, hopefully we have one next week

**Comment by stsewd** [comment]
I have triggered a new build https://readthedocs.org/projects/audioscenedescriptionformat/builds/11220806/ in order to refresh the index, it's working now (try cleaning your cookies if you still see the old result). If you are seeing this in another version, you'll need to trigger a new build there as well.

**Comment by mgeier** [comment]
It indeed works very nicely, thanks a lot @stsewd!
