### ISSUE TITLE
Sharing Requirements and conf.py Between Multiple Repos

### ISSUE THREAD

**Issue by gbroques** [readthedocs/readthedocs.org#7120]
## Details
How would I share a **Requirements file** (i.e. `requirements.txt`) and **Sphinx configuration file** (i.e. `conf.py`) between multiple repositories, each with their own hosted Read the Docs website?

I'm planning on maintaining something on the order of 50 or 100 repositories for an enterprise level non-profit organization, and would like each repository to share the *same* docs requirements and parameterized Sphinx configuration for maintainability.

My plan was to have a parent repo that individual repository maintainers in the organization install as a **dev-time** dependency. In this repo, I'd have the `requirements.txt` for the docs, and parent `conf.py` file with the bulk of Sphinx configuration.

#### Git Submodules
I see you support [Git Submodules](https://docs.readthedocs.io/en/stable/config-file/v2.html#submodules). This might be one approach that could work.

#### Host Parent Repo on PyPi
I could also host the parent repo as a dependency on PyPi. Then each child repo has this as a dependency in their `requirements.txt` and their `conf.py` can import and `exec` and imported common configuration (see [this StackOverflow](https://stackoverflow.com/a/35417352)).

Any recommendations or thoughts on either option, or a different option?

### Remote Requirements File
Also, it might be nice if you supported a remote URL to a requirements file.

If I could provide a link to the `requirements.txt` in this parent GitHub repository, then that would solve 1-half of my desire to share what's needed for the docs site.

## Related Issues
* **Collections of Projects:** #3784

## Read the Docs Project URL
* https://ose-3d-printer-workbench.readthedocs.io/en/latest/index.html

**Comment by stsewd** [comment]
> Also, it might be nice if you supported a remote URL to a requirements file.

We don't plan in supporting something like that.

Git submodules and importing the common configurations from the conf.py in the submodule should work.
