### ISSUE TITLE
How to set pathto

### ISSUE THREAD

**Issue by Lijiaoa** [readthedocs/readthedocs.org#7121]
when I set `<a href="{{ pathto('index') }}">Hello world</a>`, the text will link to the path `xx/index.html`.

But I want to get the path `xx/index.html#some`. Is it impossible?

I don't know how to set this href.

**Comment by humitos** [comment]
Hi! I'm not sure what you are trying to do, but

```html
<a href="{{ pathto('index') }}#some">Hello world</a>
```

may be what you need.

**Comment by Lijiaoa** [comment]
Hi, @humitos Thanks for your reply!

`<a href="{{ pathto('index') }}#some">Hello world</a>`

This way will get the url `xx/index#some.html`. I want to get the url `xx/index.html#some`

**Comment by stsewd** [comment]
@Lijiaoa this looks like an issue related to sphinx/jinja, not to Read the Docs.

**Comment by humitos** [comment]
> This way will get the url `xx/index#some.html`

This is not correct.

However, as @stsewd mentioned, this is not an issue with Read the Docs. You may find useful https://www.sphinx-doc.org/en/master/templating.html#pathto
