### ISSUE TITLE
Build passed, but autogenerated index file is shown

### ISSUE THREAD

**Issue by belerico** [readthedocs/readthedocs.org#7127]
## Details

* Read the Docs project URL: https://sciq.readthedocs.io/en/sprint2/
* Read the Docs username (if applicable): belerico

## Expected Result

As the build has passed, I was expecting to correctly browse the documentation. The strange thing is that the webhook for building the documentation for another branch is ok (https://sciq.readthedocs.io/en/34-online-documentation/) 

## Actual Result

For the branch "sprint2", documentation build passed, but an autogenerated file is shown; for the other branch "34-online-documentation", documentation build passed and the doc is correctly shown

**Comment by belerico** [comment]
Now, after a day of strange behaviour, it seems to correctly show the doc

**Comment by stsewd** [comment]
Probably a cached version on your browser, try a hard refresh next time (Ctrl + F5). If you hit this again and a hard refresh doesn't work, let us know.
