### ISSUE TITLE
Remove "Unknown" value from PR selector

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#7130]
In Admin -> Advanced settings.

![Screenshot_2020-05-26_19-00-26](https://user-images.githubusercontent.com/244656/82928986-437cb580-9f83-11ea-9fb4-2ef8389a532f.png)

**Comment by stsewd** [comment]
Something like this is needed https://github.com/readthedocs/readthedocs.org/pull/6996/commits/d8bebe023c44c83f2ad6ff9e447e47b7dae59892, or just do a migration withe setting the field to be not-null
