### ISSUE TITLE
disabled project and no new builds

### ISSUE THREAD

**Issue by pierrebaudot** [readthedocs/readthedocs.org#7135]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/infotopo/builds/
* Build URL (if applicable): https://infotopo.readthedocs.io/en/latest/
* Read the Docs username  pierrebaudot

Hello,
When I try to build a new version of my documentation, I get the  message "This project is currently disabled and can't trigger new builds."

## Expected Result

I wished my project to be enabled and to be able to build new version of my doc.
This already happened in a related issue "This project is currently disabled and can't trigger new builds #6291"
Thanks in advance,
Pierre

**Comment by pierrebaudot** [comment]
Hello again,
The infotopo project is yet disabled  in Read the docs, and I cannot find any way get out from what appears a deadend. Hope I did not make something wrong.
Regards

**Comment by stsewd** [comment]
Looks like your user was banned for some reason, probably a mistake. I've enabled your user again.

**Comment by pierrebaudot** [comment]
Hello,
Thank you very much!
All the best
