### ISSUE TITLE
Custom urlconf breaks automatic redirects

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#7136]
When using a custom urlconf, redirects like `/` -> `/en/latest` don't seem to work. Instead, a 404 error is returned. There is a similar issue where perhaps a top level request could redirect to `en/latest` with the prepended prefix -- ie: `/` to `/subpath/foo/en/latest/`, though this is less important likely.

To reproduce:

* Give a project a custom urlconf: `subpath/$language/$version/$filename`
* Browse to the project URL: `foo.readthedocs.io/subpath/en/latest/` -- this works
* Browse to the custom root: `foo.readthedocs.io/subpath/` -- 404 here, where normall we'd redirect to `foo.readthedocs.io/subpath/en/latest/`
* Browse to the top level path: `foo.readthedocs.io/` -- also 404 here, though this might be harder to resolve

**Comment by ericholscher** [comment]
I think this is because we're defaulting some of the variables when there's a urlconf. We probably just need to tighten up that logic: https://github.com/readthedocs/readthedocs.org/blob/f138d17b0b8ceea66c9cfe996c3f234173694fb9/readthedocs/proxito/views/utils.py#L79-L87

**Comment by stsewd** [comment]
The new proxito implementation doesn't have this problem https://github.com/readthedocs/readthedocs.org/pull/10156.

**Comment by ericholscher** [comment]
@stsewd awesome :)
