### ISSUE TITLE
Optimize HTML publishing and cache purging

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#7139]
Before we served static files, we synced HTML files as soon as they were built, before building other formats. This gives users published changes much faster, which is a better UX. We should add this functionality back to our media uploads, allowing us to publish the HTML as soon as possible. 

The weird thing about this behavior is that it will publish HTML results even when PDF's or other build steps fail. I think that's OK if we make it obvious in the UX. I'm not 100% sold on this approach, so I'm marking this Design Decision Needed.

**Comment by agjohnson** [comment]
I'd probably be -1 on this change, it feels like an edge case or potentially just a core dev team edge case as much of what we do is waiting around for builds to finish. The UX issues around having PDF and HTML content differ is fairly broken and I don't think the benefit of having HTML faster outweigh this or the effort required to tease apart our build process to make this work.

**Comment by humitos** [comment]
I agree with @agjohnson here.

**Comment by ericholscher** [comment]
Yep, it's pretty confusing. Will close it.
