### ISSUE TITLE
High number of render-blocking resources on RTD docs

### ISSUE THREAD

**Issue by davidfischer** [readthedocs/readthedocs.org#7140]
## Details

Adding extensions and other additional CSS/JS files comes with a cost: slower docs rendering for the first load. This is greatly reduced once files are cached. It is also sped up a lot by the CDN (because docs are HTTP2 which handles multiple smaller files better and because CDNs are just plain faster). Nonetheless, this is going to be a performance issue for users on slow connections or on mobile.

Rather than a concrete issue with a simple fix, I just want to raise awareness of this and make sure that whenever possible we are adding as few files as possible. Perhaps we could add a Sphinx extension that "packs" JS and CSS or something like that.

Here's a few notes:

* We currently have **33 render-blocking files in our own docs**. All of these files must be downloaded before content will be displayed by the browser. Here's a small breakdown:

  - 2 render-blocking resources are added by RTD itself (`readthedocs-doc-embed.css` and `readthedocs-data.js`)
  - 7 come from Sphinx itself. Sphinx is not super optimized for this either.
  - 6 come from the Sphinx Tabs extension
  - 2 come from the theme
  - 10+ come from hoverxref and tooltipster

* [Async JavaScript](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-async) does not block rendering. We have just a couple of these and they are added by RTD. Starting with Sphinx 1.8, it's fairly easy to make additional [JS files async](https://www.sphinx-doc.org/en/master/usage/configuration.html?highlight=conf.py#confval-html_js_files) if the script supports it.
* It's worthwhile to check out Google's [PageSpeed Insights](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdocs.readthedocs.io%2Fen%2Fstable%2F) on this. Google estimates **we have over 6 seconds of render-blocking resources** before the first content is displayed.

## Screenshot

This is a screenshot of the files loaded in our own docs `docs.readthedocs.io`:

![Screen Shot 2020-05-28 at 2 13 21 PM](https://user-images.githubusercontent.com/185043/83194850-29131b00-a0ee-11ea-8c33-fbe243cc9cef.png)

**Comment by humitos** [comment]
> * 2 render-blocking resources are added by RTD itself (`readthedocs-doc-embed.css` and `readthedocs-data.js`)

I understand with the introduction of the new addons, we will be reducing this to just one .js file.
 
> * 7 come from Sphinx itself. Sphinx is not super optimized for this either.
> * 6 come from the Sphinx Tabs extension
> * 2 come from the theme
> * 10+ come from hoverxref and tooltipster

I don't think we can do too much here, right?

**Comment by humitos** [comment]
With the new addons implementation we will be injecting only one JavaScript file that loads async. This will remove all the blocking elements we have control over.

I think we can probably close this issue since we don't have to do anything and it will be solved automatically in a near future when we migrate all projects to the new implementation for these integrations. Feel free to re-open if you consider, tho.

**Comment by humitos** [comment]
Hrm, it seems that we are not adding `async="async"` attribute to our script yet: https://github.com/readthedocs/readthedocs-ops/blob/39a45926bfad351ecd65c506b3bfceffbe7016ed/terraform/prod/cloudflare/workers/readthedocs-addons.js#L8-L11

Re-opening to do that before closing it, 😅
