### ISSUE TITLE
Can mkdocs support multi navigation for readthedocs theme

### ISSUE THREAD

**Issue by hpatil47** [readthedocs/readthedocs.org#7149]
We have created the custom theme with the help of mkdocs readthedocs theme, we are able to do two level navigation. but now we are trying to do 3rd level navigation. is it possible for read the docs theme ?

**Comment by humitos** [comment]
I haven't work with the mkdocs readthedocs theme, so I don't have a great answer here. I'd take a look at how other themes do that, since I'd say that there shouldn't be anything readthedocs-theme specific that would avoid you to do that.
