### ISSUE TITLE
Request for setting to opt out of Google Analytics

### ISSUE THREAD

**Issue by mbacchi** [readthedocs/readthedocs.org#7151]
## Details

We build a privacy focused browser, and our installation documentation is hosted on Read The Docs. All of our services attempt to prevent tracking by Google. It was just brought to my attention that [Google Analytics](https://docs.readthedocs.io/en/stable/privacy-policy.html#google-analytics) is used on RTD, and while I am aware of the fact that you honor the Do Not Track(DNT) setting in the browser, only a very small percentage of users know about this (you estimated 6% in your own [blog](https://blog.readthedocs.com/read-the-docs-2019-stats/) from earlier this year.)

In https://github.com/readthedocs/readthedocs.org/issues/1221 you said that you "hope to remove GA globally at some point, but we need it to understand RTD for now." This issue is from 5 years ago, and theoretically you have gathered the information you required to provide a stable and popular service. (Which I believe you have created, my sincere thanks.)

I would now request that you consider an option in the project settings to disable Google Analytics on documentation if the project owners so desire.

Thank you.

**Comment by davidfischer** [comment]
Understanding our audience better is an ongoing effort and the data we use from analytics is ongoing as well. You can read about why we use analytics to understand Read the Docs [here](https://docs.readthedocs.io/en/stable/advertising/advertising-details.html#analytics).

With that said, a project level opt-out seems like a fine idea that isn't too big of an effort.

**Comment by w0ts0n** [comment]
Our users are very picky about 3rd party tracking (as they should be) and have explicitly asked why we have GA on our Read the Docs page. With that in mind, any idea what the ETA would be on allowing project opt-out? If it's not short term, we will likely have to move our docs, which is something I would like to avoid.

**Comment by davidfischer** [comment]
Read the Docs has a very small core team and we generally don't give ETAs on community open source features. We have [paid plans](https://readthedocs.com/pricing/) and paid support if your company requires it.

**Comment by w0ts0n** [comment]
Fair enough, we'll move off RTD for now and revisit later. Thanks for the updates

**Comment by mbacchi** [comment]
We've disabled GA on our project and rebuilt the docs. Thanks for this feature!

**Comment by davidfischer** [comment]
Our pleasure. I'm glad we were able to get to a good solution.
