### ISSUE TITLE
Remove redundant build by a different user on our repo

### ISSUE THREAD

**Issue by jabdoa2** [readthedocs/readthedocs.org#7152]
We host our documentation using RTD on https://docs.missionpinball.org/en/latest/. Unfortunately, there is still an old project from a user which uses our repo but last build over two years ago. Can you remove that?

## Details

* Read the Docs project URL: https://mpf-docs.readthedocs.io/ and https://docs.missionpinball.org/
* Build URL (if applicable): https://readthedocs.org/projects/mpf-docs/ and https://readthedocs.org/projects/mpf/
* Read the Docs username (if applicable): jabdoa

## Expected Result

Docs are only available on https://docs.missionpinball.org/en/latest/.

## Actual Result

Docs are only available on https://docs.missionpinball.org/en/latest/ and in a very old version on https://mpf-docs.readthedocs.io/

**Comment by jabdoa2** [comment]
I already contacted him a while back about that. He wanted to take it down but apparently did not.

The emails on the site are my emails because I run the repo which he uses as source for his rtd site (mpf-docs.readthedocs.io). This is heavily outdated (release 0.33) and our "official" documentation exists with the same source repo (release 0.53 and 0.54 currently).

Unfortunately, we get user complaints because users refer to the old documentation and cannot really do anything about it. That kind of sucks for us.

**Comment by stsewd** [comment]
@jabdoa2 I'd recommend trying to contact the user again, if you don't receive a reply, let us know, so we can start the abandoned privacy policy,
