### ISSUE TITLE
Automatically run ipynb and then build html output with charts.

### ISSUE THREAD

**Issue by DanielAtKrypton** [readthedocs/readthedocs.org#7154]
## Details

* Read the Docs project URL: 
https://readthedocs.org/projects/timeseriespredictor
* Build URL (if applicable):
https://readthedocs.org/projects/timeseriespredictor/builds/11177786/
* Read the Docs username (if applicable): DanielAtKrypton

## Expected Result

The file [Usage.rst](https://github.com/DanielAtKrypton/time_series_predictor/blob/master/docs/source/usage.rst) was supposed to run and generate html with `ipynb` outputs present.
It is interesting to note that the documentation builds alright locally. But when the build is triggered by RTD, a `ModuleNotFoundError` error happens

## Actual Result

Builds are failing with the following message:
```terminal
No module named 'src'
```

**Comment by DanielAtKrypton** [comment]
This is how it behaves locally for the following [ipynb](https://github.com/DanielAtKrypton/time_series_predictor/blob/05aadf7c4727ce7ac4175b0a2ea3cbd43db23eab/docs/source/notebooks/example.ipynb).

![Imgur](https://i.imgur.com/5ZW53jz.png)

**Comment by stsewd** [comment]
Make sure you are installing the same dependencies in read the docs https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

**Comment by DanielAtKrypton** [comment]
[This](https://github.com/DanielAtKrypton/time_series_predictor/blob/05aadf7c4727ce7ac4175b0a2ea3cbd43db23eab/.readthedocs.yml#L31) is how dependencies are being installed in RTD.

**Comment by stsewd** [comment]
Looks like the src module is failing to being imported when `reading sources... [ 63%] notebooks/example_flights_dataset`

https://readthedocs.org/projects/timeseriespredictor/builds/11372427/

Please try executing the same commands as read the docs in a clean environment,  also, we don't call `make html` to build the docs, but we use the `sphinx build` command

**Comment by DanielAtKrypton** [comment]
I just created a new environment and it worked locally with `sphinx-build` command. Here is the output of the build:

![Imgur](https://i.imgur.com/cqJ981w.png)

Unfortunately [readthedocs build](https://readthedocs.org/projects/timeseriespredictor/builds/11386131/) still fails for any reason.

**Comment by DanielAtKrypton** [comment]
@stsewd, do you have any clue about why this problem happens? It looks like the folders set within RTD CI instance are not preserving same folder structure of the project.

**Comment by stsewd** [comment]
Sorry, I haven't' had time to debug this, I'll make some time next week

**Comment by stsewd** [comment]
@Daniel-Mietchen sorry for the late reply, I took a look and I'm able to see the same error locally in a clean environment.

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-0effc87bdbd7> in <module>
      4
      5 from time_series_predictor import TimeSeriesPredictor
----> 6 from src.model import BenchmarkLSTM
      7 from src.flights_dataset import FlightsDataset

ModuleNotFoundError: No module named 'src'
ModuleNotFoundError: No module named 'src'

You can ignore this error by setting the following in conf.py:

    nbsphinx_allow_errors = True

```

Also, I recommend you to use  `__file__` to the get the correct path

```python
os.path.abspath(os.path.join(__file__, '../../../'))
```

I think ipynb is ignoring the injected path when running the examples for some reason.

**Comment by Daniel-Mietchen** [comment]
Looks like @stsewd was trying to ping @DanielAtKrypton here.

**Comment by stsewd** [comment]
Oops, yeah sorry!

**Comment by DanielAtKrypton** [comment]
@stsewd, it was just solved [here](https://github.com/krypton-unite/time_series_predictor/issues/1#issuecomment-706774780).
