### ISSUE TITLE
sphinx autodoc can't show anything on readthedocs

### ISSUE THREAD

**Issue by sunshineDrizzle** [readthedocs/readthedocs.org#7156]
## Details

* Read the Docs project URL: https://dnnbrain.readthedocs.io/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

*A description of what you wanted to happen*

I hope that the sphinx autodoc directives such as ".. automodule::" in the .rst files under the directory "/docs/docs/pylib" can be recognized. And as a result, it should extract docstrings of my project and build into html as an API documentation.

## Actual Result

The buliding results on the readthedocs show the [toctree](https://dnnbrain.readthedocs.io/en/latest/docs/index.html#python-apis) of API documentation. But module pages are empty.

*A description of what actually happened*
I have added my project's root directory to the sys.path in conf.py:
![image](https://user-images.githubusercontent.com/14846772/83710064-688fb900-a652-11ea-9fd8-2019078c3f89.png)
and append extensions with 'sphinx.ext.autodoc':
![image](https://user-images.githubusercontent.com/14846772/83710176-ad1b5480-a652-11ea-87b7-d2984a3b9af4.png)

What's more, all the autodoc directives can extract my project's docstrings when I build it locally. However, it doesn't work on the readthedocs. I don't know why and I also can't find any suitable solution on the internet. Can anyone help me? If you need more information, please let me know.
Thanks very much!

**Comment by humitos** [comment]
`sphinx.ext.autodoc` needs your module to be installed to be able to extract the docstring. Are you installing it on Read the Docs as well?

See https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

If you don't want to install your module, you can use https://sphinx-autoapi.readthedocs.io/ that does not requires it to be installed.

**Comment by sunshineDrizzle** [comment]
Oh, I guess I know what the problem is.
Thanks, I will try to solve it after dealing with something urgent recently.

**Comment by CapernicusPY** [comment]
I am having the same problem too. Although the module is in the root directory (../.. relative to the current folder (project/docs/source/api.rst) and I specified that in the conf.py. When I build the latest version tho only some text headers that I defined, worked. But if I git clone the project and use the command `make html` and open the build/html/api.html it works fine. How can I fix that
