### ISSUE TITLE
Update default Sphinx version

### ISSUE THREAD

**Issue by Limonkufu** [readthedocs/readthedocs.org#7165]
ReadtheDocs will work with a newer version of sphinx instead of 1.8.5 (over a year old)

Could we update the default sphinx version or give clear reasoning why we are using still the old versions?

I can work on this since we are using RTD a lot but I need a little bit of guidance

**Comment by stsewd** [comment]
You can use any version of sphinx you want https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

The reason the default is 1.8.5 is because our theme doesn't support the latest version of sphinx yet (we are close to release a compatible version)

**Comment by Limonkufu** [comment]
Thanks for the update. Is there anything I can do for the update process? Regardless, you can close this issue :)

**Comment by stsewd** [comment]
@Limonkufu you can help us testing the pre-release version of the theme https://pypi.org/project/sphinx-rtd-theme/#history If you find a problem, please report that to https://github.com/readthedocs/sphinx_rtd_theme
