### ISSUE TITLE
Project is missing a needed branch, and has many long-deleted branches

### ISSUE THREAD

**Issue by nedbat** [readthedocs/readthedocs.org#7168]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/open-edx-building-and-running-a-course/versions/
* Build URL (if applicable): none
* Read the Docs username (if applicable): edX

## Expected Result

*A description of what you wanted to happen*

I created a branch in the GitHub repo: https://github.com/edx/edx-documentation/tree/open-release/juniper.master

I expected that branch would appear as a version in the readthedocs project. It does not.  

Meanwhile, there are dozens of branches in the versions page which have been deleted from GitHub. Is there some way to force the project to synchronize with the repo?

Thanks.

**Comment by stsewd** [comment]
Make sure your webhook is working correctly https://docs.readthedocs.io/en/latest/webhooks.html

> Is there some way to force the project to synchronize with the repo?

Yes, you can trigger a new build on any version.

**Comment by nedbat** [comment]
I will check the webhook, thanks.  

> Yes, you can trigger a new build on any version.

Maybe I'm missing something: I only see a way to choose a version from a drop-down.

**Comment by stsewd** [comment]
> Maybe I'm missing something: I only see a way to choose a version from a drop-down.

Yeah, trigger a build on any of those, that will refresh the list of versions

**Comment by nedbat** [comment]
Thanks, I am all set now.
