### ISSUE TITLE
Expose env vars when building docs from a PR/MR

### ISSUE THREAD

**Issue by webknjaz** [readthedocs/readthedocs.org#7182]
## Details

* Read the Docs project URL: https://cheroot.cherrypy.org/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/cheroot/builds/11183237/
* Read the Docs username (if applicable): webknjaz

## Expected Result

Successful build

## Actual Result

Loading a repo-local in-tree Sphinx extension fails in PR builds (with `ImportError`) but is successful on master.

I've just realized that I've set `PYTHONPATH` in the UI earlier to make it work. And now it looks like it is set in normal builds but not in PRs.

**Comment by webknjaz** [comment]
As I can see, env vars UI is implemented as storage for secrets. How about adding the ability to provide some env vars via a YAML config? That would be public and wouldn't need any extra protection implementation.

**Comment by humitos** [comment]
> I've just realized that I've set `PYTHONPATH` in the UI earlier to make it work. And now it looks like it is set in normal builds but not in PRs.

Yes. We do not expose env variables in PRs as a security protection.

> How about adding the ability to provide some env vars via a YAML config?

You already opened an issue for this at #6311. We haven't done a decision yet.

**Comment by webknjaz** [comment]
> Yes. We do not expose env variables in PRs as a security protection.

Yeah, I figured that it's because of the security considerations :)

> You already opened an issue for this at #6311. We haven't done a decision yet.

Ah, right. I've forgotten about that one. FWIW this issue brings another perspective at the problem because I didn't realize that missing open env vars feature would also hit the PR integration. So the current issue is about a slightly different side of it.
And I also wanted it to be separate feedback because the PR integration is in beta (still?).
