### ISSUE TITLE
How do I programmatically know in which language the docs are built?

### ISSUE THREAD

**Issue by fmaussion** [readthedocs/readthedocs.org#7188]
## Details

* Read the Docs project URL: https://oggm-edu.readthedocs.io/
* Read the Docs username (if applicable): fmaussion

## Usage question

I am using sphinx [ifconfig](https://www.sphinx-doc.org/en/master/usage/extensions/ifconfig.html) to display parts of the docs only in specific languages. What I need is some env variable available in `conf.py` or everywhere in the docs that I could retrieve in my rst files to write something like:

```rst
Source code
-----------

Code and data are on `GitHub <https://github.com/OGGM/alps_future>`_, BSD3 licensed.

.. ifconfig:: rtd_language in ('en')

  Possible future app improvements
  --------------------------------
  
  etc.
```

Is there such a global variable in rdt at runtime? Thanks a lot!

**Comment by stsewd** [comment]
You can use https://docs.readthedocs.io/en/stable/builds.html#build-environment

**Comment by fmaussion** [comment]
Well that was easy - so sorry to have missed this in the docs in the first place and thanks for the help :disappointed_relieved:
