### ISSUE TITLE
Page with random description and broken repo link.

### ISSUE THREAD

**Issue by ObliviousParadigm** [readthedocs/readthedocs.org#7189]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/multi-language/
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

I expected to see some info.

## Actual Result

It displayed a page with a description containing random words, and has a link to a GitHub repository that doesn't exist anymore.

**Comment by ObliviousParadigm** [comment]
Can I fix this?

**Comment by stsewd** [comment]
@ObliviousParadigm what do you mean by fixing it? We only host documentation, we are not the authors of that project if you are looking for the content (if there was any). If you mean by taking the project, you can follow our policy for abandoned projects https://docs.readthedocs.io/en/stable/abandoned-projects.html

**Comment by ObliviousParadigm** [comment]
By fix, I meant that I would like to remove the unwanted content or add a 404 redirect but based on what you've said, I don't think I can.

**Comment by humitos** [comment]
I'm closing this issue. Let us know if you need anything else!

**Comment by ObliviousParadigm** [comment]
Okay! I do have a question. Where do I start from to familiarize myself with the codebase (or atleast a part of it) so that I can start contributing?

**Comment by stsewd** [comment]
@ObliviousParadigm you can start reading https://docs.readthedocs.io/en/stable/contribute.html and you can ask question on gitter (we'll try to answer when we have time)
