### ISSUE TITLE
Can't change version back to public

### ISSUE THREAD

**Issue by gkovacs81** [readthedocs/readthedocs.org#7191]
## Details

https://readthedocs.org/projects/arpi-security   --- user: gkovacs81

I have a hidden version "dev_v0.6", and I can't make it public again. I can change the state of the Hidden checkbox and save it, but the version stays in private state.

## Expected Result

When I remove the hidden state of the version and save it, the version should be public again.

## Actual Result

The version dev_v0.6 is always private.

**Comment by humitos** [comment]
@gkovacs81 I updated that version to be PUBLIC. Let me know if that's what you expected. Thanks.

**Comment by gkovacs81** [comment]
Thanks for your prompt reply! Yes, now the version is public again.
Could you please help me if it is a bug on your side or did I make something wrong?

**Comment by humitos** [comment]
We removed PRIVATE privacy level from readthedocs.org and migrate them to Hidden versions. Maybe something went wrong there, but our tests and QA passed, so :shrug: 

Please, keep me updated if you find any other version that you can't make it PUBLIC for any reason. Thanks!

**Comment by stsewd** [comment]
We only migrated protected versions only, we are migrating private versions tomorrow. Also, we shouldn't be using the private filter in .org, so it shouldn't cause any problems having the version private
