### ISSUE TITLE
System status' page

### ISSUE THREAD

**Issue by microbit-mark** [readthedocs/readthedocs.org#7192]
## Details

* Read the Docs project URL:https://microbit-micropython.readthedocs.io
* Build URL (if applicable):
* Read the Docs username (if applicable):

When using search on the docs recently, it resulted in 500 nginx error or 502 bad gateway cloudflare errors. This seemed to rectify itself within about 15 minutes. 

It would be useful to have a system status page or a way of notifying users if there is a service degradation on readthedocs.

**Comment by humitos** [comment]
Hi @microbit-mark! Thanks for opening this issue. We have already considered having a status page, but we didn't have the time to make it publicly available yet.

**Comment by stsewd** [comment]
We have a status page now https://status.readthedocs.com/
