### ISSUE TITLE
Command killed due to excessive memory consumption

### ISSUE THREAD

**Issue by DmitriiDeriabinQB** [readthedocs/readthedocs.org#7202]
## Details

* Read the Docs project URL: https://kedro.readthedocs.io/en/stable/
* Build URL (if applicable): https://readthedocs.org/projects/kedro/builds/11272062/
* Read the Docs username (if applicable): DmitriiDeriabinQB

## Expected Result

The build to pass.

## Actual Result

The build failed when trying to build Latex version of the docs with the error from the above. Interestingly enough, tag version "0.16.2", which points to the same repo commit (a4fe8d145b37bd85aaacad1fefef18f0a5b4ec19) has been built just fine: https://readthedocs.org/projects/kedro/builds/11258379/. I need some help understanding why one build passes, while the other fails, thank you.

**Comment by DmitriiDeriabinQB** [comment]
Sometimes is passes latex build step and fails on the next one (`cat latexmkrc`): https://readthedocs.org/projects/kedro/builds/11272519/

**Comment by humitos** [comment]
Hi @DmitriiDeriabinQB! Thanks for report this to us. I think this is a bug in our configuration that's limiting build time to a lower value that it should be. 

For now, I just increased the build time for your project as a quick workaround and it should build properly now.

**Comment by DmitriiDeriabinQB** [comment]
Hi @humitos! It is indeed passing now, thank you for a very quick turnaround 👍
