### ISSUE TITLE
Show `conda list` after conda environment is created

### ISSUE THREAD

**Issue by lukelbd** [readthedocs/readthedocs.org#7210]
## Details

Would you guys consider printing `conda list` after conda environments are created? Currently, there is no way to see which packages are downloaded.

I am trying to debug #7211. It must be either an RTD issue or an issue with conda downloading a different version of something -- but unfortunately, if it is a conda issue, I cannot debug it.

This issue is similar to #5006, but that issue was dismissed on the basis that [the `pip install` step already shows the packages installed](https://github.com/readthedocs/readthedocs.org/issues/5006#issuecomment-482356900). The same is not true for conda environments.

* Read the Docs project URL: https://proplot.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/proplot/builds
* Read the Docs username (if applicable): lukelbd

## Expected Result

Packages downloaded by `conda env create` are shown.

## Actual Result

No packages shown:

<img width="1005" alt="Screen Shot 2020-06-21 at 11 10 16 PM" src="https://user-images.githubusercontent.com/19657652/85250803-d7bc2a00-b414-11ea-82be-353e1fa2d861.png">

**Comment by humitos** [comment]
I enabled this feature `LIST_PACKAGES_INSTALLED_ENV` (see https://docs.readthedocs.io/en/stable/guides/feature-flags.html#feature-flags) in your project. Let me know if it works as you expected. Thanks!

**Comment by lukelbd** [comment]
@humitos Awesome, thanks!! Just checked, it works.
