### ISSUE TITLE
Numpydoc-style parameter tables changed after re-building unchanged release

### ISSUE THREAD

**Issue by lukelbd** [readthedocs/readthedocs.org#7211]
## Details

All the pages in my "API Reference" section switched from the "Expected Result" to the "Actual Result" (see below). This issue arose *after rebuilding the stable version which was last compiled a week ago* -- i.e. the dependencies or configuration haave not changed. Wiping the versions did not help. This issue is also happening with all of my "Latest" builds as of today.

Pretty weird issue :/, hoping someone can help!

* Read the Docs project URL: https://proplot.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/proplot/builds
* Read the Docs username (if applicable): lukelbd

## Expected Result

Normal numpydoc-style parameter tables:

<img width="730" alt="Screen Shot 2020-06-22 at 12 03 42 AM" src="https://user-images.githubusercontent.com/19657652/85253632-d8a48a00-b41b-11ea-841d-1c403fcf02f4.png">

## Actual Result

Weird tables, with parameter lists bleeding into the margin and a two-column table rather than bullet points for parameter names:

<img width="1013" alt="Screen Shot 2020-06-22 at 12 02 36 AM" src="https://user-images.githubusercontent.com/19657652/85253553-b01c9000-b41b-11ea-9bd6-33e44e019e92.png">

**Comment by lukelbd** [comment]
As I guessed in #7210, this was indeed due to a new version being downloaded -- `sphinx_rtd_theme` upgraded to version 0.5.0 5 days ago and it evidently has a bug.

**Comment by agjohnson** [comment]
@lukelbd Thanks for the report. This might be a theme bug due to the change in the HTML writer. I haven't seen this replicated in any of the normal autodoc usage though. I see you're doing something custom on your docs, using an extension[1] to generate the autodoc output. Could you verify that this is not the source of the problem?

1: https://github.com/lukelbd/proplot/blame/master/docs/api.rst#L10

**Comment by agjohnson** [comment]
Moved to readthedocs/sphinx_rtd_theme#949

**Comment by lukelbd** [comment]
@agjohnson Beat me to it!

I can verify this wasn't an issue with the RTD server, was able to reproduce this on my local machine by generating the docs with `sphinx_rtd_theme` v0.5.0 instead of the previous v0.4.3.
