### ISSUE TITLE
Python 3.6: autodoc page builds locally, but is empty on readthedocs.org  

### ISSUE THREAD

**Issue by jnecus** [readthedocs/readthedocs.org#7220]
## Details

* Read the Docs project URL:
* Build URL:  https://readthedocs.org/projects/ukbiobank-tools/builds/11312342/

Appears similar to the following issue #3634 , but not caused by the same issue seemingly.

## Expected Result

I am attempting to build documentation for my project. When I build locally, autodoc produces API documentation, so I would expect that the same result on readthedocs.org, or that inspecting the build output for the project would reveal errors.

## Actual Result

The build output provides the following:
```

WARNING: autodoc: failed to import module 'ukbio' from module 'ukbiobank'; the following exception was raised:
No module named 'ukbiobank.utils'
WARNING: autodoc: failed to import module 'utils.ukbio_utils' from module 'ukbiobank'; the following exception was raised:
No module named 'ukbiobank.utils'
WARNING: autodoc: failed to import module 'filtering.ukbio_filtering' from module 'ukbiobank'; the following exception was raised:
No module named 'ukbiobank.utils'
WARNING: autodoc: failed to import module 'ukbio_utils' from module 'ukbiobank'; the following exception was raised:
No module named 'ukbiobank.utils'

```

**Comment by stsewd** [comment]
You need to have installed the same packages as you do locally, please check https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html#specifying-dependencies

**Comment by jnecus** [comment]
The package ukbiobank-tools appears to be installing successfully.  

I have managed to isolate this issue in the following way

If I remove `from .utils import getFieldsInstancesArrays` from the beginning of the ukbio.py file, then automodule works correctly:

I.e. by commenting out the first line in ukbio.py
```
#from .utils import getFieldsInstancesArrays
import pandas as pd
import os
```

The following sphinx autodoc works:

```

.. automodule:: ukbiobank.ukbio
    :members:
```


However, this line is necessary for proper functioning of the ukbiobank-tools package. The thing that I can't understand is why when installing and building locally there appears to be no problem. It is not a case of sphinx not being able to install or see ukbiobank-tools , rather it appears to be cause by the importing _within_ the ukbiobank-tools package.

**Comment by stsewd** [comment]
You can try mocking that package https://docs.readthedocs.io/en/stable/faq.html#my-project-isn-t-building-correctly

**Comment by jnecus** [comment]
I have managed to solve this now by fixing an issue with relative imports within the ukbiobank-tools python package.

@stsewd Thank you very much for your help, I appreciate your fast responses.
