### ISSUE TITLE
wxpython dependency causing build fail

### ISSUE THREAD

**Issue by jnecus** [readthedocs/readthedocs.org#7221]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/ukbiobank-tools/
* Build URL: https://readthedocs.org/projects/ukbiobank-tools/builds/11312257/

## Expected Result

Successful build.

## Actual Result

Build fails when wxpython is included in requirements.txt

wxpython is required for this package. Is there a way to ignore this dependency when building docs?

**Comment by stsewd** [comment]
You can have an `extras_require: docs` entry https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies https://docs.readthedocs.io/en/stable/config-file/v2.html#packages

**Comment by stsewd** [comment]
Also, you can make use of https://docs.readthedocs.io/en/stable/faq.html#how-do-i-change-behavior-when-building-with-read-the-docs

**Comment by jnecus** [comment]
Thank you for your suggestions. I have modified by setup.py file in the following way:

```
setup(
    name='ukbiobank-tools',
    url='https://github.com/jnecus/ukbiobank-tools',
    license=license,	
    packages=find_packages(include=["ukbiobank"]),
    package_data={"": ["data_coding/*"]},
install_requires=["pandas"],
    extras_require = {"docs": [ "sphinx",
                                "sphinxcontrib-httpdomain",
                                "sphinx-rtd-theme"]})
```

And I have modified my .readthedocs.yml file in the following way:

```
python:
   version: 3.6
   install:
      - method: pip
        path: .
        extra_requirements:
           - docs
      - method: setuptools
        path: .

```




The issue comes when i try to modify setup.py "install_requires" to include wxpython. E.g. : 

```
install_requires=["pandas", "wxpython"],
    extras_require = {"docs": [ "sphinx",
                                "sphinxcontrib-httpdomain",
                                "sphinx-rtd-theme"]})

```


`wxpython` cannot be installed on readthedocs, citing error '_: The development files for GTK+ were not found._'  (full build failure in link above). Ideally I would like the docs for ukbiobank-tools to be configured but, if necessary, bypass the installation of wxpython.

**Comment by stsewd** [comment]
You can try mocking that package (you need to remove the package from the installation in order for mocking to work as expected)

https://docs.readthedocs.io/en/stable/faq.html#my-project-isn-t-building-correctly

**Comment by stsewd** [comment]
You can use the env variables to not include the `wxpython` package and mock it 

https://docs.readthedocs.io/en/stable/faq.html#how-do-i-change-behavior-when-building-with-read-the-docs
https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by rowlesmr** [comment]
This is still an ongoing issue with wxpython. Including wxpython results in a document build failure
https://readthedocs.org/projects/pvct/builds/15203823/
