### ISSUE TITLE
Add automation rule to make version hidden

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#7230]
Would be good to have an automation rule to mark a version as `hidden`.

**Comment by saadmk11** [comment]
@humitos Will this rule make a version not `active` (in case if it was active previously) also or will it just hide the version?

**Comment by humitos** [comment]
I think that `hidden` and `not active` does not make too much sense because if it's `not active` it's basically ignored by Read the Docs completely.

If we don't want to make it `active` together with `hidden`, the user could create create two rules: one for make it `active` and _another one_ to make it `hidden`. 

cc @stsewd thoughts on this?

**Comment by stsewd** [comment]
Hidden has only effect when the rule is active, so I guess it makes sense to mark it as active and trigger a build as well.
