### ISSUE TITLE
Transfer a project from one account to another.

### ISSUE THREAD

**Issue by jwagantall** [readthedocs/readthedocs.org#7236]
Dear team, 

Would it be possible to get some help transferring a project from one account to another?

We have in the account **(lf-rtd) releng+lf-rtd@linuxfoundation.org** a project called "**onap**" that 
we would like to transfer to the account **(onap-rtd)  collab-it+onap-rtd@linuxfoundation.org**

Can this be possible?

Thanks so much  for your help!
Jess

**Comment by stsewd** [comment]
@jwagantall you can do this by adding the `onap-rtd` account as an owner of the project https://readthedocs.org/dashboard/onap/users/, after that you can remove the `lf-rtd` account from the owners list.

**Comment by jwagantall** [comment]
Thank you so much!.. 

Is there a way to move the history of the builds to the new account? Will adding the onap-rtd user behave as 
if I would have created the project there in first place?

Thank you!

**Comment by stsewd** [comment]
@jwagantall the whole history from the project will remain intact.

**Comment by stsewd** [comment]
Let us know if you have any other questions.
