### ISSUE TITLE
Abandoned project: https://archinstall.readthedocs.io/en/latest/

### ISSUE THREAD

**Issue by Torxed** [readthedocs/readthedocs.org#7242]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/archinstall/

The following project is dead and points towards a [non-existing repo](https://github.com/Sunnlightbro/ArchInstall).
I am the maintainer of [archinstall](https://github.com/Torxed/archinstall) and would like to take over the project's domain-URL.

Is this possible?

**Comment by stsewd** [comment]
Hi, we have a policy for cases like this https://docs.readthedocs.io/en/stable/abandoned-projects.html. I have emailed the user today, waiting for a reply.

/remind me about take action on this project in 6 weeks

**Comment by stsewd** [comment]
Ok, I got a replied. The user said you should contact it directly to work something out. Please email us at support@readthedocs.org linking to this issue to give you an email were you can reach the user.

**Comment by Torxed** [comment]
@stsewd Just want to let you know that I sent a e-mail referring to this ticket number by `#7242` in the subject and body of the e-mail. Thank you for the quick responses.

**Comment by Torxed** [comment]
/remind me ask what I should do if no answer in 3 weeks

**Comment by stsewd** [comment]
@Torxed since I already contacted the user, and the user stated its preference there isn't anything else we can do about it.

**Comment by stsewd** [comment]
you can try using a custom domain or something like `arch-install` if you don't receive an answer.

**Comment by Torxed** [comment]
So, if the user responds to the core team - stating that a new means of communication should be initiated to resolve the issue.
But then completely disregard that information/promise, the core team can't or won't do anything
That would mean, all I need to do - to lock readthedocs.io in a dead spot - would be to create a automatic reply to anything from `@readthedocs.io` and there's nothing you can do. Which means you are a backup service, despite:

> While Read the Docs is not a backup service

I mean, I can use custom domains, but I'd prefer not to. Especially since there's *obsolete information* laying around actually causing more harm than good since *a lot* has changed with the Arch Linux installation process. This particular documentation *(archinstall)* hasn't been updated in over two years. So I thought I'd try to correct this. I can give e-mail another shot, but you should probably look over this particular policy, especially the [Reachability](https://docs.readthedocs.io/en/stable/abandoned-projects.html#reachability) section as it's pretty weak in enforcing it's own policy if the above is true.

A better approach to this policy for everyone, without affecting the responsibility of the owner of the documentation, would be if read the docs perhaps didn't try to mediate or enter into conflicts, but at least gave more flexibility to which degree the owner has to respond in the matter. The user accepted a new means of contact. This new means of contact *(between two parties)* should apply the same policy - meaning response within six weeks or the communication should be considered unanswered. Thus, rendering the project abandoned.

Either way, it's not the end of the world, but this felt like an odd policy as a end user.

**Comment by stsewd** [comment]
Since we already contacted the user and got a response, the reachability section doesn't apply. The user didn't want to give the project name, but it was open to work something out with you (this is outside the policy).

Agree that a malicious user could just reserve several popular names (we have had this in the past), but in that case would be pretty clear the intention of that user, and we can take other options in those cases.

Agree that an outdated documentation isn't good, but we can't force our users to change some content from one of their projects (at least if it doesn't involve something like https://docs.readthedocs.io/en/stable/dmca/index.html).

**Comment by stsewd** [comment]
Also, just an idea, we could email all owners of projects that haven't been updated in a while, just as a reminder.
