### ISSUE TITLE
Edit on Github Link Broken, Missing Project [mkdocs]

### ISSUE THREAD

**Issue by Breakthrough** [readthedocs/readthedocs.org#7246]
## Details

* Read the Docs project URL: https://pyscenedetect.readthedocs.io/
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): Breakthrough

## Expected Result

*Edit on PySceneDetect on Github* (top right of page) should link to https://github.com/Breakthrough/PySceneDetect/edit/master/docs/index.md

## Actual Result

*Edit on PySceneDetect on Github* links to https://github.com/Breakthrough/edit/master/docs/index.md which yields "Not Found".

Thank you!

**Comment by stsewd** [comment]
I believe this is generates from the repo_url setting https://github.com/Breakthrough/PySceneDetect/blob/63ea7587d458b50b5f14981d9a34ac1faaf64c62/mkdocs.yml#L5

**Comment by Breakthrough** [comment]
Whups, sorry about that.   Definite oversight on my part - thanks for letting me know!
