### ISSUE TITLE
Fail to build latex PDF on one lang (on eleven)

### ISSUE THREAD

**Issue by trasher** [readthedocs/readthedocs.org#7249]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/galette-ar/ (translation) - https://readthedocs.org/projects/galette/ (main)
* Build URL (if applicable): https://readthedocs.org/projects/galette-ar/builds/11348153/
* Read the Docs username (if applicable): trasher

## Expected Result

Build success.

## Actual Result

The build fails on ar language only, with something wrong in building PDF. I had to disable PDF building to get galette-ar compiled. Project has 11 languages and all is working fine for all others.

I do not even understand what is really wrong :/

Thank you!

**Comment by stsewd** [comment]
Sorry for the late reply, if you run the same steps locally, can you replicate the problem? Maybe some char in that language that doesn't like to sphinx.
