### ISSUE TITLE
/en/latest/ is not serving index.html file

### ISSUE THREAD

**Issue by namaggarwal** [readthedocs/readthedocs.org#7250]
## Details

* Read the Docs project URL: https://splitwise.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/splitwise/builds/11361999/
* Read the Docs username (if applicable): namaggarwal

## Expected Result
https://splitwise.readthedocs.io/en/latest/ should show the docs 

## Actual Result
https://splitwise.readthedocs.io/en/latest/  shows the default "Welcome to.." page

Note that https://splitwise.readthedocs.io/en/latest/index.html shows the correct page

**Comment by stsewd** [comment]
Probably the cache, I can see the correct page. Try in a private window.

**Comment by namaggarwal** [comment]
Yes, looks like it was cached. Thank you
