### ISSUE TITLE
Unable to trigger build anymore

### ISSUE THREAD

**Issue by tapczan** [readthedocs/readthedocs.org#7256]
Read the Docs project URL: https://readthedocs.org/projects/gdpr-plugin/
Read the Docs username createit
Hello,
When I try to build a new version of my documentation, I get the message "This project is currently disabled.".

Expected Result
I wish my project to be enabled and to be able to build new version of my doc.
Appreciate your help,
Alex

**Comment by davidfischer** [comment]
Your account was flagged as spam. You are now unbanned and can build again.
