### ISSUE TITLE
Proxy our embed js to serve it from the same docs domain

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#7273]
Currently, ad blockers/privacy badger block this resource https://assets.readthedocs.org/static/javascript/readthedocs-doc-embed.js

And with that it breaks search and other things that depend on it. I'm opening this ticket in case there is a downside of doing this.

**Comment by ericholscher** [comment]
We should consider this with all our embeds.

**Comment by ericholscher** [comment]
@stsewd I haven't noticed privacy badger blocking this URL. It doesn't set cookies, so I'm not sure why it would be blocked.

**Comment by ericholscher** [comment]
@stsewd I'd still like to do this, and it would be useful for both our domains to keep all our CDN configuration on a single domain for a site. Going to add this to the backlog.
