### ISSUE TITLE
Text at the top of "Import a Repository" doesn't read well.

### ISSUE THREAD

**Issue by domdfcoding** [readthedocs/readthedocs.org#7283]
The text at the top of https://readthedocs.org/dashboard/import/ currently reads as follows:

> We're only showing public repositories. For private projects and many of features, please use Read the Docs for Business. 

However, it doesn't make sense. I think it's supposed to read something like:

> We're only showing public repositories. For private projects and many **other** features, please use Read the Docs for Business. 

The present wording was originally merged in #5849

**Comment by DougCal** [comment]
Going to look into this
