### ISSUE TITLE
Running out of memory when building html files

### ISSUE THREAD

**Issue by tardyb** [readthedocs/readthedocs.org#7298]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/iota2/
* Build URL (if applicable): https://readthedocs.org/projects/iota2/builds/11474743/
* Read the Docs username (if applicable): iota2

## Expected Result

Documentation should be produced.

We have three branches on your project:
- master
- latest
- issue218-developer_doc

latest and issue218 contains same code, and have same configuration.

## Actual Result

The build on latest seems to succeed, as at the end of source file we have:

> build succeeded, 1578 warnings.
> The HTML pages are in _build/html.
> Updating searchtools for Read the Docs  search...

but the global status is 

> Build exited due to time out

I try [again](https://readthedocs.org/projects/iota2/builds/11474982/) to build documentation and obtain the following error:

>  Command killed due to excessive memory consumption

and again

> Build exited due to time out

The build on issue218 succeed.

**Comment by humitos** [comment]
Thanks for the report. I increased your build time and memory resources. Feel free to contact us at our support email if the problem persists.
