### ISSUE TITLE
Build error with build id #11492484

### ISSUE THREAD

**Issue by ssbarnea** [readthedocs/readthedocs.org#7304]
## Details:

* Project URL: https://readthedocs.org/projects/ansible-lint/
* Build URL(if applicable): https://readthedocs.org/projects/ansible-lint/builds/11492484/
* Read the Docs username(if applicable): ssbarnea

## Expected Result

Success

## Actual Result

All tasks were a success (exit code 0) but build failed without any explanation or possibility to retrigger it.

**Comment by humitos** [comment]
Thanks for the report. That was an internal Read the Docs issue. It seemed it was just temporal and there are more builds of the same version after that failure that passed correclty. Please, keep us posted if this is happening several times.
