### ISSUE TITLE
Docs shown for some another project (geographiclib) and not for my project

### ISSUE THREAD

**Issue by jpsnir** [readthedocs/readthedocs.org#7309]
## Details

* Read the Docs project URL:https://github.com/jpsnir/gtsam.git
* Build URL (if applicable):https://doc-gtsam.readthedocs.io/en/latest/
* Read the Docs username (if applicable):jpsnir

## Expected Result
I am new to read the docs. I forked a project from this url : https://github.com/borglab/gtsam to my github account https://github.com/jpsnir/gtsam.git. The branch where I am committing my docs is devel. The folder is docs.

The current state of my documentation in docs folder is:
![read_the_docs](https://user-images.githubusercontent.com/47287420/88100349-6b932a00-cb6a-11ea-9660-fc27372140f2.png)

## Actual Result

The project after building is not showing me the right results. It shows me a webpage from geographiclib
![image](https://user-images.githubusercontent.com/47287420/88100411-7f3e9080-cb6a-11ea-9ec5-9b707ceae166.png)

**Comment by jlblancoc** [comment]
It must be related to geographiclib being embedded into the gtsam repo...
Perhaps the doc source directory is automatically detected by rtd web and it guessed incorrectly? 
Will look tomorrow, but there should be a setting for that on the web?

**Comment by stsewd** [comment]
If you are new to Read the Docs, please check https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html for an intro. What you are missing is to set the correct doc directory, you can do this with a configuration file https://docs.readthedocs.io/en/stable/config-file/v2.html

Specially the sphinx option https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx

**Comment by jlblancoc** [comment]
Thanks, Santos!

@jpsnir : Yes, please, add a root file `.readthedocs.yml` which unambiguously points to the correct file under `/doc`.

**Comment by jlblancoc** [comment]
Fixed now: https://doc-gtsam.readthedocs.io/en/latest/

Can be closed.
