### ISSUE TITLE
Minor UI tweak request: clickability affordances on build page

### ISSUE THREAD

**Issue by joseph-long** [readthedocs/readthedocs.org#7319]
## Details

A colleague asked me to help debug a new RTD project. I looked at the build output, clicked the build command, and found the error message. They were unaware that the entries on the build page could be clicked at all. Upon reflection, there's no disclosure arrow, 'expand' button, or underlined text to indicate those headings are clickable. That would be nice to have.

## Expected Result

User would see how to inspect the RTD output on the build page with a button, underlined text, or similar.

![image](https://user-images.githubusercontent.com/31168267/88434131-5c9fb800-cdb4-11ea-9793-9fcdfe63754a.png)

## Actual Result

User was unaware of clickable CI steps as a UI convention, frustrated by lack of debugging output.

![image](https://user-images.githubusercontent.com/31168267/88433913-e13e0680-cdb3-11ea-83c9-8ba149b37dbe.png)

**Comment by humitos** [comment]
Thanks for your suggestion. We are working on a complete new set of templates and look & feel for the site. We will consider your comment when working on this page.

**Comment by agjohnson** [comment]
I believe this is already a feature of the new build output page, but I'll leave this on our roadmap to remind myself to check.

**Comment by humitos** [comment]
To anyone arriving at this issue, you can see the page from the screenshot by using the current **beta** version of the new dashboard that we have published at https://beta.readthedocs.org. Expect some things to fail or not work at all 😅 --but you can start exploring it at least 😉
