### ISSUE TITLE
Does "Show Version Warning" apply to non-default versions.

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#7323]
Our default branch is not-latest and not-stable, but we want the version warning to show in not-default versions.

![image](https://user-images.githubusercontent.com/10674555/88563453-fe671500-cfff-11ea-9855-4a813e26901c.png)

**Comment by stsewd** [comment]
The version warning will be shown on versions that follow semver and are lower than the default version.

**Comment by stsewd** [comment]
You can use this extension if you want to have more control over it https://github.com/humitos/sphinx-version-warning

**Comment by Daltz333** [comment]
Thank you, I'll keep that in mind.
