### ISSUE TITLE
Replace `master` with `main`

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#7327]
There's a number of places that we use `master` still in both our repositories and code. We should look at addressing this in a way that isn't super disruptive. It seems the consensus has been with replacing it with `main`, and we should be supporting that. I'm thinking:

* We can change *our* repos to default to `main`
  * We need to change some CI & deployment scripts, at a minimum
* We can look for a `main` branch to map to `latest`, falling back to `master` only if `main` isn't found
  * We probably need to make this visible to users and explain it in documentation. 

I'm sure there's other places where we should be considering changing this, but wanted to make sure we had an issue open to track it.

**Comment by tannewt** [comment]
We did this switch in CircuitPython and it went smoothly. The Scott Hanselman blog post is a good reference.

**Comment by KPrasch** [comment]
Commenting here to prevent this Issue from being closed by the bot!

**Comment by moble** [comment]
+1 In the mean time, is there any way for users to set the default branch manually?  I have a couple repos with a `main` but no `master` branch, and the "latest" path is constantly screwing me up.  (Though these packages don't yet have many users, so I'm probably the only one being screwed up :)

**Comment by jaraco** [comment]
Same here. It would be nice if there were an API or config file override to accommodate the transition without having to muddle through the API for every project.

**Comment by ericholscher** [comment]
I don't fully understand the problem, can you explain a bit more what would be needed? We've added a few different accommodations to help with this for new repos, but I don't fully understand the issues you're hitting.

**Comment by stsewd** [comment]
@jaraco with API v3 you can do that https://docs.readthedocs.io/en/stable/api/v3.html#project-update (`default_branch`).

@moble on import you can select the "Advanced options"

![Screenshot_2020-12-14 Add a Project Read the Docs](https://user-images.githubusercontent.com/4975310/102105537-88701880-3dfd-11eb-8854-e70d18b8d090.png)

There you have the option to change the default branch before importing. We are working on having a better workflow to use that data from github/gitlab instead https://github.com/readthedocs/readthedocs.org/pull/7702

BTW, this issue is about changing the branch name in our repos, not the projects hosted on rtd

**Comment by moble** [comment]
@stsewd Yes, things are working fine for me now.  I don't know if my comment above pre-dated some improvement to the RTD side of things, or if I just didn't understand how it works, but I agree that I can set it manually.  Thanks!

**Comment by stsewd** [comment]
@moble yeah, this was added just a couple of weeks ago, no worries.

**Comment by jaraco** [comment]
> I don't fully understand the problem, can you explain a bit more what would be needed? We've added a few different accommodations to help with this for new repos, but I don't fully understand the issues you're hitting.

The issue I had, which may have had other factors involved, is I switched a repo's main branch from `master` to `main` and then noticed that docs weren't erroring but they weren't updating either. They would build but the docs would be out of date. Even after switching the default branch to the intended branch, the updates still weren't taking effect, though it may be that I just didn't wait long enough for the caches to clear. Today, I see the updates taking effect, so I suspect the changed branch was implicated, though I'm not sure.

**Comment by jaraco** [comment]
I ended up writing this routine, written in [xonsh](https://xon.sh) and relying on [httpie](https://httpie.org) and [keyring](https://pypi.org/project/keyring) to update the main branch:

```
def move_rtd(repo):
	org, _, project = repo.partition('/')
	rtd_name = project.replace('.', '')
	auth = 'Token ' + keyring.get_password('https://api.readthedocs.org/', 'token')
	http patch https://readthedocs.org/api/v3/projects/@(rtd_name)/ Authorization:@(auth) default_branch=main
```

**Comment by jaraco** [comment]
> Even after switching the default branch to the intended branch, the updates still weren't taking effect, though it may be that I just didn't wait long enough for the caches to clear. Today, I see the updates taking effect, so I suspect the changed branch was implicated, though I'm not sure.

Today, I more carefully forced refreshes after updating the default branch and rebuilding and the project ([setuptools](https://readthedocs.org/projects/setuptools)) started building again.

**Comment by edwardoughton** [comment]
> @jaraco with API v3 you can do that https://docs.readthedocs.io/en/stable/api/v3.html#project-update (`default_branch`).
> 
> @moble on import you can select the "Advanced options"
> 
> ![Screenshot_2020-12-14 Add a Project Read the Docs](https://user-images.githubusercontent.com/4975310/102105537-88701880-3dfd-11eb-8854-e70d18b8d090.png)
> 
> There you have the option to change the default branch before importing. We are working on having a better workflow to use that data from github/gitlab instead #7702
> 
> BTW, this issue is about changing the branch name in our repos, not the projects hosted on rtd

This worked for me - thanks!

**Comment by astrojuanlu** [comment]
Just reminding people that this issue is about RTD changing the default branch of our repositories. For the issue of how to get RTD to detect such renaming for your own projects, please head over to #7907.

@ericholscher about our repos: is this something that you want to do all at once? Or perhaps we can start with smaller repos first?

**Comment by ericholscher** [comment]
> @ericholscher about our repos: is this something that you want to do all at once? Or perhaps we can start with smaller repos first?

I think we should try and do them close in time, so we can manage the annoyance of having it be different, but we should at least test with a few smaller repos first. It's definitely going to break our deployments or builds _somewhere_, but I'd like to be systematic about it if possible.

**Comment by ericholscher** [comment]
This is now done 👍
