### ISSUE TITLE
Disable shallow clone for sphinxcontrib.spelling

### ISSUE THREAD

**Issue by dhellmann** [readthedocs/readthedocs.org#7331]
Based on the discussion in #5031 it looks like I need to ask for an admin to change the feature flag so that builds of sphinxcontrib.spelling do not use shallow clones in order for reno to work properly.

## Details

* Read the Docs project URL: https://readthedocs.org/projects/sphinxcontrib-spelling/
* Build URL (if applicable): https://readthedocs.org/projects/sphinxcontrib-spelling/builds/11547392/
* Read the Docs username (if applicable): doughellmann

## Expected Result

Documentation using reno for release notes should build without errors because the git history is not present.

## Actual Result

Reno threw an error because a referenced commit was missing from the local clone.

**Comment by humitos** [comment]
Done! Let me know if anything and feel free to reopen.

**Comment by humitos** [comment]
I triggered a built https://readthedocs.org/projects/sphinxcontrib-spelling/builds/11551792/ and it worked :smile:

**Comment by dhellmann** [comment]
Thank you, @humitos !
