### ISSUE TITLE
A deleted Github organization keeps appearing in my account

### ISSUE THREAD

**Issue by sbslee** [readthedocs/readthedocs.org#7335]
## Details

* Read the Docs project URL: https://pypgx.readthedocs.io/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable): sbslee

## Expected Result

My latest open source project is called PyPGx and it was initially hosted by a Github organization I created (pypgx). Therefore, its Github repository was https://github.com/pypgx/pypgx.git. However, I decided later that it should be hosted by my personal account, so I **transferred** the repository (https://github.com/sbslee/pypgx.git) and **removed** the organization (pypgx). Since then, everything has been working perfectly, including Read the Docs.

## Actual Result

My only issue -- and this is very minor -- is that the pypgx organization keeps appearing in my account as you can see in the image below. It's not causing any issues functionally, but because I want everything clean, it would please my eyes very much if I don't have to see the already deleted organization in my account. I tried to this by going to Settings, but no success. Could this be a bug? I feel like Read the Docs should automatically sever any connections to a Github account or organization that has been deleted already. Please let me know if I'm mistaken. Thank you!
 
![Screen Shot 2020-07-29 at 5 33 11 PM](https://user-images.githubusercontent.com/21111749/88777861-ae847b80-d1c2-11ea-8ef8-0523eeb31911.png)

**Comment by humitos** [comment]
This is duplicated of #2412 and will be fixed by #7310. Please, subscribe there to keep you updated.
