### ISSUE TITLE
ERROR: NetworKit compilation requires cmake. error: Setup script exited with 1

### ISSUE THREAD

**Issue by benedekrozemberczki** [readthedocs/readthedocs.org#7337]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/little-ball-of-fur/
* Build URL (if applicable): https://readthedocs.org/projects/little-ball-of-fur/builds/11554478/
* Read the Docs username (if applicable): benedek.rozemberczki

## Expected Result

*Cmake should be in the container.*

## Actual Result

*Cmake is not present, Networkit installation and build fails.*

**Comment by stsewd** [comment]
If you don't need that library to build your docs, you can mock it and remove that requirement from the installation when building on rtd https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules
