### ISSUE TITLE
Build failed- Could not import extension sphinxcontrib.napoleon in readthedocs?

### ISSUE THREAD

**Issue by aakriti0fnu** [readthedocs/readthedocs.org#7341]
I was using you wonderful [sphinx extension](https://github.com/sphinx-contrib/napoleon) and was able to generate documentation for my project locally:

https://imgur.com/5t1uguh

but, later [after pushing my code to github](https://github.com/aakriti0fnu/dl4sci-school-2020), and importing to [readthedocs](https://readthedocs.org/projects/dl4sci-school-2020/builds/11558213/), the build process failed with an error:
```
Extension error:
Could not import extension sphinxcontrib.napoleon (exception: No module named 'sphinxcontrib.napoleon')
```
https://imgur.com/Nn1jx1w
https://readthedocs.org/projects/dl4sci-school-2020/builds/11558213/
Do you know how to fix it?

[I opened an issues on the authors repository too.](https://github.com/sphinx-contrib/napoleon/issues/26)

**Comment by humitos** [comment]
Hi @aakriti0fnu! You need to tell Read the Docs to install that extension. Please, take a look at this guide https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html and let me know if that works.

**Comment by aakriti0fnu** [comment]
> Hi @aakriti0fnu! You need to tell Read the Docs to install that extension. Please, take a look at this guide https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html and let me know if that works.

thank you @humitos , 

1. I created these `docs/requirements.txt & .readthedocs.yml` following your advice: [Commit](https://github.com/aakriti0fnu/dl4sci-school-2020/commit/12d12cdbff7e7757218a8eca4159775994a89642).

2. then, I got [Sphinx error: master file {..}/checkouts/latest/contents.rst not found](https://github.com/readthedocs/readthedocs.org/issues/2569), I fixed it: [Commit](https://github.com/aakriti0fnu/dl4sci-school-2020/commit/69921f69a44cd8b8fdffa915fd9a7fa3e72e5a93)

It's fixed now, [here is documentation](https://dl4sci-school-2020.readthedocs.io/en/latest/utility.html)
