### ISSUE TITLE
Unable to build docs, getting weird build command using gitub.com

### ISSUE THREAD

**Issue by deeplook** [readthedocs/readthedocs.org#7342]
I'm having trouble to generate docs for an emerging project, 

* Read the Docs project URL: https://readthedocs.org/projects/pyteen/
* Build URL: https://readthedocs.org/projects/pyteen/builds/11559831/
* Read the Docs username: dinugherman

## Expected Result

The docs should be generated as expected.

## Actual Result

The following command is run, e.g. in the sample build above (notice what appears to be a typo in `gitub.com`):

`git clone --no-single-branch --depth 50 https://gitub.com/deeplook/pyteen .`

**Comment by stsewd** [comment]
@deeplook yes, there is a typo in your repo, you should change it in https://readthedocs.org/dashboard/pyteen/edit/
