### ISSUE TITLE
TeX capacity exceeded

### ISSUE THREAD

**Issue by pmeier** [readthedocs/readthedocs.org#7344]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pystiche/
* Build URL (if applicable): https://readthedocs.org/projects/pystiche/builds/11559074/
* Read the Docs username (if applicable): `pmeier`

## Expected Result

`latexmk -r latexmkrc -pdf -f -dvi- -ps- -jobname=pystiche -interaction=nonstopmode` should produce a `PDF`.

## Actual Result

```
! TeX capacity exceeded, sorry [main memory size=5000000].
[...]
!  ==> Fatal error occurred, no output PDF file produced!
```

From the error message I found [this on Tex Stackexchange](https://tex.stackexchange.com/questions/7953/how-to-expand-texs-main-memory-size-pgfplots-memory-overload). It seems as the Tex memory is somehow exhausted.

My `html` build works just fine, so I don't think that [my build is using too much resources](https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html). Then again, everything was working fine yesterday and I didn't add anything memory intensive. Maybe I was just below the threshold all the time.

**Comment by stsewd** [comment]
@pmeier maybe it was a temporal error, can you try building again?

**Comment by pmeier** [comment]
@stsewd Any updates on this? Maybe I can help debug this if that is an issue.

**Comment by stsewd** [comment]
So, your build is already using one of our large builders. I think this may be related to latex itself, and we need to set the `--extra-mem-bot=10000000` option, I'll see if I can replicate this locally and test with that option.

**Comment by stsewd** [comment]
@pmeier can you try disabling the singlehtml format https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html#reduce-formats-you-re-building?

**Comment by pmeier** [comment]
@stsewd 

> can you try disabling the singlehtml format

I'm not sure how to do that. The [documentation states](https://docs.readthedocs.io/en/stable/config-file/v2.html#formats) I can only enable / disable the formats `htmlzip`, `pdf`, and `epub`. Could you tell me how to disable `singlehtml`?

**Comment by pmeier** [comment]
The [build](https://readthedocs.org/projects/pystiche/builds/11613645/) with

```yml
version: 2

formats:
  - pdf

python:
  version: 3.6
```

succeeded!

**Comment by stsewd** [comment]
@pmeier htmlzip is the one that generates the single html format, your config file is right. Feel free to ask again if you experience this issues again.

**Comment by pmeier** [comment]
@stsewd Something else must have changed. For testing purposes I went back to `formats = all` and the [build](https://readthedocs.org/projects/pystiche/builds/11613675/) is still succeeding. Could you tell me how you fixed it? I ran into a similar problem locally and couldn't get `latexmk` to accept a higher `main_memory`.

**Comment by stsewd** [comment]
@pmeier nothing changed from our side

**Comment by pmeier** [comment]
This is really weird. Thanks a lot for the support :smile:
