### ISSUE TITLE
Python class attributes don't show up in generated docs

### ISSUE THREAD

**Issue by carrotIndustries** [readthedocs/readthedocs.org#7347]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/horizon-eda/

## Expected Result

On https://horizon-eda.readthedocs.io/en/latest/python.html#d-rendering-usage python attributes defined in https://github.com/horizon-eda/horizon-docs/blob/master/python.rst#3d-rendering-usage should show up (they do when building locally)

## Actual Result

Attributes don't show up.

**Comment by stsewd** [comment]
@carrotIndustries there are some warnings in your build

> /home/docs/checkouts/readthedocs.org/user_builds/horizon-eda/checkouts/latest/python.rst:92: WARNING: Error in "py:attribute" directive:
unknown option: "type".

You can check by clicking on the build steps https://readthedocs.org/projects/horizon-eda/builds/11571445/

I think you are missing installing the requirements for your project, if you try building in a clean environment you'll get the same errors. See https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

**Comment by carrotIndustries** [comment]
> You can check by clicking on the build steps https://readthedocs.org/projects/horizon-eda/builds/11571445/

Thanks for the hint. Seems like RTD is using an older version of sphinx:
> Running Sphinx v1.8.5

Howver, the docs https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#directive-option-py-attribute-type mention that this attribute first appeared in version 2.4. I haven't yet found a way to tell RTD to use  newer sphinx version.

**Comment by stsewd** [comment]
@carrotIndustries you can do that using a requirements file https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

**Comment by carrotIndustries** [comment]
Thanks a lot! That was surprisingly easy: https://github.com/horizon-eda/horizon-docs/commit/5c73380293831028336a013761735bafbb3a8adb
