### ISSUE TITLE
Search is a litte slow in rtd.com compared to rtd.org

### ISSUE THREAD

**Issue by sysdl132** [readthedocs/readthedocs.org#7349]
![image](https://user-images.githubusercontent.com/54708046/89102102-843bf380-d438-11ea-9b4f-9a54cf463509.png)
Searching?takes me about 5 seconds.(but google never happen like this...can you use a better search engine?)

**Comment by stsewd** [comment]
Do you have a project URL?

**Comment by sysdl132** [comment]
https://docs.divio.com
(This is **NOT** my website.But I think the search may be faster,not like this)

**Comment by Daltz333** [comment]
That site you gave was not valid and does not load. @stsewd close for no response?

**Comment by stsewd** [comment]
@Daltz333 it does load for me. Actually that site is using readthedocs.com. We do see slower time responses compared to search in reathedocs.org. So we are investigating why is that. We did try something last week, so it should be a little faster than before, but not that faster... we are still checking.

**Comment by Daltz333** [comment]
Ah, it was down for me when I asked. Thank you.

**Comment by stsewd** [comment]
BTW, we are planning to upgrade to ES 7.x https://github.com/readthedocs/readthedocs.org/issues/5620, there are performance improvements in that release  https://www.elastic.co/blog/elasticsearch-7-0-0-released

**Comment by stsewd** [comment]
Another thing I want to try is excluding some fields from the results, we don't use the whole document in the api.

**Comment by stsewd** [comment]
We have upgraded ES to 7.x in both sides (includes some improvements in performance). Additionally, we have deployed the new ES instances to the same zone as the main site instances. And also we merged two PRs to improve performance https://github.com/readthedocs/readthedocs.org/pull/7640 https://github.com/readthedocs/readthedocs.org/pull/7724
