### ISSUE TITLE
Project tags can not be updated using the API

### ISSUE THREAD

**Issue by nijel** [readthedocs/readthedocs.org#7354]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/weblate/

## Expected Result

The [projects API](https://docs.readthedocs.io/en/stable/api/v3.html#projects) does include project tags, but it's not possible to update it or set when creating new projects. 

## Actual Result

When including tags in the request, it gets silently ignored.

Another source of confusion might be that ProjectCreateSerializer and ProjectCreateSerializer are different - is there any reason to allow less fields in project creating than later in updating it?

**Comment by stsewd** [comment]
> Another source of confusion might be that ProjectCreateSerializer and ProjectCreateSerializer are different - is there any reason to allow less fields in project creating than later in updating it

I think that was done to mimic the import page, but if we don't have a strong reason, I think it makes sense to allow all the fields

**Comment by humitos** [comment]
>  I think it makes sense to allow all the fields

I'm fine adding support to change most (or all) the fields at this point.

**Comment by SyedMa3** [comment]
@humitos  Is this issue still open?

**Comment by humitos** [comment]
@SyedMa3 yes

**Comment by benjaoming** [comment]
Fixed in https://github.com/readthedocs/readthedocs.org/pull/9513 - thanks to @SyedMa3 for this contribution :+1:
