### ISSUE TITLE
importation of compiled submodule failed (related to cython ?)

### ISSUE THREAD

**Issue by jimy-byerley** [readthedocs/readthedocs.org#7357]
## Details

Hi,

I have a problem with my documentation (my first published with doc, so I don't really know if the problem comes from my configuration). `sphinx-build` is compiling fine on my computer, pip install works also fine in venv, and it seems to work fine on the readthedoc server too.

The functions can't be documented because the module can't be imported due to a compiled submodule that is not found ... for unexplainable reasons: the compilation log shows that `core.pyx` is well compiled as `core.c` that is cell compiled into `core-xxxx.so` 

* Read the Docs project URL:  https://readthedocs.org/projects/pymadcad/
* Build URL (if applicable):  https://readthedocs.org/api/v2/build/11589820.txt
* Read the Docs username (if applicable): jimy-byerley

## Expected Result

documentation for the API functions: https://pymadcad.readthedocs.io/en/latest/reference/mesh.html

## Actual Result

No function is found in the module, due to an ImportError, therefore, no content in the API  documentation section

Is there something wrong in my configs ? Is there a known issue with this part of readthedoc ?

**Comment by stsewd** [comment]
Please check https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by stsewd** [comment]
Can you try using pip instead of setuptools to install your project? https://docs.readthedocs.io/en/stable/config-file/v2.html#packages

**Comment by jimy-byerley** [comment]
Just tried: That's working as well

**Comment by jimy-byerley** [comment]
What are these lines from the log ?
```
creating stub loader for madcad/core.cpython-37m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/madcad/core.py to core.cpython-37.pyc
```

There is no `core.py` in the project but a `core.pyx`
That may be related to the issue in finding module core.

**Comment by stsewd** [comment]
> Just tried: That's working as well

You mean isn't working?

**Comment by stsewd** [comment]
Can you link me to the config file you created?

**Comment by jimy-byerley** [comment]
> You mean isn't working?
No, `pip install .` is working

> Can you link me to the config file you created?
What config file ?
- sphinx conf.py is at https://github.com/jimy-byerley/pymadcad/blob/master/docs/conf.py
- .readthedocs.yml doesn't exist in my repo since I thought it was optionnal
May I create a .readthedocs.yml ?

**Comment by stsewd** [comment]
> May I create a .readthedocs.yml ?

Yes, you can use pip using a rtd config file only, so not sure how were you able to install your package using pip in rtd.

**Comment by stsewd** [comment]
Also, if it's working with pip, then you should use pip to install your package. Using `setup.py install` is kind of being deprecated.

**Comment by jimy-byerley** [comment]
Ok, yet an other config file.
What does the rtd config bring the setup.py doesn't define ?

**Comment by stsewd** [comment]
They are specific platform settings https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings. We like the user being explicit on how to build a project rather than guessing, that brings a lot of problems otherwise.

**Comment by jimy-byerley** [comment]
All this settings are already present in the project configuration page on the website isn't it ?

I added the file. The result is exactly the same on the RTD doc: submodule `core` not found.

**Comment by stsewd** [comment]
> All this settings are already present in the project configuration page on the website isn't it ?

Not all of them, we are moving to have specific settings per version, rather than global settings.

**Comment by jimy-byerley** [comment]
Still, I can't get why it successfully compile and install the module, but it doesn't copy or it doesn't find the compiled submodule. It's working perfectly on my computer even in venv, what's different here ? 
Is there a way to check the file trees produced by the RTD compilation ?

**Comment by stsewd** [comment]
Looks like you are missing to install the package itself. Try with

```yaml
python:
  version: 3.7
  install:
    - path: .
      method: pip
    - requirements: docs/requirements.txt
```

**Comment by jimy-byerley** [comment]
The same

**Comment by stsewd** [comment]
Ok, I just saw the config file isn't having effect https://readthedocs.org/projects/pymadcad/builds/11603667/

Looks like there is a typo in the file name https://github.com/jimy-byerley/pymadcad/blob/4bdad61999e828b0cbad7dfbf1f88bb0fda6c896/.readthedoc.yml

it should be `/.readthedocs.yml`

**Comment by jimy-byerley** [comment]
renamed.
This time it's different ! The compiler doesn't find `core.c`. It seems that the installer didn't installed Cython this time.

**Comment by jimy-byerley** [comment]
What do you think about the last result ? I don't really know what to do since there is a requirement file stating cython.

**Comment by jimy-byerley** [comment]
In get a bit deeper into the error logs: The issue is that the compilation from readthedoc side doesn't occur as expected:

My module contains sources to compile, Sphinx can't autodoc without importing the complete compiled module. So I have to check the option "install" in the config page (or in the .readthedoc.yml). 
### The issue is that still the online compilation doesn't use the installed module, but is trying to import the sources, thus failing. 

* In the log, the repository is installed from the cloned repo
   ```bash
   /docs/checkouts/readthedocs.org/user_builds/pymadcad/checkouts/latest/setup.py install --force
   ```
* Installation states:
    ```
    Extracting pymadcad-0.2-py3.7-linux-x86_64.egg to /home/docs/checkouts/readthedocs.org/user_builds/pymadcad/envs/latest/lib/python3.7/site-packages
    ```
    So the repo is the `checkouts` folder and the installed lib is in `envs`

* After installation, the doc is generated from the source folder `checkouts`:
    ```
    cannot import name 'core' from 'madcad' (/home/docs/checkouts/readthedocs.org/user_builds/pymadcad/checkouts/latest/madcad/__init__.py)
    ```

This occurs because the sphinx generation is done in the current directory that is the cloned repo, so there is already a folder called `madcad`, that is used instead of the installed module.
It's easy to fix:  just make the compilation proceed in an other folder !

**Comment by stsewd** [comment]
If you need for sphinx to import the installed package instead from source, I think you can remove https://github.com/jimy-byerley/pymadcad/blob/89a55b7571741b9afecfccc89a59f4a5e352d676/docs/conf.py#L17 and that will work. We can't (or don't plan) to change the cwd from where the compilation happens as that will break other people's builds.

**Comment by stsewd** [comment]
I think using -e would also fix this https://github.com/readthedocs/readthedocs.org/issues/6243

**Comment by jimy-byerley** [comment]
It works ! Thanks !
I will checkout the option -e also, thanks for the advice :)

**Comment by stsewd** [comment]
It's working https://pymadcad.readthedocs.io/en/latest/reference/mesh.html, so I think we can close this. Feel free to ask to reopen if not.
