### ISSUE TITLE
Some builds are using the default queue and others the large queue (isn't deterministic)

### ISSUE THREAD

**Issue by chrisjsewell** [readthedocs/readthedocs.org#7360]
## Details

* Read the Docs project URL: https://myst-parser.readthedocs.io
* Build URL (if applicable):
* Read the Docs username (if applicable): ebp-bot

The following are what should be two identical builds:

- from branch: https://readthedocs.org/projects/myst-nb/builds/11599698/
- latest: https://readthedocs.org/projects/myst-nb/builds/11599522/

However, the second fails.

Looking for differencesm the only one I can see is that sphinx-build is called slightly differently:

- from branch: `python /home/docs/checkouts/readthedocs.org/user_builds/myst-nb/envs/release-0.8.5/bin/sphinx-build -T -E -W --keep-going -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html`
- latest: `python /home/docs/checkouts/readthedocs.org/user_builds/myst-nb/envs/latest/bin/sphinx-build -T -W --keep-going -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html`

Note that latest is not called with the `-E` flag ("don't use a saved environment, always read all files")

Is this an intentional difference?

Cheers, Chris

**Comment by stsewd** [comment]
So, the `-E` option shouldn't make any difference, as we always build from nothing on every build (probably we should remove that option from all builds). I can see the builds that failed were using a smaller builder and the builds that pass were using one of our larger builders. I'm not sure how we decide the build queue these days, I'm looking into it.

**Comment by chrisjsewell** [comment]
Thanks @stsewd yeh its a bit frustrating at present lol, because PR builds pass but then you merge the PR and the commit build fails 😕

**Comment by stsewd** [comment]
I have set your project to always use the large queue, but I'll keep this open till I figure out why it wasn't setting the queue in a deterministic way.

**Comment by chrisjsewell** [comment]
Thanks 🙏

**Comment by chrisjsewell** [comment]
Yep that did the trick 🎉

**Comment by chrisjsewell** [comment]
Out of interest what are the basic specs of the smaller and larger builder?

**Comment by chrisjsewell** [comment]
Its also still failing on stable builds 😬 https://readthedocs.org/projects/myst-nb/builds/11636965/

**Comment by stsewd** [comment]
I just build stable again (twice) and it's passing. We were experiencing some high demand on the builders during that time-lapse, so maybe related to that. Also, do you know what could be consuming a lot of resources? The project seems small.

**Comment by stsewd** [comment]
We use `Standard_D1_v2` and `Standard_D2_v3`. All limits are listed at https://docs.readthedocs.io/en/stable/builds.html

https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series?toc=/azure/virtual-machines/linux/toc.json&bc=/azure/virtual-machines/linux/breadcrumb/toc.json


https://docs.microsoft.com/en-us/azure/virtual-machines/dv3-dsv3-series?toc=/azure/virtual-machines/linux/toc.json&bc=/azure/virtual-machines/linux/breadcrumb/toc.json

**Comment by chrisjsewell** [comment]
Cheers, yeh the problem looks to lie with recent updates to nbclient.
I'm feeding back this information back to them.

**Comment by stsewd** [comment]
We haven't seen this happening in other projects or being able to replicate :man_shrugging: . Will close this for now.
