### ISSUE TITLE
Rename the DeepSpeech project slug to Mozilla Voice STT

### ISSUE THREAD

**Issue by lissyx** [readthedocs/readthedocs.org#7369]
## Details

* Read the Docs project URL: https://deepspeech.readthedocs.io/
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): deepspeech

## Expected Result

As part of rebranding of the project from "DeepSpeech" to "Mozilla Voice STT" that we are conducting, we would need to move the current slug from https://deepspeech.readthedocs.io/ to https://mozilla-voice-stt.readthedocs.io/. If this can be done with keeping a redirect from https://deepspeech.readthedocs.io/ to avoid breaking existing links, it would be really awesome.

**Comment by stsewd** [comment]
@lissyx the best way to rename your project is to create a new one with the new slug. Currently, we don't have a way to redirect a project to another easily (we support redirects, but redirects only work when your users hit a 404).

Another solution is to create a custom domain, that way you can redirect the old project to that custom domain without problems.

**Comment by lissyx** [comment]
> @lissyx the best way to rename your project is to create a new one with the new slug. Currently, we don't have a way to redirect a project to another easily (we support redirects, but redirects only work when your users hit a 404).
> 
> Another solution is to create a custom domain, that way you can redirect the old project to that custom domain without problems.

Thanks, but I have been seeing other rename request done with redirect of the content, am I mislead? Like https://github.com/readthedocs/readthedocs.org/issues/7053

Spreading on two project name is going to be a bit painful, I wanted to avoid that. We don't have domain name dedicated so it's not a viable alternative.

**Comment by stsewd** [comment]
> Thanks, but I have been seeing other rename request done with redirect of the content, am I mislead? Like #7053

That request is to take the name of an existing project, in that case the old project was renamed so the user could create a project with that same name.

Another thing you can do is to import a project with only one page (index.html), that way it'll redirect for all pages (404) except for index.html, but you can put a warning there that the new docs are on a different domain, or use a js trick to redirect.

In any case, you'll need to create another project with the new name.

**Comment by lissyx** [comment]
> In any case, you'll need to create another project with the new name.

Does this require creating a new account, or can we have two projects under the same account?

**Comment by stsewd** [comment]
You can use the same account, but you'll need to do a manual import https://readthedocs.org/dashboard/import/manual/

**Comment by lissyx** [comment]
> You can use the same account, but you'll need to do a manual import https://readthedocs.org/dashboard/import/manual/

Perfect, it looks like there's still some webhook fix to do.

**Comment by lissyx** [comment]
Looks like we're all done, thanks @stsewd !
