### ISSUE TITLE
two setups of the same project fail differently

### ISSUE THREAD

**Issue by keewis** [readthedocs/readthedocs.org#7371]
I have two setups for the same project, one for the main repository and one for my fork. If the build fails because of an exception / warning, the setup for the main repository times out while the setup for my fork works as excepted (it prints the output of the failing build).

Is there anything we set on the main setup that caused this behavior?

## Details

* readthedocs URLs: [main setup](https://readthedocs.org/projects/xray/), [fork](https://readthedocs.org/projects/xarray-keewis/)
* Build URLs (both trying to build the same commit): [main setup](https://readthedocs.org/projects/xray/builds/11623533/), [fork](https://readthedocs.org/projects/xarray-keewis/builds/11623675/)

## Expected Result

Both builds report the error.

## Actual Result

The main setup times out instead.

**Comment by keewis** [comment]
also, unrelated to this issue: could you enable `CONDA_APPEND_CORE_REQUIREMENTS` on both setups? I'd like to have more control about which version is used.

**Comment by stsewd** [comment]
Looks like both failed because of excessive use of memory, so they failed in at a different part of the program, thus leading to different errors.

I have added the feature flag for your project.

**Comment by keewis** [comment]
thanks for setting the feature flag on both projects.

> Looks like both failed because of excessive use of memory

You mean the main setup timed out because of excessive use of memory while my fork setup worked? Since I never requested a feature flag or extended memory for the fork, I think that's surprising. Is there any way to make the main setup behave more like the fork setup?

**Comment by stsewd** [comment]
I mean both builds failed

- https://readthedocs.org/projects/xray/builds/11623533/
- https://readthedocs.org/projects/xarray-keewis/builds/11623675/

But one failed earlier than the other one, thus the different messages for the error.

**Comment by keewis** [comment]
no, the second build (https://readthedocs.org/projects/xarray-keewis/builds/11623675/) failed correctly, there was an issue with the code in the docs. However, the first build (https://readthedocs.org/projects/xray/builds/11623533/) didn't print the traceback, and that's the issue here. If sphinx doesn't fail, both setups will successfully complete the builds.

**Comment by stsewd** [comment]
Ok, I don't see any constraints in your project related to build time, and both builds were running in our large builders. So one was able to finish more quickly than the other one, if you try building again you'll see one or both failing for the same reason.

- https://readthedocs.org/projects/xray/builds/11655953/
- https://readthedocs.org/projects/xarray-keewis/builds/11656091/

Also, your original project has this feature flag

![Screenshot_2020-08-13 Change feature Django site admin](https://user-images.githubusercontent.com/4975310/90162767-bdd6fd80-dd5a-11ea-99d2-c0fad83616eb.png)

**Comment by keewis** [comment]
thanks for investigating. We've fixed the code since I reported this, so to reproduce we'd have to rerun the same commit – not sure if that's possible. If not, I'll try to create a branch with a failing commit and push it to both repositories, and then we can try to debug a bit more.

I think the conda upgrade is not necessary anymore, we switched back to using the `latest` image.

Also, I noticed you enabled `CONDA_APPEND_CORE_REQUIREMENTS` only for my fork, could you enable it for the main project, too?

**Comment by stsewd** [comment]
We don't support running a build on a specific commit.

And looks like I set the wrong project (xarray instead of xray :D)

**Comment by stsewd** [comment]
Ok, looks like your project had some time constraints from before (xray). I have changed them to use the defaults from our new large builders. Feel free to ask to reopen if you can replicate.

**Comment by keewis** [comment]
thanks, I can confirm that the version pinning of `sphinx` works.

> I have changed them to use the defaults from our new large builders

Unfortunately it seems that didn't fix it, the main setup (xray) still times out. I added a branch (`failing-docs`) pointing to the failing commit to both repositories, hopefully that makes debugging easier. Trying to build them on each setup still yields different results: [xray](https://readthedocs.org/projects/xray/builds/11658388/) times out and [xarray-keewis](https://readthedocs.org/projects/xarray-keewis/builds/11658484/) fails after about 6-7 minutes, printing a traceback.

**Comment by stsewd** [comment]
Looks like almos the same stack trace was produced by the two builds

> AttributeError: 'DataArrayRolling' object has no attribute 'y'

Guessing sphinx terminated in a different step, so the different error. The error message you see can be different as we don't have a reliable way to detect an error produced by excessive consume of memory.

I have double check your project doesn't have any constraints.

**Comment by keewis** [comment]
I didn't notice the traceback, that's been my main concern. The time-out is annoying but not a serious issue, so I guess that's as far as we can get. Thanks for investigating and double checking.
