### ISSUE TITLE
Mkdocs builds failing on Python 3.x for Project with Sub-Docs

### ISSUE THREAD

**Issue by Breakthrough** [readthedocs/readthedocs.org#7374]
## Details

For some reason, my Mkdocs project is failing to build on the RTD server using Python 3.x, but works fine with Python 2.x.  Locally, I am able to build fine using `mkdocs` under Python 3.8.

RTD seems to be using Python 3.7.

* Read the Docs project URL:

https://pyscenedetect.readthedocs.io/en/latest/

https://readthedocs.org/projects/pyscenedetect/

* Build URL (if applicable):

https://readthedocs.org/projects/pyscenedetect/builds/11627663/
https://readthedocs.org/projects/pyscenedetect/builds/11627858/

* Read the Docs username (if applicable): Breakthrough

## Expected Result

Build should pass.  Have executed build locally with latest `mkdocs` successfully under Python 3.8.3, I get the following output:

    $ python -m mkdocs build --clean --site-dir _build/html --config-file mkdocs.yml
    INFO    -  Cleaning site directory
    INFO    -  Building documentation to directory: C:\Users\Breakthrough\Documents\git-repos\PySceneDetect\_build\html
    INFO    -  Documentation built in 0.47 seconds

## Actual Result

Builds are failing under Python 3.x, but not Python 2.x, with the following error:

    Error: `RuntimeError: generator raised StopIteration`

I found mkdocs/mkdocs#1531

**Comment by Breakthrough** [comment]
This might be caused by the dependency on `opencv-python` which was pushed two hours.  Still investigating, however, that bug only affects Python 2.7.  Still unsure as to why the documentation fails to build using Python 3.x.

**Comment by Breakthrough** [comment]
So, I found:

 - The Python 3 build is failing due to Mkdocs not supporting Python 3.7 correctly
 - The Python 2 build is failing due to a bad new version of a dependent package

Closing issue as it's not likely related to you folks.  Thanks again for your great work and support!

**Comment by Breakthrough** [comment]
I'm unfortunately experiencing this again:
https://readthedocs.org/projects/dvr-scan/builds/16028605/

Using same Python version as the server yields the same result.  What could there be wrong on my end that might cause this?

**Comment by stsewd** [comment]
@Breakthrough I see two things:

- You are using python 3.7 on rtd, not 3.8, you can use a config file to specify a version explicitly (instead of letting rtd decide)
- RTD is installing mkdocs 0.17.3, you may be using another version locally, see https://docs.readthedocs.io/en/stable/builds.html#default-versions-of-dependencies.

To solve both of those issues, you can use a config file https://docs.readthedocs.io/en/stable/config-file/v2.html and pinning your mkdocs version in your requirements file.

**Comment by Breakthrough** [comment]
Hey @stsewd;

Sorry I've changed environments since the original post, I confirmed I was running Python 3.7 locally and on RTD.  I also tried adding a config file to see if it resolved the issue, but I still get the same output.  To help with further debugging, I created a branch that only changes the Python version from 2.7 -> 3.7 to demonstrate the issue:

https://github.com/Breakthrough/DVR-Scan/commit/e8681fa65f65d57d32aeb68ead3fe848fa38a2a1

And the resulting build output:

https://readthedocs.org/projects/dvr-scan/builds/16040170/

Thanks for the reply, and sorry for some of the confusion there!

**Comment by Breakthrough** [comment]
Also I just read that link you provided re: dependencies, and that's a good point, I have mkdocs 1.2.3 locally installed.  Is there a way I can tell Readthedocs to use a newer version for Python 3 builds?

> Projects created before April 3, 2019 (April 23, 2019 for [Read the Docs for Business](https://docs.readthedocs.io/en/stable/commercial/index.html)) use 0.17.3. Projects created before March 9, 2021 use 1.0.4. New projects use the latest version.

I'm hoping there's a way I can run a test build with the latest versions of everything, since that seems to work fine locally.

**Comment by Breakthrough** [comment]
Building just fine now on RTD, so I'll make sure to define the requirements explicitly now.  Thank you so much for the help @stsewd, and sorry for any confusion there!  :)

**Comment by Breakthrough** [comment]
Sorry one more question - this approach doesn't seem to be working for another one of my projects that uses subprojects in RTD.  I'm able to work around this since the requirements can be specified in the project config from the Web UI, but I'd like to know, is there a way of handling this via `.readthedocs.yaml`?  I couldn't find anything in the docs, wondering if this is supported yet or not.

Thanks!

**Comment by humitos** [comment]
> I'm able to work around this since the requirements can be specified in the project config from the Web UI, but I'd like to know, is there a way of handling this via `.readthedocs.yaml`?

Take a look at https://docs.readthedocs.io/en/stable/config-file/v2.html#python. The key you are looking for is `python.install.requirements`

**Comment by Breakthrough** [comment]
Sorry to clarify, the issue I'm having is that I have two projects in the
same repo.  When I specify .readthedocs.yaml it breaks that workflow since
then both projects use the same configuration.

To avoid that I'm not using .readthedocs.yaml as a workaround.

On Monday, February 14, 2022, Manuel Kaufmann ***@***.***>
wrote:
> I'm able to work around this since the requirements can be specified in
the project config from the Web UI, but I'd like to know, is there a way of
handling this via .readthedocs.yaml?
>
> Take a look at
https://docs.readthedocs.io/en/stable/config-file/v2.html#python. The key
you are looking for is python.install.requirements
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you modified the open/close state.<
https://ci5.googleusercontent.com/proxy/CANMURan-t0SsUcazj_zv8AytIGBSzlc8X3vYFpBB-mXeJvycvepfyqFuf5Pwi9n4aFO8pzw3rKsWdFHCljIDe3PR8cgKIEkGWPO3TFnzcUw6Zz35XwqvHayP9090ldmBDTcTdXpbnEjkbOxb2jF_yMmfle9TNMd4wVs3K-G3F7qRehILd-2I9Ealu7U-FlSRJDfmDgx355LXnh9Mp1WSGlBA2AlVbcsE6tT2iOyXg=s0-d-e1-ft#https://github.com/notifications/beacon/AAA6TBGT4YSF7RM7YB7IOELU3D57LA5CNFSM4PZMGFWKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOHXXQG5I.gif>Message
ID: ***@***.***>

**Comment by stsewd** [comment]
@Breakthrough we don't support multiple config files for a repo, but we have an open issue discussing this at https://github.com/readthedocs/readthedocs.org/issues/8811.
