### ISSUE TITLE
Organization not showing up in repository list

### ISSUE THREAD

**Issue by josh146** [readthedocs/readthedocs.org#7381]
## Details

* Read the Docs project URL: n/a
* Build URL (if applicable): n/a
* Read the Docs username (if applicable): `JoshIzaac`

## Expected Result

I am having trouble importing repositories from an organization (https://github.com/PennyLaneAI). I am listed as an owner of the organization, and 3rd party access has been provided to the organization:

![image](https://user-images.githubusercontent.com/2959003/90026413-6c952280-dcf6-11ea-836f-6945d7fc0682.png)

## Actual Result

Pressing the sync button on my ReadTheDocs 'Import a Project' page has no effect; the PennyLaneAI organization is not listed.

**Comment by stsewd** [comment]
@josh146 could you share a screenshot of the https://readthedocs.org/dashboard/import page?

**Comment by josh146** [comment]
@stsewd Sure!
![image](https://user-images.githubusercontent.com/2959003/90212222-fac1f380-de31-11ea-8a3d-3c69a650713a.png)

**Comment by josh146** [comment]
@stsewd just wondering if there is an update on this? Some (non-owner) members of the organization _do_ have access to the PennyLaneAI organization in their readthedocs dashboard, it is only organization Owners that do not seem to

**Comment by stsewd** [comment]
Sorry, haven't had time to debug this.

> Some (non-owner) members of the organization do have access to the PennyLaneAI organization in their readthedocs dashboard, it is only organization Owners that do not seem to

That information is useful, thanks!

**Comment by humitos** [comment]
@josh146 I haven't jumped too deep into debugging this, but I guess that it could be solved after today's deploy. There are some cases where `RemoteOrganization` are not being synced properly due to a bug and it's solved in `master` already and going out today. I'm not 100% sure that this will solve your issue, but worth to try again tomorrow by hitting the two arrows button to re-sync your repositories and organizations. Please, let us know tomorrow.

**Comment by JamesRandom** [comment]
I started seeing this problem yesterday. That update does not seem to have fixed it.

**Comment by josh146** [comment]
@humitos indeed, the update seems to have fixed it for me. Thanks!

**Comment by stsewd** [comment]
We pushed another update yesterday, please try the rezync button again.

**Comment by JamesRandom** [comment]
No, still not working for me.

**Comment by JamesRandom** [comment]
Aha! I refreshed the page after clicking the sync button and now the organization has appeared!
Thank you

**Comment by JamesRandom** [comment]
And now it has disappeared again.

**Comment by stsewd** [comment]
@JamesRandom do you have more than one accound connected? (github and gitlab?)

**Comment by JamesRandom** [comment]
No, just GitHub. I tried disconnecting and reconnecting the GitHub account, but that didn't help.

**Comment by JamesRandom** [comment]
The existing docs from that organization can still be built, so cloning is working. Just no list of repos

**Comment by JamesRandom** [comment]
I just logged in to readthedocs with a different browser. When I went to the import page, the organization, and all the doc repos were visible. I hit the refresh button and the organization disappeared.

**Comment by JamesRandom** [comment]
This is still not working for me.

**Comment by JamesRandom** [comment]
If I log out and then go straight to the import URL (and login) then I get a full list of repositories, but the organisation is not shown in the filter list:
![Screenshot 2020-09-08 at 10 20 06](https://user-images.githubusercontent.com/11873471/92458283-157f5200-f1bd-11ea-9ca2-6281c8d5fbff.png)

If I hit the refresh button then those repos disappear:
![Screenshot 2020-09-08 at 10 20 25](https://user-images.githubusercontent.com/11873471/92458349-2af47c00-f1bd-11ea-9653-b855dd0d3123.png)

**Comment by humitos** [comment]
@JamesRandom Hi! Please, for issues with Read the Docs for Business contact our support team.

We plan to do a deploy today with a fix, so this issue should disappear later today. Thanks you all for the updates!

**Comment by chrisjsewell** [comment]
Hey @humitos, I'm an owner of https://github.com/orgs/marvel-ncc, but its not showing up in the list (I've tried re-syncing but its still not there)

<img width="890" alt="image" src="https://user-images.githubusercontent.com/2997570/95817912-f11a1680-0d22-11eb-8266-67f3da0ac6f3.png">

**Comment by humitos** [comment]
I'm reopening this issue because it seems that @JamesRandom (`jamiep`) and @chrisjsewell (`cjsewell`) still have this problem. I will try to debug this today and come back with an answer.

**Comment by humitos** [comment]
@chrisjsewell GitHub returns only 4 organizations for your username when hitting `https://api.github.com/user/orgs` (https://github.com/readthedocs/readthedocs.org/blob/4ec6175282f7e3dbfc167c9db9ef0733a1044b04/readthedocs/oauth/services/github.py#L60)

```
(Pdb) [o.get('login') for o in orgs]
['docutils', 'conda-forge', 'aiidateam', 'executablebooks']
```

So, there may be something on GitHub's side because we are not getting that information. BTW, accessing to https://github.com/orgs/marvel-ncc gives me 404 to me. Is it a private organization?

**Comment by JamesRandom** [comment]
It's actually working for me, after a recent update.

**Comment by chrisjsewell** [comment]
oops left of the last `r`: https://github.com/marvel-nccr

Hmm, thats weird, on https://github.com/chrisjsewell, it definitely shows this organisation (plus also another new one https://github.com/aiidaplugins which I created):

<img width="352" alt="image" src="https://user-images.githubusercontent.com/2997570/95837004-647e5100-0d40-11eb-836e-11664f5b4a1e.png">

and I'm definitely down as an owner on marvel-nccr:

<img width="1405" alt="image" src="https://user-images.githubusercontent.com/2997570/95837308-c343ca80-0d40-11eb-9382-e0036a41a832.png">

any tips 🤷

**Comment by humitos** [comment]
@chrisjsewell can you check what's returning the GitHub's API to you with these commands?

```
export GITHUB_TOKEN=<your-token-here>

curl --silent -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user/orgs | grep login
```

**Comment by chrisjsewell** [comment]
Yep it is there:

```
$ curl --silent -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/user/orgs | grep login
    "login": "docutils",
    "login": "conda-forge",
    "login": "aiidateam",
    "login": "marvel-nccr",
    "login": "executablebooks",
    "login": "aiidaplugins",
```

FYI, I've got the GitHub hook working to push to RTD and trigger PR builds (another owner remade https://readthedocs.org/projects/quantum-mobile/ and added me as admin), but its still not working to push back to GitHub

![image](https://user-images.githubusercontent.com/2997570/95874730-7fb58480-0d71-11eb-9a44-0844823736b3.png)

any easy fix?

**Comment by humitos** [comment]
I'm really confused here. I will need more time to debug this because I ran out of ideas about where the problem could be. In my previous comment I saw GitHub not returning that organization. So, maybe the `access_token` that Read the Docs has in the DB does not have permissions to query that organization? (guessing aloud) :thinking:

**Comment by stsewd** [comment]
Is anyone still having this problem? With github at least (there is a problem with gitlab https://github.com/readthedocs/readthedocs.org/issues/7743). We merged some PRs related to that some time ago that may have fixed this.

**Comment by chrisjsewell** [comment]
Well I'm still have the issue I explained above (https://readthedocs.org/projects/quantum-mobile/builds/) but, as mentioned I only see it for this one organisation/repo, so I think it was just an unlucky set of circumstances.
As you mention, perhaps there's a way I can "refresh" the access token

**Comment by anupam-git** [comment]
Having the same issue. Cannot see more than 4 organizations in readthedocs page and hence cannot import my repository.

User : https://github.com/anupam-git
Org : https://github.com/pico-wizard/
![image](https://user-images.githubusercontent.com/5106648/108813307-c98f6080-75d6-11eb-8baa-c59070e63bd2.png)

**Comment by humitos** [comment]
@anupam-git @chrisjsewell Hi! Can you confirm that the organization owner has approved the OAuth Read the Docs application? Take a look at this documentation page: https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/approving-oauth-apps-for-your-organization

**Comment by anupam-git** [comment]
@humitos 👏🏼 

I had to go to Settings -> Applications -> OAuth Apps -> ReadTheDocs Comminuty and "Grant" the specific organization.

After granting access, I can now see the organization on readthedocs.

Thank you so much for the reply. 😄

**Comment by humitos** [comment]
We should add an entry in our FAQ page for this: https://docs.readthedocs.io/en/latest/faq.html

**Comment by stsewd** [comment]
There is mention of this in https://docs.readthedocs.io/en/stable/pull-requests.html#troubleshooting, probably we should move it to https://docs.readthedocs.io/en/stable/connected-accounts.html

**Comment by chrisjsewell** [comment]
errr, still having this issue and now also in another organisation: https://github.com/aiidalab/aiidalab/issues/167
I just can't work out how to actually get the ReadTheDocs application to show up in the "Third party access" section of the organisation's settings? (obviously I can't grant access if its not there)
We've tried re-syncing but still it does not show up

**Comment by anupam-git** [comment]
> errr, still having this issue and now also in another organisation: [aiidalab/aiidalab#167](https://github.com/aiidalab/aiidalab/issues/167)
> I just can't work out how to actually get the ReadTheDocs application to show up in the "Third party access" section of the organisation's settings? (obviously I can't grant access if its not there)
> We've tried re-syncing but still it does not show up


I was referring to GitHub Settings here and not ReadTheDocs Settings :

> I had to go to Settings -> Applications -> OAuth Apps -> ReadTheDocs Community and **Grant** access to that specific organization.

**Comment by chrisjsewell** [comment]
Ah fixed it 🎉 

The confusion for me was that, to grant access for an organisation (and hence a repo in that organisation) you have to go to your **personal** GitHub settings and not the organisation's settings

**Comment by humitos** [comment]
@astrojuanlu there is some useful feedback from users here that would be good to document in our docs. There are multiple users bitten by this and it usually confuses ourselves as well. I'd appreciate if you can update our docs when you have some time.
