### ISSUE TITLE
How to remove published documentation

### ISSUE THREAD

**Issue by danroth27** [readthedocs/readthedocs.org#7387]
My team has some really old and stale docs published at https://aspnetcore.readthedocs.io/ that I'm trying to figure out how to take down. I tried deleting the project, but the published content is still accessible. Help?

**Comment by stsewd** [comment]
The project still exists https://readthedocs.org/projects/aspnetcore/

**Comment by danroth27** [comment]
I see. Looks like that's a project that I don't actually have ownership of. OK, thanks for the help!
