### ISSUE TITLE
readthedocs_ext.readthedocs extension does not declare if it is safe for parallel reading

### ISSUE THREAD

**Issue by pllim** [readthedocs/readthedocs.org#7394]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/astropy
* Build URL (if applicable): https://readthedocs.org/projects/astropy/builds/11686866/
* Read the Docs username (if applicable): pllim

## Expected Result

Build to succeed without warnings.

## Actual Result

```
...
WARNING: the readthedocs_ext.readthedocs extension does not declare if it is safe for parallel reading,
assuming it isn't - please ask the extension author to check and make it explicit
WARNING: doing serial read
...
build finished with problems, 2 warnings.
```

I cannot tell if this is from [sphinx-astropy settings](https://github.com/astropy/sphinx-astropy/blob/16b9fefce08db880c071059b6973139a4d476c6a/sphinx_astropy/conf/v1.py#L178) or something intrinsic to RTD. Hope you can advise. Thanks!

**Comment by stsewd** [comment]
Sorry about that, this is because we activated an experimental feature, but looks like it requires the latest version of our extension. But we don't install it by default yet

https://github.com/readthedocs/readthedocs.org/blob/de4d0bfea0ca789bfecf768d18e2df582895389a/readthedocs/doc_builder/python_environments.py#L378-L382

**Comment by stsewd** [comment]
I have forced your project to use the latest version of the rtd extension for now https://readthedocs.org/projects/astropy/builds/11689293/

**Comment by chrisjsewell** [comment]
Yep its broken all the PR build in executablebooks lol 😬 : https://github.com/executablebooks/MyST-Parser/pull/216

**Comment by stsewd** [comment]
Sorry about that, I have rolled back the feature for now. New builds shouldn't fail. Let us know if this is still happening for your projects.

**Comment by pllim** [comment]
Thank you for the quick fix!

**Comment by chrisjsewell** [comment]
thanks 🙏
