### ISSUE TITLE
Discussion: Live chat system on documentation pages to give feedback?

### ISSUE THREAD

**Issue by jd41** [readthedocs/readthedocs.org#7401]
To improve the quality of any documentation, I think it's very helpful if there is a steady stream of (non-repetitive) questions and feedback by users: A developer will probably have a harder time figuring out what is hard to understand about their software/docs than a new user.

So providing such feedback should take as little effort as possible for the user, and the user should feel confident that their question will be answered reasonably quickly and their thoughtful feedback will be taken seriously. I heard - and it fits with my 
personal experience - that "trivial inconveniences" (like finding an e-mail address or logging in into GitHub) and uncertainties 
about whether feedback is taken seriously, how long a reply takes etc. can make a massive difference in how likely people are to react/engage/do something.

In the current RTD implementation, there is already an "Edit on Github" link, which is quite nice - but I think one can improve upon this.

So I think it would be nice if there was a "live chat" feature on Readthedocs pages (similar to e.g. Intercom), in addition to the "Edit on GitHub" feature.

In Intercom, the most popular live chat solution, the following features seem important to me:

- A chat-like interface on the page is one click away, encouraging short, low-effort comments and the expectation that an answer will come quickly, and the user is free to react to that as well.
- The thing shows something like "the team usually replies in 1 hour", which reduces the uncertainty about how long one has to wait,
- The person writing the feedback is anonymous/pseudonymous by default, and the feedback isn't publicly visible. So the user doesn't have to log in to/register for anything, and they don't have to worry that their comment turns out to be stupid and will be on the internet forever (would be quite important for me!)

My question is now: What would be a good way to implement such a feature for the documentation page of open-source projects? The price of Intercom of at least 90 $/month is prohibitively high.

Is it possible that RTD starts hosting the server-side for such a thing? Google told me that Rocketchat is a FOSS system with a live chat feature, but I am not sure about how well-suited it would be for these projects. The traffic requirements for text-only chats (or text+screenshots) should be very manageable, or am I mistaken about that?

One can also imagine some integration into GitHub, e.g. one has the option to turn a conversation/conclusions into a GitHub issue with one click etc. Or alternatively, a checkbox to click about whether one wants to make the comment publicly or privately...

I am optimistic about the risk that there will be a deluge of questions by people expecting private support that the developer will be unwilling to answer. To manage the risk, it might be important to pick the formulation in the feedback box ("Have any trouble using X?" vs "Do you want to give feedback on this documentation page?")

**Comment by jd41** [comment]
In the meantime, I learned about Chatwoot, which provides Intercom-like functionality. The system is currently open source (it used to be a start-up that didn't take off). One can host it oneself (e.g. on Heroku), but also get a free tier on chatwoot.com (limited to two users answering messages, I think). One is notified of new conversations by e-mail (and the person providing feedback can enter an e-mail address as well).

A widget is currently installed on https://jd41-sphinx-test.readthedocs.io/en/latest/ (currently pointing to an instance running on the free Heroku tier, so it might not always work immediately; e-mails don't work so far either).

I'd also like to point out that the ultimate goal of documentation is not to have some text, but to help people use a thing. For quite some projects with a relatively low ratio of users to paid developers (e.g. academic projects), good one-on-one support might actually be worth considering as a way to pursue that goal...

**Comment by humitos** [comment]
I don't think that Read the Docs can implement this. It will be super hard (and a lot of work that we can't afford!) to make it generic enough to be useful for most users. This can be implemented via a Sphinx extension that integrates with the usage of an external service for each different use case.

On the other hand, dealing with anonymous feedback is extremely complicated. We will flood our servers with a lot of SPAM.

In the linked issue from PyPI (https://github.com/pypa/pip/issues/8784) I mentioned what I found so far. I suggest anyone interested on this, to subscribe to that issue.
