### ISSUE TITLE
Autodoc works on local machine, but not on readthedocs

### ISSUE THREAD

**Issue by afortiori** [readthedocs/readthedocs.org#7405]
## Details

* Read the Docs project URL: https://smm4h.readthedocs.io/en/latest
* Build URL: https://readthedocs.org/projects/smm4h/builds/
* Read the Docs username: afortiori 

## Expected Result

On my local machine, autodoc works. 

## Actual Result
My build runs without any errors, but the autodoc does not work even though it works on my local machine. I thought this might be an issue with dependencies, but because there's no build errors I am not really sure that is it.

**Comment by stsewd** [comment]
You can click on the steps to see the output and search for warnings https://readthedocs.org/projects/smm4h/builds/11730425/.

```
WARNING: autodoc: failed to import class 'cnn.CNN' from module 'smm4h'; the following exception was raised:
No module named 'file'
```

**Comment by afortiori** [comment]
Thanks so much! I was able to solve my problem my looking at the outputs.
