### ISSUE TITLE
Set environment variables in PR builds of private repos

### ISSUE THREAD

**Issue by flying-sheep** [readthedocs/readthedocs.org#7413]
## Actual Result

In PR builds, environment variables (=secrets) don’t get set to prevent people from sending them somewhere in plain text just by making a PR.

## Expected Result

In a private repo, the above wouldn’t be necessary as all contributors are trusted. There’s still incentive not to add the secrets to the code though, e.g. in case the code becomes public at some point. Therefore it would be great to be able to access the secrets in PR builds of private repos.

**Comment by humitos** [comment]
Thanks @flying-sheep for reporting this. We are already aware of this and we are thinking on making this a config per project that owners can set. See https://github.com/readthedocs/readthedocs.org/pull/7279#issuecomment-658248400

**Comment by stsewd** [comment]
I think we cal also consider this an option in the env variables form. I think others CI services do this. You can choose if the env var can be used in PRs or not.

**Comment by flying-sheep** [comment]
If you point me to some docs/example PRs on how to add a config value, I could try my hand here, my company could really use this!

**Comment by flying-sheep** [comment]
OK, so we have the current build version types, with “external” corresponding to PR builds.

```py
VersionType = Literal['branch', 'tag', 'external', 'unknown']
```

I think 2-3 types of behavior are helpful, of which we implicitly use **Private** right now:

- **Private** variables can’t be displayed once set, only exposed to “external” (PR) builds.
- **Public** variables have their values visible in the UI, and are exposed to all builds
- **Default** variables behave like **Private**, but are exposed to “external” builds too if the *version* is private (as in #7279)

I see two options for new behavior configuration of env variables:

1. A “Private” checkbox, which toggles between the current behavior (**Private**) and a new one (**Public**). Could also be named “Public”.
2. A “Visibility” dropdown, with the three options specified above

**Comment by stsewd** [comment]
I think we can have a checkbox, "expose this en var in builds from PRs", default to no. About the value visible for "public" env vars, I think we can decide about that later.

**Comment by flying-sheep** [comment]
OK, added a PR. Didn’t bother to look where to do the UI yet, but maybe someone can take this over or use as a starting point?
