### ISSUE TITLE
projects are listed as a subprojects of the wrong project

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#7417]
frc-docs-zh_CN is listed as a subprojects of daltzprivate when it should be under frc-docs
frc-docs-pt is listed as a subprojects of daltzprivate when it should be under frc-docs

It does properly show up in the language menu on https://docs.wpilib.org/

**Comment by stsewd** [comment]
Where are you seeing this? https://readthedocs.org/projects/frc-docs-pt/ doesn't show anything related. Also, if you are using them  translations, you don't need to mark them as subprojects.

**Comment by Daltz333** [comment]
Closing as it seems to have been fixed. Weird.
