### ISSUE TITLE
[Help] Only some code blocks aren't showed on the website but showed locally.

### ISSUE THREAD

**Issue by richarddwang** [readthedocs/readthedocs.org#7419]
## Details

* Read the Docs project URL: https://hugdatafast.readthedocs.io/en/latest/start.html
* Build URL (if applicable): 
* Read the Docs username (if applicable): richarddwang

## Expected Result
on local
![image](https://user-images.githubusercontent.com/17963619/91658089-ccfad100-eaf8-11ea-8a1c-1d53bf0fdd3d.png)

## Actual Result
on website
![image](https://user-images.githubusercontent.com/17963619/91658008-607fd200-eaf8-11ea-829a-2a8fcbadacfe.png)

source .rst : https://github.com/richarddwang/hugdatafast/blob/master/docs/source/start.rst

**Comment by humitos** [comment]
Hi @richarddwang! In the link you shared of the documentation, I do see it rendered as you see "on local". I think you already figure this out. Please, close the issue in that case. Otherwise, could you describe more your issue so we can help you? Thanks.

**Comment by richarddwang** [comment]
Hi @humitos ,
I just tried replacing `.. code-block::` with `::` hours ago and waiting for changes to be applied to the website.
And I found every thing work now. 🤩
