### ISSUE TITLE
Documentation build requires a native library installation

### ISSUE THREAD

**Issue by pzelasko** [readthedocs/readthedocs.org#7431]
## Details

* Read the Docs project URL: https://lhotse.readthedocs.io/en/latest/api.html#others
* Build URL (if applicable): https://readthedocs.org/projects/lhotse/builds/11550119/ (the step after `cat docs/conf.py`)
* Read the Docs username (if applicable): pzelasko

## Expected Result

In my documentation, I'm using the `autodoc` feature of Sphinx. During Python code execution, it has to import one of my dependencies, i.e. `torchaudio`. Unfortunately, `torchaudio` depends on a native library called `libsndfile1` and will crash if it can't find it. On GitHub CI I can easily install it with:

```sudo apt install libsndfile1-dev libsndfile1```

however, I could not find out how to perform a similar step in ReadTheDocs.

## Actual Result

Some sections of my code documentation are not included in the build result (API reference section).

**Comment by stsewd** [comment]
You should try mocking that dependency https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules
