### ISSUE TITLE
Build error with build id #11789294

### ISSUE THREAD

**Issue by DeepanshS** [readthedocs/readthedocs.org#7432]
## Details:

* Project URL: https://readthedocs.org/projects/mrsimulator/
* Build URL(if applicable): https://readthedocs.org/projects/mrsimulator/builds/11789294/
* Read the Docs username(if applicable): DeepanshS

## Expected Result

Build success

## Actual Result

Build failure with the following error message:
`There was a problem with Read the Docs while building your documentation. Please try again later. However, if this problem persists, please report this to us with your build id (11789294).`

with no easy way of debugging.

**Comment by stsewd** [comment]
Sorry about this, we may have a fix for this problem tomorrow.

**Comment by stsewd** [comment]
Should be fixed now https://readthedocs.org/projects/mrsimulator/builds/11804947/
