### ISSUE TITLE
Build error with build id #11789804

### ISSUE THREAD

**Issue by jxmorris12** [readthedocs/readthedocs.org#7433]
## Details:

* Project URL: https://readthedocs.org/projects/TextAttack/
* Build URL(if applicable): https://readthedocs.org/projects/textattack/builds/11789804/
* Read the Docs username(if applicable): jxmorris12
## Expected Result
Build success

## Actual Result
Build failure with the following error message:
```
There was a problem with Read the Docs while building your documentation. Please try again later. However, if this problem persists, please report this to us with your build id (11789804).
```

with no easy way of debugging.

**Comment by stsewd** [comment]
Sorry about this, we may have a fix for this problem tomorrow. See https://github.com/readthedocs/readthedocs.org/pull/7442

**Comment by stsewd** [comment]
Should be fixed now https://readthedocs.org/projects/textattack/builds/11804991/

**Comment by jxmorris12** [comment]
fixed for us! :)
