### ISSUE TITLE
Build error with build id #11791839

### ISSUE THREAD

**Issue by chillancezen** [readthedocs/readthedocs.org#7434]
## Details:

* Project URL: https://readthedocs.org/projects/ansible-galaxy-fortimanager-docs/
* Build URL(if applicable): https://readthedocs.org/projects/ansible-galaxy-fortimanager-docs/builds/11791839/
* Read the Docs username(if applicable): Linky

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by stsewd** [comment]
Sorry about this, we may have a fix for this problem tomorrow. See https://github.com/readthedocs/readthedocs.org/pull/7442

**Comment by stsewd** [comment]
This should be fixed now https://readthedocs.org/projects/ansible-galaxy-fortimanager-docs/builds/11805052/

**Comment by chillancezen** [comment]
@stsewd thank Santos so much for the quick fix.
