### ISSUE TITLE
Build error with build id #11792342

### ISSUE THREAD

**Issue by dweindl** [readthedocs/readthedocs.org#7435]
## Details:

* Project URL: https://readthedocs.org/projects/AMICI/
* Build URL(if applicable): https://readthedocs.org/projects/amici/builds/11792342/
* Read the Docs username(if applicable): dweindl

## Expected Result

Expected the documentation to be built, as happening locally and on github actions (https://github.com/AMICI-dev/AMICI/runs/1060557529). 

In case of failure, expected to see the output of the `sphinx-build` command.

## Actual Result

The build failed with uninformative error (`"There was a problem with Read the Docs while building your documentation. [...]`).

No output of `sphinx-build` is shown.

**Comment by stsewd** [comment]
Sorry about this, we may have a fix for this problem tomorrow. See https://github.com/readthedocs/readthedocs.org/pull/7442

**Comment by dweindl** [comment]
Great. Thanks for looking into that.

**Comment by stsewd** [comment]
The problem should be fixed now https://readthedocs.org/projects/amici/builds/11805276/
