### ISSUE TITLE
Build error with build id #11794568

### ISSUE THREAD

**Issue by tkoyama010** [readthedocs/readthedocs.org#7436]
## Details:

* Project URL: https://readthedocs.org/projects/getfem-ja/
* Build URL(if applicable): https://readthedocs.org/projects/getfem-ja/builds/11794568/
* Read the Docs username(if applicable): tkoyama010

## Expected Result

*A description of what you wanted to happen*
No error

## Actual Result

*A description of what actually happened*
Error happend

**Comment by stsewd** [comment]
Sorry about this, we may have a fix for this problem tomorrow. See https://github.com/readthedocs/readthedocs.org/pull/7442
