### ISSUE TITLE
Build error with build id #11794938

### ISSUE THREAD

**Issue by loikein** [readthedocs/readthedocs.org#7437]
## Details:

* Project URL: https://readthedocs.org/projects/econsa/
* Build URL(if applicable): https://readthedocs.org/projects/econsa/builds/11794938/
* Read the Docs username(if applicable): loikein

## Actual Result

[This PR](https://github.com/OpenSourceEconomics/econsa/pull/71)'s build consistently fails, so I opened a [new branch](https://github.com/OpenSourceEconomics/econsa/pull/72) just to try if anything changes, but the errors persist.

Please help…

**Comment by stsewd** [comment]
Sorry about this, we may have a fix for this problem tomorrow. See https://github.com/readthedocs/readthedocs.org/pull/7442

**Comment by stsewd** [comment]
This should be fixed now https://readthedocs.org/projects/econsa/builds/11805061/
