### ISSUE TITLE
Build error with build id #11797510

### ISSUE THREAD

**Issue by ryw** [readthedocs/readthedocs.org#7440]
## Details:

* Project URL: https://readthedocs.org/projects/Airflow/
* Build URL(if applicable): https://readthedocs.org/projects/airflow/builds/11797510/
* Read the Docs username(if applicable): ryw

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by stsewd** [comment]
Sorry about this, we may have a fix for this problem tomorrow. See https://github.com/readthedocs/readthedocs.org/pull/7442

**Comment by stsewd** [comment]
This should be fixed now https://readthedocs.org/projects/airflow/builds/11805080/
