### ISSUE TITLE
Build error with #11800587 

### ISSUE THREAD

**Issue by domeckert** [readthedocs/readthedocs.org#7444]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pyproffit/
* Build URL (if applicable): https://readthedocs.org/projects/pyproffit/builds/11800587/
* Read the Docs username (if applicable): domeckert

## Expected Result

I am trying to import a documentation from the following Github repository:

https://github.com/domeckert/pyproffit

The sphinx build works on my home computer with the exact same settings. 

## Actual Result

The build fails because of some issue with theano. The error message appears similar to the one reported here:

https://stackoverflow.com/questions/46469587/readthedocs-sphinx-build-failing-but-working-locally

However, I have tried several times since yesterday, and the error persists.

**Comment by stsewd** [comment]
Looks like a problem with a C dependency https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by domeckert** [comment]
Thanks! Using the autodoc_mock_imports option for the packages with C dependencies does the trick
