### ISSUE TITLE
Build error with build id #11798910

### ISSUE THREAD

**Issue by kalvdans** [readthedocs/readthedocs.org#7445]
## Details:

* Project URL: https://readthedocs.org/projects/cupy/
* Build URL(if applicable): https://readthedocs.org/projects/cupy/builds/11798910/
* Read the Docs username(if applicable): AnonymousUser

## Expected Result

I expected one of the build steps to fail when the build is marked as a failure.

## Actual Result

All 10 step exited with exit code 0, but still the build was marked as a failure.

**Comment by stsewd** [comment]
This should be fixed now https://readthedocs.org/projects/cupy/builds/11805082/

**Comment by kalvdans** [comment]
Out of curiosity, what was the fix?

**Comment by stsewd** [comment]
This https://github.com/readthedocs/readthedocs.org/pull/7442
