### ISSUE TITLE
Build error with build id #11802003

### ISSUE THREAD

**Issue by adamchainz** [readthedocs/readthedocs.org#7446]
## Details:

* Project URL: https://readthedocs.org/projects/django-mysql/
* Build URL(if applicable): https://readthedocs.org/projects/django-mysql/builds/11802003/
* Read the Docs username(if applicable): AdamChainz

## Expected Result

Build works

## Actual Result

Build dies on `cat latexmkrc` 🤔

It started failing after a trivial change that removed one trailing spare newline in a .rst file: https://github.com/adamchainz/django-mysql/commit/e2b2887f6235b226eb8057fc59f7c3257296f317

**Comment by stsewd** [comment]
This should be fixed now https://readthedocs.org/projects/django-mysql/builds/11805518/
