### ISSUE TITLE
Link to Pull Request that built the documentation

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#7447]
Read the Docs now support building from Pull Request and it adds a message at the top of all the pages saying that this documentation is built from a Pull Request.

![Screenshot_2020-09-03_12-55-30](https://user-images.githubusercontent.com/244656/92106588-e9db2100-ede4-11ea-9442-9ddd85480b84.png)

It would be good if that message links to the Pull Request that generates the documentation that I'm reading so I can see the discussion around it.

**Comment by stsewd** [comment]
Duplicated of https://github.com/readthedocs/readthedocs.org/issues/6303
