### ISSUE TITLE
Failed builds for the last months for PlatformIO

### ISSUE THREAD

**Issue by ivankravets** [readthedocs/readthedocs.org#7448]
Read the Docs build information
Build id: 11802690
Project: platformio
Version: latest
Commit: 949ef2c48a23f8cc8013f6467328739a916d48a3
Date: 2020-09-03T12:17:37.702063Z
State: finished
Success: False

------

Please take a look at https://readthedocs.org/projects/platformio/builds/?page=1

P.S: Is something going wrong with PlatformIO? We already disabled WHOLE RTD functionality. Users complain about missed PDF and ePub formats. We disabled everything and can't build even minimal HTML.

Should we host our docs at Github Pages?

Thanks!

**Comment by stsewd** [comment]
Sorry about that, html builds should be working now, we had a problem with the last deploy https://github.com/readthedocs/readthedocs.org/pull/7442.

**Comment by ivankravets** [comment]
Thanks! I thought the whole of our account was banned.

Do you have any ideas on how to resolve all these FAILED builds?

**Comment by stsewd** [comment]
That we need to debug a little more, tomorrow this PR should be live https://github.com/readthedocs/readthedocs.org/pull/7449 and that will allow us to have more info to debug

**Comment by ivankravets** [comment]
Thanks, Santos! I'll restart a build tomorrow to see the changes.

**Comment by stsewd** [comment]
Just an update here, looks like the other PR doesn't affect the output, this one should do it https://github.com/readthedocs/readthedocs.org/pull/7473

**Comment by stsewd** [comment]
I just triggered a new build https://readthedocs.org/projects/platformio/builds/11887839/ it's passing now, not sure if the PDF is correct https://readthedocs.org/projects/platformio/downloads/

**Comment by ivankravets** [comment]
Wow! PDF... 😊  Thanks!!!

Santos, do we need this custom file https://github.com/platformio/platformio-core/blob/develop/.readthedocs.yml? I don't remember why we added it. It seems like we can control PDF/ePUB from the admin system.

**Comment by stsewd** [comment]
@ivankravets we recommend projects to use a configuration file instead of the dashboard. There are things you can't do in the dashboard, like disabling zip builds (this format can take a lot of resources to build), having more control over search and more https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings

**Comment by ivankravets** [comment]
Thanks again for your help and everything what you do! 🙏
