### ISSUE TITLE
Build error with build id #11803738

### ISSUE THREAD

**Issue by mbeyeler** [readthedocs/readthedocs.org#7450]
## Details:

* Project URL: https://readthedocs.org/projects/pulse2percept/
* Build URL(if applicable): https://readthedocs.org/projects/pulse2percept/builds/11803738/
* Read the Docs username(if applicable): mbeyeler

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by stsewd** [comment]
Your build is executing normally now. The failure looks related fo sphinx now https://readthedocs.org/projects/pulse2percept/builds/11805505/

**Comment by mbeyeler** [comment]
Ah, this makes more sense. The build referenced above simply had no output so there was no way of telling what was wrong. Thanks, I think I've got it from here.
