### ISSUE TITLE
Build error on latest and PRs in the past few days

### ISSUE THREAD

**Issue by pllim** [readthedocs/readthedocs.org#7451]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/astropy/
* Build URL (if applicable): https://readthedocs.org/projects/astropy/builds/?page=1
* Read the Docs username (if applicable): pllim

## Expected Result

Successful builds.

## Actual Result

Cryptic failures for both `latest` and PRs, but they don't happen right away. It usually fails after 800-900 seconds with such error:

```
Error

There was a problem with Read the Docs while building your documentation. Please try again later.
However, if this problem persists, please report this to us with your build id (xxxxxxx).
```

We waited a day or two but failures seem persistent, hence this issue. Hope you can help. Thank you!

**Comment by stsewd** [comment]
The problem should be fixed now https://readthedocs.org/projects/astropy/builds/11805264/

**Comment by pllim** [comment]
Thank you!
