### ISSUE TITLE
Build error with build id #11804721

### ISSUE THREAD

**Issue by balopat** [readthedocs/readthedocs.org#7452]
## Details:

* Project URL: https://readthedocs.org/projects/balopat-Cirq-RTD/
* Build URL(if applicable): https://readthedocs.org/projects/balopat-cirq-rtd/builds/11804721/
* Read the Docs username(if applicable): balopat

## Expected Result

It should have just published it, there are no errors in the logs. 
Local build works without warnings.

## Actual Result

It showed an error on the build page and did not deploy the final version.

**Comment by stsewd** [comment]
This should be fixed now https://readthedocs.org/projects/balopat-cirq-rtd/builds/11805884/
