### ISSUE TITLE
Invalid project name, a project already exists with that name

### ISSUE THREAD

**Issue by meherett** [readthedocs/readthedocs.org#7455]
## Details

* Read the Docs project URL: http://swap.readthedocs.io/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable): meherett

## Expected Result

This `swap` docs has clearly been abandoned. The docs has no description. So, I intend to replace this docs with https://github.com/meherett/swap

## Actual Result

*A description of what actually happened*

**Comment by stsewd** [comment]
For cases like this we follow https://docs.readthedocs.io/en/stable/abandoned-projects.html. I'll try to contact the user and start the 6 weeks count.

**Comment by stsewd** [comment]
I have emailed the user today.

/remind me about take action on this project in 6 weeks

**Comment by meherett** [comment]
Hi @stsewd, Is there any response from the owner? It's now for almost 6 weeks. I want to replace http://swap.readthedocs.io/en/latest/ with https://crypto-swap.readthedocs.io/ for this project https://github.com/meherett/swap.

**Comment by stsewd** [comment]
@meherett I haven't received any email from the owner. I have added you as owner of the project.
