### ISSUE TITLE
Remove unused projects from my account

### ISSUE THREAD

**Issue by git-abhijit** [readthedocs/readthedocs.org#7456]
## Details
How to delete the projects from my account which are not being used any more?

## Expected Result

Delete unused projects from my account.

## Actual Result

*A description of what actually happened*

**Comment by davidfischer** [comment]
Under your project settings under administration, there is a link to delete a project. Let me know if you have any issues.

![Screen Shot 2020-09-04 at 11 05 04 AM](https://user-images.githubusercontent.com/185043/92272519-8ad9e280-ee9e-11ea-909d-a8a50a5dd459.png)

**Comment by git-abhijit** [comment]
Thank you David.
