### ISSUE TITLE
Improvement proposal: YAML files should use recommended file extension in documentation recommendation

### ISSUE THREAD

**Issue by AvdN** [readthedocs/readthedocs.org#7460]
The recommended extension for files containing YAML documents is `.yaml` ( http://yaml.org/faq.html ) and this has been the case since at least Sep 2006 ( https://web.archive.org/web/20060924190202/http://yaml.org/faq.html ).

Some (outdated) projects/libraries still tend to advertise the `.yml`, probably motivated with DOS 8.3 file naming compatibility (or by not bothering to investigate if what an example project does is correct). Not using the recommended extension should however never be done without proper motivation for divergence (if done at all)

Moreover an YML file format (a domain specific language derivation from XML, https://fdik.org/yml/) has been in existence for about as long as YAML, making the use of `.yml` unnecessarily ambiguous.

Readthedocs already supports filenames with the proper extension such as `.readthedocs.yaml`. The documentation should be updated to exclusively recommend  files with `.yaml` extension, instead of those with `.yml`.

Readthedocs code should continue to support both extensions. And in general readthedocs should throw an error if multiple files exists for one configuration document (e.g.  `readthedocs.yml` and `.readthedocs.yaml`), if it doesn't already do so, and not silently prefer one exension over the other in code.

I can provide a pull request with the appropriate changes (just let me know).

**Comment by stsewd** [comment]
Sure, I think it's a good idea

**Comment by stsewd** [comment]
If someone wants to take this, the changes should be done in both v1 y v2 docs the https://docs.readthedocs.io/en/stable/config-file/index.html

**Comment by humitos** [comment]
I think this is already done, but you can take a look @astrojuanlu and probably close it.

**Comment by astrojuanlu** [comment]
Closed in #7918
