### ISSUE TITLE
Special !! values are reset to null in mkdocs.yml

### ISSUE THREAD

**Issue by pawamoy** [readthedocs/readthedocs.org#7461]
## Details

As reported [here](https://github.com/readthedocs/readthedocs.org/issues/6889#issuecomment-638502825) (the issue is now stale, not sure if you'd prefer the discussion to continue over there), values like `!!python/name:module.name` in `mkdocs.yml` are dropped during the build process. They end up being `null` in the final `mkdocs.yml`, which in turn breaks build in various places (mainly plugins).

* Build URL (if applicable): https://readthedocs.org/projects/copier/builds/11817460/

## Expected Result

These values should not be reset to `null` as it breaks the build. More details in the linked issue.

## Actual Result

Special values starting with `!!python/name:` in mkdocs are reset to null, and it breaks the build.

**Comment by stsewd** [comment]
The solution in https://github.com/readthedocs/readthedocs.org/issues/6889#issuecomment-638926236 should do the trick. We parse those inside a docker environment, so it should be safe.

**Comment by stsewd** [comment]
So, we execute that in the builders, but the parsing code is still executed inside the application layer, we are safe to execute commands that we send to docker, not the ones we execute inside the application layer.

So, we can't use the normal `parse` function here. Some options:

- Make this a script that would be executed inside the docker container.
- Find another way to parse the yaml file without executing random code and without modifying the original code (maybe another library?).
- Plugins shouldn't rely on that and find another way for users to set such options.

**Comment by pawamoy** [comment]
Here's a way to "fake" load `!!python/name:` tags without losing their value when redumping them:

```python
from pathlib import Path
import yaml


class ProxyPythonName(yaml.YAMLObject):
    def __init__(self, value):
        self.value = value


class CustomLoader(yaml.SafeLoader):
    def construct_python_name(self, suffix, node):
        value = self.construct_scalar(node)
        if value: 
            raise yaml.constructor.ConstructorError(
                "while constructing a Python name", node.start_mark, 
                "expected the empty value, but found %r" % value, node.start_mark
            ) 
        return ProxyPythonName(suffix)


class CustomDumper(yaml.SafeDumper):
    def represent_name(self, data):
        return self.represent_scalar("tag:yaml.org,2002:python/name:" + data.value, "")


CustomLoader.add_multi_constructor("tag:yaml.org,2002:python/name:", CustomLoader.construct_python_name)
CustomDumper.add_representer(ProxyPythonName, CustomDumper.represent_name)

string = Path("mkdocs.yml").read_text()
loaded = yaml.load(string, Loader=CustomLoader)
dumped = yaml.dump(loaded, Dumper=CustomDumper)
print(dumped)

```

**Comment by FeeeeK** [comment]
Two years later, the problem reappeared again, but this time with `!!python/object/apply`, needed for pymdown-extensions:
https://facelessuser.github.io/pymdown-extensions/faq/#function-references-in-yaml

**Comment by pawamoy** [comment]
Shouldn't be too hard to open a new issue asking if maintainers would be OK to support it, and to copy-paste the code of the previous PR adding support for `name` and change it a bit to support `apply`.

**Comment by humitos** [comment]
@FeeeeK it seems we implemented this only for `!!python/name``, see https://github.com/readthedocs/readthedocs.org/pull/7507#discussion_r495933841. I think we could expand that list now that there is a needing for this.

As a workaround for now, you could use the feature to [Override the build process](https://docs.readthedocs.io/en/latest/build-customization.html#override-the-build-process) by using `build.commands` config key. This way, Read the Docs won't do anything with your `mkdocs.yml` file and you MkDocs plugin will work.

Here is an example of how to create the `.readthedocs.yaml` file using this approach:

```yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3"
  commands:
    pip install -r requirements.txt
    mkdocs build --site-dir $READTHEDOCS_OUTPUT/html
```

**Comment by FeeeeK** [comment]
Thanks, @humitos, I already did it, but it would be nice if there were any warnings about this, now there is only traceback from toc without any additional info.
