### ISSUE TITLE
auto export `.readthedocs.yml` from website settings

### ISSUE THREAD

**Issue by graingert** [readthedocs/readthedocs.org#7463]
I'd like to have a button to generate a `.readthedocs.yml` from my control panel so I can paste it into github

Even better would be a button to make a PR to my project that contains the file

**Comment by graingert** [comment]
currently the process is very manual https://docs.readthedocs.io/en/stable/config-file/v2.html#migrating-from-the-web-interface

**Comment by stsewd** [comment]
Duplicate of https://github.com/readthedocs/readthedocs.org/issues/4746
