### ISSUE TITLE
Build failed: 'markdown_extensions'. Error: unsupported callable 

### ISSUE THREAD

**Issue by Jackiexiao** [readthedocs/readthedocs.org#7464]
## Details

* Read the Docs project URL:
* Build URL (if applicable):  Build #11828060
* Read the Docs username (if applicable):

## Actual Result

when exec
```
/home/docs/checkouts/readthedocs.org/user_builds/jackieblog/envs/latest/bin/python -m mkdocs build --clean --site-dir _build/html --config-file mkdocs.yml
```
Error
```
ERROR   -  Config value: 'markdown_extensions'. Error: unsupported callable 
```

**Comment by stsewd** [comment]
Please provide the build URL. I think you need to use the same mkdocs version you are suing locally, see https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

**Comment by halx99** [comment]
I also have this issue, please see build url:
https://readthedocs.org/projects/yasio-docs-437/builds/12665506/
