### ISSUE TITLE
Build cannot handle numpy/llvmlite dependency.

### ISSUE THREAD

**Issue by koaning** [readthedocs/readthedocs.org#7466]
## Details

* Read the Docs project URL: https://scikit-lego.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/scikit-lego/builds/11832312/
* Read the Docs username (if applicable): koaning

## Expected Result

I've not had these issues for years but after a month of inactivity we pushed a new version to the project. It seems like something has changed in how readthedocs is processing builds because the build is started failing since yesterday. 

## Actual Result

During the build phase I get this error message: 

```
Installed /home/docs/checkouts/readthedocs.org/user_builds/scikit-lego/envs/latest/lib/python3.7/site-packages/joblib-0.16.0-py3.7.egg
Searching for llvmlite<0.35,>=0.34.0.dev0
Reading https://pypi.org/simple/llvmlite/
Downloading https://files.pythonhosted.org/packages/0b/96/07bfa93a103fb9e3e9ae7f9f7c6687ae714aee66b6f3000da3fad71e0aa2/llvmlite-0.34.0.tar.gz#sha256=f03ee0d19bca8f2fe922bb424a909d05c28411983b0c2bc58b020032a0d11f63
Best match: llvmlite 0.34.0
Processing llvmlite-0.34.0.tar.gz
Writing /tmp/easy_install-mb5hdc0a/llvmlite-0.34.0/setup.cfg
Running llvmlite-0.34.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-mb5hdc0a/llvmlite-0.34.0/egg-dist-tmp-37qxiwgu
error: Setup script exited with setup.py disabled on readthedocs: called with ['/tmp/easy_install-mb5hdc0a/llvmlite-0.34.0/setup.py', '-q', 'bdist_egg', '--dist-dir', '/tmp/easy_install-mb5hdc0a/llvmlite-0.34.0/egg-dist-tmp-37qxiwgu']
```

I am running this build with "install project" and "use system packages" turned on. The "use system packages" is something that I had never turned on before but without it turned on I got a numpy install error [see build here](https://readthedocs.org/projects/scikit-lego/builds/11828986/).

**Comment by humitos** [comment]
Hi @koaning! You may need to ask the author of the package about that problem. They call `sys.exit` when the package is installed on Read the Docs: https://github.com/numba/llvmlite/blob/master/setup.py#L25

On the other hand, you probably shouldn't install all of the dependencies of your package just to build the documentation. You can mock them all. See https://docs.readthedocs.io/en/latest/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules
