### ISSUE TITLE
Build error with build id #11800556

### ISSUE THREAD

**Issue by BlairLee** [readthedocs/readthedocs.org#7470]
## Details:

* Project URL: https://readthedocs.org/projects/datasetinsights/
* Build URL(if applicable): https://readthedocs.org/projects/datasetinsights/builds/11800556/
* Read the Docs username(if applicable): BlairLee

## Expected Result

Build successfully.

## Actual Result

I got this persistent error:
`Error: There was a problem with Read the Docs while building your documentation. Please try again later. However, if this problem persists, please report this to us with your build id (11800556).` 

Can someone tell me how I could handle it?

**Comment by stsewd** [comment]
That build is from last week, we already fixed that problem. Let us know if this is happening with a recent build.
