### ISSUE TITLE
Missing functions in documentation page with build id #11845404

### ISSUE THREAD

**Issue by loikein** [readthedocs/readthedocs.org#7472]
## Details

* Read the Docs project URL: https://econsa--71.org.readthedocs.build/en/71/methods/utility.html
* Build URL (if applicable): https://readthedocs.org/projects/econsa/builds/11845404/
* Read the Docs username (if applicable):

## Expected Result

This is how the mentioned page looks like (as expected) on my local machine:

![截图 2020-09-09 19 18 02](https://user-images.githubusercontent.com/20618587/92643390-3769f900-f2d1-11ea-94cb-61454ee9410e.png)

## Actual Result

This is the result on RTD: (only this page is affected, others are all fine)

![截图 2020-09-09 19 17 44](https://user-images.githubusercontent.com/20618587/92643401-3df87080-f2d1-11ea-9678-1a0586bc07c8.png)

**Comment by stsewd** [comment]
If you click the boxes, you can see there is warning

```
WARNING: autodoc: failed to import module 'correlation' from module 'econsa'; the following exception was raised:
No module named 'statsmodels'
```

You need to install your package or some dependencies.

**Comment by loikein** [comment]
Thank you for your prompt reply. I will edit the environment and see if the problem fixes…

**Comment by loikein** [comment]
That worked indeed! Thank you again.
