### ISSUE TITLE
Not getting email confirmation 

### ISSUE THREAD

**Issue by iceback** [readthedocs/readthedocs.org#7478]
## Details
I've requested an email confirmation a couple of times but I've not seen any emails.  The address is correct, is associated with my gitlab account.  The mail host is utah.edu.
I did successfully register/verify a second email at xmission.com

* Read the Docs project URL: https://readthedocs.org/projects/pcatag/builds/11861918
* Build URL (if applicable): https://gitlab.com/camplab/pcatag
* Read the Docs username (if applicable): Sargent

## Expected Result
An email at utah.edu
## Actual Result
No email at utah.edu in over an hour

**Comment by humitos** [comment]
Hi! Read the Docs is currently sending out emails without problems. I just tried this by myself with my account and I got the email immediately. Maybe there was a temporary issue in your email provider?

**Comment by iceback** [comment]
Thank you for your reply.

While I have successfully registered this private e-mail account, the 
proper account for these projects (PCAtag, UGenie), is 
"rob.sargent@utah.edu", since that account connects to the respective 
gitlab repositories.

I have received the following response from University of Utah IT 
department:


On 9/14/20 4:> Short description: Blocked email
> 
> Close notes: Rob, I've attached a report to this ticket showing the message was delivered to your mailbox. There is one possible hangup, this sender has a reputation that borders on being delivered, they are right at the number that would prevent the message from being delivered. If it wasn't really delivered to your mailbox it would be because they have a poor reputation with Cisco and will need to work on that reputation to get through the filters. But again the message does show delivered and hits the mailbox server. If it were blocked it would not hit the mailbox server, it would have been quarantined before being sent to the mailbox server.

However as I read the logs supplied with the above, I'm confident that 
the message has not been delivered to my inbox and I am in contact with 
the local IT staff.

If you can in anyway address the notion of "poor reputation" I would 
happily forward that on.  Alternatively, if ReadTheDocs personnel could 
mark the problematic account as "confirmed" that too would solve the issue.

Thanks for your time,
rjs

**Comment by iceback** [comment]
Perhaps this issue and issue #7501 should be linked.  They're very likely the same root cause: sendgrid.net is viewed as a spammer by more institutions than just mine

**Comment by SimUKdev** [comment]
I'm also experiencing the same, I don't get the verification email. I've waited for it to arrive, over a few days, and re-requested the verification email. Other expected emails are arriving correctly.

Read the Docs username:  SimUK

**Comment by stsewd** [comment]
I think this was the same as https://github.com/readthedocs/readthedocs.org/issues/7501, it should be fixed now. If not, please let us know.
