### ISSUE TITLE
Unexpected error after minor changes.

### ISSUE THREAD

**Issue by QLutz** [readthedocs/readthedocs.org#7480]
## Details

* Read the Docs project URL: https://scikit-network.readthedocs.io/en/latest/reference/index.html
* Build URL (if applicable): https://readthedocs.org/projects/scikit-network/builds/11876754/
* Read the Docs username (if applicable): QLutz

## Expected Result

We expected a successful doc build. Changes from the last successful built were minimal, no package were updated and the doc can be built locally without warning or errors with up-to-date dependencies.

## Actual Result

An unexpected error got raised:
AssertionError: wrong color format 'var(--jp-mirror-editor-variable-color)'

A very similar issue has been raised by other users recently as seen [here](https://stackoverflow.com/questions/63840334/fix-some-very-minor-issues-and-rebuild-sphinx-but-got-the-error-wrong-color-for).

**Comment by stsewd** [comment]
I think this may be due https://github.com/readthedocs/readthedocs.org/blob/65f96bd542ceb316eff984fbc991d8fa6530a481/readthedocs/doc_builder/python_environments.py#L355-L355

We shouldn't pre-install that dep and rely on sphinx or whatever tool to install the correct version of the dependency. We may need to dig a little more and see if sphinx was always requiring that package or the reason why we pinned the package.

**Comment by stsewd** [comment]
Sphinx declares that dependency in the latest version https://github.com/sphinx-doc/sphinx/blob/bec30596a8f7487cad23df532bf02d1b29024dbc/setup.py#L25

and since 1.0 https://github.com/sphinx-doc/sphinx/blob/690fc257e9a539a4c193ba8efe5587f7c102785c/setup.py#L47

So I think we are safe to remove it.

**Comment by stsewd** [comment]
But looks like sphinx should work with any 2.x version.

**Comment by stsewd** [comment]
In the meantime you can try installing `Pyments==2.7.0 ` in your dependencies.

**Comment by QLutz** [comment]
Thank you for your answer.

I was able able to built the doc locally with Pygments 2.7.0 and 2.3.1 (previous install was 2.6.1).

To give you an idea, our last successful remote build was 5 days ago so any harmful changes in RTD would have had to occur in the last few days.

**Comment by stsewd** [comment]
We didn't change anything that could break this, I think it may be related to an unpinned dependency from another library.

**Comment by QLutz** [comment]
The same issue has been raised on Sphinx (https://github.com/sphinx-doc/sphinx/issues/8198). It seems that pinning Pygments did indeed fix the issue for some. I'll go ahead and try to make a remote build doing this.

**Comment by QLutz** [comment]
Pinning `Pygments==2.7.1` solved the issue.

Thanks a lot for your time and help!
