### ISSUE TITLE
[FR] Have a special page listing linkable Spihnx objects per site

### ISSUE THREAD

**Issue by webknjaz** [readthedocs/readthedocs.org#7481]
## Details

Spihnx has intersphinx to allow referencing objects exposed via other Sphinx-based websites. It's already exposed as `objects.inv` in a machine-readable format but it's not particularly easy for end-users to read it (the only relatively sane way is CLI-based).

I suggest embedding a preview page on each site that would have some interface (maybe even filter/search/example) exposing those linkable objects.

I've made https://webknjaz.github.io/intersphinx-untangled (src: https://github.com/webknjaz/intersphinx-untangled) as a very simple preview for myself but hopefully, you could draw some inspiration from this demo.

## Expected Result

It should be easy to link against things on other RTD sites w/o hardcoding URLs.

## Actual Result

It's not that easy. See also: https://github.com/sphinx-doc/sphinx/issues/8211.

**Comment by stsewd** [comment]
It's in our roadmap of ideas to implement a feature like this actually. Nice demo!

**Comment by ericholscher** [comment]
@webknjaz We have this data in our DB already, so if you wanted to build a display on top it wouldn't be hard. I don't know if we're exposing it via our API at all, but that might be a good option:

https://github.com/readthedocs/readthedocs.org/blob/8e78d680d02aeba12644796b979ef62459f64932/readthedocs/sphinx_domains/models.py#L18

**Comment by stsewd** [comment]
So, we ended up removing that app/table, we no longer have that information in the DB, but I think this can still be built by inspecting the objects.inv file.

**Comment by ericholscher** [comment]
Yea, I think this is probably something that we aren't going to build into RTD at this point, given that we're moving toward support as a general platform for docs, not just Sphinx. I'm going to close this, as I think using objects.inv and Sphinx-specific integration is going to be a better approach.
