### ISSUE TITLE
Please to check my project

### ISSUE THREAD

**Issue by matthieucabos** [readthedocs/readthedocs.org#7485]
## Details

* Read the Docs project URL:https://readthedocs.org/projects/matrix-lib-v20/
* Build URL (if applicable):https://readthedocs.org/projects/matrix-lib-v20/
* Read the Docs username (if applicable):matthieucabos

## Expected Result

*A description of what you wanted to happen*
Please to compile my documentation. All is working well when compiled by myself...

## Actual Result

*A description of what actually happened*
The compilation stop with the error message : 
Sphinx error:
master file /home/docs/checkouts/readthedocs.org/user_builds/matrix-lib-v20/checkouts/latest/source/contents.rst not found

![readthedocs_failure](https://user-images.githubusercontent.com/38350182/93313562-ec883e00-f808-11ea-8a1c-9d76c84ea2a9.PNG)

**Comment by stsewd** [comment]
You need to set `master_doc = 'index'` in your conf.py file or set `sphinx>2.0` in https://github.com/matthieucabos/Matrix_lib-v2.0/blob/18d1df949580d55ff10e4579d3db42af65c3d124/source/requirements.txt#L3

**Comment by matthieucabos** [comment]
Tanks a lot for this one
Best regards

Le mer. 16 sept. 2020 à 16:48, Santos Gallegos <notifications@github.com> a
écrit :
