### ISSUE TITLE
Markdown Table Not rendering properly

### ISSUE THREAD

**Issue by git-abhijit** [readthedocs/readthedocs.org#7486]
## Details
Have installed the following tools as suggested in some of the other  github issues , but still the problem  persists. 

Github issues references : 
https://github.com/readthedocs/readthedocs.org/issues/4466
https://github.com/readthedocs/recommonmark/issues/103
https://github.com/ryanfox/sphinx-markdown-tables

Attaching the conf.py file -- modified the extension as txt to upload it
[conf.txt](https://github.com/readthedocs/readthedocs.org/files/5230904/conf.txt)
, requirements.txt file and the advanced setting. 
[requirements.txt](https://github.com/readthedocs/readthedocs.org/files/5230893/requirements.txt)

![image](https://user-images.githubusercontent.com/48888213/93313445-1ac84680-f826-11ea-94f7-6b56ddc003cf.png)

* Read the Docs project URL: http://docs.edgegallery.org/zh_CN/latest/Projects/APPSTORE/AppStore_Dependency.html#appstore-be

* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result
the results should come in table but currently its showing as txt file. 

*A description of what you wanted to happen*

The .md files when being viewed on Markdown viewer the display is fine, but in the Read The Docs page its not showing properly. 

## Actual Result
Showing as below , (in the github issue the format is able to render it but same is not happening on local , as well read the docs public server)

## AppStore-be •
|	groupId	|	artifactId	|	version	|	license	|	direct import (Y/N)	|
|	---	|	---	|	---	|	---	|	---	|
|	aopalliance	|	aopalliance	|	1.0 	|	Public Domain	|	N	|
|	com.fasterxml	|	classmate	|	1.4.0 	|	The Apache Software License, Version 2.0	|	N	|
|	com.fasterxml.jackson.core	|	jackson-annotations	|	2.9.0 	|	The Apache Software License, Version 2.0	|	N	|
|	com.fasterxml.jackson.core	|	jackson-core	|	2.9.9 	|	The Apache Software License, Version 2.0	|	N	|
|	com.fasterxml.jackson.core	|	jackson-databind	|	2.9.10.6 	|	The Apache Software License, Version 2.0	|	Y	|
|	com.fasterxml.jackson.dataformat	|	jackson-dataformat-xml	|	2.9.9 	|	The Apache Software License, Version 2.0	|	N	|
|	com.fasterxml.jackson.dataformat	|	jackson-dataformat-yaml	|	2.9.9 	|	The Apache Software License, Version 2.0	|	N	|
|	com.fasterxml.jackson.datatype	|	jackson-datatype-jdk8	|	2.9.9 	|	The Apache Software License, Version 2.0	|	N	|
|	com.fasterxml.jackson.datatype	|	jackson-datatype-jsr310	|	2.9.9 	|	The Apache Software License, Version 2.0	|	N	|
|	com.fasterxml.jackson.module	|	jackson-module-jaxb-annotations	|	2.9.9 	|	The Apache Software License, Version 2.0	|	N	|
|	com.fasterxml.jackson.module	|	jackson-module-parameter-names	|	2.9.9 	|	The Apache Software License, Version 2.0	|	N	|
|	com.fasterxml.woodstox	|	woodstox-core	|	5.0.3 	|	The Apache License, Version 2.0	|	N	|
|	com.github.ben-manes.caffeine	|	caffeine	|	2.6.2 	|	Apache License, Version 2.0	|	N	|
|	com.github.waffle	|	waffle-jna	|	1.9.1 	|	Eclipse Public License	|	N	|
|	com.google.code.findbugs	|	jsr305	|	3.0.2 	|	The Apache Software License, Version 2.0	|	N	|
|	
*A description of what actually happened*

**Comment by stsewd** [comment]
If you build your project locally with the same sphinx and python version as rtd do you see the same?

**Comment by git-abhijit** [comment]
@stsewd 
Yes the results are same in the local environment also.

**Comment by stsewd** [comment]
Then this isn't a problem related to read the docs, please try asking in stackoverflow or in the package repo or similar.

**Comment by git-abhijit** [comment]
@stsewd , what is the configuration to support markdown tables in read the docs?
