### ISSUE TITLE
Can't get RTD to build C extension with setup.py after reading FAQ

### ISSUE THREAD

**Issue by dtamayo** [readthedocs/readthedocs.org#7488]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/celmech
* Build URL (if applicable): https://readthedocs.org/projects/celmech/builds/11897380/
* Read the Docs username (if applicable): 

## Expected Result

make html works fine locally.
I want RTD to build the project's C extension so that I can import the project's modules for autodoc

## Actual Result

Can't import project modules because it can't find the shared library:

```
WARNING: autodoc: failed to import module 'andoyer' from module 'celmech'; the following exception was raised:
...
OSError: /home/docs/checkouts/readthedocs.org/user_builds/celmech/checkouts/latest/celmech/../libcelmech.cpython-37m-x86_64-linux-gnu.so: cannot open shared object file: No such file or directory
```

I don't *think* it's a path issue. I'm appending in conf.py like this:

`sys.path.append(os.path.abspath('../'))`

As far as I can tell, the C extension isn't being built at all. This line installs all requirements fine:

`home/docs/checkouts/readthedocs.org/user_builds/celmech/envs/latest/bin/python -m pip install --use-feature 2020-resolver --exists-action=w --no-cache-dir -r docs/requirements.txt
`
but doesn't seem to build our project's C extension (libcelmech) missing above

Comparing to another project with a C extension, theirs seems to get built with

`/home/docs/checkouts/readthedocs.org/user_builds/kliff/envs/latest/bin/python /home/docs/checkouts/readthedocs.org/user_builds/kliff/checkouts/latest/setup.py install --force
`
which goes on to show all the compilation lines with gcc. It seems like this project (https://readthedocs.org/projects/kliff/) installs it with its setup.py, whereas ours is using pip install (not sure if that's using PyPI?). I have the checkbox in our project's advanced settings "Install your project inside a virtualenv using setup.py install", which doesn't seem to be happening, as well as "use system packages".

Thanks for any help.

**Comment by stsewd** [comment]
I think you are missing installing your package itself, you are using a configuration file, so the options from the admin are ignored.

https://github.com/shadden/celmech/blob/4b46347ef635653bf1b7c3296f53bdf1f2d73200/.readthedocs.yml#L20-L23

```yaml
   install:
      - method: pip
        path: .

```

https://docs.readthedocs.io/en/stable/config-file/v2.html#packages

**Comment by dtamayo** [comment]
That worked great, thank you so much for your time
