### ISSUE TITLE
Outdated pygments version?

### ISSUE THREAD

**Issue by balopat** [readthedocs/readthedocs.org#7492]
## Details

See the discussion on: https://github.com/sphinx-doc/sphinx/issues/8198#issuecomment-692525937
I had to update pygments on my project to get over this issue that started roughly a week ago. 

https://github.com/quantumlib/Cirq/issues/3315

* Read the Docs project URL: http://cirq.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/cirq/builds/11853534/

## Expected Result

Successful build without having to figure out the right Pygments version.

## Actual Result

We have to pin pygments as the version is outdated in RTD.

**Comment by stsewd** [comment]
@balopat thanks for reporting, we have an open PR that fixes this problem https://github.com/readthedocs/readthedocs.org/pull/7490

**Comment by jordanperr** [comment]
We are still having this issue for pull requests for our package. Here's a link to a failed build with this issue: https://readthedocs.org/projects/openoa/builds/11932750/

Has the fix been applied to production readthedocs servers yet? Thank you.

**Comment by stsewd** [comment]
> Has the fix been applied to production readthedocs servers yet? Thank you.

No, it will live tomorrow

**Comment by stsewd** [comment]
The fix should be live now https://readthedocs.org/projects/openoa/builds/11938831/ pygments isn't installed by rtd, but as a requirement of sphinx
