### ISSUE TITLE
Document how to disable USE_NEW_PIP_RESOLVER (--use-feature=2020-resolver)

### ISSUE THREAD

**Issue by jwhitlock** [readthedocs/readthedocs.org#7498]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/ichnaea
* Build URL (if applicable): https://readthedocs.org/projects/ichnaea/builds/11930008/
* Read the Docs username (if applicable): jwhitlock

## Expected Result

Our project uses hashes, to validate the signature of package downloads, and constraints, to specify the requirements of requirements. This works with pip 20.2.3, unless the ``--use-feature=2020-resolver`` is specified, due to that version not considering hashes in constraints files:

* https://github.com/mozilla/ichnaea/pull/1289
* https://github.com/pypa/pip/issues/8792

I expected readthedocs.org to continue using the "old" resolver until pip 20.3 was released and it became the default resolver.

## Actual Result

With https://github.com/readthedocs/readthedocs.org/pull/7412 merged, the documentation is installed with ``--use-feature=2020-resolver``, and the build fails. I am unable to determine how to disable this, with ``.readthedocs.yaml`` or in the web-based admin.

**Comment by stsewd** [comment]
Hi, we are testing that feature in some random projects to help identify problems with the new resolver before it's enabled by default the next month. I have removed your project from that test, builds are passing now https://readthedocs.org/projects/ichnaea/builds/11930830/. If someone needs to disable that, opening an issue or emailing us is the path to disable it.

**Comment by jakirkham** [comment]
We are also seeing this in dask-image builds ( https://readthedocs.org/projects/dask-image/builds/12159489/ ). Would it be possible to disable it there as well?

FWIW we use Conda to install dependencies. Not sure if builds using Conda will be able to pick up dev versions of pip (depending on how it is installed). Figured it was worth mentioning in case others using Conda run into this as well 🙂

**Comment by stsewd** [comment]
@jakirkham yes, this error is bc your conda file is declaring an old version of pip, I have removed your project from that sample. https://readthedocs.org/projects/dask-image/builds/12220295/

**Comment by jakirkham** [comment]
Thanks! 😄

> Is there a way to configure RTD to use pip to just install our package and nothing else?

Any thoughts on this question?

**Comment by stsewd** [comment]
@jakirkham I'm not sure if this is going to work, but you can try with https://docs.readthedocs.io/en/stable/config-file/v2.html#packages

(make sure you read the conda section too, since looks like you are using the version 1 of the config file)

https://github.com/dask/dask-image/blob/master/readthedocs.yml
