### ISSUE TITLE
build failing due to pdflatex although not requested

### ISSUE THREAD

**Issue by fmigneault** [readthedocs/readthedocs.org#7503]
## Details

* Read the Docs project URL: https://readthedocs.org/dashboard/pavics-weaver
* Build URL (if applicable): https://readthedocs.org/projects/pavics-weaver/builds/11941746/  (latest)
* Read the Docs username (if applicable): fmigneault

I'm a bit confused as to why this build suddenly fails building `pdflatex`, as it is clearly disabled (and not desired) in advanced features. 
There is also *many* other successful builds of the `latest` branch. Issue just appeared recently (within ~last 2 months)
(last successful build of `latest`: https://readthedocs.org/projects/pavics-weaver/builds/11507255/) 

## Expected Result

`pdflatex` should just not be executed at all

## Actual Result

`pdflatex` is executed although disabled, and fails the build (as expected) - only `html` is intended

**Comment by stsewd** [comment]
@fmigneault you are using a configuration file, when using v2, the options from the web admin are ignored https://github.com/crim-ca/weaver/blob/2eefabbc5043f807055d07143f8c2b62274ca3d0/.readthedocs.yml#L5


https://docs.readthedocs.io/en/stable/config-file/v2.html#formats
