### ISSUE TITLE
Edit on github link follows symbolic link directly - creates wrong URL

### ISSUE THREAD

**Issue by PrometheusPi** [readthedocs/readthedocs.org#7504]
## Details

* Read the Docs project URL: https://picongpu.readthedocs.io
* Build URL (if applicable): https://github.com/ComputationalRadiationPhysics/picongpu/tree/dev/docs

## Expected Result
The "Edit on Github" button on https://picongpu.readthedocs.io/en/latest/examples/LaserWakefield/README.html
 should link to `https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/share/picongpu/examples/LaserWakefield/README.rst`.

## Actual Result
The "Edit on Github" button actually link to `https://github.com/ComputationalRadiationPhysics/picongpu/tree/dev/docs/source/examples/LaserWakefield/README.rst`.

```diff
- https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/docs/source/examples/LaserWakefield/README.rst
+ https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/share/picongpu/examples/LaserWakefield/README.rst
```

This is most likely caused by the symbolic link https://github.com/ComputationalRadiationPhysics/picongpu/blob/dev/docs/source/examples that points from the general documentation directory to the a documentation if the examples. 

The documentation is pared fine and in a standalone sphinx build, a txt of the rst file is generated and linked correctly. Only the link is erroneous.

**Comment by stsewd** [comment]
I don't think we have a way to detect if a file was generated from a symlink, I think the VCS provider (github) should be in charge of redirect to the correct file. Similar to https://github.com/readthedocs/readthedocs.org/issues/4043

**Comment by PrometheusPi** [comment]
@stsewd Thank you for the information.

**Comment by humitos** [comment]
I'm closing this issue since there isn't too much we can do here. We will be discussing how to make this feature work in a reliably way for the new implementation of the flyout in https://github.com/readthedocs/readthedocs.org/issues/10742
