### ISSUE TITLE
my readthedocs repo has got out of control, probably after too many force pushes

### ISSUE THREAD

**Issue by parmentelat** [readthedocs/readthedocs.org#7505]
## Details

* Read the Docs project URL:
https://readthedocs.org/projects/ue12-git/
* Build URL (if applicable):
https://readthedocs.org/projects/ue12-git/builds/11946363/
* Read the Docs username (if applicable):
parmentelat

## Expected Result

right now, the `devel` and `rtd` branches  on github are on commit `4a6147f`
I'd expect this to be the basis for my build

## Actual Result

what's happening is the build uses an old content, and the pages contents do not reflect my latest pushes - they seem like a couple commits late..

in particular the build page https://readthedocs.org/projects/ue12-git/builds/11946363/ 
show this; the displayed commit sha1 is correct , but - I take it - because of the detached state thingy, something is not right

![image](https://user-images.githubusercontent.com/4519227/94040594-7025ca00-fdc9-11ea-919f-0fac0b8b5879.png)

I've been doing quite a few force pushes, and I guess this is the problem

regardless, is there an easy way to reset the readthedocs repo so that it will get cloned from scratch again ?
preferably without re-creating the project because I've had a hard time getting the webhooks to actually trigger and I'd like to keep it this way

many thanks in advance

ps
if I had a way, here's the commands I'd run in that repo to reset it to the initial commit

```bash
git fetch origin
branches=$(git branch --format="%(refname:short)")
initial=$(git rev-list --max-parents=0 HEAD)
for branch in $branches; do git checkout $branch; git reset --hard $initial; git pull; done
```

**Comment by stsewd** [comment]
We refresh all tags/branches on push events and when building the docs, so, most likely this is a race condition with the time the builds were triggered and the force pushes. I can see all recent builds reflect the latest commit of each branch now.

https://readthedocs.org/projects/ue12-git/builds/

**Comment by parmentelat** [comment]
right, looks like it came back into line, thanks !
