### ISSUE TITLE
Build error with build id #11957776 without any error message

### ISSUE THREAD

**Issue by Trinkle23897** [readthedocs/readthedocs.org#7508]
## Details:

* Project URL: https://readthedocs.org/projects/tianshou/
* Build URL(if applicable): https://readthedocs.org/projects/tianshou/builds/11957776/
* Read the Docs username(if applicable): Trinkle23897

Hi, our most recent commit is to add MANIFEST.in in our repo (thu-ml/tianshou#227), however, the documentation build failed without any information. I tried to re-build and the error still exists.
Is there anyone help me to figure out what happened? Thanks in advance!

**Comment by humitos** [comment]
This may be a temporary issue. I didn't find anything specifically related to your project. Also, there are new builds passing for `master` version. Please, report back if you think this is happening often.

**Comment by ntessore** [comment]
@humitos Same thing happening to us as well? https://readthedocs.org/projects/skypy/builds/11979476/

**Comment by stsewd** [comment]
@ntessore builds are passing now https://readthedocs.org/projects/skypy/builds/, if you see this more than once and very often feel free to report.
