### ISSUE TITLE
cannot edit ldaptor settings without truncating description

### ISSUE THREAD

**Issue by graingert** [readthedocs/readthedocs.org#7511]
## Details

* Read the Docs project URL: https://readthedocs.org/dashboard/ldaptor/edit/
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

tried to set git url from https://github.com/twisted/ldaptor.git to https://github.com/twisted/ldaptor

## Actual Result

failed with `Ensure this value has at most 150 characters (it has 265). Description:` but I didn't edit that field

![image](https://user-images.githubusercontent.com/413772/94341163-3f2eda80-ffff-11ea-8564-fd85e0a69713.png)

and the description works fine here: https://readthedocs.org/projects/ldaptor/

I believe the project was grandfathered in to the old, larger, description limits and I want to be able to configure the project without loosing that privilege

**Comment by graingert** [comment]
related https://github.com/readthedocs/readthedocs.org/pull/7186

**Comment by humitos** [comment]
> I want to be able to configure the project without loosing that privilege

I think that won't be possible. Maybe @stsewd has more context about why we needed shorter descriptions.

However, I believe they will be completely removed (or highly de-emphasized) in the new look&feel of the site that will come sometime soon.

**Comment by stsewd** [comment]
@graingert we don't allow more than 150 now, so you'll need a shorter description, I think a larger description should be in the documentation itself.

**Comment by graingert** [comment]
That's fair, I've now shortened the description. It might be a good idea to include a notice in the admin messages banner about this new limit
