### ISSUE TITLE
having trouble enabling PR builds for twisted

### ISSUE THREAD

**Issue by graingert** [readthedocs/readthedocs.org#7515]
## Details

* Read the Docs project URL: https://readthedocs.org/dashboard/twisted/advanced/#id_external_builds_enabled
* Build URL (if applicable): https://github.com/twisted/twisted/pull/1409
* Read the Docs username (if applicable): glyph, graingert
* PR: https://github.com/twisted/twisted/pull/1409

## Expected Result

PR build to run

## Actual Result

the PR builder ignored https://github.com/twisted/twisted/pull/1409

/cc @glyph

**Comment by graingert** [comment]
note that it worked with https://github.com/twisted/ldaptor/pull/185 - which has the same configuration

**Comment by humitos** [comment]
@graingert Hi! Have you read this section already? https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html#troubleshooting

**Comment by graingert** [comment]
@humitos I tried those trouble shooting steps with @glyph https://freenode.logbot.info/twisted-dev/20200928#c5266162-c5267447

**Comment by humitos** [comment]
I think I found the issue and there is no easy way to solve it by the project maintainer.

Your project is not related with a `RemoteRepository` object in out database. That could be because it was imported manually without using our "Import Project" wizard or because the user that imported the project deleted their account.

That said, I can fix this by reconnecting your project to a `RemoteRepository` in our DB. However, I will need a username (with GH account connected) on Read the Docs that is maintainer of the `twisted` project with admin permissions in the `twisted/twisted` project on GitHub.

> Another potential fix (be careful!), is to _delete the twisted project_ from Read the Docs and re-import it by using the "Import Project" form by an admin of the Twisted project on GH.

**Comment by graingert** [comment]
@glyph should be able to do both

**Comment by humitos** [comment]
I went ahead and linked your project with @glyph 's `RemoteRepository` in our database. Could you please re-trigger a PR build and let me know if it's fixed?

**Comment by humitos** [comment]
> there is no easy way to solve it by the project maintainer.

Re-reading the code, I think was wrong. If "there is at least one maintainer of the RTD project with their GH account connected and admin permission the GH repository" Read the Docs should be able to report the build status of the PRs.

Also, in your case, as we weren't able to report the GH status, maintainers of Twisted project should have an in-site notification like: "Could not send GitHub build status report for Twisted...". @graingert do you have it?

**Comment by graingert** [comment]
@humitos I tried to recreate the PR https://github.com/twisted/twisted/pull/1409 but it still didn't trigger

**Comment by graingert** [comment]
@humitos I don't have access to those reports

**Comment by glyph** [comment]
@humitos what do you mean by "in-site notification"?

**Comment by glyph** [comment]
This is what this should look like, yes?

<img width="796" alt="image" src="https://user-images.githubusercontent.com/716529/94722514-44946980-030c-11eb-924a-f8c78a29a5a8.png">

**Comment by graingert** [comment]
I've created a github support ticket: https://support.github.com/ticket/personal/0/852155

**Comment by humitos** [comment]
I took a look at the last 10 (we don't record more than that) webhook events that we received and there is no webhook event `pull_request` (https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/webhook-events-and-payloads#pull_request) coming from your repository, which is the one that triggers the build for pull requests and report the status back to GH.

Can you check in your GH repository settings that there is a webhook enabled there and the `pull_request` event is set? Also, GH should show you there the list of past event sent to Read the Docs. Can you check there that `pull_request` events are being sent? (they have this request header: `X-Github-Event: pull_request`)

**Comment by humitos** [comment]
I created this PR in Twisted repository and I can confirm that we didn't receive the webhook. So, it seems the GH webhook is not fully configured and you may need to edit it manually to add `pull_request` event as well. If it's already active, there may be another issue that I can't think of right now.

**Comment by graingert** [comment]
@glyph @humitos this checkbox ![image](https://i.imgflip.com/4go3nq.jpg)

**Comment by humitos** [comment]
@graingert yes

**Comment by graingert** [comment]
@izuzak has replied to my support ticket:

> > > > @glyph has given full access to RTD via the RTD OAuth app, but it seems unable to manage webhooks
> > > > https://github.com/readthedocs/readthedocs.org/issues/7515#issuecomment-701550733 (@graingert)
> > > Thanks for reaching out. The comment you linked to shows that the user authorized the OAuth App, but it shows no details regarding the API call which was made to manage webhooks and failed.
> > > 
> > > Could you please send us the full output of a curl -v request (http://curl.haxx.se/) that clearly demonstrates the behavior you described, or equivalent logs? We're interested in seeing the full HTTP request and response objects for that API call, including all headers and bodies (that's what the -v flag does). That should help us investigate and provide advice. Just make sure you mask sensitive information like authentication credentials in the output of the curl command. (@izuzak)
> >
> > hey Ivan, can you add @humitos and @glyph to this ticket? or if that's not possible would it be best to respond on here? https://github.com/readthedocs/readthedocs.org/issues/7515 (@graingert)
>
> I can do that, but we'd first need to verify that those two users are okay with being added to this thread. Can you please ask the users in that public issue to confirm that they're okay with being added to the support thread and also share the message you sent to us initially so that they have all the relevant context? (@izuzak)

**Comment by humitos** [comment]
@graingert I'm OK to be looped into that thread after we have your confirmation that `twisted/twisted` GitHub repository has a webhook properly set to hit Read the Docs with `pull_request` event checked _and_ you can see the HTTP request in the GitHub page. You should be able to find all of this on your GH repository settings page. If you do, please share screenshots.

**Comment by graingert** [comment]
CC @wsanchez

**Comment by graingert** [comment]
@humitos @izuzak I recently got Owner access to twisted/twisted and the "resync webhooks" button worked when I clicked it. The PR builds now work.

**Comment by humitos** [comment]
> @humitos @izuzak I recently got Owner access to twisted/twisted and the "resync webhooks" button worked when I clicked it. The PR builds now work.

Awesome! Happy to read this! :tada:

**Comment by glyph** [comment]
I'm still curious as to why this button didn't work any of the six or seven times I clicked it before giving @graingert Owner
