### ISSUE TITLE
pip install not using manylinux2010 wheels

### ISSUE THREAD

**Issue by KristianHolsheimer** [readthedocs/readthedocs.org#7518]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/coax
* Build URL (timed out): https://readthedocs.org/projects/coax/builds/11993796/
* Build URL (successful): https://readthedocs.org/projects/coax/builds/11976575/

## Expected Result

I expected all packages to install manylinux wheels, i.e. either `manylinux1`, `manylinux2010` or `manylinux2014`.

## Actual Result

Build almost finishes but **times out** due to a slow installation of `grpcio==1.32.0`.

`pip` builds `grpcio` from source, which I suspect is because it can't find a `manylinux1` wheel.

Note that `grpcio` does provide `manylinux2010` and `manylinux2014` wheels (see builds [here](https://pypi.org/project/grpcio/1.32.0/#files)).

## Compatibility?

Is this an issue with the linux distro used by readthedocs? Is it incompatible with the `manylinux2010` and `manylinux2014` standards?

**Comment by humitos** [comment]
> Is this an issue with the linux distro used by readthedocs? Is it incompatible with the `manylinux2010` and `manylinux2014` standards?

We use Ubuntu 18.04 LTS to do the builds.

I did a small test and `pip` installs the correct one:

```
docs@1df7062803a6:~$ python3 -m venv venv
docs@1df7062803a6:~$ source venv/bin/activate
(venv) docs@1df7062803a6:~$ pip install grpcio==1.32.0
Collecting grpcio==1.32.0
  Downloading https://files.pythonhosted.org/packages/0d/8c/0a50e644e5ad68a589a0a2bcef2d49b1dc09ae6f970569cad65aad454c43/grpcio-1.32.0-cp38-cp38-manylinux2010_x86_64.whl (3.7MB)
... 
```

However, in your case the package is being installed via `setup.py` not `pip` itself. In that case, it behaves differently:

```
(venv) docs@1df7062803a6:~/coax$ python setup.py install --force
running install
running bdist_egg
running egg_info
...
Installed /home/docs/venv/lib/python3.8/site-packages/coax-0.1.2-py3.8.egg
Processing dependencies for coax==0.1.2
Searching for grpcio>=1.24.3
Reading https://pypi.org/simple/grpcio/
Downloading https://files.pythonhosted.org/packages/0e/5f/eeb402746a65839acdec78b7e757635f5e446138cc1d68589dfa32cba593/grpcio-1.32.0.tar.gz#sha256=01d3046fe980be25796d368f8fc5ff34b7cf5e1444f3789a017a7fe794465639
...
```

You can see that it downloads the `tar.gz` package instead of the `whl`.

I think you can solve that by using the Read the Docs config file (https://docs.readthedocs.io/en/stable/config-file/v2.html#python) and setting `method: pip` to install your package. Let me know if that works.

**Comment by KristianHolsheimer** [comment]
@humitos Thanks so much, that fixed it.. running time is down from about 15 min to under 2 min.

Thanks!
