### ISSUE TITLE
Build exited due to time out

### ISSUE THREAD

**Issue by redBearD-NP** [readthedocs/readthedocs.org#7519]
- Details

https://readthedocs.org/projects/theprofessional/builds/
Command killed due to excessive memory consumption

- Expected Result

Build Successful

- Actual Result

Build Failed

**Comment by humitos** [comment]
I see only one build there that it's still building: https://readthedocs.org/projects/theprofessional/builds/11994819/

**Comment by redBearD-NP** [comment]
It failed again...check now

**Comment by humitos** [comment]
I'm not sure what's happening. The project seems to be super small to consume so much memory/time. Could you disable PDF building and see if the build ends successfully?

**Comment by redBearD-NP** [comment]
How do I disable that?

**Comment by redBearD-NP** [comment]
finally dude !!

**Comment by redBearD-NP** [comment]
https://cdn.discordapp.com/attachments/756092503115038800/760868919660773376/qqeq.PNG
it worked but the picture is not loading

**Comment by redBearD-NP** [comment]
The last picture from every document is not loading

**Comment by humitos** [comment]
I guess that's a problem with your `rst` code where the path to the image is not correct. Do you see the image properly when you build your docs locally?

**Comment by redBearD-NP** [comment]
Yes I see the images properly.

**Comment by redBearD-NP** [comment]
and the code is fine...It works without any issue locally..!!

**Comment by humitos** [comment]
You build shows a warning regarding the static files, maybe it's related

```
WARNING: html_static_path entry '/home/docs/checkouts/readthedocs.org/user_builds/theprofessional/checkouts/latest/_static' does not exist
```

Please, check that you are using the exact build environment (python requirements) locally and in Read the Docs. In particular the Sphinx version.

**Comment by redBearD-NP** [comment]
Yes mate I checked everything it's all the same and has no issue locally

**Comment by humitos** [comment]
It's a problem in your `.rst` code, not on Read the Docs. If it works locally to you, I assume it's because you are using Windows. The extension of some of your images are in uppercase but you are naming them in lowercase in the RST.
