### ISSUE TITLE
RTD fails to build when trying to build wheels that works locally

### ISSUE THREAD

**Issue by marimeireles** [readthedocs/readthedocs.org#7520]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/ipycytoscape
* Build URL (if applicable): https://readthedocs.org/projects/ipycytoscape/builds/11995331/
* Read the Docs username (if applicable): marimeireles

## Expected Result

Docs build.

## Actual Result

Docs don't build, here is a relevant cut of the first error:

```
Building wheels for collected packages: ipycytoscape, pandocfilters, tornado, pyrsistent, livereload
  Building wheel for ipycytoscape (setup.py): started
  Building wheel for ipycytoscape (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/envs/latest/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-s19zpd33/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-s19zpd33/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-33qehhr8
       cwd: /tmp/pip-req-build-s19zpd33/
```

I can build the docs locally normally, no errors.
Any idea of what might be happening here or where to start debugging?

Thanks a lot! :cherry_blossom:

**Comment by marimeireles** [comment]
Sorry for the dups! my github was weird.

**Comment by humitos** [comment]
It seems it's because the package you are trying to build requires a newer `npm` version. I'm seeing this in the build output.

```
wanted: {"node":">=10.13.0"} (current: {"node":"8.10.0","npm":"3.5.2"})
```

There is no an easy way to upgrade the `npm` version on Read the Docs. You could try _an horrible hack_ as first step to confirm that upgrading `npm` will be the solution :smile:. This hack would be to put something in your `setup.py` to manually upgrade `npm` on RTD builders each time your docs are built:

```python
# https://github.com/QuantStack/ipycytoscape/blob/master/setup.py

import os
if os.environ.get('READTHEDOCS', False):
    os.system('# upgrade NPM here in some way')
```

I'm sorry I don't have a better answer here :disappointed:

**Comment by marimeireles** [comment]
Hey @humitos thanks! I'll try to downgrade this :)
I don't need a super new version. I'm just used to write node>13 on my stuff to overcome another bug (from conda). I'll report in case it works. Thanks a lot!

**Comment by marimeireles** [comment]
Sorry I decided to quit using pip, it was giving me too much trouble for too long.
Conda seems to do a very good job, it'd be cooler if we could have Mamba so it's faster :)
I'm gonna close this one. Thanks for the help peeps.

**Comment by humitos** [comment]
> Sorry I decided to quit using pip, it was giving me too much trouble for too long.

Thanks for reporting back!

> Conda seems to do a very good job, it'd be cooler if we could have Mamba so it's faster :)

If you are interested in Mamba, you could subscribe to #7239 to receive notifications.

**Comment by marimeireles** [comment]
@humitos cool! :) Thanks!

**Comment by humitos** [comment]
> There is no an easy way to upgrade the `npm` version on Read the Docs. You could try _an horrible hack_ as first step to confirm that upgrading `npm` will be the solution smile. This hack would be to put something in your `setup.py` to manually upgrade `npm` on RTD builders each time your docs are built:

It seems that I've already documented this at https://github.com/readthedocs/readthedocs-docker-images/issues/107

(I'm getting old and my memory does not work good :older_man: )
