### ISSUE TITLE
RTD fails to build wheels that builds locally

### ISSUE THREAD

**Issue by marimeireles** [readthedocs/readthedocs.org#7521]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/ipycytoscape
* Build URL (if applicable): https://readthedocs.org/projects/ipycytoscape/builds/11995331/
* Read the Docs username (if applicable): marimeireles

## Expected Result

Docs build.

## Actual Result

Docs don't build, here is a relevant cut of the first error:

```
Building wheels for collected packages: ipycytoscape, pandocfilters, tornado, pyrsistent, livereload
  Building wheel for ipycytoscape (setup.py): started
  Building wheel for ipycytoscape (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/docs/checkouts/readthedocs.org/user_builds/ipycytoscape/envs/latest/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-s19zpd33/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-s19zpd33/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-33qehhr8
       cwd: /tmp/pip-req-build-s19zpd33/
```

I can build the docs locally normally, no errors.
Any idea of what might be happening here or where to start debugging?

Thanks a lot! :cherry_blossom:

**Comment by humitos** [comment]
Duplicated of #7520
