### ISSUE TITLE
[FR] Ability to link to externally hosted documentation versions from the version flyout

### ISSUE THREAD

**Issue by prashantmital** [readthedocs/readthedocs.org#7526]
## Details

* Read the Docs project URL: http://pymongo.readthedocs.io/

Older documentation versions for this package can no longer be built. Instead, we relied on the redirects feature to redirect users to https://api.mongodb.com/python/x.y.z/ when `x.y.z < 3.5.1`. These versions used to show up in the version picker flyout after they were 'activated' even if the build failed. In #6971 the behavior changed to only show versions with successful builds in the flyout which means that readers of the documentation must now manually edit the version in the URL to see legacy docs (as the redirects still work).

The need to redirect users to external resources hosting legacy versions of a package's documentation is a legitimate and common use case (see also https://github.com/readthedocs/readthedocs.org/issues/6137#issuecomment-528410245). It will be especially helpful as users transition to using ReadTheDocs for hosting their docs from some other service. Consequently, there should be a way to customize the versions that show up in the version picker flyout to support this use-case. Instead of showing versions with failing builds, maybe you could allow users to specify a mapping of version names to external URLs. 

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by stsewd** [comment]
As explained in https://github.com/readthedocs/readthedocs.org/issues/7732#issuecomment-742606176 a better solution is to allow users to manipulate the version selector itself with data from the api.
