### ISSUE TITLE
Use wildcards to activate versions

### ISSUE THREAD

**Issue by BarrySmith** [readthedocs/readthedocs.org#7528]
It would be a nice feature if one could use wildcards in the versions they activate. For example, activate all the branches whose names end in -docs. 

```
*-docs
```

**Comment by stsewd** [comment]
@BarrySmith that feature already exists :) https://docs.readthedocs.io/en/latest/automation-rules.html

Let me know if that was what you were looking for.

**Comment by BarrySmith** [comment]
Terrific, yes.

It is well hidden, I suggest putting a link to it from the generic Activate a version page. Something like a button [Wildcard versions].

Thanks for your quick response.

**Comment by humitos** [comment]
Thanks @BarrySmith and @stsewd. The issue seems solved. I'm closing.
