### ISSUE TITLE
Account

### ISSUE THREAD

**Issue by Romit-Mohanty-1** [readthedocs/readthedocs.org#7530]
I am trying to login through my school-issued email id. It shows that it is already in use. When i am trying to login through that id using forgot password option then it is showing that no such account exists. Please help.

My school email id is romit@iitk.ac.in

**Comment by humitos** [comment]
Hi @Romit-Mohanty-1! Can you share an screenshot, please? I wasn't able to reproduce your issue using that exact email address.

**Comment by Romit-Mohanty-1** [comment]
![image](https://user-images.githubusercontent.com/72263431/95250089-40e67280-0837-11eb-8b38-54952a9c1a3a.png)
Actually it is showing that this email id is already in use. But when I tried to retrieve the account using the forgot password option, it is showing that no such account exists

**Comment by Romit-Mohanty-1** [comment]
![image](https://user-images.githubusercontent.com/72263431/95250356-9de22880-0837-11eb-8465-d872f60a7f84.png)
sir please see this too!!

**Comment by Romit-Mohanty-1** [comment]
I entered the same email id but still, it is showing an error.

**Comment by Romit-Mohanty-1** [comment]
This is my school email id. But I am unable to login. Sir, please help!!!

**Comment by stsewd** [comment]
@Romit-Mohanty-1 what you are showing is your GitHub account, this repo is for readthedocs.org. I think you should contact the support from GitHub https://support.github.com/contact
