### ISSUE TITLE
More obvious link to project homepage/GitHub

### ISSUE THREAD

**Issue by adigitoleo** [readthedocs/readthedocs.org#7531]
So far I have only used and not published any python docs, but it seems to me that a link to the project homepage or GitHub page (not the docs source) would save the need for a second web search for <projectname> GitHub whenever I decide that I need to browse the project source code (fairly often). PyPi has this on the left sidebar. Sometimes people already include a GitHub link in the docs somewhere, but it would be easier to find if there was a standard place to look for it, like right under the "search docs" field or something.

Or maybe I'm blind and I missed it so far...

**Comment by humitos** [comment]
I'm not sure what you mean but... if you click on the flyout menu (bottom left usually) and go to "Project Home" then you will have the project source used to build those docs on the right.

Also, many projects have the "Edit on GitHub" link on all the pages. So, finding the GitHub project is easy in that context.

You can see this in our docs: https://docs.readthedocs.io/en/stable/

Let me know if that helps.

**Comment by adigitoleo** [comment]
> I'm not sure what you mean but... if you click on the flyout menu (bottom left usually) and go to "Project Home" then you will have the project source used to build those docs on the right.
> 
> Also, many projects have the "Edit on GitHub" link on all the pages. So, finding the GitHub project is easy in that context.
> 
> You can see this in our docs: https://docs.readthedocs.io/en/stable/
> 
> Let me know if that helps.

Hah, I'm definitely blind :joy: For some reason I didn't see the "Project Homepage" button in the flyout menu before. Thanks for pointing it out.
