### ISSUE TITLE
Donation as supporter but no option to disable ads on project.

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#7532]
Hi, I made a $50 donation as a supporter to ReadTheDocs but I don't see a way to disable ads on my personal projects.

Username: Daltz333
Affected Projects: 
- https://frc-docs.readthedocs.io
- https://frc-docs-es.readthedocs.io
- https://frc-docs-fr.readthedocs.io
- https://frc-docs-he.readthedocs.io
- https://frc-docs-pt.readthedocs.io
- https://frc-docs-tr.readthedocs.io
- https://frc-docs-zh_CN.readthedocs.io

Sincerely,
Dalton Smith

**Comment by humitos** [comment]
I think one-time donations don't allow you to disable ads on your projects, that's allowed by becoming a Gold Member:

>  By becoming a Gold member to Read the Docs, you may remove advertising from your projects for all visitors. 

(from https://readthedocs.org/dashboard/<you-project-slug>/advertising/)

> For small businesses or personal projects, we ask for $5 per month to remove ads from a project.

(from https://readthedocs.org/accounts/gold/subscription/)

>  If you consider Read the Docs to be a useful service, and would like to see it continue to grow, consider pitching in to help cover the cost of bringing free and open documentation to everyone. Supporters receive an ad-free experience on Read the Docs. 

(from https://readthedocs.org/sustainability/)

----

In other words,

* Gold Members are able to "remove ads from projects"
* Supporters won't see Ads while browsing any documentation

If this was confusing to you and you are not getting what you expected, we can refund you the money. Please, let me know.

**Comment by Daltz333** [comment]
That would be appreciated, I will likely subscribe as gold instead.

**Comment by humitos** [comment]
Done! Let me know if anything. I suppose it will take some days (up to 7, I think) for the refund to appear in your CC. Otherwise, please contact us back. Thanks for your support!
