### ISSUE TITLE
Docs with conda options not being build because: Invalid "conda.file": file not found

### ISSUE THREAD

**Issue by marimeireles** [readthedocs/readthedocs.org#7535]
## Details

* Build URL (if applicable): https://readthedocs.org/projects/ipycytoscape/builds/12028391/
* Read the Docs username (if applicable): marimeireles

## Expected Result

Docs build using conda to create an environment.

## Actual Result

Docs don't build and I get the following:

```
Problem in your project's configuration. Invalid "conda.file": file not found
```

I tried to follow the docs and projects that use conda to build their envs and there is no difference between my files and theirs. See:
readthedocs.yaml: https://github.com/QuantStack/ipycytoscape/blob/master/readthedocs.yml
doc envs: https://github.com/QuantStack/ipycytoscape/blob/master/docs/environment.yml

I'm trying it as an alternative to `pip` since it's causing me a few problems https://github.com/readthedocs/readthedocs.org/issues/7520.

Any idea of what might be wrong?
Thanks a lot!

**Comment by stsewd** [comment]
Hi, you are missing the version of the config file, see https://docs.readthedocs.io/en/stable/config-file/v2.html#conda
