### ISSUE TITLE
Setting up latest mkdocs in RTD configuration does not result with the actual latest mkdocs version.

### ISSUE THREAD

**Issue by GraionDilach** [readthedocs/readthedocs.org#7539]
## Details

https://github.com/OpenRA/OpenRA/pull/18681 is a WIP update in the @OpenRA project documentation. During the PR review, it was noticed that the generated document featured https://github.com/mkdocs/mkdocs/issues/2027. This bug is fixed in mkdocs version 1.1.1 - https://github.com/mkdocs/mkdocs/commit/63b3eb5a1fbfdfc0e28ee54e5dcc3b714487b1b0 - already but RTD does not deploy the bugfix.

I don't know Python but I suspect 
https://github.com/readthedocs/readthedocs.org/blob/master/readthedocs/doc_builder/python_environments.py#L373 caps the  version to 1.1 which became outdated by now (blame claims it's a two year old line) and prevents RTD to deploy versions above 1.1.

## Expected Result

*Setting mkdocs to use the latest release deploys on mkdocs's latest release.*

## Actual Result

*Setting mkdocs to use the latest release deploys on mkdocs version 1.1 instead of 1.1.2.*

**Comment by GraionDilach** [comment]
Pinging @pchote and @Mailaender for interest.

**Comment by stsewd** [comment]
You can install any version of mkdocs you want, see https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

**Comment by GraionDilach** [comment]
Yes, I understand this part. Manually pinning the latest version shouldn't be the solution to circumvent an outdated default value though.

The feature flag added in https://github.com/readthedocs/readthedocs.org/pull/5505 seems to cause the problem here - it was added to hold back then-existing documentation instances of mkdocs to 0.17.0. However the way it was set up, it kept the latest version to 1.0 (1.1 was in-dev during that time). 1.1 was released, and received bugfix releases since as well which regressed RTD at mkdocs documentations which does not pin the required versions to latest on their own.

**Comment by humitos** [comment]
> However the way it was set up, it kept the latest version to 1.0 (1.1 was in-dev during that time).

We need to pin our dependencies in some way to try to make them deterministic. At some point those default will be outdated and we need to come up with a plan to update the default values. We have the same problem with Sphinx right now and it's not easy to update the versions and keep every user happy with the new default.

**Comment by stsewd** [comment]
@GraionDilach we recommend pinning to a specific version so your builds don't break if we update the default version, also if gives you a way to have the exact build locally.

**Comment by Mailaender** [comment]
An example of how a `requirements.txt` should actually look like would also be helpful. At the moment information is scattered around and after reading it all, I still don't understand how to update mkdocs per project.

**Comment by stsewd** [comment]
your requirements.txt file should be like

```
mkdocs==1.1.2
```

**Comment by Mailaender** [comment]
Thanks. I tried it. https://github.com/OpenHV/docs/commit/06861676e049676e73158a5400001b8259eab298 but it regresses in terms of the TOC and also doesn't fix the syntax highlighting as expected.

**Comment by stsewd** [comment]
Please report those problems to the mkdocs repo

**Comment by Mailaender** [comment]
Setting `requirements.txt` to
```
mkdocs==1.1.1
```
or
```
mkdocs==1.1
```
also didn't help. Only deleting `requirements.txt` reverted things back to normal. So I think it must be part of your dependency system where the breakage occurs.

**Comment by stsewd** [comment]
@Mailaender please link to your project and also see if you can replicate locally with the same version

**Comment by Mailaender** [comment]
See https://github.com/OpenHV/docs

**Comment by Zylann** [comment]
I also noticed a difference in my table of contents compared to the version of mkdocs I tested with locally.
When I tested locally, the theme shipped with mkdocs had working collapsible sections, while the one I just built with RTD shows everything at once.

So I decided to change the version in my `requirements.txt`:
```
mkdocs>=1.1.2
```

But strangely, in the build log, I can see this occurring:
```
python -m pip install --upgrade --no-cache-dir [...] mkdocs<1.1
```
And then this next:
```
python -m pip install --exists-action=w --no-cache-dir -r addons/zylann.hterrain/doc/requirements.txt
```

Which results in two installs of `mkdocs`?
The build: https://readthedocs.org/projects/hterrain-plugin/builds/12444767/

I'm trying to understand why my local install of `mkdocs` has great theme but not the one RTD built :/

**Comment by stsewd** [comment]
> Update: somehow the theme now looks the same. I didn't change anything shrug

It may have been a cached page. Also, we install a default version of mkdocs, but you can install any version you require, that's why is installed twice, the second installation is the one being used.

**Comment by Zylann** [comment]
So apparently the problem with mkdocs would actually come from RTD: https://github.com/mkdocs/mkdocs/issues/2145#issuecomment-735342512

`docs_dir` is being overriden somehow, because it doesn't properly defaults to its normal default value.
I had to explicitely set `docs_dir: docs` in `mkdocs.yml` (which is what it normally defaults to) to make it work.

**Comment by stsewd** [comment]
We set that value here if isn't present.

https://github.com/readthedocs/readthedocs.org/blob/2dc9706c4fe7fa6d4410ed0e5aedca8d4796fe0f/readthedocs/doc_builder/backends/mkdocs.py#L148-L148

I think maybe old versions of mkdocs didn't a default value? Still, if so the docs wouldn't build locally, so I think we shouldn't edit that setting. Another possibility is that this was added for users that didn't have a mkdocs.yaml file (think this may be the case actually) https://github.com/readthedocs/readthedocs.org/issues/2483.

**Comment by stsewd** [comment]
This fix should be live by next tuesday.

**Comment by stsewd** [comment]
@Zylann the fix is live now, if you want to give it a try :)

**Comment by Zylann** [comment]
I removed my workaround and it seems to work this time. Thank you!
