### ISSUE TITLE
Download links for subproject translation are wrong

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#7543]
Given the following scenario, the links to downloads are wrong:

* Project A is set up as a superproject
* Project A has a custom domain `docs.example.com` (I'm not sure if this is necessary for reproduction)
* Project B is set up as a subproject of project A
* Project C is set up as the russian translation of project B

The download link for project B PDF should be: `https://docs.example.com/_/downloads/B/en/pdf/`
The download link for project C PDF should be: `https://docs.example.com/_/downloads/B/ru/pdf/`

Instead, the link for project C is wrong:

`https://docs.example.com/_/downloads/ru/pdf/`

**Comment by stsewd** [comment]
I have fixed this already https://github.com/readthedocs/readthedocs.org/pull/7541

**Comment by stsewd** [comment]
Is the same case you reported in .com

**Comment by agjohnson** [comment]
So fast! :wink: I'm going to target the fix for next release

**Comment by stsewd** [comment]
Fixed in artlogic-artlogicdocs.readthedocs-hosted.com
