### ISSUE TITLE
how to move the readthedocs interface in the right bottom corner to the left bottom corner

### ISSUE THREAD

**Issue by JaehyunShim** [readthedocs/readthedocs.org#7549]
## Details

* Read the Docs project URL: https://github.com/JaehyunShim/ros2_tutorial
* Build URL (if applicable): https://ros2-tutorial.readthedocs.io/en/latest/?
* Read the Docs username (if applicable): JaehyunShim

## Expected Result

Move the interface to the left bottom corner like the following official page of readthedocs
https://docs.readthedocs.io/en/latest/?badge=latest

## Actual Result

The default setting is that it is placed in the right bottom corner.
https://ros2-tutorial.readthedocs.io/en/latest/?

Also, how to write a name on it. The default is that there is nothing written on it, but 'Read the Docs' is written if you see the one on the official page.

Thanks in advance,
Jaehyun

**Comment by humitos** [comment]
Hi @JaehyunShim! Read the Docs documentation is using Sphinx and your project is using MkDocs. Due to that difference the integration with Read the Docs it's a slightly different. Unfortunately, there is no easy way to make them look exactly the same.

**Comment by JaehyunShim** [comment]
@humitos 

Thank you for your reply. Where should I request for modification on the feature then? Of course, it can vary depending on whether Sphinx / MkDocs. However, if the one from Sphinx is the more intuitive and new feature, I would like to request updates on the MkDocs doc project. I believe moving to the left bottom side and put the name of the doc in it wouldn't be that difficult. 

Jaehyun

**Comment by JaehyunShim** [comment]
@humitos 

I have another question. The domain of my webpage created using ReadTheDocs is as follows
(https://ros2-tutorial.readthedocs.io/en/latest/?badge=latest)

However, what if the name of the project 'ros2_tutorial' is already taken by another user. I think there must be a user name or something with the project name in the domain so that you can prevent the potential conflicts between projects of the same name by different users. I think this is even more important than the question I asked above. 

Jaehyun.

**Comment by humitos** [comment]
> Thank you for your reply. Where should I request for modification on the feature then?

I suppose the mkdocs project is the right place: https://github.com/mkdocs/mkdocs

> However, what if the name of the project 'ros2_tutorial' is already taken by another user

We have a shared namespace. If someone's else already registered that project you have to pick a different slug; or claim for it if the project is abandoned. See https://docs.readthedocs.io/en/stable/abandoned-projects.html

I'm closing this issue. Feel free to re-open if you consider.

**Comment by JaehyunShim** [comment]
@humitos 

Thank you for adding the link. I opened a new thread there and asked the questions.

Jaehyun
