### ISSUE TITLE
Sphinx error: master file /home/docs/checkouts/readthedocs.org/user_builds/swig1/checkouts/latest/SphinxDocs/contents.rst not found

### ISSUE THREAD

**Issue by manitejav** [readthedocs/readthedocs.org#7550]
## Details

* https://swig1.readthedocs.io/en/latest/index.html
* https://readthedocs.org/projects/swig1/builds/12054920/
* manitejav
## Expected Result
Succesful build

conf.py
master_doc = 'index'

Updated requirements.txt to use the versions used in the local versions.

Tried setting configuration path in RTD admin panel.

None of them succeded.

## Actual Result

Build fails with 
Sphinx error:
master file /home/docs/checkouts/readthedocs.org/user_builds/swig1/checkouts/latest/SphinxDocs/contents.rst not found

**Comment by stsewd** [comment]
Hi, looks like the path to your config file is wrong https://github.com/manitejav/swig/blob/9d9a61c972e9d7ba442c875e95d12cb41d8ecff9/.readthedocs.yml#L10

it should be https://github.com/manitejav/swig/blob/master/SphinxDocs/source/conf.py
