### ISSUE TITLE
Support Python 3.9

### ISSUE THREAD

**Issue by cjolowicz** [readthedocs/readthedocs.org#7554]
Opening this issue to track when Python 3.9 support becomes available for documentation builds on Read the Docs. Python 3.9.0 was released on October 5, 2020.

For reference, the issue for the previous major Python release (3.8) was #6324. Support for Python 3.8 was added in #6654.

Thank you 🙇‍♂️ 

## Details

* Read the Docs project URL: https://readthedocs.org/projects/cookiecutter-hypermodern-python-instance
* Build URL (if applicable): https://readthedocs.org/projects/cookiecutter-hypermodern-python-instance/builds/12066088/
* Read the Docs username (if applicable): cjolowicz

## Expected Result

Documentation builds use Python 3.9 when this version is specified in `.readthedocs.yml`:

```yaml
python:
  version: 3.9
```

## Actual Result

The build fails with the following error message:

```
Error: Problem in your project's configuration. Invalid "python.version": expected one of (2, 2.7, 3, 3.5, 3.6, 3.7, 3.8, pypy3.5), got 3.9
```

**Comment by graingert** [comment]
it would be good to support 3.10dev at the same time

**Comment by humitos** [comment]
Python 3.9 should be included in our docker images. We have an issue opened for that at https://github.com/readthedocs/readthedocs-docker-images/issues/140

**Comment by ThiefMaster** [comment]
certainly not stale ;)

**Comment by graingert** [comment]
Bump

**Comment by staticdev** [comment]
@humitos I would like to add that all my projects are already building the docs with Python 3.9 and I didn't have any problem so far.

**Comment by ThiefMaster** [comment]
@staticdev So RTD now finally supports building with Python 3.9? Or are you using any workarounds to use 3.9?

**Comment by staticdev** [comment]
@ThiefMaster I didn't use any workaround, it just worked. Did you experience any problem?

**Comment by ThiefMaster** [comment]
I haven't tried again this year, but the last time I checked there was no Python 3.9 support on RTD, and when I had a quick look at your repos they still seem to use 3.8 in the RTD config file.

**Comment by oddlama** [comment]
Is there any update on the issue? Python 3.9 is now almost 5 months old.

**Comment by ThiefMaster** [comment]
https://github.com/readthedocs/readthedocs-docker-images/pull/159#issuecomment-785048185

This worked for me.

**Comment by humitos** [comment]
@oddlama as @ThiefMaster mentioned, using 

```yaml
build:
  image: testing
```

in your `.readthedocs.yaml` file is the way to go for now. Please, report any problem that you may find here as we are still testing this Docker image and Python version.

**Comment by oddlama** [comment]
Thanks! No problems thus far, worked perfectly without other adjustments.

**Comment by astrojuanlu** [comment]
Can this be closed then? (See also https://github.com/kiwitcms/Kiwi/blob/master/readthedocs.yml)
