### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement

### ISSUE THREAD

**Issue by ericorain** [readthedocs/readthedocs.org#7555]
## Details

* Read the Docs project URL:
https://readthedocs.org/projects/netscud/

* Build URL (if applicable):
https://readthedocs.org/projects/netscud/builds/12077251/

* Read the Docs username (if applicable):

## Expected Result

Should find the python module.

## Actual Result

I got this error message:

```
/home/docs/checkouts/readthedocs.org/user_builds/netscud/envs/latest/bin/python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
ERROR: Could not find a version that satisfies the requirement netscud==1.0.0 (from -r docs/requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for netscud==1.0.0 (from -r docs/requirements.txt (line 1))
```

docs/requirements.txt
```
netscud==1.0.0
```

If I do not use a requirement file then I have this error message:

```
WARNING: autodoc: failed to import module 'netscud'; the following exception was raised:
No module named 'netscud'
```

Some help would be appreciated since I do not know what is wrong.

**Comment by humitos** [comment]
It seems that pip is not finding the wheel for some reason. This is not a problem with Read the Docs, but with pip and the package that you are trying to install.

You can reproduce this issue outside Read the Docs, just by trying to install that package. It seems that the package requires Python +3.8 and you are using 3.7 on Read the Docs.

You can use 3.8 on Read the Docs via the config file https://docs.readthedocs.io/en/stable/config-file/v2.html#python

I'm closing this issue, but feel free to re-open if you consider. Thanks!

**Comment by ericorain** [comment]
I created a file .readthedocs.yml at the root of the project with that data:

################################
version: 2

sphinx:
  configuration: docs/conf.py

formats: []

python:
  version: 3.8
  install:
    - requirements: docs/requirements.txt
################################

Now it is working. Thanks.
