### ISSUE TITLE
<script> tag in code blocks not escaped in lists

### ISSUE THREAD

**Issue by nikita-fuchs** [readthedocs/readthedocs.org#7556]
## Details

* Read the Docs project URL: https://aeternity-js-sdk.readthedocs.io/en/latest/bugtest/

## Expected Result

On localhost, when I run `mkdocs serve`, things look fine: 
![image](https://user-images.githubusercontent.com/11761828/95745308-2546f600-0c95-11eb-8da6-07366a1f3394.png)

## Actual Result

When things get built on readthedocs, the same looks like:
![image](https://user-images.githubusercontent.com/11761828/95745446-63441a00-0c95-11eb-93d1-d4580bc1e90d.png)
(as linked above)

**Comment by stsewd** [comment]
@nikita-fuchs hi, can you please check you are using the same mkdocs version locally? 

Your builds are using `mkdocs-1.0.4` https://readthedocs.org/projects/aeternity-js-sdk/builds/12081766/, if you need another version see https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

**Comment by nikita-fuchs** [comment]
Thanks for the quick help @stsewd ! I'm on `v1.1.2` indeed, but I'm afraid specifying anything manually requires some knowledge of python, which I have 0 of. As per the link, I created a `requirements.txt`, but what do I put there ? Are there any other places I have to amend some more information?

**Comment by nikita-fuchs** [comment]
Thank you very much, could you add that to the docs for the rest of the world to know? I would create a PR, but you'd know better where to put it - maybe right below https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html#specifying-a-requirements-file ?
