### ISSUE TITLE
Build failed with conda: not found.

### ISSUE THREAD

**Issue by DeepanshS** [readthedocs/readthedocs.org#7560]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/mrsimulator/
* Build URL (if applicable): https://readthedocs.org/projects/mrsimulator/builds/12093927/
* Read the Docs username (if applicable): DeepanshS

## Expected Result

Build success using conda env

## Actual Result

/bin/sh: 1: conda: not found

**Comment by DeepanshS** [comment]
Thank you for looking into the problem.

**Comment by humitos** [comment]
@DeepanshS we just deployed a fix. I'm closing this issue, but please confirm that's solved for you.

**Comment by DeepanshS** [comment]
@humitos  The issue is solved for me. Thank you.
