### ISSUE TITLE
Set no shallow clone for ddtrace

### ISSUE THREAD

**Issue by Kyle-Verhoog** [readthedocs/readthedocs.org#7561]
As described in #5031, can we disable shallow cloning for ddtrace since we use [`reno`](https://docs.openstack.org/reno/latest/) which is causing our docs build to break.

Thanks! 🙂

**Comment by humitos** [comment]
Done! I re-triggered a build for your project https://readthedocs.org/projects/ddtrace/builds/12102395/ and it seems it worked. I'm closing this issue.

> Next time, please contact us via email for this kind of issues (not a bug in our application) :smile:
