### ISSUE TITLE
missing tags in versions list

### ISSUE THREAD

**Issue by Borda** [readthedocs/readthedocs.org#7562]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pytorch-lightning
* Build URL (if applicable):
* Read the Docs username (if applicable): Borda

## Expected Result

Build one of the previous releases...

## Actual Result

In Github and everywhere we have 0.9.0 release but I can't build it as it missing from listed versions
on the other hand, there is a strange 0.9._a which is not a branch nor tag...

**Comment by stsewd** [comment]
0.9.0_a points to the 0.9.0 tag https://github.com/PyTorchLightning/pytorch-lightning/tree/0.9.0

https://pytorch-lightning.readthedocs.io/en/0.9.0_a/

Not sure how the  `_a` suffix got added (maybe you had a version with that tag/branch and delete it? or maybe just a race condition).

No get the "correct" name, you need to deactivate that version, after that triggering a build in any version will refresh your versions.

**Comment by Borda** [comment]
@stsewd I have done as you said, deactivated the `0.9.0_a` trigger `latest` build which passed, but `0.9.0` is missing and the `0.9.0_a` is still there...

**Comment by stsewd** [comment]
ah, that didn't work because the tag has the same commit already. I have changed the slug manually. Just for curiosity, did you have a branch named `0.9.0` at some point? or did you do a re-tag?

**Comment by Borda** [comment]
> Just for curiosity, did you have a branch named `0.9.0` at some point? or did you do a re-tag?

it could be, do not remember...

**Comment by marcelzwiers** [comment]
I did, I had a 3.6.1 branch and than I released it with a 3.6.1 tag. Now it is shown with a `_a` suffix...

https://bidscoin.readthedocs.io/en/3.6.1_a/
