### ISSUE TITLE
Dependencies problem during installation

### ISSUE THREAD

**Issue by filipito** [readthedocs/readthedocs.org#7567]
Hello, opening this issue as I had problems with installation of Read the Docs I did according to [this page](https://docs.readthedocs.io/en/stable/development/install.html).

After running the following command 
`pip install -r requirements.txt`
an error with dependencies of serde_json occured. It was trying to clone a non-existing repository.
Probably caused by strict demand of orjson version 2.0.7.

After installing orjson version 3.4.0 everyting works.

I suggest not to demand orjson version 2.0.7.

## Details

* Read the Docs project URL: No project yet
* Build URL (if applicable):
* Read the Docs username : filipito

**Comment by stsewd** [comment]
What version of python are you using? We currently only support 3.6

**Comment by filipito** [comment]
I am using Python 3.8.3. That could be the problem.
However, It seems to work fine now.

čt 15. 10. 2020 v 19:05 odesílatel Santos Gallegos <notifications@github.com>
napsal:

**Comment by stsewd** [comment]
We are working into support 3.8 https://github.com/readthedocs/readthedocs.org/pull/7421

**Comment by humitos** [comment]
Hi @filipito! I recommend you to follow this guide instead, https://docs.readthedocs.io/en/stable/development/standards.html, which is what the Core Team uses in a daily basis and where we can provide you help with.

The guide that you were following may be outdated and we don't offer support on that one.

**Comment by filipito** [comment]
Hello @humitos , thank you for the link. I will follow it next time.
