### ISSUE TITLE
Import project with `-` as ending char in slug

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#7573]
When importing a project, if you change the slug to `somehing-ending-in-` the form will validate and the project will be imported.

However, when you hit `something-ending-in-.readthedocs.io` it won't work because of a SSL certificate issue. Besides, the pull request builder does not work as well.

In other words, slugs ending in `-` are not supported and our form should raise a validation error when that happens.

**Comment by stsewd** [comment]
Looks like we also allow slugs that start with `-`, don't think that's a valid subdomain either.
