### ISSUE TITLE
Documentation not showing up online

### ISSUE THREAD

**Issue by ssolari** [readthedocs/readthedocs.org#7575]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/simpleh5/

I have /docs in the public github and a successful build on readthedocs and while the documentation is not perfect yet, there is a valid hierarchy (at least I can download a pdf from the project that has it), so it seems the documentation is actually building.   From the bottom left link at https://simpleh5.readthedocs.io/en/latest/#  I can even download 'html' and view the html page, so it seems there is an issue with linking the page to the correct html?

I suspect there is an issue with switching the latest branch from master to main?

I switched the latest branch to main, but the the link to github at https://simpleh5.readthedocs.io/en/latest/
Still shows master? https://github.com/ssolari/simpleh5/blob/master/index.rst  (also this link doesn't work)

I don't know if that is the issue or not.

## Expected Result

Expect some sort of documentation to show at https://simpleh5.readthedocs.io/en/latest/

## Actual Result

Getting the parked page.

**Comment by humitos** [comment]
> Expect some sort of documentation to show at [simpleh5.readthedocs.io/en/latest](https://simpleh5.readthedocs.io/en/latest/)

I'm seeing some docs there

![Screenshot_2020-10-19_19-17-43](https://user-images.githubusercontent.com/244656/96489508-d3c3db80-123f-11eb-86f0-6555cfe29835.png)

and it seems that's generated from https://github.com/ssolari/simpleh5/blob/main/docs/index.rst and looks correct. Isn't it? If not, what are you expecting to see in that documentation page?

If you build your documentation locally, what you get?

**Comment by ssolari** [comment]
I did some hard browser refreshes and I see what you see.    Maybe there was a caching issue.     My issue is fixed, going to close this.   Thank you!
