### ISSUE TITLE
Build fails due to extension not found

### ISSUE THREAD

**Issue by stefanodavid** [readthedocs/readthedocs.org#7584]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/opendatahub/
* Build URL (if applicable): https://readthedocs.org/api/v2/build/12141315.txt
* Read the Docs username (if applicable):

## Expected Result

A successful build of the docs.

## Actual Result

The build (and a lot of the previous builds) end with

`ERROR: Could not find a version that satisfies the requirement sphinx-tooglebutton (from -r requirements.txt (line 2)) (from versions: none)
ERROR: No matching distribution found for sphinx-tooglebutton (from -r requirements.txt (line 2))`

I tried to remove requirements.txt, add a readthedocs.yaml following RTD's documentation and hints in similar issues here (e.g., #7555, #6832) but with no result. Apparently, the extension is installed with pip and not with pip3? Can this be the reason? 

I also checked the extension's repo if there were some hints about content of the requirements.txt files (docs of this extension are also hosted on RTD), but found nothing.

Thanks for all hints!

**Comment by Daltz333** [comment]
You need to set the location of your requirements.txt in your yaml readthedocs configuration. Additionally your yaml configuration is invalid.

**Comment by stefanodavid** [comment]
Thanks to both of you for your time and answers. The problem was not even with the yaml file, but a (@#$%&) typo in the name of the extension... :facepalm:
