### ISSUE TITLE
Help needed with TLS

### ISSUE THREAD

**Issue by rmk135** [readthedocs/readthedocs.org#7585]
## Details

* Read the Docs project URL: https://python-dependency-injector.ets-labs.org/
* Build URL (if applicable):
* Read the Docs username (if applicable): rmk

## Expected Result

Hello ReadTheDocs Team,

I'm looking for a help to debug a recent TLS-related issue. I have an issue opened in my project https://github.com/ets-labs/python-dependency-injector/issues/304 to serve the docs over ``https://``. I found this idea great and:

1) Enabled this checkbox in settings:
<img width="1013" alt="Screenshot 2020-10-20 at 11 23 27" src="https://user-images.githubusercontent.com/1742049/96608360-4a57ec00-12c7-11eb-85be-c5a66c7d6944.png">
2) Updated all links in the documentation and examples to explicitly lead to ``https://``.

Actual result: docs are served over ``https://`` but there are some issue though.

## Actual Result

Issue 1: user is still reporting a problem:
<img width="1046" alt="Screenshot 2020-10-20 at 11 30 08" src="https://user-images.githubusercontent.com/1742049/96608713-b63a5480-12c7-11eb-8a7b-b2a116561864.png">
<img width="1033" alt="Screenshot 2020-10-20 at 11 30 15" src="https://user-images.githubusercontent.com/1742049/96608721-b89cae80-12c7-11eb-812d-aec1b4b3a927.png">

Issue 2: I've scanned https://python-dependency-injector.ets-labs.org/ with https://www.ssllabs.com/ and found this:
<img width="1020" alt="Screenshot 2020-10-20 at 11 32 07" src="https://user-images.githubusercontent.com/1742049/96608979-fe597700-12c7-11eb-9346-74b468c66772.png">
I don't know how critical is this and if that's a root of cause of my issue.
Is it something expected?

Issue 3: in addition after making a test I found that my docs has grade B cause you have TLS 1.0 and TLS 1.1 enabled. Can you disable that?
<img width="1211" alt="Screenshot 2020-10-20 at 11 33 20" src="https://user-images.githubusercontent.com/1742049/96609447-8770ae00-12c8-11eb-80a8-11ea357365d7.png">

**Comment by stsewd** [comment]
https://python-dependency-injector.ets-labs.org/ loads fine to me. If you are using cloudflare, see https://docs.readthedocs.io/en/stable/custom_domains.html#notes-for-cloudflare-dns-users (just disable the orange cloud for that CNAME).

> Issue 3: in addition after making a test I found that my docs has grade B cause you have TLS 1.0 and TLS 1.1 enabled. Can you disable that?

I think we did some work about that, maybe @davidfischer can answer that better.

**Comment by rmk135** [comment]
Hey @stsewd ,

Thanks for a quick response. I don't use Cloudflare explicitly. Since I have a custom domain I assume cloudflare is used indirectly to provision a certificate for my domain. I use GoDaddy and that's how my CNAMEs look like:

<img width="1017" alt="Screenshot 2020-10-20 at 11 54 08" src="https://user-images.githubusercontent.com/1742049/96612086-59409d80-12cb-11eb-9c1d-9f8489277b8a.png">

**Comment by humitos** [comment]
TLS looks OK to me in your domain https://python-dependency-injector.ets-labs.org/ --it's being served as a secure site.

**Comment by stsewd** [comment]
Everything looks good from here, and getting all A's here https://www.ssllabs.com/ssltest/analyze.html?d=python%2ddependency%2dinjector.ets%2dlabs.org&latest. Let us know if this is still a problem or if we are missing something to replicate this.
