### ISSUE TITLE
"Your project, testfixtures, needs to be reconfigured in order to continue building automatically after January 31st, 2019"

### ISSUE THREAD

**Issue by cjw296** [readthedocs/readthedocs.org#7588]
## Details

This project is very old in RTD terms, and I think something needs a tweak:
https://readthedocs.org/projects/testfixtures/

I get a "Your project, testfixtures, needs to be reconfigured in order to continue building automatically after January 31st, 2019" message whenever I'm logged in to RTD, but testfixtures docs have been building fine for the last 2 years...

What can I do to remove that warning?

(obviously this is pretty low priority, but since I'm logging RTD issues today...)

**Comment by stsewd** [comment]
@cjw296 you need to click on the link of the message in order to make it go away. Our new templates make this more obvious.
