### ISSUE TITLE
move "RTD box" to left nav for non-default themes.

### ISSUE THREAD

**Issue by cjw296** [readthedocs/readthedocs.org#7589]
## Details

I was confused when I started using https://github.com/pradyunsg/furo as I couldn't see the version-picker-links-to-builds-etc box when using that theme, to the point where I put in a feature request: https://github.com/pradyunsg/furo/issues/25

As @pradyunsg pointed out, I see it on the right now, but that's not where I'd expect it to be, and for some themes it ends up looking pretty ugly:

https://pip.pypa.io/en/stable/

## Expected Result

The box to be in the left nav, roughly where it would be for the default theme

## Actual Result

It's over on the right, where I don't expect it, and where it looks ugly on themes which have a left nav, which I would hazard a guess to be all of them.

**Comment by humitos** [comment]
I'm not sure _where_ we are adding this, but I think this should be configurable.

**Comment by pradyunsg** [comment]
https://github.com/readthedocs/readthedocs.org/blob/a81d82ed736b611491050f39649bd668ef212c0f/readthedocs/core/static-src/core/js/doc-embed/footer.js#L79

The relevant point in code.

**Comment by pradyunsg** [comment]
FWIW, Furo now does place this correctly in the sidebar, although it needed reading of sponsorship.js here, and a bunch more investigation.

Here is how stuff looks with the development documentation for pip (big file, screenshot):

![Screenshot 2020-11-14 at 4 21 30 AM](https://user-images.githubusercontent.com/3275593/99128499-f673c500-2630-11eb-974b-4063ea49e904.png)

The tracking issue for the mismatched colors is https://github.com/readthedocs/ethical-ad-client/issues/37

**Comment by pradyunsg** [comment]
Oh, and here's what was the tracking issue for this on Furo's end: https://github.com/pradyunsg/furo/issues/23

**Comment by pradyunsg** [comment]
Oh, unless we're talking about the hover box thingie -- in which case, WHOOPS, coz I was talking about the ads. :)

**Comment by cjw296** [comment]
Yep, hover box thingy, which I think your screenshot still shows off on the right, whereas the RTD theme has it on the left, which I think it belongs...

**Comment by pradyunsg** [comment]
@cjw296 Ah, I assume you mean the sidebar.

That's non-trivial for the embedding JS here (which applies to *all* of ReadTheDocs) to implement while still respecting any designs that themes could have (eg: only right sidebars like Sphinx's own documentation). I expect Furo to get the relevant styling for RTD settled down at some point, but that's not today. :)

**Comment by cjw296** [comment]
This is still an issue.

**Comment by stsewd** [comment]
As mentioned, we do this because there is no guarantee that all themes will have a sidebar that fits the version chooser. We are planning in make it more easy to integrate, so theme authors can choose where and how to place it. See https://github.com/readthedocs/readthedocs.org/issues/7748
