### ISSUE TITLE
Please allow Tor users to access documentation

### ISSUE THREAD

**Issue by lukejohnsonrp** [readthedocs/readthedocs.org#7598]
Your Cloudflare configuration is blocking Tor users and the captcha is broken in a way that makes accessing the documentation projects impossible. 

Please whitelist Tor users, you can follow this short guide https://github.com/allow-tor/on-cloudflare that briefly explains how to do it inside a Cloudflare account. 

I have also made a short video that shows how accessing https://electrum.readthedocs.io looks like: https://oshi.at/MypUof/Screencast_2020-10-23_064254.mp4

**Comment by humitos** [comment]
Hi @lukejohnsonrp! I'm not able to reproduce this issue using Tor `10.0.2 (based on Mozilla Firefox 78.4.0esr) (64-bit)`. I can access https://electrum.readthedocs.io/en/latest/ with that Tor version without problem.

Are there some replication steps that I am missing here?

BTW, the video you shared seems to be broken for some reason and does not load.

**Comment by lukejohnsonrp** [comment]
I am sorry that the link didn't work for you, but it loads fine on my browsers. I have reuploaded it to a different sharing platform: https://gofile.io/d/KUfGSO Let me know if there are still issues.

I don't use `Tor Browser` and to reproduce what I did on video you should have a `Tor` standalone client running on your system. Usually on any Linux distribution, the package is called `tor` (Debian/Ubuntu: `apt install tor`), once installed it opens a SOCKS port `9050` by default that can be used on any browser which will provide same networking behaviour as Tor browser - your external IP addresses will be Tor exists.

The software stack shown on the video is: `Chromium 83.0.4103.116` using a socks 127.0.0.1:9050 provided by `Tor 0.4.4.5` on `Debian GNU/Linux 10.6`, those are in fact just the latest software versions on Debian main repository.

However, I have downloaded `Tor Browser 10.0.2` and can confirm that https://electrum.readthedocs.io/en/latest/ is accessible without a problem from that specific browser. It looks like Cloudflare browser detection mechanism fingerprints Tor Browser to provide better experience to Tor Browser users. 
Anyway, please note that not all Tor users are Tor Browser users, "using Tor" doesn't necessarily mean to use `Tor Browser`.

The difference between using `Tor Browser` and `Tor` standalone approach is only in browser settings, because the IP/networking behaviour will be exactly same and if the host is determining risk for their DDoS protection only based on User-Agent then it's not a correct DDoS protection.

For cases like this one, Cloudflare has a firewall rule for country based match, which include `A1` / `Tor` as a country name, used to whitelist Tor exists, so that non-`Tor Browser` users who use Tor can access the sites.

There are also other (popular) use cases that can reproduce this behaviour:

- Using Whonix distro with Whonix Gateway which wraps all the OS network stack into Tor, which results all the software on the OS to appear using Tor.

- Using a VPN that exists into Tor, that also results all traffic to go via Tor without a need of using Tor Browser.

**Comment by davidfischer** [comment]
I was able to check out the screencast without issue. The captcha checks look pretty annoying and once you got through them it looked like the static files (CSS, JS, etc.) didn't load correctly. I'm guessing there was a separate Cloudflare challenge for the static files or something like that. That's odd because most of those files should be coming from the same domain so I'd expect a single challenge to suffice.

I'll dig in a little bit here but in general as I outlined in #4509 we have no problem with folks browsing RTD through Tor. When we rolled out the CDN setup, we actually tested Tor (using Tor Browser) to make sure Tor users could continue to use RTD. What we have to protect ourselves from is poorly behaved bots hitting us through Tor. We absolutely get crawled or get unwanted security scans frequently by bots crawling RTD to the tune of tens of requests per second and I want to challenge those people. As a result, I don't want to have a blanket allow rule for Tor unless other challenge rules take precedence. With that said, I'll review our challenge rules now.

@lukejohnsonrp, would you mind sharing a few other things:

- Do you have non-standard cookie settings in the browser you're using? I'm not precisely sure (I'll test this) but I believe if you've set all cookies to reject, you're going to get more challenges especially if you're using Tor because there will be no memory of passing the previous challenge.
- I noticed you were using some ad blocker plugins. With their standard settings, those should be fine. Are you doing anything non-standard with respect to blocking requests back to Read the Docs?
- Are you using any other browser plugins there to block requests for certain types of content? Opening the developer console would tell why those requests for static files were blocked.

**Comment by davidfischer** [comment]
I reviewed our settings and we don't have any Tor specific challenge settings or anything like that. One area that Cloudflare offers some improvements is in [Onion Routing](https://support.cloudflare.com/hc/en-us/articles/203306930-Understanding-Cloudflare-Tor-support-and-Onion-Routing) which possibly Tor Browser uses but your setup doesn't. We have this option enabled.

I know that Tor setups can vary quite a bit so maybe with a few more details we can get to the bottom of this. I reviewed challenged requests to `electrum.readthedocs.io` and they were basically all challenged for reputation and basically all the traffic was Tor. What's odd to me is that I do see quite a few challenge requests for static files which is odd given I'd expect the first challenge for the HTML to allow access to the static files.

**Comment by davidfischer** [comment]
> I do see quite a few challenge requests for static files

Actually virtually all of these were for custom fonts. That's still odd that those get challenged but not loading fonts wouldn't cause the pages to look like what they do in the screencast.

**Comment by lukejohnsonrp** [comment]
> We absolutely get crawled or get unwanted security scans frequently by bots crawling RTD to the tune of tens of requests per second and I want to challenge those people. As a result, I don't want to have a blanket allow rule for Tor unless other challenge rules take precedence. With that said, I'll review our challenge rules now.

I have asked on #tor on irc.oftc.net IRC and found out that the reason why `Tor Browser` is working without issues is that `Onion Routing` option that you mentioned activates a protocol that was designed by Cloudflare for Tor that permits performing a challenge containing `Alt-Svc` which provides an `.onion` address to redirect the requests to. In that specific case, Cloudflare provides its own .onion domain and asks Tor Browser to be redirected to it. 

This article describes very well how it works: https://blog.cloudflare.com/cloudflare-onion-service/

The crawler bots could have implemented this protocol to avoid captchas easily and it's pointless to worry about some extra crawling in that case. This is not even a javascript challenge, it's a raw HTTP exchange that permits avoiding captcha and could be successfully abused. I wouldn't recommend relying fully on it as a crawler/bots protection and I believe that you still should whitelist Tor exits as there should be no dramatic difference, except you will allow Tor users to have best experience with your site. I run various own sites with Tor whitelisted in CF (not Onion Routing) and there are no issues with crawlers, except they "eat" some little more bandwidth, especially when you don't host dynamic content with heavy backends that are supposed to have their own bots protection mechanisms.

Summarizing, at this point you can provide a Tor Hidden Service (.onion) and there should be no difference between having it and 'Onion Routing' enabled in Cloudflare.

> @lukejohnsonrp, would you mind sharing a few other things:
> 
> Do you have non-standard cookie settings in the browser you're using? I'm not precisely sure (I'll test this) but I believe if you've set all cookies to reject, you're going to get more challenges especially if you're using Tor because there will be no memory of passing the previous challenge.

No, all settings are default provided by Debian package.

> I noticed you were using some ad blocker plugins. With their standard settings, those should be fine. Are you doing anything non-standard with respect to blocking requests back to Read the Docs?

No, all settings are default, I do not modify AdBlock and uBlock settings.

> Are you using any other browser plugins there to block requests for certain types of content? Opening the developer console would tell why those requests for static files were blocked.

No.

**Comment by lukejohnsonrp** [comment]
> We absolutely get crawled or get unwanted security scans frequently by bots crawling RTD to the tune of tens of requests per second and I want to challenge those people. As a result, I don't want to have a blanket allow rule for Tor unless other challenge rules take precedence. With that said, I'll review our challenge rules now.

I have asked on #tor on irc.oftc.net IRC and found out that the reason why `Tor Browser` is working without issues is that `Onion Routing` option that you mentioned activates a protocol that was designed by Cloudflare for Tor that permits performing a challenge containing `Alt-Svc` which provides an `.onion` address to redirect the requests to. In that specific case, Cloudflare provides its own .onion domain and asks Tor Browser to be redirected to it. 

This article describes very well how it works: https://blog.cloudflare.com/cloudflare-onion-service/

The crawler bots could have implemented this protocol to avoid captchas easily and it's pointless to worry about some extra crawling in that case. This is not even a javascript challenge, it's a raw HTTP exchange that permits avoiding captcha and could be successfully abused. I wouldn't recommend relying fully on it as a crawler/bots protection and I believe that you still should whitelist Tor exits as there should be no dramatic difference, except you will allow Tor users to have best experience with your site. I run various own sites with Tor whitelisted in CF (not Onion Routing) and there are no issues with crawlers, except they "eat" some little more bandwidth, especially when you don't host dynamic content with heavy backends that are supposed to have their own bots protection mechanisms.

Summarizing, at this point you can provide a Tor Hidden Service (.onion) and there should be no difference between having it and 'Onion Routing' enabled in Cloudflare.

> @lukejohnsonrp, would you mind sharing a few other things:
> 
> Do you have non-standard cookie settings in the browser you're using? I'm not precisely sure (I'll test this) but I believe if you've set all cookies to reject, you're going to get more challenges especially if you're using Tor because there will be no memory of passing the previous challenge.

No, all settings are default provided by Debian package.

> I noticed you were using some ad blocker plugins. With their standard settings, those should be fine. Are you doing anything non-standard with respect to blocking requests back to Read the Docs?

No, all settings are default, I do not modify AdBlock and uBlock settings.

> Are you using any other browser plugins there to block requests for certain types of content? Opening the developer console would tell why those requests for static files were blocked.

No.


In relation to why the page loads with broken CSS content, this is not an issue on your side. As the screencast shows, Cloudflare requests captcha again after it has been successfullly solved, so it's what happens for subsequent HTTP requests for CSS - those requests are being stuck on bot protection again because there is some session management problems on Cloudflare side.

**Comment by davidfischer** [comment]
I will admit that my Tor knowledge is pretty minimal. After reading up on `Alt-Svc` I expected to see it in the response headers using Tor Browser but I didn't see it. Maybe I'm doing something wrong. I use Tor Browser in my testing setup due to ease of setup/install but maybe I need to go through the steps you outlined.

With that said, certain requests on Read the Docs are somewhat expensive and 404s on certain projects especially are a little taxing on the server (we try various things like redirects, etc.). As a result, I don't want to just have a blanket allow rule for Tor. From what I can see, the steps you outlined would mean users using Tor would never get challenged which is not what I want.

**Comment by happysmash27** [comment]
The authorisation to view the pages keeps resetting and this results in all assets and CSS being broken: 

![2021-11-29-073813_1229x971_scrot](https://user-images.githubusercontent.com/3620657/143897274-6065897f-a1b6-4d3f-ada9-39de5c3c739c.png)

**Comment by davidfischer** [comment]
@happysmash27 Does this occur on all RTD documentation? For example, does this also occur on https://docs.readthedocs.io? I assume you are using Tor but this looks like a challenge for static files which is odd. Can you describe your Tor setup a bit? This does not happen for me at least with the Tor browser from torproject.org although it could be based on your exit node.
