### ISSUE TITLE
Trying to enable colored HTML for ANSI escape sequences

### ISSUE THREAD

**Issue by leeping** [readthedocs/readthedocs.org#7599]
First off, I wanted to say thanks for making the documentation hosting process so easy to use.  My experience as a new user has been overwhelmingly positive.  This issue is regarding something that (to my knowledge) hasn't been attempted on RTD before, but I hope it is useful enough to merit some attention.

## Details

* Read the Docs project URL: geometric.readthedocs.io
* Build URL (if applicable): https://geometric.readthedocs.io/en/latest/quickstart.html
* Read the Docs username (if applicable): leeping

## Expected Result

I'm creating some documentation pages where I'd like to have control over the color of text in literal blocks.  The reason is that my project makes use of ANSI color codes in its output and I want the example output in my documentation to reflect what users see in the terminal.  I found that this was possible with a package [sphinxcontrib-ansi](https://github.com/sphinx-contrib/ansi) that converts ANSI escape codes to HTML color output, and I was able to get it working locally.  Here's a screenshot of the locally built docs.

![Screenshot 2020-10-23 at 6 14 20 AM](https://user-images.githubusercontent.com/1441560/97007945-05b29780-14f7-11eb-9693-180817e2f2ea.png)

Additionally, I noticed that sphinxcontrib-ansi hadn't been maintained for some time, and it wasn't pip-installable so I created a [project on PyPI](https://pypi.org/project/sphinxcontrib-ansi/) for it.

## Actual Result

The [latest build](https://readthedocs.org/projects/geometric/builds/12171275/) of the docs does not appear to show any colored text.  From looking at the build logs, it looks like the package is being installed correctly, and the build system is aware of my conf.py file.  The [source files uploaded to RTD](https://geometric.readthedocs.io/en/latest/_sources/quickstart.rst.txt) are unmodified from the originals, including the ANSI escape codes, however the HTML output does not contain the color blocks that I expected.

![Screenshot 2020-10-23 at 6 16 30 AM](https://user-images.githubusercontent.com/1441560/97008148-51654100-14f7-11eb-81ce-c7eb79e80601.png)

**Comment by stsewd** [comment]
I'd recommend using a config file and pinning your dependencies to the same you are using locally (like the same version of sphinx) so you can make sure the same versions are running on rtd.

https://github.com/leeping/geomeTRIC/blob/master/docs/requirements.txt

https://docs.readthedocs.io/en/stable/config-file/v2.html
