### ISSUE TITLE
Build error with build id #12145227

### ISSUE THREAD

**Issue by afshin** [readthedocs/readthedocs.org#7600]
# Details
Read the Docs project URL: https://readthedocs.org/projects/jupyterlab/
Build URL (if applicable): Build number 12145227
Read the Docs username (if applicable): darian

# Expected Result
JupyterLab is a widely used (10K+ stars) platform for interactive computing.  
We are trying to add TypeScript API documention to our narrative documentation.
The build commands work locally and rely on running the typedoc service against our TypeScript packages.

# Actual Result
The command that generates the TypeScript documentation is giving ""Command killed due to excessive memory consumption".
Would it be possible to increase our project's memory limit?
Thank you so much for the ReadTheDocs service, it has been invaluable for our project.

**Comment by humitos** [comment]
Thanks for the report! This is already in my radar. I've already moved your project to one of our bigger server and it's still failing, so we will need ask the them what would be the next step.

I'm closing this as duplicated of #7583. Please, subscribe there.

**Comment by afshin** [comment]
Thank you!
