### ISSUE TITLE
Document variables used to resolve project/version/domain

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#7607]
It would be good to document the variables that we are injecting in the `request` object in the Proxito middleware (and maybe in other places as well) so we avoid confusions in the future.

We have (at least) these ones:

- `host_project_slug`
- `path_version_slug`
- `path_project_slug`
- `cname`
- `subdomain`
- `rtdheader`
- `external_domain`
- etc

Reference: https://github.com/readthedocs/readthedocs.org/pull/7593#discussion_r512536230

**Comment by stsewd** [comment]
With the refactors around proxito, most of those variables don't exist anymore. The remaining ones are `path_version_slug` and `path_project_slug`.
