### ISSUE TITLE
Build documentation on server fails

### ISSUE THREAD

**Issue by HeaTTheatR** [readthedocs/readthedocs.org#7609]
## Details

* Read the Docs project URL: https://github.com/kivymd-components/sweetalert/tree/master/docs
* Build URL (if applicable): https://readthedocs.org/projects/sweetalert/builds/12200845/
* Read the Docs username (if applicable): KivyMD

*A description of what you wanted to happen*
I want to make an automatic build of documentation when new changes appear in my project - https://github.com/kivymd-components/sweetalert I configured all the necessary hooks.

## Actual Result
For some reason, the documentation assembly is trying to build from the entire Python library, and I only need it from my project.

*A description of what actually happened*
Build documentation on the server fails. Although locally on my computer, building the documentation works.

**Comment by stsewd** [comment]
> For some reason, the documentation assembly is trying to build from the entire Python library, and I only need it from my project.

What do you mean by this?

I'm not able to reproduce the problem locally.

Maybe this is a problem with the paths?  I'd recommend to use `__file__` so it works from any cwd.

https://github.com/kivymd-components/sweetalert/blob/1d097cfc4445713a685635fa7d61f8a6f155e754/docs/sources/conf.py#L50
