### ISSUE TITLE
.. autoclass:: working on the index.html file but it doesn't when I publish the documentation

### ISSUE THREAD

**Issue by ulgenklc** [readthedocs/readthedocs.org#7610]
I am trying to publish my documentation and API using autodoc. 
This is the first time I'm using ReadTheDocs and I felt like I was so close until I clicked on the API page on the documentation.

In my index html file 
<img width="1440" alt="Screen Shot 2020-10-27 at 3 09 22 PM" src="https://user-images.githubusercontent.com/41899160/97349887-68dd5a80-1866-11eb-8d7a-66e18a2c6538.png">

I can see the python API documentation but when I build the documentation with ReadTheDocs, 

<img width="1440" alt="Screen Shot 2020-10-27 at 3 10 31 PM" src="https://user-images.githubusercontent.com/41899160/97350010-91fdeb00-1866-11eb-9897-d85cf10f4f93.png">

It's empty like this. Every other page works fine except the API.

I get two warnings when I'm building the documentation on ReadTheDocs:

`` Running Sphinx v3.2.1``
``loading translations [en]... done``
``making output directory... done``
``WARNING: html_static_path entry '_static' does not exist``
``building [mo]: targets for 0 po files that are out of date``
``building [latex]: all documents``
``updating environment: [new config] 4 added, 0 changed, 0 removed``
``reading sources... [ 25%] Complex_Contagions``
``reading sources... [ 50%] Introduction``
``reading sources... [ 75%] Quick Tutorial``
``reading sources... [100%] index``

``looking for now-outdated files... none found``
``pickling environment... done``
``checking consistency... done``
``processing complexneuronalcontagions.tex... index Introduction Quick Tutorial Complex_Contagions ``
``resolving references...``
``done``
``writing... done``
``copying images... [ 16%] networkx.png``
``copying images... [ 33%] contagion.png``
``copying images... [ 50%] first_activation.png``
``copying images... [ 66%] distance_matrix.png``
``copying images... [ 83%] contagion_sizes.png``
``copying images... [100%] pers_diag.png``

``copying TeX support files... copying TeX support files...``
``done``
``build succeeded, 1 warning.``

``The LaTeX files are in _build/latex.``
``Run 'make' in that directory to run these through (pdf)latex``
``(use `make latexpdf' here to do that automatically).``
``WARNING: Missing searchtools: /home/docs/checkouts/readthedocs.org/user_builds/complex-contagions/checkouts/latest/Excitations_python/docs/source/_build/latex/_static/searchtools.js ``

This is what my configuration file looks like

<img width="1440" alt="Screen Shot 2020-10-27 at 3 15 56 PM" src="https://user-images.githubusercontent.com/41899160/97350844-5d3e6380-1867-11eb-96dc-7ea96f6681dc.png">

Here is the repository:

https://github.com/ulgenklc/Complex-Contagions/tree/master/Excitations_python

Any suggestions?

**Comment by ulgenklc** [comment]
Nevermind, it suddenly wanted to work out of nowhere!!

**Comment by stsewd** [comment]
> Nevermind, it suddenly wanted to work out of nowhere!!

it could have been a cached version :)

**Comment by ulgenklc** [comment]
Yes, possibly! Do you think those two warnings are worth to follow up?

**Comment by stsewd** [comment]
>  WARNING: html_static_path entry '_static' does not exist

the first warning is because you don't have the `_static` directory in your repo (is usually an empty dir so git doesn't include it)

>  WARNING: Missing searchtools: /home/docs/checkouts/readthedocs.org/user_builds/complex-contagions/checkouts/latest/Excitations_python/docs/source/_build/latex/_static/searchtools.js 

I have no idea about that one, but looks like related to the pdf generation
