### ISSUE TITLE
Dependencies from conda-forge are being removed during sphinx installation due to conda channel priority

### ISSUE THREAD

**Issue by bdice** [readthedocs/readthedocs.org#7619]
## Details

* Read the Docs project URL: https://freud.readthedocs.io/en/stable/
* Build URL (if applicable): https://readthedocs.org/projects/freud/builds/12216572/
* Read the Docs username (if applicable): bdice

## Expected Result

I have a conda environment yml file:
```
name: freud-rtd
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - pip
  - scikit-build
  - cmake
  - cython
  - tbb
  - tbb-devel
  - numpy
  - sphinx
  - sphinx_rtd_theme
  - nbsphinx
  - jupyter_sphinx
  - sphinxcontrib-bibtex
```

Some of the packages are installed from conda-forge, and then removed during the step:
`conda install --yes --quiet --name 668 mock pillow sphinx sphinx_rtd_theme`

I expected that this step wouldn't remove my package dependencies.

## Actual Result

Dependencies were removed, resulting in a failed build. This appears to be due to channel priority, where `main` is preferred over `conda-forge` in the second step even though my conda environment prefers `conda-forge` over `main`.

```
The following packages will be REMOVED:

  jupyter_sphinx-0.3.1-py39hde42818_1
  pybtex-0.23.0-py39hde42818_0
  pybtex-docutils-0.2.2-py39hde42818_2
  python_abi-3.9-1_cp39
  scikit-build-0.11.1-py39hf149a3a_2
  sphinxcontrib-bibtex-1.0.0-py_0
```

This appears to have changed in the last 2 weeks or so (or at least that's when my builds started failing).

**Comment by bdice** [comment]
Swapping the channel order so that `conda-forge` is after `main` seems to fix the package installation issues, but it's not the behavior I would prefer. I'd like to have `conda-forge` at the top. There is currently another problem in my build (linking against Intel TBB fails) but I think that is unrelated. https://readthedocs.org/projects/freud/builds/12217822/

**Comment by stsewd** [comment]
Would the `CONDA_APPEND_CORE_REQUIREMENTS` feature flag help with this? https://docs.readthedocs.io/en/stable/guides/feature-flags.html#available-flags

> Append Read the Docs core requirements to environment.yml file
> Makes Read the Docs to install all the requirements at once on conda create step. This helps users to pin dependencies on conda and to improve build time.

**Comment by bdice** [comment]
@stsewd I think that would help, yes! If the conda environment only performs a "solve" one time instead of twice, and the channels are set correctly during that solve, it should fix the problem.

I don't see how to activate the feature flag. Do I enable that by setting an Environment Variable in my project settings? What do I set it to?

**Comment by humitos** [comment]
@bdice I added that flag to your project. Let me know if that works.

> I don't see how to activate the feature flag. Do I enable that by setting an Environment Variable in my project settings? What do I set it to?

These feature flags can be enabled by the core team only --they are not available for users.

**Comment by bdice** [comment]
@humitos @stsewd Thanks, this issue is resolved!

I had originally looked for a solution in the conda config options, perhaps this feature can be added there. https://docs.readthedocs.io/en/stable/config-file/v2.html#conda

**Comment by stsewd** [comment]
Feature flags are experimental options that in time would be default or become an option, if this one becomes an option the config file would be great place, yes.
