### ISSUE TITLE
PRs show incorrect current version

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#7622]
Our PRs constantly link to another PR as the latest version, which isn't current.

![image](https://user-images.githubusercontent.com/10674555/97650000-1a2eec80-1a2f-11eb-9b18-81fb9b218075.png)

https://frc-docs--905.org.readthedocs.build/en/905/

**Comment by stsewd** [comment]
This was already fixed in https://github.com/readthedocs/readthedocs.org/pull/7340. The problem here is that the API call isn't redirecting correctly for some reason 

https://frc-docs--905.org.readthedocs.build/_/api/v2/footer_html/?_=1604327369858&absolute_uri=https%3A%2F%2Ffrc-docs--905.org.readthedocs.build%2Fen%2F905%2F&callback=jQuery351021399906449841266_1604327369857&docroot=%2Fsource%2F&format=jsonp&page=index&project=frc-docs&source_suffix=.rst&theme=sphinx_rtd_theme&version=905

(infinite redirect)

**Comment by stsewd** [comment]
Maybe do you have some redirects setup in your project? I can't replicate this in other projects

**Comment by stsewd** [comment]
This is weird, this only happening on this subdomain https://frc-docs--905.org.readthedocs.build/, https://frc-docs--915.org.readthedocs.build/en/915/ works fine

**Comment by stsewd** [comment]
Seeing an infinite redirect on the footer when the version is 905 https://frc-docs--905.org.readthedocs.build/_/api/v2/footer_html/?project=frc-docs&version=905&page=index&format=jsonp&docroot=%2Fsource%2F

It works with 906 https://frc-docs--905.org.readthedocs.build/_/api/v2/footer_html/?project=frc-docs&version=906&page=index&format=jsonp&docroot=%2Fsource%2F

Same for other subdomain https://frc-docs--915.org.readthedocs.build/_/api/v2/footer_html/?project=frc-docs&version=905&page=index&format=jsonp&docroot=%2Fsource%2F

**Comment by stsewd** [comment]
Found the problem, this happens when a version doesn't exist. We delete the version after the PR is closed, so the docs you are seeing are cached, or we don't delete them from storage.

**Comment by Daltz333** [comment]
We do custom redirects using the sphinxext-rediraffe plugin. But I do not think that is the issue.

**Comment by stsewd** [comment]
We don't delete external versions when the PR is closed/merged now. We mark them as inactive, so the infinite redirect shouldn't happen now (in new builds).

**Comment by Daltz333** [comment]
This issue is still there. The redirect is fine but the detected latest version is false. It should use whatever is marked stable. Not another PR ![Screenshot_20201209-193751_Firefox Focus.jpg](https://user-images.githubusercontent.com/10674555/101705948-1d69bf00-3a56-11eb-86c4-17e622fbc660.jpg)

**Comment by stsewd** [comment]
@Daltz333 is that a recent PR build? Can you put the link here?

**Comment by Daltz333** [comment]
Here is a PR that was updated recently https://frc-docs--974.org.readthedocs.build/en/974/

**Comment by stsewd** [comment]
I can see the api is returning `show_version_warning: false`. Looks like that message comes from this extension https://sphinx-version-warning.readthedocs.io/en/latest/configuration.html#confval-versionwarning_default_message, not from rtd.

**Comment by Daltz333** [comment]
Oh, lol.
