### ISSUE TITLE
ReadTheDocs.io is down

### ISSUE THREAD

**Issue by jason-lang2018** [readthedocs/readthedocs.org#7625]
It looks like the site is down again

**Comment by Luberr-Dhruv** [comment]
Our Documentation website ages to load, but it loads. Avg time: 4-5 mins per page/link.

**Comment by stsewd** [comment]
We are taking a look, thanks for reporting!

**Comment by stsewd** [comment]
Looks like maybe this is related to cloudflare https://www.cloudflarestatus.com/#past-incidents, a partial solution has been implemented docs are loading for me again.

**Comment by Luberr-Dhruv** [comment]
Same Here. Docs loading at faster speeds now. I need your honest answer now. Does this happen frequently?
