### ISSUE TITLE
Translations not appearing on frc-docs

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#7626]
Translations are not appearing in our sidebar on our project, they were showing up previously and no changes have been made to the project configuration.

Project URL: https://docs.wpilib.org/en/latest/ and https://frc-docs.readthedocs.io/en/latest/
Project: frc-docs
Maintainer: daltz333

Attached is an image of the problem plus our translation configuration.

![image](https://user-images.githubusercontent.com/10674555/97735251-7554f380-1ab0-11eb-90c2-0d4d3c8ce2be.png)

![image](https://user-images.githubusercontent.com/10674555/97735087-43439180-1ab0-11eb-9385-2df14429e907.png)

@stsewd @humitos

**Comment by stsewd** [comment]
> Looks like this is a problem globally, see on the ReadTheDocs own documentation page
> ![image](https://user-images.githubusercontent.com/10674555/97735756-1fcd1680-1ab1-11eb-8cc1-083833ff08c4.png)

yeah, we were having problems last friday, so we disabled the footer api call for a moment
