### ISSUE TITLE
Readthedocs out of sync with branch on GitHub when using jupyter-sphinx

### ISSUE THREAD

**Issue by GroenteLepel** [readthedocs/readthedocs.org#7629]
## Details

* Read the Docs project URL: https://qiskit-quantum-knn.readthedocs.io/en/docs/
* Read the Docs username (if applicable): GroenteLepel

## Expected Result

I have a branch named [`docs`](https://github.com/GroenteLepel/qiskit-quantum-knn/tree/docs) on my GitHub page where I update all my docstrings. I have added this branch in my project page on readthedocs.org. I have made some changes on that branch locally, pushed the changes to GitHub and automatically my docs are being build.

I use `jupyter-sphinx` to create some example code snippets, which nicely show on my local machine using Sphinx. I'd like to have my URL page of RTD have this too.

## Actual Result

However, when I take a look at the [source code](https://qiskit-quantum-knn.readthedocs.io/en/docs/_modules/qiskit_quantum_knn/qknn/qknn_construction.html#create_qknn) which RTD has nicely found, it seems that the [created HTML page](https://qiskit-quantum-knn.readthedocs.io/en/docs/source/qiskit_quantum_knn.qknn.html#qiskit_quantum_knn.qknn.qknn_construction.create_qknn) does not have that example ready. I checked the Build page and the [raw file](https://readthedocs.org/api/v2/build/12243823.txt) corresponding to the build, but I cannot find any errors on this (beside the warnings of wrong indentations but I also have those on my machine, it's still a WIP).

**Comment by humitos** [comment]
> it seems that the [created HTML page](https://qiskit-quantum-knn.readthedocs.io/en/docs/source/qiskit_quantum_knn.qknn.html#qiskit_quantum_knn.qknn.qknn_construction.create_qknn) does not have that example ready.

What do you mean by this?

I'm seeing this example in the link you shared and it looks correct to me.

![Screenshot_2020-11-02_16-56-53](https://user-images.githubusercontent.com/244656/97889304-81e58000-1d2c-11eb-99c8-6f9c8517faf8.png)

Can you highlight what's the exact difference between the source code and the documentation?

Also, if this is correct now and it wasn't when you checked it may be related to the cache being purged. It takes a couple of minutes sometimes.

**Comment by GroenteLepel** [comment]
Oh wow yes exactly that. I can see it on my own devices as well. Allright seems I was a bit impatient then!
