### ISSUE TITLE
Build error with build id #12244434

### ISSUE THREAD

**Issue by ssbarnea** [readthedocs/readthedocs.org#7631]
## Details:

* Project URL: https://readthedocs.org/projects/ansible-lint/
* Build URL(if applicable): https://readthedocs.org/projects/ansible-lint/builds/12244434/
* Read the Docs username(if applicable): ssbarnea

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by stsewd** [comment]
Hi, this looks like a temporal problem, the latest build from your project is working https://readthedocs.org/projects/ansible-lint/builds/12245030/. We don't have a way to re-trigger a build from a PR, but you can close/open the PR or push a new commit to re-trigger a new build.
