### ISSUE TITLE
option to opt out of install_core_requirements

### ISSUE THREAD

**Issue by graingert** [readthedocs/readthedocs.org#7638]
## Details

* Read the Docs project URL: ldaptor

we're currently explicitly installing the latest version of various core requirements to avoid using the very outdated ones currently installed
https://github.com/twisted/ldaptor/blob/master/setup.cfg#L39-L48

I'd like to an option to opt out of install_core_requirements and manage them entirely with our own requirements.txt files or pip extras

## Expected Result

I'd like to an option to install_core_requirements and manage them entirely with requirements.txt files or pip extras

## Actual Result

install_core_requirements currently cannot be skipped

**Comment by stsewd** [comment]
@graingert we recommend pinning your dependencies just as you are doing it now so your docs are reproducible outside RTD too.

> I'd like to an option to opt out of install_core_requirements and manage them entirely with our own requirements.txt files or pip extras

Isn't that what you are doing now?

**Comment by graingert** [comment]
@stsewd no currently the old packages are installed mock, pillow etc, and then our doc extra uninstalls them and installs updated versions. I'd like to be able to skip the `install_core_requirements` and configure my own requirements-pypa.txt and [doc] extra without having to worry about these older deps

**Comment by stsewd** [comment]
> the old packages are installed mock, pillow etc, and then our doc extra uninstalls them and installs updated versions

I don't see why that would be a problem then. The requirements installed during the build are the new ones from your project (and we recommend pinning your requirements).

**Comment by stsewd** [comment]
I don't think we would support this, the builds depend on other packages we install by default, this would add extra complexity and not real improvement. Default packages can already be overridden.
