### ISSUE TITLE
Dependency installed multiple times until memory runs out

### ISSUE THREAD

**Issue by yoelcortes** [readthedocs/readthedocs.org#7639]
## Details

* Read the Docs project URL:
https://readthedocs.org/projects/biosteam/
* Build URL (if applicable):
https://readthedocs.org/projects/biosteam/builds/12255097/
* Read the Docs username (if applicable):
yoelcortes

## Expected Result

The build should install scipy>=1.3.1 only once

## Actual Result

Multiple versions of scipy were downloaded until readthedocs ran out of memory
```
Collecting scipy>=1.3.1
  Downloading scipy-1.5.2-cp37-cp37m-manylinux1_x86_64.whl (25.9 MB)
Collecting scipy>=1.3.1
  Downloading scipy-1.5.1-cp37-cp37m-manylinux1_x86_64.whl (25.9 MB)
Collecting scipy>=1.3.1
  Downloading scipy-1.5.0-cp37-cp37m-manylinux1_x86_64.whl (25.9 MB)
Collecting scipy>=1.3.1
  Downloading scipy-1.4.1-cp37-cp37m-manylinux1_x86_64.whl (26.1 MB)
Collecting scipy>=1.3.1
  Downloading scipy-1.4.0-cp37-cp37m-manylinux1_x86_64.whl (26.1 MB)
Collecting scipy>=1.3.1
  Downloading scipy-1.3.3-cp37-cp37m-manylinux1_x86_64.whl (25.2 MB)
Collecting scipy>=1.3.1
  Downloading scipy-1.3.2-cp37-cp37m-manylinux1_x86_64.whl (25.2 MB)
Collecting scipy>=1.3.1
  Downloading scipy-1.3.1-cp37-cp37m-manylinux1_x86_64.whl (25.2 MB)

Command killed due to excessive memory consumption
```

Any help on how to get readthedocs to download just one version (without having to use "==") would be appreciated! Thanks!

**Comment by stsewd** [comment]
Hi, does this happen locally? I think it may be related to the new pip resolver https://github.com/pypa/pip/issues/8713

I'll try removing your project from the sample of projects using the new resolver.

**Comment by stsewd** [comment]
I have removed your project from the sample using the new pip resolver https://readthedocs.org/projects/biosteam/builds/12256575/

But the problem may be back when the new resolver is used by default at the end of this month. You may want to check the issue I linked.
