### ISSUE TITLE
Please increase build timeout for Colour project.

### ISSUE THREAD

**Issue by KelSolaar** [readthedocs/readthedocs.org#7641]
## Details

* Read the Docs project URL: https://colour.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/colour/builds/12259421/
* Read the Docs username (if applicable): colour-science

## Expected Result

*A description of what you wanted to happen*

A successful build.

## Actual Result

*A description of what actually happened*

The build is timing out! CCing @MichaelMauderer for visibility.

We are generating Matplotlib plots during the build and I think we just got past the systematic timeout so we are asking politely if it would be possible to increase our build timeout.

For reference, the local build of HTML and PDF targets along with the plots on my (old) Macbook is about 13 minutes:

```
real    12m34.329s
user    7m54.276s
sys     0m30.664s
```

Thanks,

Thomas, Michael and The Colour Developers

**Comment by humitos** [comment]
I increased the time for your project to 1200s and triggered a new build on `develop`: https://readthedocs.org/projects/colour/builds/12262842/. Let's see if it pass, and let me know otherwise.

**Comment by KelSolaar** [comment]
Hi @humitos,

Thanks a ton, I think it went through!

> Build took 908 seconds

I think we were surfing at the border :)

Cheers,

Thomas

**Comment by humitos** [comment]
@KelSolaar great! Feel free to ask again for more time if needed in the future.

**Comment by KelSolaar** [comment]
Awesome and thank you so much for the great support! You people are doing a fantastic job!
