### ISSUE TITLE
Files are not remove between succesive builds for the same READTHEDOCS_VERSION

### ISSUE THREAD

**Issue by adiroiban** [readthedocs/readthedocs.org#7642]
First i want to thank you for the great RTD project :)

## Details

I am trying to hack the Sphinx build system by creating pydoctor based API docs at the end of the Sphinx narrative docs.

The goal is to have the full documentation for a project inside the read the docs both source code API docs and Sphinx narrative docs.

It looks like old files are not removed when pushing the build for a new version... and there is a strange caching

I have the following RTD URL https://pydoctor--254.org.readthedocs.build/en/254/

As part of on older build https://readthedocs.org/projects/pydoctor/builds/12266734/ some files were pushed to /apidocs/ path.

In a newer build  https://readthedocs.org/projects/pydoctor/builds/12266754/ those files were move to /api/ path.

## Expected Result

The old https://pydoctor--254.org.readthedocs.build/en/254/apidocs/ will no longer be available

All pages are generated with the same (or very close) timestamp.

## Actual Result

The RTD public page has both files:

https://pydoctor--254.org.readthedocs.build/en/254/api/
https://pydoctor--254.org.readthedocs.build/en/254/apidocs/

And we have an old file at https://pydoctor--254.org.readthedocs.build/en/254/apidocs/pydoctor.html
But on older file was removed https://pydoctor--254.org.readthedocs.build/en/254/apidocs/moduleIndex.html

Also, I can see this build times, when the latest build for that PR was at 2020-11-05 00:45:00

* 2020-11-04 23:07:30.  https://pydoctor--254.org.readthedocs.build/en/254/api/index.html 
* 2020-11-05 00:13:09  https://pydoctor--254.org.readthedocs.build/en/254/api/pydoctor.html

**Comment by adiroiban** [comment]
well, after reporting this issue, at 01:15 the page at https://pydoctor--254.org.readthedocs.build/en/254/api/index.html was updated and has time as " 2020-11-05 00:46:51"

still the page at https://pydoctor--254.org.readthedocs.build/en/254/api/pydoctor.html has time as "2020-11-05 00:13:09"

and the old https://pydoctor--254.org.readthedocs.build/en/254/apidocs/ is still there

so it looks like this is a caching issue

**Comment by adiroiban** [comment]
Another thing that I have observed

These pages have different content 
https://pydoctor--254.org.readthedocs.build/en/254/api/
https://pydoctor--254.org.readthedocs.build/en/254/api/index.html

I am expecting to have the same content.

**Comment by adiroiban** [comment]
Another think

https://pydoctor--254.org.readthedocs.build/en/254/api/  -> © Copyright 2020, Michael Hudson-Doyle and various contributors (see Git history) Revision ac47ef33. 

https://pydoctor--254.org.readthedocs.build/en/254/index.html © Copyright 2020, Michael Hudson-Doyle and various contributors (see Git history) Revision 31b056ff.

**Comment by humitos** [comment]
Hi @adiroiban! I think all the problems you mentioned are cache related. Immediately after the build succeeds, we send a signal to Cloudflare to purge the cache. It could takes some minutes to be finally purged from all the CDN servers.

I don't think this issue is valid anymore since the cache was purged correctly and all the links that you shared are 404 or show the correct information.

Please, expand on this if you think it's not related to cache or share any other specific example that I can take a look.

**Comment by adiroiban** [comment]
True. Many thanks.

**Comment by adiroiban** [comment]
Maybe on a PR, in the same place in which the "This page was created from a pull request." warning is placed, also add information that there is an aggressive cache provided by Cloudflare.

**Comment by adiroiban** [comment]
@humitos  or another crazy idea... don't use CloudFlare caching for PR builds.

The PR builds should be used for development and quick feedback... so I think that the current CloudFlare caching makes them just a test for build ok / build fail status...but you can't really check the build HTML updates.
