### ISSUE TITLE
[Errno 2] No such file or directory

### ISSUE THREAD

**Issue by AninditaBasu** [readthedocs/readthedocs.org#7647]
## Details

* Read the Docs project URL: https://readthedocs.com/projects/vymo-technologies-docs/
* Build URL (if applicable): https://readthedocs.com/projects/vymo-technologies-docs/builds/471552/
* Read the Docs username (if applicable):

## Expected Result

Build without errors. (A local installation of MkDocs builds without errors.)

## Actual Result

`ERROR   -  Error reading page 'topics/wip/relnotes.md': [Errno 2] No such file or directory: ''`

The file exists in the directory but the build failed. To get a successful build, I had to remove the file from the directory.

**Comment by humitos** [comment]
Hi @AninditaBasu! Please, if you have question or doubt about Read the Docs for Business (readthedocs.com) contact us at support@readthedocs.com. Thanks!

**Comment by AninditaBasu** [comment]
Hi @humitos Apologies! I did not realise this was not the correct place to ask about this issue :blush: 
Am now writing to support@readthedocs.com
