### ISSUE TITLE
Can't find email address associated with username

### ISSUE THREAD

**Issue by dionyziz** [readthedocs/readthedocs.org#765]
I own the username `dionyziz`. When I tried to register on your site, it tells me that username already exists. I'm pretty sure that I've registered there, as I'm the only person using that username in the world. I don't remember my password, so I can't login. When I click on forgot password, it asks me for my e-mail address. I don't know what e-mail address I've signed up with (I've had tens of e-mail addresses throughout the years). I tried my main e-mail address, but it didn't work. What's the right way to reset my password based on my username and not just my e-mail address?

**Comment by mskmsss** [comment]
Same issue with me

**Comment by mskmsss** [comment]
how to recover password using username?

**Comment by agustinernestocardeilhac** [comment]
Hi Guys !. I'm not able to recover my password. My username is agustincba !. I am using the one I used to register and it doesn't exist... I've been doing PR a lot this passt two months... Dunno what happened...

**Comment by agustinernestocardeilhac** [comment]
I commented with another user...

**Comment by harielakantie** [comment]
I have another GITHub account with userName: harielakanti. and link: https://github.com/harielakanti
I don't the emailId for this account and I forgot the PW.
am not able to logIn here, and not able to do ForgotPassword.
I was to reActivate or Permanently delete this Account.
Please help me.

**Comment by RichardLitt** [comment]
This is quite an old issue, and not ideal as a place to drop requests like this, because it isn't a catch-all for this type of issue (as it as opened by one person for one support task), and because it's likely that comments here will be missed in the general amount of issues RTFD has. Please open a new issue. For now, I am going to lock this. Thanks.
