### ISSUE TITLE
Tracking down a problem with make latexpdf, possibly in a table

### ISSUE THREAD

**Issue by temcdrm** [readthedocs/readthedocs.org#7651]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/tesp/
* Build URL (if applicable): https://readthedocs.org/projects/tesp/builds/12284806/ 
* Read the Docs username (if applicable): temcderm

## Expected Result

The build should produce both HTML and a PDF download. This triggered build worked on October 3: https://readthedocs.org/projects/tesp/builds/12017094/ but this one failed on October 7: https://readthedocs.org/projects/tesp/builds/12042725/

## Actual Result

The triggered HTML build works but the PDF stops with one remaining error shown below. However, I'm able to do `make latex` on my own computer, upload those LaTex files to Overleaf, and then produce a PDF there with no problems. How can I track this down on ReadTheDocs so that the triggered build can include PDF?

`Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/tesp/envs/latest/lib/python3.8/site-packages/sphinx/writers/latex.py", line 947, in <listcomp>
    underlined = [cell.row + cell.height == self.table.row + 1 for cell in cells]
AttributeError: 'NoneType' object has no attribute 'row'
The full traceback has been saved in /tmp/sphinx-err-8ij6mnnl.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!`

**Comment by humitos** [comment]
Hi @temcdrm! Are you using the exact same version of dependencies locally than on Read the Docs? In particular, `Sphinx` version.

**Comment by temcdrm** [comment]
Thanks!  It seems the problem occurs in **sphinx-jsonschema**, at version **1.16.4**.  My JSON file seems valid (and has not changed) so I will report the issue over at https://github.com/lnoor/sphinx-jsonschema/issues .
