### ISSUE TITLE
failed badge on home page but actual build succeed 

### ISSUE THREAD

**Issue by W3-Anjan** [readthedocs/readthedocs.org#7652]
## Details

* Read the Docs project URL: https://github.com/w3-engineers/telemesh
* Build URL (if applicable): https://readthedocs.org/projects/telemesh/builds/12294044/
* Read the Docs username (if applicable): W3-Anjan 

## Expected Result

If the local build is successful, then the badge would be also success

## Actual Result

On Github home page read the docs badge is failing

**Comment by humitos** [comment]
I remember we had a similar case already: #3323

However, it seems that we fixed it by adding the `max-age=0` and `no-cache`. Now it is back for some reason?

**Comment by W3-Anjan** [comment]
@humitos  thanks for your reply. 
I have reviewed the ticket, you mentioned. So it's a problem from GitHub, right?

**Comment by humitos** [comment]
Probably?

If you go to the Read the Docs' project page, https://readthedocs.org/projects/telemesh/ you will see the correct badge in green as well as if you request that file directly: https://readthedocs.org/projects/telemesh/badge/?version=latest

So, we are returning the correct badge from our side and we are communicating that it shouldn't be cached. I'm not sure if there is something else we can do.

**Comment by W3-Anjan** [comment]
thanks a lot, @humitos. 
The link works well
