### ISSUE TITLE
Disable --use-feature 2020-resolver for onap-* builds

### ISSUE THREAD

**Issue by jwagantall** [readthedocs/readthedocs.org#7654]
Dear RTD team, 

Can someone please help us disabling this feature for our builds under the "onap-rtd" account?
I noticed some were selected to run randomly this feature but they are failing. For example:
https://readthedocs.org/projects/onap-doc/
https://readthedocs.org/projects/onap-doc/builds/12283190/

Can we have all onap-* builds disabled for this feature please?

Thanks so much!
Jess

**Comment by stsewd** [comment]
Hi! I have removed all projects from that account from the sample using the new pip resolver https://readthedocs.org/projects/onap-doc/builds/12300174/

Remember that the new resolver will be enabled by default in the new release from pip (around November)
