### ISSUE TITLE
Not working with Google Analytics 4

### ISSUE THREAD

**Issue by bcb** [readthedocs/readthedocs.org#7662]
## Details

* Read the Docs project URL: https://jsonrpcserver.readthedocs.io/
* Build URL (if applicable):
* Read the Docs username (if applicable): beau

## Expected Result

Google Analytics 4 launched recently and I upgraded. Updated my GA code in both the RTD web UI and in conf.py, expecting to see stats.

## Actual Result

Getting zeroes in GA.

<img width="655" alt="Screen Shot 2020-11-12 at 7 48 26 pm" src="https://user-images.githubusercontent.com/134581/98917081-0c459500-2520-11eb-8857-3d19f38d2599.png">

**Comment by ericholscher** [comment]
Does your analytics code look like `UA-` or something different? I'm guessing we need a new JS client for the updated analytics.

**Comment by bcb** [comment]
Yes, the javascript for GA4 is here:
https://developers.google.com/analytics/devguides/collection/ga4

The `UA-` codes are the old ids, the new one starts with `G-`.

**Comment by JuanDCG** [comment]
I've the same problem, code start with `G-` and it doesn't works with it in RTD web UI and in conf.py.

Thanks for fixing the bug.

**Comment by davidfischer** [comment]
I am looking at this and I have a few bits to work out before we have a solution. In the current setup, Read the Docs attaches its own GA code as well as any user analytics code. Hopefully we can still support that. 

Other visitors can disable GA by using the do not track feature of their browser and project authors can disable GA entirely for their documentation. These features should still be supported.

* It looks like the new snippet supports the old (`UA-*`)and new (`G-*`) properties. Here's how to [add multiple codes](https://developers.google.com/gtagjs/devguide/add) and here's how to route events like [custom events](https://developers.google.com/gtagjs/devguide/routing).
* Read the Docs reduces the GA cookie time in the interest of privacy. It looks like [this](https://developers.google.com/gtagjs/devguide/cookies) is how that works.
* Here's the guide on [custom dimensions](https://developers.google.com/analytics/devguides/collection/gtagjs/custom-dims-mets). Read the Docs uses these to record things like the project slug and documentation type (Sphinx, MkDocs). Ideally these custom dimensions only apply to our analytics code.

**Comment by davidfischer** [comment]
I have a pending fix if any of the affected users would like to take a look: https://github.com/readthedocs/readthedocs.org/pull/7691

**Comment by stsewd** [comment]
@bcb the fix is live now, can you confirm is working for you?

**Comment by bcb** [comment]
Yes I’m seeing numbers now. 

One small note, you might want a separate field for each GA code, because I think 4 is meant to be able to run alongside the previous generation, so it’s possible someone might want to have both at once. But for me, I just went straight to using 4.

Thanks for resolving!
