### ISSUE TITLE
No module named 'nbsphinx'

### ISSUE THREAD

**Issue by aaronmarkham** [readthedocs/readthedocs.org#7665]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/sagemaker-examples/
* Build URL (if applicable): https://readthedocs.org/projects/sagemaker-examples/builds/12335396/
* Read the Docs username (if applicable): awsml

## Expected Result

A successful build using nbsphinx.
This worked 3 weeks ago on a different branch, but I just merged to master and the new build didn't work.

## Actual Result
```
Collecting nbsphinx==0.7.1
  Downloading nbsphinx-0.7.1-py3-none-any.whl (24 kB)
```
So it gets the module when preparing the container...
But when Sphinx is running later it gets this error:
`Could not import extension nbsphinx (exception: No module named 'nbsphinx')`

This points to my environment file:
https://github.com/aws/amazon-sagemaker-examples/blob/website/.readthedocs.yml

Which is here:
https://github.com/aws/amazon-sagemaker-examples/blob/website/environment.yml#L3
Where I specify `nbsphinx`

**Comment by aaronmarkham** [comment]
I reran the build using the old branch that was working before and that also failed. 
I can run the build locally with either branch, and it works fine.

**Comment by aaronmarkham** [comment]
I moved nbsphinx into the conda dependencies instead of pip and the build worked. I also have sphinx pinned to an earlier version, but it isn't respecting that... it is using 3.2.1 instead of what I have in there - 3.1.1.

I think this is a bug.

**Comment by swaldhoer** [comment]
This is the same issue as reported in #7663

**Comment by aaronmarkham** [comment]
> This is a little bit like #7663. However, as mentioned in my comment #7663, I use conda instead of pip and it does not help.

I looked at your build logs and it is the same behavior. You have `sphinx_copybutton` in your environment and it installs it, but then it isn't found later in the pipeline. It's like it builds the env, but then uses something else.

**Comment by swaldhoer** [comment]
Then it would good to know why using conda solved your problem, bur not mine. Maybe I dig into this sometimes on the weekend.

**Comment by stsewd** [comment]
@aaronmarkham see https://github.com/readthedocs/readthedocs.org/issues/3829 for that problem.

**Comment by stsewd** [comment]
I'll keep open the other issue to track the other problem with the import error

**Comment by aaronmarkham** [comment]
> I'll keep open the other issue to track the other problem with the import error

The core issue I had was the pip problem - it was installing nbsphinx and not finding it later. I don't know why moving nbsphinx to conda would work, but it did. This isn't a viable solution for everyone or every dependency though. I'm concerned that there is still a bug here, and if I require a pip package that's not on conda too, I'll be stuck.

3829 explains why it didn't load v3.1.1 of Sphinx though... this is more of an annoyance... the pip problem is kind of a big deal.

**Comment by stsewd** [comment]
I was referring to https://github.com/readthedocs/readthedocs.org/issues/7663

**Comment by NEGU93** [comment]
In case it works for someone... I also had this problem and I installed everything with conda. I fixed it by updating sphinx. 
`sphinx                                         3.1.2-py_0 --> 3.4.3-pyhd3eb1b0_0`
My `nbsphinx` version was: `nbsphinx           conda-forge/noarch::nbsphinx-0.8.0-pyhd3deb0d_0`
