### ISSUE TITLE
new branches don't appear in versions

### ISSUE THREAD

**Issue by aaronmarkham** [readthedocs/readthedocs.org#7682]
## Details

I checked the webhook and I can see the new branch was reported, but it isn't appearing in the list of versions, so I can't activate it. What am I missing here?

## Expected Result

When I push a branch, it appears in this of inactive versions.

## Actual Result

Branches seem to be stale... just as they were when I imported the repo, despite having a webhook setup.

**Comment by stsewd** [comment]
@aaronmarkham can you please link me to the rtd project?

**Comment by aaronmarkham** [comment]
> @aaronmarkham can you please link me to the rtd project?

https://sagemaker-examples.readthedocs.io/en/latest/index.html#

**Comment by stsewd** [comment]
I can see all branches from your repo are there https://github.com/aws/amazon-sagemaker-examples/branches/all https://readthedocs.org/projects/sagemaker-examples/versions/

If you can't see it, can you be more specific about what branch is missing?
