### ISSUE TITLE
Duplicated build error?

### ISSUE THREAD

**Issue by Arthurdw** [readthedocs/readthedocs.org#7685]
## Details

When I tried to let readthedocs generate my documentation

## Expected Result

Let it successfully build the documentation and put it online.

## Actual Result

I just got a message that said `Duplicated build`

## Useful links

* [ReadTheDocs Build Url](https://readthedocs.org/projects/dblstats/builds/12386773/)  
* [Docs folder](https://github.com/Arthurdw/dblstats/tree/master/docs)  
* [Read the docs YML](https://github.com/Arthurdw/dblstats/blob/master/.readthedocs.yml)

**Comment by Arthurdw** [comment]
I had to add `docs` as a requirement.

**Comment by conqp** [comment]
I have the same issue building a project. Where did you add this requirement?
