### ISSUE TITLE
Please set DONT_SHALLOW_CLONE for kpi-reporter

### ISSUE THREAD

**Issue by diurnalist** [readthedocs/readthedocs.org#7688]
## Details

This project uses `reno` to generate release notes, which relies on Git history.

* Read the Docs project URL: https://kpi-reporter.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/kpi-reporter/builds/12395873/
* Read the Docs username (if applicable): diurnalist

**Comment by humitos** [comment]
Done!

**Comment by diurnalist** [comment]
@humitos thank you kindly for the quick action!
