### ISSUE TITLE
RtD only recognizes the master branch

### ISSUE THREAD

**Issue by GVieirao** [readthedocs/readthedocs.org#7693]
## Build version fails without the master branch

'Main branch' isn't recognized as the principal branch, and building only works when i create a new branch called master (github recently changed the naming pattern for new repositories).

## Raw file:

Read the Docs build information
Build id: 12405729
Project: readthedocsexemplo
Version: latest
Commit: None
Date: 2020-11-23T21:34:09.772018Z
State: finished
Success: False

[rtd-command-info] start-time: 2020-11-23T21:34:11.689804Z, end-time: 2020-11-23T21:34:12.814915Z, duration: 1, exit-code: 0
git clone --no-single-branch --depth 50 https://github.com/GVieirao/readthedocs.git .
Cloning into '.'...

[rtd-command-info] start-time: 2020-11-23T21:34:13.229696Z, end-time: 2020-11-23T21:34:13.323040Z, duration: 0, exit-code: 1
git checkout --force master
error: pathspec 'master' did not match any file(s) known to git.

**Comment by stsewd** [comment]
Hi, you need to go the admin settings of your project and change the default branch to main there. We have a solution for this that is going live tomorrow https://github.com/readthedocs/readthedocs.org/pull/7646.
