### ISSUE TITLE
Please change a specific project slug

### ISSUE THREAD

**Issue by hmpf** [readthedocs/readthedocs.org#7696]
A project that started out life as "aas" now has a new name and a package on PyPI: "[argus-server](https://pypi.org/project/argus-server/)". The existing rtd-link "https://readthedocs.org/projects/aas/" has not been deliberately spread. Would it be possible to change the project slug to "argus-server", with a resulting link "https://readthedocs.org/projects/argus-server/"? (Then we can finally add the rtd-badge to the README.)

See #5403.

**Comment by stsewd** [comment]
Hi, if the project is recent and you don't have anything important, you can just create a new project with the name you want and delete the old project.

**Comment by hmpf** [comment]
How do I delete the old project?

**Comment by hmpf** [comment]
Found it, hard to spot.
