### ISSUE TITLE
Change default github branch from master to main

### ISSUE THREAD

**Issue by patel-zeel** [readthedocs/readthedocs.org#7706]
It fails when I leave the field of the default branch empty.

**Comment by stsewd** [comment]
Hi, if you leave it empty, it will default to master, you'll need to change it to main. When importing a project, you can change this in the advanced options 
![Screenshot_2020-11-30 Add a Project Read the Docs](https://user-images.githubusercontent.com/4975310/100626325-b29ce300-32f3-11eb-9922-7f26c9cc79ee.png)


With https://github.com/readthedocs/readthedocs.org/pull/7702 you won't need to change that manually, but it will take the one defined in your repository.
