### ISSUE TITLE
branch builds for pull requests are cached for 1 hour which is too long

### ISSUE THREAD

**Issue by mmerickel** [readthedocs/readthedocs.org#7708]
I enabled branch builds for the pyramid project (https://readthedocs.org/projects/pyramid/) and it's awesome except that the result is cached for an hour via `cache-control: public, max-age=3600`. When pushing updates to the branch it's really hard to view the docs improvements after a successful build.

I suggest turning off caching for branch builds or lowering it to only a minute or 5.

**Comment by ericholscher** [comment]
This should be fixed now, please confirm it looks better.

**Comment by mmerickel** [comment]
Good stuff, I think this is working. Thank you for such a quick turnaround!!

**Comment by ericholscher** [comment]
Glad to hear it 👍
