### ISSUE TITLE
/en/latest is a dead page

### ISSUE THREAD

**Issue by srcarter3** [readthedocs/readthedocs.org#7713]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/python-awips/
* Build URL (if applicable): 
* Read the Docs username (if applicable):

## Description

We recently changed our documentation host from readthedocs to github pages, and I've created a redirect page when you visit https://python-awips.readthedocs.io/.  Unfortunately, one of the top links that comes up when I search for "python-awips" is this url: https://python-awips.readthedocs.io/en/latest/ and it results in a "Sorry, this page does not exist yet" message.
I tried setting up a an "Exact Redirect" from https://python-awips.readthedocs.io/en/latest/ to https://python-awips.readthedocs.io/ in the "Admin" > "Redirects" settings page, but that doesn't seem to work.
Is there some other way I can get https://python-awips.readthedocs.io/en/latest/ to land on the redirect page I have set up for https://python-awips.readthedocs.io/?

## Expected Result
https://python-awips.readthedocs.io/en/latest/ will land at the redirect page for our new documentation link

## Actual Result
https://python-awips.readthedocs.io/en/latest/ is a "page does not exist yet" webpage

**Comment by stsewd** [comment]
Please try this exact redirect: `/en/latest` -> `https://python-awips.readthedocs.io`

**Comment by srcarter3** [comment]
Okay, I thought that might be the case...
I just added that as an exact redirect.   Do I have to rebuild the project or anything for it to take effect?  (It still is landing on the same page, currently).

**Comment by stsewd** [comment]
I have changed your redirect to be `/en/latest/` (note the final /). Now https://python-awips.readthedocs.io/en/latest and https://python-awips.readthedocs.io/en/latest/ redirect correctly. But I think what you really want is `/en/latest/$rest` so any URL gets redirected. But that will redirect  https://python-awips.readthedocs.io/en/latest/foo to https://python-awips.readthedocs.io/foo.

You can also just redirect to https://unidata.github.io/python-awips.

**Comment by srcarter3** [comment]
Great, thank you!
