### ISSUE TITLE
The docs styling breaks on readthedocs.io but not when built manually

### ISSUE THREAD

**Issue by tandemdude** [readthedocs/readthedocs.org#7720]
## Details

Read the Docs project URL:
https://readthedocs.org/projects/hikari-lightbulb/

Build URL (if applicable):
https://readthedocs.org/projects/hikari-lightbulb/builds/12463485/

Read the Docs username (if applicable):
tandemdude

## Expected Result

The built documentation should look like this: https://tandemdude.gitlab.io/lightbulb

## Actual Result

The documentation seems to be missing assets and/or fonts causing it not to render correctly.

I have tried putting all the assets from built documentation into the `_static` folder but that did not fix it.

**Comment by humitos** [comment]
Hi! I don't see any different in the pages. Could you please link a specific difference on both sites?

**Comment by tandemdude** [comment]
Apologies, seems like it may have been an issue with my browser caching a previous version of the webpage.
Sorry about this 😅
