### ISSUE TITLE
readthedocs cannot handle recursive dependencies

### ISSUE THREAD

**Issue by dizcza** [readthedocs/readthedocs.org#7721]
## Details

* Read the Docs project URL: failed to build
* Build URL (if applicable): https://readthedocs.org/projects/elephant-docs-development/builds/12469513/
* Read the Docs username (if applicable): dizcza
* readthedocs.yml: https://github.com/INM-6/elephant/blob/89ec31407818ea6fb0732d1f39855fc6bce0d2fc/readthedocs.yml#L21

## Expected Result

readthedocs installed the dependencies

## Actual Result

Recursive error (see the build logs).

## More info

Elephant `requirements/requirements-tutorials.txt` contains a line `viziphant @ git+https://github.com/INM-6/viziphant.git` but viziphant, in turns, requires `elephant[extras]` package. Such a recursive dependency breaks the readthedocs.

**NOTE**. I can easily install `pip install .[extras,tutorials]`.

**Comment by humitos** [comment]
Isn't this a problem with the new pip's resolver?

**Comment by dizcza** [comment]
> Isn't this a problem with the new pip's resolver?

Huh? I'm not aware of any.

**Comment by stsewd** [comment]
This looks like a pip problem, maybe related to https://github.com/pypa/pip/issues/8713.

I'm not able to see what pip version your package is using from the logs, but I think you'll be able to replicate it locally in a clean conda environment.

**Comment by dizcza** [comment]
I think you can close the issue or link to the one, if you have any, that mentions an option to pass flags to pip install commands on RTD.

**Comment by stsewd** [comment]
I have commented how to use an older version of pip if needed https://github.com/pypa/pip/issues/9202#issuecomment-739993342 if using the legacy resolver is needed as well, we can try falling back to that.

**Comment by dizcza** [comment]
Thanks, I don't think though that allowing users to pass additional build flags is a good idea because of several reasons, starting from security issues up to the hell of supporting all ways users could run pip or any other build package command.

**Comment by Btrfly79** [comment]
Ok, can someone help me fix it when I get my new computer?  I can't do anything on my phone....even if I could he'll stop me.  I just got this alert from apple it's metsadata in my map.   I'm keeping my phone insecure so they can get as much info as possible before I get my new phone
