### ISSUE TITLE
Transfer a project to its new owner

### ISSUE THREAD

**Issue by germainlefebvre4** [readthedocs/readthedocs.org#7729]
## Details

* Read the Docs project URL: https://libtado.readthedocs.io/
* Build URL (if applicable):
* Read the Docs username (if applicable): 
   * old: ekeih
   * new: germainlefebvre4
* Github repo : 
   * old: https://github.com/ekeih/libtado (that is archived)
   * new: https://github.com/germainlefebvre4/libtado

## Expected Result

I want the rtd project `libtado `owned by me : germainlefebvre4

## Actual Result

The rtd project `libtado `is owned by the old one : ekeih

**Comment by stsewd** [comment]
@germainlefebvre4 have you tried contacting the user? You need to that before we can start with https://docs.readthedocs.io/en/stable/abandoned-projects.html

**Comment by germainlefebvre4** [comment]
Sure I tried to reach him but no sound heared for a whole year.

**Comment by stsewd** [comment]
I have contacted the user today.

/remind me about take action on this project in 6 weeks

**Comment by stsewd** [comment]
No bot?

/remind me about take action on this project in 6 weeks

**Comment by germainlefebvre4** [comment]
Ekeih just reply to my last message after you ping him 
He told me it is ok

**Comment by stsewd** [comment]
@germainlefebvre4 I have added you as owner https://readthedocs.org/profiles/germainlefebvre4/, you can remove the old owner from the admin panel if you wish.
