### ISSUE TITLE
Allow to modify versions listed in the selector

### ISSUE THREAD

**Issue by doctorcolinsmith** [readthedocs/readthedocs.org#7732]
I would like to define my own orderings for versions.  Currently, if the branch names contain letters, they sort alphabetically.

For example, if I have branches foo-2.8.0, foo-2.9.0, and foo-2.10.0, they appear in the side bar as foo-2.9.0, foo-2.8.0, foo-2.10.0.  That is, the most recent release branch appears last.

Ideally, it would be great if we could supply a regex and set the orderings on the regex groups.

For a live example, please see the side bar on https://rocfft.readthedocs.io/en/latest/

**Comment by stsewd** [comment]
I think this is better implemented having the footer api returning a json instead of a html block, that way users can use their own order/style to display the versions. We are discussing this feature internally, but I think @ericholscher was about to create a public issue, we can close this one that one is created.

**Comment by doctorcolinsmith** [comment]
I think that is a reasonable proposal @stsewd.  I have not yet tried to do any customization with the footer API, but I can look at that more.

**Comment by humitos** [comment]
This is going to be supported by our new Flyout Addon we are working on at https://github.com/readthedocs/addons/ where people would be able to use the exact same data we will use to build our flyout to build their own.

**Comment by humitos** [comment]
I worked on an implementation to be able to define the sorting algorithm in https://github.com/readthedocs/readthedocs.org/pull/11069. This allow users to choose different approaches or define their own pattern. @doctorcolinsmith would that approach solve your issue? I'd appreciate your feedback.

**Comment by doctorcolinsmith** [comment]
Thanks @humitos.  On first review, this looks like a good solution.  I will pass this on to our doc team.

**Comment by humitos** [comment]
A feature to sort versions in the beta addons flyout was released today. To enable this feature, you will need to activate the new beta addons in your project first, and then edit the sorting from the project's setting using the new beta dashboard from https://beta.readthedocs.org/. Please, let me know any feedback you may have 🙏🏼 

![Screenshot_2024-03-12_16-36-16](https://github.com/readthedocs/readthedocs.org/assets/244656/846146ad-5b30-4240-9d08-901ef56232df)
