### ISSUE TITLE
API requires trailing slash (`/`)

### ISSUE THREAD

**Issue by domdfcoding** [readthedocs/readthedocs.org#7744]
## Details

* Read the Docs project URL: https://shippinglabel.readthedocs.org
* Build URL (if applicable): n/a
* Read the Docs username (if applicable): domdfcoding

## Expected Result

Making a PATCH request to the `readthedocs.org/api/v3/projects/shippinglabel` endpoint would update the project metadata.

An example of my intended usage:

```python
import requests

r = requests.patch(
        "https://readthedocs.org/api/v3/projects/shippinglabel",
        json={
            "tags": ["python", "packaging", "pypi", "requirements"],
            "homepage": "https://github.com/domdfcoding/shippinglabel",
            },
        headers={"Authorization": f"Token {token}"})

print(r)  # <Response [204]>
```

## Actual Result

Although the API responds with the expected `204` status code, the changes aren't visible on subsequent API calls or on the project's settings page.

**Comment by humitos** [comment]
Hi! Thanks for the report!

This is weird, we have a test case for this case in particular and it's passing :sweat_smile:, https://github.com/readthedocs/readthedocs.org/blob/0ff60a3cc9ed526d7065864c57d872999b0e4dc3/readthedocs/api/v3/tests/test_projects.py#L237-L262

However, I just tested this by myself using `curl` and I had the same problem:

```
▶ curl -X PATCH -H "Authorization: Token ${TOKEN}" --data '{"homepage": "https://example.org"}' https://readthedocs.org/api/v3/projects/blog-humitos/

~                                                                                                                                                                                                                                                                             
▶ curl --silent -X GET -H "Authorization: Token ${TOKEN}" https://readthedocs.org/api/v3/projects/blog-humitos/ | jq .homepage              
"https://elblogdehumitos.com"
```

I will take a deeper look to see what's happening.

**Comment by humitos** [comment]
BTW, `tags` is not a valid field and can't be updated via the API currently.

**Comment by humitos** [comment]
@domdfcoding found the issue! you are not sending the header `"Content-Type: application/json"`. Please, try that and let me know.

It's on the documentation for BASH, https://docs.readthedocs.io/en/stable/api/v3.html#project-update but it's not in the Python tab :/

**Comment by stsewd** [comment]
Hmm, I imagine `requests` would send that header when using the json field.

**Comment by domdfcoding** [comment]
Ok, I've looked into this some more and it seems to come down to a lack of a forward slash `/` at the end of the URL. I wasn't including one, but the examples in the docs do. I added the trailing slash and suddenly it worked! I guess the server's being picky about the trailing slash.

It still works even if I include the `tags` field, so I assume the server just silently ignores it. It also works if I omit the `Content-Type` header, so I think @stsewd is correct and `requests` includes it automatically.

I'd like to add a list of fields that can be updated to the docs, as I can't see one. Are these the only ones that can be?

https://github.com/readthedocs/readthedocs.org/blob/6c161f89c4de7dce2b423609a38e15d8ab692122/readthedocs/api/v3/serializers.py#L479-L492

**Comment by Btrfly79** [comment]
He's on my phone I can't use the code my computer is being fixed

**Comment by Btrfly79** [comment]
https://semver.org/

**Comment by Btrfly79** [comment]
![image](https://user-images.githubusercontent.com/74492878/101870056-f201d580-3b24-11eb-9dd2-356327d268a4.png)

**Comment by Btrfly79** [comment]
He's using bootstrap and JQuery versions are according to smserver

**Comment by humitos** [comment]
Hi @domdfcoding! Yes those are the fields that you can edit via the API currently.

**Comment by stsewd** [comment]
I think we should add the trailing / automatically, maybe we just need to set a setting in DRF or modify the URLs.

**Comment by stsewd** [comment]
So, looks like there is an option https://www.django-rest-framework.org/api-guide/routers/ (`trailing_slash=False`) but then URLs with slash don't work. I get a 301 response when hitting a URL with no slash, I think that's how it should behave.

```
$ http PATCH https://readthedocs.org/api/v3/projects/test-builds "Authorization:Token {token}" < test.json

HTTP/1.1 301 Moved Permanently

```
