### ISSUE TITLE
Make our documentation page APIs more user friendly

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#7748]
This issue is a bit of a meta issue, but it also has at least one concrete action associated with it.

### The high level

We want to make it easier for theme authors to integrate the information in our flyout into their themes, which means giving hooks into the information. The most commonly used data here is:

* Active versions
* Translations
* Downloads (PDF, HTML, Epub)
* View/Edit on GitHub links

### Short term work

The most obvious place to focus in the short term is breaking out our monolithic "footer API" into something more usable by users. Currently this API returns rendered HTML with the data instead, along with a few additional JSON details. It doesn't include in JSON the actual data used to render the HTML.

So I imagine the steps towards transition are:

* Add additional JSON data to the current response
* Migrate our code to use this new JSON data structure
* Remove the existing HTML data structure after a deprecation period

I don't believe many users are currently using this structure, but I do know some people have custom CSS on top of it, so we should try and not alter the final HTML output if we can avoid it. 

##### Current response

![Screen Shot 2020-12-14 at 9 10 27 AM](https://user-images.githubusercontent.com/25510/102112189-37a3f400-3dec-11eb-876b-820cfcdced87.png)

##### Current flyout

![Screen Shot 2020-12-14 at 9 12 43 AM](https://user-images.githubusercontent.com/25510/102112432-88b3e800-3dec-11eb-9eff-414b4dc5ead8.png)

### Longer term vision

Once we are returning the JSON data, we need to find a pattern for theme authors to "hook" into this data with Javascript. I think there are a few different approaches to this, and I don't know what the best option would be. I just want to note that is probably the "v2" after we migrate to using the JSON data approach is actually exposing that data to users in a standard way.

Refs #7732

**Comment by humitos** [comment]
I'm commenting on this issue to bump it up in your inboxes since it may be a good addition to 2023 roadmap.

This issue is also related to:

* https://github.com/readthedocs/readthedocs.org/pull/8052
* https://github.com/readthedocs/readthedocs.org/issues/9063
* https://github.com/readthedocs/readthedocs.org/pull/9357

**Comment by ericholscher** [comment]
Yea, this is definitely defining the problem pretty effectively, thanks for digging it up :)
