### ISSUE TITLE
build killed as a result of https://github.com/pypa/pip/issues/9284

### ISSUE THREAD

**Issue by cjw296** [readthedocs/readthedocs.org#7752]
## Details

* First Build that broke: https://readthedocs.org/projects/testfixtures/builds/12564243/

## Expected Result

Build as it did 4 days ago, no config changes on the project side:
https://readthedocs.org/projects/testfixtures/builds/12537398/

## Actual Result

Looks like the build is now trying to download every version of every library in my project's dependencies.

I think i've found the reason:

```
/home/docs/checkouts/readthedocs.org/user_builds/testfixtures/envs/latest/bin/python -m pip install --upgrade --no-cache-dir pip
Requirement already satisfied: pip in /home/docs/checkouts/readthedocs.org/user_builds/testfixtures/envs/latest/lib/python3.7/site-packages (20.3.1)
Collecting pip
  Downloading pip-20.3.2-py2.py3-none-any.whl (1.5 MB)
WARNING: The candidate selected for download or install is a yanked version: 'pip' candidate (version 20.3.2 at https://files.pythonhosted.org/packages/3d/0c/01014c0442830eb38d6baef0932fdcb389279ce74295350ecb9fe09e048a/pip-20.3.2-py2.py3-none-any.whl#sha256=8d779b6a85770bc5f624b5c8d4d922ea2e3cd9ce6ee92aa260f12a9f072477bc (from https://pypi.org/simple/pip/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*))
Reason for being yanked: <none given>
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.3.1
    Uninstalling pip-20.3.1:
      Successfully uninstalled pip-20.3.1
Successfully installed pip-20.3.2
```

Not sure why pip is upgrading itself to a version it knows is bad, is there anything that can fix this on the RTD side?

**Comment by cjw296** [comment]
This looks like the problem with 20.3.2: https://github.com/pypa/pip/issues/9284

**Comment by cjw296** [comment]
I've logged https://github.com/pypa/pip/issues/9287 to report this on the pip side: https://github.com/pypa/pip/issues/9287

**Comment by stsewd** [comment]
Hi, we install the latest version of pip by default, you can set the version of pip to be installed using a config file https://docs.readthedocs.io/en/stable/config-file/v2.html#python

```yaml
version: 2

python:
  version: 3.7
  install:
    - requirements: docs/pip.txt
    - requirements: docs/requirements.txt
```

Where pip.txt has `pip==20.3.1` or whatever version you need.

**Comment by stsewd** [comment]
Looks like a new release will be out soon https://github.com/pypa/pip/issues/8936#issuecomment-745355547
