### ISSUE TITLE
Add scroll bar to side bar

### ISSUE THREAD

**Issue by rvernica** [readthedocs/readthedocs.org#7767]
## Details

The sidebar has not scroll bar. I guess the main way to scroll over it is using the mouse wheel. For users without a mouse wheel, there does not seem to be way to scroll it with the mouse. 

It is possible to scroll it with the keyboard but only if the sidebar is active (in Firefox at least). To make the side bar active you have to click on the sidebar. But the sidebar is 90% covered with links so clicking would mean loading a different page and still the side-bar won't be active. One has to find the 10% which is not covered by links in order to activate the side bar and then use the keyboard to scroll over it.

I scroll bar on the sidebar would be very useful.

**Comment by stsewd** [comment]
Hi, this is an issue of the theme, there are several issues related to this there https://github.com/readthedocs/sphinx_rtd_theme/issues/818 https://github.com/readthedocs/sphinx_rtd_theme/issues/824 https://github.com/readthedocs/sphinx_rtd_theme/issues/1015
