### ISSUE TITLE
 can't install local version, SQLite error

### ISSUE THREAD

**Issue by SerhiiZahuba** [readthedocs/readthedocs.org#7769]
I follow the instructions from https://docs.readthedocs.io/en/stable/development/install.html but after the command python manage.py migrate I see an error
django.core.exceptions.ImproperlyConfigured: SQLite 3.8.3 or later is required (found 3.7.17)
in pip.txt I did not find where to fix the SQLite version. help please

**Comment by SerhiiZahuba** [comment]
Really complex system setup. Many packages need to be installed from their sources. (I am using regular Centos 7 with all updates). I was unable to install with standard packages. I will try to find another system with similar properties.

**Comment by humitos** [comment]
Hi @SerhiiZahuba! The documentation that you linked is deprecated and we should probably remove it from our docs. We are using this setup since a year ago or so: https://docs.readthedocs.io/en/stable/development/standards.html. Please take a look at that one and let us know.

**Comment by SerhiiZahuba** [comment]
Perhaps you have recommendations for the system?
I am using the usual centos 7, in the standard repositories there are not all programs that require "readthedocs.org". For example for sqllite, I only found the package at https://kojipkgs.fedoraproject.org//packages/sqlite/3.8.11/1.fc21/x86_64/sqlite-3.8.11-1.fc21.x86_64.rpm. glibc requires 2.18 only - I tried it via https://www.rpmfind.net/linux/rpm2html/search.php?query=glibc to download packages but they didn't help

**Comment by humitos** [comment]
I'm using Arch. Other devs are using MacOS and we use Ubuntu in production. However, I strongly recommend you to use our development setup that uses Docker and runs in all those systems without issues.

Please, try that and open another issue if you find a problem with that setup.
