### ISSUE TITLE
Increase memory for gmic-py project

### ISSUE THREAD

**Issue by myselfhimself** [readthedocs/readthedocs.org#7775]
## Details

When I try to build tutorials.rst for the gmic-py open source project, I face a "Command killed due to excessive memory consumption" after several G'MIC run calls (Python/C++ calls using a single G'MIC language interpreter instance)

* Read the Docs project URL: gmic-py.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/gmic-py/builds/12614497/
* Read the Docs username (if applicable): myselfhimself

## Expected Result

No crash because there is enough memory allowed. Building on my local old T400 laptop works with 7 Go RAM works.

*A description of what you wanted to happen*

I lack time tonight to determine the exact max RAM size needed by my docs/ build process.
What I have is, maybe a 2.7GB need.
```
(gmicpy290numpy) jd@jd-ThinkPad-T400:~/Productions/GMIC/gmic-py$ /usr/bin/time -v bash build_tools.bash 6b_make_doc_without_c_recompilation tutorials.rst |& grep resident
	Maximum resident set size (kbytes): 2637520
	Average resident set size (kbytes): 0
```

## Actual Result

Build does not continue with "Command killed due to excessive memory consumption" error amid the tutorials.rst build.

**Comment by humitos** [comment]
Hi @myselfhimself! The builder where your project is building on RTD is 4Gb. I moved your project to a 8Gb builder, and triggered another build https://readthedocs.org/projects/gmic-py/builds/12617168/

Feel free to reopen if the issue is not solved.

**Comment by myselfhimself** [comment]
You are marvellous, thank you!

út 22. 12. 2020 v 10:14 odesílatel Manuel Kaufmann <notifications@github.com>
napsal:
