### ISSUE TITLE
Use a unique callback for footer jsonp callback

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#7779]
We just edited the callback name to be `callback` recently, which could overlap with an existing function `callback()` that exists in the user documentation. We don't need to use a generated name, but we should use something more guaranteed to be unique in order to avoid overwriting a user function, or calling a user function on jsonp callback.

**Comment by stsewd** [comment]
We allow CORS for public versions and always use the proxied apis now, I think we can finally ditch jsonp now.

**Comment by humitos** [comment]
This is not required anymore since we are migrating our footer API to the new addons (https://github.com/readthedocs/addons/)
