### ISSUE TITLE
Add documentation on using SSH keys and importing manually

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#7780]
Our docs don't mention how to manually manage project SSH keys for commercial hosting. We should cover the following:

- [ ] How to use your SSH key on
    - [ ] GitHub
    - [ ] Gitlab
    - [ ] Bitbucket

Additionaly, the new theme will re-enable manual project creation as a default option, but with heavy warnings about manual creation on our commercial hosting. It would be helpful to cover the entire process:

- [ ] Precautions to cloning manually
- [ ] How to start creation of your project -- form walkthrough
- [ ] Explain manual webhook creation needs and point to webhook docs
- [ ] Explain SSH key needs and point to :point_up: docs

Blocking this on release of theme first. We'll want to be able to describe the UI or at least some screen grabs of the UI.

**Comment by stsewd** [comment]
There is mention on how to add the ssh key for the supported providers at https://docs.readthedocs.io/en/stable/guides/private-submodules.html we can use that as reference for the new document.

**Comment by agjohnson** [comment]
I think this documentation was written already. I know we have some directions for Azure/etc now. Can this be closed?

**Comment by astrojuanlu** [comment]
https://docs.readthedocs.io/en/stable/guides/private-submodules.html closing!
