### ISSUE TITLE
Recommonmark pinned at 0.5.0 when 0.6.0 or greater desired

### ISSUE THREAD

**Issue by liamtoney** [readthedocs/readthedocs.org#7789]
## Details

* Read the Docs project URL: [https://readthedocs.org/projects/lsforce/](https://readthedocs.org/projects/lsforce/)
* Build URL (if applicable): [https://readthedocs.org/api/v2/build/12663241.txt](https://readthedocs.org/api/v2/build/12663241.txt)
* Read the Docs username (if applicable): liamtoney

## Expected Result

Recommonmark >= 0.6.0 installed, to avoid [Markdown parsing issues with alt text](https://github.com/readthedocs/recommonmark/pull/150).

## Actual Result

Recommonmark 0.5.0 installed

## Description

There was an issue with Markdown image alt text that was fixed in Recommonmark 0.6.0. However, RTD seems to be pinning Recommonmark at 0.5.0 according to my build logs (see snippet below). This results in Markdown errors when alt text is used.
```
/home/docs/checkouts/readthedocs.org/user_builds/lsforce/envs/rtd/bin/python -m pip install --upgrade --no-cache-dir setuptools==41.0.1 docutils==0.14 mock==1.0.1 pillow==5.4.1 alabaster>=0.7,<0.8,!=0.7.5 six commonmark==0.8.1 recommonmark==0.5.0 sphinx sphinx-rtd-theme readthedocs-sphinx-ext<2.2
```
I looked around to see if I could pin a higher Recommonmark version myself, but I couldn't find any info. Thanks in advance.

**Comment by stsewd** [comment]
@liamtoney you can specify any version with a requirements file https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

Related to https://github.com/readthedocs/readthedocs.org/issues/5201 and https://github.com/readthedocs/readthedocs.org/issues/2483

**Comment by liamtoney** [comment]
Great, thank you very much @stsewd. If it helps others, the contents of my `doc/requirements.txt` now look like:
```
sphinxcontrib-apidoc
recommonmark>=0.6.0
```
