### ISSUE TITLE
Could not import extension sphinx.builders.applehelp

### ISSUE THREAD

**Issue by fepegar** [readthedocs/readthedocs.org#7790]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/torchio/
* Build URL (if applicable): https://readthedocs.org/projects/torchio/builds/12670593/
* Read the Docs username (if applicable): fepegar

## Expected Result

Successful build as usual.

## Actual Result

The last build failed with this message:

```
python /home/docs/checkouts/readthedocs.org/user_builds/torchio/envs/latest/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html
```

```python-traceback
Running Sphinx v1.8.5
loading translations [en]... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/torchio/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 472, in load_extension
    mod = __import__(extname, None, None, ['setup'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/torchio/envs/latest/lib/python3.7/site-packages/sphinx/builders/applehelp.py", line 20, in <module>
    from sphinx.builders.html import StandaloneHTMLBuilder
  File "/home/docs/checkouts/readthedocs.org/user_builds/torchio/envs/latest/lib/python3.7/site-packages/sphinx/builders/html/__init__.py", line 33, in <module>
    from sphinx.domains import Domain, Index, IndexEntry
ImportError: cannot import name 'IndexEntry' from 'sphinx.domains' (/home/docs/checkouts/readthedocs.org/user_builds/torchio/envs/latest/lib/python3.7/site-packages/sphinx/domains/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/torchio/envs/latest/lib/python3.7/site-packages/sphinx/cmd/build.py", line 303, in build_main
    args.tags, args.verbosity, args.jobs, args.keep_going)
  File "/home/docs/checkouts/readthedocs.org/user_builds/torchio/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 224, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/torchio/envs/latest/lib/python3.7/site-packages/sphinx/application.py", line 449, in setup_extension
    self.registry.load_extension(self, extname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/torchio/envs/latest/lib/python3.7/site-packages/sphinx/registry.py", line 475, in load_extension
    raise ExtensionError(__('Could not import extension %s') % extname, err)
sphinx.errors.ExtensionError: Could not import extension sphinx.builders.applehelp (exception: cannot import name 'IndexEntry' from 'sphinx.domains' (/home/docs/checkouts/readthedocs.org/user_builds/torchio/envs/latest/lib/python3.7/site-packages/sphinx/domains/__init__.py))

Extension error:
Could not import extension sphinx.builders.applehelp (exception: cannot import name 'IndexEntry' from 'sphinx.domains' (/home/docs/checkouts/readthedocs.org/user_builds/torchio/envs/latest/lib/python3.7/site-packages/sphinx/domains/__init__.py))
```

Please let me know if you need any further information.

**Comment by fepegar** [comment]
Nevermind. I [wiped](https://docs.readthedocs.io/en/stable/guides/wipe-environment.html) and rebuilt and it seems fine now.

Many thanks for this wonderful project!

**Comment by fepegar** [comment]
I'm having this error consistently, so I'm reopening. I hope someone will get a notification!

**Comment by stsewd** [comment]
@fepegar are you able to build your docs locally?  Also, maybe the sphinx version `Running Sphinx v1.8.5` that is the version running on rtd, you can use any other version by specifying it in your requirements file.

**Comment by stsewd** [comment]
also, unrelated, you are using some features from the config file v2 in the v1

https://github.com/fepegar/torchio/blob/master/.readthedocs.yml

https://docs.readthedocs.io/en/stable/config-file/v2.html

See also https://docs.readthedocs.io/en/stable/config-file/v2.html#migrating-from-v1

**Comment by fepegar** [comment]
Thanks for replying. It works fine locally. I didn't quite get what you said about the Sphinx version.

I didn't know there was a new version for the config file. I'll migrate soon, then. Should I try again after migrating and let you know if that fixed it?

**Comment by stsewd** [comment]
@fepegar what I meant was to set sphinx to the same version you are using locally here https://github.com/fepegar/torchio/blob/master/docs/requirements.txt

**Comment by fepegar** [comment]
I modified that file, but I must have done something wrong because `Running Sphinx v1.8.5` shows up [in the latest build](https://readthedocs.org/projects/torchio/builds/12821252/).

**Comment by stsewd** [comment]
@fepegar sorry about that, looks like your project was using an experimental feature (caching the previous env), I have disabled it, and now should be using the version of sphinx from your requirements https://readthedocs.org/projects/torchio/builds/12821969/ https://readthedocs.org/projects/torchio/builds/12822026/

**Comment by fepegar** [comment]
Thanks for your help. And many thanks for RTD!!
