### ISSUE TITLE
Management command to trigger VCS provider data re-sync

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#7791]
Once we have the new `RemoteRepository` and `RemoteOrganization` modeling using `*Relation` models in production, we will need a management command to trigger the re-sync of this data.

Taking into account that we may hit rate limit API (*) we will need to do this in chunks and have some way to trigger re-sync with some filters

- re-sync only specific users: `--users humitos --users readthedocs`
- skip users: `--skip-users humitos`
- use a specific celery queue for the tasks (only the instance with new modeling will be listen to this queue): `--queue resync-oauth`
- limit the amount of tasks triggered: `--max-tasks 100`
- continue from an offset: `--offset 100`
- print total tasks required to complete and current position: `Re-syncing 100-199 / 60000`

(*) I'm not super worried about this since the rate limit is based on user, and it's 5k per user on GH, IIRC.

**Comment by saadmk11** [comment]
closed on https://github.com/readthedocs/readthedocs.org/pull/7803
