### ISSUE TITLE
Management command to export/load `Project -> RemoteRepository` relations

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#7806]
#7791 will help us to re-sync all the VCS data coming from GH, GL and BB. However, it won't re-sync the relations between `Project`s and `RemoteRepository`s.

We will need a command to export these relationships from our old table and import them into the new table. I'm imaging something like this:

```python
# Export query for current production database
Project.objects.filter(remote_repository__isnull=False).values('slug','remote_repository__full_name')  # about 38k records
```

```python
# Load code at the moment of doing the swap to `oauth_*_2020` tables
for project_slug, remote_repository__full_name in relations:
    project = Project.objects.get(slug=project_slug)
    remote_repository = RemoteRepository.objects.get(full_name=remote_repository__full_name)

    project.remote_repository = remote_repository
    project.save()
```

It may happen the `full_name` does not match in case it was updated in the VCS provider and not re-synced in our database. We could use `remote_repository__json__id` instead (or similar depending on the VCS provider) to be 100% sure.

**Comment by saadmk11** [comment]
I like the idea of using `remote_repository__json__id` as this is more robust approach and less likely to have issues. but we need to check if all the `RemoteRepository` objects have data in `json` field with `id`.

The looping might be really slow and put stress on the DB as it will do 3 queries per loop. So, for 38k projects, there will be 100k+ queries. I don't know many different ways to make it faster. But something like this may help a little bit to decrease the query count. @humitos Let me know what you think. :)

```python
for project_slug, remote_repository__full_name in relations:
    subquery = Subquery(
        Project.objects.filter(slug=project_slug).values('id')[:1]
    )
    RemoteRepository.objects.filter(
        full_name=remote_repository__full_name
    ).update(project=subquery)
```

**Comment by humitos** [comment]
> I like the idea of using `remote_repository__json__id` as this is more robust approach and less likely to have issues. but we need to check if all the `RemoteRepository` objects have data in `json` field with `id`.

:+1: --I think they all have the `json` field. We can give this a try, but I think it will be more complex.

> The looping might be really slow and put stress on the DB as it will do 3 queries per iteration

Yeah. The looping was the easiest way to describe what we need here.

Your proposal, will do only 2 queries per iteration, right? One for the `SELECT` (together with the subquery) and another one for the `UPDATE`?

Question, if instead of `project_slug` we save the `project_pk` when exporting can we remove the subquery by doing the following?:

```python
for project_pk, remote_repository__full_name in relations:
    RemoteRepository.objects.filter(
        full_name=remote_repository__full_name
    ).update(project_id=project_pk)
```

In the end, we are not changing `Project.id` (we are for `RemoteRepository`, that's why we need the `full_name` or `remote_id` here).

**Comment by saadmk11** [comment]
> Your proposal, will do only 2 queries per iteration, right? One for the `SELECT` (together with the subquery) and another one for the `UPDATE`?

Yes

> Question, if instead of `project_slug` we save the `project_pk` when exporting can we remove the subquery by doing the following?:
> 
> ```python
> for project_pk, remote_repository__full_name in relations:
>     RemoteRepository.objects.filter(
>         full_name=remote_repository__full_name
>     ).update(project_id=project_pk)
> ```
> 
> In the end, we are not changing `Project.id` (we are for `RemoteRepository`, that's why we need the `full_name` or `remote_id` here).

Yeah Good idea :100: , I think we can do that. :)

**Comment by humitos** [comment]
@saadmk11 did we already created this script? I only found #7803, but I think we didn't do this yet, right?

**Comment by humitos** [comment]
I just realized than besides `project_pk` and `remote_id` we could also save the `username` tied to the `RemoteRepository` from that relationship. This will allow us to _force_ a re-sync for those users in case we need to. For example, if the VCS re-sync for that user was done and after that the user imported a new project (unknown previously for us as: there is no `RemoteRepository` created for it).
