### ISSUE TITLE
Version warning does not appear as top banner

### ISSUE THREAD

**Issue by hugovk** [readthedocs/readthedocs.org#7809]
### Problem

Sometimes people read/link to old versions of our documentation and miss new features and changes.

For example, from a Google search for a module, I ended up at http://pillow.readthedocs.org/en/3.1.x/reference/ImageChops.html

RtD has a setting to help with this:

> ## Version warning
>
> This is a banner that appears on the top of every page of your docs that aren’t stable or latest. This banner has a text with a link redirecting the users to the latest version of your docs.
>
> This feature is disabled by default on new projects, you can enable it in the admin section of your docs (`Admin` > `Advanced Settings`).

[docs.readthedocs.io/en/stable/versions.html#version-warning](https://docs.readthedocs.io/en/stable/versions.html#version-warning)

However this is enabled at [readthedocs.org/dashboard/pillow/advanced](https://readthedocs.org/dashboard/pillow/advanced/) and whilst we *do* get a red bar on the version selector at the bottom left, there's no top banner with a redirect to the latest version:

![image](https://user-images.githubusercontent.com/1324225/102853555-3b0d3000-4429-11eb-860b-7b04cd958d1a.png)

### Reproducible Project

https://pillow.readthedocs.io/en/3.1.x/

#### Expected Results

I expect to see "a banner that appears on the top of every page of your docs that aren’t stable or latest. This banner has a text with a link redirecting the users to the latest version of your docs."

### Environment Info

- Python Version: 3.7
- Sphinx Version: 3.4.0
- RTD Theme Version: 0.4.3

**Comment by stsewd** [comment]
Looks like those versions are marked as `built`, but as inactive, that combination shouldn't exist... Maybe do you remember contacting support to allow to hide old versions from the footer? I think that may be the case (but that solution was a hack). We now support hidden versions that do that.

This could also maybe was an old bug that didn't delete the versions for some reason, in that case I can delete them manually for you. Let me know if you want that.

**Comment by fritzo** [comment]
@stsewd I'm seeing a similar issue with https://docs.pyro.ai: old versions used to appear red, but no longer appear red. This is causing confusion for our users https://github.com/pyro-ppl/pyro/issues/2816

**Comment by stsewd** [comment]
@fritzo I can see the warning banner at the top of all of your old versions, for example https://docs.pyro.ai/en/1.5.1/

**Comment by fritzo** [comment]
Apologies @stsewd I indeed see the top banner.  IIRC I had previously seen the version in the lower left as red for old versions as well, but I guess it is a top banner now.  Thanks.

**Comment by stsewd** [comment]
> I expect they'll sooner or later drop out of the Google index and (hopefully) be replaced with newer ones?

Yes, we also generate a robots.txt and sitemap with the current active versions https://pillow.readthedocs.io/robots.txt (looks like our sitemap code is broken :/ I'll take a look)

Anyway, I have deleted all files from your versions except from latest and stable. Let us know if you this happening again.

**Comment by RemDelaporteMathurin** [comment]
@stsewd @hugovk I think I'm experiencing the same issue, our [FESTIM project ](https://github.com/festim-dev/FESTIM) has several versions of the documentation on RTD. I believe there used to be the version warning banner on old versions but it doesn't appear anymore, see for example:

- https://festim.readthedocs.io/en/fenicsx/
- https://festim.readthedocs.io/en/v1.2/ 

Everything is ticked in the RTD dashboard:

![image](https://github.com/user-attachments/assets/b27dbfea-727c-4345-9e08-6c3a99b4807f)

**Comment by RemDelaporteMathurin** [comment]
I have the same problem for this project:

https://h-transport-materials.readthedocs.io/en/latest/

**Comment by RemDelaporteMathurin** [comment]
@stsewd just opened a new issue! :-) Thanks~
