### ISSUE TITLE
Version warning doesn't work with Material theme for MkDocs

### ISSUE THREAD

**Issue by reginapizza** [readthedocs/readthedocs.org#7810]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/regina-argocd-notifications/
* Build URL (if applicable): https://readthedocs.org/projects/regina-argocd-notifications/builds/
* Read the Docs username (if applicable): reginapizza

## Expected Result

I'm trying to have version warning labels set up for branches that are not stable nor latest (aka, one of my branches called 'regina-dev') . I'm using material theme for MkDocs. I went to Advanced Settings and checked the box for show version warning. I thought that this would give me a warning label somewhere on the page when I switched to my regina-dev branch in the version selector but it does not. When I go to other sites using RTD and switch older versions, I can see the version warning displayed, but I haven't seen one that does it with Material theme.

## Actual Result

No version warning appears. 

Is this just a limitation of the Material theme with MkDocs + RTD or am I just setting this up wrong? I've been able to implement this with `mike` versioning, [as shown in a PR here for anyone interested](https://github.com/argoproj/argo-cd/pull/5099), but my team would prefer to use RTD instead of `mike` because we prefer a service over a tool and have concerns about the maturity and upkeep with `mike`. Please let me know if this is possible or if you know of anyone who's gotten something like this to work... much appreciated and thanks for a great product!

**Comment by stsewd** [comment]
Hi @reginapizza, I think this is because your version name is `regina-dev`, so rtd doesn't know how to compare that version with the latest one. If you enable other version like `v0.2.2`, the banner should appear.

**Comment by stsewd** [comment]
So, I just remembered that the banner is only available for sphinx projects, sorry https://github.com/readthedocs/readthedocs-sphinx-ext/blob/master/readthedocs_ext/versionwarning.py.

Probably we should update the documentation.

**Comment by reginapizza** [comment]
Ah, that's too bad. Thanks for your help!

**Comment by stsewd** [comment]
> So, I just remembered that the banner is only available for sphinx projects, sorry https://github.com/readthedocs/readthedocs-sphinx-ext/blob/master/readthedocs_ext/versionwarning.py.

I was changing this code and realized I lied here... We don't use that extension, so it works for mkdocs and sphinx, but it requires jquery and a div with a `body` or `document` class (but we are going to change that to allow `role=main` or a `<main>` tag as well. https://github.com/readthedocs/readthedocs.org/pull/8079
