### ISSUE TITLE
Expose the PR builds toggle via config or API

### ISSUE THREAD

**Issue by webknjaz** [readthedocs/readthedocs.org#7811]
## Details

The PR builds setting is only togglable via UI. But for people who maintain many projects, it's rather hard to track and enable it everywhere with no API.

## Expected Result

It should be possible to automatically set up all of the settings in RTD projects.

## Actual Result

Manual work needed on each project, this is especially painful on scale.

**Comment by Mariatta** [comment]
I would like to see this feature too.

**Comment by humitos** [comment]
This is implemented and deployed. Thanks @saadmk11 for doing the hard work! :smile:

**Comment by Mariatta** [comment]
Yay! Thank you all!
