### ISSUE TITLE
Command killed due to excessive memory consumption

### ISSUE THREAD

**Issue by cbouy** [readthedocs/readthedocs.org#7813]
## Details

* Read the Docs project URL: [https://prolif.readthedocs.io/en/latest/](https://prolif.readthedocs.io/en/latest/)
* Build URL (if applicable): [12712572](https://readthedocs.org/projects/prolif/builds/12712572/)
* Read the Docs username (if applicable): cbouy

## Expected Result

I'm generating part of my documentation (tutorials) through notebooks thanks to the nbsphinx extension. Until the above build, everything was working as expected. 

## Actual Result

I recently added a few more computer-intensive analysis to one of the notebooks (in `docs/notebooks/visualisation.ipynb`) and I'm now getting the following error:

```
/home/docs/checkouts/readthedocs.org/user_builds/prolif/conda/latest/bin/python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
Running Sphinx v3.4.2
loading translations [en]... done
making output directory... done
WARNING: html_static_path entry '_static' does not exist
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
loading intersphinx inventory from https://docs.mdanalysis.org/2.0.0-dev0/objects.inv...
loading intersphinx inventory from https://www.rdkit.org/docs/objects.inv...
loading intersphinx inventory from https://pandas.pydata.org/docs/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 13 source files that are out of date
updating environment: [new config] 13 added, 0 changed, 0 removed
reading sources... [  7%] index
reading sources... [ 15%] notebooks/how-to
reading sources... [ 23%] notebooks/protein-protein_interactions
reading sources... [ 30%] notebooks/quickstart
reading sources... [ 38%] notebooks/visualisation


Command killed due to excessive memory consumption
Command time: 1193s Return: 137
```
but the top of the log says
```
Build failed
Error
Build exited due to time out
```
So I'm not sure if it's a time or a memory problem, or both.
Executing all cells in this "visualisation" notebook takes around 8 minutes and uses 0.6Go of memory on my laptop, and the whole documentation takes 11min.
There are other more recent builds with the same error, as I was trying to fix some stuff that didn't render properly in the notebook, if it helps track down the issue.

PS: Unrelated question, but I saw in the docs that there's the possibility to use mamba instead of conda when creating the env. How do I enable that ? Creating my environment takes currently more than 6 minutes so I guess mamba could help with that.

Thank you in advance for your help,
Cédric

**Comment by humitos** [comment]
> So I'm not sure if it's a time or a memory problem, or both.

It's a time out issue --but our code gets confused and also says it's a memory problem :upside_down_face: 

> PS: Unrelated question, but I saw in the docs that there's the possibility to use mamba instead of conda when creating the env. How do I enable that ? Creating my environment takes currently more than 6 minutes so I guess mamba could help with that.

Mamba is not yet available to be enabled by users. However, I will enable it in your project and I will trigger a build. This will definitely helps to reduce some time on each build. The build is at https://readthedocs.org/projects/prolif/builds/12722861/ and it passed.

I will appreciate if you can keep us posted about how things keep going on with your project now that it has `mamba` enabled.

I'm closing this issue for now, but feel free to reopen, open a new one, or add a comment here for now.
