### ISSUE TITLE
Sphinx-1.8.5 is used even if newer Sphinx installed

### ISSUE THREAD

**Issue by tk0miya** [readthedocs/readthedocs.org#7816]
## Details

Thank you for hosting the greatest service! Now I got trouble with the version of Sphinx.
Sphinx-1.8.5 has been used to build our document even if newer Sphinx is installed.
This trouble has been started since Jan 7th. Before that, the expected version of Sphinx had been used.

* Read the Docs project URL: https://readthedocs.org/projects/sphinx/
* Build URL (if applicable): https://readthedocs.org/projects/sphinx/builds/12712472/
* Read the Docs username (if applicable): tk0miya

refs: https://github.com/sphinx-doc/sphinx/issues/8662

## Expected Result

The newer version is used to build the document. In my understanding, the newer version of Sphinx was installed on the before step via `setup.py install --force` command.
(I confirmed the expected version was used at Jan 6th: https://readthedocs.org/projects/sphinx/builds/12705105/)

## Actual Result

The default version Sphinx-1.8.5 is used.

**Comment by stsewd** [comment]
Hi, thanks for reporting, this is because we activated this flag

https://github.com/readthedocs/readthedocs.org/blob/96d1170ccc3d84f3b7b7943e55352143a76a1474/readthedocs/doc_builder/backends/sphinx.py#L264-L274


For some reason sphinx-build uses the newest installed version, but `python -m sphinx` uses the old one. I have disabled the feature for now, we'll need to investigate what's happening before enabling it again.

**Comment by stsewd** [comment]
I think maybe because setup.py install doesn't remove the old one? Maybe using pip install will solve this. You'll need to use a config file for that, I have commented how to use it here https://github.com/sphinx-doc/sphinx/pull/8666

**Comment by tk0miya** [comment]
Thank you for disabling it. Now I added a configuration file. It's okay to enable it again. I suppose this is a trouble only for sphinx project.

**Comment by stsewd** [comment]
I have enabled the feature again, looks like using pip fixed the problem https://readthedocs.org/projects/sphinx/builds/12793774/
