### ISSUE TITLE
Only index.html url showing the correct version

### ISSUE THREAD

**Issue by mebibou** [readthedocs/readthedocs.org#7824]
## Details

* Read the Docs project URL: https://hestia-data-validation.readthedocs.io/en/stable/
* Build URL (if applicable): https://readthedocs.org/projects/hestia-data-validation/builds/12753063/
* Read the Docs username (if applicable): hestia-earth

## Expected Result

*A description of what you wanted to happen*

The menu on the left should show "API Reference" with the link to the package module

## Actual Result

*A description of what actually happened*

The menu shows other links. Strangely, when going on https://hestia-data-validation.readthedocs.io/en/stable/index.html it does show the correct links, but https://hestia-data-validation.readthedocs.io/en/stable/ does not. Did it built two different pages?

Note: I have another project built with exactly the same code (at least I think since I copy-pasted everything) and it does work:
- https://hestia-utils.readthedocs.io/en/stable/
- https://hestia-utils.readthedocs.io/en/stable/index.html

**Comment by stsewd** [comment]
Hi, I can see both pages are the same, probably it was cached.

**Comment by mebibou** [comment]
@stsewd that's a cache on readthedocs? any way to force clearing it?

**Comment by stsewd** [comment]
@mebibou cache at the rtd/cloudflare level should be purged when a build happens and every two hours in case we missed something. You can clear the cache at the browser level with a hard refresh (Ctrl + F5 usually).
