### ISSUE TITLE
Make read the docs work together with GitHub pages ./docs/ directory

### ISSUE THREAD

**Issue by jcubic** [readthedocs/readthedocs.org#7837]
## Details

I don't have yet documentation on readthedocs I'm planing on creating one for my project hosted on GitHub. The problem is that GitHub pages use docs directory the same as readthedocs. Can I use both jekyll source and read the docs source in same directory and build both? Maybe there is way to specifiy the directory like `/docs/docs/` that will be read docs and `/docs/` will be jekyll project.

How to you go about having GItHub pages and read the docs hosted together?

**Comment by stsewd** [comment]
@jcubic we don't support building docs from a jekyll project, you need to use sphinx https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html or mkdocs https://docs.readthedocs.io/en/stable/intro/getting-started-with-mkdocs.html

You can put the project in any directory you want https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by jcubic** [comment]
My question was not to build docs from Jekyll project but can I have both read the docs sphinx files and GitHub pages Jekyll files  in same directory.

Thanks for the link of how to change the directory.
