### ISSUE TITLE
Set DONT_SHALLOW_CLONE for the cocotb project

### ISSUE THREAD

**Issue by imphil** [readthedocs/readthedocs.org#7848]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/cocotb
* Build URL (if applicable): https://readthedocs.org/projects/cocotb/builds/
* Read the Docs username (if applicable): imphil

Would it please be possible to disable shallow clones for the project above, as discussed at https://github.com/readthedocs/readthedocs.org/issues/5031? We'd like setuptools_scm to pick up the project version properly from the source tree.

Thanks a lot!

**Comment by stsewd** [comment]
Done https://readthedocs.org/projects/cocotb/builds/12808986/

**Comment by imphil** [comment]
Thanks a lot, you guys are great!
