### ISSUE TITLE
Write better requirements guide

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#7852]
It would be great to have a longer guide on how to specify requirements, why it's a good idea, and a step-by-step tutorial showing how to figure out your requirements and specify them on RTD.

This could also be a larger guide along the lines of "How to ensure your build doesn't break" or something like that. We have a lot of users who hit issues with the build breaking because of the dependencies being upgraded, and it would be good to be able to send them a document with all the suggestions to improve this situation. 

The current guide is here: https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

**Comment by Pradhvan** [comment]
Hi @eric-wieser I have created a basic outline of the guide 


Heading: **Writing effective requirements for a sustainable build** 

* An example of a somewhat `requirements` dir with multiple `.txt` files.

* How to specify a requirement?

* Pinned requirements vs Unpinned requirements. (The reason why pinned requirements are better and how to create them)

* Comments are gifts for your future (Have requirements file split up in sections like  Search, Utils, and leaving notes is a good idea.) 

* How to handle upgrades for your packages in your requirements file.

**Comment by ericholscher** [comment]
@Pradhvan Great! I just realized there is an open PR here: https://github.com/readthedocs/readthedocs.org/pull/7888 -- so it would be good to review it based on your outline, and make sure that it contains all the information you suggested!
