### ISSUE TITLE
Problem was that task responsible for building documentation (update_docs) was failing silently

### ISSUE THREAD

**Issue by son1999hy** [readthedocs/readthedocs.org#7861]
Problem was that task responsible for building documentation (update_docs) was failing silently. Thus state 'Triggering' never concluded and build was never initiated. It happens that this error was my own fault I run django server on different port than it's in default settings. Exception was thrown, it was never logged, state of task was never updated, readthedocs was left in the limbo.
![image](https://user-images.githubusercontent.com/46740820/105479603-3ad9ac00-5cd7-11eb-811c-cd2da265758e.png)

**Comment by keywinf** [comment]
same problem with 5.10.0

**Comment by humitos** [comment]
If you are working on a local instance, please install it by following this guide and let us know if you find any issue: https://docs.readthedocs.io/en/stable/development/standards.html
