### ISSUE TITLE
Can't configure Korean language

### ISSUE THREAD

**Issue by mfrasca** [readthedocs/readthedocs.org#7862]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/ghinidesktop-docsi18n-ko/
* Build URL (if applicable): https://ghini.readthedocs.io/ko/ghini-1.0-dev/administration.html
* Read the Docs username (if applicable): mariotomo

## Situation

I have a documentation project that is partially translated to several languages, among them Chinese and Korean. They have always been low priority.  Now I'm starting to get some translation strings to Korean, and I don't manage to get it on readthedocs.

## Expected Result

The pages relative to 'administration.html' should be translated to Korean, as they are translated if I run sphinx-build locally.

## Actual Result

All that is at https://ghini.readthedocs.io/ko/ghini-1.0-dev/administration.html stays in the original English form.

## Extra Actions and Observations

To exclude the possibility that something else might be wrong in the project, I have altered the project's language to Chinese or Russian, and the pages are correctly computed, at

https://ghini.readthedocs.io/zh/ghini-1.0-dev/administration.html
https://ghini.readthedocs.io/ru/ghini-1.0-dev/editing.html

bringing it back to Language -> Korean results again in the purely English original text at the expected `ko` location.

It would be helpful if the Build page would contain more than just the commands it executed, and the global resulting status.  By opening the page https://readthedocs.org/projects/ghinidesktop-docsi18n-ko/builds/12828039/ I do not see any indication of trouble, while I suspect that seeing the complete console output might provide some hints on what to adjust.

**Comment by stsewd** [comment]
@mfrasca if you click on the command you can see the output. I can see the language is being set correctly in the command `language=ko`, are you able to build the project using the ko language locally?

**Comment by mfrasca** [comment]
> if you click on the command you can see the output

ah, ok, thanks, that helps, and I see this text:
`writing... WARNING: no Babel option known for language u'ko'`
which looks relevant, or isn't it?

> are you able to build the project using the ko language locally

Locally it works, but locally I'm using sphinx on Python3.7.3

![image](https://user-images.githubusercontent.com/122869/105738108-b10f2600-5f04-11eb-8a92-78c67a6f6eb5.png)

**Comment by stsewd** [comment]
> Locally it works, but locally I'm using sphinx on Python3.7.3

@mfrasca you should use the same version of python and sphinx on rtd https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

**Comment by mfrasca** [comment]
but I don't get it … normally, when I don't specify dependencies explicitly, I get the latest of the latest.
normally, I would put explicit version dependencies in order to freeze a situation to an old version.

**Comment by stsewd** [comment]
@mfrasca we install some libs by default with a specific version, this is to avoid breaking docs, we are in the process to migrate to install the latest version of deps by default, but we always recommend to users to make it explicit. Using a configuration file is recommended for this.

**Comment by mfrasca** [comment]
moving to Python3.x did not change the result, pure English.

**Comment by mfrasca** [comment]
> Using a configuration file is recommended for this.

@stsewd I would not know which version to specify in the requirements file, since I do not have an example of a working version.

**Comment by stsewd** [comment]
@mfrasca do you mean https://docs.readthedocs.io/en/stable/config-file/v2.html? Or if you mean sphinx, looks like you are already using the same version locally, I'd recommend trying to build your docs in a clean environment (clean git and python env) and see if you can reproduce. Also, I can see your local build is using another theme.

**Comment by mfrasca** [comment]
let me suggest something different: can you point me to a project on rtd where the translation to Korean works properly?  I have looked for one, and didn't fine any.

**Comment by stsewd** [comment]
@mfrasca godot and sphinx have working docs in ko https://docs.godotengine.org/ko/stable/ https://www.sphinx-doc.org/ko/latest/

**Comment by mfrasca** [comment]
godot using Sphinx v1.8.5, sphinx using Sphinx 4.0.0.

**Comment by mfrasca** [comment]
I'll be reviewing my `conf.py` file, which looks much more complicated than the one from sphinx.

**Comment by mfrasca** [comment]
> see if you can reproduce

I'm going to do some randomized changes, because without an error message, I would not know what to fine-tune.

**Comment by mfrasca** [comment]
or better: leaving it unresolved.

**Comment by stsewd** [comment]
I just cloned the repo locally and build it, I got the same result as on rtd.

```
git clone https://github.com/Ghini/ghini.desktop-docs.i18n
cd docs
pip install sphinx sphinx-rtd-theme
python -m sphinx -T -E -b html -d _build/doctrees -D language=ko . _build/html
```

![Screenshot from 2021-01-28 17-08-10](https://user-images.githubusercontent.com/4975310/106204832-99959e80-618b-11eb-94c0-b848eade1a10.png)

![Screenshot_2021-01-28 Documentation for Ghini 1 0 — Ghini 1 0 x 문서](https://user-images.githubusercontent.com/4975310/106204873-a5816080-618b-11eb-9c93-babd96154634.png)


![Screenshot_2021-01-28 Database Administration — Ghini 1 0 50 문서](https://user-images.githubusercontent.com/4975310/106205083-f002dd00-618b-11eb-9e24-d2a2403f2683.png)


Make sure you are testing locally on a clean environment, this isn't a rtd problem.
