### ISSUE TITLE
'conda env create' out of memory (OOM) error, probably need UPDATE_CONDA_STARTUP set for our Finch project

### ISSUE THREAD

**Issue by tlvu** [readthedocs/readthedocs.org#7863]
## Details

* Read the Docs project URL: https://pavics-sdi.readthedocs.io/projects/finch/en/latest/
* Build URL (if applicable): Multiple builds on the same commit with different results !!!
  * pass, Completed Jan. 13, 2021. 5:10 p.m: https://readthedocs.org/projects/finch/builds/12757192/
  * fail OOM on `conda env create`, Completed Jan. 13, 2021. 5:12 p.m:  https://readthedocs.org/projects/finch/builds/12757205/
  * fail OOM on `conda env create`, Completed Jan. 22, 2021. 3:53 p.m: https://readthedocs.org/projects/finch/builds/12828574/
* Another problem: `conda env create` did not error out but dependencies not installed correctly: https://readthedocs.org/projects/finch/builds/12827604/
* Read the Docs username (if applicable): 

## Expected Result

Build no error since we can build locally fine.

## Actual Result

Intermittent errors reported above.

## Extra note

We have had OOM error in the past with another of our project (Raven) see https://github.com/readthedocs/readthedocs.org/issues/5847#issuecomment-519201106.

You guys enabled `UPDATE_CONDA_STARTUP` and we never had problems afterwards.

Could we try the same `UPDATE_CONDA_STARTUP` to see if the OOM goes away?

For the 2nd problem that `conda env create` did not error out but seems to not installed all the dependencies properly, that one is still a mystery.  Wonder if there are more logs on your side.

**Comment by tlvu** [comment]
FYI @huard

**Comment by stsewd** [comment]
Hi, I have enabled the flag for your project https://readthedocs.org/projects/finch/builds/12849879/

**Comment by tlvu** [comment]
@stsewd Thanks !!!

**Comment by tlvu** [comment]
Wow build on RtD is also twice faster!  Awsome.
