### ISSUE TITLE
Allow searching in "import a repository" list

### ISSUE THREAD

**Issue by WoLpH** [readthedocs/readthedocs.org#7864]
## Details

* Read the Docs project URL: n/a
* Build URL (if applicable): n/a
* Read the Docs username: wolph

## Expected Result

A searchable list when importing repositories to prevent having to click next page a few dozen times.

## Actual Result

Having to click "next" many times to find the right repository.

This might be an issue specifically to me, but I have many repositories (256 currently, not counting external organisations) and it's a huge pain to have to click through the pagination with 15 pages per item. It wouldn't even be bad if this was only available once you've selected an organisation filter first if that makes the API calls easier to handle, but it's really annoying as it is right now.

In somewhat related note, the current filters could benefit from a website/source indication. Right now I have 3 repositories called "wolph" and no way to see which is which until I actually filter:
![image](https://user-images.githubusercontent.com/270571/105618344-5b445c00-5de6-11eb-93ad-40cd07ff7248.png)

**Comment by humitos** [comment]
Hi! We are aware of this and we have an issue tracking this problem already (I haven't find it). We are working on a new design theme of our entire platform that will include this by default.

**Comment by WoLpH** [comment]
Ah, excellent. I guess this is a dupe in that case.

**Comment by WoLpH** [comment]
Actually, looking at that issue it seems related but different. The filters work for me, but even with filters I have hundreds (or thousands depending on the organisation) repositories

**Comment by stsewd** [comment]
@WoLpH this feature is being implemented in the new version of the theme https://github.com/readthedocs/readthedocs.org/issues/7509

**Comment by WoLpH** [comment]
Awesome, dupe it is :)
