### ISSUE TITLE
Cloning not capturing latest code when pushing multiple quick updates

### ISSUE THREAD

**Issue by reginapizza** [readthedocs/readthedocs.org#7866]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/regina-argocd-notifications/
* Build URL (if applicable): not applicable to a single build
* Read the Docs username (if applicable): reginapizza

## Expected Result

I would expect that my code always updates and my branch is built from the actual commit ID that it says it's using.

## Actual Result

I am currently trying to use RTD to provide versioning built with MkDocs and create my own styling for it as well ([adding a custom select and version warning](https://github.com/argoproj/argo-cd/pull/5099)). To develop this solution, I must use `(window['READTHEDOCS_DATA'])` and to have access to that data, I need to have it deployed (I can't get this information from running it locally with mkdocs serve), so I make frequent commits and have builds automatically triggered. I see that the build takes about a minute and has the correct commit ID associated with it, but if I've made a few commits over a short amount of time (really only like 5 or so at times is all it takes to break it) then my most recent code isn't used and it takes hours after that to update it accordingly without even triggering a new build. I just have to refresh the page hours later or view the docs from the most recent build and they'll be there, just much later. At one point I timed it to be about an hour and 15 minutes, other times I tried after 4 hours and it was still not updated. 

I can probably provided a demo of this (live if necessary) if you need more information or want to troubleshoot it, it probably won't be visible on my project unless I've done a lot of commits very recently. 

I thought this issue might be related to build limits so I emailed support@readthedocs.org and spoke with David, who told me that it didn't look like we were hitting any build limits and encouraged me to log this issue. He also said that "there is a Cloudflare CDN serving the content. Finishing a build is supposed to invalidate the cache but it's possible that is getting confused when builds happen in quick succession. I haven't seen reports of that in the past though".

Thanks for looking into this!

**Comment by stsewd** [comment]
Hi @reginapizza, indeed we invalidate the cache automatically after some time, but we also invalidate the cache on every build. If this happens again, can you try a hard refresh (ctrl+ f5)? The cache should be invalidated automatically after 2 hours.

**Comment by stsewd** [comment]
On a side note: looks like some times our cache invalidation is failing (since last week), this is due to a rate limit with the Cloudflare API (this doesn't affect the cache being invalidated automatically after 2 hours)

**Comment by reginapizza** [comment]
Hi @stswed, thanks for the suggestion. Unfortunately I tried refreshing the cache with f5 and it is still showing me the same result. I pushed new code this morning and I haven't worked on it for a few days at this point, and even on the first push it's not updating with my most recent code now. Here is a screenshot of my code editor showing that I pushed code to my branch, the only line I changed this time was line 86. I cleared my cache and refreshed the page, the build was done from the code with the correct commit id, but you can still see in my sources tab that line 86 is not accurately reflecting what I had pushed (that is still what it was previously).

![Screenshot from 2021-01-26 09-40-18](https://user-images.githubusercontent.com/50851526/105860207-54227700-5fbb-11eb-850b-03625eb70ac5.png)

**Comment by stsewd** [comment]
@reginapizza I'm able to see that change in your docs now. Please, if you find this situation again, could you take note of the age reponse header?

![header](https://user-images.githubusercontent.com/4975310/105868117-d020bd00-5fc3-11eb-95c4-4057c5ca6783.png)

That would be helpful to confirm my theory about the rate limit we are hitting with cloudflare.

**Comment by stsewd** [comment]
Ok, we have deployed a fix to not hit the rate limit from cloudflare, so if that was the problem, docs should be purged on new builds automatically.

**Comment by reginapizza** [comment]
just tried it out again, not sure if that should be an automatic fix but it still seems to be happening. Here is my response header (hopefully it's the correct one). At 760 it seems very high seeing as yours was only 32. This was after I refreshed and cleared my cache as well. 
![Screenshot from 2021-01-26 15-12-59](https://user-images.githubusercontent.com/50851526/105899844-366c0680-5fe9-11eb-9eb9-55d12135864f.png)

**Comment by stsewd** [comment]
@reginapizza sorry, turns out my previous comment was a lie, the deploy didn't go through, we have fixed that now. The fix should be live now. And yes, that't the correct file/header. The number depends on when was  cache purged, so if it was recent the number should be low (max is 7200), so it should be low after a recent build/purged.

**Comment by reginapizza** [comment]
@stsewd thanks for your help, it seems to be working right now with really only 30 seconds or so of lag before it updates it correctly. Hopefully it stays like that, I'll keep the issue open for now and continue to work on it today and see if that changes at all and then if it continues to work I'll go ahead and close the issue :)

**Comment by reginapizza** [comment]
This all seems to be working now, I will go ahead and close the issue. Thank you so much for your help!
