### ISSUE TITLE
Using binaries downloaded as pip package

### ISSUE THREAD

**Issue by FedyuninV** [readthedocs/readthedocs.org#7868]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/neoml/

This Python module is a wrapper of C++ library, which needs Intel MKL. Intel MKL libraries can be installed via `pip install mkl_devel` but I can't find a way to get to its install location (it's `dist-packages/../../lib` or `site-packages/../../lib`). The problem is that I can't get the location of the `dist-packages` directory. None of variables are defined (`CONDA_PREFIX` `CONDA_DIR` `VIRTUAL_ENV`, `PYTHONPATH`) which doesn't allow me to link agains MKL.

(I'm building this module in order to get `autodoc` working)

Is there some env variable which shows me current python location? (preferrably without Conda because I don't need it)

## Expected Result

Successful build

## Actual Result

MKL not found

**Comment by FedyuninV** [comment]
Found a workaround

**Comment by FedyuninV** [comment]
Nope, that was a bug, I still need directory, where `pip install` installed packages (at least for `pybind11`)

**Comment by FedyuninV** [comment]
Found a workaround again)

**Comment by stsewd** [comment]
I was about to suggest conda, but looks like isn't an option, you can also try mocking https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules
