### ISSUE TITLE
API reference using autodoc is empty

### ISSUE THREAD

**Issue by leroyvn** [readthedocs/readthedocs.org#7871]
## Details

* Read the Docs project URL: https://pinttrs.readthedocs.io/en/latest/rst/api.html
* Build URL (if applicable): https://readthedocs.org/projects/pinttrs/builds/12861893/
* Read the Docs username (if applicable): leroyv
* GitHub project page: https://github.com/leroyvn/pinttrs

I checked many similar issues but no solution I tried to implement worked. I don't see warnings or errors in build logs. 

## Expected Result

An autodoc-documented API reference page (see local build below).

![Screenshot 2021-01-26 at 20 18 05](https://user-images.githubusercontent.com/34740232/105893716-b909bb80-6013-11eb-893e-6111b58e336c.png)

## Actual Result

The page is empy (see page on RTD below).

![Screenshot 2021-01-26 at 20 18 19](https://user-images.githubusercontent.com/34740232/105893785-cd4db880-6013-11eb-8390-93984954732a.png)

**Comment by stsewd** [comment]
Hi, I can see the correct page

![Screenshot_2021-01-26 API Reference - Pinttrs documentation](https://user-images.githubusercontent.com/4975310/105907478-00cc1b00-5ff3-11eb-9515-ee7e577c648a.png)

We were having some issues with purging our cache, so I guess that was it. But it should be fixed now.

**Comment by leroyvn** [comment]
Thanks a lot, I'll close this issue.
