### ISSUE TITLE
Don't rely on the HTMLFile model to index and re-index files

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#7875]
So, we don't need these objects in the db to re-index, since we re-read all their data from storage to index/re-index.
The only benefit is to track changed files, but that is going to be removed in https://github.com/readthedocs/readthedocs.org/pull/7874.

Our current flow is:

- Create html objects from all html files in storage
- Create intersphinx data for existing html files (here we use the html file objects to check that, but it can be replaced by keeping files in memory)
- Sync to ES
- Delete html files from previous builds (afte this, the html objects aren't used for anything else other thant the re-index management command)

Benefits include not having that data in the db (more spaaaace!), and removing the `django-elasticsearch-dsl` package (fewer dependencies!).

Work to do:

- Use a structure/class instead of an ORM model to pass around the data in the indexing step.
- Change our re-indexing management command to not depend on the objects from the db, but do the re-index directly.

**Comment by humitos** [comment]
This was implemented in https://github.com/readthedocs/readthedocs.org/pull/10696

> removing the `django-elasticsearch-dsl` package (fewer dependencies!).

This is going to be done in https://github.com/readthedocs/readthedocs.org/issues/10730
