### ISSUE TITLE
question on how to setup the rtd environment

### ISSUE THREAD

**Issue by parmentelat** [readthedocs/readthedocs.org#7877]
Hi

I have a question - not a bug report really - on how to set up the rtd context; in a nutshell, I need Jupyter with a ijavascript kernel, which boils down to having python + node and then issuing
```
npm install ijavascript
ijsinstall
```

So first off, apologies if here is not the right place to ask, in that case please just redirect me

I am aware of `readthedocs.yaml`, and know to get `pip` installs, but could not yet find how to achieve the above

any hint would be most welcome

and thanks for rtd which is a lifesaver !!

**Comment by stsewd** [comment]
@parmentelat currently we don't support executing custom commands in the build process, but you can achieve the same by making those calls from inside your conf.py file (if you are using sphinx).

Also, another popular alternative is using a conda package that already includes all dependencies if one is available.

See https://github.com/readthedocs/readthedocs.org/issues/6662
