### ISSUE TITLE
 Set DONT_SHALLOW_CLONE for the fusesoc project

### ISSUE THREAD

**Issue by imphil** [readthedocs/readthedocs.org#7879]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/fusesoc/
* Build URL (if applicable): https://readthedocs.org/projects/fusesoc/builds/
* Read the Docs username (if applicable): imphil

Would it please be possible to disable shallow clones for the project above, as discussed at #5031? We'd like setuptools_scm to pick up the project version properly from the source tree.

Thanks a lot!

**Comment by stsewd** [comment]
Done https://readthedocs.org/projects/fusesoc/builds/12880238/!
