### ISSUE TITLE
Specify a source directory different from the configuration directory

### ISSUE THREAD

**Issue by Lucide** [readthedocs/readthedocs.org#7883]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/visualt/
* Build URL (if applicable): https://readthedocs.org/projects/visualt/builds/12886634/
* Read the Docs username (if applicable): Lucide

## Expected Result

*TLDR*
My doc sources are in a different directory than the `conf.py` file. How can I tell that to readthedocs?
"source directory": https://www.sphinx-doc.org/en/master/glossary.html#term-source-directory
"configuration directory": https://www.sphinx-doc.org/en/master/glossary.html#term-configuration-directory

I'm really struggling to port my GitHub ci workflow to readthedocs. I'm using the usual cmake+doxygen+breathe+sphinx tolchain to document a C project. I managed to run cmake using a providential [pip distribution](https://pypi.org/project/cmake/), but I hit a wall again because sphinx searches doc sources in the wrong path.
I also had to use an unconventional [conf.py](https://github.com/Lucide/VisualT/blob/master/doc/readthedocs/conf.py) setup but that seems working.

## Actual Result

Sphinx searches for `index.rst` in the configuration directory

**Comment by stsewd** [comment]
Hi, currently we don't support specifying a custom source directory. I'm not sure if it is worth the effort adding another setting in the config file.

**Comment by Lucide** [comment]
I'm really losing my mind (and time) trying to get this to work. A workaround would be to copy all the contents of the source directory to the cofig directory.
```
├── CMakeLists.txt
├── stuff
├── images
│   ├── VCat-alpha.png
├── importers
│   └── import-xp.rst
├── readthedocs
│   ├── conf.py
│   └── requirements.txt
```
That means moving the contents of the directory inside `./readthedocs` except for `readthedocs` itself.
I'm not familiar with python. I've tried
```python
subprocess.run(["cp", "-r", "-l", "-n", "doc/!(readthedocs)", "doc/readthedocs"], cwd="../..", shell=True, check=True)
```
Error code 2

I've tried [pyrocopy](https://pypi.org/project/pyrocopy/), it doesn't install.

I've already done more than 15 push just for get readthedocs's build to work. If specifying the correct folders can't be done, could you please give me a hint on how to copy the required files to the config directory in a way the builder likes?

**Comment by stsewd** [comment]
@Lucide I think a more simple approach would be to create a symlink from the conf.py file to the source directory, or just move it. Is there a problem that makes you place the conf.py file in another directory?

**Comment by Lucide** [comment]
The documentation is for a C project that is configured/built/installer with CMake. The `doc` folder contains the sphinx sources and a template file called `conf.py.in`. This file needs to be processed by CMake, and the processed file will be located under a `/build` directory. This is more or less how every CMake project works. The `doc/readthedocs/conf.py` is an extension that runs CMake to configure and build everything required (except the html build of course), and then evaluates the configured `conf.py`. Unfortunately there's no room for link trickeries, the real solution would be to support Sphinx correctly and do not treat the config dir and the source dir as the same thing.
Since that's not going to happen anytime soon, the only option left is copying files, and the copy must support folder exclusion. How do I do that in readthedocs? Why does `cp` fail?
I could try to copying the files with a CMake script maybe, that might work..

**Comment by stsewd** [comment]
> Why does cp fail?

I think maybe something with the cwd, I'll recommend using `__file__` to get the absolute path.

**Comment by Lucide** [comment]
I used a simple CMake script to do the copy:
```CMake
file(COPY "${CMAKE_CURRENT_LIST_DIR}/../" DESTINATION ${CMAKE_CURRENT_LIST_DIR}
     PATTERN "readthedocs" EXCLUDE)
```
With
```python
# -- readthedocs CI ----------------------------------------------------------

import subprocess

subprocess.run(["cmake -P copy.cmake"], shell=True, check=True)
subprocess.run(["cmake -D VisualT_ASSUME_LITTLE_ENDIAN:BOOL=YES -S . -B build"], cwd="../..", shell=True, check=True)
subprocess.run(["cmake --build build --target VisualT_doxygen_generate_xml"], cwd="../..", shell=True, check=True)
with open("../../build/doc/conf.py") as infile:
    exec(infile.read())
```

The main advantages are that it's os (and shell) agnostic, and I have total control of the paths/cwd.

You're right about the `__file__`, I don't know how to use it (and when to no use it) correctly tho. If you don't mind I'll leave the issue open since it mentions the Sphinx config dir option.

**Comment by humitos** [comment]
Hi @Lucide! I had the same doubt as yourself some time ago and I change the source directory from my `conf.py` file. See https://github.com/python/python-docs-es/blob/c79c770adf608d2cf9ac707792c6c54b9fb01f89/conf.py#L112-L113

I don't think we will add a config option in the Read the Docs file to do this. I don't think it worth the effort for an edge case like this and having a simple workaround to fix it.
