### ISSUE TITLE
Custom robots.txt isn't working

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#7892]
- Create a project using test-builds
- Activate the robots-txt version
- Make that version the default

https://test-builds.readthedocs.io/robots.txt should be the same as https://test-builds.readthedocs.io/en/robots-txt/robots.txt

**Comment by humitos** [comment]
@stsewd are you sure you are not hitting the new cloud?

It does work to me.

```
▶ diff <(curl --silent https://test-builds.readthedocs.io/en/robots-txt/robots.txt) <(curl --silent https://test-builds.readthedocs.io/robots.txt) 

~                                                                                                                                            
▶ curl --silent https://test-builds.readthedocs.io/robots.txt
# This is a comment in my custom robots.txt
# for the test-builds project under Read the Docs
User-agent: *
Allow: /
```

**Comment by humitos** [comment]
Or... maybe you got a cached response?

**Comment by stsewd** [comment]
Hmm, I can see they are the same now, cache maybe.
