### ISSUE TITLE
Change the project slug

### ISSUE THREAD

**Issue by aprilahijriyan** [readthedocs/readthedocs.org#7898]
## Details

* Repo: https://github.com/zemfrog/zemfrog/
* Old URL: https://zemfrog.readthedocs.io/en/latest/
* New URL: https://zemfrog-zemfrog.readthedocs-hosted.com/en/latest/

I don't really understand why the document is not updated when I add some new documents to it.
Then I checked on the dashboard that there was no project in it, could it be deleted by yourself? I don't really understand, but I can still access the old documentation.

The question is can you help me delete the old document and change the new document with the old project slug?

Thank you in advance.

**Comment by stsewd** [comment]
@aprilahijriyan you are using two different platforms (readthedocs.org and readthedocs.com). For the old project, you can delete it from here https://readthedocs.org/dashboard/zemfrog/delete/.

Changing the slug for projects on .com isn't possible, as they are build by using the name of your organization + the name of the project. For public facing documentation, we recommend using a custom domain https://docs.readthedocs.io/en/stable/custom_domains.html?tab=Read%20the%20Docs%20for%20Business#custom-domain-support

**Comment by stsewd** [comment]
Also, for issues related with readthedocs.com, please contact us via support https://readthedocs.com/support/
