### ISSUE TITLE
How to import a project when the name is occupied by an abandoned project?

### ISSUE THREAD

**Issue by johann-petrak** [readthedocs/readthedocs.org#7900]
I would like to create a project with the name `gatenlp`, for the Pypi package `gatenlp` (see https://pypi.org/project/gatenlp/)

This is not possible since a project with the name `gatenlp` already exists on rtd. However, that project is abandoned under that name, the owner has renamed the original pypi package to https://github.com/nickwbarber/gatenlphiltlab 

I have tried to contact the owner about this issue related to RTD but did not get a response after several months. 

I have seen the policy about abandoned projects here: https://docs.readthedocs.io/en/latest/abandoned-projects.html but this does not give advice about how to access the name of an abandoned project or initiate its removal.

**Comment by stsewd** [comment]
Hi, the policy is applied by the core team, you can reach us via an issue or email (this is the preferred method). I'll trey to contact the  user next week or so and start the 6 weeks count.

**Comment by johann-petrak** [comment]
I just received an email by the owner of the project who told me that he renamed the project, so I was able to import my own project now! 
This issue is therefore resolved and no further action necessary!
