### ISSUE TITLE
Underfull \vbox TeX capacity exceeded

### ISSUE THREAD

**Issue by tcassanelli** [readthedocs/readthedocs.org#7906]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pyoof/
* Build URL (if applicable): https://readthedocs.org/projects/pyoof/builds/13010427/
* Read the Docs username (if applicable): tcassanelli

## Expected Result
Build succeeds in readthedocs compilation.

## Actual Result

While building locally LaTeX and html versions work fine, but in readthedocs fails in compiling the LaTeX file.

The compilation error that I am getting is

```bash
Underfull \vbox (badness 10000) detected at line 937
! TeX capacity exceeded, sorry [input stack size=5000].
<to be read again> 
                   \reserved@b 
l.937 \end{sphinxVerbatim}
                          
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on pyoof.log.
Latexmk: Index file 'pyoof.idx' was written
Latexmk: List of undefined refs and citations:
  Citation `aperture/index:loyeun' on page 63 undefined on input line 761
  Citation `aperture/index:stutzman' on page 61 undefined on input line 687
  Citation `aperture/index:welford' on page 64 undefined on input line 767
Latexmk: Summary of warnings:
  Latex failed to resolve 3 citation(s)
Failure to make 'pyoof.pdf'
Collected error summary (may duplicate other messages):
  pdflatex: Command for 'pdflatex' gave return code 256
Latexmk: Errors, in force_mode: so I tried finishing targets
```
which repeats over several times until it fails. This also maybe related to the issue #7344.
(If there is no easy solve I would also rather cancel the optional LaTeX build).

**Comment by humitos** [comment]
We don't have currently a workaround for this. We my need to implement something like mentioned in https://github.com/readthedocs/readthedocs.org/issues/7344#issuecomment-669323227 at some point that matches the VM RAM. However, that will take some dev/QA time. I suggest to disable PDF for now. Or... find out why there are some many in your PDF

```
Underfull \vbox (badness 10000) detected at line 937
```

and see if you can do something from your side.

**Comment by tcassanelli** [comment]
thank you @humitos, how do I disable the PDF creation?

**Comment by stsewd** [comment]
@tcassanelli you can do this from the admin panel of your project https://readthedocs.org/dashboard/pyoof/advanced/ or by using a config file https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by tcassanelli** [comment]
Gracias @humitos and @stsewd, I updated to `version: 2` and run again without the PDF compiler and it builds,
https://readthedocs.org/projects/pyoof/builds/13035432/
Keep me posted if in the future there's a solution for this!

**Comment by stsewd** [comment]
This looks like a good thing to try https://github.com/readthedocs/readthedocs.org/issues/8382#issuecomment-892097499

**Comment by humitos** [comment]
I'm a little confused here. Is there anything we can do from our side to solve this issue?
