### ISSUE TITLE
New builds updating new pages, but not old pages

### ISSUE THREAD

**Issue by moshez** [readthedocs/readthedocs.org#7911]
## Details

* Read the Docs project URL: https://readthedocs.org/dashboard/moshez-recipes/
* Build URL (if applicable):  https://readthedocs.org/projects/moshez-recipes/builds/12991552/
* Read the Docs username (if applicable): moshez

## Expected Result

All pages in a project should show the same build version eventually
(in less than 3 days).

## Actual Result

Here is an example showing two pages in the project wiht different built versions:

```
$ curl https://recipes.orbifold.xyz/index.html -s |grep Revision
          Revision <code>664a2c15</code>.
$ curl https://recipes.orbifold.xyz/hamantaschen.html -s |grep Revision
          Revision <code>8126efe1</code>.
```

**Comment by humitos** [comment]
I checked our storage and I can confirm that one file was modified on Feb 10, and another was on Jan 29 for the same `latest` version.

![Screenshot_2021-02-15_12-14-31](https://user-images.githubusercontent.com/244656/107939723-6aeb3680-6f87-11eb-87ae-56827a0180b6.png)

I'm triggering a new build on your project to see if all the files are overwritten or none of them (considering there was no modifications since the last build 4 days ago)

**Comment by humitos** [comment]
OK. After the new build **all the files were updated** (`February 15, 2021, 12:17:04 (UTC+01:00)`) and now it returns the same revision:

```
▶ curl https://recipes.orbifold.xyz/index.html -s |grep Revision
          Revision <code>40e3ba6d</code>.

~                                                                                                                                                                                                                          
▶ curl https://recipes.orbifold.xyz/hamantaschen.html -s |grep Revision
          Revision <code>40e3ba6d</code>.
```

I don't have a clear explanation about what happened, but last week [we were migrating clouds](https://blog.readthedocs.com/aws-migration/) and we re-synced incrementally the files from our old storage to the new one, so something may happened in the middle? we may omit some projects by mistake? @ericholscher does this makes sense to you?

@moshez if you can, please keep an eye on this and let us know if you notice this problem again; but I suppose it won't happen again.

**Comment by ericholscher** [comment]
It's certainly possible that a couple files were missed. It's also possible a file failed to upload on the original build, or a few other possible outcomes. It's hard to really know, but certainly at our scale these kind of issues happen probably each hour for at least a few files.

**Comment by stsewd** [comment]
The timeframe matches our storage migration. Feel free to ask to re-open if you this happening again.
