### ISSUE TITLE
Static files missing for localized builds

### ISSUE THREAD

**Issue by nijel** [readthedocs/readthedocs.org#7914]
## Details

* Read the Docs project URL: https://docs.weblate.org/ru/latest/
* Build URL (if applicable): https://readthedocs.org/projects/weblate-ru/builds/13023133/
* Read the Docs username (if applicable): nijel

## Expected Result

Some localized builds now lack static resources and fail to display properly in browser.

For example, https://docs.weblate.org/ru/latest/_static/docs.css and https://docs.weblate.org/fr/latest/_static/docs.css - fails with 404, while https://docs.weblate.org/uk/latest/_static/docs.css and https://docs.weblate.org/en/latest/_static/docs.css work just fine. 

All languages are using the same setup and are built from the same repository.

## Actual Result

I expect all localizations behave equally. It used to work and broke recently.

**Comment by stsewd** [comment]
Hi, I can see all the links are working for me, so maybe it was a cached response.

**Comment by nijel** [comment]
Yes, it's working now. It did not work for several hours and only some translations were broken.

**Comment by stsewd** [comment]
Probably a temporal error when purging our CDN, but we clear the cache after two hours in case isn't done after a build.

**Comment by Fat-Zer** [comment]
For the record, this was broken for a couple of days, not hours. I haven't reported it right away in hope it will resolve sooner...

**Comment by stsewd** [comment]
If this wasn't working before doing a recent build, it may have been caused by https://github.com/readthedocs/readthedocs.org/issues/7917#issuecomment-779949539
