### ISSUE TITLE
config file ignored

### ISSUE THREAD

**Issue by gaborbernat** [readthedocs/readthedocs.org#7915]
Hello,

I added a readthedocs config to my project https://github.com/tox-dev/tox/commit/d5957b82de26c5785fd88eb29106e478b622ac8b. However, for some reason, it seems to be ignored and 3.6 still used instead of python3.8. Any ideas? (build number 13028284)

Thanks,

**Comment by stsewd** [comment]
Thanks for reporting, I can't replicate this locally, so I'll need to dig a little more :/

**Comment by stsewd** [comment]
And.... This is why, you have two config files https://github.com/tox-dev/tox/blob/master/readthedocs.yml, the older one is being read first :D

**Comment by stsewd** [comment]
You should delete the older one, so the new one always takes effect. I think we should reduce the number of accepted formats to avoid this problems.

**Comment by gaborbernat** [comment]
Thanks, all done 👍🏻
