### ISSUE TITLE
Readthedocs is serving old documentation pages

### ISSUE THREAD

**Issue by shan18** [readthedocs/readthedocs.org#7917]
## Details

* Read the Docs project URL: https://tensornet.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/api/v2/build/12969124.txt
* Read the Docs username (if applicable): shan18
* GitHub repo URL to docs: https://github.com/shan18/TensorNet/docs

## Expected Result

The latest build of the documentation was successful and was published 8 days ago. After publishing, the documentation page worked perfectly.

## Actual Result

When I checked the documentation page again today, all the information on the page was lost and it reverted back to the base text that one finds after initializing sphinx.
As you can check by the commit logs in the GitHub URL mentioned above, no change has been made to the repository in the past 8 days and somehow all the documentation of the project is gone.

What could be the issue?

**Comment by stsewd** [comment]
Sorry about that, looks like there was an error when we changed platforms [1], and the old files got synced to our new storage. We are investigating this problem. You could also trigger a re-build to update the files to the current version in the meantime.

[1]: https://blog.readthedocs.com/aws-migration/

**Comment by shan18** [comment]
Re-building worked. Thanks.

**Comment by UniversalSuperBox** [comment]
I can confirm this issue, but mine was only on localizations of our main docs.ubports.com site. More similar to https://github.com/readthedocs/readthedocs.org/issues/7914. A rebuild fixed them.

**Comment by stsewd** [comment]
So, we talked about this, and re-syncing the files to this point isn't something we can do, as we could override existing files. Triggering a re-build should be the easiest way to fix this problem, if you can't do that for some reason, let us know and we can try to resync those files manually.
