### ISSUE TITLE
RTD is building an old version of the documentation

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [readthedocs/readthedocs.org#7919]
## Details

* Read the Docs project URL: https://trtools.readthedocs.io/en/latest/index.html
* Build URL (if applicable): https://readthedocs.org/projects/trtools/builds/13031730/
* Read the Docs username (if applicable): gymreklab

## Expected Result

I just manual rebuilt `latest`. It should have the documentation from the most recent commit of the master branch which is `v4.0.0`. This would be clear from seeing "Release Notes" as a link in the sidebar on the right.

## Actual Result

An old version of the documentation is built.

## Testing

I checked out the master branch of the repo and ran `cd doc ; make clean && make html` This produced up to date documentation.

What's going wrong here?

Thanks!

**Comment by stsewd** [comment]
Hi, I can see the latest changes in https://trtools.readthedocs.io/en/latest/RELEASE_NOTES.html, I think you were looking a cached version, cache is purged after a build or after two hours. If you see this problem again please feel free to report it.

**Comment by LiterallyUniqueLogin** [comment]
Oh, I can see that now too. I'll remember that for the future.

Thanks for looking at this.
