### ISSUE TITLE
Internal error when parsing responses at web application using `docker-compose`

### ISSUE THREAD

**Issue by gmiejski** [readthedocs/readthedocs.org#7923]
## Details

* Read the Docs project URL: local development, branch `rel` 
* Build URL (if applicable):
* Read the Docs username (if applicable):

When setting up the local environment using `inv docker.up`, everything urns smoothly until triggering build by hand. When build is triggered, error appears and no results are produced:

## Expected Result

The build is scheduled as normally and it's progress is displayed at the web UI.

## Actual Result

![image](https://user-images.githubusercontent.com/3779045/108193767-1924e680-7116-11eb-8a0a-b5846eb6f9e5.png)

Error:
```
build_1     | [17/Feb/2021 10:43:00] readthedocs.projects.tasks:641[15]: ERROR An unhandled exception was raised during build setup
build_1     | Traceback (most recent call last):
build_1     |   File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 697, in _update_chunk_length
build_1     |     self.chunk_left = int(line, 16)
build_1     | ValueError: invalid literal for int() with base 16: b''
build_1     |
build_1     | During handling of the above exception, another exception occurred:
build_1     |
build_1     | Traceback (most recent call last):
build_1     |   File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 438, in _error_catcher
build_1     |     yield
build_1     |   File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 764, in read_chunked
build_1     |     self._update_chunk_length()
build_1     |   File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 701, in _update_chunk_length
build_1     |     raise InvalidChunkLength(self, line)
build_1     | urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)
build_1     |
build_1     | During handling of the above exception, another exception occurred:
build_1     |
build_1     | Traceback (most recent call last):
build_1     |   File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 753, in generate
build_1     |     for chunk in self.raw.stream(chunk_size, decode_content=True):
build_1     |   File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 572, in stream
build_1     |     for line in self.read_chunked(amt, decode_content=decode_content):
build_1     |   File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 793, in read_chunked
build_1     |     self._original_response.close()
build_1     |   File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
build_1     |     self.gen.throw(type, value, traceback)
build_1     |   File "/usr/local/lib/python3.6/dist-packages/urllib3/response.py", line 455, in _error_catcher
build_1     |     raise ProtocolError("Connection broken: %r" % e, e)
build_1     | urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```

**Comment by humitos** [comment]
Hi! I've never seen that error. Did you follow the steps from https://docs.readthedocs.io/en/stable/development/standards.html and immediately got that error? Or did you change/install something else?

Where all the other services from `docker-compose` able to start?

**Comment by gmiejski** [comment]
Hi, yes, I've followed this guide. I think something broke during the `5.9.0` version (as it's been merged to `rel` branch AFAIK).
When running locally via `python ./manage.py runserver` there are no exceptions when building the documentation on a given project (same branch)

What additional information would be useful from my side to verify that it's not my local settings only?
Thanks!

**Comment by humitos** [comment]
> When running locally via `python ./manage.py runserver`

Where are you running this? We are using containers and there shouldn't be need to run this command manually. Just by running `inv docker.up` everything should work (use `master` branch). Can you describe what are the exact steps you are following?

**Comment by gmiejski** [comment]
Sorry for the trouble, had my environment "dirty" with previous attempts. Closing.
