### ISSUE TITLE
Recovering access to repository

### ISSUE THREAD

**Issue by apdibbo** [readthedocs/readthedocs.org#7924]
## Details
Hi, unfortunately the member of staff who ran our readthedocs repository for us has left and we no longer have access and are now seeing build errors which I need to investigate. Is there a way to get access back?
* Read the Docs project URL:
 https://stfc-cloud-docs.readthedocs.io/
* Build URL (if applicable):
https://readthedocs.org/projects/stfc-cloud-docs/builds/13039952/
* Read the Docs username (if applicable):
apdibbo-stfc

**Comment by stsewd** [comment]
@apdibbo we have a policy for abandoned projects we can follow for this case https://docs.readthedocs.io/en/stable/abandoned-projects.html#abandoned-projects. I have emailed the user today, if I don't get a reply in 6 weeks I'll transfer the project to your account.

**Comment by stsewd** [comment]
/remind me about take action on this project in 6 weeks

**Comment by stsewd** [comment]
Didn't receive any reply, I have added this user as owner of the project https://readthedocs.org/profiles/apdibbo-stfc/
