### ISSUE TITLE
Non-tagged versions are not updated properly

### ISSUE THREAD

**Issue by cbouy** [readthedocs/readthedocs.org#7927]
## Details

* Read the Docs project URL: [https://readthedocs.org/projects/prolif/](https://readthedocs.org/projects/prolif/)
* Build URL (if applicable):
* Read the Docs username (if applicable): cbouy

## Expected Result

The [latest](https://prolif.readthedocs.io/en/latest/) build should use the latest version available on my master branch on GitHub (commit `fb07487`).
The [stable](https://prolif.readthedocs.io/en/stable/) build should be the same as the latest tagged version (v0.3.1, commit `4231d296`).

## Actual Result

Only the builds corresponding to tagged versions are correct.
The `latest` build is (mostly) based on Revision `67d5d69c` (as shown at the bottom of the page) instead of `fb07487`.
The `stable` build is (mostly) based on Revision `447057cc` instead of `4231d296`.

Oddly enough, the Revision versions are displayed correctly under the ["Versions" tab](https://readthedocs.org/projects/prolif/versions/) of the project.

Also strange: new pages are not displayed in the toc but are accessible, like the [Citation](https://prolif.readthedocs.io/en/stable/source/citation.html) page on the `stable` build, which wasn't available in previous versions but was added in v0.3.1 (latest tag).

**Comment by stsewd** [comment]
Hi, sorry about that, this looks like the same as https://github.com/readthedocs/readthedocs.org/issues/7917, you can fix this by triggering a new build to the affected versions.
