### ISSUE TITLE
Feature Request for Azure AD integration for Public ReadTheDocs

### ISSUE THREAD

**Issue by MourIdri** [readthedocs/readthedocs.org#7930]
## Details
Hi team, any plan to have Azure AD integration for ReadTheDocs public service ( github only today...) 
A nice sample here shows how to bring python integration
https://github.com/Azure-Samples/ms-identity-python-flask-webapp-authentication
Thanks

**Comment by stsewd** [comment]
Hi, would this only for authentication or also for integrations like importing [repositories](https://azure.microsoft.com/en-us/services/devops/repos/)?

Looks like they offer private repositories only? So, not sure if we are going to add that integration into .org.

**Comment by MourIdri** [comment]
"Only" for auth, this would be a significant step in bridging the Public SaaS with private access thru AAD Auth. Offloading Identity management to AAD. 

AAD free version allow things like MFA, which would be a good use case for small team access. 

A couple of application are present there already : 

https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/tutorial-list

Working in that manner 

![image](https://user-images.githubusercontent.com/19348103/108392137-b1a09100-7212-11eb-9878-52c79301253c.png)

**Comment by stsewd** [comment]
Interesting, that sounds more like a feature to add for readthedocs.com, not sure if owners from public repositories and OSS are using AAD.

**Comment by MourIdri** [comment]
Well, At least adding a third solution for ID management would be great.

**Comment by humitos** [comment]
I don't think we will implement this. We already support GitHub / GitLab / Bitbucket / Google. Azure AD doesn't seem to be widely used in the OSS world unfortunately to worth the effort of implementing and maintaining it.
