### ISSUE TITLE
Documentation build fails on 'Updating searchtools for Read the Docs search...'

### ISSUE THREAD

**Issue by atedstone** [readthedocs/readthedocs.org#7931]
## Details

* Read the Docs project URL: https://marutils.readthedocs.io/en/dev/
* Build URL (if applicable): https://readthedocs.org/projects/marutils/builds/13047057/
* Read the Docs username (if applicable): atedstone

## Expected Result

Successful build to `dev` label of documentation.

## Actual Result

Build fails. There is no error message given as such, but the last line of logging provided is 'Updating searchtools for Read the Docs search...'. I tried wiping the build and re-starting but this has not helped.

I can build locally with Sphinx v3.3.1 without problems, this seems to be a configuration/incompatibility issue with searchtools, but I do not know how to fix.

**Comment by humitos** [comment]
I found the issue. I was confused for some time :confused: --I think after `Updating searchtools for Read the Docs search...` we should show `... done` or similar to avoid this.

You have https://github.com/GlacioHack/marutils/blob/dev/.readthedocs.yml#L11 enabled, and there is a warning: `WARNING: html_static_path entry '_static' does not exist`

So, either, disable the fail on warning, or remove `_static` from `html_static_path`

Feel free to reopen if needed.
