### ISSUE TITLE
Excessive Memory while writing outputs to RST files 

### ISSUE THREAD

**Issue by peterrwilson99** [readthedocs/readthedocs.org#7936]
## Details

* Read the Docs project URL: https://besos.readthedocs.io/en/ipynb-rtd-integration/
* Build URL (if applicable): https://readthedocs.org/projects/besos/versions/
* Read the Docs username (if applicable): peterrwilson99

## Expected Result

A successful build of the ipynb-rtd-integration branch

## Actual Result

'Command killed due to excessive memory consumption 

The build fails while writing the output to the RST files generated by nbconvert locally. We recently were expanding our examples on readthedocs, where we now have over 40 RST files on this new branch. 
![Screen Shot 2021-02-19 at 11 36 24 AM](https://user-images.githubusercontent.com/57307032/108552843-b4e55c80-72a6-11eb-8f73-e98adfb07933.png)

**Comment by humitos** [comment]
Hi @peterrwilson99! I moved your project to our bigger builders and the memory issue disappeared. However, you still have a problem with PDF builds that you may take a look: https://readthedocs.org/projects/besos/builds/13074644/

**Comment by peterrwilson99** [comment]
Thank you!
