### ISSUE TITLE
Update getting started docs to point to Myst instead of recommonmark

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#7937]
[Myst](https://myst-parser.readthedocs.io/en/latest/index.html) is a more maintained and feature complete version of markdown for Sphinx. We should probably deprecate recommonmark, and repoint users to Myst. This includes updating our recommonmark repo, along with pointing users towards MyST in our `docs/intro/getting-started-with-sphinx.rst#using-markdown-with-sphinx` section.

**Comment by Pradhvan** [comment]
@ericholscher hi 👋🏾  I have updated the `docs/intro/getting-started-with-sphinx.rst#using-markdown-with-sphinx` and added Myst in the `Using Markdown with Sphinx` section. 

Though recommonmark is used throughout the project so migration to Myst would be in the same PR?
