### ISSUE TITLE
Additional steps to setup a custom domain previously from gitbook

### ISSUE THREAD

**Issue by FatGrizzly** [readthedocs/readthedocs.org#7939]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/infinitzhost/
* Build URL (if applicable): https://support.infinitzhost.com
* Read the Docs username (if applicable): soundarrr

## Expected Result
The mkdocs should be served in my custom domain.
## Actual Result
It just redirects to my old gitbook knowledgebase, ah yeah, dont accuse me for dns propagation, its been 24 hours and I can confirm that it has propagated 
https://www.whatsmydns.net/#CNAME/support.infinitzhost.com

Even the SSL state is active, probably a bug.

**Comment by humitos** [comment]
It seems the domain was managed by gitbook at some point. I know we recently had a similar problem with another domain and @davidfischer figured it out. I didn't track it completely and I'm not sure what was the exact problem/solution, but there is some history in https://github.com/readthedocs/readthedocs.org/pull/7801

@davidfischer do you know what the user/us have to do here to make the custom domain to work?

**Comment by davidfischer** [comment]
@FatGrizzly, you're right that this is extremely bizarre and we tracked it down to a Cloudflare/GitBook.com bug ([relevant forum post](https://community.cloudflare.com/t/dns-subdomain-no-longer-works-nor-redirects-to-anything/240984)). Basically, for some "partners" like GitBook.com, Cloudflare seems to be doing some magic with DNS resolution and directing HTTP traffic.

Even though when we query DNS, your setup looks correct and we are even able to issue the certificate, you still can't reach it. While your DNS has propagated, when you do an HTTP request (eg. `curl -IL https://support.infinitzhost.com/`), it never reaches Read the Docs' servers. The previous person who had this problem fixed it by reaching out to both Cloudflare and GitBook support. I'm sorry I am not more helpful but hopefully that gives you enough to fix it.

**Comment by FatGrizzly** [comment]
Hmm, thanks for the reply, I will contact gitbook soon and let's see what happens

**Comment by FatGrizzly** [comment]
Fixed this by contacting gitbook support, and why not add a small warning for previous gitbook users in rtd?

**Comment by stsewd** [comment]
yeah, we could have an entry in the docs. A PR with the process you followed is welcome!

**Comment by FatGrizzly** [comment]
#7945
