### ISSUE TITLE
"Aborted (core dumped)" on sphinx build

### ISSUE THREAD

**Issue by neuromusic** [readthedocs/readthedocs.org#7942]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/spacetx-starfish/
* Build URL (if applicable): https://readthedocs.org/projects/spacetx-starfish/builds/13079448/
* Read the Docs username (if applicable): neuromusic

## Expected Result

I expected the branch to build, as it does locally...

```
(starfish-docs) √ docs % make html 
Running Sphinx v3.5.1
making output directory... done
generating gallery...
Using Sphinx-Gallery to convert rst text blocks to markdown for .ipynb files.
generating gallery for gallery/quick_start... [100%] plot_quick_start.py        
generating gallery for gallery/data_formatting... [ 50%] plot_format_structured_generating gallery for gallery/data_formatting... [100%] plot_format_tilefetcher.py
generating gallery for gallery/data_formatting_examples... [ 12%] 
...
```

## Actual Result

The build fails with a "core dump" as soon as sphinx-gallery starts generating examples...

(from RTD build output)
```
Running Sphinx v3.5.1
loading translations [en]... done
making output directory... done
generating gallery...
Using Sphinx-Gallery to convert rst text blocks to markdown for .ipynb files.
generating gallery for gallery/quick_start... [100%] plot_quick_start.py
Aborted (core dumped)
```

**Comment by humitos** [comment]
Hi @neuromusic! We don't have much more logs than the ones reported in the build output for this case. I'd say it's a OOM issue, probably. Are you doing lot of processing in those ipynb/gallery files?

Can you do a memory profile locally and check how much memory consumes building your docs?

**Comment by neuromusic** [comment]
> We don't have much more logs than the ones reported in the build output for this case.

OK, that's good to know.

I'd be surprised if its an OOM issue... this exact pipeline was building fine until we added one new dependency.

HOWEVER, my colleague reminded me that we had to [specify additional libraries in our Travis config & specify a display](https://github.com/spacetx/starfish/blob/master/.travis.yml#L64)

>       before_install:
>        - sudo apt-get install -y libgl1-mesa-glx libqt5x11extras5 xvfb
>       - make install-dev
>        - pip install .[napari] pytest-qt
>        - pip freeze
>        - export DISPLAY=:99
>        - Xvfb $DISPLAY -ac -screen 0 1024x768x24 &
>        - sleep 10

Might this be the culprit? 

And is it possible to do something similar on RTD?

**Comment by humitos** [comment]
> this exact pipeline was building fine until we added one new dependency.

What's the dependency? Is it possible to isolate the problem in two different branches as test? One branch without the dependency (passing build) and another branch with the dependency (failing build).

> HOWEVER, my colleague reminded me that we had to [specify additional libraries in our Travis config & specify a display](https://github.com/spacetx/starfish/blob/master/.travis.yml?rgh-link-date=2021-02-23T20%3A21%3A01Z#L64)

Read the Docs does not support installing packages via `apt`. Are those packages _required_ to build the documentation?
