### ISSUE TITLE
Readthedocs documentation is not updated

### ISSUE THREAD

**Issue by nndiaye-ledger** [readthedocs/readthedocs.org#7950]
## Details

* Read the Docs project URL:https://github.com/LedgerHQ/ledger-dev-doc
* Build URL (if applicable):https://readthedocs.org/projects/ledger/builds/12935180/
* Read the Docs username (if applicable):nndiaye-ledger
* Documentation URL: https://ledger.readthedocs.io/en/latest/userspace/debugging.html

## Expected Result

The latest build was successful and include the commit with our last changes. When built locally, the generated HTML pages show the last changes.

## Actual Result

But the online documentation page is never updated

**Comment by FatGrizzly** [comment]
#7917 Rebuilding again should solve the issue.

**Comment by stsewd** [comment]
Hi @nndiaye-ledger as mentioned this is the same error as #7917, can be solved by rebuilding your project, sorry for the trouble!
