### ISSUE TITLE
Autodoc does not work "cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by mwerezak** [readthedocs/readthedocs.org#7954]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/dearpygui-obj/
* Build URL (if applicable): https://dearpygui-obj.readthedocs.io/en/latest/
* Read the Docs username (if applicable):

## Expected Result

I wanted autodoc to import my modules and produce documentation.

## Actual Result

*A description of what actually happened*

The build passes, but:

```
WARNING: autodoc: failed to import module 'dearpygui_obj'; the following exception was raised:
libpython3.8.so.1.0: cannot open shared object file: No such file or directory
```
and so on...

The shared object is not a dependency of my project, but seems to be coming from my main dependency (`dearpygui`). I have no idea how to supply the .so so that it can actually produce documentation.

Everything works fine locally of course, it's only on RTD that it fails.

**Comment by stsewd** [comment]
Hi, if that dep isn't required to build your docs you can mock it and not install in on rtd https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules or use something like https://github.com/readthedocs/sphinx-autoapi

**Comment by mwerezak** [comment]
Thanks! I did not know about that autodoc functionality. I used it to mock out dearpygui and now it works!
