### ISSUE TITLE
Lots of failing builds

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#7956]
## Details

* Read the Docs project URL: https://frc-docs.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/frc-docs/builds/13100517/
* Read the Docs username (if applicable): daltz333

## Expected Result

Successful build

## Actual Result

Failed build:

https://readthedocs.org/projects/frc-docs/builds/13100517/
https://readthedocs.org/projects/frc-docs/builds/13098678/

Ideally, I'd prefer this to report a "failed" status back to GitHub.

**Comment by humitos** [comment]
> Ideally, I'd prefer this to report a "failed" status back to GitHub.

Isn't it reporting anything? I mean, you still see a yellow dot on GitHub next to the commit?

**Comment by Daltz333** [comment]
It reports back a yellow dot saying "status is awaiting to be reported". Ideally since RTD failed, it failed. We have ReadTheDocs has a required build check before merging documentation, and it really bites us sometimes.

**Comment by stsewd** [comment]
I can see they are always passing now, probably a temporal error. For the status report, please subscribe to https://github.com/readthedocs/readthedocs.org/issues/8177 or https://github.com/readthedocs/readthedocs.org/issues/6524
