### ISSUE TITLE
ERROR: No matching distribution found for orjson==2.0.7

### ISSUE THREAD

**Issue by alex4200** [readthedocs/readthedocs.org#7958]
## Details

* Read the Docs project URL: https://docs.readthedocs.io/en/stable/development/install.html
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

When I follow the instructions I expect the following command to succeed, in order to install all requirements for a local RTD installation:

`pip install -r requirements.txt` 

## Actual Result

```
ERROR: Could not find a version that satisfies the requirement orjson==2.0.7
ERROR: No matching distribution found for orjson==2.0.7
```

on Ubuntu 20.04.1

My guess: `requirements/pip.txt` needs to be fixed

**Comment by humitos** [comment]
Hi @alex4200! That documentation is probably out of date and we are not using that stack anymore for local development. I strongly recommend you to give it a try to https://docs.readthedocs.io/en/stable/development/standards.html which is what we are using currently.

I think we should probably delete that page at this point.

**Comment by stsewd** [comment]
This probably due to your python version I think.
