### ISSUE TITLE
HTML files not found during ES reindex

### ISSUE THREAD

**Issue by 2Fake** [readthedocs/readthedocs.org#7959]
## Details
Hi,
i try to set up readthedocs locally to start developing. I encountered just one problem. 
I was able to run readthedocs. Everything is fine, i can build documentation etc, but readthedocs reports only the projects to elasticsearch. If readthedocs is looking for HTML files it always find 0 documents.

Do you have an idea, why readthedocs cant find the HTML files?

```
[25/Feb/2021 11:11:42] elasticsearch:263[487]: INFO PUT http://search:9200/read_the_docs_pages_20210225111138 [status:200 request:0.437s]
[25/Feb/2021 11:11:42] readthedocs.search.management.commands.reindex_elasticsearch:74[487]: INFO Temporal index created: read_the_docs_pages_20210225111138
[25/Feb/2021 11:11:42] readthedocs.search.management.commands.reindex_elasticsearch:88[487]: INFO Tasks issued successfully. model=projects.HTMLFile items=0
```

## Expected Result

HTML files are found and indexed

## Actual Result

HTML files are not found

**Comment by humitos** [comment]
Hi @2Fake! Can you explain a little more the steps you followed? In particular, are you running RTD with the docker based setup as explained here https://docs.readthedocs.io/en/stable/development/standards.html?

**Comment by 2Fake** [comment]
hi @humitos  Yes i run it in a docker based setup, but not as described in the link you mentioned, because i didn' found this document at my starting point. I set up everything as described here (https://docs.readthedocs.io/en/stable/development/install.html)
I saw that there is already a ticket to gelete this page as this setup is valid anymore, but i build docker containers around that description. 
I have docker containers for nginx, rtd, celery, elasticsearch and redis and they are working fine together except that HTML file indexing to elasticsearch is not working and i have no clue, why. The log snippet is from the command

´´´
python manage.py reindex_elasticsearch
´´´

**Comment by 2Fake** [comment]
Ok, will try this and come back. Thank you!

**Comment by stsewd** [comment]
Do you have HTMLFile objects in your db? HTMLFile.objects.all().count()

**Comment by 2Fake** [comment]
@stsewd No my HTMLFile count is at 0. I saw a difference between the rTD docher contianer startup and my startup of the containers. When the RTD container starts, they trigger this task for Celery 
```
readthedocs.builds.tasks:67[2142]: INFO Skipping routing non-build task. task=readthedocs.search.tasks.index_objects_to_es
```
Is this may this missing link, why my HTML files are empty? Why isn't my RTD container triggering this task at startup?

**Comment by humitos** [comment]
@2Fake sorry, I should have pasted the link here. This is the guide that you should be following: https://docs.readthedocs.io/en/stable/development/standards.html

**Comment by stsewd** [comment]
@2Fake maybe a setting https://github.com/readthedocs/readthedocs.org/blob/master/docs/development/settings.rst#elasticsearch_dsl_autosync but as mentioned you should be using our docker images as reference.
