### ISSUE TITLE
Error: custom CSS not loading on starting page ("/")

### ISSUE THREAD

**Issue by lorenzoamici** [readthedocs/readthedocs.org#7961]
## Details

* Read the Docs project URL: https://gis4schools.readthedocs.io/en/latest/
* Build URL (if applicable): 
* Read the Docs username (if applicable): yedi

## Expected Result

I have a custom CSS file that is applied everywhere but in the homepage built by ReadTheDocs (served at "/")

## Actual Result

The CSS is not loaded and a MIME error is thrown in the console. The problem seems to be given because in the code of the homepage ("/") the name of the CSS file is style.css, but my file is actually called my_theme.css

**Comment by stsewd** [comment]
I can see the file loading correctly at https://gis4schools.readthedocs.io/en/latest/
![Screenshot from 2021-02-25 09-50-40](https://user-images.githubusercontent.com/4975310/109170639-f8304700-774e-11eb-8c13-c145c8cfca6d.png)

**Comment by lorenzoamici** [comment]
It's currently working! Thank you, sorry for the disturb

**Comment by stsewd** [comment]
This was probably to a local cache or our cache (it should take a couple of seconds to purge after a build). If you this again, you can try a hard refresh (ctrl + f5).
