### ISSUE TITLE
Docs Build "RuntimeError: Working outside of application context."

### ISSUE THREAD

**Issue by alexdlaird** [readthedocs/readthedocs.org#7976]
I recently renamed my branches from `master` to `main` on _two_ repositories—`pyngrok` and `hookee`. The `pyngrok` docs still build just fine, the `hookee` docs error with the following:

```
Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/hookee/envs/latest/lib/python3.7/site-packages/Flask-1.1.2-py3.7.egg/flask/globals.py", line 52, in _find_app
    raise RuntimeError(_app_ctx_err_msg)
RuntimeError: Working outside of application context.
```

What's interesting is this error is now across _all_ branches, even old ones. I tried building the last release tag (2.0.2), and it also fails with this same warning despite not code or branch changes there.

Any idea what's going on here? My suspicion is that this has nothing to do with the branch rename, since `pyngrok` is building just fine, and that it's just something that started happening due to some recent change, which is why I'm asking here.

Failing `hookee` build: https://readthedocs.org/projects/hookee/builds/13144687/
Passing `pyngrok` build (same branch rename changes): https://readthedocs.org/projects/pyngrok/builds/13144686/

**Comment by stsewd** [comment]
> What's interesting is this error is now across all branches, even old ones. I tried building the last release tag (2.0.2), and it also fails with this same warning despite not code or branch changes there.

That points to an unpinned dependency

https://github.com/alexdlaird/hookee/blob/main/docs/requirements.txt or from https://github.com/alexdlaird/hookee/blob/main/requirements.txt

You can try replicating this by building your project locally in a clean environment.

**Comment by alexdlaird** [comment]
I should have clarified that I had already tried building locally on the same branches / checking out the same Git tags. No errors locally.

**Comment by alexdlaird** [comment]
Comparing installed dependencies from [passing](https://readthedocs.org/projects/hookee/builds/12649574/) and [failing](https://readthedocs.org/projects/hookee/builds/13144687/) builds:

Passing Build Install Command: `/home/docs/checkouts/readthedocs.org/user_builds/hookee/envs/latest/bin/python -m pip install --upgrade --no-cache-dir setuptools==41.0.1  mock==1.0.1 pillow==5.4.1 alabaster>=0.7,<0.8,!=0.7.5 six commonmark==0.8.1 recommonmark==0.5.0 sphinx<2 sphinx-rtd-theme<0.5 readthedocs-sphinx-ext<2.2`
Result: `Successfully installed Jinja2-2.11.2 MarkupSafe-1.1.1 Pygments-2.7.3 alabaster-0.7.12 babel-2.9.0 certifi-2020.12.5 chardet-4.0.0 commonmark-0.8.1 docutils-0.16 future-0.18.2 idna-2.10 imagesize-1.2.0 mock-1.0.1 packaging-20.8 pillow-5.4.1 pyparsing-2.4.7 pytz-2020.5 readthedocs-sphinx-ext-2.1.1 recommonmark-0.5.0 requests-2.25.1 setuptools-41.0.1 six-1.15.0 snowballstemmer-2.0.0 sphinx-1.8.5 sphinx-rtd-theme-0.4.3 sphinxcontrib-serializinghtml-1.1.4 sphinxcontrib-websupport-1.2.4 urllib3-1.26.2`

Failing Build Install Command: `/home/docs/checkouts/readthedocs.org/user_builds/hookee/envs/latest/bin/python -m pip install --upgrade --no-cache-dir  mock==1.0.1 pillow==5.4.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.8.1 recommonmark==0.5.0 sphinx<2 sphinx-rtd-theme<0.5 readthedocs-sphinx-ext<2.2`
Result: `Successfully installed Jinja2-2.11.3 MarkupSafe-1.1.1 Pygments-2.8.0 alabaster-0.7.12 babel-2.9.0 certifi-2020.12.5 chardet-4.0.0 commonmark-0.8.1 docutils-0.16 future-0.18.2 idna-2.10 imagesize-1.2.0 mock-1.0.1 packaging-20.9 pillow-5.4.1 pyparsing-2.4.7 pytz-2021.1 readthedocs-sphinx-ext-2.1.3 recommonmark-0.5.0 requests-2.25.1 six-1.15.0 snowballstemmer-2.1.0 sphinx-1.8.5 sphinx-rtd-theme-0.4.3 sphinxcontrib-serializinghtml-1.1.4 sphinxcontrib-websupport-1.2.4 urllib3-1.26.3`

Only difference in the command at this point appears to be that ReadTheDocs is now pinning `setuptools`. Then RTD install my reqs file, `pip install -r requirements.txt`. At this point all reqs are satisfied except `sphinx_notfound_page`, where the passing build pulls v0.5 and the failing build pulls v0.6. This failing stacktrace begins in the autodoc code, which is why I raised this. Even if it's a pinning issue due to some now out of sync dependency, it might be an issue others also start seeing.

I will continue to investigate these differences.

**Comment by alexdlaird** [comment]
Alright, after pinning various entries in `setup.py`, I isolated the issue to `itsdangerous` getting bumped to `2.0.0rc1`. I don't use this dependency directly, it comes from `Flask` `1.1.2` pinning it only as `>=0.24`, and the new RC seems to be incompatible with my build.

I solved this (for now) by adding `itsdangerous<=1` to my `setup.py`, though I think I'll need to keep an eye on `Flask` and `itsdangerous` to see if this is resolved in the future, as I'd rather not have this in my `setup.py`.

**Comment by alexdlaird** [comment]
Worth noting this issue opened with Flask appears related: https://github.com/pallets/flask/issues/3909

**Comment by stsewd** [comment]
@alexdlaird thanks for the research, we already install the latest version of setuptools, you can see in your logs

> Requirement already satisfied: setuptools in /home/docs/checkouts/readthedocs.org/user_builds/hookee/envs/latest/lib/python3.7/site-packages (54.0.0)

https://pypi.org/project/setuptools/ww

**Comment by alexdlaird** [comment]
Interesting. Then I'm unsure what this adding `yaml` config fixed my build, but at least the issue is resolved for me. Old builds still fail if I retry them, so something in the defaults has still changed that is causing pre-release packages to be selected when I don't think they should be, but that's not a huge deal for my project. Might be something to keep an eye on though.

**Comment by stsewd** [comment]
Looks like what fixed it was installing the project with pip instead of using `setup.py install`, installing projects using pip is recommended over setup.py install. Also, we recommend using the v2 of the config file https://docs.readthedocs.io/en/stable/config-file/v2.html, you get more config options ans some other features :)
