### ISSUE TITLE
Enable DONT_SHALLOW_CLONE for PlasmaPy

### ISSUE THREAD

**Issue by StanczakDominik** [readthedocs/readthedocs.org#7980]
* Read the Docs project URL: https://readthedocs.org/projects/plasmapy/
* Read the Docs username (if applicable): StanczakDominik

Hi, I'd like to ask for DONT_SHALLOW_CLONE to be set for PlasmaPy as discussed previously for other projects at https://github.com/readthedocs/readthedocs.org/issues/5031. In https://github.com/PlasmaPy/PlasmaPy/pull/1052 we realized this causes setuptools_scm to show the wrong version on https://docs.plasmapy.org/en/latest (see the HTML <title> tag) and in PR builds such as https://plasmapy--1052.org.readthedocs.build/en/1052/whatsnew/0.6.0.html.

I worry a bit about the drain on your resources - with --depth 1, the repo is 21MB, while without the --depth flag it's 32MB. Times however many builds in a day, times the number of projects building their docs on RTD, I suppose it adds up. I really don't want RTD to go the way of TravisCI. However, I wasn't able to find a sensible workaround. :disappointed:

**Comment by stsewd** [comment]
> I worry a bit about the drain on your resources

Thanks for worrying, I think we are doing fine for now :)

I have triggered a new build, is doing a full clone now https://readthedocs.org/projects/plasmapy/builds/13160999/

**Comment by StanczakDominik** [comment]
Thanks! :)
