### ISSUE TITLE
Inquiry: Were tag versions being hidden / not being built by default starting October 2020?

### ISSUE THREAD

**Issue by ChoiByungWook** [readthedocs/readthedocs.org#7987]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/sagemaker/
* Build URL (if applicable): https://readthedocs.org/projects/sagemaker/builds/12137897/
* Read the Docs username (if applicable):

## Expected Result

We expect all tag versions that are pushed to our [Github repository](https://github.com/aws/sagemaker-python-sdk/tags) to have corresponding readthedoc versions.

For now, I've gone and activated the versions manually.

## Actual Result

We noticed that starting at around October 19th 2020, that versions in our project weren't being put into an active state. Usually all tags that we pushed to our Github project would have corresponding updated readthedocs, however all versions that were pushed after 10/19/20 stopped being built/active.

I believe nothing changed on our end and looking through the readthedoc's changelog, I can't seem to find any corresponding change that may have caused all future versions to not be considered active.

[States](https://docs.readthedocs.io/en/stable/versions.html#states) seem to have been introduced before October 2020: https://github.com/readthedocs/readthedocs.org/blob/HEAD/CHANGELOG.rst#version-418

And other changes to the hidden state in the automation rule don't line up with our timeline: https://github.com/readthedocs/readthedocs.org/blob/HEAD/CHANGELOG.rst#version-521

Was there a change that happened to readthedocs around October 2020 that defaulted versions to not be active?

Did we hit a limit on active versions?

For now, I've added an [automation rule](https://readthedocs.org/dashboard/sagemaker/rules/) to activate all future tag versions, however I believe this used to be done without the automation rule, so I'm a bit confused about what caused this to happen.

Thanks!

**Comment by stsewd** [comment]
As long as your versions follow https://www.python.org/dev/peps/pep-0440/ and your new tag is greater than the "stable" one you shouldn't need an automation rule. We use https://pypi.org/project/packaging/ to parse and compare versions. So, this may be because:

- your webhook isn't working (maybe not since your builds are working?)
- There is a version greater than your other versions, so they don't get activated (this one is the most likely)

**Comment by ChoiByungWook** [comment]
> As long as your versions follow [python.org/dev/peps/pep-0440](https://www.python.org/dev/peps/pep-0440/) and your new tag is greater than the "stable" one you shouldn't need an automation rule. We use [pypi.org/project/packaging](https://pypi.org/project/packaging/) to parse and compare versions. So, this may be because:
> 
> * your webhook isn't working (maybe not since your builds are working?)
> * There is a version greater than your other versions, so they don't get activated (this one is the most likely)

Our tagging version follows the [semantic versioning but appends a v](https://semver.org/#is-v123-a-semantic-version) to the front, so I'm not sure if should be built/active by default, since the semvar document deems they don't follow semantic versioning due to the v, however they used to be.

> * There is a version greater than your other versions, so they don't get activated (this one is the most likely)

Our last successful build was for 2.15.2 on our end.

We're currently on 2.29.0, and those from 2.15.3 to 2.29.0 have never been built/active. I just went in today and manually activated all of those.

It sounds like the versions after should have been built, since 2.15.3 > 2.15.2?

**Comment by ChoiByungWook** [comment]
We just released a new version to PyPI: https://pypi.org/project/sagemaker/2.29.1/ and I noticed that the automation rule kicked in, however a build was already started by ReadTheDocs, so it failed as a duplicate.

Custom automation rule, that failed as duplicate: https://readthedocs.org/projects/sagemaker/builds/13201770/
Automatic default ReadTheDocs build: https://readthedocs.org/projects/sagemaker/builds/13201768/

I'm not too sure what is going on, but I'm wondering if maybe the ReadTheDocs server side had ran into issues with an older previous build (2.15.3?) that was causing it to not automatically run builds for new versions, even though it seems to be a greater number than the last built one.

**Comment by stsewd** [comment]
yeah, it may have been an old tag that was around or a tag that wasn't meant to be pushed. About the duplicate build, I think we maybe want to disable that "automatic" rule if the project is using automation rules.

**Comment by ChoiByungWook** [comment]
@stsewd gotcha. I think it is probably worth on our end setting up alarms for corresponding versions. I am tempted to keep the automation rule in, however I imagine it can also run into the original issue where the ReadTheDocs backend ran into issues and wasn't able to continue automatically building.
