### ISSUE TITLE
"mysql_config: not found" but Dockerfile does include "libmysqlclient-dev"

### ISSUE THREAD

**Issue by FrancescoCasalegno** [readthedocs/readthedocs.org#7990]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/blue-brain-search/
* Build URL (if applicable): https://readthedocs.org/projects/blue-brain-search/builds/13169816/
* Read the Docs username (if applicable): FrancescoCasalegno

## Expected Result

I would expect `pip install .[dev]` to run successfully without any issue. 

The only tricky point is the `mysqlclient` dependency in the `setup.py`, because this package [requires a C system library](https://stackoverflow.com/a/51511294) and I read that RTD ["does not support installing random C libraries"](https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules). 
However this should not be an issue for the following reasons:
1. The only C system library I need is `libmysqlclient-dev` and the RTD `Dockerfile` [seems to include it](https://github.com/readthedocs/readthedocs-docker-images/blob/master/Dockerfile#L35)
2. I tried to `docker pull readthedocs/build:latest` and run the various commands locally, and everything worked fine. The `mysql_config` is also clearly there:
```yml
docs@27e903412d0f:/$ file /usr/bin/mysql_config 
/usr/bin/mysql_config: POSIX shell script, ASCII text executable
```

## Actual Result

The RTD build fails when trying to install the `mysqlclient` dependency, saying `mysql_config: not found`.

**Comment by humitos** [comment]
I'm closing this issue we can continue the discussion in https://github.com/readthedocs/readthedocs-docker-images/issues/158
