### ISSUE TITLE
Document `page` and `page_size` for server side search API

### ISSUE THREAD

**Issue by raghav-binary** [readthedocs/readthedocs.org#8006]
## How can I set Limit and offset to pagination to server side search API? 

* The documentations provide no reference to adding a limit or offset to search API. They do have the **"page"** query parameter to jump to a page, but the default limit per page is set to **50 records**. 
* Is there any way we can change the limit to our expected value and also the offset? 

Reference: 

1.  [Server side API Docs](https://docs.readthedocs.io/en/stable/server-side-search.html#api)

**Comment by stsewd** [comment]
Hi @raghav-binary you can use `page_size` to limit the results, we should document that.

**Comment by raghav-binary** [comment]
Hey @stsewd Thanks. It's working as expected now with page and page_size.
Closing this issue.

**Comment by stsewd** [comment]
Great, we should document that, so I'm keeping this issue, feel free to unsubscribe!

**Comment by raghav-binary** [comment]
Hi @stsewd,  apart from the page and page_size combination, do we have Limit and Offset for this API as of now?

**Comment by stsewd** [comment]
> Hi @stsewd, apart from the page and page_size combination, do we have Limit and Offset for this API as of now?

No, we don't support that. I think page and page_size should be enough for the use case of search.
