### ISSUE TITLE
proxito: build_media_storage.url() with http_method breaks storage interop

### ISSUE THREAD

**Issue by bplotnick** [readthedocs/readthedocs.org#8013]
## Details

This is a pretty minor bug overall, but the [following](https://github.com/readthedocs/readthedocs.org/blob/master/readthedocs/proxito/views/serve.py#L157) line uses the `http_method` argument that only appears to be available in the S3 django-storages backend:

```python
storage_url = build_media_storage.url(path, http_method=request.method)
```

I'm not sure how much you want to focus on interop, but so far this is the only issue i've seen. I also don't know why the http method is needed in this call.

## Expected Result

I would think that the function signatures should be consistent amongst storage backends, so they could be swapped out as needed, but in fact this argument isn't available in all of the backends.

## Actual Result

```
TypeError: url() got an unexpected keyword argument 'http_method'
```

**Comment by humitos** [comment]
Thanks! We are aware of this already. We used to run the same code with AWS S3 _and_ Azure BlobStorage as backend. At that time we override this class to ignore the `http_method` attribute.

https://github.com/readthedocs/readthedocs.org/blob/3d3b9d298545b0ce8d721afaef000f670c424eab/readthedocs/storage/azure_storage.py#L27

Then we migrated completely to S3 and we don't require that override anymore.

**Comment by bplotnick** [comment]
Cool! That's exactly the override i wrote to get this to work (for GCS). Feel free to close this issue given the straightforward workaround.

**Comment by humitos** [comment]
Thanks!
