### ISSUE TITLE
pull request documentation build

### ISSUE THREAD

**Issue by shahzebsiddiqui** [readthedocs/readthedocs.org#8033]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/buildtest/
* Build URL (if applicable): https://readthedocs.org/projects/buildtest/builds/13281209/
* Read the Docs username (if applicable): shahzebmsiddiqui

## Expected Result

I should see readthedocs build in github CI shown in fig 6 see https://docs.readthedocs.io/en/stable/pull-requests.html#features

If you see my PR https://github.com/buildtesters/buildtest/pull/694 i don't see the readthedocs icon. I can see the build is coming through on readthedocs and its building the docs on the PR. 
![Screen Shot 2021-03-18 at 12 49 43 PM](https://user-images.githubusercontent.com/12942230/111664703-6b762780-87e8-11eb-92ed-e6810ae8e03f.png)

I have recreated my webhook mentioned in https://docs.readthedocs.io/en/stable/webhooks.html#github i and i see my payload is working fine. I noticed that `Pull requests` button was not enabled in the instructions when i did `push` it didn't work for me.

Shown below is my webhook settings for buildtest. 

![Screen Shot 2021-03-18 at 12 51 52 PM](https://user-images.githubusercontent.com/12942230/111664990-b859fe00-87e8-11eb-98aa-ee1dec34b308.png)
![Screen Shot 2021-03-18 at 12 52 04 PM](https://user-images.githubusercontent.com/12942230/111665022-bf810c00-87e8-11eb-8116-ecb7e4d50c69.png)
 
![Screen Shot 2021-03-18 at 12 52 16 PM](https://user-images.githubusercontent.com/12942230/111665043-c60f8380-87e8-11eb-8653-a29ea9676381.png)

This is my admin settings in readthedocs it has **Build pull requests for this project** enabled. 
![Screen Shot 2021-03-18 at 12 53 06 PM](https://user-images.githubusercontent.com/12942230/111665184-e63f4280-87e8-11eb-9bdc-679e1548190f.png)

I looked at the troubleshooting guide https://docs.readthedocs.io/en/stable/pull-requests.html#troubleshooting and i can't find the ReadtheDocs oath app in my buildtest project settings its not clear where i will see this.

I can confirm my readthedocs user is connected to github 
![Screen Shot 2021-03-18 at 12 54 58 PM](https://user-images.githubusercontent.com/12942230/111665466-27cfed80-87e9-11eb-9843-94d3af184419.png)

I can see readthedocs application is shown in my personal account but i can't see it when i switch accounts to **buildesters** organization
![Screen Shot 2021-03-18 at 12 57 27 PM](https://user-images.githubusercontent.com/12942230/111665829-809f8600-87e9-11eb-9c88-9988203ecfd3.png)

I have tried reopening this PR few times to see if CI checks will show up in github checks but it hasn't shown up. 

![Screen Shot 2021-03-18 at 1 01 23 PM](https://user-images.githubusercontent.com/12942230/111666533-3074f380-87ea-11eb-9b04-eb2117ac8bfa.png)

![Screen Shot 2021-03-18 at 1 01 36 PM](https://user-images.githubusercontent.com/12942230/111666414-1509e880-87ea-11eb-8e1e-9b9a5d7676c5.png)

I can see there was another build triggered in readthedocs so i am not sure what the issue can you please help me out.

![Screen Shot 2021-03-18 at 1 03 20 PM](https://user-images.githubusercontent.com/12942230/111666689-54d0d000-87ea-11eb-91a0-5846d56900a1.png)

**Comment by sklam** [comment]
I'm seeing similar issue for https://readthedocs.org/projects/numba/.

**Comment by stsewd** [comment]
> I looked at the troubleshooting guide https://docs.readthedocs.io/en/stable/pull-requests.html#troubleshooting and i can't find the ReadtheDocs oath app in my buildtest project settings its not clear where i will see this.

This in the settings of your github account.

> I can see readthedocs application is shown in my personal account but i can't see it when i switch accounts to buildesters organization

The image you show below this paragraph is the one you are looking for. You need to clink on the Read the Docs app and check that it has permissions over your organization "Organization access". The link is in the docs https://github.com/settings/applications

**Comment by shahzebsiddiqui** [comment]
Thanks @stsewd that did the trick. I was able to grant access to the buildesters project it was disabled. 
<img width="876" alt="Screen Shot 2021-03-24 at 9 27 15 PM" src="https://user-images.githubusercontent.com/12942230/112404955-b65fd580-8ce7-11eb-8595-7f259277e715.png">


Once that was done i see the CI check from readthedocs in my PR see: https://github.com/buildtesters/buildtest/pull/704
<img width="969" alt="Screen Shot 2021-03-24 at 9 28 12 PM" src="https://user-images.githubusercontent.com/12942230/112405014-d8595800-8ce7-11eb-9b82-90d3886910d3.png">

Thanks for your help. @sklam this may be same issue with numba project. I am going to close this issue now that it works!

**Comment by sklam** [comment]
After recreating the webhooks a few times, it was working again. I didn't realize RTD is automatically inserting webhook into Github for me. So, I have two active RTD webhooks. I also noticed that the RTD auto-created webhooks are different from the documentation (https://docs.readthedocs.io/en/stable/webhooks.html) that the "secret" field is not blank.

**Comment by humitos** [comment]
> I also noticed that the RTD auto-created webhooks are different from the documentation ([docs.readthedocs.io/en/stable/webhooks.html](https://docs.readthedocs.io/en/stable/webhooks.html)) that the "secret" field is not blank.

We should update that section of the documentation. We are sending the secret now in this line: https://github.com/readthedocs/readthedocs.org/blob/901100594bf6549eda973be84b1ab7ad44379d64/readthedocs/oauth/services/github.py#L205

**Comment by stsewd** [comment]
> I'm not 100% sure how we should update that. I don't think we are exposing the secret value to the user to copy and paste on GitHub, cc @stsewd ?

So, we don't create the secret when the webhook is created manually, and also we don't show it in the UI. I brought that a time ago, but I don't remember the arguments against showing it. Guess the UX? like this is an extra step for the user.
