### ISSUE TITLE
Filter by branch on project dashboard

### ISSUE THREAD

**Issue by pllim** [readthedocs/readthedocs.org#8053]
## Details

Would be nice if there is a way to only show builds from certain branches. This is especially useful if a project has PR builder activated, which sometimes results in the build log full of PR builds, so it takes many clicks to find the last run of, say, `latest`.

![Screenshot 2021-03-26 131441](https://user-images.githubusercontent.com/2090236/112668896-6727bb00-8e35-11eb-8b13-c07ea3c1d868.jpg)

## Expected Result

A new drop-down menu that let me only see builds from the select branch.

## Actual Result

I have to click a few pages to find the last `latest` build. The drop-down is only to select branch to trigger new build for, and does not affect what I see on the dashboard.

**Comment by humitos** [comment]
This sounds like a good UX improvement. There is going to be a lot of changes to the build listing page, but this could be something to consider, if you haven't already @agjohnson

**Comment by agjohnson** [comment]
Yeah, this was already implemented.

**Comment by humitos** [comment]
This is not possible in our new beta dashboard. As example, this page shows only the builds for the `latest` version of Read the Docs' documentation: https://beta.readthedocs.org/projects/docs/builds/?state=&type=&version=latest

We would appreciate any feedback you may want to share with us 👍🏼

**Comment by pllim** [comment]
Thanks, @humitos ! Is this beta dashboard feature complete yet? I see two things that are not working at https://beta.readthedocs.org/projects/astropy/builds/

1. Version dropdown is not populated even when it obviously show a lot of versions when you click on "Versions" tab.
2. `Type -> Pull/merge request` results in "no results" even when I see a lot of `Pull Request N` listed when no filter is applied.

**Comment by humitos** [comment]
> Is this beta dashboard feature complete yet?

Not, yet, no. We are actively working on it still and we hope to do a public announcement of our beta soon.

I'm pinging @agjohnson here so he can read your feedback as well. Thanks 👍🏼

**Comment by agjohnson** [comment]
Thanks for the feedback @pllim !

> Type -> Pull/merge request

I hit this the other week as well, it was a bug with the build filter. This will be fixed by #10528 hopefully settled by next release or so.

> Version dropdown is not populated

The UX here is still shifting and I'm meaning to revamp this UI a bit, but this is helpful feedback. Though it does look like it is supposed to load all versions, it is actually a search filter. So, typing the name of your version will cause this filtered list to reload, hopefully with your version in the list:

[Screencast from 2023-07-24 15-11-00.webm](https://github.com/readthedocs/readthedocs.org/assets/1140183/96332f06-5b58-4790-b486-e236ced3bd8f)

There are a few things that would make this more obvious, mainly not loading anything until *after* some typing.

**Comment by pllim** [comment]
In a project with many arbitrary version names, requiring user to type it out might be too much hassle. Is there a reason why it cannot be pre-populated as dropdown?

**Comment by agjohnson** [comment]
It could include more results, but at some point we need to paginate over the API responses and this will slow the response down. I think for projects with less than 20 or 30 versions (or matches) a mostly fully populated list is possible, especially if we increase pagination limits on the request. But after around that point, search filtering is going to be a better UX anyways.

But this isn't super common either, especially given pull request versions are not included in that list. Most projects only have a handful of active versions.

The version search filter is a partial match filter currently. So at least this only requires a few key presses, not a full match, and doesn't require endless scrolling for projects that are at the more extreme end of active version counts. I agree we could probably increase the result count without degrading response time or making scrolling through results too difficult.

**Comment by pllim** [comment]
Thanks for the clarifications, @agjohnson ! It was that downward arrow that tripped me as I associate it with dropdown, not a free-form text box.

**Comment by pllim** [comment]
p.s. Any plan for dark mode? 😉

**Comment by agjohnson** [comment]
Dark mode is somewhere in the cards, but it wouldn't happen until after the beta period is wrapped up. The styles are all there at least, as part of FomanticUI, but we need to make use of them.
