### ISSUE TITLE
Improve docs on Gold subscription

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/readthedocs.org#8054]
- Emphasize going ad-free as main benefit of Gold subscription
- Clarify ad-free conditions, in particular noting that they only apply when the user is logged-in

**Comment by astrojuanlu** [comment]
Also:

> The $5 total makes it ad free for just them. For $5/mo, they can mark a project ad free.

**Comment by humitos** [comment]
We need to clarify that "to become ad-free the user requires a Gold Membership, no just a one-time donation."
