### ISSUE TITLE
Consider hiding `latest` docs

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/readthedocs.org#8055]
@ericholscher says:

> It only has docs for code that isn't deployed, so probably not providing much value to users. With PR previews, we get most of the value we previously got from `latest`. 

and I'm +1

**Comment by ericholscher** [comment]
I think this probably makes sense, unless we have a strong reason for keeping the `latest` docs around. I think now that we're on a weekly release schedule, the `stable` version is always the most valuable to users, and `latest` is mostly only useful for core devs working on docs PR's. This value is mostly filled by PR builds, so we can preview builds prior to deploying them.

**Comment by humitos** [comment]
I'm :+1: on disabling `latest`

**Comment by agjohnson** [comment]
This is a good idea, I only use `stable` docs on our docs now. :+1:

**Comment by stsewd** [comment]
+1 on hiding it.

**Comment by astrojuanlu** [comment]
I took the tiniest action possible, which was just to hide `latest`. It's still accessible, so I didn't bother adding redirects yet. Closing!
