### ISSUE TITLE
conda sphinx_rtd_theme gets superseded from pkgs/main

### ISSUE THREAD

**Issue by alexsavulescu** [readthedocs/readthedocs.org#8059]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/nrn/
* Build URL (if applicable): https://readthedocs.org/projects/nrn/builds/13377572/
* Read the Docs username (if applicable): alexsavulescu

## Expected Result

conda uses sphinx_rtd_theme from `conda-forge (0.5.1)`

## Actual Result

conda uses  sphinx_rtd_theme from `pkgs/main (0.4.3)`

## Issue
* `conda env create --quiet --name latest --file docs/conda_environment.yml` installs latest conda-forge `sphinx_rtd_theme` 
* `conda install --yes --quiet --name latest mock pillow sphinx sphinx_rtd_theme` subsequently installs `sphinx_rtd_theme` from `pkgs/main` 

## Solution?
* Is there a way not to call the `conda install` ? Everything needed is already installed with `conda create`
* Maybe using `conda config --set channel_priority false` can help? Ideally run before `conda install` since it is currently unsupported in the `environment.yml` (see https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-channels.html)

**Comment by stsewd** [comment]
I think you are hitting https://github.com/readthedocs/readthedocs.org/issues/3829, also we recommend pinning your deps https://github.com/neuronsimulator/nrn/blob/master/docs/docs_requirements.txt https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#pinning-dependencies. I have applied the solution from #3829, it's using the latest version of the theme now https://readthedocs.org/projects/nrn/builds/13384187/

**Comment by alexsavulescu** [comment]
Thanks @stsewd
