### ISSUE TITLE
readthedocs uses config of upstream project instead of forked project

### ISSUE THREAD

**Issue by jugmac00** [readthedocs/readthedocs.org#8068]
## Details

* Read the Docs project URL: https://flask-reuploaded.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/api/v2/build/13422631.txt
* Read the Docs username (if applicable): jugmac00
* github repo: https://github.com/jugmac00/flask-reuploaded.git

## Expected Result

Read the Docs builds my documentation with my configuration.

## Actual Result

Read the Docs builds my documentation with the upstream configuration ( https://github.com/maxcountryman/flask-uploads / https://flask-uploads.readthedocs.io/en/latest/ ).

So I forked `flask-uploads` due to maintainer neglected it for too long about a year ago into `Flask-Reuploaded`. I worked on the code, but did not do much with the documentation. I did not create a new sphinx conf.py but updated the old one.

Today, I tried to activate `autodoc`, which works locally, but not on Read the Docs.

The reason is ... not my configuration is used, but the configuration of the upstream project. This results in build warnings and other odd entries in the raw log like these...

```
[rtd-command-info] start-time: 2021-04-04T17:04:48.818351Z, end-time: 2021-04-04T17:04:48.907607Z, duration: 0, exit-code: 0
cat docs/conf.py
# -*- coding: utf-8 -*-
#
# Flask-Uploads documentation build configuration file, created by
# sphinx-quickstart on Thu Jul  8 14:12:15 2010.
```

That is not my project name!!!

```
# General information about the project.
project = u'Flask-Uploads'
copyright = u'2010, Matthew "LeafStorm" Frazier'
``` 

That's not me!

And finally the reason why autodoc does not work....

```

/home/docs/checkouts/readthedocs.org/user_builds/flask-reuploaded/envs/stable/lib/python3.7/site-packages/sphinx/util/nodes.py:94: FutureWarning: 
   The iterable returned by Node.traverse()
   will become an iterator instead of a list in Docutils > 0.16.
  for classifier in reversed(node.parent.traverse(nodes.classifier)):
WARNING: autodoc: failed to import class 'uploads.UploadSet' from module 'flaskext'; the following exception was raised:
No module named 'flaskext'
WARNING: autodoc: failed to import class 'uploads.UploadConfiguration' from module 'flaskext'; the following exception was raised:
No module named 'flaskext'
WARNING: autodoc: failed to import function 'uploads.configure_uploads' from module 'flaskext'; the following exception was raised:
No module named 'flaskext'
WARNING: autodoc: failed to import function 'uploads.patch_request_class' from module 'flaskext'; the following exception was raised:
No module named 'flaskext'
WARNING: autodoc: failed to import class 'uploads.AllExcept' from module 'flaskext'; the following exception was raised:
No module named 'flaskext'
WARNING: autodoc: failed to import data 'uploads.DEFAULTS' from module 'flaskext'; the following exception was raised:
No module named 'flaskext'
WARNING: autodoc: failed to import data 'uploads.ALL' from module 'flaskext'; the following exception was raised:
No module named 'flaskext'
WARNING: autodoc: failed to import data 'uploads.TEXT' from module 'flaskext'; the following exception was raised:
No module named 'flaskext'
WARNING: autodoc: failed to import data 'uploads.IMAGES' from module 'flaskext'; the following exception was raised:
No module named 'flaskext'
WARNING: autodoc: failed to import data 'uploads.AUDIO' from module 'flaskext'; the following exception was raised:
No module named 'flaskext'
WARNING: autodoc: failed to import data 'uploads.DOCUMENTS' from module 'flaskext'; the following exception was raised:
No module named 'flaskext'
WARNING: autodoc: failed to import data 'uploads.DATA' from module 'flaskext'; the following exception was raised:
No module named 'flaskext'
WARNING: autodoc: failed to import data 'uploads.SCRIPTS' from module 'flaskext'; the following exception was raised:
No module named 'flaskext'
WARNING: autodoc: failed to import data 'uploads.ARCHIVES' from module 'flaskext'; the following exception was raised:
No module named 'flaskext'
WARNING: autodoc: failed to import data 'uploads.EXECUTABLES' from module 'flaskext'; the following exception was raised:
No module named 'flaskext'
WARNING: autodoc: failed to import class 'uploads.TestingFileStorage' from module 'flaskext'; the following exception was raised:
No module named 'flaskext'
```

Unlike my project, where there is no reference to `flaskext`, the unmaintained upstream projects has two references to `flaskext`, one in the `index.rst` (for autodoc) and one in the docstring of its main module.

But... the content of the built docs is mine!

## Recap

- autodoc does not work
- in the raw log lots of references appear to the unmaintained upstream project
- docs get build for my Project with my content, but autodoc fails, as there are import warnings about `flaskext` which only appears in the upstream documentation `index.rst`

Disclaimer: I am a sphinx and readthedocs beginner and I am pretty much confused now  :-)

P.S.: An alternative explanation may be that rtd cached a very old version of the conf.py back from a year ago when I forked the upstream package.

**Comment by ericholscher** [comment]
This is using your `stable` version, which will be from your latest tag. Try building a specific branch that you're working on, and it should pull the correct commits.

**Comment by jugmac00** [comment]
@ericholscher, thank you for taking your time.

In the admin settings ( https://readthedocs.org/dashboard/flask-reuploaded/advanced/ ) I selected `master` as default branch and now it works!

Thanks so much!

P.S.: the only tag is from 2015, and was set back then by the maintainer of the unmaintained upstream project. I was not aware that my fork also uses it, and that it gets used by default by rtd.

**Comment by ericholscher** [comment]
@jugmac00 You can disable the `stable` version, and it won't do that anymore 👍

**Comment by jugmac00** [comment]
> @jugmac00 You can disable the `stable` version, and it won't do that anymore

❤️
