### ISSUE TITLE
some file are not downloaded when I rebuild my doc 

### ISSUE THREAD

**Issue by 12rambau** [readthedocs/readthedocs.org#8072]
I work with the following doc : https://docs.sepal.io/en/latest/index.html and my source leave here: https://github.com/openforis/sepal-doc

My documentation is gathering files from other location to build a complete documentation of our tool. 

The file list live in this [file](https://github.com/openforis/sepal-doc/blob/master/docs/source/data/modules/en.json) which is a simple .json.

Based on this json I download them at each build to populate a specific folder. In my [conf.py](https://github.com/openforis/sepal-doc/blob/master/docs/source/conf.py) file I've added the following line : 
```python 
# -- Copy the modules documentation ------------------------------------------

from urllib.request import urlretrieve
import json 

with open('data/modules/en.json') as json_file:
    module_doc = json.load(json_file)

for name in module_doc:
    urlretrieve (module_doc[name], f"modules/dwn/{name}.rst")
```

This is working just fine locally but it seems that these files are not updating when I rebuild my doc. For example this [doc page](https://docs.sepal.io/en/latest/modules/dwn/clip-time-series.html) should be mirroring this [file](https://github.com/openforis/clip-time-series/blob/master/doc/en.rst) which is obviously not the case. 

What am I missing and why does my documentation not updating all the files ?

**Comment by stsewd** [comment]
@12rambau hi, I think you may find useful to add some logging there. But maybe this is due that rtd is using a different cwd than the one you expect, to avoid that you can use something like:

```python
from pathlib import Path

json_file = Path(__file__).parent / 'data/modules/en.json'
# the same for the output file.
```

**Comment by 12rambau** [comment]
As you suggested I update the path using a relative path from conf and prompt the success of the download:
```python 
from urllib.request import urlretrieve
from pathlib import Path
import json 

module_dir = Path(__file__).expanduser().parent.joinpath('data', 'modules')
dwn_dir = Path(__file__).expanduser().parent.joinpath('modules', 'dwn')

with module_dir.joinpath('en.json').open() as json_file:
    module_doc = json.load(json_file)

for name in module_doc:
    urlretrieve (module_doc[name], dwn_dir.joinpath(f'{name}.rst'))
    
    # prompt for the readthedoc build
    print(f"{name} documentation have been copied to the dwn folder")
```

In the readthedoc compilation console I got: 
```console
sepal_ui_template documentation have been copied to the dwn folder
sepal_pysmm documentation have been copied to the dwn folder
alert_module documentation have been copied to the dwn folder
clip-time-series documentation have been copied to the dwn folder
import_to_gee documentation have been copied to the dwn folder
zonal-analysis documentation have been copied to the dwn folder
gfc_wrapper_python documentation have been copied to the dwn folder
```

I assume the pathlib relative path was the solution, and the doc is now fully updating itself at each build. I still don't get why the file were there if I was mistakening but now it works so thanks for your help !
