### ISSUE TITLE
css issue at RTD site?

### ISSUE THREAD

**Issue by galanisd** [readthedocs/readthedocs.org#8086]
* Read the Docs project URL: https://european-language-grid.readthedocs.io/en/release1.1.2/all/1_Introduction/Introduction.html
We have the same issue in all pages that use bullets.

## Expected Result

Until a couple days ago bullets in a list were shown as expected. However now for some reason  they have disappeared.
When we build the project locally they are shown. Same version of sphinx as in the online version (3.5.3)

We have also the same issue for old versions of the project that are kept in separate branches and they haven't been changed for quite some time. After rebuilding the project the bullets have disappeared.
The problem seems to be in  the CSS files of the online site. Not sure though.

**Comment by galanisd** [comment]
Locally 

![image](https://user-images.githubusercontent.com/10739759/114285452-15e81000-9a60-11eb-8ba1-eed6d0bc5a75.png)

At the RTD site

![image](https://user-images.githubusercontent.com/10739759/114285482-344e0b80-9a60-11eb-8ff9-98962d5cc2a2.png)

**Comment by Daltz333** [comment]
You need to pin docutils to 0.16.0 or update your theme to 0.5.2

**Comment by galanisd** [comment]
Set sphinx-rtd-theme==0.5.2 and this did the trick

**Comment by takluyver** [comment]
Here's the main issue about this problem: https://github.com/readthedocs/sphinx_rtd_theme/issues/1115

(Cross-linking to help other people who find this issue first :-)
