### ISSUE TITLE
document.settings.tab_width fails project build.

### ISSUE THREAD

**Issue by EzraEn1** [readthedocs/readthedocs.org#8088]
## Details

* Read the Docs project URL:  [https://bte.rtfd.io](https://bte.rtfd.io)
* Build URL (if applicable): `https://readthedocs.org/projects/bte/builds/13479756/`
* Read the Docs username (if applicable): `EzraEn`

## Expected Result

Project automatically builds with no tab_width exceptions.

## Actual Result

Project fails to build, with an Exception re: `document.settings.tab_width`.

No config changes have occured since the last time this project built. This can be verified by comparing against the last successful RTD build log [here](https://www.diffchecker.com/ymPuVQwR) (link valid until 1 month from now).
Only content-level changes have been made since the last successful build. This can also be verified by correlating the commits made in [this repo](https://github.com/EzraEn1/bteguide-site) to those listed within the build logs. By process of elimination, we can conclude that RTD's Sphinx setup is likely to blame.

**Comment by EzraEn1** [comment]
Attempting to manually configure docutils via a `docutils.conf` in the root directory according to https://docutils.sourceforge.io/docs/user/config.html#tab-width does not change build results, and continues to fail with the same error.

**Comment by EzraEn1** [comment]
Attmepting different option form (`tab-width` instead of `tab_width`) did not change results.

**Comment by EzraEn1** [comment]
There are no tabs present in the `/source` content whatsoever.

**Comment by EzraEn1** [comment]
This issue seem to be relevant to ReCommonMark and Docutils. See https://github.com/readthedocs/recommonmark/issues/177.

Relevant error to `document.settings.tab_width` might be 
```.../python3.7/site-packages/recommonmark/parser.py:75: UserWarning: Container node skipped: type=document```
as if document hasn't been initialised properly, settings are unlikely to default correctly, resulting in fatal error:
````Exception occurred:
  File ".../python3.7/site-packages/docutils/parsers/rst/__init__.py", line 189, in parse
    inputstring, tab_width=document.settings.tab_width,
AttributeError: 'Values' object has no attribute 'tab_width'```

Workaround in RCM #177 removed first error, but failed to resolve tab_width issue.

**Comment by EzraEn1** [comment]
Oh boy, y'all _really_ need to stop using old default packages when building.
After trimming down my `conf.py`, I took the time to actually look over the logs in closer detail.
I ended up playing around with the `requirements.txt`, and by simply updating sphinx to 3.5.4 fixed the issue. This really is on RTD at this point.

**Comment by stsewd** [comment]
@EzraEn1 we recommend specifying your dependencies explicitly https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html?#pinning-dependencies. Installing the latest version is the default for projects created after Oct 20, 2020 (this is done for backwards incompatibility).

**Comment by EzraEn1** [comment]
Ah, thank you! I hadn't delved deep enough in the docs to see this article. Was relying on my past experience for this. Thank you very much!
