### ISSUE TITLE
Enable DONT_OVERWRITE_SPHINX_CONTEXT for tapir-scala

### ISSUE THREAD

**Issue by adamw** [readthedocs/readthedocs.org#8091]
I need to overwrite the `conf_py_path` context value, so that the "Edit on github" links are properly generated on https://tapir.softwaremill.com/en/latest/ - they currently point to the `generated-doc` directory, instead of the `doc` directory (there's an additional docs type-checking step during a release).

I've tried following https://docs.readthedocs.io/en/latest/guides/vcs.html and defining the `html_contex` as specified there - this works locally, but not on rtd:

```
html_context = {
    'display_github': True, # Integrate GitHub
    'github_user': 'softwaremill', # Username
    'github_repo': 'tapir', # Repo name
    'github_version': 'master', # Version
    'conf_py_path': '/doc/', # Path in the checkout to the docs root
}
```

I then found https://github.com/readthedocs/readthedocs.org/issues/2971, and as I understand, I need the `DONT_OVERWRITE_SPHINX_CONTEXT` feature flag enabled. I tried doing this by defining an environment variable, but this doesn't seem to work. 

Can this feature be enabled for the `tapir-scala` project, or maybe there's a better way to adjust the "Edit on GitHub" link?

**Comment by stsewd** [comment]
I have added that feature flag to your project, it should link to the correct page no https://tapir.softwaremill.com/en/latest/

**Comment by adamw** [comment]
@stsewd Works, thank you very much! Sorry for not mentioning this outright, could you do the same for the `sttp` project? It uses the same mechanism.

**Comment by stsewd** [comment]
@adamw done!

**Comment by adamw** [comment]
@stsewd Thanks again! :)

**Comment by ghostbuster91** [comment]
@stsewd Can I ask for the same for the https://github.com/softwaremill/diffx project? It uses the same mechanism.

**Comment by humitos** [comment]
@ghostbuster91 Hi! Please, send us an email to support@readthedocs.org and let us know the URL of your project under Read the Docs (not the GH, one). Thanks!

**Comment by ghostbuster91** [comment]
@humitos I'll do that, thanks for the info :)
