### ISSUE TITLE
[BUG] Adding a partial `.readthedocs.yml` file overrides all of the settings set in the web UI

### ISSUE THREAD

**Issue by webknjaz** [readthedocs/readthedocs.org#8092]
## Details

Recently, I observed at least two projects adding a minimalist `.readthedocs.yml` and not noticing immediately that the effective URL scheme has changed.

Here's some references:
* https://github.com/pyca/cryptography/issues/5863 / https://github.com/pyca/cryptography/pull/5964
* https://github.com/pypa/packaging.python.org/issues/876 / https://github.com/pypa/packaging.python.org/pull/877

What happened in both cases was that the projects have `dirhtml` builder set in the web UI but then, they wanted to _only_ change specific properties of the build envs (without touching other settings) so they added the following configs to their repos to do just chage:
```yaml
# .readthedocs.yml

version: 2

sphinx:
  configuration: source/conf.py

python:
  version: 3.8
```
```yaml
# .readthedocs.yml

version: 2

build:
  image: "7.0"
```

## Expected Result

`sphinx.builder` is unset so the implicit expectation was that the one set earlier in the web UI would still be used.

## Actual Result

`sphinx.builder` was set to `html` without any warnings/notifications.

## How to improve this

I think, there are a few things RTD could do to make this situation better:
1. Add a big red warning to https://docs.readthedocs.io/en/stable/config-file/v2.html explaining how this works.
2. Print out an explanation on how the config is constructed to the build logs.
3. Merge the config file with the settings in the UI, overriding only specific options that have been explicitly requested via the config.
4. Or at least grey out all of the settings in the UI with an explanation that the config file in the repo now controls those and UI changes are disabled.

**Comment by stsewd** [comment]
Hi, this is done on purpose, since v2 of the config file has its own defaults (nicer defaults) that are different from web web-ui. There is a small mention of this at the bottom (`Some values from the web interface are no longer respected`), but I think it is better if we mention this at the top of the docs and make it more explicit yeah.

> Or at least grey out all of the settings in the UI with an explanation that the config file in the repo now controls those and UI changes are disabled.

We can't do this since they are still used for versions that don't have a config file and/or are already released.

**Comment by astrojuanlu** [comment]
> > Or at least grey out all of the settings in the UI with an explanation that the config file in the repo now controls those and UI changes are disabled.
>
> We can't do this since they are still used for versions that don't have a config file and/or are already released.

I think the proposal was: "if project X has a `.readthedocs.yaml` config, then grey out all the fields in the UI to avoid confusion". I've been bitten by this in the recent past as well.

In any case, +1 on having this better documented at least.

**Comment by webknjaz** [comment]
> We can't do this since they are still used for versions that don't have a config file and/or are already released.

How about having a warning "some of the builds use the config instead of this"? Also, not all of the web UI settings are even available in the config. So I can imagine extending the config to support such settings would implicitly override the previous settings without any notifications — it'd be nice to somehow mark settings that are overridable vs those that aren't.

**Comment by stsewd** [comment]
> > We can't do this since they are still used for versions that don't have a config file and/or are already released.
> 
> How about having a warning "some of the builds use the config instead of this"? Also, not all of the web UI settings are even available in the config. So I can imagine extending the config to support such settings would implicitly override the previous settings without any notifications — it'd be nice to somehow mark settings that are overridable vs those that aren't.

We already split the settings that are available in the config file, we are only missing mentioning the they would be ignored when using a v2 config file

![Screenshot_2021-04-14 Edit Advanced Project Settings Read the Docs](https://user-images.githubusercontent.com/4975310/114731677-8ebcc580-9d07-11eb-935a-8da39cd6d34b.png)

**Comment by astrojuanlu** [comment]
Apart from the suggested documentation improvements, @stsewd do you think it would be possible to add an `if (.readthedocs.yaml detected): (gray out UI fields)`? @webknjaz would that make things easier to understand?

**Comment by henryiii** [comment]
"Settings in the configuration file override the settings listed here" really sounds to me like that you can pick and choose; if something is not listed in the configuration file, I'd assume it is not "overriding" something here. Maybe wording it like "adding a configuration file will cause that to be used instead of the settings here". Graying it out would be fantastic, or even better, picking up the values from the configuration file and placing them in the grayed out boxes; but that might cause issues for someone who wants to remove a configuration file then set things here - but that's a pretty rare/special case. Once you have a file, you should usually not go back. Anyway, things to think about.

**Comment by stsewd** [comment]
> Apart from the suggested documentation improvements, @stsewd do you think it would be possible to add an `if (.readthedocs.yaml detected): (gray out UI fields)`? @webknjaz would that make things easier to understand?

We could, but we would need to check that ALL versions have a v2 config file, and if a new version is added we would need to keep tracking that.

**Comment by stsewd** [comment]
btw, the message says override because when using the v1 of the config file it does merge the settings from the web admin, the v2 of the config file does ignore them. But we already deprecated the v1, so I'm fine changing the message to assume you are using the v2.

**Comment by astrojuanlu** [comment]
Ah, I understand now - different versions of the project might have different configs. Thanks for the clarification @stsewd 👍🏽
