### ISSUE TITLE
No module found error (unable to import Class) when building of readthedocs.io

### ISSUE THREAD

**Issue by Prince2347X** [readthedocs/readthedocs.org#8093]
## Details
The autoclass is working correctly in local machine. But when i pushed the project and readthedocs build the docs, It's giving warning(No module named `module_name`) and not showing the docs.

* Read the Docs project URL: https://pydoodle.rtfd.io
* Build URL (if applicable): https://readthedocs.org/api/v2/build/13489407.txt
* Read the Docs username (if applicable): Prince2347X
* Github code (if needed): https://github.com/Prince2347X/pydoodle

## Expected Result
As on the local machine, the docs should be shown.

## Actual Result
Docs aren't showing up and it's giving warning. (See [build text](https://readthedocs.org/api/v2/build/13489407.txt) )

**Comment by astrojuanlu** [comment]
Hi @Prince2347X, thanks for using Read the Docs!

I see in the logs that you are installing the `requirements.txt`, but not the project itself. You might need to tick the `Install Project` checkbox on the Read the Docs admin, or write a [configuration file](https://docs.readthedocs.io/page/config-file/v2.html).

**Comment by Prince2347X** [comment]
Thank you very much @astrojuanlu for giving your valueable time! 
I checked the ``Install project`` checkbox and it automatically built the docs. I'm closing the issue now. 🙂 Thanks so much
