### ISSUE TITLE
Link broken on support page

### ISSUE THREAD

**Issue by johnomotani** [readthedocs/readthedocs.org#8095]
At https://github.com/readthedocs/readthedocs.org/blob/master/docs/support.rst, the link that's supposed to be to 'documentation guides' isn't correct. It actually points to https://github.com/readthedocs/readthedocs.org/blob/master/docs/support.rst#id1, which just leads back to the support page.

**Comment by stsewd** [comment]
@johnomotani we use sphinx to render our documentation, so the preview from github isn't what you should look at. The page you are looking is https://docs.readthedocs.io/en/stable/support.html, and the link is rendered correctly there https://docs.readthedocs.io/en/stable/guides/index.html
