### ISSUE TITLE
Unconditionally extending pip deps causes "double requirement" errors

### ISSUE THREAD

**Issue by dhalperi** [readthedocs/readthedocs.org#8096]
## Details

* Read the Docs project URL: https://pybatfish.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/pybatfish/builds/13493033/
* Read the Docs username (if applicable): dhalperi

## Expected Result

The project builds

## Actual Result

Our builds are failing on:

```
CondaEnvException: Pip failed

Ran pip subprocess with arguments:
[u'/home/docs/checkouts/readthedocs.org/user_builds/pybatfish/conda/latest/bin/python', '-m', 'pip', 'install', '-U', '-r', '/home/docs/checkouts/readthedocs.org/user_builds/pybatfish/checkouts/latest/docs/tmpRsess2.requirements.txt']
Pip subprocess output:

Pip subprocess error:
ERROR: Double requirement given: recommonmark==0.6.0 (from -r /home/docs/checkouts/readthedocs.org/user_builds/pybatfish/checkouts/latest/docs/tmpRsess2.requirements.txt (line 41)) (already in recommonmark (from -r /home/docs/checkouts/readthedocs.org/user_builds/pybatfish/checkouts/latest/docs/tmpRsess2.requirements.txt (line 1)), name='recommonmark')
```

Note that the dependency is pinned to `recommonmark==0.6.0` in our `environment.yml` files, but it seems that ReadTheDocs is unconditionally adding `recommonmark`  (unpinned) to the dependencies [here](https://github.com/readthedocs/readthedocs.org/blob/bc3e147770e5740314a8e8c33fec5d111c850498/readthedocs/doc_builder/python_environments.py#L654) and this is causing the error in `pip`.

Maybe this was always happening, and newer versions of `pip` are rejecting this?

**Comment by dhalperi** [comment]
Also, having a hard time debugging or reproducing this. The `cat docs/environment.yml` command in the build is clearly not using OUR checked-in `docs/environment.yml`: it has been modified to have extra dependencies that are breaking us.

**Comment by stsewd** [comment]
Sorry about that, we are moving away from doing that https://github.com/readthedocs/readthedocs.org/pull/8076.

Note: I was trying to fix this by checking if the dep was already in the list of pip deps and not adding those

https://github.com/readthedocs/readthedocs.org/blob/8009046a9c416816ddc3448c8427d9c683f0e65d/readthedocs/doc_builder/python_environments.py#L619

but we would also need to check if they already are in the top deps as well (here for example they are installing sphinx from pip, and we are installing it from conda too!), I think better to focus on implementing the new builders mentioned in #8076 than adding more code for checking this.

**Comment by humitos** [comment]
Isn't this solved by CONDA_APPEND_REQUIREMENTS feature flag? https://docs.readthedocs.io/en/stable/guides/feature-flags.html#feature-flags

**Comment by stsewd** [comment]
@humitos I think that flag is already default for everyone, and that's the issue actually, since we are appending dependencies that the user already declared.

**Comment by humitos** [comment]
We are removing `recommonmark` from the "core packages" installed on August 7th. Read more about this at https://blog.readthedocs.com/python-core-requirements-changed/

If you want to me to enable this behavior to your project before that date, let me know.
