### ISSUE TITLE
How to enable/add feature flags

### ISSUE THREAD

**Issue by jbusecke** [readthedocs/readthedocs.org#8098]
I am very curious to use the [Feature Flags](https://docs.readthedocs.io/en/stable/guides/feature-flags.html#feature-flags), in particular I would like to test `CONDA_USES_MAMBA` for my [project docs](https://readthedocs.org/projects/cmip6-preprocessing/).

From the documentation page on [Feature Flags](https://docs.readthedocs.io/en/stable/guides/feature-flags.html#feature-flags) it is not clear to me how these are set/enabled by the projects admin. I think it would be helpful to add this bit of information to the docs.

**Comment by jbusecke** [comment]
Sorry, I think I misread the description. I thought `the site admin` meant the project admin, but I think that was wrong.

**Comment by stsewd** [comment]
You need to contact support, we can make this more clear yeah, the paragraph could be re-written to make it more explicit and short.

**Comment by jbusecke** [comment]
I think that would be very helpful. Email is sent. Thanks!
