### ISSUE TITLE
Search Functionality Not Working With readthedocs Theme After `mkdocs serve`

### ISSUE THREAD

**Issue by Austinreedthomas** [readthedocs/readthedocs.org#8112]
## Details

* Read the Docs project URL: Classified
* Build URL (if applicable): Classified
* Read the Docs username (if applicable): Classified

Using mkdocs v 1.1.2 (Python 3.7) and the readthedocs theme.

## Expected Result

After running `mkdocs serve` and navigating to 127.0.0.1:8000 in a browser, I'm expecting to find some sort of search result. 

## Actual Result

It never finds any. The included README.md for example has instructions for using mkdocs and a general search for "mkdocs" returns nothing. It hangs and just says "Searching..." forever.

**Comment by stsewd** [comment]
Hi, this repository is for bugs related to projects hosted on readthedocs.org. You should open an issue on the mkdocs repo https://github.com/mkdocs/mkdocs.
