### ISSUE TITLE
Command killed due to excessive memory consumption

### ISSUE THREAD

**Issue by mengliu1998** [readthedocs/readthedocs.org#8128]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/diveintographs/
* Build URL (if applicable): https://readthedocs.org/projects/diveintographs/builds/13572015/
* Read the Docs username (if applicable): divelab

## Expected Result

I changed the environment requirement file for Read the Docs from requirement.txt (used for pip) to environment.yaml (used for conda), since some of my dependencies can only be installed by conda. The original pip version works well. 

## Actual Result

However, the conda version fails to build. After I read some similar issues, I think this is an issue about time. Could you take a look? Thank you in advance.

![image](https://user-images.githubusercontent.com/33959783/115601239-2a6baa00-a2a3-11eb-80cc-e9b4d3844bdb.png)

**Comment by stsewd** [comment]
Hi, I have moved your project to builder with more resources https://readthedocs.org/projects/diveintographs/builds/13572552/, let's see if it passes now.

**Comment by stsewd** [comment]
Looks like the build failed for an unrelated problem now.

**Comment by mengliu1998** [comment]
Hi,

Thank you for your response.

Yes, I am taking care of the current error. If you have any thought, please let me know. Thank you.

**Comment by mengliu1998** [comment]
I have fixed the new issue. It is related to the python version. Thank you again for your help.
