### ISSUE TITLE
Custom Redirects seem not to work on one Project (but does work on a fork)

### ISSUE THREAD

**Issue by alistairjevans** [readthedocs/readthedocs.org#8134]
## Details

* Read the Docs project URL: https://autofac.readthedocs.io/

I'm attempting to set up an exact redirect on the autofac docs, which does not appear to work, but the same redirect *does* work on a different project URL.

I've defined the same Exact Redirect on both the main autofac project (`autofac`) and my personal fork of our docs (`aemydocumentation`):

`/foo/bar -> /en/latest/faq/per-request-scope.html`

However the redirect only works on my personal fork, so:

- https://aemydocumentation.rtfd.io/foo/bar  redirects correctly to https://aemydocumentation.readthedocs.io/en/latest/faq/per-request-scope.html
but...
- https://autofac.rtfd.io/foo/bar redirects to https://autofaccn.readthedocs.io/en/latest/foo/bar and gives me a 404

I can see that the domain name I end up with is slightly different (with the `cn` suffix); is that anything to do with it? I'm aware the Autofac docs are a relatively high-traffic site.

Thanks for any help!

## Expected Result

The redirect works on the autofac docs and ends up at the redirect target.

## Actual Result

The redirect goes to the 'standard' 404 page.

**Comment by stsewd** [comment]
Hi, looks like your project is set as a translation of this other project https://readthedocs.org/projects/autofaccn/, if you don't have access to that other project I can remove the relationship (there was an old bug that allowed users to set projects as translation of others without having the same owner). Also, maybe there is a bug in our serving logic when using translations that I'd try to investigate later.

**Comment by alistairjevans** [comment]
Hi @stsewd, thanks for point that out; we have no idea how that ended up being the case (none of us know anything about the autofaccn project), so we should break the link. Possibly someone else did it using that bug as you mentioned.

My only concern is that the docs have been like this for some time, so a lot of external links to our docs would break if that domain is changed, right? Is there any way to avoid that or put a redirect back in the other way?

**Comment by stsewd** [comment]
@alistairjevans sorry for the late reply, I was asking the team on how to solve this. The easy way is to solve this together with the author of the translation: @nicoxiang.

@nicoxiang rtd had a bug that allowed users to add any project as translation of another, but that was fixed a time ago, and now we require that a both projects need to share the same owner in order to add it as translation. The docs have been using your project as the main one `autofaccn`. Would you help us to fix this, so all docs are served from the main project `autofac` without breaking existing urls? These are the steps to follow:

- Add https://readthedocs.org/profiles/alistairjevans/ as maintainer of your rtd project https://readthedocs.org/dashboard/autofaccn/users/
- Create an exact redirect from `/en/$rest` to `https://autofac.readthedocs.io/en/` https://readthedocs.org/dashboard/autofac/redirects/ (test that it works by hitting https://autofaccn.readthedocs.io/en/latest/foo, it should redirect to https://autofac.readthedocs.io/en/latest/foo, maybe it would be infinite redirect, but that's ok).
- Remove the translation https://readthedocs.org/dashboard/autofaccn/translations/ (this will fix the infinite redirect)
- Add the translation from the main project https://readthedocs.org/dashboard/autofac/translations/
- Check that old links are working for both projects, now https://autofaccn.readthedocs.io/zh/latest/ would be redirected to https://autofac.readthedocs.io/zh/latest/

If you need help or more information about those steps please let me know

**Comment by nicoxiang** [comment]
Sorry for the late reply. @alistairjevans   and i'm working on it now. I translated autofac docs into chinese years ago, and the relationship generated automatically, i don't know how that happen either. I'd like to know if you really need this translation, if it's unnecessary, i can delete this project. I am so sorry to cause you trouble.

**Comment by alistairjevans** [comment]
Hi @nicoxiang, thanks for helping us out, and don't worry about it, these things happen, and it's taken us this long to notice that something is up! Also sounds like a ReadTheDocs bug was involved somehow.

I don't think you can actually delete your project entirely without breaking a lot of existing links; it'll have to "exist" in RTD for the redirects to work.

However, if you are not actively maintaining the translation (which is fine, that would be loads of work, and thank you for translating it originally), then we may not mark your existing project as an actual translation of the Autofac docs any more. 

I'm concerned that very out-of-date docs may be worse than not having the translation at all.

**Comment by nicoxiang** [comment]
Thanks for the advice @alistairjevans Just as what you said, that translation took me several months to finish it but I do admit that i'm not a good maintainer, daily jobs are taking up lots of my time these days, so i have deleted the project entirely. BTW, Autofac is a really great project. If you need help in the future please let me know.

**Comment by alistairjevans** [comment]
@nicoxiang; did you follow the instructions provided by @stsewd?

Our docs to appear to just be broken now...getting infinite redirects.

**Comment by nicoxiang** [comment]
@stsewd @alistairjevans yes, i follow the instructions and i have finished step 1-3, after that i delete the project.

**Comment by alistairjevans** [comment]
Ah. Deleting the project breaks any of the configuration you put in place.  The project needed to stay up so the redirects work.

I'm going to try re-creating the autofaccn project myself under the Autofac org.

**Comment by alistairjevans** [comment]
OK, so I've recreated the `autofaccn` project under autofac ownership, set up those redirects appropriately, so any old direct page links (`https://autofaccn.readthedocs.io/en/latest/$rest` URLs) correctly redirect to the same page in the main documentation.

Some issues that still remain (perhaps @stsewd you can suggest something?):

- I cannot redirect the root `https://autofaccn.readthedocs.io/en/latest` to `https://autofac.readthedocs.io/en/latest`; as far as I can tell from your docs, this is because the page exists, and RTD only serves redirects for 404s.  I cannot delete that initial page, so it currently contains a "sorry, we've moved" page: https://autofaccn.readthedocs.io/en/latest.

- If I try to set this new `autofaccn` project as Chinese to catch redirects for `/zh`, my `/en` redirects don't work (and vice-versa). I'm guessing that perhaps it won't even consider my redirect if the project does not provide that language?

- If I set `docs.autofac.org` as the Canonical domain name of the project, I get an infinite redirect. This setting was on before, but I guess it was overridden by the whole translation mess.

The state now is that most of the existing links docs are redirected appropriately, but we have a slightly ugly landing page for `https://autofaccn.readthedocs.io/`.

**Comment by stsewd** [comment]
@nicoxiang thanks for taking care of this!

@alistairjevans you can use this trick for the index.html redirect, put this on your index.rst

```rst
.. meta::
   :http-equiv=Refresh: 0; url='https://google.com'
```

> If I try to set this new autofaccn project as Chinese to catch redirects for /zh, my /en redirects don't work (and vice-versa). I'm guessing that perhaps it won't even consider my redirect if the project does not provide that language?

When you set that project as translation of the other, your main project changes to be `autofac`, and so it will use the redirects from that project instead. But as the project was deleted, then doesn't look like you want to set that project as a translation.

> If I set docs.autofac.org as the Canonical domain name of the project, I get an infinite redirect. This setting was on before, but I guess it was overridden by the whole translation mess.

Looks like you don't have a CNAME set

> dig +short docs.autofac.org CNAME

Please check https://docs.readthedocs.io/en/stable/custom_domains.html#custom-domain-support

**Comment by alistairjevans** [comment]
@stewd, thanks; sorry I didn't reply before now; the meta redirect trick works, thank you.

I'll look at getting that CNAME sorted in our DNS.

**Comment by alistairjevans** [comment]
This can stay closed; the rest of it is on me to sort out.
