### ISSUE TITLE
[Support] Remove obsolete Epub, PDF and HTMLZip downloads from Godot docs

### ISSUE THREAD

**Issue by akien-mga** [readthedocs/readthedocs.org#8135]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/godot/
* Build URL (if applicable): https://readthedocs.org/projects/godot/downloads/
* Read the Docs username (if applicable): Akien

## Support request

I'd like to request the existing, obsolete Epub, PDF and HTMLZip downloads for the Godot documentation to be removed: https://readthedocs.org/projects/godot/downloads/ (I'm the project admin).

Godot documentation is huge and neither of those options are usable. We recently re-tried Epub downloads and they were broken: https://github.com/godotengine/godot-docs/issues/3862.

Current Godot stable release is 3.3 so these old 2.1, 3.0 and 3.1 attempts at providing offline builds are now more harmful than useful.

We'd really love to provide multi-page HTML zips for offline use (https://github.com/readthedocs/readthedocs.org/issues/3242) but that's another issue :)

Thanks in advance!

**Comment by stsewd** [comment]
Done https://readthedocs.org/projects/godot/downloads/! If you still can access old downloads if probably a cached version.

**Comment by akien-mga** [comment]
Thanks!

**Comment by akien-mga** [comment]
> If you still can access old downloads it's probably a cached version.

Is the cache expected to expire eventually? It's been 10 days and the downloads are still all up on https://readthedocs.org/projects/godot/downloads/

![Screenshot_20210506_151223](https://user-images.githubusercontent.com/4701338/117303871-7743a900-ae7d-11eb-96ce-770576f74d67.png)

**Comment by stsewd** [comment]
@akien-mga last time I checked they weren't there. Looks like you triggered new builds for those versions https://readthedocs.org/projects/godot/builds/, that would regenerate the epub and pdf files.

**Comment by stsewd** [comment]
If you are able to change old versions, you can set the formats to an empty list using the config file https://github.com/godotengine/godot-docs/blob/3.1/.readthedocs.yml (v2 is recommended https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by akien-mga** [comment]
Oh you're right! Sorry about that.

Rebuilding each branch with all formats disabled did the trick, and even removed the existing downloads: https://readthedocs.org/projects/godot/downloads/

So it seems I didn't even need to ask for admin intervention to remove them, but just changing the config also removes old builds? If so, maybe I can contribute a paragraph about it in https://docs.readthedocs.io/en/stable/downloadable-documentation.html?

**Comment by stsewd** [comment]
> So it seems I didn't even need to ask for admin intervention to remove them, but just changing the config also removes old builds? If so, maybe I can contribute a paragraph about it in https://docs.readthedocs.io/en/stable/downloadable-documentation.html?

Sure, anything that should have done this more explicit. Maybe a "Deleting downloadable content" section
