### ISSUE TITLE
RTD: Command killed due to excessive memory consumption when installing setup.py

### ISSUE THREAD

**Issue by shaod2** [readthedocs/readthedocs.org#8140]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/protobuf-shaod/
* Build URL (if applicable): https://readthedocs.org/projects/protobuf-shaod/builds/13620835/
* Read the Docs username (if applicable): shaod2

## Expected Result

Build successfully

## Actual Result

[Command killed due to excessive memory consumption](https://readthedocs.org/api/v2/build/13620835.txt) during `python setup.py install`

Seems like this command costs a lot of memory space. Wondering if there's any workaround to reduce the memory consumption or increase the capacity.

**Comment by stsewd** [comment]
Hi, your project is already using our big builders, the memory error comes from https://github.com/shaod2/protobuf/blob/b9ccafbc542c1a1711966cf1a5255dc97d7df24c/python/setup.py#L129 does your project need to execute that in order to generate the docs?
