### ISSUE TITLE
Autodoc overlooking certain files

### ISSUE THREAD

**Issue by bryan-garcia** [readthedocs/readthedocs.org#8150]
## Details

* Read the Docs project URL: https://github.com/LLNL/INGRID/tree/documentation
* Build URL (if applicable): https://readthedocs.org/projects/ingrid/builds/13651804/
* Read the Docs username (if applicable): bryan-garcia

## Expected Result

Documentation to be generated for source files in ``INGRID`` via autodoc.

## Actual Result

Files ``ingrid.py`` and ``topologies/*.py`` did not generate documentation when built on readthedocs, whereas all other
source files did. Locally this issue does not occur when building.

## Additional information

I've already gone ahead and configured my settings online to build the ``documentation`` branch.
I followed [this](https://github.com/readthedocs/readthedocs.org/issues/3634) post and resolved older issues I had. 

Thank you for any help.

**Comment by stsewd** [comment]
Hi, I can see the docs extracted from sources here https://ingrid.readthedocs.io/en/latest/ingrid.html or is there any other page missing?

**Comment by bryan-garcia** [comment]
Hi, thank you for reaching out. There are no other pages missing and all my documentation is now live. I'm not sure why there was a delay on those two files, but there is no longer an issue.
