### ISSUE TITLE
search word highlight not work 

### ISSUE THREAD

**Issue by lucays** [readthedocs/readthedocs.org#8152]
## Details

* Read the Docs project URL:
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

if use [Search query syntax](https://docs.readthedocs.io/en/stable/guides/searching-with-readthedocs.html#search-query-syntax) or [Enable “search as you type” in your documentation](https://docs.readthedocs.io/en/stable/guides/searching-with-readthedocs.html#enable-search-as-you-type-in-your-documentation), highlight search word still work.

## Actual Result

if use Search query syntax like ":
![not match "](https://user-images.githubusercontent.com/29814851/116857969-3dca2e00-ac30-11eb-8fff-a1fb4963a574.png)

not match "" so highlight dont work.

if use readthedocs-sphinx-search click a search result directly:
![link missing highlight=xx](https://user-images.githubusercontent.com/29814851/116858204-9699c680-ac30-11eb-893e-33d692467f9e.png)

link missing "highlight=" so highlight dont work

**Comment by stsewd** [comment]
Hi, this is due that we use the same search term to pass to the `highlight` query param. Maybe we can do this in a smarter way and use the highlighted word in the results instead.

**Comment by humitos** [comment]
Closing in favor of https://github.com/readthedocs/addons/issues/36. Please, subscribe there to keep up to date.
