### ISSUE TITLE
ethicalads snippet included even when project has disabled ads

### ISSUE THREAD

**Issue by nijel** [readthedocs/readthedocs.org#8161]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/weblate/
* Build URL (if applicable):
* Read the Docs username (if applicable): nijel

## Expected Result

As a gold member, I have disabled advertisement on Weblate docs and I would expect no ads code to load.

## Actual Result

https://media.ethicalads.io/media/client/beta/ethicalads.min.js and https://media.ethicalads.io/abp/px.gif are loaded from the page. 

As far as I know, no ads are actually displayed.

## Note

I've run into this as some users complained about documentation load times and removing not used third-party scripts might help in this. Though the root cause of the performance issues is most likely elsewhere.

**Comment by stsewd** [comment]
Hi, the script that load this comes from

```html
 <script async="async" src="https://assets.readthedocs.org/static/javascript/readthedocs-doc-embed.js"></script>
```

As you can see it loads asynchronously, so it shouldn't block rendering. But yeah, we shouldn't need to load the script if the project is ad-free.

> I've run into this as some users complained about documentation load times

Are those users from china? Please see https://github.com/readthedocs/readthedocs.org/issues/7205

**Comment by nijel** [comment]
> As you can see it loads asynchronously, so it shouldn't block rendering. 

I agree, the performance impact should be minimal here.

> Are those users from china?

No, they were from Europe. It might be caused by our documentation containing huge pages, probably it's time to split some of them to smaller ones.

**Comment by stsewd** [comment]
A fix has been deployed, I don't see the ethical ads script being loaded in your site https://docs.weblate.org/en/latest/.

If anyone sees this, in order to take effect you need to rebuild your project.
