### ISSUE TITLE
Can not submit support request with Firefox

### ISSUE THREAD

**Issue by cedk** [readthedocs/readthedocs.org#8165]
When I submit a support request from firefox on https://readthedocs.org/support/
I always got the error message:

> Support Form Error 
> These has been an error submitting your support request.
> Please try again, filling out all form fields.

from the URL: https://readthedocs.org/support/error/?code=bad_referer&message=This%20form%20was%20not%20submitted%20from%20the%20configured%20location.

It worked with Chrome.

**Comment by humitos** [comment]
Hi @cedk! Are you using some kind of extensions on Firefox. That may be blocking some of the fields being sent? I was able to fill and send the form using the latest Firefox version and beta version as well.

**Comment by Daltz333** [comment]
Sounds like an issue with incorrect blocks from AdGuard.

**Comment by stsewd** [comment]
Looks like a problem with a plugin, not the site. Please let us know if you still have the problem when disabling those extensions.
