### ISSUE TITLE
Abandoned project: Coherence

### ISSUE THREAD

**Issue by McManning** [readthedocs/readthedocs.org#8167]
Hello,

I'd like to take over the "Coherence" project name: https://readthedocs.org/projects/coherence/

I cannot find a way to contact the current owner myself and it looks like this falls under RTD's abandoned projects policy.

In the meantime - am I able to spin up documentation under a different namespace (e.g. `coherence-plugin`) until I can migrate it over to the new one? 

Thanks!
Chase

**Comment by stsewd** [comment]
Hi, I have emailed the user today, I'll let you know if I hear back.

**Comment by stsewd** [comment]
@McManning I have received a reply from the user, and I can transfer the project to you, I need your rtd username to do that.

**Comment by McManning** [comment]
Username is McManning.

I've setup https://coherence-plugin.readthedocs.io/ in the meantime - would I be able to migrate that over to just "coherence"?

**Comment by stsewd** [comment]
I have added you as owner https://readthedocs.org/projects/coherence/.

> would I be able to migrate that over to just "coherence"?

You'll need to setup the project repo and any configuration from the other project.
