### ISSUE TITLE
Allow language agnostics redirects

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#8168]
Say you have multiple languages setup in your docs.

- en
- es
- ch_ZN
- ...

If you want a redirect, this must append to the end of the language.

I would like to propose the ability to add redirects to the root URL, to either a doc URL, or a custom external URL.

Input: /stacktrace.html
EX: https://docs.wpilib.org/stacktrace.html

which redirects to Output

Output: /en/latest/docs/software/basic-programming/reading-stacktraces.html

this is currently not possible with the current behavior.

**Comment by Daltz333** [comment]
The input for page redirects is after the /en/latest/ tags.

So an input of 

/stacktrace.html

Would be a redirect from /en/latest/stacktrace.html, which is *not* what I want.

**Comment by stsewd** [comment]
I'm not sure to fully understand what you mean, can you provide some examples of URLs and the expected redirect?

**Comment by Daltz333** [comment]
Example URL
https://docs.wpilib.org/stacktrace.html

Which will then redirect to

https://docs.wpilib.org/en/latest/docs/software/basic-programming/reading-stacktrace.html

Currently, it will only work if I do

https://docs.wpilib.org/en/latest/. I want it a root domain redirect.

**Comment by Daltz333** [comment]
I might have had my configuration setup wrong. I will attempt again later.

**Comment by stsewd** [comment]
You can do that with an exact redirect https://docs.readthedocs.io/en/stable/user-defined-redirects.html#exact-redirects

```
Type: Exact Redirect
From URL: /stacktrace.html
To URL:   /en/latest/docs/software/basic-programming/reading-stacktrace.html
```

But I'm not sure where the "language agnostic" part fits here.

**Comment by Daltz333** [comment]
My verbiage might have been confusing. I was more specifying language agnostic to refer to not requiring the /en/ and /latest/ part of the URLs.

I was not able to get that to work previously. I will attempt again. Does it take affect immediately?

**Comment by stsewd** [comment]
> I was not able to get that to work previously. I will attempt again. Does it take affect immediately?

Yeah. Here is a test redirect I just created for example https://test-builds.readthedocs.io/foo

![Screenshot_2021-05-10 Edit Redirects Read the Docs](https://user-images.githubusercontent.com/4975310/117739563-3a9ce800-b1c4-11eb-8905-66013823d845.png)
