### ISSUE TITLE
Error in Guide: Cross-referencing with Sphinx

### ISSUE THREAD

**Issue by JoelForamitti** [readthedocs/readthedocs.org#8172]
## Details

Read the Docs project URL: https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html

The following paragraph:

```
The reference displays the name of the target by default, but we can use any text you want. 
For example: `my custom text   <target to paragraph>`_, that will be rendered as: my custom text.
```

## Expected Result

The link `my custom text` should lead to the target.

## Actual Result

The link returns a `Page not Found` error.

**Comment by stsewd** [comment]
oops, looks like this doesn't work as I was expecting, not sure why I didn't realize this when writing the guide. But looks like the ref role does support that `` :ref:`Target to paragraph <target to paragraph>` ``
