### ISSUE TITLE
Deleted versions of documentation are still being served

### ISSUE THREAD

**Issue by imphil** [readthedocs/readthedocs.org#8174]
## Details

* Read the Docs project URL: https://fusesoc.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/fusesoc/builds/
* Read the Docs username (if applicable): imphil

## Expected Result

We did have two versions (branches) of documentation that got deleted in the meantime, but are still being served:
- https://fusesoc.readthedocs.io/en/master/
- https://fusesoc.readthedocs.io/en/rtd/

Both are not listed at https://readthedocs.org/projects/fusesoc/versions/ any more and contain outdated material that should no longer be available. (Unfortunately, Google places some of the dead documentation versions very prominently, confusing users with outdated/wrong documentation.)

See also https://github.com/olofk/fusesoc/issues/464

## Actual Result

After deleting the two `master` and `rtd` versions of the documentation, we would have expected them not to be available any more.

Can you delete them manually for us? 

I don't know if this is expected behavior, or a bug in the deletion routines.

**Comment by imphil** [comment]
Thanks!

The versions were deleted on February 11 (https://github.com/olofk/fusesoc/issues/464#issuecomment-777455935)

**Comment by olofk** [comment]
Thanks for taking care of it. Just a question. Is it possible to redirect them to e.g. https://fusesoc.readthedocs.io/en/stable Problem is that Google for some reason prefer the https://fusesoc.readthedocs.io/en/rtd/ version, so now we have a broken link (well, a maze) instead of outdated docs
