### ISSUE TITLE
Redirect only works with URL prefixed with HTTPS not HTTP

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#8183]
## Details

* Read the Docs project URL: https://docs.wpilib.org/
* Build URL (if applicable): na
* Read the Docs username (if applicable): na

We have the following redirect setup

![image](https://user-images.githubusercontent.com/10674555/118324392-fc5b3d80-b4cf-11eb-91fc-c70a0aa353be.png)

The redirect works properly if given the URL: https://docs.wpilib.org/stacktrace

It *does not* work properly if given the same URL but without SSL: http://docs.wpilib.org/stacktrace

I suspect there may be an issue relating to "always use HTTPS for this domain"

**Comment by TheTripleV** [comment]
Furthermore, the redirect fails on readthedoc's urls.

Both `https://frc-docs.readthedocs.io/stacktrace` and `http://frc-docs.readthedocs.io/stacktrace` fail to follow the specified redirect and instead go to `https://docs.wpilib.org/en/stable/stacktrace`

**Comment by stsewd** [comment]
The fix is live, I can see all redirects are good now
