### ISSUE TITLE
Search does not work for website with utf-8 content

### ISSUE THREAD

**Issue by iarigby** [readthedocs/readthedocs.org#8196]
My website is primarily in Georgian and search bar does not work for English or Georgian keywords. Console shows no error so we have no idea where to start troubleshooting this issue.
 
## Details

* Read the Docs project URL: https://github.com/freeuni-digital-technologies/freeuni-digital-technologies.github.io
* Build URL (if applicable): https://freeuni-digital-technologies.github.io/
* Read the Docs username (if applicable):

## Expected Result
typing a keyword from page or heading should bring up search results

## Actual Result
No results are brought up for keywords of any language

**Comment by humitos** [comment]
Hi @iarigby! It seems that our website is hosted under GitHub pages 😄 . If my assumption is not correct, please provide your Read the Docs project's information. Thanks!

**Comment by iarigby** [comment]
@humitos thank you for the reply! I've posted the repo and build site, do you mean config.yml file?

**Comment by humitos** [comment]
@iarigby No. What's your Read the Docs' (https://readthedocs.org) username and your Read the Docs' project URL?

**Comment by iarigby** [comment]
Don't have one, should I have signed up?

**Comment by stsewd** [comment]
@iarigby this repository is about projects using sphinx or mkdocs and being hosted on readthedocs.org or projects using the https://github.com/readthedocs/sphinx_rtd_theme theme. Looks like your projects is hosted on github pages using jekyll. Please make sure you contact those projects instead (looks like the theme you are using is https://github.com/pmarsceill/just-the-docs)
