### ISSUE TITLE
Build failed due  excessive memory consumption error

### ISSUE THREAD

**Issue by shivangi-aneja** [readthedocs/readthedocs.org#8199]
## Details

* Read the Docs project URL: https://cosmos-dataset.readthedocs.io/en/latest/index.html
* Build URL (if applicable): https://readthedocs.org/projects/cosmos-dataset/builds/13807855/
* Read the Docs username (if applicable): 

## Actual Result

The build is failing due to memory error, I have tried building it multiple times but no help. Also it worked when I rean the build first time. I tried wiping and build again, but doesnt help

**Comment by stsewd** [comment]
Hi, I have moved your project to a bigger builder https://readthedocs.org/projects/cosmos-dataset/builds/13808313/, it's passing now.
