### ISSUE TITLE
Build error with build id #13830655

### ISSUE THREAD

**Issue by akruis** [readthedocs/readthedocs.org#8204]
## Details:

* Project URL: https://readthedocs.org/projects/stackless/
* Build URL(if applicable): https://readthedocs.org/projects/stackless/builds/13830655/
* Read the Docs username(if applicable): akruis

## Expected Result

Build succeeds or fails with an error message.

## Actual Result

Build fails with the message 

> *There was a problem with Read the Docs while building your documentation. Please try again later. However, if this problem persists, please report this to us with your build id (13830655).*

But there is no indication of an error. The raw output is

```
Read the Docs build information
Build id: 13830655
Project: stackless
Version: v3.7.9-slp
Commit: 8ad319a856a471166b9844d7dd3ab406a5e9b865
Date: 2021-05-22T17:51:38.678327Z
State: finished
Success: False


[rtd-command-info] start-time: 2021-05-22T17:51:39.747677Z, end-time: 2021-05-22T17:52:33.940797Z, duration: 54, exit-code: 0
git clone --no-single-branch --depth 50 https://github.com/stackless-dev/stackless .
Cloning into '.'...

[rtd-command-info] start-time: 2021-05-22T17:52:34.157695Z, end-time: 2021-05-22T17:52:34.911025Z, duration: 0, exit-code: 0
git checkout --force 8ad319a856a471166b9844d7dd3ab406a5e9b865
Note: checking out '8ad319a856a471166b9844d7dd3ab406a5e9b865'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 8ad319a85 Update changelog.txt for release v3.7.9-slp

[rtd-command-info] start-time: 2021-05-22T17:52:35.041545Z, end-time: 2021-05-22T17:52:35.127082Z, duration: 0, exit-code: 0
git clean -d -f -f


```

**Comment by stsewd** [comment]
Hi, this looks like a problem when using the 2.0 build image

https://github.com/stackless-dev/stackless/blob/8ad319a856a471166b9844d7dd3ab406a5e9b865/.readthedocs.yml#L4-L5

We don't have that image anymore in our servers, we use `latest` or `stable` now, but you can just omit the image name.

Can't remember if we had a plan for users using the old image /cc @readthedocs/core

**Comment by akruis** [comment]
> Hi, this looks like a problem when using the 2.0 build image
> 
> https://github.com/stackless-dev/stackless/blob/8ad319a856a471166b9844d7dd3ab406a5e9b865/.readthedocs.yml#L4-L5
> 
> We don't have that image anymore in our servers, we use `latest` or `stable` now, but you can just omit the image name.

Many thanks for your assistance. I updated our configuration.

**Comment by humitos** [comment]
> Can't remember if we had a plan for users using the old image /cc @readthedocs/core

Hrm, it seems we didn't cover these old images in https://docs.readthedocs.io/en/stable/development/design/build-images.html#deprecation-plan. We should probably log projects using these old images and contact them telling them have to migrate to the new images. I think this should be part of that document, probably.

**Comment by stsewd** [comment]
> We should probably log projects using these old images

I only saw this project in sentry so far.
