### ISSUE TITLE
Lists are not displayed correctly on most recent builds

### ISSUE THREAD

**Issue by fwitte** [readthedocs/readthedocs.org#8209]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/tespy/
* Build URL (**successful**): https://readthedocs.org/projects/tespy/builds/13784187/ (**Sphinx version 3.5.4**)
* Build URL (**lists not rendered**): e.g. dev version https://readthedocs.org/projects/tespy/builds/13848977/ (**Sphinx version 4.0.2**)
* Read the Docs username (if applicable): fwitte
* GitHub repository: https://github.com/oemof/tespy/

## Expected Result

Lists from .rst type files should be rendered as usual. This did work about a week ago using sphinx version 3.5.4 (e.g. see https://tespy.readthedocs.io/en/stable/tespy_modules.html) and it also does work locally using sphinx version 4.0.2, which is why I do not really see, why it should not in RTD.

![grafik](https://user-images.githubusercontent.com/20252362/119494748-f08a3980-bd61-11eb-8dc2-622d8cbc29f9.png)

## Actual Result

In the most recent builds (latest, main, dev) lists are not formatted correctly (e.g. https://tespy.readthedocs.io/en/latest/tespy_modules.html). Each bullet is displayed as separate paragraph, see screenshot.

![grafik](https://user-images.githubusercontent.com/20252362/119494705-e5370e00-bd61-11eb-920c-f51b22d785ed.png)

## Comments

I did some changes in the RTD configuration, which might be related, but I do not really see how:

- Add a redirect for /en/master/ to /en/main/ (after renaming master to main some time ago)
- Activate the latest version and make it point to main instead of master

In the code base, no relevant changes have been applied to the code since the last successful build on the stable branch, e.g. compare main and stable (one commit only: https://github.com/oemof/tespy/commit/67650cdb175e2f9ad89023633a450f503b9db5eb).

Maybe somebody can give me a hint, what the issue might be here or if this is a bug?

Thank you, best regards

**Comment by stsewd** [comment]
Hi, your build is using an old version of the theme by default, which isn't compatible with the latest sphinx version. We are moving away from doing that, I have put your project under a feature flag to install the latest versions by default, you can still override them from your requirements file.

https://readthedocs.org/projects/tespy/builds/13851909/

**Comment by fwitte** [comment]
Thank you very much!
