### ISSUE TITLE
Document how to configure repository with Azure DevOps

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#8210]
We don't have plans to add support for Azure DevOps directly currently, but we have had a few requests for how to connect a repository manually. This is still possible, but we should go over how to connect the repository, how to add webhooks, and where applicable, private keys.

Might also be helpful to touch more on "Manually importing unsupported repository sources" in a guide, which we have only touched on in pieces in the documentaiton. We do touch on private key management for submodules https://docs.readthedocs.io/en/stable/guides/private-submodules.html -- but you might not find this if you don't use submodules. The directions are similar however.

**Comment by stsewd** [comment]
We already have this guide now
