### ISSUE TITLE
404 When using USE_SUBDOMAIN : False

### ISSUE THREAD

**Issue by ddquk** [readthedocs/readthedocs.org#8218]
I have successfully installed an instance of Read-the-Docs locally
If I set USE_ SUBDOMAIN:TRUE，I can view the docs press the green "View Docs" ,And docs are served via <project name>.<domain name>/<lang>/<version>. it works.
On the other hand, when USE_SUBDOMAIN = False, docs are served via <domain name>/docs/<projectname>/<lang>/<version>
a 404 (Page not found (404))

![image](https://user-images.githubusercontent.com/17616833/119719309-37c81580-be9b-11eb-97a7-d87447abe21e.png)

**Comment by stsewd** [comment]
@ddquk hi, we no longer support that option, if you are looking to contribute or have a custom installation you can use our docker setup at https://docs.readthedocs.io/en/stable/development/install.html as a reference. We don't support custom installations https://docs.readthedocs.io/en/stable/open-source-philosophy.html#unsupported
