### ISSUE TITLE
Version build is accessible, but settings page give 404

### ISSUE THREAD

**Issue by benjeffery** [readthedocs/readthedocs.org#8219]
## Details

I've found an old version of `msprime` docs are still accessible (version slug = `multi-requirements`) https://msprime.readthedocs.io/en/multi-requirements/

I'd like to remove this version as it is coming up in searches and confusing users, but the version is not listed on the "Versions" tab of the settings page. How do I remove this version?

Many thanks!

* Read the Docs project URL: https://msprime.readthedocs.io/en/multi-requirements/
* Read the Docs username (if applicable): benjeffery

## Expected Result

I can edit the settings of a deployed version to make it no longer accessible

## Actual Result

The version is not in the versions list, manually editing the URL to include the version slug results in 404.

**Comment by stsewd** [comment]
sorry about that, that was some leftovers from when we migrated from cloud providers. I have deleted all old files.

**Comment by stsewd** [comment]
Cache may be purged automatically after an hour or two.

**Comment by benjeffery** [comment]
Thanks so much for fixing! :heart:
