### ISSUE TITLE
ReadTheDocs Somehow don't say that it was built by mkdocs but it say built by sphinx

### ISSUE THREAD

**Issue by dumb-stuff** [readthedocs/readthedocs.org#8221]
## Details

* Read the Docs project URL: https://miraculous.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/miraculous/builds/13890978/
* Read the Docs username (if applicable): dumb-stuff

## Expected Result

Get my index.MD showed

## Actual Result

It doesn't show anything and I expect it going to have mkdocs introduction page (when you build with mkdocs but no .rst or .md files it gonna show the default mkdocs page right?) but instead I see this
![image](https://user-images.githubusercontent.com/59832159/120137520-b5bf5000-c1fe-11eb-9a1f-d740c6fa7d30.png)

**Comment by stsewd** [comment]
Hi, the documentation was actually built with sphinx, you need to change that in the admin of your project or use a config file https://docs.readthedocs.io/en/stable/config-file/v2.html?tab=MkDocs (recommended). But looks like you already figured out.
