### ISSUE TITLE
Can't find email address associated with username 

### ISSUE THREAD

**Issue by ThanhNguyenDo** [readthedocs/readthedocs.org#8225]
## Details

try to forget the github password for ndthanhkhtn@gmail.com. But it does not send the email, and show messages "Can't find email address associated with username "

## Expected Result

send an email to recover new password for account ndthanhkhtn@gmail.com

## Actual Result

It shows the message "Can't find email address associated with username"

**Comment by humitos** [comment]
Hi @ThanhNguyenDo! Please, contact our support team at support@readthedocs.org so we can guide you better privately without exposing any sensible information publicly.
