### ISSUE TITLE
Error on build: "Error: The markupsafe module cannot be found. Did you install Sphinx and its dependencies correctly?"

### ISSUE THREAD

**Issue by sloria** [readthedocs/readthedocs.org#823]
RTD URL: https://readthedocs.org/builds/textblob/

Example failing build: https://readthedocs.org/builds/textblob/1385110/

Strangely, only the `dev` version is failing to build. `latest` builds fine. The `dev-requirements.txt` I am using for the virtualenv is identical for the versions, and the `setup.py` is also identical. 

Any clues on this?

**Comment by ajdavis** [comment]
Just saw this a few minutes ago:
```
Build Standard Error



html
-----

Error: The markupsafe module cannot be found. Did you install Sphinx and its dependencies correctly?
```

Initial build of a standard boring Sphinx / Python HTML project:

https://readthedocs.org/builds/mockupdb/2391625/

Wiping the build dir fixed it.

**Comment by Spedge** [comment]
Just had the same issue in a private install, same error message. Again, as @ajdavis reported, wiping the build dir of the particular project it was trying to build worked.
