### ISSUE TITLE
How to set the `USE_SPHINX_LATEST` feature?

### ISSUE THREAD

**Issue by jrbourbeau** [readthedocs/readthedocs.org#8230]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/dask/
* Build URL (if applicable): https://readthedocs.org/api/v2/build/13915818.txt
* Read the Docs username (if applicable): jrbourbeau

## Expected Result

Since my project doesn't specify a version for `sphinx-rtd-theme` (nor do any of my project's dependencies), I expected the latest version of `sphinx-rtd-theme` to be installed (version 0.5.2 at the time of writing this issue)

## Actual Result

`sphinx-rtd-theme` 0.4.3 was installed instead because an additional `sphinx-rtd-theme<0.5` version constrain was added during the build installation step. 

From what I can tell this extra version constraint originates from here

https://github.com/readthedocs/readthedocs.org/blob/b586cf01482af58c534b4e0a3f60af1eb704dbfe/readthedocs/doc_builder/python_environments.py#L380-L386

However, I would like to have the latest `sphinx-rtd-theme` installed to avoid https://github.com/readthedocs/sphinx_rtd_theme/issues/1115. I'm wondering how I can set the `USE_SPHINX_LATEST` feature in order to avoid the  `sphinx-rtd-theme<0.5` constraint.

**Comment by humitos** [comment]
Hi @jrbourbeau! I added `USE_SPHINX_LATEST` to the project `dask`. Let me know if it works as you expected. Thanks!

**Comment by jrbourbeau** [comment]
That worked great, thank you @humitos! Could you also add `USE_SPHINX_LATEST` to `distributed` (https://readthedocs.org/projects/distributed) which is co-released with `dask`?
