### ISSUE TITLE
How to use a .readthedocs.yaml config file with subprojects?

### ISSUE THREAD

**Issue by qlyoung** [readthedocs/readthedocs.org#8234]
I believe this is a question and not a bug, though it could constitute a docs bug.

## Details

I'm reading through the documentation on using a config file for RTD available here:
https://docs.readthedocs.io/en/stable/config-file/v2.html#sphinx

My project's docs are composed of a main project and one subproject. The main project corresponds to path `doc/user` and the subproject corresponds to path `doc/developer` within the repository; we maintain two separate manuals, one for the user docs and one for development docs. Presently I have this set up properly using the RTD web interface and things work swimmingly. However, I'd like to switch to a config file for various reasons.

In the RTD docs, I don't see how I could express subprojects in the config file.

I apologize if I missed the answer in the docs or in a previous issue.

* Read the Docs project URL: http://docs.frrouting.org/en/latest/ and http://docs.frrouting.org/projects/dev-guide/en/latest/
* Read the Docs username (if applicable): qlyoung
* Project: https://github.com/frrouting/frr

**Comment by stsewd** [comment]
Hi, currently having several config files in the same repo isn't supported. We were discussing having an env var that users could add to read the config file from that location, so they could use the same repo imported twice.

**Comment by qlyoung** [comment]
Ok. Should I submit a PR to clarify the docs in this respect? They are very pro-config file but should mention that the config file doesn't support subprojects.

**Comment by stsewd** [comment]
> Ok. Should I submit a PR to clarify the docs in this respect? They are very pro-config file but should mention that the config file doesn't support subprojects.

Sure, but I'd use "It doesn't support multiple docs projects in the same repo" or "it doesn't support using multiple config files in the same repo", as subprojects sounds more like git subprojects, which we do support.

**Comment by qlyoung** [comment]
Ok, I can make this clear. Though I will note there's an entire section titled [Subprojects](https://docs.readthedocs.io/en/stable/subprojects.html), which ought to provide context.

**Comment by humitos** [comment]
Yeah, Read the Docs uses the concept of "Project" and "Sub-project". Git, on the other hand, uses "Sub-module".

**Comment by qlyoung** [comment]
@stsewd just to make sure - while you say that one repo can't support multiple config files there's no way to specify multiple projects in one config file, right? Conceptually that is what I expected when I have a project that has a subproject.

**Comment by stsewd** [comment]
> @stsewd just to make sure - while you say that one repo can't support multiple config files there's no way to specify multiple projects in one config file, right? Conceptually that is what I expected when I have a project that has a subproject.

Yeah that's it, you can import the same project, but can't use a different config file.

**Comment by KennethNielsen** [comment]
@qlyoung did you ever open the separate issue for this?

**Comment by qlyoung** [comment]
@KennethNielsen I did not, and I didn't submit a pull request either.

**Comment by KennethNielsen** [comment]
Ok. I think I will file it as a feature request then. I don't have the bandwidth to attempt a PR, but it can't hurt to raise it as a feature request.

**Comment by stsewd** [comment]
This feature is in our roadmap, so hopefully will be implemented in the next months.

**Comment by ewdurbin** [comment]
Is this still planned?

**Comment by stsewd** [comment]
@ewdurbin hi there, supporting multiple config filer per project is still pending a design decision at https://github.com/readthedocs/readthedocs.org/issues/8811, the issue here is about documenting the current limitation.

**Comment by benjaoming** [comment]
A quick update on why this issue is now closed and fixed:

The proposal from @ewdurbin in #10001 was adopted and will premiere in the next deployment. If there's any feedback, please don't hesitate to write here or open a new issue :+1:
