### ISSUE TITLE
Mixing of caching methods

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#8236]
We're currently using `lru_cache` and `cached_property` in the same class, and they seem to do the same thing:

https://github.com/readthedocs/readthedocs.org/blob/28ac0c252da17995c5d60853a1893368a53bf26c/readthedocs/embed/views.py#L125-L139

We should make these the same, or add a comment if there's a reason we have 2.

**Comment by stsewd** [comment]
The reason is that one is a property and the other a method call, I'm fine having the two, or refactor the cached_property to make it a method instead, as we have more methods than properties using a cache.

**Comment by humitos** [comment]
We can make all of the properties since they don't receive any argument, right?
