### ISSUE TITLE
Refactor how we build badge_only.css

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#8247]
Currently we embed https://github.com/readthedocs/readthedocs.org/blob/4083525f338130ade975b51076c776a2a5600e7e/media/css/badge_only.css on documentation pages that aren't our theme. This is so we can show the flyout to these users. We also ship a version of the flyout in the RTD theme itself. We should figure out a plan to making the flyout fully styled outside of the RTD theme, and let any theme override it. 

This would allow us to fully ship the CSS for the flyout as part of RTD, and remove the dependency on the theme from the larger platform.

**Comment by humitos** [comment]
This work is being done in https://github.com/readthedocs/addons/pull/66. Once we deploy the new flyout we will be able to remove all these files that we are injecting --which is tracked in https://github.com/readthedocs/addons/issues/72
