### ISSUE TITLE
Command killed due to excessive memory consumption

### ISSUE THREAD

**Issue by vringar** [readthedocs/readthedocs.org#8248]
## Details

* Read the Docs project URL: https://openwpm.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/openwpm/builds/
* Read the Docs username (if applicable): vringar

## Expected Result

I want ReadTheDocs to build the documentation for OpenWPM

## Actual Result

The builder runs out of memory when trying to create the conda environment.

Is there a way to either reduce the amount of memory I need or to increase the amount of memory available?

**Comment by astrojuanlu** [comment]
Hi @vringar , thanks for using Read the Docs! conda buiders already have maxed RAM. I have enabled usage of `mamba` for your project, which is a drop-in replacement for conda tht should be faster and consume less memory, and looks like builds are now passing. I'm closing the issue, feel free to open a new one if you experience any other problems.

**Comment by vringar** [comment]
Thank you so much for enabling this!
Is there anything we can do from our side to reduce the amount of RAM we use?

**Comment by astrojuanlu** [comment]
I see that you are already pinning all your dependencies in https://github.com/mozilla/OpenWPM/blob/master/docs/environment-rtd.yaml, which is what we recommend already in our [conda guide](https://docs.readthedocs.io/en/stable/guides/conda.html) ("Constrain the package versions as much as possible to reduce the solution space"). You could perhaps remove the `main` channel, although that will have a modest effect on the memory consumption. I think there is little we can do about conda being memory-hungry - fortunately, mamba is much more efficient.
