### ISSUE TITLE
Basic "npm install" command fails during build

### ISSUE THREAD

**Issue by pkgw** [readthedocs/readthedocs.org#8249]
## Details

* Read the Docs project URL: https://pywwt.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/pywwt/builds/13969079/
* Read the Docs username (if applicable): pkgw

## Expected Result

Docs build.

## Actual Result

During `pip install` of our package:

```
Building wheels for collected packages: pywwt, pyrsistent, pandocfilters
  Building wheel for pywwt (PEP 517): started
  Building wheel for pywwt (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/docs/checkouts/readthedocs.org/user_builds/pywwt/envs/latest/bin/python /home/docs/checkouts/readthedocs.org/user_builds/pywwt/envs/latest/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpcaaov2lb
       cwd: /tmp/pip-req-build-k27c0d0o
  Complete output (68 lines):
  running bdist_wheel
  running js-content
  Installing build dependencies with npm.  This may take a while...
  > npm install
  npm ERR! Linux 5.4.0-1035-aws
  npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
  npm ERR! node v8.10.0
  npm ERR! npm  v3.5.2
  npm ERR! code EMISSINGARG
  
  npm ERR! typeerror Error: Missing required argument #1
  npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
  npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
  npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
  npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
  npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
  npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
  npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
  npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
  npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
  npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
  npm ERR! typeerror This is an error with npm itself. Please report this error at:
  npm ERR! typeerror     <http://github.com/npm/npm/issues>
  
  npm ERR! Please include the following file with any support request:
  npm ERR!     /tmp/pip-req-build-k27c0d0o/frontend/npm-debug.log
```

I'm confused because it really does look like the system install of NPM is somehow borked here, and that just seems so unlikely.

**Comment by pkgw** [comment]
I suspect that we're facing this:

https://github.com/npm/cli/issues/681

with the RTD build using an extremely old version of NPM.

**Comment by stsewd** [comment]
Looks like pip is trying to build the package from source, and that requires a version of npm that isn't available on rtd (we use the default that comes with ubuntu). If you don't need that package to build the docs you can omit them when building your docs, but if you do you can also mock it https://docs.readthedocs.io/en/stable/faq.html#i-get-import-errors-on-libraries-that-depend-on-c-modules

**Comment by pkgw** [comment]
The package in question is our primary package, so we can't get away with skipping or mocking it. As far as I can tell, the best approach is to use a Conda environment and install a custom `nodejs` that's new enough.

The version of NPM in this image is very old, but I see that there are efforts to update the builder image, so I don't think this issue adds anything new. I'll close it out.

**Comment by astrojuanlu** [comment]
Hi @pkgw , indeed installing nodejs from conda-forge on RTD is your best bet. Let us know if you have trouble with it.

**Comment by minrk** [comment]
If anybody else finds themselves here, the new [v2 config](https://docs.readthedocs.io/en/stable/config-file/v2.html) has [build.tools.nodejs](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-nodejs) so you can specify node 16 without needing to invoke a conda install step:

```yaml
build:
  os: ubuntu-20.04
  tools:
    python: "3.9"
    nodejs: "16"
```

[this commit](https://github.com/jupyterhub/jupyterhub/pull/3779/commits/0c315f31b7c27c1602c07ad67afbf968f2eeab72) in [this PR](https://github.com/jupyterhub/jupyterhub/pull/3779) fixed our builds that suddenly started having the same issue today.
