### ISSUE TITLE
403 for objects.inv as downloaded by intersphinx

### ISSUE THREAD

**Issue by Terrance** [readthedocs/readthedocs.org#8251]
## Details

I've recently started encountering issues acquiring inventories (objects.inv) from RTD-hosted docs.

I'm building my own Python docs (on a local server, not on RTD), using [intersphinx](https://www.sphinx-doc.org/en/3.x/usage/extensions/intersphinx.html) to reference modules and classes from other projects, including one whose docs [are hosted on RTD](https://docs.telethon.dev/en/latest/).  In the last week or so, I've noticed some of the builds warning that they can't retrieve the inventory file from the docs in question.

## Actual Result

> $ make html
> Running Sphinx v3.5.4
> loading pickled environment... done
> loading intersphinx inventory from https://docs.telethon.dev/en/latest/objects.inv...
> WARNING: failed to reach any of the inventories with the following issues:
> intersphinx inventory 'https://docs.telethon.dev/en/latest/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 403 Client Error: Forbidden for url: https://docs.telethon.dev/en/latest/objects.inv

Checking in a browser, I can access the site and the inventory file without issue, though using curl on the server I appeared to be served a (presumably Cloudflare's) captcha hold page (I can't currently reproduce it though).

## Expected Result

If you're using methods to restrict machine access to documentation sites, it would be useful to have machine-readable files objects.inv exempt from restrictions.

**Comment by stsewd** [comment]
Hi, I think this is because we enabled the cloudflare firewall https://twitter.com/readthedocs/status/1402019277733974030.
We can maybe relax restriction over intersphinx files.

**Comment by davidfischer** [comment]
We disabled some firewall rules for `objects.inv` files. Please let us know if it works for you. I tried getting it with `curl` and `requests` without issue.

**Comment by Terrance** [comment]
Thanks!  Looks like it's retrieving the inventory fine for now; I'll keep an eye on it and let you know if things change.
