### ISSUE TITLE
bullet list stops working in recent builds

### ISSUE THREAD

**Issue by yzhao062** [readthedocs/readthedocs.org#8252]
## Details

Hi there, since a few builds ago, the bullet list stops working in my documentation. I am not exactly sure when did this first occur.

This affects all the pages (index and all other pages). In the local build, the bullet lists are rendered ok (see figures below).

* Read the Docs project URL: https://pyod.readthedocs.io/en/latest/index.html#
* Build URL (if applicable): https://readthedocs.org/projects/pyod/builds/13979249/
* Read the Docs username (if applicable): yuezhao9210

## Expected Result

*A description of what you wanted to happen*

**The correctly rendered local build**:
![image](https://user-images.githubusercontent.com/15079146/121562606-9fc44300-c9e7-11eb-9091-cb3bf18b190b.png)

## Actual Result

*A description of what actually happened*: the bullet points are incorrectly rendered as new lines only without any bullets.

**The current online version**:
![image](https://user-images.githubusercontent.com/15079146/121562496-828f7480-c9e7-11eb-9814-036ab80448c0.png)

Thanks a lot for the help.

**Comment by astrojuanlu** [comment]
Hi @yzhao062 ! You would have to pin `docutils<0.17`. This is a known issue https://github.com/readthedocs/sphinx_rtd_theme/issues/1115, and the latest version of `sphinx-rtd-theme` takes care of this pinning.

Closing this in favor of https://github.com/readthedocs/sphinx_rtd_theme/issues/1115, hope this helps!

**Comment by yzhao062** [comment]
Thanks @astrojuanlu . Pin to 0.16 fixes the issue. looking forward to the permanent solution :)
