### ISSUE TITLE
PDF builds not working?

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/readthedocs.org#8253]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/poliastro/
* Build URL (if applicable): https://readthedocs.org/projects/poliastro/builds/13985247/
* Read the Docs username (if applicable): Juanlu001

## Expected Result

As I have the "Enable PDF build" checkbox checked in my Advanced Settings, I expected a PDF download somewhere, either in the flyout menu or the "Downloads" section.

## Actual Result

There is no mention of a PDF in the flyout, and the https://readthedocs.org/projects/poliastro/downloads/ section is empty.

**Comment by stsewd** [comment]
The settings from the web admin are ignores when using a config file https://github.com/poliastro/poliastro/blob/main/.readthedocs.yml you need to list pdf as in the formats on the config file.

**Comment by astrojuanlu** [comment]
🤦🏽 I should have known this myself, thanks @stsewd

**Comment by sachin-suresh-rapyuta** [comment]
I have the below code in my readthedocs.yaml file and also PDF checkbox is checked in Advanced Settings, but still I dont see the PDF download option in the flyout menu.

Project_root/.readthedocs.yaml

```
# Required
version: 2
...
...
# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
```

Am I missing anything?

**Comment by astrojuanlu** [comment]
Hi @sachin-suresh-rapyuta, I'd recommend you open a new issue following the template 👍🏽
