### ISSUE TITLE
Webhook warning persists after deleting project

### ISSUE THREAD

**Issue by CodeMouse92** [readthedocs/readthedocs.org#8255]
## Details

* Read the Docs project URL: N/A
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): mousepawmedia

## Expected Result

I had set up a manual project, but realized I'd made a mistake in the slug. Meanwhile, I was getting the warning...

> The project MousePaw Media Development Documentation doesn't have a valid webhook set up, commits won't trigger new builds for this project. See the project integrations for more information.

I expected that error to disappear when I deleted the project (which I did).

## Actual Result

The error message still appears at the top of my account pages. Constantly. Forever. Clicking the provided links goes to "Maze Found" because, obviously, the project doesn't exist anymore.

**Comment by humitos** [comment]
Hi @CodeMouse92! This is a known issue and the only way to remove the notification, for now, is just by clicking on the link it has on its message.

@agjohnson I know that we talked a lot about the "new notification system", but I'm not sure where we landed at. Are you planning a solution for this on the new templates?

**Comment by CodeMouse92** [comment]
> Hi @CodeMouse92! This is a known issue and the only way to remove the notification, for now, is just by clicking on the link it has on its message.

I have done so a few times. It hasn't removed it yet.

**Comment by stsewd** [comment]
@CodeMouse92 do you have js enabled? Because behind the scenes we capture the click event and first remove the notification before redirecting to the link, that require js enabled.

**Comment by CodeMouse92** [comment]
Yes, I have JS enabled.

**Comment by stsewd** [comment]
@CodeMouse92 we have added a close button to individual notification now, you should be able to close it now.

**Comment by CodeMouse92** [comment]
Resolved, thank you!
