### ISSUE TITLE
"Custom Domains and White Labeling" contains no information on white labeling

### ISSUE THREAD

**Issue by LoganDark** [readthedocs/readthedocs.org#8257]
## Details

The page "[Custom Domains and White Labeling](https://docs.readthedocs.io/en/stable/custom_domains.html)" contains no mentions of white labeling besides the title. 

I expected to see at least some mention of it, even if it's just to say that white labeling is not supported, or only supported behind an expensive paid tier. Because now I'm curious and can't find any information about it online.

**Comment by humitos** [comment]
Hi @LoganDark. You are right! The page doesn't guide you through how to have a full white-labeled project. We need to update it with that particular content.

However, it's supported to some degree. You can change the theme from your project, and use custom 404 pages. Besides, you can add some extra CSS (https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html).

That said, there are some things that are not currently possible to change. These include:

- 500.html page
- login page (Read the Docs for Business)
- maybe other that I don't have in mind now (please, comment if you have any other specific page in mind)

**Comment by humitos** [comment]
We don't have any mention to white labeling anymore.
