### ISSUE TITLE
Recovering access to documentation

### ISSUE THREAD

**Issue by ana-nichifor** [readthedocs/readthedocs.org#8258]
## Details

* Read the Docs project URL: 
https://pycaption.readthedocs.io/en/stable/
* Read the Docs username (if applicable):
ana-nichifor

Hi, we've been trying for some time to find out who's the owner of this project in order to obtain access and bring it up to date, but with no success unfortunately. Could you help us by either transferring access or renaming the project so we can create a new one with this name? Both solutions would work fine for us. Let me know if you need more details.

Thank you!

**Comment by stsewd** [comment]
Hi, the owner is https://readthedocs.org/profiles/arielpontes/, if you don't know that person we can follow our policy here https://docs.readthedocs.io/en/stable/abandoned-projects.html

**Comment by ana-nichifor** [comment]
Hi, thank you for this information! We succeeded getting in touch with him and gained access to the project.
