### ISSUE TITLE
Docs for deleted branch still being around

### ISSUE THREAD

**Issue by The-Compiler** [readthedocs/readthedocs.org#8264]
## Details

* Read the Docs project URL: https://pytest.readthedocs.io/ / https://docs.pytest.org/
* Build URL (if applicable): https://docs.pytest.org/en/reorganize-docs/
* Read the Docs username (if applicable): The-Compiler

A couple of years ago, we created a `reorganize-docs` branch, trying to restructure our documentation. Even after deleting the branch and removing it as version from RTD, the docs are still around at the build URL above:

![image](https://user-images.githubusercontent.com/625793/122017508-52b6e700-cdc2-11eb-95c1-ced1be865abc.png)

Even trying to add a redirect to the main docs doesn't seem to have any effect. As a result, people often accidentally refer to 6 year old docs, because those links seem to often show up in Google search results:

https://github.com/pytest-dev/pytest/issues/4115#issuecomment-429194220
https://github.com/pytest-dev/pytest/issues/8094
https://github.com/pytest-dev/pytest/issues/8665#issuecomment-841390317

etc. etc.

We've agreed to delete that branch:

https://github.com/pytest-dev/pytest/issues/4120
https://github.com/pytest-dev/pytest/issues/8098

And from what I (and other admins) can see, it doesn't show up anywhere in the admin panel anymore.

## Expected Result

The docs being gone, and/or us being able to delete them somewhere in the admin panel, and/or a redirect working.

## Actual Result

Zombie docs :scream:

**Comment by stsewd** [comment]
Hi, sorry about that, this is likely happened when we migrated from cloud providers. I have deleted the old docs from our storage, cache should be purged in 2 hours max.

**Comment by The-Compiler** [comment]
Thanks @stsewd for the quick fix! I'm hoping this will help to make those disappear from search results.

I'm now trying to add a redirect for those:

![image](https://user-images.githubusercontent.com/625793/123908473-dd2d4800-d977-11eb-913c-f8258f276303.png)

but e.g. https://docs.pytest.org/en/reorganize-docs/index.html doesn't redirect as expected. Is that due to something still being around, or am I doing something wrong there?

**Comment by stsewd** [comment]
@The-Compiler you need to use an exact redirect instead. `/en/reorganize-docs/$rest -> /en/6.2.x/`

https://docs.readthedocs.io/en/stable/user-defined-redirects.html#exact-redirects

**Comment by stsewd** [comment]
a prefix redirect is used when you have migrated your docs from another service.

**Comment by The-Compiler** [comment]
Ah, that makes sense!

I should've guessed there's some great documentation about the admin interface somewhere, but it wasn't obvious to me that's in a totally separate place, and not linked from the explanations on the page. I opened a PR to fix that: #8308.

Thanks for all the help! :+1:
