### ISSUE TITLE
Don't show the rebuild option for closed/merged PRs

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#8267]
Currently, we show the option for closed PRs, but when clicking the option it will show you a 404 page since our queryset doesn't include inactive versions (versions from closed/merged PRs are marked as inactive to be deleted after 3 months or so)

**Comment by arimanyus** [comment]
Can I look into this?

**Comment by humitos** [comment]
@arimanyus sure! go ahead! Let us know if the issue's description is clear. Feel free to send a PR with a proposal 👍🏼
