### ISSUE TITLE
Wrong version/language prefix added to 404 page

### ISSUE THREAD

**Issue by GrabowskiM** [readthedocs/readthedocs.org#8272]
## Details

* Read the Docs project URL: https://doc.ibexa.co/en/latest
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

When loading 404 page everything works, links have correct prefix depending on version and language in address bar.

## Actual Result

All links are prefixed with `en/latest`
As you can see in these two cases:
https://doc.ibexa.co/en/latest/aaa
https://doc.ibexa.co/en/404-fix/aaa (This one is hidden, as it's only for tests purpose only)
404 page is loaded depending on version (I added "custom" word to content to test it) but still all links (including js and css files) are prefixed with en/latest (where latest id default version), it breaks many things, including version switcher, as request is done for latest version.
I tried to find some config option or anything to fix it, but weren't able to glimpse anything useful.

**Comment by humitos** [comment]
Hi @GrabowskiM! I'm not sure to understand the result you are expecting. Can you expand on the example you shared mentioning what's showing and what you were expecting?

If I enter to https://doc.ibexa.co/en/latest/aaa I see a proper 404 page and the assets as, eg. `/en/latest/assets/stylesheets/main.ca7ac06f.min.css`, which looks correct to me. What's wrong with it?

**Comment by GrabowskiM** [comment]
Latest works ok, the problem is with other versions, for instance this one: https://doc.ibexa.co/en/2.5/aaa it's version 2.5 but it loads all the links with `en/latest` prefixes, like here:
```
        <script src="/en/latest/assets/javascripts/bundle.76f349be.min.js"></script>
      
        <script src="/en/latest/js/jquery.min.js"></script>
      
        <script src="/en/latest/js/jquery-ui.min.js"></script>
      
        <script src="/en/latest/js/custom.js"></script>
      
        <script src="/en/latest/js/docs.switcher.js"></script>
      
        <script src="/en/latest/js/ez-guidelines-switchers.js"></script>
      
        <script src="/en/latest/js/ez-guidelines-modals.js"></script>
      
        <script src="//cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
      
        <script src="/en/latest/readthedocs-data.js"></script>
        ```
Also all links in sidebar are prefixed with `en/latest` instead of `en/2.5`

**Comment by humitos** [comment]
Read the Docs does not modify the `src=` attribute from your HTML files. Are you using the extension [`sphinx-notfound-page`](https://sphinx-notfound-page.readthedocs.io/en/latest/)? In that case, you should use [`notfound_urls_prefix`](https://sphinx-notfound-page.readthedocs.io/en/latest/configuration.html#confval-notfound_urls_prefix) config to match the version currently being built.
