### ISSUE TITLE
Broken links with mkdocs

### ISSUE THREAD

**Issue by tastybento** [readthedocs/readthedocs.org#8273]
## Details

MKDocs links that have worked fine broke after the site was rebuilt yesterday following commits to the GitHub repo. The last commit was about a month ago and everything has been working until yesterday. Did something change with the engine?

For example, on this [page](https://docs.bentobox.world/en/latest/gamemodes/AcidIsland/index.html) there is a "Placeholders can be found here" line. The mkdocs for this is:

`Placeholders can be found [here](Placeholders).`

The source for the page is [here](https://github.com/BentoBoxWorld/docs/blob/master/docs/gamemodes/AcidIsland/index.md).

There is the appropriate Placeholders.md file in the directory:
<img width="487" alt="Screen Shot 2021-06-19 at 9 33 16 AM" src="https://user-images.githubusercontent.com/4407265/122649149-64a9ca00-d0e1-11eb-8e17-402373cd220d.png">

* Read the Docs project URL: https://docs.bentobox.world/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/bentobox-world/builds/
* Read the Docs username (if applicable): tastybento

## Expected Result

When clicking on the Placeholders link in the index, it should link to the Placeholders.md file.

## Actual Result
When clicking on the link, you get the big 404 error.

The resulting link in the HTML built yesterday is:
 `https://docs.bentobox.world/en/latest/gamemodes/AcidIsland/Placeholders` This breaks. However, adding html to the URL as in `https://docs.bentobox.world/en/latest/gamemodes/AcidIsland/Placeholders.html` works. As far as I know, this conversion is all handled by the mkdocs engine, so I'm not sure how I could break it and I'm not sure how I can work around it even. Please help!

**Comment by astrojuanlu** [comment]
Hi @tastybento , thank you for using Read the Docs! I notice that you don't have your mkdocs version pinned, and therefore the recent 1.2.1 release might have broken something:

https://www.mkdocs.org/about/release-notes/#version-12-2021-06-04

In particular:

> The site_url configuration option is now required. If it is not set, a warning will be issued. In a future release an error will be raised (# 2189).
> The use_directory_urls configuration option will be forced to false if site_url is set to an emtpy string. In that case, if use_directory_urls is not explicitly set to false, a warning will be issued 

Would you please either

- review your project configuration or
- pin your mkdocs version

and see if that fixes the issue?

**Comment by tastybento** [comment]
That did fix the issue! Thanks. I pinned it to 1.1.2 (for now). I'll also go and pin the other dependencies as per what is written here: https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#pinning-dependencies
