### ISSUE TITLE
More translateable text for website & doc side panel

### ISSUE THREAD

**Issue by Blueberryy** [readthedocs/readthedocs.org#8280]
I wish someone can make https://readthedocs.org/ website fully translateable and these from doc side panel
![Screenshot_20210623-193128_Chrome](https://user-images.githubusercontent.com/36592509/123115961-f3a84080-d459-11eb-9e6b-ce5e7d8645c8.jpg) "On Read the Docs", "Project Home" and "On github"
![Screenshot_20210623-193151_Chrome](https://user-images.githubusercontent.com/36592509/123116176-1df9fe00-d45a-11eb-96bb-3c2d8a201822.jpg) "Hosted by Read the Docs"
![Screenshot_20210623-193202_Chrome](https://user-images.githubusercontent.com/36592509/123116292-35d18200-d45a-11eb-9c0f-125ba1dd89a8.jpg) "Search docs"
![Screenshot_20210623-193237_Chrome](https://user-images.githubusercontent.com/36592509/123116352-4681f800-d45a-11eb-9450-dfbe1fa9cd81.jpg) "Languages"

**Comment by stsewd** [comment]
Hi, those are using translations https://github.com/readthedocs/readthedocs.org/blob/c86f18a4bffa828a0b71a5f4107545e2468d593a/readthedocs/api/v2/templates/restapi/footer.html#L42 we just need to update/add the translations for the language you are using on your browser. https://github.com/readthedocs/readthedocs.org/issues/4462
