### ISSUE TITLE
Increase the width for build messages.

### ISSUE THREAD

**Issue by kolibril13** [readthedocs/readthedocs.org#8289]
In the building process, the width of the  for error messages is a bit small:
(the error itself does not play any role in this issue.)
![image](https://user-images.githubusercontent.com/44469195/123547839-a6caaf80-d762-11eb-92d2-88d091fbd207.png)
Increasing the size of this frame would make it more convenient to read the error messages.

**Comment by humitos** [comment]
Hi! Thanks for the report. We are already aware of this and we are working on a full re-design of this page and this is already considered.

**Comment by stsewd** [comment]
You should be able to horizontal scroll that section, on firefox the scroll bars are always shown

**Comment by kolibril13** [comment]
Thanks for your feedback! 
Looking forward to the new design 🙂
