### ISSUE TITLE
project is currently disabled and can't trigger new builds

### ISSUE THREAD

**Issue by AgentDS** [readthedocs/readthedocs.org#8290]
## Details

* Read the Docs project URL: https://readthedocs.com/projects/fedlab-fedlab/
* Build URL (if applicable): https://readthedocs.com/projects/fedlab-fedlab/builds/
* Read the Docs username (if applicable): AgentDS (linked from GitHub)

Hello,
When I try to build a new version of my documentation, I get the message "This project is currently disabled and can't trigger new builds." And it seems the project haven't been build since 2 months, 2 weeks ago.

## Expected Result

I wished my project to be enabled and to be able to build new version of my doc.

Please help we with that.

Regards

**Comment by humitos** [comment]
Hi @AgentDS!

Please contact our Read the Docs for Business support at https://readthedocs.com/support/

This repository is only for the community version.
