### ISSUE TITLE
Please set `USE_SPHINX_LATEST` and/or `PIP_ALWAYS_UPGRADE` for Fuzzinator

### ISSUE THREAD

**Issue by renatahodovan** [readthedocs/readthedocs.org#8324]
Fuzzinator has changed where its dependencies are specified. Previously, documentation-related deps were listed as `[docs]` extra requirements, but now they have been moved to a `docs/requirements.txt` file. However, RTD calls pip differently depending on whether it's a "requirements file" installation or a "package" installation. I.e., a "package" installation will do something like `pip install --upgrade --upgrade-strategy eager .[docs]` while a "requirements file" installation will trigger a `pip install -r docs/requirements.txt` (note the lack of `--upgrade`). (https://github.com/readthedocs/readthedocs.org/blob/master/readthedocs/doc_builder/python_environments.py) This matters, because both `[docs]` and `docs/requirements.txt` specified sphinx as a dependency (as well as sphinx_rtd_theme), but only the extra req-based approach ensured the installation of latest Sphinx.

Similar discussions found at:
- https://github.com/readthedocs/readthedocs.org/issues/2569
- https://github.com/readthedocs/readthedocs.org/issues/8230

## Details

* Read the Docs project URL: https://readthedocs.org/projects/fuzzinator/
* Read the Docs username (if applicable): renatahodovan

## Expected Result

Excerpt from last successful build log: https://readthedocs.org/projects/fuzzinator/builds/14157601/

```
Running Sphinx v4.0.2
...
build succeeded, 1 warning.
```

## Actual Result

Excerpt from most recent build log: https://readthedocs.org/projects/fuzzinator/builds/14185468/

```
Running Sphinx v1.8.5
...
Sphinx error:
master file /home/docs/checkouts/readthedocs.org/user_builds/fuzzinator/checkouts/latest/docs/contents.rst not found
```

**Comment by stsewd** [comment]
Done! https://readthedocs.org/projects/fuzzinator/builds/14187200/

**Comment by renatahodovan** [comment]
@stsewd Thanks!
