### ISSUE TITLE
MinIO update broke developer installation setup

### ISSUE THREAD

**Issue by RuRo** [readthedocs/readthedocs.org#8332]
## Details

4 days ago, a [new version of MinIO](https://github.com/minio/minio/releases/tag/RELEASE.2021-07-08T01-15-01Z) was released. It contains the following breaking change:

> Embedded MinIO Browser removed replaced with MinIO Console project https://github.com/minio/console, this is a **breaking** change
> > MinIO redirects browser access requests to the configured server port (i.e. `127.0.0.1:9000`) to the configured Console port. MinIO uses the hostname or IP address specified in the request when building the redirect URI. The URL and port *must* be accessible by the client for the redirection to work

This breaks the current development setup in 2 ways:
1) `http://localhost:9000/` now redirects to `http://localhost:<some_port>/ ` where `<some_port>` is dynamically generated at MinIO startup. Since this port isn't forwarded, you can't configure MinIO:

   ```
   WARNING: MINIO_ACCESS_KEY and MINIO_SECRET_KEY are deprecated.
            Please use MINIO_ROOT_USER and MINIO_ROOT_PASSWORD
   API: http://10.10.0.2:9000  http://127.0.0.1:9000 

   Console: http://10.10.0.2:<some_port> http://127.0.0.1:<some_port> 

   Documentation: https://docs.min.io

   WARNING: Console endpoint is listening on a dynamic port (<some_port>), please use --console-address ":PORT" to choose a static port.
   ```
2) Even if you manually add the `--console-address` setting and forward the appropriate port, the [instructions in step 7](https://docs.readthedocs.io/en/stable/development/install.html) still don't make sense, since there doesn't seem to be a `static` bucket anywhere and the UI is different.

**Comment by astrojuanlu** [comment]
Thanks @RuRo , I can reproduce. A quick solution can be to pin the minio version in https://github.com/readthedocs/common/:

```diff
diff --git a/dockerfiles/docker-compose.yml b/dockerfiles/docker-compose.yml
index 95c4865..7eafcfd 100644
--- a/dockerfiles/docker-compose.yml
+++ b/dockerfiles/docker-compose.yml
@@ -144,7 +144,7 @@ services:
       readthedocs:
 
   storage:
-    image: minio/minio
+    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
     ports:
       - "9000:9000"
     environment:
```
