### ISSUE TITLE
enable DONT_SHALLOW_CLONE for mud

### ISSUE THREAD

**Issue by mathematicalmichael** [readthedocs/readthedocs.org#8333]
## Details
* Read the Docs project URL: https://readthedocs.org/projects/mud/
* Build URL (if applicable): https://readthedocs.org/projects/mud/builds/
* Read the Docs username (if applicable): mathematicalmichael

Would it please be possible to disable shallow clones for the project above, as discussed at #5031? I am using `setuptools_scm` to pick up the project version. Finally got it showing `0.0.0` instead of `unknown` and I believe the clone depth is why.

Apologies if this is the incorrect forum for the request.

I'll be doing this for `mud-examples` soon as well, once I get everything validated with `mud`.

**Comment by humitos** [comment]
Hi @mathematicalmichael! I've disabled shallow clones in your project. Please let me know if there is any problem.

**Comment by mathematicalmichael** [comment]
thanks for the timely response! much appreciated.
I can see in the build steps that it no longer has the "depth 50" flag: https://readthedocs.org/projects/mud/builds/14220933/

However, I am still seeing `0.0.0` as the version in https://mud.dataconsistent.com/en/latest/ (better than 'unknown' in https://mud.dataconsistent.com/en/stable/), _and_ the readthedocs button in the bottom corner doesn't expand at all (clicking on it does nothing)

---


relevant bit of the conf.py file:
```
# The short X.Y version.
version = ""  # Is set by calling `setup.py docs`
# The full version, including alpha/beta/rc tags.
release = ""  # Is set by calling `setup.py docs`

...

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
try:
    from mud import __version__ as version
    release = version
except ImportError:
    pass
else:
    release = version
```

and locally:
```
$ python -c 'from mud import __version__; print(__version__)'
0.0.24.post1.dev7+g01a0d00
```

**Comment by mathematicalmichael** [comment]
figured it out! 
my requirements.txt file inside of `docs` which was being pointed to for the installation was missing `setuptools_scm`. I now have versions working! https://mud.dataconsistent.com/en/hotfix-readthedocs-version/

only problem remaining is why the "fly out" menu isn't working.

**Comment by mathematicalmichael** [comment]
fly out menu ended up just being a safari-specific experience. weird. downloaded opera to check and it worked fine there.

**Comment by mathematicalmichael** [comment]
@humitos noticing that safari consistently doesn't allow the flyout menu. mobile + desktop both exhibit the behavior.
I don't see an existing issue tracking this. Basically it's just unresponsive entirely. 

This person faced a similar issue it seems: https://stackoverflow.com/questions/66436744/how-to-activate-the-rtd-flyout-menu. Playing with "prevent cross-site tracking" does nothing.

My question is... should I open a new issue to track this behavior or is this a known thing?

**Comment by stsewd** [comment]
> My question is... should I open a new issue to track this behavior or is this a known thing?

Yes, please, provide the version of the browser you are using and maybe if there is anything in the logs from the console.
