### ISSUE TITLE
Use long-form build options in our Sphinx builds

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#8339]
Currently when you look at the Sphinx builds on RTD, it's super hard to understand what all the options do. We should switch from `-m sphinx -T -E -b html -d _build/doctrees -D language=en` to using the long-form options so users have more understanding of what is happening. 

This change should happen in this file, and just add long-form arguments instead of the short one: 
https://github.com/readthedocs/readthedocs.org/blob/b3baa7a7a90b78d0c4f730d88b54fdb20ee72805/readthedocs/doc_builder/backends/sphinx.py#L263-L281

**Comment by humitos** [comment]
As a general rule, I'm 👍🏼 on using long-form arguments on scripts and any non-human-typed commands.

**Comment by jklaise** [comment]
Looking at the `sphinx-build` argument parser it's not clear that long-form options for most of these commands even exist, or am I missing something: https://github.com/sphinx-doc/sphinx/blob/336605b8e4b14c5da9f4d872fb730dc6894edb77/sphinx/cmd/build.py#L101

**Comment by stsewd** [comment]
@jkeyes you are right! the only long form option is `--keep-going` https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-keep-going which is already used.
We already use long options for mkdocs https://github.com/readthedocs/readthedocs.org/blob/2b303d2acbeceae9612902b34a1acb27247bfb20/readthedocs/doc_builder/backends/mkdocs.py#L280-L299

So we can close this
