### ISSUE TITLE
safari doesn't allow the flyout menu. mobile + desktop

### ISSUE THREAD

**Issue by mathematicalmichael** [readthedocs/readthedocs.org#8341]
I am noticing that safari consistently doesn't allow the flyout menu. mobile + desktop both exhibit the behavior. Desktop Safari: Version 14.1.1 (16611.2.7.1.4)
Mobile Safari: iOS 14.6

I don't see an existing issue tracking this. Basically it's just unresponsive entirely. 

This person faced a similar issue it seems: https://stackoverflow.com/questions/66436744/how-to-activate-the-rtd-flyout-menu. Playing with "prevent cross-site tracking" does nothing.

_Originally posted by @mathematicalmichael in https://github.com/readthedocs/readthedocs.org/issues/8333#issuecomment-878507605_

Console from Safari (when I click on the flyout menu):
<img width="1344" alt="image" src="https://user-images.githubusercontent.com/40366263/125384062-98c98100-e355-11eb-870b-e11c3d04eaa0.png">

Opening it in Opera shows that it works, so I think it's the browser. nothing in that console.

site: mud.rtfd.io

**Comment by stsewd** [comment]
This looks comming from https://github.com/readthedocs/readthedocs.org/blob/fe7fda029f818d3ca3a555e3f84c422b0c51c52b/media/javascript/readthedocs-analytics.js#L21-L21. Maybe something to do with safari's built-in antitracker?

**Comment by stsewd** [comment]
From https://developers.google.com/gtagjs/devguide/datalayer we are using it like in the example. Maybe safari needs to be explicit about globals? Can you try this on your safari console (sorry, I don't use mac).

```js
window.dataLayer = window.dataLayer || [];
dataLayer
```

**Comment by mathematicalmichael** [comment]
@stsewd wow that was magic.
I entered that into the console and wam-bam the flyout menu worked!

**Comment by Daltz333** [comment]
Bump. Had a user bring this up.

**Comment by Daltz333** [comment]
Another bump. This is critical functionality. This means language pop-out menu does not work on iPhone devices, which is a large portion of our viewer base.

**Comment by stsewd** [comment]
If this code works on the console https://github.com/readthedocs/readthedocs.org/issues/8341#issuecomment-880359626, then I'm not sure what the problem could be, can't debug more since I don't use safari.

**Comment by ericholscher** [comment]
I have Safari and can confirm this issue and the fix. Do we just need to put `window.dataLayer = window.dataLayer || [];` in our JS?

**Comment by stsewd** [comment]
Just to be clear, we do have that line in our current js https://github.com/readthedocs/readthedocs.org/blob/fe7fda029f818d3ca3a555e3f84c422b0c51c52b/media/javascript/readthedocs-analytics.js#L20, we might have a syntax error (missing `;` in the above statement). We will confirm this in a couple of hours.

**Comment by ericholscher** [comment]
I'm trying to reproduce this, and I can't figure out what's happening. It only appears to happen on the `mud` docs. I tried it on:

* RTD docs, works: https://docs.readthedocs.io/en/latest/
* Another furo theme, works: https://urllib3.readthedocs.io/en/stable/

So I'm not really sure how to diagnose this without a bit more information. It seems to only be effecting a small number of docs sets -- is there anything you can do on your docs to stop this from happening? Or cause it to happen on other docs -- I can't really figure out the issue without being able to reproduce it.

**Comment by Daltz333** [comment]
Another case is https://docs.wpilib.org/en/stable

**Comment by ericholscher** [comment]
It looks like you've disabled google analytics on your projects? Guessing that's the issue.

**Comment by ericholscher** [comment]
The block of code that's executing isn't being run, but somehow that function is being defined:

https://github.com/readthedocs/readthedocs.org/blob/master/media/javascript/readthedocs-analytics.js#L20-L21

So somehow line 20 is not being executed, but line 21 it, it seems.

**Comment by davidfischer** [comment]
Strangely only seems to affect Safari though due to a subtle difference in scope of a defined function. Regardless, should be a simple fix.

**Comment by ericholscher** [comment]
I did a PR to fix this by disabling the caller when analytics are disabled. I think there's probably a better solution if someone knows JS well, but the naive approach should solve this issue at least.

**Comment by mathematicalmichael** [comment]
I really appreciate the fix, because yes, I did disable google analytics. 

Very odd that it's so Safari specific. 

Thank you all so much!
