### ISSUE TITLE
Project logo missing since 5.0.2 update

### ISSUE THREAD

**Issue by ceb8** [readthedocs/readthedocs.org#8343]
## Details

* Read the Docs project URL: https://astrocut.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/astrocut/builds/14232858/
* Read the Docs username (if applicable): ceb8

Starting today (13 Jult 2021) the project logo in the left sidebar is not appearing, and instead is the word "logo" that functions as the same link the image used to. This is the behavior I get when the logo image cannot be found, however nothing in the main branch of my repository has changed since the last tagged version, and the logo shows on that version.

I use "html_logo" and "html_favicon" to set the logo and favicon in my conf.py file.

## Expected Result
The is what I expect the sidebar to look like.

![Screen Shot 2021-07-13 at 3 50 38 PM](https://user-images.githubusercontent.com/9406508/125515989-7d6c0efd-4864-4ec3-b478-983d1605b7bf.png)

## Actual Result

This is what the sidebar now looks like.

![Screen Shot 2021-07-13 at 3 51 29 PM](https://user-images.githubusercontent.com/9406508/125516117-d6adc309-88f8-480c-83b6-23da88fdd3e3.png)

**Comment by astrojuanlu** [comment]
This is because of https://github.com/sphinx-doc/sphinx/issues/9438, you can pin Sphinx to `!=4.1.0` and 4.1.1 will be out soon

**Comment by ceb8** [comment]
That worked!! Thank you!!
