### ISSUE TITLE
Typo in documentation ("vieweable")

### ISSUE THREAD

**Issue by anirvan** [readthedocs/readthedocs.org#8346]
## Details

* Read the Docs project URL: https://readthedocs.org/

## Expected Result

The section on "Downloadable formats" refers to docs being viewable

## Actual Result

The word "viewable" is misspelled as "vieweable"

**Comment by humitos** [comment]
@anirvan thanks for reporting this! do you want to open a PR with this change?

**Comment by anirvan** [comment]
@humitos I would have, but the "vieweable" spelling is also present in the translatable strings in the .po files, and I wasn't sure of the best way to fix that without breaking translation workflows.

Could you (or someone else who understands the workflow) make the fix?

Thanks!

**Comment by stsewd** [comment]
@anirvan we use a script to update the po files, we don't touch those manually. You don't need to update those in your PR.

**Comment by Nkarnaud** [comment]
https://github.com/readthedocs/readthedocs.org/pull/8351

**Comment by astrojuanlu** [comment]
Closed in #8351
