### ISSUE TITLE
Wrong sphinx.configuration path causes not correct error message

### ISSUE THREAD

**Issue by NickVeld** [readthedocs/readthedocs.org#8352]
## Details

* Read the Docs project URL:
    https://readthedocs.org/projects/battery-handyman/
* Build URL (if applicable):
    - Failed: https://readthedocs.org/projects/battery-handyman/builds/14266261/
    - Passed: https://readthedocs.org/projects/battery-handyman/builds/14266265/

* Read the Docs username (if applicable):

## Expected Result

*A description of what you wanted to happen*

After `.readthedocs.yml` creation the build is passed too.

## Actual Result

*A description of what actually happened*

After `.readthedocs.yml` creation the build is failed because `sphinx` starts opening `docs/index.rst` instead of `docs/source/index.rst`.

From the logs of the failed build:
```
sphinx.errors.SphinxError: master file /home/docs/checkouts/readthedocs.org/user_builds/battery-handyman/checkouts/latest/docs/index.rst not found
```

After `.readthedocs.yml` deletion everything works fine. See the passed build.

**Comment by astrojuanlu** [comment]
Hi @NickVeld ! The problem was here:

```python
sphinx:
   configuration: docs/conf.py
```

https://github.com/NickVeld/battery_handyman/commit/8add82577c82810bc92c40ee8d3dae3b29337546#diff-cde814ef2f549dc093f5b8fc533b7e8f47e7b32a8081e0760e57d5c25a1139d9L8-L9

Your configuration is in `docs/source/conf.py` instead. Can you confirm that restoring the `.readthedocs.yaml` with the correct path for `conf.py` fixes the issue?

**Comment by NickVeld** [comment]
Hello, @astrojuanlu 

Yeah, thanks for the hint! After the path fix the docs was built successfully.
Then I am renaming the issue to the suggestion to provide more readable error for this case. 

But the strangest thing is that the [build](https://readthedocs.org/projects/battery-handyman/builds/14266277/) is passed with the following setting in the Admin Web UI:
![image](https://user-images.githubusercontent.com/17028401/126073882-30c3f7b2-c45f-4e59-8f61-de39ddc2de31.png)

**Comment by stsewd** [comment]
> But the strangest thing is that the build is passed with the following setting in the Admin Web UI:

When not using a config file, a lot of magic happens.... Like we try to find another config file if the one you provided doesn't exist, that's for backwards compatibility.

**Comment by NickVeld** [comment]
I see, thanks

**Comment by humitos** [comment]
@stsewd I think it's fine to close this issue. If not, what's the actionable we have to do from our side to be able to close it?
