### ISSUE TITLE
could not read Username for 'https://github.com and webhooks not working ?

### ISSUE THREAD

**Issue by ajh123** [readthedocs/readthedocs.org#8353]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/historysurvival/
* Build URL (if applicable): https://readthedocs.org/projects/historysurvival/builds/14267917/
* Read the Docs username (if applicable): ajh123

## Expected Result

The documentation to build / upload successfully 

## Actual Result

Build failed with ```fatal: could not read Username for 'https://github.com': terminal prompts disabled```

So i have a public [repo](https://github.com/ajh123-development/HistroySurvival) with my [docs folder here](https://github.com/ajh123-development/HistroySurvival/tree/main/docs) . I got the web-hooks made to ( based on [this](https://docs.readthedocs.io/en/stable/webhooks.html#github) ) but they are also failing with a 400 code.

Everything is going wrong :(
At least the rst's are being generated in the docs/soucre folder!

**Comment by stsewd** [comment]
@ajh123 looks like your repo url is wrong, you are using https://github.com/ajh123-development/HistorySurvival on read the docs, but your project is called HistroySurvival on github

**Comment by ajh123** [comment]
YAAA, it works!
