### ISSUE TITLE
Define Python supported versions as strings instead of float

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#8361]
In https://github.com/readthedocs/readthedocs.org/pull/8328#discussion_r666366384 we realized that we are using floats to set the version of Python (`3.5`, `3.8`, `3.10`) which doesn't make sense and breaks due to `3.10` is `3.1`.

This is the setting involved here:

https://github.com/readthedocs/readthedocs.org/blob/e5fe9ac7a7229e8a6972d5bce84b50e49ba62592/readthedocs/settings/base.py#L452-L500

We need to,

- [ ] define those Python versions as string
- [ ] convert the Python version defined in YAML file to string
- [ ] update tests to work with versions as string
- [ ] update documentation to mention that YAML `python.version` uses string
- [ ] demotivate the usage of float in YAML

There may be more changes required here, but I think they will appear as we are making the other changes. Feel free to add them to this list.

**Comment by stsewd** [comment]
This is already done
