### ISSUE TITLE
Increased build time for frc-docs

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#8363]
Project: frc-docs
Homepage: https://docs.wpilib.org/

My team is developing a Sphinx extension that we plan on making public that follows the web standard for responsive images. Source for this is available here: https://github.com/wpilibsuite/frc-docs/pull/1399

However, the side affect of this extension is bloating build times to 29 minutes (on HTML only builds), due to generating multiple images and sizes. I believe our current build limit is at 30 minutes. 

If we deploy this, alongside HTML and PDF, I could see us easily exceeding past 30 minute build times. However, the benefit of this is very enormous on image heavy pages (page times are reduced anywhere from 30% to 270% depending on the device). Hence, I'd like to open a discussion on moving forward. 

As a temporary workaround, can we get our build limit increased to 45 minutes per-build? We plan to disable responsive images for PR builds, but still want this functionality in the deployed environment.

**Comment by humitos** [comment]
> As a temporary workaround, can we get our build limit increased to 45 minutes per-build?

I increased the build time to 45.

> We plan to disable responsive images for PR builds, but still want this functionality in the deployed environment.

Please do it when you can 🙏🏼 

Let me know if anything!
