### ISSUE TITLE
Logging: log conda version and docker image hash

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/readthedocs.org#8375]
While testing #8328, I found a couple of things that could be logged to improve observability:

- [x] Log conda version, if used
- [ ] Log Docker image hash, apart from `stable`, `latest`, or `testing`

**Comment by humitos** [comment]
Just adding some context here. We are logging the `image=` and the `id=` in https://github.com/readthedocs/readthedocs.org/blob/cea9c3e417f34b240f5d77d78ea068a2a7308a76/readthedocs/doc_builder/environments.py#L1041-L1045

We should probably update that line to add these other values.
