### ISSUE TITLE
iFrame embed pdf file by link doesn't viewed at page anymore

### ISSUE THREAD

**Issue by EDI-N** [readthedocs/readthedocs.org#8377]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/docs-ua/

## Expected Result

For example: I have a page https://wiki.edin.ua/uk/latest/integration_ETTN/cert.html with a syntax:

```
.. raw:: html

    <embed>
      <iframe align="middle" frameborder="1" height="907px" id="ID" scrolling="auto" src="https://wiki.edin.ua/uk/latest/_static/files/Certs/АТС_Інтеграційний_модуль_EDIN.pdf" style="border:1px solid #666CCC" title="PDF" width="99.5%"></iframe>
    </embed>
```

When I go to a source link https://wiki.edin.ua/uk/latest/_static/files/Certs/%D0%90%D0%A2%D0%A1_%D0%86%D0%BD%D1%82%D0%B5%D0%B3%D1%80%D0%B0%D1%86%D1%96%D0%B9%D0%BD%D0%B8%D0%B9_%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D1%8C_EDIN.pdf everything is ok but that file doesn't imports to another page

That method worked and now it doesn't  

## Actual Result

I can import a pdf to a page in previous way or some new

**Comment by humitos** [comment]
Thanks @EDI-N for reporting this issue. We are sending `X-Frame-Origin: DENY` HTTP header in our response. This doesn't allow to use iframe to embed this PDF.

I made a quick fix for now in your domain to send `X-Frame-Origin: SAMEORIGIN` that I think it will solve the problem. It will take effect once the cache is purged/expired (~1hs). Please, let me know if that works for now.

**Comment by EDI-N** [comment]
@humitos thank you for quick response, yes now pdf is displayed! Thanks!
So those fix means that by default readthedocs platform doesn't allow to use iframe anymore?
If a company will change a domain name i needed to write you again? Sorry for questions, I'm just curious

**Comment by humitos** [comment]
> We are sending `X-Frame-Origin: DENY` HTTP header in our response

This was deployed last Tuesday by mistake. We rolled this back and we are not sending it anymore. We are still discussing if it's a good default to have or not --so, this may change in the future.

Your project still has `SAMEORIGIN`, do you want to keep it or do you prefer to completely remove `X-Frame-Origin`?

Sorry for the troubles occasioned here.

**Comment by EDI-N** [comment]
At this point such `X-Frame-Origin: SAMEORIGIN` HTTP header is also suitable for my purposes.
Of course as for me would be better if I will be able to add some google docs or static file from another site (github for example). I don't need clickbait frames and don't understand that security rule with `X-Frame-Origin`. So yes I prefer to completely remove it. Thanks)

**Comment by humitos** [comment]
> So yes I prefer to completely remove it.

Done!

**Comment by EDI-N** [comment]
Thanks)
