### ISSUE TITLE
Add language code TLH to the docs

### ISSUE THREAD

**Issue by Daltz333** [readthedocs/readthedocs.org#8381]
Transifex Supports Language Code TLH (Klingon) for documentation translation. We have just opened this up for our userbase to translate, as we see this as a critical audience! We would like to deploy this to our ReadTheDocs site, but ReadTheDocs does not support custom language codes or TLH.

Source: https://en.wikipedia.org/wiki/TLH
Source: https://www.transifex.com/wpilib/frc-docs/language/tlh/

**Comment by Daltz333** [comment]
In all seriousness, (I would still like TLH) it'd be nice for improvement of more language codes and/or custom language codes in ReadTheDocs. I believe Sphinx allows custom language builders.

**Comment by Daltz333** [comment]
While the official Sphinx documentation only shows supported languages, it's just a mapping system.

Below example is tested for Klingon from the [frc-docs](https://github.com/wpilibsuite/frc-docs)
1. Generate POs
  - ``./make gettext``
  - `` sphinx-intl update -p build/gettext -l tlh``
2. Translate POs
3. Build via ``make -e SPHINXOPTS="-D language='tlh'" html``

This works as intended, except ReadTheDocs does not give the ability to use it. A workaround is to map your language to a different language, but the proper language code does not show up.

Also, Klingon (TLH) is an official ISO language (https://en.wikipedia.org/wiki/ISO_639-2)

**Comment by humitos** [comment]
I'm not sure we will be able to prioritize this work, unfortunately. Closing it for now.
