### ISSUE TITLE
Tex Capacity Exceeded when building PDF

### ISSUE THREAD

**Issue by AAndersn** [readthedocs/readthedocs.org#8382]
When building the latex PDF of my documentation (as called by `latexmk -r latexmkrc -pdf -f -dvi- -ps- -jobname=gridappsd-training -interaction=nonstopmode`, my build fails with the following error:

```
! TeX capacity exceeded, sorry [main memory size=5000000].
\sphinxafterbreak ->\copy \sphinxcontinuationbox 

!  ==> Fatal error occurred, no output PDF file produced!
````
Is there a way to increase the memory size allocated to the latex build?

Background: 

I suspect that Latex is simply running out of allocated space due to the size of doc. The PDF from previous successful builds ran at ~200 pages. The documentation source is a large set of python notebooks that I am building with nbconvert and nbsphinx. 

Previous builds (e.g. https://readthedocs.org/projects/gridappsd-training/builds/14260952/) worked successfully. I recently added  several more pages with many .png images and now the build fails (https://readthedocs.org/projects/gridappsd-training/builds/14364897/).

I tried changing the conf.py file to use xelatex instead, and get a different error (https://readthedocs.org/projects/gridappsd-training/builds/14365366/)

```
Segmentation fault (core dumped)

xdvipdfmx:fatal: File ended prematurely
```

I am not running into any build problems with the html version. If I disable epub and pdf in the advanced settings of the project, the project builds successfully in 95 sec.

**Comment by stsewd** [comment]
Hi, I have moved your project to a queue with more powerful builders, let me know if PDF works now.

**Comment by AAndersn** [comment]
Hi, I have tested on the more powerful builder and am still getting the same error.

I suspect it might be related to issues #7906 and #7344 

I will also check if reverting to an older sphinx / nbsphinx version might reduce the number of `Underfull \hbox (badness 10000) in paragraph at lines xxx-xxx` errors. My builds from about 3 weeks ago did not have those errors.

I'll also check if it might be a problem on the nbsphinx side related to old issue https://github.com/spatialaudio/nbsphinx/issues/276

**Comment by AAndersn** [comment]
Changing the PDF builder to LuaLaTex seems to work. The PDF builds successfully by using `latex_engine = 'lualatex'` in the `conf.py` file.
