### ISSUE TITLE
I suggest the following to do signing certificate pinning:

### ISSUE THREAD

**Issue by Devkey19** [readthedocs/readthedocs.org#8386]
I suggest the following to do signing certificate pinning:
* call the function `VerifyGoogleAuthenticodeSignature` from `DownloadManager::CachePackage`. You could probably call this function from other places, but `CachePackage` stands out since that's where the payload hash is verified.
* Introducing new pins in your fork requires changes to the `base/const_code_signing.h`, `base/signaturevalidator_unittest.cc`, `common/google_signaturevalidator_unittest.cc`, and possibly adding new unit test support files to verify the pins.
* I suggest implementing the feature behind a conditional build flag, so that you could potentially upstream your change from your fork.
* Unfortunately, the pin files and the program identifiers are hardcoded to Google. I suggest not making lexical renames, it is what it is. In your case, `VerifyGoogleAuthenticodeSignature` means verifying the payload with your company's pins, not Google's.
* An issue to keep in mind: Authenticode requires a network check for its certificate revocation list.
* At any rate, running the code under the debugger and testing the code is doing the right thing is critical. Obviously, such feature may result in preventing future updates to updaters or apps. It needs to be rolled out carefully, even if the code is correct. 

This are the high level ideas I can come up right now. Please do ask questions, we are glad to help.

``
_Originally posted by @sorinj in https://github.com/google/omaha/issues/272#issuecomment-852564575_

**Comment by stsewd** [comment]
Hi, looks like you are reporting this on the wrong repo, this repo is for the code that powers readtheddocs.org, we only build and host docs. Looks like you are referring to a project that has their docs hosted on our platform.
