### ISSUE TITLE
Error in documentation: .readthedocs.yaml: Invalid configuration option: build.python.

### ISSUE THREAD

**Issue by paternal** [readthedocs/readthedocs.org#8392]
## Details

* Read the Docs project URL: http://pdfimpose.rtfd.io
* Build URL (if applicable): https://readthedocs.org/projects/pdfimpose/builds/14401231/
* Read the Docs username (if applicable): spalax
* .readthedocs.yaml fine in the commit that triggered that build: https://framagit.org/spalax/pdfimpose/-/blob/b0ba10eef8fb2cc6274252b726fdf47a3d1d5e36/.readthedocs.yaml

## Expected Result

Compilation succeeds.

## Actual Result

The compilation fails with the following error:

~~~
Problem in your project's configuration. Invalid "build.python": .readthedocs.yaml: Invalid configuration option: build.python. Make sure the key name is correct.
~~~

## Some explanations

This key is described [in the documentation](https://docs.readthedocs.io/en/stable/development/design/build-images.html#specifying-extra-user-s-dependencies), with the following example:

~~~yaml
build:
  image: ubuntu20
  python: 3.9
  system_packages:
    - swig
    - imagemagick
  extras:
    - node==14
    - rust==1.46
~~~

I think the correct way to specify the python version is:

~~~yaml
python:
  version: 3.9
~~~

Sorry if the error is on my side, or if this has already been reported.

-- Louis

**Comment by stsewd** [comment]
@paternal hi, those docs aren't supposed to be user facing, as those features described in that page aren't available or may end up implemented differently. This is our official documentation for the config file https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by paternal** [comment]
Ok. Thanks, and sorry for the noise.

-- Louis
