### ISSUE TITLE
API v3: /subrpojects endpoints are returning `subproject_of`

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#8394]
If I remember correctly, we decided that results from /subprojects endpoints wouldn't return the `subproject_of` field.
We even have that in the class

https://github.com/readthedocs/readthedocs.org/blob/15a18966852cc499560dbfff5cf06f9607c1a5e8/readthedocs/api/v3/serializers.py#L684-L696

But the tests do include the subproject_of field

https://github.com/readthedocs/readthedocs.org/blob/15a18966852cc499560dbfff5cf06f9607c1a5e8/readthedocs/api/v3/tests/responses/projects-subprojects-list.json#L43-L52

The problem with this is that if a project has several subprojects, we are going to return the same project n times

```
subproject_a: {subrpoject_of: project}
subproject_b: {subrpoject_of: project}
subproject_c: {subrpoject_of: project}
```

Found this in https://github.com/readthedocs/readthedocs.org/pull/8393/files but not sure if this was on purpose, didn't want to break the api, so creating an issue instead.

Why is this happening if we are ignoring that field? Is because we are inheriting from `ProjectSerializer` which is an object override of `ProjectSerializerBase`, not the class itself.

**Comment by humitos** [comment]
Reading the code you linked it seems that _originally_ we didn't want to show `subproject_of` for this case. So, I'm fine fixing the code and the test to make it work as we originally expected.
