### ISSUE TITLE
please enable DONT_SHALLOW_CLONE

### ISSUE THREAD

**Issue by mathematicalmichael** [readthedocs/readthedocs.org#8403]
## Details
* Read the Docs project URL: https://readthedocs.org/projects/cafelytics/
* Build URL (if applicable): https://readthedocs.org/projects/cafelytics/builds/
* Read the Docs username (if applicable): mathematicalmichael

Would it please be possible to disable shallow clones for the project above, as discussed at #5031? I am using `setuptools_scm` to pick up the project version. It is showing `unknown` and I believe the clone depth is why.

**Comment by humitos** [comment]
@mathematicalmichael Hi! I just disable shallow clones in your project. Let us know if it works as expected. Thanks.

**Comment by mathematicalmichael** [comment]
@humitos thanks!
working great, much appreciated!
