### ISSUE TITLE
Images not updating

### ISSUE THREAD

**Issue by bicarlsen** [readthedocs/readthedocs.org#8433]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/thot-data-docs/
* Build URL (if applicable): https://thot-data-docs.readthedocs.io/
* Read the Docs username (if applicable): bicarlsen

## Expected Result

I updated [an image](https://github.com/bicarlsen/thot-data-docs/blob/main/source/_static/get_started/local/bulk_edit_menu.png) in my GitHub repository, but it is not being updated [in the project](https://thot-data-docs.readthedocs.io/en/latest/get_started/local/containers.html#id9).

## Actual Result

An old version of the image is being used.

**Comment by bicarlsen** [comment]
The images in the PDF and ePub seem to be updating though.

**Comment by bicarlsen** [comment]
It appears this issue resolved itself. Perhaps it was a caching problem.

**Comment by astrojuanlu** [comment]
Thanks @bicarlsen! Feel free to comment here if it happens again or open a new issue.
