### ISSUE TITLE
Docs built from PR are not updating to latest commits

### ISSUE THREAD

**Issue by emlys** [readthedocs/readthedocs.org#8434]
## Details

* Read the Docs project URL: https://invest-userguide.readthedocs.io/en/latest/
* Build URL (if applicable): https://invest-userguide--40.org.readthedocs.build/en/40/
* Read the Docs username (if applicable): emlys

## Expected Result
I expect to be able to view the docs built from the latest commit in my PR.

## Actual Result
The built docs page points to an older commit. I can see that the docs are getting built for each commit in the [builds page](https://readthedocs.org/projects/invest-userguide/builds/), and I can see the [build for the latest commit](https://readthedocs.org/projects/invest-userguide/builds/14521517/). But when I click on "View docs" from that build page, the [built docs](https://invest-userguide--40.org.readthedocs.build/en/40/) do not have the latest updates. When I click on "was created" in the "Warning: this page was created from a pull request" box, it links me back to the same old commit. It's like the URL https://invest-userguide--40.org.readthedocs.build/en/40/ doesn't update to point to the latest build.

This happened yesterday for several hours, and kept showing a commit (#0e4626d) from that morning. Today it is happening with a newer, outdated commit (#8006ca5).

**Comment by astrojuanlu** [comment]
Hi @emlys, after a quick overview I'm not exactly sure what do you mean by "latest built docs aren't showing up". For example, I see that in https://github.com/natcap/invest.users-guide/pull/40 you're changing the "data needs" section, and I do observe a difference between:

https://invest-userguide.readthedocs.io/en/latest/carbon_edge.html#data-needs

> This section outlines the specific data used by the model. ...

and https://invest-userguide--40.org.readthedocs.build/en/40/carbon_edge.html#data-needs

> Note that all spatial inputs must be in the same projected coordinate system and in linear meter units.

So, it seems to me that the pull request builder is picking the changes from https://github.com/natcap/invest.users-guide/pull/40. Am I missing anything?

**Comment by emlys** [comment]
Thanks for looking into this. That particular example is working as expected now. It seems like there's a significant lag time for it to update. When I created this issue, the docs at https://invest-userguide--40.org.readthedocs.build/en/40/ did indeed have some of the changes from the PR, but not the _latest_ changes. It was about 3 commits behind.

**Comment by stsewd** [comment]
@emlys this might be your browser cache, next time you can try a hard refresh (usually `Ctrl+F5`) or opening the page in an incognito mode, if you still see the old version, that may be a problem with our cache purging.
