### ISSUE TITLE
`latest` on RTD pointing to `latest` tag, not `master`

### ISSUE THREAD

**Issue by Yoshanuikabundi** [readthedocs/readthedocs.org#8460]
Hi! We have a tag called [`latest`](https://github.com/openforcefield/openff-toolkit/releases/tag/latest) to [support](https://github.com/openforcefield/openff-toolkit/issues/286#issuecomment-825655553) caching on [Binder](https://mybinder.org/). Our default branch is set to `master` in RTD, but the "latest" version points to the `latest` tag, not the `master` branch. This means our in-development documentation is not being served at all.

## Details

* Read the Docs project URL: https://open-forcefield-toolkit.readthedocs.io/en/0.10.0/
* Build URL (if applicable): https://open-forcefield-toolkit.readthedocs.io/en/latest/
* GitHub URL: https://github.com/openforcefield/openff-toolkit
* Read the Docs username (if applicable): Yoshanuikabundi

## Expected Result

The "latest" version on RTD should point to the latest commit to the `master` branch, as configured.

## Actual Result

The "latest" version on RTD points to the `latest` tag in our Git tree

Thanks!

**Comment by astrojuanlu** [comment]
Hi @Yoshanuikabundi ! I confirm that the configuration looks correct. We'll have a look at this on Monday, thanks for your patience.

**Comment by humitos** [comment]
IIRC this was implemented in this way to allow users to "override the behavior of what Read the Docs understand by `latest` and `stable`" due that many users wanted them to work differently.

> We also create a stable version, if your project has any tagged releases. stable will be automatically kept up to date to point at your highest version. If you want a custom stable version, create either a tag or branch in your project with that name.

(from https://docs.readthedocs.io/en/stable/versions.html)

However, it seems that we mention this "customization" only for the `stable` version, but I think we are doing it for the `latest` version as well. Maybe @stsewd can give more context here (I wasn't able to find the PR)

**Comment by stsewd** [comment]
Hi. So, we have these two special names on rtd, `stable` and `latest`, the version name used when serving your docs is chosen from the branch/tag, so in this case `/latest` will serve the docs from the `latest` branch.

I think you can solve this by marking `latest` as inactive https://readthedocs.org/dashboard/open-forcefield-toolkit/version/latest/edit/.

**Comment by stsewd** [comment]
A work around would is changing the default branch to other than master, and then changing it again to master again (isn't guaranteed that this would stick). A solution is to rename your tag to something else than latest, and a solution from our side would be to don't depend on the version name for things like latest/stable or allow creating aliases or changing the version slug https://github.com/readthedocs/readthedocs.org/issues/5318.

**Comment by Yoshanuikabundi** [comment]
Alright thanks! We'll have a chat internally about what we wanna do. Making `latest` inactive isn't quite what we want, as we'd like the docs for the latest development version to be available.

**Comment by humitos** [comment]
It seems the issue was clarified and we can close it, right? Let me know otherwise 👍🏼

**Comment by Yoshanuikabundi** [comment]
Yep! Thanks for your help.
