### ISSUE TITLE
Provide a setting for configuring theme for ads

### ISSUE THREAD

**Issue by bhch** [readthedocs/readthedocs.org#8462]
I've a heavily modified sphinx_rtd_theme. The sidebar is light coloured and the ads displayed are dark coloured. It looks too contrasting.

Please provide a setting for configuring the theme used for ads (light or dark).

Screenshot:

![dark-ad](https://user-images.githubusercontent.com/6051897/132127361-3f97f59e-e0e6-4def-8ed8-0f825dfed088.png)

**Comment by humitos** [comment]
I'm pinging @davidfischer and @agjohnson that were working on this already. However, I'm not sure how much customizable it is nor how to do it 😅
