### ISSUE TITLE
'INIT' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by vishallanke** [readthedocs/readthedocs.org#8464]
## Details

* Read the Docs project URL: **https://docs.readthedocs.io/en/stable/development/install.html**
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Actual Result
I have successfully followed all the steps. However, I am getting below error in last step
```
$ inv docker.up  --init
'INIT' is not recognized as an internal or external command,
operable program or batch file.
```

I am working on Windows 10.
Docker and other requirements are installed.

Is there any other way if inv docker.up  --init is not working ?

## Expected Result
http://localhost:9000/ should be accessible

**Comment by astrojuanlu** [comment]
Hi @vishallanke, what shell are you using on Windows? Maybe you could try with WSL2 instead. We do not test these instructions on Windows.

**Comment by vishallanke** [comment]
@astrojuanlu 
Thanks a lot. Let me check. I am using bash(gitbash), tried on powersheel
With WSL, it wont work. Let me check with WSL2.
I am going to try with AWS Linux.

Quick question - nothing related to defect
We have AWS Subscription and we would like to configure local instance of readthedocs.
So, we would expect that after installation we will get http://// some URL and able to use readthedoc to host/create docs.
So, am I on right track https://docs.readthedocs.io/en/stable/development/install.html
If not, can you just navigate me to the correct documentation where I can look

**Comment by humitos** [comment]
> Let me check with WSL2.

Were you able to make it work? Any feedback that you can share about the guide?

> We have AWS Subscription and we would like to configure local instance of readthedocs.
> So, we would expect that after installation we will get http://// some URL and able to use readthedoc to host/create docs. So, am I on right track [docs.readthedocs.io/en/stable/development/install.html](https://docs.readthedocs.io/en/stable/development/install.html)

The guide that you are following is for development purposes and it's strictly not recommended for production environments. Unfortunately, we don't have a guide for production.

**Comment by vishallanke** [comment]
These steps are not working - https://docs.readthedocs.io/en/stable/development/install.html on Windows
We also tried https://haha.readthedocs.io/en/latest/install.html on AWS Ubuntu. But, then there are lots of errors. Looks like that steps are outdated. We tried to resolve the technical issues but then its taking too much time

**Comment by humitos** [comment]
> 1 - These steps are not working - [docs.readthedocs.io/en/stable/development/install.html](https://docs.readthedocs.io/en/stable/development/install.html) on Windows

What were the problems that you found here?

> 2 - We also tried [haha.readthedocs.io/en/latest/install.html](https://haha.readthedocs.io/en/latest/install.html) on AWS Ubuntu

This is not an official guide. I wouldn't recommend you to follow it.

**Comment by vishallanke** [comment]
Error - inv docker.up  --init
'INIT' is not recognized as an internal or external command,
operable program or batch file.

**Comment by humitos** [comment]
Right, that's the same output from the description of the issue. Then you said that you were about to test with WSL and that's the feedback that I'm interested in.

Our instructions do not work on Windows _without_ WSL, and I don't think we will make them work without WSL. However, we recently had a successful case of a setup following those instructions on WSL.

**Comment by vishallanke** [comment]
Can I follow these steps on Linux ?
or there are different set of steps ?

**Comment by astrojuanlu** [comment]
@vishallanke the steps are meant for Linux, I just opened #8494 to clarify that.

The `'INIT' is not recognized as an internal or external command,` message seems to come from `cmd.exe`, which means that you are running the steps in a Windows terminal, not a Linux-like terminal. To confirm, you can attach a screenshot that shows the whole window.

When you have WSL2 up and running, you should run these instructions from _inside_ WSL2, which gives you a Bash terminal on an Ubuntu-like system. You can read more [on the Ubuntu docs](https://ubuntu.com/wsl).
