### ISSUE TITLE
Document how canonical domains work

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#8469]
We have implemented the redirects on canonical domains (I didn't find the PR). In this comment, we mentioned how they work https://github.com/readthedocs/readthedocs.org/issues/8250#issuecomment-860754126. However, our documentation doesn't explain how canonical domains work and nor their redirects

* https://docs.readthedocs.io/en/stable/automatic-redirects.html
* https://docs.readthedocs.io/en/stable/guides/canonical.html

We should update our documentation to reflect this because it's generating confusion to our users.

**Comment by humitos** [comment]
When working on this issue, we need to mention that it's required to re-build old versions when the Canonical URL is updated (from https://github.com/readthedocs/readthedocs.org/issues/8533#issuecomment-1101854923)

**Comment by stsewd** [comment]
That is already mentioned in the page https://docs.readthedocs.io/en/stable/canonical-urls.html.

**Comment by benjaoming** [comment]
From the issue description:

> However, our documentation doesn't explain how canonical domains work and nor their redirects

Now since https://github.com/readthedocs/readthedocs.org/pull/9676, the docs explain:

> Your documentation can have multiple secondary domains but only one canonical domain name. Additional domains or subdomains will redirect to the canonical domain.

I believe this should be sufficient. But please LMK if you had something else in mind :+1:
