### ISSUE TITLE
Abandoned project and name transfer request: skimpy

### ISSUE THREAD

**Issue by aeturrell** [readthedocs/readthedocs.org#8479]
Hi,

I'd like to start the process for an abandoned project, [ankiano/skimpy](https://github.com/ankiano/skimpy), in order to use the name skimpy for a readthedocs site for a different project, [aeturrell/skimpy](https://github.com/aeturrell/skimpy). The following information may be useful:

- There is no content on the readthedocs page for the existing project (see [here](https://skimpy.readthedocs.io/)). 
- I have raised an [issue](https://github.com/ankiano/skimpy/issues/1) on the older project to ask for a name switch. As yet, no reply.
- [aeturrell/skimpy](https://github.com/aeturrell/skimpy) is new but is [on PyPI](https://pypi.org/project/skimpy/), has been [blogged](https://towardsdatascience.com/summarize-pandas-data-frames-b9770567f940) about, and has attracted stars.
- [aeturrell/skimpy](https://github.com/aeturrell/skimpy) has been directing traffic to the read the docs entry for [ankiano/skimpy](https://github.com/ankiano/skimpy) (oops!)
- [aeturrell/skimpy](https://github.com/aeturrell/skimpy)'s name is meant to make it clear that it's analogous to R's *skimr* package, plus be a play on words: so an alternative name would be less fitting.

Thanks for maintaining this amazing service!

**Comment by humitos** [comment]
Thanks for opening this issue. I saw that the issue in the other repository was created 2 days ago, so we may need to wait a little more before starting the process for the abandoned project.

Also, note that the project was imported about 1 year ago and the last build on RTD is 5 months ago.

**Comment by humitos** [comment]
@aeturrell is this issue still valid or should we close it?

**Comment by aeturrell** [comment]
I decided to try a different approach for the documentation via GitHub pages as **skimpy** is a very small package. The documentation uses Quarto and can be found [here](https://aeturrell.github.io/skimpy/). 

So completely okay to close this! Thank you.
