### ISSUE TITLE
Abandoned project and name transfer request: dexter

### ISSUE THREAD

**Issue by igormagalhaesr** [readthedocs/readthedocs.org#8480]
There's an abandoned project: https://readthedocs.org/projects/dexter/ that I'd like to use the name of to document my project https://github.com/igormagalhaesr/dexter on readthedocs.

**Comment by humitos** [comment]
Hi @igormagalhaesr! That project was SPAM, so I renamed it as `-abandoned` following our policy. Feel free to import your project now under that namespace. Let me know if anything.
