### ISSUE TITLE
the building termina does not render ANSII coloring

### ISSUE THREAD

**Issue by 12rambau** [readthedocs/readthedocs.org#8484]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/sepal-ui/
* Build URL (if applicable): https://readthedocs.org/projects/sepal-ui/builds/14700568/
* Read the Docs username (if applicable): borntobealive

## Expected Result

I build my new documentation using a new extention called jupyter-sphinx. The extention build jupyter binder on the fly to execute cells and display them within the documentation. My installation was working just fine locally but when i pushed it to RDT an error occured. 

The issue being that python kernel error are displayed using ANSII color code. These color codes are not rendered by the RDT terminal, making it impossible to read:

```
[0;31m---------------------------------------------------------------------------[0m
[0;31mFileNotFoundError[0m                         Traceback (most recent call last)
[0;32m/tmp/ipykernel_244/3861035409.py[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;32mfrom[0m [0msepal_ui[0m [0;32mimport[0m [0mmapping[0m [0;32mas[0m [0msm[0m[0;34m[0m[0;34m[0m[0m
[1;32m      2[0m [0;34m[0m[0m
[0;32m----> 3[0;31m [0msm[0m[0;34m.[0m[0mSepalMap[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
```

which should look like: 
```
--------------------------------------------------------------------------- 
FileNotFoundError Traceback (most recent call last) /tmp/ipykernel_244/3861035409.py in <module>  
          1 from sepal_ui import mapping as sm  
          2  
----> 3 sm.SepalMap()
```

**Comment by stsewd** [comment]
Hi, we set the `NO_COLOR` env https://no-color.org, there is an open issue on the plugin repo about this https://github.com/jupyter/jupyter-sphinx/issues/115.

I think @agjohnson did some progress to support ansii colors in the build page on the new templates.

**Comment by agjohnson** [comment]
Yup! New templates will do fancy ANSI color code replacements on build output

**Comment by astrojuanlu** [comment]
Shouldn't this be kept open until the new templates are available for users?

**Comment by stsewd** [comment]
We usually track works that needs to be done, when the new templates are released, I don't think that would pass unnoticed. But I @agjohnson should be the one to decide if we should keep these open.

**Comment by agjohnson** [comment]
Issues like these are in a strange place until we have our public beta ready at very least. Agreed that it feels like we need a way to track these though, and follow up when the public beta goes up.

I'd avoid putting these on the development board for the new templates, as they'll just get shuffled out of view I'm sure (the work is done).
