### ISSUE TITLE
PEP 517 build failed

### ISSUE THREAD

**Issue by snowformatics** [readthedocs/readthedocs.org#8485]
## Details

* Read the Docs project URL:
https://readthedocs.org/projects/gwas-web-production/

* Build URL (if applicable):
https://readthedocs.org/projects/gwas-web-production/builds/14707038/

* Read the Docs username (if applicable):
snowformatics

## Expected Result
Succesfull build

*A description of what you wanted to happen*
Failed to build fastlmm
ERROR: Could not build wheels for fastlmm which use PEP 517 and cannot be installed directly

## Actual Result
Build failed
*A description of what actually happened*
I tried to add a fake setup.py but it didn't work, probably it's content is wrong

Thanks for any help

**Comment by 12rambau** [comment]
I don't have access to your build as I'm not a maintainer of the project but I was passing by ;-) 

In your conf.py file you are importing a local file from your computer: 

https://github.com/snowformatics/gwas_web_production/blob/7fa01a4c0d94f14a85cb8ab5d053af96bdb95be6/docs/source/conf.py#L19

I'm not sure it's the only issue but I'm sure that it will not work when your build will try to access `C:/Users/lueck/PycharmProjects/gwas_web_production/`.

Instead use relative path from your file

**Comment by stsewd** [comment]
Looks like the fastlmm dep  is failing to compile

```
  Building wheel for fastlmm (PEP 517): started
  Building wheel for fastlmm (PEP 517): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /home/docs/checkouts/readthedocs.org/user_builds/gwas-web-production/envs/latest/bin/python /home/docs/checkouts/readthedocs.org/user_builds/gwas-web-production/envs/latest/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpeqvv5_7r
       cwd: /tmp/pip-install-ysxtycjw/fastlmm_30a1d454aa8a4429b2cdf5d2503a0f14
  Complete output (203 lines):


g++ -pthread -shared -L/home/docs/.pyenv/versions/3.7.9/lib -L/home/docs/.pyenv/versions/3.7.9/lib build/temp.linux-x86_64-3.7/fastlmm/util/matrix/cample.o -Lexternal/intel/linux/mkl/lib/intel64 -Lexternal/intel/linux/compiler/lib/intel64 -Wl,--enable-new-dtags,-Rexternal/intel/linux/mkl/lib/intel64 -Wl,--enable-new-dtags,-Rexternal/intel/linux/compiler/lib/intel64 -lmkl_rt -lmkl_intel_ilp64 -lmkl_core -lmkl_intel_thread -liomp5 -lmkl_sequential -o build/lib.linux-x86_64-3.7/fastlmm/util/matrix/cample.cpython-37m-x86_64-linux-gnu.so
  /usr/bin/ld: cannot find -lmkl_rt
  /usr/bin/ld: cannot find -lmkl_sequential
  collect2: error: ld returned 1 exit status
  error: command 'g++' failed with exit status 1
```

For this kind of libs that need compilation, is better to use conda https://docs.readthedocs.io/en/stable/guides/conda.html

**Comment by snowformatics** [comment]
> I don't have access to your build as I'm not a maintainer of the project but I was passing by ;-)
> 
> In your conf.py file you are importing a local file from your computer:
> 
> https://github.com/snowformatics/gwas_web_production/blob/7fa01a4c0d94f14a85cb8ab5d053af96bdb95be6/docs/source/conf.py#L19
> 
> I'm not sure it's the only issue but I'm sure that it will not work when your build will try to access `C:/Users/lueck/PycharmProjects/gwas_web_production/`.
> 
> Instead use relative path from your file

Thanks for this suggestion!

**Comment by snowformatics** [comment]
> Looks like the fastlmm dep is failing to compile
> 
> ```
>   Building wheel for fastlmm (PEP 517): started
>   Building wheel for fastlmm (PEP 517): finished with status 'error'
>   ERROR: Command errored out with exit status 1:
>    command: /home/docs/checkouts/readthedocs.org/user_builds/gwas-web-production/envs/latest/bin/python /home/docs/checkouts/readthedocs.org/user_builds/gwas-web-production/envs/latest/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpeqvv5_7r
>        cwd: /tmp/pip-install-ysxtycjw/fastlmm_30a1d454aa8a4429b2cdf5d2503a0f14
>   Complete output (203 lines):
> 
> 
> g++ -pthread -shared -L/home/docs/.pyenv/versions/3.7.9/lib -L/home/docs/.pyenv/versions/3.7.9/lib build/temp.linux-x86_64-3.7/fastlmm/util/matrix/cample.o -Lexternal/intel/linux/mkl/lib/intel64 -Lexternal/intel/linux/compiler/lib/intel64 -Wl,--enable-new-dtags,-Rexternal/intel/linux/mkl/lib/intel64 -Wl,--enable-new-dtags,-Rexternal/intel/linux/compiler/lib/intel64 -lmkl_rt -lmkl_intel_ilp64 -lmkl_core -lmkl_intel_thread -liomp5 -lmkl_sequential -o build/lib.linux-x86_64-3.7/fastlmm/util/matrix/cample.cpython-37m-x86_64-linux-gnu.so
>   /usr/bin/ld: cannot find -lmkl_rt
>   /usr/bin/ld: cannot find -lmkl_sequential
>   collect2: error: ld returned 1 exit status
>   error: command 'g++' failed with exit status 1
> ```
> 
> For this kind of libs that need compilation, is better to use conda https://docs.readthedocs.io/en/stable/guides/conda.html

Ok I see, I will try and give feedback.

**Comment by snowformatics** [comment]
Via conda it worked, thanks a lot!

**Comment by astrojuanlu** [comment]
Thanks for the confirmation @snowformatics ! Closing
