### ISSUE TITLE
Codecov is broken

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/readthedocs.org#8505]
Last update to Codecov was 14 months ago https://app.codecov.io/gh/readthedocs/readthedocs.org

Probably related to this error, that goes unnoticed:

```
==> Detecting CI provider
  -> Got branch from git/hg
  -> Got sha from git/hg
==> Preparing upload
==> Processing gcov (disable by -X gcov)
==> Collecting reports
    Generating coverage xml reports for Python
    + /home/circleci/project/readthedocs/coverage.xml bytes=664156
==> Uploading
    .url https://codecov.io
    .query commit=f939aee83169ed506455bf7bd690bb4ffb02fbc3&branch=additional-history-fields&package=py2.1.12
    Gzipping contents..
    Compressed contents to 49890 bytes
    Pinging Codecov...
Error: Could not determine repo and owner
Tip: See all example repositories: https://github.com/codecov?query=example
```

**Comment by stsewd** [comment]
I suggested for someone with admin permissions to re-install the app https://github.com/readthedocs/readthedocs.org/settings/installations. Because I don't see any other reason why it should fail...

**Comment by astrojuanlu** [comment]
To note: https://hynek.me/til/ditch-codecov-python/

**Comment by stsewd** [comment]
I think it's fine keeping codecov, we don't use it as part of our tests, and I do find their report interface nice and easy to look up. The method proposed in the post requires you to download those files to see then in your browser

**Comment by humitos** [comment]
> I suggested for someone with admin permissions to re-install the app

ping @agjohnson @ericholscher

**Comment by ericholscher** [comment]
I re-installed the GH app.
