### ISSUE TITLE
One html page isnt showing code documentation properly

### ISSUE THREAD

**Issue by abdullah-al-masud** [readthedocs/readthedocs.org#8508]
## Details
My open source project link is here- https://github.com/abdullah-al-masud/msdlib

I have used sphinx v4.2.0 to build the index.rst and conf.py and designed other rst files using proper commands in my local machine. All html pages are being shown properly except one (this- https://msdlib.readthedocs.io/en/latest/mlutils.html). It shows the initial write ups from rst file but doesnt show documentation from the code. 

The corresponding html file build by sphinx in local machine is here- https://github.com/abdullah-al-masud/msdlib/blob/master/docs/_build/html/mlutils.html

The corresponding rst file is this- https://github.com/abdullah-al-masud/msdlib/blob/master/docs/mlutils.rst

The corresponding code script is here- https://github.com/abdullah-al-masud/msdlib/blob/master/msdlib/mlutils.py

* Read the Docs project URL: https://msdlib.readthedocs.io/en/latest/
* 
* Build URL (if applicable):
* Read the Docs username (if applicable): abdullah_al_masud

## Expected Result
https://github.com/abdullah-al-masud/msdlib/blob/master/docs/_build/html/mlutils.html
*A description of what you wanted to happen*
Show the whole html documentation
## Actual Result
https://msdlib.readthedocs.io/en/latest/mlutils.html
*A description of what actually happened*
showing only first paragraph, doesnt showing documentation from the code.

**Comment by astrojuanlu** [comment]
Hi @abdullah-al-masud ! I see this warning on your build https://readthedocs.org/projects/msdlib/builds/14754572/: 

```
WARNING: autodoc: failed to import module 'mlutils' from module 'msdlib'; the following exception was raised:
No module named 'torch'
```

Therefore, you're missing some dependencies. You can specify them using the `.readthedocs.yaml` file: https://docs.readthedocs.io/en/stable/config-file/v2.html

**Comment by abdullah-al-masud** [comment]
@astrojuanlu 

> Hi @abdullah-al-masud ! I see this warning on your build https://readthedocs.org/projects/msdlib/builds/14754572/:
> 
> WARNING: autodoc: failed to import module 'mlutils' from module 'msdlib'; the following exception was raised:
> No module named 'torch'
> Therefore, you're missing some dependencies. You can specify them using the .readthedocs.yaml file: https://docs.readthedocs.io/en/stable/config-file/v2.html

Thank you very much for your response. I have tried adding the .readthedocs.yaml file and inside I added necessary installation libraries. Now there is no importation failure. But still I dont get that particular html page to work. Still the same.

**Comment by abdullah-al-masud** [comment]
This is the configuration file that I am using

# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# Optionally build your docs in additional formats such as PDF
formats:
   - pdf

# Optionally set the version of Python and requirements required to build your docs
python:
   version: "3.8"
   install:
   - requirements: docs/requirements.txt
   - requirements: requirements.txt
   - requirements: requirements-dev.txt

**Comment by astrojuanlu** [comment]
You're right, there are no autodoc warnings now but still the `automodule` is not shown. Other `automodule` directives in the documentation work.

Can you confirm if it builds locally? If it doesn't, then the issue is with Sphinx and not with Read the Docs.

**Comment by abdullah-al-masud** [comment]
I was able to build it locally which works perfectly fine. I get the complete documentation of mlutils. After local build, I get this html file for mlutils.
https://github.com/abdullah-al-masud/msdlib/blob/master/docs/_build/html/mlutils.html

**Comment by astrojuanlu** [comment]
It was a caching issue, now the page appears 👍🏽 I think this can be closed, please leave a comment otherwise!
