### ISSUE TITLE
Data not displaying on public build but is displaying on local build

### ISSUE THREAD

**Issue by michaelavs** [readthedocs/readthedocs.org#8519]
## Details

* Read the Docs project URL: geocat-examples.readthedocs.io
* Build URL (if applicable): https://geocat-examples.readthedocs.io/en/overlay11_issues/
* Read the Docs username (if applicable): michaelavs

## Expected Result

When running ```make html``` locally via terminal, the build for [Overlay_11a](https://geocat-examples.readthedocs.io/en/overlay11_issues/gallery/Overlays/NCL_overlay_11a.html#sphx-glr-gallery-overlays-ncl-overlay-11a-py) displays data via contourf on the map. As seen below:

![image](https://user-images.githubusercontent.com/43652875/134239488-fc39c6d7-8ad1-403f-86de-0f6579eca269.png)

Which is the expected behavior

## Actual Result
When this repo is built publicly/via RTD, the data disappears:

![image](https://user-images.githubusercontent.com/43652875/134239708-6a7a60d0-c5e2-455a-9d31-58c7d4c8f854.png)

The environments are the same between the local and public versions of the builds. I have also tried editing the code to change the order that the data is plotted on the map and that did not resolve this issue. I've seen somewhat similar issues from a few years back, but their resolutions didn't lead to a solution here.

**Comment by astrojuanlu** [comment]
Hi @michaelavs ! Maybe it's a caching issue? This is what I see:

![IMG_20210921_221924](https://user-images.githubusercontent.com/316517/134241682-7fd2a0e9-56a7-4ae2-93eb-fe9749c6c161.jpg)

**Comment by astrojuanlu** [comment]
I confirm I see now an empty plot.

Notice by the way that you can debug this using our Pull Request builder: https://docs.readthedocs.io/en/stable/pull-requests.html that will make it easier to see the diff of the code and the rendered result without having to commit to the default branch.

**Comment by michaelavs** [comment]
We do have that enabled. The only thing changed between the last time the plot fully showed and this version is disabling a separate plot from the repository (changed .py into .inact to prevent it building). The branch, and version, "overlay11_issues" was created to address the plot not showing correctly when built, but also addressed a failure that came up during that time (failure was caused by an incorrect axes extent call). At this time, the builds are all successful for the branch and version "overlay11_issues", even though this one plot will only show the data during local builds via ```make html``` but not when RTD builds it. It's just a bit puzzling as nothing was touched with respect to the file of interest, conf.py, or the actual environment used in the GitHub repo which would all be the first places I would look for any changes.

**Comment by astrojuanlu** [comment]
@michaelavs I see that you've been doing some experiments on the branch lately. Can you point to a specific commit that should show the correct plot locally, but showed an empty plot on Read the Docs?

Locally, https://github.com/NCAR/GeoCAT-examples/commit/e410731d543d05e20b50586bce8fd2603f4a7664 shows the plot covered with data (also the sea), like the screenshot I shared yesterday, and https://github.com/NCAR/GeoCAT-examples/commit/39f446a1f023092caa205b144c74a4d754fbce29 shows the empty plot. Therefore, I can't reproduce the "correct" plot locally (happy to follow this conversation on https://github.com/NCAR/GeoCAT-examples/pull/415).

**Comment by michaelavs** [comment]
@astrojuanlu The correct plot would be built via the most recent build triggered ([b62df12](https://github.com/NCAR/GeoCAT-examples/pull/415/commits/b62df12c6ae2105a31c3a8f78a573bec4f36c3c2)). We are going to be closing out the associated PR today just to merge a fix that will allow the overall build to succeed for the repo, but I will be opening another PR on Monday to address the behavior of Overlay_11a and Overlay_11b. In the mean time, for a more visual guide of what I see with this build, here are the output projections when running the code with my IDE, locally building via ```make html```, and then the RTD build for Overlay11a:!

**via IDE (Pycharm)**
![image](https://user-images.githubusercontent.com/43652875/134719246-ec6cac9a-0879-4444-97e2-cc3c0640afbd.png)

**via make html**
![image](https://user-images.githubusercontent.com/43652875/134719442-5d405307-68cf-401c-9731-9a85d0f39034.png)

**RTD build**
![image](https://user-images.githubusercontent.com/43652875/134731462-d213229e-b207-4228-8530-063f7b7b2d52.png)
_Note: overlay11b is also having similar issues to 11a (above) but I am mostly concerned with 11a for the time being_

With the PR being merged today, you should also be able to see this issue with the main branch build ('latest' version in RTD).

**Comment by astrojuanlu** [comment]
I tested this:

```
24551  [2021-09-28 15:15:43] git reset --hard b62df12
24552  [2021-09-28 15:15:45] mamba env create --name overlay11_issues -f conda_environment.yml 
24553  [2021-09-28 15:17:02] conda activate overlay11_issues
24554  [2021-09-28 15:17:11] python Plots/Overlays/NCL_overlay_11a.py
```

and I still got the empty plot. However, with this change:

```diff
diff --git a/Plots/Overlays/NCL_overlay_11a.py b/Plots/Overlays/NCL_overlay_11a.py
index 1a9615f..d2a07d4 100644
--- a/Plots/Overlays/NCL_overlay_11a.py
+++ b/Plots/Overlays/NCL_overlay_11a.py
@@ -147,7 +147,7 @@ newcmp = gvutil.truncate_colormap(gvcmaps.BkBlAqGrYeOrReViWh200,
 
 # Draw the temperature contour plot with the subselected colormap
 # (Place the zorder of the contour plot at the lowest level)
-cf = ax.contourf(lon, lat, T, levels=clevs, cmap=newcmp, zorder=1)
+cf = ax.contourf(lon, lat, T, levels=clevs, cmap=newcmp, zorder=3)
 
 # Draw horizontal color bar
 cax = plt.axes((0.14, 0.08, 0.74, 0.02))
```

I got the same plot I got here: https://github.com/readthedocs/readthedocs.org/issues/8519#issuecomment-924353362

 😕 

I suspect there is some caching behavior from sphinx-gallery that makes it more difficult to evaluate the changes locally, as well as Read the Docs own caching policies. That's why I ran the script directly with `python Plots/Overlays/NCL_overlay_11a.py`.

In any case, I still can't say that this is a Read the Docs issue.

**Comment by michaelavs** [comment]
Just to make sure I'm on the same page here, based on your tests, do you think this is more of a Sphinx issue than RTD? If so, I will say that one of the things we are looking into is if the newest version of Sphinx may be causing the issues we're having. This idea is because the timeframe that our builds started having issues was September 1st/2nd and Sphinx released it's newest version on September 2nd. 

I'm currently trying to clear out Sphinx cache's locally and see if that may help resolve the discrepancies, but if you have any other pointers in the mean time, please let me know!

**Comment by astrojuanlu** [comment]
Based on my tests, I think Sphinx or Read the Docs have no influence in the result, since `python Plots/Overlays/NCL_overlay_11a.py` runs the script directly without including it in the documentation. Perhaps a new cartopy or matplotlib version instead? Could you try running that script and see what the output is, and then doing so inside a newly created conda environment?
