### ISSUE TITLE
CSS file doesn't work for side panel

### ISSUE THREAD

**Issue by CrackAndDie** [readthedocs/readthedocs.org#8527]
## Details

* Read the Docs project URL: https://robocadsim.readthedocs.io/en/latest/
* Github URL: https://github.com/CADindustries/robocadSim-docs
* Read the Docs username: crackanddie

## Expected Result

I have an ```.css``` file in my ```_static``` folder. So I have this in my ```conf.py``` file:
```python
def setup(app):
    app.add_css_file('css/cad_css.css')
```

Three month ago I had a normal view of my side panel in the docs. But now it is very ugly and ```.css``` file doesn't work as I understood.  

You can see a normal side page on ```1.3.4-branch``` version of docs.

![image](https://user-images.githubusercontent.com/52558686/134887841-dc7b51ec-cff6-4ef5-89dc-1fa788d351e8.png)

## Actual Result

Here is the actual result:

![image](https://user-images.githubusercontent.com/52558686/134887790-ffe0ea54-2cbc-45aa-815b-6aad7227afd4.png)  

What should I do? Where could be the problem?

**Comment by CrackAndDie** [comment]
Solved: https://stackoverflow.com/questions/69347139/why-doesnt-css-file-work-in-readthedocs/69362066#69362066

**Comment by astrojuanlu** [comment]
Thanks @CrackAndDie ! For future reference, the problem was docutils 0.16 and an outdated stylesheet.
