### ISSUE TITLE
Canonical URLs not automatically applied to old docs versions

### ISSUE THREAD

**Issue by edshee** [readthedocs/readthedocs.org#8533]
## Details

* Read the Docs project URL: https://docs.seldon.io/projects/seldon-core/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable): Seldonio

RTD docs state that canonical URLs are automatically handled like so:
```
We point all versions of your docs at the “latest” version as canonical.
We point at the user specified canonical URL, generally a custom domain for your docs.
```
The second is working as expected. https://seldon-core.readthedocs.io correctly redirects and adds `<link rel="canonical">` tags to point to https://docs.seldon.io/projects/seldon-core/en/latest/.

The first, however, is not being applied at all. Older versions have no canonical links provided to the latest version which is leading to indexing issues on search engines.

## Expected Result

On the page https://docs.seldon.io/projects/seldon-core/en/v1.8.0/ a `<link rel="canonical" href="https://docs.seldon.io/projects/seldon-core/en/latest/">` should be applied automatically.

## Actual Result

No `<link rel="canonical">` tags have been added to the page

**Comment by stsewd** [comment]
Hi, those attributes are statically generated, so you'll need to re-build those versions in order to see the changed. We could make a clarification in the docs.

**Comment by edshee** [comment]
Hi @stsewd I've just rebuilt this version:
https://docs.seldon.io/projects/seldon-core/en/v1.2.3_a/ (Build #14844358)

I still don't see any `<link rel="canonical">` tags in the page.

**Comment by stsewd** [comment]
That looks like something to do with the project being a subproject, in this case we try to take the cannonical url from the subproject itself rather than the canocical url from the parent project. I think it makes sense to search for the canonical url of the parent project in this case.

**Comment by edshee** [comment]
I'm not sure I follow you?

The project is "single version" so is served from the root domain: https://docs.seldon.io/

The sub-project is the one with versions. I'm trying to avoid those being indexed on Google but because they haven't had the canonical urls added automatically it's a struggle. 

Worth noting that I added the following robots.txt to the main project:
```
User-agent: *
Allow: /projects/seldon-core/en/latest/
Allow: /projects/alibi/en/latest/
Allow: /projects/alibi-detect/en/latest/
Allow: /$
Disallow: / 

Sitemap: https://docs.seldon.io/sitemap.xml
```
In theory this should have helped but it seems google still has a strong preference for some older versions.

**Comment by stsewd** [comment]
> The project is "single version" so is served from the root domain: https://docs.seldon.io/

Yeah, but the subprojects are trying to use their own canonical domain, instead of the one given to the parent project.

**Comment by edshee** [comment]
Yeah I'm ok with that. They are standalone projects. I just need the versions at e.g. https://docs.seldon.io/projects/seldon-core/en/v1.8.0/ to point to https://docs.seldon.io/projects/seldon-core/ so that search engines will index that or /en/latest.

**Comment by stsewd** [comment]
> I've just rebuilt this version:
https://docs.seldon.io/projects/seldon-core/en/v1.2.3_a/ (Build #14844358)
> I still don't see any <link rel="canonical"> tags in the page.

Looks like this was due to an old version of the theme being installed (<0.5)

https://github.com/SeldonIO/seldon-core/blob/4983ff1f8dc3769b8c3a07d93ff0b0e460f5f640/doc/requirements.txt#L4

There was a change to support the canonical URL using sphinx's `html_baseurl` a while ago.
https://github.com/readthedocs/sphinx_rtd_theme/commit/c27ac2944bc26cc1d65a6963a3763c36f7fd3dfb

I have changed your projects to install the latest version by default https://docs.readthedocs.io/en/stable/builds.html#default-versions-of-dependencies.

I triggered a re-build for that version again https://readthedocs.org/projects/seldon-core/builds/16680900/ and it has the correct canonical tag.

```
<link rel="canonical" href="https://docs.seldon.io/projects/seldon-core/en/latest/index.html" />
```

**Comment by edshee** [comment]
Thanks @stsewd that's really helpful. Happy for you to close this if it's not present in current versions.

**Comment by stsewd** [comment]
I think we should still update our docs about the need to re-build previous versions if the canonical URL is changed.

**Comment by humitos** [comment]
Closing in favor of #8469. That issue is about documenting how Canonical URLs work. I added a comment there saying that we need to communicate this requirement better.

**Comment by corneliusroemer** [comment]
We're encountering this issue with `nextstrain-augur.readthedocs.io`. Google shows the correct link for stable: `docs.nextstrain.org/augur/stable` but _also_ further down the results for outdated versions pointing to `nextstrain-augur.readthedocs.io`. I guess we need to rebuild.
