### ISSUE TITLE
Mark commercial documentation more clearly

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/readthedocs.org#8535]
>> How do we distinguish .com content? Perhaps an emoji and a warning at the top of the guide or similar to what we do for sphinx-only content?

> I was precisely thinking of an emoji. And rather than a warning, a custom-colored admonition?

Creating a custom admonition was harder than expected 🙃 But even so, I think the right approach would be to mark a page or a section with `:commercial:`, and have some extension code that does the rest (changing the color? adding an admonition on top? adding an emoji to the title?). Also, it should work on PDF and EPUB, not only on HTML.

**Comment by ericholscher** [comment]
I don't think we need an extension for this. I think we can just use an emoji and a normal admonition in the header?

**Comment by astrojuanlu** [comment]
Yes we can - but we'd have to do it manually for every page? A bit of copy-paste that we could avoid with some Sphinx hackery

![XKCD 974](https://imgs.xkcd.com/comics/the_general_problem.png)

<sup>See also XKCD#1205, or XKCD#1319...</sup>

**Comment by ericholscher** [comment]
We'd still need to set some metadata on every page, and probably want different admonitions I'm guessing over time :)

**Comment by humitos** [comment]
If we want to do an extension, it can be done in a similar way as https://github.com/humitos/sphinx-version-warning . It used to add an extra docutils node for the admonition.

While using an extension like that may be simple, I think it may be _too much_ for this. I think we can just add a CSS class to do this job:

```rst
.. admonition: Title
   :class: commercial
   
   Content
```

Then in a CSS file:

```css
.commercial {
  ...
}
```

An improved version of this could be to use `:commercial:` RST metadata on each page. Then from Python at build time, iterate over those and append an admonition node on the top of the page. It's simpler, but does not allow different admonitions for each page.

**Comment by astrojuanlu** [comment]
I concede that creating an extension for this might be premature optimization, but do we _really_ want different admonitions for each page? I think we should strive for consistency.

Even if we don't block this work on creating an extension, I don't think this use case is _so_ niche. I bet other projects would benefit from it.

**Comment by humitos** [comment]
I think that depends on what we want. With more clear requirements on the work wanted here, it would be easier to give better feedback here. A Sphinx extension can be "as simple as a Python function" ™️  in our `conf.py` if we want to just add a docutils node on the top --so I'm not discarding that idea _yet_ (see https://github.com/humitos/sphinx-version-warning/blob/0.2.0/versionwarning/__init__.py#L39 and https://github.com/humitos/sphinx-version-warning/blob/0.2.0/versionwarning/signals.py#L18-L21 which are, 10 lines?)

**Comment by astrojuanlu** [comment]
> A Sphinx extension can be "as simple as a Python function" :tm: in our `conf.py` if we want to just add a docutils node on the top

Hah, not so fast 😛 https://github.com/sphinx-doc/sphinx/issues/6751 (it just needs to be in `doc_extensions.py`)

**Comment by humitos** [comment]
> I'm all for simple solutions until we have a strong need for more creative solutions. If we are going to put the same block at the top of pages/sections that are specific to commercial hosting, we can always just start with an `.. include::`.

This is the solution that's currently implemented: https://github.com/readthedocs/readthedocs.org/blob/3eae8f51fc4bb670f89fb47abd5ce23b5cd95e9a/docs/user/guides/manage-read-the-docs-teams.rst?plain=1#L4

> A complementary (or I might say underlying, even) issue we have with commercial-specific documentation is that this documentation is scattered and rather buried

This was part of the Diataxis work we've done.
