### ISSUE TITLE
Add new section to docs with "meta" content

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/readthedocs.org#8538]
I think in the future we should migrate support/faq to another section, probably w/ glossary and a few other "meta" things.

_Originally posted by @ericholscher in https://github.com/readthedocs/readthedocs.org/pull/8528#discussion_r717746117_

**Comment by humitos** [comment]
I think the current FAQ does a good job by listing all the questions at the top. I'm not sure if there are others things required from this issue. I will close it for now, but feel free to reopen expanding what's missing from our side.
