### ISSUE TITLE
Replace yamale with python implementation of jsonschema

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#8549]
https://github.com/Julian/jsonschema that looks like a good implementation of json schema in python, we could even replace part of our config validation with that.

We are using yamale only here https://github.com/readthedocs/readthedocs.org/blob/master/readthedocs/rtd_tests/tests/test_build_config.py, but we don't use anything from yamale in production which is also weird having yamale only to test the spec (which we don't use).

Also, yamale doesn't have all features from jsonschema (we added comments in the file because of that)
https://github.com/readthedocs/readthedocs.org/blob/master/readthedocs/rtd_tests/fixtures/spec/v2/schema.yml

And now our json schema is published in schemastore https://github.com/readthedocs/readthedocs.org/blob/master/readthedocs/rtd_tests/fixtures/spec/v2/schema.json, so I think makes more sense to test that schema instead of the one from yamale.

Other parts were we are using yamale is in our docs, we are linking to the yamale spec, we should instead link to the json schema instead, which is more popular.

**Comment by humitos** [comment]
👍🏼 on removing things we don't use 😄
