### ISSUE TITLE
Installing pypiwin32 Fails; Python 2.x Print Statement?

### ISSUE THREAD

**Issue by jmdelahanty** [readthedocs/readthedocs.org#8554]
## Details
Installing pypiwin32 during RTD build fails due to what appears to be a Python 2 print statement.  It collects the package successfully, but when it tries to install it I get the following message during the process:
```
Collecting pypiwin32
  Downloading pypiwin32-219.zip (4.8 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/docs/checkouts/readthedocs.org/user_builds/bruker-control/envs/latest/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-1zxucya9/pypiwin32_977510538cc24a8fbce43efbe8ebacda/setup.py'"'"'; __file__='"'"'/tmp/pip-install-1zxucya9/pypiwin32_977510538cc24a8fbce43efbe8ebacda/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ydauo4rq
         cwd: /tmp/pip-install-1zxucya9/pypiwin32_977510538cc24a8fbce43efbe8ebacda/
    Complete output (6 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-1zxucya9/pypiwin32_977510538cc24a8fbce43efbe8ebacda/setup.py", line 121
        print "Building pywin32", pywin32_version
                               ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Building pywin32", pywin32_version)?
```
I read up that the version I'm using here was built for Python 2 on the package's pypi page, but it's the version that works with the API I'm using to control a cool microscope.

Also, RTD is great! Thank you for all your work maintainers!

* Read the Docs project URL:  https://bruker-control.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/bruker-control/builds/14893925/
* Read the Docs username (if applicable): jmdelahanty

## Expected Result

Installation of pypiwin32

## Actual Result

Error message during build as shown above.

**Comment by astrojuanlu** [comment]
Hi @jmdelahanty ! One quick question: don't you mean `pywin32`, rather than `pypiwin32`? I see that the latter depends on the former, so it seems to be there just to protect users from typos? Also, looks like `pywin32` is compatible with Python 3.

**Comment by astrojuanlu** [comment]
Yes, see https://github.com/mhammond/pywin32/issues/1151

**Comment by jmdelahanty** [comment]
Hello astrojuanlu! Thanks for your help!

This morning I've been working with your suggestion to use pywin32 and I've been running into a hopefully more straightforward error. I get the following when I include `pywin32` in my `requirements.txt`:
```
ERROR: Could not find a version that satisfies the requirement pywin32 (from versions: none)
ERROR: No matching distribution found for pywin32
```

When I try to specify the version of pywin32 I used for running the application that's in my environment file, I run into the same error:
```
ERROR: Could not find a version that satisfies the requirement pywin32==228 (from versions: none)
ERROR: No matching distribution found for pywin32==228
```

Could this be because I used conda to install `pywin32` and not pip?

**Comment by jmdelahanty** [comment]
That makes sense! I was looking for a way to build it without mocking the imports. I've tried mocking before, but didn't seem to get it working properly. I'll give that a shot today and see if I make any progress. I'll update here if I run into any issues. Thank you so much for your help!

**Comment by jmdelahanty** [comment]
Quick update for the thread: Still not getting the mocking correct for some reason... Perhaps one solution is to make a "Docs only" module and then use that for documentation in the future? What do you think @astrojuanlu?

**Comment by jmdelahanty** [comment]
I have solved the problem! It turns out I was mocking things incorrectly because in my module I use `win32com` to actually use `pywin32`!

When I have:
`autodoc_mock_imports = ['win32com']`

My docs build like they're supposed to!

I'll close the issue with this. Thanks for all your help everyone!

**Comment by Adele583** [comment]
i have the same problem but don't understand what you are all saying

**Comment by astrojuanlu** [comment]
Hi @Adele583 , welcome! Please open a new issue describing your problem in detail 😊
