### ISSUE TITLE
Invalid certificates (Let's Encrypt related)

### ISSUE THREAD

**Issue by tfardet** [readthedocs/readthedocs.org#8555]
Probably due to the fact that the Let's Encrypt root certificate expired on 30 September 2021, trying to pull from many non-Github repositories leads to ``server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none``.
Would it be possible to update the certificates to resolve this?
This is for instance an issue when using submodules that are not hosted on GitHub.

**Comment by humitos** [comment]
>  Would it be possible to update the certificates to resolve this?

What are the required steps that Read the Docs should follow to do this?

**Comment by humitos** [comment]
> trying to pull from many non-Github repositories leads to `server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none`.

Do you have an example of a build URL failing with this error?

**Comment by tfardet** [comment]
> Do you have an example of a build URL failing with this error?

https://readthedocs.org/api/v2/build/14898416.txt

> What are the required steps that Read the Docs should follow to do this?

I don't know exactly how you manage your VMs but you need to patch the system certificate of your Linux (Ubuntu LTS?) to use the new Let'sEncrypt certificate

**Comment by humitos** [comment]
Another workaround would be to execute `apt-get install ca-certificates` as part of the build process from inside Read the Docs application itself.

**Comment by agjohnson** [comment]
I think we should be able to rebuild all the images, not just our beta image. Ubuntu releases are stable enough that I would trust things to work. Package versions do not drift heavily once in an LTS

**Comment by tfardet** [comment]
> However, we can easily rebuild our latest one (readthedocs/build:ubuntu-20.04) with the latest ca-certificates version (20210119~20.04.2) installed and tell users to define this image on their config file.

That's fine with me :+1: can you ping me once that done?

I don't think a workaround is a good idea, the first option would probably save you some work when others start having that same issue

**Comment by rjw57** [comment]
> However, we can easily rebuild our latest one (readthedocs/build:ubuntu-20.04) with the latest ca-certificates version (20210119~20.04.2) installed and tell users to define this image on their config file.

Wouldn't that introduce a chicken and egg problem whereby the repo needs to be able to be cloned so that the configuration required to clone the repo can be read?

**Comment by ExtremOPS** [comment]
I am experiencing the same problem as op described. My code repository is hosted on a GitLab server.

If there is something with which I (a noob) could help, please let me know.

**Comment by humitos** [comment]
@rjw57 

> Wouldn't that introduce a chicken and egg problem whereby the repo needs to be able to be cloned so that the configuration required to clone the repo can be read?

Yes. I may express myself wrong here.

We use a default Docker image to run `git` commands inside it (currently we use `readthedocs/build:latest`) and I think we could use the new image `readthedocs/build:ubuntu-20.04` with a newer version of `ca-certificates` to do the `git` commands.

However, even if the `git` commands succeed, there may be other commands that may fail in the build process due to the old CA certificates. In that case, users could define `readthedocs/build:ubuntu-20.04` as the build image to fix that problem.

**Comment by astrojuanlu** [comment]
xref https://stackoverflow.com/q/69439345/554319

**Comment by tfardet** [comment]
@humitos can I approve the PR or does it have to be someone from RtD?

**Comment by stsewd** [comment]
> @humitos can I approve the PR or does it have to be someone from RtD?

that's a core team decision, but if you have any feedback there, feel free to comment!

**Comment by tfardet** [comment]
> that's a core team decision, but if you have any feedback there, feel free to comment!

thought so, so no, nothing to change on my side; I think this is the right server-side fix for now

**Comment by humitos** [comment]
We deployed a quick and temporal fix for now. Please, let us know if you still have issues with the certificates. Thanks!

**Comment by guigomcha** [comment]
I can confirm that the hotfix fixed our project build. Thanks a lot everyone!
