### ISSUE TITLE
Missing E1120 for the incorrectly called class methods of objects passed to the functions

### ISSUE THREAD

**Issue by manefix** [readthedocs/readthedocs.org#8556]
1. create class with some method with any mandatory field, e.g. 'error_message' 
2. create some function with one argument accepted with type of that class created above
3. inside that function just call the class method of the passed object with no arguments
4. Run pylint vs the code above

## Expected Result

E1120: No value for argument 'error_message' in method call (no-value-for-parameter)

## Actual Result

Nothing is reported, and this is pretty common situation

--------------------------------------------

Sample that is required to work but it is not: 

---------------------------------------------
class Report:
    def add_error(self, error_message: str):
        print(self, error_message)

def main(report: Report):
    report.add_error() # here we should pass printable value, but forgot about it, pycharm will remind us, but not pylint... 

---------------------------------------------

Currently working: 

---------------------------------------------
class Report:
    def add_error(self, error_message: str):
        print(self, error_message)

report = Report()
report.add_error() # outside the function this code will cause pylint violations

---------------------------------------------

**Comment by astrojuanlu** [comment]
Hello @manefix, it's a bit difficult to understand how this issue is related to Read the Docs. Could you please clarify which project does this refer to?

**Comment by manefix** [comment]
sorry, I ve been reporting to pylint issue, is it possible to move it to pylint project?
