### ISSUE TITLE
Track creation date of redirects

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#8561]
We need to inherit from `TimeStampedModel`

https://github.com/readthedocs/readthedocs.org/blob/3313d556096310c50b51be06bf46a78d827019fd/readthedocs/redirects/models.py#L54-L54

similar to https://github.com/readthedocs/readthedocs.org/blob/3313d556096310c50b51be06bf46a78d827019fd/readthedocs/projects/models.py#L1478-L1478

and override those fields to be nullable to avoid downtime during deploy.

We could expose this data in the UI later, so is easy to know when the list of redirects was last updated.

**Comment by humitos** [comment]
I would extend the issue to cover all our models if possible --not only `Redirect`; unless there is a reason to not do it 😄

**Comment by stsewd** [comment]
yeah, we should add this to more models,

**Comment by deepto98** [comment]
@stsewd I would like to pick this up, ca you assign this to me?

**Comment by stsewd** [comment]
> @stsewd I would like to pick this up, can you assign this to me?

Feel free to just say you are working on the issue and send the PR, no need for assignments.

**Comment by humitos** [comment]
If I understand correctly we have this data already: https://github.com/readthedocs/readthedocs.org/blob/237709469573a5b50fe44e27d095129166abebbd/readthedocs/redirects/models.py#L105-L106
