### ISSUE TITLE
detect removed/unavailable/404 repository and take generated output offline

### ISSUE THREAD

**Issue by crackwitz** [readthedocs/readthedocs.org#8570]
## Details

* Read the Docs project URL: (example) https://opencv24-python-tutorials.readthedocs.io/

## Expected Result

I think that if a source repo is removed, so should the generated documentation on RTD. If such an action is delayed for some "grace period", I think that's reasonable.

## Actual Result

Generated output is still there (see URL above) even though the repo was taken offline by the owner because it's a stale fork of another repo that was upstreamed into the actual open source project.

**Comment by astrojuanlu** [comment]
That would actually help us with some spam issues we're having 🙂  But detecting if a project is "gone" might be very resource-intensive, I assume? (Like, polling every repository of every project on RTD with some cadence).

A different case is checking _when the project admin changes the URL_. I think @humitos proposed something along these lines. But still, doesn't solve your original request, I think.

**Comment by crackwitz** [comment]
No, this is about that:
OpenCV is an active project with actively maintained documentation.
People fork it, make a few commits if any, and then leave their version of the documentation on RTD.
That example repo up there was last touched in 2016, and removed by the owner in 2021.
I hate for newbies to find it and work off information that is five years out of date

**Comment by stsewd** [comment]
Still, we can't just delete those projects, I understand that this is a problem, but we don't dictate the content users should publish.

If this is just to mark or identify those type or projects, we already have https://github.com/readthedocs/readthedocs.org/issues/3382 open. The abandoned project policy is used per-user request, isn't something we would do automatically.

There were some other ideas about having a "verified" status for projects, so they have more priority over forks/clones.

**Comment by ericholscher** [comment]
Yea, I'm going to close this issue. We are working towards making a policy for removing unofficial, outdated docs, which is what I think this issue is mostly about. So this will be solved via human judgement, not automated systems 👍
