### ISSUE TITLE
Clarify webhook and integration documentation

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/readthedocs.org#8573]
Coming from #8522:

> So, in our docs we have a `webhooks` page...

Seeking some feedback on the terminology here. We could:

- Rename `/webhooks.html` to `/integrations.html`
- Replace `Incoming Webhooks and Automation` by `Integrations and Automation`,
- And use the term "integration" rather than "webhook" throughout the page, unless it refers to a UI option.

This would be more consistent with the UI. However, each of these individual integrations is still called "incoming webhook":

![image](https://user-images.githubusercontent.com/316517/136829010-8c50ac23-17f1-45b1-9ec0-72752269e98b.png)

Therefore, for full consistency, probably we should rename "incoming webhook" to just "integration". I just checked that this is what GitHub and MailerLite do.

What do folks think?

And then, after renaming `/webhooks.html`, would it be wise to repurpose the URL for outgoing webhooks? Otherwise, we would keep them at https://docs.readthedocs.io/en/stable/build-notifications.html#using-webhook, including the upcoming new features introduced at https://github.com/readthedocs/readthedocs.org/pull/8522.

cc @readthedocs/advocacy @readthedocs/backend

**Comment by ericholscher** [comment]
@astrojuanlu Definitely feel free to do a larger rename/refactor here. Lots of naming debt, so make a proposal 👍

**Comment by humitos** [comment]
I'd avoid using "Integrations" unless we provide something else than a webhook. When using "webhook" is clear that we will send/receive a request with data, nothing else. On the other hand, "integration" conveys a lot more work done between the parts involved in the integration. An example of integration to me are GitHub Applications and/or Slack Applications.
