### ISSUE TITLE
Build fails on build.tools.python="3.10"

### ISSUE THREAD

**Issue by awolosh1** [readthedocs/readthedocs.org#8610]
## Details

* Read the Docs project URL: https://ha-task-locker.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/ha-task-locker/builds/15075981/
* Read the Docs username (if applicable): awolosh

## Expected Result

Build to render docs using python 3.10

## Actual Result

Problem in your project's configuration. Invalid "build.tools.python": .readthedocs.yaml: Invalid configuration option: build.tools.python. Make sure the key name is correct.

**Comment by layday** [comment]
> What would be the change you would like to see in the docs to make it more clear?

The error message is misleading. The build fails because the `os` key is missing but it points to the `python` option being invalid, which it isn't.

**Comment by astrojuanlu** [comment]
Fair enough, I wonder if it would be possible to improve the error message without breaking backwards compatibility?
