### ISSUE TITLE
Build Failed. TypeError: 'generator' object is not subscriptable

### ISSUE THREAD

**Issue by GilimkhanovDenis** [readthedocs/readthedocs.org#8616]
_**Update from @astrojuanlu**: see [this comment](https://github.com/readthedocs/readthedocs.org/issues/8616#issuecomment-952034858) for a workaround for this issue, [our blog](https://blog.readthedocs.com/build-errors-docutils-0-18/) for a more detailed explanation, and [this comment](https://github.com/readthedocs/readthedocs.org/issues/8616#issuecomment-973994826) for current status of this issue_

---

Success Build: https://readthedocs.org/projects/diadocsdk-1c/builds/15092197/
Failed Build: https://readthedocs.org/projects/diadocsdk-1c/builds/15095749/

It's the same commit

What is changed during 8 hours ?
What can I do for successful build?

```
building [html]: targets for 402 source files that are out of date
updating environment: 402 added, 0 changed, 0 removed
reading sources... [  0%] ComObjects/AcceptanceCertificateBuyerContent
reading sources... [  0%] ComObjects/AcceptanceCertificateContent
reading sources... [  0%] ComObjects/AcceptanceCertificateItem
reading sources... [  0%] ComObjects/AcceptanceCertificateSellerContent

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/diadocsdk-1c/envs/dev/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/diadocsdk-1c/envs/dev/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/diadocsdk-1c/envs/dev/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/diadocsdk-1c/envs/dev/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/diadocsdk-1c/envs/dev/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/diadocsdk-1c/envs/dev/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/diadocsdk-1c/envs/dev/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/docs/checkouts/readthedocs.org/user_builds/diadocsdk-1c/envs/dev/lib/python3.7/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/diadocsdk-1c/envs/dev/lib/python3.7/site-packages/docutils/core.py", line 219, in publish
    self.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/diadocsdk-1c/envs/dev/lib/python3.7/site-packages/docutils/core.py", line 200, in apply_transforms
    self.document.transformer.apply_transforms()
  File "/home/docs/checkouts/readthedocs.org/user_builds/diadocsdk-1c/envs/dev/lib/python3.7/site-packages/sphinx/transforms/__init__.py", line 90, in apply_transforms
    Transformer.apply_transforms(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/diadocsdk-1c/envs/dev/lib/python3.7/site-packages/docutils/transforms/__init__.py", line 171, in apply_transforms
    transform.apply(**kwargs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/diadocsdk-1c/envs/dev/lib/python3.7/site-packages/sphinx/transforms/references.py", line 38, in apply
    domain.process_doc(self.env, self.env.docname, self.document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/diadocsdk-1c/envs/dev/lib/python3.7/site-packages/sphinx/domains/std.py", line 586, in process_doc
    self.note_labels(env, docname, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/diadocsdk-1c/envs/dev/lib/python3.7/site-packages/sphinx/domains/std.py", line 638, in note_labels
    n = node.traverse(addnodes.toctree)[0]
TypeError: 'generator' object is not subscriptable

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/diadocsdk-1c/envs/dev/lib/python3.7/site-packages/sphinx/domains/std.py", line 638, in note_labels
    n = node.traverse(addnodes.toctree)[0]
TypeError: 'generator' object is not subscriptable
```

**Comment by anitagraser** [comment]
I tried to pin docutils in setup.py:  https://github.com/anitagraser/movingpandas/commit/1b6a47ee0fbbc8cde78ee86a36531a01951cd789

But the build keeps failing: https://readthedocs.org/projects/movingpandas/builds/15140289/

Is it recommended to use requirements.txt instead of setup.py?

**Comment by astrojuanlu** [comment]
Hi @anitagraser , I see in the logs that the `setup.py install` step is effectively bringing docutils 0.17, and still the error appears. I still don't know what could have happened, feel free to open a new issue to analyze this case in depth.

**Comment by gwilku** [comment]
> For future readers, the solution for this problem is to pin `docutils<0.18` in your `requirements.txt` file, and have a `.readthedocs.yaml` file with these contents:
> 
> ```
> version: 2
> 
> python:
>    install:
>    - requirements: docs/requirements.txt
> ```
> 
> More information [in our docs](https://docs.readthedocs.io/en/stable/config-file/v2.html#requirements-file).

How can we do that? The docs quoted is really not helpful at all (mentions the requirements.txt but doesn't give any details on it's syntax nor how to generate it)

**Comment by astrojuanlu** [comment]
Good point @gwilku, I agree that those docs should have more context. In the meanwhile, this page contains exactly what you need: https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html

**Comment by gwilku** [comment]
@astrojuanlu so, do I understand correctly, that a step by step is to:
edit .readthedocs.yml and uncomment:
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt

and create docs/requirements.txt with a single line:
docutils<0.18


and that's it?

or do I need to generate the requirements.txt so that it includes all the requirements somehow?

**Comment by gwilku** [comment]
Because the page you linked shows a sample:
# File: docs/requirements.txt

sphinx==3.4.3
sphinx_rtd_theme==0.5.1
readthedocs-sphinx-search==0.1.0rc3

But I have no idea, where to get the version numbers from?

**Comment by gwilku** [comment]
Because I tried the requirements.txt with docutils<0.18 yet the build seems to ignore it anyway, and keeps:
Collecting docutils>=0.11
  Downloading docutils-0.18-py2.py3-none-any.whl (569 kB)

**Comment by astrojuanlu** [comment]
@gwilku I see you figured it out here: https://github.com/gwilku/jscan-docs/commit/b4f1ebeb445757c2901ae629edd2fa8d26073163

**Comment by gwilku** [comment]
@astrojuanlu yes, got it -  it's enough to have this one line in the requirements.txt

**Comment by coleifer** [comment]
Does it make sense to just have the default build environment used by RTD specify the working version of docutils?

**Comment by gwilku** [comment]
> Does it make sense to just have the default build environment used by RTD specify the working version of docutils?

This is exactly what I have suggested (and would actually have expected)

**Comment by agjohnson** [comment]
Well, there are some problems with trying to guess the version of docutils that users need. We actually used to install a pinned version of docutils as a pre-install step, but every dependency that we pin leads to confusion for users. Because of this, and all the confusing UX resulting from this, we've been moving away from pinning dependencies for users, and instead expect users to tell us what to install. At least this way you can easily replicate errors locally by just installing your dependencies. With Read the Docs magic helping in the middle, this isn't possible and it gets even more confusing.

The problem is that if we pin `docutils==0.16` as a pre install step, that now satisfies the dependency from Sphinx 4 for `docutils<0.18` and docutils is never upgraded. Very few projects would ever know what docutils does, so this particular dependency is not likely to be pinned in a projects dependencies. Additionally, we aren't doing any inspection of which version of Sphinx is installed, so would need to pre-install a docutils version for all projects.

The best solution here is probably for Sphinx to backport release 1.x and 2.x releases, neither of which pin docutils at the moment. Sphinx 3.x does pin `docutils>=0.12,<0.17` at least, as does Sphinx 4.x. Alternatively, there needs to be a better error message emitted from docutils so users are left absolutely lost all of a sudden.

**Comment by gmilde** [comment]
Please update the examples in the RTD documentation (https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html).

We now know that e.g.

> ✅ Good:
> The specified versions will be used for all your builds, in all platforms, and won’t be updated unexpectedly.
> 
> # File: docs/requirements.txt
> 
> sphinx==3.4.3
> sphinx_rtd_theme==0.5.1
> readthedocs-sphinx-search==0.1.0rc3

is actually not good (as it pins a legacy Sphinx version but not the related Docutils).

With the requirements relaxed to

~~~
sphinx<4.0
sphinx_rtd_theme==0.5.1
~~~

users will get the backported fix (Docutils pin added in 3.5). 
A a pin on not-fixed legacy Sphinx versions must be amended with a Docutils pin like, e.g.

~~~
sphinx==3.4.3
docutils < 0.17
sphinx_rtd_theme==0.5.1
readthedocs-sphinx-search==0.1.0rc3
~~~

**Comment by astrojuanlu** [comment]
Good catch @gmilde , I'll do

**Comment by astrojuanlu** [comment]
Update: Sphinx 1.8.6 was released this week, and it pins docutils to `<0.18` (thanks @tk0miya ❤️)

However, users of old pip versions (for example on Python 2) might not benefit from this, and will need to pin docutils themselves anyway. Otherwise, they will still observe the error, plus this warning on the logs:

```
ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. This behaviour is the source of the following dependency conflicts.
sphinx 1.8.6 requires docutils<0.18,>=0.11, but you'll have docutils 0.18 which is incompatible.
```

**Comment by gmilde** [comment]
Am 19.11.21 schrieb Juan Luis Cano Rodríguez:

> However, users of old pip versions (for example on Python 2) might not
> benefit from this
...

Could you test whether Docutils 0.18.1b (released on Thursday) fixes the
error? Then, Sphinx 1.8.x could lift the pin to `docutils < 1.0`.

**Comment by astrojuanlu** [comment]
Thanks @gmilde , looking into this 👍🏽

**Comment by astrojuanlu** [comment]
@gmilde I confirm that docutils 0.18.1b1 does not exhibit the `'generator' object has no attribute '__getitem__'` (or variations of it) anymore 👍🏽 

<details>

I was testing with a fork of the project where I originally detected this. I may delete the project at any time.

- Bad build :x: https://readthedocs.org/projects/phpunit-documentation-english/builds/15345361/
- Good build ✔️ https://readthedocs.org/projects/phpunit-documentation-english/builds/15345399/

Amending diff: https://github.com/astrojuanlu/phpunit-documentation-english/commit/968e3d20b6fa119a157ef8ea5c2ebd8973964096

</details>
