### ISSUE TITLE
Does readthedocs behave differently if a build branch has a slash in it?

### ISSUE THREAD

**Issue by villaa** [readthedocs/readthedocs.org#8633]
## Details

I am using `readthedocs` to build documentation for my [project][1].

I currently have two branches `docstest` and `feature/sphinx` with identical content being parsed by `readthedocs`. You can view each of these by clicking the version tab on the sidebar from the docs frontpage that I linked. 

I have been struggling to get `feature/sphinx` to render correctly, in particular it seems like (maybe?) when I use `feature/sphinx` it expects the source tree to start in `docs/` rather than `docs/source`. Currently all the source is in `docs/source` like in [this example][2]. This leads to `feature/sphinx` not rendering correctly (i.e. the ToC is not rendered at all). Is it because the branch name has a slash in it? 

Also neither branch seems to render the side-bar correctly. Any idea why that is? 

  [1]: https://nrcascadesim.readthedocs.io/en/latest/
  [2]: https://obscura.readthedocs.io/en/stable/

See issue on SO [here](https://stackoverflow.com/questions/69745031/does-readthedocs-behave-differently-if-a-build-branch-has-a-slash-in-it).

## Expected Result

That the rendering of two identical branches be identical regardless of their naming formats. 

## Actual Result

The branch that had a slash in it seemed to be different.

**Comment by humitos** [comment]
It seems the original issue was solved and there is no any other action we have to do from our side. Please, feel free to re-open the issue if that's the case.
