### ISSUE TITLE
Projects using conda don't show all packages installed (and IPython CSS is broken)

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/readthedocs.org#8638]
This tweet by @Carreau caught my attention:

https://twitter.com/Mbussonn/status/1454253505724649472

> Yes, css broken. I don't know why, but enough for today.

And indeed, it looks like IPython is experiencing https://github.com/readthedocs/sphinx_rtd_theme/issues/1115:

- Good ✔️  https://ipython.readthedocs.io/en/7.23.1/whatsnew/version7.html#ipython-7-23 (build https://readthedocs.org/projects/ipython/builds/13687131/)
- Bad :x: https://ipython.readthedocs.io/en/7.24.0/whatsnew/version7.html#ipython-7-23-and-7-23-1 (build https://readthedocs.org/projects/ipython/builds/13879122/)

And recent builds also exhibit this behavior, see https://readthedocs.org/projects/ipython/builds/15133660/.

Clearly docutils 0.17 is being used now, but I would expect sphinx_rtd_theme to have addressed the incompatibility. Yet, there is no way to know what version of the theme is getting installed in each build, since the `conda env create` has the `--quiet` flag, and only shows the `pip` part.

**Comment by astrojuanlu** [comment]
Enabled the flag for IPython and triggered a `latest` build https://readthedocs.org/projects/ipython/builds/15221374/

The culprit seems to be a old version of `sphinx_rtd_theme`:

```
conda list --name latest
# packages in environment at /home/docs/checkouts/readthedocs.org/user_builds/ipython/conda/latest:
#
# Name                    Version                   Build  Channel
...
docutils                  0.17.1           py38h06a4308_1  
...
sphinx                    4.2.0              pyhd3eb1b0_1  
sphinx_rtd_theme          0.4.3              pyhd3eb1b0_0  
...
```

**Comment by astrojuanlu** [comment]
Attempt to fix at https://github.com/ipython/ipython/pull/13261

**Comment by astrojuanlu** [comment]
> We have a feature flag for that

Is there a reason to not have `LIST_PACKAGES_INSTALLED_ENV` enabled by default? cc @agjohnson

**Comment by stsewd** [comment]
This is comment linked on the other issue https://github.com/readthedocs/readthedocs.org/pull/6992#issuecomment-621247945

**Comment by astrojuanlu** [comment]
This is a known issue then, and the support request has been addressed. Closing.
