### ISSUE TITLE
Random formatting & parsing

### ISSUE THREAD

**Issue by gwilku** [readthedocs/readthedocs.org#8643]
## Details

* Read the Docs project URL: https://jscan-docs.readthedocs.io/en/latest/jeep/jeep.html#grand-cherokee-wk-wk2
* Build URL (if applicable): https://github.com/gwilku/jscan-docs/commit/01541976df7ba2acbed3ccf9c3f798567997111

## Expected Result

I wanted to get a documentation formatted according to the RST formatting I used.

## Actual Result

RTD/Sphinx decided to format the result based on absolutely no reasonable grounds:

source:
2) Check if Rear Turn Lamps Output Present -> Activated – this option will enable large pins C5/E pin number 3 & C6/F pin number 42 on BCM (Body Computer).
	.. note:: In most vehicles the wiring harness will already have those pins properly wired. If the conversion doesn't work as expected, check the wiring first.

output: sentence in bullet 2) is displayed as bold. WHY?

In addition, formatting lists usually doesn't work on first build and needs two or three tries for RTD to properly format numbered lists ( instead, the list entries are rendered as inline text)

**Comment by Daltz333** [comment]
I took a quick peek and it is strange.

Also it's important to note that ReadTheDocs doesn't really do anything here. The build engine is called [sphinx](https://github.com/sphinx-doc/sphinx). Think of ReadTheDocs more as a web host, it just called `sphinx-build` and hosts the built HTML files (it does do a bit of fancy injection, but I seriously doubt that is the issue here).

**Comment by stsewd** [comment]
Hi, pasting an image could be helpful here. But anyway, what I see is that your list was incorrect indented.

https://github.com/gwilku/jscan-docs/commit/01541976df7ba2acbed3ccf9c3f798567997111

The next line should start below the start of the previous one, i.e:

```rst
1) Replace US rear lights with EU version
2) Set Combined Rear Lightning On/Off -> Set this option to Deactivated. 
   This will leave only turn signals instead of combined lamps.
3) You will now need to add a wire from the third (center) stop light to the stop lights on the sides.
```

**Comment by gwilku** [comment]
Thanks, but that's not the area I'm concerned with:

`
1) Combined Rear Lightning On/Off -> Set this option to Deactivated – this option will disable, brake with turn, only brake light will be available.
2) Check if Rear Turn Lamps Output Present -> Activated – this option will enable large pins C5/E pin number 3 & C6/F pin number 42 on BCM (Body Computer).
	.. note:: In most vehicles the wiring harness will already have those pins properly wired. If the conversion doesn't work as expected, check the wiring first.
3) Right – Second Reverse Lamp – On/Off -> Set this option to Deactivated
`

is rendered as:

![image](https://user-images.githubusercontent.com/6851485/139701626-3cf32bca-e4e4-42d3-9099-60459a42e5e1.png)

where does the bold come from?

**Comment by stsewd** [comment]
@gwilku have you tested that with other themes? If it looks correct in other theme, this may be a bug from https://github.com/readthedocs/sphinx_rtd_theme

**Comment by stsewd** [comment]
Actually, I think I know from where this comes from, it's still related to indentation.

```
1) Check if Rear Turn Lamps Output Present -> Activated – this option will enable large pins C5/E pin number 3 & C6/F pin number 42 on BCM (Body Computer).
	.. note:: In most vehicles the wiring harness will already have those pins properly wired. If the conversion doesn't work as expected, check the wiring first.
```

That line is being interpreted as a definition list inside the enumerated list. You should write it like this instead

```
1) Check if Rear Turn Lamps Output Present -> Activated – this option will enable large pins C5/E pin number 3 & C6/F pin number 42 on BCM (Body Computer).

   .. note:: In most vehicles the wiring harness will already have those pins properly wired. If the conversion doesn't work as expected, check the wiring first.

```
