### ISSUE TITLE
Linking to a sphinx-tabs tab no longer works

### ISSUE THREAD

**Issue by Harmon758** [readthedocs/readthedocs.org#8644]
## Details

Linking to a specific tab when using sphinx-tabs and with the syntax described in https://github.com/executablebooks/sphinx-tabs/issues/47#issuecomment-610563228 no longer works.

Possibly related to / another instance of #7979

* Read the Docs project URL: Any that use sphinx-tabs,  e.g. https://sphinx-tabs.readthedocs.io/en/latest/

## Expected Result

Attempting to link to a sphinx-tabs tab in the URL (e.g. https://sphinx-tabs.readthedocs.io/en/latest/?tab=Oranges) selects the tab.

## Actual Result

The tab is not selected and the URL parameter seems to be ignored.

**Comment by stsewd** [comment]
Hi, the code lives here https://github.com/readthedocs/readthedocs.org/blob/master/docs/_static/js/expand_tabs.js, and it was manually added, it's not part of the sphinx-tabs extension. This problem isn't related to rtd, as we don't provide that as a plugin or anything.

**Comment by Harmon758** [comment]
Ohh, I see, that code is specifically for https://docs.readthedocs.io/. Sorry, I misunderstood your example in https://github.com/executablebooks/sphinx-tabs/issues/47#issuecomment-610563228.
