### ISSUE TITLE
Readthedocs documentation not showing the actual documentation

### ISSUE THREAD

**Issue by Aspect1103** [readthedocs/readthedocs.org#8650]
## Details
So the sphinx build on my local machine builds just fine and displays the documentation, however, on readthedocs, it passes but none of the autoclasses are shown.

* Read the Docs project URL: https://readthedocs.org/projects/lavapy/
* Build URL (if applicable): https://readthedocs.org/projects/lavapy/builds/15176820/
* Read the Docs username (if applicable): Aspect11

## Expected Result

It would show the documentation as per my lavapy.rst file.

## Actual Result

It's not showing the documentation.

**Comment by astrojuanlu** [comment]
Hi @Aspect1103 , looking at the logs (you can expand the subsections by clicking them, or see the raw logs clicking on "View raw"), I see these warnings:

```
WARNING: autodoc: failed to import class 'NodePool' from module 'lavapy'; the following exception was raised:
No module named 'discord'
```

therefore, I'd say that you're missing one of your dependencies. Can you please double check?

**Comment by Aspect1103** [comment]
> Hi @Aspect1103 , looking at the logs (you can expand the subsections by clicking them, or see the raw logs clicking on "View raw"), I see these warnings:
> 
> ```
> WARNING: autodoc: failed to import class 'NodePool' from module 'lavapy'; the following exception was raised:
> No module named 'discord'
> ```
> 
> therefore, I'd say that you're missing one of your dependencies. Can you please double check?

So I added the discord.py packages to my requirements.txt file in docs folder and rebuilt it: https://readthedocs.org/projects/lavapy/builds/15176931/

They're still not showing though.

**Comment by stsewd** [comment]
@Aspect1103 I can see the content at https://lavapy.readthedocs.io/en/latest/lavapy.html, try a hard refresh (Ctrl-F5) or in an incognito window.

**Comment by Aspect1103** [comment]
> @Aspect1103 I can see the content at https://lavapy.readthedocs.io/en/latest/lavapy.html, try a hard refresh (Ctrl-F5) or in an incognito window.

Ahhh, now it's showing. Guess it just took a while to show up on my end.
