### ISSUE TITLE
Disabling autodoc type hints

### ISSUE THREAD

**Issue by ronf** [readthedocs/readthedocs.org#8662]
## Details

* Read the Docs project URL: https://asyncssh.readthedocs.io
* Build URL (if applicable):
* Read the Docs username (if applicable): ronf

## Expected Result

I recently added type hints to my Python project, but I already have markup listing arguments and return values that I'd prefer to use in RTD.

I added `autodoc_typehints = None` to my Sphinx config (in docs/conf.py) and configured that location in the RTD config, but it doesn't seem to be honoring this setting.

## Actual Result

I'm still getting type hint information showing up in the pages RTD generates.

Is there some other mechanism I should be using to change this setting?

**Comment by humitos** [comment]
Hi @ronf! If you build your docs locally, do you get the expected output?

**Comment by ronf** [comment]
Yes - it works fine with my local instance of sphinx-build, which is currently version 4.1.2.

**Comment by humitos** [comment]
In Read the Docs your project is using Sphinx v1.8.5. That may be the problem. Note that you can explicitly tell Read the Docs what dependencies. Read more about this at https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html

Let me know if this works for you. Thanks!

**Comment by ronf** [comment]
Indeed - that fixed it! Thanks so much!
