### ISSUE TITLE
--upgrade-strategy eager in environment setup leads to VersionConflict

### ISSUE THREAD

**Issue by fwitte** [readthedocs/readthedocs.org#8677]
## Details

* Read the Docs project URL: tespy.readthedocs.io
* Build URL (if applicable):
  * https://readthedocs.org/projects/tespy/builds/15254849/
  * https://readthedocs.org/projects/tespy/builds/15234704/ (pull request build)
* Read the Docs username (if applicable): fwitte
* GitHub repository link: https://github.com/oemof/tespy

## Expected Result

The installation of dependencies in two steps (first sphinx and stuff, then the actual package, TESPy) should work smoothly.

## Actual Result

Build fails due to `ContextualVersionConflict`.

## Reason

* pyparsing is first installed in version 2.4.7 (from packaging->sphinx>=1.3->-r docs/requirements.txt), requirement: pyparsing<3,>=2.0.2
* pyparsing is then installed in version 3.0.5 (from matplotlib<4,>=3.2.1->TESPy==0.5.1.dev0), requirement pyparsing>=2.2.1

This leads to the error above and cancels the build. This might be somewhat related (https://github.com/readthedocs/readthedocs.org/issues/7345) but since I am not too familiar with the pip strategies applied on readthedocs, I wanted to ask, if this is a bug. Or should I just add a `pyparsing<3` requirement to the setup.py dependencies of TESPy? Maybe there is a more ellegant solution?

I would also guess, that any other package with a similar matplotlib dependency would lead to the same issue.

Thank you very much for your help, have a nice weekend

**Comment by stsewd** [comment]
Looks like this is a matplolib issue, https://github.com/matplotlib/matplotlib/pull/21446. It was already fixed, but they need a new release.

**Comment by fwitte** [comment]
Thanks for letting me know! :) Should we keep this open, until the matplotlib version is released?

**Comment by stsewd** [comment]
I think it's fine closing, as this isn't specific to rtd, but to the dependencies of sphinx and matplotlib
