### ISSUE TITLE
SORRY This page does not exist yet. (but it does)

### ISSUE THREAD

**Issue by williambrandler** [readthedocs/readthedocs.org#8682]
We have a readthedocs documentation page with a series of notebooks embedded in html.
On most of the docs pages, the notebooks show up fine, except for this page:

https://glow.readthedocs.io/en/latest/tutorial.html
https://github.com/projectglow/glow/blob/master/docs/source/tutorial.rst

The errors states, `SORRY This page does not exist yet.`

I cannot figure out why though, because the notebooks are there and referenced correctly. When I build locally with `make livehtml` they show up

What are the potential causes of this?

**Comment by stsewd** [comment]
Looks like the path from the iframe is wrong.

`src="../_static/notebooks/tertiary/1_quality_control.html"`, it should be `src="_static/notebooks/tertiary/1_quality_control.html"`

Probably the `..` in the path here https://github.com/projectglow/glow/blob/9348a482e0b85a6be4e130c1af1b8b93bd79d7c7/docs/source/tutorial.rst?plain=true#L36

**Comment by williambrandler** [comment]
ah, thanks @stsewd I see what I did, it should be, 

`.. notebook:: . tertiary/1_quality_control.html`
not:
`.. notebook:: .. tertiary/1_quality_control.html`

I didn't spot it because when I built locally the notebooks do show up, which is weird

**Comment by stsewd** [comment]
> I didn't spot it because when I built locally the notebooks do show up, which is weird

that should be because locally the docs are served from `/`, and on rtd they are served from `/en/latest/`.

**Comment by williambrandler** [comment]
ah! 

And the other examples in the Glow docs are one level deeper in the directory structure, so they show up fine
