### ISSUE TITLE
some dependencies should be added in configuration files

### ISSUE THREAD

**Issue by yuluc123** [readthedocs/readthedocs.org#8692]
## Details
I notice that there are several dependencies are missing in configuration files. they are:
- gitdb
- requests_oauthlib
- invoke
- django_cors_headers
- azure_common

They are used in source code. For example, gitdb is used in _readthedocs/vcs_support/backends/git.py_

## Expected Result
It is necessary to add direct dependencies into configuration files.

**Comment by astrojuanlu** [comment]
Hi @yuluc123 , when you say configuration files, you mean our various `requirements/*.txt` files we use to install dependencies for development and production?

**Comment by stsewd** [comment]
- gitdb is an implicit dep from gitpython, I think it's fine having gitpython manage that (we only import that module for a hack/optimization over gitpython)
- invoke isn't used in the rtd codebase, but on separate scripts, and it's on https://github.com/readthedocs/common/blob/main/dockerfiles/requirements.txt (that repo is a submodule on this repo)
- requests_oauthlib no idea from where that dep comes from
- django_cors_headers, didn't find any import from this, but if you mean this https://github.com/readthedocs/readthedocs.org/blob/2696eca9e2a0cf0b3e577a3a48fbe256e7647cb5/requirements/pip.txt#L97, then it's already on our requirements.
- azure_common, we don't use azure in production anymore, we use aws.

**Comment by yuluc123** [comment]
Hi @astrojuanlu I mean that if the dependency is directly used in code files, it should be declared. For example, if the dependency is used for development, maybe it can be declared in requirements-dev.txt?

**Comment by yuluc123** [comment]
Thanks to your reply. Here are my some opinions.
- requests_oauthlib is used in _readthedocs/oauth/services/base.py_ in line 12?
- django-cors-headers is used in _readthedocs/core/signals.py_ in line 8?
Sorry to bother you.

**Comment by astrojuanlu** [comment]
https://github.com/readthedocs/readthedocs.org/blob/2cab501bc95b4f7dcc3d13adacc2f27683973a87/readthedocs/oauth/services/base.py#L12

https://github.com/readthedocs/readthedocs.org/blob/2cab501bc95b4f7dcc3d13adacc2f27683973a87/readthedocs/core/signals.py#L5

**Comment by astrojuanlu** [comment]
> I mean that if the dependency is directly used in code files, it should be declared.

Totally agree with you @yuluc123 👍🏽 Looks like we can be more explicit or do some cleanup.

**Comment by humitos** [comment]
I'm a little lost here 😅 . What are the explicit actions required?

**Comment by astrojuanlu** [comment]
We have 2 undeclared dependencies, that I assume get installed because they are transitive dependencies of something else: `requests_oauthlib` and `django_cors_headers`. We should explicitly list them in our requirements. Besides, we can remove `azure_common`.

**Comment by humitos** [comment]
* I added `requests-oauthlib`.
* `corsheaders` is already declared, it comes from `django-cors-middleware`
* I didn't find anything related to `azure_common`
