### ISSUE TITLE
Config build.tools.python does not accept '3' as doc'd

### ISSUE THREAD

**Issue by adamchainz** [readthedocs/readthedocs.org#8696]
## Details

* Read the Docs project URL: https://django-mysql.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/django-mysql/builds/15309799/
* Read the Docs username (if applicable): adamchainz

## Expected Result

`.readthedocs.yml` is documented as accepting '3' for `build.tools.python`, to mean "latest CPython": https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python

I tried this

## Actual Result

Build failed with:

```
Error

Problem in your project's configuration. Invalid "build.tools.python": expected one of (2.7, 3.6, 3.7, 3.8, 3.9, 3.10, pypy3.7, miniconda3-4.7, mambaforge-4.10, 3), got 3
```

**Comment by astrojuanlu** [comment]
It's documented as accepting `"3"`, since `Type` is `string`. For the enumeration, I followed the convention we had in other parts of that page, but perpahs we could make it more clear that folks should use double quotes?

**Comment by adamchainz** [comment]
Oh, my bad, I missed that "3" is mentioned in the "expected one of..."

**Comment by stsewd** [comment]
We have a warning on the python.version https://docs.readthedocs.io/en/stable/config-file/v2.html#python-version-legacy option, but I think we should show the list with quotes instead of bare numbers, at least for the numeric values. And also the error message should also use quotes to list the valid options, probably.

**Comment by humitos** [comment]
We added this note some time ago:

> Make sure to use quotes (") to make it a string. We previously supported using numbers here, but that approach is deprecated.

I'm closing the issue.
