### ISSUE TITLE
Update base locale

### ISSUE THREAD

**Issue by Blueberryy** [readthedocs/readthedocs.org#8698]
It's been 3 years since last change on these files
(https://github.com/readthedocs/readthedocs.org/blob/2cab501bc95b4f7dcc3d13adacc2f27683973a87/readthedocs/locale/en/LC_MESSAGES/django.po)

**Comment by humitos** [comment]
I'm afraid that we haven't had the time to update these. The work required here would be an automatic integration with Transifex. I think there was a PR opened for this but I couldn't find it. That's the work we should push forward.

**Comment by humitos** [comment]
Here it is the issue, at least: https://github.com/readthedocs/readthedocs.org/issues/4463
