### ISSUE TITLE
Document build page

### ISSUE THREAD

**Issue by astrojuanlu** [readthedocs/readthedocs.org#8704]
On #8702, @agjohnson left this feedback:

> Looks great! There maybe there isn't really anything substantial here, but maybe we want to mention how to verify that the dependencies are being used? This guide goes to mention pinning and the lock file, but might leave the reader guessing how to wrap this process up.

_Originally posted by @agjohnson in https://github.com/readthedocs/readthedocs.org/pull/8702#pullrequestreview-813095693_

But then I realized that, unless I'm mistaken, we are not describing our build page anywhere. I'm referring to this:

![Screenshot 2021-11-23 at 09-44-42 Rich Read the Docs](https://user-images.githubusercontent.com/316517/142993693-4eacaba6-96ab-4fb6-80b4-230757d6a10e.png)

This page has a few UX issues, most notably that the `/home/docs/checkouts/.../python -m pip install` lines need lateral scrolling to actually know what are they installing. And also, I don't think it's at all obvious that folks can _click_ on the blocks to expand the logs. (Pinging @nienn so we take this into account for the new UI)

Then the question is: should we add more information on how users can effectively use this page? Or should we declare it a lost cause until the new UI is ready?

**Comment by astrojuanlu** [comment]
Related: https://github.com/readthedocs/readthedocs.org/issues/7319 (this is probably why most people share the raw link when asking for help)

**Comment by agjohnson** [comment]
> we are not describing our build page anywhere

We do not. This is a huge blind spot in our docs. We have a number of pages I feel we could describe in a much more serious fashion.

> (Pinging @nienn so we take this into account for the new UI)

@nienn is not yet working on ext-theme. I already have this UI polished however, tackling a lot of the UI issues we've noted with this page (including the path prefixing and over-verbosity of commands)

> Then the question is: should we add more information on how users can effectively use this page? Or should we declare it a lost cause until the new UI is ready?

Maybe a middle ground? Is there perhaps some level of hand waving we can do here, or describe things a bit more vague than we might like? Skipping on it for now is totally valid too, I imagine we want to talk about specific features and include screenshots/etc -- so, a bit of lost work if we do it now.

**Comment by humitos** [comment]
Some things have changed here since this issue was opened. We cleanup the commands to avoid showing all those paths, which was pretty annoying.

Besides, the new dashboard does an excellent job here and I don't think we need in-depth documentation about this page: https://beta.readthedocs.org/projects/rich/builds/21185844/

I'm closing this issue for now, but feel free to re-open if you consider.
