### ISSUE TITLE
Can i mark a commit as to skip building the docs?

### ISSUE THREAD

**Issue by ankostis** [readthedocs/readthedocs.org#871]
Is it possible to mark a commit so that readthedocs does not start rebuilding the docs?

TravisCI has this feature: http://docs.travis-ci.com/user/how-to-skip-a-build/#Not-All-Commits-Need-CI-Builds

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3qipz)

**Comment by ankostis** [comment]
If this gets implementedc, it would alleviate some needless burden on the RTD's servers.

By the way, TravisCI supports both these forms: ``[ci skip]`` and ``[skip ci]`` so i would expect here to be: ``[rtd skip]`` and ``[skip rtd]``.

**Comment by gregmuellegger** [comment]
When we implement it, we should stick to a generic tag like travis is doing (so that more documentation  platforms could support it), like `[docs skip]` and `[skip docs]`.

**Comment by humitos** [comment]
Updated travis documentation: https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build

**Comment by Artic2017** [comment]
9

**Comment by RichardLitt** [comment]
Looks like the link @humitos provided answers this issue. I'm closing it, for now. Feel free to comment if you need more closure!

**Comment by humitos** [comment]
Hehe, my link was just to fix the one that was added to the description (which doesn't point to the correct section) but the feature is not implemented at RTD yet. I'm reopening it.

Sorry about the confusion, I should have explained myself better :)

**Comment by humitos** [comment]
We are not going to implement this for now. We just closed the PR #3457. We can revisit later if we consider. Thank you all!

**Comment by stsewd** [comment]
Since we have our new feature for building docs from PRs, we are considering having this feature.

**Comment by agjohnson** [comment]
Update here: we are currently working on a generic way to expose the ability to skip builds in #9649. Users will be able to define any pattern they like here to skip a build, using `build.jobs` and `build.commands`.
