### ISSUE TITLE
Don't allow last maintainer to leave a project

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#8719]
This maybe needs replication, I thought we blocked this already. It could be that a user removes their account, leaving projects behind in an abandoned state.

It seems it might be possible for the last remaining maintainer on a project to remove themself from the project, effectively abandoning the project. This is an action we should probably block from happening, and maybe steer the user towards deleting the project instead.

In the case of a user deleting their account, I thought we also at least warned about this and/or removed the project. If not, it might be another place to block the user from deleting and require no single-maintainer projects to exist before deletion?

**Comment by stsewd** [comment]
Where did you find this problem?

We do check for this

https://github.com/readthedocs/readthedocs.org/blob/master/readthedocs/projects/views/private.py#L488-L496

but  I guess that code could hit a race condition with two users removing themselves at the same time.

**Comment by agjohnson** [comment]
This was a user report. I updated the project users to fix the problem already, so not sure if there is too much to debug in the data.

Seems the user had imported a project, hit some issue with the project, and was trying to free up the slug to reuse it. I found the project with 0 maintainers, but it wasn't clear how that happened. It looked like a personal repository of the user, so this user was most likely the sole user prior to whatever happened.

**Comment by stsewd** [comment]
We don't even show the option to remove yourself if you are the only one left. So, I'm not sure if we have enought information to fix this.

![Screenshot 2021-11-30 at 09-42-23 Edit Maintainers Read the Docs](https://user-images.githubusercontent.com/4975310/144068152-45cde5fe-6633-4c46-bbe2-837c1c22dcfb.png)

**Comment by stsewd** [comment]
also tried deleting an account, the project is deleted as well.

**Comment by agjohnson** [comment]
I can point out the conversation in chat, I was quite baffled by this one as well.
