### ISSUE TITLE
Build error with build id #15389045

### ISSUE THREAD

**Issue by MartinPdeS** [readthedocs/readthedocs.org#8721]
## Details:

* Project URL: https://readthedocs.org/projects/PyMieSim/
* Build URL(if applicable): https://readthedocs.org/projects/pymiesim/builds/15389045/
* Read the Docs username(if applicable): MartinPdeS

## Expected Result

I expect the build to start.

## Actual Result

The build stop and exit after the git clone --no-single-branch --depth 50 https://github.com/MartinPdeS/PyMieSim.git .
While the raw shows only exit-code 0 (== Sucess), the build do not proceed.

**Comment by gbroques** [comment]
GitHub was having an incident yesterday around the time of your build failures:
https://www.githubstatus.com/incidents/r5qrpp2f5fc0

It may be related.

Your build seems to be passing now.

**Comment by astrojuanlu** [comment]
Thanks @gbroques for chiming in. Indeed, @MartinPdeS your project builds seem to be passing now, feel free to open a new issue if you see anything weird again.
