### ISSUE TITLE
Building fails since the latest release of mistune

### ISSUE THREAD

**Issue by xuyxu** [readthedocs/readthedocs.org#8741]
## Details

It looks like that RTD fails to build my document since the [latest release](https://pypi.org/project/mistune/#history) of `mistune` in Dec 5.

* Read the Docs project URL: https://ensemble-pytorch.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/ensemble-pytorch/builds/15462088/
* Read the Docs username (if applicable):xuyx

Will appreciate your help very much, thanks!

## Expected Result

The building process goes smooth.

## Actual Result

The building process crushes and reports: `AttributeError: module 'mistune' has no attribute 'BlockGrammar'`

**Comment by stsewd** [comment]
Hi, on your last succesfull build (https://readthedocs.org/projects/ensemble-pytorch/builds/15441694/), the version installed was mistune-0.8.4 (which is the previous stable release). You should pin that dependency to that version or update your code to support the new version.

**Comment by xuyxu** [comment]
Problem solved 🎊, thanks @stsewd
