### ISSUE TITLE
Show token for GitLab integration webhook

### ISSUE THREAD

**Issue by douglas-raillard-arm** [readthedocs/readthedocs.org#8743]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/lisa-linux-integrated-system-analysis/

## Expected Result

I'm currently trying to setup an incoming webhook from https://gitlab.arm.com/. 

## Actual Result

I tried the following:
* GitLab integration: the setup fails because I'm not trying to setup a repo linked to a gitlab.com account, https://gitlab.arm.com/ is a self-managed instance.
* Generic API incoming webhook: this fails because there is no way to pass the "token" header in the POST request. The gitlab UI to setup the webhook is very basic and allows no customization of the request.

What would be required to make the thing work is simply to display the token in the settings of the Gitlab incoming webhook, so that it can be set manually in gitlab UI in the "Secret token" field, rather than 100% relying on the account linking.

For now I found a hack that works but I guess it could stop working any time:
* I created a Gitlab incoming webhook and used its endpoint URL in gitlab settings
* I created a generic API incoming webhook and used its token in gitlab settings

This frankenstein setup seems to work as readthedocs now properly looks for the token in X-Gitlab-Token since its an endpoint configured for gitlab integration, and the token is a valid token (even though not associated with that specific endpoint)

**Comment by stsewd** [comment]
Hi, you should be able to use your self-hosted instance by manually creating a gitlab integration from rtd admin and using that URL on your gitlab instance.

https://readthedocs.org/dashboard/lisa-linux-integrated-system-analysis/integrations/

**Comment by douglas-raillard-arm** [comment]
Indeed thanks @stsewd I don't know how I missed that. The secret token is not necessary when setting up a gitlab integration, thanks.
