### ISSUE TITLE
"Forgot password" sends same token repeatedly -- only worked on Chrome incognito

### ISSUE THREAD

**Issue by jzohrab** [readthedocs/readthedocs.org#8745]
## Details

On the sign-in page, clicking reset takes me to https://readthedocs.org/accounts/password/reset/.  When I enter my email, I get the same token every single time, eg:

https://readthedocs.org/accounts/password/reset/key/SAME-KEY-REPEATEDLY/

and when I click that I get the message

`Bad Token - The password reset link was invalid, possibly because it has already been used. Please request a new password reset.`

When I request a new reset, I get the same token.

I then finally tried to do the same thing through incognito, and copy/pasted the link to the incognito window, which worked.

Not sure if I was doing something wrong, or if something needed a few sentences of documentation.

Cheers and thanks! jz

**Comment by humitos** [comment]
We weren't able to replicate this issue. Are you still having this problem? If so, please feel free to re-open the issue.
