### ISSUE TITLE
Documentation Marked as Spam

### ISSUE THREAD

**Issue by drneavin** [readthedocs/readthedocs.org#8750]
## Details

* Read the Docs project URL: https://demultiplexing-doublet-detecting-docs.readthedocs.io/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable): drneavin

## Expected Result

My readthedocs doumentation was working previously but has suddenly been marked as spam - am unsure the reason why.

## Actual Result
This is what I see when I go to my documentation:
<img width="641" alt="Screen Shot 2021-12-08 at 12 15 41 pm" src="https://user-images.githubusercontent.com/44268007/145133697-84dce999-5610-4322-a99a-e630e5f33fdd.png">

Any help to fix this and prevent it from happening in the future would be much appreciated.

Thanks for your help!

**Comment by stsewd** [comment]
@drneavin sorry about that, looks like you user was banned by mistake, I have unbanned you.
