### ISSUE TITLE
Handle build restarts cleaner

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#8754]
This might be a dupe, I know we've discussed this a few times.

In the case that a build restarts, or is terminated due to an event like server scale in, build commands are recorded again, and usually out of order. We could reset previously executed commands on the build pretty easily, however it might also make sense to add some state somewhere for the Build object. For instance, perhaps some state on Build that specifies this is a build that was restarted? Or the number of retries (we probably only want to retry 2 or 3 times perhaps)?

The second part of this issue is that fact that builds can be interrupted -- and usually this is long running builds too, so the failure can continue to cascade for multiple attempts, until there are no servers left to scale in or there is a break in scaling to allow the server to exist for the full build length. This may require something like a pre-build activation of scale in protection to avoid interrupted builds.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_33knb)

**Comment by humitos** [comment]
Related issue reported by @astrojuanlu at https://github.com/readthedocs/readthedocs-corporate/issues/1234
