### ISSUE TITLE
 ModuleNotFoundError: No module named 'setuptools._distutils'

### ISSUE THREAD

**Issue by tshasc** [readthedocs/readthedocs.org#8778]
I am seeing an error due to setuptools, I wonder if somebody can help me with this.

bazel query rdeps(//..., :BUILD)
2021-12-21 08:20:46 UTC Running native bazel
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
INFO: Call stack for the definition of repository 'rules_proto_grpc_py3_deps' which is a pip_import (rule definition at /home/jenkins/Company/Dev/.cache/_bazel_root/be7cf4075b37cc68d311c9dca9bf0dbb/external/rules_python/python/pip.bzl:44:14):
 - <builtin>
 - /var/lib/jenkins/workspace/Organization/Presubmit/job/WORKSPACE:283:1
ERROR: An error occurred during the fetch of repository 'rules_proto_grpc_py3_deps':
   pip_import failed: Collecting grpcio==1.25.0 (from -r /home/jenkins/Company/Dev/.cache/_bazel_root/be7cf4075b37cc68d311c9dca9bf0dbb/external/rules_proto_grpc/python/requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/50/f7/4c124f7576f427f55566825f9f30082adc89414f85443c531a1815508d6b/grpcio-1.25.0-cp37-cp37m-manylinux1_x86_64.whl
  Saved ./grpcio-1.25.0-cp37-cp37m-manylinux1_x86_64.whl
Collecting grpclib==0.3.1 (from -r /home/jenkins/Company/Dev/.cache/_bazel_root/be7cf4075b37cc68d311c9dca9bf0dbb/external/rules_proto_grpc/python/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/2b/35/dbe0afb8bab692fa31118c0597188813590c1fdda3fcc57c056a208a7aed/grpclib-0.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/tmp95vumc87/setuptools-tmp/setuptools/__init__.py", line 5, in <module>
        import distutils.core
      File "/home/jenkins/.local/lib/python3.7/site-packages/_distutils_hack/__init__.py", line 83, in create_module
        return importlib.import_module('setuptools._distutils')
      File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
    ModuleNotFoundError: No module named 'setuptools._distutils'

*A description of what actually happened*

**Comment by humitos** [comment]
Hi @tshasc! I think this is a dup of #8775 (*). Are you using `use_system_site_packages` option? In that case, I'm curious about the reason behind using that option 😄 

In any case, can you try disabling that option for now? I think that should fix the problem.

(*) please, take a look at the discussion there as well.

**Comment by astrojuanlu** [comment]
Also, this seems to come from a local Jenkins deployment, so it definitely has nothing to do with Read the Docs. Closing.
