### ISSUE TITLE
Broken links in README file

### ISSUE THREAD

**Issue by dogukanteber** [readthedocs/readthedocs.org#8784]
Links in the 'Get in Touch' and 'Contributing' sections of the README file are broken. They seem to redirect to https://docs.readthedocs.io/en/latest/contribute.html.

**Comment by astrojuanlu** [comment]
Thanks for reporting @dogukanteber ! I see that we missed some redirections after #8751. Addressing that shortly.

**Comment by astrojuanlu** [comment]
Hmmm weird. We do have those redirects:

![Screenshot 2021-12-22 at 07-12-05 Edit Redirects Read the Docs](https://user-images.githubusercontent.com/316517/147091410-a2589ebc-e0e7-4bfc-af31-7daee628d9ad.png)

But I get weird behavior:

- https://doc.readthedocs.io/page/contribute.html is redirecting me to https://doc.readthedocs.io/fr/latest/contribute.html
- https://docs.readthedocs.io/en/latest/contribute.html is _not_ redirecting me to https://dev.readthedocs.io/en/stable/contribute.html
- Same happens with roadmap and code-of-conduct

**Comment by astrojuanlu** [comment]
I think this was a bad use of redirects. Fixed now 👍🏽
