### ISSUE TITLE
Embed video/youtube ?

### ISSUE THREAD

**Issue by PowerKiKi** [readthedocs/readthedocs.org#879]
Hello,

I am quite new to readthedocs.org and the whole Sphinx thing. And I was wondering if you ever considered supporting embedding video in the docs ? It seems that it could benefit many people, including [readthedocs itself](https://docs.readthedocs.org/en/latest/getting_started.html?highlight=screencast).

It seems that http://countergram.com/youtube-in-rst would be a starting point. But I honestly have no idea how/where this should be integrated, or even if this is a good idea.

I would really appreciate if you could give me a few pointers on how to achieve this. And please forgive me if I am talking non-sense.

**Comment by YoungxHelsinki** [comment]
I had to put "https:~~" for youtube url.

**Comment by asottile** [comment]
I also added `margin-bottom: 2em;` to the `<div>` as I have content directly after the video
