### ISSUE TITLE
Enable no shallow clone (DONT_SHALLOW_CLONE) for setuptools-git-versioning

### ISSUE THREAD

**Issue by dolfinus** [readthedocs/readthedocs.org#8798]
## Details

* Read the Docs project URL: https://setuptools-git-versioning.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/setuptools-git-versioning/builds/15693350/
* Read the Docs username (if applicable): dolfinus

## Expected Result

`setuptools-git-versioning` is a library which allows to generate project version using git tags and commits history.

It is expected that documentation will be generated with version number like `1.7.4.post76+git.91212162`.
To do this, library need all the tags to be present in the local git repo.

## Actual Result

Due to shallow copy of the repo (#5031), all tags are missing, and library version is always 0.0.1.

Please disable shallow copy for setuptools-git-versioning

**Comment by stsewd** [comment]
Done https://readthedocs.org/projects/setuptools-git-versioning/builds/15702008/!

**Comment by dolfinus** [comment]
Thank you!
