### ISSUE TITLE
[India] Ethical Ads do not load, failing with `Placement is configured with invalid parameters.`

### ISSUE THREAD

**Issue by pradyunsg** [readthedocs/readthedocs.org#8799]
Tried on:

- https://docs.readthedocs.io/en/stable/
- https://furo.readthedocs.io/en/stable/
- https://pip.pypa.io/en/stable/

I noticed this while trying to get ads loading locally, as part of working on https://github.com/pradyunsg/sphinx-basic-ng/issues/12.

Platform: Firefox 95.0.2 / Safari 15.2 / Chrome 96 on MacOS

**Comment by stsewd** [comment]
They do work for me, tested on firefox and chromium, not sure what could be happening that doesn't load for you.

**Comment by pradyunsg** [comment]
Here's a screenshot:

<img width="1440" alt="Screenshot 2022-01-06 at 20 56 51" src="https://user-images.githubusercontent.com/3275593/148406886-d5886bb5-07fc-447f-bd46-82c6d923e301.png">

Based on this comment:

https://github.com/readthedocs/ethical-ad-client/blob/005cde6b67c8b3d4126760c7e755aa5b65ad94dc/index.js#L424

It seems that this can also happen when there's no ad to show. I'm in India, which *may* have a role to play? Could you share a single ad ID for me to use (maybe the ReadTheDocs ad or something) to use with [`data-ea-force-ad`](https://ethical-ad-client.readthedocs.io/en/latest/#configuration)?

**Comment by pradyunsg** [comment]
> It seems that this can also happen when there's no ad to show.

Yup, sounds about right. The JSONP response here was: `ad_1641483214329_436596({});`

**Comment by stsewd** [comment]
I have connected to my VPN using an IP from India, I was able to replicate this.

**Comment by davidfischer** [comment]
I'm almost certain this is just a bad error message when there's no ad to show. We should have a different one. I'll prioritize https://github.com/readthedocs/ethical-ad-client/issues/26.

**Comment by pradyunsg** [comment]
Is there any way for me to force an ad to be shown?

**Comment by technotip** [comment]
I'm getting the same error message on my website. I was getting almost 90% fill rate till last month, but now I'm getting this error message "Placement is configured with invalid parameters" most of the time.

**Comment by pradyunsg** [comment]
Closing this, since this is basically a duplicate of https://github.com/readthedocs/ethical-ad-client/issues/26. Let's consolidate discussion over to that issue.
