### ISSUE TITLE
Graphviz dot files stopped being converted to png

### ISSUE THREAD

**Issue by fniessink** [readthedocs/readthedocs.org#8800]
Recently, Graphviz dot files in the documentation of Quality-time (https://quality-time.readthedocs.io/en/latest/) stopped being converted to png images on RTD. Running sphinx locally works fine, and the dot files are converted to png as expected.

This version of the docs, created Jan 2, 2022, has the dot files converted: https://quality-time.readthedocs.io/en/v3.31.0-rc.4/software.html. 

This version of the docs, created Jan 6, 2022, has the dot files not being converted: https://quality-time.readthedocs.io/en/v3.31.0-rc.5/software.html. Instead, the text of the dot file contents are displayed.

The only documentation-related dependency updated between these two dates in the Quality-time project was furo (bumped from 2021.11.23 to 2022.1.2), but reverting furo did not solve the issue.

## Details

* Read the Docs project URL: https://readthedocs.org/projects/quality-time/
* Build URL (if applicable): https://readthedocs.org/projects/quality-time/builds/15701306/
* Read the Docs username (if applicable): fniessink

## Expected Result

Graphviz dot files being converted to png and being displayed.

Docs with converted dot file: https://quality-time.readthedocs.io/en/v3.31.0-rc.4/software.html

## Actual Result

The text of the dot file is shown instead of the png image. 

Docs without conversion of dot file: https://quality-time.readthedocs.io/en/v3.31.0-rc.5/software.html

**Comment by stsewd** [comment]
Hi, looks like the config file was updated to make use of the new builder option https://github.com/ICTU/quality-time/commit/cbfed802e7dfe8ea4802a759da31c397db91065b#diff-03efc769b870804394632e45d7885272b44c16939517fb31c9d7c614d2ffae57, the new builders don't include several pre-installed packages like the older ones, you must install them with https://docs.readthedocs.io/en/stable/config-file/v2.html#build-apt-packages. I think you only need to install the `graphviz-dev` and/or `libgraphviz-dev` packages.

**Comment by fniessink** [comment]
Thanks so much, installing `graphviz` did the trick. This is how the `build` part of the `.readthedocs.yaml` now looks:

```yaml
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz
```
