### ISSUE TITLE
Build failed with no global changes

### ISSUE THREAD

**Issue by EDI-N** [readthedocs/readthedocs.org#8807]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/docs-ua/builds/
* Build URL: all new builds
* Read the Docs username: EDI-N
* Requirements: https://github.com/EDI-N/Docs_ua/blob/master/docs/requirements.txt

Hello, for some reason all new builds falls with sphinxcontrib-contentui block errors (as I can understand). Sphinxcontrib-contentui doesn't changed so maybe something changed in your builder? Please, help me in resolving those issue

**Comment by astrojuanlu** [comment]
This is the error:

```
Obtaining sphinxcontrib-plantuml from git+git://github.com/sphinx-contrib/plantuml.git#egg=sphinxcontrib-plantuml (from -r docs/requirements.txt (line 5))
  Cloning git://github.com/sphinx-contrib/plantuml.git to /home/docs/checkouts/readthedocs.org/user_builds/docs-ua/envs/latest/src/sphinxcontrib-plantuml
  Running command git clone --filter=blob:none -q git://github.com/sphinx-contrib/plantuml.git /home/docs/checkouts/readthedocs.org/user_builds/docs-ua/envs/latest/src/sphinxcontrib-plantuml
  fatal: remote error:
    The unauthenticated git protocol on port 9418 is no longer supported.
  Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
```

I think you will have to change this line:

```
-e git://github.com/sphinx-contrib/plantuml.git#egg=sphinxcontrib-plantuml
```

to

```
-e git+https://github.com/sphinx-contrib/plantuml.git#egg=sphinxcontrib-plantuml
```

I tested this locally and it works. Can you confirm?

**Comment by EDI-N** [comment]
Yep seems that was wrong lines in requirements
Thank you)
