### ISSUE TITLE
Build error with build id #15748567

### ISSUE THREAD

**Issue by colinoflynn** [readthedocs/readthedocs.org#8810]
## Details:

* Project URL: https://readthedocs.org/projects/chipwhisperer/
* Build URL(if applicable): https://readthedocs.org/projects/chipwhisperer/builds/15748567/
* Read the Docs username(if applicable): coflynn

## Expected Result

* Build passes or fails with errors

## Actual Result

* Build fails, no obvious error.

Output looks like (shortened):

```
Read the Docs build information
Build id: 15748461
Project: chipwhisperer
Version: latest
Commit: 3d99ee5a392c98d9c9334e5c39ea634886d72242
Date: 2022-01-12T12:06:31.188114Z
State: finished
Success: False


[rtd-command-info] start-time: 2022-01-12T12:08:39.462634Z, end-time: 2022-01-12T12:09:05.753683Z, duration: 26, exit-code: 0
git clone --no-single-branch --depth 50 https://github.com/newaetech/chipwhisperer .
Cloning into '.'...
Checking out files:  13% (1277/9564)   
... lines removed ...
Checking out files:  99% (9529/9564)   
Checking out files: 100% (9564/9564)   
Checking out files: 100% (9564/9564), done.

[rtd-command-info] start-time: 2022-01-12T12:09:05.960685Z, end-time: 2022-01-12T12:09:06.752633Z, duration: 0, exit-code: 0
git checkout --force origin/develop
Note: checking out 'origin/develop'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 3d99ee5a Update .readthedocs.yaml

[rtd-command-info] start-time: 2022-01-12T12:09:07.048648Z, end-time: 2022-01-12T12:09:07.256940Z, duration: 0, exit-code: 0
git clean -d -f -f
```

The last passing build had the `git submodule sync` command which happens after the `git clean`:

```
[rtd-command-info] start-time: 2021-11-02T21:02:28.135418Z, end-time: 2021-11-02T21:02:28.229938Z, duration: 0, exit-code: 0
git submodule sync
```

But I'm not sure where the issue came from. Here is the [readthedocs.yaml](https://github.com/newaetech/chipwhisperer/blob/develop/.readthedocs.yaml) file. I did make some changes to try and troubleshoot without luck (chage python version, remove explicit image specification on build)

I've also hit the 'wipe build env' button to confirm that doesn't do anything to fix it. Not entirely sure what I broke but appreciate any insight!

**Comment by humitos** [comment]
I found a log in our server containing this error:

```
AttributeError: 'Tree' object has no attribute '_name'
```

I think we already had this issue before and it was a problem with `gitpython` package on particular git repositories. I will need to take a look at some history probably. @stsewd do you remember this problem?

**Comment by humitos** [comment]
Here it is the issue that I remembered #4371

**Comment by colinoflynn** [comment]
Ah thanks for the note @humitos - let me check our submodules config, I wasn't thinking that error would get hidden. Could have introduced a problem there, gives me something to check now.

**Comment by colinoflynn** [comment]
Adding:

```
submodules:
  exclude: all
```

Fixed this - we had submodules for part of the project only before, I'm not sure it's still needed. Closing for now as the general problem is solved immediately & will see if we actually need anything that triggers a problem.

**Comment by stsewd** [comment]
This is mostly to having submodules that aren't on the repository anymore https://github.com/newaetech/chipwhisperer/blob/develop/.gitmodules, like openadc.
