### ISSUE TITLE
OSError: File does not exist: staticfiles.json - Dev Install

### ISSUE THREAD

**Issue by Lowe-Man** [readthedocs/readthedocs.org#8812]
## Details

* Read the Docs project URL: **N/A**
* Build URL (if applicable): **N/A**
* Read the Docs username (if applicable): **N/A**

## Expected Result

Show the http://community.dev.readthedocs.io/ local site and allow you to login and generate docs.

## Actual Result

![Screenshot 2022-01-14 002309](https://user-images.githubusercontent.com/12134329/149456476-6e2d0d65-9d7b-4880-b798-1ee74985870c.png)

This error also shows up when you try to go to http://community.dev.readthedocs.io/ but in the form of a nicely formatted django error with details about it.

**Comment by humitos** [comment]
Hi! Did you follow the steps from https://docs.readthedocs.io/en/latest/development/install.html? Are you using the latest commit from `master` branch of this repository?

I'm not able to reproduce your error locally by following the steps from that link. We may need more debugging information to be able to trace down your error.

**Comment by soika1978** [comment]
Same with me on latest/master release, fallback to 6.3.3 works.
Followed all step as per https://docs.readthedocs.io/en/latest/development/install.html

**Comment by Lowe-Man** [comment]
Yes I used the latest commit from the master branch and followed https://docs.readthedocs.io/en/latest/development/install.html

**Comment by Lowe-Man** [comment]
> Hi! Did you follow the steps from https://docs.readthedocs.io/en/latest/development/install.html? Are you using the latest commit from `master` branch of this repository?
> 
> I'm not able to reproduce your error locally by following the steps from that link. We may need more debugging information to be able to trace down your error.

Yes I used the latest commit from the master branch and followed https://docs.readthedocs.io/en/latest/development/install.html

**Comment by humitos** [comment]
Hi! I was able to reproduce this by deleting my local Docker volumes. I solved this problem in https://github.com/readthedocs/readthedocs.org/pull/8853

Please, let me know if it works for you! Thanks for reporting this issue.
