### ISSUE TITLE
RTD shows part of the API pages 

### ISSUE THREAD

**Issue by afergadis** [readthedocs/readthedocs.org#8814]
## Details

* Read the Docs project URL: https://irrcac.readthedocs.io/en/latest/index.html
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

The generated page does not have the documentation of *some* of the modules in the package.

## Actual Result

For the API documentation I have run sphinx-apidoc. This produced an [irrCAC.rst](https://github.com/afergadis/irrCAC/blob/master/docs/source/irrCAC.rst) file pointing to the modules in my package. In my local directory, the produced page shows the documentation from all packages. The page in RTD shows the documentation of *some* of the modules. In the following screenshot, you can see the difference where the `irrCAC.benchmark module` is empty in the left (RTD) while the locally produced page on the right describes a class.
![screen-diff](https://user-images.githubusercontent.com/5690874/149535740-b64a606c-d88d-41cb-8a0e-a03cba1bf4cb.png)

Inspecting the generated source from the two pages (part of the diff below), I see that the `href` produced by RTD for three of the modules is wrong (the *left text* is from the local page and the *right text* from RTD). Those three are the ones that miss the documentation. Specifically, the `href` anchors produced for the benchmark module is `irrcac-bencmark-module` instead of the correct `module-irrCAC.benchmark`. The other two erroneous links are for the `raw` and `table` models. However, the links for `datasets` and `weights` are correct. 
![image](https://user-images.githubusercontent.com/5690874/149536415-c8c2d95f-10bf-47c3-85b1-c0510e30ce78.png)

In the following link you can see the full diff: [Local vs RTD source](https://www.jstoolset.com/diff/9d2174eb2045c798)

**Comment by humitos** [comment]
Hi! On your build page, there is a warning saying that it could not import your module due to a missing dependency:

```
WARNING: autodoc: failed to import module 'benchmark' from module 'irrCAC'; the following exception was raised:
No module named 'scipy'
WARNING: autodoc: failed to import module 'raw' from module 'irrCAC'; the following exception was raised:
No module named 'scipy'
WARNING: autodoc: failed to import module 'table' from module 'irrCAC'; the following exception was raised:
No module named 'scipy'
```

(from https://readthedocs.org/projects/irrcac/builds/15739382/)

You will need to add `scipy` to the requirements. Let me know if that works.

**Comment by afergadis** [comment]
Yes, that did work!
I saw that the build passed and didn't check the raw output.
Thank you.
