### ISSUE TITLE
Build not triggered on PR

### ISSUE THREAD

**Issue by elParaguayo** [readthedocs/readthedocs.org#8819]
## Details

* Read the Docs project URL: http://docs.qtile.org
* Build URL (if applicable):
* Read the Docs username (if applicable): elParaguayo

## Expected Result

I recently changed the settings so that our docs should be built on a new pull request. My understanding was this would then provide a status message in the pull request's checks to show whether or not the build was successful but I don't see this happening. See https://github.com/qtile/qtile/pull/3209 for an example.

## Actual Result

No build triggered and no status message in GitHub checks.

**Comment by humitos** [comment]
Hi! If you enable the PR builder _after_ creating the PR in your project, it won't trigger builds for that PR. I don't remember the exact implementation of this, but maybe if you push a commit to that PR now it may be caught by Read the Docs and trigger a build.

What happens if you open a _new_ PR request now? Does RTD trigger a build for it?

**Comment by elParaguayo** [comment]
Thanks for the quick reply. 

It's failed to trigger on new PRs too. Here's another: https://github.com/qtile/qtile/pull/3214

**Comment by humitos** [comment]
Does any of the maintainers of the RTD project have their GitHub account connected to RTD? Does any of them have `write` permissions on the GitHub repository? Take a look at this section of the documentation https://docs.readthedocs.io/en/stable/pull-requests.html#troubleshooting

**Comment by elParaguayo** [comment]
I am a maintainer of the qtile RTD project. 
My github account is connected to RTD.
![connected](https://user-images.githubusercontent.com/946265/149934039-19b502e8-3869-455c-84fa-bac5d5823b8d.png)

I have write permissions on the qtile Github repository.
ReadTheDocs has oauth access to my personal account and qtile allows access to anything that I've granted access to.

**Comment by elParaguayo** [comment]
Closing this as it seems to be working now. Thanks for your help!

**Comment by humitos** [comment]
Can you expand about what was the reason? Did you change anything? Thanks!

**Comment by elParaguayo** [comment]
Not entirely sure. I tried resyncing the webhooks (but I'd done that before). I then checked the integrations setting in GitHub and saw that the hook was due to be triggered on pull requests. I submitted a new PR and it just worked.

My guess is that the resyncing was the key step.
