### ISSUE TITLE
How to add extra files using a sphinx extention ? 

### ISSUE THREAD

**Issue by 12rambau** [readthedocs/readthedocs.org#8825]
> I don't like my title but it's complicated to set everything in a 1-liner....

## Details

* Read the Docs project URL:https://readthedocs.org/projects/sphinx-icon/
* Build URL (if applicable): https://sphinx-icon.readthedocs.io/en/latest/
* Read the Docs username (if applicable): borntobealive

## Expected Result

I'm building a sphinx extension to add a `:icon:` role based on fontawesome5 icon list. It's a nice exercise and I hope it will be useful eventually. The extension code is here: https://github.com/12rambau/sphinx-icon. 

The idea is pretty simple, identify the icon, verify if it's existing in the fontawesome metadata file and if yes, use a `<i>` tag in the html output and a `\FaIcon` command in the latex one. other types are not supported. 

To work I need to add extra files in the output like the css and js fontawesome files. It is done here: https://github.com/12rambau/sphinx-icon/blob/05eed2d20515ecb394b232a8d6128a13c3c7b432/sphinxcontrib/icon/font_handler.py#L18

It creates an extra `_font` folder containing everything I need in the output folder. Locally, everything works fine but in RDT the file https://sphinx-icon.readthedocs.io/home/docs/checkouts/readthedocs.org/user_builds/sphinx-icon/checkouts/latest/docs/source/_build/html/_font/fontawesome/css/all.min.css cannot be accessed. Is it even created ? 

If yes why cannot I access it ?    
If no what is the process I should follow to make the file accessible ? 

## Actual Result

As it cannot be accessed, the icon is obviously not displayed in the rendered html

**Comment by humitos** [comment]
Hi @12rambau! I took a quick look at the code and also at the build output. I didn't find anything too obvious about what could not be working. I'd recommend you add some log lines in the sphinx extension to be able to debug it.

In theory, Read the Docs does not do anything special for this case, so I'm not sure how this would be related to Read the Docs. Logging may help to understand the problem and if it's related to RTD or not.

**Comment by 12rambau** [comment]
I don't really see what log could be added from my side. Before I do can you just confirm that the folder `_font` is created in `_build` and that it's not empty ?

**Comment by TheTripleV** [comment]
In your code, I don't see an addition to the html static path. I believe this is may be used to determine which files are copied/published.

A few examples in the wild:
sphinxext-presentations: https://github.com/wpilibsuite/sphinxext-presentations/blob/main/sphinxext/presentations/__init__.py#L9-L12
sphinx-panels: https://github.com/executablebooks/sphinx-panels/blob/4a310ebb0f2ba358a5ab08db07c3b9afbeb2bb96/sphinx_panels/__init__.py#L54-L56

**Comment by 12rambau** [comment]
I didn't realized that not only the file needed to be added to the folder but also to the app static path, thanks for the insight.
I corrected it in https://github.com/12rambau/sphinx-icon/commit/1f09fcb12809808595e4e8a1fdae6a2f7f3e18cc and now it runs as expected.
