### ISSUE TITLE
extra package make latex build crash

### ISSUE THREAD

**Issue by 12rambau** [readthedocs/readthedocs.org#8826]
## Details

Read the Docs project URL:https://readthedocs.org/projects/sphinx-icon/
Build URL (if applicable): https://sphinx-icon.readthedocs.io/en/latex/
Read the Docs username (if applicable): borntobealive

## Expected Result

I'm building a sphinx extension to add a `:icon:` role based on fontawesome5 icon list. It's a nice exercise and I hope it will be useful eventually. The extension code is here: https://github.com/12rambau/sphinx-icon.

The idea is pretty simple, identify the icon, verify if it's existing in the fontawesome metadata file and if yes, use a `<i>` tag in the html output and a `\FaIcon` command in the latex one. other types are not supported.

To work I need to add an extra package to my `preamble`:  "\\usepackage{fontawesome5}"  
(https://github.com/12rambau/sphinx-icon/blob/0de1c314216351c2c86541ae4edd3f67d12605c1/sphinxcontrib/icon/icon.py#L81) 

When I 'm building the doc locally, everything works fine but in the RDT build, latex fails with error messages that I don't understand. 

> Rule 'pdflatex': Rules & subrules not known to be previously run:
   pdflatex

Have you ever faced this issue and if it's related to my package how should I add it ? 

## Actual Result

Latex build fails

**Comment by astrojuanlu** [comment]
Hi @12rambau ! I think the relevant error is this one:

```
! LaTeX Error: Unknown graphics extension: .svg.
```

perhaps you need an extra package in [`build.apt_packages`](https://docs.readthedocs.io/en/stable/config-file/v2.html#build-apt-packages) for this to work?

**Comment by 12rambau** [comment]
Ok my bad I was experimenting on something else. I removed the badges from `index.rst` which solved this first issue. Now I'm back on the error I didn't understand: 

> mktexpk: don't know how to create bitmap font for fa5free0solid.
mktexpk: perhaps fa5free0solid is missing from the map file.
kpathsea: Appending font creation commands to missfont.log.

it seems related to the package I'm using: [`\usepackage{fontawesome5}`](https://www.ctan.org/pkg/fontawesome5), what modification should I make to make it available ?

**Comment by astrojuanlu** [comment]
After searching around a bit, I think this is your problem: https://tex.stackexchange.com/a/497798/2488

I am not sure if this would be fixed by upgrading from Ubuntu 18.04 to Ubuntu 20.04. Can you try adding a `build.os` and `build.tools` as explained in [our blog](https://blog.readthedocs.com/new-build-specification/) and [docs](https://docs.readthedocs.io/en/latest/config-file/v2.html#build-os) to see if the problem persists?

Alternatively, that link gives a workaround of a command that must be run before generating the PDF.

**Comment by 12rambau** [comment]
Congratulation @astrojuanlu for finding this post, I should go on tex.stackexchange.com more often! 
Changing the build os to 20.04 solved it. I prefer this solution to the one with the extra command, it's easier to setup .
