### ISSUE TITLE
Enable no shallow clone (DONT_SHALLOW_CLONE) for mlflow-client

### ISSUE THREAD

**Issue by dolfinus** [readthedocs/readthedocs.org#8829]
## Details

* Read the Docs project URL: https://mlflow-client.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/mlflow-client/builds/15840813/
* Read the Docs username (if applicable): dolfinus

## Expected Result

It is expected that `mlflow-client` documentation will be generated with version number like `2.0.0.dev123`.
To do this, library need all the tags to be present in the local git repo.

## Actual Result

Due to shallow copy of the repo (#5031), all tags are missing.

Please disable shallow copy for mlflow-client

**Comment by humitos** [comment]
Done! Let us know if everything works as you expected 👍🏼

**Comment by dolfinus** [comment]
Thank you!
