### ISSUE TITLE
Enable no shallow clone (DONT_SHALLOW_CLONE) for mlflow-rest-client

### ISSUE THREAD

**Issue by dolfinus** [readthedocs/readthedocs.org#8839]
## Details

* Read the Docs project URL: https://mlflow-rest-client.readthedocs.io/
* Build URL (if applicable): https://readthedocs.org/projects/mlflow-rest-client/builds/15874675/
* Read the Docs username (if applicable): dolfinus

## Expected Result

It is expected that `mlflow-rest-client` documentation will be generated with version number like `2.0.0.dev123`.
To do this, library need all the tags to be present in the local git repo.

## Actual Result

Due to shallow copy of the repo (#5031), all tags are missing.

Please disable shallow copy for mlflow-rest-client

Clones #8829 because I recreated project with another name

**Comment by astrojuanlu** [comment]
@dolfinus The flag is now enabled for your project! Please confirm that everything is working correctly, and don't hesitate to reach out if you have any other questions.

**Comment by dolfinus** [comment]
Thank you!
