### ISSUE TITLE
Start deprecating old VCS support

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#8840]
Currently, we support the following VCS in our platform:

- git (`git`)
- bazaar (`bzr`)
- mercurial (`hg`)
- subversion (`svn`)

I'd like to start a conversation about the possibility to deprecate the ones that are mainly _not used_. In particular, subversion. I went ahead and took some numbers from our platform to find out how much each of them is used:

### Number of projects using VCS

* git: 247,599
* hg: 1,773
* bzr: 1,765
* svn: 1,673

### Number of projects using VCS with a build in the last 30 days

* git: 14,141
* hg: 46
* svn: 31
* bzr: 12

### Number of projects using VCS with a successful build in the last 30 days

* git: 11,532
* hg: 37
* svn: 2
* bzr: 0

> Also note that I'm not discarding spam projects. So, these numbers are lower.

----

I'd propose to start removing `svn` (and probably `bzr` as well) from the UI to avoid new projects being imported using these VCS. Then, the next step would be to communicate projects that are not spam that we are deprecating support for the VCS they are using.

Also note that to select `svn` and/or `bzr` users have to import the project manually, which gives them a worse UX of the whole platform: manual import, manual webhook setup, etc.

This will allow us to not maintain features that almost nobody uses but consume our time in different ways.

> Edit: fix numbers that were wrong (missed a `DISTINCT` in the query)

**Comment by agjohnson** [comment]
It would be helpful to know *when* these projects were created as well. That is, were `bzr` and `svn` projects mostly created 5 years ago? Git is obviously the primary vcs, but I would guess that new projects are even *more* leaning towards git.

I'm :+1:  on deprecating support on `svn` and `bzr`. Slowly helps here: removal from the UI, then removing actual support in the backends. Though, given above, I doubt we get a lot of new projects coming in with either.

**Comment by humitos** [comment]
Notes from our meeting in January 😄 :
* Make a deprecation timeline (Remove from UI at this time?)
* Find projects to email (Valid build in last year) & email them
* Finally, deprecate/remove code

**Comment by agjohnson** [comment]
More notes: maybe it makes sense to scope this down to removing suggestions for bzr/hg in our docs, and point users to always use git. Code removal will be a ways out

**Comment by humitos** [comment]
I'm fine with removing this from the documentation as the first step. However, I think we are always pushing back on deprecating things properly with a hard final date. Finally, we end up with inconsistencies between our docs, our code, and what we want. I think we should start becoming more strict with deprecations, in particular with those that are not heavily used.

**Comment by agjohnson** [comment]
We could definitely add a bit more to the scope here. We get the most value here out of consistently pointing new users/projects to Git. The main point is that full removal and deprecation is going to be a fair amount of work and we won't get a whole lot of value out of this work.

As a big chunk of work, this doesn't yet have priority on our roadmap. But we can prioritize small steps in this direction more immediately.

Full deprecation and removal of this code will require UX/UI around unavailable VCS, contacting users, monitoring deprecation before code removal, etc. So, quite a lot considering we don't spend a lot of time with the code now anyways.

**Comment by humitos** [comment]
@agjohnson 

> But we can prioritize small steps in this direction more immediately.

We already have done this in our meeting from January https://github.com/readthedocs/readthedocs.org/issues/8840#issuecomment-1144879129


> Full deprecation and removal of this code will require UX/UI around unavailable VCS, contacting users, monitoring deprecation before code removal, etc

I'd expect that the new UX/UI does not support these old VCS at all.

On the other hand, having a hard date of removal/end support communicated to users removes the requirement of a "monitoring" step.

> So, quite a lot considering we don't spend a lot of time with the code now anyways.

I don't fully agree with this sentence. It's true that we don't touch this code too much, but simple things like #9424 require a lot more thinking, testing and QAing.

**Comment by agjohnson** [comment]
> We already have done this in our meeting from January

Yeah we had some direction on this from that meeting, but in our roadmap planning call, this felt like an issue that we should bump out a quarter as it didn't really align. But we did agree we should have something from this on our radar.

That said, I think we're just describing making "Make a deprecation timeline (Remove from UI at this time?)" a few discrete steps. We can prioritize some smaller actions first

> I'd expect that the new UX/UI does not support these old VCS at all.

Disallowing new project VCS choices could be another more immediate step.

> On the other hand, having a hard date of removal/end support communicated to users removes the requirement of a "monitoring" step.

Though we will want to watch things periodically either way, we can expect new inbound support as we start the deprecation. We probably won't be lucky enough to get away with just emailing users and then returning to delete the code, there's some lump of work in the middle.

> It's true that we don't touch this code too much, but simple things like https://github.com/readthedocs/readthedocs.org/pull/9424 require a lot more thinking, testing and QAing.

That's fair, there is work hiding here. At least for this next quarter, we hope to be touching the backend code less than we did in Q1/2, so this might not be a driving function of this change.

**Comment by humitos** [comment]
> It would be helpful to know _when_ these projects were created as well. That is, were `bzr` and `svn` projects mostly created 5 years ago?

This table shows the trending pretty well:

![Screenshot_2022-08-22_17-54-34](https://user-images.githubusercontent.com/244656/185965115-03f4f530-ad2b-4c52-9c50-1b789330d527.png)

> Screenshot from https://ethicalads.metabaseapp.com/question/238-projects-grouped-by-pub-date-month-and-vcs-type-success-build-in-last-year

This plot shows "projects with at least 1 success build in the last 12 months grouped by VCS type"

![Screenshot_2022-08-22_17-56-42](https://user-images.githubusercontent.com/244656/185965477-f2ddfe32-836c-411e-ac85-f0f84df86b62.png)

> Screenshot from https://ethicalads.metabaseapp.com/question/239-projects-vcs-types-with-a-success-build-in-last-year

**Comment by humitos** [comment]
Some notes from the meeting that I was able to write down. Feel free to edit them or add context, comments.

- soft deprecation
- remove mentions from `bzr` and `svn` from all the documentation
- keep the code around
- avoid projects to select `bzr` and `svn` in the UI or similar places

**Comment by ericholscher** [comment]
I think we could even get rid of hg in the docs and drop downs. I like simplifying to be able to just support git would dramatically improve a lot of our messaging.

**Comment by benjaoming** [comment]
> remove mentions from bzr and svn from all the documentation

Also "VCS"?

Normal git users don't go around saying "VCS" no more.. it's like VHS :)

We put "VCS" in a bunch of navigation labels, links and titles.. it's quite bad, I think people won't get what an entire core section of our feature list is about.

**Comment by ericholscher** [comment]
@benjaoming What would replace it?

**Comment by benjaoming** [comment]
In some cases "git" is enough, some cases it can work with "git platform". I'm not convinced that "git host", "git provider", "git system" or "git service" sound good.

**Comment by benjaoming** [comment]
@agjohnson 

Could a deprecation look like this?

1. Remove mentioning of bzr, hg and svn from documentation (or archiving them in a legacy section)
2. Once our new Policy for Supported Tools is added, then update it: https://github.com/readthedocs/readthedocs.org/pull/7859
3. Remove support of bzr, hg and svn from import wizard
4. Notify remaining projects
5. Finally remove build support and clean up code

I am asking because I'm interested in _how soon_ we can start to rename and simplify some of the current VCS articles, since they are going through some processing over the next weeks.

**Comment by agjohnson** [comment]
I think what we're talking about above is not doing 4 and 5. Doing all of the work to notify projects and break their usage will be a fair bit of work, and might be overall negative value too.

I know that having the VCS code around is still a bit of a liability. It would be great if we could version our build backend API in some fashion and disregard this code going forward. Perhaps if that is a possibility that would be the point in time to remove the code.

**Comment by benjaoming** [comment]
@agjohnson 

Sounds good - do you have any objections about moving forwards with the first item during the coming weeks? It's mostly about a move towards saying "git" rather than "VCS". Regarding _actual_ contents, we don't have much more than this VCS Support Matrix to remove: https://docs.readthedocs.io/en/stable/versions.html#version-control-support-matrix

**Comment by agjohnson** [comment]
> do you have any objections about moving forwards with the first item during the coming weeks?

Nope! It's something we have to do at some point. I would say you should dictate when it makes the most sense to change this, as you'll be changing the most around documentation and we should avoid derailing your refactor work with content changes as much as possible.

**Comment by benjaoming** [comment]
Great! The work has started here: https://github.com/readthedocs/readthedocs.org/pull/9675

**Comment by humitos** [comment]
We merged the PR that disallow other VCS that are not Git for new projects. Another step forward to accomplish with this issue 💪🏼

**Comment by benjaoming** [comment]
We're removing this one in https://github.com/readthedocs/readthedocs.org/pull/10186 - I think we are on a good track :)

![image](https://user-images.githubusercontent.com/374612/228059794-07083163-536a-416c-84a1-9044c888976c.png)

**Comment by benjaoming** [comment]
Two things that I noticed while working with the Git backend:

1) It would be great to get rid of the other backends (hg/bzr/svn) in order to start working on simplifications _after_ #10430

2) For the deprecation announcement, we can tell projects that export to Git, that they can **edit their repo URL** instead of creating a new project :bulb: I'm not sure that we can fully support all aspects of editing a repo URL from for instance hg to Git. However, I think we can encourage people to do this in order to keep all their old builds (and not lose their project slug to an automatic deletion). We should be able to pull _some_ tricks such that versions built and published with the previous VCS are kept. This may also be an option for a 5 year old project that doesn't intend to do new builds, needs to keep the old builds and wants to avoid getting deleted.

**Comment by ericholscher** [comment]
@benjaoming I'm not sure why we need to do anything specific when projects change their repo url to keep old versions? That should be the default behavior... Is there a benefit to deleting and re-creating the project vs. just changing the repo url that makes you think we'd suggest deletion?

**Comment by benjaoming** [comment]
@ericholscher if they _export_ their project from X to Git, then they might:

a) be correctly exporting tags and branches :heavy_check_mark: 
b) or they might _not_ export tags and branches :warning: 

If a), then I think we are safe, but it's only by skimming the code: If the export is fine and all tag and branch data has the same names as before, then it shouldn't matter that the commit hashes change.

If b), then I think our behavior is to auto-remove Versions that are no longer matched by any branch or tag? I think we have the Feature flag `SKIP_SYNC_VERSIONS` because of such issues?

**Comment by benjaoming** [comment]
@ericholscher I'm trying to summarize my understanding of how this looks from user POV. Does this draft make sense?

> We are deprecating support for SVN/Mercurial/Bazaar and focusing our efforts on Git.
>
> To continue building your project on Read the Docs, you will need to provide a Git repository.
>
> 1. Export your SVN/Mercurial/Bazaar project to a Git repository.
> 2. If your documentation has multiple versions, make sure that your tags and branches
>    are re-created in Git, as they will be matched with existing versions on Read the Docs.
> 3. Edit your Repository type and URL in your Project Admin
> 4. Save :heavy_check_mark: 
>
> After saving these changes, you can continue setting up automated builds with your Git provider by following these steps: https://docs.readthedocs.io/en/stable/guides/setup/git-repo-manual.html
> 
> In case your project has multiple versions that you need to either update or recreate, then you can re-build a specific version in your Project Admin's "Builds" section.

**Comment by humitos** [comment]
I don't think that people using SVN/Mercurial/Bazaar will do that. If they are using those VCS it's for a (good/bad) reason and they just don't want/can to use Git. So, telling them to export/convert their repository into Git just to use Read the Docs is a no-go, to me.

I think we just want to communicate these users that these VCS won't be supported in the future and if they want to use Read the Docs, they have to provide a Git repository with the documentation. Will they do that? How they do that? I think it's not our business 🤷🏼 

Pointing back to this comment again: https://github.com/readthedocs/readthedocs.org/issues/8840#issuecomment-1222558652. We have just a few projects (238, in total --some of them may be SPAM, testing/demo projects, or just invalid) using deprecated/unsupported VCS.

**Comment by ericholscher** [comment]
Agreed. I think we just alert these people, but we don't have to do any work or thinking about how they migrate. It's up to them to decide what is best for their project.

**Comment by humitos** [comment]
We have 6k _total_ affected projects (including spam and everything there). **I'm targeting the fully removal of the code for November 7th**. I've already started writing the email we will be sending to communicate this following the standard process we've been using for a deprecation like this one.

**Comment by ericholscher** [comment]
@humitos I know we discussed starting with bzr & svn, since hg is still somewhat used. Are you wanting to remove everything?

**Comment by humitos** [comment]
@ericholscher 

> I know we discussed starting with bzr & svn, since hg is still somewhat used. Are you wanting to remove everything?

I think it's worth removing everything at once, yes. We only have 236 Mercurial projects with a successful build in the last year; this includes spam and other invalid projects. So, it's just a few amount of projects.

Besides, we are usually "not thinking about other VCSs that are not Git" when working on the product, so I don't think it makes too much sense to keep Mercurial in a half-backed support any longer. Don't removing it now together with the other unsupported VCSs is just pushing the problem to the future since we are not thinking about those users anyways, IMHO.

**Comment by ericholscher** [comment]
@humitos That's a reasonable argument, but I do imagine there will be real users who will complain pretty heavily about this change, so we need to be ready for that to happen. I'm not sure how many active projects we're willing to kick off for this, but I do think it's a pretty big win in terms of simplifying our product, allowing us to completely remove the `vcs_type` field, and all the associated code abstractions, so it's likely worth a larger cost in terms of losing users.

**Comment by humitos** [comment]
I will start writing the email for the deprecation, then.

> That's a reasonable argument, but I do imagine there will be real users who will complain pretty heavily about this change, so we need to be ready for that to happen

What do you mean by "be ready" here? What do you have in mind? I assume this is just a "planned reply" explaining this decision. If that's the case, wouldn't the blog post be enough to them there?

**Comment by humitos** [comment]
I took a deeper look at those Mercurial projects.

```
In [8]: projects = Project.objects.filter(builds__date__gt=timezone.datetime(2022, 8, 9), repo_type='hg').distinct().order_by('slug')

In [14]: slugs = []
    ...: for p in projects:
    ...:     if spam_score(p) < 200:
    ...:         slugs.append(p.slug)
    ...: 

In [15]: len(slugs)
Out[15]: 327

In [19]: len([s for s in slugs if s.startswith('tryton')])
Out[19]: 202

In [20]: len(slugs)
Out[20]: 327

In [21]: 327 - 202
Out[21]: 125
```

* We have 327 projects in total that "are not spam"
* I took a closer look at those slugs and there are some of them that are spam 😄 
* There are other projects that their `/` returns 404
* 202 projects are related to Tryton (main server and desktop project plus different modules and translations)

I also took a look at the Business site and we have only 1 projects (Thunderbird Source Docs) with an active organization (Thunderbird).

**Comment by agjohnson** [comment]
Next up, we need to contact the users of Tryton, etc and get some feedback.

**Comment by humitos** [comment]
Here is the draft email that I wrote some time ago. We can use it as a starting point: https://hackmd.io/ZiEI9rbTSI651i71pPyxbw

**Comment by humitos** [comment]
I can send the email with that content this week probably, if we are 👍🏼 .

**Comment by ericholscher** [comment]
Sounds good. We should likely only send it to active projects using non-git VCS 👍

**Comment by humitos** [comment]
I sent the email:
* Community: 26 users / 290 projects
* Commercial: 7 users / 1 project

Let's see what's the feedback we receive from this.

**Comment by ericholscher** [comment]
Got 3 annoyed users, which seems like a small number in the scheme of things..

**Comment by AlbertMietus** [comment]
I don't understand this issue ...  
Yes, I know, I'm one of those "non-git" users; but that is only partly the point
BTW never got an email on this topic ... So the numbers above are wrong -- I probably am not the only one
Besides, It's kind of misleading to survey git on a git-fan website!

Anyhow, when we can vote: I would VOTE NO.
Not only because I have thought about which VCS I prefer ("not-git"), and I like to have the freedom to choose what is best for me/my projects. 
I think we, at least most of us, support "_open source"._ **Open**! That is the liberty to choose. Which IMHO opinion includes which VCS?

I can (kind of) understand that we sometimes need to remove existing functionality. 

- For example, when 'we' have to pay to support a VCS.
- Or, when it depends on non-maintained, bad, unsecured, ... 3rd party software
- Maybe even when supporting "less used" parts is very labour-intensive.
(Although, the latter is typical/often a symptom of a bad design)

When counting the numbers, roughly 2.5% of all projects use "non-git".  One can argue, that is a minority, but does that matter? 

ReadTheDocs is about "docs". Not about "the best VCS". As I stated, I don't understand the issue. IMHO there is no valid reason to exclude "others".

I don't like to believe this initiative is a kind of "git wants to rule the world by ignoring all others". Plz, do not make it look like that (asking for support on a git-site; ignore initial, old users, etc).

**Comment by ericholscher** [comment]
@AlbertMietus What is the project you have on RTD? I'd like to understand why we didn't email you.

**Comment by agjohnson** [comment]
A couple notes on next steps:

- Dates on brown outs and final cut off
- Blog posts and docs, email updates

**Comment by AlbertMietus** [comment]
> @AlbertMietus What is the project you have on RTD? I'd like to understand why we didn't email you. 

Currently, Only a few, small "doc only" ones.

See e.g.

https://readthedocs.org/projects/docideas/

**Comment by humitos** [comment]
[I started writing a blog post to communicate our decision](https://github.com/readthedocs/website/pull/264). It also has some potential workaround ideas for people that want to migrate their repositories to Git or keep using their VCS to build the docs on Read the Docs. I hope that helps.
