### ISSUE TITLE
emojis not rendered properly on PDF output

### ISSUE THREAD

**Issue by tomkralidis** [readthedocs/readthedocs.org#8841]
## Details

(via https://github.com/geopython/pygeoapi/issues/844 cc @maaattes)

Emojis used in HTML documentation do not render in the PDF so some parts lose their information.

* Read the Docs project URL: https://readthedocs.org/projects/pygeoapi/
  * PDF output: https://docs.pygeoapi.io/_/downloads/en/latest/pdf/ (see page 39 - screenshots also below)
* Read the Docs username (if applicable): https://readthedocs.org/profiles/tomkralidis

## Expected Result

Emoji's should render as per below:

![image](https://user-images.githubusercontent.com/910430/150971233-a94097ce-3ede-4c30-9f07-42bba0ac57d0.png)

## Actual Result

![image](https://user-images.githubusercontent.com/910430/150972115-3b630f46-07cb-462a-98fe-3161e0099167.png)

**Comment by astrojuanlu** [comment]
Hi @tomkralidis ! If you render the PDF locally, does it show the emojis?

- If so, this is a RTD issue
- If not, this is most likely a Sphinx issue https://github.com/sphinx-doc/sphinx/issues/

**Comment by tomkralidis** [comment]
Digging into the RTD build logs, I see a number of these at the PDF building stage:


```bash
latexmk -r latexmkrc -pdf -f -dvi- -ps- -jobname=pygeoapi -interaction=nonstopmode

<snip/>

! Package inputenc Error: Unicode char ✅ (U+2705)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1626 \end{tabulary}
                     

! Package inputenc Error: Unicode char ❌ (U+274C)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.1626 \end{tabulary}                                   
```

**Comment by humitos** [comment]
@tomkralidis where you able to build the PDF locally and check if it has the same problem?

**Comment by tomkralidis** [comment]
@humitos I'm able to reproduce the issue when running the workflow locally.  Will move to the Sphinx issue tracker.

**Comment by tomkralidis** [comment]
Reported to Sphinx issues at https://github.com/sphinx-doc/sphinx/issues/10171
