### ISSUE TITLE
Enable no shallow clone (DONT_SHALLOW_CLONE) for Black

### ISSUE THREAD

**Issue by JelleZijlstra** [readthedocs/readthedocs.org#8852]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/black/
* Build URL (if applicable): https://readthedocs.org/projects/black/builds/15896411/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/JelleZijlstra/

We're losing version information on Black because it's been more than 50 commits since the last release. Could you turn off shallow clones for us? (reference: #5031)

Thanks!

**Comment by ichard26** [comment]
For context we use setuptools-scm to automatically manage versions for us.

> We're losing version information on Black because it's been more than 50 commits since the last release.

Evidence we are past 50 commits: https://github.com/psf/black/compare/21.12b0...main ... we're coming close up to the next release :)

**Comment by humitos** [comment]
Done! Let me know if everything is OK!

**Comment by ichard26** [comment]
Thank you @humitos, it appears fixed now 🎉 https://readthedocs.org/projects/black/builds/15902046/
