### ISSUE TITLE
rtd tries to pull from master although main is specified

### ISSUE THREAD

**Issue by nschloe** [readthedocs/readthedocs.org#8859]
* Read the Docs project URL: https://readthedocs.org/projects/pygmsh/
* Build URL (if applicable): https://readthedocs.org/projects/pygmsh/builds/15912813/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/nschloe/

I would like to build the pygmsh docs from the `main` branch. The "default branch" is set correctly in the advanced settings:

![r1](https://user-images.githubusercontent.com/181628/151556772-75ce61d9-478a-464f-a8d2-92cc3a18fea9.png)

However, it still tries to pull from "master".

![r2](https://user-images.githubusercontent.com/181628/151556667-cf8cb440-eb07-4cce-8819-e3bc1552659a.png)

**Comment by humitos** [comment]
Hi @nschloe! Note that the "Default branch" setting you are defining applies to `latest` version on Read the Docs. However, from your build detail's page URL (https://readthedocs.org/projects/pygmsh/builds/15912813/) it seems you are building the `master` version, not `latest`.

I checked on an old build from your project of the `latest` version and it's building from `origin/main` as you want. Take a look at https://readthedocs.org/projects/pygmsh/builds/15912764/

**Comment by nschloe** [comment]
That's it, thank you!
