### ISSUE TITLE
'The Edit on GitHub' link error -- says page not found 

### ISSUE THREAD

**Issue by eleensmathew** [readthedocs/readthedocs.org#8860]
'The Edit on GitHub' link in https://docs.readthedocs.io/en/stable/ seems to be broken 
![broken link](https://user-images.githubusercontent.com/92302620/151581661-ec745144-90e9-4aa0-92ea-8e263a011408.png)

**Comment by stsewd** [comment]
Hi, this was already fixed in https://github.com/readthedocs/readthedocs.org/pull/8833, it should be live next week.
