### ISSUE TITLE
RtD's embed JS calls Sphinx's Search.init unnecessarily

### ISSUE THREAD

**Issue by pradyunsg** [readthedocs/readthedocs.org#8862]
## Details

* Read the Docs project URL: https://sphinx--10028.org.readthedocs.build/en/10028/
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): N/A

## Expected Result

Sphinx's search JS should only inject "Searching" once, but it calls it twice, resulting in an extra heading.

See https://sphinx--10028.org.readthedocs.build/en/10028/search.html?q=Hello

## Actual Result

Read the Docs' embed JS calls `Search.init` even when not using the server-side search. This means that Sphinx's search is triggered twice, resulting in multiple "Searching" prompts on the search result. This is reproducible on other documentation sets, using the current stable version of Sphinx.

**Comment by TimKam** [comment]
Also, see the (in particular) [this comment](https://github.com/sphinx-doc/sphinx/pull/10028#issuecomment-1025204395) and the ones that follow.

**Comment by stsewd** [comment]
Hi, we remove the `Sphinx.init` call from our custom extension, so we can call it when necessary. Seems like in the refactor, this was changed to be `_ready(Sphinx.init);`, so we need to update our extension to handle that. Will also look into the other error.
