### ISSUE TITLE
Hyphens Not Loading

### ISSUE THREAD

**Issue by reustle** [readthedocs/readthedocs.org#8863]
## Details

* Read the Docs project URL: https://procrastinate.readthedocs.io/en/stable/howto/django.html
* Build URL (if applicable): n/a
* Read the Docs username (if applicable): n/a

## Expected Result

Hyphens should show when wrapping words, but squares show instead.

## Actual Result

RTD is using `hyphens: auto` on paragraph tags in the body, but the character used for the hyphen doesn't seem to be loading and is showing as a square instead. I've checked the source code on the page, and of the source rst file ( https://raw.githubusercontent.com/procrastinate-org/procrastinate/main/docs/howto/django.rst ) and don't see any strange characters that could be causing this. I've got my adblock (ublock) turned off, too. Running the latest Chrome on the latest MacOS.

Alternatively, we remove `hyphens: auto` all together.

Thank you!

![image](https://user-images.githubusercontent.com/304560/151670512-30f7e245-6bf3-49f9-8c7f-9e6c502f9b7b.png)

**Comment by humitos** [comment]
Hi! If you build your documentation locally, are you able to reproduce this issue?

Also, note that going to the linked page, I can't reproduce your issue on Firefox. Hyphens look OK to me:

![Screenshot_2022-01-31_10-55-59](https://user-images.githubusercontent.com/244656/151773106-a99e7b52-1893-4274-9103-1d566e207cc5.png)

I'm not sure this is a problem on the Read the Docs side of the world 😄

**Comment by stsewd** [comment]
Hi, this looks like a bug on chrome, see https://github.com/bitprophet/alabaster/issues/187.

**Comment by hugovk** [comment]
The fixed Chrome 98 has now been released and I confirmed https://procrastinate.readthedocs.io/en/stable/howto/django.html looks good now (Monterey 12.2, Chrome Version 98.0.4758.80):

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/1324225/152693132-77ac9e2b-ac75-46a9-8231-81f77680a577.png">
