### ISSUE TITLE
Would compile my theme: pydata_sphinx_theme

### ISSUE THREAD

**Issue by rachna-lm** [readthedocs/readthedocs.org#8883]
I downloaded the pydata_sphinx_theme and have configured everything fine. Still it wouldnt compile. The error is below:

done
preparing documents... WARNING: unsupported theme option 'logo_only' given
WARNING: unsupported theme option 'display_version' given
WARNING: unsupported theme option 'sticky_navigation' given
done
writing output... [  1%] concepts/ABFP                                                                  
Theme error:
An error happened in rendering the page concepts/ABFP.
Reason: TemplateNotFound('navbar-logo.html')
make: *** [html] Error 2
rachna@rachnas-mbp idiom-docs %

**Comment by humitos** [comment]
Hi @rachna-lm! I'm not sure to follow how the command's output you are showing here is related to Read the Docs. Can you expand on that and what's the problem you are having on Read the Docs? Thanks,

**Comment by rachna-lm** [comment]
It is a theme issue which is provided by RTD. So therefore asked. 

Regards
-rachna

**Comment by humitos** [comment]
Hi @rachna-lm! We do not have control over this particular theme. So, I'd suggest you open an issue at https://github.com/pydata/pydata-sphinx-theme explaining your situation and clearly describing the problem you are facing. Thanks!

**Comment by rachna-lm** [comment]
Oh thanks!

Regards
-rachna
