### ISSUE TITLE
community server image has been removed or access denied

### ISSUE THREAD

**Issue by billmats96** [readthedocs/readthedocs.org#8885]
## Details

Hello! I am trying to build readthedocs using the steps for development installation as described in  Read the Docs project URL: https://dev.readthedocs.io/en/latest/install.html#set-up-your-environment

I get an error when running sudo inv docker.up --init (previous steps are all successful) 

```
Pulling proxito (community_server:latest)...
ERROR: The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing.

Continue with the new image? [yN]y
Pulling proxito (community_server:latest)...
ERROR: pull access denied for community_server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

## Expected Result

Docker images should be pulled and running

## Actual Result

Cannot find the images or access to them is denied. Alsp consider to check if other images face the same issue (postgres, redis, minio worked fine)

**Comment by humitos** [comment]
I'm not sure why `Pulling proxito (community_server:latest)...` message is shown. That image should be built locally after you run `inv docker.build`. Maybe you skipped that step by mistake?
