### ISSUE TITLE
Analytics: download data via API

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#8891]
A requested feature: the ability to automate exporting of the search/traffic analytics data. The user is automating this currently by iterating over projects returned through the project API, and then scripting login and download using the UI dashboard export button. This seems like something we could expose either with our API or could put an authentication method in front of the export function to allow scripting -- or both even.

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_3dgnb)

**Comment by humitos** [comment]
I'm going to close this issue in favor of a discussion about the analytics feature on itself and next steps: https://github.com/readthedocs/meta/discussions/130. We can re-open when we decide what's the path to follow regarding this feature.
