### ISSUE TITLE
analytics_id setting in html_theme_options not generating analytics code block when deploying

### ISSUE THREAD

**Issue by hrishikeshrt** [readthedocs/readthedocs.org#8895]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pycdsl/
* Build URL (if applicable): https://readthedocs.org/projects/pycdsl/builds/16013428/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/hrishikeshrt/

## Expected Result

I've added 
```python
html_theme_options = {
    'analytics_id': 'G-XXXXXXXXXX'
}
```
to my `docs/conf.py`. Google analytics javascript code is generated locally, but not when it is deployed.

Last few lines of locally generated HTML:

```html
<script>
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script>
    <!-- Theme Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-XXXXXXXXXX"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-XXXXXXXXXX', {
          'anonymize_ip': false,
      });
    </script> 

</body>
</html>
```

Last few lines of HTML from https://pycdsl.readthedocs.io/en/latest/

```html
   </div>
  </div>
<script>
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script> 

</body>
</html>
```

## Actual Result

Google analytics code block should be generated on https://pycdsl.readthedocs.io pages as it generates for local build.

**Comment by stsewd** [comment]
Hi, looks like we don't include that when running on RTD...

https://github.com/readthedocs/sphinx_rtd_theme/blob/d64dadf1ceec4f9ff6c1ca2d3ea4c3d0fdb0e8d2/sphinx_rtd_theme/layout.html#L237-L237

There is an open issue to remove that weirdness https://github.com/readthedocs/sphinx_rtd_theme/issues/650

You can set the option from the admin of your project https://docs.readthedocs.io/en/stable/analytics.html#enabling-google-analytics-on-your-project.
