### ISSUE TITLE
Embed API: cache tags aren't attached to the response

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#8906]
The view is inheriting from `CachedResponseMixin`, but isn't implementing the `_get_project` and `_get_version` methods. 

https://github.com/readthedocs/readthedocs.org/blob/ebca8e025e960fc8c7eae395092f42b054821c83/readthedocs/embed/v3/views.py#L31-L31

For v2 we have

https://github.com/readthedocs/readthedocs.org/blob/ebca8e025e960fc8c7eae395092f42b054821c83/readthedocs/embed/views.py#L72-L88

**Comment by ericholscher** [comment]
@stsewd good catch!
