### ISSUE TITLE
Build error with build id #16113872

### ISSUE THREAD

**Issue by jackj770** [readthedocs/readthedocs.org#8933]
## Details:

* Project URL: https://readthedocs.org/projects/ECE1400/
* Build URL(if applicable): https://readthedocs.org/projects/ece1400/builds/16113872/
* Read the Docs username(if applicable): jackj770

## Expected Result

To clone and build

## Actual Result

Fails after 12 seconds, usually just as cloning starts. I added a _readthedocs.yml but it didn't help...

**Comment by jackj770** [comment]
I solved it

**Comment by humitos** [comment]
Hi! Can you please comment here explaining how did you fix it? Thanks!
