### ISSUE TITLE
Build: ajust memory and time limits

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#8967]
We have documented (https://docs.readthedocs.io/en/stable/builds.html) that we offer:

* 15 minutes of CPU time
* 3Gb RAM memory

However, we have touched these settings in multiple opportunities and we never finish this work.

https://github.com/readthedocs/readthedocs.org/blob/1a96766e259dfcb2a1da5a38382322cf8c05b775/readthedocs/settings/base.py#L611-L620

The current math ends up being:

* build-default
  * 15 minutes
  * 2.6 Gb (note: we can't increase this number because otherwise, we ran out of memory for our app)
```
In [1]: settings.DOCKER_LIMITS
Out[1]: {'memory': '2700m', 'time': 900.0}
```
* build-large
  * 31 minutes
  * 6.5 Gb
```
# build-large
In [1]: settings.DOCKER_LIMITS
Out[1]: {'memory': '6700m', 'time': 1900.0}
```

**Comment by ericholscher** [comment]
Is this just updating the docs with the actual limits?

**Comment by humitos** [comment]
I'd like to simplify the math logic if possible as well without the need to be dynamic and hacky. Just something like

* total memory is 4Gb -> 2.5Gb for the user
* total memory is 8Gb -> 6.5Gb for the user
* total memory is 16Gb -> 14.5Gb for the user

Which is `total memory - 1.5Gb (application memory) = memory for the user`. We need something similar for the time as well.

**Comment by ericholscher** [comment]
Sounds reasonable 👍
