### ISSUE TITLE
RTD <-> Sphinx Gallery

### ISSUE THREAD

**Issue by ExtremOPS** [readthedocs/readthedocs.org#8982]
## Details

We are using RTD for our porject [gorkov](https://gitlab.com/acoustofluidics/gorkov) in conjunction with [sphinx-gallery](https://sphinx-gallery.github.io/stable/index.html). For the [example]((https://gorkov.readthedocs.io/en/patch-documentation/examples/)) section of our project we want to have this dynamic gallery extension. The problem is that somehow the figures within one example are not available, e.g. [here](https://gorkov.readthedocs.io/en/patch-documentation/examples/plot_air_bubble_in_water/#scattering-plot). Strangely, the thumbnail pictures at the [example](https://gorkov.readthedocs.io/en/patch-documentation/examples/) section level are there.

If I build this docu locally or on our gitlab runner, it all works fine. I already performed a thorough google search but could not find a similar problem.

Do you have any glue/ideas how to solve this.

**Comment by stsewd** [comment]
Hi, the path of the generated images looks to be wrong.

```
src="../_images/sphx_glr_plot_air_bubble_in_water_001.png"
```
that resolves to
https://gorkov.readthedocs.io/en/patch-documentation/examples/_images/sphx_glr_plot_air_bubble_in_water_001.png

When it should be https://gorkov.readthedocs.io/en/patch-documentation/_images/sphx_glr_plot_air_bubble_in_water_001.png.

There is probably a setting you are missing.

**Comment by ExtremOPS** [comment]
Hi stsewd,

thanks for the comment. But how would you explain that it works if I build it locally?

I just let it re-run and opened the path to thumbnail figure and the one in the example. Both point to `gorkov/docs/_build/html/_images`. Also if I check my local `_build/html/_images' folder, I find there all necessary pngs. Lastly, our runner on gitlab.com uses a docker image. There the documentation is also build as part of the pipeline. [There](https://acoustofluidics.gitlab.io/gorkov/examples/plot_cu_in_oil.html#sphx-glr-examples-plot-cu-in-oil-py) the displaying also works.

**Comment by stsewd** [comment]
One obvious difference is that you are using html paths (foo.html) on gitlab and htmldir paths on rtd (foo/index.html). That makes the `../` to not advance one directory up.

**Comment by ExtremOPS** [comment]
@stsewd : That fixed the problem. Thank you!!

**Comment by stsewd** [comment]
If there isn't an option that fixes this, this may be bug of sphinx-gallery when using the htmldir builder.

**Comment by ExtremOPS** [comment]
Good point. I'll will maybe also raise there an issue. Thanks again for this fast support!
