### ISSUE TITLE
Build: incompatible Mercurial versions from VCS setup than build commands

### ISSUE THREAD

**Issue by ahal** [readthedocs/readthedocs.org#8995]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/taskcluster-taskgraph/
* Build URL (if applicable): https://readthedocs.org/projects/taskcluster-taskgraph/builds/16259866/
* Read the Docs username (if applicable): ahal

## Expected Result

The builds should succeed :)

## Actual Result

Builds fail as seen [here](https://readthedocs.org/projects/taskcluster-taskgraph/builds/16259866/). I don't believe anything changed on the repo side, this was [working a week or two ago](https://readthedocs.org/projects/taskcluster-taskgraph/builds/).

```
hg identify --id
abort: repository requires features unknown to this Mercurial: sparserevlog!
(see https://mercurial-scm.org/wiki/MissingRequirement for more information) 
```

**Comment by marmoute** [comment]
I only skimmed through the logs, but this is weird. It looks like the `hg id` call is suddently too old to be able to read the repository that just got cloned by that same hg.

So, might this is no longer the same hg and some of the virtualenv play in between downgraded it somehow ?

**Comment by ahal** [comment]
I don't have any insight into reathedocs infrastructure, though a co-worker pointed out a [somewhat suspicious commit](https://www.mercurial-scm.org/repo/hg/rev/6d2ddea0721a2a70dc399bd94829ee36bf7597af) to Mercurial which would have been released a couple weeks before this started failing. But yeah, it's weird that the earlier `hg` commands aren't failing.

**Comment by marmoute** [comment]
The "suspicious commit" (and the related work in this area) only affects the "streaming clone" feature. Streaming clone does not seems to be involved in this build at all. So I would be surprised if these changes play any part in the current failures.

**Comment by mattip** [comment]
We are seeing this on the [PyPy doc builds](https://readthedocs.org/projects/pypy/builds/) as well. Is there a way to find all the projects that are using mercurial to find one that is succeeding?

**Comment by mattip** [comment]
According to #8840 there are ~46 repos using mercurial. Are all their builds failing?

**Comment by humitos** [comment]
@ahal can you try using a Read the Docs config file with build.os (https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os) declared as Ubuntu 20.04?

**Comment by humitos** [comment]
I guess the problem here is that we are using a newer version in the `hg clone` and then an old version for the second `hg identify` command. I think this issue was introduced in https://github.com/readthedocs/readthedocs.org/pull/8930 when we started using the `ubuntu-20.04` for the VCS steps.

I think you will be able to fix this problem by using Ubuntu 20.04 in your config file as I suggested in my previous comment.

It would be good to find a way to tell Mercurial to clone the repository to make it compatible with older versions.

**Comment by marmoute** [comment]
You can use `--config format.sparse-revlog=no` when cloning (or update the config of the thing doing the clone).
This problem will arise in the future as we turn format variant on by default overtime. Maybe Mercurial need some generic flag to request clone compatible with version X

**Comment by ahal** [comment]
> @ahal can you try using a Read the Docs config file with build.os (https://docs.readthedocs.io/en/stable/config-file/v2.html#build-os) declared as Ubuntu 20.04?

Thanks, this works around the issue for me.

**Comment by mattip** [comment]
Something is wrong. I cannot build the PyPy docs https://readthedocs.org/projects/pypy/builds/ for the last day: the build fails to get `hg id`.

**Comment by humitos** [comment]
@mattip for some reason `hg tags` is returning `Command exited abnormally`. I was able to reproduce this error locally when building your project with my Read the Docs development instance, but I don't understand why it's happening yet. However, I'm not able to reproduce this by running the commands manually.

**Comment by mattip** [comment]
Thanks for looking.

**Comment by mattip** [comment]
@marmoute if you mean me, I only have the information in the build log https://readthedocs.org/projects/pypy/builds/16514248/

**Comment by humitos** [comment]
I've already found the issue and opened a PR to fix it at https://github.com/readthedocs/readthedocs.org/pull/9055 --It's a Read the Docs' bug, not related with Mercurial itself.

**Comment by ericholscher** [comment]
This is now deployed. Please let me know if this solves the issue.

**Comment by ericholscher** [comment]
Looks like pypy is working properly: https://readthedocs.org/projects/pypy/builds/16518308/
