### ISSUE TITLE
Better error when using conda without an environment file

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#9008]
In this build https://readthedocs.org/projects/test-builds/builds/16326429/ I'm using coda, but I didn't define the environment file in the config file, so it gave me a generic error

The error came from https://github.com/readthedocs/readthedocs.org/blob/6752de13bd7f8ebcf393e66c4fdb738e17171046/readthedocs/doc_builder/python_environments.py#L550-L557

We should probably require using conda.environment when using build.tools.python = conda

**Comment by humitos** [comment]
The other way should also be considered probably: defining `conda.environment` but using `build.tools.python: "3.8"`. See https://github.com/readthedocs/readthedocs.org/issues/10047#issuecomment-1438326133

**Comment by humitos** [comment]
When working on this issue, we should also take a look at https://github.com/readthedocs/readthedocs.org/issues/10502 which is strongly related.

**Comment by humitos** [comment]
Something similar happens when the Git submodule does not exist: https://github.com/readthedocs/readthedocs.org/pull/10594/files#r1282428289 -- The user gets a weird error.

I noting this here so we don't forget to improve this error when working on this.

**Comment by humitos** [comment]
This is another issue related to better error messaging on the config file https://github.com/readthedocs/readthedocs.org/issues/8595
