### ISSUE TITLE
Build error with Python 3.10 project

### ISSUE THREAD

**Issue by vinkami** [readthedocs/readthedocs.org#9024]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/kripweb/
* Build URL: https://readthedocs.org/projects/kripweb/builds/16398314/
* Read the Docs username: https://readthedocs.org/profiles/vinkami/

## Expected Result

*A description of what you wanted to happen*

Successfully building the docs for me instead of failing

## Actual Result

*A description of what actually happened*

The build fails

## How to Replicate

1. Create a Python 3.10 project
2. Do the usual business by creating `.readthedocs.yaml` and `mkdocs.yml`
3. Make extra sure your project is in Python 3.10 with this
```
build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
```

## Investigation

I've done my greatest job debugging my own codes only to conclude that it's probably not my fault.

When it was building, this exception was raised
```
Traceback (most recent call last):
  File "/home/docs/.asdf/installs/python/3.10.0/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/docs/.asdf/installs/python/3.10.0/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/docs/checkouts/readthedocs.org/user_builds/kripweb/envs/latest/lib/python3.10/site-packages/mkdocs/__main__.py", line 14, in <module>
    from mkdocs import config
  File "/home/docs/checkouts/readthedocs.org/user_builds/kripweb/envs/latest/lib/python3.10/site-packages/mkdocs/config/__init__.py", line 2, in <module>
    from mkdocs.config.defaults import DEFAULT_SCHEMA
  File "/home/docs/checkouts/readthedocs.org/user_builds/kripweb/envs/latest/lib/python3.10/site-packages/mkdocs/config/defaults.py", line 4, in <module>
    from mkdocs.config import config_options
  File "/home/docs/checkouts/readthedocs.org/user_builds/kripweb/envs/latest/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 5, in <module>
    from collections import Sequence, namedtuple
ImportError: cannot import name 'Sequence' from 'collections' (/home/docs/.asdf/installs/python/3.10.0/lib/python3.10/collections/__init__.py)
```
It mainly says that the `collections` module has no `Sequence` inside.
And here's what I found in https://docs.python.org/3.9/library/collections.html
```
Deprecated since version 3.3, will be removed in version 3.10: Moved [Collections Abstract Base Classes](https://docs.python.org/3.9/library/collections.abc.html#collections-abstract-base-classes) to the [collections.abc](https://docs.python.org/3.9/library/collections.abc.html#module-collections.abc) module. For backwards compatibility, they continue to be visible in this module through Python 3.9.
```
All the abstract classes were in `collections` all the way till Python 3.9, but then got removed and must be found in `collections.abc`.
Turns out `Sequence` is a type of ABC, therefore I assume it got moved to `collections.abc` but the code for building the docs still remains at `collections`, causing the bug to happen.

![image](https://user-images.githubusercontent.com/51741497/158876419-f52fa6d3-ca91-463b-8742-87a53981431c.png)
The image is my test to prove my point, and it is amazingly similar to the last few lines of the error trace above.

I hope that's the exact problem I'm facing, instead of me being stupid and actually have the `.readthedocs.yaml` or `mkdocs.yml` wrong.
Thanks for reading that long passage.

**Comment by stsewd** [comment]
Hi, this is probably something to do with the version of mkdocs installed, please see https://docs.readthedocs.io/en/stable/builds.html#default-versions-of-dependencies

**Comment by akanksha-singh-robomq** [comment]
I am also facing this issue while using build.tools.python 3.11, can I know what we need to add in the configuration file .readthedocs.yml
Currently I am adding there lines to .readthedocs.yml file:
version: 2
build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
mkdocs:
  configuration: mkdocs.yml
  
  @stsewd what is the meaning to the mkdocs version? How can I specify it in the configuration file?

**Comment by akanksha-singh-robomq** [comment]
@vinkami @dag @alex @robhudson @Carreau @hickford @U-238 Please answer my question. Thanks

**Comment by Carreau** [comment]
Please don't at-mention people like this:

1) you only wrote 4h ago. 
2) it's on a close issue
3) some people you mention don't work on this repo.
