### ISSUE TITLE
Compiling python wrapper for c++ fails - cannot find header.

### ISSUE THREAD

**Issue by MatPiq** [readthedocs/readthedocs.org#9034]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/rlassopy
* Build URL (if applicable): https://readthedocs.org/projects/rlassopy/builds/16446285/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/MatPiq/

I am trying to build a project that depends on pybind11 and Eigen. I can compile the project locally using `pip install .` without any problems but it fails during the RTD build process because its seems to be unable to find the location of Eigen and pybind11. I have tried installing pybind11 both using conda by setting up an `environment.yml` and using `pip`. The Eigen library is included in the project under `extern/eigen-3.4.0`. 

I would be very grateful to any suggestions as to where to continue with debugging. 

## Expected Result

Successful build.

## Actual Result

```
gcc -pthread -B /home/docs/checkouts/readthedocs.org/user_builds/rlassopy/conda/latest/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DVERSION_INFO=0.0.1 -I/home/docs/checkouts/readthedocs.org/user_builds/rlassopy/conda/latest/lib/python3.8/site-packages/pybind11/include -Iextern/eigen-3.4.0 -I/home/docs/checkouts/readthedocs.org/user_builds/rlassopy/conda/latest/include/python3.8 -c rlassopy/solver_fast.cpp -o _skbuild/linux-x86_64-3.8/setuptools/temp.linux-x86_64-3.8/rlassopy/solver_fast.o -std=c++17 -fvisibility=hidden -g0
cc1plus: warning: command-line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
In file included from rlassopy/solver_fast.cpp:2:
/home/docs/checkouts/readthedocs.org/user_builds/rlassopy/conda/latest/lib/python3.8/site-packages/pybind11/include/pybind11/eigen.h:30:10: fatal error: Eigen/Core: No such file or directory
   30 | #include <Eigen/Core>
      |          ^~~~~~~~~~~~
compilation terminated.
```

**Comment by ericholscher** [comment]
@MatPiq I'm guessing it's missing some kind of dependency. You can install apt packages via the config file, which might help? https://docs.readthedocs.io/en/latest/config-file/v2.html#build-apt-packages

**Comment by MatPiq** [comment]
Hi @ericholscher, thank you for your quick response and sorry for my late reply. I have tried installing Eigen through apt but it doesn't change anything. Pybind is installed using conda.

**Comment by humitos** [comment]
@MatPiq are you able to create the environment locally using conda? does it install your dependency property? I don't know how conda handles these dependencies, but I suppose that you should tell it where to find them somehow.

**Comment by MatPiq** [comment]
Yes, I am able to do it locally. I finally managed to solve it by following the approach used in https://github.com/tohtsky/irspack by having `setup.py` download the Eigen header to the parent directory of the project.
