### ISSUE TITLE
Build analytics dashboard with CDN stats

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#9035]
It would be neat to be able to have a project-specific analytics dashboard via cloudflare data. This could include data from the CDN layer (Cache hit rate, bandwidth, etc.) as well as our own analytics (404 pages, pageviews, etc.). I'd love to have the interesting stats pulled out in a "heads up" manner similar to this:

<img width="989" alt="Screen Shot 2022-03-23 at 11 24 09 AM" src="https://user-images.githubusercontent.com/25510/159769703-1e9b7aa3-3f9c-49bb-a09a-98e88a5c7e38.png">

**Comment by ericholscher** [comment]
https://developers.cloudflare.com/analytics/graphql-api/tutorials/build-your-own-analytics/

**Comment by ericholscher** [comment]
Another use case here: build.commands users who aren't integrating our `analytics.js`.

**Comment by humitos** [comment]
> Another use case here: build.commands users who aren't integrating our `analytics.js`.

This has changed with the introduction of the addons. Now, projects using `build.commands` do have analytics integrated.

**Comment by humitos** [comment]
I'm going to close this issue in favor of a discussion about the analytics feature on itself and next steps: https://github.com/readthedocs/meta/discussions/130. We can re-open when we decide what's the path to follow regarding this feature.
