### ISSUE TITLE
RDT build suddenly starts failing without any changes in conf.py

### ISSUE THREAD

**Issue by RobiFag** [readthedocs/readthedocs.org#9037]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/manuale-catasto-strade/
* Build URL (if applicable): https://readthedocs.org/projects/manuale-catasto-strade/builds/16458010/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/RobiFag/

## Actual Result

Everything worked fine till few hours ago then the build started failing. We don't have modified any configuration in the conf.py file and just added text and images to a page of the manual.

```
The errors are:
ImportError: cannot import name 'contextfunction' from 'jinja2' (/home/docs/checkouts/readthedocs.org/user_builds/manuale-catasto-strade/envs/novara/lib/python3.7/site-packages/jinja2/__init__.py)

Could not import extension sphinx.builders.latex (exception: cannot import name 'contextfunction' from 'jinja2' (/home/docs/checkouts/readthedocs.org/user_builds/manuale-catasto-strade/envs/novara/lib/python3.7/site-packages/jinja2/__init__.py))
```

We get the same errors in another manual:

* Read the Docs project URL: https://readthedocs.org/projects/template-rtd/
* Build URL (if applicable): https://readthedocs.org/projects/template-rtd/builds/16458056/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/RobiFag/

**Comment by ericholscher** [comment]
I'm guessing this is because of a new release of jinja2 (https://github.com/pallets/jinja/releases). You'll need to pin your jinja2 requirement in your build to ensure it continues to work to `jinja2<3.1.0`. We recommend upgrading from Sphinx 1.8 though, because these kind of issues will continue to happen on older dependencies. 

We are also deploying a fix to Sphinx 1.8, but we generally do recommend upgrading: https://docs.readthedocs.io/en/latest/guides/reproducible-builds.html#using-a-configuration-file

**Comment by lizadams** [comment]
Also having this issue https://readthedocs.org/projects/cyclecloud-cmaq/

**Comment by lizadams** [comment]
The error is also described here: https://github.com/pallets/jinja/issues/1631
I've set 
# File: docs/requirements.txt
#
# sphinx==4.2.0
# sphinx_rtd_theme==1.0.0
# readthedocs-sphinx-search==0.1.1
# jinja2==3.0.0

and
# File: docs/environment.yaml

name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - sphinx==4.2.0
  - nbsphinx==0.8.1
  - pip:
    - sphinx_rtd_theme==1.0.0
  - jinja2==3.0.0

It doesn't resolve the error.

**Comment by ericholscher** [comment]
@lizadams it looks like your requirements file is commented out. You need to remove the `#` before the dependencies.,

**Comment by lizadams** [comment]
@ericholscher - Thanks!
This seems to have worked:
# File: docs/requirements.txt
mkdocs==1.2.3
jinja2==3.0.0

# File: docs/environment.yaml

name: docs
channels:
  - conda-forge
  - defaults
dependencies:
  - mkdocs==1.2.3
  - pip:
    - jinja2==3.0.0

**Comment by fnielsen** [comment]
What does "We recommend upgrading from Sphinx 1.8 though", that @ericholscher writes, mean? Aren't we typically running something like `sphinx==4.2.0`.

**Comment by pranayrauni** [comment]
> Hi @ericholscher now the build starts working correctly without any changes!
> 
> Anyway thanks for the suggestions, I will try to update Sphinx!

Can you tell me how did it work?

**Comment by ericholscher** [comment]
@pranayrauni We pinned Jinja2 to a working version for old versions of Sphinx that we were installing.
