### ISSUE TITLE
Duplicate build sends GH PR status, showing failure until the first build finishes

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#9040]
## Expected Result

I expect GH to show "build running" with a link pointing to the first build for that commit

## Actual Result

GH shows a failed build in the status result, pointing to the build that failed with `Duplicated build`. This is replaced with a ✔️ success after the first build finishes and overwrites the status.

**Comment by humitos** [comment]
Good catch! I think we should probably avoid sending the github notification status when we detect the build is duplicated. This happens at `on_failure` or `after_return`, I think.
