### ISSUE TITLE
Readthedocs not finding new branches being created on the repo

### ISSUE THREAD

**Issue by iquah1** [readthedocs/readthedocs.org#9044]
## Details

[Docs Project URL](https://readthedocs.org/projects/openfhe-development) `https://readthedocs.org/projects/openfhe-development`
Build URL: - 
RTD username: ` iquah1`

## Expected Result

New branches are found.

## Actual Result

Branches aren't being found. specifically [sphinx_logging](https://github.com/openfheorg/openfhe-development/tree/sphinx_logging) branch, or [sphinx logging PR](https://github.com/openfheorg/openfhe-development/pull/12)

**Comment by stsewd** [comment]
Hi, could you check if the webhook was handled correctly? https://readthedocs.org/dashboard/openfhe-development/integrations/? (you could also check this from the github side)

In any case, triggering a build to any version should update your branches/tags.
