### ISSUE TITLE
Build fails due to "no matching distribution" / .readthedocs.yaml config is ignored

### ISSUE THREAD

**Issue by NickleDave** [readthedocs/readthedocs.org#9054]
Hi, thank you for this great site and resource. Apologies if this is not the right place to raise this issue but I do think this might actually be a bug? Or at least it's not at all clear to me what I'm doing wrong.

## Details

* Read the Docs project URL: https://crowsetta.readthedocs.io/en/latest/
* Build URL (if applicable): 
  https://readthedocs.org/projects/crowsetta/builds/16508695/
  https://readthedocs.org/projects/crowsetta/builds/16508574/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/nickledave/

## Expected Result

Expected build to work

## Actual Result
Build fails.

- On the `pip install` step I get a couple of errors about `no matching distribution` for packages, even though I know they're on PyPI
  
```
[rtd-command-info] start-time: 2022-03-30T01:12:48.165681Z, end-time: 2022-03-30T01:12:50.981486Z, duration: 2, exit-code: 1
/home/docs/checkouts/readthedocs.org/user_builds/crowsetta/envs/latest/bin/python -m pip install --upgrade --upgrade-strategy eager --no-cache-dir /home/docs/checkouts/readthedocs.org/user_builds/crowsetta/checkouts/latest[docs]
Processing /home/docs/checkouts/readthedocs.org/user_builds/crowsetta/checkouts/latest
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
WARNING: crowsetta 3.4.0 does not provide the extra 'docs'
Collecting numpy>=1.18.1
  Downloading numpy-1.19.5-cp36-cp36m-manylinux2010_x86_64.whl (14.8 MB)
Collecting SoundFile>=0.10.3
  Downloading SoundFile-0.10.3.post1-py2.py3-none-any.whl (21 kB)
Collecting attrs>=19.3.0
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
ERROR: Could not find a version that satisfies the requirement evfuncs>=0.3.4 (from crowsetta[docs]) (from versions: 0.1.1a1, 0.1.1a2, 0.1.1a3, 0.1.1, 0.2.0, 0.2.1, 0.3.0, 0.3.1, 0.3.2, 0.3.2.post1)
ERROR: No matching distribution found for evfuncs>=0.3.4
```

Sometimes it's a different package for which no matching distribution is found:

```
Collecting attrs>=19.3.0
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
ERROR: Could not find a version that satisfies the requirement birdsong-recognition-dataset>=0.3.0 (from crowsetta[docs]) (from versions: none)
ERROR: No matching distribution found for birdsong-recognition-dataset>=0.3.0
```

- I have added a `.readthedocs.yaml` file but it seems like it's being ignored? I still see a message suggesting I should use one, and the Python being used is 3.6 instead of the 3.8 specified in my config file

https://github.com/NickleDave/crowsetta/blob/main/.readthedocs.yaml

My build has been broken for a while, and I am now just trying to fix it, but I am not seeing any obvious changes I made when it broke that could explain this.

Thank you

**Comment by humitos** [comment]
Thanks for reporting this issue. It called my attention that you have a `.readthedocs.yaml` file defining 3.8 as Python version but it's using 3.6 to create the environment. I thought the YAML file may not be read by Read the Docs but then I saw that the same file declares to install `docs` as pip requirements extra, which is indeed installed by Read the Docs.

We will need to debug a little more to understand what's happening here.

**Comment by stsewd** [comment]
This is because  you have two config files, you should delete this one, so the other takes effect https://github.com/NickleDave/crowsetta/blob/main/readthedocs.yml

**Comment by NickleDave** [comment]
Wow, how did I miss that?
@stsewd thanks mi pana! That fixed it :raised_hands: Closing
