### ISSUE TITLE
broken link for signup 

### ISSUE THREAD

**Issue by shahzebsiddiqui** [readthedocs/readthedocs.org#9059]
When you click on `sign up` button from https://readthedocs.org/ i get redirected to https://readthedocs.org/accounts/signup/ and its a broken link. This used to work before and reason i bring this up i am running a urlchecker in our docs and this shows up as a failure

![Screen Shot 2022-03-30 at 2 07 21 PM](https://user-images.githubusercontent.com/12942230/160902241-531f0617-88e9-4bce-b174-25aec6a597ef.png)

It looks like the url for signup is https://readthedocs.org/accounts/signup/?next=%2Fsupport%2F which works but this is different than the one i see. Can we please fix this so we can use same link https://readthedocs.org/accounts/signup/

**Comment by stsewd** [comment]
@shahzebsiddiqui the page isn't broken, you are just presented with a captcha, maybe there were some suspicious requests to that page from your IP. The other URL works because it has a query parameter (which shouldn't skip the captcha, as both pages are the same)

**Comment by stsewd** [comment]
But looks like I'm getting a captcha every time... that's not ideal.

**Comment by stsewd** [comment]
We have disabled that rule from our firewall, you shouldn't be presented with a captcha now.

**Comment by shahzebsiddiqui** [comment]
Thanks @stsewd it is now working, i am not seeing the captcha.
