### ISSUE TITLE
install dependency

### ISSUE THREAD

**Issue by stuti404** [readthedocs/readthedocs.org#9070]
Run pip install -r requirements.txt
Processing /home/ktietz/src/ci/alabaster_1[6](https://github.com/stuti404/Heart-Disease-Prediction/runs/5817903534?check_suite_focus=true#step:5:6)11[9](https://github.com/stuti404/Heart-Disease-Prediction/runs/5817903534?check_suite_focus=true#step:5:9)21544520/work
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/home/ktietz/src/ci/alabaster_1611921544520/work'

Error: Process completed with exit code 1.

whenever i try to deploy this error occur how can i resolv this please help me

**Comment by stsewd** [comment]
Hi, can you please provide the information from the template? https://github.com/readthedocs/readthedocs.org/blob/main/.github/ISSUE_TEMPLATE/bug.md

> : '/home/ktietz/src/ci/alabaster_1611921544520/work'

That path looks like something from your local machine, so probably this isn't related to Read the Docs.
