### ISSUE TITLE
Proxito: issues with parsing of URLs with bad characters

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#9072]
It seems there was a fix in Python around 3.8.11 -- and which was backported to 3.8.10 in Ubuntu[1] -- that strips out characters from URLs during calls to (at least) `urlsplit`. If you pass in `/\r/example.com` to 3.8.10, the `\r` is not stripped but this is an invalid character for URLs either way. If you pass in `/\r/example.com` to 3.8.11 or a backported 3.8.10, `urlsplit` discards the character, changing the URL to `//example.com`, a valid URL.

Discussion on the Python issues: https://bugs.python.org/issue43882

1: http://changelogs.ubuntu.com/changelogs/pool/main/p/python3.8/python3.8_3.8.10-0ubuntu1~20.04.4/changelog

**Comment by humitos** [comment]
@agjohnson @stsewd I'm not sure if this issue is solved by #9075 or not. If it's not, what's the missing required action here?

**Comment by stsewd** [comment]
I think we can close, there are other usages of urlparse in our codebase, but I can look into that today in open PRs if needed.
