### ISSUE TITLE
Analytics: track referrer

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#9101]
This is specially useful for 404s, so users know from where the broken link comes from. Currently, we store one record per-day, so we will need to store something like an array of referrers, or re-think our page view models. There are also ideas about using Cloudflare for this.

**Comment by ericholscher** [comment]
https://developers.cloudflare.com/analytics/graphql-api/tutorials/build-your-own-analytics/

**Comment by humitos** [comment]
I'm going to close this issue in favor of a discussion about the analytics feature on itself and next steps: https://github.com/readthedocs/meta/discussions/130. We can re-open when we decide what's the path to follow regarding this feature.
