### ISSUE TITLE
lsremote fails if the output is bigger than DATA_UPLOAD_MAX_MEMORY_SIZE

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#9112]
When executing commands, we are sanitizing the output

https://github.com/readthedocs/readthedocs.org/blob/464f20e77b63f550d10dcdaa0de9bab7a7f2e349/readthedocs/doc_builder/environments.py#L160-L160

https://github.com/readthedocs/readthedocs.org/blob/464f20e77b63f550d10dcdaa0de9bab7a7f2e349/readthedocs/doc_builder/environments.py#L206-L210

but lsremote depends on the output as is. This is a problem for repositories with a lot of branches/tags

ref https://sentry.io/organizations/read-the-docs/issues/3193177679/?alert_rule_id=229005&alert_timestamp=1649941826119&alert_type=email&environment=production&project=148442 

We should exclude cutting the output from that command or do this "sanitation" just when saving the command.

**Comment by agjohnson** [comment]
Raised in chat: I had added this separate implementation of API requests for users that were hitting request limits:

https://github.com/readthedocs/readthedocs.org/blob/main/readthedocs/doc_builder/environments.py#L238-L255

It might be good to get that out of feature flag, or potentially feature flag the truncation for now at least.

**Comment by humitos** [comment]
This seems duplicated of #8990
