### ISSUE TITLE
404 tracking should filter out bot traffic

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#9116]
Currently we are storing a bunch of 404s from bots that aren't really valuable to users. We can probably use either an existing bot database of user agents, or Cloudflare's data to give us this: https://developers.cloudflare.com/bots/concepts/bot-score/

Looks like we can add this [as a header](https://community.cloudflare.com/t/adding-bot-score-as-a-header-passed-to-origin/300589), so our application can read it.

**Comment by humitos** [comment]
I like the idea of using CF bot's score data, passing it as a header to our app, and ignoring tracking that 404 requests. Looks like a simple technical implementation and is more trustable that any heuristic we can implement by ourselves in a short term.
