### ISSUE TITLE
Ability to activate other analytics tools

### ISSUE THREAD

**Issue by samhita-alla** [readthedocs/readthedocs.org#9126]
Google Analytics is the currently-integrated analytics tool in read the docs. Would there be a possibility to support other web analytics tools, say, Umami, Plausible, etc.?

**Comment by stsewd** [comment]
Hi, don't think we will be integrating other analytics tools in our UI, but adding one of those tools usually means injecting a js snipped on each page, that can be already done from Sphinx https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html or mkdocs https://www.mkdocs.org/user-guide/configuration/#extra_javascript

**Comment by samhita-alla** [comment]
That seems like the way forward. Thank you!
