### ISSUE TITLE
Tests: improve how we run tox enviroments

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#9129]
I'd like to get more granularity when running `tox` tests locally.

Currently, I'm trying to run some tests that I've changed in the `readthedocs/rtd_tests/tests/test_api.py` file. So, I'm executing:

```
tox -e py38 -- -k test_api
```

However, this includes search tests that I don't want because I usually don't run ElasticSearch since it consumes a lot of resources:

```
pytest ... -m "not proxito and not embed_api" -k test_api'
```

However, if I don't pass any argument and just run `tox -e py38` I got this command executed:

```
pytest ... -m "not proxito and not embed_api" -m "not search and not proxito and not embed_api"'
```

Note that duplicates the `-m` argument. One includes `not search` and the other one does not. This command makes search tests not be run, but when you pass any argument to pytest from tox, the search tests are included 🤷🏼 

I think we need to review this line here, https://github.com/readthedocs/readthedocs.org/blob/8bff524c63424c6b40063d8376d39f519889228a/tox.ini#L23, fix it, and make it more customizable from the command line.

Also, I think it would be better to make tox environment more explicit:

- `tox -e proxito`
- `tox -e search`
- `tox -e readthedocs`
- `tox -e embedapi`

Instead of trying to run all the tests within the same command. It's more explicit and easier to work locally. What do you think, @readthedocs/backend?

**Comment by stsewd** [comment]
> Note that duplicates the -m argument. One includes not search and the other one does not. This command makes search tests not be run, but when you pass any argument to pytest from tox, the search tests are included

That's because the last `-m` option takes precedence, the previous ones are ignored, if you pass an extra argument then the second `-m` isn't included. Your first example is correct if you don't want to run the search tests.



There is some discussion around this at https://github.com/readthedocs/readthedocs.org/pull/8116/, we are already running search tests by default on .com, and as Eric mentioned, you can always pass the file at the end to make it more explicit from where to collect the tests.

And I think the declarative syntax from tox has fallen short for our needs, we are basically hacking it to adapt it to our needs, a more flexible tool is [nox](https://nox.thea.codes/en/stable/).

**Comment by humitos** [comment]
@stsewd 

> There is some discussion around this at #8116, we are already running search tests by default on .com, and as Eric mentioned, you can always pass the file at the end to make it more explicit from where to collect the tests.
 
Yeah, that has the problem that I mentioned at https://github.com/readthedocs/readthedocs.org/pull/8116#issuecomment-856859046

> And I think the declarative syntax from tox has fallen short for our needs, we are basically hacking it to adapt it to our needs, a more flexible tool is [nox](https://nox.thea.codes/en/stable/).

I don't think we need to change all the way how we run the tests for this. We just need to define more environments and re-use them as suggested in this issue (proxito, search, readthedocs, embedapi)  and also in that PR you linked.

**Comment by agjohnson** [comment]
We all just use `-k` and push to CI.

**Comment by ericholscher** [comment]
We are all basically just doing dev locally with `-k test_foo`, and then pushing to CI for the full suite. It's not ideal, but so it goes :)
