### ISSUE TITLE
Show a proper error message if the build exceeded the number of retries

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#9148]
Currently if the number of retries is reached (25)

https://github.com/readthedocs/readthedocs.org/blob/7db65821e65fcdf24df85030c3e72039537f9578/readthedocs/settings/base.py#L121-L121

An exception will be raised (BuildMaxConcurrencyError), and we will be hitting this code

https://github.com/readthedocs/readthedocs.org/blob/ea5d9e34da15be8a9eaad86b536801b68849d488/readthedocs/projects/tasks/builds.py#L416-L418

that code just updates the build to the same error as `Concurrency limit reached (2), retrying in 5 minutes`, and mark the build as failed, that isn't accurate as the build will not be retried.

**Comment by humitos** [comment]
I think this is a dup of #9011
