### ISSUE TITLE
Couldn't get certificate for .ru custom domain

### ISSUE THREAD

**Issue by leotsarev** [readthedocs/readthedocs.org#9149]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/joinrpg/
* Build URL (if applicable): n/a
* Read the Docs username (if applicable): https://readthedocs.org/leotsarev/

## Expected Result

I want my https://docs.joinrpg.ru domain works as before

## Actual Result

https://readthedocs.org/dashboard/joinrpg/domains/4680/edit/ 
` SSL certificate status: restricted_name_failure: Use of one or more domains on the certificate is restricted `

https://docs.joinrpg.ru
```
nmap --script ssl-enum-ciphers -p 443 docs.joinrpg.ru
Starting Nmap 7.92 ( https://nmap.org ) at 2022-04-27 11:02 CEST
Nmap scan report for docs.joinrpg.ru (104.17.32.82)
Host is up (0.0054s latency).
Other addresses for docs.joinrpg.ru (not scanned): 2606:4700::6811:2052 2606:4700::6811:2152 104.17.33.82

PORT    STATE SERVICE
443/tcp open  https
```

If I'll add another .ru domain, I'' have a same result

**Comment by ericholscher** [comment]
I think this is the result of our registrar not supporting `.ru` domains. I believe we can add logic to use Lets Encrypt for this. I've added it to our roadmap for this sprint, so it should be resolved soon.

**Comment by leotsarev** [comment]
Thanks for update! It was working for 3+ years before, so it's recent development.

**Comment by ericholscher** [comment]
@leotsarev I don't see `[docs.joinrpg.ru](https://docs.joinrpg.ru/)` in our DB. If you try to create it, I can manually assign it to LE so it should validate.

**Comment by leotsarev** [comment]
@ericholscher yes, I had temporary removed it. 
Added back https://readthedocs.org/dashboard/joinrpg/domains/13157/edit/

**Comment by leotsarev** [comment]
It seems to be working for me now at first glance. Thanks for your work and support.
Sadly, I can't express my gratitude by switching to the gold membership. VISA & Mastercard prevents me to use my credit cards abroad :-(

**Comment by stsewd** [comment]
We did a PR to fix this from our side (use LE for restricted TLDs), but looks like CF was one step ahead of us and did this (yesterday?) from their side... But isn't clear what would happen with existing domains once they need to renew their certificate.

**Comment by leotsarev** [comment]
Yes, it's working now for me!
