### ISSUE TITLE
Docs: "Good vs. Bad" examples of using `build.jobs`

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#9152]
I've seen people using `build.jobs` for things we already support in a better way, without the need of writing all the commands by hand. I'm not opposed to people doing this. However, there are cases where there are technical reasons that making usage of what Read the Docs suggests is better. Mainly, because of speed and better support over time.

This is a non-exhaustive list of things I've noticed that could be described in the content proposed:

- installing packages with `pip install` or `poetry install -E` instead of using `python.install.requirements`
- installing the repository Python package instead of using `python.install.method`
- defining environment variables (`export VAR=foo`) instead of using Read the Docs environment variables feature
- downloading and installing `rust` or any of the other supported tools via `build.tools`
- cloning an extra repository instead of using `submodules`

**Comment by ericholscher** [comment]
I think it's going to be difficult to tell people what not to do in the docs, if they already aren't not reading the docs to understand the right thing to do? I think this is not going to provide us much value unless we're proactive with it in email or something based on their build. I'm deprioritizing this in the roadmap, but also think it can probably just be closed.

**Comment by humitos** [comment]
My original idea here was to do something similar to what we've done in https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#don-t-rely-on-implicit-dependencies

I think it works as a good way to _guide people about how we recommend them to use our platform_.

**Comment by ericholscher** [comment]
We have a bunch of good examples now 👍
