### ISSUE TITLE
After click the build button, the new result of the new build doesn't show up but cache shows up.

### ISSUE THREAD

**Issue by hangfei** [readthedocs/readthedocs.org#9155]
## Details
After the build is succeessful, i clicked the [View docs](https://test233.readthedocs.io/en/latest/) link, the link still renders the old results. It's only after i hit refersh button again, the new results of this build shows up.
* Read the Docs project URL: https://readthedocs.org/projects/test233/
* Build URL (if applicable): https://readthedocs.org/projects/test233/builds/16786476/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/feathr/

## Expected Result
After i click the View docs button, the result for this build shows up.
*A description of what you wanted to happen*

## Actual Result
After i click the View docs button, the result of a previous build(probably cached) shows up.
*A description of what actually happened*

![image](https://user-images.githubusercontent.com/5482153/166074768-cc0a17cb-6e71-421a-97d5-0a831a332797.png)

**Comment by humitos** [comment]
> It's only after i hit refersh button again, the new results of this build shows up.

This is normal behavior. We use CDN to speed up our doc serving and it may take some minutes to purge the content and show the new one. Besides, it could be your own browser's cache as well.

That said, the update of the docs is _almost_ immediately, but it may some extra minutes to serve the newer version.

**Comment by hangfei** [comment]
got it. thanks.
