### ISSUE TITLE
Docs: mention that purging the cache may take a couple of minutes

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#9167]
We have lots of users opening issues about outdated pages on their docs, but this usually due to the cache not being purged yet, or due to cache on their browser. We should note this somewhere, and maybe add a message after the build completes (show it only once after the build has finished)

https://docs.readthedocs.io/en/stable/hosting.html#content-delivery-network-cdn

**Comment by humitos** [comment]
It seems we stopped receiving this type of support requests. This is probably because we have been tweaking a lot our CDN and also making the whole infra (Celery, in particular) more stable here. I will close this issue for now but we can reconsider opening in case we want to tackle this work.
