### ISSUE TITLE
code-block not displayed

### ISSUE THREAD

**Issue by FLAK-ZOSO** [readthedocs/readthedocs.org#9173]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/classeviva
* Build URL (if applicable): https://readthedocs.org/projects/classeviva/builds/16852935/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/FLAK-ZOSO/
* GitHub-stored file: https://github.com/Lioydiano/Classeviva/blob/v0.2.1b1.dev3/docs/esempi.rst

## Code

I wrote [this small `.rst` file](https://github.com/Lioydiano/Classeviva/blob/v0.2.1b1.dev3/docs/esempi.rst) to see if I liked the styling, and I wrote the code block following [`this tutorial`](https://sphinx-tutorial.readthedocs.io/step-1/#code-example-syntax).

```rst
.. codeblock:: python
    if __name__ == "__main__":
        s = Session("<my-username>", "<my-password>", hidden=False)
        s.login()
```

I tried also with `codeblock` and `code` instead of `code-block`.

## Expected Result

I expected it to display as a block of code.

## Actual Result

I got [`this result`](https://classeviva.readthedocs.io/it/v0.2.1b1.dev3/esempi.html): no piece of code was displayed.

**Comment by stsewd** [comment]
Hi, the directive name should be `.. code-block::`, if you build your project locally you'll see the same error from https://readthedocs.org/projects/classeviva/builds/16852935/

```
/home/docs/checkouts/readthedocs.org/user_builds/classeviva/checkouts/v0.2.1b1.dev3/docs/esempi.rst:4: ERROR: Unknown directive type "codeblock".

.. codeblock:: python
    from classeviva import Session, Valutazioni, Note, Registro
    from classeviva.variables import NoteSortBy
```

**Comment by agjohnson** [comment]
The issue here is the missing space between the directive name and the directive body. `codeblock` directive takes arguments, so an empty line is required after the directive name and arguments, if any.

That is:

```rst
.. codeblock:: python

    if __name__ == "__main__":
        s = Session("<my-username>", "<my-password>", hidden=False)
        s.login()
```

This isn't an issue with Read the Docs, so I'll go ahead and close this.
