### ISSUE TITLE
Delay `builder.move` until after `post_build` job

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#9179]
I hit this in testing and was raised again by a user in #9172.

The issue is that files are copied to the artifact path immediately after the build process completes. This negates any actions on the built files in `post_build`, as these changes won't be copied to the artifact path.

I believe the code in question is:
https://github.com/readthedocs/readthedocs.org/blob/main/readthedocs/doc_builder/director.py#L359-L360

We should only move/copy files to the artifact path **after** `post_build` job. Even with a static/configurable output path, it's a sufficiently confusing that changes to `docs/_build/...` don't update the hosted docs.

**Comment by humitos** [comment]
Why we are moving the files to an intermediate location in the first place? Why we don't upload the `docs/_build/` directory directly to S3?

**Comment by agjohnson** [comment]
The original issue that this solved was when we used to do multiple builds in the same path. Seems we can use a hardcoded, known path instead here now.

**Comment by ericholscher** [comment]
Adding this to an upcoming sprint, so we can prioritize it 👍
