### ISSUE TITLE
Docs: write a guide or a blog post about documenting Javascript API with `jsdoc`

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#9247]
This is a small issue to track this task somewhere. The idea comes from #9241 which has a little more context.

**Comment by agjohnson** [comment]
I could take this issue as one of my doc sprints. Though JS support isn't our core focus, I think this does a good job of showing some advanced usage with `build.jobs` and extending our supported toolchain a bit.

There are a few guides on this configuration already, so can build on those, but there were a few RTD specific configuration bits as well.
