### ISSUE TITLE
Equation render failed

### ISSUE THREAD

**Issue by chaoming0625** [readthedocs/readthedocs.org#9252]
### Describe the bug

I found the eqution render failed in many readthedoc websites. Like:

- https://jax.readthedocs.io/en/latest/jax-101/04-advanced-autodiff.html
- https://brainpy.readthedocs.io/en/brainpy-1.x/apis/simulation/generated/brainpy.simulation.layers.GRU.html
- https://brainmodels.readthedocs.io/en/latest/apis/generated/brainmodels.neurons.AdExIF.html
- https://brainpy-examples.readthedocs.io/en/latest/cann/Wu_2008_CANN.html

I don't know why?

### Your project

- https://readthedocs.org/projects/brainmodels/
- https://readthedocs.org/projects/brainpy-examples/
- https://readthedocs.org/projects/brainpy/

**Comment by chaoming0625** [comment]
In many pages, equations are rendered failed. 

Like this, 

![image](https://user-images.githubusercontent.com/14275596/169683608-49b4ad03-463a-487b-bc65-4553db6b5e91.png)

Like this, 

![image](https://user-images.githubusercontent.com/14275596/169683623-18169ae3-fbb6-400d-8d0f-fa17802be181.png)


Like this, 

![image](https://user-images.githubusercontent.com/14275596/169683638-650a2449-2578-4e53-b08a-36992ac5267b.png)

**Comment by chaoming0625** [comment]
In Edge brower, and some chrome browser of my colleagues.

**Comment by humitos** [comment]
Hi! I don't think that this is related to Read the Docs itself. It's probably an incompatibility between the JS library used to render the equation and the browser, probably.

If you open the HTML generated locally by your Sphinx project from localhost, I suppose it will have the same problem. Can you confirm that?

**Comment by chaoming0625** [comment]
Dear @humitos , thanks for your reply. This is related to MathJax,  cannot be loaded when opening these webpages in China. We have solved it. Thank your reply.
