### ISSUE TITLE
pyup or dependabot together with pip-tools

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#9273]
pyup does not understand pip-tools (pip-compile), so I was taking a look at dependabot and it seems it does: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#supported-repositories-and-ecosystems

We should probably migrate to it and use pip-tools for all our dependencies.

**Comment by humitos** [comment]
I used this in sphinx-hoverxref and it worked: https://github.com/readthedocs/sphinx-hoverxref/pull/182

**Comment by stsewd** [comment]
Looks like pyup is currently tracking only the docs' requirements https://github.com/readthedocs/readthedocs.org/blob/68226d18173b7b30d4861fa7c9055e85504659ce/.pyup.yml#L24, the app requirements aren't being updated anymore

**Comment by stsewd** [comment]
Actually, sphinx released a new version, and we haven't seen a PR from the bot :/

**Comment by humitos** [comment]
I'm bumping this to the next sprint because pyup is currently broken and it's not updating any package.
