### ISSUE TITLE
Subscriptions: convert Subscription model to use djstripe

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#9312]
Once we have djstripe added again, we'll want to start thinking about moving our logic to use djstripe. The easiest piece to update first might be our Subscription model. We aren't doing any real magic here, besides our handling of subscription state.

A few notes:

- The logic around how we interpret Stripe's subscription state is a little confusing to follow, because Stripe makes this harder than it should be. Namely, we have to use a Trial plan to create a trial period, and we manually cancel subscription state with application code when we determine the trial period to be over.
- We need to monitor this heavily. Any changes to subscription flow need to be monitored on a weekly basis, both in Sentry and in Stripe (see the daily view of new trials and daily view of MRR)
- We have had a few transient issues with id lookup on Stripe and organization/subscriptions missing ids. These errors likely are going away with this change. But see also a few related Sentry issues around Subscriptions and id lookup:

  - Sentry issue: [READTHEDOCSCOM-9HZ](https://sentry.io/organizations/read-the-docs/issues/3048896842/?referrer=github_integration)
  - Sentry issue: [READTHEDOCSCOM-8T5](https://sentry.io/organizations/read-the-docs/issues/2834387551/?referrer=github_integration)
  - Sentry issue: [READTHEDOCSCOM-9N3](https://sentry.io/organizations/read-the-docs/issues/3301234214/?referrer=github_integration)
  - Sentry issue: [READTHEDOCSCOM-5Z6](https://sentry.io/organizations/read-the-docs/issues/2243855318/?referrer=github_integration)

**Comment by stsewd** [comment]
Djstripe allows you to attach a subscriber to the `Customer` object (defaults to User https://dj-stripe.dev/reference/settings/#djstripe_subscriber_model-settingsauth_user_model), but we have stripe customers attached to organizations and users (gold), so we could just add that field in the models manually, this is start by adding a `stripe_customer` field to our organization/gold model (same as `stripe_id`).

https://github.com/readthedocs/readthedocs.org/blob/b0ae8f8d2d3860f78369f3ecb822a27eb126ecfe/readthedocs/organizations/models.py#L90-L95

https://github.com/readthedocs/readthedocs.org/blob/b0ae8f8d2d3860f78369f3ecb822a27eb126ecfe/readthedocs/gold/models.py#L52-L52

And slowly migrate all mentions of `Organization.subscription` to `Organization.stripe_customer.subscription`, we can start by using the new relationship to display the subscription information at https://github.com/readthedocs/readthedocs.org/blob/main/readthedocs/subscriptions/templates/subscriptions/subscription_detail.html.
We will keep updating our current models till we have completed migrated.

Another approach could be to have an intermediate model with a generic foreign key, something like:

```python
class Subscriber(models.Model):
    object = GenericForeignKey()
    customer = models.ForeignKey(stripe.models.Customer)
```

this way we have the same model for all type of subscribers, and we could attach some metadata if required.
But I think the first approach is enough for now.

**Comment by agjohnson** [comment]
@humitos :point_up: You're probably the best resource here

**Comment by humitos** [comment]
I'd go with the first approach as well. Generic foreign keys are usually too complicated/ambiguous. It seems the first approach covers exactly what we need and it's simpler.
