### ISSUE TITLE
After an update of the theme and rebuild, the initial theme still shows up on the project documentation starting page/homepage

### ISSUE THREAD

**Issue by han16nah** [readthedocs/readthedocs.org#9355]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pytreedb/g}/
* Build URL (if applicable): https://readthedocs.org/projects/pytreedb/builds/17220838/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/han16nah/

## Expected Result

I uploaded our project to ReadTheDocs for the first time. Our documentation was created with Sphinx. I then noticed that I prefer the default ReadTheDocs theme to the "nature" theme and changed this in `conf.py`. I then rebuilt the documentation on ReadTheDocs and expected to see the default theme now on all pages of the documentation, including the Starting page (https://pytreedb.readthedocs.io/).

## Actual Result

On the starting page (https://pytreedb.readthedocs.io/ or https://pytreedb.readthedocs.io/en/latest/), the old theme "nature" appears. Only when I switch to one of the pages (e.g. https://pytreedb.readthedocs.io/en/latest/index.html, https://pytreedb.readthedocs.io/en/latest/README.html), the default theme appears.

## Further questions

Can I solve this somehow myself? Was there something I did not consider?
In general, can I delete a project and then re-create it for the same GitHub repository or will this cause issues?

**Comment by humitos** [comment]
Hi @han16nah! I'm seeing the same theme in all the pages from that project. The theme used is Read the Docs' Theme (https://github.com/readthedocs/sphinx_rtd_theme). Is that the theme you want to use?

**Comment by han16nah** [comment]
Okay, cleaning the browser cache actually solved this, sorry for the confusion :D
