### ISSUE TITLE
pip install needs the --use-deprecated=legacy-resolver option

### ISSUE THREAD

**Issue by avaldebe** [readthedocs/readthedocs.org#9368]
## Details

My project builds are failing because one of the dependencies is incompatible with pip's new dependency resolver

https://readthedocs.org/projects/pyaerocom/builds/17248077/

The relevant parts of failed install step are:

```
/home/docs/checkouts/readthedocs.org/user_builds/pyaerocom/envs/686/bin/python -m pip install --upgrade --upgrade-strategy eager --no-cache-dir .[proj-legacy,docs]

[...]

WARNING: Requested cartopy!=0.20.*,>=0.16.0 from https://files.pythonhosted.org/packages/ed/ca/524ce33692df3faeaa56852fb6a33b0b410be94cc288417565b96fef3f64/Cartopy-0.19.0.post1.tar.gz#sha256=4b8b4773a98ed7009fe17d9b6ec87ac3ac62b7d14634d7768c190eadc647d576 (from pyaerocom==0.13.1.post1), but installing version 0.0
Discarding https://files.pythonhosted.org/packages/ed/ca/524ce33692df3faeaa56852fb6a33b0b410be94cc288417565b96fef3f64/Cartopy-0.19.0.post1.tar.gz#sha256=4b8b4773a98ed7009fe17d9b6ec87ac3ac62b7d14634d7768c190eadc647d576 (from https://pypi.org/simple/cartopy/) (requires-python:>=3.5): Requested cartopy!=0.20.*,>=0.16.0 from https://files.pythonhosted.org/packages/ed/ca/524ce33692df3faeaa56852fb6a33b0b410be94cc288417565b96fef3f64/Cartopy-0.19.0.post1.tar.gz#sha256=4b8b4773a98ed7009fe17d9b6ec87ac3ac62b7d14634d7768c190eadc647d576 (from pyaerocom==0.13.1.post1) has inconsistent version: filename has '0.19.0.post1', but metadata has '0.0'

[...]
```

On the CI of the project we work around the problem by adding the `--use-deprecated=legacy-resolver` option to `pip install` metno/pyaerocom#686.

I can see no way to customize the `pip install` command via configuration, or a way to downgrade the pip version so the `--use-deprecated=legacy-resolver` option is not needed.

## Expected Result

The install step succeed and is followed by the docs build step.

## Actual Result

The install step fails.

**Comment by humitos** [comment]
Hi! We don't support the `legacy-resolver`. Unfortunately, I don't think we will implement this since it's not going to be available going forward. If you _really_ need to work around this, you can take a look at https://docs.readthedocs.io/en/latest/build-customization.html. However, the proper solution here would be to fix the packages your project depend on to resolve properly with the new resolver.

I'm closing the issue, but feel free to re-open if there is any actionable from our side here.

**Comment by ekanpycoderx** [comment]
got an error of option --use-deprecated: invalid choice: 'backtrack-on-build-failures' (choose from 'legacy-resolver'). How to solve it?
