### ISSUE TITLE
Import manually: No branches available for newly created project

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#9369]
## Details

If we create a new project, there are no branches immediately visible. This means that it isn't possible for the user to change the value of "Default branch" after creating a new project with a blank default branch -- which fails as described in #9367

![image](https://user-images.githubusercontent.com/374612/175045489-a613a1ad-a275-4fb0-8370-c9ea6b478622.png)

* Read the Docs project URL: https://readthedocs.org/projects/example-sphinx-basic/
* Build URL (if applicable): https://readthedocs.org/projects/example-sphinx-basic/builds/17248339/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/benjaoming/

## Expected Result

A list of all branch names from public Github project should appear immediately when importing new projects manually.

## Actual Result

No branch names :cold_face:

**Comment by natefoo** [comment]
Is there a workaround for this issue other than deleting the project and starting over (and setting the branch name this time)? It seems like #9424 is probably a fix, but I don't know when that will be live.

**Comment by stsewd** [comment]
@natefoo you can create a temporal branch named master, after that all the versions should appear (if they don't, try triggering a build for master)

**Comment by natefoo** [comment]
@stsewd that worked, thanks!

**Comment by showierdata9978** [comment]
You could add a way to edit the branch added when you import manually (after the project is done)

**Comment by benjaoming** [comment]
@showierdata9978 you can consider [the workaround above](https://github.com/readthedocs/readthedocs.org/issues/9369#issuecomment-1183790993) :arrow_up:

**Comment by showierdata9978** [comment]
> @showierdata9978 you can consider [the workaround above](https://github.com/readthedocs/readthedocs.org/issues/9369#issuecomment-1183790993) ⬆️

ye, IK i just said that as a possible fix!

**Comment by benjaoming** [comment]
The underlying issue is that the empty dropdown is supposed to show a list of valid branches. But the list isn't populated when the initial default branch is unset and doesn't match `master`.

**Comment by showierdata9978** [comment]
maybe on import you could check if that branch exists, and if not show an error

**Comment by showierdata9978** [comment]
why is this not exposed on the project update form, it would solve this problem by adding a even better workaround 

https://github.com/readthedocs/readthedocs.org/blob/43ee207ccb2315cda89114ef37f184163836fc66/readthedocs/projects/forms.py#L83-L89****

**Comment by showierdata9978** [comment]
im trying to find the page for manual import, your codebase is just so dang huge

**Comment by showierdata9978** [comment]
found the js file

https://github.com/readthedocs/readthedocs.org/blob/43ee207ccb2315cda89114ef37f184163836fc66/readthedocs/projects/static-src/projects/js/import.js

**Comment by showierdata9978** [comment]
i need to find where the user inputs the default branch, and check if that branch exists on the VCS

**Comment by showierdata9978** [comment]
the amount of tabs i opened to find everything tho....

![image](https://user-images.githubusercontent.com/68120127/207977163-6357cfb1-1869-41fe-a877-246f485c11d7.png)

**Comment by benjaoming** [comment]
@showierdata9978 YES! The codebase for Read the Docs is a big one and is based on a decade of careful crafting and fiffling by a lot of people, so you are always welcome to ask questions.

Are you looking for a way to automatically fill in the branch name? I think that the approach taken has been to discover the default branch _after_ creating the project _if_ the branch name is left empty.

However, since the default branch name isn't discovered correctly, this approach fails. To fix it, I think that #9424 needs to move forwards.

@humitos would it be correct to assume that this issue will also be fixed by #9424?

Let's note in any case that this issue is closely related to #9367

**Comment by showierdata9978** [comment]
I was thinking of checking with the vcs provider to check if the branch
exists

**Comment by showierdata9978** [comment]
Where is the actual forum source code, I would be  able to make a fix if I knew that

**Comment by showierdata9978** [comment]
Note: a quick fix is to just got clone, without a selected branch, then do git branch and show that to the user

**Comment by benjaoming** [comment]
I think it sounds good to think of this as input validation. If a branch is specified, verify that it exists. If no branch is specified, automatically use the default branch.

In any case, VCS actions have to happen server-side. I'm not sure if JS is relevant here, couldn't this be handled entirely in form validation?

Using `git clone --depth 1` and then [this method](https://github.com/readthedocs/readthedocs.org/issues/9367#issuecomment-1209204921) to get the default branch might work.

**Comment by showierdata9978** [comment]
Ye, it could, js is relevant so I can trace it back lol

**Comment by showierdata9978** [comment]
why was this not used for validaion in the first place?

https://github.com/readthedocs/readthedocs.org/blob/af0d328db4f1b59648340640ebdeb9dd0cd12ed4/readthedocs/vcs_support/backends/git.py#L205

**Comment by showierdata9978** [comment]
found where it needs to be addedd

**Comment by showierdata9978** [comment]
also just found this file, it could work as a spot to put the validator

`readthedocs/projects/validators.py`

**Comment by showierdata9978** [comment]
ah, danget i cant use `in` because of the class `VCSVersion`

**Comment by showierdata9978** [comment]
came up with this

```py
    def __call__(self, vcs ,fourm):
        branch = fourm.fields['default_branch']
        project_url = fourm.fields['project_url']

        branches = vcs.branches

        # Cant optimise this as vcs.branches returns list[VCSVersion]

        branch_exists = False

        for remote_branch in branches:
            if branch == remote_branch.verbose_name:
                branch_exists = True
                break

        if not branch_exists:
            raise ValidationError("Default branch not found in VCS")
        
        return

**Comment by benjaoming** [comment]
@showierdata9978 are you able to test your approach in a development environment? There is information available here: https://dev.readthedocs.io/en/latest/install.html

**Comment by showierdata9978** [comment]
> @showierdata9978 are you able to test your approach in a development environment? There is information available here: https://dev.readthedocs.io/en/latest/install.html

i am not, i will be able to in ~1 hour as im not at home right now

**Comment by humitos** [comment]
This issue was solved by https://github.com/readthedocs/readthedocs.org/pull/9424 and it's going to be deployed today.

**Comment by tomwardio** [comment]
I just ran into this same issue when setting up a new project. Fortunately the workaround (creating a master branch and then deleting) fixed the issue, but it would appear this is still an issue?
