### ISSUE TITLE
Dark mode request

### ISSUE THREAD

**Issue by mendax1234** [readthedocs/readthedocs.org#9378]
Readthedocs is an awesome theme , but l think dark mode is a need bacause it can give user a better experience. l know that dark reader has done a great job ,but l also recommnad readthedocs team can add an original dark mode support to readthedocs theme. Thanks!

Best
Daniel

**Comment by humitos** [comment]
Hi @mendax1234! We already had a discussion about dark mode in #3819. Please, refer to that issue. I'm closing this as a duplicate.
