### ISSUE TITLE
Documentation Marked as Spam

### ISSUE THREAD

**Issue by westinhuang** [readthedocs/readthedocs.org#9386]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pydarm/
* Build URL (if applicable): 
* Read the Docs username (if applicable): https://readthedocs.org/profiles/hsiang-yu.huang/

## Expected Result

I am able to enter my project to make this build.

## Actual Result

After I fail to build a few times, it mark this project as spam

**Comment by siangyuhuang** [comment]
Yes. I used access token to clone private repo. to import into readthedocs.

**Comment by humitos** [comment]
@westinhuang The project is not marked as spam. Is there any actionable from our side here? Otherwise, I will close the issue.

**Comment by westinhuang** [comment]
> @westinhuang The project is not marked as spam. Is there any actionable from our side here? Otherwise, I will close the issue.

Yes. You can close this issue.
