### ISSUE TITLE
Include private pip dependency in build (mkdocs-material-insiders)

### ISSUE THREAD

**Issue by rfay** [readthedocs/readthedocs.org#9388]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/ddev/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/rfay/

## Expected Result

I would like to be able to include a private pip dependency (mkdocs-material-insiders, see https://squidfunk.github.io/mkdocs-material/insiders/) in a readthedocs project.  But there seems no way to specify this in a requirements.txt

## Actual Result

(Couldn't figure out how to do it)

**Comment by humitos** [comment]
I think this guide has the content you are looking for https://docs.readthedocs.io/en/stable/guides/private-python-packages.html

**Comment by rfay** [comment]
You're awesome, yes that works. Sorry I didn't find it. I had searched for "private", and I see that now when I search the docs. Thanks!

**Comment by rfay** [comment]
Hmm, it does say "This guide is for [Read the Docs for Business](https://docs.readthedocs.io/en/stable/commercial/index.html).", but it does seem to work with open-source readthedocs.

**Comment by humitos** [comment]
Yeah, it should work on both platforms. I'm not 100% sure why it says it's for Read the Docs for Business.  I guess that's because most projects on community use only public dependencies. We should probably remove that note, tho.
