### ISSUE TITLE
Build Failed due to unavailability of a module

### ISSUE THREAD

**Issue by Aaronphilip2003** [readthedocs/readthedocs.org#9395]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/observatory-project
* Build URL (if applicable): https://readthedocs.org/projects/observatory-project/builds/17330117/
* Read the Docs username (if applicable):https://readthedocs.org/profiles/Aaronphilip2003/

## Expected Result
Build astropy 5.0.2

*Successful build of the readthedocs project with all its dependencies including astropy 5.0.2*

## Actual Result
Build Failed
*A description of what actually happened*
Build #17330117
[latest](https://readthedocs.org/dashboard/observatory-project/version/latest/edit/) ([f914de11f66528b77e0a18473323a466736fb13a](https://github.com/Aaronphilip2003/Observatory-Documentation/commit/f914de11f66528b77e0a18473323a466736fb13a))
Build failed
Configure your documentation builds! Adding a [.readthedocs.yaml](https://docs.readthedocs.io/page/config-file/v2.html) file to your project is the recommended way to configure your documentation builds. You can declare dependencies, set up submodules, and many other great features.

Error
We encountered a problem with a command while building your project. To resolve this error, double check your project configuration and installed dependencies are correct and have not changed recently.

git clone --no-single-branch --depth 50 https://github.com/Aaronphilip2003/Observatory-Documentation .
git checkout --force origin/main
git clean -d -f -f
python3.7 -mvirtualenv /home/docs/checkouts/readthedocs.org/user_builds/observatory-project/envs/latest
/home/docs/checkouts/readthedocs.org/user_builds/observatory-project/envs/latest/bin/python -m pip install --upgrade --no-cache-dir pip setuptools<58.3.0
/home/docs/checkouts/readthedocs.org/user_builds/observatory-project/envs/latest/bin/python -m pip install --upgrade --no-cache-dir mock==1.0.1 pillow==5.4.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.8.1 recommonmark==0.5.0 sphinx sphinx-rtd-theme readthedocs-sphinx-ext<2.2
/home/docs/checkouts/readthedocs.org/user_builds/observatory-project/envs/latest/bin/python -m pip install --exists-action=w --no-cache-dir -r requirements.txt

 Installing build dependencies: started

*ERROR: No matching distribution found for astropy==5.0.2*

**Comment by humitos** [comment]
I think this happens because you are using Python 3.7 to build your documentation but `astropy==5.0.2` requires at least Python 3.8. See https://github.com/astropy/astropy/blob/v5.0.2/setup.cfg#L35

You should use `build.tools.python` in your config file to define the Python version, https://docs.readthedocs.io/en/stable/config-file/v2.html#build-tools-python
