### ISSUE TITLE
Language switcher does not appear for English project, but does for translated version.

### ISSUE THREAD

**Issue by drwhut** [readthedocs/readthedocs.org#9398]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/tabletop-club/
* Build URL (if applicable): https://readthedocs.org/projects/tabletop-club/builds/17344860/
* Read the Docs username (if applicable): drwhut

I added a Russian translation of my documentation following [this guide](https://docs.readthedocs.io/en/stable/localization.html), and while the translated documentation appears to work and can be accessed, I noticed it could not be accessed from the English docs.

The language switcher does not appear in the English project, but strangely it does for the Russian project. I had also tried building the English docs again after adding the Russian project as a translation, but this has not fixed the issue.

## Expected Result
The language switcher should appear for both the English docs and the Russian docs.

## Actual Result
The language switcher only appears for the Russian docs.

A screenshot from [the English version](https://tabletop-club.readthedocs.io/en/latest/):
![Screenshot from 2022-07-03 21-59-15](https://user-images.githubusercontent.com/13645454/177057147-9e411f8d-6955-4a0b-8cf3-16dbd833a2db.png)

A screenshot from [the Russian version](https://tabletop-club.readthedocs.io/ru/latest/):
![Screenshot from 2022-07-03 21-59-26](https://user-images.githubusercontent.com/13645454/177057155-91d15868-c87b-4d91-a552-e844773beafd.png)

**Comment by humitos** [comment]
This was probably a cache issue.

I can see the EN and RU languages when I go to https://tabletop-club.readthedocs.io/en/latest/ and https://tabletop-club.readthedocs.io/ru/latest/
