### ISSUE TITLE
Build failed in RTD

### ISSUE THREAD

**Issue by forestbat** [readthedocs/readthedocs.org#9399]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/waterdoc/
* Build URL (if applicable): https://readthedocs.org/projects/waterdoc/builds/17337182/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/forestbat/

https://github.com/mkdocs/mkdocs/issues/2877
https://github.com/mkdocs/mkdocs/issues/2878
See this two issues，why readthedocs occured an old problem which is fixed in mkdocs？

**Comment by humitos** [comment]
Hi @forestbat! You can specify the version of MkDocs you want to use by adding it as a requirement for your docs. See https://docs.readthedocs.io/en/stable/guides/specifying-dependencies.html

We are installing an old version by default for reasons, but we want to stop doing that in the near future.
