### ISSUE TITLE
Translation language codes not showing in flyout

### ISSUE THREAD

**Issue by azvoleff** [readthedocs/readthedocs.org#9406]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/trendsearth/
* Build URL (if applicable): https://trends.earth

## Expected Result

The `trendsearth` project is meant to be generated both in English and in a number of translations. When the translations are generated, the appropriate language codes should show up in the flyout menu so a user can link to those pages.

## Actual Result

When I build the docs for the `trendsearth` project the two letter language code links to the translated versions of the documentation do not show in the flyout menu (for example see the flyout menu [here](https://trends.earth/en/latest/)). The translated versions of the project ARE generated and the pages do show up correctly when I link to them directly (for example [ES](https://trends.earth/es/latest/) and [PT](https://trends.earth/pt/latest/)). However the flyout menu doesn't seem to generate properly as it doesn't list any language codes.

I'm not sure if this is related or a different issue, but the "Downloads" links also do not appear in the flyout even though I have chosen for them to be generated on the project's settings page.

For some reason the flyout does show correctly on pull request builds, [for example this one](https://trendsearth--666.org.readthedocs.build/en/666/), which makes me wonder if it is an issue with the docs being served from a custom domain (since the pull request build in the above link is being served from a readthedocs.build subdomain)?

**Comment by stsewd** [comment]
Hi, looks like the API is returning 404 from your domain

https://trends.earth/_/api/v2/footer_html/?project=trendsearth&version=latest

but it works from outside your domain

https://docs.readthedocs.io/_/api/v2/footer_html/?project=trendsearth&version=latest

In fact, looks like all proxied APIs don't work on your domain.

Did you follow the steps from https://docs.readthedocs.io/en/stable/custom-domains.html#adding-a-custom-domain? especially the part about using an ANAME or ALIAS record

**Comment by humitos** [comment]
@azvoleff I'd recommend you to disable "canonical domain" on your project and take a look if everything works fine in trendsearth.readthedocs.io domain. That check will tell you if the problem is on your AWS setup.

**Comment by ericholscher** [comment]
@azvoleff I'd recommend using a non-root domain for this, which is a supported use case. It's likely your proxy will break if you try to do something custom, and we aren't able to support it.

**Comment by azvoleff** [comment]
Thanks, I confirmed a subdomain ([https://docs.trends.earth](https://docs.trends.earth)) works fine. The downloads still aren't showing, but I assume that is a separate issue - so I'll look into it further and post a separate issue if need be.

**Comment by humitos** [comment]
@azvoleff downloads are not showing because there is no artifacts built yet. See https://readthedocs.org/projects/trendsearth/downloads/

**Comment by azvoleff** [comment]
Thanks @humitos. I've had both PDF and EPUB builds enabled for several weeks but the builds don't seem to trigger. Is there something else I need to do? The build logs always end in the HTML build and I don't see anything triggering for PDF/EPUBs.

**Comment by stsewd** [comment]
@azvoleff you need to enable the formats in your configuration file, see https://docs.readthedocs.io/en/stable/config-file/v2.html#formats.
