### ISSUE TITLE
Docs: write a "How to do docs-as-code with Read the Docs" guide

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#9412]
It would be good to mention the "Documentation As Code" concept in our documentation more.

There are some good websites covering these topics already that we can use as a guide for our how-to:

* https://docs-as-co.de/
* https://www.docslikecode.com/

**Comment by benjaoming** [comment]
This is a really good idea! I have experience where people's entry-point wasn't about Read the Docs or Sphinx or API docs... but "Documentation as Code" - I think it has a very strong position in the minds of people who are used to writing documentation that *isn't* code, like Confluence, Word, Wikis etc.. stuff that's database-driven.

This is also relevant for landing pages.

**Comment by humitos** [comment]
We've publish this content at https://about.readthedocs.com/docs-as-code/
