### ISSUE TITLE
Redirects: allow editing of redirects

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#9418]
Currently, redirects cannot be edited. The view and forms should allow for editing, and we should add a form view and UI in addition to the existing views. I don't think we have any reason for keeping redirects immutable, so this seems like it might have been an oversight or a set of views that was never updated.

**Comment by ericholscher** [comment]
Putting this in the sprint, because we got bogged down with a grand redirects project. Let's just start making the current version better in obvious ways..

**Comment by SimonBiggs** [comment]
Thanks @ericholscher :slightly_smiling_face:

**Comment by SimonBiggs** [comment]
> Let's just start making the current version better in obvious ways for now :)

Also, I know it's potentially a significant difference but the following approach has the potential to be quite powerful:

> Another alternative, is that we do have the capacity for the redirects to be defined within the `readthedocs.yml`, but we make it so that only the `readthedocs.yml` within the `main` default branch is utilised for these "project level" configuration items.

**Comment by agjohnson** [comment]
> There is a huge maintenance benefit in having the redirects defined within the repository's version control

We definitely all would like to see this eventually, but this is actually the point that we wrestled with the most. The experience around putting per-project redirects in a per-version configuration is quite awkward.

But, if you are looking for an immediate way to accomplish this, this is an interesting community project that I've pointed folks towards in the past:

https://pypi.org/project/readthedocs-cli/

It uses our API and a file you can check in to your repository to manage redirects.

> Also, if there was capacity for a regex based redirect (with group resolution)

Regex rules have always seemed like a really obvious experience here, but we've had unfortunate experiences implementing similar advanced rules in the past. One constraint we have here is that redirects get evaluated in our 404 handling. Coupled with a moderate amount of malicious/bot scans, activating 404 handling, regex rules and complex conditional rules have strong potential to overwhelm our web servers.

**Comment by SimonBiggs** [comment]
> regex rules and complex conditional rules have strong potential to overwhelm our web servers.

Yup, fair point.

I wonder if regex resolutions only happen just prior to 404, as in all other redirects run first, and, any time a redirect based on a regex is found, then it is cached. And those cached redirects are utilised prior to any regex being utilised. The regex cache gets invalidated if the maintainer changes the original regex. And then, on top of that, implement a quota on the number of "new regex resolutions" that one documentation base url can handle globally in a given second.

Might something like that have a chance to work?

> But, if you are looking for an immediate way to accomplish this, this is an interesting community project that I've pointed folks towards in the past:
> 
> https://pypi.org/project/readthedocs-cli/

I will definitely check that out! Thank you! :slightly_smiling_face:

**Comment by ssbarnea** [comment]
Please make this happen. Putting this configuration inside the default repository branch is the normal approach, same taken by other automation systems that had the same dilemma, examples github actions and zuul ci, on both the main branch has more authority than others and there are specific configuration options that must happen first on default branch before the build system would use them.

**Comment by TheTripleV** [comment]
With editable redirects and an api for it now, is there a plan for version level redirects? That would be really useful and is the main reason for https://github.com/wpilibsuite/sphinxext-rediraffe . Project level redirects are just infeasible for versioned documentation. As links for multiple versions pop up on Google, with only project level redirects, links to old versions will break as the "new" paths won't exist.

**Comment by ericholscher** [comment]
@TheTripleV We do support version-level redirects here: https://docs.readthedocs.io/en/stable/user-defined-redirects.html#page-redirects -- but they apply to all versions. Can you clarify the exact redirect you'd like to see, and how it would be configured?
