### ISSUE TITLE
GitHub Pull Request integration: No checks shown on GH project, no builds shown in RTD

### ISSUE THREAD

**Issue by rfay** [readthedocs/readthedocs.org#9422]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/ddev/
* Build URL (if applicable): https://readthedocs.org/projects/ddev/builds/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/rfay/

## Expected Result

* With PR builds enabled in project settings "Build pull requests for this project" and VCS integration enabled on the user, I should see 
  * a GitHub check on the PR
  * I should see a build happen in RTD.  

## Actual Result

No Github Check (https://github.com/drud/ddev/pull/3980) and no builds on ReadTheDocs, https://readthedocs.org/projects/ddev/builds/

Since this project is many years old, I removed the old GitHub webhook integration and re-added it to try to solve this, but that doesn't seem to have done anything.

Thanks so much for your help! This will be an awesome feature and will significantly improve our docs dev workflow.

**Comment by humitos** [comment]
@rfay hi! Have you checked this section of the docs already? https://docs.readthedocs.io/en/latest/pull-requests.html#troubleshooting

**Comment by rfay** [comment]
Thanks @humitos - It looks like that should be a help, and it looks like although my personal github has the oauth app connected and set up, the org account (drud) does not. I poked around and didn't figure out how to connect the drud org account to oauth. How do you connect an org account as opposed to personal? If I "disconnect" the rfay connected service, and then "connect to github" it immediately connects rfay again.  I assume I have to get it to connect to the org for this to work?

**Comment by humitos** [comment]
@rfay I'm not sure to 100% follow here, but you can connect any GH account you are logged into.

If you want to connect the "drud" account, just logout from the other and login in GH with "drud" account. Then connect it from the users settings on RTD

(I'm from the phone -we can talk more on Monday, tho)

**Comment by rfay** [comment]
Thanks @humitos, thanks so much - maybe I'm having a brain fart here, but [drud](https://github.com/drud) is an org, and I can't log into RTD with an org... because it's not an account. 

* The open-source project where we want PRs to create RTD builds is https://github.com/drud/ddev
* The admin of the drud org is rfay, who has an account on RTD where the builds happen, https://readthedocs.org/profiles/rfay/
* PRs are almost always forked PRs

**Comment by humitos** [comment]
@rfay 

* can you confirm there is a webhook set up on the GH repository pointing to Read the Docs with the `pull_request` event enabled?
* can you confirm in the GH webhook's log that they are being sent to Read the Docs?
* can you confirm from the Read the Docs webhook logs that they are being received?

**Comment by rfay** [comment]
Hi @humitos - thanks. As mentioned above, these hooks are on the rfay account. Both default-branch pushes on the rfay account and default-branch pushes on the drud (org) account work fine and cause a build on RTD.

* Here's the webhook. It works fine and consistently to trigger a build. As I mentioned it above, I removed and created it anew. 
<img width="1151" alt="Webhooks" src="https://user-images.githubusercontent.com/112444/178268447-0dc6f129-9c2b-4e73-b8fc-10dff80d6836.png">

<img width="776" alt="Webhook_·_https___readthedocs_org_api_v2_webhook_test-ddev_99139_" src="https://user-images.githubusercontent.com/112444/178268656-6d5fcd38-7325-4061-b22b-ee149a0f6613.png">

* Recent deliveries
<img width="910" alt="Webhook_·_https___readthedocs_org_api_v2_webhook_test-ddev_99139_" src="https://user-images.githubusercontent.com/112444/178268786-02195c05-785a-4cca-b615-e13098de87b7.png">

* RTD receiving: Since every push results in a build... I guess they are.

**Comment by humitos** [comment]
@rfay I'm not sure to follow you. The problem is solved, then, right?

**Comment by rfay** [comment]
It's working now, and the configuration of the drud/ddev webhook was the missing piece. I thought that the Connected Services (https://readthedocs.org/accounts/social/connections/) was where these things get set up. And the doc seems to imply that.

But it's actually the *integrations* on the project, https://readthedocs.org/dashboard/ddev/integrations/ that's the issue. And of course, the webhook for drud/ddev was set up probably 6 years ago or more, so didn't have the PR checkbox. 

I do think the docs should mention the webhook...

Thanks for your help!
