### ISSUE TITLE
Search: race condition/bad state in the index task

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#9431]
A couple of things can go wrong here

https://github.com/readthedocs/readthedocs.org/blob/f87e99f46662bd8bf0613a99814899c7066a79ee/readthedocs/projects/tasks/search.py#L46-L65

- A race condition if more than one index tasks are running for the same version at the same time.
  
  One task will be deleting the HTML files that aren't part of the current build

  https://github.com/readthedocs/readthedocs.org/blob/efdb6335b715a38a5b0f5bb9d0fe6cf6771ed145/readthedocs/projects/tasks/search.py#L90-L104

  And the other task will be trying to use those objects (html_file)

   https://github.com/readthedocs/readthedocs.org/blob/efdb6335b715a38a5b0f5bb9d0fe6cf6771ed145/readthedocs/projects/tasks/search.py#L226-L229

- Bad state: If any of these two fail

  https://github.com/readthedocs/readthedocs.org/blob/efdb6335b715a38a5b0f5bb9d0fe6cf6771ed145/readthedocs/projects/tasks/search.py#L47-L53
  
  https://github.com/readthedocs/readthedocs.org/blob/efdb6335b715a38a5b0f5bb9d0fe6cf6771ed145/readthedocs/projects/tasks/search.py#L58

  The task will continue to

  https://github.com/readthedocs/readthedocs.org/blob/efdb6335b715a38a5b0f5bb9d0fe6cf6771ed145/readthedocs/projects/tasks/search.py#L63

  and delete everything that isn't part of the current build, this will result in an empty index for that version (no search results!)

**Comment by ericholscher** [comment]
@stsewd Is there a proposed solution to this?

**Comment by ericholscher** [comment]
Cool, moving off roadmap them 👍

**Comment by ericholscher** [comment]
I am actually going to just close this, if we don't think it's a priority to fix it. We can always work on it again if we have a user hit it.
