### ISSUE TITLE
Bold bullets are rendering differently on RTD than locally

### ISSUE THREAD

**Issue by AnotherSamWilson** [readthedocs/readthedocs.org#9434]
## Details

The latest build [here](https://miceforest.readthedocs.io/en/latest/) renders the 3 main bullets (Fast, Flexible, Production Ready) like this:
![image](https://user-images.githubusercontent.com/44655289/179301693-8c1134e7-fb80-436c-99a5-e13c509842c0.png)

However, locally, it renders correctly:
![image](https://user-images.githubusercontent.com/44655289/179301831-c73ba0e8-0ee0-4d56-988c-d5c821ba1154.png)

Here is a link to the rst in question:
https://raw.githubusercontent.com/AnotherSamWilson/miceforest/master/docs/index.rst

I have checked to make sure that sphinx is running the same version locally and on RTD. I would rather not keep pushing commits trying to fix the issue - is there anything obvious I am missing?

**Comment by humitos** [comment]
Quick reply from the phone: make sure the version of "docutils" is the same.

**Comment by AnotherSamWilson** [comment]
Hmmm this did not work unfortunately. Using docutils 0.17.1 locally and on RTD. Here's a crazy idea - should I just copy my local virtual environment requirements.txt file to the docs requirements.txt, with the obvious packages removed? I am not sure which packages might be causing the problem, if any. Are there any obvious problems with doing this?

**Comment by AnotherSamWilson** [comment]
Well... That worked. requirements file:
https://github.com/AnotherSamWilson/miceforest/blob/c41f797d7a48a6be6c59eef0eb3e6b65e4783d87/docs/requirements.txt
