### ISSUE TITLE
Docs: add custom build example for Docsify

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#9435]
This is maybe a potential target for an example of build customization, to use a tool that isn't Sphinx/Mkdocs.

Docsify is a rather minimal docs tool that is fairly popular. It renders markdown directly, instead of generating output files. To use docsify, you just copy the `docs/` path into our output path.

https://github.com/agjohnson/test-builds/commit/b68fb82e14cad39c6efaa6b00224b9eefe0b9a22

**Comment by humitos** [comment]
I like the idea! I will add an example to this section https://docs.readthedocs.io/en/latest/build-customization.html#override-the-build-process

**Comment by agjohnson** [comment]
I'd also be +1 on doing this with any number of tools -- Pelican, maybe site generators like Hugo? Just something to spark some interest in using RTD for non-Sphinx projects.

These could me interesting blog posts or site resources also.

Anyways, this isn't a super high priority item, but could be a small step forward on build customization.

**Comment by humitos** [comment]
I'm going to close this issue because the initial work was done in #9439 

Besides, we are deciding what are those other doctools we want to promote in https://github.com/readthedocs/meta/discussions/35. We can open specific issues for particular tasks if we want, tho.
