### ISSUE TITLE
Environment variables not available when overriding build

### ISSUE THREAD

**Issue by agoose77** [readthedocs/readthedocs.org#9438]
I'm working on documenting a project that will require long build times (exceeding available time on RTD). We already use GitHub Actions to build the necessary assets, and I'd hoped to build the documentation on the CI as well. In order to connect to RTD, my plan was to trigger a build on RTD via webhook, and have RTD pull the assets from the GitHub Actions Workflow. This requires a custom build process (`build.commands`).

Unfortunately, I observed that the access token I'd added to the environment variables in the project settings was not exposed to the builder logic. Here's a build that demonstrates the problem:

(`SPECIAL_TOKEN` is not visible in the output of `env` in this build)

https://readthedocs.org/projects/test-ccache-gha/builds/17481074/

Apologies that this is so terse, and thanks for all of the hard work!

**Comment by agjohnson** [comment]
I hit this today as well. I made a test-build test case to test it at https://github.com/readthedocs/test-builds/pull/2091

**Comment by agoose77** [comment]
@agjohnson what are the odds! Thanks for making a cleaner test case.

**Comment by humitos** [comment]
Hi! The fix for this issue was already deployed. I did a quick test in https://readthedocs.org/projects/test-builds/builds/17604894/ and I can see my variable there. Let me know if this works for you!
