### ISSUE TITLE
PyPy repo integration (via heptapod web hook) stopped building automatically

### ISSUE THREAD

**Issue by mattip** [readthedocs/readthedocs.org#9455]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pypy/ and https://readthedocs.org/projects/rpython
* Build URL (if applicable): https://readthedocs.org/projects/{your_project_slug}/builds/{build_id}/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/mattip/

## Expected Result

There is a web hook registered with the repo stored on https://foss.heptapod.net/pypy/pypy. Heptapod is a gitlab fork that can work with mercurial. Triggering the builds manually works fine.

## Actual Result

It is triggering a 403 and is not triggering the build. 

<details>

Response
403

{"detail":"Authentication credentials were not provided."}

Headers

Date: Wed, 27 Jul 2022 10:45:09 GMT
Content-Type: application/json
Content-Length: 58
Connection: close
Allow: POST, OPTIONS
Vary: Accept, Accept-Language, Cookie
Referrer-Policy: strict-origin-when-cross-origin
Content-Security-Policy: object-src 'none'; frame-ancestors 'none'; block-all-mixed-content
X-Frame-Options: DENY
X-Content-Type-Options: nosniff
X-Xss-Protection: 1; mode=block
Content-Language: en
Strict-Transport-Security: max-age=31536000;
X-Backend: web-i-0f073571b24489920
Cf-Cache-Status: DYNAMIC
Expect-Ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
Cf-Ray: 7314c8adeb003ba9-CDG

Request

{
  "object_kind": "push",
  "event_name": "push",
  "before": "7f468a6d850be8a1d0a3c1867cf8d9b661051144",
  "hg_before": "05f9300568e91aa985f7a051ad82545a33a35efa",
  "hg_after": "97aea389af338c9a65abf81171080a4c6f2060c6",
  "after": "4b0fe910e7692ae24f79daf3c0c2a656940566a7",
  "ref": "refs/heads/branch/default",
  "checkout_sha": "4b0fe910e7692ae24f79daf3c0c2a656940566a7",
  "checkout_hgsha": "97aea389af338c9a65abf81171080a4c6f2060c6",
  "message": null,
  "user_id": 38,
  "user_name": "Matti Picus",
  "user_username": "mattip",
  "user_email": "",
  "user_avatar": "https://secure.gravatar.com/avatar/72f994ca072df3a3d2c3db8a137790fd?s=80&d=identicon",
  "project_id": 76,
  "project": {
    "id": 76,
    "name": "pypy",
    "description": "PyPy is a very fast and compliant implementation of the Python language.",
    "web_url": "https://foss.heptapod.net/pypy/pypy",
    "avatar_url": "https://foss.heptapod.net/uploads/-/system/project/avatar/76/favicon2.png",
    "git_ssh_url": "ssh://hg@foss.heptapod.net/pypy/pypy",
    "git_http_url": "https://foss.heptapod.net/pypy/pypy",
    "namespace": "PyPy",
    "visibility_level": 20,
    "path_with_namespace": "pypy/pypy",
    "default_branch": "branch/default",
    "ci_config_path": null,
    "homepage": "https://foss.heptapod.net/pypy/pypy",
    "url": "ssh://hg@foss.heptapod.net/pypy/pypy",
    "ssh_url": "ssh://hg@foss.heptapod.net/pypy/pypy",
    "http_url": "https://foss.heptapod.net/pypy/pypy"
  },
  "commits": [
    {
      "id": "4b0fe910e7692ae24f79daf3c0c2a656940566a7",
      "message": "resync _vmprof with vmprof-python\n",
      "title": "resync _vmprof with vmprof-python",
      "timestamp": "2022-07-27T13:44:50+03:00",
      "url": "https://foss.heptapod.net/pypy/pypy/-/commit/4b0fe910e7692ae24f79daf3c0c2a656940566a7",
      "author": {
        "name": "Matti Picus",
        "email": "matti.picus@gmail.com"
      },
      "added": [

      ],
      "modified": [
        "rpython/rlib/rvmprof/src/shared/_vmprof.c",
        "rpython/rlib/rvmprof/src/shared/vmprof_config.h",
        "rpython/rlib/rvmprof/src/shared/vmprof_getpc.h"
      ],
      "removed": [

      ],
      "hgid": "97aea389af338c9a65abf81171080a4c6f2060c6"
    }
  ],
  "total_commits_count": 1,
  "push_options": {
  },
  "repository": {
    "name": "pypy",
    "url": "ssh://hg@foss.heptapod.net/pypy/pypy",
    "description": "PyPy is a very fast and compliant implementation of the Python language.",
    "homepage": "https://foss.heptapod.net/pypy/pypy",
    "git_http_url": "https://foss.heptapod.net/pypy/pypy",
    "git_ssh_url": "ssh://hg@foss.heptapod.net/pypy/pypy",
    "visibility_level": 20
  }
}

Headers

Content-Type: application/json
User-Agent: GitLab/14.10.5
X-Gitlab-Event: Push Hook
X-Gitlab-Token: XXXXXXXXXXXXXXXXXXXXXXXX
X-Gitlab-Event-UUID: XXXXXXXXXXXXXXXXXXX

**Comment by stsewd** [comment]
Hi, I don't see that your project has a `GitLab` integration, it has a Bitbucket and a generic one, did you delete the GitLab one?

**Comment by mattip** [comment]
I deleted the inactive bitbucket one. When I try to add a gitlab hook, I get an message
```
This integration is not managed by Read the Docs currently. If this integration is not functioning correctly, you can try re-syncing it. Otherwise you'll need to update the configuration on your repository. You can use the following address to manually configure this webhook.

[readthedocs.org/api/v2/webhook/pypy/208339/](https://readthedocs.org/api/v2/webhook/pypy/208339/)

For more information on manually configuring a webhook, refer to our webhook documentation
```

I am not sure what I am supposed to do. The generic hook worked until two months ago.

**Comment by stsewd** [comment]
> I am not sure what I am supposed to do.

You need to add that webhook to your project on heptapod.

> The generic hook worked until two months ago.

If you were using the generic integration, then the payload that you posted isn't compatible with the expected from the generic integration, see https://docs.readthedocs.io/en/stable/integrations.html#using-the-generic-api-integration, so if you were always sending that same payload, the generic integration should never have worked. I think something must have changed in your project on heptapod that removed/changed the old webhook.

**Comment by mattip** [comment]
OK.
How do I enable the gitlab webhook? I added https://readthedocs.org/api/v2/webhook/pypy/208339 to the heptapod (gitlab) web hooks for my project, but when I test it I get `Hook executed successfully but returned HTTP 405 {"detail":"Method \"GET\" not allowed."}`. Don;t I need a token?

**Comment by stsewd** [comment]
@mattip I'm not sure if it's the same, but these are the instructions for GitLab https://docs.readthedocs.io/en/stable/integrations.html#gitlab.

**Comment by stsewd** [comment]
I'm closing this, since it doesn't look like a problem with rtd, but with the heptapod integration.

**Comment by paugier** [comment]
Note that integration between Heptapod and RTD now works fine.

- On RTD: integrations on the project setting page (for example https://readthedocs.org/dashboard/fluiddyn/integrations/), add a webhook for generic API.

- On Heptapod: Integration setting on the project (for example https://foss.heptapod.net/fluiddyn/fluiddyn/-/settings/integrations), use the Read the Docs integration and copy the webhook data obtained from RTD.
