### ISSUE TITLE
No downloadable content

### ISSUE THREAD

**Issue by PierreMarchand20** [readthedocs/readthedocs.org#9474]
## Details

* Read the Docs project URL: https://htool-documentation.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/htool-documentation/builds/15613076/
* Read the Docs username (if applicable):PierreMarchand20

I noticed that since the last succeeded build of my project (https://readthedocs.org/projects/htool-documentation/builds/15613076/), there is no downloadable content (pdf, epub,...). The only difference I saw with the previous succeeded build was that I added a config file where I did not mention anything about format.

Just in case, I added a format configuration for pdf in https://github.com/htool-ddm/htool_documentation/blob/master/.readthedocs.yaml#L12, it seems to build [here](https://readthedocs.org/projects/htool-documentation/builds/17625973/). But I still have no downloadable content.

## Expected Result

I should get downloadable content.

## Actual Result

There is nothing in download.

**Comment by stsewd** [comment]
Hi, I'm able to see the download here https://readthedocs.org/projects/htool-documentation/downloads/ and in your docs
![Screenshot 2022-08-04 at 11-46-07 Htool – Parallelised hierarchical matrices — Htool 1 0 0 documentation](https://user-images.githubusercontent.com/4975310/182905889-b6515115-bb1f-4d4a-8b48-3b1de3d85f42.png)

And yes, when using a config file, you need to specify the formats you want to build, by defatul it's empty.

**Comment by PierreMarchand20** [comment]
Interesting, I do see it on safari on my mobile, but not on my laptop even if I reload the page, unless I use use private mode. Anyway, thank you for your answer, I guess this is more related to some cache issue with my browser.
