### ISSUE TITLE
Add blacken-docs to pre-commit hooks (and blacken docs)

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#9502]
While waiting for pre-commit hooks and Black to be added (and indeed run for the entire code base to be blackened), we can test out this pre-commit hook:

https://github.com/asottile/blacken-docs

To fix the issue:

* Add the hook to the pre-commit config over in https://github.com/readthedocs/common/blob/main/pre-commit-config.yaml
* Run blacken-docs on all files (but please don't run all hooks on all files)

**Comment by ArhyaSaha** [comment]
Hi I am starting my open source journey!
Would love to be able to contribute on this.

Can you assign me this issue?

**Comment by ArhyaSaha** [comment]
`-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==22.6.0]`

 Also, will adding this over in https://github.com/readthedocs/common/blob/main/pre-commit-config.yaml solve the issue?

**Comment by benjaoming** [comment]
Hi @ArhyaSaha - this issue should ideally be solved in the two steps outlined above. I would recommend opening up a PR on the `common` repo and then link it to a PR on the `readthedocs.org` repo (this one) that shows the results of running `--all-files` (should only affect `docs/` of course).

One more thing: The `common` module is shared between several repositories (hence the name). I think that you can assume that documentation always lives in a `docs/` folder.

**Comment by ArhyaSaha** [comment]
Hi @benjaoming I am unable to run the pre-commit hook in my local repo. It gives me an error. 

An error has occurred: InvalidConfigError: 
==> File .pre-commit-config.yaml
=====> Expected a Config map but got a str

I cloned the `readthedocs.org` repo and also cloned the `common` repo and moved it in place of the `common` folder in the `readthedocs.org` repo. After that I also made sure to install pre-commit. Then I added the code i suggested above(previous comment) in https://github.com/readthedocs/common/blob/main/pre-commit-config.yaml . When I try to run the pre-commit hooks it gives me the mentioned error.

How should i move forward with this? Please guide me.

**Comment by ArhyaSaha** [comment]
Hi @benjaoming. I tried setting up my environment as mentioned in the docs. I am not able to build docker image for the servers as it gives me an error when I run the given command. 
The error might be because I am on a windows platform. 
Is there any other way i can set up my local environment for this issue?

**Comment by benjaoming** [comment]
Hi @ArhyaSaha - you strictly speaking won't need this environment to contribute this change. It is only affecting `docs/`, so you should be able to change the pre-commit configuration and run that without ever running Read the Docs itself...

**Comment by ArhyaSaha** [comment]
@benjaoming So i cloned the `readthedocs.org` repo and installed the requirements from the `common` submodule. Then i added the lines in `.pre-commit-config.yaml` and it gives me an error.

An error has occurred: InvalidConfigError: 
==> File .pre-commit-config.yaml
=====> Expected a Config map but got a str

Please guide me on how to solve this issue.

**Comment by benjaoming** [comment]
You'd have to figure that one out by carefully reading your config file and comparing it to what pre-commit expects.

**Comment by dojutsu-user** [comment]
Hi @benjaoming,
Taking this up.

**Comment by razor-vg** [comment]
Hi @benjaoming,

While the team is reviewing the PRs, is it possible to redirect me to some other issue.

**Comment by dojutsu-user** [comment]
Hi @benjaoming 
While the team is reviewing the PRs, is it possible to redirect me to some other issue?

**Comment by dojutsu-user** [comment]
@benjaoming Can you also help me with `hacktoberfest-accepted` badges on the PRs.

**Comment by benjaoming** [comment]
Yes, I think that we can add a "hacktoberfest-accepted" label and that should be enough :+1:  https://blog.shahednasser.com/hacktoberfest-2022-everything-you-need-to-know-to-participate/
