### ISSUE TITLE
Strange behavior during building docstrings

### ISSUE THREAD

**Issue by DenisSidoren** [readthedocs/readthedocs.org#9506]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/fedot/
* Build URL (if applicable): https://readthedocs.org/projects/fedot/builds/17805926/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/Denis_Sidorenko/
* Working branch of the project: https://github.com/nccr-itmo/FEDOT/tree/docstrings

## Expected Result

Biult documntations by docstrings

## Actual Result

Currently, Google-style docstrings can not be built, for example this [file](https://github.com/nccr-itmo/FEDOT/blob/docstrings/fedot/api/main.py) looks like this page [page in Read the Docs](https://fedot--807.org.readthedocs.build/en/807/api/api.html)

At this time, spinx-style docsrtings have strange behavior: same style docstrings in this [one](https://github.com/nccr-itmo/FEDOT/blob/docstrings/fedot/utilities/profiler/memory_profiler.py) and the [second one](https://github.com/nccr-itmo/FEDOT/blob/docstrings/fedot/utilities/profiler/time_profiler.py) were union by Restructured text in the [file](https://github.com/nccr-itmo/FEDOT/blob/docstrings/docs/source/api/profiler.rst) and finally it looks like [this](https://fedot--807.org.readthedocs.build/en/807/api/profiler.html) - only one file was built.

**Comment by stsewd** [comment]
Hi, I see lots of warnings in your build (you can click on each command to see the output)

> * ImportError: cannot import name 'NoneType' from 'types' (/home/docs/checkouts/readthedocs.org/user_builds/fedot/envs/807/lib/python3.7/types.py)
> * AttributeError: module 'fedot.core.operations' has no attribute 'model'

Make sure you are using the same python version and requirements on rtd as you have locally, and also make sure to use a path relative to the conf.py file, not the CWD.

https://github.com/nccr-itmo/FEDOT/blob/0fe7146d712f346d681d6952c38ffeae1d8d1f4d/docs/source/conf.py#L16

see https://github.com/readthedocs/readthedocs.org/issues/8105#issuecomment-820610813

**Comment by DenisSidoren** [comment]
@stsewd  thanks a lot! I've fixed warnings, changed path and it works now
