### ISSUE TITLE
Exact Redirect between version doesn't work without slash 

### ISSUE THREAD

**Issue by jcfr** [readthedocs/readthedocs.org#9507]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/slicer/

## Expected Result

We are currently building documentation associated with branch [Slicer@5.0](https://github.com/Slicer/Slicer/tree/5.0) and setup an `Exact Redirect` from `/en/v5.0/$rest` -> `/en/5.0/`

![image](https://user-images.githubusercontent.com/219043/184954118-ef1f7568-98fe-4bd2-8973-44c033897f42.png)

And we were expecting the following to work:

| from URL | to URL |
|--|--|
| https://slicer.readthedocs.io/en/v5.0  | https://slicer.readthedocs.io/en/5.0 |
| https://slicer.readthedocs.io/en/v5.0/  | https://slicer.readthedocs.io/en/5.0/ |
| https://slicer.readthedocs.io/en/v5.0/user_guide/modules/transforms.html  | https://slicer.readthedocs.io/en/5.0/user_guide/modules/transforms.html |

## Actual Result

Here is what we observe:

| from URL | to URL | Status |
|--|--|--|
| https://slicer.readthedocs.io/en/v5.0  | https://slicer.readthedocs.io/en/5.0 | :x: |
| https://slicer.readthedocs.io/en/v5.0/  | https://slicer.readthedocs.io/en/5.0/ | :heavy_check_mark:  |
| https://slicer.readthedocs.io/en/v5.0/user_guide/modules/transforms.html  | https://slicer.readthedocs.io/en/5.0/user_guide/modules/transforms.html | :heavy_check_mark:  |

Setting up the additional redirect `Exact Redirect` from `/en/v5.0` -> `/en/5.0` didn't help either.

![image](https://user-images.githubusercontent.com/219043/184954533-3ebbcd6d-78ef-4f33-b0b3-c1ea9b74bd61.png)

And there are still observing the following:

| from URL | to URL | Status |
|--|--|--|
| https://slicer.readthedocs.io/en/v5.0  | https://slicer.readthedocs.io/en/5.0 | :x: |
| https://slicer.readthedocs.io/en/v5.0/  | https://slicer.readthedocs.io/en/5.0/ | :heavy_check_mark:  |
| https://slicer.readthedocs.io/en/v5.0/user_guide/modules/transforms.html  | https://slicer.readthedocs.io/en/5.0/user_guide/modules/transforms.html | :heavy_check_mark:  |

**Comment by humitos** [comment]
Hi! Have you tried from `/en/v5.0$rest` to `/en/5.0`? Note the is no trailing slash. I think that should work.

**Comment by stsewd** [comment]
> Setting up the additional redirect Exact Redirect from /en/v5.0 -> /en/5.0 didn't help either.

This should be fixed with https://github.com/readthedocs/readthedocs.org/pull/9557. And maybe the original redirect that has `$rest` will also be fixed.

**Comment by humitos** [comment]
@stsewd @ericholscher we should create a test case for this particular issue 👍🏼

**Comment by humitos** [comment]
@jcfr can you confirm if you are still having this issue? We just deployed a potential fix and I quickly tested this by creating a redirect as I suggested in my previous comment (https://github.com/readthedocs/readthedocs.org/issues/9507#issuecomment-1217705654) and it worked! 👍🏼

**Comment by jcfr** [comment]
Thanks for the update 🙏 I will follow up on Thursday when back on the computer.

**Comment by jcfr** [comment]
I confirm the fix works as expected:

### Before

* Relying on javascript redirect implemented in Slicer/Slicer@a3b7544eca759d3289502c2744d1f9ce1cb12dc4)
* **Redirect**: `/en/v5.0/$rest` to `/en/5.0/`

|  |
|--|
| ![image](https://user-images.githubusercontent.com/219043/203194784-e5c13ad4-7c15-469b-8249-85cbd419dc5d.png) |

### After

* with updated redirect config suggested in https://github.com/readthedocs/readthedocs.org/issues/9507#issuecomment-1217705654
**Redirect**: `/en/v5.0$rest` to `/en/5.0`

|  |
|--|
| ![image](https://user-images.githubusercontent.com/219043/203195028-ff2eacb1-0e2b-4bf5-ad08-78c1adc383c0.png) | |
