### ISSUE TITLE
Docs: Subscription and billing management

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#9520]
I don't believe we have any appreciable amount of documentation covering our billing process, subscriptions, and payment questions. This might also be an addition for our website instead, but either way, some of the information we aren't communicating to users might look something like:

* Payment options
  * Monthly vs annual payments
  * We support credit card recurring subscriptions for monthly/annual subscriptions
  * We should define our support for invoicing, which so far is: you really should be using recurring credit card payments. We can support invoicing, but I'm not sure we really want to raise it as a possibility even, as that would almost certainly lend to more invoice payable subscriptions.
* How to manage a subscription
  * You need to be an organization owner
  * How to add a CC to invoices
  * How to add your companies information and VAT/etc
  * We don't need to explain too much about the UI, it's pretty straight forward. There are some hidden pieces though

**Comment by agjohnson** [comment]
Re invoice by email, what I tend to do is:

If a user wants a PO first, I create a Stripe quote. Not sure if we want to document this though?

If approved, I give them the link to their existing subscription's invoice, payable by CC recurring. If they insist on an invoice, I'll edit/regenerate the invoice for email invoicing.

If they send me set up instructions for their vendor system, I tell the that we don't support this for our self-service plans. We'll only do for high tier plans, even then it's a pain.

**Comment by ericholscher** [comment]
@agjohnson What is the quote doing in this case? Why not just link them to the invoice up front?

**Comment by agjohnson** [comment]
It's a nicer workflow, and avoids the invoice going to unpaid/noncollectable, and doesn't count towards our revenue. This is specific to users asking for a quote or PO for approval.

**Comment by benjaoming** [comment]
I think this is best placed as part of #9748 or #9749, i.e. once the new structure has landed and we are iterating over content refinements and additions.
