### ISSUE TITLE
Broken link to Transifex page

### ISSUE THREAD

**Issue by xk999** [readthedocs/readthedocs.org#9522]
## Details

* Read the Docs project URL: https://dev.readthedocs.io/en/latest/contribute.html#contributing-to-translations

## Expected Result

The link to "[our projects on Transifex](https://www.transifex.com/projects/p/readthedocs/)" leads to Readthedocs projects

## Actual Result

The link redirects to https://explore.transifex.com/

**Comment by humitos** [comment]
Hi @xk999! Thanks for reporting this. The link should be https://explore.transifex.com/readthedocs/

Do you want to open a PR for this?
