### ISSUE TITLE
Default CSS seems to not be included when html_content 'css_files' is specified

### ISSUE THREAD

**Issue by sjfleming** [readthedocs/readthedocs.org#9523]
## Details

* Read the Docs project URL: https://cellbender.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/cellbender/builds/17259494/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/sjfleming/

## Expected Result

The docs should render correctly using the default ReadTheDocs CSS.

## Actual Result

As you can see, the docs render as raw HTML without any CSS.

## Notes

Maybe six months ago, the site was rendering just fine on readthedocs (all versions of the docs).  I have made no changes since (it's guaranteed I made no changes to older versions), but now it will not render.

I did some digging, and I found that `v0.1.0` still renders (see https://cellbender.readthedocs.io/en/v0.1.0/)

The only difference in my docs code after `v0.1.0` was that I added these lines to `conf.py`
https://github.com/broadinstitute/CellBender/blob/cb2d209d5aedffe71e28947bc5b7859600aef64d/docs/source/conf.py#L67-L71
```python
html_context = {
    'css_files': [
        '_static/theme_overrides.css',  # override wide tables in RTD theme
        ],
     }
```

It seems that instead of adding this CSS file, it has replaced the ReadTheDocs default CSS with this.  That was not my intention at all.  And as of like 6 months ago, everything was working fine, i.e. the docs were still getting the default ReadTheDocs CSS.  If I inspect the page source on readthedocs for my project, I see that indeed the builds with those `html_context` lines are now missing the default CSS.

Is this a bug, or am I misunderstanding something?  Thanks!

(I submitted a ticket to support a week (or two?) ago but I haven't heard anything, so I thought I'd post here.)

**Comment by sjfleming** [comment]
I submitted a ticket to support a week (or two?) ago but I haven't heard anything, so I thought I'd post here.

**Comment by stsewd** [comment]
Hi there, I just checked, and your email was replied, but just in case you missed it. The problem is that you are replacing all css files instead of adding yours. You should use this sphinx setting https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_css_files as mentioned in https://docs.readthedocs.io/en/stable/guides/adding-custom-css.html

**Comment by sjfleming** [comment]
Thanks very much!

**Comment by sjfleming** [comment]
Exactly what I needed!  Everything is working now.  Thanks again.
