### ISSUE TITLE
Add READTHEDOCS_DATA for default version URL

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#9532]
Raised in https://github.com/readthedocs/doc-diff/issues/3, it would be helpful to add a value for the base URL that the diff library will use to compare pages. My current approach is hacky and full of holes.

I'm not certain, but I think what I'm looking for is at least the hostname of the default version, though with changes around subproject URL structure/etc, I guess this might need to be the hostname and base path to the project (`https://docs.readthedocs.io/projects/foo/en/latest/`).

Ultimately, this needs to be the full URL and path to the page to compare (`https://docs.readthedocs.io/en/latest/some/path/page.html`). I'm currently grabbing the page name from the READTHEDOCS_DATA `page` attribute, which might not be ideal. Currently I just append `.html` to the URL, and this likely doesn't work for all projects.

So, this might be a resolved base URL, or fully resolved base URL and file path name. Either probably work for the diff library use case.

I'm guessing this would be implemented in readthedocs-sphinx-ext, but I'm also assuming we'll want to use our resolver for this value.

**Comment by ericholscher** [comment]
You might be able to use this? https://github.com/readthedocs/readthedocs.org/blob/main/readthedocs/api/v2/views/core_views.py#L23-L27

**Comment by humitos** [comment]
We are removing the usage of `READTHEDOCS_DATA` and migrating all of it to the new API endpoint, `/readthedocs-config/` which will be used by the new js client. Developers can subscribe to a js event to access this data as well: https://github.com/readthedocs/readthedocs-client/issues/60

Related to https://github.com/readthedocs/readthedocs-client/issues/23 also; where we are building the docdiff integration.
