### ISSUE TITLE
Build: missing submodule throws exception

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#9539]
If a user configures a submodule to use in their readthedocs.yaml, the build command/step to pull submodules will fail with an exception and will not report back to the user that there was a problem.

To reproduce, specify `submodules.include: ['submodule-that-doesnt-exist']` in a configuration file. 

Here is a test-builds test case, which failed:

https://github.com/readthedocs/test-builds/blob/submodule-not-found/.readthedocs.yaml
https://readthedocs.org/projects/test-builds/builds/17876929/

I would expect that build step to report back to the user that there is a missing submodule.

**Comment by humitos** [comment]
Looks related or duplicate of https://github.com/readthedocs/readthedocs.org/issues/9365

**Comment by agjohnson** [comment]
Yeah, seems related a bit. Definitely related in that the exception is not reported back to the user.

If we do anything here specifically, it could be a command/build failure that "Submodule `submodule-that-doesnt-exist` was not found". On #9365, that might error message might be a little different perhaps, though I could see both being covered with a generic message too.

**Comment by agjohnson** [comment]
Rolled into #9365
