### ISSUE TITLE
Notifications: remove unused/old notifications

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#9545]
We aren't using some notifications like https://github.com/readthedocs/readthedocs.org/blob/b25a193c19db1c42f1fd4589e75ac93c0df87332/readthedocs/projects/notifications.py#L64-L64

we should just remove them.

ref https://github.com/readthedocs/readthedocs.org/pull/9538#discussion_r953605785

**Comment by humitos** [comment]
All this code was removed in https://github.com/readthedocs/readthedocs.org/pull/10423/
