### ISSUE TITLE
GitLab: oauth tokens aren't refreshed after they expire

### ISSUE THREAD

**Issue by warsaw** [readthedocs/readthedocs.org#9548]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/fluflenum/
* ~Build URL (if applicable): https://readthedocs.org/projects/{your_project_slug}/builds/{build_id}/~
* Read the Docs username (if applicable): https://readthedocs.org/profiles/barry/

## Expected Result

Once I set up an integration, I expect it to keep working.

## Actual Result

It seems like integrations are getting lost after a day or a few hours.  Case in point: [flufl.enum](https://gitlab.com/warsaw/flufl.enum) is one of the projects that I maintain on GitLab and publish docs on RTD.  I've just recently started making changes to this project again after some time off.  I noticed that new MRs were not building their draft documentation and there was no External test for RTD on the MR pipeline.  I tried to resync the webhook, but this failed, telling me I had to check my permissions.  I went to my Connected Services and saw both GitLab and GitHub still there.

It occurred to me that maybe I should delete my GitLab Connected Service, and re-add it.  After I did that, I went back to my flufl.enum integrations page and was able to resync my web hook.  After that, pushes to my MR all worked as expected; my draft documentation got built, and my MR pipeline showed an external test pointing to RTD.

After a day or so, I pushed a new change to my MR and again noticed that the GitLab/RTD integration was broken, just as above.  Hmm.  I did the same thing, i.e. deleted my GitLab Connected Service, re-added it, then resync'd my flufl.enum webhook, and again, everything started working again.  Okay I thought, maybe it was just a glitch.

Well, just now I noticed the *same thing happening again*.  A new MR, and no external test for RTD in my [pipeline](https://gitlab.com/warsaw/flufl.enum/-/pipelines/622347178).  So I went through the dance again of deleting my GitLab connected service, re-adding it, then resyncing my webhook.  And now it's working again.

This is clearly a recurring problem.  My connection to my GitLab account or the webhook just keeps getting dropped after some amount of time.  This affects other projects that I host on GitLab and publish on RTD.  I have not tested the same scenario with GitHub.

**Comment by stsewd** [comment]
Hi @warsaw, when this happens, do you still have builds triggered? This is, only the status fails to be reported to gitlab or also the builds aren't triggered for merge requests? Also, would be helpful if you could check the integration history (click on the integration to see this), and you could also check the history of the integration from gitlab (webhooks)

**Comment by warsaw** [comment]
Hi @stsewd.  Yes, it looks like builds are still triggered, but it's just the status that fails to be reported to GitLab.  I can't be 100% certain about that because when I look at my RTD builds page, I do see some builds happening, but it's difficult for me to correlate that with the MR timestamps.  RIght now, I just pushed an MR to `flufl.i18n` and I see both the builds and the status updates, so at the moment, my workaround is still in place.

AFAICT, the *integrations* look fine, and I see the webhook getting triggered as expected when I view the integration history.  And when I click on `resync webhook` right now it comes back successful.  However, when I didn't see the status in the GitLab MR, and clicked on resync then, it would fail telling me to check my permissions.  That's when I chanced on the workaround of deleting and re-adding my Connected Services.  Otherwise, there's no indication that somehow the connection was broken.

**Comment by stsewd** [comment]
@warsaw I checked the logs around the status report, and I see GitLab returning 401 on several of your projects. Looks like the token being used is expired, and isn't getting refreshed automatically for some reason. I'm digging a little more...

**Comment by warsaw** [comment]
Looks like the token may have expired again because I'm not seeing the external RTD test on this MR: https://gitlab.com/warsaw/flufl.lock/-/pipelines/624292157

But it does look like the webhook got delivered and the build for that MR succeeded: https://readthedocs.org/projects/flufllock/builds/17910811/

**Comment by stsewd** [comment]
> Looks like the token may have expired again because I'm not seeing the external RTD test on this MR: https://gitlab.com/warsaw/flufl.lock/-/pipelines/624292157

Yeah, there is a problem with the oauth integration not being able to refresh the tokens, so they are only valid for some hours after the initial creation/sync. We are looking into that.

**Comment by warsaw** [comment]
Thanks for looking into this problem.  LMK if you need anything more from me, and I'm happy to help test things out.

When I go to my User Settings -> Applications, here's what I see:

```
Read the Docs Community (readthedocs.org) | 2022-08-25 14:18:45 UTC | read_user api
-- | -- | --
```

**Comment by warsaw** [comment]
Great news @stsewd thanks!  I've just reconnected by GL account so I'll keep an eye on it as I push new updates to my repos.  Do you have a summary of the problem you can share?

**Comment by stsewd** [comment]
@warsaw basically the account that owns the application on gitlab was blocked, and for some reason that wasn't allowing us to refresh the tokens, we contacted support and now we have access again.

**Comment by warsaw** [comment]
Hmm, I'm not so sure this is fixed.  I noticed on my public project on GL that it wasn't building the docs, so I did the workaround mentioned previously.  I removed my GL connected service and re-added it, then I synced the web hook on RTD.  Yesterday when I built a PR everything looked okay.

I was about to do a similar PR on my flufl.enum project so I started by looking at RTD.  However I cannot resync the webhook because I get the same permission problem.  That seems to tell me that the GL connected service isn't validated.  So it looks like the token still isn't getting refreshed.

Is there something else I need to do on my side?

**Comment by warsaw** [comment]
Confirmed.  Not fix.  I lost connection again today.

**Comment by humitos** [comment]
Thanks @warsaw for all your help and feedback on this. We contacted GitLab's support 3 days ago and we are waiting for a reply to see if they can solve this problem from their side. Currently, I'm not sure if there is any actionable we can do from Read the Docs. We will keep you posted about any news. Thanks again!

**Comment by warsaw** [comment]
Thanks @humitos !  I really appreciate y'alls follow through with this.  Ping me here if GitLab or you need any other testing or information.  🤞
