### ISSUE TITLE
Also use `_readthedocs/html` path for normal builds

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#9554]
When using build commands customization, it's quite nice to have a defined `_readthedocs/html` output path to manipulate. I was surprised that the same path isn't used when building with our normal builders, while using build jobs customizations.

I was trying to manipulate the output from Sphinx before we upload (using `build.jobs.post_build`), and found that manipulating the `docs/_build/html` files after build didn't result in any changes to hosted files. We ran into this in the other builder as well, as the files are immediately synced after the Sphinx build, so any manipulation in `post_build` to these files is discarded.

This seems like it would take altering our build process though, and executing `post_build` before syncing files. But, if the issue is similar to the `build.commands` bug that we resolved, it's simply that an undocumented path is being used before syncing.

**Comment by humitos** [comment]
> I was trying to manipulate the output from Sphinx before we upload (using `build.jobs.post_build`), and found that manipulating the `docs/_build/html` files after build didn't result in any changes to hosted files

We have an issue tracking this at #9172, which is also related to #9179

All these three issues together means "Use `_readthedocs/html` for all the builders and document this path. Besides, upload this output directly from this directory to S3 without using an intermediate directory"

**Comment by agjohnson** [comment]
I'll close this as duplicate. I've put both of those on the q4 roadmap, they feel like pretty important improvements to build.jobs.
