### ISSUE TITLE
WARNING: unknown mimetype for _static/favicon.ico, ignoring

### ISSUE THREAD

**Issue by lemonypancakes** [readthedocs/readthedocs.org#9556]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/origins-bukkit/
* Build URL (if applicable): https://readthedocs.org/projects/origins-bukkit/builds/17920944/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/LemonyPancakes/

## Expected Result

I want to change the favicon of the site.

## Actual Result

WARNING: unknown mimetype for _static/Origins-Bukkit-256x.ico, ignoring

**Comment by humitos** [comment]
Hi @LemonyPancakes! This looks like a problem on your .ico file that Sphinx is not able to read it properly. I don't think this is an issue related to Read the Docs.

**Comment by LemonyPancakes** [comment]
> 

It works perfectly fine locally but it breaks when readthedocs is the one building the project. It breaks because the fail-on-warning setting in readthedocs.yml is set to true so I disabled it temporarily. https://origins-bukkit.lemonypancakes.me
