### ISSUE TITLE
Build error with build id #17944783

### ISSUE THREAD

**Issue by Jiunixo** [readthedocs/readthedocs.org#9566]
## Details:

* Project URL: https://readthedocs.org/projects/code_tympan/
* Build URL(if applicable): https://readthedocs.org/projects/code-tympan/builds/17944783/
* Read the Docs username(if applicable): Code_TYMPAN

## Expected Result

Latest build in success.

## Actual Result

Latest  build fails
I resent request from Gitlab but it does not trigger a new build.

**Comment by humitos** [comment]
It seems it was a temporal issue. I triggered a new build for your project and it did work fine: https://readthedocs.org/projects/code-tympan/builds/17946862/

> I resent request from Gitlab but it does not trigger a new build.

We are having issues with GitLab currently and we are working to solve them. Take a look at #9548

**Comment by Jiunixo** [comment]
I've just pushed a new change to gitlab and it did not trigger a new build.

I can wait for the issue #9548 to be solved.

Thank you very much for your help.

**Comment by stsewd** [comment]
>> I resent request from Gitlab but it does not trigger a new build.
>
> We are having issues with GitLab currently and we are working to solve them. Take a look at https://github.com/readthedocs/readthedocs.org/issues/9548

https://github.com/readthedocs/readthedocs.org/issues/9548 only affects reporting the status for merge requests, webhooks should be working okay (the webhook creation could fail due to the bug, but if the webhook is already in place, it should work).

**Comment by Jiunixo** [comment]
> I've just pushed a new change to gitlab and it did not trigger a new build.

Sorry, at that time, only develop branch was enabled on our project and I had pushed to another branch.
After merging to develop occurred on Gitlab, the build did start on ReadTheDocs.

The first build error was probably a temporary issue.

We can closed this issue unless you want to do further investigations.
