### ISSUE TITLE
404 page is not rendered properly when mkdocs-material is used

### ISSUE THREAD

**Issue by renardeinside** [readthedocs/readthedocs.org#9570]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/dbx/

## Expected Result

When running `mkdocs serve` locally, 404 page is rendered as follows:

<img width="1228" alt="Screenshot 2022-08-31 at 21 10 26" src="https://user-images.githubusercontent.com/4979594/187762737-1a9b2953-83ee-48cf-92b0-1c35598a6775.png">

## Actual Result

However when deployed to readthedocs something breaks (maybe during render?), for example

https://dbx.readthedocs.io/notfound

Leads to this:

<img width="1349" alt="Screenshot 2022-08-31 at 21 11 20" src="https://user-images.githubusercontent.com/4979594/187762946-69bf6cc7-e8a7-47ce-b63d-5497e3d382fc.png">

Code of mkdocs.yml is provided [here](https://github.com/databrickslabs/dbx/blob/main/mkdocs.yml), readthedocs.yaml is [here](https://github.com/databrickslabs/dbx/blob/main/.readthedocs.yaml)

Any help would be much appreciated.

**Comment by renardeinside** [comment]
not sure if this might be helpful, here is the console log from browser:

<img width="560" alt="Screenshot 2022-08-31 at 21 14 16" src="https://user-images.githubusercontent.com/4979594/187763447-0370764c-c13a-42b0-b116-f2abeba8a8b4.png">

**Comment by stsewd** [comment]
@renardeinside this is since the 404 page from mkdocs is linking to the styles as absolute links to `/` (`/assets/stylesheets/main.69437709.min.css`), but your docs are being serve from `/en/latest/` (`/en/latest/assets/stylesheets/main.69437709.min.css`), not from `/`.

For sphinx we have an extension that changes the links to be absolute to the default version https://github.com/readthedocs/sphinx-notfound-page. For MkDocs I'm not sure about the solution, maybe setting https://www.mkdocs.org/user-guide/configuration/#site_url could work.

**Comment by renardeinside** [comment]
hi @stsewd , 
but I've `site_url` set in my `mkdocs` as per link [here](https://github.com/databrickslabs/dbx/blob/main/mkdocs.yml):
```
site_name: dbx
site_description: 🧱Databricks CLI eXtensions - aka dbx is a CLI tool for development and advanced Databricks workflows management.
site_url: https://dbx.readthedocs.io/
```

**Comment by renardeinside** [comment]
btw, this issue is also [reproducible](https://example-mkdocs-basic.readthedocs.io/en/latest/notfound) even with the example linked in the readthedocs doc as an example.

**Comment by stsewd** [comment]
@renardeinside your site URL needs to have `/en/latest`.

> btw, this issue is also [reproducible](https://example-mkdocs-basic.readthedocs.io/en/latest/notfound) even with the example linked in the readthedocs doc as an example.

yeah, but this problem isn't related to RTD itself, you will have the same problem in any other hosting where the docs are served in a path different from `/`.

And if setting the site URL works, it should probably be set differently for each version (`/en/latest/`, `/en/stable/`, etc)

**Comment by stsewd** [comment]
> And if setting the site URL works, it should probably be set differently for each version (/en/latest/, /en/stable/, etc)

This is related to https://github.com/readthedocs/readthedocs.org/issues/4820 and https://github.com/readthedocs/readthedocs.org/issues/8529.

**Comment by renardeinside** [comment]
huge thanks @stsewd , adding `/en/latest/` indeed fixed the issue 👍
