### ISSUE TITLE
Docs: update pull request page

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#9574]
From #9258 

  - the content looks good, it could use a more marketing language to sell it more, but it's fine for now
  - maybe some small edits will help

**Comment by cletheren** [comment]
Hello, I am a newcomer to the project and I'd like to see whether I can assist with this issue. For the avoidance of any doubt (and to help me as a newcomer), would you mind pointing me to the page that you're referring to please?

**Comment by agjohnson** [comment]
The documentation page discussed here is https://docs.readthedocs.io/en/stable/pull-requests.html

**Comment by humitos** [comment]
I understand this page was reviewed when we added addons documentation here. The work mentioned in the description looks outdated and/or done already.
