### ISSUE TITLE
Docs: update builds and build customization page

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#9575]
From #9258 

  - these page were updated some weeks ago
  - anthony made some notes of improvements he wanted to see here, so we can recover those notes and update it

**Comment by benjaoming** [comment]
> anthony made some notes of improvements he wanted to see here, so we can recover those notes and update it

When you have time, those notes would be helpful. Build and Build customization pages are already in the Diátaxis Refactor, so they will be looked at, and the process will be much better and faster with prior inputs :+1: :heart:
