### ISSUE TITLE
Enable Cloudflare Optimizations - Brotli

### ISSUE THREAD

**Issue by TheTripleV** [readthedocs/readthedocs.org#9578]
On [https://frc-docs.readthedocs.io](https://frc-docs.readthedocs.io), I noticed that all files are being downloaded with gzip encoding. However, Cloudflare does supports Brotli compression, which results in smaller files.

According to Cloudflare's docs (https://support.cloudflare.com/hc/en-us/articles/200168396-What-will-Cloudflare-compress-), Brotli is enabled by default on some plans and disabled by default on others.

Would it be possible to enable Brotli compression?

**Comment by humitos** [comment]
Hi @TheTripleV ! I read the document you linked but I didn't find what are the benefits of Brotli over gzip. Also, is Brotli widely supported for most of the browsers? That would be another thing to consider before enabling it.

**Comment by TheTripleV** [comment]
According to a study by Akamai, Brotli's resulting files are 21% smaller than GZIP for HTML, 14% smaller for JS, and 17% smaller for CSS.

Brotli is supported on all major browser apart from Internet Explorer (https://caniuse.com/brotli) and Cloudflare says it will only send Brotli to compatible clients.

**Comment by TheTripleV** [comment]
To give a few examples of sites using Brotli, Google/Youtube and Facebook have it enabled.

**Comment by ericholscher** [comment]
I have enabled this for now. Please let me know if you see the change 👍

**Comment by TheTripleV** [comment]
Pages are now downloading with brotli compression. Thanks!

**Comment by humitos** [comment]
Thanks for reporting back. I'm closing this issue since its done and it's working fine.
