### ISSUE TITLE
All links in the flyout injected by Read the Docs end with `/null/`, breaking the flyout

### ISSUE THREAD

**Issue by mpilgrem** [readthedocs/readthedocs.org#9585]
## Details

The documentation for the Haskell Tool Stack at https://docs.haskellstack.org/en/stable/ is generated by Read the Docs using MkDocs (version 1.3.1) with the Material for MkDocs theme (current version). By adding JQuery 3.6.1, I could get the Read the Docs flyout to be injected on each page (extract from `mkdocs.yml`):

~~~yaml
extra_javascript:
# Read the Docs requires JQuery for its JavaScript code to inject the flyout
# menu. Material for MkDocs does not come with JQuery.
- 'https://code.jquery.com/jquery-3.6.1.min.js'
~~~

This seemed to be working fine until recently. However, today I have identified that on versions of the documentation ('latest' and 'stable') that use the Material for MkDocs theme all of the links in the flyout are to URLs which end with `/null/` (on every page where the flyout is injected). For example (extracts - inserted within `<body></body>`):

~~~html
<!-- Inserted RTD Footer -->
<div class="injected">
  <div class="rst-versions rst-badge shift-up" data-toggle="rst-versions">
    <span class="rst-current-version" data-toggle="rst-current-version">
    </span>
    <div class="rst-other-versions">
      <dl>
        <dt>Versions</dt>        
        <dd>
          <a href="https://docs.haskellstack.org/en/latest/null/">latest</a>
        </dd>        
        <dd class="rtd-current-item">
          <a href="https://docs.haskellstack.org/en/stable/null/">stable</a>
        </dd>        
        <dd>
          <a href="https://docs.haskellstack.org/en/v2.7.5/null/">v2.7.5</a>
        </dd>        
        <dd>
          <a href="https://docs.haskellstack.org/en/v2.7.3/null/">v2.7.3</a>
        </dd>
      </dl>
      <dl>
        <dt>On GitHub</dt>
        <dd>
          <a href="https://github.com/commercialhaskell/stack/blob/stable/doc/null.md">View</a>
        </dd>        
        <dd>
          <a href="https://github.com/commercialhaskell/stack/edit/stable/doc/null.md">Edit</a>
        </dd>        
      </dl>
    </div>
  </div>
</div>
~~~

I do not think that I have done anything differently very recently. However, I have been making incremental use of the Material for MkDocs extensions to Markdown. The current set of extensions used are:

~~~yaml
markdown_extensions:
# For admonitions
- admonition
# For icons and emojis
- attr_list
# For admonitions
- pymdownx.details
# For icons and emojis
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg
# For code blocks
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
# For code blocks and content tabs
- pymdownx.superfences
# For content tabs
- pymdownx.tabbed:
    alternate_style: true
- toc:
    permalink: true
~~~

* Read the Docs project URL: https://readthedocs.org/projects/stack/

## Expected Result

A working version of the flyout is injected on to each page.

## Actual Result

A non-functioning version of the flyout is injected on to each page.

**Comment by mpilgrem** [comment]
I note that this pull request happened 11 hours ago: https://github.com/readthedocs/readthedocs.org/pull/9584 and v8.4.3 seems to have done something to the 'footer' - https://docs.readthedocs.io/en/stable/changelog.html. Did the changes break something?

**Comment by stsewd** [comment]
@mpilgrem hi, I found the bug. Hopefully we can release the fix soon.

**Comment by ericholscher** [comment]
@mpilgrem This fix should be deployed. You might need to hard refresh to clear your browser cache, but I confirmed it's working.

**Comment by mpilgrem** [comment]
@ericholscher, many thanks for such a speedy response.

**Comment by ericholscher** [comment]
@mpilgrem Glad it worked! Thank @stsewd mostly -- I just pushed the deploy buttons 🔘
