### ISSUE TITLE
Remove the `zh` Chinese translation 

### ISSUE THREAD

**Issue by Geeyun-JY3** [readthedocs/readthedocs.org#9595]
Currently, there are four Chinese translations on Transifex:

- [zh](https://www.transifex.com/readthedocs/dashboard/all_projects/zh/) 
- [zh_CN](https://www.transifex.com/readthedocs/dashboard/all_projects/zh_CN/) 
- [zh_TW](https://www.transifex.com/readthedocs/dashboard/all_projects/zh_TW/) 
- [zh_HK](https://www.transifex.com/readthedocs/dashboard/all_projects/zh_HK/) 

But the language code [`zh`](https://www.transifex.com/readthedocs/dashboard/all_projects/zh/) is ambiguous, which may refer to all Chinese language variants.
Translating into the above 3 other Chinese language variants is enough, which can cover almost all Chinese language users.

**Comment by agjohnson** [comment]
Thanks! Agreed it is redundant, I've updated Transifex. It looks like it that locale was at 0% translation, so not a significant change.

**Comment by Geeyun-JY3** [comment]
The [`zh` Chinese translation of readthedocs-docs](https://www.transifex.com/readthedocs/readthedocs-docs/language/zh/) should be removed too.
