### ISSUE TITLE
Site performance Issues

### ISSUE THREAD

**Issue by derks** [readthedocs/readthedocs.org#96]
The response of RTD is extremely slow.  Almost getting to the point of not wanting to use it... as my users would be even more critical I'm sure.  Any plans to speed things up?

**Comment by bittner** [comment]
There seem to be site performance issues (again), at least for managing documentation projects (i.e. in the area that you have to log in for). Not sure what could be the problem. My browser (Firefox) seems to wait for `typekit.net`.
