### ISSUE TITLE
Docs: use Plausible for analytics

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#9603]
We started using Plausible on our new website, we should eventually consolidate our own docs site there as well.

This might take a little bit of thought, but isn't a lot of work otherwise. Is there anything we care to preserve from GA or replicate from GA before migrating?

**Comment by benjaoming** [comment]
Would it be sufficient to simply fetch and archive a few statistical reports on statistics we would want to refer back to? I'm thinking specifically about metrics we can use to assess how things are developing?

* Total site usage
* Individual page hits
* Geographical region
* Browser
* Search terms
* Top entry page / exit page

fin.

**Comment by humitos** [comment]
I'm bumping this up for the next sprint. We have been talking about this lately. We want to add Plausible in:

- [ ] blog
- [ ] our documentation

That way, we will have everything in one place (together with about.readthedocs.com) and also be able to define some goals.

**Comment by ericholscher** [comment]
It's already on the blog, but adding it to our docs shouldn't be hard. 👍
