### ISSUE TITLE
Application: use Plausible for dashboard analytics

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#9604]
We started using Plausible on our new website, we should eventually consolidate our own application/dashboard analytics there as well. This might aid in correlating website traffic to subscription creation/etc.

I don't believe we're tracking anything of moderate importance currently, so this should be fairly low friction.

**Comment by humitos** [comment]
Bumping it for the next sprint, together with https://github.com/readthedocs/readthedocs.org/issues/9603
