### ISSUE TITLE
Fails to manually set the default branch

### ISSUE THREAD

**Issue by CoderMaggie** [readthedocs/readthedocs.org#9606]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/sylius/
* Build URL (if applicable): https://readthedocs.org/projects/sylius/builds/18077139/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/CoderMaggie/

## Expected Result

At Sylius we've switched from the `master` default branch naming to `1.12` (which is the next version to be tagged). Thus I wanted to reconfigure readthedocs to be pointing to the `1.12` branch with the `/latest` URL.
Here's my configuration:

![image](https://user-images.githubusercontent.com/13198869/190355450-95d00c88-8d67-4fb1-95b4-bac18667290e.png)

## Actual Result

Having it configured as above the `/latest` URL is still not working.

![image](https://user-images.githubusercontent.com/13198869/190365052-dbbaa34a-a4f2-40c1-aff2-ce8a9d7858b9.png)

**Comment by stsewd** [comment]
@CoderMaggie hi, looks like you don't have the latest version enabled, you can do this from https://readthedocs.org/dashboard/sylius/version/latest/edit/.

**Comment by CoderMaggie** [comment]
Hi @stsewd!

Indeed it was the problem! Thank you for your help 🤝 💚
