### ISSUE TITLE
feature request: bug template provides no affordance for feature requests

### ISSUE THREAD

**Issue by glyph** [readthedocs/readthedocs.org#9612]
The contributing documentation talks about applying the feature tag, but there's only a template for bug reports.

**Comment by humitos** [comment]
Hi @glyph! 👋🏼 Can you expand a little more on this issue? I'm not sure to understand what it refers to.

**Comment by stsewd** [comment]
@humitos this is when clicking on "new issue", you are redirected to https://github.com/readthedocs/readthedocs.org/issues/new/choose, but we don't provide a template for a feature, only for bug reports.

**Comment by glyph** [comment]
> @humitos this is when clicking on "new issue", you are redirected to https://github.com/readthedocs/readthedocs.org/issues/new/choose, but we don't provide a template for a feature, only for bug reports.

Yep, this. Just a meta-issue on workflow process here.

**Comment by glyph** [comment]
Thanks!
