### ISSUE TITLE
Forced redirect `/$rest -> example.com` redirects PR previews (external domain) to target domain

### ISSUE THREAD

**Issue by andersy005** [readthedocs/readthedocs.org#9614]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/xray/
* Build URL (if applicable): https://readthedocs.org/projects/xray/builds/18134887/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/{your_rtd_username}/

## Expected Result

Pull Request preview to work when using custom domain. 

## Actual Result

We recently switched to using a custom domain for our docs on RTD [docs.xarray.dev](https://docs.xarray.dev/), and this appears to have broken the pull request preview feature (or this doesn't seem to work for us at least). For instance, The GitHub check for  this PR: https://github.com/pydata/xarray/pull/7061 points to https://docs.xarray.dev/en/7061/. This page returns a 404

Cc @jhamman

**Comment by stsewd** [comment]
And other solution could be to ignore user redirects when serving PR previews.

**Comment by andersy005** [comment]
> https://xarray.readthedocs.io/$rest -> https://docs.xarray.dev/ (it will only redirect for requests on the readthedocs.io domain).

this appears to be working fine 🎉 . Thank you, @stsewd!

**Comment by jhamman** [comment]
Actually, I'm not sure it is working. 

https://xarray.pydata.org/en/stable/api.html is no longer redirecting to https://docs.xarray.dev/en/stable/api.html as expected.

**Comment by andersy005** [comment]
> [xarray.pydata.org/en/stable/api.html](https://xarray.pydata.org/en/stable/api.html) is no longer redirecting to [docs.xarray.dev/en/stable/api.html](https://docs.xarray.dev/en/stable/api.html) as expected.

Good catch... Forgot to check this

**Comment by stsewd** [comment]
> > https://xarray.readthedocs.io/$rest -> https://docs.xarray.dev/ (it will only redirect for requests on the readthedocs.io domain).
> 
> this solution appears to be working for us tada . Thank you, @stsewd!

Sorry, I meant that those solutions we could implement in the future, that's not currently supported.

**Comment by stsewd** [comment]
This will be fixed with https://github.com/readthedocs/readthedocs.org/pull/10881. We decided to not run user redirects on previews from PRs, those domains should be treated as temporary.

**Comment by humitos** [comment]
> We decided to not run user redirects on previews from PRs, those domains should be treated as temporary.

@stsewd do we have this decision documented somewhere? If not, I think it will be good for users and also for ourselves.

**Comment by stsewd** [comment]
> > We decided to not run user redirects on previews from PRs, those domains should be treated as temporary.
> 
> @stsewd do we have this decision documented somewhere? If not, I think it will be good for users and also for ourselves.

It's in the documentation and design document.

https://docs.readthedocs.io/en/latest/user-defined-redirects.html#limitations-and-observations
