### ISSUE TITLE
Abandoned project: Piexif

### ISSUE THREAD

**Issue by davetapley** [readthedocs/readthedocs.org#9619]
I have assumed ownership of this project on PyPi: https://github.com/hMatoba/Piexif/issues/122#issuecomment-1241027599
and moved it to a new fork: https://github.com/JEFuller/Piexif/.

Can I get https://piexif.readthedocs.io/ transferred to my rtd user `davetapley`? 🙏🏻

**Comment by stsewd** [comment]
Hi, I have contacted the current owner today, if I we don't hear anything in six weeks, I'll transfer the project to you.

**Comment by stsewd** [comment]
Hi there! We didn't hear back from them, I added you as owner of the project.
