### ISSUE TITLE
Telemetry: track `extensions` and `html_theme` Sphinx variables

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#9627]
While working on https://github.com/sphinx-doc/sphinx/issues/10070, @AA-Turner ask for the content of `extensions` and `html_theme` and I think it could be useful to store in the Telemetry database somehow. Considering these values may be dynamically populated, we should find a way to execute this code and grab the final value of them.

**Comment by AA-Turner** [comment]
If your metrics are able to work with Sphinx extensions, this could be read as `app.extensions` and `app.config.html_theme` by hooking into the `config-inited` event.

A
