### ISSUE TITLE
Build failed: "command killed due to timeout or excessive memory consumption"

### ISSUE THREAD

**Issue by jtpavlock** [readthedocs/readthedocs.org#9631]
## Details

Not sure what's causing this to happen, I can install my project and build the docs locally just fine.

* Read the Docs project URL: https://readthedocs.org/projects/mrmoe/
* Build URL (if applicable): https://readthedocs.org/projects/mrmoe/builds/18199605/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/jtpavlock/

## Expected Result

Build to pass

## Actual Result

Build failed

**Comment by humitos** [comment]
It seems `pip` is taking a lot of time trying to resolve your dependencies. I'd suggest to only install the ones that are strictly required to build your documentation. Besides, reduce the scope of versions that `pip` has to try by pinning them to specific versions.

Also, make sure you are using the same version of Python locally than on Read the Docs.

**Comment by jtpavlock** [comment]
Thanks, it was due to a mismatched python version.
