### ISSUE TITLE
ModuleNotFoundError: No module named 'sphinxcontrib.images'

### ISSUE THREAD

**Issue by sunkangchina** [readthedocs/readthedocs.org#9632]
https://readthedocs.org/projects/easyinvcoice-doc/builds/18200989/

![image](https://user-images.githubusercontent.com/66815206/192978359-218e9560-074e-4e41-bd2a-803a0e9c6fe3.png)

**Comment by humitos** [comment]
Hi! Can you please complete the issue with the information that is requested in the pre-filled description? Thanks.

**Comment by humitos** [comment]
You have defined that extension in your Sphinx configuration file but you are not installing it on the virtualenv used by Read the Docs.

```python
extensions = ['sphinx.ext.doctest', 'sphinx.ext.intersphinx', 'sphinx.ext.todo', 'sphinx.ext.coverage',  'sphinx.ext.mathjax', 'sphinx.ext.ifconfig', 'sphinx.ext.viewcode','recommonmark','sphinxcontrib.images']
```

To solve this problem, you have to install all the extensions you are using. Take a look at https://docs.readthedocs.io/en/stable/config-file/v2.html#requirements-file

**Comment by stsewd** [comment]
I'm closing this issue since it isn't a problem with Read the Docs, but a problem with missing dependencies, see the comment above on how to solve it https://github.com/readthedocs/readthedocs.org/issues/9632#issuecomment-1262055364
