### ISSUE TITLE
Version warning link of outdated docs doesnt redirect correctly

### ISSUE THREAD

**Issue by LZimmermannLZI** [readthedocs/readthedocs.org#9644]
## Details
As mentioned in readthedocs/readthedocs.org#9633 and further information in telefonicaid/fiware-orion#4218 the redirection of the links in version warning messages of outdated docs is not working as expected. It works for the start page of the docs but not for subfolders.

## Expected Result

Clicking on the link in the warning message of an outdated documentation page should redirect to the same subfolder of the newest version.

## Actual Result
Example for the FIWARE docs:
The actual URL for the pagination subtopic of v 3.7.0 looks like this:
https://fiware-orion.readthedocs.io/en/3.7.0/user/pagination.html

The redirected link of the warning note of v 1.15.0 looks like this:
https://fiware-orion.readthedocs.io/en/3.7.0/user/pagination/index.html
The redirected link provokes an 404 Error.

Edit: A similar issue seems to be present if the version is manually switched in the menu that is in the right bottom corner of the doc.
![grafik](https://user-images.githubusercontent.com/91118736/194314326-d7130c07-e794-46d1-bf35-f66102ea3516.png)

**Comment by stsewd** [comment]
Hi, we don't track moves/renames of pages, so if the page is in a different path than the old version there isn't much we can do, we just use the current path to construct the new link. I'd recommend for you to create a page redirect, see https://docs.readthedocs.io/en/stable/user-defined-redirects.html#page-redirects.

**Comment by Maghnie** [comment]
@fgalan

**Comment by fgalan** [comment]
> @fgalan hopefully this solves the issue?

Could you elaborate? In which sense this solves the issue?

**Comment by Maghnie** [comment]
I meant the suggestion to implement page redirects

**Comment by fgalan** [comment]
> I meant the suggestion to implement page redirects

Not sure... I have read the link provided by @stsewd but I'm not sure how this applies to the documentation in the [Orion repository](https://github.com/telefonicaid/fiware-orion).

@Maghnie @LZimmermannLZI I'd suggest to move back the discussion to https://github.com/telefonicaid/fiware-orion/issues/4218. Could you elaborate there on how to implement page redirects taking into account the Orion documentation, please? Thanks!

**Comment by stsewd** [comment]
I'm closing this issue, as explained in https://github.com/readthedocs/readthedocs.org/issues/9644#issuecomment-1270267039 we don't track renames, and this should be solved by creating a redirect. Or if you want to have more control over the message, you can use this extension https://sphinx-version-warning.readthedocs.io/en/latest/.
