### ISSUE TITLE
Some of my package's classes have disappeared in the html version of the documentation, although in the pdf version everything is displayed correctly.

### ISSUE THREAD

**Issue by mpgl** [readthedocs/readthedocs.org#9645]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/dendrify/
* Build URL (if applicable): https://readthedocs.org/projects/dendrify/builds/18267964/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/mpgl/
* RTD configuration file: https://github.com/Poirazi-Lab/dendrify/blob/main/.readthedocs.yaml
* Sphinx conf.py: https://github.com/Poirazi-Lab/dendrify/blob/main/docs_sphinx/source/conf.py
* RTD requirements file: https://github.com/Poirazi-Lab/dendrify/blob/main/docs_sphinx/source/requirements_docs.txt

## Expected Result

Read the docs should be able to properly identify and display all of my package's classes and their docstrings in the html version of the documentation.

## Actual Result

Some classes are displayed correctly (see [here](https://dendrify.readthedocs.io/en/latest/classes/dendrite.html)) while other classes have disappeared entirely (see [here](https://dendrify.readthedocs.io/en/latest/classes/compartment.html)). 

Weirdly enough, if you check the online PDF version of the documentation, everything is displayed as expected at the [API reference section](https://dendrify.readthedocs.io/_/downloads/en/latest/pdf/). In the past I did not have this issue with previous builds and also locally everything works perfectly. The only thing that I changed in the last build is that I added some type hints that are allowed only in python 3.10+. I thought that this caused the issue but even after I removed them the problem persists.

Thank you.

**Comment by stsewd** [comment]
Hi, I'm able to see the content of that page

![Screenshot 2022-10-06 at 12-46-21 Compartment - Dendrify](https://user-images.githubusercontent.com/4975310/194383058-f91637ad-919e-46b8-91a3-9ede4a4b671f.png)

Please try in a private window or with a hard refresh (ctrl + f5), this is probably your browser cache.

**Comment by mpgl** [comment]
WOW. Now it works. I never imagined that an issue like this exists. Thank you so much for the rapid response.
