### ISSUE TITLE
Subscriptions: attach stripe_subscription to Organization model?

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#9652]
Currently, we only attach the stripe customer to the organization object, and we have a little helper to get the stripe subscription

https://github.com/readthedocs/readthedocs.org/blob/9e7787ce036c49ea03410bbf77b20ccf1b607873/readthedocs/organizations/models.py#L127-L127

All good, but if we want to query organizations by their subscription status, then we have a little problem... A customer can have more than one subscription, and to have our query work around the "current" subscription, we need a subquery like

```python
current_sub = djstripe.Subscription.objects.filter(customer__rtd_organization=OuterRef("id")).order_by("-created").values("id")[:1]
q = Organization.objects.filter(stripe_customer__subscriptions__id=Subquery(current_sub))
```

Which is... ugly

Luckily, we always have just one active subscription per customer (or a subscription that isn't canceled per customer),
so we are okay omitting the subquery if we filter subscriptions by a status different from `canceled`, but when we require querying by canceled subscriptions or without a given status, than we need to use the subquery https://github.com/readthedocs/readthedocs.org/blob/9e7787ce036c49ea03410bbf77b20ccf1b607873/readthedocs/organizations/querysets.py#L41-L202.

So the question is: are we okay with using a subquery for those cases? Or maybe we should attach the current stripe subscription into the organization model? We would need to keep it up to date with the "current" subscription, but that shouldn't be complicated (we just need to listen to the `subscription.created` event), and I think queries will be more clear having just to write `Organization.objects.filter(stripe_subscription__=...)`.

**Comment by ericholscher** [comment]
I think the big question in my mind is, will customers always have only *1* subscription? I think in the past we've created additional subscription objects to add on additional features/billing. I think this is likely something that we would also do in the future, so I don't think we can make that assumption. 

I think having the subscription assigned to the organization as the "primary" or main one is probably the best path forward. I think being explicit here is good, instead of relying on implicit data in the DB. We likely need some logic around what types of subscription can be the "main" subscription, if we're relying on incoming webhooks, and we'd need to filter out any additional subscriptions.

I'm imagining the case in the future where we are selling support as an additional subscription upsell, have a customer with:

* Organization: Example
* Plan: Advanced
* Support Plan: Pro

We need some way to not blow up in this scenario :)

**Comment by humitos** [comment]
IIRC, for the cases that Eric mentions we are still using 1 subscription with multiple products. We have customers paying the regular plan + additional builders in the same subscription. I'm not saying that making the assumption that _we will always have 1 subscription per customer_ is good, tho --just noticing that _it's possible to have 1 subscription with multiple products on it_.

**Comment by stsewd** [comment]
Currently, we have 0 users that have more than one subscription that isn't `canceled`, and as Manuel mentioned, currently we are just adding a new product into the subscription. And looks like we can combine yearly/monthly products in the same subscription D:

![Read the Docs Inc – Stripe](https://user-images.githubusercontent.com/4975310/195194261-2ded4d24-f3d9-4969-8a33-f3832d3e10c1.png)

What we can't do is to have a different trial for each product. Just mentioning what we can do before going for multiple subscriptions :)

So, +1 on having a "main" subscription.

Another solutions could be to change our querysets to be related to the Subscriptions instead of the Organizations,
this is query for subscriptions where their trial is about to end instead of querying for organizations that have subscriptions that are about to end. Then we will have access to the organization from `stripe_subscription.customer.rtd_organization`.

And instead of querying subscriptions that are cancelled/trial-ended, we can make use of the stripe webhook to email users the exact time the subscription ends the trial.

The only one query that we can't migrate by simply change that relation is https://github.com/readthedocs/readthedocs.org/blob/55fd87e708acfa3c5518ba34d12d5e5df8ff90db/readthedocs/organizations/querysets.py#L171

But we could add an attribute in the organization for that, something like `subscription_ended`, we will need to have that field up to date when a subscription is created/canceled obviously.

Just a thought, I'm fine moving with the "main subscription" idea too, but will require a data migration.

**Comment by ericholscher** [comment]
I'm good with a `main` subscription then 👍
