### ISSUE TITLE
Build error with build id #18277779

### ISSUE THREAD

**Issue by Jiunixo** [readthedocs/readthedocs.org#9653]
## Details:

* Project URL: https://readthedocs.org/projects/code_tympan/
* Build URL(if applicable): https://readthedocs.org/projects/code-tympan/builds/18277779/
* Read the Docs username(if applicable): Code_TYMPAN

## Expected Result

Doc should be built without errors.

## Actual Result

The compilation failed on the build of develop branch and I can't figure out how to relaunch the build.
- I cannot see any way to do so on the interface.
- I resend the webhook from Gitlab and the compilation is not relaunched.

![image](https://user-images.githubusercontent.com/6851237/195012267-035f953d-c0e0-4c43-b098-f61fe39facaa.png)

**Comment by stsewd** [comment]
Hi, sorry for the late reply! I see that your builds are passing now https://readthedocs.org/projects/code-tympan/builds/. This was probably a temporal error, I'm closing this issue, but let us know if you need more help.

> I can't figure out how to relaunch the build.

You can do this from https://readthedocs.org/projects/code-tympan/builds/, select the "latest" version and click on the "Build Version" button.
