### ISSUE TITLE
Allow specifying verbose flag for MkDocs

### ISSUE THREAD

**Issue by KevinMGranger** [readthedocs/readthedocs.org#9678]
We're trying to debug an issue with our build. While troubleshooting, we realized there was no way to specify a verbose flag!

If this were added, it would look something like this:

```yaml
mkdocs:
  verbose: true
```

**Comment by humitos** [comment]
For future reference: https://github.com/mkdocs/mkdocs/issues/3013

**Comment by humitos** [comment]
Hey @KevinMGranger  👋🏼 ! You can use `build.jobs` config file now to run any command you want and debug MkDocs. Take a look at https://docs.readthedocs.io/en/latest/build-customization.html

Feel free to reopen this issue if that does not solve your problem.
