### ISSUE TITLE
Trigger a build for default branch and `latest` when saving the project form

### ISSUE THREAD

**Issue by lindstro** [readthedocs/readthedocs.org#9685]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/zfp/

## Expected Result

Selecting the "default branch" in Admin->Advanced Settings and clicking "Save" should result in the "latest" version (https://zfp.readthedocs.io/en/latest/, in our case) rebuilding/showing HTML documentation on that branch.  Specifically, after selecting "release1.0.0" as default branch, documentation on the "release0.5.5" branch is still shown as latest.

## Actual Result

The HTML documentation is not rebuilt automatically after updating the "default branch."  After manually rebuilding via Overview->Build a version->latest today, both the HTML and PDF were updated, but unfortunately this attached today's date to the PDF, which is over two months later than the release date (can this be reverted?).  This behavior appears different from the "default version" setting, which when updated resulted in expected behavior, i.e., https://zfp.readthedocs.io/ correctly shows documentation for version 1.0.0.

If my expectations are wrong, what is the proper procedure for updating both the default version and branch to point to a new release and having those take effect immediately?

**Comment by stsewd** [comment]
Hi, I wasn't able to replicate this, the build not being triggered after changing the default branch could have been a temporal issue. We always trigger a build to `latest` after the form is saved.

> but unfortunately this attached today's date to the PDF, which is over two months later than the release date (can this be reverted?)

Sorry, this isn't possible other than manually changing the date.

**Comment by lindstro** [comment]
Thanks for clarifying.  I'll keep an eye on this for our next release.

I didn't realize you could manually override the date for the PDF generation.  I was able to do so successfully by setting `today` in the Sphinx `conf.py`.  Is that the recommended way of doing it?

**Comment by stsewd** [comment]
> I was able to do so successfully by setting today in the Sphinx conf.py. Is that the recommended way of doing it?

I haven't had the need to that, so not sure. But I'd say is okay, but keep in mind that this is used with https://docs.python.org/3/library/time.html#time.strftime

https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-today

**Comment by lindstro** [comment]
Well, `today_fmt` isn't used when `today` is non-empty, so it seems that one could just override the date by setting `today`.

One issue I see is that fixing this would require pushing a commit to a "frozen" release branch.  This would cause it to diverge from our `master` branch, which on GitHub takes on the role of `latest`.  I don't suppose there's any way ReadTheDocs keeps a backup of files (the PDF in question) that could be easily restored without having us do surgery on the repo itself?  Or to just manually replace the PDF--I can supply one with a corrected date.

**Comment by stsewd** [comment]
> Or to just manually replace the PDF--I can supply one with a corrected date.

We don't usually do this, but we can make this one-time exception. Please email us to support@readthedocs.org with the PDF you want us to replace (this will be replaced only for the latest version, if you want it replaced in the 1.0.0 version as well, let us know).

**Comment by lindstro** [comment]
Thanks--I emailed a PDF.  And yes, we'd like the PDF for both the `latest` and `release1.0.0` branches updated.  But isn't this one and the same PDF?  When I click PDF for the `latest` branch, it takes me to https://zfp.readthedocs.io/_/downloads/en/release1.0.0/pdf/, as desired.

**Comment by lindstro** [comment]
The PDFs have been updated.  Thanks for your help.

**Comment by lindstro** [comment]
This same issue I was having earlier with the [zfp project](https://zfp.readthedocs.io/en/latest/) is occurring again with `latest` pointing to `release1.0.0`, both for the HTML and PDF documentation, even though it's set to point to `release1.0.1` in Advanced Settings:

<img width="586" alt="image" src="https://github.com/readthedocs/readthedocs.org/assets/1304791/1a0a1943-59aa-4851-b143-d28ed8401976">

Are any GitHub pushes or manual rebuilds of `latest` needed to force an update?  The answer above seems to suggest not, yet I'm seeing the same issue again.

**Comment by stsewd** [comment]
@lindstro hi, the problem is that only the release1.0.1 version was rebuilt, the `latest` version wasn't, you can manually trigger a build for latest. I'll check why it wasn't triggered.

**Comment by lindstro** [comment]
@stsewd Thanks for your help.  Looks like you may have done some work to fix this?  This is the second time that `latest` is not being rebuilt when pointing it at a new branch, so there's definitely something wrong that needs fixing.

**Comment by stsewd** [comment]
@lindstro this is a bug, the attached PR should fix it.

**Comment by lindstro** [comment]
Thanks for fixing.

**Comment by lindstro** [comment]
I am reopening this issue as `latest` still points to an old version (zfp 1.0.0 in this case rather than 1.0.1):

<img width="1129" height="710" alt="Image" src="https://github.com/user-attachments/assets/cb716d37-ea1f-4c54-9df0-27f531f1ed10" />

Not sure if the PR mentioned above solves this issue only for future releases.

To fix this issue for my current `latest` version, is it recommended that I trigger a manual rebuild of `latest` from the Versions tab in this screenshot?  I was previously concerned that doing so would attach the wrong date (today's date instead of the release date) to the PDF, but I believe my `conf.py` will override the date.  Any other potential concerns I should be aware of before trying this?

**Comment by lindstro** [comment]
I decided to simply go ahead and rebuilt `latest`, which initially did not seem to fix the issue.  After waiting 5-10 minutes after the build completed, links to the correct version seemed to finally be working.  I'm closing this issue.
