### ISSUE TITLE
Admin: bad request saving project admin

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#9687]
I just tried to save a project in the Django admin (I was updating the allowed time limit for the project), and I got a 400 bad request response.

Sentry didn't have the traceback, but did record the error:

`The number of GET/POST parameters exceeded settings.DATA_UPLOAD_MAX_NUMBER_FIELDS.`

**Comment by humitos** [comment]
I think this happens when a project has a lot of versions. We are displaying the versions inline. We should probably remove those because are useless, IMO.

**Comment by agjohnson** [comment]
Roger, that makes a lot of sense. Agreed, I don't think I ever change anything in the versions list. If there was a read only list, that would be helpful -- I do sometimes review the versions list form for configuration

**Comment by stsewd** [comment]
@agjohnson was this locally? Because we have this setting for the admin (see admin.sls on rtd-ops)

```python
DATA_UPLOAD_MAX_NUMBER_FIELDS = None
```

https://docs.djangoproject.com/en/4.1/ref/settings/#data-upload-max-number-fields

**Comment by agjohnson** [comment]
This was in prod on commercial, not local. I didn't see any traces in Sentry

**Comment by stsewd** [comment]
@agjohnson oh, looks like that setting is on .org only, we should set it in .com too

**Comment by ericholscher** [comment]
Looks like that PR we just merged should solve this, but I agree with removing inline versions. I do use those sometimes to see how a project is performing, but it's definitely overwhelming when they have a lot of versions.
