### ISSUE TITLE
referenced rst files via include directive no longer rendering

### ISSUE THREAD

**Issue by jessestewart1** [readthedocs/readthedocs.org#9700]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/egp-crn/
* Build URL (if applicable): https://readthedocs.org/projects/egp-crn/builds/18494894/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/jessestewart1/

## Expected Result

*I have several instances where I use the "include" directive to reference a local .rst file containing raw html to be rendered in the document.*

## Actual Result

*They are no longer being rendered. These sections appear empty in my docs. See this page (where most of my .rst inclusions should be): https://egp-crn.readthedocs.io/en/latest/source/road_network_collapse/meshblock_conflation.html#scenario-missing-ngd-roads*

**Comment by stsewd** [comment]
Hi @jessestewart1, I see a lot of warnings in your build related to your problem (you can click on the command to see the output).

> .../docs/source/road_network_collapse/meshblock_conflation.rst:103: WARNING: "source/_static/meshblock_conflation/qgis_example_output.rst": line 10 exceeds the line-length-limit.

You should be able to replicate those warning locally by executing the same commands you see on Read the Docs on a clean environment.

**Comment by jessestewart1** [comment]
Ah solved it. The other week I tried reducing dependencies in my environment.yml by removing Sphinx, but my specific documentation structure requires version 4.0.0 otherwise several things don't work as expected. Removing my explicit Sphinx version dependency made it use the latest version instead...causing the issue.
