### ISSUE TITLE
Docs: Diátaxis task bucket (meta)

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#9702]
**_This issue is here to track smaller items. Once there is more time, it should be processed and individual actionable issues can be opened._**

This list will be updated for each Diátaxis refactor that occur and results in the need or idea for other documentation updates.

What this issue is _not_:

* A plan / design / implementation of contents
* A list of approved proposals... it's just a reminder of things to get back to!

The intention is that we can do a larger refactor with fewer distractions.

## Page-specific

* Replace "VCS" in titles
* Create a new reference/feature page for Traffic Analysis
* Create a new reference/feature page for "VCS Integration" (but with some other title)
* Improve the Build Notification feature page with screenshots

## General items

* Align titles, navigation titles and one-line descriptions. Potentially use meta directives by writing a role to access [BuildEnvironment.metadata](https://www.sphinx-doc.org/en/master/extdev/envapi.html#sphinx.environment.BuildEnvironment.metadata)
* Reusable admonition in `docs/user/shared`: "This function is only accessible by an owner of your Read the Docs for Business subscription. If you are not the owner..."

**Comment by humitos** [comment]
@benjaoming is this issue still relevant? I think most of it is already tracked in the Diataxis iteration issues and we can close this one.

**Comment by benjaoming** [comment]
Currently, we are working a bit faster than we can open and close individual tickets about smaller tasks.

Perhaps we can break this one down during the next Sprint. Adding it to the roadmap to do that...

**Comment by benjaoming** [comment]
All of these items are now either done or mentioned elsewhere :+1:
