### ISSUE TITLE
conda dependency conflicts in RTD environment only

### ISSUE THREAD

**Issue by emlys** [readthedocs/readthedocs.org#9703]
## Details
My project depends on `gdal>=3.4.2`. In trying to isolate an issue, I found that builds fail in an environment with just that one dependency:
```
# environment.yml
channels:
- conda-forge
- nodefaults
dependencies:
- gdal>=3.4.2
```
I see that in the RTD build, there are some extra dependencies added:
```
# environment.yml
channels:
- conda-forge
- nodefaults
dependencies:
- gdal>=3.4.2
- pip:
  - recommonmark
  - readthedocs-sphinx-ext
- mock
- pillow
- sphinx
- sphinx_rtd_theme
```
The `conda env create --quiet --name 95 --file environment.yml` command works for me locally with either of these environment files.

* Read the Docs project URL: https://readthedocs.org/projects/invest-userguide/
* Build URL (if applicable): https://readthedocs.org/projects/invest-userguide/builds/18508851/

## Expected Result

I expect to be able to create a conda environment from a valid set of dependencies.

## Actual Result

I get dependency conflicts on a set of dependencies that are valid locally

**Comment by humitos** [comment]
@emlys is this issue still happening to you? I think I could enable `CONDA_APPEND_CORE_REQUIREMENTS` in your project to workaround this issue: https://docs.readthedocs.io/en/stable/feature-flags.html#feature-flags

**Comment by emlys** [comment]
Thanks but we have decided to move away from ReadTheDocs for building this project.
