### ISSUE TITLE
Allow to set git clone depth

### ISSUE THREAD

**Issue by DifferentialOrange** [readthedocs/readthedocs.org#9708]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/tarantool-python/
* Build URL (if applicable): https://readthedocs.org/projects/tarantool-python/builds/18526775/
* Read the Docs username (if applicable): DifferentialOrange

We use [setuptools_scm](https://pypi.org/project/setuptools-scm/) to compute our package version automatically based on git metadata. Documentation displays the package version.

## Expected Result

setuptools_scm successfully computes package version in every case.

## Actual Result

setuptools_scm fails to compute expected package version if there are more than 50 commits since last tag.

Since git clone depth is 50 in build pipeline, tag info is not fetched and it displays `0.1.dev50+g26c6db1` version instead of `0.9.1.dev73+g26c6db1`. It would be nice to be able to tune git clone settings to fix such behavior.

**Comment by humitos** [comment]
Hi @DifferentialOrange! You can use https://docs.readthedocs.io/en/latest/build-customization.html#unshallow-clone to unshallow your repository. Let me know if that doesn't work for you for any reason.

**Comment by DifferentialOrange** [comment]
> Hi @DifferentialOrange! You can use https://docs.readthedocs.io/en/latest/build-customization.html#unshallow-clone to unshallow your repository. Let me know if that doesn't work for you for any reason.

That helped. Thanks a lot!
