### ISSUE TITLE
[UX] Filter repositories sidebar should label the account origins

### ISSUE THREAD

**Issue by webknjaz** [readthedocs/readthedocs.org#9718]
## Details

I've got GitHub, GitLab and Bitbucket accounts linked to RTD. All of these account have the same username and the profile picture. As a result, on the "Import a Repository" page, the "Filter repositories" sidebar shows 3 exactly identical entries.
I suppose it'd be the same if there'd be an organization I'd have access to across multiple hostings.

* Read the Docs project URL: https://readthedocs.org/dashboard/import/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/webknjaz/

## Expected Result

It should be possible to distinguish between the accounts from different code hostings.
The easiest solution I could think of is to just add icons of the corresponding code hosting next to each entry.
While there, it could also be useful to know if an account is a user or an org.

## Actual Result

It's a guessing game. Here's what it looks like to me:
![rtd-confusing-filtering](https://user-images.githubusercontent.com/578543/200646529-737015af-f8df-4ad1-8b10-864a4838cb86.png)

**Comment by humitos** [comment]
We solved this issue in the new templates. You can search for the specific repository you want now and it auto-completes/auto-suggests the results showing all the organizations/usernames you belong to:

![Screenshot_2023-06-05_12-20-13](https://github.com/readthedocs/readthedocs.org/assets/244656/c6bca388-f098-4656-9f43-2d1af5834239)

Please, give it a try at https://beta.readthedocs.org/ and let us know any feedback you may have 👍🏼
