### ISSUE TITLE
DIsable the version component in RTD

### ISSUE THREAD

**Issue by renardeinside** [readthedocs/readthedocs.org#9720]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/dbx/
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): N/A

## Expected Result

*A description of what you wanted to happen*

No version overlay in my project (component with class `rst-current-version`.

## Actual Result

Since some time ago the following version overlay appeared (e.g. [here](https://dbx.readthedocs.io/en/latest/intro/)):
<img width="594" alt="Screenshot 2022-11-09 at 12 38 40" src="https://user-images.githubusercontent.com/4979594/200820752-39a73679-e94e-461b-b9a0-ce782cf75204.png">

I would like to be able to disable it. Project docs are made with mkdocs-material.

**Comment by stsewd** [comment]
Hi! You can change the position of the flyout menu, or hide it using CSS, see https://docs.readthedocs.io/en/stable/flyout-menu.html.

**Comment by cbrnr** [comment]
@stsewd could you please be more specific on how to hide it? The linked documentation doesn't mention this explicitly.

I would happily leave the flyout menu on my site if it was working – currently, it is rendered but clicking on it has no effect (see https://sleepecg.readthedocs.io/en/stable/).

**Comment by humitos** [comment]
@cbrnr 

> I would happily leave the flyout menu on my site if it was working – currently, it is rendered but clicking on it has no effect (see [sleepecg.readthedocs.io/en/stable](https://sleepecg.readthedocs.io/en/stable/)).

I think it's because the flyout depends on jQuery and you are using Material for MkDocs theme that does not include it. You could manually include jQuery in your project to make it work properly.

We are working on better integration with Material for MkDocs that will solve this problem in the near future.

**Comment by cbrnr** [comment]
Thank you @humitos! I'm looking forward to a better integration with Material! Meanwhile, if I do not want to include jQuery, can the flyout be disabled or hidden without much hassle?

**Comment by chester-leung** [comment]
Hi @humitos , do you have any estimated timeline on the integration with Material for MkDocs? Thank you.

**Comment by humitos** [comment]
Hi @chester-leung! The integrations with Material for MkDocs is already in our roadmap, so hopefully it will be done in 2023 Q1.

**Comment by cbrnr** [comment]
And what about disabling for now?

**Comment by chester-leung** [comment]
@cbrnr there is a workaround for this [here](https://github.com/squidfunk/mkdocs-material/issues/3104#issuecomment-1348044223). I tested this and it seems to work!

**Comment by humitos** [comment]
Great! I'm happy that you found a solution to inject jQuery on Material for MkDocs. We are already working on a better integration with Material for MkDocs and we won't be assuming that jQuery is already loaded in the near future. I'm closing this issue, but feel free to open a new one if you find any other problem 👍🏼
