### ISSUE TITLE
Docs: add landing page example using `build.commands`

### ISSUE THREAD

**Issue by agjohnson** [readthedocs/readthedocs.org#9722]
This is an example I've wanted for a while, and overlaps with discussing build.commands more.

Post/docs should show:

- Project topology -- subprojects, etc
- How to use a separate tool to build docs

Maybe now, maybe later:

- How to generate up to date information, like new subproject active versions etc (can't be the API though?)

**Comment by ericholscher** [comment]
Cool example: https://docs.nautobot.com/

**Comment by benjaoming** [comment]
Question:

Is this issue about creating a new example repository in readthedocs-examples?

Follow-up question:

Should we use the new monorepo layout to showcase this?

**Comment by agjohnson** [comment]
I would say monorepo is not related to a landing page and should be it's own example. A landing page is strictly a lightweight project and it would have a custom domain attached and would have subprojects configured.

I'd probably even keep all tooling out of this example entirely and just use straight HTML for a landing page. Isolated examples will allow users to pick their own patterns.

**Comment by ericholscher** [comment]
I think we've done most of this work, so going to call this done 👍

**Comment by agjohnson** [comment]
Can visit this in https://github.com/readthedocs/readthedocs.org/issues/11187
