### ISSUE TITLE
Instructions for adding a custom domain are slightly confusing

### ISSUE THREAD

**Issue by tudortimi** [readthedocs/readthedocs.org#9729]
I struggled a bit with adding a custom domain. The [doc page](https://docs.readthedocs.io/en/stable/custom-domains.html) says to:

1. Go the Admin tab of your project.
1. Click on Domains.
1. Enter your domain.
1. ...

I added my domain for the project (`svunit.org`). I set up a CNAME record for `docs.svunit.org` to `svunit.readthedocs.io`, even though the doc page says to add a record to `readthedocs.io`. My thought process was that this was the way to tie `docs.svunit.org` to `svunit.readthedocs.io`, because how else would Read The Docs know which project to tie my URL to?

After some certificate errors, the admin page saying "validation pending" for the certificate, and some experimentation, I finally figured out that I'm supposed to use use the subdomain (`docs.svunit.org`) as the domain in the admin page and really set `readthedocs.io` as the CNAME record target.

The doc page (and maybe the admin page as well) could prevent such errors if they would explicitly say something like "Enter your domain (or subdomain)".

**Comment by humitos** [comment]
Hi @tudortimi! Thanks for opening this issue.

I'm not sure to understand your description. You said the documentation tells you to add a CNAME pointing to `readthedocs.io` but you added `svunit.readthedocs.io` instead. Then after some problems and investigations you changed it what the documentation says and it worked.

Am I missing something? What's the part of the documentation that's confusing?

**Comment by tudortimi** [comment]
> Enter your domain.

This is what's confusing, because the user is supposed to enter their sub-domain if they want to use a sub-domain.

The docs make it seem that the user has to input their root domain. For example, in other places it shows domains of the type `YOURDOMAIN.TLD` . It made me think I have to put `svunit.org` in there, not `docs.svunit.org`.
