### ISSUE TITLE
Small documentation changes causing hanging and excessive memory consumption

### ISSUE THREAD

**Issue by Zeitsperre** [readthedocs/readthedocs.org#9735]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/xclim/
* Build URL (if applicable): https://readthedocs.org/projects/xclim/builds/18640278/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/Zeitsperre/

I'm attempting to link my repository's `README.rst` to the RTD documentation, and I am seeing significant hanging and excessive memory usage. There are no issues for me building the documentation locally and the changes are relatively minuscule (https://github.com/Ouranosinc/xclim/pull/1233). The only thing I can think of is that there are a few more URL targets, but that should not be build-breaking.

It would be helpful to know where the issue is arising when building on RTD,

## Expected Result

Something resembling https://xclim.readthedocs.io/en/latest/

## Actual Result

` Build took 1910 seconds `
...
`Command killed due to timeout or excessive memory consumption`

**Comment by Zeitsperre** [comment]
Following up on this:

I still cannot pinpoint the cause of this failure. Locally, the build time is nearly identical between the development and main branches. The only addition is the integration of the README of my project (which includes some hyperlinks).

I'm wondering if part of the issue is that some hyperlinks point to the documentation on ReadTheDocs. Is it possible that this is causing a memory issue when building on ReadTheDocs? The lack of useful output from the build logs makes this especially difficult to address.

**Comment by humitos** [comment]
Hi! The problem is not memory consumption, but time out. It seems there are lot of links and making a request per link takes a lot of time. Finally, the build time is exceeded (1910 seconds!) and the build is cancelled because of that.

**Comment by Zeitsperre** [comment]
The fact that it's a timeout makes sense. The thing is that the number of links added in my PR (linking to the ReadMe page) is not significant (an addition of around 15 links, some to ReadTheDocs itself). Other builds tend to finish in around 600 seconds, so I'm having trouble figuring out how a 200% increase in build time can happen.

Is it possible that some hyperlinks being checked could be stalling the build ? If so, why is this only happening on ReadTheDocs and not locally? Is there a way to modify the request wait time in sphinx?

I'm going to try ignoring most of the hyperlinks on the ReadMe as a test, but something still isn't adding up.

**Comment by humitos** [comment]
There are lot of links returning 503. That should give you an insight where it's the problem. Probably, `linkcheck` does not have a timeout and that's why it's consuming so much time.

```
-ignored- https://doi.org/10.1002/wics.1375: 503 Server Error: Service Temporarily Unavailable for url: https://onlinelibrary.wiley.com/doi/10.1002/wics.1375
```

**Comment by Zeitsperre** [comment]
I see, so I should set a timeout that's much less than the default (my settings locally suggest `None`, i.e. wait forever?). I've bypassed this problem in my builds by ignoring more links for the time being, but I'll give the timeout setting approach a try and report back here.

Thanks again, @humitos !
