### ISSUE TITLE
Removing an old abandoned project of mine

### ISSUE THREAD

**Issue by kmod** [readthedocs/readthedocs.org#9741]
Hello, I have an old project up at https://pyston.readthedocs.io/en/stable/. The docs are completely out of date and are confusing to our new users, and I'd like to simply take the project down.

Unfortunately I don't remember which account I used to create the readthedocs project, and it's possible that I no longer have access to it. I believe it meets the criteria for an abandoned project so I'm hopeful that we can do this. Ideally the project could be simply taken down, but if necessary I can create a new github account that I'm willing to connect to readthedocs and I could take these steps if that account was added as a manager. Or if you can tell me which github account created it originally then I could try to manage it from there.

**Comment by humitos** [comment]
@kmod if you have a Read the Docs account, please contact us using the form from the application at https://readthedocs.org/support/ (preferred)

Otherwise, please send us an email about this issue at support@readthedocs.org. Thanks 🙏🏼

**Comment by kmod** [comment]
I'm not going to give anyone all of the permissions you ask for, so I emailed the email address.
