### ISSUE TITLE
Build: `--upgrade-strategy eager` upgrade packages that were already pinned

### ISSUE THREAD

**Issue by felixchalumeau** [readthedocs/readthedocs.org#9752]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/qdax/
* Build URL (if applicable): https://readthedocs.org/projects/qdax/builds/18693487/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/felixchalumeau/

A recent PR from the project QDax has it's readthedocs's stage of CI [broken](https://github.com/adaptive-intelligent-robotics/QDax/pull/108) although there has been no core change in this PR. More generally speeking, all our recents PRs have a broken documentation, although they branch from develop that had a working CI.

Interestingly, I cannot reproduce the error when I try to serve the documentation on my local computer with `mkdocs serve` (everything is fine locally).

## Expected Result

I would expect the docs to build.

## Actual Result

Cf. to details section of this issue, the doc does not build on readthedocs while no breaking change happened in the code and while it seems to work locally.

**Comment by humitos** [comment]
Hi @felixchalumeau! Make sure you are using the exact same versions of Python packages locally than on Read the Docs build environment. Take a look at https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html

At first sight, I'd guess there is a version difference in `pytkdocs` since it's where the dictionary key is not found.

**Comment by felixchalumeau** [comment]
Hi @humitos 

Thanks for you quick answer!

First, good news, I fixed my issue. It was not due to docs requirements but to other requirements from the project.

Second, I wanted to ask you a question about the situation that I encounter. My project is indeed using the good practices presented in the link your shared. But some uncertainty in the requirements used in the final build of the docs comes from the last step from the process in readthedocs : `pip install --upgrade --upgrade-strategy eager --no-cache-dir .`, which overrides some dependencies from `requirements.txt` by using those from `setup.py`. 

This creates some uncertainties because it seems that the good practice is to not fix the dependencies in setup.py files.

This is what happened in my case. One of my dependencies is pinned in my requirements but not in the setup, and was hence updated during the `pip install .` and created the issue. 

Do you think it would be possible/better to install the package while keeping the exact requirements given in the requirement files?

**Comment by benjaoming** [comment]
@felixchalumeau We have a loot of good experiences with pip-tools. We use it to manage two versions of our requirements: The loosely pinned requirements, and the exactly pinned requirements.

See more: https://github.com/jazzband/pip-tools

**Comment by Zeitsperre** [comment]
Running into this issue today specifically due to the need to pin some geospatial libraries (GDAL). Would be great to have some control over these install flags!

**Comment by ericholscher** [comment]
This change should now be deployed, if anyone who is still having this issue could confirm things look better 👍
