### ISSUE TITLE
"Edit on GitHub" link points to the non-existent Master branch even though the default branch is Main

### ISSUE THREAD

**Issue by EISTW** [readthedocs/readthedocs.org#9762]
## Details

Read the Docs project URL: (https://openldocs.readthedocs.io/en/latest/)

## Expected Result
When a web page visitor clicks "Edit on GitHub" it opens GitHub showing the default branch of the associated repo (as specified in RTD Advanced Settings).

## Actual Result
When a web page visitor clicks "Edit on GitHub" it sends them to https://github.com/<GitHub username>/><ProjectName>/edit/**master**/docs/index.md even though in Advanced Settings the default branch is set to Main (in our case it was previously Master but we no longer have a Master branch). A 404 "Page not Found" error is subsequently shown.

**Comment by stsewd** [comment]
Hi, that's the mkdocs's default, you need to change this setting

https://www.mkdocs.org/user-guide/configuration/#edit_uri

**Comment by EISTW** [comment]
Ah! Great. Thanks for that!

Adrian
