### ISSUE TITLE
RTD No longer builds my project after I added the Superfences configuration

### ISSUE THREAD

**Issue by EISTW** [readthedocs/readthedocs.org#9766]
## Details

Build URL: (https://github.com/EISTW/OpenLdocs)

## Expected Result

ReadtheDocs successfully builds my project after I add the superfences configuration to the mkdocs.yml file:

```

markdown_extensions:
  - markdown.extensions.admonition
  - pymdownx.superfences

```

## Actual Result

RTD build fails with the following err msg:

```
[31mERROR    -  [0mConfig value 'markdown_extensions': Failed to load extension 'pymdownx.superfences'.
ModuleNotFoundError: No module named 'pymdownx'
Aborted with 1 Configuration Errors!
```

**Comment by stsewd** [comment]
Hi, that's because you need to install those dependencies on RTD, see https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#using-a-configuration-file

**Comment by EISTW** [comment]
Thanks. My requirements.txt file has this content below. Are you saying it should also have something related to the pymdownx.superfences extension? (It is not clear to me from the link that you posted exactly what dependency I am missing).

```
jinja2==3.1.2
markdown==3.3.7
mkdocs==1.4.2
```

**Comment by stsewd** [comment]
@EISTW yes, you need to add the dependency that provides the pymdownx extension

**Comment by EISTW** [comment]
Okay thanks again. I added pymdown-extensions and it is working now.
