### ISSUE TITLE
`transifex-client` in docs (deprecated tool, sunset on Nov 30, 2022)

### ISSUE THREAD

**Issue by rffontenelle** [readthedocs/readthedocs.org#9767]
## Details

The [Using Transifex](https://docs.readthedocs.io/en/stable/guides/manage-translations-sphinx.html#using-transifex) section in [Manage Translations for Sphinx projects](https://docs.readthedocs.io/en/stable/guides/manage-translations-sphinx.html#manage-translations-for-sphinx-projects) page in RTD's docs uses [transifex-client](https://github.com/transifex/transifex-client/).

transifex-client uses Transifex APIv2, which will sunset in November 30 (tomorrow) and will stop working. Now, the recommended tool is the [Transifex CLI tool](https://github.com/transifex/cli)

**Comment by RCheesley** [comment]
+1 on this, I'm bumping into this problem trying to understand how to use the new version.

Docs are here: https://github.com/transifex/cli/blob/devel/README.md#adding-resources-in-bulk - bulk mapping is no longer available and they provide some suggestions on how to work around it, but it's a bit too much for me to understand what's going on under the hood to know how to proceed.

Asked for guidance in https://community.transifex.com/t/struggling-with-github-sync-and-has-no-metadata-to-indicate-the-github-file-path/3112/24?u=rcheesley - will make a PR to update the docs if they come back to me with some suggestions!

**Comment by rffontenelle** [comment]
@RCheesley I know two solutions for regenerating the .tx/config, and none of them involves the new Transifex CLI tool. They are: sphinx-intl or Transifex Python SDK.

When using the [sphinx-intl](https://sphinx-intl.readthedocs.io) method, you need to first generate the POT file from the project. Then use `sphinx-intl update-txconfig-resources` (preceeded by `sphinx-intl create-txconfig` if the .tx/config doesn't exist yet). See [how I do for the python-doc Transifex organization](https://github.com/rffontenelle/docspush-transifex/blob/main/.github/workflows/ci.yml).

When using the [Transifex Python SDK](https://developers.transifex.com/reference/api-python-sdk), you can query the Transifex for information like projects in an organization, and resources in a project. Then you do a filename normalization (e.g. library--re resource should be library/re.po file). This requires less setting up the environment, requires installing transifex-python library, and requires more scripting. See how [Ukraine teams for Python documentation did](https://github.com/python/python-docs-uk/blob/main/.github/scripts/manage_translation.py) (`_slug_to_file_path` and `recreate_config` functions)

Note that the sphinx-intl method recreates the config based on the strings and files extracted into POT, while in the Transifex CLI client you recreate the config based on info fetched from Transifex. First method seems important for setting up source strings in a Transifex project (`tx push --source`)

**Comment by RCheesley** [comment]
Thanks @rffontenelle - it would be super appreciated to have a very clear, step-by-step guide with examples, just like there is currently, on how to get from the starting point of an all-base-language RTD instance, to having the strings up on Transifex and ready to be translated. 

It would be super helpful for folks like me who maybe aren't so familiar with the inner workings of everything, and don't know much Python either.

I can help with the Transifex GitHub integration side of things, if that's of any use, as that was quite something to set up (they recommend a totally different route to the docs on RTD, which we just could never get to work, using their GitHub integration.

**Comment by rffontenelle** [comment]
Hey, I'm dropping a pull request here, which hopefully solves this issue. Tests and feedback are welcome.
