### ISSUE TITLE
Command killed due to timeout or excessive memory consumption

### ISSUE THREAD

**Issue by xiki-tempula** [readthedocs/readthedocs.org#9776]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/alchemlyb
* Build URL (if applicable): https://readthedocs.org/projects/alchemlyb/builds/18814878/ 

Github: https://github.com/alchemistry/alchemlyb/pull/277

## Expected Result

The build runs

## Actual Result

```
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Collecting package metadata: ...working... done
Solving environment: ...working... Killed


Command killed due to timeout or excessive memory consumption
```

**Comment by humitos** [comment]
(from the phone)

Please, try using Mamba instead of Conda to manage your environment. That would fix this issue

**Comment by xiki-tempula** [comment]
@humitos Many thanks for the help. I'm investigating this option now. I wonder how do I install the package if I use the mamba?
I used to do
```
python:
  version: 3.8
  install:
    - method: pip
      path: .
```
I think I should be doing 
```
build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
```
now but I'm not sure of how to adopt the 
```
  install:
    - method: pip
      path: .
```
part. Thank you.

**Comment by xiki-tempula** [comment]
Ok, I have solved the problem. Thank you.

**Comment by humitos** [comment]
Thanks! I'm closing this issue since your problem is solved already.
