### ISSUE TITLE
Build: environment variable for canonical URL

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#9781]
This is probably best solved together with https://github.com/readthedocs/readthedocs.org/issues/9423

* [x] Add a new environment variable `READTHEDOCS_CANONICAL_URL`
* [x] Add some test build that ensures it's correctly defined inside a build environment?
* [ ] Update [example-mkdocs-basic](https://github.com/readthedocs-examples/example-mkdocs-basic/)
* [x] Update documentation
* [ ] Mark https://github.com/readthedocs/readthedocs.org/issues/4820 as fixed through the documentation and example

**Comment by stsewd** [comment]
This is kind of similar to https://github.com/readthedocs/readthedocs.org/issues/8260, but that includes the whole URL
