### ISSUE TITLE
unable to change branch from default

### ISSUE THREAD

**Issue by showierdata9978** [readthedocs/readthedocs.org#9786]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/scratchvmdocs/

## Expected Result

branch changing dropdown shows all branches

## Actual Result

no branches are showed apart from `-----------`

**Comment by showierdata9978** [comment]
this shows up with github manually imported (as it did not show up when trying to import manually) , and main branch being 'main' instead of master

**Comment by showierdata9978** [comment]
![image](https://user-images.githubusercontent.com/68120127/206293277-a4d1fc43-8e58-42b6-a665-5a2ea7d95e53.png)

**Comment by benjaoming** [comment]
Hi @showierdata9978 - thanks for reporting this. Is it the same issue as https://github.com/readthedocs/readthedocs.org/issues/9369 ?

**Comment by showierdata9978** [comment]
prob, did not see it
