### ISSUE TITLE
Missing searchtools warning when making LaTeX

### ISSUE THREAD

**Issue by tjk584** [readthedocs/readthedocs.org#9796]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/borealis/
* Build URL (if applicable): https://readthedocs.org/projects/borealis/builds/18872987/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/superdarncanada/
* Documentation source code: https://github.com/SuperDARNCanada/borealis/tree/readthedocs_cleanup/docs

## Problem

I am getting the following warning when I try to compile my docs into latex format:

```
copying TeX support files... copying TeX support files...
done
WARNING: Missing searchtools: /home/docs/checkouts/readthedocs.org/user_builds/borealis/checkouts/readthedocs_cleanup/docs/source/_build/latex/_static/searchtools.js
build succeeded, 1 warning.

The LaTeX files are in _build/latex.
```

I believe this error is thrown from this line of code: https://github.com/readthedocs/readthedocs-sphinx-ext/blob/f1145b1819458643f442b21083b3397aeebc8e72/readthedocs_ext/readthedocs.py#L277

This problem doesn't occur when I compile the docs locally - see the source code linked above.

## Solutions Attempted

This problem is very similar to https://github.com/readthedocs/readthedocs.org/issues/5029, but I am using the latest version of Sphinx (5.3.x) instead.

I have tried:

- Copying the `searchtools.js` source code into my repo and loading in `conf.py` with:
```
html_search_scorer = 'searchtools.js'
```
- Loading `sphinx_search.extension` within `conf.py`

Neither made the warning go away.

**Comment by humitos** [comment]
I think this is a bug and the check for `searchtools.js` should only be done if the builder is HTML.

**Comment by humitos** [comment]
This was fixed in https://github.com/readthedocs/readthedocs-sphinx-ext/pull/129
