### ISSUE TITLE
Pin Tox version

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#9806]
* CI builds should not break because of Tox upgrades
* CI builds should be reproducible

We should track the version of Tox that CI builds use.

We should not specify the version in Circle CI but in a requirements/tox.in file such that the version is tracked together with the conventional mechanism.

**Comment by humitos** [comment]
We are currently pinning the version in CI: https://github.com/readthedocs/readthedocs.org/blob/3eae8f51fc4bb670f89fb47abd5ce23b5cd95e9a/.circleci/config.yml#L24
