### ISSUE TITLE
Enable no shallow clone (DONT_SHALLOW_CLONE) for cloud-init

### ISSUE THREAD

**Issue by holmanb** [readthedocs/readthedocs.org#9808]
## Details

Is this the right place to request DONT_SHALLOW_CLONE for readthedocs.com projects?

Per https://github.com/readthedocs/readthedocs.org/issues/5031 requesting DONT_SHALLOW_CLONE for cloud-init project.

* Read the Docs project URL: https://readthedocs.com/projects/canonical-cloud-init
* Build URL (if applicable): https://readthedocs.com/projects/canonical-cloud-init/builds/1220162/

**Comment by holmanb** [comment]
> Is this the right place to request DONT_SHALLOW_CLONE for readthedocs.com projects?

I'm suspecting the answer to this question is no, per section [1.11.5](https://readthedocs.org/projects/read-the-docs/downloads/pdf/latest/). I'm going to try to track down my site admin internally, but I'll leave this open in the off chance that this _is_ the right path.

Feel free to close if I'm searching in the wrong places.

**Comment by ericholscher** [comment]
You can ask support to enable this for you: https://docs.readthedocs.io/en/stable/support.html

**Comment by stsewd** [comment]
Hi, you should be able to unshallow your project by using the config file, see https://docs.readthedocs.io/en/stable/build-customization.html#unshallow-clone.
