### ISSUE TITLE
Update JSON schema

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#9822]
Our json schema is outdated https://github.com/readthedocs/readthedocs.org/blob/main/readthedocs/rtd_tests/fixtures/spec/v2/schema.json (`build.comands` is missing), and we should also make use of the `deprecated` field https://json-schema.org/draft/2020-12/json-schema-validation.html#name-deprecated for deprecated features (like `pyhton.version`).

**Comment by KhalilJoya** [comment]
{
  $jsonSchema :{
    bsonType : "object",
    required : ["name" , "fatherName", "email", "DOB" ,  "mobile" , "batchName"] ,
    properties : {
      name :{
        bsonType : "string",
      },
      fatherName : {
           bsonType : "string",
      },
      email:{
          bsonType: "string",
        pattern: "^[a-zA-Z0-9._]+@+[a-zA-Z]+\.+[a-zA-Z]{2,}$"
      },
      DOB :{
        bsonType : "date",
      },
      mobile: {
        bsonType : "string",
        pattern: "^(\+?91|0)?[6789]\d{9}$"
      },
      batchName :{
        bsonType : "string",
        enum : ["Node.js", "Designing", "JavaScript", "Computerbasic"]
      }
    },
    address : {
      bsonType : "string"
    },
    fees : {
      bsonType : "number",
      minimum : 2000,
      maximum : 5000
    },
    marks : {
      bsonType : "array"
    }
  }
}
