### ISSUE TITLE
Build: Path trimming needs refinements (test case or regex pattern)

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#9833]
Follow-up from #9824

```
>       self.assertEqual(
            build["commands"][0]["command"],
            "python -m pip install --upgrade --no-cache-dir pip setuptools<58.3.0",
        )
E       AssertionError: '/home/docs/checkouts/readthedocs.org/user[101 chars].3.0' != 'python -m pip install --upgrade --no-cach[23 chars].3.0'
E       - /home/docs/checkouts/readthedocs.org/user_builds/myproject/envs/myversion/bin/python -m pip install --upgrade --no-cache-dir pip setuptools<58.3.0
E       + python -m pip install --upgrade --no-cache-dir pip setuptools<58.3.0
```

Origin of build error: https://app.circleci.com/pipelines/github/benjaoming/readthedocs.org/114/workflows/dc84d28d-ed92-4b40-8ce9-1638fc801eac/jobs/278

**Comment by humitos** [comment]
Meh, I merged that PR before merging the other ones. This will be fixed once https://github.com/readthedocs/readthedocs.org/pull/9831 got merged.

**Comment by benjaoming** [comment]
Awesome!! Thanks for fixing! Unfortunate, but making the build output easier to read is ace :100:

**Comment by benjaoming** [comment]
> Meh, I merged that PR before merging the other ones. This will be fixed once https://github.com/readthedocs/readthedocs.org/pull/9831 got merged.

Closing this, another issue fixed by @humitos :tada:
