### ISSUE TITLE
About the error in the installation steps of readthedocs local server

### ISSUE THREAD

**Issue by pilgrimage80** [readthedocs/readthedocs.org#9849]
I'm trying to install readthedocs on my local gitlab server and I'm following the guide in the link.

[ReadThedocs Guide](https://read-the-docs.readthedocs.io/en/latest/install.html)

Here's the python version and pip version I'm using;

Python3.9 
Pip3.9

To run the virtual pip environment, I use the following command.

**python3.9 -m venv tutorial-env  # I completed the install process with this command.** 

**source tutorial-env/bin/activate # with this command I access the virtual pip environment****

my steps in the virtual pip environment;

I run this from the readthedocs installation steps.

**(tutorial-env) [redhat@gitlab tutorial-env]$ pip install -r requirements.txt 
And no error occurred.**

(tutorial-env) [redhat@gitlab tutorial-env]$ python3.9 /home/redhat/readthedocs.org/manage.py migrate

**Gave the following error message**

[debug    ] Using slumber v2.              [readthedocs.api.v2.client] api_host=http://127.0.0.1:8000 username=test

Traceback (most recent call last):

  File "/home/redhat/readthedocs.org/manage.py", line 11, in <module>

    execute_from_command_line(sys.argv)

  File "/home/redhat/tutorial-env/lib64/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line

    utility.execute()

  File "/home/redhat/tutorial-env/lib64/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute

    django.setup()

  File "/home/redhat/tutorial-env/lib64/python3.9/site-packages/django/__init__.py", line 24, in setup

    apps.populate(settings.INSTALLED_APPS)

  File "/home/redhat/tutorial-env/lib64/python3.9/site-packages/django/apps/registry.py", line 122, in populate

    app_config.ready()

  File "/home/redhat/readthedocs.org/readthedocs/core/apps.py", line 15, in ready

    import readthedocs.core.signals  # noqa

  File "/home/redhat/readthedocs.org/readthedocs/core/signals.py", line 17, in <module>

    from readthedocs.core.unresolver import unresolve

  File "/home/redhat/readthedocs.org/readthedocs/core/unresolver.py", line 16, in <module>

    @dataclass(slots=True)

**TypeError: dataclass() got an unexpected keyword argument 'slots'**

because of this problem I can not install local readthedocs. What should I pay attention to to overcome this problem? I need your support on this issue.

**Comment by humitos** [comment]
(from the phone)

That's not the official documentation. Follow the instructions from https://dev.readthedocs.io/en/latest/install.html and let us know

**Comment by pilgrimage80** [comment]
this problem was solved when I installed python 3.10 version and pip 3.10

thankyou.

**Comment by pilgrimage80** [comment]
I don't quite understand what you are saying. right now I have gitlab installed on my redhat 7.9 system and I installed it by following the steps in this link. https://read-the-docs.readthedocs.io/en/latest/install.html it is running smoothly now. can there be a problem in the future because I did it with the installation of the steps in this link? Do you recommend me to follow the steps in the offical doc. right now readthedoc worked locally without any problems. only the integration step with gitlab is left.

**Comment by humitos** [comment]
(phone)

Yes, I recommend you to follow the official docs. The one you read are old and outdated. The environment has changed a lot since that docs was written.

**Comment by pilgrimage80** [comment]
Readthedocs do you need to install ubuntu specifically as a linux operating system. I currently want to install 7.9 on redhat but I am having trouble installing redhat 7.9 python 3.10. I also understand that readthedosc wants minium 3.10 as phyton.

**Comment by humitos** [comment]
Hi @pilgrimage80! I'm closing this issue. Please, follow the instructions from the official installation guide that uses Docker and let us know if you have any problem. You can read it at https://dev.readthedocs.io/en/latest/install.html

**Comment by pilgrimage80** [comment]
Honestly, I'm a bit nervous right now. Since I'm installing a non-offical configuration, I'll install it with a docker image first thing tomorrow. I hope I'll be successful. Thanks for the information.

**Comment by pilgrimage80** [comment]
Do I need to install docker redhat to run readthedocs docker install ?

**Comment by pilgrimage80** [comment]
Install the requirements from common submodule:

pip install -r common/dockerfiles/requirements.txt

When entering the command here, I need to enter it without root in pip venv environment?

**Comment by pilgrimage80** [comment]
I installed redhat 8.7 docker and when I enter inv docker.build command in pip venv virtual environment, I get " can't find any collection named task error.
