### ISSUE TITLE
URL for math images is incorrect (requires redirect)

### ISSUE THREAD

**Issue by murrayrm** [readthedocs/readthedocs.org#9852]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/python-control/

## Expected Result

Math that is rendered by Sphinx generates an image file that should show up on the documentation page via a link to an image in the directory `/en/<ver>/_images/math/`.

## Actual Result

The URL for math images is `/en/<ver>/generated/_images/math/` (extra `generated` in path), causing a 404 error.  A temporary fix is to set up a redirect from `/en/<ver>/generated/_images/` to `/en/<ver>/_images/`.

Example w/out redirect: https://murrayrm-python-control.readthedocs.io/en/readthedocs-17dec2022/generated/control.StateSpace.html#control.StateSpace

With redirect: https://python-control.readthedocs.io/en/latest/generated/control.StateSpace.html#control.StateSpace

**Comment by murrayrm** [comment]
Source code for the page above is https://github.com/python-control/python-control/blob/main/control/statesp.py#L166-L1520

Sphinx configuration file is https://github.com/python-control/python-control/blob/main/doc/conf.py

Page on documentation where image is displayed: https://python-control.readthedocs.io/en/latest/generated/control.StateSpace.html#control.StateSpace (this is the link above and uses the redirect to get the image to show).

This works correctly on my local machine:
```
nbsphinx                  0.8.9              pyhd8ed1ab_0    conda-forge
sphinx                    5.1.1              pyhd8ed1ab_1    conda-forge
sphinx_rtd_theme          0.5.2              pyhd8ed1ab_0    conda-forge
```

**Comment by humitos** [comment]
> This works correctly on my local machine:

Make sure you are using the same environment on Read the Docs. As far as I can see, it's using Sphinx 5.3.0 and sphinx_rtd_theme 0.4.3 (got this from https://readthedocs.org/projects/python-control/builds/19045950/)

You should pin your dependencies to use the versions that you know work correctly. See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html

**Comment by murrayrm** [comment]
Thanks @humitos.  Will try playing with this and post here if I can't get it to work consistently across my local machine and readthedocs.

**Comment by humitos** [comment]
I'm closing this issue. Feel free to re-open if you consider it's still valid.
