### ISSUE TITLE
Cannot see the docstrings of my documentation on read the docs, with no warning or errors, although locally it works

### ISSUE THREAD

**Issue by avacaondata** [readthedocs/readthedocs.org#9863]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/nlpboost/
* Build URL (if applicable): https://readthedocs.org/projects/nlpboost/builds/19075176/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/avacaondata/

## Expected Result

Locally I created a clean environment, did `pip install -e` to install my library, and then I'm able with `make html` inside docs to get a functional website, locally. However, when I try to upload to readthedocs, docstrings are not shown, I mean, there is no information on the package, methods, etc. There is no warning or error in the build log, so I don't understand what is going on... why are the docstrings correctly parsed locally but not on readthedocs? 

## Actual Result

The docstrings are not parsed by readthedocs, the modules appear completely empty.

**Comment by agjohnson** [comment]
I see a number of errors in your previous builds around missing modules. Guessing there was a path discrepancy between our build and your local build. It seems you probably figured it out, as the later builds show automodule output, but it's normal for Sphinx to silently skip this content when it encounters errors with importing modules or dependencies.

Is this the automodule output you're looking for?

https://nlpboost.readthedocs.io/en/latest/nlpboost.html
