### ISSUE TITLE
What is the cause of the error readthedocs install "Can't find any collection named tasks"

### ISSUE THREAD

**Issue by pilgrimage80** [readthedocs/readthedocs.org#9864]
According to the guide in the link, I am trying to install Readthedocs with docker. However, the "inv docker.build" mentioned in the doc gives an error like this

https://dev.readthedocs.io/en/latest/install.html

inv docker.build "Can't find any collection named 'tasks'!"

What is the cause of this error? I need to install according to the document in the link. My environment is redhat 9.0 docker-engine installed python 3.11 pip 22.3.3.1 I need help to overcome this problem. why does this command give such an error?

**Comment by agjohnson** [comment]
Seem you either missed a step in the installation setup, or you are not running the Invoke command from the repository checkout. Invoke, (`inv` command) is looking for `tasks.py` in the repository root.

I'd suggest looking at the Invoke docs if you are not familiar.

**Comment by pilgrimage80** [comment]
Set up your environment[¶](https://dev.readthedocs.io/en/latest/install.html#set-up-your-environment)
Clone the readthedocs.org repository:

git clone --recurse-submodules https://github.com/readthedocs/readthedocs.org/
Install the requirements from common submodule:

pip install -r common/dockerfiles/requirements.txt
Build the Docker image for the servers:

Warning

Hello, I am trying to install by following the steps in the dev document. In fact, I am very close to completing the installation successfully, but unfortunately I cannot complete the installation because I do not know exactly how to use the inv command. I need an answer that I think will take a little time because you are experienced and experienced. I have looked at the inv documentation but I have not mastered the subject. I am really trying to do a lot of research to install but I am stuck in the inv docker.build section because I have no experience. I would appreciate if you can help me with this. I need your valuable support when I am this close to the installation in the readthedocs docker environment.



**This command could take a while to finish since it will download several Docker images.

inv docker.build
Tip**


If you pass the GITHUB_TOKEN and GITHUB_USER environment variables to this command, it will add support for readthedocs-ext.

Pull down Docker images for the builders:

inv docker.pull --only-required
Start all the containers:

inv docker.up  --init  # --init is only needed the first time
Go to http://devthedocs.org/ to access your local instance of Read the Docs.

**Comment by pilgrimage80** [comment]
Actually, the reason I didn't want to run it as root was that I didn't want to run it as root because pip could affect system files in particular, so I heeded the warning not to run pip as root. Now when I run source activate command with root, enter pip virtual environment and run inv docker.build directly under readthedocs folder, the installation process started. I hope I'm doing it right this time. 

Thank you for your time.

**Comment by benjaoming** [comment]
Sounds good!

Notice that the development environment of Read the Docs is quite complex. If you want more guidance, I would suggest that you share a bit more about what you are working on and perhaps join the community on Gitter: https://dev.readthedocs.io/en/latest/contribute.html#get-in-touch
