### ISSUE TITLE
Mention/add `npm run vendor` in our frontend dev steps

### ISSUE THREAD

**Issue by stsewd** [readthedocs/readthedocs.org#9867]
We don't update our vendored packages that often, but when needed, I had no idea how to update them, we lost that step when migrating the process to docker.

See 
- https://github.com/readthedocs/readthedocs.org/pull/9861#discussion_r1061894753
- https://github.com/readthedocs/readthedocs.org/blob/3.11.0/docs/development/front-end.rst

**Comment by humitos** [comment]
This probably won't required anymore since we are migrating all the frontend things to addons and ex-theme. I don't we will need to rebuild the frontend things from this repository anymore.

**Comment by stsewd** [comment]
> Also, I think the current pattern is just running inv docker.buildassets

That doesn't run `npm run vendor`

https://github.com/readthedocs/common/blob/e6da5905c17254b5e8d78adc20e77a88f51f41f1/dockerfiles/tasks.py#L165-L169

I haven't been following the frontend changes, so up to you if you thinks this is still needed.
