### ISSUE TITLE
Which version is the latest and stable? 

### ISSUE THREAD

**Issue by pilgrimage80** [readthedocs/readthedocs.org#9870]
I follow the installation steps in the dev readthedocs documentation. 

I will pull your docker image with inv docker.pull 

Which of the following tags should I choose? 
https://hub.docker.com/r/readthedocs/build/tags

the latest one was last updated  3 years ago 

ubuntu version 22 10 months ago 

Obviously I'm seeing online readthedocs 9.1.1. This means that if I choose which docker image, I can install the 9.1.1 stable version. I need guidance on this. What are these choices made according to? Thank you.

**Comment by pilgrimage80** [comment]
I solved the problem.sorry I'm just learning these things, I realize my questions are very silly. inv docker.build --only-required downloaded what was needed with 9.1.2 thanks.

**Comment by benjaoming** [comment]
Hi @pilgrimage80 - that sounds great. I will close this issue.

What are you working on that makes you interested in running a development environment?
