### ISSUE TITLE
Docs: Tutorial to cover requirements

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#9873]
The current tutorial has a mistake:

![image](https://user-images.githubusercontent.com/374612/211290901-ed2ee261-2d61-4a96-89a7-d93f07ee78b5.png)

These requirements are not in the [tutorial-template repo](https://github.com/readthedocs/tutorial-template/) and are not covered in the tutorial.

Proposing to:

1. Fix the issue by adding a `requirements.txt` that's monitored by dependabot
2. Expand the tutorial such that it gives the first instructions on how to handle dependencies (must be extremely beginner-friendly!!)

**Comment by abe-101** [comment]
I'd be happy to tabcke this one.

I see two ways to address it:

1. remove the line `including some required dependencies in docs/requirements.txt,` from the [getting-started](https://docs.readthedocs.io/en/stable/tutorial/index.html#getting-started) tutorial.
one can argue that having to deal with dependencies will just confuse the beginner and its [my understanding](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#don-t-rely-on-implicit-dependencies) that readthedocs will build the docs without a `requirments.txt` file. 
  > By default Read the Docs will install the tool you chose to build your docs, and other dependencies, this is done so new users can build their docs without much configuration.

  2. keep the line and fix up the [tutorial-template](https://github.com/readthedocs/tutorial-template/tree/main/docs/source)
  the argument for this side is its strongly encouraged to include a dependence file:
  > We highly recommend not to assume these dependencies will always be present or that their versions won’t change. Always declare your dependencies explicitly using a [configuration file](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#using-a-configuration-file), for example:
  
  
  I'd be happy to create a PR with the changes

**Comment by abe-101** [comment]
To expand a bit on the 2nd approach.
The changes I would propose for the [tutorial-template](https://github.com/readthedocs/tutorial-template/tree/main/docs/source) repo include:
1. Adding a `.readthedocs.yaml` file with this [example](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#id3) 
```
version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

sphinx:
  configuration: docs/conf.py

python:
  install:
    - requirements: docs/requirements.txt
```
2. Adding a `docs/requirements.txt` file with this [example](https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#id5)
```
sphinx==5.3.0
sphinx_rtd_theme==1.1.1
readthedocs-sphinx-search==0.1.2
```

**Comment by benjaoming** [comment]
Hi @abe-101 :wave: 

That sounds wonderful! I have a preference for moving towards the 2nd approach.

I'll try to express some learning objectives, if that makes sense? That is easier to fundamentally agree to. Would love to hear what others think, especially with some input from people who have been giving support around Read the Docs for new projects.

_The tutorial should make readers succeed in:_

1. Emerging with a simple but state-of-the-art documentation project
1. Sub-goal:  Emerging with a documentation project that includes `requirements.txt` and `.readthedocs.yaml`
3. Possessing the knowledge that `requirements.txt` is for expressing versions of the software that builds their documentation project
4. Possessing the knowledge that `.readthedocs.yaml` configures how Read the Docs behaves (not their local Sphinx build)
5. Possessing the knowledge of where to find further documentation about `requirements.txt` and `.readthedocs.yaml`

From our experience at Read the Docs, we probably want to link to the longer article about "reproducible builds": https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html

**Comment by benjaoming** [comment]
> In case we want to explain it somehow, we could create an "advanced part two" of the tutorial

That's what I've been meaning with adding more steps -- such that the reader can drop out at any step (as long as they read them in consecutive order) and have a functional documentation project. Always complete, never finished :)

**Comment by agjohnson** [comment]
I agree with Manuel on all those points. Our tutorial should stay minimal as we are promoting other build tooling, some not Python tools. We do have a doc that covers this already, our doc on reproducible builds. I think that could get some updates, but either way could be the doc that we link out to.

**Comment by benjaoming** [comment]
> Our tutorial should stay minimal as we are promoting other build tooling, some not Python tools.

The tutorial uses Sphinx and contains a Python project. Seeing it as a Sphinx tutorial makes a lot of sense. I'm already liking the idea of splitting out API docs to a separate follow-up section.

But I didn't mean for this issue to re-design the tutorial, more to raise the question of what to do with requirements and pinning.

Seems there isn't any interest in adding more content to the tutorial @abe-101 - I think the simple fix is what you proposed in very first solution "Remove the line...".

**Comment by abe-101** [comment]
> We should add a .. seealso:: section pointing the user to https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html or similar where it's explained how to use requirements.txt in their project

Before merging #9902 I'd like to clarify if it should it be included in the same PR? and where do you intend  the above should go? 

1. Under pr above the picture [GitHub template for the tutorial](https://docs.readthedocs.io/en/stable/tutorial/index.html#id3)
2. [Where to go from here](https://docs.readthedocs.io/en/stable/tutorial/index.html#where-to-go-from-here)
