### ISSUE TITLE
Impossible to use latest sphinx-rtd-theme on project created prior to Oct 2020?

### ISSUE THREAD

**Issue by FoamyGuy** [readthedocs/readthedocs.org#9876]
## Details

* Read the Docs project URL: https://docs.circuitpython.org/projects/irremote/en/latest/index.html
* Build URL (if applicable): https://readthedocs.org/projects/adafruit-circuitpython-irremote/builds/19119227/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/{your_rtd_username}/

## Expected Result

We are trying to get RTD to use the latest version of `sphinx-rtd-theme` for a project that was created prior to october 2020. I've found in the documentation that projects created before then default to versions `0.4.3`, while projects created after that default to the latest version available at build time.

In order to try to force RTD to use the new version we specified `sphinx-rtd-theme` inside of `docs/requirements.txt` which is pointed to from `.readthedocs.yml`

## Actual Result

Inside of the RTD build instance, it runs pip install on all of it's own hardcoded versions first i.e. `pip install sphinx-rtd-version<0.5`

Then in the next step it runs a command to insall from the docs requirements something like `pip install -r docs/requirements.txt`

The problem is that the first install command installed version 0.4.3 which means when the second install command runs pip chooses not to install anything because the requirement is already satisfied by the one installed on the prior command. 

If we specify a version inside the requirements file i.e. `sphinx-rtd-theme=1.1.1` then it will actually install that version and use it. But ideally we want to always take the latest version, especially since that is the behavior that all of the projects created more recently have. 

Is there some way we can force RTD to use the newest version of `sphinx-rtd-theme` on a project created after oct 2020, without specifying an exact version (or relative version, like greater than or less than, ideally we just want always latest not related to any specific number. Just like the newer projects behave by default.)

Perhaps it's possible to specify the order that things are installed? If we could make it do our requirements file first then do the hardcoded ones perhaps the latest version which was gotten from our requirements could take precedent over the old one hardcoded?

**Comment by FoamyGuy** [comment]
tagging @kattni for reference.

**Comment by FoamyGuy** [comment]
This may be possible by specifying the version with a greater than operator in requirements. something like `sphinx-rtd-theme>=1.1.1` 

I will try this out and close if that solves. I'm think I had an incorrect understanding of how the greater than operator works in that context.

**Comment by stsewd** [comment]
Hi @FoamyGuy, we can disable this behavior for your project, but using the > operator I believe it should work too.

**Comment by stsewd** [comment]
I have opted out your project from that "feature"

> python -m pip install --upgrade --no-cache-dir pillow mock==1.0.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.9.1 recommonmark==0.5.0 sphinx sphinx-rtd-theme readthedocs-sphinx-ext<2.3 

the rtd theme is no longer pinned https://readthedocs.org/projects/adafruit-circuitpython-irremote/builds/19120223/, let us know if want this for other projects.

**Comment by FoamyGuy** [comment]
@stsewd thank you! I do think it's likely we'll want the same configuration on some other libraries as well. Kattni from our team will follow up about the others here when she has a chance

**Comment by stsewd** [comment]
You can reach us via our support email at https://readthedocs.org/support/.
