### ISSUE TITLE
readthedoc does not recognize the !!!warning tag

### ISSUE THREAD

**Issue by be-engineer** [readthedocs/readthedocs.org#9878]
## Details
I use markdown syntax in my documentation，like this
![image](https://user-images.githubusercontent.com/16242748/211455876-097aa9b1-8fc2-465e-bd76-5c2f036c230a.png)

* Read the Docs project URL: https://readthedocs.org/projects/{your_project_slug}/
* Build URL (if applicable): https://readthedocs.org/projects/{your_project_slug}/builds/{build_id}/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/{your_rtd_username}/

## Expected Result
The effect should be like this. This is also the effect in markdown preview
![image](https://user-images.githubusercontent.com/16242748/211455157-00e97561-13b8-48a0-b4a0-c99d00e463d0.png)

*A description of what you wanted to happen*

## Actual Result
But the effect obtained after compiling from rtd is as follows，what should I do?
![image](https://user-images.githubusercontent.com/16242748/211455808-3bf5db33-8bde-435a-9e40-d7a7c8db7a1b.png)

*A description of what actually happened*

**Comment by stsewd** [comment]
Hi, does this happen when you build your docs locally? And please provide all correct URLs that we ask on the template, so it's easier to help you.

**Comment by be-engineer** [comment]
The document I created on github was compiled on rtd and written in vscode. The warning icon can be displayed when previewed on vscode, but it becomes text after being compiled on rtd. The address of the document is
https://mikrotik-doc-cn.readthedocs.io/zh/latest/Getting_started/Software_Specifications/index.html

**Comment by stsewd** [comment]
@be-engineer Read the Docs is building your documentation using sphinx, that may be different on how GitHub renders the documents (GitHub uses its own flavor of markdown). You may want to check our tutorial if you are not familiar with Sphinx https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html, there we have steps to use rst or markdown.

**Comment by be-engineer** [comment]
Excuse me, how can I modify it？
