### ISSUE TITLE
Read The docs is not updating with new tags

### ISSUE THREAD

**Issue by khider** [readthedocs/readthedocs.org#9885]
## Details

* Read the Docs project URL: [https://readthedocs.org/projects/{your_project_slug}/](https://readthedocs.org/projects/pyleoclim-util/)
* Build URL (if applicable): N/A
* Read the Docs username (if applicable): https://readthedocs.org/profiles/dkhider/

## Expected Result

Under versions, I would like to be able to activate my latest tag v0.10.0, but it is not showing up.

**Comment by humitos** [comment]
Hi @khider! Can you please provide the URL of your project on Read the Docs?

**Comment by khider** [comment]
https://pyleoclim-util.readthedocs.io/en/master/

**Comment by humitos** [comment]
HI @khider! I just triggered a new build for `latest` at https://readthedocs.org/projects/pyleoclim-util/builds/19159606/ and the versions were refreshed correctly. I see 0.10.0 at https://readthedocs.org/projects/pyleoclim-util/versions/?version_filter=0.10.0

**Comment by khider** [comment]
Thank you. Not sure if it's a related question/problem to the one above but I can no longer select the version from this page: https://pyleoclim-util.readthedocs.io/en/master/. When clicking on the arrow next to master, nothing happens.

**Comment by humitos** [comment]
@khider I think that issue was already fixed. Can you try triggering a new build for your `master` version and double-check if it's solved?

**Comment by stsewd** [comment]
@khider this issue is because the RTD theme isn't compatible with sphinx 6 yet, 1.2.0 will fix this https://github.com/readthedocs/sphinx_rtd_theme/issues/1413.
