### ISSUE TITLE
Search: avoid indexing spam and giving spam results

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#9899]
Currently, when using the global search, a lot of spam projects are shown in the search results. None of them should be shown on these results.

![Screenshot_2023-01-09_18-09-04](https://user-images.githubusercontent.com/244656/212671454-7647f9cc-36ad-49ce-91e7-55b51297a97e.png)

We could define a new threshold, `RTD_SPAM_THRESHOLD_DONT_SHOW_SEARCH_RESULTS` to skip these:

https://github.com/readthedocs/readthedocs.org/blob/2f009cd520d8ad8a4c783ac091e5c32b88fc9342/readthedocs/settings/base.py#L993-L998

**Comment by stsewd** [comment]
The easiest way to archive this without having to introduce a new field or have to keep a track of projects to filter by (which probably won't scale) is to just have a task that removes the files from the index when a project is marked as spam or has a score greater than x. If there was a mistake, we can just trigger the re-index task after un-marking the project as spam.

**Comment by agjohnson** [comment]
Can this be closed? I think since this was opened, we've leaned more towards deprioritizing this UI in favor of bringing some of these features to our in-doc, Addons search instead. This UI doesn't get much use and global project search is community specific.

**Comment by humitos** [comment]
If we are not going to do this work or similar, I'd propose to kill this view completely then. At this point, I think this is just bad UX and exposes the search as a broken and useless feature; degrading its trust.

**Comment by ericholscher** [comment]
We hit this recently, so we should find a good way to move forward here. This could also include work on #11533, if that makes sense as well?

**Comment by agjohnson** [comment]
Also a note, we are probably still not talking about trying to tune the global search UI, as that view is going away with the new dashboard. The work here is indeed solely working to avoid indexing and surfacing search results.

There is some slightly related work in not surfacing spam projects in our dashboard as well:

- https://github.com/readthedocs/readthedocs-ext/issues/554
