### ISSUE TITLE
Build: remove support for `pdflatex`

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#9907]
Our current code decides whether using `pdflatex` or `latexmk` depending on the Sphinx version. It uses `pdflatex` when `sphinx<=1.6.x` and for all the other versions it uses `latexmk`:

https://github.com/readthedocs/readthedocs.org/blob/8195ecb00d7e9caa6b83ef822416982ad98f4346/readthedocs/doc_builder/backends/sphinx.py#L332-L342

I think we could safely remove this chunk of code since nobody is using such an old version to build their documentation with Sphinx. This Metabase query shows that the oldest version currently used on Read the Docs is `1.8.6` [^1]

[^1]: this is because we are forcing pinning to that version for old projects

**Comment by SyedMa3** [comment]
I can't find this chunk of code in the main branch. So assuming this code is removed, so issue can be closed? @humitos
