### ISSUE TITLE
Proxito: Next steps on Improve URL Handling

### ISSUE THREAD

**Issue by ericholscher** [readthedocs/readthedocs.org#9911]
**Design doc**: https://dev.readthedocs.io/en/latest/design/better-doc-urls-handling.html

**First work**: https://github.com/readthedocs/readthedocs.org/pull/9534 https://github.com/readthedocs/readthedocs.org/pull/9500 https://github.com/readthedocs/readthedocs.org/pull/9462

What are the next steps here?

**Comment by ericholscher** [comment]
@stsewd Thoughts on next steps for this work? Wanting to make sure we don't lose it.

**Comment by stsewd** [comment]
So, the last thing I did related to this is https://github.com/readthedocs/readthedocs.org/pull/9726. There I'm refactoring the code so introducing the new resolver is easier.

I was also playing with how the new implementation will look like at https://github.com/readthedocs/readthedocs.org/pull/9710/ (DO NOT REVIEW, I'm only playing around with the new implementation).

Next steps could be checking what we can remove/refactor from the middleware, so it is easy to integrate with the new implementation. I was thinking of introducing the new implementation incrementally, this is, serving some of our docs with the old implementation and other with the new one, this could be archived by splitting the traffic to each view, like serving all subprojects with the new implementation or projects that start with `x` or similar.

**Comment by ericholscher** [comment]
> Next steps could be checking what we can remove/refactor from the middleware, so it is easy to integrate with the new implementation. I was thinking of introducing the new implementation incrementally, this is, serving some of our docs with the old implementation and other with the new one, this could be archived by splitting the traffic to each view, like serving all subprojects with the new implementation or projects that start with x or similar.

This sounds good. We could also just feature flag it?

**Comment by ericholscher** [comment]
#10044

**Comment by ericholscher** [comment]
Yea... silly.

**Comment by ericholscher** [comment]
Fighting the bots :D

**Comment by stsewd** [comment]
Forgot to re-open this :D

**Comment by humitos** [comment]
@stsewd can you expand here with an update for this issue? What's missing? What's blocked? What was done already?

**Comment by stsewd** [comment]
- We are using the new implementation to serve 200 and redirects on some projects
- Next week after deploy, we will be able to serve 404s with the new implementation
- We are still missing implementing support for custom URLs
- We won't see all benefits of the new implementation till we put all serving into a single view, this is migrating
https://github.com/readthedocs/readthedocs.org/blob/dd07a3e9d467d9fd0047f6faf40d08fe0afed019/readthedocs/proxito/urls.py#L141-L188

into a single entry point

**Comment by ericholscher** [comment]
> We are still missing implementing support for custom URLs

Excited for this!

**Comment by ericholscher** [comment]
> * We are still missing implementing support for custom URLs
> * We won't see all benefits of the new implementation till we put all serving into a single view, this is migrating
>   https://github.com/readthedocs/readthedocs.org/blob/dd07a3e9d467d9fd0047f6faf40d08fe0afed019/readthedocs/proxito/urls.py#L141-L188
> 
> into a single entry point

@stsewd are either of these good to plan on for next sprint? We need to roll out the proxito serving via feature flag more widely. Seems like the single view refactor will be easier, I'm guessing?

**Comment by stsewd** [comment]
> Seems like the single view refactor will be easier, I'm guessing?

That would be the final step, since it would be difficult to do that with a feature flag.

**Comment by stsewd** [comment]
Next steps after https://github.com/readthedocs/readthedocs.org/pull/10156 is merged:

- Decide what to do with paths that aren't docs https://github.com/readthedocs/readthedocs.org/issues/10181, should we support prefixing everything under `/_/` or just tell people to proxy those paths as is to our servers?
- Depending on the decision, migrate existing projects to the new proxito implementation using custom prefixes.
- Roll out the new implementation to everyone (.com, since .org is already using the new implementation)
- Remove old code and use one single entry point for the serve docs view.
- Implement https://github.com/readthedocs/readthedocs.org/issues/10307.

**Comment by ericholscher** [comment]
I'm going to migrate the above comment into a new issue, since we're now done with the initial work here!
