### ISSUE TITLE
No such kernel named python3

### ISSUE THREAD

**Issue by 12rambau** [readthedocs/readthedocs.org#9922]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/pyqutree/
* Build URL (if applicable): https://readthedocs.org/projects/pyqutree/builds/19220096/
* Read the Docs username (if applicable): https://readthedocs.org/dashboard/

## Expected Result

I'm building my documentation locally using nox (so the env is isolated) and everything works just fine. 

## Actual Result

When pushing the PR I get the following error:
```
Notebook error:
NoSuchKernel in examples/demo.ipynb:
No such kernel named python3
```

What I don't understand is that I never changed the kernel from my side.  I never used `nbsphinx` in RDT before so I'm very green. Is it a bug ? If not, what python kernel name should I use instead?

**Comment by stsewd** [comment]
I'm not familiar with nbsphinx/jupyter, but I'd guess there is a dependency that's missing, make sure to execute the same installation steps on RTD as you did locally to have jupyter working.

**Comment by 12rambau** [comment]
The answer was well hidden in their documentation/issue tracker:
- https://github.com/spatialaudio/nbsphinx/issues/121
- https://nbsphinx.readthedocs.io/en/0.8.1/usage.html#Automatic-Creation-of-HTML-and-PDF-output-on-readthedocs.org

I should have read better. sorry for the noise.

PS: latest build worked like a charm
