### ISSUE TITLE
Inconsistency in Documentattion

### ISSUE THREAD

**Issue by dikwickley** [readthedocs/readthedocs.org#9927]
## Details

<img width="956" alt="image" src="https://user-images.githubusercontent.com/31622972/214222272-c1dc8096-3063-45a5-8f86-574149a9166b.png">

the second command `python package/setup.py install` seems inconsistent as in the confi v2 example, the second method is still `pip`

## Expected Result

*A description of what you wanted to happen*

## Actual Result

*A description of what actually happened*

**Comment by dikwickley** [comment]
I'd like to work on this, please assign it to me

**Comment by humitos** [comment]
@dikwickley Hi! Feel free to open a PR with your suggestions 👍🏼

**Comment by humitos** [comment]
This is now fixed.
