### ISSUE TITLE
Build: output `_readthedocs/` directories feedback after deploy

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs.org#9931]
We were able build other formats (PDF, HTMLZip) by outputting the files into `_readthedocs/{pdf,htmlzip}` directories: https://test-builds.readthedocs.io/en/all-formats-build-jobs/

We found some limitations:

* the name of the PDF **must be** `_readthedocs/pdf/<project-slug>.pdf`
* the name of the HTMLZip **must be** `_readthedocs/htmlzip/project-slug>.zip`
* double-check if it happens the same for ePUB 😄 
* we are only checking for the existence of `_readthedocs/<format>` but **we are not checking if it's a directory** at https://github.com/readthedocs/readthedocs.org/blob/e1e7a186232c494161ce03d58f0ccb8dc5465c60/readthedocs/projects/tasks/builds.py#L539

Also, while debugging this we hit #9468

**Comment by humitos** [comment]
I just realized that we had another issue: the build process raised an exception at `Uploading` state while uploading things to the storage backend and the built got stuck. This is because the upload step happens inside `on_success` instead of `execute` as the other things.

I've already moved this to the right place in https://github.com/readthedocs/readthedocs.org/pull/9800

**Comment by humitos** [comment]
> * the name of the PDF **must be** `_readthedocs/pdf/<project-slug>.pdf`
> * the name of the HTMLZip **must be** `_readthedocs/htmlzip/project-slug>.zip`
> * double-check if it happens the same for ePUB smile

I'm not convinced about how to remove this restriction, yet. I don't want to _rename_ the file on behalf the user because that would be incompatible with ["Multiple pdf files for single project"](https://github.com/readthedocs/readthedocs.org/issues/2045) since we don't want to _rename all the user's PDF filenames_ (e.g. if they have `Tutorial-Basic.pdf` and `Tutorial-Advanced.pdf` we want to keep those names).

We may want to prefix/suffix the project/version slug, tho. In any case, **we will need to save the filename in our database** to know what's the PDF the user wants to download.

However, for now, we could do a `listdir` on S3 bucket and serve the first filename found --since it will always be one.

**Comment by humitos** [comment]
I think my initial proposal to solve this problem would be to return a `.pdf` or a `.zip` file depending on the number of files in the output directory:

- one (`1`) file
  - rename the file at upload time (e.g. `Tutorial-Basic.pdf` -> `$READTHEDOCS_PROJECT_SLUG`) --_this is the new part_
  - return the `.pdf` with a name changed (this is the current behavior)
- multiple (`>1`) files
  - zip all the `.pdf` files _without renaming them_ into a `.zip` file with the name we choose
  - return a `.zip` file

This is the simpler implementation for this, since we don't have to change the UI (add one link per `.pdf` file, for example) nor change the filenames we are already using. At serving time, we will need to know if the version has _one or multiple_ PDFs to know the extension of the file we have to serve (`.zip` or `.pdf`). The name will always be `$READTHEDOCS_PROJECT_SLUG`

**Comment by humitos** [comment]
> I just realized that we had another issue: the build process raised an exception at `Uploading` state while uploading things to the storage backend and the built got stuck. This is because the upload step happens inside `on_success` instead of `execute` as the other things.

I've done this in #9941 👍🏼

**Comment by agjohnson** [comment]
@humitos What about doing this more explicitly and adding a zip file output download format instead?

It feels maybe a bit hacky to do this automatically for projects. It seems like we might be building an edge case that will frustrate us at some point -- indeterminately returning non-pdf content from our pdf endpoints.

If our long term plan does not include distributing zip archives, this will be something we have to work around later too. If we do ever support multiple output files natively, we'll have single pdf builds, multiple pdf builds, and legacy zip archive pdfs too.

Supporting zip archives for downloads actually might be a fine way to solve this UX for good. Instead of supporting arbitrary numbers of arbitrary files in our UX, users can just opt to output a zip file with whatever they want.

I might lean towards this approach at this point. In the case we support multiple PDF files in output, we have to change all the UI/UX around "Download PDF" to now also *list* the PDFs to download. If we add a zip format, we don't, and this batch of work is infinitely easier.

**Comment by humitos** [comment]
> > * the name of the PDF **must be** `_readthedocs/pdf/<project-slug>.pdf`
> > * the name of the HTMLZip **must be** `_readthedocs/htmlzip/project-slug>.zip`
> > * double-check if it happens the same for ePUB smile
> 
> I'm not convinced about how to remove this restriction, yet. I don't want to _rename_ the file on behalf the user because that would be incompatible with ["Multiple pdf files for single project"](https://github.com/readthedocs/readthedocs.org/issues/2045) since we don't want to _rename all the user's PDF filenames_ (e.g. if they have `Tutorial-Basic.pdf` and `Tutorial-Advanced.pdf` we want to keep those names).

I won't remove this restriction yet without more conversation. For now, I think it will be enough by documenting how it works. Basically, people need to use `READTHEDOCS_PROJECT` environment variable for the filename of them. Example:

```bash
 cd _readthedocs ; zip -r -j htmlzip/$READTHEDOCS_PROJECT.zip $READTHEDOCS_PROJECT
 mv _readthedocs/simplepdf/"Test Builds.pdf" _readthedocs/pdf/$READTHEDOCS_PROJECT.pdf 
```

_(example from https://readthedocs.org/projects/test-builds/builds/19268359/)_

**Comment by agjohnson** [comment]
Requiring a specific filename still seems like a straightforward approach, I agree that documenting this behavior is enough for this first pass. It keeps the implementation outcome the same, but is still a step towards more user control.

I'm also still fine taking more time on multiple pdf/epub support, we don't need this feature to wrap up this change. There are UI and UX questions for both maintainers and readers with all three approaches here, and I'm not very convinced on any of them yet.

**Comment by humitos** [comment]
This is already fixed. We've created other issues to track the missing parts. I'm closing it.
