### ISSUE TITLE
Dashboard: Smaller errors in redirect "preview" widget

### ISSUE THREAD

**Issue by benjaoming** [readthedocs/readthedocs.org#9943]
There are two very similar errors in the Redirect form's preview area:

1) It seems like external "To URLs" aren't correctly rendered for Redirect Type of "Page Redirect". Seems to also be reported here: https://github.com/readthedocs/readthedocs.org/issues/4023

![image](https://user-images.githubusercontent.com/374612/214606579-ad3850f2-b51e-46a3-8f09-3e3c1904977a.png)

2) The value of "From URL" is prepended to "faq.html" instead of overwriting it

![image](https://user-images.githubusercontent.com/374612/214606753-ba5c0f4c-aa4e-446e-97c6-f9e90988f0b9.png)

Will update this issue if I stumble upon more since I'm working on the documentation article of this page at the moment.

**Comment by Mayuresh0072** [comment]
@humitos @benjaoming  Hello, I want to work on this issue and contribute.. Please assign me this issue. Thanks.

**Comment by benjaoming** [comment]
Hi @Mayuresh0072

Sounds great! Have you seen on developer documentation? Please refer to this guide to get started:

* https://dev.readthedocs.io/en/latest/contribute.html

You will also find a guide for creating your first [Development Installation](https://dev.readthedocs.io/en/latest/install.html). Let us know when you are ready, and we can assign you the issue :+1:

**Comment by Mayuresh0072** [comment]
I have read contribute page instructions. I am ready to solve. Please assign the issue. Thank you.

**Comment by benjaoming** [comment]
@Mayuresh0072 sure sure

**Comment by agjohnson** [comment]
@benjaoming we have already addressed this in our new dashboard UI, most likely. I'd suggest trying the new interface out and if there are changes there, we should open an issue against the new UI instead

**Comment by benjaoming** [comment]
@agjohnson sounds great - and on that note, I would very much benefit from a quick demo :heart: It could help me to quickly grasp if something is already fixed :+1:
