### ISSUE TITLE
Error only on the stable version of docs

### ISSUE THREAD

**Issue by thephez** [readthedocs/readthedocs.org#9955]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/dash-docs-core/
* Build URL (if applicable): https://readthedocs.org/projects/dash-docs-core/builds/19286447/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/thephez/

## Expected Result

The [`stable` version](https://dash-docs-core.readthedocs.io/en/stable/index.html) would produce a build that matches the build for the [related branch (`18.0.0`)](https://dash-docs-core.readthedocs.io/en/18.0.0/index.html) in this case.

## Actual Result

The `stable` page shows an error in the console and doesn't properly display some Font Awesome elements. Both builds are based on the `18.0.0` branch (specifically [this commit](https://github.com/dashpay/docs-core/tree/0bd92043efb889b0714bb590d2e3133a18a31585)). Both builds completed successfully.

Error message:
`Refused to apply style from 'https://dash-docs-core.readthedocs.io/en/stable/_static/vendor/fontawesome/6.1.2/css/all.min.css?digest=796348d33e8b1d947c94' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

Everything correctly displayed on `18.0.0` https://dash-docs-core.readthedocs.io/en/18.0.0/index.html:
![image](https://user-images.githubusercontent.com/8145677/214920529-13326b7c-fb95-466f-a88a-43f8b898ba1d.png)

Missing Font Awesome stuff (e.g. icons on right side of header) on `stable` https://dash-docs-core.readthedocs.io/en/stable/index.html:
![image](https://user-images.githubusercontent.com/8145677/214920660-84f9ccb7-ce13-4158-938d-92f5483e0d20.png)

I tried rebuilding both `stable` and `18.0.0` multiple times and have gotten the same result each time.

I also have a fork of these same docs where this issue doesn't exist. I only see it on `stable` for the repo listed in the details section at the top of this issue:
https://dash-user-docs.readthedocs.io/projects/core/en/stable/index.html
https://dash-user-docs.readthedocs.io/projects/core/en/18.0.0/index.html
Based on https://github.com/thephez/docs-core and https://readthedocs.org/projects/docs-core-tp/

**Comment by humitos** [comment]
Hrm, I'm not seeing that issue

![Screenshot_2023-01-26_21-40-34](https://user-images.githubusercontent.com/244656/214945768-720c87f6-8115-464b-b3f5-49e11bea65f5.png)


![Screenshot_2023-01-26_21-42-20](https://user-images.githubusercontent.com/244656/214946103-b301e4be-3440-41c6-a61d-7bd58f9e7977.png)

both sites seem to work fine from my end.

**Comment by thephez** [comment]
@humitos Thanks for checking this. I'm still seeing it on multiple machines/browsers here, but now have had confirmation from someone else that they aren't seeing the issue either. :thinking: So it seems that things are fine on your end. I'll close the issue and re-open it if I come across anything that contradicts that assumption. Thanks!
