### ISSUE TITLE
Flyout: more visible language selection

### ISSUE THREAD

**Issue by jeanas** [readthedocs/readthedocs.org#9957]
Currently, the UX for switching to another language is to click on the "v: xxx" (like "v: latest") RTD badge, getting something like this:

![image](https://user-images.githubusercontent.com/37271310/214999384-a027ba00-f414-4dfe-85e6-b354dac71f4d.png)

In my humble opinion, language selection would ideally be far more discoverable.

- You have to click on a button to discover it,
- The button's title doesn't say what it's for. If you understand "v: latest", it's about the version of the documentation.
- The languages are given as two-letter codes.

The problem here is that if you are browsing a page that is in a language you don't understand, you will quickly give up unless you can immediately notice that it has a translation available. So the current language selection is not discoverable enough.

For https://extending-lilypond.readthedocs.io, I added something in the header, it looks like this:

![image](https://user-images.githubusercontent.com/37271310/214999737-286c603a-7940-41f6-8c15-6ab4ae290d10.png)

Not perfect, but already better in my opinion. I would like to record the feature request of something more discoverable like this. It could also be a dropdown, which would be more usual (but I didn't take the time to learn the CSS/JS for that). 

This is also related to readthedocs/readthedocs.org#7471: it would improve the UX for non-English speakers (well, people who don't speak the source language of the docs, but that's usually English) if the right language were chosen by default from the browser preferences, while still allowing selection.

Thank you for considering this and for making RTD the incredibly practical tool that it is.

Related: https://github.com/readthedocs/addons/issues/250

**Comment by humitos** [comment]
Thanks for sharing this feedback with us. It's really valuable 💯

@agjohnson this could be considered into all the Javascript refactor we are about to start doing

**Comment by humitos** [comment]
This would eventually be supported by https://github.com/readthedocs/addons/pull/64
