### ISSUE TITLE
Builds not pulling docstrings from C++ python extension

### ISSUE THREAD

**Issue by SethMMorton** [readthedocs/readthedocs.org#9970]
## Details

* Read the Docs project URL: https://readthedocs.org/projects/fastnumbers/
* Build URL (if applicable): https://readthedocs.org/projects/fastnumbers/builds/19340076/
* Read the Docs username (if applicable): https://readthedocs.org/profiles/SethMMorton/

## Expected Result

Ideally, the docstrings from my C++ extension's functions would appear in the API documentation (screenshot is from my local build)

![image](https://user-images.githubusercontent.com/1596189/215954538-00bf3474-a4cc-4e03-b179-17f6e530aa53.png)

Additionally, the main page TOC should have all sections listed (again, screenshot is from local build)

![image](https://user-images.githubusercontent.com/1596189/215953625-1841853e-7f2a-4300-9fc2-595cd456bf9a.png)

## Actual Result

I am seeing two issues, in order of decreasing severity:

- None of the functions from my modules have documentation that shows up (see first screenshot below)
- The main page TOC does not list all sections (second screenshot below)

![image](https://user-images.githubusercontent.com/1596189/215954333-23089b0e-7d4e-4ed4-ab81-21b1d6fcf14d.png)

![image](https://user-images.githubusercontent.com/1596189/215954030-a7d7e97f-f2ca-4eeb-baa5-1c5188cb9c2d.png)

## Why am I not filing this with sphinx?

I cannot reproduce this locally. I am using a fully-pinned `requirements.txt`, so ideally I should be seeing the same environment between my machine and the readthedocs machines. The only difference I can imagine is how the C++ extension gets installed. I am wondering if somehow it is not visible to the virtual environment.

What can I do to make this work properly?

**Comment by stsewd** [comment]
Hi there, I'm able to see the proper docstrings at https://fastnumbers.readthedocs.io/en/master/api.html#the-built-in-replacement-functions, probably you are seeing a cached version, try a hard refresh with ctrl+F5 or similar, or in a private window.

**Comment by SethMMorton** [comment]
Oh my. Yes, a hard refresh shows what I expect. This is embarrassing. Thank you for your time, and many apologies for wasting it.
