### ISSUE TITLE
Embed API does not correctly consider multiple terms per description in a glossary

### ISSUE THREAD

**Issue by jpfeuffer** [readthedocs/readthedocs.org#9975]
## Details

* Read the Docs project URL: https://pyopenms.readthedocs.io/en/latest/background.html

## Expected Result

Hover over LC-MS and see the description.

## Actual Result

<img width="181" alt="Bildschirmfoto 2023-02-02 um 13 31 10" src="https://user-images.githubusercontent.com/8102638/216325689-a35f4379-50f0-4592-b045-b97c3ccd4601.png">

**Comment by jpfeuffer** [comment]
Sphinx specifically describes this as valid RST https://www.sphinx-doc.org/en/master/usage/restructuredtext/directives.html#:~:text=You%20can%20link%20to%20all%20of%20the%20terms.%20For%20example%3A

**Comment by jpfeuffer** [comment]
The API request is made by the xhoverref extension.

**Comment by jpfeuffer** [comment]
Feel free to move this issue to this extension.

**Comment by jpfeuffer** [comment]
duplicate of https://github.com/readthedocs/sphinx-hoverxref/issues/97

**Comment by jpfeuffer** [comment]
Actually, I will reopen since it was noted in the xhoverref issue that this is an issue for the API, as guessed.

**Comment by humitos** [comment]
This was fixed in https://github.com/readthedocs/readthedocs.org/pull/10024. Feel free to re-open if your issue was not solved. The link to your project is 404 now, so I can't test it.

**Comment by jpfeuffer** [comment]
Yes works: https://pyopenms.readthedocs.io/en/latest/user_guide/background.html#introduction
