### ISSUE TITLE
Gold subscription not applying to translations?

### ISSUE THREAD

**Issue by jeanas** [readthedocs/readthedocs.org#9986]
Hi!

I have a ReadTheDocs gold subscription, which I have used to make https://extending-lilypond.readthedocs.io/ available without ads for everyone. However, I found out that this doesn't apply to the translations, only to the English version. I understand that this kind of makes sense because RTD handles each translation as a separate “project”… but I thought you might want to know about it, since including translations would seem rather logical.

## Details

* Read the Docs project URL: https://readthedocs.org/projects/extending-lilypond, https://readthedocs.org/projects/extending-lilypond-fr, https://readthedocs.org/projects/extending-lilypond-de
* Read the Docs username (if applicable): https://readthedocs.org/profiles/jeanas

**Comment by ericholscher** [comment]
Thanks for the note. We aren't investing more development time into our "Gold" subscriptions unfortunately. For some esoteric technical reasons, we're looking to migrate that code, and the new version will be much nicer and more flexible. 

Best of luck on your new host.
